= XAUTOCLAIM

**语法**

[source,text]
----
XAUTOCLAIM key group consumer min-idle-time start [COUNT count]
  [JUSTID]
----

**可用版本**：6.2.0

**时间复杂度**：如果 COUNT 很小，则为 O(1)。

**ACL 类别**：**@write, @stream, @fast**

此命令转移与指定条件匹配的挂起流条目的所有权。 从概念上讲，`XAUTOCLAIM` 相当于先调用 `XPENDING`，然后调用 `XCLAIM`，但通过类似 `SCAN` 的语义提供了一种更直接的方法来处理消息传递失败。

与 `XCLAIM` 类似，该命令对 `<key>` 处的流条目以及提供的 `<group>` 的上下文中进行操作。 它将等待时间超过 `<min-idle-time>` 毫秒且 ID 等于或大于 `<start>` 的消息的所有权转移给 `<consumer>`。

可选的 `<count>` 参数（默认为 100）是该命令尝试声明的条目数的上限。 在内部，该命令从 `<start>` 开始扫描消费者组的待处理条目列表 (PEL)，并过滤掉空闲时间小于或等于 `<min-idle-time>` 的条目。 该命令扫描的待处理条目的最大数量是 <count> 的值乘以 10（硬编码）的乘积。 因此，申请的条目数可能会小于指定值。

可选的 `JUSTID` 参数将回复更改为仅返回成功声明的消息 ID 数组，而不返回实际消息。 使用此选项意味着重试计数器不会增加。

该命令以数组形式返回声明的条目。 它还返回一个流 ID，用于类似游标的用途，作为后续调用的 <start> 参数。 当没有剩余的 PEL 条目时，该命令返回特殊的 0-0 ID 以表示完成。 但是，请注意，即使在扫描完成并使用 0-0 作为 <start> ID 后，您可能仍希望继续调用 XAUTOCLAIM，因为已经过去了足够的时间，因此较旧的待处理条目现在可能有资格声明。

请注意，只有空闲时间超过 <min-idle-time> 的消息才会被声明，并且声明消息会重置其空闲时间。 这确保了只有单个消费者可以在特定时刻成功声明给定的待处理消息，并且大大降低了多次处理同一消息的概率。

在迭代 PEL 时，如果 XAUTOCLAIM 偶然发现流中不再存在的消息（被 XDEL 修剪或删除），它不会声明该消息，并将其从找到它的 PEL 中删除。 该功能是在 Redis 7.0 中引入的。 这些消息 ID 作为 XAUTOCLAIM 回复的一部分返回给调用者。

最后，使用 XAUTOCLAIM 声明消息也会增加该消息的尝试传递计数，除非已指定 JUSTID 选项（仅传递消息 ID，而不传递消息本身）。 由于某种原因而无法处理的消息（例如，因为消费者在处理它们时系统性崩溃）将表现出可通过监控检测到的高尝试传递计数。

== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-arrays[数组]:

具有三个元素的数组：

* 用作下次调用 XAUTOCLAIM 的 <start> 参数的流 ID。
* 包含所有成功声明的消息的数组，其格式与 XRANGE 相同。
* 包含流中不再存在的消息 ID 的数组，这些消息 ID 已从找到它们的 PEL 中删除。

== 示例

[source,text]
----
> XAUTOCLAIM mystream mygroup Alice 3600000 0-0 COUNT 25
1) "0-0"
2) 1) 1) "1609338752495-0"
      2) 1) "field"
         2) "value"
3) (empty array)
----

在上面的示例中，我们尝试声明最多 25 个待处理且空闲（尚未确认或声明）的条目，这些条目从流的开头开始至少一个小时。 来自 "mygroup" 组的消费者 "Alice" 获得这些消息的所有权。
注意，示例中返回的流 ID 是 0-0，表示扫描了整个流。 我们还可以看到 `XAUTOCLAIM` 没有偶然发现任何已删除的消息（第三个回复元素是一个空数组）。

== 历史

* 从 Redis 版本 7.0.0 开始：向返回数组添加了一个元素，其中包含命令从 PEL 中清除的已删除条目