= XCLAIM

**语法**

[source,text]
----
XCLAIM key group consumer min-idle-time id [id ...] [IDLE ms]
  [TIME unix-time-milliseconds] [RETRYCOUNT count] [FORCE] [JUSTID]
  [LASTID lastid]
----

**可用版本**：5.0.0

**时间复杂度**：O(log N)，其中 N 是消费者组 PEL 中的消息数。

**ACL 类别**：**@write, @stream, @fast**


== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-integers[整数]: .

在流使用者组的上下文中，此命令更改待处理消息的所有权，以便新所有者是作为命令参数指定的使用者。 通常情况下会发生这样的情况：

. 有一个具有关联消费者组的流。
. 某个消费者 A 在该消费者组的上下文中通过 XREADGROUP 从流中读取消息。
. 作为副作用，在消费者组的待处理条目列表 (PEL) 中创建待处理消息条目：这意味着消息已传递给给定的消费者，但尚未通过 XACK 确认。
. 然后突然间，该消费者就永远失败了。
. 其他消费者可以使用 XPENDING 命令检查已过时相当长一段时间的待处理消息列表。 为了继续处理此类消息，他们使用 XCLAIM 来获取消息的所有权并继续。 消费者还可以使用 XAUTOCLAIM 命令自动扫描并声明陈旧的待处理消息。

https://redis.io/docs/data-types/streams/[Stream 介绍文档中] 清楚地解释了这种动态。

请注意，只有当消息的空闲时间大于我们在调用 XCLAIM 时指定的最小空闲时间时，才会声明该消息。 因为作为副作用，XCLAIM 还将重置空闲时间（因为这是处理消息的新尝试），因此尝试同时声明消息的两个消费者永远不会同时成功：只有一个消费者会成功声明消息。 这避免了我们以简单的方式多次处理给定的消息（但在一般情况下多次处理是可能且不可避免的）。

此外，作为副作用，XCLAIM 将增加尝试传送消息的计数，除非已指定 JUSTID 选项（仅传送消息 ID，而不传送消息本身）。 通过这种方式，由于某种原因而无法处理的消息（例如，因为消费者在尝试处理它们时崩溃）将开始具有更大的计数器，并且可以在系统内部检测到。

在以下情况下，XCLAIM 不会领取消息：

. 该消息不存在于组 PEL 中（即从未被任何消费者读取过）
. 该消息存在于组 PEL 中，但不存在于流本身中（即消息已被读取但从未确认，然后通过修剪或 XDEL 从流中删除）

在这两种情况下，回复将不包含该消息的相应条目（即回复数组的长度可能小于提供给 XCLAIM 的 ID 数量）。 在后一种情况下，该消息也将从发现该消息的 PEL 中删除。 该功能是在 Redis 7.0 中引入的。

== 命令选项

该命令有多个选项，但大多数主要供内部使用，以便将 XCLAIM 或其他命令的效果传输到 AOF 文件并将相同的效果传播到副本，并且对普通用户不太可能有用：

. IDLE <ms>：设置消息的空闲时间（上次发送时）。 如果未指定 IDLE，则假定 IDLE 为 0，即重置时间计数，因为该消息现在有一个新所有者正在尝试处理它。
. TIME <ms-unix-time>：这与 IDLE 相同，但不是相对的毫秒数，而是将空闲时间设置为特定的 Unix 时间（以毫秒为单位）。 这对于重写生成 XCLAIM 命令的 AOF 文件很有用。
. RETRYCOUNT <count>：将重试计数器设置为指定值。 每次再次传送消息时，该计数器都会递增。 通常，XCLAIM 不会更改此计数器，该计数器仅在调用 XPENDING 命令时提供给客户端：这样客户端可以检测异常情况，例如在大量传递尝试后由于某种原因从未处理的消息。
. FORCE：即使某些指定的 ID 尚未在分配给其他客户端的 PEL 中，也会在 PEL 中创建待处理消息条目。 但是该消息必须存在于流中，否则不存在的消息的 ID 将被忽略。
. JUSTID：仅返回成功领取的消息 ID 数组，而不返回实际消息。 使用此选项意味着重试计数器不会增加。

== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-arrays[数组]：

该命令返回所有成功领取的消息，格式与 XRANGE 相同。 但是，如果指定了 JUSTID 选项，则仅报告消息 ID，而不包括实际消息。

== 示例

[source,text]
----
> XCLAIM mystream mygroup Alice 3600000 1526569498055-0
1) 1) 1526569498055-0
   2) 1) "message"
      2) "orange"
----

在上面的示例中，我们声明 ID 为 1526569498055-0 的消息，前提是该消息空闲至少一小时而原始消费者或其他消费者没有取得进展（确认或声明它），并将所有权分配给消费者 Alice 。
