= XPENDING

**语法**

[source,text]
----
XPENDING key group [[IDLE min-idle-time] start end count [consumer]]
----

**可用版本**：5.0.0

**时间复杂度**：O(N)，其中N是返回的元素数量，因此要求每次调用有少量固定数量的条目是O(1)。当命令只返回摘要时，假设使用者列表很小，它将在O(1)时间内运行，否则需要额外的O(N)时间来遍历每个使用者。

**ACL 类别**：**@read, @stream, @slow**

通过消费者组从流中获取数据，并且不确认此类数据，会产生创建待处理条目的效果。 这在 XREADGROUP 命令中得到了很好的解释，在我们对 Redis Streams 的介绍中甚至有更好的解释。 XACK 命令将立即从待处理条目列表 (PEL) 中删除待处理条目，因为一旦成功处理消息，消费者组就不再需要跟踪它并记住消息的当前所有者。

XPENDING 命令是检查待处理消息列表的接口，因此是一个非常重要的命令，用于观察和了解流消费者组发生的情况：哪些客户端处于活动状态，哪些消息等待被消费， 或者查看是否有空闲消息。 此外，该命令与 XCLAIM 一起使用是为了实现对长时间失败的消费者的恢复，从而导致某些消息未被处理：不同的消费者可以声明该消息并继续。 这在流简介和 XCLAIM 命令页面中得到了更好的解释，此处不再介绍。

== XPENDING 汇总表

当仅使用键名称和消费者组名称调用 XPENDING 时，它仅输出有关给定消费者组中待处理消息的摘要。 在下面的示例中，我们创建一个消费者组，并通过使用 XREADGROUP 从该组中读取来立即创建一条待处理消息。

[source,text]
----
> XGROUP CREATE mystream group55 0-0
OK

> XREADGROUP GROUP group55 consumer-123 COUNT 1 STREAMS mystream >
1) 1) "mystream"
   2) 1) 1) 1526984818136-0
         2) 1) "duration"
            2) "1532"
            3) "event-id"
            4) "5"
            5) "user-id"
            6) "7782813"
----

我们期望消费者组 group55 的待处理条目列表现在有一条消息：名为 Consumer-123 的消费者获取了该消息，但未确认其处理。 简单的 XPENDING 表格将为我们提供以下信息：

[source,text]
----
> XPENDING mystream group55
1) (integer) 1
2) 1526984818136-0
3) 1526984818136-0
4) 1) 1) "consumer-123"
      2) "1"
----

在这种形式中，该命令输出该消费者组的待处理消息总数，为 1，后跟待处理消息中最小和最大的 ID，然后列出该消费者组中至少有一条待处理消息的每个消费者， 以及它拥有的待处理消息的数量。

== XPENDING 的扩展形式

摘要提供了很好的概述，但有时我们对细节感兴趣。 为了查看具有更多关联信息的所有待处理消息，我们还需要传递一系列 ID（与 XRANGE 类似）和非可选计数参数，以限制每次调用返回的消息数量：

[source,text]
----
> XPENDING mystream group55 - + 10
1) 1) 1526984818136-0
   2) "consumer-123"
   3) (integer) 196415
   4) (integer) 1
----

在扩展表单中，我们不再看到摘要信息，而是在待处理条目列表中显示每条消息的详细信息。 对于每条消息，返回四个属性：

. 消息的 ID。
. 获取消息且仍需确认的消费者的名称。 我们称其为消息的当前所有者。
. 自上次将此消息传递给此使用者以来经过的毫秒数。
. 该消息被传送的次数。

当其他消费者使用 XCLAIM 声明消息时，或者当通过 XREADGROUP 再次传递消息时，当访问消费者组中的消费者的历史记录时（请参阅 XREADGROUP 页面了解更多信息）。

可以向命令传递一个附加参数，以便查看具有特定所有者的消息：

[source,text]
----
> XPENDING mystream group55 - + 10 consumer-123
----

但在上述情况下，输出将是相同的，因为我们只有单个消费者的待处理消息。 然而，要记住的重要一点是，即使有来自许多消费者的许多待处理消息，这种由特定消费者过滤的操作也不是低效的：我们在全局和每个消费者都有一个待处理条目列表数据结构，所以 我们可以非常有效地只显示单个消费者待处理的消息。

空闲时间过滤器

还可以按空闲时间（以毫秒为单位）过滤待处理的流条目（对于一段时间未处理的 XCLAIMing 条目很有用）：

[source,text]
----
> XPENDING mystream group55 IDLE 9000 - + 10
> XPENDING mystream group55 IDLE 9000 - + 10 consumer-123
----

第一种情况将返回整个组中空闲时间超过 9 秒的前 10 个（或更少）PEL 条目，而第二种情况仅返回 Consumer-123 的 PEL 条目。

== Exclusive ranges and iterating the PEL

XPENDING 命令允许迭代挂起的条目，就像 XRANGE 和 XREVRANGE 允许流的条目一样。 您可以通过在上次读取的挂起条目的 ID 前添加表示开放（独占）范围的 ( 字符，并将其证明给该命令的后续调用来完成此操作。

== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-arrays[数组]: 该命令根据调用方式以不同格式返回数据，如本页先前所述。 然而，回复始终是一个项目数组。.

== 历史

从 Redis 版本 6.2.0 开始：添加了 IDLE 选项和 exclusive range intervals。
