= XTRIM

**语法**

[source,text]
----
XTRIM key <MAXLEN | MINID> [= | ~] threshold [LIMIT count]
----

**可用版本**：5.0.0

**时间复杂度**：O(N)，其中 N 是被驱逐条目的数量。 然而，常数时间非常小，因为条目被组织在包含多个条目的宏节点中，这些条目可以通过一次释放来释放。

**ACL 类别**：**@write, @stream, @slow**

如果需要，XTRIM 通过驱逐较旧的条目（具有较低 ID 的条目）来修剪流。

可以使用以下策略之一来修剪流：

* MAXLEN：只要流的长度超过指定的阈值，就驱逐条目，其中阈值是正整数。
* MINID：驱逐 ID 低于阈值的条目，其中阈值是流 ID。

例如，这会将流修剪为恰好最新的 1000 个项目：

[source,text]
----
XTRIM mystream MAXLEN 1000
----

而在此示例中，所有 ID 低于 649085820-0 的条目都将被驱逐：

[source,text]
----
XTRIM mystream MINID 649085820
----

默认情况下，或者当提供可选的 = 参数时，该命令执行精确修剪。

根据策略的不同，精确修剪意味着：

* MAXLEN：修剪后的流的长度将恰好是其原始长度和指定阈值之间的最小值。
* MINID：流中最旧的 ID 将恰好是其原始最旧 ID 和指定阈值之间的最大值。

== 近乎精确的修剪

由于精确修剪可能需要 Redis 服务器进行额外的工作，因此可以提供可选的 ~ 参数以使其更加高效。

例如：

[source,text]
----
XTRIM mystream MAXLEN ~ 1000
----

MAXLEN 策略和阈值之间的 ~ 参数意味着用户请求修剪流，使其长度至少为阈值，但可能稍长一些。 在这种情况下，当可以获得性能时（例如，当数据结构中的整个宏节点无法删除时），Redis 将提前停止修剪。 这使得修剪更加高效，并且这通常是您想要的，尽管在修剪之后，流可能有几十个超过阈值的额外条目。

使用 ~ 时控制命令完成的工作量的另一种方法是 LIMIT 子句。 使用时，它指定将被驱逐的条目的最大数量。 当未指定 LIMIT 和 count 时，将隐式使用默认值 100 * 宏节点中的条目数作为计数。 将值 0 指定为 count 会完全禁用限制机制。

== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-integers[整数]: 从流中删除的条目数。.

== 示例

[source,text]
----
redis> XADD mystream * field1 A field2 B field3 C field4 D
"1693193612881-0"
redis> XTRIM mystream MAXLEN 2
(integer) 0
redis> XRANGE mystream - +
1) 1) "1693193612881-0"
   2) 1) "field1"
      2) "A"
      3) "field2"
      4) "B"
      5) "field3"
      6) "C"
      7) "field4"
      8) "D"
redis>
----

== 历史

从 Redis 版本 6.2.0 开始：添加了 `MINID` trimming 策略和 LIMIT 选项。