= Spring Framework 中文文档
include::attributes.adoc[]

[horizontal]
<<overview.adoc#overview, 概述>> :: Spring 的历史介绍，设计理念， 反馈和贡献，以及入门指南。
<<core.adoc#spring-core, 核心组件>> :: IoC 容器，事件，资源，国际化，验证，数据绑定，类型转换，SpEL，AOP，AOT。
<<testing.adoc#testing, 测试>> :: Mock objects，TestContext 框架，Spring MVC 测试，WebTestClient。
<<data-access.adoc#spring-data-tier, 数据访问>> :: Transactions(事务支持)，DAO support(DAO 支持)，JDBC，R2DBC，ORM(对象关系映射)，编组 XML。
<<web.adoc#spring-web, Web Servlet>> :: Spring MVC，WebSocket，SockJS, STOMP 消息。
<<web-reactive.adoc#spring-webflux, Web Reactive>> :: Spring WebFlux，WebClient，WebSocket，RSocket。
<<integration.adoc#spring-integration, 集成>> :: REST Clients，JMS(java 消息服务)，JCA(J2EE 连接器架构)，JMX(Java 管理扩展)， Email(电子邮箱)，Tasks(任务执行)， Scheduling(调度)，Cache(缓存)。
<<languages.adoc#languages, 语言>> :: Kotlin, Groovy, Dynamic languages。
<<appendix.adoc#appendix, Appendix>> :: Spring properties。
https://github.com/spring-projects/spring-framework/wiki[*Wiki*] :: 最新特性，更新日志，支持的版本, 和其他跨版本的信息都在 https://github.com/spring-projects/spring-framework/wiki[*Github Wiki*] 进行维护。

NOTE: 本文档以 HTML 和 PDF 格式提供。

Rod Johnson, Juergen Hoeller, Keith Donald, Colin Sampaleanu, Rob Harrop, Thomas Risberg,
Alef Arendsen, Darren Davison, Dmitriy Kopylenko, Mark Pollack, Thierry Templier, Erwin
Vervaet, Portia Tung, Ben Hale, Adrian Colyer, John Lewis, Costin Leau, Mark Fisher, Sam
Brannen, Ramnivas Laddad, Arjen Poutsma, Chris Beams, Tareq Abedrabbo, Andy Clement, Dave
Syer, Oliver Gierke, Rossen Stoyanchev, Phillip Webb, Rob Winch, Brian Clozel, Stephane
Nicoll, Sebastien Deleuze, Jay Bryant, Mark Paluch

Copyright © 2002 - 2022 VMware, Inc. All Rights Reserved.

Copies of this document may be made for your own use and for distribution to others,
provided that you do not charge any fee for such copies and further provided that each
copy contains this Copyright Notice, whether distributed in print or electronically.