[[spring-webflux]]
= Web Reactive
include::attributes.adoc[]

文档的介绍了基于 https://www.reactive-streams.org/[Reactive Streams] API 构建的响应式 Web 应用程序的支持,该应用程序可在非阻塞服务器(例如 Netty,Undertow 和 Servlet 3.1+ 容器)上运行.
各个章节涵盖了  <<webflux.adoc#webflux, Spring WebFlux>>  框架,响应式  <<webflux-client, `WebClient`>>,对 <<webflux-test, 测试>>的支持以及  <<webflux-reactive-libraries, reactive libraries>>.
对于 Servlet 堆栈 Web 应用程序,请参阅 <<web.adoc#spring-web, Web on Servlet Stack>>.

include::web/webflux.adoc[leveloffset=+1]

include::web/webflux-webclient.adoc[leveloffset=+1]

[[webflux-http-interface-client]]
== HTTP Interface Client

Spring Frameworks 允许您将 HTTP 服务定义为具有 HTTP 交换方法的 Java 接口。 然后，您可以生成一个实现此接口并执行交换的代理。
这有助于简化 HTTP 远程访问，并为选择 API 样式（例如同步或响应式）提供了额外的灵活性。

有关详细信息，请参阅 <<integration.adoc#rest-http-interface, REST Endpoints>>。

include::web/webflux-websocket.adoc[leveloffset=+1]

[[webflux-test]]
== 测试
[.small]#<<web.adoc#webmvc.test, Same in Spring MVC>>#

`spring-test` 模块提供了 `ServerHttpRequest`,`ServerHttpResponse` 和 `ServerWebExchange` 的模拟实现. 有关模拟对象的讨论,请参见 <<testing.adoc#mock-objects-web-reactive, Spring Web Reactive>>

<<testing.adoc#webtestclient, `WebTestClient`>> 建立在这些模拟请求和响应对象的基础上,以提供对无需 HTTP 服务器即可测试 WebFlux 应用程序的支持.您也可以将 `WebTestClient` 用于端到端集成测试.


include::rsocket.adoc[leveloffset=+1]

[[webflux-reactive-libraries]]
== Reactive 库

`spring-webflux` 依赖于 `reactor-core`，并在内部使用它来构成异步逻辑并提供 Reactive Streams 支持. 通常,WebFlux API 返回 Flux 或 Mono(因为它们在内部使用),并且宽容地接受任何 Reactive Streams `Publisher` 实现作为输入.
Flux vs Mono 的使用很重要,因为它有助于表达基数,例如,是期望单个还是多个异步值,并且对于决策(例如在编码或解码 HTTP 消息时)至关重要.

对于带注解的控制器,WebFlux 透明的自动选择合适的 reactive 库.这是在 `ReactiveAdapterRegistry` 的帮助下完成的,该工具为 reactive 库和其他异步类型提供了可插入的支持.
该注册表具有对 RxJava 3,  Kotlin coroutines 和 SmallRye Mutiny 的内置支持,但您也可以注册其他的.

对于功能性API(例如 <<webflux-fn>>,`WebClient` 等),WebFlux API 的一般规则适用于- `Flux` 和 `Mono` 作为返回值,而 Reactive Streams Publisher 作为输入.
提供发布者(无论是自定义的还是来自其他响应式库的发布者)时,只能将其视为语义未知(0..N)的流.但是,如果知道语义,则可以使用 `Flux` 或 `Mono.from(Publisher)` 对其进行包装,而不用传递原始 `Publisher`.

例如,给定的 `Publisher` 不是 `Mono`,Jackson JSON 消息编写者需要多个值.如果媒体类型暗示无限流(例如 `application/json+stream`),则将分别写入和刷新值.否则,值将缓冲到列表中并呈现为 JSON 数组.