[[multi_project_builds]]
= Gradle 中的多项目构建

Gradle 中的多项目构建由一个根项目和一个或多个子项目组成。

[[sec:creating_multi_project_builds]]
== 创建一个多项目构建

一个最基本的多项目构建包含一个根项目和一个子项目。 这是一个多项目构建的结构，其中包含一个名为 `app` 的子项目：

.Basic multi-project build
====
[.multi-language-sample]
=====
.Project layout
[source, groovy]
----
.
├── app
│   ...
│   └── build.gradle
└── settings.gradle
----
=====
[.multi-language-sample]
=====
.Project layout
[source, kotlin]
----
.
├── app
│   ...
│   └── build.gradle.kts
└── settings.gradle.kts
----
=====
====

上面的项目结构是 Gradle 推荐您开始项目结构。 <<build_init_plugin#,build init plugin>> 还生成此结构的项目框架-具有单个子项目的根项目。

请注意，根项目没有 Gradle 构建文件，只有一个定义包括子项目的 settings 文件。
====
include::{snippets-dir}/multiproject/basic-multiproject/groovy/settings.gradle[]
include::{snippets-dir}/multiproject/basic-multiproject/kotlin/settings.gradle.kts[]
====

在这种情况下，Gradle 将在 `app` 目录中查找构建文件。

我们可以通过运行 `gradle projects` 命令来查看多项目构建的结构。

----
> gradle -q projects
include::{snippets-dir}/multiproject/basic-multiproject/tests/projects.out[]
----

假设子项目是应用了 <<application_plugin#,application plugin>> 的 Java应用程序，然后配置主类：

====
include::{snippets-dir}/multiproject/basic-multiproject/groovy/app/build.gradle[]
include::{snippets-dir}/multiproject/basic-multiproject/kotlin/app/build.gradle.kts[]
.app/src/main/java/com/example/Hello.java
[source, java]
----
include::{snippets-dir}/multiproject/basic-multiproject/groovy/app/src/main/java/com/example/Hello.java[]
----
====

然后，我们可以通过从 <<application_plugin#,application plugin>> 执行 `run`  任务来运行应用程序。

----
> gradle -q run
include::{snippets-dir}/multiproject/basic-multiproject/tests/run.out[]
----

这就是创建基本的多项目构建的过程，非常简单。

[[sec:adding_subprojects]]
== 添加子项目

假设我们要向之前创建的项目中添加另一个名为 `lib` 的子项目。我们需要做的就是在根 settings 文件中添加另一个 `include` 语句：

====
include::{snippets-dir}/multiproject/multiple-subprojects/groovy/settings.gradle[]
include::{snippets-dir}/multiproject/multiple-subprojects/kotlin/settings.gradle.kts[]
====

然后 Gradle 将在项目的 `lib/` 子目录中寻找新子项目的构建文件：

.Multi-project build with two subprojects
====
[.multi-language-sample]
=====
.Project layout
[source, groovy]
----
.
├── app
│   ...
│   └── build.gradle
├── lib
│   ...
│   └── build.gradle
└── settings.gradle
----
=====
[.multi-language-sample]
=====
.Project layout
[source, kotlin]
----
.
├── app
│   ...
│   └── build.gradle.kts
├── lib
│   ...
│   └── build.gradle.kts
└── settings.gradle.kts
----
=====
====

接下来，将探讨如何在子项目之间 <<sharing_build_logic_between_subprojects#,共享构建逻辑>> 以及 <<declaring_dependencies_between_subprojects#,子项目如何相互依赖>>。

== 命名建议

随着项目的不断发展，命名的一致性变得越来越重要。为了使您的构建可维护，我们建议以下操作：

：可以在设置文件中配置自定义项目名称。 

：。 

：“ rootProject.name”有效地为整个构建分配一个名称，该名称用于诸如构建扫描的报告中。 如果未设置根项目名称，则该名称将是容器目录名称，该名称可能不稳定（即您可以将项目检出到任何目录）。


1. _保留子项目的默认项目名称_:
可以在 settings 文件中配置自定义项目名称.
但是，对于开发人员来说，跟踪哪个项目属于哪个文件夹是不必要的额外工作。.

2. _所有项目名称均使用 kebab 大小写格式_:
kebab 大小写格式是指所有字母均小写，单词之间用短划线（'-'）分隔的字符（例如 `kebab-case-formatting`）
这已经是许多大型项目的实际模式。 此外，Gradle 支持 kebab 案例名称的 <<command_line_interface.adoc#sec:name_abbreviation,kebab 名称的名称缩写>>。

3. _在 settings 文件中定义根项目名称_:
´rootProject.name´ 为整个构建分配一个名称，该名称用于诸如构建扫描的报告中。
如果未设置根项目名称，则该名称将是项目所在目录的名称，该名称可能不稳定（即您可以将项目检出到任何目录）。
