[[sharing_build_logic_between_subprojects]]
= 子项目之间共享构建逻辑

[[sec:convention_plugins]]
== 插件合约

通常，多项目构建中的子项目具有一些共同的特征. 例如，几个子项目可能包含特定编程语言的代码，而另一个子项目可能专用于文档.
代码质量规则适用于所有代码子项目，但不适用于文档子项目.
同时，具有一个共同特征的子项目可能有不同的用途-它们可能会产生不同的工件类型，从而进一步区分它们，例如:

- _public libraries_ - 发布到某个存储库的 libraries
- _internal libraries_ - 其他子项目在项目内部依赖的库
- _command line applications_ - 具有特定打包要求的应用
- _web services_ - 具有与上述不同的特定打包要求的应用
- 等等

其他一些子项目的代码可能专用于测试目的等等.

上面的特征标识子项目的类型.换句话说，子项目的类型告诉我们该项目具有哪些特征.

Gradle 建议的组织构建逻辑的方法是使用其插件系统.插件应定义子项目的类型.实际上，<<plugin_reference#,Gradle core plugins>> 也以相同的方式建模-例如，<<java_plugin#,Java Plugin>> 配置一个通用的 Java 项目，
而 <<java_library_plugin#,Java Library Plugin>> 在内部应用 <<java_plugin#,Java Plugin>> 并配置特定于 Java 库的方面.
同样，<<application_plugin#,Application Plugin>> 将应用并配置 Java 插件和 <<distribution_plugin#,Distribution Plugin>>.

您可以通过应用和配置 core 和外部插件来组成构建逻辑，并创建定义新项目类型和配置特定于您的项目或组织的约定的定制插件.
对于本节开头的每个示例特征，我们可以编写一个插件，该插件封装给定类型的子项目所共有的逻辑.

我们建议将用于常规插件的源代码和测试放在项目根目录下的特殊 `buildSrc` 目录中. 有关 `buildSrc` 的更多信息，请参阅 <<organizing_gradle_projects.adoc#sec:build_sources,使用 buildSrc 组织构建逻辑>>.

看一下 link:../samples/sample_convention_plugins.html[多项目构建的示例]，该示例使用插件的约定对构建逻辑进行建模.

使用约定插件组成构建逻辑的多项目构建的另一个更复杂和真实的示例是 link:https://github.com/gradle/gradle[Gradle Build Tool] 本身的构建.

[[sec:convention_plugins_vs_cross_configuration]]
== 跨项目配置

在子项目之间共享构建逻辑的另一种方法(不鼓励使用)是通过 `subprojects {}` 和 `allprojects {}` DSL 构造进行跨项目配置.
通过交叉配置，可以将构建逻辑注入到子项目中，但在查看子项目的构建脚本时这并不明显，这使得理解特定子项目的逻辑变得更加困难.
从长远来看，交叉配置通常会随着越来越多的条件逻辑和更高的维护负担而变得复杂.
交叉配置还会在项目之间引入 <<multi_project_configuration_and_execution#sec:decoupled_projects,配置时耦合>> ，这可能会阻止 <<multi_project_configuration_and_execution#sec:configuration_on_demand,按需配置>> 等优化工作正常进行.


交叉配置有两种最常见的用法，可以使用插件的约定更好地建模:

- 将插件或其他配置应用于某些类型的子项目.
如果子项目的类型为 `X`，则交叉配置通常会配置 `Y`.这等效于将 `X-conventions` 插件直接应用于子项目.
- 从特定类型的子项目中提取信息.可以使用 <<cross_project_publications.adoc#sec:simple-sharing-artifacts-between-projects,outgoing configuration variants>> 对这种用例进行建模
