[[kotlin.coroutines]]
= Coroutines

Kotlin https://kotlinlang.org/docs/reference/coroutines-overview.html[Coroutines] 是Kotlin轻量级线程，允许以命令式方式编写非阻塞代码.  在语言方面，挂起函数为异步操作提供了一种抽象，而在库方面，https://github.com/Kotlin/kotlinx.coroutines[kotlinx.coroutines] 提供了诸如 https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html[`async { }`] 之类的函数以及诸如 https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/index.html[`Flow`] 之类的类型.

Spring Data 模块 在以下范围内提供对 Coroutines 的支持:

* https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-deferred/index.html[Deferred] 和 https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/index.html[Flow] Kotlin扩展中的返回值支持

[[kotlin.coroutines.dependencies]]
== 依赖

当 `kotlinx-coroutines-core` 和 `kotlinx-coroutines-reactor` 依赖项位于类路径中时，将启用 Coroutines 支持:

.在Maven pom.xml中添加的依赖
====
[source,xml]
----
<dependency>
	<groupId>org.jetbrains.kotlinx</groupId>
	<artifactId>kotlinx-coroutines-core</artifactId>
</dependency>

<dependency>
	<groupId>org.jetbrains.kotlinx</groupId>
	<artifactId>kotlinx-coroutines-reactor</artifactId>
</dependency>
----
====

NOTE: 支持 `1.3.0` 及更高版本.

[[kotlin.coroutines.reactive]]
== Reactive 如何转换为 Coroutines?

对于返回值，以下是从 Reactive 到 Coroutines API的转换:

* `fun handler(): Mono<Void>` 变成 `suspend fun handler()`
* `fun handler(): Mono<T>` 变成 `suspend fun handler(): T` 或 `suspend fun handler(): T?` 取决于 `Mono` 是否可以为空 (具有更静态键入的优势)
* `fun handler(): Flux<T>` 变成 `fun handler(): Flow<T>`


在 Coroutines 中， https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/index.html[`Flow`] 和 `Flux` 是等效的, 适用于热流或冷流，有限流或无限流，主要区别如下:

* `Flow` 是基于推式的 `Flux` 是推拉式混合的
* 背压通过暂停功能实现
* `Flow` 只有一个暂停的 https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/collect.html[收集方法] 并且运算符被实现为 https://kotlinlang.org/docs/reference/extensions.html[扩展]借助 Coroutines，操作员易于实施
* https://github.com/Kotlin/kotlinx.coroutines/tree/master/kotlinx-coroutines-core/common/src/flow/operators[Operators are easy to implement] thanks to Coroutines
* 扩展允许向 `Flow` 添加自定义运算符
* 收集操作正在暂停功能
* https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/map.html[`map` operator] 支持异步操作 (不需要 `flatMap`) ，因为它需要一个暂停函数参数

通过阅读有关 https://spring.io/blog/2019/04/12/going-reactive-with-spring-coroutines-and-kotlin-flow[Spring，Coroutines和Kotlin Flow Reactive]的博客文章，了解更多详细信息，包括如何与Coroutines并发运行代码.