ifndef::projection-collection[]
:projection-collection: Collection
endif::[]

[[projections]]
= 投影

Spring Data查询方法通常返回存储库管理的聚合根的一个或多个实例。 但是，有时可能需要根据这些类型的某些属性创建投影。 Spring Data允许对专用的返回类型进行建模，以更选择性地检索托管聚合的部分视图。

想象一下一个存储库和聚合根类型，例如以下示例：

.一个样本集合和存储库
====
[source, java, subs="+attributes"]
----
class Person {

  @Id UUID id;
  String firstname, lastname;
  Address address;

  static class Address {
    String zipCode, city, street;
  }
}

interface PersonRepository extends Repository<Person, UUID> {

  {projection-collection}<Person> findByLastname(String lastname);
}
----
====

现在，假设我们只想检索此人的姓名属性。 Spring Data提供什么手段来实现这一目标？ 本章的其余部分将回答该问题。

[[projections.interfaces]]
== 基于界面的投影

将查询结果限制为仅 `name` 属性的最简单方法是声明一个接口，该接口公开要读取的属性的访问器方法，如以下示例所示：
The easiest way to limit the result of the queries to only the name attributes is by declaring an interface that exposes accessor methods for the properties to be read, as shown in the following example:

.一个投影界面来检索属性的子集
====
[source, java]
----
interface NamesOnly {

  String getFirstname();
  String getLastname();
}
----
====

此处重要的一点是，此处定义的属性与聚合根中的属性完全匹配。 这样做可以使查询方法添加如下：

.使用基于接口的投影和查询方法的存储库
====
[source, java, subs="+attributes"]
----
interface PersonRepository extends Repository<Person, UUID> {

  {projection-collection}<NamesOnly> findByLastname(String lastname);
}
----
====

查询执行引擎在运行时为返回的每个元素创建该接口的代理实例，并将对公开方法的调用转发给目标对象。

[[projections.interfaces.nested]]
投影可以递归使用。 如果还希望包括一些 `Address` 信息，则为此创建一个投影接口，并从 `getAddress()` 的声明返回该接口，如以下示例所示：

.一个投影界面来检索属性的子集
====
[source, java]
----
interface PersonSummary {

  String getFirstname();
  String getLastname();
  AddressSummary getAddress();

  interface AddressSummary {
    String getCity();
  }
}
----
====

在方法调用时，将获得目标实例的 `address` 属性，并将其包装到投影代理中。

[[projections.interfaces.closed]]
=== 封闭的投影

其访问器方法均与目标集合的属性完全匹配的投影接口被视为封闭投影。 下面的示例（也在本章前面使用过）是一个封闭的投影：

.一个封闭的投影
====
[source, java]
----
interface NamesOnly {

  String getFirstname();
  String getLastname();
}
----
====

如果您使用封闭式投影，Spring Data可以优化查询执行，因为我们知道支持投影代理所需的所有属性。 有关更多信息，请参见参考文档中特定于模块的部分。

[[projections.interfaces.open]]
=== 打开投影

投影接口中的访问器方法也可以通过使用 `@Value` 批注来计算新值，如以下示例所示：

[[projections.interfaces.open.simple]]
.一个 打开投影
====
[source, java]
----
interface NamesOnly {

  @Value("#{target.firstname + ' ' + target.lastname}")
  String getFullName();
  …
}
----
====

在  `target`  变量中提供了支持投影的合计根。 使用 `@Value` 的投影接口是开放式投影。 在这种情况下，Spring Data无法应用查询执行优化，因为SpEL表达式可以使用聚合根的任何属性。

`@Value` 中使用的表达式应该不太复杂-您要避免在 `String` 变量中进行编程。 对于非常简单的表达式，一种选择可能是求助于默认方法（在Java 8中引入），如以下示例所示：

[[projections.interfaces.open.default]]
.使用默认方法自定义逻辑的投影接口
====
[source, java]
----
interface NamesOnly {

  String getFirstname();
  String getLastname();

  default String getFullName() {
    return getFirstname().concat(" ").concat(getLastname());
  }
}
----
====

这种方法要求您能够完全基于投影接口上公开的其他访问器方法来实现逻辑。 第二个更灵活的选择是在Spring bean中实现自定义逻辑，然后从SpEL表达式中调用该自定义逻辑，如以下示例所示：

[[projections.interfaces.open.bean-reference]]
.Sample Person 对象
====
[source, java]
----
@Component
class MyBean {

  String getFullName(Person person) {
    …
  }
}

interface NamesOnly {

  @Value("#{@myBean.getFullName(target)}")
  String getFullName();
  …
}
----
====

请注意SpEL表达式如何引用 `myBean` 并调用  `getFullName(…)` 方法，并将投影目标作为方法参数转发。 SpEL表达式评估支持的方法也可以使用方法参数，然后可以从表达式中引用这些参数。 方法参数可通过名为 `args` 的对象数组获得。
下面的示例演示如何从 `args` 数组获取方法参数：

.Sample Person 对象
====
[source, java]
----
interface NamesOnly {

  @Value("#{args[0] + ' ' + target.firstname + '!'}")
  String getSalutation(String prefix);
}
----
====

同样，对于更复杂的表达式，您应该使用Spring bean并让该表达式调用方法，<<projections.interfaces.open.bean-reference,如前所述>>。

[[projections.dtos]]
== 基于类的投影（DTO）

定义投影的另一种方法是使用值类型DTO（数据传输对象），该类型DTO保留应该被检索的字段的属性。 这些DTO类型可以以与使用投影接口完全相同的方式使用，除了没有代理发生和不能应用嵌套投影之外。

如果商店通过限制要加载的字段来优化查询执行，则要加载的字段由公开的构造函数的参数名称确定。

以下示例显示了一个预计的DTO：

.一个投影的DTO
====
[source, java]
----
class NamesOnly {

  private final String firstname, lastname;

  NamesOnly(String firstname, String lastname) {

    this.firstname = firstname;
    this.lastname = lastname;
  }

  String getFirstname() {
    return this.firstname;
  }

  String getLastname() {
    return this.lastname;
  }

  // equals(…) and hashCode() implementations
}
----
====



[TIP]
.避免投影DTO的样板代码
====
您可以使用 https://projectlombok.org[Project Lombok] 大大简化DTO的代码，该项目提供了 `@Value` 注释（不要与前面的界面示例中显示的Spring的 `@Value` 注释混淆）。 如果您使用Project Lombok的 `@Value` 批注，则前面显示的示例DTO将变为以下内容：

[source, java]
----
@Value
class NamesOnly {
	String firstname, lastname;
}
----
默认情况下，字段是  `private final` 的，并且该类公开了一个构造函数，该构造函数接受所有字段并自动获取实现的 `equals(…)` 和 `hashCode()` 方法。
====

[[projection.dynamic]]
== 动态投影

到目前为止，我们已经将投影类型用作集合的返回类型或元素类型。 但是，您可能想要选择在调用时要使用的类型（这使它成为动态的）。 要应用动态投影，请使用查询方法，如以下示例中所示：

.使用动态投影参数的存储库
====
[source, java, subs="+attributes"]
----
interface PersonRepository extends Repository<Person, UUID> {

  <T> {projection-collection}<T> findByLastname(String lastname, Class<T> type);
}
----
====

通过这种方式，该方法可以按原样或应用投影来获得聚合，如下例所示:

.使用带有动态投影的存储库
====
[source, java, subs="+attributes"]
----
void someMethod(PersonRepository people) {

  {projection-collection}<Person> aggregates =
    people.findByLastname("Matthews", Person.class);

  {projection-collection}<NamesOnly> aggregates =
    people.findByLastname("Matthews", NamesOnly.class);
}
----
====
