[[elasticsearch-migration-guide-4.0-4.1]]
= 从 4.0.x 升级到 4.1.x

本节介绍了从版本 4.0.x 到 4.1.x 的重大更改，以及如何用新引入的功能替换已删除的功能.

[[elasticsearch-migration-guide-4.0-4.1.deprecations]]
== 弃用

.定义 id 属性
通过使用 `id` 或  `document` 命名，可以将实体的属性定义为 id 属性。
现在已弃用此行为，并将产生警告。
请向我们提供 `@Id` 注解，以将某个属性标记为 `id` 属性.

.索引映射
在 `ReactiveElasticsearchClient.Indices`  接口中，不赞成使用  `updateMapping`  方法，而建议使用 `putMapping` 方法。
它们执行相同的操作，但是 `putMapping` 与 Elasticsearch API 中的命名一致:

.Alias handling
在 `IndexOperations` 接口中， 不赞成使用 `addAlias(AliasQuery)`, `removeAlias(AliasQuery)` 和 `queryForAlias()` 方法.
请使用的新的 `alias(AliasAction)`, `getAliases(String...)` 和 `getAliasesForIndex(String...)` 方法，他们提供了更多功能和更简洁的 API.

.Parent-ID
从版本 6 开始，已从 Elasticsearch 中删除了父代 ID 的用法。我们现在弃用相应的字段和方法.

[[elasticsearch-migration-guide-4.0-4.1.removal]]
== 删除

.Type mappings
删除了 `@Document` 注解的 _type mappings_ 参数和 `IndexCoordinates` 对象。
它们在 Spring Data Elasticsearch 4.0 中已弃用，并且不再使用它们的值.

[[elasticsearch-migration-guide-4.0-4.1.breaking-changes]]
== 重大变化

=== ReactiveElasticsearchClient.Indices 方法的返回类型

到目前为止，尚未使用 `ReactiveElasticsearchClient.Indices` 中的方法.
随着 `ReactiveIndexOperations` 的引入，有必要更改一些返回类型:

* `createIndex`  将返回 `Mono<Boolean>` 而不是 `Mono<Void>` 来指示成功创建索引.
* `updateMapping`  现在返回 `Mono<Boolean>` 而不是 `Mono<Void>` 来表示成功的映射存储.

=== DocumentOperartions.bulkIndex 方法的返回类型

这些方法正在重现包含新索引记录的 ID 的 `List<String>`。
现在他们返回一个 `List<IndexedObjectInformation>`; 这些对象包含 id 和有关乐观锁的信息(seq_no和primary_term)
