[[elasticsearch.clients]]
= Elasticsearch 客户端

本章介绍了如何配置和使用支持的 Elasticsearch 客户端的实现

Spring Data Elasticsearch 在连接到单个 Elasticsearch 节点或集群的 Elasticsearch 客户端上进行操作. 虽然可以使用 Elasticsearch Client 客户端与集群一起工作, 但使用 Spring Data Elasticsearch 通常使用更加高级的抽象 <<elasticsearch.operations>> 和 <<elasticsearch.repositories>>.

[[elasticsearch.clients.transport]]
== Transport Client

WARNING: 众所周知,从 Elasticsearch 7 开始 `TransportClient` 已经被弃用,并且在  Elasticsearch 8 中删除. (https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html[see the Elasticsearch documentation]). Spring Data Elasticsearch 支持 `TransportClient` 只要它在已使用的 Elasticsearch  <<preface.versions,版本>>  中可用,但从4.0版本开始已弃用使用它的类.

强烈建议使用  <<elasticsearch.clients.rest>> 而不是 `TransportClient`.

.Transport Client
====
[source,java]
----
@Configuration
public class TransportClientConfig extends ElasticsearchConfigurationSupport {

    @Bean
    public Client elasticsearchClient() throws UnknownHostException {
        Settings settings = Settings.builder().put("cluster.name", "elasticsearch").build();        <.>
        TransportClient client = new PreBuiltTransportClient(settings);
        client.addTransportAddress(new TransportAddress(InetAddress.getByName("127.0.0.1"), 9300)); <.>
        return client;
    }

    @Bean(name = { "elasticsearchOperations", "elasticsearchTemplate" })
    public ElasticsearchTemplate elasticsearchTemplate() throws UnknownHostException {

		ElasticsearchTemplate template = new ElasticsearchTemplate(elasticsearchClient, elasticsearchConverter);
		template.setRefreshPolicy(refreshPolicy());                                                 <.>

		return template;
    }
}

// ...

IndexRequest request = new IndexRequest("spring-data")
 .id(randomID())
 .source(someObject);

IndexResponse response = client.index(request);
----
<.> 必须使用群集名称配置 `TransportClient`.
<.> 连接客户端的主机和端口.
<.> RefreshPolicy 必须在 `ElasticsearchTemplate` 中设置（覆盖 `refreshPolicy()` 以不使用默认值）
====

[[elasticsearch.clients.rest]]
== 更高级别的 REST Client

Java High Level REST Client 是 Elasticsearch 默认的客户端, 它可以直接替代 `TransportClient` 因为他们接受并返回完全相同的请求和响应.因此依赖于 Elasticsearch core 项目
异步调用是在客户端管理的线程池上进行的,并且要求在完成请求时通知回调.

.High Level REST Client
====
[source,java]
----
@Configuration
public class RestClientConfig extends AbstractElasticsearchConfiguration {

    @Override
    @Bean
    public RestHighLevelClient elasticsearchClient() {

        final ClientConfiguration clientConfiguration = ClientConfiguration.builder()  <1>
            .connectedTo("localhost:9200")
            .build();

        return RestClients.create(clientConfiguration).rest();                         <2>
    }
}

// ...

  @Autowired
  RestHighLevelClient highLevelClient;

  RestClient lowLevelClient = highLevelClient.lowLevelClient();                        <3>

// ...

IndexRequest request = new IndexRequest("spring-data")
  .id(randomID())
  .source(singletonMap("feature", "high-level-rest-client"))
  .setRefreshPolicy(IMMEDIATE);

IndexResponse response = highLevelClient.index(request,RequestOptions.DEFAULT);
----
<1> 使用 builder 提供集群地址, 设置默认的 `HttpHeaders` 或 启用 SSL.
<2> 创建 RestHighLevelClient.
<3> 也可以获取 `lowLevelRest()` 客户端.
====

[[elasticsearch.clients.reactive]]
== Reactive Client

`ReactiveElasticsearchClient` 是一个基于 `WebClient` 的非官方驱动程序.它使用 Elasticsearch core 项目提供的请求/响应对象.调用直接在响应式堆栈上操作,而不是将异步(线程池绑定)响应包装为响应式类型.

.Reactive REST Client
====
[source,java]
----
@Configuration
public class ReactiveRestClientConfig extends AbstractReactiveElasticsearchConfiguration {

    @Override
    @Bean
    public ReactiveElasticsearchClient reactiveElasticsearchClient() {
        final ClientConfiguration clientConfiguration = ClientConfiguration.builder() <.>
            .connectedTo("localhost:9200") //
            .build();
        return ReactiveRestClients.create(clientConfiguration);

    }
}
// ...

Mono<IndexResponse> response = client.index(request ->

  request.index("spring-data")
    .id(randomID())
    .source(singletonMap("feature", "reactive-client"));
);
----
<1> 使用 builder 提供集群地址, 设置默认的 `HttpHeaders` 或 启用 SSL.
====

NOTE: ReactiveClient 响应, (特别是搜索操作)绑定到请求的 `from` (offset) & `size` (limit) 选项.

[[elasticsearch.clients.configuration]]
== Client 配置

客户端行为可以通过 `ClientConfiguration` 更改,该配置允许设置 SSL、connect 和 socket timeouts, headers 和其他参数的选项.

.Client Configuration
====
[source,java]
----
HttpHeaders httpHeaders = new HttpHeaders();
httpHeaders.add("some-header", "on every request")                      <.>

ClientConfiguration clientConfiguration = ClientConfiguration.builder()
  .connectedTo("localhost:9200", "localhost:9291")                      <.>
  .usingSsl()                                                           <.>
  .withProxy("localhost:8888")                                          <.>
  .withPathPrefix("ela")                                                <.>
  .withConnectTimeout(Duration.ofSeconds(5))                            <.>
  .withSocketTimeout(Duration.ofSeconds(3))                             <.>
  .withDefaultHeaders(defaultHeaders)                                   <.>
  .withBasicAuth(username, password)                                    <.>
  .withHeaders(() -> {                                                  <.>
    HttpHeaders headers = new HttpHeaders();
    headers.add("currentTime", LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
    return headers;
  })
  .withClientConfigurer(                                                <.>
    ReactiveRestClients.WebClientConfigurationCallback.from(webClient -> {
  	  // ...
      return webClient;
  	}))
  .withClientConfigurer(                                                <.>
    RestClients.RestClientConfigurationCallback.from(clientBuilder -> {
  	  // ...
      return clientBuilder;
  	}))
  . // ... other options
  .build();
----
<.> 定义默认的 headers, 如有需要,可以自定义
<.> 使用 builder 提供集群机制, 设置默认 `HttpHeaders` 或 启用 SSL.
<.> 可选的,启用 SSL.
<.> 可选的,设置代理.
<.> 可选的,设置路径前缀, 主要用于不同的集群在某个反向代理后面.
<.> 设置连接超时.默认值为 10 秒.
<.> 设置 socket 超时.默认值为 5 秒
<.> 可选的.设置 headers.
<.> 添加 basic 认证.
<.> 可以指定一个 `Supplier<Header>` 函数,该函数在每次请求发送到 Elasticsearch 之前都会被调用——例如,上例中,当前时间被写入 header 中.
<.> 用于响应式设置一个配置 `WebClient` 的函数
<.> 用于非响应式设置，配置 REST 客户端的功能
====

IMPORTANT: 如上例所示,可以将随时间变化请求头的注入到 Supplier 中, 例如身份验证 JWT 令牌. 如果这是在响应式中使用的,supplier 函数一定不能阻塞!

=== Elasticsearch 7 compatibility headers

当使用 Spring Data Elasticsearch 4（使用 Elasticsearch 7 客户端库）并访问在版本 8 上运行的 Elasticsearch 集群时，需要设置兼容性请求头
https://www.elastic.co/guide/en/elasticsearch/reference/8.0/rest-api-compatibility.html[参见 Elasticserach 文档]。
这应该使用如上所示的 header supplier 来完成：

====
[source,java]
----
ClientConfigurationBuilder configurationBuilder = new ClientConfigurationBuilder();
    configurationBuilder //
		// ...
		.withHeaders(() -> {
			HttpHeaders defaultCompatibilityHeaders = new HttpHeaders();
			defaultCompatibilityHeaders.add("Accept",
                          "application/vnd.elasticsearch+json;compatible-with=7");
			defaultCompatibilityHeaders.add("Content-Type",
                          "application/vnd.elasticsearch+json;compatible-with=7");
			return defaultCompatibilityHeaders;
		});
----
====


[[elasticsearch.clients.logging]]
== Client 日志

要查看实际发送到服务器和从服务器接收的内容,请按照以下代码片段中的说明打开在 transport 级别的 `Request` / `Response` 日志记录.

.Enable transport layer logging
[source,xml]
----
<logger name="org.springframework.data.elasticsearch.client.WIRE" level="trace"/>
----

NOTE: 当分别通过 `RestClients` 和 `ReactiveRestClients` 获得时,以上内容适用于 `RestHighLevelClient` 和 `ReactiveElasticsearchClient`,不适用于 `TransportClient`.