[[elasticsearch.misc]]
= 其他 Elasticsearch 操作支持

本章涵盖了对不能通过 repository 接口直接访问的 Elasticsearch 操作的额外支持。建议将这些操作添加为自定义实现，如 <<repositories.custom-implementations>> 中所述。

[[elasticsearch.misc.filter]]
== Filter Builder

Filter Builder 提高查询速度.

====
[source,java]
----
private ElasticsearchOperations operations;

IndexCoordinates index = IndexCoordinates.of("sample-index");

SearchQuery searchQuery = new NativeSearchQueryBuilder()
  .withQuery(matchAllQuery())
  .withFilter(boolFilter().must(termFilter("id", documentId)))
  .build();
  
Page<SampleEntity> sampleEntities = operations.searchForPage(searchQuery, SampleEntity.class, index);
----
====

[[elasticsearch.scroll]]
== 对的数据量大的结果集使用 Scroll

Elasticsearch 有一个 scroll API，用于以块为单位获取较大的结果集。 Spring Data Elasticsearch 在内部使用此方法来提供 `<T> SearchHitsIterator<T> SearchOperations.searchForStream(Query query, Class<T> clazz, IndexCoordinates index)` 方法的实现。

[source,java]
----
IndexCoordinates index = IndexCoordinates.of("sample-index");

SearchQuery searchQuery = new NativeSearchQueryBuilder()
  .withQuery(matchAllQuery())
  .withFields("message")
  .withPageable(PageRequest.of(0, 10))
  .build();

SearchHitsIterator<SampleEntity> stream = elasticsearchTemplate.searchForStream(searchQuery, SampleEntity.class, index);

List<SampleEntity> sampleEntities = new ArrayList<>();
while (stream.hasNext()) {
  sampleEntities.add(stream.next());
}

stream.close();
----

`SearchOperations` API 中没有方法访问 scroll ID，如果必须访问 scroll ID，则可以使用 `ElasticsearchRestTemplate` 的以下方法：

[source,java]
----

@Autowired ElasticsearchRestTemplate template;

IndexCoordinates index = IndexCoordinates.of("sample-index");

SearchQuery searchQuery = new NativeSearchQueryBuilder()
  .withQuery(matchAllQuery())
  .withFields("message")
  .withPageable(PageRequest.of(0, 10))
  .build();

SearchScrollHits<SampleEntity> scroll = template.searchScrollStart(1000, searchQuery, SampleEntity.class, index);

String scrollId = scroll.getScrollId();
List<SampleEntity> sampleEntities = new ArrayList<>();
while (scroll.hasSearchHits()) {
  sampleEntities.addAll(scroll.getSearchHits());
  scrollId = scroll.getScrollId();
  scroll = template.searchScrollContinue(scrollId, 1000, SampleEntity.class);
}
template.searchScrollClear(scrollId);
----

要将 Scroll API 与存储库方法一起使用，返回类型必须在 `Elasticsearch` 存储库中定义为 `Stream`。 然后，该方法的实现将使用 `ElasticsearchTemplate` 中的 scroll 方法。

[source,java]
----
interface SampleEntityRepository extends Repository<SampleEntity, String> {

    Stream<SampleEntity> findBy();

}
----

[[elasticsearch.misc.sorts]]
== Sort 选项

除了描述的默认排序选项之外，<<repositories.paging-and-sorting>> Spring Data Elasticsearch 还具有 `GeoDistanceOrder` 类，该类可以将搜索结果按地理距离排序。

如果要搜索的类有 _location_ 的 `GeoPoint` 属性，则下面的 `Sort` 将按到指定点的距离对结果进行排序：

[source,java]
----
Sort.by(new GeoDistanceOrder("location", new GeoPoint(48.137154, 11.5761247)))
----


