[[elasticsearch.operations]]
= Elasticsearch 操作

Spring Data Elasticsearch 使用几个接口来定义对 Elasticsearch 索引调用的操作(有关响应式接口的描述，请参阅 <<elasticsearch.reactive.operations>>)。

* `IndexOperations` 定义索引的动作，例如创建和删除索引
* `DocumentOperations` 定义根据实体 id 存储，更新和检索文档实体的操作
* `SearchOperations` 定义使用查询来搜索多个实体的动作
* `ElasticsearchOperations` 结合了 `DocumentOperations` 和 `SearchOperations` 接口.

这些接口与 https://www.elastic.co/guide/en/elasticsearch/reference/current/rest-apis.html[Elasticsearch API] 相对应.

接口的默认实现提供:

* 管理索引.
* domain 类型的读写映射.
* 丰富的查询和条件 API.
* 资源管理和异常转化.

[[elasticsearch.operations.template]]
== ElasticsearchTemplate

NOTE: 从 4.0 版开始不推荐使用 ElasticsearchTemplate , 建议使用 ElasticsearchRestTemplate 替代.

`ElasticsearchTemplate` 使用了 <<elasticsearch.clients.transport>> ，并实现了 `ElasticsearchOperations` 接口.

.ElasticsearchTemplate 配置
====
[source,java]
----
@Configuration
public class TransportClientConfig extends ElasticsearchConfigurationSupport {

  @Bean
  public Client elasticsearchClient() throws UnknownHostException {                 <1>
    Settings settings = Settings.builder().put("cluster.name", "elasticsearch").build();
    TransportClient client = new PreBuiltTransportClient(settings);
    client.addTransportAddress(new TransportAddress(InetAddress.getByName("127.0.0.1"), 9300));
    return client;
  }

  @Bean(name = {"elasticsearchOperations", "elasticsearchTemplate"})
  public ElasticsearchTemplate elasticsearchTemplate() throws UnknownHostException { <2>
  	return new ElasticsearchTemplate(elasticsearchClient());
  }
}
----
<1> 设置 <<elasticsearch.clients.transport>>. 从 4.0 版本开始废弃.
<2> 创建 `ElasticsearchTemplate` bean, 并提供两个命名, _elasticsearchOperations_ 和 _elasticsearchTemplate_.
====

[[elasticsearch.operations.resttemplate]]
== ElasticsearchRestTemplate

`ElasticsearchRestTemplate` 使用了 <<elasticsearch.clients.rest>> 并实现了 `ElasticsearchOperations` 接口.

.ElasticsearchRestTemplate 配置
====
[source,java]
----
@Configuration
public class RestClientConfig extends AbstractElasticsearchConfiguration {
  @Override
  public RestHighLevelClient elasticsearchClient() {       <1>
    return RestClients.create(ClientConfiguration.localhost()).rest();
  }

  // no special bean creation needed                       <2>
}
----
<1> 设置 <<elasticsearch.clients.rest>>.
<2> `AbstractElasticsearchConfiguration` 已经提供了 `elasticsearchTemplate` bean.
====

[[elasticsearch.operations.usage]]
== 使用案例

因为 `ElasticsearchTemplate` 和 `ElasticsearchRestTemplate` 都实现了 `ElasticsearchOperations` 接口，所以在使用它们时的代码没有什么不同。这个例子展示了如何在 Spring REST 控制器中使用 `ElasticsearchOperations` 实例。如果使用的是 `TransportClient` 或 `RestClient`，则可以通过为相应的 Bean 提供上面所示的配置之一来做出决定。

.ElasticsearchOperations usage
====
[source,java]
----
@RestController
@RequestMapping("/")
public class TestController {

  private  ElasticsearchOperations elasticsearchOperations;

  public TestController(ElasticsearchOperations elasticsearchOperations) { <1>
    this.elasticsearchOperations = elasticsearchOperations;
  }

  @PostMapping("/person")
  public String save(@RequestBody Person person) {                         <2>

    IndexQuery indexQuery = new IndexQueryBuilder()
      .withId(person.getId().toString())
      .withObject(person)
      .build();
    String documentId = elasticsearchOperations.index(indexQuery);
    return documentId;
  }

  @GetMapping("/person/{id}")
  public Person findById(@PathVariable("id")  Long id) {                   <3>
    Person person = elasticsearchOperations
      .queryForObject(GetQuery.getById(id.toString()), Person.class);
    return person;
  }
}

----
<1> 在构造函数中注入 `ElasticsearchOperations` bean.
<2> 在 Elasticsearch 集群中存储一些 entity.
<3> 通过 id 搜索 eneity.
====

要查看 `ElasticsearchOperations` 的全部功能，请参阅 API 文档。

include::reactive-elasticsearch-operations.adoc[leveloffset=+1]

[[elasticsearch.operations.searchresulttypes]]
== 搜索结果类型

使用 `DocumentOperations` 接口的方法搜索文档时，只返回匹配的实体。 使用 `SearchOperations` 接口的方法进行搜索时，每个实体都有额外的其他附加信息，例如，找到的的实体具有  _score_ 或 _sortValues_。

为了返回此信息，每个实体都包装在一个 `SearchHit` 对象中，该对象包含该特定于实体的附加信息。 这些 `SearchHit` 对象本身在 `SearchHits` 对象中返回，该对象还包含有关整个搜索的信息，例如 _maxScore_  或请求的聚合。 现在可以使用以下类和接口：

.SearchHit<T>
包含以下信息:

* Id
* Score
* Sort Values
* Highlight fields
* The retrieved entity of type <T>

.SearchHits<T>
包含以下信息:

* Number of total hits
* Total hits relation
* Maximum score
* A list of `SearchHit<T>` objects
* Returned aggregations

.SearchPage<T>
定义一个包含 `SearchHits<T>` 的 Spring Data `Page` 可以使用存储库方法进行分页访问。.

.SearchScrollHits<T>
由 `ElasticsearchRestTemplate` 中的低级 scroll API 函数返回，它使用 Elasticsearch scroll ID丰富了 `SearchHits<T>`。

.SearchHitsIterator<T>
由 `SearchOperations` 接口返回一个可迭代的流(Stream).

