[[elasticsearch.operations]]
= Elasticsearch 操作

Spring Data Elasticsearch 使用几个接口来定义对 Elasticsearch 索引调用的操作(有关响应式接口的描述,请参阅 <<elasticsearch.reactive.operations>>).

* `IndexOperations` 定义索引的动作,例如创建和删除索引
* `DocumentOperations` 定义根据实体 id 存储,更新和检索文档实体的操作
* `SearchOperations` 定义使用查询来搜索多个实体的动作
* `ElasticsearchOperations` 结合了 `DocumentOperations` 和 `SearchOperations` 接口.

这些接口与 https://www.elastic.co/guide/en/elasticsearch/reference/current/rest-apis.html[Elasticsearch API] 相对应.

接口的默认实现提供:

* 管理索引.
* domain 类型的读写映射.
* 丰富的查询和条件 API.
* 资源管理和异常转化.

[NOTE]
====
.索引管理以及自动创建索引和映射.

可以从 `ElasticsearchOperations` 接口中获得 `IndexOperations` 接口和其实现类 - 例如,调用  `operations.indexOps(clazz)`- 可以使用户能够创建索引, put mappings 或 store template 和 Elasticsearch 集群中的别名信息.

**这些操作都不是由**  `IndexOperations` 或 `ElasticsearchOperations` 的实现自动完成的.  调用方法是用户的责任.

使用 Spring Data Elasticsearch repositories 时支持自动创建索引和写入映射,  请参见  <<elasticsearch.repositories.autocreation>>

====

[[elasticsearch.operations.template]]
== ElasticsearchTemplate

NOTE: 从 4.0 版开始不推荐使用 ElasticsearchTemplate , 建议使用 ElasticsearchRestTemplate 替代.

`ElasticsearchTemplate` 使用了 <<elasticsearch.clients.transport>> ,并实现了 `ElasticsearchOperations` 接口.

.ElasticsearchTemplate 配置
====
[source,java]
----
@Configuration
public class TransportClientConfig extends ElasticsearchConfigurationSupport {

  @Bean
  public Client elasticsearchClient() throws UnknownHostException {                 <1>
    Settings settings = Settings.builder().put("cluster.name", "elasticsearch").build();
    TransportClient client = new PreBuiltTransportClient(settings);
    client.addTransportAddress(new TransportAddress(InetAddress.getByName("127.0.0.1"), 9300));
    return client;
  }

  @Bean(name = {"elasticsearchOperations", "elasticsearchTemplate"})
  public ElasticsearchTemplate elasticsearchTemplate() throws UnknownHostException { <2>
  	return new ElasticsearchTemplate(elasticsearchClient());
  }
}
----
<1> 设置 <<elasticsearch.clients.transport>>. 从 4.0 版本开始废弃.
<2> 创建 `ElasticsearchTemplate` bean, 并提供两个命名, _elasticsearchOperations_ 和 _elasticsearchTemplate_.
====

[[elasticsearch.operations.resttemplate]]
== ElasticsearchRestTemplate

`ElasticsearchRestTemplate` 使用了 <<elasticsearch.clients.rest>> 并实现了 `ElasticsearchOperations` 接口.

.ElasticsearchRestTemplate 配置
====
[source,java]
----
@Configuration
public class RestClientConfig extends AbstractElasticsearchConfiguration {
  @Override
  public RestHighLevelClient elasticsearchClient() {       <1>
    return RestClients.create(ClientConfiguration.localhost()).rest();
  }

  // no special bean creation needed                       <2>
}
----
<1> 设置 <<elasticsearch.clients.rest>>.
<2> `AbstractElasticsearchConfiguration` 已经提供了 `elasticsearchTemplate` bean.
====

[[elasticsearch.operations.usage]]
== 使用案例

因为 `ElasticsearchTemplate` 和 `ElasticsearchRestTemplate` 都实现了 `ElasticsearchOperations` 接口,所以在使用它们时的代码没有什么不同.这个例子展示了如何在 Spring REST 控制器中使用 `ElasticsearchOperations` 实例.如果使用的是 `TransportClient` 或 `RestClient`,则可以通过为相应的 Bean 提供上面所示的配置之一来做出决定.

.ElasticsearchOperations usage
====
[source,java]
----
@RestController
@RequestMapping("/")
public class TestController {

  private  ElasticsearchOperations elasticsearchOperations;

  public TestController(ElasticsearchOperations elasticsearchOperations) { <1>
    this.elasticsearchOperations = elasticsearchOperations;
  }

  @PostMapping("/person")
  public String save(@RequestBody Person person) {                         <2>

    IndexQuery indexQuery = new IndexQueryBuilder()
      .withId(person.getId().toString())
      .withObject(person)
      .build();
    String documentId = elasticsearchOperations.index(indexQuery);
    return documentId;
  }

  @GetMapping("/person/{id}")
  public Person findById(@PathVariable("id")  Long id) {                   <3>
    Person person = elasticsearchOperations
      .queryForObject(GetQuery.getById(id.toString()), Person.class);
    return person;
  }
}

----
<1> 在构造函数中注入 `ElasticsearchOperations` bean.
<2> 在 Elasticsearch 集群中存储一些 entity.
<3> 通过 id 搜索 eneity.
====

要查看 `ElasticsearchOperations` 的全部功能,请参阅 API 文档.

include::reactive-elasticsearch-operations.adoc[leveloffset=+1]

[[elasticsearch.operations.searchresulttypes]]
== 搜索结果类型

使用 `DocumentOperations` 接口的方法搜索文档时,只返回匹配的实体. 使用 `SearchOperations` 接口的方法进行搜索时,每个实体都有额外的其他附加信息,例如,找到的的实体具有  _score_ 或 _sortValues_.

为了返回此信息,每个实体都包装在一个 `SearchHit` 对象中,该对象包含该特定于实体的附加信息. 这些 `SearchHit` 对象本身在 `SearchHits` 对象中返回,该对象还包含有关整个搜索的信息,例如 _maxScore_  或请求的聚合. 现在可以使用以下类和接口:

.SearchHit<T>
包含以下信息:

* Id
* Score
* Sort Values
* Highlight fields
* Inner hits (this is an embedded `SearchHits` object containing eventually returned inner hits)
* The retrieved entity of type <T>

.SearchHits<T>
包含以下信息:

* Number of total hits
* Total hits relation
* Maximum score
* A list of `SearchHit<T>` objects
* Returned aggregations

.SearchPage<T>
定义一个包含 `SearchHits<T>` 的 Spring Data `Page` 可以使用存储库方法进行分页访问..

.SearchScrollHits<T>
由 `ElasticsearchRestTemplate` 中的低级 scroll API 函数返回,它使用 Elasticsearch scroll ID丰富了 `SearchHits<T>`.

.SearchHitsIterator<T>
由 `SearchOperations` 接口返回一个可迭代的流(Stream).

== Queries

几乎在 `SearchOperations` 和 `ReactiveSearchOperations` 接口中定义的所有方法都采用 `Query` 参数,  该参数定义要执行的查询以进行搜索.  `Query` 是一个接口,  Spring Data Elasticsearch 提供了三种实现: `CriteriaQuery`,  `StringQuery` 和 `NativeSearchQuery`.

=== CriteriaQuery

基于 `CriteriaQuery` 的查询允许创建查询来搜索数据,  而无需了解 Elasticsearch 查询的语法或基础知识.  它们允许用户通过简单地链接和组合 `Criteria` 对象来构建查询,  这些对象指定了搜索文档必须满足的条件.

NOTE: 在谈论 AND 或 OR 时,  请牢记组合条件 在 Elasticsearch 中, AND 会被转换为 **must** 条件, OR 会被转换为 **should**

最好通过示例来说明 `Criteria` 的用法.(假设我们有一个具有 `price` 属性的 `Book` 实体):

.Get books with a given price
====
[source,java]
----
Criteria criteria = new Criteria("price").is(42.0);
Query query = new CriteriaQuery(criteria);
----
====

可以链接同一字段的条件,  这些条件将与逻辑 AND 相结合:

.Get books with a given price
====
[source,java]
----
Criteria criteria = new Criteria("price").greaterThan(42.0).lessThan(34.0L);
Query query = new CriteriaQuery(criteria);
----
====

当链接 `Criteria` 时,  默认情况下使用 AND 逻辑:

.Get all persons with first name _James_  and last name _Miller_:
====
[source,java]
----
Criteria criteria = new Criteria("lastname").is("Miller") <1>
  .and("firstname").is("James")                           <2>
Query query = new CriteriaQuery(criteria);
----
<1> 第一个 `Criteria`
<2> and() 创建一个新的 `Criteria` 并且将其链接到第一个.
====

如果要创建嵌套查询,  则需要为此使用子查询.  假设我们要查找 last name 为 _Miller_ 且 first name 为 _Jack_ 或 _John_ 的所有人:

.Nested subqueries
====
[source,java]
----
Criteria miller = new Criteria("lastName").is("Miller")  <.>
  .subCriteria(                                          <.>
    new Criteria().or("firstName").is("John")            <.>
      .or("firstName").is("Jack")                        <.>
  );
Query query = new CriteriaQuery(criteria);
----
<.> 为 last name 创建第一个 `Criteria`
<.> 这与 AND 合并为一个子条件
<.> This sub Criteria is an OR combination for the first name _John_
<.> and the first name Jack
====

请参阅 `Criteria` 类的 API 文档以获取有关各种可用操作的完整概述.

=== StringQuery

此类将 Elasticsearch 查询作为 JSON 字符串.
以下代码显示了一个查询,  该查询搜索 first name 为 "Jack" 的人:

====
[source,java]
----

Query query = new SearchQuery("{ \"match\": { \"firstname\": { \"query\": \"Jack\" } } } ");
SearchHits<Person> searchHits = operations.search(query, Person.class);

----
====

如果您已经有要使用的 Elasticsearch 查询,  则可以使用 `StringQuery`.

=== NativeSearchQuery

`NativeSearchQuery` 是当您有复杂查询或无法使用 `Criteria` API 表示的查询(例如,  在构建查询和使用聚合时)时使用的类.
它允许使用来自 Elasticsearch 库的所有不同的 `QueryBuilder` 实现,  因此命名为 "native"..

下面的代码显示了如何搜索具有给定名字的人,  并且找到的文档具有 terms 聚合,  这些 terms 对这些人的 lastnames 的出现次数进行了计数:

====
[source,java]
----
Query query = new NativeSearchQueryBuilder()
    .addAggregation(terms("lastnames").field("lastname").size(10)) //
    .withQuery(QueryBuilders.matchQuery("firstname", firstName))
    .build();

SearchHits<Person> searchHits = operations.search(query, Person.class);
----
====




