[[elasticsearch.repositories]]
= Elasticsearch Repositories

本章包括 Elasticsearch 存储库实现的详细信息.

. `Book` 实体
====
[source,java]
----
@Document(indexName="books")
class Book {
    @Id
    private String id;

    @Field(type = FieldType.text)
    private String name;

    @Field(type = FieldType.text)
    private String summary;

    @Field(type = FieldType.Integer)
    private Integer price;

	// getter/setter ...
}
----
====

include::elasticsearch-repository-queries.adoc[leveloffset=+1]

include::reactive-elasticsearch-repositories.adoc[leveloffset=+1]

[[elasticsearch.repositories.annotations]]
== repository 方法注解

=== @Highlight

`@Highlight` 注解定义了返回实体中那些字段需要高亮显示. 假如要在 `Book` 中将一些文本的 name 和 summary 高亮显示,可以使用一下存储库方法.

====
[source,java]
----
interface BookRepository extends Repository<Book, String> {

    @Highlight(fields = {
        @HighlightField(name = "name"),
        @HighlightField(name = "summary")
    })
    List<SearchHit<Book>> findByNameOrSummary(String text, String summary);
}
----
====

可以定义多个像上面那样高亮显示的字段,并且 `@Highlight` 和 `@HighlightField` 注解都可以通过 `@HighlightParameters` 注解进一步定制.查看 Javadocs 以获得可能的配置选项.

在搜索结果中,可以从 `SearchHit` 类中检索高亮显示的数据.

[[elasticsearch.annotation]]
== 基于注解的配置

Spring Data Elasticsearch repositories 可以通过 JavaConfig 使用注解来启用.

.Spring Data Elasticsearch repositories using JavaConfig
====
[source,java]
----
@Configuration
@EnableElasticsearchRepositories(                             <1>
  basePackages = "org.springframework.data.elasticsearch.repositories"
  )
static class Config {

  @Bean
  public ElasticsearchOperations elasticsearchTemplate() {    <2>
      // ...
  }
}

class ProductService {

  private ProductRepository repository;                       <3>

  public ProductService(ProductRepository repository) {
    this.repository = repository;
  }

  public Page<Product> findAvailableBookByName(String name, Pageable pageable) {
    return repository.findByAvailableTrueAndNameStartingWith(name, pageable);
  }
}
----

<1> `EnableElasticsearchRepositories` 启用 Repository 支持. 如果没有配置 base package, 它将使用放在上面的配置类之一.
<2> 使用 <<elasticsearch.operations>> 一章中显示的配置之一 提供一个名为 `elasticsearchTemplate` 的 `ElasticsearchOperations` bean
<3> 让 Spring 将 Repository bean 注入到您的类中.
====

[[elasticsearch.cdi]]
== Elasticsearch Repositories 使用 CDI

还可以使用 CDI 功能设置 Spring Data Elasticsearch 存储库.

.Spring Data Elasticsearch repositories using CDI
====
[source,java]
----
class ElasticsearchTemplateProducer {

  @Produces
  @ApplicationScoped
  public ElasticsearchOperations createElasticsearchTemplate() {
    // ...                               <1>
  }
}

class ProductService {

  private ProductRepository repository;  <2>
  public Page<Product> findAvailableBookByName(String name, Pageable pageable) {
    return repository.findByAvailableTrueAndNameStartingWith(name, pageable);
  }
  @Inject
  public void setRepository(ProductRepository repository) {
    this.repository = repository;
  }
}                
----
<1> 通过使用与 <<elasticsearch.operations>> 一章中相同的方式来创建组件.
<2> 让 CDI 框架将存储库注入到您的类中.
====

[[elasticsearch.namespace]]
== Spring 命名空间

Spring Data Elasticsearch 模块包含一个自定义命名空间,允许定义存储库 bean 以及用于实例化 `ElasticsearchServer` 的元素.

如 <<repositories.create-instances>> 中所述,使用 `repositories` 元素查找 Spring Data 存储库.

.Setting up Elasticsearch repositories using Namespace
====
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:elasticsearch="http://www.springframework.org/schema/data/elasticsearch"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       https://www.springframework.org/schema/beans/spring-beans-3.1.xsd
       http://www.springframework.org/schema/data/elasticsearch
       https://www.springframework.org/schema/data/elasticsearch/spring-elasticsearch-1.0.xsd">

  <elasticsearch:repositories base-package="com.acme.repositories" />

</beans>
----
====

使用 `Transport Client` 或 `Rest Client` 元素在上下文注册 `Elasticsearch Server` 实例.

.Transport Client using Namespace
====
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:elasticsearch="http://www.springframework.org/schema/data/elasticsearch"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       https://www.springframework.org/schema/beans/spring-beans-3.1.xsd
       http://www.springframework.org/schema/data/elasticsearch
       https://www.springframework.org/schema/data/elasticsearch/spring-elasticsearch-1.0.xsd">

  <elasticsearch:transport-client id="client" cluster-nodes="localhost:9300,someip:9300" />

</beans>
----
====

.Rest Client using Namespace
====
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:elasticsearch="http://www.springframework.org/schema/data/elasticsearch"
       xsi:schemaLocation="http://www.springframework.org/schema/data/elasticsearch
       https://www.springframework.org/schema/data/elasticsearch/spring-elasticsearch.xsd
       http://www.springframework.org/schema/beans
       https://www.springframework.org/schema/beans/spring-beans.xsd">

  <elasticsearch:rest-client id="restClient" hosts="http://localhost:9200">

</beans>
----
====
