[[elasticsearch.misc]]
= 其他 Elasticsearch 操作支持

本章涵盖了对不能通过 repository 接口直接访问的 Elasticsearch 操作的额外支持.建议将这些操作添加为自定义实现,如 <<repositories.custom-implementations>> 中所述.

[[elasticsearc.misc.index.settings]]
== 设置索引

当使用 Spring Data Elasticsearch 创建 Elasticsearch 索引时，可以使用 `@Setting` 注解定义不同的索引设置。
可以使用以下参数：

* `useServerConfiguration` does not send any settings parameters, so the Elasticsearch server configuration determines them.
* `settingPath` refers to a JSON file defining the settings that must be resolvable in the classpath
* `shards` the number of shards to use, defaults to _1_
* `replicas` the number of replicas, defaults to _1_
* `refreshIntervall`, defaults to _"1s"_
* `indexStoreType`, defaults to _"fs"_


也可以定义 https://www.elastic.co/guide/en/elasticsearch/reference/7.11/index-modules-index-sorting.html[索引排序]（查看链接的 Elasticsearch 文档以了解可能的字段 类型和值）：

====
[source,java]
----
@Document(indexName = "entities")
@Setting(
  sortFields = { "secondField", "firstField" },                                  <.>
  sortModes = { Setting.SortMode.max, Setting.SortMode.min },                    <.>
  sortOrders = { Setting.SortOrder.desc, Setting.SortOrder.asc },
  sortMissingValues = { Setting.SortMissing._last, Setting.SortMissing._first })
class Entity {
    @Nullable
    @Id private String id;

    @Nullable
    @Field(name = "first_field", type = FieldType.Keyword)
    private String firstField;

    @Nullable @Field(name = "second_field", type = FieldType.Keyword)
    private String secondField;

    // getter and setter...
}
----

<.> when defining sort fields, use the name of the Java property (_firstField_), not the name that might be defined for Elasticsearch (_first_field_)
<.> `sortModes`, `sortOrders` and `sortMissingValues` are optional, but if they are set, the number of entries must match the number of `sortFields` elements
====

[[elasticsearch.misc.mappings]]
== Index Mapping（索引映射）

当 Spring Data Elasticsearch 使用 `IndexOperations.createMapping()` 方法创建索引映射时，它会使用 <<elasticsearch.mapping.meta-model.annotations>> 中描述的注解，尤其是 `@Field` 注解。
除此之外，还可以将 `@Mapping` 注解添加到类中。 此注解具有以下属性：

* `mappingPath` a classpath resource in JSON format; if this is not empty it is used as the mapping, no other mapping processing is done.
* `enabled`  when set to false, this flag is written to the mapping and no further processing is done.
* `dateDetection` and `numericDetection` set the corresponding properties in the mapping when not set to `DEFAULT`.
* `dynamicDateFormats` when this String array is not empty, it defines the date formats used for automatic date detection.
* `runtimeFieldsPath` a classpath resource in JSON format containing the definition of runtime fields which is written to the index mappings, for example:

====
[source,json]
----
{
  "day_of_week": {
    "type": "keyword",
    "script": {
      "source": "emit(doc['@timestamp'].value.dayOfWeekEnum.getDisplayName(TextStyle.FULL, Locale.ROOT))"
    }
  }
}
----
====

[[elasticsearch.misc.filter]]
== Filter Builder

Filter Builder 提高查询速度.

====
[source,java]
----
private ElasticsearchOperations operations;

IndexCoordinates index = IndexCoordinates.of("sample-index");

SearchQuery searchQuery = new NativeSearchQueryBuilder()
  .withQuery(matchAllQuery())
  .withFilter(boolFilter().must(termFilter("id", documentId)))
  .build();
  
Page<SampleEntity> sampleEntities = operations.searchForPage(searchQuery, SampleEntity.class, index);
----
====

[[elasticsearch.scroll]]
== 对的数据量大的结果集使用 Scroll

Elasticsearch 有一个 scroll API,用于以块为单位获取较大的结果集. Spring Data Elasticsearch 在内部使用此方法来提供 `<T> SearchHitsIterator<T> SearchOperations.searchForStream(Query query, Class<T> clazz, IndexCoordinates index)` 方法的实现.

====
[source,java]
----
IndexCoordinates index = IndexCoordinates.of("sample-index");

SearchQuery searchQuery = new NativeSearchQueryBuilder()
  .withQuery(matchAllQuery())
  .withFields("message")
  .withPageable(PageRequest.of(0, 10))
  .build();

SearchHitsIterator<SampleEntity> stream = elasticsearchTemplate.searchForStream(searchQuery, SampleEntity.class, index);

List<SampleEntity> sampleEntities = new ArrayList<>();
while (stream.hasNext()) {
  sampleEntities.add(stream.next());
}

stream.close();
----
====

`SearchOperations` API 中没有方法访问 scroll ID,如果必须访问 scroll ID,则可以使用 `ElasticsearchRestTemplate` 的以下方法:

====
[source,java]
----

@Autowired ElasticsearchRestTemplate template;

IndexCoordinates index = IndexCoordinates.of("sample-index");

SearchQuery searchQuery = new NativeSearchQueryBuilder()
  .withQuery(matchAllQuery())
  .withFields("message")
  .withPageable(PageRequest.of(0, 10))
  .build();

SearchScrollHits<SampleEntity> scroll = template.searchScrollStart(1000, searchQuery, SampleEntity.class, index);

String scrollId = scroll.getScrollId();
List<SampleEntity> sampleEntities = new ArrayList<>();
while (scroll.hasSearchHits()) {
  sampleEntities.addAll(scroll.getSearchHits());
  scrollId = scroll.getScrollId();
  scroll = template.searchScrollContinue(scrollId, 1000, SampleEntity.class);
}
template.searchScrollClear(scrollId);
----
====

要将 Scroll API 与存储库方法一起使用,返回类型必须在 `Elasticsearch` 存储库中定义为 `Stream`. 然后,该方法的实现将使用 `ElasticsearchTemplate` 中的 scroll 方法.

====
[source,java]
----
interface SampleEntityRepository extends Repository<SampleEntity, String> {

    Stream<SampleEntity> findBy();

}
----
====

[[elasticsearch.misc.sorts]]
== Sort 选项

除了 <<repositories.paging-and-sorting>> 中描述的默认排序选项之外，Spring Data Elasticsearch 还提供了继承自 `org.springframework.data.domain.Sort.Order` 的类 `org.springframework.data.elasticsearch.core.query.Order` 。
它提供了在指定结果排序时可以发送到 Elasticsearch 的其他参数（请参阅 https://www.elastic.co/guide/en/elasticsearch/reference/7.15/sort-search-results.html）。

如果要搜索的类有 _location_ 的 `GeoPoint` 属性,则下面的 `Sort` 将按到指定点的距离对结果进行排序:

====
[source,java]
----
Sort.by(new GeoDistanceOrder("location", new GeoPoint(48.137154, 11.5761247)))
----
====

[[elasticsearch.misc.runtime-fields]]
== Runtime Fields

从 Elasticsearch 的 7.12 版本开始，添加了运行时字段的功能（https://www.elastic.co/guide/en/elasticsearch/reference/7.12/runtime.html）。
Spring Data Elasticsearch 通过两种方式支持这一点：

=== Runtime field definitions in the index mappings

定义 runtime 字段的第一种方法是将定义添加到索引映射中（请参阅 https://www.elastic.co/guide/en/elasticsearch/reference/7.12/runtime-mapping-fields.html）。
要在 Spring Data Elasticsearch 中使用这种方法，用户必须提供一个包含相应定义的 JSON 文件，例如：

.runtime-fields.json
====
[source,json]
----
{
  "day_of_week": {
    "type": "keyword",
    "script": {
      "source": "emit(doc['@timestamp'].value.dayOfWeekEnum.getDisplayName(TextStyle.FULL, Locale.ROOT))"
    }
  }
}
----
====

这个 JSON 文件的路径必须存在于类路径中，然后必须在实体的 `@Mapping` 注解中设置：:

====
[source,java]
----
@Document(indexName = "runtime-fields")
@Mapping(runtimeFieldsPath = "/runtime-fields.json")
public class RuntimeFieldEntity {
	// properties, getter, setter,...
}

----
====

=== 在查询上设置的 Runtime  字段定义

定义 runtime 字段的第二种方法是将定义添加到搜索查询中（请参阅 https://www.elastic.co/guide/en/elasticsearch/reference/7.12/runtime-search-request.html）。
以下代码示例显示了如何使用 Spring Data Elasticsearch 执行此操作：

使用的实体是一个具有  `price`  属性的简单对象：

====
[source,java]
----
@Document(indexName = "some_index_name")
public class SomethingToBuy {

	private @Id @Nullable String id;
	@Nullable @Field(type = FieldType.Text) private String description;
	@Nullable @Field(type = FieldType.Double) private Double price;

	// getter and setter
}

----
====

以下查询使用运行时字段，该字段通过将 19% 的价格添加到计算 `priceWithTax` 值，并在搜索查询中使用此值来查找 `priceWithTax` 高于或等于给定值的所有实体：

====
[source,java]
----
RuntimeField runtimeField = new RuntimeField("priceWithTax", "double", "emit(doc['price'].value * 1.19)");
Query query = new CriteriaQuery(new Criteria("priceWithTax").greaterThanEqual(16.5));
query.addRuntimeField(runtimeField);

SearchHits<SomethingToBuy> searchHits = operations.search(query, SomethingToBuy.class);
----
====

这适用于  `Query`  接口的每个实现。

[[elasticsearch.misc.jointype]]
== Join-Type 实现

Spring Data Elasticsearch 支持 https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html[Join data type],  用于创建相应的索引映射并存储相关信息.

=== 设置数据

对于具有父子关系的实体中,  它必须具有 `JoinField` 属性,  并且对其注解.
假设有一个 `Statement` 实体,  其中的语句可能是 _question_,   _answer_,  _comment_ 或 _vote_(在此示例中也显示了 _Builder_,  但这不是必需的,  但稍后将在示例代码中使用):

====
[source,java]
----
@Document(indexName = "statements")
public class Statement {
    @Id
    private String id;

    @Field(type = FieldType.Text)
    private String text;

    @JoinTypeRelations(
        relations =
            {
                @JoinTypeRelation(parent = "question", children = {"answer", "comment"}), <1>
                @JoinTypeRelation(parent = "answer", children = "vote")                   <2>
            }
    )
    private JoinField<String> relation;                                                   <3>

    private Statement() {
    }

    public static StatementBuilder builder() {
        return new StatementBuilder();
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public JoinField<String> getRelation() {
        return relation;
    }

    public void setRelation(JoinField<String> relation) {
        this.relation = relation;
    }

    public static final class StatementBuilder {
        private String id;
        private String text;
        private JoinField<String> relation;

        private StatementBuilder() {
        }

        public StatementBuilder withId(String id) {
            this.id = id;
            return this;
        }

        public StatementBuilder withText(String text) {
            this.text = text;
            return this;
        }

        public StatementBuilder withRelation(JoinField<String> relation) {
            this.relation = relation;
            return this;
        }

        public Statement build() {
            Statement statement = new Statement();
            statement.setId(id);
            statement.setText(text);
            statement.setRelation(relation);
            return statement;
        }
    }
}
----
<1> 一个 question 可以有 answers 和 comments
<2> 一个 answer 可以有 votes
<3> `JoinField` 属性用于将相关联的名称 (_question_, _answer_, _comment_ or _vote_) 和父 ID 组合在一起. 泛型类型必须与带注解的 `@Id` 属性相同.
====

Spring Data Elasticsearch 将为此类构建以下映射:

====
[source,json]
----
{
  "statements": {
    "mappings": {
      "properties": {
        "_class": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "relation": {
          "type": "join",
          "eager_global_ordinals": true,
          "relations": {
            "question": [
              "answer",
              "comment"
            ],
            "answer": "vote"
          }
        },
        "text": {
          "type": "text"
        }
      }
    }
  }
}
----
====

=== 存储数据

给定该类的存储库,  以下代码插入一个 question,  两个 answers,  一个 comment 和一个 vote:

====
[source,java]
----
void init() {
    repository.deleteAll();

    Statement savedWeather = repository.save(
        Statement.builder()
            .withText("How is the weather?")
            .withRelation(new JoinField<>("question"))                          <1>
            .build());

    Statement sunnyAnswer = repository.save(
        Statement.builder()
            .withText("sunny")
            .withRelation(new JoinField<>("answer", savedWeather.getId()))      <2>
            .build());

    repository.save(
        Statement.builder()
            .withText("rainy")
            .withRelation(new JoinField<>("answer", savedWeather.getId()))      <3>
            .build());

    repository.save(
        Statement.builder()
            .withText("I don't like the rain")
            .withRelation(new JoinField<>("comment", savedWeather.getId()))     <4>
            .build());

    repository.save(
        Statement.builder()
            .withText("+1 for the sun")
            .withRelation(new JoinField<>("vote", sunnyAnswer.getId()))         <5>
            .build());
}
----
<1> create a question statement
<2> the first answer to the question
<3> the second answer
<4> a comment to the question
<5> a vote for the first answer
====

=== 检索数据

当前必须使用本地搜索查询来查询数据,  因此标准存储库方法不提供支持.  可以使用<<repositories.custom-implementations>> 代替.

下面的代码示例展示了如何使用 `ElasticsearchOperations` 实例检索所有具有 _vote_ (必须为 _answers_,  因为只有 answers 才可以 vote) 的所有条目:

====
[source,java]
----
SearchHits<Statement> hasVotes() {
    NativeSearchQuery query = new NativeSearchQueryBuilder()
        .withQuery(hasChildQuery("vote", matchAllQuery(), ScoreMode.None))
        .build();

    return operations.search(query, Statement.class);
}
----
====


