[[elasticsearch.reactive.operations]]
= Reactive Elasticsearch 操作

`ReactiveElasticsearchOperations` 是使用 `ReactiveElasticsearchClient` 对 Elasticsearch 集群执行高级命令的网关..

`ReactiveElasticsearchTemplate` 是 `ReactiveElasticsearchOperations` 的默认实现.

[[elasticsearch.reactive.template]]
== Reactive Elasticsearch Template

在使用 `ReactiveElasticsearchTemplate` 之前,需要先了解要使用的实际客户端,有关客户端的详细信息,请参见  <<elasticsearch.clients.reactive>> .

[[elasticsearch.reactive.template.configuration]]
=== Reactive Template 配置

配置 `ReactiveElasticsearchTemplate` 最简单的方法就是通过 `AbstractReactiveElasticsearchConfiguration` 提供的
配置方法配置 `base package`, `initial entity set` 等.

.The AbstractReactiveElasticsearchConfiguration
====
[source,java]
----
@Configuration
public class Config extends AbstractReactiveElasticsearchConfiguration {

  @Bean <1>
  @Override
  public ReactiveElasticsearchClient reactiveElasticsearchClient() {
      // ...
  }
}
----
<1> 配置要使用的客户端. 这可以由 `ReactiveRestClients` 或直接通过 `DefaultReactiveElasticsearchClient` 完成.
====

NOTE: 如果要适用默认的`HttpHeaders` ,可以通过  `ReactiveElasticsearchClient` 的 `ClientConfiguration` 设置. 请参考 <<elasticsearch.clients.configuration>>.

TIP: 如果需要配置 `ReactiveElasticsearchTemplate` 默认的 `RefreshPolicy` 和 `IndicesOptions` ,可以通过覆盖 `refreshPolicy()` 和 `indicesOptions()` 方法设置.

但是,可能需要更多地控制实际组件,并使用更详细的方法.

.Configure the ReactiveElasticsearchTemplate
====
[source,java]
----
@Configuration
public class Config {

  @Bean <1>
  public ReactiveElasticsearchClient reactiveElasticsearchClient() {
    // ...
  }
  @Bean <2>
  public ElasticsearchConverter elasticsearchConverter() {
    return new MappingElasticsearchConverter(elasticsearchMappingContext());
  }
  @Bean <3>
  public SimpleElasticsearchMappingContext elasticsearchMappingContext() {
    return new SimpleElasticsearchMappingContext();
  }
  @Bean <4>
  public ReactiveElasticsearchOperations reactiveElasticsearchOperations() {
    return new ReactiveElasticsearchTemplate(reactiveElasticsearchClient(), elasticsearchConverter());
  }
}
----
<1> 配置要使用的客户端. 这可以由 `ReactiveRestClients` 或直接通过 `DefaultReactiveElasticsearchClient` 完成.
<2> 使用映射上下文提供的元数据设置来提供 doamin 类型映射的 `ElasticsearchConverter`.
<3> 特定于 Elasticsearch 的 domain 类型元数据映射上下文.
<4> 基于 client 和 conversion 结构的真实 template.
====

[[elasticsearch.reactive.template.usage]]
=== Reactive Template 使用

`ReactiveElasticsearchTemplate` 使您可以保存,查找和删除 domain 对象,并将这些对象映射到存储在 Elasticsearch 中的文档..

如下:

.Use the ReactiveElasticsearchTemplate
====
[source,java]
----
@Document(indexName = "marvel")
public class Person {

  private @Id String id;
  private String name;
  private int age;
  // Getter/Setter omitted...
}
----

[source,java]
----
template.save(new Person("Bruce Banner", 42))                    <1>
  .doOnNext(System.out::println)
  .flatMap(person -> template.findById(person.id, Person.class)) <2>
  .doOnNext(System.out::println)
  .flatMap(person -> template.delete(person))                    <3>
  .doOnNext(System.out::println)
  .flatMap(id -> template.count(Person.class))                   <4>
  .doOnNext(System.out::println)
  .subscribe(); <5>
----

上面的输出如下.

[source,text]
----
> Person(id=QjWCWWcBXiLAnp77ksfR, name=Bruce Banner, age=42)
> Person(id=QjWCWWcBXiLAnp77ksfR, name=Bruce Banner, age=42)
> QjWCWWcBXiLAnp77ksfR
> 0
----
<1> 将一个新的 `Person` 文档插入到 _marvel_ 索引下,类型为字符串. `id` 由服务端自动生成并返回实例.
<2> 在  _marvel_  索引中查找匹配 `id` 的 `Person`.
<3> 在  _marvel_  索引中删除匹配 `id` 的 `Person`.
<4> 计算 _marvel_ 索引下的文档总数.
<5> 不要忘记了 _subscribe()_.
====


