[[health]]
= Health (`health`)
`health` 端点提供有关应用程序的运行状况的详细信息.



[[health.retrieving]]
== 检索应用程序的运行状况
要检索应用程序的运行状况, 请向 `/actuator/health` 发出 `GET` 请求, 如以下基于 curl 的示例所示:

include::snippets/health/curl-request.adoc[]

产生的响应类似于以下内容:

include::snippets/health/http-response.adoc[]



[[health.retrieving.response-structure]]
=== 响应结构
该响应包含应用程序运行状况的详细信息. 下表描述了响应的结构:

[cols="2,1,3"]
include::snippets/health/response-fields.adoc[]

NOTE: 上面的响应字段适用于 V3 API. 如果您需要返回 V2 JSON, 则应使用 `accept` 头或 `application/vnd.spring-boot.actuator.v2+json`

[[health.retrieving-component]]
== 检索组件的运行状况
要检索应用程序运行状况的特定组件的运行状况, 请向 `/actuator/health/\{component}` 发出 `GET` 请求, 如以下基于 curl 的示例所示:

include::snippets/health/component/curl-request.adoc[]

产生的响应类似于以下内容:

include::snippets/health/component/http-response.adoc[]



[[health.retrieving-component.response-structure]]
=== 响应结构
该响应包含应用程序中特定组件的运行状况的详细信息. 下表描述了响应的结构:

[cols="2,1,3"]
include::snippets/health/component/response-fields.adoc[]



[[health.retrieving-component-nested]]
== 检索嵌套组件的运行状况
如果特定组件包含其他嵌套组件(如上例中的 `broker` 指标), 则可以通过向 `/actuator/health/\{component}/\{subcomponent}` 发出 `GET` 请求来检索此类嵌套组件的运行状况, 以下基于 curl 的示例所示:

include::snippets/health/instance/curl-request.adoc[]

产生的响应类似于以下内容:

include::snippets/health/instance/http-response.adoc[]

应用程序运行状况的组件可以任意深度嵌套, 具体取决于应用程序的运行状况指示器及其分组方式. 运行状况端点支持 `/\{component}` URL中的任意数量的标识符, 以允许检索任何深度的组件的运行状况.

[[health.retrieving-component-nested.response-structure]]
=== 响应结构
该响应包含应用程序特定组件实例的运行状况的详细信息. 下表描述了响应的结构:

[cols="2,1,3"]
include::snippets/health/instance/response-fields.adoc[]
