= Spring GraphQL 参考文档
Brian Clozel; Andreas Marek; Rossen Stoyanchev; Mark Paluch
include::attributes.adoc[]

本文档包含 https://docs.jcohy.com/docs/spring-graphql/{spring-graphql-version}/pdf/zh-cn/index.pdf[一个 PDF].

[[overview]]
== 概述

Spring for GraphQL 为构建在 https://www.graphql-java.com/[GraphQL Java] 上的 Spring 应用程序提供支持。 这是两个团队的联合协作。 我们的共同理念是摈弃固执己见，更多地集中于提供全面而广泛的支持。

Spring for GraphQL 是 GraphQL Java 团队的 https://github.com/graphql-java/graphql-java-spring[GraphQL Java Spring] 项目的继承者。
它旨在成为所有 Spring、GraphQL 应用程序的基础。

该项目目前正处于 1.0 版本的里程碑阶段，正在寻求反馈。 请使用我们的 https://github.com/spring-projects/spring-graphql/issues[issue tracker] 报告问题、讨论设计问题或请求功能。

要开始，请查看 https://start.spring.io 上的 Spring GraphQL starter 和 <<samples>> 部分。

[[requirements]]
== 要求

Spring for GraphQL 有以下要求:

* JDK8
* Spring Framework 5.3
* GraphQL Java 18
* QueryDSL 或 Query by Example 需要 Spring Data 2021.1.0 或更高版本

[[server-transports]]
== 服务器传输

Spring for GraphQL 支持服务器通过 HTTP、WebSocket 和 RSocket 处理 GraphQL 请求。


[[server-http]]
=== HTTP

GraphQlHttpHandler 处理 GraphQL HTTP 请求，并将并委托给 <<server-interception>>  链执行。 有两种形式，一种用于 Spring MVC，一种用于 Spring WebFlux。
两者都异步处理请求并具有相同的功能，区别是使用阻塞和非阻塞 I/O 来编写 HTTP 响应。

请求必须使用 HTTP POST，并将 GraphQL 请求的详细信息作为 JSON 包含在请求 body 中，如提议的 https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md[GraphQL over HTTP] 规范中所定义。
解码 JSON body 成功后，HTTP 响应状态始终为 200（正常），GraphQL 请求执行中的任何错误都会出现在 GraphQL 响应的 "errors" 部分。
媒体类型默认和首选都是 `"application/graphql+json"` ，但也支持 `"application/json"`，如规范中所述。

`GraphQlHttpHandler` 可以通过声明 `RouterFunction` bean 并使用 Spring MVC 或 WebFlux 的 `RouterFunctions` 创建路由来公开 HTTP 端点。
Boot starter 执行此操作，请参阅 {spring-boot-ref-docs}/web.html#web.graphql.web-endpoints[Web Endpoints] 部分了解详细信息，或检查它包含的 `GraphQlWebMvcAutoConfiguration` 或 `GraphQlWebFluxAutoConfiguration` 以获取实际配置。

Spring for GraphQL 存储库包含一个 Spring MVC {github-main-branch}/samples/webmvc-http[HTTP sample] 应用程序。

[[server-websocket]]
=== WebSocket

`GraphQlWebSocketHandler` 基于 https://github.com/enisdenjo/graphql-ws[graphql-ws] 库中定义的 https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md[协议]  处理 GraphQL WebSocket 请求。
在 WebSocket 上使用 GraphQL 的主要原因是订阅允许发送 GraphQL 响应流，但它也可以用于具有单个响应的常规查询。 处理程序将每个请求委托给  <<server-interception>>  链以进一步执行请求。

[TIP]
.基于 WebSocket 协议的 GraphQL
====

有两种这样的协议，一种在 https://github.com/apollographql/subscriptions-transport-ws[subscriptions-transport-ws] 库中，
另一种在 https://github.com/enisdenjo/graphql-ws[graphql-ws] 库中。 前者不活跃，由后者接替。
阅读 https://the-guild.dev/blog/graphql-over-websockets[这篇博文] 了解历史。
====

GraphQlWebSocketHandler 有两种形式，一种用于 Spring MVC，一种用于 Spring WebFlux。 两者都异步处理请求并具有相同的功能。 WebFlux 处理程序还使用非阻塞 I/O 和背压来流式传输消息，这很好用，因为在 GraphQL Java 中订阅响应是 Reactive Streams `Publisher`。

`graphql-ws` 项目列出了许多供客户端使用的 https://github.com/enisdenjo/graphql-ws#recipes[方法]。

`GraphQlWebSocketHandler` 可以通过声明 `SimpleUrlHandlerMapping` bean ,将处理程序映射到 URL 路径来公开 {spring-boot-ref-docs}/web.html#web.graphql.web-endpoints[Web Endpoints]。
Boot starter 具有启用此功能的选项，请参阅 Web 端点部分了解详细信息，或检查它包含的 `GraphQlWebMvcAutoConfiguration` 或 `GraphQlWebFluxAutoConfiguration` 以获取实际配置。

Spring for GraphQL 存储库包含一个 WebFlux {github-main-branch}/samples/webflux-websocket[WebSocket sample]  应用程序。

[[server-rsocket]]
=== RSocket

`GraphQlRSocketHandler` 通过 RSocket 处理 GraphQL 请求。 查询和 mutations 可能会作为 RSocket `request-response` 交互处理，而订阅作为 `request-stream` 处理。

`GraphQlRSocketHandler` 可以用作来自映射到 GraphQL 请求路由的 `@Controller` 的委托。 例如：

[source,java,indent=0,subs="verbatim,quotes"]
----
@Controller
public class GraphQlRSocketController {

	 private final GraphQlRSocketHandler handler;

	 GraphQlRSocketController(GraphQlRSocketHandler handler) {
			this.handler = handler;
	 }

	 @MessageMapping("graphql")
	 public Mono<Map<String, Object>> handle(Map<String, Object> payload) {
			return this.handler.handle(payload);
	 }

	 @MessageMapping("graphql")
	 public Flux<Map<String, Object>> handleSubscription(Map<String, Object> payload) {
			return this.handler.handleSubscription(payload);
	 }
}
----

[[server-interception]]
=== 拦截器

Spring MVC 和 Spring WebFlux 传输处理程序，用于 <<server-http>> 和 <<server-websocket>>，都委托给同一个 `WebGraphQlInterceptor` 链，然后是调用 GraphQL Java 引擎的 `ExecutionGraphQlService`。
您可以使用它来拦截通过任何 Web 传输的 GraphQL 请求。

`WebGraphQlInterceptor` 暴露了底层传输（HTTP 或 WebSocket 握手）请求的详细信息，并允许自定义为 GraphQL Java 准备的 `graphql.ExecutionInput`。 例如，要提取 HTTP 头并通过 `GraphQLContext` 将其提供给数据获取器：

[source,java,indent=0,subs="verbatim,quotes"]
----
class HeaderInterceptor implements WebGraphQlInterceptor {

	@Override
	public Mono<WebGraphQlResponse> intercept(WebGraphQlRequest request, Chain chain) {
		List<String> headerValue = request.getHeaders().get("myHeader");
		request.configureExecutionInput((executionInput, builder) ->
				builder.graphQLContext(Collections.singletonMap("myHeader", headerValue)).build());
		return chain.next(request);
	}
}
----

然后 `DataFetcher` 可以访问这个值，例如 <<controllers,带注解的控制器>> 方法：

[source,java,indent=0,subs="verbatim,quotes"]
----
@Controller
class MyController {

	@QueryMapping
	Person person(@ContextValue String myHeader) {
			// ...
	}
}
----

拦截器还可以自定义 HTTP 响应头，或者检查 和/或 转换来自 GraphQL Java 的 `graphql.ExecutionResult`：

[source,java,indent=0,subs="verbatim,quotes"]
----
class MyInterceptor implements WebGraphQlInterceptor {

	@Override
	public Mono<WebGraphQlResponse> intercept(WebGraphQlRequest request, Chain chain) {
		return chain.next(request)
				.map(response -> {
					Object data = response.getData();
					Object updatedData = ... ;
					return response.transform(builder -> builder.data(updatedData));
				});
	}
}
----

`WebGraphQlHandler` 有一个 builder 来创建 `WebGraphInterceptor` 链。 Boot starter 使用它，请参阅 Boot 的 {spring-boot-ref-docs}/web.html#web.graphql.web-endpoints[Web Endpoints] 部分。

<<server-rsocket>> 传输处理程序委托给类似的 `GraphQlInterceptor` 链，您可以使用它来拦截 RSocket 请求上的 GraphQL。

[[execution]]
== 执行请求

`ExecutionGraphQlService` 调用 GraphQL Java 来执行请求，是 Spring 核心抽象。 底层传输（例如 <<server-transports>>）委托给 `ExecutionGraphQlService` 来处理请求。

主要实现是 `DefaultExecutionGraphQlService` ，其有一个 `GraphQlSource` 配置，可以访问要调用的 `graphql.GraphQL` 实例。

[[execution-graphqlsource]]
=== `GraphQLSource`

`GraphQlSource` 是一个 Spring 核心抽象，用于访问 `graphql.GraphQL` 实例，用于请求执行。 它提供了一个 builder  API 来初始化 GraphQL Java 并构建一个 `GraphQlSource`。

默认的 `GraphQlSource` builder 可通过 `GraphQlSource.schemaResourceBuilder()` 访问，支持  <<execution-reactive-datafetcher>>, <<execution-context>>  和 <<execution-exceptions>>。

Spring Boot {spring-boot-ref-docs}/web.html#web.graphql[starter] 通过默认的 `GraphQlSource.Builder` 初始化一个 `GraphQlSource` 实例，并启用以下功能：

- 从配置的位置加载 <<execution-graphqlsource-schema-resources, schema files>>.
- 公开适用于 {spring-boot-ref-docs}/application-properties.html#appendix.application-properties.web[properties] `GraphQlSource.Builder` 的属性。
- 检测 <<execution-graphqlsource-runtimewiring-configurer>> beans.
- 检测 {spring-boot-ref-docs}/actuator.html#actuator.metrics.supported.spring-graphql[GraphQL 指标] 的 https://www.graphql-java.com/documentation/instrumentation[Instrumentation] beans .
- 检测  <<execution-exceptions, 解决异常>>的 `DataFetcherExceptionResolver` beans .

为了进一步自定义，您可以声明自己的 `GraphQlSourceBuilderCustomizer` beans； 例如，配置您自己的 `ExecutionIdProvider`

[source,java,indent=0,subs="verbatim,quotes"]
----
@Configuration(proxyBeanMethods = false)
class GraphQlConfig {

	@Bean
	public GraphQlSourceBuilderCustomizer sourceBuilderCustomizer() {
		return (builder) ->
				builder.configureGraphQl(graphQlBuilder ->
						graphQlBuilder.executionIdProvider(new CustomExecutionIdProvider()));
	}
}
----

[[execution-graphqlsource-schema-resources]]
==== Schema 资源

`GraphQlSource.Builder` 可以配置一个或多个要解析并合并在一起的 `Resource` 实例。 这意味着 schema 文件几乎可以从任何位置加载。

默认情况下，Spring Boot starter 从众所周知的类路径位置 {spring-boot-ref-docs}/web.html#web.graphql.schema[查找 schema files]，但您可以通过 `FileSystemResource` 将其更改为文件系统上的某个位置，通过 `ByteArrayResource` 更改为字节内容，或者实现一个自定义资源，从远程位置或存储。

[[execution-graphqlsource-schema-creation]]
==== 创建 Schema

默认情况下，`GraphQlSource.Builder` 使用 GraphQL Java `GraphQLSchemaGenerator` 来创建 `graphql.schema.GraphQLSchema`。 这适用于大多数应用程序，但如有必要，您可以通过 builder 创建 schema：

[source,java,indent=0,subs="verbatim,quotes"]
----
GraphQlSource.Builder builder = ...

builder.schemaResources(..)
		.configureRuntimeWiring(..)
		.schemaFactory((typeDefinitionRegistry, runtimeWiring) -> {
			// create GraphQLSchema
		})
----

这样做的主要原因是通过 federation 库创建 schema。

<<execution-graphqlsource, GraphQlSource 章节>> 解释了如何使用 Spring Boot 配置它。

[[execution-graphqlsource-runtimewiring-configurer]]
==== `RuntimeWiringConfigurer`

你可以使用 `RuntimeWiringConfigurer` 注册:

 - 自定义 scalar 类型.
 - 指令处理代码。
 - `TypeResolver`，如果您需要覆盖类型的 <<execution-graphqlsource-default-type-resolver>> 。
 - 字段的 `DataFetcher`，尽管大多数应用程序将简单地配置 `AnnotatedControllerConfigurer`，它检测带注解的 `DataFetcher` 处理程序方法。 Spring Boot starter 默认添加 `AnnotatedControllerConfigurer`。

NOTE: 与 Web 框架不同，GraphQL 不使用 Jackson 注解来驱动 JSON 序列化/反序列化。 自定义数据类型及其序列化 https://www.graphql-java.com/documentation/scalars/[必须描述为 Scalars] 。

Spring Boot starter 检测类型为 `RuntimeWiringConfigurer` 的 bean，并将它们注册到 `GraphQlSource.Builder` 中。 这意味着在大多数情况下，您的配置中会有类似以下的内容：

[source,java,indent=0,subs="verbatim,quotes"]
----
@Configuration
public class GraphQlConfig {

	@Bean
	public RuntimeWiringConfigurer runtimeWiringConfigurer(BookRepository repository) {

		GraphQLScalarType scalarType = ... ;
		SchemaDirectiveWiring directiveWiring = ... ;
		DataFetcher dataFetcher = QuerydslDataFetcher.builder(repository).single();

		return wiringBuilder -> wiringBuilder
				.scalar(scalarType)
				.directiveWiring(directiveWiring)
				.type("Query", builder -> builder.dataFetcher("book", dataFetcher));
	}
}
----

如果您需要添加 `WiringFactory`，例如，要进行定义 schema 的注册，请实现接收 `RuntimeWiring.Builder` 和输出 `List<WiringFactory>` 的替代配置方法。
这允许您添加任意数量的工厂，然后按顺序调用这些工厂。

[[execution-graphqlsource-default-type-resolver]]
==== 默认 `TypeResolver`

`GraphQlSource.Builder` 将 `ClassNameTypeResolver` 注册为默认的 `TypeResolver`，并与于尚未通过  <<execution-graphqlsource-runtimewiring-configurer>> 注册的 GraphQL 接口和联合。
GraphQL Java 中 `TypeResolver` 的目的是为 GraphQL 接口或联合字段的 `DataFetcher` 返回确定 GraphQL 对象类型的值。

`ClassNameTypeResolver` 尝试将值的简单类名与 GraphQL 对象类型匹配，如果不成功，它还会寻找其超类（包括基类和接口）以寻找匹配项。 `ClassNameTypeResolver` 提供了一个选项来配置提取名称功能以及类到 GraphQL 对象类型名称的映射，这应该有助于涵盖更多的极端情况：

[source,java,indent=0,subs="verbatim,quotes"]
----
GraphQlSource.Builder builder = ...
ClassNameTypeResolver classNameTypeResolver = new ClassNameTypeResolver();
classNameTypeResolver.setClassNameExtractor((klass) -> {
	// Implement Custom ClassName Extractor here
});
builder.defaultTypeResolver(classNameTypeResolver);
----

<<execution-graphqlsource, GraphQlSource 章节>> 解释了如何使用 Spring Boot 配置它。

[[execution-graphqlsource-operation-caching]]
==== 缓存操作

GraphQL Java 必须在执行之前解析和验证操作。 这可能会显着影响性能。 为了避免重新解析和验证，应用程序可以配置一个 `PreparsedDocumentProvider` 来缓存和重用 `Document` 实例。
{graphql-java-docs}/execution/#query-caching[GraphQL Java docs] 提供了有关通过 `PreparsedDocumentProvider` 进行查询缓存的更多详细信息。

在 Spring GraphQL 中，您可以通过 `GraphQlSource.Builder#configureGraphQl` 注册 `PreparsedDocumentProvider`:

[source,java,indent=0,subs="verbatim,quotes"]
----
// Typically, accessed through Spring Boot's GraphQlSourceBuilderCustomizer
GraphQlSource.Builder builder = ...

// Create provider
PreparsedDocumentProvider provider = ...

builder.schemaResources(..)
		.configureRuntimeWiring(..)
		.configureGraphQl(graphQLBuilder -> graphQLBuilder.preparsedDocumentProvider(provider))
----

<<execution-graphqlsource, GraphQlSource 章节>> 解释了如何使用 Spring Boot 配置它。

[[execution-graphqlsource-directives]]
==== 指令

GraphQL 语言支持 "描述 GraphQL 文档中的备用运行时执行和类型验证行为" 的指令。 指令类似于 Java 中的注解，但在 GraphQL 文档中声明类型、字段、片段和操作。

GraphQL Java 提供了 `SchemaDirectiveWiring` 契约来帮助应用程序检测和处理指令。 有关详细信息，请参阅 GraphQL Java 文档中的 {graphql-java-docs}/sdl-directives/[Schema Directives] 。

在 Spring GraphQL 中，您可以通过 <<execution-graphqlsource-runtimewiring-configurer>> 注册 `SchemaDirectiveWiring`。 Spring Boot starter 检测到这样的 beans，所以你可能有类似的东西：

[source,java,indent=0,subs="verbatim,quotes"]
----
@Configuration
public class GraphQlConfig {

	 @Bean
	 public RuntimeWiringConfigurer runtimeWiringConfigurer() {
		  return builder -> builder.directiveWiring(new MySchemaDirectiveWiring());
	 }

}
----

TIP: 有关指令支持的示例，请查看 https://github.com/graphql-java/graphql-java-extended-validation[Extended Validation for Graphql Java] library。

[[execution-reactive-datafetcher]]
=== Reactive `DataFetcher`

默认的 `GraphQlSource` builder 支持 `DataFetcher` 返回 `Mono` 或 `Flux`，使它们适应 `CompletableFuture`，其中 `Flux` 值被聚合并转换为 `List`，除非请求是 GraphQL 订阅请求，在这种情况下，返回值仍然是 Reactive Streams 用于流式传输 GraphQL 响应的 `Publisher`。

响应式 `DataFetcher` 可以依赖于对从传输层传播的 Reactor 上下文的访问，例如从 WebFlux 请求处理，请参阅 <<execution-context-webflux, WebFlux Context>>。

[[execution-context]]
=== Context Propagation(上下文传播)

Spring for GraphQL 透明地支持通过 GraphQL Java 传播上下文从 <<server-transports>> 传输，并传播到 `DataFetcher` 和它调用的其他组件。 这包括来自 Spring MVC 请求处理线程的 `ThreadLocal` 上下文和来自 WebFlux 处理管道的 Reactor `Context`。

[[execution-context-webmvc]]
==== WebMvc

GraphQL Java 调用的 `DataFetcher` 和其他组件可能并不总是在与 Spring MVC 处理程序在相同的线程上执行，例如，如果异步 <<server-interception, `WebGraphQlInterceptor`>> 或 `DataFetcher` 可能在不同的线程。

Spring for GraphQL 支持将 `ThreadLocal` 值从 Servlet 容器线程传播到 `DataFetcher` 线程，由 GraphQL Java 调用在其上执行的其他组件。 为此，应用程序需要创建一个 `ThreadLocalAccessor` 来提取感兴趣的 `ThreadLocal` 值：

[source,java,indent=0,subs="verbatim,quotes"]
----
public class RequestAttributesAccessor implements ThreadLocalAccessor {

	private static final String KEY = RequestAttributesAccessor.class.getName();

	@Override
	public void extractValues(Map<String, Object> container) {
		container.put(KEY, RequestContextHolder.getRequestAttributes());
	}

	@Override
	public void restoreValues(Map<String, Object> values) {
		if (values.containsKey(KEY)) {
			RequestContextHolder.setRequestAttributes((RequestAttributes) values.get(KEY));
		}
	}

	@Override
	public void resetValues(Map<String, Object> values) {
		RequestContextHolder.resetRequestAttributes();
	}

}
----

可以在 `WebGraphHandler` builder 中注册 `ThreadLocalAccessor`。 Boot starter 检测这种类型的 beans 并自动为 Spring MVC 应用程序注册它们，请参阅 {spring-boot-ref-docs}/web.html#web.graphql.web-endpoints[Web Endpoints] 章节。

[[execution-context-webflux]]
==== WebFlux

<<execution-reactive-datafetcher>> 可以依赖于对源自 WebFlux 请求处理链的 Reactor 上下文的访问。 这包括由 <<server-interception, WebGraphQlInterceptor>> 组件添加的 Reactor 上下文。

[[execution-exceptions]]
=== 异常解决

GraphQL Java 应用程序可以注册一个 `DataFetcherExceptionHandler` 来决定如何在 GraphQL 响应的 "errors" 部分中表示来自数据层的异常。

Spring for GraphQL 有一个内置的 `DataFetcherExceptionHandler`，由默认的 <<execution-graphqlsource>> builder 使用。 它允许应用程序注册一个或多个按顺序调用的 Spring `DataFetcherExceptionResolver` 组件，
直到将异常解析为 `graphql.GraphQLError` 对象列表（可能为空）。

`DataFetcherExceptionResolver` 是一个异步合约。 对于大多数实现，扩展 `DataFetcherExceptionResolverAdapter` 并覆盖其同步解决异常的 `resolveToSingleError` 或 `resolveToMultipleErrors` 方法之一就足够了。

可以通过 `graphql.ErrorClassification` 将 `GraphQLError` 分配给分类。 在 Spring GraphQL 中，您还可以通过 `ErrorType` 进行分配，它具有以下常见分类，应用程序可以使用这些分类来对错误进行分类：

- `BAD_REQUEST`
- `UNAUTHORIZED`
- `FORBIDDEN`
- `NOT_FOUND`
- `INTERNAL_ERROR`

如果异常仍未解决，默认情况下它被归类为 `INTERNAL_ERROR`，并带有一条通用消息，其中包括来自 `DataFetchingEnvironment` 的类别名称和 `executionId`。 该消息是有意不透明的，以避免泄漏实现细节。
应用程序可以使用 `DataFetcherExceptionResolver` 来自定义错误详细信息。

未解决的异常与 `executionId` 一起记录在 `ERROR` 级别，以与发送给客户端的错误相关联。 已解决的异常记录在 `DEBUG` 级别。

[[execution-batching]]
=== Batch Loading

给定一本书及其作者，我们可以为一本书创建一个 `DataFetcher`，为其作者创建另一个 `DataFetcher`。 这允许选择有或没有作者的书，但这意味着书和作者不会一起加载，这在查询多本书时效率特别低，因为每本书的作者都是单独加载的。 这被称为 `N+1` 选择问题。

[[execution-batching-dataloader]]
==== `DataLoader`

GraphQL Java 提供了 `DataLoader` 机制，用于批量加载相关实体。 您可以在 {graphql-java-docs}/batching/[GraphQL Java docs] 中找到完整的详细信息。 以下是其工作原理的摘要：

 1. 在给定唯一键的情况下，可以在加载实体的 `DataLoaderRegistry` 中注册 `DataLoader`。
 2. `DataFetcher` 可以访问 `DataLoader` 并可以按 `ID` 加载实体。
 3. `DataLoader` 通过返回 `future` 来延迟加载，因此可以批量完成。
 4. `DataLoader` 维护加载实体的每个请求缓存，可以进一步提高效率。

[[execution-batching-batch-loader-registry]]
==== `BatchLoaderRegistry`

GraphQL Java 中完整的批处理加载机制需要实现几个 `BatchLoader` 接口之一，然后将它们包装并注册为 `DataLoader`，并在 `DataLoaderRegistry` 中使用一个名称。

Spring GraphQL 中的 API 略有不同。 对于注册，只有一个中央 `BatchLoaderRegistry` 公开工厂方法和一个 builder 来创建和注册任意数量的批加载函数：

[source,java,indent=0,subs="verbatim,quotes"]
----
@Configuration
public class MyConfig {

	public MyConfig(BatchLoaderRegistry registry) {

		registry.forTypePair(Long.class, Author.class).registerMappedBatchLoader((authorIds, env) -> {
				// return Mono<Map<Long, Author>
		});

		// more registrations ...
	}

}
----

Spring Boot starter 声明了一个 `BatchLoaderRegistry` bean，您可以将其注入到您的配置中，如上所示，或者注入到任何组件（例如控制器）中，以便注册批量加载功能。 反过来，`BatchLoaderRegistry` 被注入到 `DefaultExecutionGraphQlService` 中，
它确保每个请求的 `DataLoader` 注册。

默认情况下，`DataLoader` 名称基于目标实体的类名。 这允许 `@SchemaMapping` 方法声明具有通用类型的 <<controllers-schema-mapping-data-loader,DataLoader 参数>>，而无需指定名称。
但是，如果需要，可以通过 `BatchLoaderRegistry` builder 以及其他 `DataLoader` 选项自定义名称。

对于很多情况，在加载相关实体时，可以使用 `@BatchMapping` 控制器方法，这是一种快捷方式，可以替代直接使用 `BatchLoaderRegistry` 和 `DataLoader` 的需要。 `BatchLoaderRegistry` 还提供了其他重要的好处。
它支持从批量加载函数和 `@BatchMapping` 方法访问相同的 `GraphQLContext`，并确保对它们的 <<execution-context>>。 这就是应用程序应该使用它的原因。 可以直接执行您自己的 `DataLoader` 注册，但注册此类会放弃上述好处。

[[execution-batching-testing]]
==== 测试 Batch Loading

首先让 `BatchLoaderRegistry` 在 `DataLoaderRegistry` 上执行注册：

[source,java,indent=0,subs="verbatim,quotes"]
----
BatchLoaderRegistry batchLoaderRegistry = new DefaultBatchLoaderRegistry();
// perform registrations...

DataLoaderRegistry dataLoaderRegistry = DataLoaderRegistry.newRegistry().build();
batchLoaderRegistry.registerDataLoaders(dataLoaderRegistry, graphQLContext);
----

现在您可以按如下方式访问和测试各个 `DataLoader`：

[source,java,indent=0,subs="verbatim,quotes"]
----
DataLoader<Long, Book> loader = dataLoaderRegistry.getDataLoader(Book.class.getName());
loader.load(1L);
loader.loadMany(Arrays.asList(2L, 3L));
List<Book> books = loader.dispatchAndJoin(); // actual loading

assertThat(books).hasSize(3);
assertThat(books.get(0).getName()).isEqualTo("...");
// ...
----

[[data]]
== Data 集成

Spring for GraphQL 让您可以利用现有的 Spring 技术，遵循常见的编程模型，通过 GraphQL 公开底层数据源。

本节讨论 Spring Data 的集成层，它提供了一种将 Querydsl 或 Query by Example 存储库适配到 `DataFetcher` 的简单方法，包括自动检测选项和标记为 `@GraphQlRepository` 的存储库的 GraphQL 查询注册。

[[data-querydsl]]
=== Querydsl

Spring for GraphQL 支持使用 `Querydsl` 通过 Spring Data https://docs.spring.io/spring-data/commons/docs/current/reference/html/#core.extensions[Querydsl extension] 来获取数据。 `Querydsl` 提供了一种灵活但类型安全的方法来通过使用注解处理器生成元模型来表达查询谓词。

例如，将存储库声明为 `QuerydslPredicateExecutor`：

[source,java,indent=0,subs="verbatim,quotes"]
----
public interface AccountRepository extends Repository<Account, Long>,
			QuerydslPredicateExecutor<Account> {
}
----

然后使用它创建一个 `DataFetcher`:

[source,java,indent=0,subs="verbatim,quotes"]
----
	// For single result queries
	DataFetcher<Account> dataFetcher =
			QuerydslDataFetcher.builder(repository).single();

	// For multi-result queries
	DataFetcher<Iterable<Account>> dataFetcher =
			QuerydslDataFetcher.builder(repository).many();
----

现在，你可以通过 <<execution-graphqlsource-runtimewiring-configurer>> 注册上述的 `DataFetcher`

`DataFetcher` 从 `GraphQL` 请求参数构建一个 Querydsl `Predicate`，并使用它来获取数据。 Spring Data 支持 JPA、MongoDB 和 LDAP 的 `QuerydslPredicateExecutor`。

如果存储库是 `ReactiveQuerydslPredicateExecutor`，builder 返回 `DataFetcher<Mono<Account>>` 或 `DataFetcher<Flux<Account>>`。 Spring Data 支持 MongoDB 的这种形式。

[[data-querydsl-build]]
==== 设置构


要在您的构建中配置 Querydsl，请遵循 https://querydsl.com/static/querydsl/latest/reference/html/ch02.html[官方参考文档]：

例如:

[source,groovy,indent=0,subs="verbatim,quotes,attributes",role="primary"]
.Gradle
----
dependencies {
	//...

	annotationProcessor "com.querydsl:querydsl-apt:$querydslVersion:jpa",
			'org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.2.Final',
			'javax.annotation:javax.annotation-api:1.3.2'
}

compileJava {
	 options.annotationProcessorPath = configurations.annotationProcessor
}
----
[source,xml,indent=0,subs="verbatim,quotes,attributes",role="secondary"]
.Maven
----
<dependencies>
	<!-- ... -->
	<dependency>
		<groupId>com.querydsl</groupId>
		<artifactId>querydsl-apt</artifactId>
		<version>${querydsl.version}</version>
		<classifier>jpa</classifier>
		<scope>provided</scope>
	</dependency>
	<dependency>
		<groupId>org.hibernate.javax.persistence</groupId>
		<artifactId>hibernate-jpa-2.1-api</artifactId>
		<version>1.0.2.Final</version>
	</dependency>
	<dependency>
		<groupId>javax.annotation</groupId>
		<artifactId>javax.annotation-api</artifactId>
		<version>1.3.2</version>
	</dependency>
</dependencies>
<plugins>
	<!-- Annotation processor configuration -->
	<plugin>
		<groupId>com.mysema.maven</groupId>
		<artifactId>apt-maven-plugin</artifactId>
		<version>${apt-maven-plugin.version}</version>
		<executions>
			<execution>
				<goals>
					<goal>process</goal>
				</goals>
				<configuration>
					<outputDirectory>target/generated-sources/java</outputDirectory>
					<processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
				</configuration>
			</execution>
		</executions>
	</plugin>
</plugins>
----


{github-main-branch}/samples/webmvc-http[webmvc-http] sample 使用 Querydsl `artifactRepositories`.


[[data-querydsl-customizations]]
==== Customizations

`QuerydslDataFetcher` 支持自定义如何将 GraphQL 参数绑定到属性，创建 `Querydsl` `Predicate`。 默认情况下，每个可用属性的参数都绑定为 "is equal to"。 要对其进行自定义，
您可以使用 `QuerydslDataFetcher` builder 方法来提供 `QuerydslBinderCustomizer`。

存储库本身可能是 `QuerydslBinderCustomizer` 的一个实例。 这是在 <<data-querydsl-registration>> 期间自动检测和透明应用的。 但是，当手动构建 `QuerydslDataFetcher` 时，您将需要使用 builder 方法来应用它。

`QuerydslDataFetcher` 支持接口和 DTO 投影以在返回查询结果以供进一步 GraphQL 处理之前转换查询结果。


TIP: 要了解什么是投影，请参阅 https://docs.spring.io/spring-data/commons/docs/current/reference/html/#projections[Spring Data docs]。 要了解如何在 GraphQL 中使用投影，请参阅 <<data-projections>>。

要将 Spring Data 投影与 Querydsl 存储库一起使用，请创建投影接口或目标 DTO 类，并通过 `projectAs` 方法对其进行配置以获得生成目标类型的 `DataFetcher`：

[source,java,indent=0,subs="verbatim,quotes"]
----
	class Account {

		String name, identifier, description;

		Person owner;
	}

	interface AccountProjection {

		String getName();

		String getIdentifier();
	}

	// For single result queries
	DataFetcher<AccountProjection> dataFetcher =
			QuerydslDataFetcher.builder(repository).projectAs(AccountProjection.class).single();

	// For multi-result queries
	DataFetcher<Iterable<AccountProjection>> dataFetcher =
			QuerydslDataFetcher.builder(repository).projectAs(AccountProjection.class).many();
----



[[data-querydsl-registration]]
==== 自动注册

如果存储库使用 `@GraphQlRepository` 注解，它会自动注册为尚未注册 `DataFetcher` ，并其返回类型与存储库域类型匹配的查询。 这包括单值和多值查询。

默认情况下，查询返回的 GraphQL 类型的名称必须与存储库领域类型的简单名称相匹配。 如果需要，您可以使用 `@GraphQlRepository` 的 `typeName` 属性来指定目标 GraphQL 类型名称。

自动注册检测会检测特定的存储库是否实现了 `QuerydslBinderCustomizer`， 并通过 `QuerydslDataFetcher` builder 方法应用它。
自动注册是通过内置的 `RuntimeWiringConfigurer` 执行的，可以从 `QuerydslDataFetcher` 获得。 {spring-boot-ref-docs}/web.html#web.graphql.data-query[Boot starter] 会自动检测 `@GraphQlRepository` bean 并使用它们来初始化 `RuntimeWiringConfigurer`。

自动注册不支持 <<data-querybyexample-customizations, 自定义>>。 如果需要，您需要使用 `QueryByExampleDataFetcher` 通过 <<execution-graphqlsource-runtimewiring-configurer>> 手动构建和注册 `DataFetcher`。

[[data-querybyexample]]
=== Query by Example

Spring Data 支持使用 https://docs.spring.io/spring-data/commons/docs/current/reference/html/#query-by-example[Query by Example] 来获取数据。 示例查询 (QBE) 是一种简单的查询技术，不需要您通过特定 store 的查询语言编写查询。

首先声明一个存储库，它是 `QueryByExampleExecutor`：

[source,java,indent=0,subs="verbatim,quotes"]
----
public interface AccountRepository extends Repository<Account, Long>,
			QueryByExampleExecutor<Account> {
}
----

使用 `QueryByExampleDataFetcher` 将存储库变成 `DataFecher`：

[source,java,indent=0,subs="verbatim,quotes"]
----
	// For single result queries
	DataFetcher<Account> dataFetcher =
			QueryByExampleDataFetcher.builder(repository).single();

	// For multi-result queries
	DataFetcher<Iterable<Account>> dataFetcher =
			QueryByExampleDataFetcher.builder(repository).many();
----

您现在可以通过 <<execution-graphqlsource-runtimewiring-configurer>> 注册上述 `DataFetcher`。

`DataFetcher` 使用 GraphQL 参数映射来创建存储库的领域类型，并将其用作示例对象来获取数据。 Spring Data 支持 JPA、MongoDB、Neo4j 和 Redis 的 `QueryByExampleDataFetcher`。

如果存储库是 `ReactiveQueryByExampleExecutor`，builder 返回 `DataFetcher<Mono<Account>>` 或 `DataFetcher<Flux<Account>>`。 Spring Data 支持 MongoDB、Neo4j、Redis 和 R2dbc 的这种形式。

[[data-querybyexample-build]]
==== 设置构建

Query by Example 已经包含在支持它的数据存储的 Spring Data 模块中，因此不需要额外的设置来启用它。

[[data-querybyexample-customizations]]
==== Customizations

`QueryByExampleDataFetcher` 支持接口和 DTO 投影，返回查询结果后可以进一步处理之前 GraphQL 转换查询结果。

TIP: 要了解什么是投影，请参阅 https://docs.spring.io/spring-data/commons/docs/current/reference/html/#projections[Spring Data documentation]。 要了解投影在 GraphQL 中的作用，请参阅 <<data-projections>>。

要将 Spring Data 投影与 Query by Example 存储库一起使用，请创建投影接口或目标 DTO 类，并通过 `projectAs` 方法对其进行配置，以获取生成目标类型的 `DataFetcher`：

[source,java,indent=0,subs="verbatim,quotes"]
----
	class Account {

		String name, identifier, description;

		Person owner;
	}

	interface AccountProjection {

		String getName();

		String getIdentifier();
	}

	// For single result queries
	DataFetcher<AccountProjection> dataFetcher =
			QueryByExampleDataFetcher.builder(repository).projectAs(AccountProjection.class).single();

	// For multi-result queries
	DataFetcher<Iterable<AccountProjection>> dataFetcher =
			QueryByExampleDataFetcher.builder(repository).projectAs(AccountProjection.class).many();
----


[[data-querybyexample-registration]]
==== 自动注册

如果存储库使用 `@GraphQlRepository` 注解，它会自动注册为尚未注册 `DataFetcher` ，并其返回类型与存储库领域类型匹配的查询。 这包括单值和多值查询。

默认情况下，查询返回的 GraphQL 类型的名称必须与存储库领域类型的简单名称相匹配。 如果需要，您可以使用 `@GraphQlRepository` 的 `typeName` 属性来指定目标 GraphQL 类型名称。

自动注册是通过内置的 `RuntimeWiringConfigurer` 执行的，可以从 `QueryByExampleDataFetcher` 获得。 {spring-boot-ref-docs}/web.html#web.graphql.data-query[Boot starter]  会自动检测 `@GraphQlRepository` bean 并使用它们来初始化 `RuntimeWiringConfigurer`。

自动注册不支持 <<data-querybyexample-customizations, customizations>>。 如果需要，您需要使用 `QueryByExampleDataFetcher` 通过 <<execution-graphqlsource-runtimewiring-configurer>> 手动构建和注册 `DataFetcher`。

[[data-projections]]
=== 选择集 vs 投影

一个常见问题是，GraphQL 选择集与 https://docs.spring.io/spring-data/commons/docs/current/reference/html/#projections[Spring Data projections] 相比如何，它们扮演什么角色？

简短的回答是，Spring for GraphQL 不是将 GraphQL 查询直接转换为 SQL 或 JSON 查询的数据。 相反，它允许您利用现有的 Spring 技术，并且不假设 GraphQL Schema 和底层数据模型之间存在一对一的映射。 这就是数据模型的客户端驱动选择和服务器端转换可以起到互补作用的原因。

为了更好地理解，请考虑 Spring Data 将领域驱动 (DDD) 设计作为管理数据层复杂性的推荐方法。 在 DDD 中，遵守聚合的约束很重要。 根据定义，聚合只有在完整加载时才有效，因为部分加载的聚合可能会对聚合功能施加限制。

在 Spring Data 中，您可以选择是否希望聚合按原样公开，或者是否在将其作为 GraphQL 结果返回之前对数据模型应用转换。 有时执行前者就足够了，默认情况下，<<data-querydsl>>  和 <<data-querybyexample>>  集成将 GraphQL 选择集转换为底层 Spring Data 模块用于限制选择的属性路径提示。

在其他情况下，减少甚至转换底层数据模型以适应 GraphQL Schema 是很有用的。 Spring Data 通过接口和 DTO 投影支持这一点。

接口投影定义了一组固定的属性，以根据数据存储查询结果公开属性可能为 `null` 或可能不为 `null` 的位置。 有两种接口投影，它们都决定了从底层数据源加载哪些属性：

- 如果您不能部分具体化聚合对象，但您仍想公开属性的子集，则 https://docs.spring.io/spring-data/commons/docs/current/reference/html/#projections.interfaces.closed[Closed interface projections] 很有用。
- https://docs.spring.io/spring-data/commons/docs/current/reference/html/#projections.interfaces.open[Open interface projections] 利用 Spring 的 `@Value` 注解和 {spring-framework-ref-docs}/core.html#expressions[SpEL]  表达式来应用轻量级数据转换，例如串联、计算或将静态函数应用于属性。

DTO 投影提供更高级别的自定义，因为您可以将转换代码放在构造函数或 getter 方法中。

DTO 投影从查询具体化，其中各个属性由投影本身确定。 DTO 投影通常与全参数构造函数（例如 Java record）一起使用，因此只有当所有必需的字段（或列）都是数据库查询结果的一部分时才能构造它们。

[[controllers]]
== Controllers 注解

Spring for GraphQL 提供了一种基于注解的编程模型，其中 `@Controller` 使用注解来声明具有灵活方法签名的处理程序方法，以获取特定 GraphQL 字段的数据。 例如：

[source,java,indent=0,subs="verbatim,quotes"]
----
	@Controller
	public class GreetingController {

			@QueryMapping // <1>
			public String hello() { // <2>
				return "Hello, world!";
			}

	}
----
<1> 将此方法绑定到查询，即查询类型下的字段。
<2> 如果未在注解上声明，则根据方法名称确定查询。

GraphQL 的 Spring 使用 `RuntimeWiring.Builder` 将上述处理程序方法注册为名为 "hello" 的查询的 `graphql.schema.DataFetcher`。

[[controllers-declaration]]
=== 定义

您可以将 `@Controller` 定义为标准的 Spring bean。 `@Controller` 可以自动检测，与 Spring 对检测类路径上的 `@Controller` 和 `@Component` 类并为它们自动注册 bean 定义的一般支持保持一致。
它还充当带注解类的构造型，表明其在 GraphQL 应用程序中作为数据获取组件的角色。

`AnnotatedControllerConfigurer` 检测 `@Controller`  并通过 `RuntimeWiring`.Builder 将其注解的处理程序方法注册为 `DataFetchers`。 它是 `RuntimeWiringConfigurer` 的一个实现，
可以添加到 `GraphQlSource.Builder`。 Spring Boot starter 自动将 `AnnotatedControllerConfigurer` 声明为一个 bean，并将所有 `RuntimeWiringConfigurer` 添加到 `GraphQlSource.Builder` 并启用对带注解的 `DataFetchers` 的支持，请参阅 Boot starter 文档中的 {spring-boot-ref-docs}/web.html#web.graphql.runtimewiring[GraphQL RuntimeWiring] 部分。

[[controllers-schema-mapping]]
=== `@SchemaMapping`

`@SchemaMapping` 注解将处理程序方法映射到 GraphQL Schema 中的字段，并将其声明为该字段的 `DataFetcher`。 注解可以指定父类型名称和字段名称：

[source,java,indent=0,subs="verbatim,quotes"]
----
	@Controller
	public class BookController {

		@SchemaMapping(typeName="Book", field="author")
		public Author getAuthor(Book book) {
			// ...
		}
	}
----

`@SchemaMapping` 注解也可以省略那些属性，在这种情况下，字段名默认为方法名，而类型名默认为注入到方法中的 source/parent 对象的简单类名。 例如，下面默认 "Book" 和字段 "author"：

[source,java,indent=0,subs="verbatim,quotes"]
----
	@Controller
	public class BookController {

		@SchemaMapping
		public Author author(Book book) {
			// ...
		}
	}
----

`@SchemaMapping` 注解可以在类级别声明，以指定类中所有处理程序方法的默认类型名称。

[source,java,indent=0,subs="verbatim,quotes"]
----
	@Controller
	@SchemaMapping(typeName="Book")
	public class BookController {

		// @SchemaMapping methods for fields of the "Book" type

	}
----

`@QueryMapping`、`@MutationMapping` 和 `@SubscriptionMapping` 是元注解，它们本身使用 `@SchemaMapping` 进行注解，并且 `typeName` 分别预设为 `Query`、`Mutation` 或 `Subscription`。
实际上，这些分别是 `Query`、`Mutation` 和 `Subscription` 类型下字段的快捷注解。 例如：

[source,java,indent=0,subs="verbatim,quotes"]
----
	@Controller
	public class BookController {

		@QueryMapping
		public Book bookById(@Argument Long id) {
			// ...
		}

		@MutationMapping
		public Book addBook(@Argument BookInput bookInput) {
			// ...
		}

		@SubscriptionMapping
		public Flux<Book> newPublications() {
			// ...
		}
	}
----

`@SchemaMapping` 处理程序方法具有灵活的签名，可以从一系列方法参数和返回值中进行选择。

[[controllers-schema-mapping-signature]]
==== 方法签名

Schema 映射处理程序方法可以具有以下任何方法参数：

[cols="1,2"]
|===
| 方法参数 | 描述

| `@Argument`
| 用于访问绑定到更高级别类型对象的命名字段参数。 参见 <<controllers-schema-mapping-argument>>。

| `@Arguments`
| 用于访问绑定到更高级别的类型对象的所有字段参数。
参见 <<controllers-schema-mapping-arguments>>.

| `@ProjectedPayload` Interface
| 用于通过项目接口访问字段参数。
参见 <<controllers-schema-mapping-projectedpayload-argument>>.

| Source
|用于访问字段的源 (i.e. parent/container) 实例。
参见 <<controllers-schema-mapping-source>>.

| `DataLoader`
| 在  `DataLoaderRegistry` 中访问 `DataLoader`.
参见 <<controllers-schema-mapping-data-loader>>.

| `@ContextValue`
| 从 `DataFetchingEnvironment` 中的 main `GraphQLContext` 访问属性

| `@LocalContextValue`
| 从 `DataFetchingEnvironment` 中的 local `GraphQLContext` 访问属性

| `GraphQLContext`
| 从 `DataFetchingEnvironment` 中访问 context.

| `java.security.Principal`
| 如果可用，从 Spring Security 上下文中获取。

| `@AuthenticationPrincipal`
| 从 Spring Security context 中访问 `Authentication#getPrincipal()`.

| `DataFetchingFieldSelectionSet`
| 通过 `DataFetchingEnvironment` 访问查询的选择集。

| `Locale`, `Optional<Locale>`
| 用于从 `DataFetchingEnvironment` 访问 `Locale`。

| `DataFetchingEnvironment`
| 用于直接访问底层的 `DataFetchingEnvironment`。

|===

Schema mapping 处理程序方法可以返回：

- 一个被解析的任何类型值.
- `Mono` 和 `Flux` 用于异步值。 支持控制器方法和 Reactive DataFetcher 中描述的任何 <<execution-reactive-datafetcher>>。
- `java.util.concurrent.Callable` 以异步生成值。 为此，必须使用 `Executor` 配置 `AnnotatedControllerConfigurer`。

[[controllers-schema-mapping-argument]]
==== `@Argument`

在 GraphQL Java 中，`DataFetchingEnvironment` 提供对特定字段参数值映射的访问。 这些值可以是简单的标量值（例如 String、Long）、用于更复杂输入的值映射或值列表。

使用 `@Argument` 注解将参数绑定到目标对象并注入到处理程序方法中。 绑定是通过将参数值映射到预期方法参数类型的主要数据构造函数来执行的，或者通过使用默认构造函数来创建对象，然后将参数值映射到它的属性来执行。
这是递归重复的，使用所有嵌套的参数值并相应地创建嵌套的目标对象。 例如：

[source,java,indent=0,subs="verbatim,quotes"]
----
	@Controller
	public class BookController {

		@QueryMapping
		public Book bookById(@Argument Long id) {
			// ...
		}

		@MutationMapping
		public Book addBook(@Argument BookInput bookInput) {
			// ...
		}
	}
----

默认情况下，如果方法参数名称可用（需要 Java 8+ 的 `-parameters` 编译器标志或来自编译器的调试信息），它用于查找参数。 如果需要，您可以通过注解自定义名称，例如 `@Argument("bookInput")`.

TIP: `@Argument` 注解没有 "required" 标志，也没有指定默认值的选项。 这两者都可以在 GraphQL Schema 指定，并由 GraphQL Java 强制执行。

如果绑定失败，将引发 `BindException`，绑定问题累积为字段错误，其中每个错误的字段是发生问题的参数路径。
您可以在 `Map<String, Object>` 参数上使用 `@Argument` 来获取所有参数值。 不得设置 `@Argument` 上的 `name` 属性。

[[controllers-schema-mapping-arguments]]
==== `@Arguments`

如果要将完整参数映射绑定到单个目标对象，请使用 `@Arguments` 注解，这与绑定特定命名参数的 `@Argument` 形成对比。

例如，`@Argument BookInput bookInput` 使用参数 "bookInput" 的值来初始化 `BookInput`，而 `@Arguments` 使用完整的参数映射，在这种情况下，顶级参数绑定到 `BookInput` 属性。

[[controllers-schema-mapping-projectedpayload-argument]]
==== `@ProjectedPayload` 接口

作为使用带有 <<controllers-schema-mapping-argument>> 的完整对象的替代方法，您还可以使用投影接口。通过定义良好的最小接口访问 GraphQL 请求参数。 当 Spring Data 在类路径上时，参数投影由 https://docs.spring.io/spring-data/commons/docs/current/reference/html/#projections.interfaces[Spring Data's Interface projections] 提供。

要使用它，请创建一个用 `@ProjectedPayload` 注解的接口，并将其声明为控制器方法参数。 如果参数用 `@Argument` 注解，它适用于 `DataFetchingEnvironment.getArguments()` 映射中的单个参数。
当在没有 `@Argument` 的情况下声明时，投影适用于完整参数映射中的顶级参数。

例如：

[source,java,indent=0,subs="verbatim,quotes"]
----
	@Controller
	public class BookController {

		@QueryMapping
		public Book bookById(BookIdProjection bookId) {
			// ...
		}

		@MutationMapping
		public Book addBook(@Argument BookInputProjection bookInput) {
			// ...
		}
	}

	@ProjectedPayload
	interface BookIdProjection {

		Long getId();
	}

	@ProjectedPayload
	interface BookInputProjection {

		String getName();

		@Value("#{target.author + ' ' + target.name}")
		String getAuthorAndName();
	}
----

[[controllers-schema-mapping-source]]
==== Source

在 GraphQL Java 中，`DataFetchingEnvironment` 提供对源字段 (i.e. parent/container) 实例的访问。 要访问它，只需声明一个预期目标类型的方法参数。

[source,java,indent=0,subs="verbatim,quotes"]
----
	@Controller
	public class BookController {

		@SchemaMapping
		public Author author(Book book) {
			// ...
		}
	}
----

源方法参数还有助于确定映射的类型名称。 如果 Java 类的简单名称与 GraphQL 类型匹配，则无需在 `@SchemaMapping` 注解中显式指定类型名称。

[TIP]
====
给 source/parent books 对象列表，<<controllers-batch-mapping>> 处理程序方法可以批量加载查询的所有作者。
====


[[controllers-schema-mapping-data-loader]]
==== `DataLoader`

当您为实体注册批量加载函数时，如 <<execution-batching>> 中所述，您可以通过声明 `DataLoader` 类型的方法参数并使用它来加载实体来访问实体的 `DataLoader`：

[source,java,indent=0,subs="verbatim,quotes"]
----
@Controller
public class BookController {

	public BookController(BatchLoaderRegistry registry) {
		registry.forTypePair(Long.class, Author.class).registerMappedBatchLoader((authorIds, env) -> {
			// return Map<Long, Author>
		});
	}

	@SchemaMapping
	public CompletableFuture<Author> author(Book book, DataLoader<Long, Author> loader) {
		return loader.load(book.getAuthorId());
	}

}
----

默认情况下，`BatchLoaderRegistry` 使用值类型的完整类名（例如 `Author` 的类名）作为注册键，因此只需声明具有泛型类型的 `DataLoader` 方法参数即可提供足够的信息以在 `DataLoaderRegistry` 中注册它。
退一步说，`DataLoader` 方法参数解析器还将尝试将方法参数名称作为键，但通常这不是必需的。

请注意，对于加载相关实体的许多情况，`@SchemaMapping` 只是委托给 `DataLoader`，您可以使用下一节所述的 <<controllers-batch-mapping,@BatchMapping>>  方法来减少样板。

[[controllers-schema-mapping-validation]]
==== Validation

当找到 `javax.validation.Validator` bean 时，`AnnotatedControllerConfigurer` 会启用对带注解的控制器方法的 {spring-framework-ref-docs}/core.html#validation-beanvalidation-overview[Bean Validation]。 通常，bean 的类型为 `LocalValidatorFactoryBean`。

Bean 验证使您可以声明对类型的约束：

[source,java,indent=0,subs="verbatim,quotes"]
----
public class BookInput {

	@NotNull
	private String title;

	@NotNull
	@Size(max=13)
	private String isbn;
}
----

然后，您可以使用 `@Valid` 注解控制器方法参数以在方法调用之前对其进行验证：

[source,java,indent=0,subs="verbatim,quotes"]
----
	@Controller
	public class BookController {

		@MutationMapping
		public Book addBook(@Argument @Valid BookInput bookInput) {
			// ...
		}
	}
----

如果在验证期间发生错误，则会引发 `ConstraintViolationException`。 您可以使用 <<execution-exceptions>> 链来决定如何通过将其转化为包含在 GraphQL 响应中的错误来将其呈现给客户端。

TIP: 除了 `@Valid`，你还可以使用 Spring 的 `@Validated`，它允许指定验证组。

Bean 验证对 <<controllers-schema-mapping-argument>>,
<<controllers-schema-mapping-arguments>>, and
<<controllers-schema-mapping-projectedpayload-argument,@ProjectedPayload>> 方法参数很有用，但更普遍地适用于任何方法参数。

[WARNING]
.Validation 和 Kotlin 协程
====
Hibernate Validator 与 Kotlin Coroutine 方法不兼容，并且在检查它们的方法参数时失败。 请参阅 https://github.com/spring-projects/spring-graphql/issues/344#issuecomment-1082814093[spring-projects/spring-graphql#344 (comment)] 以获取相关问题的链接和建议的解决方法。
====

[[controllers-batch-mapping]]
=== `@BatchMapping`

<<execution-batching>>  通过使用 `org.dataloader.DataLoader` 延迟加载单个实体实例来解决 N+1 选择问题，因此它们可以一起加载。 例如：

[source,java,indent=0,subs="verbatim,quotes"]
----
@Controller
public class BookController {

	public BookController(BatchLoaderRegistry registry) {
		registry.forTypePair(Long.class, Author.class).registerMappedBatchLoader((authorIds, env) -> {
			// return Map<Long, Author>
		});
	}

	@SchemaMapping
	public CompletableFuture<Author> author(Book book, DataLoader<Long, Author> loader) {
		return loader.load(book.getAuthorId());
	}

}
----

对于加载关联实体的直接情况，如上所示，`@SchemaMapping` 方法只是委托给 `DataLoader`。 这是可以使用 `@BatchMapping` 方法避免的样板。 例如：

[source,java,indent=0,subs="verbatim,quotes"]
----
	@Controller
	public class BookController {

		@BatchMapping
		public Mono<Map<Book, Author>> author(List<Book> books) {
			// ...
		}
	}
----

以上成为 `BatchLoaderRegistry` 中的批量加载函数，其中键是 `Book` 实例，加载的值是它们的 Author。 此外，`DataFetcher` 还透明地绑定到 `Book` 类型的 author 字段，它简单地委托给作者的 `DataLoader`，
给定其 source/parent  `Book` 实例。

[TIP]
====
要用作唯一键，`Book` 必须实现 `hashcode` 和 `equals`。
====

默认情况下，字段名称默认为方法名称，而类型名称默认为输入 `List` 元素类型的简单类名称。 两者都可以通过注解属性进行定制。 类型名称也可以从类级别 `@SchemaMapping` 继承。

[[controllers-batch-mapping-signature]]
==== 方法签名

Batch mapping 方法支持以下参数：

[cols="1,2"]
|===
| 方法参数 | 描述

| `List<K>`
| source/parent 对象.

| `java.security.Principal`
| 如果可用，从 Spring Security 上下文中获取。

| `@ContextValue`
| 用于访问来自 `BatchLoaderEnvironment` 的 `GraphQLContext` 的值，该值与来自 `DataFetchingEnvironment` 的上下文相同。

| `GraphQLContext`
| 用于从 `BatchLoaderEnvironment` 访问上下文，它与 `DataFetchingEnvironment` 中的上下文相同。

| `BatchLoaderEnvironment`
| GraphQL Java 中可用于 `org.dataloader.BatchLoaderWithContext` 的环境。

|===

Batch mapping 方法可以返回：

[cols="1,2"]
|===
| 返回类型| 描述

| `Mono<Map<K,V>>`
| 以父对象为键，以批量加载的对象为值的映射。

| `Flux<V>`
| 一系列批量加载的对象，它们的顺序必须与传递到方法中的 source/parent 对象的顺序相同。

| `Map<K,V>`, `Collection<V>`
| Imperative variants, e.g. without remote calls to make.

| `Callable<Map<K,V>>`, `Callable<Collection<V>>`
| Imperative variants to be invoked asynchronously. For this to work,
  `AnnotatedControllerConfigurer` must be configured with an `Executor`.

|===


[[security]]
== Security

<<server-transports, Web>>  GraphQL 端点的路径可以使用 HTTP URL 安全性来保护，以确保只有经过身份验证的用户才能访问它。 但是，这不会区分单个 URL 上此类共享端点上的不同 GraphQL 请求。

要应用更细粒度的安全性，请将 Spring Security 注解（例如 `@PreAuthorize` 或 `@Secured`）添加到涉及获取 GraphQL 响应的特定部分的服务方法。 这应该是有效的，因为 <<execution-context>> 旨在使安全性和其他上下文在数据获取级别可用。

Spring for GraphQL 存储库包含 {github-main-branch}/samples/webmvc-http-security[Spring MVC] 和 {github-main-branch}/samples/webflux-security[WebFlux] 的示例。

include::client.adoc[leveloffset=+1]

include::testing.adoc[leveloffset=+1]

[[samples]]
== Samples

这个 Spring for GraphQL 存储库包含各种场景的 {github-main-branch}/samples[sample applications]。

您可以通过克隆此存储库并从您的 IDE 运行主要应用程序类或在命令行中键入以下内容来运行它们：

[source,bash,indent=0,subs="verbatim,quotes"]
----
$ ./gradlew :samples:{sample-directory-name}:bootRun
----
