[[integration-tests]]
= 在集成测试中运行
尽管您可以从测试 (或测试套件) 本身非常轻松地启动 Spring Boot 应用程序,但可能需要在构建本身中进行处理. 为了确保围绕集成测试正确管理 Spring Boot 应用程序的生命周期,可以使用  `start` 和 `stop` 目标,如以下示例所示:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/integration-tests/pom.xml[tags=integration-tests]
----

现在,这样的设置可以使用 https://maven.apache.org/surefire/maven-failsafe-plugin[failsafe-plugin] 按预期运行集成测试.

NOTE: 默认情况下,应用程序是在单独的进程中启动的,并且使用 JMX 与应用程序进行通信. 默认使用 `9001` 端口。如果需要配置 JMX 端口,请参见 <<integration-tests.examples.jmx-port,the dedicated example>>.

您还可以配置更高级的设置,以在设置了特定属性时跳过集成测试,请参见 <<integration-tests.examples.skip,the dedicated example>>.

[[integration-tests.no-starter-parent]]
== 在没有 Spring Boot 的 Parent POM 的情况下使用故障保护
Spring Boot's Parent POM, `spring-boot-starter-parent`, 将 Failsafe 的 `<classesDirectory>` 设置为 `${project.build.outputDirectory}`.
如果没有此配置, 这将导致 Failsafe 使用已编译的类而不是重新包装的 jar,  Failsafe 无法加载您的应用程序的类.
如果您不使用 parent POM,  则应以相同的方式配置故障保护:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/integration-tests/failsafe-pom.xml[tags=failsafe]
----

include::goals/start.adoc[leveloffset=+1]

include::goals/stop.adoc[leveloffset=+1]

[[integration-tests.examples]]
== 示例

[[integration-tests.examples.random-port]]
=== 使用随机端口进行集成测试
Spring Boot 测试集成的一个不错的功能是它可以为 Web 应用程序分配一个空闲端口. 当使用插件的 `start` 目标时,Spring Boot 应用程序将单独启动,因此很难将实际端口传递给集成测试本身.

下面的示例展示了如何使用 https://www.mojohaus.org/build-helper-maven-plugin[Build Helper Maven 插件] 实现相同的功能:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/integration-tests/random-port-pom.xml[tags=random-port]
----

现在,您可以在任何集成测试中搜索 `test.server.port`  系统属性,以创建指向服务器的正确 `URL`.

[[integration-tests.examples.jmx-port]]
=== 自定义 JMX 端口
`jmxPort` 属性允许自定义插件用于与 Spring Boot 应用程序通信的端口.

本示例显示了在已经使用 `9001` 的情况下如何自定义端口:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/integration-tests/customize-jmx-port-pom.xml[tags=customize-jmx-port]
----

TIP: 如果需要配置 JMX 端口,请确保在上述全局配置中进行配置,以便两个目标都可以共享它.

[[integration-tests.examples.skip]]
=== 跳过集成测试
`skip` 属性允许完全跳过 Spring Boot maven 插件的执行.

此示例说明如何跳过带有命令行属性的集成测试,并仍然确保 `repackage`  目标运行:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/integration-tests/skip-integration-tests-pom.xml[tags=skip-integration-tests]
----

默认情况下,将运行集成测试,但是此设置使您可以在命令行上轻松禁用它们,如下所示:

[indent=0]
----
	$ mvn verify -Dskip.it=true
----
