[[packaging]]
= 打包可执行文件

该插件可以创建包含应用程序所有依赖的可执行文件 (jar 文件和 war 文件) ,然后可以使用 `java -jar` 运行.

打包可执行文件是由重 `repackage` 目标执行的,如以下示例所示:


[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/repackage-pom.xml[tags=repackage]
----

TIP: 如果您使用的是 `spring-boot-starter-parent`,则已经使用 `repackage` 执行 ID 预配置了此类执行,因此只需要添加插件定义.

上面的示例重新打包了在 Maven 生命周期的打包阶段构建的 jar 或 war ,包括在项目中定义的 `provided`  所有依赖. 如果其中一些依赖需要排除,则可以使用 `exclude` 选项之一;  有关更多详细信息,请参见 <<packaging.examples.exclude-dependency,依赖排除>> .

默认情况下,原始 (即不可执行) artifact 被重命名为 `.original`,但是也可以使用自定义 classifier 保留原始 artifact.

NOTE: 当前不支持 `maven-war-plugin` 的 `outputFileNameMapping` 功能.

默认情况下,会自动排除 Devtools (您可以使用 `excludeDevtools` 属性进行控制) . 为了使它与 `war` 打包一起使用,必须将 `spring-boot-devtools` 依赖设置为`optional`  或具有 `provided`  的作用域.

该插件将重写清单,尤其是它管理 `Main-Class` 和 `Start-Class`. 如果默认设置不起作用,则必须在 Spring Boot 插件中配置值,而不是在 `jar` 插件中配置值. 清单中的 `Main-Class` 由 Spring Boot 插件的 `layout` 属性控制,如以下示例所示:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/non-default-pom.xml[tags=non-default]
----

`layout` 属性默认为由 archive 类型( jar 或 war )确定的值.以下是可用的布局:(`jar` or `war`). 以下布局可用:

* `JAR`: 常规的可执行 JAR 布局.
* `WAR`: 可执行的 WAR 布局. `provided` 依赖放在 `WEB-INF/lib-provided` 中,以避免在将 `war`  部署到 servlet 容器中时发生任何冲突.
* `ZIP` (又名 `DIR`): 与使用 `PropertiesLauncher` 的 `JAR` 布局相似.
* `NONE`: 捆绑所有依赖和项目资源.不捆绑引导加载程序.

[[packaging.layers]]
== Jar 或 War 分层

重新打包的 jar 分别在 `BOOT-INF/classes` 和 `BOOT-INF/lib` 中包含应用程序的类和依赖.
类似地，一个可执行的war包含应用程序的类在 `WEB-INF/classes` 和依赖关系在 `WEB-INF/lib` 和 `WEB-INF/lib-provided`。
对于需要从 jar 的内容中构建 docker 镜像的情况,能够进一步分隔这些目录以便将它们写入不同的层中很有用.

分层的构件使用与常规重新打包的 jar 或 war 相同的布局,但是包括了描述每个层的附加元数据文件.

默认情况下,定义了以下层:

* `dependencies`:  包含所有的依赖,但不包括 `SNAPSHOT` 版本的依赖.
* `spring-boot-loader`:  用于加载类.
* `snapshot-dependencies`:  包含所有的 `SNAPSHOT` 版本依赖 .
* `application`:  应用程序类和资源.

通过查看当前构建的所有模块来确定模块依赖关系. 如果一个模块依赖只能被解析, 因为它已经被安装到 Maven 的本地缓存中, 并且它不是当前构建的一部分, 那么它将被标识为常规依赖.


层的顺序很重要,因为它确定了部分应用程序更改时可以缓存先前的层的可能性. 默认顺序是 `dependencies`, `spring-boot-loader`, `snapshot-dependencies`, `application`. 应该首先添加最不可能更改的内容,然后添加有可能更改的层.

重新打包 archive 默认包含 `layers.idx` 文件. 禁用该特性的方法如下:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/disable-layers-pom.xml[tags=disable-layers]
----


[[packaging.layers.configuration]]
=== 自定义层的配置

根据您的应用程序,您可能想要调整层的创建方式和添加新层的方式.可以使用一个单独的配置文件来完成此操作,该文件应如下所示进行注册:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/custom-layers-pom.xml[tags=custom-layers]
----

配置文件描述了如何将 archive 分为几层,以及这些层的顺序.下面的示例显示如何显式定义上述默认顺序:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/layers.xml[tags=layers]
----


`layers` XML 分为三部分:

* `<application>` 定义应如何对应用程序类和资源进行分层.
* `<dependencies>` 定义应层之间的依赖关系.
* `<layerOrder>` 定义应写入层的顺序.

嵌套的 `<into>` 用于 `<application>` 和 `<dependencies>` 中,以声明层的内容. 从上到下,按照定义的顺序评估. 较早的块未声明的任何内容仍然可供后续块使用.

`<into>` 块使用嵌套的 `<include>` 和 `<exclude>` 元素声明内容. `<application>` 对 include/exclude  表达式使用 Ant 风格的匹配模式. `<dependencies>` 使用 `group:artifact[:version]` 模式.它还提供了 `<includeModuleDependencies />` 和 `<excludeModuleDependencies />` 元素, 可以用来包含或排除本地模块依赖.

如果未定义 `<include>`,则将考虑所有内容 (较早的块未声明) .

如果未定义 `<exclude>`,则不应用任何排除项.

查看上面的 `<dependencies>` 示例,我们可以看到第一个 `<into>` 将声明所有的项目依赖, 第二个 `<into>` 将为  `snapshot-dependencies`  声明所有快照依赖.  最后的 `<into>` 将声明 `dependencies` 层的所有剩余内容 (在这种情况下,不是 项目 或 SNAPSHOT 的任何依赖) .

`<application>` 块具有相似的规则. 首先声明 `spring-boot-loader` 层的 `org/springframework/boot/loader/**`  内容. 然后为 `application` 层声明所有剩余的类和资源.

NOTE: `<into>` 块的定义顺序通常与层的写入顺序不同. 因此,必须始终包含 `<layerOrder>` 元素,并且必须覆盖 `<into>` 块引用的所有层.

include::goals/repackage.adoc[leveloffset=+1]

[[packaging.examples]]
== 示例

[[packaging.examples.custom-classifier]]
=== 自定义 Classifier
默认情况下,`repackage` 目标将原始 artifact 替换为重新打包的 artifact. 对于表示应用程序的模块来说,这是理智的行为,但是如果您的模块用作另一个模块的依赖,则需要为重新打包的模块提供 classifier. 这样做的原因是应用程序类打包在 `BOOT-INF/classes`  中,因此从属模块无法加载经过重新打包的 jar 的类.

如果是这种情况,或者您希望保留原始 artifact,然后将重新打包的 artifact 与其他 classifier 相连,请配置插件,如以下示例所示:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/different-classifier-pom.xml[tags=different-classifier]
----

如果您使用的是 `spring-boot-starter-parent`,则 `repackage` 目标将在 ID 为 `repackage` 的执行中自动执行.在该设置中,只需要指定配置,如以下示例所示:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/repackage-configuration-pom.xml[tags=repackage-configuration]
----

这种配置将生成两个 artifacts : 原始 artifacts 和由重新打包目标产生的重新打包的对应零件. 两者都将透明安装/部署.

如果要以替换主要 artifact 的相同方式重新打包辅助 artifact,也可以使用相同的配置. 以下配置使用重新打包的应用程序安装/部署单个 `task` 分类的 artifact:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/classified-artifact-pom.xml[tags=classified-artifact]
----

由于 `maven-jar-plugin` 和 `spring-boot-maven-plugin` 都在同一阶段运行,因此必须首先定义 jar 插件 (以便在重新打包目标之前运行) ,这一点很重要. 同样,如果您使用的是 `spring-boot-starter-parent`,可以将其简化如下:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/jar-plugin-first-pom.xml[tags=jar-plugin-first]
----


[[packaging.examples.custom-name]]
=== 自定义名称
如果您需要重新打包的 jar 的本地名称与项目的 `artifactId` 属性定义的本地名称不同,请使用标准的 `finalName`,如以下示例所示:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/custom-name-pom.xml[tags=custom-name]
----

此配置将在 `target/my-app.jar` 中生成重新打包的文件.

[[packaging.examples.local-artifact]]
=== 本地 Repackaged Artifact
默认情况下,`repackage` 目标将原始 artifact 替换为可执行文件. 如果您只需要部署原始 jar,但仍能够使用常规文件名运行您的应用,请按以下步骤配置插件:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/local-repackaged-artifact-pom.xml[tags=local-repackaged-artifact]
----

这种配置生成两个 artifacts : 原始 artifacts 和由  `repackage` 目标产生的可执行计数器部分.仅原始的将被安装/部署.

[[packaging.examples.custom-layout]]
=== 自定义布局

Spring Boot 使用附加 jar 文件中定义的自定义布局工厂对该项目的 jar 文件重新打包,该工厂作为对构建插件的依赖关系提供:


[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/custom-layout-pom.xml[tags=custom-layout]
----

布局工厂是作为 `pom` 中明确指定的 `LayoutFactory` 的实现 (来自 `spring-boot-loader-tools`) 提供的. 如果插件的类路径上只有一个自定义 `LayoutFactory`,并且已在  `META-INF/spring.factories` 中列出,则无需在插件配置中显式设置它.

如果设置了 <<goals-repackage-parameters-details-layoutFactory,layout>> ,则总是会忽略布局工厂.

[[packaging.examples.exclude-dependency]]
=== Dependency 排除

默认情况下,`repackage` 和 `run` 目标都将包括项目中定义的所有提供的依赖. Spring Boot 项目应将 `provided` 的依赖视为运行应用程序所需的 "container"  依赖.

这些依赖中的某些可能根本不需要,应该从可执行 jar 中排除. 为了保持一致,在运行应用程序时也不应该显示它们.

有两种方法可以在运行时打包/使用中排除依赖:

* 排除由 `groupId` 和 `artifactId` 标识的组件, 如有需要,可以使用可选的 `classifier`.
* 排除所有 `groupId` 的组件.

以下示例排除 `com.example:module1`,只排除此 artifact:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/exclude-artifact-pom.xml[tags=exclude-artifact]
----

此示例排除了属于 `com.example` 组的所有组件:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/exclude-artifact-group-pom.xml[tags=exclude-artifact-group]
----

[[packaging.examples.layered-archive-tools]]
=== Layered Jar Tools
创建分层 jar 或 war 时,`spring-boot-jarmode-layertools` jar 或 war 将作为依赖添加到 jar 中. 将此 jar 放在类路径上,您可以在特殊模式下启动应用程序,该模式允许引导代码运行与您的应用程序完全不同的内容,例如,提取层的内容. 如果要排除此依赖关系,可以按以下方式进行:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/exclude-dependency-pom.xml[tags=exclude-dependency]
----

[[packaging.examples.custom-layers-configuration]]
=== Custom Layers Configuration
默认设置将依赖分为快照和非快照,但是,您可能具有更复杂的规则. 例如,您可能希望在专用层中隔离项目的公司特定依赖性. 以下 `layers.xml` 配置显示了一种这样的设置:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/packaging/layers-configuration.xml[tags=layers-configuration]
----

上面的配置使用所有带有 `com.acme` groupId 的库创建一个附加的 `company-dependencies` 层.
