[[using]]
= 使用插件

Maven 用户可以继承 `spring-boot-starter-parent` 项目以获取合适的默认值,父项目提供了以下功能:

* Java 1.8 作为默认编译器.
* 源代码使用 UTF-8 编码.
* Compilation with `-parameters`.
* using-boot-dependency-management,依赖管理部分, 继承自 `spring-boot-dependencies` 的 POM,允许您省略常见依赖的 `<version>` 标签.
* 执行  `repackage` id 重新执行 <<goals.adoc#goals-repackage, `repackage` goal>>
* `native` profile 配置构建生成原生镜像。
* 合理的 https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html[资源过滤].
* 合适的插件配置 (https://www.mojohaus.org/exec-maven-plugin/[exec plugin], https://github.com/ktoso/maven-git-commit-id-plugin[Git commit ID], and https://maven.apache.org/plugins/maven-shade-plugin/[shade]).
* 对 `application.properties` 和 `application.yml` 资源的合理过滤,包括特定 profile 的文件(例如 , `application-dev.properties` 和 `application-dev.yml`)

注意: 由于 `application.properties` 和 `application.yml` 文件接受 Spring 风格的占位符 (`${...}`) ,因此 Maven 改为使用 `@..@` 占位符 (您可以使用 Maven 的 `resource.delimiter` 属性重写它)

[[using.parent-pom]]
== 继承 Starter Parent
配置项目继承 `spring-boot-starter-parent`,只需要按以下方式设置 `parent`:

[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
	<!-- Inherit defaults from Spring Boot -->
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>{gradle-project-version}</version>
	</parent>
----

NOTE: 您只需要在此依赖上指定 Spring Boot 的版本号. 如果您要导入其它 starter,则可以放心地省略版本号.

通过该设置,您还可以重写自己项目中的配置属性来覆盖个别依赖. 例如,要升级到另一个 SLF4J 库和 Spring Data 发行版本,您需要将以下内容添加到 `pom.xml` 文件中.

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/using/different-versions-pom.xml[tags=different-versions]
----

查看 {version-properties-appendix}[`Dependency versions Appendix`] 获取等多的版本依赖关系.

[[using.import]]
== 不使用父 POM
不是每个人都喜欢从 `spring-boot-starter-parent` 继承 POM. 您可能需要使用自己公司标准的父 POM,或者您可能只是希望明确地声明所有 Maven 配置.

如果您不想使用 `spring-boot-starter-parent`,则仍然可以通过使用 `import`scope 依赖来获得依赖管理 (但不是插件管理) 的好处:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/using/no-starter-parent-pom.xml[tags=no-starter-parent]
----

如上所述,上述示例设置不会让您使用属性来覆盖个别依赖. 要达到相同的目的,需要在 `spring-boot-dependencies` 项之前在项目的 `dependencyManagement` 中添加一项. 例如,要升级到另一个 SLF4J 库和 Spring Data 发行版,您可以将以下元素添加到 `pom.xml` 中:

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/using/no-starter-parent-override-dependencies-pom.xml[tags=no-starter-parent-override-dependencies]
----

[[using.overriding-command-line]]
== 通过命令行重写配置
使用 spring-boot,该插件提供了许多用户属性,可让您从命令行自定义配置.

例如,您可以调整配置文件以在运行应用程序时启用,如下所示:

[indent=0]
----
	$ mvn spring-boot:run -Dspring-boot.run.profiles=dev,local
----

如果您希望同时拥有一个默认值,同时允许在命令行上覆盖它,那么您应该结合使用用户提供的项目属性和 MOJO 配置.

[source,xml,indent=0,subs="verbatim,attributes",tabsize=4]
----
include::../maven/using/default-and-override-pom.xml[tags=default-and-override]
----

以上内容确保默认情况下启用了 local  和 dev. 也可以在命令行中覆盖它:

[indent=0]
----
	$ mvn spring-boot:run -Dapp.profiles=test
----
