= EXPIRE

**语法**

[source,text]
----
EXPIRE key seconds [NX | XX | GT | LT]
----

**可用版本**：1.0.0

**时间复杂度**：O(1)

**ACL 类别**：**@keyspace, @write, @fast**

为给定 `key` 设置超时时间，当 key 超时时，它会被自动删除。在 Redis 术语中，带有超时时间的 key 被称为『易失的』(volatile)。

超时时间可以通过使用 `DEL` 命令来删除整个 key 来移除，或者被 SET 和 GETSET 命令覆写(overwrite)，

只有具有删除或覆盖 key 内容的命令才会清除超时，包括 `DEL`, `SET`, `GETSET` 和所有 `*STORE`  命令。 这意味着，如果一个命令只是修改(alter)一个带超时时间的 key 的值而不是用一个新的 key 值来代替(replace)它的话，那么超时时间不会被改变。
例如，使用  `INCR` 增加 key 的值，使用 `LPUSH` 将新值推送到列表中，或者使用 `HSET` 更改哈希的字段值，这些操作都不会影响超时。

还可以使用  `PERSIST` 命令清除超时，将 key 恢复为持久 key。

如果使用 `RENAME` 对一个 key 进行改名，那么改名后的 key 的超时时间和改名前一样。

如果某个 key 被 `RENAME` 覆盖，就像已存在的 key `Key_A`，调用 `RENAME Key_B Key_A` 被 `Key_B` 覆盖，则原始 `Key_A` 是否有关联的超时并不重要 ，新 key `Key_A` 将继承 `Key_B` 的所有特性。

请注意，如果使用非正，或者过去的超时时间调用 `EXPIRE/PEXPIRE` 或 `EXPIREAT/PEXPIREAT` 命令，将导致 key 被删除而不是过期（因此，发出的 https://redis.io/docs/manual/keyspace-notifications/[key event] 将是 `del`，而不是 `expired`）。

== 选项

`EXPIRE` 命令支持以下选项:

* NX -- 只有 key 不存在过期时间时设置过期时间
* XX -- 只有 key 存在过期时间时设置过期时间
* GT -- 只有 key 新的过期时间大于当前过期时间设置过期时间
* LT -- 只有 key 新的过期时间小于当前过期时间设置过期时间

出于 `GT` 和 `LT` 的目的，对于非易失性的 key 被视为无限 TTL。 `GT`, `LT` 和 `NX` 选项是互斥的。

== 刷新过期

可以使用已存在过期设置的 key 作为参数来调用 `EXPIRE`。 在这种情况下，key 的超时时间将更新为新值。 有许多有用的应用程序，下面的导航会话模式部分记录了一个示例。

== Redis 2.1.3 之前版本的差异

在 Redis 2.1.3 之前的版本中，修改一个带有生存时间的 key 会导致整个 key 被删除，这一行为是受当时复制(replication)层的限制而作出的，现在这一限制已经被修复。

`EXPIRE` 将返回 0 并且不会更改设置了超时的 key 的超时。

== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-integers[返回整型]:

* 1 - 如果设置了超时.
* 0 - 如果未设置超时，则为 0。 例如 key 不存在，或由于提供的参数而跳过操作。

== 示例

[source,text]
----
redis> SET mykey "Hello"
"OK"
redis> EXPIRE mykey 10
(integer) 1
redis> TTL mykey
(integer) 10
redis> SET mykey "Hello World"
"OK"
redis> TTL mykey
(integer) -1
redis> EXPIRE mykey 10 XX
(integer) 0
redis> TTL mykey
(integer) -1
redis> EXPIRE mykey 10 NX
(integer) 1
redis> TTL mykey
(integer) 10
redis>
----

== 模式：导航会话

想象一下，您有一个 Web 服务，并且您对用户最近访问的最新 N 个页面感兴趣，因此每个相邻页面视图的执行时间不会晚于上一个页面超过 60 秒。
从概念上讲，您可以将这组页面视图视为用户的导航会话，其中可能包含有关他或她当前正在寻找哪种产品的有趣信息，以便您可以推荐相关产品。

您可以使用以下策略轻松地在 Redis 中对此模式进行建模：每次用户进行页面查看时，您都可以调用以下命令：

[source,text]
----
MULTI
RPUSH pagewviews.user:<userid> http://.....
EXPIRE pagewviews.user:<userid> 60
EXEC
----

如果用户停止阅览超过 60 秒，那么它的导航会话就会被清空，当用户重新开始阅览的时候，系统又会重新记录导航会话，继续进行物品推荐。

这种模式很容易修改为使用 `INCR` 的计数器，而不是使用 `RPUSH` 的列表。

== 附录：Redis 过期

=== Keys 的过期

通常，Redis key 的创建没有关联的生存时间。 该 key 将永远存在，除非用户显式的删除它，例如使用 `DEL` 命令。

`EXPIRE` 系列命令能够将过期时间与给定 key 相关联，但代价是该 key 使用了一些额外的内存。 当某个 key 设置了过期时间时，Redis 将确保在指定的时间后删除该 key。

可以使用 `EXPIRE` 和 `PERSIST` 命令（或其他严格相关的命令）更新或完全删除 key 生存时间。

=== 过期准确率

在 Redis 2.4 版本中，过期时间的延迟在 1 秒钟之内 —— 也即是，就算 key 已经过期，但它还是可能在过期之后一秒钟之内被访问到，而在新的 Redis 2.6 版本中，延迟被降低到 1 毫秒之内。

=== 过期和持久化

key 过期信息存储为绝对 Unix 时间戳（在 Redis 版本 2.6 或更高版本中以毫秒为单位）。这意味着即使 Redis 实例不活动，时间也在流动。

为了使过期功能正常工作，计算机时间必须保持稳定。 如果您从两台时钟严重不同步的计算机上移动 RDB 文件，可能会发生有趣的事情（例如加载的所有 key 在加载时都已过期）。

即使正在运行的实例也会始终检查计算机时钟，因此，例如，如果您将 key 的生存时间设置为 `1000` 秒，然后将计算机时间设置为未来 `2000` 秒，则该密钥将立即过期，而不是持续 `1000` 秒。

=== Redis 如何使密钥过期

Redis 密钥有两种过期方式：被动和主动。

仅当某些客户端尝试访问 key 并且发现 key 已超时时，key 才会被动过期。

当然，这还不够，因为存在永远不会再次访问的过期 key。 无论如何，这些 key 都应该过期，因此 Redis 会定期在设置了过期时间的 key 中随机测试一些 key。 所有已过期的 key 都将从 key 空间中删除。

具体来说，Redis 每秒执行 10 次：

. 测试具有关联过期的 key 集中的 20 个随机 key。
. 删除所有发现过期的 key。
. 如果超过 25% 的 key 已过期，请从步骤 1 重新开始。

这是一个简单的概率算法，基本上假设我们的样本代表整个 key 空间，并且我们继续过期，直到可能过期的 key 的百分比低于 25%

这意味着在任何给定时刻，正在使用内存的已过期 key 的最大数量等于每秒最大写入操作量除以 4。

=== 副本和 AOF 文件中如何处理过期

为了在不牺牲一致性的情况下获得正确的行为，当 key 过期时，会在 AOF 文件中合成 `DEL` 操作并获取所有附加的副本节点。 这样，过期过程就集中在主实例中，并且不会出现一致性错误。

然而，虽然连接到主服务器的副本不会独立使 key 过期（但会等待来自主服务器的 `DEL`），但它们仍然会采用数据集中现有的过期状态的完整状态，因此当副本被选为主服务器时 它将能够独立地使 key 过期，完全充当主设备。

=== 历史

从 Redis 版本 7.0.0 开始：添加了选项：`NX`、`XX`、`GT` 和 `LT`。