= MIGRATE

**语法**

[source,text]
----
MIGRATE host port <key | ""> destination-db timeout [COPY] [REPLACE]
  [AUTH password | AUTH2 username password] [KEYS key [key ...]]
----

**可用版本**：2.6.0

**时间复杂度**：这个命令在源实例上实际执行 `DUMP` 命令和 `DEL` 命令，在目标实例执行 `RESTORE` 命令，查看以上命令的文档可以看到详细的复杂度说明。
key 数据在两个实例之间传输的复杂度为 O(N) 。

**ACL 类别**：**@keyspace, @write, @slow, @dangerous**

将 key 原子性地从当前实例传送到目标实例的指定数据库上，一旦传送成功， key 保证会出现在目标实例上，而当前实例上的 key 会被删除。

这个命令是一个原子操作，它在执行的时候会阻塞进行迁移的两个实例，直到以下任意结果发生：迁移成功，迁移失败，超时。在 3.2 及更高版本中，通过传递空字符串 ("") 作为 key 并添加 `KEYS` 子句，可以在对 `MIGRATE` 的单次调用中对多个 key 进行管道化。

命令的内部实现是这样的：它在当前实例对给定 key 执行 `DUMP` 命令 ，将它序列化，然后传送到目标实例，目标实例再使用 `RESTORE` 对数据进行反序列化，并将反序列化所得的数据添加到数据库中；当前实例就像目标实例的客户端那样，只要看到 `RESTORE` 命令返回 `OK` ，它就会调用 `DEL` 删除自己数据库上的 key 。

`timeout` 参数以毫秒为格式，指定当前实例和目标实例进行沟通的最大间隔时间。这说明操作并不一定要在 `timeout` 毫秒内完成，只是说数据传送的时间不能超过这个 `timeout` 数。

`MIGRATE` 命令需要在给定的时间规定内完成 IO 操作。如果在传送数据时发生 IO 错误，或者达到了超时时间，那么命令会停止执行，并返回一个特殊的错误： `IOERR` 。

当 IOERR 出现时，有以下两种可能：

* key 可能存在于两个实例
* key 可能只存在于当前实例

唯一不可能发生的情况就是丢失 key ，因此，如果一个客户端执行 `MIGRATE` 命令，并且不幸遇上 `IOERR` 错误，那么这个客户端唯一要做的就是检查自己数据库上的 key 是否已经被正确地删除。

如果有其他错误发生（以 ERR 开头），那么 `MIGRATE` 保证 key 只会出现在当前实例中。（当然，目标实例的给定数据库上可能有和 key 同名的键，不过这和 `MIGRATE` 命令没有关系）。

如果源实例中没有要迁移的 key ，则返回 `NOKEY`。 因为在正常情况下（例如过期）可能会丢失 key，所以 `NOKEY` 不是错误。

== 使用单个命令调用迁移多个 key

从 Redis 3.0.6 开始，`MIGRATE` 支持新的批量迁移模式，该模式使用管道在实例之间迁移多个键，而不会产生往返时间延迟以及使用单个 `MIGRATE` 移动每个 key 时产生的其他开销。

为了启用此形式，使用 `KEYS` 选项，并将普通键参数设置为空字符串。 实际的键名称将在 `KEYS` 参数本身之后提供，如下例所示：

[source,text]
----
MIGRATE 192.168.1.34 6379 "" 0 5000 KEYS key1 key2 key3
----

使用此形式时，仅当实例中不存在任何 key 时才返回 `NOKEY` 状态代码，否则即使仅存在一个 key，也会执行命令。

选项

* COPY -- 不要从本地实例中删除 key。
* REPLACE -- 替换远程实例上的现有 key。
* KEYS -- 如果 key 参数是空字符串，该命令将迁移 `KEYS` 选项后面的所有键（有关更多信息，请参阅上面的部分）。
* AUTH -- 使用给定的密码对远程实例进行身份验证。
* AUTH2 -- 使用给定的用户名和密码对进行身份验证（Redis 6 或更高版本的 ACL 身份验证样式）。

== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-simple-strings[简单字符串]: 该命令成功时返回 OK，如果在源实例中未找到 key，则返回 `NOKEY`。

== 历史

从 Redis 版本 3.0.0 开始：添加了 `COPY` 和 `REPLACE` 选项。
从 Redis 版本 3.0.6 开始：添加了 `KEYS` 选项。
从 Redis 版本 4.0.7 开始：添加了 `AUTH` 选项。
从 Redis 版本 6.0.0 开始：添加了 `AUTH2` 选项。
