= WAITAOF

**语法**

[source,text]
----
WAITAOF numlocal numreplicas timeout
----

**可用版本**：7.2.0

**时间复杂度**：O(1)

**ACL 类别**：**@slow, @connection**

此命令会阻塞当前客户端，直到确认该客户端之前的所有写入命令已同步到本地 Redis 的 AOF 和/或至少指定数量的副本。 如果达到以毫秒为单位指定的超时，则即使未满足指定的确认数量，该命令也会返回。

该命令将始终返回在 WAITAOF 命令之前已同步当前客户端发送的所有写入命令的主节点和副本节点的数量，无论是满足指定阈值的情况还是达到超时的情况。

几点说明：

* 当 WAITAOF 返回时，在当前连接的上下文中发送的所有先前写入命令都保证被 fsynced 到至少由 `WAITAOF` 返回的主副本数量的 AOF。
* 如果该命令作为 MULTI 事务（或任何其他不允许阻塞的上下文，例如内部脚本）的一部分发送，则该命令不会阻塞，而是立即返回 fsynced 所有先前写入命令的主节点和副本的数量。
* 超时为 0 意味着永远阻塞。
* 由于 `WAITAOF` 在成功和超时的情况下都会返回完成的 fsynced 数量，因此客户端应检查返回的值是否等于或大于所需的持久性级别。
* `WAITAOF` 不能在副本实例上使用，并且如果本地 Redis 未启用 AOF，则 numlocal 参数不能为非零。

== 局限性

可以编写一个模块或 Lua 脚本来将写入传播到 AOF 但不传播到复制流。 （对于模块，这是使用 `RedisModule_Call` 或 `RedisModule_Replicate` 的 `fmt` 参数完成的；对于 Lua 脚本，这是使用 `redis.set_repl` 实现的。）

这些功能与当前实现的 `WAITAOF` 命令不兼容，组合使用它们可能会导致不正确的行为。

== WAITAOF 一致性

请注意，与 `WAIT` 类似，`WAITAOF` 并不使 Redis 成为强一致性存储。 除非等待集群的所有成员将写入同步到磁盘，否则在故障转移或 Redis 重新启动期间数据仍然可能丢失。 然而，WAITAOF 确实提高了现实世界的数据安全性。

== 实现细节

从 Redis 7.2 开始，即使没有配置副本（只要存在 AOF），Redis 也会跟踪并增加复制偏移量。

此外，Redis 副本使用两个复制偏移量异步 ping 其主节点：它们在复制流中处理的偏移量，以及它们已 fsynced 到 AOF 的偏移量。

对于每个客户端，Redis 都会记住在该客户端上下文中执行最后一个写入命令时所生成的复制流的复制偏移量。 当调用 WAITAOF 时，Redis 会检查本地 Redis 和/或指定数量的副本是否已确认将此偏移量或更大的偏移量同步到其 AOF。


== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-arrays[数组]: 该命令返回一个由两个整数组成的数组：第一个是已将当前连接上下文中执行的所有写入 fsynced 到 AOF 的本地 Redis 数量（0 或 1）； 第二个是已确认执行相同操作的副本数量。


== 示例

[source,text]
----
> SET foo bar
OK
> WAITAOF 1 0 0
1) (integer) 1
2) (integer) 0
> WAITAOF 0 1 1000
1) (integer) 1
2) (integer) 0
----

在上面的例子中，第一次调用 `WAITAOF` 不使用超时，只要求写入 `fsynced` 到本地 Redis； 完成后返回 [1, 0]。

在第二次尝试中，我们改为指定超时，并要求写入被单个副本确认为 `fsynced`。 由于没有连接的副本，WAITAOF 命令在一秒后解除阻塞，并再次返回 [1, 0]，表示写入已在本地 Redis 上进行 fsynced，但没有副本。
