= WAIT

**语法**

[source,text]
----
WAIT numreplicas timeout
----

**可用版本**：3.0.0

**时间复杂度**：O(1)

**ACL 类别**：**@slow, @connection**

此命令会阻塞当前客户端，直到所有先前的写入命令均已成功传输并至少被指定数量的副本确认为止。 如果达到以毫秒为单位指定的超时，即使尚未达到指定的副本数量，该命令也会返回。

该命令将始终返回在 `WAIT` 命令之前确认当前客户端发送的写入命令的副本数，无论是在达到指定副本数的情况下，还是在达到超时时。

几点说明：

* 当 `WAIT` 返回时，在当前连接的上下文中发送的所有先前写入命令都保证被 `WAIT` 返回的副本数量接收。
* 如果该命令作为 `MULTI` 事务的一部分发送（自 Redis 7.0 起，任何不允许阻塞的上下文，例如内部脚本），该命令不会阻塞，而是仅返回 `ASAP` 确认先前写入命令的副本数量 。
* 超时为 `0` 意味着永远阻塞。
* 由于 `WAIT` 返回在失败和成功情况下达到的副本数量，因此客户端应检查返回的值是否等于或大于其所需的复制级别。

== WAIT 一致性

请注意，`WAIT` 并不使 Redis 成为强一致性存储：虽然同步复制是复制状态机的一部分，但它并不是唯一需要的东西。 然而，在 Sentinel 或 Redis 集群故障转移的情况下，WAIT 提高了现实世界的数据安全性。

具体来说，如果给定的写入传输到一个或多个副本，则更有可能（但不能保证）如果主服务器发生故障，我们将能够在故障转移期间提升接收写入的副本：Sentinel 和 Redis 集群将尽最大努力在可用副本集中提升最佳副本。

然而，这只是尽力而为的尝试，因此仍然可能会丢失同步复制到多个副本的写入。

== 实现细节

自从引入了与副本的部分重新同步（PSYNC 功能）以来，Redis 副本会使用它们已在复制流中处理的偏移量异步 ping 其主服务器。 这有多种用途：

* 检测超时的副本。
* 断开连接后执行部分重新同步。
* 实现 WAIT。

在实现 WAIT 的特定情况下，Redis 会为每个客户端记住在给定客户端的上下文中执行给定写入命令时生成的复制流的复制偏移量。 当调用 WAIT 时，Redis 会检查指定数量的副本是否已确认此偏移量或更大的偏移量。

== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-integers[整数]: 该命令返回当前连接上下文中执行的所有写入所达到的副本数。.


== 示例

[source,text]
----
> SET foo bar
OK
> WAIT 1 0
(integer) 1
> WAIT 2 1000
(integer) 1
----

在以下示例中，对 WAIT 的第一次调用不使用超时，并要求写入到达 1 个副本。 它成功返回。 在第二次尝试中，我们设置了超时，并要求将写入复制到两个副本。 由于只有一个副本可用，一秒后 WAIT 解除阻塞并返回 1，即已达到的副本数量。
