// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[custom_plugins]]
= 开发自定义 Gradle 插件

Gradle 插件打包了可重用的构建逻辑,可在许多不同的项目和构建中使用. Gradle 允许您实现自己的插件,因此您可以重复使用构建逻辑,并与他人共享.

您可以使用任何喜欢的语言来实现 Gradle 插件,前提是该语言最终可以被编译为 JVM 字节码. 在我们的示例中,我们将使用 Java 作为独立插件项目的实现语言,并在 buildscript 插件示例中使用 Groovy 或 Kotlin.
通常,使用 Java 或 Kotlin (静态类型) 实现的插件比使用 Groovy 实施的插件性能更好.

[[sec:packaging_a_plugin]]
== 打包插件

您可以在几个地方放置插件的源代码.

Build script::
您可以直接在构建脚本中包含插件的源代码. 这样的好处是,无需执行任何操作即可自动编译插件并将其包含在构建脚本的类路径中. 但是,该插件在构建脚本之外不可见,因此您不能在定义该构建脚本的外部重用该插件.

`buildSrc` 项目::
您可以将任务类的源代码放在 `__rootProjectDir__/buildSrc/src/main/java` 目录中 (或者 `__rootProjectDir__/buildSrc/src/main/groovy` 或 `__rootProjectDir__/buildSrc/src/main/kotlin`  具体取决于您喜欢哪种语言). 
Gradle 将负责编译和测试 task 类,并使其在构建脚本的类路径中可用.task 类对生成所使用的每个生成脚本都是可见的.但是,它在构建之外是不可见的,因此您不能在其定义的构建之外重重用该插件.
+
有关 `buildSrc` 项目的更多详细信息,请参见 <<organizing_gradle_projects.adoc#organizing_gradle_projects,Organizing Gradle Projects>>.

Standalone project::
您可以为插件创建一个单独的项目. 这个项目产生并发布了一个 JAR,您可以在多个版本中使用它并与他人共享. 通常,此 JAR 可能包含一些插件,或将几个相关的任务类捆绑到一个库中. 或两者的某种组合.

在我们的示例中,我们将从构建脚本中的插件开始,然后,我们将考虑创建一个独立的项目.

[[sec:writing_a_simple_plugin]]
== 编写一个简单的 plugin

要创建 Gradle 插件,您需要编写一个实现 link:{javadocPath}/org/gradle/api/Plugin.html[Plugin] 接口的类. 将插件应用于项目后,Gradle 会创建插件类的实例,并调用该实例的 link:{javadocPath}/org/gradle/api/Plugin.html#apply-T-[Plugin.apply()] 方法.
项目对象作为参数传递,插件可以使用该参数配置项目,但需要这样做. 下面的示例包含一个 Greeting 插件,该插件向项目添加了 `hello` 任务.

.A custom plugin
====
include::{snippets-dir}/customPlugins/customPlugin/groovy/build.gradle[]
include::{snippets-dir}/customPlugins/customPlugin/kotlin/build.gradle.kts[]
====

.**`gradle -q hello`** 的输出
----
> gradle -q hello
include::{snippets-dir}/customPlugins/customPlugin/tests/customPlugin.out[]
----

需要注意的一件事是,将为每个应用插件的项目创建一个插件的新实例. 另请注意,link:{javadocPath}/org/gradle/api/Plugin.html[Plugin] 类是泛型类型.
此示例接收 link:{groovyDslPath}/org.gradle.api.Project.html[Project] 类型作为类型参数. 插件可以改为接收类型为 link:{groovyDslPath}/org.gradle.api.initialization.Settings.html[Settings] 的参数 (在这种情况下,该插件可以应用在设置脚本中) 或参数类型为  link:{groovyDslPath}/org.gradle.api.invocation.Gradle.html[Gradle] 的参数,
在这种情况下,可以将插件应用在初始化脚本中.

[[sec:getting_input_from_the_build]]
== 使插件可配置

大多数插件为构建脚本提供了一些配置选项,其他插件则用于自定义插件的工作方式. 插件使用扩展对象执行此操作. Gradle 项目具有一个关联的 link:{groovyDslPath}/org.gradle.api.Project.html[Project] has an associated link:{javadocPath}/org/gradle/api/plugins/ExtensionContainer.html[ExtensionContainer] 对象,
该对象包含已应用于该项目的插件的所有设置和属性. 您可以通过向该容器添加扩展对象来为您的插件提供配置. 扩展对象只是具有表示配置的 Java Bean 属性的对象.

Most plugins offer some configuration options for build scripts and other plugins to use to customize how the plugin works. Plugins do this using _extension objects_.
The Gradle  object
that contains all the settings and properties for the plugins that have been applied to the project.
You can provide configuration for your plugin by adding an extension object to this container.
An extension object is simply an object with Java Bean properties that represent the configuration.

让我们向项目添加一个简单的扩展对象.在这里,我们向项目添加了 `greeting` 扩展对象,该对象使您可以配置 greeting.

.A custom plugin extension
====
include::{snippets-dir}/customPlugins/customPluginWithConvention/groovy/build.gradle[]
include::{snippets-dir}/customPlugins/customPluginWithConvention/kotlin/build.gradle.kts[]
====

.**`gradle -q hello`** 的输出
----
> gradle -q hello
include::{snippets-dir}/customPlugins/customPluginWithConvention/tests/customPluginWithConvention.out[]
----

在此示例中,`GreetingPluginExtension` 是一个具有 `message` 的属性的对象. 扩展对象以 `greeting` 添加到项目中. 然后,该对象可用作与扩展对象同名的项目属性.

通常,您需要在单个插件上指定多个相关属性. Gradle 为每个扩展对象添加一个配置块,因此您可以将设置分组在一起.以下示例向您展示了它是如何工作的.

.A custom plugin with configuration block
====
include::{snippets-dir}/customPlugins/customPluginWithAdvancedConvention/groovy/build.gradle[]
include::{snippets-dir}/customPlugins/customPluginWithAdvancedConvention/kotlin/build.gradle.kts[]
====

.**`gradle -q hello`** 的输出
----
> gradle -q hello
include::{snippets-dir}/customPlugins/customPluginWithAdvancedConvention/tests/customPluginWithAdvancedConvention.out[]
----

[.multi-language-text.lang-groovy]
在此示例中,可以将几个设置组合在  `greeting` closure 闭包中. 构建脚本中的闭包块名称 (`greeting`) 需要与扩展对象名称匹配. 然后,在执行闭包时,扩展对象上的字段将根据标准的 Groovy 闭包委托特性映射到闭包内的变量.

这样,使用扩展对象可以扩展 Gradle DSL,从而为插件添加项目属性和 DSL 块. 因为扩展对象只是一个普通对象,所以可以通过向扩展对象添加属性和方法来提供嵌套在插件块中的 DSL.

[.multi-language-text.lang-kotlin]
在此示例中,几个设置可以在 `configure`  `configure<GreetingPluginExtension>` block 中组合在一起. 构建脚本中配置函数使用的类型 (`GreetingPluginExtension`) 需要匹配扩展类型.然后,当执行块时,块的接收方是扩展.

=== 开发项目扩展

您可以在  <<custom_gradle_types.adoc#custom_gradle_types,Developing Custom Gradle Types>> 中找到有关实现项目扩展的更多信息.

[[sec:working_with_files_in_custom_tasks_and_plugins]]
== 在自定义任务和插件中处理文件

在开发自定义任务和插件时,最好在接受文件位置的输入配置时非常灵活. 为此,您可以利用 link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:file(java.lang.Object)[Project.file(java.lang.Object)] 方法尽可能晚地将值解析为文件.

.Evaluating file properties lazily
====
include::{snippets-dir}/tasks/customTaskWithFileProperty/groovy/build.gradle[tags=all]
include::{snippets-dir}/tasks/customTaskWithFileProperty/kotlin/build.gradle.kts[tags=all]
====

.**`gradle -q sayGreeting`** 的输出
----
> gradle -q sayGreeting
include::{snippets-dir}/tasks/customTaskWithFileProperty/tests/lazyFileProperties.out[]
----

在本例中,我们将 `greet`  任务 `destination` 属性配置为一个 closure/provider,它将通过 link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:file(java.lang.Object)[Project.file(java.lang.Object)]  方法进行评估,以便在最后一刻将闭包/提供程序的返回值转换为一个 `File` 对象.
您将注意到,在上面的示例中,我们在配置为对任务使用 `greetingFile` 属性值之后指定了它.这种惰性计算是在设置文件属性时接受任何值,然后在读取属性时解析该值的一个关键好处.

[[sec:mapping_extension_properties_to_task_properties]]
== 将扩展属性映射到任务属性

从构建脚本通过扩展捕获用户输入并将其映射到自定义任务的输入/输出属性是一种有用的模式. 构建脚本作者仅与扩展定义的 DSL 交互. 命令式逻辑隐藏在插件实现中.

Gradle 提供了一些类型,您可以在任务实现和扩展中使用这些类型来帮助您. 有关更多信息,请参考 <<lazy_configuration.adoc#lazy_configuration,Lazy Configuration>> .

[[sec:custom_plugins_standalone_project]]
== 一个独立的项目

现在,我们将插件移至独立项目,以便我们可以发布它并与他人共享. 这个项目只是一个 Java 项目,它产生包含插件类的 JAR. 打包和发布插件的最简单且推荐的方法是使用 <<java_gradle_plugin.adoc#java_gradle_plugin,Java Gradle Plugin Development Plugin>>.
该插件将自动应用  <<java_plugin.adoc#java_plugin,Java Plugin>>,将 `gradleApi()` 依赖添加到 api 配置中,在生成的 JAR 文件中生成所需的插件描述符,并配置要在发布时使用的插件 <<plugins.adoc#sec:plugin_markers,Plugin Marker Artifact>>.
这是该项目的简单构建脚本.

.A build for a custom plugin
====
include::{snippets-dir}/plugins/customPlugin/groovy/java-gradle-plugin/build.gradle[tags=use-and-configure-plugin]
include::{snippets-dir}/plugins/customPlugin/kotlin/java-gradle-plugin/build.gradle.kts[tags=use-and-configure-plugin]
====

[[sec:creating_a_plugin_id]]
=== 创建一个插件 id

Plugin ids  以类似于 Java 软件包的方式 (即反向域名) 完全合格. 这有助于避免冲突,并提供了一种将具有相似所有权的插件分组的方法.

您的插件 ID 应该是反映命名空间 (指向您或您的组织的合理指针) 的组件及其提供的插件名称的组合. 例如,如果您有一个名为 "foo" 的 Github 帐户,而您的插件名为 "bar",则合适的插件 ID 可能是 `com.github.foo.bar`.
同样,如果插件是由 baz 组织开发的,则插件ID可能是 `org.baz.bar`.

插件ID应符合以下条件:

* 可以包含任何字母数字, '.', and '-'.
* 必须至少包含一个 '.' 分隔命名空间和插件名称的字符.
* 按照惯例,对命名空间使用小写的反向域名约定
* 通常,名称中仅使用小写字符
* 不能使用 `org.gradle` 和 `com.gradleware` 命名空间
* 不能以 '.' 开头或结尾.
* 不能包含连续的 '.'  (i.e. '..').

尽管插件 ID 和程序包名称之间存在常规的相似之处,但通常包名称比插件 ID 所必需的更为详细. 例如,在您的插件 ID 中添加 "gradle" 作为组件似乎是合理的,但是由于插件 ID 仅用于 Gradle 插件,因此这是多余的.
通常,一个良好的插件 ID 只需要一个用于标识所有权和名称的命名空间.

[[sec:publishing_your_plugin]]
=== 发布您的插件

如果要在内部发布插件供组织内部使用,则可以像其他任何代码 artifacts 一样发布它. 请参阅有关发布 artifacts 的  <<publishing_ivy.adoc#publishing_ivy,Ivy>> 和 <<publishing_maven.adoc#publishing_maven,Maven>> 章节.

如果您有兴趣发布供更广泛的 Gradle 社区使用的插件,则可以将其发布到 http://plugins.gradle.org[Gradle Plugin Portal]. 该站点提供了搜索和收集有关 Gradle 社区贡献的插件的信息的功能. 请参阅相应的  https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/[guide] ,以了解如何在此站点上使用您的插件.

[[sec:using_your_plugin_in_another_project]]
=== 在另一个项目中使用您的插件

要在构建脚本中使用插件,您需要在项目设置文件的 `pluginManagement {}` 块中配置存储库. 以下示例显示了将插件发布到本地存储库后如何执行此操作:

.Using a custom plugin in another project
====
include::{snippets-dir}/plugins/customPlugin/groovy/consumer/settings.gradle[tags=use-plugin]
include::{snippets-dir}/plugins/customPlugin/groovy/consumer/build.gradle[tags=use-plugin]
include::{snippets-dir}/plugins/customPlugin/kotlin/consumer/settings.gradle.kts[tags=use-plugin]
include::{snippets-dir}/plugins/customPlugin/kotlin/consumer/build.gradle.kts[tags=use-plugin]
====

==== 没有 `java-gradle-plugin` 发布的插件的注意事项

如果您的插件是在未使用<<java_gradle_plugin.adoc#java_gradle_plugin,Java Gradle Plugin Development Plugin>> 插件的情况下发布的,则发布的 Artifact 缺少 <<plugins.adoc#sec:plugin_markers,Plugin Marker Artifact>>,
这是  <<plugins.adoc#sec:plugins_block,plugins DSL>> 查找插件所需的. 在这种情况下,建议的在其他项目中解析插件的方法是在该项目的设置文件的  `pluginManagement {}` 块中添加 `resolutionStrategy` 部分,如下所示.

.Resolution strategy for plugins without Plugin Marker Artifact
====
include::{snippets-dir}/plugins/customPlugin/groovy/consumer/settings.gradle[tags=use-legacy-plugin]
include::{snippets-dir}/plugins/customPlugin/kotlin/consumer/settings.gradle.kts[tags=use-legacy-plugin]
====

[[sec:precompiled_plugins]]
== 预编译脚本插件

除了作为独立项目编写的插件外,Gradle 还允许您提供用 Groovy 或 Kotlin dsl 编写的构建逻辑,作为预编译的脚本插件.您可以将它们写为 `src/main/groovy` 目录中的 `\*.gradle` 文件或 `src/main/kotlin` 目录中的 `*.gradle.kts` 文件.

预编译的脚本插件被编译成类文件并打包到 jar 中.无论出于何种目的,它们都是二进制插件,可以通过插件ID应用,并作为二进制插件进行测试和发布.事实上,插件元数据是使用 <<java_gradle_plugin#java_gradle_plugin,Gradle Plugin Development Plugin>> 插件生成的.

[NOTE]
====
Gradle 6.0 内置的 Kotlin DSL 预编译脚本插件不能与 Gradle 的早期版本一起使用. 在 Gradle 的未来版本中将取消此限制.

Groovy DSL 预编译脚本插件从 Gradle 6.4 开始可用.
====








[.multi-language-text.lang-groovy]
要应用预编译的脚本插件,您需要知道其 ID,该 ID 是从插件脚本的文件名 (减去 `.gradle` 扩展名)

[.multi-language-text.lang-kotlin]
要应用预编译的脚本插件,您需要知道其 ID,该 ID 是从插件脚本的文件名 (减去 `.gradle.kts` 扩展名) 及其包声明 (可选) 扩展 而来的.

[.multi-language-text.lang-groovy]
例如,脚本 `src/main/groovy/java-library-convention.gradle` 的插件 ID 为 `java-library-convention`. 同样, `src/main/groovy/my.java-library-convention.gradle` 将产生 `my.java-library-convention` 的插件 ID.

[.multi-language-text.lang-kotlin]
例如,脚本 `src/main/kotlin/java-library-convention.gradle.kts` 的插件 ID 为 `java-library-convention` (假设它没有包声明) .
同样,只要 `src/main/kotlin/my/java-library-convention.gradle.kts` 的软件包声明为 `my`,其插件 ID 为 `my.java-library-convention`.

为了演示如何实现和使用预编译的脚本插件,让我们来看一个基于 `buildSrc` 项目的示例.

[.multi-language-text.lang-groovy]
首先,您需要一个应用 `groovy-gradle-plugin` 插件的 `buildSrc/build.gradle` 文件:

[.multi-language-text.lang-kotlin]
首先,您需要一个应用 `kotlin-dsl` 插件的 `buildSrc/build.gradle.kts`  文件:

.Enabling precompiled script plugins
====
include::{snippets-dir}/plugins/precompiledScriptPlugins-inBuildSrc/groovy/buildSrc/build.gradle[tags=apply]
include::{snippets-dir}/plugins/precompiledScriptPlugins-inBuildSrc/kotlin/buildSrc/build.gradle.kts[tags=apply]
====

[.multi-language-text.lang-groovy]
我们建议您还创建一个 `buildSrc/settings.gradle` 文件,您可以将其保留为空.

[.multi-language-text.lang-kotlin]
我们建议您还创建一个 `buildSrc/settings.gradle.kts` 文件,您可以将其保留为空.

[.multi-language-text.lang-groovy]
接下来,在 `buildSrc/src/main/groovy` 目录中创建一个新的 `java-library-convention.gradle` 文件,并将其内容设置为以下内容:

[.multi-language-text.lang-kotlin]
接下来,在 `buildSrc/src/main/kotlin`目录中创建一个新的 `java-library-convention.gradle.kts` 文件,并将其内容设置为以下内容:

.Creating a simple script plugin
====
include::{snippets-dir}/plugins/precompiledScriptPlugins-inBuildSrc/groovy/buildSrc/src/main/groovy/java-library-convention.gradle[]
include::{snippets-dir}/plugins/precompiledScriptPlugins-inBuildSrc/kotlin/buildSrc/src/main/kotlin/java-library-convention.gradle.kts[]
====

该脚本插件仅应用Java库和Checkstyle插件并对其进行配置. 请注意,这实际上会将插件应用于主项目,即应用预编译脚本插件的插件.

最后,将脚本插件应用于根项目,如下所示:

.Applying the precompiled script plugin to the main project
====
include::{snippets-dir}/plugins/precompiledScriptPlugins-inBuildSrc/groovy/build.gradle[]
include::{snippets-dir}/plugins/precompiledScriptPlugins-inBuildSrc/kotlin/build.gradle.kts[]
====

=== 在预编译的脚本插件中应用外部插件
为了在预编译的脚本插件中应用外部插件,必须将其添加到插件的构建文件中的插件项目的实现类路径中.
====
include::{snippets-dir}/plugins/precompiledScriptPlugins-externalPlugins/groovy/buildSrc/build.gradle[]
include::{snippets-dir}/plugins/precompiledScriptPlugins-externalPlugins/kotlin/buildSrc/build.gradle.kts[]
====

然后可以将其应用在预编译的脚本插件中.
====
include::{snippets-dir}/plugins/precompiledScriptPlugins-externalPlugins/groovy/buildSrc/src/main/groovy/my-plugin.gradle[]
include::{snippets-dir}/plugins/precompiledScriptPlugins-externalPlugins/kotlin/buildSrc/src/main/kotlin/my-plugin.gradle.kts[]
====

在这种情况下,插件版本在依赖声明中定义.

在将来的 Gradle 版本中将删除此限制.

[[sec:writing_tests_for_your_plugin]]
== 为您的插件编写测试

您可以使用 link:{javadocPath}/org/gradle/testfixtures/ProjectBuilder.html[ProjectBuilder]  类创建要在测试插件实现时使用的 link:{groovyDslPath}/org.gradle.api.Project.html[Project] 实例.

=== Example: Testing a custom plugin

[source.multi-language-sample,java]
.src/test/java/org/gradle/GreetingPluginTest.java
----
include::{snippets-dir}/plugins/customPlugin/groovy/plugin/src/test/java/org/gradle/GreetingPluginTest.java[tag=test-plugin]
----

== 更多细节

插件通常还提供自定义任务类型. 有关更多详细信息,请参见 <<custom_tasks.adoc#custom_tasks,Developing Custom Gradle Task Types>>.

Gradle 提供了许多在开发 Gradle 类型 (包括插件) 时有用的功能. 有关更多详细信息,请参见 <<custom_gradle_types.adoc#custom_gradle_types,Developing Custom Gradle Types>>.

CAUTION: 在开发 Gradle 插件时,将信息记录到构建日志中时请务必小心. 记录敏感信息 (例如凭据,令牌,某些环境变量)  <<logging.adoc#sec:debug_security,被视为安全漏洞>> .
公共持续集成服务的构建日志在世界范围内可见,并且可以公开此敏感信息.

== 最后

那么 Gradle 是如何找到 link:{javadocPath}/org/gradle/api/Plugin.html[Plugin] 实现的呢?答案是——您需要在 JAR 的 `META-INF/gradle-plugins` 目录中提供一个与插件id匹配的属性文件,
该文件由 <<java_gradle_plugin.adoc#java_gradle_plugin,Java Gradle Plugin Development Plugin>> 处理

=== Example: Wiring for a custom plugin

[source,properties]
.src/main/resources/META-INF/gradle-plugins/org.samples.greeting.properties
----
include::{snippets-dir}/plugins/customPlugin/groovy/plugin/src/main/resources/META-INF/gradle-plugins/org.samples.greeting.properties[]
----

请注意,属性文件名与插件 ID 匹配,并放置在资源文件夹中,并且 `implementation-class` 属性标识 link:{javadocPath}/org/gradle/api/Plugin.html[Plugin] 实现类
