// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[custom_tasks]]
= 开发自定义 Gradle 任务类型

Gradle 支持两种类型的任务。 其中一种类型是 simple task，其中使用 action 闭包定义任务。 我们已经在 <<tutorial_using_tasks.adoc#tutorial_using_tasks,Build Script Basics>> 中看到了这些。
对于这种类型的任务，action 闭包确定任务的行为。 这种类型的任务非常适合在构建脚本中实现一次性任务。

任务的另一种类型是增强型任务，其中行为内置于任务中，并且该任务提供了一些可用于配置行为的属性。 我们已经在  <<more_about_tasks.adoc#more_about_tasks,Authoring Tasks>> 中看到了这些。
大多数 Gradle 插件使用增强的任务。 使用增强型任务，您无需像处理简单任务那样实现任务行为。 您只需声明任务并使用其属性配置任务。 通过这种方式，增强型的任务使您可以在许多不同的地方（可能跨不同的构建）重用某种行为。

增强型任务的行为和属性由任务的类定义。 声明增强的任务时，可以指定任务的类型或类。

在 Gradle 中实现自己的自定义任务类很容易。 您可以使用任何您喜欢的语言来实现自定义任务类，只要最终将其编译为 JVM 字节码即可。 在我们的示例中，我们将使用 Groovy 作为实现语言。 Groovy，Java 或 Kotlin 都是用于实现 task 类的语言，都是不错的选择，因为 Gradle API 被设计为可以与这些语言很好地配合使用。 通常，使用 Java 或 Kotlin（静态类型）实现的任务将比使用 Groovy 实现的任务执行得更好。

[[sec:packaging_a_task_class]]
== 打包 task class

有几个地方可以放置 task 类的源代码。.

Build script::
您可以将 task 类直接包含在构建脚本中。 这样的好处是，task 类将自动编译并包含在构建脚本的类路径中，而无需执行任何操作。 但是，task 类在构建脚本之外不可见，因此您不能在定义该任务的构建脚本之外重用该 task 类。

`buildSrc` project::
您可以将任务类的源代码放在 `__rootProjectDir__/buildSrc/src/main/groovy` 目录中 (或者 `__rootProjectDir__/buildSrc/src/main/java` 或 `__rootProjectDir__/buildSrc/src/main/kotlin` 具体取决于您喜欢哪种语言). 
Gradle 将负责编译和测试 task 类，并使其在构建脚本的类路径中可用。task 类对生成所使用的每个生成脚本都是可见的。但是，它在构建之外是不可见的，因此您不能在其定义的构建之外重用 task 类。使用 buildSrc 项目方法将任务声明(即任务应该做什么)与任务实现(即任务如何执行)分离开来。
+
有关 `buildSrc` 项目的更多详细信息，请参见 <<organizing_gradle_projects.adoc#organizing_gradle_projects,Organizing Gradle Projects>>。

Standalone project::
您可以为任务类创建一个单独的项目。 并发布了一个 JAR，您可以在多个版本中使用它并与他人共享。 通常，此 JAR 可能包含一些自定义插件，或将几个相关的任务类捆绑到一个库中。 或两者的某种组合。

在我们的示例中，我们将从构建脚本中的 task 类开始。然后，我们将考虑创建一个独立的项目。

[[sec:writing_a_simple_task_class]]
== 编写一个简单的 task class

要实现自定义任务类，可以扩展 link:{groovyDslPath}/org.gradle.api.DefaultTask.html[DefaultTask].

.Defining a custom task
====
include::{snippets-dir}/tasks/customTask/groovy/build.gradle[tags=define-task]
include::{snippets-dir}/tasks/customTask/kotlin/build.gradle.kts[tags=define-task]
====

该任务没有做任何事情，所以让我们添加一些行为。 为此，我们向此任务添加一个方法，并使用 link:{javadocPath}/org/gradle/api/tasks/TaskAction.html[TaskAction] 注解对其进行标记。 任务执行时，Gradle 将调用该方法。 您不必使用方法来定义任务的行为。
例如，您可以在任务构造函数中使用闭包调用 `doFirst()` 或 `doLast()` 以添加行为。

.A hello world task
====
include::{snippets-dir}/tasks/customTask/groovy/build.gradle[tags=add-action]
include::{snippets-dir}/tasks/customTask/kotlin/build.gradle.kts[tags=add-action]
====

.**`gradle -q hello`** 的输出
----
> gradle -q hello
include::{snippets-dir}/tasks/customTask/tests/customTaskWithAction.out[]
----

让我们为任务添加一个属性，以便我们对其进行自定义。 任务只是简单的 POGO，声明任务时，可以在任务对象上设置属性或调用方法。 在这里，我们添加了 `greeting` 属性，并在声明 `greeting` 任务时设置该值。

.A customizable hello world task
====
include::{snippets-dir}/tasks/customTaskWithProperty/groovy/build.gradle[tags=add-property]
include::{snippets-dir}/tasks/customTaskWithProperty/kotlin/build.gradle.kts[tags=add-property]
====

.**`gradle -q hello greeting`** 的输出
----
> gradle -q hello greeting
include::{snippets-dir}/tasks/customTaskWithProperty/tests/customTaskWithProperty.out[]
----


[[sec:custom_tasks_standalone_project]]
== 一个独立的项目

现在，我们将把任务移到一个独立的项目中，以便我们可以发布并与他人共享。 这个项目只是一个 Groovy 项目，它由一个包含 task 类的 JAR 组成。 这是该项目的简单构建脚本。
它应用了 Groovy 插件，并将 Gradle API 添加为编译时依赖。

.A build for a custom task
====
include::{snippets-dir}/base/customExternalTask/groovy/task/build.gradle[tags=external-task-build]
include::{snippets-dir}/base/customExternalTask/kotlin/task/build.gradle.kts[tags=external-task-build]
====


遵循 task 类源码应该放在哪里的约定.

=== Example: 自定义 task

[source.multi-language-sample,groovy]
.src/main/groovy/org/gradle/GreetingTask.groovy
----
include::{snippets-dir}/base/customExternalTask/groovy/task/src/main/groovy/org/gradle/GreetingTask.groovy[]
----

[[sec:using_your_task_class_in_another_project]]
=== 在另一个项目中使用 task 类

要在构建脚本中使用任务类，您需要将该类添加到构建脚本的类路径中。 为此，请使用 `buildscript { }` ，如 <<tutorial_using_tasks.adoc#sec:build_script_external_dependencies,构建脚本的外部依赖>> 中所述。 以下示例显示了包含已发布到本地仓库 task 类的 JAR 时如何执行此操作：

.Using a custom task in another project
====
include::{snippets-dir}/base/customExternalTask/groovy/consumer/build.gradle[tags=use-task]
include::{snippets-dir}/base/customExternalTask/kotlin/consumer/build.gradle.kts[tags=use-task]
====

[[sec:writing_tests_for_your_task_class]]
=== 为 task 类编写测试

您可以使用 link:{javadocPath}/org/gradle/testfixtures/ProjectBuilder.html[ProjectBuilder] 类创建在测试 task 类时要使用的 link:{groovyDslPath}/org.gradle.api.Project.html[Project] 实例。

=== Example: 测试自定义 task

[source.multi-language-sample,groovy]
.src/test/groovy/org/gradle/GreetingTaskTest.groovy
----
include::{snippets-dir}/base/customExternalTask/groovy/task/src/test/groovy/org/gradle/GreetingTaskTest.groovy[tag=test-task]
----

[[incremental_tasks]]
== 增量任务

使用Gradle，可以很容易地实现一个任务，当它的所有输入和输出都是最新的时将被跳过（请参阅 <<more_about_tasks.adoc#sec:up_to_date_checks,增量构建>>）。
但是，自上次执行以来，有时只有少数输入更改，因此您希望避免重新处理所有未更改的输入。 这对于已经更改的 1:1 转换为输出的转换器任务特别有用。

如果您想优化构建，以便仅处理过时的输入文件，则可以执行增量任务。

[NOTE]
====
有 link:{javadocPath}/org/gradle/api/tasks/incremental/IncrementalTaskInputs.html[IncrementalTaskInputs] API，在 5.4 之前的 Gradle 版本中可用。 使用 link:{javadocPath}/org/gradle/api/tasks/incremental/IncrementalTaskInputs.html[IncrementalTaskInputs] 时，
只能查询任务输入的所有文件更改。 无法查询各个输入文件属性的更改。 而且，旧的 API 不能区分增量任务输入和非增量任务输入，因此任务本身需要确定更改的来源。 因此，不建议使用此 API，并最终将其删除。
本文记录了新的 link:{groovyDslPath}/org.gradle.work.InputChanges.html[InputChanges] API，它取代了旧的API并解决了其缺点。 如果需要使用旧的API，请查看 link:https://docs.gradle.org/5.3.1/userguide/custom_tasks.html#incremental_tasks[Gradle 5.3.1 用户手册中的文档]。
====

[[sec:implementing_an_incremental_task]]
=== 实现增量任务

为了使任务能够处理增量输入，该任务必须包含一个增量任务动作。 也就是具有 link:{groovyDslPath}/org.gradle.work.InputChanges.html[InputChanges] 参数的任务操作方法。
该参数告诉 Gradle 该操作仅想处理更改的输入。 此外，任务需要使用 link:{javadocPath}/org/gradle/work/Incremental.html[@Incremental] 或 link:{javadocPath}/org/gradle/api/tasks/SkipWhenEmpty.html[@SkipWhenEmpty] 声明至少一个增量文件输入属性。

[IMPORTANT]
====
要查询输入文件属性的增量更改，该属性始终需要返回相同的实例。 完成此操作的最简单方法是对此类属性使用以下类型之一：link:{javadocPath}/org/gradle/api/file/RegularFileProperty.html[RegularFileProperty], link:{javadocPath}/org/gradle/api/file/DirectoryProperty.html[DirectoryProperty] or link:{javadocPath}/org/gradle/api/file/ConfigurableFileCollection.html[ConfigurableFileCollection].


您可以在 <<lazy_configuration#lazy_configuration,Lazy Configuration>>  一章中了解有关 `RegularFileProperty` 和 `DirectoryProperty` 的更多信息，尤其是有关 <<lazy_configuration#lazy_properties,使用只读配置属性>>  以及 <<lazy_configuration#working_with_files_in_lazy_properties,lazy file properties>> 的部分。
====

增量任务操作可以使用 link:{groovyDslPath}/org.gradle.work.InputChanges.html#org.gradle.work.InputChanges:getFileChanges(org.gradle.api.file.FileCollection)[InputChanges.getFileChanges()] 来查找哪些文件已更改为给定的基于文件的输入属性，
类型为 `RegularFileProperty`, `DirectoryProperty` or `ConfigurableFileCollection`. 该方法返回 link:{javadocPath}/org/gradle/work/FileChange.html[FileChanges] 类型的 `Iterable`，然后可以查询以下内容：

* the link:{javadocPath}/org/gradle/work/FileChange.html#getFile--[affected file]
* the link:{javadocPath}/org/gradle/work/FileChange.html#getChangeType--[change type] (`ADDED`, `REMOVED` or `MODIFIED`)
* the link:{javadocPath}/org/gradle/work/FileChange.html#getNormalizedPath--[normalized path] of the changed file
* the link:{javadocPath}/org/gradle/work/FileChange.html#getFileType--[file type] of the changed file

以下示例演示了具有目录输入的增量任务。假定目录包含文本文件的集合，并将它们复制到输出目录，对文件中的文本进行反转操作。 需要注意的关键是 `inputDir` 属性的类型，其注解以及操作  (`execute()`) 如何使用 `getFileChanges()`  处理自上次构建以来实际上已更改的文件的子集。
您还可以查看如果删除了相应的输入文件，则该如何操作删除目标文件：

[[taskDefinition]]
.Defining an incremental task action
====
include::{snippets-dir}/tasks/incrementalTask/groovy/build.gradle[tags=incremental-task]
include::{snippets-dir}/tasks/incrementalTask/kotlin/build.gradle.kts[tags=incremental-task]
====

如果由于某种原因（例如，通过使用 `--rerun-tasks` 运行）以非增量方式执行任务，则无论先前状态如何，所有文件均报告为 "已添加"。 在这种情况下，Gradle 自动删除先前的输出，因此增量任务仅需要处理给定的文件。

对于像上述示例这样的简单转换器任务，任务操作仅需要为任何过期输入生成输出文件，并为任何已删除输入删除输出文件。

[IMPORTANT]
====
一个任务只能包含一个增量任务动作。
====

[[sec:which_inputs_are_considered_out_of_date]]
=== 哪些输入被认为是过时的？

当以前执行任务时，自执行以来唯一的更改是增量输入文件属性，则 Gradle 能够确定需要处理哪些输入文件（增量执行）。 在这种情况下，link:{groovyDslPath}/org.gradle.work.InputChanges.html#org.gradle.work.InputChanges:getFileChanges(org.gradle.api.file.FileCollection)[InputChanges.getFileChanges()] 方法将返回添加，修改或删除的给定属性的所有输入文件的详细信息。

但是，在许多情况下，Gradle 无法确定需要处理哪些输入文件（非增量执行）。 示例包括：

* 没有上一次执行的历史记录。
* 你用的是不同版本的 Gradle。目前，Gradle 并不使用来自不同版本的任务历史记录。
* 添加到任务的 link:{javadocPath}/org/gradle/api/tasks/TaskOutputs.html#upToDateWhen-groovy.lang.Closure-[`upToDateWhen`] 条件返回 `false`.
* 自上次执行以来，输入属性发生了更改。
* 自上次执行以来，非增量输入文件属性发生了更改。
* 自上次执行以来，一个或多个输出文件发生了更改。

在所有这些情况下，Gradle 将报告添加的所有输入文件，而 `getFileChanges()` 方法将返回构成给定输入属性的所有文件的详细信息。

您可以使用 link:{groovyDslPath}/org.gradle.work.InputChanges.html#org.gradle.work.InputChanges.html##org.gradle.work.InputChanges:incremental[InputChanges.isIncremental()] 方法检查任务执行是否为增量执行。

[[sec:an_incremental_task_in_action]]
=== An incremental task in action

给 <<#taskDefinition,上面>> 增量任务的示例实现，让我们逐一介绍一些方案。

首先，考虑一个首次针对一组输入执行的 `IncrementalReverseTask` 实例。在这种情况下，所有输入将被视为已添加，如下所示：

[[ex:incremental_task_definition]]
.Running the incremental task for the first time
====
include::{snippets-dir}/tasks/incrementalTask/groovy/build.gradle[tags=reverse]
include::{snippets-dir}/tasks/incrementalTask/kotlin/build.gradle.kts[tags=reverse]

.Build layout
----
.
├── build.gradle
└── inputs
    ├── 1.txt
    ├── 2.txt
    └── 3.txt
----

.`gradle -q incrementalReverse` 的输出
----
> gradle -q incrementalReverse
include::{snippets-dir}/tasks/incrementalTask/tests/incrementalTaskFirstRun.out[]
----
====

如果再次执行任务且没有任何更改，则整个任务都是最新的，并且不执行任务动作：

.Running the incremental task with unchanged inputs
====
.`gradle incrementalReverse` 的输出
----
> gradle incrementalReverse
include::{snippets-dir}/tasks/incrementalTask/tests/incrementalTaskNoChange.out[]
----
====

如果以某种方式修改了输入文件或添加了新的输入文件，则重新执行任务将导致 link:{groovyDslPath}/org.gradle.work.InputChanges.html#org.gradle.work.InputChanges:getFileChanges(org.gradle.api.file.FileCollection)[InputChanges.getFileChanges()] 返回这些文件。 下面的示例在运行增量任务之前修改一个文件的内容并添加另一个文件的内容：

.Running the incremental task with updated input files
====
include::{snippets-dir}/tasks/incrementalTask/groovy/build.gradle[tags=updated-inputs]
include::{snippets-dir}/tasks/incrementalTask/kotlin/build.gradle.kts[tags=updated-inputs]

.`gradle -q updateInputs incrementalReverse` 的输出
----
> gradle -q updateInputs incrementalReverse
include::{snippets-dir}/tasks/incrementalTask/tests/incrementalTaskUpdatedInputs.out[]
----
====

NOTE: 各种任务（`updateInputs`, `removeInput` 等）仅用于演示增量任务的行为。不应将它们视为您应该在自己的构建脚本中拥有的任务或任务实现类型。

删除现有输入文件后，重新执行任务将导致该文件由 link:{groovyDslPath}/org.gradle.work.InputChanges.html#org.gradle.work.InputChanges:getFileChanges(org.gradle.api.file.FileCollection)[InputChanges.getFileChanges()] 返回为  `REMOVED`。下面的示例在执行增量任务之前删除现有文件之一：

.Running the incremental task with an input file removed
====
include::{snippets-dir}/tasks/incrementalTask/groovy/build.gradle[tags=removed-input]
include::{snippets-dir}/tasks/incrementalTask/kotlin/build.gradle.kts[tags=removed-input]

.`gradle -q removeInput incrementalReverse` 的输出
----
> gradle -q removeInput incrementalReverse
include::{snippets-dir}/tasks/incrementalTask/tests/incrementalTaskRemovedInput.out[]
----
====

当输出文件被删除（或修改）时，Gradle 无法确定哪些输入文件已过期。 在这种情况下，link:{groovyDslPath}/org.gradle.work.InputChanges.html#org.gradle.work.InputChanges:getFileChanges(org.gradle.api.file.FileCollection)[InputChanges.getFileChanges()] 返回给定属性的所有输入文件的详细信息。 以下示例仅从构建目录中删除输出文件之一，但请注意如何将所有输入文件视为 `ADDED`：

.Running the incremental task with an output file removed
====
include::{snippets-dir}/tasks/incrementalTask/groovy/build.gradle[tags=removed-output]
include::{snippets-dir}/tasks/incrementalTask/kotlin/build.gradle.kts[tags=removed-output]

.`gradle -q removeOutput incrementalReverse` 的输出
----
> gradle -q removeOutput incrementalReverse
include::{snippets-dir}/tasks/incrementalTask/tests/incrementalTaskRemovedOutput.out[]
----
====

我们要讨论的最后一个场景涉及修改基于非文件的输入属性时发生的情况。 在这种情况下，Gradle 无法确定属性如何影响任务输出，因此任务将以非增量方式执行。 
这意味着给定属性的所有输入文件都由 link:{groovyDslPath}/org.gradle.work.InputChanges.html#org.gradle.work.InputChanges:getFileChanges(org.gradle.api.file.FileCollection)[InputChanges.getFileChanges()] 返回，并且都被视为 `ADDED`。 
下面的示例在运行  `incrementalReverse`  任务时将项目属性 `taskInputProperty` 设置为新值，并且该项目属性用于初始化任务的 `inputProperty`  属性，如本节的 <<ex:incremental_task_definition,第一个示例所示>>。 在这种情况下，您可以期待以下输出：

.Running the incremental task with an input property changed
====
.`gradle -q -PtaskInputProperty=changed incrementalReverse` 的输出
----
> gradle -q -PtaskInputProperty=changed incrementalReverse
include::{snippets-dir}/tasks/incrementalTask/tests/incrementalTaskChangedProperty.out[]
----
====

[[sec:storing_incremental_task_state]]
=== 缓存任务保存增量状态

自上次执行以来，使用 Gradle 的 `InputChanges` 并不是创建仅对更改起作用的任务的唯一方法。 诸如 Kotlin 编译器之类的工具将增量性作为内置功能提供。 通常的实现方式是该工具将有关先前执行状态的分析数据存储在某个文件中。
如果此类状态文件 <<build_cache.adoc#sec:task_output_caching_inputs,relocatable>>，则可以将其声明为任务的输出。 这样，当从缓存中加载任务的结果时，下一次执行也可以使用从缓存中加载的分析数据。
,
但是，如果状态文件不可重定位，则无法通过构建缓存共享它们。 实际上，当从缓存加载任务时，必须清除所有此类状态文件，以防止过时的状态在下一次执行期间使工具混乱。 如果通过 link:{javadocPath}/org/gradle/api/tasks/TaskLocalState.html#register-java.lang.Object++...++-[task.localState.register()] 声明了旧文件，或者使用  link:{javadocPath}/org/gradle/api/tasks/LocalState.html[@LocalState] 注解标记了属性，则 Gradle 可以确保删除这些陈旧文件。

[[sec:declaring_and_using_command_line_options]]
== 声明和使用命令行选项

有时，用户希望在命令行而不是构建脚本上声明公开的任务属性的值。 如果更频繁地更改属性值，则在命令行上传递它们特别有用。 任务 API 支持一种用于标记属性的机制，以在运行时自动生成具有特定名称的相应命令行参数。

[[sec:declaring_task_option]]
=== 声明命令行选项

为任务属性公开新的命令行选项非常简单。 您只需要使用 link:{javadocPath}/org/gradle/api/tasks/options/Option.html[Option] 注解属性的相应 setter 方法即可。 一个选项需要一个强制标识符。
此外，您可以提供可选的描述。 任务可以公开与类中可用属性一样多的命令行选项。

让我们看一个示例来说明功能。 定制任务 `UrlVerify` 通过进行 HTTP 调用并检查响应代码来验证是否可以解析给定的 URL。 可以通过属性 `url` 配置要验证的 URL。 该属性的 setter 方法使用 link:{javadocPath}/org/gradle/api/tasks/options/Option.html[@Option] 注解

=== Example: Declaring a command line option

[source.multi-language-sample,java]
.UrlVerify.java
----
include::{snippets-dir}/tasks/commandLineOption-stringOption/groovy/buildSrc/src/main/java/UrlVerify.java[tag=custom-task-implementation]
----

通过运行 `help` 任务和 `--task`选项，可以将为任务声明的所有选项 <<#sec:listing_task_options,在控制台输出>> 。

[[sec:using_task_option_command_line]]
=== 在命令行上使用选项

在命令行上使用选项必须遵守以下规则:

- 该选项使用双破折号作为前缀，例如： `--url`. 单个破折号不能作为任务选项的有效语法。
- 选项参数直接跟随在任务声明之后 e.g. `verifyUrl --url=http://www.google.com/`.
- 任务的多个选项可以在任务名称后面的命令行中以任何顺序声明

回到前面的示例，构建脚本创建类型为 `UrlVerify` 的任务实例，并通过 exposed 选项从命令行提供一个值。

.Using a command line option
====
include::{snippets-dir}/tasks/commandLineOption-stringOption/groovy/build.gradle[tags=task]
include::{snippets-dir}/tasks/commandLineOption-stringOption/kotlin/build.gradle.kts[tags=task]
====

.**`gradle -q verifyUrl --url=http://www.google.com/`** 的输出
----
> gradle -q verifyUrl --url=http://www.google.com/
include::{snippets-dir}/tasks/commandLineOption-stringOption/tests/taskCommandLineOption.out[]
----

[[sec:supported_task_option_data_types]]
=== 选项支持的数据类型

Gradle 限制了可用于声明命令行选项的数据类型集。命令行上的用法因类型而异。

`boolean`, `Boolean`, `Property<Boolean>`::
描述值为 `true` 或 `false`. 在命令行上传递选项会将值视为 `true`. 例如 `--enabled` 等于 `true`. 没有该选项将使用属性的默认值.

`String`, `Property<String>`::
描述值为 String 类型. 在命令行上传递选项还需要一个值 e.g. `--container-id=2x94held` 或 `--container-id 2x94held`.

`enum`, `Property<enum>`::
描述值为 enumerated 类型. 在命令行上传递选项还需要一个值 e.g. `--log-level=DEBUG` 或 `--log-level debug`. 该值不区分大小写。

`List<String>`, `List<enum>`::
Describes an option that can takes multiple values of a given type. The values for the option have to be provided as multiple declarations e.g. `--image-id=123 --image-id=456`. Other notations such as comma-separated lists or multiple values separated by a space character are currently not supported.

[[sec:documenting_available_task_option_values]]
=== 记录选项的可用值

理论上，属性类型为 `String` 或 `List<String>` 的选项可以接受任何任意值。 可以在注解 link:{javadocPath}/org/gradle/api/tasks/options/OptionValues.html[OptionValues] 的帮助下以编程方式记录此选项的期望值。 可以将此注解分配给任何返回受支持数据类型之一的 `List` 的方法。
另外，您必须提供选项标识符以指示选项和可用值之间的关系。

[NOTE]
====
在选项中不支持的命令行上传递值不会使构建失败或引发异常。您必须在任务操作中为此类行为实现自定义逻辑。
====

本示例说明了单个任务使用多个选项的情况。任务实现提供选项 `output-type` 的可用值列表。

=== Example: Declaring available values for an option

[source.multi-language-sample,java]
.UrlProcess.java
----
include::{snippets-dir}/tasks/commandLineOption-optionValues/groovy/buildSrc/src/main/java/UrlProcess.java[tag=custom-task-implementation]
----

[[sec:listing_task_options]]
=== 列出命令行选项

使用注解 link:{javadocPath}/org/gradle/api/tasks/options/Option.html[Option] 和 link:{javadocPath}/org/gradle/api/tasks/options/OptionValues.html[OptionValues] 的命令行选项是自行记录的。您将在 `help` 任务的控制台输出中看到 <<#sec:declaring_task_option,声明的选项>> 及其 <<#sec:documenting_available_task_option_values,可用值>>。输出以字母顺序呈现选项。

=== Example: 列出选项的可用值

.**`gradle -q help --task processUrl`** 的输出
----
> gradle -q help --task processUrl
include::{snippets-dir}/tasks/commandLineOption-optionValues/tests/helpTaskOptions.out[]
----

=== 局限性

当前支持声明命令行选项有一些限制。

- 只能通过注解为自定义任务声明命令行选项。 没有用于定义选项的程序化等效项。
- 选项不能全局声明，例如 在项目级别或作为插件的一部分。
- 在命令行上分配选项时，需要明确说明暴露该选项的任务，例如. `gradle check --tests abc` 不起作用，即使检查任务取决于 `test` 任务

[[worker_api]]
== Worker API

[NOTE]
====

Worker API <<feature_lifecycle.adoc#feature_lifecycle,是一个孵化功能>> .

====

从对 <<#incremental_tasks,增量任务>> 的讨论中可以看出，可以将任务执行的 work 视为离散单位（即，将输入的子集转换为特定的输出子集）。 很多时候，这些 work 单元彼此高度独立，这意味着它们可以以任何顺序执行，
并且可以简单地汇总在一起以形成任务的整体动作。 在单线程执行中，这些 work 单元将按顺序执行，但是，如果我们有多个处理器，则希望同时执行独立的 work 单元。 这样，我们可以在构建时充分利用可用资源，
并更快地完成任务的活动。

Worker API 提供了一种完成此操作的机制。 它允许在任务动作期间安全，并行地执行多项 work 。 但是，Worker API的好处不仅限于并行执行任务。 您还可以配置所需的隔离级别，以便可以在隔离的类加载器甚至隔离的进程中执行 work 。 此外，好处甚至超出了执行单个任务的范围。 默认情况下，使用Worker API，Gradle可以开始并行执行任务。 换句话说，一旦任务提交了要异步执行的 work ，并且退出了任务动作，Gradle便可以并行开始执行其他独立任务，即使这些任务在同一项目中

[[using-the-worker-api]]
=== 使用 Worker API

为了将 work 提交给 Worker API，必须提供两件事：work 单元的实现，以及 work 单元的参数。

work 单元的参数定义为实现 link:{javadocPath}/org/gradle/workers/WorkParameters.html[WorkParameters] 的接口或抽象类。 参数类型必须是 <<custom_gradle_types.adoc#managed_types,managed type>>。

您可以在 <<custom_gradle_types.adoc#custom_gradle_types,开发自定义 Gradle 类型>>中找到有关实现 work 参数的更多信息。

该实现是扩展 link:{javadocPath}/org/gradle/workers/WorkAction.html[WorkAction] 的类。 此类应该是抽象的，并且不应实现 `getParameters()`  方法。 Gradle 将在运行时为每个 work 单元的参数对象注入此方法的实现。

.Defining the unit of work parameters and implementation
====
include::{snippets-dir}/workerApi/noIsolation/groovy/build.gradle[tags=unit-of-work]
include::{snippets-dir}/workerApi/noIsolation/kotlin/build.gradle.kts[tags=unit-of-work]
====

`WorkAction` 实现可以注入在 work 执行过程中提供功能的服务，例如上例中的 link:{javadocPath}/org/gradle/api/file/FileSystemOperations.html[FileSystemOperations] 服务。 有关注入服务类型的更多信息，请参见 <<custom_gradle_types.adoc#service_injection,Service Injection>>。

为了提交 work 单元，必须首先获得 link:{javadocPath}/org/gradle/workers/WorkerExecutor.html[WorkerExecutor]。 为此，任务应具有一个带有 `javax.inject.Inject`  注解的构造函数，该构造函数接受 link:{javadocPath}/org/gradle/workers/WorkerExecutor.html[WorkerExecutor] 参数。
创建任务时，Gradle 将在运行时注入 link:{javadocPath}/org/gradle/workers/WorkerExecutor.html[WorkerExecutor] 的实例。
然后可以创建一个 link:{javadocPath}/org/gradle/workers/WorkQueue.html[WorkQueue] 对象，并可以提交各个 work 项。

.Submitting a unit of work for execution
====
include::{snippets-dir}/workerApi/noIsolation/groovy/build.gradle[tags=task-implementation]
include::{snippets-dir}/workerApi/noIsolation/kotlin/build.gradle.kts[tags=task-implementation]
====

提交任务动作的所有 work 后，可以安全地退出任务动作。 该 work 将异步和并行执行（取决于 `max-workers` 的设置）。 当然，在完成所有异步 work 之前，任何依赖于此任务的任务（以及该任务的任何后续任务动作）都不会开始执行。 但是，与此任务无关的其他独立任务可以立即开始执行。

如果在执行异步 work 时发生任何故障，该任务将失败，并且将抛出 link:{javadocPath}/org/gradle/workers/WorkerExecutionException.html[WorkerExecutionException]，详细说明每个失败的 work 项的故障。 这将被视为任务执行期间的任何失败，并且将阻止执行任何从属任务。

但是，在某些情况下，可能希望在退出任务操作之前等待 work 完成。 使用 link:{javadocPath}/org/gradle/workers/WorkQueue.html#await--[WorkQueue.await()] 方法可以实现。 与允许 work 异步完成的情况一样，
执行 work 项时发生的任何故障都将作为从  link:{javadocPath}/org/gradle/workers/WorkQueue.html#await--[WorkQueue.await()]  方法引发的 link:{javadocPath}/org/gradle/workers/WorkerExecutionException.html[WorkerExecutionException] 出现。

[NOTE]
====

请注意，当任务退出任务动作并将执行控制权返回给 Gradle 时，Gradle 将仅开始并行运行其他独立任务。 使用 link:{javadocPath}/org/gradle/workers/WorkQueue.html#await--[WorkQueue.await()] 时，执行不会离开任务动作。 这意味着Gradle将不允许其他任务开始执行，并且将等待任务动作完成后再执行。

====

.Waiting for asynchronous work to complete
====
include::{snippets-dir}/workerApi/waitForCompletion/groovy/build.gradle[tags=wait-for-completion]
include::{snippets-dir}/workerApi/waitForCompletion/kotlin/build.gradle.kts[tags=wait-for-completion]
====

[[isolation-modes]]
=== 隔离模式

Gradle 提供了三种隔离模式，可以在创建 link:{javadocPath}/org/gradle/workers/WorkQueue.html[WorkQueue] 时对其进行配置，并使用 link:{javadocPath}/org/gradle/workers/WorkerExecutor.html[WorkerExecutor] 上的以下方法之一进行指定：

link:{javadocPath}/org/gradle/workers/WorkerExecutor.html#noIsolation--[WorkerExecutor.noIsolation()]::
这表明 work 应在具有最小隔离度的线程中运行。 例如，它将共享从中加载任务的同一类加载器。 这是最快的隔离级别。
link:{javadocPath}/org/gradle/workers/WorkerExecutor.html#classLoaderIsolation-org.gradle.api.Action-[WorkerExecutor.classLoaderIsolation()]::
这表明 work 应在具有隔离类加载器的线程中运行。 类加载器将具有来自加载了 work 单元实现类的类加载器的类路径，以及通过 link:{javadocPath}/org/gradle/workers/ClassLoaderWorkerSpec.html#getClasspath--[ClassLoaderWorkerSpec.getClasspath()] 添加的任何其他类路径条目。
link:{javadocPath}/org/gradle/workers/WorkerExecutor.html#processIsolation-org.gradle.api.Action-[WorkerExecutor.processIsolation()]::
这表明应通过在单独的进程中执行 work 来最大程度地隔离 work 。 流程的类加载器将使用加载了 work 单元的类加载器中的类路径，以及通过 link:{javadocPath}/org/gradle/workers/ClassLoaderWorkerSpec.html#getClasspath--[ClassLoaderWorkerSpec.getClasspath()] 添加的任何其他类路径条目。
此外，该过程将是一个 work 守护程序，该守护程序将保持活动状态，并且可以重复用于将来可能具有相同要求的 work 项。 使用 link:{javadocPath}/org/gradle/workers/ProcessWorkerSpec.html#forkOptions-org.gradle.api.Action-[ProcessWorkerSpec.forkOptions(org.gradle.api.Action)]，可以使用与 Gradle JVM 不同的设置来配置此过程。

[[worker-daemons]]
=== Worker Daemons

使用 `processIsolation()` 时，gradle 将启动一个寿命很长的 Worker Daemon 进程，该进程可用于将来的 work 项。

.Submitting an item of work to run in a worker daemon
====
include::{snippets-dir}/workerApi/workerDaemon/groovy/build.gradle[tags=worker-daemon]
include::{snippets-dir}/workerApi/workerDaemon/kotlin/build.gradle.kts[tags=worker-daemon]
====

提交 work 程序守护程序的 work 单元时，Gradle 首先会查看是否存在兼容的空闲守护程序。 如果是这样，它将把 work 单元发送到空闲的守护程序，将其标记为忙。 如果没有，它将启动一个新的守护程序。 
在评估兼容性时，Gradle 会考虑许多标准，所有这些标准都可以通过 link:{javadocPath}/org/gradle/workers/ProcessWorkerSpec.html#forkOptions-org.gradle.api.Action-[ProcessWorkerSpec.forkOptions(org.gradle.api.Action)] 进行控制.

默认情况下，辅助守护程序的最大堆启动为512MB。可以通过调整worker fork选项来更改.

executable::
守护程序仅在使用相同的Java可执行文件时才被认为是兼容的。.
classpath::
如果守护程序的类路径包含所有请求的类路径条目，则该守护程序被认为是兼容的。请注意，只有当类路径与请求的类路径完全匹配时，守护程序才被认为是兼容的.
heap settings::
如果守护程序至少具有与请求相同的堆大小设置，则认为该守护程序是兼容的。换句话说，具有高于请求的堆设置的守护程序将被视为兼容.
jvm arguments::
如果守护程序已设置所有请求的 jvm 参数，则该守护程序被认为是兼容的。 请注意，如果守护程序除了请求的参数之外还具有其他jvm参数，则该守护程序被认为是兼容的（除了专门处理的参数，例如堆设置，断言，调试等）.
system properties::
如果守护程序已将请求的所有系统属性设置为相同的值，则该守护程序被认为是兼容的。请注意，如果守护程序具有除请求的属性之外的其他系统属性，则该守护程序被认为是兼容的.
environment variables::
如果守护程序已将所有请求的环境变量设置为相同的值，则认为该守护程序是兼容的。请注意，如果守护程序除请求的环境变量之外还具有更多环境变量，则该守护程序被认为是兼容的。
bootstrap classpath::
如果守护程序包含所有请求的引导类路径条目，则该守护程序被认为是兼容的。请注意，如果守护程序除请求的引导程序类路径条目之外还有更多的引导程序类路径条目，则该守护程序被认为是兼容的。
debug::
仅当将debug设置为与请求相同的值（真或假）时，守护程序才被视为兼容。
enable assertions::
仅当将启用断言设置为与请求相同的值（true 或 false）时，守护程序才被视为兼容。
default character encoding::
仅当默认字符编码设置为与请求相同的值时，守护程序才被视为兼容。

辅助守护程序将保持运行状态，直到启动它们的构建守护程序停止或系统内存不足为止。 当可用系统内存不足时，Gradle 将开始停止 work 程序守护程序，以尽量减少内存消耗。

== 取消和超时

为了支持取消操作（例如，当用户使用CTRL + C停止构建时）和任务超时，自定义任务应对其正在执行的线程被中断做出反应。 通过 work 人员 API 提交的 work 项也是如此。 如果任务在 10 秒内未响应中断，则守护程序将关闭以释放系统资源。

== 更多细节

在自定义 Gradle 插件中打包自定义任务类型通常是一种好方法。 该插件可以为任务类型提供有用的默认值和约定，并提供一种从构建脚本或其他插件使用任务类型的便捷方法。 请参阅开发 <<custom_plugins.adoc#custom_plugins,Developing Custom Gradle Plugins>>  以获取更多详细信息。

Gradle 提供了许多功能，这些功能在 （包括任务）时非常有用。 有关更多详细信息，请参见开发 <<custom_gradle_types.adoc#,Developing Custom Gradle Types>> 。
