[[custom_gradle_types]]
= 开发自定义 Gradle 类型

您可以为 Gradle 开发几种不同类型的"附加组件”,例如 <<custom_plugins.adoc#custom_plugins,plugins>>,<<custom_tasks.adoc#custom_tasks,tasks>>,<<custom_plugins.adoc#sec:getting_input_from_the_build,project extensions>> or <<artifact_transforms.adoc#sec:implementing-artifact-transforms,artifact transforms>>,,
它们都作为类,并且可以在 JVM 上运行的其他类型实现. 本章讨论了这些类型共有的一些功能和概念. 您可以使用这些功能来帮助实现自定义的 Gradle 类型,并为用户提供一致的 DSL.

本章适用于以下类型:

- Plugin 类型.
- Task 类型.
- Artifact 参数转换类型.
- Worker API work action 参数类型.
- 使用 `ExtensionContainer.create()` 创建扩展对象, 例如由插件注册的项目扩展.
- 使用 `ObjectFactory.newInstance()` 创建的对象.
- Objects created for a managed nested property.
- Elements of a `NamedDomainObjectContainer`.

== 使用 bean 属性进行配置

您实现的自定义 Gradle 类型通常包含一些您希望使其可用于构建脚本和其他插件的配置. 例如,下载任务可以具有指定要从中下载的 URL 和将结果写入到的文件系统位置的配置. 此配置表示为 Java bean 属性.

Kotlin 和 Groovy 为声明 Java bean 属性提供了便利,这使它们成为实现 Gradle 类型的良好语言选择. 在下面的示例中演示了这些便利.

Gradle 还为使用 bean 属性实现类型提供了一些便利.

[[managed_properties]]
=== Managed properties (托管属性)

Gradle 可以提供抽象属性的实现. 这被称为托管属性,因为 Gradle 负责管理属性的状态. 属性可以是可变的,这意味着它既具有 getter 方法又具有 setter 方法,或者是只读的,意味着它仅具有 getter 方法.

[NOTE]
====
托管属性当前是一个 <<feature_lifecycle.adoc#feature_lifecycle,孵化>> 功能.
====

==== 可变的托管属性

要声明可变的托管属性,请为该类型的属性添加一个抽象的 getter 方法和一个抽象的 setter 方法.

这是带有 `uri` 属性的任务类型的示例:

.Mutable managed property
====
[source.multi-language-sample,java]
.Download.java
----
include::{snippets-dir}/plugins/mutableManagedProperty/groovy/buildSrc/src/main/java/Download.java[]
----
====

请注意,要使某个属性被视为可变的托管属性,该属性的所有 getter 方法和 setter 方法都必须是 `abstract`  的,并且具有 `public` 或 `protected`  的可见性.

[[read_only_managed_properties]]
==== 只读托管属性

要声明只读托管属性,请为该类型添加一个抽象的 getter 方法. 该属性不应具有任何 setter 方法. Gradle 将提供 getter 的实现,并为该属性创建一个值.

与 Gradle 的一种可配置的  <<lazy_configuration.adoc#lazy_configuration,lazy property>> 或容器类型一起使用时,这是一种有用的模式.

这是带有 `uri` 属性的任务类型的示例:

.Read-only managed property
====
[source.multi-language-sample,java]
.Download.java
----
include::{snippets-dir}/plugins/readOnlyManagedProperty/groovy/buildSrc/src/main/java/Download.java[]
----
====

请注意,要使某个属性被视为只读托管属性,则该属性的所有 getter 方法都必须是 `abstract`  的,并且必须具有 `public` 或 `protected`  的可见性. 该属性不得具有任何 setter 方法. 此外,属性类型必须具有以下之一:

- `Property<T>`
- `RegularFileProperty`
- `DirectoryProperty`
- `ListProperty<T>`
- `SetProperty<T>`
- `MapProperty<K, V>`
- `ConfigurableFileCollection`
- `ConfigurableFileTree`
- `DomainObjectSet<T>`
- `NamedDomainObjectContainer<T>`

Gradle 以与 link:{javadocPath}/org/gradle/api/model/ObjectFactory.html[ObjectFactory] 相同的方式为只读托管属性创建值.

[[read_only_managed_nested_properties]]
==== 只读托管嵌套属性

要声明一个只读的托管嵌套属性,请将该属性的抽象 getter 方法添加到以 `@link:{javadocPath}/org/gradle/api/tasks/Nested.html[Nested]` 注解的类型.
该属性不应具有任何 setter 方法. Gradle 提供了 getter 方法的实现,还为该属性创建了一个值. 嵌套类型也被视为自定义类型,并且可以使用本章中讨论的功能.

当定制类型的嵌套复杂类型具有相同的生命周期时,此模式很有用. 如果生命周期不同,请考虑改为使用 `Property<NestedType>` .

这是带有 `resource` 属性的任务类型的示例. `Resource` 类型也是自定义 Gradle 类型,并定义了一些托管属性:

.Read-only managed nested property
====
[source.multi-language-sample,java]
.Download.java
----
include::{snippets-dir}/plugins/readOnlyNestedProperty/groovy/buildSrc/src/main/java/Download.java[tags=download]
include::{snippets-dir}/plugins/readOnlyNestedProperty/groovy/buildSrc/src/main/java/Resource.java[tags=resource]
----
====

请注意,要使某个属性被视为只读的托管嵌套属性,则该属性的所有 getter 方法都必须是 `abstract` 的,并且具有 `public` 或 `protected` 的可见性. 该属性不得具有任何 setter 方法. 此外,必须使用 `@link:{javadocPath}/org/gradle/api/tasks/Nested.html[Nested]` 注解属性获取器

[[managed_types]]
=== Managed types

托管类型是一个没有字段且其属性都被托管的抽象类或接口. 也就是说,这是一种其状态完全由Gradle管理的类型.

== DSL 支持和可扩展性

当 Gradle 创建自定义类型的实例时,它会将该实例装饰为混入 DSL 和可扩展性支持.

每个经过修饰的实例都实现 link:{javadocPath}/org/gradle/api/plugins/ExtensionAware.html[ExtensionAware],因此可以将扩展对象附加到其上.

请注意,由于向后兼容性问题,当前未装饰使用 link:{javadocPath}/org/gradle/api/Project.html#container-java.lang.Class-[Project.container()]  创建的插件和容器的元素.

[[service_injection]]
== Service injection

Gradle 提供了许多可用于自定义 Gradle 类型的有用服务. 例如,任务可以使用 link:{javadocPath}/org/gradle/workers/WorkerExecutor.html[WorkerExecutor] 服务来并行运行工作,如<<custom_tasks.adoc#worker_api,worker API>> 部分所示. 通过服务注入提供服务.

[[services_for_injection]]
=== 可用服务

以下服务可用于注入:

- link:{javadocPath}/org/gradle/api/model/ObjectFactory.html[ObjectFactory] - 允许创建模型对象. 有关更多详细信息,请参见 <<#nested_objects>>.
- link:{javadocPath}/org/gradle/api/file/ProjectLayout.html[ProjectLayout] - 提供对关键项目位置的访问. 有关更多详细信息,请参见  <<lazy_configuration.adoc#working_with_files_in_lazy_properties,lazy configuration>>. 该服务在 Worker API 操作中不可用.
- link:{javadocPath}/org/gradle/api/provider/ProviderFactory.html[ProviderFactory] - 创建 `Provider` 实例. 有关更多详细信息,请参见 <<lazy_configuration.adoc#lazy_configuration,lazy configuration>>.
- link:{javadocPath}/org/gradle/workers/WorkerExecutor.html[WorkerExecutor] - 允许任务并行运行工作. 有关更多详细信息,请参见 <<custom_tasks.adoc#worker_api,the worker API>>.
- link:{javadocPath}/org/gradle/api/file/FileSystemOperations.html[FileSystemOperations] - 允许任务在文件系统上运行操作,例如删除文件,复制文件或同步目录.
- link:{javadocPath}/org/gradle/api/file/ArchiveOperations.html[ArchiveOperations] - 允许任务对存档文件 (例如 ZIP 或 TAR 文件) 运行操作.
- link:{javadocPath}/org/gradle/process/ExecOperations.html[ExecOperations] - 允许任务运行具有外部运行 `java` 程序专用支持的外部进程.
- link:{javadocPath}/org/gradle/tooling/provider/model/ToolingModelBuilderRegistry.html[ToolingModelBuilderRegistry] - 允许插件注册 Gradle 工具 API 模型.

除此之外, `ProjectLayout` 和 `WorkerExecutor` 服务仅可用于注入项目插件.

=== 构造器注入

对象可以通过两种方式接收其所需的服务. 第一种选择是将服务添加为类构造函数的参数. 构造函数必须使用 `javax.inject.Inject` 注解进行注解. Gradle 使用每个构造函数参数的声明类型来确定对象所需的服务.
构造函数参数及其名称的顺序并不重要,可以随便更改.

这是一个示例,显示了一个通过其构造函数接收 `ObjectFactory`  的任务类型:

.Constructor service injection
====
[source.multi-language-sample,java]
.Download.java
----
include::{snippets-dir}/plugins/constructorServiceInjection/groovy/buildSrc/src/main/java/Download.java[]
----
====

=== 属性注入

或者,可以通过在类中添加带有 `javax.inject.Inject` 注解的属性 getter 方法来注入服务. 例如,当由于向后兼容性约束而无法更改类的构造函数时,此功能很有用. 这种模式还允许 Gradle 将服务的创建推迟到调用 getter 方法之前,而不是在创建实例时进行.
这可以帮助提高性能. Gradle 使用 getter 方法的声明的返回类型来确定要提供的服务. 该属性的名称并不重要,并且可以是您喜欢的任何名称.

属性获取器方法必须是 `public` or `protected` 的. 该方法可以是 `abstract` 的,或者在不可能的情况下可以使用虚拟方法主体. 方法主体将被丢弃.

这是一个示例,显示了一个通过属性 getter 方法接收两项服务的任务类型:

.Property service injection
====
[source.multi-language-sample,java]
.Download.java
----
include::{snippets-dir}/plugins/propertyServiceInjection/groovy/buildSrc/src/main/java/Download.java[]
----
====

[[nested_objects]]
== 创建嵌套对象

自定义 Gradle 类型可以使用 link:{javadocPath}/org/gradle/api/model/ObjectFactory.html[ObjectFactory] 服务创建 Gradle 类型的实例以用于其属性值. 这些实例可以利用本章讨论的功能,使您可以创建"嵌套”对象和嵌套DSL.

您还可以让 Gradle 使用 <<read_only_managed_nested_properties,managed nested property>> 为您创建嵌套对象.

在以下示例中,项目扩展通过其构造函数接收一个 `ObjectFactory` 实例. 构造函数使用它创建一个嵌套的 `Resource` 对象 (也是一个自定义的Gradle类型) ,并使该对象可通过 `resource` 属性使用.

.Nested object creation
====
[source.multi-language-sample,java]
.DownloadExtension.java
----
include::{snippets-dir}/plugins/nestedObjects/groovy/buildSrc/src/main/java/DownloadExtension.java[]
include::{snippets-dir}/plugins/nestedObjects/groovy/buildSrc/src/main/java/Resource.java[tags=resource]
----
====

[[collection_types]]
== 集合类型

Gradle 提供了用于维护对象集合的类型,旨在与 Gradle DSL 配合使用并提供有用的功能,例如延迟配置.

=== NamedDomainObjectContainer

link:{javadocPath}/org/gradle/api/NamedDomainObjectContainer.html[NamedDomainObjectContainer] 管理一组对象,其中每个元素都有一个与之关联的名称. 该容器负责创建和配置元素,并提供一个 DSL,构建脚本可用于定义和配置元素. 它旨在容纳本身可配置的对象,例如一组自定义Gradle对象.

Gradle 在整个 API 中广泛使用 `NamedDomainObjectContainer` 类型. 例如,用于管理项目任务的 `project.tasks` 对象是 `NamedDomainObjectContainer<Task>`.

您可以使用 link:{javadocPath}/org/gradle/api/model/ObjectFactory.html[ObjectFactory] 服务创建容器实例,该服务提供 link:{javadocPath}/org/gradle/api/model/ObjectFactory.html#domainObjectContainer-java.lang.Class-[ObjectFactory.domainObjectContainer()] 方法.
也可以使用 link:{javadocPath}/org/gradle/api/Project.html#container-java.lang.Class-[Project.container()] 方法来使用,但是在自定义 Gradle 类型中,通常最好使用注入的 `ObjectFactory` 服务,而不是传递 `Project`  实例.

您还可以使用如上所述的  <<read_only_managed_properties,read-only managed property>> 创建容器实例.

为了将类型与任何 `domainObjectContainer()` 方法一起使用,它必须公开名为 "`name`" 属性作为该对象的唯一且恒定的名称. 该方法的 `domainObjectContainer(Class)` 变体通过调用带有字符串参数的类的构造函数来创建新实例,该参数是对象的所需名称. 以这种方式创建的对象被视为自定义Gradle类型,因此可以利用本章讨论的功能,例如服务注入或托管属性.

有关允许自定义实例化策略的 `domainObjectContainer()` 方法变体,请参见上面的链接.

.Managing a collection of objects
====
[source.multi-language-sample,java]
.DownloadExtension.java
----
include::{snippets-dir}/plugins/namedDomainObjectContainer/groovy/buildSrc/src/main/java/DownloadExtension.java[]
include::{snippets-dir}/plugins/namedDomainObjectContainer/groovy/buildSrc/src/main/java/Resource.java[tags=resource]
----
====

对于每个容器属性,Gradle 会自动向 Groovy 和 Kotlin DSL 添加一个块,您可以使用该块来配置容器的内容:

.Configure block
====
[source.multi-language-sample,kotlin]
.build.gradle.kts
----
include::{snippets-dir}/plugins/namedDomainObjectContainer/kotlin/build.gradle.kts[]
----
[source.multi-language-sample,groovy]
.build.gradle
----
include::{snippets-dir}/plugins/namedDomainObjectContainer/groovy/build.gradle[]
----
====

=== ExtensiblePolymorphicDomainObjectContainer

link:{javadocPath}/org/gradle/api/ExtensiblePolymorphicDomainObjectContainer.html[ExtensiblePolymorphicDomainObjectContainer] 是一个 `NamedDomainObjectContainer` ,它允许您为不同类型的对象定义实例化策略.

您可以使用 link:{javadocPath}/org/gradle/api/model/ObjectFactory.html#polymorphicDomainObjectContainer-java.lang.Class-[ObjectFactory.polymorphicDomainObjectContainer()]  方法创建实例.

=== NamedDomainObjectSet

link:{javadocPath}/org/gradle/api/NamedDomainObjectSet.html[NamedDomainObjectSet] 包含一组可配置对象,其中每个元素都有一个与之关联的名称. 这类似于 `NamedDomainObjectContainer`,但是 `NamedDomainObjectSet` 不管理集合中的对象. 它们需要手动创建和添加.

您可以使用 link:{javadocPath}/org/gradle/api/model/ObjectFactory.html#namedDomainObjectSet-java.lang.Class-[ObjectFactory.namedDomainObjectSet()] 方法创建实例.

=== NamedDomainObjectList

link:{javadocPath}/org/gradle/api/NamedDomainObjectList.html[NamedDomainObjectList] 包含一个可配置对象的列表,其中每个元素都有一个与之关联的名称. 这类似于 `NamedDomainObjectContainer`,但是 `NamedDomainObjectList` 并不管理集合中的对象. 它们需要手动创建和添加.

您可以使用 link:{javadocPath}/org/gradle/api/model/ObjectFactory.html#namedDomainObjectList-java.lang.Class-[ObjectFactory.namedDomainObjectList()] 方法创建实例.

=== DomainObjectSet

link:{javadocPath}/org/gradle/api/DomainObjectSet.html[DomainObjectSet] 仅包含一组可配置对象. 与 `NamedDomainObjectContainer` 相比,`DomainObjectSet` 不管理集合中的对象. 它们需要手动创建和添加.

您可以使用 link:{javadocPath}/org/gradle/api/model/ObjectFactory.html#domainObjectSet-java.lang.Class-[ObjectFactory.domainObjectSet()] 方法创建实例.
