[[preface]]
= 前言

Spring Data MongoDB 项目将 Spring 的核心概念应用到使用 MongoDB 文档风格数据存储的解决方案的开发中。我们提供了一个 "`template`" 作为存储和查询文档的高级抽象。您可能会注意到 Spring 框架提供的JDBC 支持和这个有些相似。

本文档是 Spring Data - MongoDB 支持的参考指南。它解释了 MongoDB 模块的概念以及各种存储名称空间的语义和语法。

本节提供 Spring 和 Document 数据库的一些基本介绍。文档的其余部分仅引用了 Spring Data MongoDB 特性，并且我们认为用户已经熟悉了 MongoDB 和 Spring 概念。

[[get-started:first-steps:spring]]
== 学习 Spring

Spring Data 使用 Spring 框架的一些 https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html[核心] 特性, 其中包含:

* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#beans[IoC] 容器
* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#validation[类型转换系统]
* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#expressions[表达式语言]
* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/integration.html#jmx[JMX 集成]
* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/data-access.html#dao-exceptions[DAO 异常层次结构].

您可以不了解 Spring APIs，但是理解它们背后的概念是很重要的。至少，反转控制 (IoC) 背后的思想应该很熟悉，您应该熟悉选择使用的任何 IoC 容器。

MongoDB 支持的核心功能可以直接使用，不需要调用 Spring Container 的 IoC 服务。这很像 `JdbcTemplate`，它可以 “独立” 使用，而不需要 Spring 容器的任何其他服务。为了利用 Spring Data MongoDB 的所有特性，比如存储库支持，您需要配置库的某些部分来使用 Spring。

要了解关于 Spring 的更多信息，可以参考详细解释 Spring 框架的全面文档。有很多关于这个主题的文章、博客和书籍。有关更多信息，请参见 Spring 框架 https://spring.io/docs[主页]。

[[get-started:first-steps:nosql]]
== 学习 NoSQL 和文档型数据库
NoSQL 存储已经席卷了存储领域。 这是一个广阔的领域，有大量的解决方案、术语和模式（更糟糕的是，甚至术语本身也有多种 https://www.google.com/search?q=nosoql+acronym[含义]）。 虽然有些原则是通用的，但您必须在一定程度上熟悉 MongoDB。 熟悉的最好方法是阅读文档并按照示例进行操作。 完成它们通常不会超过 5-10 分钟，特别是如果您来自 rdmbs 的背景，这些练习可以让您大开眼界。

学习 MongoDB 的起点是  https://www.mongodb.org/[www.mongodb.org]。 以下是其他有用资源的列表：

* 该手册介绍了 MongoDB，并包含了入门指南、参考文档和教程的链接。
* https://try.mongodb.org/[online shell] 在线教程提供了一种与 MongoDB 实例交互的便捷方式。
* MongoDB https://docs.mongodb.org/ecosystem/drivers/java/[Java Language Center]。
* 您可以购买 https://www.mongodb.org/books[几本书]。
* Karl Seguin 的在线书籍：https://openmymind.net/mongodb.pdf[The Little MongoDB Book]

[[requirements]]
== 要求

Spring Data MongoDB 3.x 需要 JDK 8.0 及更高版本和 https://spring.io/docs[Spring Framework] {springVersion} 及更高版本。

在文档存储方面，您至少需要 https://www.mongodb.org/[MongoDB] 3.6 版本，但我们建议使用更新的版本。

[[compatibility.matrix]]
=== 兼容性矩阵

下面的兼容性矩阵总结了从 Spring Data 到 MongoDB 驱动程序/数据库版本。数据库版本显示通过 Spring Data 测试套件的最高支持的服务器版本。您可以使用较新的服务器版本，除非您的应用程序使用的功能受到 MongoDB 服务器更改的影响。

以下兼容性矩阵总结了 Spring Data 版本到 MongoDB 驱动程序/数据库版本。 数据库版本显示通过 Spring Data 测试套件的最高支持服务器版本。 您可以使用较新的服务器版本，除非您的应用程序使用受 <<compatibility.changes,MongoDB 服务器更改>>影响的功能。

[cols="h,m,m,m", options="header"]
|===

|Spring Data Release Train
|Spring Data MongoDB
|Driver Version
|Server Version

|2021.0
|3.2.x
|4.1.x
|4.4.x

|2020.0
|3.1.x
|4.1.x
|4.4.x

|Neumann
|3.0.x
|4.0.x
|4.4.x

|Moore
|2.2.x
|3.11.x/Reactive Streams 1.12.x
|4.2.x

|Lovelace
|2.1.x
|3.8.x/Reactive Streams 1.9.x
|4.0.x

|===

[[compatibility.changes]]
[[compatibility.changes-4.4]]
==== MongoDB 4.4 中的相关变化

* 当没有 `$text`  条件出现时，字段列表不能包含文本搜索 score 属性。详情请参见 https://docs.mongodb.com/manual/reference/operator/query/text/[`$text` operator]
* 运行 map reduce 时，Sort 不能是空文档。

[[compatibility.changes-4.2]]
==== MongoDB 4.2 中的相关变化

* 删除 `geoNear` 命令. 查看 https://docs.mongodb.com/manual/release-notes/4.2-compatibility/#remove-support-for-the-geonear-command[Removal of `geoNear`]
* 删除 `eval` 命令. 查看 https://docs.mongodb.com/manual/release-notes/4.2-compatibility/#remove-support-for-the-eval-command[Removal of `eval`]

[[get-started:help]]
== 其他帮助资源

学习一个新的框架并不是那么简单的。在本节中，我们尝试提供一个我们认为很容易遵循的指南，以开始使用 Spring Data MongoDB 模块。但是，如果您遇到问题或需要建议，请使用以下链接之一:

[[get-started:help:community]]
社区论坛 :: Spring Data 是一个 https://stackoverflow.com/questions/tagged/spring-data[Stack Overflow] 标签，用于所有 Spring Data (不仅仅是文档)用户共享信息和互相帮助。请注意，只有发帖时才需要注册。

[[get-started:help:professional]]
专业支持 :: Spring Data 和Spring 背后的公司 https://pivotal.io/[Pivotal Software, Inc.] 提供专业的支持，并保证响应时间。

[[get-started:up-to-date]]
== Following Development

有关 Spring Data Mongo 源代码存储库、每日构建和快照构件的信息，请参阅 https://projects.spring.io/spring-data-mongodb/[Spring Data Mongo 主页]。您可以通过 https://stackoverflow.com/questions/tagged/spring-data[Stack Overflow] 上的社区与开发人员进行交互，帮助 Spring Data 更好地满足 Spring 社区的需求。要跟踪开发人员的活动，请在 Spring Data Mongo https://projects.spring.io/spring-data-mongodb/[主页] 上查找邮件列表信息。如果您遇到了错误或想要提出改进建议，请在 Spring Data 问题跟踪器上创建一个 https://github.com/spring-projects/spring-data-mongodb/issues[issue tracker]。要了解 Spring 生态系统中的最新新闻和公告，请订阅 Spring 社区 https://spring.io[门户]。您还可以在 Twitter (https://twitter.com/SpringData[SpringData])上关注 Spring https://spring.io/blog[blog] 或项目团队。
