[[preface]]
= 前言

Spring Data MongoDB 项目将 Spring 的核心概念应用于开发使用 MongoDB 文档风格数据存储的解决方案。我们提供一个 “template” 作为存储和查询文档的高级抽象。
你可能会注意到与 Spring 框架所提供的 JDBC 支持有相似之处。

本文档是 Spring Data - MongoDB 支持的参考指南。它解释了 MongoDB 模块的概念以及各种存储命名空间（store namespace）的语义和语法。

本节提供了一些关于 Spring 和文档数据库的基本介绍。本文的其余部分仅提及 Spring Data MongoDB 的功能，并假设用户熟悉 MongoDB 和 Spring 的概念。

[[get-started:first-steps:spring]]
== 学习 Spring

Spring Data 使用 Spring 框架的 https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html[核心]  功能，包括。

* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#beans[IoC] 容器
* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#validation[类型转换系统]
* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#expressions[表达式语言]
* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/integration.html#jmx[JMX 集成]
* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/data-access.html#dao-exceptions[DAO 异常层次].

虽然不需要你知道 Spring 的 API，但理解它们背后的概念是很重要的。至少，你应该熟悉控制反转（IoC）背后的理念，而且你应该熟悉你选择使用的任何 IoC 容器。

可以直接使用 MongoDB 支持的核心功能，而不需要调用 Spring 容器的 IoC 服务。这很像 `JdbcTemplate`，它可以 "独立" 使用，不需要 Spring 容器的任何其他服务。为了利用 Spring Data MongoDB 的所有功能，如 repository 支持，你需要配置库的某些部分来使用 Spring。

要了解更多关于 Spring 的信息，你可以参考详细解释 Spring 框架的综合文档。有很多关于这个主题的文章、博客条目和书籍。更多信息请参见 Spring framework https://spring.io/docs[主页]。

[[get-started:first-steps:nosql]]
== 学习 NoSQL 和 文档型数据库

NoSQL 存储已经在存储世界中掀起了风暴。这是一个庞大的领域，有大量的解决方案、术语和模式（更糟糕的是，甚至这个术语本身也有 https://www.google.com/search?q=nosoql+acronym[多种含义]）。虽然有些原则是通用的，但你必须在某种程度上熟悉 MongoDB。
熟悉的最好方法是阅读文档和跟随例子。通常需要花费不到 5-10 分钟就能看完，特别是，如果有 RDMBS （关系数据库管理系统）的背景，这些练习可以让你大开眼界。

学习 MongoDB 的起点是 https://www.mongodb.org/[www.mongodb.org]。这里有一个其他有用资源的列表。

* 该 https://docs.mongodb.org/manual/[手册] 介绍了 MongoDB，并包含指向入门指南、参考文档和教程的链接。
* https://try.mongodb.org/[online shell] 结合在线 https://docs.mongodb.org/manual/tutorial/getting-started/[提供了一种与 MongoDB 实例交互的便捷方式 教程]。
* MongoDB Java 语言中心.
* 你可以购买的几本 https://www.mongodb.org/books[books]。
* Karl Seguin 的在线书籍：https://openmymind.net/mongodb.pdf[The Little MongoDB Book]。

[[requirements]]
== 要求

Spring Data MongoDB 4.x 需要 JDK 17+，以及 Spring Framework {springVersion}+。

在文档存储方面，你至少需要 3.6 版的 https://www.mongodb.org/[MongoDB]，尽管我们建议使用较新的版本。

[[compatibility.matrix]]
=== 兼容性

下表总结了 Spring Data 版本与 MongoDB 驱动/数据库版本的兼容关系。数据库版本显示的是通过 Spring Data 测试套件的最高支持服务器版本。
你可以使用较新的服务器版本，除非你的应用程序使用的功能受到 <<compatibility.changes,MongoDB 服务器变化>>  的影响。关于驱动程序和服务器版本的兼容性，
请参阅  https://www.mongodb.com/docs/drivers/java/sync/current/compatibility/[官方的 MongoDB 驱动程序兼容性表]。

[cols="h,m,m,m", options="header"]
|===

|Spring Data Release Train
|Spring Data MongoDB
|Driver Version
|Server Version

|2022.0
|4.0.x
|4.7.x
|6.0.x

|2021.2
|3.4.x
|4.6.x
|5.0.x

|2021.1
|3.3.x
|4.4.x
|5.0.x

|2021.0
|3.2.x
|4.1.x
|4.4.x

|2020.0
|3.1.x
|4.1.x
|4.4.x

|Neumann
|3.0.x
|4.0.x
|4.4.x

|Moore
|2.2.x
|3.11.x/Reactive Streams 1.12.x
|4.2.x

|Lovelace
|2.1.x
|3.8.x/Reactive Streams 1.9.x
|4.0.x

|===

[[compatibility.changes]]
[[compatibility.changes-4.4]]
==== MongoDB 4.4 的相关变化

* 当没有 `$text` 条件存在时，字段列表不得包含文本搜索得分属性。另见 https://docs.mongodb.com/manual/reference/operator/query/text/[`$text` 操作符]
* 在运行 map reduce 时，排序不能是一个空文档。

[[compatibility.changes-4.2]]
==== MongoDB 4.2 的相关变化

* 删除 `geoNear` 命令。另见 https://docs.mongodb.com/manual/release-notes/4.2-compatibility/#remove-support-for-the-geonear-command[删除 `geoNear`] 。
* 删除 `eval` 命令。参见 https://docs.mongodb.com/manual/release-notes/4.2-compatibility/#remove-support-for-the-eval-command[删除 `eval`]。

[[get-started:help]]
== 其他帮助资源

学习一个新的框架并不总是那么简单。在本节中，我们试图提供一个我们认为是简单易行的指南，让大家从 Spring Data MongoDB 模块开始学习。然而，如果你遇到问题或需要建议，请随时使用以下链接。

[[get-started:help:community]]
社区论坛 :: https://stackoverflow.com/questions/tagged/spring-data[Stack Overflow] 上的 Spring Data 是所有 Spring Data（不仅仅是 Document）用户分享信息和相互帮助的一个标签。请注意，只有在发帖时才需要注册。


[[get-started:help:professional]]
专业支持 :: Spring Data 和 Spring 背后的公司 Pivotal Software, Inc. 提供专业的、来自源头的支持，并保证响应时间。

[[get-started:up-to-date]]
== 关注开发

有关 Spring Data Mongo 源代码库、每日构建和快照构件的信息，请参阅 Spring Data Mongo https://spring.io/projects/spring-data-mongodb/[主页]。
你可以通过 https://stackoverflow.com/questions/tagged/spring-data[Stack Overflow] 与社区和开发人员互动，帮助 Spring Data 最好地满足 Spring 社区的需求。
要关注开发人员的活动，请在 Spring Data Mongo https://spring.io/projects/spring-data-mongodb/[主页] 上查找邮件列表信息。
如果你遇到了一个错误或想提出改进建议，请在 Spring Data https://github.com/spring-projects/spring-data-mongodb/issues[issue tracker] 上创建一个 ticket。
要想了解 Spring 生态中的最新新闻和公告，请订阅 Spring 社区 https://spring.io[Portal]。你也可以关注 Spring https://spring.io/blog[blog] 或关注 Twitter 上 （https://twitter.com/SpringData[SpringData]）项目团队。
