[[mongo.aggregation]]
== 聚合框架支持

Spring Data MongoDB 为 2.2 版中引入 MongoDB 的聚合框架提供支持。

有关更多信息，请参阅 MongoDB 的聚合框架和其他数据聚合工具的完整 https://docs.mongodb.org/manual/aggregation/[参考文档]。

[[mongo.aggregation.basic-concepts]]
=== 基本概念

Spring Data MongoDB 中的聚合框架支持基于以下关键抽象：`Aggregation`、`AggregationDefinition` 和 `AggregationResults`。

* `Aggregation`
+
`Aggregation` 代表 MongoDB aggregate 操作，并持有聚合管道（aggregation pipeline ）指令的描述。聚合是通过调用 `Aggregation` 类的适当的 `newAggregation(…)` 静态工厂方法来创建的，该方法接收一个 `AggregateOperation` 的列表和一个可选的输入类。
+
实际的聚合操作是由 `MongoTemplate` 的 `aggregate` 方法运行的，该方法将所需的输出类作为参数。
+
* `TypedAggregation`
+
`TypedAggregation`，就像 `Aggregation`，持有聚合管道的指令和对输入类型的引用，用于将 domain 属性映射到实际文档字段。
+
在运行时，根据给定的输入类型检查字段引用，考虑潜在的  `@Field`  注解。
[NOTE]
====
在 3.2 中更改，引用不存在的属性不再引发错误。 要恢复以前的行为，请使用 `AggregationOptions` 的 `strictMapping` 选项。
====
* `AggregationDefinition`
+
`AggregationDefinition` 代表 MongoDB 聚合管道（aggregation pipeline）操作，并描述在此聚合步骤中应执行的处理。尽管你可以手动创建一个 `AggregationDefinition`，但我们建议使用 `Aggregate` 类提供的静态工厂方法来构建一个 `AggregateOperation`。
+
* `AggregationResults`
+
`AggregationResults` 是聚合操作结果的容器。它提供了对原始聚合结果的访问，其形式是指向映射对象的 `Document` 和关于聚合的其他信息。
+
下面的列表显示了使用 Spring Data MongoDB 支持 MongoDB 聚合框架的典型示例。
+
[source,java]
----
import static org.springframework.data.mongodb.core.aggregation.Aggregation.*;

Aggregation agg = newAggregation(
    pipelineOP1(),
    pipelineOP2(),
    pipelineOPn()
);

AggregationResults<OutputType> results = mongoTemplate.aggregate(agg, "INPUT_COLLECTION_NAME", OutputType.class);
List<OutputType> mappedResult = results.getMappedResults();
----

请注意，如果你提供一个输入类作为 `newAggregation` 方法的第一个参数，`MongoTemplate` 会从这个类派生出输入集合的名称。否则，如果你没有指定一个输入类，你必须明确提供输入集合的名称。如果同时提供了一个输入类和一个输入集合，则后者优先考虑。

[[mongo.aggregation.supported-aggregation-operations]]
=== Supported Aggregation Operations

MongoDB 聚合框架提供以下类型的聚合操作：:

* 管道（Pipeline）聚合操作
* Group/Accumulator 聚合操作。
* Boolean 聚合操作。
* Comparison 聚合操作。
* Arithmetic 聚合操作。
* String 聚合操作。
* Date 聚合操作。
* Array 聚合操作。
* Conditional 聚合操作。
* Lookup 聚合操作。
* Convert 聚合操作。
* Object 聚合操作。
* Script 聚合操作。

在撰写本文时，我们为 Spring Data MongoDB 中的以下聚合操作提供支持：

.Spring Data MongoDB 目前支持的聚合操作
[cols="2*"]
|===
| Pipeline 聚合操作
| `bucket`, `bucketAuto`, `count`, `facet`, `geoNear`, `graphLookup`, `group`, `limit`, `lookup`, `match`, `project`, `rand`, `replaceRoot`, `skip`, `sort`, `unwind`

| Set 聚合操作
| `setEquals`, `setIntersection`, `setUnion`, `setDifference`, `setIsSubset`, `anyElementTrue`, `allElementsTrue`

| Group/Accumulator 聚合操作
| `addToSet`, `bottom`, `bottomN`, `covariancePop`, `covarianceSamp`, `expMovingAvg`, `first`, `firstN`, `last`, `lastN` `max`, `maxN`, `min`, `minN`, `avg`, `push`, `sum`, `top`, `topN`, `count` (+++*+++), `stdDevPop`, `stdDevSamp`

| Arithmetic 聚合操作
| `abs`, `acos`, `acosh`, `add` (+++*+++ via `plus`), `asin`, `asin`, `atan`, `atan2`, `atanh`, `ceil`, `cos`, `cosh`, `derivative`, `divide`, `exp`, `floor`, `integral`, `ln`, `log`, `log10`, `mod`, `multiply`, `pow`, `round`, `sqrt`, `subtract` (+++*+++ via `minus`), `sin`, `sinh`, `tan`, `tanh`, `trunc`

| String 聚合操作
| `concat`, `substr`, `toLower`, `toUpper`, `strcasecmp`, `indexOfBytes`, `indexOfCP`, `regexFind`, `regexFindAll`, `regexMatch`, `replaceAll`, `replaceOne`, split`, `strLenBytes`, `strLenCP`, `substrCP`, `trim`, `ltrim`, `rtim`

| Comparison 聚合操作
| `eq` (+++*+++ via `is`), `gt`, `gte`, `lt`, `lte`, `ne`

| Array 聚合操作
| `arrayElementAt`, `arrayToObject`, `concatArrays`, `filter`, `first`, `in`, `indexOfArray`, `isArray`, `last`, range`, `reverseArray`, `reduce`, `size`, `sortArray`, `slice`, `zip`

| Literal Operators
| `literal`

| Date 聚合操作
| `dateSubstract`, `dateTrunc`, `dayOfYear`, `dayOfMonth`, `dayOfWeek`, `year`, `month`, `week`, `hour`, `minute`, `second`, `millisecond`, `dateAdd`, `dateDiff`, `dateToString`, `dateFromString`, `dateFromParts`, `dateToParts`, `isoDayOfWeek`, `isoWeek`, `isoWeekYear`, `tsIncrement`, `tsSecond`

| Variable Operators
| `map`

| Conditional 聚合操作
| `cond`, `ifNull`, `switch`

| Type 聚合操作
| `type`

| Convert 聚合操作
| `convert`, `degreesToRadians`, `toBool`, `toDate`, `toDecimal`, `toDouble`, `toInt`, `toLong`, `toObjectId`, `toString`

| Object 聚合操作
| `objectToArray`, `mergeObjects`, `getField`, `setField`

| Script 聚合操作
| `function`, `accumulator`

|===

+++*+++ 该操作由 Spring Data MongoDB 映射或添加。.

请注意，Spring Data MongoDB 目前不支持此处未列出的聚合操作。 Comparison 聚合操作。是以 `Criteria` 表达式来表示的。

[TIP]
====
不受支持的聚合 operations/operators（如 https://www.mongodb.com/docs/atlas/atlas-search/query-syntax/[$search] for MongoDB Atlas）可以通过实现 `AggregationOperation` 或 `AggregationExpression`来提供 .
`Aggregation.stage` 是通过提供 JSON 或 Bson 表示法来注册 pipeline stage 的快捷方式。

[source,java]
----
Aggregation.stage("""
    { $search : {
        "near": {
          "path": "released",
          "origin": { "$date": { "$numberLong": "..." } } ,
          "pivot": 7
        }
      }
    }
""");
----
====

[[mongo.aggregation.projection]]
=== 投影表达式

投射表达式用于定义作为特定聚合步骤结果的字段。投影表达式可以通过 `Aggregation` 类的 `project` 方法来定义，可以通过传递一个 `String` 对象的列表或聚合框架 `Fields` 对象。
投影可以通过 fluent API，通过使用 `and(String)` 方法和使用 `as(String)` 方法的别名来扩展额外的字段。注意，你也可以通过使用聚合框架的 `Fields.field` 静态工厂方法来定义带有别名的字段，
然后你可以用它来构造一个新的 `Fields` 实例。在以后的聚合阶段对投影字段的引用只对包含的字段或其别名（包括新定义的字段及其别名）的字段名有效。未包括在投影中的字段不能在以后的聚合阶段被引用。下面的列表显示了投射表达式的例子。

.投影表达的例子
====
[source,java]
----
// generates {$project: {name: 1, netPrice: 1}}
project("name", "netPrice")

// generates {$project: {thing1: $thing2}}
project().and("thing1").as("thing2")

// generates {$project: {a: 1, b: 1, thing2: $thing1}}
project("a","b").and("thing1").as("thing2")
----
====

.使用投影和排序的多级聚合
====
[source,java]
----
// generates {$project: {name: 1, netPrice: 1}}, {$sort: {name: 1}}
project("name", "netPrice"), sort(ASC, "name")

// generates {$project: {name: $firstname}}, {$sort: {name: 1}}
project().and("firstname").as("name"), sort(ASC, "name")

// does not work
project().and("firstname").as("name"), sort(ASC, "firstname")
----
====

更多项目操作示例可以在 `AggregationTests` 类中找到。 请注意，有关投影表达式的更多详细信息可以在 MongoDB 聚合框架参考文档的 https://docs.mongodb.org/manual/reference/operator/aggregation/project/#pipe._S_project[对应部分] 中找到。

[[mongo.aggregation.facet]]
=== 分面分类（faceted classification）

从版本 3.4 开始，MongoDB 使用聚合框架支持分面分类。 分面分类使用组合起来创建完整分类条目的语义类别（一般或特定主题）。 流经聚合管道的文档被分类为桶。 多面分类可以在同一组输入文档上进行各种聚合，而无需多次检索输入文档。

==== Buckets

`Bucket` 操作根据指定的表达式和 `Bucket` 边界将传入文档分类为称为存储桶的组。 `Bucket` 操作需要分组字段或分组表达式。 您可以使用 `Aggregate` 类的 `bucket()` 和 `bucketAuto()` 方法来定义它们。 `BucketOperation` 和 `BucketAutoOperation`
可以根据输入文档的聚合表达式公开累积。 您可以使用 `with...()` 方法和 `andOutput(String)` 方法通过 fluent API 使用附加参数扩展 Bucket 操作。 您可以使用 `as(String)` 方法为操作设置别名。 每个 `Bucket` 在输出中表示为一个文档。

`BucketOperation` 采用一组定义的边界将传入的文档分组到这些类别中。 需要对边界进行排序。 以下清单显示了 Bucket 操作的一些示例：

.Bucket 操作示例
====
[source,java]
----
// generates {$bucket: {groupBy: $price, boundaries: [0, 100, 400]}}
bucket("price").withBoundaries(0, 100, 400);

// generates {$bucket: {groupBy: $price, default: "Other" boundaries: [0, 100]}}
bucket("price").withBoundaries(0, 100).withDefault("Other");

// generates {$bucket: {groupBy: $price, boundaries: [0, 100], output: { count: { $sum: 1}}}}
bucket("price").withBoundaries(0, 100).andOutputCount().as("count");

// generates {$bucket: {groupBy: $price, boundaries: [0, 100], 5, output: { titles: { $push: "$title"}}}
bucket("price").withBoundaries(0, 100).andOutput("title").push().as("titles");
----
====

`BucketAutoOperation` 确定边界以尝试将文档平均分配到指定数量的 Bucket 中。 `BucketAutoOperation` 可选地采用粒度值，该值指定 https://en.wikipedia.org/wiki/Preferred_number[preferred number] 系列用于确保计算的边界边以首选
整数或 10 的幂结束。 以下清单显示了 Bucket 操作的示例：

.Bucket operation examples
====
[source,java]
----
// generates {$bucketAuto: {groupBy: $price, buckets: 5}}
bucketAuto("price", 5)

// generates {$bucketAuto: {groupBy: $price, buckets: 5, granularity: "E24"}}
bucketAuto("price", 5).withGranularity(Granularities.E24).withDefault("Other");

// generates {$bucketAuto: {groupBy: $price, buckets: 5, output: { titles: { $push: "$title"}}}
bucketAuto("price", 5).andOutput("title").push().as("titles");
----
====

要在桶中创建输出字段，桶操作可以通过 `andOutput()` 和 <<mongo.aggregation.projection.expressions, SpEL 表达式>> 通过 `andOutputExpression()` 使用 `AggregationExpression`。

请注意，有关 bucket 表达式的更多详细信息可以在 https://docs.mongodb.org/manual/reference/operator/aggregation/bucket/[`$bucket` 部分] 和
MongoDB 聚合框架参考文档的 https://docs.mongodb.org/manual/reference/operator/aggregation/bucketAuto/[`$bucketAuto` 部分]。

==== 多面的聚合

多个聚合管道可用于创建多方面聚合，在单个聚合阶段内跨多个维度（或方面）表征数据。 多面聚合提供多种过滤器和分类来指导数据浏览和分析。 分面的常见实现是有多少在线零售商通过对产品价格、制造商、尺寸和其他因素应用过滤器来提供缩小搜索结果的方法。

您可以使用 `Aggregation` 类的 `facet()` 方法定义 `FacetOperation`。 您可以使用 `and()` 方法使用多个聚合管道对其进行自定义。 每个子管道在输出文档中都有自己的字段，其结果存储为文档数组。

子管道可以在分组之前投影和过滤输入文档。 常见用例包括在分类之前提取日期部分或计算。 以下清单显示了构面操作示例：

.Facet operation examples
====
[source,java]
----
// generates {$facet: {categorizedByPrice: [ { $match: { price: {$exists : true}}}, { $bucketAuto: {groupBy: $price, buckets: 5}}]}}
facet(match(Criteria.where("price").exists(true)), bucketAuto("price", 5)).as("categorizedByPrice"))

// generates {$facet: {categorizedByCountry: [ { $match: { country: {$exists : true}}}, { $sortByCount: "$country"}]}}
facet(match(Criteria.where("country").exists(true)), sortByCount("country")).as("categorizedByCountry"))

// generates {$facet: {categorizedByYear: [
//     { $project: { title: 1, publicationYear: { $year: "publicationDate"}}},
//     { $bucketAuto: {groupBy: $price, buckets: 5, output: { titles: {$push:"$title"}}}
// ]}}
facet(project("title").and("publicationDate").extractYear().as("publicationYear"),
      bucketAuto("publicationYear", 5).andOutput("title").push().as("titles"))
  .as("categorizedByYear"))
----
====

请注意，有关方面操作的更多详细信息可以在 MongoDB 聚合框架参考文档的 https://docs.mongodb.org/manual/reference/operator/aggregation/facet/[`$facet` 部分] 中找到。

[[mongo.aggregation.sort-by-count]]
==== 按计数（Count）排序

按计数排序操作根据指定表达式的值对传入文档进行分组，计算每个不同组中的文档计数，并按计数对结果进行排序。 它提供了在使用 <<mongo.aggregation.facet>> 时应用排序的便捷快捷方式。 按计数排序操作需要分组字段或分组表达式。 以下清单显示了按计数排序的示例：

.Sort by count example
====
[source,java]
----
// generates { $sortByCount: "$country" }
sortByCount("country");
----
====

按计数排序操作等价于以下 BSON（二进制 JSON）：:

----
{ $group: { _id: <expression>, count: { $sum: 1 } } },
{ $sort: { count: -1 } }
----

[[mongo.aggregation.projection.expressions]]
==== 投影表达式中的 Spring 表达式支持

我们通过 `ProjectionOperation` 和 `BucketOperation` 类的 `andExpression` 方法支持在投影表达式中使用 SpEL 表达式。 此功能允许您将所需的表达式定义为 SpEL 表达式。 在运行查询时，SpEL 表达式被转换为相应的 MongoDB 投影表达式部分。 这种安排使得表达复杂的计算变得更加容易。

===== 使用 SpEL 表达式进行复杂计算

考虑以下 SpEL 表达式:

[source,java]
----
1 + (q + 1) / (q - 1)
----

前面的表达式被翻译成下面的投影表达式部分:

[source,javascript]
----
{ "$add" : [ 1, {
    "$divide" : [ {
        "$add":["$q", 1]}, {
        "$subtract":[ "$q", 1]}
    ]
}]}
----

您可以在 <<mongo.aggregation.examples.example5>> 和 <<mongo.aggregation.examples.example6>> 中查看更多上下文中的示例。 您可以在 `SpelExpressionTransformerUnitTests` 中找到支持的 SpEL 表达式构造的更多使用示例。 下表显示了 Spring Data MongoDB 支持的 SpEL 转换：

.Supported SpEL transformations
[%header,cols="2"]
|===
| SpEL Expression
| Mongo Expression Part
| a == b
| { $eq : [$a, $b] }
| a != b
| { $ne : [$a , $b] }
| a > b
| { $gt : [$a, $b] }
| a >= b
| { $gte : [$a, $b] }
| a < b
| { $lt : [$a, $b] }
| a <= b
| { $lte : [$a, $b] }
| a + b
| { $add : [$a, $b] }
| a - b
| { $subtract : [$a, $b] }
| a * b
| { $multiply : [$a, $b] }
| a / b
| { $divide : [$a, $b] }
| a^b
| { $pow : [$a, $b] }
| a % b
| { $mod : [$a, $b] }
| a && b
| { $and : [$a, $b] }
| a \|\| b
| { $or : [$a, $b] }
| !a
| { $not : [$a] }
|===

除了上表中显示的转换之外，您还可以使用标准的 SpEL 操作，例如 `new` 来（例如）通过它们的名称（后跟要在括号中使用的参数）创建数组和引用表达式。 以下示例显示了如何以这种方式创建数组：

[source,java]
----
// { $setEquals : [$a, [5, 8, 13] ] }
.andExpression("setEquals(a, new int[]{5, 8, 13})");
----

[[mongo.aggregation.examples]]
==== 聚合框架实例

本节中的示例演示了 MongoDB Aggregation Framework 与 Spring Data MongoDB 的使用模式。

[[mongo.aggregation.examples.example1]]
===== 聚合框架实例 1

在这个介绍性示例中，我们想要聚合标签列表，以从 MongoDB 集合（称为 `tags`）中获取特定标签的出现计数，按出现计数按降序排序。 此示例演示了分组、排序、投影（选择）和展开（结果拆分）的用法。

[source,java]
----
class TagCount {
 String tag;
 int n;
}
----

[source,java]
----
import static org.springframework.data.mongodb.core.aggregation.Aggregation.*;

Aggregation agg = newAggregation(
    project("tags"),
    unwind("tags"),
    group("tags").count().as("n"),
    project("n").and("tag").previousOperation(),
    sort(DESC, "n")
);

AggregationResults<TagCount> results = mongoTemplate.aggregate(agg, "tags", TagCount.class);
List<TagCount> tagCount = results.getMappedResults();
----

前面的清单使用以下算法：:

. 使用 `newAggregation` 静态工厂方法创建一个新聚合，我们将聚合操作列表传递给该方法。这些聚合操作定义了我们的“聚合”的聚合管道。
. 使用 `project` 操作从输入集合中选择 `tags` 字段（字符串数组）。
. 使用 `unwind` 操作为 `tags` 数组中的每个标签生成一个新文档。
. 使用 `group` 操作为我们聚合出现次数的每个 `tags` 值定义一个组（通过使用 `count` 聚合运算符并将结果收集到一个名为 `n` 的新字段中）。
. 选择 `n` 字段并为从前一个组操作（因此调用 `previousOperation()`）生成的 ID 字段创建一个别名，名称为 `tag`。
. 使用 `sort` 操作按标签的出现次数以降序对生成的标签列表进行排序。
. 在 `MongoTemplate` 上调用 `aggregate` 方法让 MongoDB 执行实际的聚合操作，并将创建的 `Aggregation` 作为参数。

请注意，输入集合被明确指定为 `aggregate` 方法的 `tags` 参数。 如果输入集合的名称没有明确指定，它派生自作为第一个参数传递给 `newAggreation` 方法的输入类。

[[mongo.aggregation.examples.example2]]
===== 聚合框架实例 2

此示例基于 MongoDB 聚合框架中的 https://docs.mongodb.org/manual/tutorial/aggregation-examples/#largest-and-smallest-cities-by-state[Largest and Smallest Cities by State] 示例 文档。 我们添加了额外的排序以使用不同的 MongoDB 版本产生稳定的结果。 在这里，我们想通过使用聚合框架返回每个州的人口最小和最大的城市。 此示例演示了分组、排序和投影（选择）。

[source,java]
----
class ZipInfo {
   String id;
   String city;
   String state;
   @Field("pop") int population;
   @Field("loc") double[] location;
}

class City {
   String name;
   int population;
}

class ZipInfoStats {
   String id;
   String state;
   City biggestCity;
   City smallestCity;
}
----

[source,java]
----
import static org.springframework.data.mongodb.core.aggregation.Aggregation.*;

TypedAggregation<ZipInfo> aggregation = newAggregation(ZipInfo.class,
    group("state", "city")
       .sum("population").as("pop"),
    sort(ASC, "pop", "state", "city"),
    group("state")
       .last("city").as("biggestCity")
       .last("pop").as("biggestPop")
       .first("city").as("smallestCity")
       .first("pop").as("smallestPop"),
    project()
       .and("state").previousOperation()
       .and("biggestCity")
          .nested(bind("name", "biggestCity").and("population", "biggestPop"))
       .and("smallestCity")
          .nested(bind("name", "smallestCity").and("population", "smallestPop")),
    sort(ASC, "state")
);

AggregationResults<ZipInfoStats> result = mongoTemplate.aggregate(aggregation, ZipInfoStats.class);
ZipInfoStats firstZipInfoStats = result.getMappedResults().get(0);
----

请注意，`ZipInfo` 类映射给定输入集合的结构。 `ZipInfoStats` 类以所需的输出格式定义结构。

前面的清单使用以下算法：

. 使用 `group` 操作从输入-集合中定义一个组。分组的标准是 `state` 和 `city` 字段的组合，这形成了组的 ID 结构。我们通过使用 `sum` 运算从分组的元素中汇总 `population` 属性的值，并将结果保存在 `pop` 字段中。
. 使用 `sort` 操作，按照 `pop`、`state` 和 `city` 字段对中间结果进行升序排序，使最小的城市位于结果的顶部，最大的城市位于底部。请注意，对 `state` 和 `city` 的排序是隐含地针对 group ID 字段进行的（Spring Data MongoDB 处理）。
. 再次使用 group 操作，将中间结果按 `state` 分组。请注意，`state` 再次隐含地引用了一个 group ID 字段。我们在 `project` 操作中分别调用 `last(…)` 和 `first(…)` 操作符来选择最大和最小的城市（`city`）的名称和人口数（population count）。
. 选择前一个 group 操作中的 `state` 字段。请注意，state 再次隐含地引用了一个 `group` ID字段。因为我们不希望出现一个隐含生成的ID，所以我们通过使用 `and(previousOperation()).exclude()` 将 ID 从之前的操作中排除。因为我们想在我们的输出类中填充嵌套的 `City` 结构，我们必须通过使用嵌套方法来发出适当的子文档。
. 在 `sort` 操作中，将得到的 `StateStats` 列表按其州名以升序排序。

请注意，我们从作为第一个参数传递给 `newAggregation` 方法的 `ZipInfo` 类派生输入集合的名称。

[[mongo.aggregation.examples.example3]]
===== 聚合框架实例 3

这个例子是基于 MongoDB 聚合框架文档中 https://docs.mongodb.org/manual/tutorial/aggregation-examples/#states-with-populations-over-10-million[人口超过1000万的州] 的例子。我们增加了额外的排序，以便在不同的 MongoDB 版本中产生稳定的结果。在这里，我们想使用聚合框架返回所有人口超过1000万的州。这个例子演示了分组、排序和匹配（过滤）。

[source,java]
----
class StateStats {
   @Id String id;
   String state;
   @Field("totalPop") int totalPopulation;
}
----

[source,java]
----
import static org.springframework.data.mongodb.core.aggregation.Aggregation.*;

TypedAggregation<ZipInfo> agg = newAggregation(ZipInfo.class,
    group("state").sum("population").as("totalPop"),
    sort(ASC, previousOperation(), "totalPop"),
    match(where("totalPop").gte(10 * 1000 * 1000))
);

AggregationResults<StateStats> result = mongoTemplate.aggregate(agg, StateStats.class);
List<StateStats> stateStatsList = result.getMappedResults();
----

前面的清单使用以下算法：

. 按 `state` 字段对输入集合进行分组，并计算 `population` 字段的总和，并将结果存储在新字段 `"totalPop"` 中。
. 除了 `"totalPop"` 字段之外，还按前一个 group 操作的 id-reference 对中间结果进行升序排序。
. 通过使用接受 `Criteria` query 作为参数的 match 操作来过滤中间结果。

注意，我们从作为第一个参数传递给 `newAggregation` 方法的 `ZipInfo` 类中导出了输入集合的名称。

[[mongo.aggregation.examples.example4]]
===== 聚合框架实例 4

这个例子演示了在投影操作中使用简单的算术运算。

[source,java]
----
class Product {
    String id;
    String name;
    double netPrice;
    int spaceUnits;
}
----

[source,java]
----
import static org.springframework.data.mongodb.core.aggregation.Aggregation.*;

TypedAggregation<Product> agg = newAggregation(Product.class,
    project("name", "netPrice")
        .and("netPrice").plus(1).as("netPricePlus1")
        .and("netPrice").minus(1).as("netPriceMinus1")
        .and("netPrice").multiply(1.19).as("grossPrice")
        .and("netPrice").divide(2).as("netPriceDiv2")
        .and("spaceUnits").mod(2).as("spaceUnitsMod2")
);

AggregationResults<Document> result = mongoTemplate.aggregate(agg, Document.class);
List<Document> resultList = result.getMappedResults();
----

请注意，我们从作为第一个参数传递给 `newAggregation` 方法的 `Product` 类中导出了输入集合的名称。

[[mongo.aggregation.examples.example5]]
===== 聚合框架实例 5

此示例演示了在投影操作中使用从 SpEL 表达式衍生的简单算术运算。

[source,java]
----
class Product {
    String id;
    String name;
    double netPrice;
    int spaceUnits;
}
----

[source,java]
----
import static org.springframework.data.mongodb.core.aggregation.Aggregation.*;

TypedAggregation<Product> agg = newAggregation(Product.class,
    project("name", "netPrice")
        .andExpression("netPrice + 1").as("netPricePlus1")
        .andExpression("netPrice - 1").as("netPriceMinus1")
        .andExpression("netPrice / 2").as("netPriceDiv2")
        .andExpression("netPrice * 1.19").as("grossPrice")
        .andExpression("spaceUnits % 2").as("spaceUnitsMod2")
        .andExpression("(netPrice * 0.8  + 1.2) * 1.19").as("grossPriceIncludingDiscountAndCharge")

);

AggregationResults<Document> result = mongoTemplate.aggregate(agg, Document.class);
List<Document> resultList = result.getMappedResults();
----

[[mongo.aggregation.examples.example6]]
===== 聚合框架实例 6

这个例子展示了在投影操作中使用来自 SpEL 表达式的复杂算术操作。

Note: 传递给 `addExpression` 方法的额外参数可以根据其位置用索引器表达式来引用。在这个例子中，我们用 `[0]` 引用参数数组的第一个参数。当 SpEL 表达式被转换为 MongoDB 聚合框架表达式时，外部参数表达式被替换为其各自的值。

[source,java]
----
class Product {
    String id;
    String name;
    double netPrice;
    int spaceUnits;
}
----

[source,java]
----
import static org.springframework.data.mongodb.core.aggregation.Aggregation.*;

double shippingCosts = 1.2;

TypedAggregation<Product> agg = newAggregation(Product.class,
    project("name", "netPrice")
        .andExpression("(netPrice * (1-discountRate)  + [0]) * (1+taxRate)", shippingCosts).as("salesPrice")
);

AggregationResults<Document> result = mongoTemplate.aggregate(agg, Document.class);
List<Document> resultList = result.getMappedResults();
----

请注意，我们还可以在 SpEL 表达式中引用文档的其他字段。

[[mongo.aggregation.examples.example7]]
===== 聚合框架实例 7

此示例使用条件投影。 它源自 https://docs.mongodb.com/manual/reference/operator/aggregation/cond/[$cond 参考文档]。

[source,java]
----
public class InventoryItem {

  @Id int id;
  String item;
  String description;
  int qty;
}

public class InventoryItemProjection {

  @Id int id;
  String item;
  String description;
  int qty;
  int discount
}
----

[source,java]
----
import static org.springframework.data.mongodb.core.aggregation.Aggregation.*;

TypedAggregation<InventoryItem> agg = newAggregation(InventoryItem.class,
  project("item").and("discount")
    .applyCondition(ConditionalOperator.newBuilder().when(Criteria.where("qty").gte(250))
      .then(30)
      .otherwise(20))
    .and(ifNull("description", "Unspecified")).as("description")
);

AggregationResults<InventoryItemProjection> result = mongoTemplate.aggregate(agg, "inventory", InventoryItemProjection.class);
List<InventoryItemProjection> stateStatsList = result.getMappedResults();
----

这一步汇总使用了 `inventory` 集合的投影操作。我们通过对所有 `qty` 大于或等于 `250` 的库存项目进行条件性操作来预测 `discount` 字段。对 `description` 字段进行了第二个条件预测。我们对所有没有 `description` 字段的项目或描述为 `null` 的项目应用 `Unspecified` 的 `description`。

从 MongoDB 3.6 开始，可以通过使用条件表达式将字段从投影中排除。

.Conditional aggregation projection
====
[source,java]
----
TypedAggregation<Book> agg = Aggregation.newAggregation(Book.class,
  project("title")
    .and(ConditionalOperators.when(ComparisonOperators.valueOf("author.middle")     <1>
        .equalToValue(""))                                                          <2>
        .then("$$REMOVE")                                                           <3>
        .otherwiseValueOf("author.middle")                                          <4>
    )
	.as("author.middle"));
----
<1> 如果字段 `author.middle` 的值
<2> 不包含一个值，
<3> 然后使用 https://docs.mongodb.com/manual/reference/aggregation-variables/#variable.REMOVE[``$$REMOVE``] 排除该字段。
<4> 否则，添加 `author.middle` 的字段值。
====
