[[mongo.sessions]]
= MongoDB 会话（Session）

从3.6版本开始，MongoDB 支持会话的概念。会话的使用实现了 MongoDB 的 https://docs.mongodb.com/manual/core/read-isolation-consistency-recency/#causal-consistency[Causal Consistency]（因果一致性） 模型，它保证了以尊重其因果关系的顺序运行操作。这些会话被分成 `ServerSession` 实例和 `ClientSession` 实例。
在本节中，当我们谈到会话时，我们指的是 `ClientSession`。

WARNING: 客户端会话内的操作与会话外的操作没有隔离。

`MongoOperations` 和 `ReactiveMongoOperations` 都提供了将 `ClientSession` 绑定到操作上的网关方法。`MongoCollection` 和 `MongoDatabase` 使用实现 MongoDB 的集合和数据库接口的会话代理对象，因此你不需要在每次调用时添加会话。这意味着，对 `MongoCollection#find()` 的潜在调用被委托给 `MongoCollection#find(ClientSession)`。

NOTE: `(Reactive)MongoOperations#getCollection` 等方法返回原生 MongoDB Java Driver 网关对象（如 `MongoCollection`），这些对象本身为 `ClientSession` 提供专用方法。这些方法不是会话代理的。在与 `MongoCollection` 或 `MongoDatabase` 直接交互时，你应该在需要时提供 `ClientSession`，而不是通过 `MongoOperations` 上的 `#execute` 回调。

[[mongo.sessions.sync]]
== 支持同步的 `ClientSession`.

下面的例子显示了一个会话的用法。

.`ClientSession` 和 `MongoOperations`
====
[source,java]
----
ClientSessionOptions sessionOptions = ClientSessionOptions.builder()
    .causallyConsistent(true)
    .build();

ClientSession session = client.startSession(sessionOptions); <1>

template.withSession(() -> session)
    .execute(action -> {

        Query query = query(where("name").is("Durzo Blint"));
        Person durzo = action.findOne(query, Person.class);  <2>

        Person azoth = new Person("Kylar Stern");
        azoth.setMaster(durzo);

        action.insert(azoth);                                <3>

        return azoth;
    });

session.close()                                              <4>
----
<1> 从服务器获取一个新的会话。
<2> 像以前一样使用 `MongoOperation` 方法。`ClientSession` 会被自动应用。
<3> 确保关闭 `ClientSession`.
<4> 关闭 session.
====

WARNING: 当处理 `DBRef` 实例时，特别是懒加载的实例，在所有数据被加载之前不要关闭 `ClientSession` 是非常重要的。否则，懒加载会失败。

[[mongo.sessions.reactive]]
== 支持响应式的 `ClientSession`

如下面的例子所示，响应式的对应方法使用与命令式相同的构件。

.ClientSession with ReactiveMongoOperations
====
[source,java]
----
ClientSessionOptions sessionOptions = ClientSessionOptions.builder()
    .causallyConsistent(true)
    .build();

Publisher<ClientSession> session = client.startSession(sessionOptions); <1>

template.withSession(session)
    .execute(action -> {

        Query query = query(where("name").is("Durzo Blint"));
        return action.findOne(query, Person.class)
            .flatMap(durzo -> {

                Person azoth = new Person("Kylar Stern");
                azoth.setMaster(durzo);

                return action.insert(azoth);                            <2>
            });
    }, ClientSession::close)                                            <3>
    .subscribe();                                                       <4>
----
<1> 为新的会话检索获得一个 `Publisher` 。
<2> 像以前一样使用 `ReactiveMongoOperation` 方法。自动获得并应用 `ClientSession`。
<3> 确保关闭 `ClientSession`.
<4> 在你订阅之前什么都不会发生。详见 https://projectreactor.io/docs/core/release/reference/#reactive.subscribe[the Project Reactor Reference Guide].
====

通过使用一个提供实际会话的 `Publisher`，你可以将会话的获取推迟到实际订阅的时候。但是，你仍然需要在完成后关闭会话，这样就不会让旧的会话污染服务器。当你不再需要会话时，
使用 `execute` 上的 `doFinally` 钩子来调用 `ClientSession#close()`。如果你喜欢对会话本身有更多的控制，你可以通过驱动获得 `ClientSession`，并通过 `Supplier` 来提供它。

NOTE: `ClientSession` 的响应式使用仅限于 Template API 的使用。目前还没有与响应式 repository 的会话集成。

[[mongo.transactions]]
= MongoDB 事务

从版本4开始，MongoDB支持  https://www.mongodb.com/transactions[事务]。事务是建立在 <<mongo.sessions,Sessions>> 之上的，因此，需要一个活跃的 `ClientSession`。

NOTE: 除非你在你的应用程序上下文中指定一个 `MongoTransactionManager`，否则事务支持是 *DISABLED*（禁用的）。你可以使用 `setSessionSynchronization(ALWAYS)` 来参与正在进行的非本地 MongoDB 事务。

为了获得对事务的完全程序化控制，你可能想在 `MongoOperations` 上使用会话回调。

下面的例子显示了在一个 `SessionCallback` 中的程序化事务控制。

.程序性事务
====
[source,java]
----
ClientSession session = client.startSession(options);                   <1>

template.withSession(session)
    .execute(action -> {

        session.startTransaction();                                     <2>

        try {

            Step step = // ...;
            action.insert(step);

            process(step);

            action.update(Step.class).apply(Update.set("state", // ...

            session.commitTransaction();                                <3>

        } catch (RuntimeException e) {
            session.abortTransaction();                                 <4>
        }
    }, ClientSession::close)                                            <5>
----
<1> 获得一个新的 `ClientSession`.
<2> 开始事务.
<3> 如果一切按预期进行，就提交修改
<4> 出现意外，所以要回滚一切。
<5> 完成后不要忘记关闭会话。
====

前面的例子让你完全控制事务行为，同时在回调中使用会话范围的 `MongoOperations` 实例，以确保会话被传递给每个服务器调用。为了避免这种方法带来的一些开销，你可以使用 `TransactionTemplate` 来消除手动事务流的一些噪音。

[[mongo.transactions.transaction-template]]
== 事务和 `TransactionTemplate`

Spring Data MongoDB 事务支持一个 `TransactionTemplate`。下面的例子展示了如何创建和使用 `TransactionTemplate`。

.事务和 `TransactionTemplate`
====
[source,java]
----
template.setSessionSynchronization(ALWAYS);                                     <1>

// ...

TransactionTemplate txTemplate = new TransactionTemplate(anyTxManager);         <2>

txTemplate.execute(new TransactionCallbackWithoutResult() {

    @Override
    protected void doInTransactionWithoutResult(TransactionStatus status) {     <3>

        Step step = // ...;
        template.insert(step);

        process(step);

        template.update(Step.class).apply(Update.set("state", // ...
    };
});
----
<1> 在 Template API 配置中启用事务同步。
<2> 使用提供的 `PlatformTransactionManager` 创建 `TransactionTemplate`。
<3> 在回调中，`ClientSession` 和事务已经被注册。
====

CAUTION: 在运行期间改变 `MongoTemplate` 的状态（就像你可能认为在前面列表的第1项中可能发生的那样）会导致线程和可见性问题。

[[mongo.transactions.tx-manager]]
== 事务和 `MongoTransactionManager`

`MongoTransactionManager` 是通往众所周知的 Spring 事务支持的网关。它可以让应用程序使用 https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/html/transaction.html[Spring 的事务托管功能] 。`MongoTransactionManager` 将一个 `ClientSession` 绑定到线程上。`MongoTemplate` 会检测会话，
并相应地对这些与事务相关的资源进行操作。`MongoTemplate` 也可以参与到其他正在进行的事务中。下面的例子展示了如何用 `MongoTransactionManager` 创建和使用事务。

.事务和 MongoTransactionManager
====
[source,java]
----
@Configuration
static class Config extends AbstractMongoClientConfiguration {

    @Bean
    MongoTransactionManager transactionManager(MongoDatabaseFactory dbFactory) {  <1>
        return new MongoTransactionManager(dbFactory);
    }

    // ...
}

@Component
public class StateService {

    @Transactional
    void someBusinessFunction(Step step) {                                        <2>

        template.insert(step);

        process(step);

        template.update(Step.class).apply(Update.set("state", // ...
    };
});

----
<1> 在应用 application context 中注册 `MongoTransactionManager`
<2> 将方法标记为事务性。
====

NOTE: `@Transactional(readOnly = true)` 建议 `MongoTransactionManager` 也启动一个事务，将 `ClientSession` 添加到发出的请求中。

[[mongo.transactions.reactive]]
== 响应式事务

与支持响应式 `ClientSession` 一样，`ReactiveMongoTemplate` 提供了专门的方法，用于在事务中进行操作，而不必担心根据操作结果提交或停止操作。

NOTE: 除非你在你的 application context 中指定一个 `ReactiveMongoTransactionManager`，否则事务支持是 *DISABLED*（禁用的）。你可以使用 `setSessionSynchronization(ALWAYS)` 来参与正在进行的非本地 MongoDB 事务。

使用普通的MongoDB响应式驱动API，在一个事务性流程中的 `delete` 可能看起来像这样。

.原生驱动的支持
====
[source,java]
----
Mono<DeleteResult> result = Mono
    .from(client.startSession())                                                             <1>

    .flatMap(session -> {
        session.startTransaction();                                                          <2>

        return Mono.from(collection.deleteMany(session, ...))                                <3>

            .onErrorResume(e -> Mono.from(session.abortTransaction()).then(Mono.error(e)))   <4>

            .flatMap(val -> Mono.from(session.commitTransaction()).then(Mono.just(val)))     <5>

            .doFinally(signal -> session.close());                                           <6>
      });
----
<1> 首先，我们显然需要启动 session。
<2> 一旦我们有了 `ClientSession`，就开始事务。
<3> 通过向操作传递 `ClientSession`，在事务中进行操作。
<4> 如果操作异常完成，我们需要停止事务并保留错误。
<5> 当然，也可以在成功的情况下提交更改。仍然保留操作结果。
<6> 最后，我们需要确保关闭会话
====

上述操作的罪魁祸首是在保留 main flow `DeleteResult`，而不是通过 `commitTransaction()` 或 `abortTransaction()` 发布的事务结果，这导致了相当复杂的设置。

[[mongo.transactions.reactive-operator]]
== 事务和 `TransactionalOperator`

Spring Data MongoDB事务支持一个 `TransactionalOperator`。下面的例子展示了如何创建和使用一个 `TransactionalOperator`。

.事务和 `TransactionalOperator`
====
[source,java]
----
template.setSessionSynchronization(ALWAYS);                                          <1>

// ...

TransactionalOperator rxtx = TransactionalOperator.create(anyTxManager,
                                   new DefaultTransactionDefinition());              <2>


Step step = // ...;
template.insert(step);

Mono<Void> process(step)
    .then(template.update(Step.class).apply(Update.set("state", …))
    .as(rxtx::transactional)                                                         <3>
    .then();
----
<1> 为事务性参与启用事务同步。
<2> 使用提供的 `ReactiveTransactionManager` 创建 `TransactionalOperator`。
<3> `TransactionalOperator.transactional(…)` 为所有上游操作提供事务管理。
====

[[mongo.transactions.reactive-tx-manager]]
== 事务和 `ReactiveMongoTransactionManager`

`ReactiveMongoTransactionManager` 是通往众所周知的 Spring 事务支持 的网关。它允许应用程序利用 https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/html/transaction.html[Spring 的管理事务功能]。`ReactiveMongoTransactionManager` 将 `ClientSession` 绑定到 `subscriber` Context。
`ReactiveMongoTemplate` 会检测会话，并对这些与事务相关的资源进行相应操作。 `ReactiveMongoTemplate` 也可以参与其他正在进行的事务。下面的例子展示了如何用 `ReactiveMongoTransactionManager` 创建和使用事务。

.事务和 `ReactiveMongoTransactionManager`
====
[source,java]
----
@Configuration
public class Config extends AbstractReactiveMongoConfiguration {

    @Bean
    ReactiveMongoTransactionManager transactionManager(ReactiveMongoDatabaseFactory factory) {  <1>
        return new ReactiveMongoTransactionManager(factory);
    }

    // ...
}

@Service
public class StateService {

    @Transactional
    Mono<UpdateResult> someBusinessFunction(Step step) {                                  <2>

        return template.insert(step)
            .then(process(step))
            .then(template.update(Step.class).apply(Update.set("state", …));
    };
});

----
<1> 在 application context中注册 `ReactiveMongoTransactionManager`。
<2> 将方法标记为事务性的。
====

NOTE: `@Transactional(readOnly = true)` 建议 `ReactiveMongoTransactionManager` 也启动一个事务，将 `ClientSession` 添加到发出的请求中。

[[mongo.transactions.behavior]]
== 事务内部的特殊行为

在事务内部，MongoDB 服务器有一个稍微不同的行为。

*Connection Settings*

MongoDB驱动提供了一个专门的副本集名称配置选项，使驱动进入自动检测模式。这个选项有助于识别主要的副本集节点和事务中的命令路由。

NOTE: 确保在 MongoDB 的 URI 中添加 `replicaSet`。请参考 https://docs.mongodb.com/manual/reference/connection-string/#connections-connection-options[连接字符串选项] 以了解更多细节。

*Collection Operations*

MongoDB 不支持集合操作，例如在事务中创建集合。这也会影响到第一次使用时发生的即时集合创建。因此，请确保所有需要的结构都已到位。

*Transient Errors*

MongoDB 可以为在事务性操作中出现的错误添加特殊标签。这些标签可能表示暂时性的故障，这些故障可能通过重试操作而消失。我们强烈推荐 https://github.com/spring-projects/spring-retry[Spring Retry] 用于这些目的。
然而，我们可以覆写 `MongoTransactionManager#doCommit(MongoTransactionObject)`，以实现 MongoDB 参考手册中所述的 https://docs.mongodb.com/manual/core/transactions/#retry-commit-operation[重试提交操作行为] 。

*Count*

MongoDB的 `count` 操作是基于集合统计的，可能无法反映事务中的实际情况。当在一个多文档事务中发出 `count` 命令时，服务器会响应 error 50851。一旦 `MongoTemplate` 检测到一个活动的事务，所有暴露的 `count()` 方法都会被转换，
并使用 `$match` 和 `$count` 操作符委托给聚合框架，保留 `Query` 设置，如 `collation`。

在 aggregation count helper 中使用 `geo` 命令时，有一些限制。以下运算符不能使用，必须用不同的运算符代替。

* `$where` -> `$expr`
* `$near` -> `$geoWithin` with `$center`
* `$nearSphere` -> `$geoWithin` with `$centerSphere`

使用 `Criteria.near(…)` 和 `Criteria.nearSphere(…)` 的查询必须改写为 `Criteria.within(…)` 各自的 `Criteria.withinSphere(…)`。同样适用于 repository 查询方法中的 `near` 查询关键字，必须改为 `within`。也请参见 MongoDB JIRA ticket https://jira.mongodb.org/browse/DRIVERS-518[DRIVERS-518] 以进一步参考。

下面的片段显示了会话绑定闭包内的 `count` 用法。

====
[source,javascript]
----
session.startTransaction();

template.withSession(session)
    .execute(action -> {
        action.count(query(where("state").is("active")), Step.class)
        ...
----
====

上面的片段具体化为以下命令:

====
[source,javascript]
----
db.collection.aggregate(
   [
      { $match: { state: "active" } },
      { $count: "totalEntityCount" }
   ]
)
----
====

而不是:

====
[source,javascript]
----
db.collection.find( { state: "active" } ).count()
----
====
