[[mapping-usage-references]]
=== 使用 DBRef

映射框架不一定要把子对象嵌入到文档中去存储。你也可以单独存储它们，并使用一个 `DBRef` 来引用该文档。当对象从 MongoDB 加载时，这些引用会被急切地解析，这样你得到的映射对象看起来就像它被嵌入到你的顶级文档中存储一样。

下面的例子使用一个 DBRef 来引用一个特定的文档，该文档独立于它被引用的对象而存在（为了简洁起见，两个类都是在线显示）。

====
[source,java]
----
@Document
public class Account {

  @Id
  private ObjectId id;
  private Float total;
}

@Document
public class Person {

  @Id
  private ObjectId id;
  @Indexed
  private Integer ssn;
  @DBRef
  private List<Account> accounts;
}
----
====

你不需要使用 `@OneToMany` 或类似的机制，因为对象的列表告诉映射框架你想要一个一对多的关系。当对象被存储在 MongoDB 中时，有一个 `DBRefs` 的列表，而不是 `Account` 对象本身。当涉及到加载 `DBRef` 的集合时，建议将集合类型中持有的引用限制在一个特定的 MongoDB 集合。
这允许批量加载所有的引用，而指向不同 MongoDB 集合的引用则需要一个一个地解析。

IMPORTANT: 映射框架不处理级联保存。如果你改变一个被 `Person` 对象引用的 `Account` 对象，你必须单独保存 `Account` 对象。在 `Person` 对象上调用保存并不会自动保存 `Account` 属性中的 `Account` 对象。

`DBRef` 也可以被延迟地解析。在这种情况下，实际的 `Object` 或引用 `Collection` 在第一次访问该属性时被解析。使用 `@DBRef` 的 `lazy` 属性来指定这一点。同样被定义为懒加载 `DBRef` 并被用作构造函数参数的必要属性也会用懒加载代理进行装饰，以确保尽可能地减少对数据库和网络的压力。

TIP: 懒加载 `DBRef` 可能很难调试。确保工具不会通过调用 `toString()` 或一些内联 debug 渲染调用属性 getter 而意外地触发代理解析。请考虑为 `org.springframework.data.mongodb.core.convert.DefaultDbRefResolver` 启用 trace logging，以深入了解 `DBRef` 的解析情况。

CAUTION: 懒加载可能需要类代理，而类代理又可能需要访问 jdk 内部，由于 https://openjdk.java.net/jeps/396[JEP 396: Strongly Encapsulate JDK Internals by Default] 的规定，从 Java 16+ 开始，这些内部是不开放的。默认情况下强封装JDK内部。对于这些情况，请考虑退回到一个接口类型（例如，从 `ArrayList` 切换到 `List`）或提供必要的 `--add-opens` 参数。

[[mapping-usage.document-references]]
=== 使用文档引用

使用 `@DocumentReference` 提供了一种在 MongoDB 中引用实体的灵活方式。虽然目标与使用 <<mapping-usage-references,DBRefs>> 时相同，但存储的表示方法却不同。DBRef 解析到一个具有固定结构的文档，如 https://docs.mongodb.com/manual/reference/database-references/[MongoDB Reference documentation] 中所述。

文档引用，不遵循特定的格式。它们实际上可以是任何东西，一个单一的值，整个文档，基本上所有可以存储在 MongoDB 中的东西。默认情况下，映射层将使用被引用实体的 `id` 值进行存储和检索，就像下面的例子。

====
[source,java]
----
@Document
class Account {

  @Id
  String id;
  Float total;
}

@Document
class Person {

  @Id
  String id;

  @DocumentReference                                   <1>
  List<Account> accounts;
}
----

[source,java]
----
Account account = …

tempate.insert(account);                               <2>

template.update(Person.class)
  .matching(where("id").is(…))
  .apply(new Update().push("accounts").value(account)) <3>
  .first();
----

[source,json]
----
{
  "_id" : …,
  "accounts" : [ "6509b9e" … ]                        <4>
}
----
<1> 标记要引用的 `Account` 值的集合。
<2> 映射框架不处理级联保存，所以要确保单独持久化被引用的实体。
<3> 添加对现有实体的引用。
<4> 被引用的 `Account` 实体被表示为其 `_id` 值的数组。
====

上面的例子使用基于 `_id` 的 fetch query (`{ '_id' : ?#{#target} }`) 进行数据检索，并急切地解析链接实体。可以使用 `@DocumentReference` 的属性来改变解析默认值（如下所列）。

.@DocumentReference 默认值
[cols="2,3,5",options="header"]
|===
| 属性 | 描述 | 默认值

| `db`
| 用于集合查询的目标数据库名称。
| `MongoDatabaseFactory.getMongoDatabase()`

| `collection`
| 目标集合的名称。
| 被注解的属性的 domain 类型，如果是类似于 `Collection` 或 `Map` 的属性，则分别是值类型，集合名称。

| `lookup`
| 单个文档查找查询通过 SpEL 表达式评估占位符，使用 `#target` 作为给定源值的标记。类似于 `Collection` 或 `Map` 的属性通过 `$or` 运算符将单个查找结合起来。
| 一个基于 `_id` 字段的查询 (`{ '_id' : ?#{#target} }`)，使用加载的 source value。

| `sort`
| 用于在服务器端对结果文档进行排序。
| 默认为 `None`。类似于 `Collection` 的属性的结果顺序会根据所使用的 lookup query 在尽力的基础上进行恢复。

| `lazy`
| 如果设置为 `true`，则在第一次访问该属性时延迟解析。
| 默认情况下，急切地解析属性。
|===

CAUTION: 懒加载可能需要类代理，而类代理又可能需要访问 jdk 内部（internal），由于 https://openjdk.java.net/jeps/396[JEP 396: Strongly Encapsulate JDK Internals by Default] 的规定，从 Java 16+ 开始，这些内部是不开放的。默认情况下强封装JDK内部。对于这些情况，请考虑退回到一个接口类型（例如，从 `ArrayList` 切换到 `List`）或提供必要的 `--add-opens` 参数。

`@DocumentReference(lookup)` 允许定义与 `_id` 字段不同的过滤查询，因此提供了一种灵活的方式来定义实体之间的引用，正如下面的例子所展示的那样，book 的 `Publisher` 被其 `acronym` 而不是内部 `id` 所引用。

====
[source,java]
----
@Document
class Book {

  @Id
  ObjectId id;
  String title;
  List<String> author;

  @Field("publisher_ac")
  @DocumentReference(lookup = "{ 'acronym' : ?#{#target} }") <1>
  Publisher publisher;
}

@Document
class Publisher {

  @Id
  ObjectId id;
  String acronym;                                            <1>
  String name;

  @DocumentReference(lazy = true)                            <2>
  List<Book> books;

}
----

.`Book` document
[source,json]
----
{
  "_id" : 9a48e32,
  "title" : "The Warded Man",
  "author" : ["Peter V. Brett"],
  "publisher_ac" : "DR"
}
----

.`Publisher` document
[source,json]
----
{
  "_id" : 1a23e45,
  "acronym" : "DR",
  "name" : "Del Rey",
  …
}
----
<1> 使用 `acronym` 字段来查询 `Publisher` 集合中的实体。
<2> 懒加载回对 `Book` 集合的引用。
====

上面的片段显示了使用自定义引用对象时的读取情况。写作需要一些额外的设置，因为映射信息并不表达 `#target` 来自哪里。映射层需要在目标文档和 `DocumentPointer` 之间注册一个 `Converter`，就像下面这个。

====
[source,java]
----
@WritingConverter
class PublisherReferenceConverter implements Converter<Publisher, DocumentPointer<String>> {

	@Override
	public DocumentPointer<String> convert(Publisher source) {
		return () -> source.getAcronym();
	}
}
----
====

如果没有提供 `DocumentPointer` converter，目标参考文档可以根据给定的查找查询进行计算。在这种情况下，关联的目标属性被评估，如下面的例子所示。

====
[source,java]
----
@Document
class Book {

  @Id
  ObjectId id;
  String title;
  List<String> author;

  @DocumentReference(lookup = "{ 'acronym' : ?#{acc} }") <1> <2>
  Publisher publisher;
}

@Document
class Publisher {

  @Id
  ObjectId id;
  String acronym;                                        <1>
  String name;

  // ...
}
----

[source,json]
----
{
  "_id" : 9a48e32,
  "title" : "The Warded Man",
  "author" : ["Peter V. Brett"],
  "publisher" : {
    "acc" : "DOC"
  }
}
----
<1> 使用 `acronym` 字段来查询 `Publisher` 集合中的实体。
<2> lookup query 的字段值占位符（如 `acc`）被用来形成引用文档。
====

也可以使用 `@ReadonlyProperty` 和 `@DocumentReference` 的组合来建立关系式的一对多引用。这种方法允许链接类型（link type）不在拥有的文档中存储链接值，而是在引用的文档中存储，如下面的例子所示。

====
[source,java]
----
@Document
class Book {

  @Id
  ObjectId id;
  String title;
  List<String> author;

  ObjectId publisherId;                                        <1>
}

@Document
class Publisher {

  @Id
  ObjectId id;
  String acronym;
  String name;

  @ReadOnlyProperty                                            <2>
  @DocumentReference(lookup="{'publisherId':?#{#self._id} }")  <3>
  List<Book> books;
}
----

.`Book` document
[source,json]
----
{
  "_id" : 9a48e32,
  "title" : "The Warded Man",
  "author" : ["Peter V. Brett"],
  "publisherId" : 8cfb002
}
----

.`Publisher` document
[source,json]
----
{
  "_id" : 8cfb002,
  "acronym" : "DR",
  "name" : "Del Rey"
}
----
<1> 通过在 `Book` 文档中存储 `Publisher.id`，设置从 `Book`（引用）到 `Publisher`（所有者）的链接。
<2> 将持有引用的属性标记为只读。这可以防止在 `Publisher` 文档中存储对个别 `Book` 的引用。
<3> 使用 `#self` 变量来访问 `Publisher` 文档中的值，并在此检索具有匹配 `publisherId` 的 `Books`。
====

有了以上所有的东西，就有可能对实体之间的各种关联进行建模。请看下面这个不完全的样本列表，以获得对可能的东西的感觉。

.使用 id 字段的简单文档引用
====
[source,java]
----
class Entity {
  @DocumentReference
  ReferencedObject ref;
}
----

[source,json]
----
// entity
{
  "_id" : "8cfb002",
  "ref" : "9a48e32" <1>
}

// referenced object
{
  "_id" : "9a48e32" <1>
}
----
<1> MongoDB 的简单类型可以直接使用，无需进一步配置。
====

.使用 id 字段的简单文档参考，带有明确的 lookup query。
====
[source,java]
----
class Entity {
  @DocumentReference(lookup = "{ '_id' : '?#{#target}' }") <1>
  ReferencedObject ref;
}
----

[source,json]
----
// entity
{
  "_id" : "8cfb002",
  "ref" : "9a48e32"                                        <1>
}

// referenced object
{
  "_id" : "9a48e32"
}
----
<1> _target_ 定义了引用值本身。
====

.文档引用提取查询的 `refKey` 字段
====
[source,java]
----
class Entity {
  @DocumentReference(lookup = "{ '_id' : '?#{refKey}' }")  <1> <2>
  private ReferencedObject ref;
}
----

[source,java]
----
@WritingConverter
class ToDocumentPointerConverter implements Converter<ReferencedObject, DocumentPointer<Document>> {
	public DocumentPointer<Document> convert(ReferencedObject source) {
		return () -> new Document("refKey", source.id);    <1>
	}
}
----

[source,json]
----
// entity
{
  "_id" : "8cfb002",
  "ref" : {
    "refKey" : "9a48e32"                                   <1>
  }
}

// referenced object
{
  "_id" : "9a48e32"
}
----
<1> 用于获取引用值的 key 必须是写入时使用的 key 。
<2> `refKey` 是 `target.refKey` 的缩写。
====

.有多个值的文件引用，形成 lookup query
====
[source,java]
----
class Entity {
  @DocumentReference(lookup = "{ 'firstname' : '?#{fn}', 'lastname' : '?#{ln}' }") <1> <2>
  ReferencedObject ref;
}
----

[source,json]
----
// entity
{
  "_id" : "8cfb002",
  "ref" : {
    "fn" : "Josh",           <1>
    "ln" : "Long"            <1>
  }
}

// referenced object
{
  "_id" : "9a48e32",
  "firsntame" : "Josh",      <2>
  "lastname" : "Long",       <2>
}
----
<1> 根据 lookup query，从链接文档中读取/写入key `fn` & `ln`。
<2> 使用非 `id` 字段来查找目标文档。
====

.Document Reference reading from a target collection
====
[source,java]
----
class Entity {
  @DocumentReference(lookup = "{ '_id' : '?#{id}' }", collection = "?#{collection}") <2>
  private ReferencedObject ref;
}
----

[source,java]
----
@WritingConverter
class ToDocumentPointerConverter implements Converter<ReferencedObject, DocumentPointer<Document>> {
	public DocumentPointer<Document> convert(ReferencedObject source) {
		return () -> new Document("id", source.id)                                   <1>
                           .append("collection", … );                                <2>
	}
}
----

[source,json]
----
// entity
{
  "_id" : "8cfb002",
  "ref" : {
    "id" : "9a48e32",                                                                <1>
    "collection" : "…"                                                               <2>
  }
}
----
<1> 从参考文档中读取/写入key `_id`，以便在 lookup query 中使用它们。
<2> 集合的名称可以通过引用文档的 key 来读取。
====

[WARNING]
====
我们知道，在 lookup query 中使用各种MongoDB查询操作符是很诱人的，这也很好。但是有几个方面需要考虑:

* 请确保有支持你的查询的索引。
* 注意，解决这个问题需要一个服务器rountrip引起的延迟，考虑延迟策略。
* 使用 `$or` 操作符批量加载一个文档引用集合。

原始元素的顺序会在内存中以最佳方式恢复。只有在使用等价表达式时才能恢复顺序，而在使用 MongoDB 查询操作符时不能恢复。在这种情况下，结果将在从 store 收到时或通过提供的 `@DocumentReference(sort)` 属性进行排序。

再谈几句一般性的意见:

* 你是否使用循环引用？问问你自己是否需要它们。
* 懒加载文档引用是很难调试的。确保工具不会通过调用 `toString()` 等方式意外地触发代理解析。
* 没有支持使用响应式基础设施来阅读文档引用。
====
