[[gridfs]]
== 支持 GridFS

MongoDB 支持在其文件系统 GridFS 中存储二进制文件。Spring Data MongoDB 提供了一个 `GridFsOperations` 接口以及相应的实现，即 `GridFsTemplate`，让你与文件系统互动。
你可以通过给它一个 `MongoDatabaseFactory` 以及一个 `MongoConverter` 来设置一个 `GridFsTemplate` 实例，如下例所示。

====
.Java
[source,java,role="primary"]
----
class GridFsConfiguration extends AbstractMongoClientConfiguration {

  // … further configuration omitted

  @Bean
  public GridFsTemplate gridFsTemplate() {
    return new GridFsTemplate(mongoDbFactory(), mappingMongoConverter());
  }
}
----

.XML
[source,xml,role="secondary"]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:mongo="http://www.springframework.org/schema/data/mongo"
  xsi:schemaLocation="http://www.springframework.org/schema/data/mongo
                      https://www.springframework.org/schema/data/mongo/spring-mongo.xsd
                      http://www.springframework.org/schema/beans
                      https://www.springframework.org/schema/beans/spring-beans.xsd">

  <mongo:db-factory id="mongoDbFactory" dbname="database" />
  <mongo:mapping-converter id="converter" />

  <bean class="org.springframework.data.mongodb.gridfs.GridFsTemplate">
    <constructor-arg ref="mongoDbFactory" />
    <constructor-arg ref="converter" />
  </bean>

</beans>
----
====

现在，该 template 可以被注入并用于执行存储和检索操作，如下例所示。

.使用 GridFsTemplate 来存储文件
====
[source,java]
----
class GridFsClient {

  @Autowired
  GridFsOperations operations;

  @Test
  public void storeFileToGridFs() {

    FileMetadata metadata = new FileMetadata();
    // populate metadata
    Resource file = … // lookup File or Resource

    operations.store(file.getInputStream(), "filename.txt", metadata);
  }
}
----
====

`store(…)` 操作接收一个 `InputStream`、一个文件名和（可选择的）关于要存储的文件的元数据信息。元数据可以是一个任意的对象，它将被配置在 `GridFsTemplate` 中的 `MongoConverter` 处理。另外，你也可以提供一个 `Document`。

你可以通过 `find(…)` 或 `getResources(…)` 方法从文件系统中读取文件。让我们先看一下 `find(…)` 方法。你可以找到一个文件，也可以找到符合 `Query` 条件的多个文件。你可以使用 `GridFsCriteria` helper 类来定义查询。它提供了静态的工厂方法来封装默认的元数据字段（比如 `whereFilename()` 和 `whereContentType()`），
或者通过 `whereMetaData()` 封装一个自定义的元数据。下面的例子显示了如何使用 `GridFsTemplate` 来查询文件。

.使用 GridFsTemplate 来查询文件
====
[source,java]
----
class GridFsClient {

  @Autowired
  GridFsOperations operations;

  @Test
  public void findFilesInGridFs() {
    GridFSFindIterable result = operations.find(query(whereFilename().is("filename.txt")))
  }
}
----
====

NOTE: 目前，MongoDB 不支持在从 GridFS 检索文件时定义排序标准。出于这个原因，任何定义在 Query 实例上的排序标准都会被忽略，而这些排序标准会被交给 `find(…)` 方法来处理。

从 GridFs 读取文件的另一个选择是使用 `ResourcePatternResolver` 接口引入的方法。它们允许在方法中输入 `Ant` 路径，因此可以检索到与给定 pattern 相匹配的文件。下面的例子显示了如何使用 `GridFsTemplate` 来读取文件。

.使用 GridFsTemplate 来读取文件
====
[source,java]
----
class GridFsClient {

  @Autowired
  GridFsOperations operations;

  @Test
  public void readFilesFromGridFs() {
    GridFsResources[] txtFiles = operations.getResources("*.txt");
  }
}
----
====

`GridFsOperations` 继承了 `ResourcePatternResolver`，并允许将 `GridFsTemplate`（例如）插入 `ApplicationContext`，以从 MongoDB 数据库读取 Spring 配置文件。
