
[[mapping-chapter]]
= 映射（Mapping）

丰富的映射支持是由 `MappingMongoConverter` 提供的。`MappingMongoConverter` 有一个丰富的元数据模型，提供完整的功能集，将 domain 对象映射到 MongoDB 文档。映射元数据模型是通过在你的 domain 对象上使用注解来填充的。
然而，该基础设施并不限于使用注解作为元数据信息的唯一来源。`MappingMongoConverter` 还可以让你在不提供任何额外元数据的情况下，通过遵循一组约定，将对象映射到文档。

本节介绍了 `MappingMongoConverter` 的功能，包括基本原理，如何使用约定将对象映射到文档，以及如何用基于注解的映射元数据覆盖这些约定。

include::{spring-data-commons-location}/object-mapping.adoc[leveloffset=+1]

[[mapping-conventions]]
== 基于常规的映射

当没有提供额外的映射元数据时，`MappingMongoConverter` 有一些惯例用于将对象映射到文档。这些约定如下：

* 短的Java类名以如下方式映射到集合名。`com.bigbank.SavingsAccount` 这个类映射到 `savingsAccount` 集合的名称。
* 所有的嵌套对象都作为文档中的嵌套对象而不是作为 DBRefs 来存储。
* converter 使用与它注册的任何 Spring Converter 来覆盖对象属性到文档字段和值的默认映射。
* 一个对象的字段被用来转换为文档中的字段和从文档中转换。public `JavaBean` 属性不被使用。
* 如果你有一个单一的非零参数构造器，其构造器参数名称与文档的顶级字段名称相匹配，则使用该构造器。否则，将使用零参数的构造函数。如果有一个以上的非零参数构造函数，将抛出一个异常。

[[mapping.conventions.id-field]]
=== 在映射层中如何处理 `_id` 字段

MongoDB 要求你为所有文档提供一个 `_id` 字段。如果你没有提供一个，驱动程序将分配一个生成值的 `ObjectId`。 "_id" 字段可以是任何类型，而不是数组，只要它是唯一的。驱动程序自然支持所有原始类型和日期。当使用 `MappingMongoConverter` 时，有一些规则规定了如何将 Java 类的属性映射到 `_id` 字段。

下面概述了什么字段将被映射到 `_id` 文档字段。

* 一个用 `@Id` (`org.springframework.data.annotation.Id`) 注解的字段将被映射到 `_id` 字段。
* 一个没有注解但名为 id 的字段将被映射到 `_id` 字段。
* id 的默认字段名是 `_id`，可以通过 `@Field` 注解进行自定义。

[cols="1,2", options="header"]
.转换 `_id` 字段定义的例子
|===
| Field definition
| Resulting Id-Fieldname in MongoDB

| `String` id
| `_id`

| `@Field` `String` id
| `_id`

| `@Field("x")` `String` id
| `x`

| `@Id` `String` x
| `_id`

| `@Field("x")` `@Id` `String` x
| `_id`
|===

下面概述了将对映射到 `_id` 文档字段的属性进行何种类型转换（如果有的话）。

* 如果一个名为 `id` 的字段在 Java 类中被声明为 `String` 或 `BigInteger`，它将被转换为 `ObjectId` 并尽可能地存储。`ObjectId` 作为一个字段类型也是有效的。如果你在你的应用程序中为 `id` 指定了一个值，那么转换为 `ObjectId` 的过程会被 MongoDB 驱动检测到。
如果指定的 `id` 值不能被转换为 `ObjectId`，那么该值将被原样存储在文档的 `_id` 字段中。这也适用于该字段被注解为 `@Id` 的情况。
* 如果一个字段在 Java 类中被 `@MongoId` 注解，它将被转换为使用其实际类型进行存储。除非 `@MongoId` 声明了一个想要的字段类型，否则不会发生进一步的转换。如果没有为 `id` 字段提供值，一个新的 `ObjectId` 将被创建并转换为属性类型。
* 如果一个字段在 Java 类中被注解为 `@MongoId(FieldType….)`，它将尝试将该值转换为声明的 `FieldType`。如果没有为 `id` 字段提供任何值，将创建一个新的 `ObjectId`，并转换为声明的类型。
* 如果一个名为 `id` 的字段在 Java 类中没有被声明为 `String`、`BigInteger` 或 `ObjectID`，那么你应该在你的应用程序中为它赋值，这样它就可以 "按原样" 存储在文档的 `_id` 字段中。
* 如果 Java 类中没有名为 `id` 的字段，那么驱动程序将生成一个隐含的 `_id` 文件，但不会映射到 Java 类的一个属性或字段。

当查询和更新时，`MongoTemplate` 将使用 converter 来处理 `Query` 和 `Update` 对象的转换，这些对象与上述保存文档的规则相对应，因此在你的查询中使用的字段名和类型将能够与你的 domain 类中的内容相匹配。

[[mapping-conversion]]
== 数据映射和类型转换

本节解释了如何将类型映射到 MongoDB 的表示方法，以及如何从 MongoDB 的表示方法中获取类型。Spring Data MongoDB 支持所有可表示为 BSON（MongoDB 的内部文档格式）的类型。除了这些类型外，Spring Data MongoDB 还提供了一组内置的转换器来映射其他类型。你可以提供您自己的转换器来调整类型转换。请参阅 <<mongo.custom-converters>>  以了解更多细节。

下面提供了每个可用类型转换的示例。

[cols="3,1,6", options="header"]
.Type
|===
| 类型
| 类型转换
| 示例

| `String`
| native
| `{"firstname" : "Dave"}`

| `double`, `Double`, `float`, `Float`
| native
| `{"weight" : 42.5}`

| `int`, `Integer`, `short`, `Short`
| native +
32-bit integer
| `{"height" : 42}`

| `long`, `Long`
| native +
64-bit integer
| `{"height" : 42}`

| `Date`, `Timestamp`
| native
| `{"date" : ISODate("2019-11-12T23:00:00.809Z")}`

| `byte[]`
| native
| `{"bin" : { "$binary" : "AQIDBA==", "$type" : "00" }}`

| `java.util.UUID` (Legacy UUID)
| native
| `{"uuid" : { "$binary" : "MEaf1CFQ6lSphaa3b9AtlA==", "$type" : "03" }}`

| `Date`
| native
| `{"date" : ISODate("2019-11-12T23:00:00.809Z")}`

| `ObjectId`
| native
| `{"_id" : ObjectId("5707a2690364aba3136ab870")}`

| Array, `List`, `BasicDBList`
| native
| `{"cookies" : [ … ]}`

| `boolean`, `Boolean`
| native
| `{"active" : true}`

| `null`
| native
| `{"value" : null}`

| `Document`
| native
| `{"value" : { … }}`

| `Decimal128`
| native
| `{"value" : NumberDecimal(…)}`

| `AtomicInteger` +
calling `get()` before the actual conversion
| converter +
32-bit integer
| `{"value" : "741" }`

| `AtomicLong` +
calling `get()` before the actual conversion
| converter +
64-bit integer
| `{"value" : "741" }`

| `BigInteger`
| converter +
`String`
| `{"value" : "741" }`

| `BigDecimal`
| converter +
`String`
| `{"value" : "741.99" }`

| `URL`
| converter
| `{"website" : "https://spring.io/projects/spring-data-mongodb/" }`

| `Locale`
| converter
| `{"locale : "en_US" }`

| `char`, `Character`
| converter
| `{"char" : "a" }`

| `NamedMongoScript`
| converter +
`Code`
| `{"_id" : "script name", value: (some javascript code)`}

| `java.util.Currency`
| converter
| `{"currencyCode" : "EUR"}`

| `Instant` +
(Java 8)
| native
| `{"date" : ISODate("2019-11-12T23:00:00.809Z")}`

| `Instant` +
(Joda, JSR310-BackPort)
| converter
| `{"date" : ISODate("2019-11-12T23:00:00.809Z")}`

| `LocalDate` +
(Joda, Java 8, JSR310-BackPort)
| converter / native (Java8)footnote:[Uses UTC zone offset. Configure via <<mapping-configuration,MongoConverterConfigurationAdapter>>]
| `{"date" : ISODate("2019-11-12T00:00:00.000Z")}`

| `LocalDateTime`, `LocalTime` +
(Joda, Java 8, JSR310-BackPort)
| converter / native (Java8)footnote:[Uses UTC zone offset. Configure via <<mapping-configuration,MongoConverterConfigurationAdapter>>]
| `{"date" : ISODate("2019-11-12T23:00:00.809Z")}`

| `DateTime` (Joda)
| converter
| `{"date" : ISODate("2019-11-12T23:00:00.809Z")}`

| `ZoneId` (Java 8, JSR310-BackPort)
| converter
| `{"zoneId" : "ECT - Europe/Paris"}`

| `Box`
| converter
| `{"box" : { "first" : { "x" : 1.0 , "y" : 2.0} , "second" : { "x" : 3.0 , "y" : 4.0}}`

| `Polygon`
| converter
| `{"polygon" : { "points" : [ { "x" : 1.0 , "y" : 2.0} , { "x" : 3.0 , "y" : 4.0} , { "x" : 4.0 , "y" : 5.0}]}}`

| `Circle`
| converter
| `{"circle" : { "center" : { "x" : 1.0 , "y" : 2.0} , "radius" : 3.0 , "metric" : "NEUTRAL"}}`

| `Point`
| converter
| `{"point" : { "x" : 1.0 , "y" : 2.0}}`

| `GeoJsonPoint`
| converter
| `{"point" : { "type" : "Point" , "coordinates" : [3.0 , 4.0] }}`

| `GeoJsonMultiPoint`
| converter
| `{"geoJsonLineString" : {"type":"MultiPoint", "coordinates": [ [ 0 , 0 ], [ 0 , 1 ], [ 1 , 1 ] ] }}`

| `Sphere`
| converter
| `{"sphere" : { "center" : { "x" : 1.0 , "y" : 2.0} , "radius" : 3.0 , "metric" : "NEUTRAL"}}`

| `GeoJsonPolygon`
| converter
| `{"polygon" : { "type" : "Polygon", "coordinates" : [[ [ 0 , 0 ], [ 3 , 6 ], [ 6 , 1 ], [ 0 , 0  ] ]] }}`

| `GeoJsonMultiPolygon`
| converter
| `{"geoJsonMultiPolygon" : { "type" : "MultiPolygon", "coordinates" : [
     [ [ [ -73.958 , 40.8003 ] , [ -73.9498 , 40.7968 ] ] ],
     [ [ [ -73.973 , 40.7648 ] , [ -73.9588 , 40.8003 ] ] ]
  ] }}`

| `GeoJsonLineString`
| converter
| `{ "geoJsonLineString" : { "type" : "LineString", "coordinates" : [ [ 40 , 5 ], [ 41 , 6 ] ] }}`

| `GeoJsonMultiLineString`
| converter
| `{"geoJsonLineString" : { "type" : "MultiLineString", coordinates: [
     [ [ -73.97162 , 40.78205 ], [ -73.96374 , 40.77715 ] ],
     [ [ -73.97880 , 40.77247 ], [ -73.97036 , 40.76811 ] ]
  ] }}`
|===


[[mapping-configuration]]
== 映射配置

除非明确配置，否则在你创建 `MongoTemplate` 时，默认会创建 `MappingMongoConverter` 的实例。你可以创建你自己的 `MappingMongoConverter` 的实例。这样做可以让你决定在 classpath 中找到你的 domain 类，以便 Spring Data MongoDB 能够提取元数据并构建索引。此外，通过创建自己的实例，你可以注册 Spring converter，以便将特定的类映射到数据库中，或从数据库中提取。

你可以通过使用基于 Java 或基于 XML 的元数据来配置 `MappingMongoConverter` 以及 `com.mongodb.client.MongoClient` 和 `MongoTemplate`。下面的例子显示了配置情况。

====
.Java
[source,java,role="primary"]
----
@Configuration
public class MongoConfig extends AbstractMongoClientConfiguration {

  @Override
  public String getDatabaseName() {
    return "database";
  }

  // the following are optional

  @Override
  public String getMappingBasePackage() { <1>
    return "com.bigbank.domain";
  }

  @Override
  void configureConverters(MongoConverterConfigurationAdapter adapter) { <2>

  	adapter.registerConverter(new org.springframework.data.mongodb.test.PersonReadConverter());
  	adapter.registerConverter(new org.springframework.data.mongodb.test.PersonWriteConverter());
  }

  @Bean
  public LoggingEventListener<MongoMappingEvent> mappingEventsListener() {
    return new LoggingEventListener<MongoMappingEvent>();
  }
}

----

.XML
[source,xml,role="secondary"]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:mongo="http://www.springframework.org/schema/data/mongo"
  xsi:schemaLocation="
    http://www.springframework.org/schema/data/mongo https://www.springframework.org/schema/data/mongo/spring-mongo.xsd
    http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans-3.0.xsd">

  <!-- Default bean name is 'mongo' -->
  <mongo:mongo-client host="localhost" port="27017"/>

  <mongo:db-factory dbname="database" mongo-ref="mongoClient"/>

  <!-- by default look for a Mongo object named 'mongo' - default name used for the converter is 'mappingConverter' -->
  <mongo:mapping-converter base-package="com.bigbank.domain">
    <mongo:custom-converters>
      <mongo:converter ref="readConverter"/>
      <mongo:converter>
        <bean class="org.springframework.data.mongodb.test.PersonWriteConverter"/>
      </mongo:converter>
    </mongo:custom-converters>
  </mongo:mapping-converter>

  <bean id="readConverter" class="org.springframework.data.mongodb.test.PersonReadConverter"/>

  <!-- set the mapping converter to be used by the MongoTemplate -->
  <bean id="mongoTemplate" class="org.springframework.data.mongodb.core.MongoTemplate">
    <constructor-arg name="mongoDbFactory" ref="mongoDbFactory"/>
    <constructor-arg name="mongoConverter" ref="mappingConverter"/>
  </bean>

  <bean class="org.springframework.data.mongodb.core.mapping.event.LoggingEventListener"/>

</beans>
----
<1> 映射基础包定义了用于扫描实体的根路径，用于预先初始化 `MappingContext`。默认情况下，配置类包被使用。
<2> 为特定的 domain 类型配置额外的自定义 converter，用你的自定义实现替换这些类型的默认映射程序。
====

`AbstractMongoClientConfiguration` 要求你实现定义 `com.mongodb.client.MongoClient` 的方法，并提供一个数据库名称。`AbstractMongoClientConfiguration` 也有一个名为 `getMappingBasePackage(…)` 的方法，你可以覆盖该方法，以告诉 converter 在哪里扫描带有 `@Document` 注解的类。

你可以通过覆写 `customConversionsConfiguration` 方法向 `converter` 添加额外的 `converter`。MongoDB 的本地 JSR-310 支持可以通过 `MongoConverterConfigurationAdapter.useNativeDriverJavaTimeCodecs()` 启用。前面的例子中还显示了一个 `LoggingEventListener`，它记录了发布到 Spring 的 `ApplicationContextEvent` 基础架构上的 `MongoMappingEvent` 实例。

NOTE: `AbstractMongoClientConfiguration` 创建了一个 `MongoTemplate` 实例，并以 `mongoTemplate` 的名字在容器中注册了它。

`base-package` 属性告诉它在哪里扫描带有 `@org.springframework.data.mongodb.core.mapping.Document` 注解的类。

[[mapping-usage]]
== 基于元数据的映射

为了充分利用 Spring Data MongoDB 支持中的对象映射功能，你应该用 `@Document` 注解来注解你的映射对象。尽管映射框架没有必要拥有这个注解（即使没有任何注解，你的 POJO 也能正确映射），但它能让 classpath 扫描器找到并预处理你的领域对象，以提取必要的元数据。
如果你不使用这个注解，你的应用程序在第一次存储 domain 对象时就会受到轻微的性能影响，因为映射框架需要建立其内部元数据模型，以便它知道你的 domain 对象的属性以及如何持久化它们。下面的例子显示了一个 domain 对象。

.domain 对象实例
====
[source,java]
----
package com.mycompany.domain;

@Document
public class Person {

  @Id
  private ObjectId id;

  @Indexed
  private Integer ssn;

  private String firstName;

  @Indexed
  private String lastName;
}
----
====

IMPORTANT: `@Id` 注解告诉映射器你想使用哪个属性作为 MongoDB `_id` 属性，而 `@Indexed` 注解告诉映射框架在你文档的那个属性上调用 `createIndex(…)` ，使搜索更快。自动索引创建只针对用 `@Document` 注解的类型。

WARNING: 自动索引创建默认是禁用的（**disabled**），需要通过配置启用（见 <<mapping.index-creation>>）。

[[mapping.index-creation]]
=== 创建索引

Spring Data MongoDB 可以为用 `@Document` 注解的实体类型自动创建索引。自 3.0 版本以来，必须明确启用索引创建，以防止对集合生命周期和性能产生不希望看到的影响。在应用程序启动时以及在应用程序运行时首次访问实体类型时，会自动为初始实体集创建索引。

我们通常推荐显式索引的创建，以实现基于应用的索引控制，因为 Spring Data 不能自动为应用运行时重新创建的集合创建索引。

如果你想利用 `@Indexed` 注解，如 `@GeoSpatialIndexed`、`@TextIndexed`、 `@CompoundIndex` 和 `@WildcardIndexed`，`IndexResolver` 为编程式索引定义的创建提供了一个抽象。你可以使用带有 `IndexOperations` 的索引定义来创建索引。
创建索引的一个好的时间点是在应用程序启动时，特别是在 application context 被刷新后，通过观察 `ContextRefreshedEvent` 触发的。这个事件保证了 context 是完全初始化的。请注意，此时其他组件，尤其是 Bean Factory 可能会访问 MongoDB 数据库。

[WARNING]
====
除非用 `@WildcardIndexed` 注解，否则类似 `Map` 的属性会被 `IndexResolver` 跳过，因为 map key 必须是索引定义的一部分。因为 map 的目的是使用动态的 key 和 value，所以 key 不能从静态的映射元数据中解决。
====

.Programmatic Index Creation for a single Domain Type
====
[source,java]
----
class MyListener {

  @EventListener(ContextRefreshedEvent.class)
  public void initIndicesAfterStartup() {

    MappingContext<? extends MongoPersistentEntity<?>, MongoPersistentProperty> mappingContext = mongoTemplate
                .getConverter().getMappingContext();

    IndexResolver resolver = new MongoPersistentEntityIndexResolver(mappingContext);

    IndexOperations indexOps = mongoTemplate.indexOps(DomainType.class);
    resolver.resolveIndexFor(DomainType.class).forEach(indexOps::ensureIndex);
  }
}
----
====

.Programmatic Index Creation for all Initial Entities
====
[source,java]
----
class MyListener{

  @EventListener(ContextRefreshedEvent.class)
  public void initIndicesAfterStartup() {

    MappingContext<? extends MongoPersistentEntity<?>, MongoPersistentProperty> mappingContext = mongoTemplate
        .getConverter().getMappingContext();

    // consider only entities that are annotated with @Document
    mappingContext.getPersistentEntities()
                            .stream()
                            .filter(it -> it.isAnnotationPresent(Document.class))
                            .forEach(it -> {

    IndexOperations indexOps = mongoTemplate.indexOps(it.getType());
    resolver.resolveIndexFor(it.getType()).forEach(indexOps::ensureIndex);
    });
  }
}
----
====

另外，如果你想在任何组件能够从你的应用程序访问你的数据库之前确保索引和集合的存在，为 `MongoTemplate` 声明一个 `@Bean` 方法，并在返回 `MongoTemplate` 对象之前包含上面的代码。

[NOTE]
====
要打开自动索引创建功能，请在你的配置中覆写 `autoIndexCreation()`。
[source,java]
----
@Configuration
public class Config extends AbstractMongoClientConfiguration {

  @Override
  public boolean autoIndexCreation() {
    return true;
  }

// ...
}
----
====

IMPORTANT: 从 3.0 版本开始，自动索引创建默认为关闭。

[[mapping-usage-annotations]]
=== 映射注解概述

`MappingMongoConverter` 可以使用元数据来驱动对象到文档的映射。以下注解是可用的。

* `@Id`: 应用在字段，以标记用于 ID 的字段。
* `@MongoId`: 在字段级应用，以标记用于 ID 的字段。接受一个可选的 `FieldType` 来自定义 ID 转换。
* `@Document`: 应用在类的层面上，表示这个类是映射到数据库的候选对象。你可以指定存储数据的集合的名称。
* `@DBRef`: 应用在字段上，表明它将使用 `com.mongodb.DBRef` 来存储。
* `@DocumentReference`: 应用在字段上，表示它将作为一个指向另一个文档的指针被存储。这可以是一个单一的值（默认为 id），也可以是一个通过 converter 提供的 `Document`。
* `@Indexed`: 应用于字段级，描述如何对字段进行索引。
* `@CompoundIndex` (可重复): 在类型层面上应用于声明复合索引。
* `@GeoSpatialIndexed`: 应用于 domain 层面，描述如何对 domain 进行地理索引（geoindex ）。
* `@TextIndexed`: 在字段一级应用，以标记要包括在文本索引中的字段。
* `@HashIndexed`: 在字段级应用于哈希索引中的使用，以在分片集群中对数据进行分割。
* `@Language`: 应用于字段级，用于设置文本索引的语言覆盖属性。
* `@Transient`: 默认情况下，所有字段都被映射到文档中。这个注解排除了它所应用的字段被存储在数据库中。瞬时（Transient）属性不能在持久化构造函数中使用，因为 converter 不能为构造函数参数具体化一个值。
* `@PersistenceConstructor`: 标记一个给定的构造函数 — 即使是一个受包保护的构造函数 — 在从数据库实例化对象时使用。构造函数参数通过名称映射到检索的文档中的关键值。
* `@Value`: 这个注解是 Spring 框架的一部分。在映射框架内，它可以应用于构造器参数。这让你可以使用 Spring 表达式语言语句来转换在数据库中检索到的 key 值，然后再用于构造 domain 对象。为了引用一个给定文档的属性，我们必须使用这样的表达式。`@Value("#root.myProperty")` 其中 root 指的是给定文档的 root。
* `@Field`: 应用于字段级别，它允许描述字段的名称和类型，因为它将在 MongoDB BSON 文档中表示出来，因此允许名称和类型与类的字段名以及属性类型不同。
* `@Version`: 应用于字段级，用于乐观锁，并在保存操作中检查是否有修改。初始值为 `0`（原始类型为 `1`），在每次更新时都会自动增加。

映射元数据基础设施定义在一个独立的 spring-data-commons 项目中，该项目与技术无关。特定的子类在 MongoDB 支持中使用，以支持基于注解的元数据。如果有需求的话，其他的策略也是可以实现的。

下面是一个更复杂的映射的例子。

[source,java]
----
@Document
@CompoundIndex(name = "age_idx", def = "{'lastName': 1, 'age': -1}")
public class Person<T extends Address> {

  @Id
  private String id;

  @Indexed(unique = true)
  private Integer ssn;

  @Field("fName")
  private String firstName;

  @Indexed
  private String lastName;

  private Integer age;

  @Transient
  private Integer accountTotal;

  @DBRef
  private List<Account> accounts;

  private T address;

  public Person(Integer ssn) {
    this.ssn = ssn;
  }

  @PersistenceConstructor
  public Person(Integer ssn, String firstName, String lastName, Integer age, T address) {
    this.ssn = ssn;
    this.firstName = firstName;
    this.lastName = lastName;
    this.age = age;
    this.address = address;
  }

  public String getId() {
    return id;
  }

  // no setter for Id.  (getter is only exposed for some unit testing)

  public Integer getSsn() {
    return ssn;
  }

// other getters/setters omitted
}
----

[TIP]
====
`@Field(targetType=...)` 在映射基础设施推断出的本地 MongoDB 类型与预期类型不一致时可以派上用场。比如 `BigDecimal`，它被表示为 `String` 而不是 `Decimal128`，只是因为 MongoDB 服务器的早期版本没有对它的支持。
[source,java]
----
public class Balance {

  @Field(targetType = DECIMAL128)
  private BigDecimal value;

  // ...
}
----

你甚至可以考虑你自己的、自定义的注解。

[source,java]
----
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
@Field(targetType = FieldType.DECIMAL128)
public @interface Decimal128 { }

// ...

public class Balance {

  @Decimal128
  private BigDecimal value;

  // ...
}
----
====

[[mapping-custom-object-construction]]
=== 自定义 Object 构造

映射子系统允许通过用 `@PersistenceConstructor` 注解来定制对象的构造。用于构造器参数的值以下列方式解析。

* 如果一个参数被 `@Value` 注解，给定的表达式被评估，其结果被用作参数值。
* 如果 Java 类有一个属性，其名称与输入文件的给定字段相匹配，那么它的属性信息将被用来选择适当的构造函数参数来传递输入字段的值。这只有在参数名称信息存在于 java `.class` 文件中时才起作用，这可以通过编译带有调试信息的源代码或使用 Java 8 中 javac 新的 `-parameters` 命令行开关来实现。
* 否则，将抛出一个 `MappingException`，表明所给的构造函数参数不能被绑定。

[source,java]
----
class OrderItem {

  private @Id String id;
  private int quantity;
  private double unitPrice;

  OrderItem(String id, @Value("#root.qty ?: 0") int quantity, double unitPrice) {
    this.id = id;
    this.quantity = quantity;
    this.unitPrice = unitPrice;
  }

  // getters/setters ommitted
}

Document input = new Document("id", "4711");
input.put("unitPrice", 2.5);
input.put("qty",5);
OrderItem item = converter.read(OrderItem.class, input);
----

NOTE: 如果给定的属性路径无法解析，quantity 参数的 `@Value` 注解中的 SpEL 表达式就会回落到值 `0`。

在 https://github.com/spring-projects/spring-data-mongodb/blob/master/spring-data-mongodb/src/test/java/org/springframework/data/mongodb/core/convert/MappingMongoConverterUnitTests.java[MappingMongoConverterUnitTests] 测试套件中可以找到使用 `@PersistenceConstructor` 注解的其他例子。

[[mapping-usage-indexes.compound-index]]
=== 复合索引

复合索引也被支持。它们是在类的层面上定义的，而不是在单个属性上。

NOTE: 复合索引对于提高涉及多个字段 criteria 的查询性能非常重要

下面是一个例子，它创建了一个升序的 `lastName` 和降序的 `age` 的复合索引。

.复合索引使用实例
====
[source,java]
----
package com.mycompany.domain;

@Document
@CompoundIndex(name = "age_idx", def = "{'lastName': 1, 'age': -1}")
public class Person {

  @Id
  private ObjectId id;
  private Integer age;
  private String firstName;
  private String lastName;

}
----
====

[TIP]
====
`@CompoundIndex` 是可重复的，使用 `@CompoundIndexes` 作为其容器。

[source,java]
----
@Document
@CompoundIndex(name = "cmp-idx-one", def = "{'firstname': 1, 'lastname': -1}")
@CompoundIndex(name = "cmp-idx-two", def = "{'address.city': -1, 'address.street': 1}")
public class Person {

  String firstname;
  String lastname;

  Address address;

  // ...
}
----
====

[[mapping-usage-indexes.hashed-index]]
=== 哈希索引

Hash索引允许在 sharded cluster 内进行基于hash的分片。使用hash字段值来分片的结果是一个更随机的分布。详情请参考 https://docs.mongodb.com/manual/core/index-hashed/[MongoDB Documentation]。

下面是一个为 `_id` 创建 Hash 索引的例子:

.Hash 索引使用示例
====
[source,java]
----
@Document
public class DomainType {

  @HashIndexed @Id String id;

  // ...
}
----
====

Hash 索引可以像下面所示的那样在其他索引定义的旁边创建，在这种情况下，两个索引都被创建。

.Hash 索引与简单索引一起使用的例子
====
[source,java]
----
@Document
public class DomainType {

  @Indexed
  @HashIndexed
  String value;

  // ...
}
----
====

如果上面的例子过于冗长，复合注解允许减少需要在一个属性上声明的注解的数量。

.复合hash索引使用示例
====
[source,java]
----
@Document
public class DomainType {

  @IndexAndHash(name = "idx...")                            <1>
  String value;

  // ...
}

@Indexed
@HashIndexed
@Retention(RetentionPolicy.RUNTIME)
public @interface IndexAndHash {

  @AliasFor(annotation = Indexed.class, attribute = "name") <1>
  String name() default "";
}
----
<1> 有可能为元注解的某些属性注册一个别名。
====

[NOTE]
====
尽管通过注解创建索引在很多情况下都很方便，但考虑通过 `IndexOperations` 手动设置索引来接管更多的控制权。

[source,java]
----
mongoOperations.indexOpsFor(Jedi.class)
  .ensureIndex(HashedIndex.hashed("useTheForce"));
----
====

[[mapping-usage-indexes.wildcard-index]]
=== 通配符索引

通配符索引（`WildcardIndex`）是一个索引，可以用来包括所有字段或基于给定（通配符）模式（pattern）的特定字段。详情请参考 https://docs.mongodb.com/manual/core/index-wildcard/[MongoDB Documentation]。

该索引可以通过 `IndexOperations` 使用 `WildcardIndex` 进行编程设置。

.Programmatic WildcardIndex setup
====
[source,java]
----
mongoOperations
    .indexOps(User.class)
    .ensureIndex(new WildcardIndex("userMetadata"));
----
[source,javascript]
----
db.user.createIndex({ "userMetadata.$**" : 1 }, {})
----
====

`@WildcardIndex` 注解允许一个声明性的索引设置，可以与文档类型或属性一起使用。

如果放在一个 root 级 domain 实体的类上（一个用 `@Document` 注释的类），索引解析器将为它创建一个通配符索引。

.Wildcard index on domain type
====
[source,java]
----
@Document
@WildcardIndexed
public class Product {
	// …
}
----
[source,javascript]
----
db.product.createIndex({ "$**" : 1 },{})
----
====

通配符投影（`wildcardProjection`）可以用来指定索引中的包含/排除。

.Wildcard index with `wildcardProjection`
====
[source,java]
----
@Document
@WildcardIndexed(wildcardProjection = "{ 'userMetadata.age' : 0 }")
public class User {
    private @Id String id;
    private UserMetadata userMetadata;
}
----
[source,javascript]
----
db.user.createIndex(
  { "$**" : 1 },
  { "wildcardProjection" :
    { "userMetadata.age" : 0 }
  }
)
----
====

通配符索引也可以通过直接向字段添加注解来表达。请注意，`wildcardProjection` 在嵌套路径上是不允许的，比如属性。在索引创建过程中，用 `@WildcardIndexed` 注解的类上的投影被省略。

.Wildcard index on property
====
[source,java]
----
@Document
public class User {
    private @Id String id;

    @WildcardIndexed
    private UserMetadata userMetadata;
}
----
[source,javascript]
----
db.user.createIndex({ "userMetadata.$**" : 1 }, {})
----
====

[[mapping-usage-indexes.text-index]]
=== 文本索引

NOTE: 对于 MongoDB v.2.4 来说，文本索引功能默认是禁用的。

创建一个文本索引可以将几个字段累积成一个可搜索的全文索引。每个集合只能有一个文本索引，所以所有标有 `@TextIndexed` 的字段都被合并到这个索引中。属性可以被加权以影响排名结果的文档分数。文本索引的默认语言是英语。要改变默认语言，将 `language` 属性设置为你想要的任何语言（例如，`@Document(language="spanish")`）。
使用一个叫做 `language` 或 `@Language` 的属性可以让你在每个文档的基础上定义一个语言覆盖。下面的例子显示了如何创建一个文本索引并将语言设置为西班牙语（Spanish）。

.文本索引使用实例
====
[source,java]
----
@Document(language = "spanish")
class SomeEntity {

    @TextIndexed String foo;

    @Language String lang;

    Nested nested;
}

class Nested {

    @TextIndexed(weight=5) String bar;
    String roo;
}
----
====

include::document-references.adoc[]

[[mapping-usage-events]]
=== 映射框架事件

事件在映射过程的整个生命周期中被触发。这将在 <<mongodb.mapping-usage.events,Lifecycle Events>> 部分进行描述。
在你的 Spring ApplicationContext 中声明这些 Bean 会导致它们在事件被调度时被调用。

include::unwrapping-entities.adoc[]

include::mongo-custom-conversions.adoc[]
include::mongo-property-converters.adoc[]
