[[mongo.custom-converters]]
== 自定义转换 - 覆盖默认映射

影响映射结果的最简单的方法是通过 `@Field` 注解指定所需的原生 MongoDB 目标类型。这允许在 domain 模型中使用非 MongoDB 类型，如 `BigDecimal`，同时以本地 `org.bson.types.Decimal128` 格式持久化数值。

.明确的目标类型映射
====
[source,java]
----
public class Payment {

  @Id String id; <1>

  @Field(targetType = FieldType.DECIMAL128) <2>
  BigDecimal value;

  Date date; <3>

}
----
[source,java]
----
{
  "_id"   : ObjectId("5ca4a34fa264a01503b36af8"), <1>
  "value" : NumberDecimal(2.099), <2>
  "date"   : ISODate("2019-04-03T12:11:01.870Z") <3>
}
----
<1> 代表有效 `ObjectId` 的字符串 `id` 值会自动转换。详见  <<mongo-template.id-handling>>。
<2> 所需的目标类型被明确定义为 `Decimal128`，翻译成 `NumberDecimal`。否则 `BigDecimal` 的值就会被截成一个 `String`。
<3> `Date` 值由MongoDB驱动本身处理，并存储为 ISODate。
====

上面的片段对于提供简单的类型提示很方便。为了获得对映射过程更精细的控制，你可以用 `MongoConverter` 实现注册 Spring converter，例如 `MappingMongoConverter`。

`MappingMongoConverter` 在尝试映射对象本身之前，会检查是否有 Spring converter 可以处理特定的类。要 "劫持" `MappingMongoConverter` 的正常映射策略，也许是为了提高性能或其他自定义映射需求，
你首先需要创建一个Spring `Converter` 接口的实现，然后将其与 `MappingConverter` 注册。

NOTE: 关于Spring类型转换服务的更多信息，请看 https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#validation[这里的参考文档]。

[[mongo.custom-converters.writer]]
=== 通过使用注册的 Spring Converter 来节约成本

下面的例子显示了一个 `Converter` 的实现，它将 `Person` 对象转换为 `org.bson.Document`。

[source,java]
----
import org.springframework.core.convert.converter.Converter;

import org.bson.Document;

public class PersonWriteConverter implements Converter<Person, Document> {

  public Document convert(Person source) {
    Document document = new Document();
    document.put("_id", source.getId());
    document.put("name", source.getFirstName());
    document.put("age", source.getAge());
    return document;
  }
}
----

[[mongo.custom-converters.reader]]
=== 通过使用 Spring Converter 进行读取

下面的例子显示了一个 `Converter` 的实现，它可以从 `Document` 转换为 `Person` 对象。

[source,java]
----
public class PersonReadConverter implements Converter<Document, Person> {

  public Person convert(Document source) {
    Person p = new Person((ObjectId) source.get("_id"), (String) source.get("name"));
    p.setAge((Integer) source.get("age"));
    return p;
  }
}
----

[[mongo.custom-converters.xml]]
=== 用 `MongoConverter` 注册 Spring Converter

[source,java]
----
class MyMongoConfiguration extends AbstractMongoClientConfiguration {

	@Override
	public String getDatabaseName() {
		return "database";
	}

	@Override
	protected void configureConverters(MongoConverterConfigurationAdapter adapter) {
		adapter.registerConverter(new com.example.PersonReadConverter());
		adapter.registerConverter(new com.example.PersonWriteConverter());
	}
}
----

include::../{spring-data-commons-docs}/custom-conversions.adoc[leveloffset=+3]
