[[mongodb.repositories.queries.aggregation]]
=== 聚合 Repository 方法

repository 层提供了通过注解的 repository 查询方法与 <<mongo.aggregation, 聚合框架>>  交互的手段。与 <<mongodb.repositories.queries.json-based, 基于 JSON 的查询>> 类似，
你可以使用 `org.springframework.data.mongodb.repository.Aggregation` 注解定义一个管道。该定义可以包含简单的占位符，如 `?0`，以及 https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#expressions[SpEL 表达式]  `?#{ … }`。

.聚合 Repository 方法
====
[source,java]
----
public interface PersonRepository extends CrudReppsitory<Person, String> {

  @Aggregation("{ $group: { _id : $lastname, names : { $addToSet : $firstname } } }")
  List<PersonAggregate> groupByLastnameAndFirstnames();                            <1>

  @Aggregation("{ $group: { _id : $lastname, names : { $addToSet : $firstname } } }")
  List<PersonAggregate> groupByLastnameAndFirstnames(Sort sort);                   <2>

  @Aggregation("{ $group: { _id : $lastname, names : { $addToSet : ?0 } } }")
  List<PersonAggregate> groupByLastnameAnd(String property);                       <3>

  @Aggregation("{ $group: { _id : $lastname, names : { $addToSet : ?0 } } }")
  Slice<PersonAggregate> groupByLastnameAnd(String property, Pageable page);       <4>

  @Aggregation("{ $group: { _id : $lastname, names : { $addToSet : $firstname } } }")
  Stream<PersonAggregate> groupByLastnameAndFirstnamesAsStream();                  <5>

  @Aggregation("{ $group : { _id : null, total : { $sum : $age } } }")
  SumValue sumAgeUsingValueWrapper();                                              <6>

  @Aggregation("{ $group : { _id : null, total : { $sum : $age } } }")
  Long sumAge();                                                                   <7>

  @Aggregation("{ $group : { _id : null, total : { $sum : $age } } }")
  AggregationResults<SumValue> sumAgeRaw();                                        <8>

  @Aggregation("{ '$project': { '_id' : '$lastname' } }")
  List<String> findAllLastnames();                                                 <9>
}
----
[source,java]
----
public class PersonAggregate {

  private @Id String lastname;                                                     <2>
  private List<String> names;

  public PersonAggregate(String lastname, List<String> names) {
     // ...
  }

  // Getter / Setter omitted
}

public class SumValue {

  private final Long total;                                                        <6> <8>

  public SumValue(Long total) {
    // ...
  }

  // Getter omitted
}
----
<1> 聚合管道，在 `Person` 集合中通过 `lastname` 对名字进行分组，将这些名字作为 `PersonAggregate` 返回。
<2> 如果存在 `Sort` 参数，`$sort` 被附加在已声明的管道阶段之后，这样它只影响到通过所有其他聚合阶段后的最终结果的顺序。因此，`Sort` 属性被映射到返回类型为 `PersonAggregate` 的方法上，该方法将 `Sort.by("lastname")` 变成 `{ $sort : { '_id', 1 } }`，因为 `PersonAggregate.lastname` 是用 `@Id` 来注解的。
<3> 用给定的 property 值替换动态聚合管道的 `?0`。
<4> `$skip`、`$limit` 和 `$sort` 可以通过一个 `Pageable` 参数来传递。和 <2> 中一样，操作符被附加到管道定义中。接受 `Pageable` 的方法可以返回 `Slice` 以方便分页。
<5> 聚合方法可以返回 `Stream`，直接从底层游标中消费结果。确保在消费完流之后关闭它，通过调用 `close()` 或通过 `try-with-resources` 释放服务器端的游标。
<6> 将返回单个 `Document` 的聚合结果映射到所需的 `SumValue` 目标类型的一个实例。
<7> 聚合产生的单个文档只持有一个累积结果，比如 `$sum` 可以直接从结果 `Document` 中提取。为了获得更多的控制，你可以考虑将 `AggregationResult` 作为方法的返回类型，如 <7> 所示。
<8> 获取映射到通用目标包装类型 `SumValue` 或 `org.bson.Document` 的原始 `AggregationResults`。
<9> 像 <6> 中一样，一个单一的值可以直接从多个结果 `Document` 中获得。
====

在某些情况下，聚合可能需要额外的选项，比如最大运行时间、额外的日志注释，或者允许暂时将数据写入磁盘。使用 `@Meta` 注解，通过 `maxExecutionTimeMs`、`comment` 或 `allowDiskUse` 来设置这些选项。

[source,java]
----
interface PersonRepository extends CrudReppsitory<Person, String> {

  @Meta(allowDiskUse = true)
  @Aggregation("{ $group: { _id : $lastname, names : { $addToSet : $firstname } } }")
  List<PersonAggregate> groupByLastnameAndFirstnames();
}
----

或者使用 `@Meta` 来创建你自己的注解，如下面的例子所示。

[source,java]
----
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.METHOD })
@Meta(allowDiskUse = true)
@interface AllowDiskUse { }

interface PersonRepository extends CrudReppsitory<Person, String> {

  @AllowDiskUse
  @Aggregation("{ $group: { _id : $lastname, names : { $addToSet : $firstname } } }")
  List<PersonAggregate> groupByLastnameAndFirstnames();
}
----

TIP: 你也可以将 `@Aggregation` 用于 <<mongo.reactive.repositories, Reactive Repositories>>。

[NOTE]
====
简单类型的单一结果检查返回的 `Document`，并检查以下内容。

. 文档中只有一个条目，请退回。
. 两个条目，一个是 `_id` 值。返回另一个。
. 返回为第一个可分配给返回类型的值。
. 如果上述情况都不适用，则抛出一个异常。
====

WARNING: 使用 `@Aggregation` 的 repository 方法不支持 `Page` 的返回类型。然而，你可以使用 `Pageable` 参数，将 `$skip`、`$limit` 和 `$sort` 加入管道，让方法返回 `Slice`。
