[[mongo.repositories]]
= MongoDB Repositories

[[mongo-repo-intro]]
本章指出了 MongoDB 的 repository 支持的特殊性。本章建立在 与 Spring Data Repository 一起工作 中解释的核心 <<repositories>> 支持的基础上。你应该对那里解释的基本概念有一个正确的理解。

[[mongo-repo-usage]]
== 用法

为了访问存储在 MongoDB 中的 domain 实体，你可以使用我们复杂的 repository 支持，这大大简化了实现。要做到这一点，为你的 repository 创建一个接口，如下例所示。

.Sample Person entity
====
[source,java]
----
public class Person {

  @Id
  private String id;
  private String firstname;
  private String lastname;
  private Address address;

  // … getters and setters omitted
}
----
====

注意在前面的例子中显示的 domain 类型有一个名为 `id` 的 `String` 类型的属性。`MongoTemplate` 中使用的默认序列化机制（它支持 repository）将名为 `id` 的属性视为文档 ID。
目前，我们支持 `String`、`ObjectId` 和 `BigInteger` 作为 `ID` 类型。请参阅 <<mongo-template.id-handling, ID 映射>>  以了解更多关于在映射层中如何处理 `id` 字段的信息。

现在我们有了一个 domain 对象，我们可以定义一个使用它的接口，如下所示。

.持久保存 Person 实体的基本 repository 接口
====
[source]
----
public interface PersonRepository extends PagingAndSortingRepository<Person, String> {

  // additional custom query methods go here
}
----
====

现在，这个接口只起到提供类型信息的作用，但我们可以在以后为它添加额外的方法。

要开始使用repository，请使用 `@EnableMongoRepositories` 注解。该注解带有与命名空间元素相同的属性。如果没有配置基础包（base package），基础设施会扫描被注解的配置类的包。下面的例子展示了如何配置你的应用程序以使用MongoDB repository。

====
.Java
[source,java,role="primary"]
----
@Configuration
@EnableMongoRepositories("com.acme.*.repositories")
class ApplicationConfig extends AbstractMongoClientConfiguration {

  @Override
  protected String getDatabaseName() {
    return "e-store";
  }

  @Override
  protected String getMappingBasePackage() {
    return "com.acme.*.repositories";
  }
}
----

.XML
[source,xml,role="secondary"]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:mongo="http://www.springframework.org/schema/data/mongo"
  xsi:schemaLocation="http://www.springframework.org/schema/beans
    https://www.springframework.org/schema/beans/spring-beans-3.0.xsd
    http://www.springframework.org/schema/data/mongo
    https://www.springframework.org/schema/data/mongo/spring-mongo-1.0.xsd">

  <mongo:mongo-client id="mongoClient" />

  <bean id="mongoTemplate" class="org.springframework.data.mongodb.core.MongoTemplate">
    <constructor-arg ref="mongoClient" />
    <constructor-arg value="databaseName" />
  </bean>

  <mongo:repositories base-package="com.acme.*.repositories" />

</beans>
----
====

这个命名空间元素会使基础包扫描扩展 `MongoRepository` 的接口，并为找到的每个接口创建 Spring Bean。默认情况下，存储库会得到一 个 `MongoTemplate` Spring Bean wired，它被称为 `mongoTemplate`，所以你只需要在偏离这一惯例时明确配置 `mongo-template-ref`。

因为我们的 domain repository 继承了 `PagingAndSortingRepository`，它为你提供了 CRUD 操作以及分页和排序访问实体的方法。使用 repository 实例只是将其依赖注入到客户端的问题。因此，在页面大小为 `10` 的情况下访问第二页的 `Person` 对象将类似于以下代码。

.对 `Person` 实体的分页访问
====
[source,java]
----
@ExtendWith(SpringExtension.class)
@ContextConfiguration
class PersonRepositoryTests {

    @Autowired PersonRepository repository;

    @Test
    void readsFirstPageCorrectly() {

      Page<Person> persons = repository.findAll(PageRequest.of(0, 10));
      assertThat(persons.isFirstPage()).isTrue();
    }
}
----
====

前面的例子用Spring的单元测试支持创建了一个 application context，它将基于注解的依赖注入到测试案例中。在测试方法中，我们使用 repository 来查询数据存储。我们交给 repository 一个 `PageRequest` 实例，请求页面大小为 `10` 的 `Person` 对象的第一页。

[[mongodb.repositories.queries]]
== Query 方法

你通常在 repository 上触发的大多数数据访问操作都会导致对 MongoDB 数据库的查询被执行。定义这样的查询只需要在 repository 接口上声明一个方法，就像下面的例子所示。

.具有 Query 方法的 PersonRepository
====
[source,java]
----
public interface PersonRepository extends PagingAndSortingRepository<Person, String> {

    List<Person> findByLastname(String lastname);                      <1>

    Page<Person> findByFirstname(String firstname, Pageable pageable); <2>

    Person findByShippingAddresses(Address address);                   <3>

    Person findFirstByLastname(String lastname)                        <4>

    Stream<Person> findAllBy();                                        <5>
}
----

<1> `findByLastname` 方法显示了一个对所有具有给定姓氏（last name）的人的查询。该查询是通过解析方法名称中可以与 `And` 和 `Or` 相连接的约束条件而得到的。
因此，方法名称的结果是一个查询表达式 `{"lastname" : lastname}`
<2> 将分页应用到查询中。你可以为你的方法签名配备一个 `Pageable` 参数，并让方法返回一个 `Page` 实例，Spring Data 会自动对查询进行相应的分页。
<3> 显示你可以基于非原始类型的属性进行查询。如果发现一个以上的匹配，会抛出 `IncorrectResultSizeDataAccessException`。
<4> 使用 `First` 关键字，将查询限制在第一个结果上。与 <3> 不同的是，如果找到一个以上的匹配，这个方法不会抛出一个异常。
<5> 使用一个 Java 8 Stream，在迭代流的同时读取和转换单个元素。
====

NOTE: 我们不支持引用在 domain 类中被映射为 `DBRef` 的参数。

下表显示了查询方法所支持的关键字:

[cols="1,2,3",options="header"]
.查询方法支持的关键字
|===
| Keyword
| Sample
| Logical result

| `After`
| `findByBirthdateAfter(Date date)`
| `{"birthdate" : {"$gt" : date}}`

| `GreaterThan`
| `findByAgeGreaterThan(int age)`
| `{"age" : {"$gt" : age}}`

| `GreaterThanEqual`
| `findByAgeGreaterThanEqual(int age)`
| `{"age" : {"$gte" : age}}`

| `Before`
| `findByBirthdateBefore(Date date)`
| `{"birthdate" : {"$lt" : date}}`

| `LessThan`
| `findByAgeLessThan(int age)`
| `{"age" : {"$lt" : age}}`

| `LessThanEqual`
| `findByAgeLessThanEqual(int age)`
| `{"age" : {"$lte" : age}}`

| `Between`
| `findByAgeBetween(int from, int to)` +
`findByAgeBetween(Range<Integer> range)`
| `{"age" : {"$gt" : from, "$lt" : to}}` +
lower / upper bounds (`$gt` / `$gte` & `$lt` / `$lte`) according to `Range`

| `In`
| `findByAgeIn(Collection ages)`
| `{"age" : {"$in" : [ages...]}}`

| `NotIn`
| `findByAgeNotIn(Collection ages)`
| `{"age" : {"$nin" : [ages...]}}`

| `IsNotNull`, `NotNull`
| `findByFirstnameNotNull()`
| `{"firstname" : {"$ne" : null}}`

| `IsNull`, `Null`
| `findByFirstnameNull()`
| `{"firstname" : null}`

| `Like`, `StartingWith`, `EndingWith`
| `findByFirstnameLike(String name)`
| `{"firstname" : name} (name as regex)`

| `NotLike`, `IsNotLike`
| `findByFirstnameNotLike(String name)`
| `{"firstname" : { "$not" : name }} (name as regex)`

| `Containing` on String
| `findByFirstnameContaining(String name)`
| `{"firstname" : name} (name as regex)`

| `NotContaining` on String
| `findByFirstnameNotContaining(String name)`
| `{"firstname" : { "$not" : name}} (name as regex)`

| `Containing` on Collection
| `findByAddressesContaining(Address address)`
| `{"addresses" : { "$in" : address}}`

| `NotContaining` on Collection
| `findByAddressesNotContaining(Address address)`
| `{"addresses" : { "$not" : { "$in" : address}}}`

| `Regex`
| `findByFirstnameRegex(String firstname)`
| `{"firstname" : {"$regex" : firstname }}`

| `(No keyword)`
| `findByFirstname(String name)`
| `{"firstname" : name}`

| `Not`
| `findByFirstnameNot(String name)`
| `{"firstname" : {"$ne" : name}}`

| `Near`
| `findByLocationNear(Point point)`
| `{"location" : {"$near" : [x,y]}}`

| `Near`
| `findByLocationNear(Point point, Distance max)`
| `{"location" : {"$near" : [x,y], "$maxDistance" : max}}`

| `Near`
| `findByLocationNear(Point point, Distance min, Distance max)`
| `{"location" : {"$near" : [x,y], "$minDistance" : min, "$maxDistance" : max}}`

| `Within`
| `findByLocationWithin(Circle circle)`
| `{"location" : {"$geoWithin" : {"$center" : [ [x, y], distance]}}}`

| `Within`
| `findByLocationWithin(Box box)`
| `{"location" : {"$geoWithin" : {"$box" : [ [x1, y1], x2, y2]}}}`

| `IsTrue`, `True`
| `findByActiveIsTrue()`
| `{"active" : true}`

| `IsFalse`,  `False`
| `findByActiveIsFalse()`
| `{"active" : false}`

| `Exists`
| `findByLocationExists(boolean exists)`
| `{"location" : {"$exists" : exists }}`

| `IgnoreCase`
| `findByUsernameIgnoreCase(String username)`
| `{"username" : {"$regex" : "^username$", "$options" : "i" }}`
|===

NOTE: 如果属性标准（property criterion）比较的是一个文档，那么字段的顺序和在文档中的完全平等（equality）就很重要。

[[mongodb.repositories.queries.update]]
=== Repository Update 方法

你也可以使用前述表格中的关键字来创建查询，以识别匹配的文档，从而对其运行更新。实际的更新操作是由方法本身的 `@Update` 注解来定义的，如下表所示。注意，派生查询的命名模式以 `find` 开头。使用 `update`（如 `updateAllByLastname(…)`）只允许与 `@Query` 相结合。

更新适用于所有匹配的文档，不可能通过传入一个 `Page` 或使用任何 <<repositories.limit-query-result,限制性关键字>> 来限制范围。返回类型可以是 `void`，也可以是数字类型，比如 `long`，用来保存修改的文档数量。

.Update 方法
====
[source,java]
----
public interface PersonRepository extends CrudRepository<Person, String> {

  @Update("{ '$inc' : { 'visits' : 1 } }")
  long findAndIncrementVisitsByLastname(String lastname); <1>

  @Update("{ '$inc' : { 'visits' : ?1 } }")
  void findAndIncrementVisitsByLastname(String lastname, int increment); <2>

  @Update("{ '$inc' : { 'visits' : ?#{[1]} } }")
  long findAndIncrementVisitsUsingSpELByLastname(String lastname, int increment); <3>

  @Update(pipeline = {"{ '$set' : { 'visits' : { '$add' : [ '$visits', ?1 ] } } }"})
  void findAndIncrementVisitsViaPipelineByLastname(String lastname, int increment); <4>

  @Update("{ '$push' : { 'shippingAddresses' : ?1 } }")
  long findAndPushShippingAddressByEmail(String email, Address address); <5>

  @Query("{ 'lastname' : ?0 }")
  @Update("{ '$inc' : { 'visits' : ?1 } }")
  void updateAllByLastname(String lastname, int increment); <6>
}
----
<1> 更新的过滤查询来自于方法名称。更新是 "原样" 的，没有绑定任何参数。
<2> 实际的增量值是由与 `?1` 占位符绑定的 `increment` 方法参数定义的。
<3> 使用 Spring 表达式语言（SpEL）进行参数绑定。
<4> 使用 pipeline 属性来发布 <<mongo-template.aggregation-update,聚合管道更新>>。
<5> 更新可能包含复杂的对象。
<6> 将一个 <<mongodb.repositories.queries.json-based,基于字符串的查询>> 与更新结合起来。
====

WARNING: Repository 更新不会发出持久性或映射生命周期事件。

[[mongodb.repositories.queries.delete]]
=== Repository Delete 查询

上表中的关键词可以与 `delete…By` 或 `remove…By` 结合使用，创建删除匹配文档的查询。

.`Delete…By` 查询
====
[source,java]
----
public interface PersonRepository extends MongoRepository<Person, String> {

  List <Person> deleteByLastname(String lastname);      <1>

  Long deletePersonByLastname(String lastname);         <2>

  @Nullable
  Person deleteSingleByLastname(String lastname);       <3>

  Optional<Person> deleteByBirthdate(Date birthdate);   <4>
}
----

<1> 使用 `List` 的返回类型可以在实际删除文档之前检索并返回所有匹配的文档。
<2> 一个数字返回类型直接删除匹配的文档，返回被删除的文档总数。
<3> 单一 domain 类型的结果会检索并删除第一个匹配的文档。
<4> 与 3 中相同，但被包裹在一个 `Optional` 类型中。
====

[[mongodb.repositories.queries.geo-spatial]]
=== 地理空间（Geo） Repository 查询

正如你在前面的关键字表中看到的，有几个关键字在MongoDB查询中触发了地理空间操作。`Near` 关键字允许一些进一步的修改，正如接下来的几个例子所示。

下面的例子显示了如何定义一个 `near` 查询，找到与给定点有一定距离的所有人员。

.高级 `Near` 查询
====
[source,java]
----
public interface PersonRepository extends MongoRepository<Person, String> {

  // { 'location' : { '$near' : [point.x, point.y], '$maxDistance' : distance}}
  List<Person> findByLocationNear(Point location, Distance distance);
}
----
====

在查询方法中添加一个 `Distance` 参数可以将结果限制在给定的距离内。如果 `Distance` 被设置为包含一个 `Metric`，我们会透明地使用 `$nearSphere` 而不是 `$code`，如下例所示。

.使用 `Distance` 和 `Metrics`
====
[source,java]
----
Point point = new Point(43.7, 48.8);
Distance distance = new Distance(200, Metrics.KILOMETERS);
… = repository.findByLocationNear(point, distance);
// {'location' : {'$nearSphere' : [43.7, 48.8], '$maxDistance' : 0.03135711885774796}}
----
====

使用带有 `Metric` 的 `Distance` 会导致添加一个 `$nearSphere`（而不是普通的 `$near`）子句。除此之外，实际的距离会根据所使用的 `Metrics` 来计算。

(注意，`Metric` 并不是指公制计量单位。它可能是英里而不是公里。相反，`metric` 指的是一个测量系统的概念，不管你使用哪种系统)。

NOTE: 在目标属性上使用 `@GeoSpatialIndexed(type = GeoSpatialIndexType.GEO_2DSPHERE)` 可以强制使用 `$nearSphere` 操作符。

==== 地理附近（Geo-near）查询

Spring Data MongoDb 支持地理范围内的查询，如下例所示。

[source,java]
----
public interface PersonRepository extends MongoRepository<Person, String> {

  // {'geoNear' : 'location', 'near' : [x, y] }
  GeoResults<Person> findByLocationNear(Point location);

  // No metric: {'geoNear' : 'person', 'near' : [x, y], maxDistance : distance }
  // Metric: {'geoNear' : 'person', 'near' : [x, y], 'maxDistance' : distance,
  //          'distanceMultiplier' : metric.multiplier, 'spherical' : true }
  GeoResults<Person> findByLocationNear(Point location, Distance distance);

  // Metric: {'geoNear' : 'person', 'near' : [x, y], 'minDistance' : min,
  //          'maxDistance' : max, 'distanceMultiplier' : metric.multiplier,
  //          'spherical' : true }
  GeoResults<Person> findByLocationNear(Point location, Distance min, Distance max);

  // {'geoNear' : 'location', 'near' : [x, y] }
  GeoResults<Person> findByLocationNear(Point location);
}
----

[[mongodb.repositories.queries.json-based]]
=== MongoDB 基于 JSON 的查询方法和字段限制

通过将 `org.springframework.data.mongodb.repository.Query` 注解添加到你的 repository 查询方法中，你可以指定一个 MongoDB JSON 查询字符串来使用，而不是让查询从方法名称中导出，如下例所示。

[source,java]
----
public interface PersonRepository extends MongoRepository<Person, String> {

  @Query("{ 'firstname' : ?0 }")
  List<Person> findByThePersonsFirstname(String firstname);

}
----

占位符 `?0` 让你把方法参数的值替换到JSON查询字符串中。


NOTE: `String` 参数值在绑定过程中被转义，这意味着不可能通过参数添加 MongoDB 特定的操作符。

你也可以使用过滤器属性来限制被映射到 Java 对象中的属性集，如下例所示。

[source,java]
----
public interface PersonRepository extends MongoRepository<Person, String> {

  @Query(value="{ 'firstname' : ?0 }", fields="{ 'firstname' : 1, 'lastname' : 1}")
  List<Person> findByThePersonsFirstname(String firstname);

}
----

前面例子中的查询只返回 `Person` 对象的 `firstname`、`lastname` 和 `Id` 属性。`age` 属性是一个 `java.lang.Integer`，没有被设置，因此它的值是 `null`。

[[mongodb.repositories.queries.sort]]
=== 对查询方法的结果进行排序

MongoDB repository 允许用各种方法来定义排序顺序。让我们看一下下面的例子。

.对结果进行排序
====
[source,java]
----
public interface PersonRepository extends MongoRepository<Person, String> {

  List<Person> findByFirstnameSortByAgeDesc(String firstname); <1>

  List<Person> findByFirstname(String firstname, Sort sort);   <2>

  @Query(sort = "{ age : -1 }")
  List<Person> findByFirstname(String firstname);              <3>

  @Query(sort = "{ age : -1 }")
  List<Person> findByLastname(String lastname, Sort sort);     <4>
}
----



<1> 静态排序源于方法名称。`SortByAgeDesc` 的结果是 `{ age : -1 }` 为排序参数。
<2> 使用一个方法参数进行动态排序。`Sort.by(DESC, "age")` 为排序参数创建 `{ age : -1 }`。
<3> 通过 `Query` 注解进行静态排序。按照 `sort` 属性中的规定应用排序参数。
<4> 通过 `Query` 注解的默认排序与通过方法参数的动态排序相结合。`Sort.unsorted()` 的结果是 `{ age : -1 }`。使用 `Sort.by(ASC, "age")` 覆盖了默认值并创建了 `{ age : 1 }`。`Sort.by(ASC, "firstname")` 改变了默认值，结果是 `{ age : -1, firstname : 1 }`。
====

[[mongodb.repositories.queries.json-spel]]
=== 用 SpEL 表达式进行基于 JSON 的查询

查询字符串和字段定义可与 SpEL 表达式一起使用，以便在运行时创建动态查询。SpEL 表达式可以提供谓词值（predicate value），并可用于用子文档扩展谓词。

表达式通过一个包含所有参数的数组暴露方法参数。下面的查询使用 `[0]` 来声明 `lastname` 的谓语值（predicate value）（相当于 `?0` 的参数绑定）。

[source,java]
----
public interface PersonRepository extends MongoRepository<Person, String> {

  @Query("{'lastname': ?#{[0]} }")
  List<Person> findByQueryWithExpression(String param0);
}
----

表达式可以用来调用函数、评估条件和构造值。与 JSON 一起使用的 SpEL 表达式揭示了一个副作用，因为 SpEL 内部的类似 `Map` 的声明读起来就像 JSON 一样，正如下面的例子所示。

[source,java]
----
public interface PersonRepository extends MongoRepository<Person, String> {

  @Query("{'id': ?#{ [0] ? {$exists :true} : [1] }}")
  List<Person> findByQueryWithExpressionAndNestedObject(boolean param0, String param1);
}
----

WARNING: 查询字符串中的 SpEL 可以是增强查询的一种强大方式。然而，它们也可以接受广泛的不需要的参数。确保在将字符串传递给查询之前对其进行脱敏，以避免产生漏洞或对你的查询进行不必要的改变。

表达式支持可通过查询 SPI：`org.springframework.data.repository.query.spi.EvaluationContextExtension` 来扩展。查询 SPI 可以贡献属性和函数，并可以定制根对象。扩展是在构建查询时，在 SpEL 评估时从 application context 中检索出来的。
下面的例子显示了如何使用 `EvaluationContextExtension`。

[source,java]
----
public class SampleEvaluationContextExtension extends EvaluationContextExtensionSupport {

  @Override
  public String getExtensionId() {
    return "security";
  }

  @Override
  public Map<String, Object> getProperties() {
    return Collections.singletonMap("principal", SecurityContextHolder.getCurrent().getPrincipal());
  }
}
----

NOTE: 自己启动 `MongoRepositoryFactory` 并不了解应用程序的上下文，需要进一步配置以获取 `Query` SPI 扩展。

NOTE: 响应式查询方法可以利用 `org.springframework.data.spel.spi.ReactiveEvaluationContextExtension`.

[[mongodb.repositories.queries.type-safe]]
=== 类型安全的查询方法

MongoDB repository 支持与 http://www.querydsl.com/[Querydsl] 项目集成，后者提供了一种执行类型安全查询的方法。引用项目描述中的话，"不是把查询写成内联字符串或外化成XML文件，而是通过 fluent API 来构建。" 它提供了以下功能:

* 在 IDE 中的代码补全（所有的属性、方法和操作都可以在你喜欢的 Java IDE 中展开）
* 几乎不允许语法上的无效查询（在所有层面上都是类型安全的）。
* Domain 类型和属性可以被安全引用 — 不涉及字符串
* 能更好地适应Domain类型的重构变化。
* 增量查询的定义更容易。

关于如何使用 Maven 或 Ant 为基于 APT 的代码生成启动环境，请参阅  http://www.querydsl.com/static/querydsl/latest/reference/html/[QueryDSL 文档]。

QueryDSL可以让你编写如下的查询:

[source,java]
----
QPerson person = new QPerson("person");
List<Person> result = repository.findAll(person.address.zipCode.eq("C0123"));

Page<Person> page = repository.findAll(person.lastname.contains("a"),
                                       PageRequest.of(0, 2, Direction.ASC, "lastname"));
----

`QPerson` 是一个由 Java 注解后处理工具生成的类。它是一个 `Predicate`，可以让你编写类型安全的查询。请注意，除了 `C0123` 的值之外，查询中没有任何字符串。

你可以通过使用 `QuerydslPredicateExecutor` 接口来使用生成的 `Predicate` 类，下面的列表显示了这一点:

[source,java]
----
public interface QuerydslPredicateExecutor<T> {

  T findOne(Predicate predicate);

  List<T> findAll(Predicate predicate);

  List<T> findAll(Predicate predicate, OrderSpecifier<?>... orders);

  Page<T> findAll(Predicate predicate, Pageable pageable);

  Long count(Predicate predicate);
}
----

要在你的 repository 实现中使用它，需要把它添加到你的接口所继承的 repository 接口列表中，如下面的例子所示。

[source,java]
----
public interface PersonRepository extends MongoRepository<Person, String>, QuerydslPredicateExecutor<Person> {

   // additional query methods go here
}
----

[[mongodb.repositories.queries.full-text]]
===  全文检索查询

MongoDB 的全文搜索功能是特定于 store 的，因此，可以在 `MongoRepository` 上找到，而不是在更通用的 `CrudRepository` 上。我们需要一个有全文索引的文档（参见 "`<<mapping-usage-indexes.text-index>>`" 以了解如何创建全文索引）。

`MongoRepository` 上的其他方法将 `TextCriteria` 作为一个输入参数。除了这些明确的方法之外，还可以添加一个 `TextCriteria` 衍生的 repository 方法。这些标准（criteria）被添加为额外的 `AND` 标准。一旦实体包含一个 `@TextScore` 注解的属性，
就可以检索到文档的全文得分。此外，`@TextScore` 注解也使得按文档的分数排序成为可能，正如下面的例子所示。

[source,java]
----
@Document
class FullTextDocument {

  @Id String id;
  @TextIndexed String title;
  @TextIndexed String content;
  @TextScore Float score;
}

interface FullTextRepository extends Repository<FullTextDocument, String> {

  // Execute a full-text search and define sorting dynamically
  List<FullTextDocument> findAllBy(TextCriteria criteria, Sort sort);

  // Paginate over a full-text search result
  Page<FullTextDocument> findAllBy(TextCriteria criteria, Pageable pageable);

  // Combine a derived query with a full-text search
  List<FullTextDocument> findByTitleOrderByScoreDesc(String title, TextCriteria criteria);
}


Sort sort = Sort.by("score");
TextCriteria criteria = TextCriteria.forDefaultLanguage().matchingAny("spring", "data");
List<FullTextDocument> result = repository.findAllBy(criteria, sort);

criteria = TextCriteria.forDefaultLanguage().matching("film");
Page<FullTextDocument> page = repository.findAllBy(criteria, PageRequest.of(1, 1, sort));
List<FullTextDocument> result = repository.findByTitleOrderByScoreDesc("mongodb", criteria);
----

include::../{spring-data-commons-docs}/repository-projections.adoc[leveloffset=+2]

include::./mongo-repositories-aggregation.adoc[]

[[mongodb.repositories.misc.cdi-integration]]
== CDI 集成

repository 接口的实例通常由容器创建，而 Spring 是与 Spring Data 合作时最自然的选择。从 1.3.0 版本开始，Spring Data MongoDB 带有一个自定义的 CDI 扩展，
可以让你在 CDI 环境中使用 repository 抽象。该扩展是 JAR 的一部分。要激活它，请将 Spring Data MongoDB JAR 放入你的 classpath。现在你可以通过为 `MongoTemplate` 实现 CDI Producer 来设置基础设施，如下面的例子所示。

[source,java]
----
class MongoTemplateProducer {

    @Produces
    @ApplicationScoped
    public MongoOperations createMongoTemplate() {

        MongoDatabaseFactory factory = new SimpleMongoClientDatabaseFactory(MongoClients.create(), "database");
        return new MongoTemplate(factory);
    }
}
----

Spring Data MongoDB CDI 扩展将 `MongoTemplate` 作为 CDI Bean 使用，并在容器请求 repository 类型的 bean 时为 Spring Data Repository 创建一个代理。因此，获取 Spring Data Repository 的实例只是声明一个 `@Inject` 属性的问题，正如下面的例子所示。

[source,java]
----
class RepositoryClient {

  @Inject
  PersonRepository repository;

  public void businessMethod() {
    List<Person> people = repository.findAll();
  }
}
----
