[[mongo.jsonSchema]]
=== JSON Schema

从3.6版本开始，MongoDB支持根据提供的 https://docs.mongodb.com/manual/core/schema-validation/#json-schema[JSON Schema] 验证文档的集合。schema 本身以及验证动作和级别都可以在创建集合时定义，如下面的例子所示。

.JSON schema 示例
====
[source,json]
----
{
  "type": "object",                                                        <1>

  "required": [ "firstname", "lastname" ],                                 <2>

  "properties": {                                                          <3>

    "firstname": {                                                         <4>
      "type": "string",
      "enum": [ "luke", "han" ]
    },
    "address": {                                                           <5>
      "type": "object",
      "properties": {
        "postCode": { "type": "string", "minLength": 4, "maxLength": 5 }
      }
    }
  }
}
----
<1> JSON schema 文档总是从根部开始描述整个文档。一个 schema 是一个 schema 对象本身，它可以包含描述属性和子文件的嵌入式 schema 对象。
<2> `required` 是一个描述文档中哪些属性是必需的属性。它可以和其他 schema 约束一起被选择性地指定。参见 MongoDB 关于 https://docs.mongodb.com/manual/reference/operator/query/jsonSchema/#available-keywords[可用关键字的文档]。
<3> `properties` 与描述一个 `object` 类型的 schema 对象有关。它包含特定属性 schema 式约束。
<4> `firstname` 为文档中的 `firstname` 字段指定约束。这里，它是一个基于字符串的 `properties` 元素，声明了可能的字段值。
<5> `address` 是一个子文档，为其 `postCode` 字段的值定义了一个 schema。
====

你可以通过指定 schema 文档（即使用 `Document` API 解析或构建文档对象）或使用 `org.springframework.data.mongodb.core.schema` 中的 Spring Data 的 JSON schema 工具构建 schema 来提供 schema。
`MongoJsonSchema` 是所有 JSON schema 相关操作的入口点。下面的示例展示了如何使用 `MongoJsonSchema.builder()` 来创建一个 JSON schema。

.创建一个 JSON schema
====
[source,java]
----
MongoJsonSchema.builder()                                                    <1>
    .required("lastname")                                                    <2>

    .properties(
                required(string("firstname").possibleValues("luke", "han")), <3>

                object("address")
                     .properties(string("postCode").minLength(4).maxLength(5)))

    .build();                                                                <4>
----
<1> 获得一个 schema builder，用 fluent API 配置模式。
<2> 直接配置所需的 properties，如图所示，或如 3 中的更多细节。
<3> 配置所需的 String 类型的 `firstname` 字段，只允许 `luke` 和 `han` 值。`Properties` 可以是类型化的，也可以是未类型化的。使用 `JsonSchemaProperty` 的静态导入，使语法稍微紧凑一些，并获得 `string(…)` 等入口。
<4> 构建 schema 对象。使用该 schema 来创建一个集合或  <<mongodb-template-query.criteria,查询文档>>。
====

已经有一些预定义和强类型的模式对象（`JsonSchemaObject` 和 `JsonSchemaProperty`）可以通过网关接口上的静态方法获得。然而，你可能需要建立自定义的 property 验证规则，这些规则可以通过 builder API创建，如下例所示。

[source,java]
----
// "birthdate" : { "bsonType": "date" }
JsonSchemaProperty.named("birthdate").ofType(Type.dateType());

// "birthdate" : { "bsonType": "date", "description", "Must be a date" }
JsonSchemaProperty.named("birthdate").with(JsonSchemaObject.of(Type.dateType()).description("Must be a date"));
----

`CollectionOptions` 提供了对集合的 schema 支持的入口，正如下面的例子所示。

.用 `$jsonSchema` 创建集合
====
[source,java]
----
MongoJsonSchema schema = MongoJsonSchema.builder().required("firstname", "lastname").build();

template.createCollection(Person.class, CollectionOptions.empty().schema(schema));
----
====

[[mongo.jsonSchema.generated]]
==== 生成一个 Schema

设置 schema 可能是一项耗时的工作，我们鼓励每个决定这样做的人，真的要花点时间。这很重要，schema 的改变可能很困难。然而，有时人们可能并不想与之纠缠不清，这就是 `JsonSchemaCreator` 发挥作用的地方。

`JsonSchemaCreator` 及其默认实现会从映射基础设施提供的 domain 类型元数据中生成 `MongoJsonSchema`。这意味着，<<mapping-usage-annotations, annotated properties>> 以及潜在的 <<mapping-configuration, custom conversions>> 都被考虑在内。

.从domain 类型生成 Json Schema
====
[source,java]
----
public class Person {

    private final String firstname;                   <1>
    private final int age;                            <2>
    private Species species;                          <3>
    private Address address;                          <4>
    private @Field(fieldType=SCRIPT) String theForce; <5>
    private @Transient Boolean useTheForce;           <6>

    public Person(String firstname, int age) {        <1> <2>

        this.firstname = firstname;
        this.age = age;
    }

    // gettter / setter omitted
}

MongoJsonSchema schema = MongoJsonSchemaCreator.create(mongoOperations.getConverter())
    .createSchemaFor(Person.class);

template.createCollection(Person.class, CollectionOptions.empty().schema(schema));
----

[source,json]
----
{
    'type' : 'object',
    'required' : ['age'],                     <2>
    'properties' : {
        'firstname' : { 'type' : 'string' },  <1>
        'age' : { 'bsonType' : 'int' }        <2>
        'species' : {                         <3>
            'type' : 'string',
            'enum' : ['HUMAN', 'WOOKIE', 'UNKNOWN']
        }
        'address' : {                         <4>
            'type' : 'object'
            'properties' : {
                'postCode' : { 'type': 'string' }
            }
        },
        'theForce' : { 'type' : 'javascript'} <5>
     }
}
----
<1> 简单的对象 properties 被认为是常规 properties。
<2> 基本类型被认为是必要的属性。
<3> 枚举被限制为可能的值。
<4> 对象类型properties 被检查并表示为嵌套文档。
<5> 被转换器转换为 `Code` 的 `String` 类型属性。
<6> `@Transient` 属性在生成 schema 时被省略。
====

NOTE: 使用可转换为 `ObjectId` 的类型（如 `String`）的 `_id` 属性被映射为 `{type : 'object'}`，除非通过 `@MongoId` 注解有更具体的信息。

[cols="2,2,6", options="header"]
.Sepcial Schema Generation rules
|===
| Java
| Schema Type
| Notes

| `Object`
| `type : object`
| with `properties` if metadata available.

| `Collection`
| `type : array`
| -

| `Map`
| `type : object`
| -

| `Enum`
| `type : string`
| with `enum` property holding the possible enumeration values.

| `array`
| `type : array`
| simple type array unless it's a `byte[]`

| `byte[]`
| `bsonType : binData`
| -

|===

上面的例子展示了如何从一个非常精确的类型源中推导出 schema。在 domain 模型中使用多态元素会导致 `Object` 和泛型 `<T>` 的 schema 表示不准确，这些类型很可能被表示为 `{ type : 'object' }` 而没有进一步说明。
`MongoJsonSchemaCreator.property(..)` 允许定义额外的细节，例如在渲染 schema 时应考虑的嵌套文档类型。

.为 properties 指定额外的类型
====
[source,java]
----
class Root {
	Object value;
}

class A {
	String aValue;
}

class B {
	String bValue;
}
MongoJsonSchemaCreator.create()
    .property("value").withTypes(A.class, B.class) <1>
----

[source,json]
----
{
    'type' : 'object',
    'properties' : {
        'value' : {
            'type' : 'object',
            'properties' : {                       <1>
                'aValue' : { 'type' : 'string' },
                'bValue' : { 'type' : 'string' }
            }
        }
    }
}
----
<1> 给定类型的 Properties 被合并为一个元素。
====

MongoDB 的无 schema 方法允许在一个集合中存储不同结构的文档。这些文档可以通过一个共同的基类进行建模。无论选择哪种方法，`MongoJsonSchemaCreator.merge(…)` 都可以帮助规避将多个 schema 合并为一个的需要。

.将多个 Schema 合并为一个 Schema definition
====
[source,java]
----
abstract class Root {
	String rootValue;
}

class A extends Root {
	String aValue;
}

class B extends Root {
	String bValue;
}

MongoJsonSchemaCreator.mergedSchemaFor(A.class, B.class) <1>
----

[source,json]
----
{
    'type' : 'object',
       'properties' : { <1>
           'rootValue' : { 'type' : 'string' },
           'aValue' : { 'type' : 'string' },
           'bValue' : { 'type' : 'string' }
       }
    }
}
----
<1> 给定类型的Properties （及其继承的属性）被合并为一个schema。
====

[NOTE]
====
具有相同名称的 Properties 需要引用相同的 JSON schema 才能被合并。下面的例子显示了一个因为数据类型不匹配而无法自动合并的 definition。在这种情况下，必须向 `MongoJsonSchemaCreator` 提供一个 `ConflictResolutionFunction`。

[source,java]
----
class A extends Root {
	String value;
}

class B extends Root {
	Integer value;
}
----
====

[[mongo.jsonSchema.query]]
==== 查询一个集合以匹配JSON Schema

你可以使用 schema 来查询任何集合中符合 JSON schema 所定义的给定结构的文档，如下面的例子所示。

.查询符合 `$jsonSchema` 的文档
====
[source,java]
----
MongoJsonSchema schema = MongoJsonSchema.builder().required("firstname", "lastname").build();

template.find(query(matchingDocumentStructure(schema)), Person.class);
----
====

[[mongo.jsonSchema.encrypted-fields]]
==== 加密的字段

MongoDB 4.2 https://docs.mongodb.com/master/core/security-client-side-encryption/[字段级加密]  允许直接对单个属性进行加密。

在设置 JSON Schema 时，Properties 可以被包裹在一个加密的 Properties 中，如下例所示。

.通过 Json Schema 的客户端字段级加密
====
[source,java]
----
MongoJsonSchema schema = MongoJsonSchema.builder()
    .properties(
        encrypted(string("ssn"))
            .algorithm("AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic")
            .keyId("*key0_id")
	).build();
----
====

我们可以利用 `@Encrypted` 注解来代替手动定义加密字段，如下文所示。

.通过 Json Schema 的客户端字段级加密
====
[source,java]
----
@Document
@Encrypted(keyId = "xKVup8B1Q+CkHaVRx+qa+g==", algorithm = "AEAD_AES_256_CBC_HMAC_SHA_512-Random") <1>
static class Patient {

    @Id String id;
    String name;

    @Encrypted <2>
    String bloodType;

    @Encrypted(algorithm = "AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic") <3>
    Integer ssn;
}
----
<1> 将为 `encryptMetadata` 设置的默认加密设置。
<2> 使用默认加密设置的加密字段。
<3> 加密字段覆盖了默认的加密算法。
====

[TIP]
====
`@Encrypted` 注解支持通过 SpEL 表达式解析 keyIds。要做到这一点，需要额外的环境元数据（通过 `MappingContext`），并且必须提供。

[source,java]
----
@Document
@Encrypted(keyId = "#{mongocrypt.keyId(#target)}")
static class Patient {

    @Id String id;
    String name;

    @Encrypted(algorithm = "AEAD_AES_256_CBC_HMAC_SHA_512-Random")
    String bloodType;

    @Encrypted(algorithm = "AEAD_AES_256_CBC_HMAC_SHA_512-Deterministic")
    Integer ssn;
}

MongoJsonSchemaCreator schemaCreator = MongoJsonSchemaCreator.create(mappingContext);
MongoJsonSchema patientSchema = schemaCreator
    .filter(MongoJsonSchemaCreator.encryptedOnly())
    .createSchemaFor(Patient.class);
----

`mongocrypt.keyId` 函数是通过 `EvaluationContextExtension` 定义的，如下面的片段所示。提供一个自定义扩展提供了计算 keyIds 的最灵活的方式。

[source,java]
----
public class EncryptionExtension implements EvaluationContextExtension {

    @Override
    public String getExtensionId() {
        return "mongocrypt";
    }

    @Override
    public Map<String, Function> getFunctions() {
        return Collections.singletonMap("keyId", new Function(getMethod("computeKeyId", String.class), this));
    }

    public String computeKeyId(String target) {
        // ... lookup via target element name
    }
}
----

要在 Spring Boot 应用程序中把派生加密设置与 `AutoEncryptionSettings` 结合起来，请使用 `MongoClientSettingsBuilderCustomizer`。

[source,java]
----
@Bean
MongoClientSettingsBuilderCustomizer customizer(MappingContext mappingContext) {
    return (builder) -> {

        // ... keyVaultCollection, kmsProvider, ...

        MongoJsonSchemaCreator schemaCreator = MongoJsonSchemaCreator.create(mappingContext);
        MongoJsonSchema patientSchema = schemaCreator
            .filter(MongoJsonSchemaCreator.encryptedOnly())
            .createSchemaFor(Patient.class);

        AutoEncryptionSettings autoEncryptionSettings = AutoEncryptionSettings.builder()
            .keyVaultNamespace(keyVaultCollection)
            .kmsProviders(kmsProviders)
            .extraOptions(extraOpts)
            .schemaMap(Collections.singletonMap("db.patient", patientSchema.schemaDocument().toBsonDocument()))
            .build();

        builder.autoEncryptionSettings(autoEncryptionSettings);
    };
}
----
====

NOTE: 请确保将驱动 `com.mongodb.AutoEncryptionSettings` 设置为使用客户端加密。MongoDB 不支持对所有字段类型进行加密。特定的数据类型需要确定性的加密，以保留平等比较（equality comparison）功能。

[[mongo.jsonSchema.types]]
==== JSON Schema 类型

下表显示了支持的 JSON schema 类型。

[cols="3,1,6", options="header"]
.支持的 JSON schema 类型
|===
| Schema Type
| Java Type
| Schema Properties

| `untyped`
| -
| `description`, generated `description`, `enum`, `allOf`, `anyOf`, `oneOf`, `not`

| `object`
| `Object`
| `required`, `additionalProperties`, `properties`, `minProperties`, `maxProperties`, `patternProperties`

| `array`
| any array except `byte[]`
| `uniqueItems`, `additionalItems`, `items`, `minItems`, `maxItems`

| `string`
| `String`
| `minLength`, `maxLentgth`, `pattern`

| `int`
| `int`, `Integer`
| `multipleOf`, `minimum`, `exclusiveMinimum`, `maximum`, `exclusiveMaximum`

| `long`
| `long`, `Long`
| `multipleOf`, `minimum`, `exclusiveMinimum`, `maximum`, `exclusiveMaximum`

| `double`
| `float`, `Float`, `double`, `Double`
| `multipleOf`, `minimum`, `exclusiveMinimum`, `maximum`, `exclusiveMaximum`

| `decimal`
| `BigDecimal`
| `multipleOf`, `minimum`, `exclusiveMinimum`, `maximum`, `exclusiveMaximum`

| `number`
| `Number`
| `multipleOf`, `minimum`, `exclusiveMinimum`, `maximum`, `exclusiveMaximum`

| `binData`
| `byte[]`
| (none)

| `boolean`
| `boolean`, `Boolean`
| (none)

| `null`
| `null`
| (none)

| `objectId`
| `ObjectId`
| (none)

| `date`
| `java.util.Date`
| (none)

| `timestamp`
| `BsonTimestamp`
| (none)

| `regex`
| `java.util.regex.Pattern`
| (none)

|===

NOTE: `untyped` 是一个被所有类型化 schema 类型所继承的通用类型。它为类型化 schema 类型提供所有 `untyped` schema 属性。

欲了解更多信息，请参见 https://docs.mongodb.com/manual/reference/operator/query/jsonSchema/#op._S_jsonSchema[$jsonSchema]。
