[[query-by-example.running]]
== 运行 Example

下面的例子显示了在使用 repository（这里是指 `Person` 对象）时如何通过 example 进行查询。

.使用 repository 的 Example 查询
====
[source, java]
----
public interface PersonRepository extends QueryByExampleExecutor<Person> {

}

public class PersonService {

  @Autowired PersonRepository personRepository;

  public List<Person> findPeople(Person probe) {
    return personRepository.findAll(Example.of(probe));
  }
}
----
====

一个包含无类型的 `ExampleSpec` 的 `Example` 使用 Repository 类型和它的集合名称。泛型 `ExampleSpec` 实例使用其泛型作为结果类型，并使用来自 `Repository` 实例的集合名称。

NOTE: 当在 `ExampleSpec` 中包含 `null` 值时，Spring Data Mongo 使用嵌入式文档匹配而不是点符号属性匹配。这样做是为了强迫所有的属性值和嵌入式文档中的属性顺序进行精确的文档匹配。

Spring Data MongoDB 提供对以下匹配选项的支持:

[cols="1,2", options="header"]
.`StringMatcher` 选项
|===
| Matching
| Logical result

| `DEFAULT` (区分大小写)
| `{"firstname" : firstname}`

| `DEFAULT` (case-insensitive)
| `{"firstname" : { $regex: firstname, $options: 'i'}}`

| `EXACT`  (区分大小写)
| `{"firstname" : { $regex: /^firstname$/}}`

| `EXACT` (case-insensitive)
| `{"firstname" : { $regex: /^firstname$/, $options: 'i'}}`

| `STARTING`  (区分大小写)
| `{"firstname" : { $regex: /^firstname/}}`

| `STARTING` (case-insensitive)
| `{"firstname" : { $regex: /^firstname/, $options: 'i'}}`

| `ENDING`  (区分大小写)
| `{"firstname" : { $regex: /firstname$/}}`

| `ENDING` (case-insensitive)
| `{"firstname" : { $regex: /firstname$/, $options: 'i'}}`

| `CONTAINING`  (区分大小写)
| `{"firstname" : { $regex: /.\*firstname.*/}}`

| `CONTAINING` (case-insensitive)
| `{"firstname" : { $regex: /.\*firstname.*/, $options: 'i'}}`

| `REGEX`  (区分大小写)
| `{"firstname" : { $regex: /firstname/}}`

| `REGEX` (case-insensitive)
| `{"firstname" : { $regex: /firstname/, $options: 'i'}}`

|===

[[query-by-example.untyped]]
== Untyped Example

默认情况下，`Example` 是严格类型化的。这意味着映射的查询有一个包含的类型匹配，将其限制在可探测的可分配类型。例如，当坚持使用默认的类型键（`_class`）时，查询有如下限制（`_class : { $in : [ com.acme.Person] }`）。

通过使用 `UntypedExampleMatcher`，可以绕过默认行为，跳过类型限制。因此，只要字段名匹配，几乎所有的 domain 类型都可以作为创建引用的探针，正如下面的例子所示。

.Untyped Example Query
====
[source, java]
----

class JustAnArbitraryClassWithMatchingFieldName {
  @Field("lastname") String value;
}

JustAnArbitraryClassWithMatchingFieldNames probe = new JustAnArbitraryClassWithMatchingFieldNames();
probe.value = "stark";

Example example = Example.of(probe, UntypedExampleMatcher.matching());

Query query = new Query(new Criteria().alike(example));
List<Person> result = template.find(query, Person.class);
----
====

[NOTE]
====
如果你在一个集合中存储不同的实体或者选择不写 类型提示（<<mongo-template.type-mapping,type hints>>），那么 `UntypedExampleMatcher` 可能是你的正确选择。

另外，请记住，使用 `@TypeAlias` 需要对 `MappingContext` 进行急切的初始化。为此，配置 `initialEntitySet`，以确保读取操作的别名解析正确。
====
