[[mongo.reactive.repositories]]
= 响应式 MongoDB repositories

本章描述了 MongoDB 的响应式 repository 支持的特性。本章建立在 与 Spring Data Repository 一起工作 中解释的核心 <<repositories>> 支持的基础上。你应该对那里解释的基本概念有一个正确的理解。

[[mongo.reactive.repositories.libraries]]
== 响应式组合库

响应式空间提供了各种响应式组合库。最常见的库是 https://github.com/ReactiveX/RxJava[RxJava] 和 https://projectreactor.io/[Project Reactor]。

Spring Data MongoDB 建立在 https://mongodb.github.io/mongo-java-driver-reactivestreams/[MongoDB Reactive Streams] 驱动之上，通过依赖 https://www.reactive-streams.org/[Reactive Streams] 倡议来提供最大的互操作性。
静态 API，如 `ReactiveMongoOperations`，是通过使用 Project Reactor 的 `Flux` 和 `Mono` 类型提供的。Project Reactor 提供了各种适配器（adapters）来转换响应式包装类型（`Flux` 到 `Observable`，反之亦然），但转换很容易使你的代码变得混乱。

Spring Data 的 Repository 抽象是一个动态的 API，主要由你和你的需求在你声明查询方法时定义。响应式 MongoDB Repository 可以通过使用 RxJava 或 Project Reactor 包装类型，从以下库的特定存 Repository 接口中扩展实现。

* `ReactiveCrudRepository`
* `ReactiveSortingRepository`
* `RxJava2CrudRepository`
* `RxJava2SortingRepository`
* `RxJava3CrudRepository`
* `RxJava3SortingRepository`

Spring Data 在幕后转换了响应式包装类型，因此你可以坚持使用你最喜欢的组合库。

[[mongo.reactive.repositories.usage]]
== 用法

要访问存储在 MongoDB 数据库中的 domain 实体，你可以使用我们复杂的 repository 支持，它可以大大缓解实现这些实体。要做到这一点，为你的 repository 创建一个类似的接口。不过在这之前，你需要一个实体，比如下面这个例子中定义的实体。

.简单的 `Person` 实体
====
[source,java]
----
public class Person {

  @Id
  private String id;
  private String firstname;
  private String lastname;
  private Address address;

  // … getters and setters omitted
}
----
====

请注意，前面的例子中定义的实体有一个名为 `id` 的 `String` 类型的属性。 `MongoTemplate` 中使用的默认序列化机制（它支持 repository）将名为 `id` 的属性视为文档 ID。
目前，我们支持 `String`、`ObjectId` 和 `BigInteger` 作为 `id` 类型。请参阅 <<mongo-template.id-handling, ID 映射>> 以了解更多关于在映射层中如何处理 id 字段的信息。

下面的例子显示了如何创建一个接口，定义针对前述例子中的 `Person` 对象的查询。

.持久保存 `Person` 实体的基本 repository 接口
====
[source]
----
public interface ReactivePersonRepository extends ReactiveSortingRepository<Person, String> {

  Flux<Person> findByFirstname(String firstname);                                   <1>

  Flux<Person> findByFirstname(Publisher<String> firstname);                        <2>

  Flux<Person> findByFirstnameOrderByLastname(String firstname, Pageable pageable); <3>

  Mono<Person> findByFirstnameAndLastname(String firstname, String lastname);       <4>

  Mono<Person> findFirstByLastname(String lastname);                                <5>
}
----
<1> 该方法显示了对所有具有给定 `lastname` 的人的查询。该查询是通过解析方法名称中可以与 `And` 和 `Or` 相连接的约束条件而得到的。因此，方法名称的结果是一个查询表达式 `{"lastname" : lastname}`。
<2> 一旦给定的 `Publisher` 发出 `firstname` ，该方法将显示对所有具有给定 `firstname` 的人的查询。
<3> 使用 `Pageable` 向数据库传递 `offset` 和 `sort` 参数。
<4> 为给定的 criteria 寻找一个单一的实体。对于非唯一的结果，抛出 `IncorrectResultSizeDataAccessException`。
<5> 除非 <4>，否则即使查询产生了更多的结果文档，第一个实体也总是被发出。
====

对于 Java 配置，使用 `@EnableReactiveMongoRepositories` 注解。该注解带有与命名空间元素相同的属性。如果没有配置基础包（base package），基础设施会扫描注解的配置类的包。

NOTE: MongoDB 使用两种不同的驱动程序来进行强制性（同步/阻塞）和反应性（非阻塞）数据访问。您必须通过使用 Reactive Streams 驱动程序创建连接，以便为 Spring Data 的 Reactive MongoDB 支持提供所需的基础设施。
因此，您必须为 MongoDB 的 Reactive Streams 驱动程序提供单独的配置。注意，如果你使用反应式和阻塞式 Spring Data MongoDB 模板和 repository，你的应用程序会在两个不同的连接上运行。

下面的列表显示了如何为一个 repository 使用Java配置:

.Repository 的 Java 配置
====
[source,java]
----
@Configuration
@EnableReactiveMongoRepositories
class ApplicationConfig extends AbstractReactiveMongoConfiguration {

  @Override
  protected String getDatabaseName() {
    return "e-store";
  }

  @Override
  public MongoClient reactiveMongoClient() {
    return MongoClients.create();
  }

  @Override
  protected String getMappingBasePackage() {
    return "com.oreilly.springdata.mongodb";
  }
}
----
====

因为我们的 domain repository 继承了 `ReactiveSortingRepository`，它为你提供了 CRUD 操作以及对实体的排序访问方法。如下面的例子所示，使用 repository 实例是将其依赖注入到客户端的问题。

.对 Person 实体的排序访问
====
[source,java]
----
@ExtendWith(SpringExtension.class)
@ContextConfiguration
class PersonRepositoryTests {

    @Autowired ReactivePersonRepository repository;

    @Test
    public void sortsElementsCorrectly() {
      Flux<Person> persons = repository.findAll(Sort.by(new Order(ASC, "lastname")));
    }
}
----
====

WARNING: `Page` 的返回类型（如 `Mono<Page>`）不被响应式 repository 所支持。

可以在派生的查找方法中使用 `Pageable`，将 `sort`、`limit` 和 `offset` 参数传递给查询，以减少负载和网络流量。返回的 `Flux` 将只发出声明范围内的数据。

.使用响应式存储库的 Limit 和 Offset
====
[source,java]
----
Pageable page = PageRequest.of(1, 10, Sort.by("lastname"));
Flux<Person> persons = repository.findByFirstnameOrderByLastname("luke", page);
----
====

[[mongo.reactive.repositories.features]]
== 特性

与阻塞式 <<mongo.repositories,MongoDB Repositories>> 相比，Spring Data 的 Reactive MongoDB 支持的功能集有所减少。

它支持以下功能:

* <<mongodb.repositories.queries,使用字符串查询和查询派生的查询方法>>
* <<mongodb.reactive.repositories.queries.geo-spatial>>
* <<mongodb.repositories.queries.delete>>
* <<mongodb.repositories.queries.json-based>>
* <<mongodb.repositories.queries.full-text>>
* <<mongodb.reactive.repositories.queries.type-safe>>
* <<projections>>

[[mongodb.reactive.repositories.queries.geo-spatial]]
=== 地理空间 Repository 查询

正如你在前面的 "`<<mongodb.reactive.repositories.queries.geo-spatial>>`" 中所看到的，一些关键字在 MongoDB 查询中会触发地理空间操作。 `Near` 关键字允许一些进一步的修改，正如接下来的几个例子所示。

下面的例子显示了如何定义一个 `near` 查询，找到与给定点有一定距离的所有 person:

.高级 `Near` 查询
====
[source,java]
----
interface PersonRepository extends ReactiveMongoRepository<Person, String> {

  // { 'location' : { '$near' : [point.x, point.y], '$maxDistance' : distance}}
  Flux<Person> findByLocationNear(Point location, Distance distance);
}
----
====

在查询方法中添加一个 `Distance` 参数可以将结果限制在给定的距离内。如果 `Distance` 被设置为包含一个 `Metric`，我们会透明地使用 `$nearSphere` 而不是 `$code`，正如下面的例子所示。

.使用 `Distance` 与 `Metrics`。
====
[source,java]
----
Point point = new Point(43.7, 48.8);
Distance distance = new Distance(200, Metrics.KILOMETERS);
… = repository.findByLocationNear(point, distance);
// {'location' : {'$nearSphere' : [43.7, 48.8], '$maxDistance' : 0.03135711885774796}}
----
====

NOTE: 响应应式地理空间 repository 查询支持 domain 类型和响应式包装类型中的 `GeoResult<T>` 结果。不支持 `GeoPage` 和 `GeoResults`，因为它们与预先计算平均距离的递延结果方法相矛盾。不过，你仍然可以传入一个 `Pageable` 参数来自行翻阅结果。

使用带有 `Metric` 的 `Distance` 会导致添加一个 `$nearSphere`（而不是普通的 `$near`）子句。除此之外，实际的距离会根据所使用的 `Metrics` 来计算。

(请注意，`Metric` 并不是指公制的计量单位。它可能是英里而不是公里。相反，`metric` 指的是一个测量系统的概念，不管你使用哪种系统。)

NOTE: 在目标属性上使用 `@GeoSpatialIndexed(type = GeoSpatialIndexType.GEO_2DSPHERE)` 强制使用 `$nearSphere` 运算符。

==== 地理附近查询

Spring Data MongoDB 支持地理附近查询，如下面的例子所示。

[source,java]
----
interface PersonRepository extends ReactiveMongoRepository<Person, String>  {

  // {'geoNear' : 'location', 'near' : [x, y] }
  Flux<GeoResult<Person>> findByLocationNear(Point location);

  // No metric: {'geoNear' : 'person', 'near' : [x, y], maxDistance : distance }
  // Metric: {'geoNear' : 'person', 'near' : [x, y], 'maxDistance' : distance,
  //          'distanceMultiplier' : metric.multiplier, 'spherical' : true }
  Flux<GeoResult<Person>> findByLocationNear(Point location, Distance distance);

  // Metric: {'geoNear' : 'person', 'near' : [x, y], 'minDistance' : min,
  //          'maxDistance' : max, 'distanceMultiplier' : metric.multiplier,
  //          'spherical' : true }
  Flux<GeoResult<Person>> findByLocationNear(Point location, Distance min, Distance max);

  // {'geoNear' : 'location', 'near' : [x, y] }
  Flux<GeoResult<Person>> findByLocationNear(Point location);
}
----

[[mongodb.reactive.repositories.queries.type-safe]]
=== 类型安全的查询方法

响应式 MongoDB repository 支持与  http://www.querydsl.com/[Querydsl] 项目集成，后者提供了一种执行类型安全查询的方法。

[quote, Querydsl Team]
不是把查询写成内联字符串或外化成XML文件，而是通过一个 fluent API来构建。

它提供了以下功能:

* 在 IDE 中的代码补全（所有的属性、方法和操作都可以在你喜欢的 Java IDE 中展开）。
* 几乎不允许语法上的无效查询（在所有层面上都是类型安全的）。
* Domain 的类型和属性可以被安全地引用—不涉及字符串的问题。
* 能更好地适应 domain 类型的重构变化。
* 增量查询的定义更容易。

关于如何使用 Maven 或 Ant 为基于 APT 的代码生成启动环境，请参阅 http://www.querydsl.com/static/querydsl/latest/reference/html/[Querydsl 文档]。

Querydsl repository 支持让你编写和运行查询，例如以下内容。

[source,java]
----
QPerson person = QPerson.person;

Flux<Person> result = repository.findAll(person.address.zipCode.eq("C0123"));
----

`QPerson` 是一个由Java注释后处理工具生成的类。它是一个 `Predicate`，可以让你编写类型安全的查询。请注意，除了 `C0123` 值之外，查询中没有任何字符串。

你可以通过使用 `ReactiveQuerydslPredicateExecutor` 接口来使用生成的 `Predicate` 类，下面的列表显示了这一点。


.Reactive Querydsl 的网关 - `ReactiveQuerydslPredicateExecutor`
====
[source,java]
----
interface ReactiveQuerydslPredicateExecutor<T> {

	Mono<T> findOne(Predicate predicate);

	Flux<T> findAll(Predicate predicate);

	Flux<T> findAll(Predicate predicate, Sort sort);

	Flux<T> findAll(Predicate predicate, OrderSpecifier<?>... orders);

	Flux<T> findAll(OrderSpecifier<?>... orders);

	Mono<Long> count(Predicate predicate);

	Mono<Boolean> exists(Predicate predicate);
}
----
====

要在你的 repository 实现中使用它，需要把它添加到你的接口所继承的 repository 接口列表中，如下面的例子所示。

.Reactive Querydsl Respository Declaration
====
[source,java]
----
interface PersonRepository extends ReactiveMongoRepository<Person, String>, ReactiveQuerydslPredicateExecutor<Person> {

   // additional query methods go here
}
----
====

NOTE: 请注意，响应式 MongoDB，不支持连接（DBRef）。
