[[mongo.reactive]]
= 响应式 MongoDB 支持

响应式 MongoDB 支持包含以下基本功能集。

* Spring 配置支持，使用基于 Java 的 `@Configuration` 类、`MongoClient` 实例和副本集。
* `ReactiveMongoTemplate`，它是一个辅助类，通过以响应式方式使用 `MongoOperations` 来提高生产力。它包括 `Document` 实例和 POJO 之间的集成对象映射。
* 异常转换成 Spring 的可移植数据访问异常（Data Access Exception）层次结构。
* 功能丰富的对象映射与 Spring 的 `ConversionService` 集成。
* 基于注解的映射元数据，可扩展到支持其他元数据格式。
* 持久性（Persistence）和映射生命周期事件。
* 基于 Java 的 `Query`、`Criteria` 和 `Update` DSL。
* 自动实现响应式 repository 接口，包括支持自定义查询方法。

对于大多数任务，你应该使用 `ReactiveMongoTemplate` 或 repository 支持，它们都使用丰富的映射功能。`ReactiveMongoTemplate` 是访问功能的地方，如递增计数器（incrementing）或临时 CRUD 操作。
`ReactiveMongoTemplate` 还提供了回调方法，这样你就可以使用低级别的 API 工件（如 `MongoDatabase`）来直接与 MongoDB 进行通信。在各种 API 构件上的命名约定的目的是复制基础 MongoDB Java 驱动中的命名约定，以便你可以将现有知识映射到 Spring API 上。

[[mongodb-reactive-getting-started]]
== 入门

支持 Spring MongoDB 需要 MongoDB 2.6 或更高版本和 Java SE 8 或更高版本。

首先，你需要设置一个正在运行的 MongoDB 服务器。请参考 https://docs.mongodb.org/manual/core/introduction/[MongoDB 快速入门指南]，了解如何启动 MongoDB 实例。安装完毕后，启动 MongoDB 通常只需运行以下命令即可： `${MONGO_HOME}/bin/mongod`

要在 STS 中创建一个 Spring 项目，进入 File → New → Spring Template Project → Simple Spring Utility Project，在提示时按 Yes。然后输入一个项目和一个包的名称，比如 `org.spring.mongodb.example`。

然后在 `pom.xml` dependencies 部分添加以下内容。

[source,xml,subs="+attributes"]
----
<dependencies>

  <!-- other dependency elements omitted -->

  <dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-mongodb</artifactId>
    <version>{version}</version>
  </dependency>

  <dependency>
    <groupId>org.mongodb</groupId>
    <artifactId>mongodb-driver-reactivestreams</artifactId>
    <version>{mongo-reactivestreams}</version>
  </dependency>

  <dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-core</artifactId>
    <version>{reactor}</version>
  </dependency>

</dependencies>
----

NOTE: MongoDB 使用两种不同的驱动来进行阻塞式和响应式（非阻塞式）数据访问。虽然默认提供阻塞操作，但你可以选择加入响应式使用。

为了开始一个工作实例，创建一个简单的 `Person` 类来进行持久化，如下所示。

[source,java]
----
@Document
public class Person {

  private String id;
  private String name;
  private int age;

  public Person(String name, int age) {
    this.name = name;
    this.age = age;
  }

  public String getId() {
    return id;
  }
  public String getName() {
    return name;
  }
  public int getAge() {
    return age;
  }

  @Override
  public String toString() {
    return "Person [id=" + id + ", name=" + name + ", age=" + age + "]";
  }
}
----

然后创建一个应用程序来运行，如下所示:

[source,java]
----
public class ReactiveMongoApp {

  private static final Logger log = LoggerFactory.getLogger(ReactiveMongoApp.class);

  public static void main(String[] args) throws Exception {

    CountDownLatch latch = new CountDownLatch(1);

    ReactiveMongoTemplate mongoOps = new ReactiveMongoTemplate(MongoClients.create(), "database");

    mongoOps.insert(new Person("Joe", 34))
          .flatMap(p -> mongoOps.findOne(new Query(where("name").is("Joe")), Person.class))
          .doOnNext(person -> log.info(person.toString()))
          .flatMap(person -> mongoOps.dropCollection("person"))
          .doOnComplete(latch::countDown)
          .subscribe();

    latch.await();
  }
}
----

运行前面的类产生以下输出:

[source]
----
2016-09-20 14:56:57,373 DEBUG .index.MongoPersistentEntityIndexCreator: 124 - Analyzing class class example.ReactiveMongoApp$Person for index information.
2016-09-20 14:56:57,452 DEBUG .data.mongodb.core.ReactiveMongoTemplate: 975 - Inserting Document containing fields: [_class, name, age] in collection: person
2016-09-20 14:56:57,541 DEBUG .data.mongodb.core.ReactiveMongoTemplate:1503 - findOne using query: { "name" : "Joe"} fields: null for class: class example.ReactiveMongoApp$Person in collection: person
2016-09-20 14:56:57,545 DEBUG .data.mongodb.core.ReactiveMongoTemplate:1979 - findOne using query: { "name" : "Joe"} in db.collection: database.person
2016-09-20 14:56:57,567  INFO                 example.ReactiveMongoApp:  43 - Person [id=57e1321977ac501c68d73104, name=Joe, age=34]
2016-09-20 14:56:57,573 DEBUG .data.mongodb.core.ReactiveMongoTemplate: 528 - Dropped collection [person]
----

即使在这个简单的例子中，也有一些事情需要注意:

* 你可以通过使用标准的 `com.mongodb.reactivestreams.client.MongoClient` 对象和要使用的数据库名称来实例化 Spring Mongo 的中心 helper 类 (<<mongo.reactive.template,`ReactiveMongoTemplate`>>)。
* 该 mapper 针对标准的 POJO 对象工作，不需要任何额外的元数据（尽管你可以选择性地提供这些信息。 见 <<mapping-chapter,这里>>）。
* 惯例用于处理 ID 字段，在数据库中存储时将其转换为 `ObjectId`。
* 映射约定可以使用字段访问。请注意，`Person` 类只有 getter。
* 如果构造函数的参数名与存储文档的字段名相匹配，它们将被用来实例化对象。

有一个 GitHub仓库，https://github.com/spring-projects/spring-data-examples[里面有几个例子] ，你可以下载并玩一玩，感受一下这个库是如何工作的。

[[mongo.reactive.driver]]
== 用 Spring 和 Reactive Streams 驱动连接到 MongoDB

在使用 MongoDB 和 Spring 时，首要任务之一是通过使用 IoC 容器创建一个 `com.mongodb.reactivestreams.client.MongoClient` 对象。

[[mongo.reactive.mongo-java-config]]
=== 使用基于 Java 的元数据注册 MongoClient 实例

下面的例子展示了如何使用基于 Java 的 Bean 元数据来注册 `com.mongodb.reactivestreams.client.MongoClient` 的一个实例。

.使用基于 Java 的 bean 元数据注册一个 `com.mongodb.reactivestreams.client.MongoClient` 对象
====
[source,java]
----
@Configuration
public class AppConfig {

  /*
   * Use the Reactive Streams Mongo Client API to create a com.mongodb.reactivestreams.client.MongoClient instance.
   */
   public @Bean MongoClient reactiveMongoClient()  {
       return MongoClients.create("mongodb://localhost");
   }
}
----
====

这种方法可以让你使用标准的 `com.mongodb.reactivestreams.client.MongoClient` API（你可能已经知道）。

另一种方法是通过使用 Spring 的 `ReactiveMongoClientFactoryBean` 向容器注册 `com.mongodb.reactivestreams.client.MongoClient` 实例。与直接实例化 `com.mongodb.reactivestreams.client.MongoClient` 实例相比， `FactoryBean` 方法还有一个优势，
即为容器提供 `ExceptionTranslator` 实现，该实现可将 `MongoDB` 异常转换为 Spring 的可移植 `DataAccessException` 层次结构中的异常，用于注解有 `@Repository` 的数据访问类。这种层次结构和 `@Repository` 的使用在 https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/data-access.html[Spring 的 DAO 支持功能] 中有所描述。

下面的例子显示了基于 Java 的 Bean 元数据，它支持 `@Repository` 注解的类上的异常翻译。

.使用 Spring 的 `MongoClientFactoryBean` 注册 `com.mongodb.reactivestreams.client.MongoClient` 对象并启用 Spring 的异常翻译支持。
====
[source,java]
----
@Configuration
public class AppConfig {

    /*
     * Factory bean that creates the com.mongodb.reactivestreams.client.MongoClient instance
     */
     public @Bean ReactiveMongoClientFactoryBean mongoClient() {

          ReactiveMongoClientFactoryBean clientFactory = new ReactiveMongoClientFactoryBean();
          clientFactory.setHost("localhost");

          return clientFactory;
     }
}
----
====

要访问由 `ReactiveMongoClientFactoryBean` 在其他 `@Configuration` 或你自己的类中创建的 `com.mongodb.reactivestreams.client.MongoClient` 对象，可从 `context` 中获取 `MongoClient`。

[[mongo.reactive.mongo-db-factory]]
=== ReactiveMongoDatabaseFactory 接口

虽然 `com.mongodb.reactivestreams.client.MongoClient` 是响应式 MongoDB 驱动程序 API 的入口，但连接到特定 MongoDB 数据库实例需要额外的信息，例如数据库名称。有了这些信息，你就可以获得 `com.mongodb.reactivestreams.client.MongoDatabase` 对象并访问特定 MongoDB 数据库实例的所有功能。
Spring 提供了 `org.springframework.data.mongodb.core.ReactiveMongoDatabaseFactory` 接口来引导与数据库的连接。下面的列表显示了 `ReactiveMongoDatabaseFactory` 接口。

[source,java]
----
public interface ReactiveMongoDatabaseFactory {

  /**
   * Creates a default {@link MongoDatabase} instance.
   *
   * @return
   * @throws DataAccessException
   */
  MongoDatabase getMongoDatabase() throws DataAccessException;

  /**
   * Creates a {@link MongoDatabase} instance to access the database with the given name.
   *
   * @param dbName must not be {@literal null} or empty.
   * @return
   * @throws DataAccessException
   */
  MongoDatabase getMongoDatabase(String dbName) throws DataAccessException;

  /**
   * Exposes a shared {@link MongoExceptionTranslator}.
   *
   * @return will never be {@literal null}.
   */
  PersistenceExceptionTranslator getExceptionTranslator();
}
----

`org.springframework.data.mongodb.core.SimpleReactiveMongoDatabaseFactory` 类实现了 `ReactiveMongoDatabaseFactory` 接口，并以标准的 `com.mongodb.reactivestreams.client.MongoClient` 实例和数据库名称创建。

你可以在标准的 Java 代码中使用它们，而不是使用 IoC 容器来创建 `ReactiveMongoTemplate` 的实例，如下所示。

[source,java]
----
public class MongoApp {

  private static final Log log = LogFactory.getLog(MongoApp.class);

  public static void main(String[] args) throws Exception {

    ReactiveMongoOperations mongoOps = new ReactiveMongoOperations(new SimpleReactiveMongoDatabaseFactory(MongoClient.create(), "database"));

    mongoOps.insert(new Person("Joe", 34))
        .flatMap(p -> mongoOps.findOne(new Query(where("name").is("Joe")), Person.class))
        .doOnNext(person -> log.info(person.toString()))
        .flatMap(person -> mongoOps.dropCollection("person"))
        .subscribe();
  }
}
----

使用 `SimpleReactiveMongoDatabaseFactory` 是 <<mongodb-reactive-getting-started,入门部分>> 所示清单的唯一区别。

[[mongo.reactive.mongo-db-factory-java]]
=== 通过使用基于 Java 的元数据注册 `ReactiveMongoDatabaseFactory` 实例

为了在容器中注册一个 `ReactiveMongoDatabaseFactory` 实例，你可以编写与前面代码清单中强调的差不多的代码，如下例所示。

[source,java]
----
@Configuration
public class MongoConfiguration {

  public @Bean ReactiveMongoDatabaseFactory reactiveMongoDatabaseFactory() {
    return new SimpleReactiveMongoDatabaseFactory(MongoClients.create(), "database");
  }
}
----

为了定义用户名和密码，创建一个 MongoDB 连接字符串并将其传入工厂方法，正如下一个列表所示。下面的清单还显示了如何使用 `ReactiveMongoDatabaseFactory` 来向容器注册 `ReactiveMongoTemplate` 的实例。

[source,java]
----
@Configuration
public class MongoConfiguration {

  public @Bean ReactiveMongoDatabaseFactory reactiveMongoDatabaseFactory() {
    return new SimpleReactiveMongoDatabaseFactory(MongoClients.create("mongodb://joe:secret@localhost"), "database");
  }

  public @Bean ReactiveMongoTemplate reactiveMongoTemplate() {
    return new ReactiveMongoTemplate(reactiveMongoDatabaseFactory());
  }
}
----

[[mongo.reactive.template]]
== `ReactiveMongoTemplate` 简介

位于 `org.springframework.data.mongodb` 包中的 `ReactiveMongoTemplate` 类是 Spring 的 Reactive MongoDB 支持的中心类，它提供了丰富的功能集来与数据库交互。该模板提供了创建、更新、删除和查询 MongoDB 文档的便利操作，并提供了你的 domain 对象和 MongoDB 文档之间的映射。

NOTE: 一旦配置好，`ReactiveMongoTemplate` 是线程安全的，可以在多个实例中重复使用。

MongoDB 文档和 domain 类之间的映射是通过委托给 `MongoConverter` 接口的实现完成的。Spring 提供了 `MongoMappingConverter` 的默认实现，但你也可以编写自己的转换器。更详细的信息请参见 <<mongo.custom-converters,MongoConverter 实例部分>>。

`ReactiveMongoTemplate` 类实现了 `ReactiveMongoOperations` 接口。 `ReactiveMongoOperations` 上的方法尽可能地反映了 MongoDB 驱动 `Collection` 对象上的方法，以使习惯于驱动 API 的现有 MongoDB 开发人员熟悉该 API。
例如，你可以找到诸如 `find`、`findAndModify`、`findOne`、`insert`、`remove`、`save`、`update` 和 `updateMulti` 等方法。设计目标是使其尽可能容易地在使用基本 MongoDB 驱动和 `ReactiveMongoOperations` 之间过渡。
这两个 API 之间的主要区别是，`ReactiveMongoOperations` 可以传递 domain 对象而不是 `Document`，而且 `Query`、`Criteria` 和 `Update` 操作有 fluent API，
而不是通过填充 `Document` 来指定这些操作的参数。

NOTE: 引用 `ReactiveMongoTemplate` 实例上的操作的首选方式是通过其 `ReactiveMongoOperations` 接口。

`ReactiveMongoTemplate` 使用的默认转换器实现是 `MappingMongoConverter`。虽然 `MappingMongoConverter` 可以使用额外的元数据来指定对象到文档的映射，但它也可以通过使用一些惯例来转换 ID 和集合名称的映射，从而转换不包含额外元数据的对象。这些约定以及映射注解的使用在 <<mapping-chapter,映射一章>> 中进行了解释。

`ReactiveMongoTemplate` 的另一个核心功能是将 MongoDB Java 驱动中抛出的异常转换为 Spring 的可移植数据访问异常（Data Access Exception）层次结构。更多信息请参见 <<mongo.exception,异常转换>> 部分。

`ReactiveMongoTemplate` 上有许多便利方法，可以帮助你轻松地执行常见的任务。然而，如果你需要直接访问 MongoDB 驱动程序 API，以访问 MongoTemplate 没有明确暴露的功能，你可以使用几个 execute 回调方法之一来访问底层驱动程序 API。`execute` 回调给你一个对 `com.mongodb.reactivestreams.client.MongoCollection` 或 `com.mongodb.reactivestreams.client.MongoDatabase` 对象的引用。参见 <<mongo.reactive.executioncallback,Execution 回调>>  以了解更多信息。

[[mongo.reactive.template.instantiating]]
=== 实例化 ReactiveMongoTemplate

你可以使用 Java 来创建和注册 `ReactiveMongoTemplate` 的实例，如下所示。

.注册 `com.mongodb.reactivestreams.client.MongoClient` 对象并启用 Spring 的异常转换支持。
====
[source,java]
----
@Configuration
public class AppConfig {

  public @Bean MongoClient reactiveMongoClient() {
      return MongoClients.create("mongodb://localhost");
  }

  public @Bean ReactiveMongoTemplate reactiveMongoTemplate() {
      return new ReactiveMongoTemplate(reactiveMongoClient(), "mydatabase");
  }
}
----
====

`ReactiveMongoTemplate` 有几个重载构造函数，包括:

* `ReactiveMongoTemplate(MongoClient mongo, String databaseName)`: 接受 `com.mongodb.reactivestreams.client.MongoClient` 对象和默认的数据库名称来进行操作。
* `ReactiveMongoTemplate(ReactiveMongoDatabaseFactory mongoDatabaseFactory)`: 接收一个封装了 `com.mongodb.reactivestreams.client.MongoClient` 对象和数据库名称的 `ReactiveMongoDatabaseFactory` 对象。
* `ReactiveMongoTemplate(ReactiveMongoDatabaseFactory mongoDatabaseFactory, MongoConverter mongoConverter)`: 添加一个用于映射的 `MongoConverter`。

创建 `ReactiveMongoTemplate` 时，你可能还想设置以下属性:

* `WriteResultCheckingPolicy`
* `WriteConcern`
* `ReadPreference`

NOTE: 引用 `ReactiveMongoTemplate` 实例上的操作的首选方式是通过其 `ReactiveMongoOperations` 接口。

[[mongo.reactive.template.writeresultchecking]]
=== `WriteResultChecking` 策略

在开发过程中，如果从任何 MongoDB 操作返回的 `com.mongodb.WriteResult` 包含一个错误，那么记录或抛出一个异常是很方便的。在开发过程中，忘记这样做是很常见的，然后最终得到一个看起来运行成功的应用程序，而事实上，
数据库并没有按照你的预期进行修改。将 MongoTemplate `WriteResultChecking` 属性设置为一个枚举，其值为：`LOG`、`EXCEPTION` 或 `NONE`，以记录错误、抛出异常或不做任何事情。默认是使用 `NONE` 的 `WriteResultChecking` 值。

[[mongo.reactive.template.writeconcern]]
=== `WriteConcern`

如果尚未通过驱动程序在更高层次（如 `MongoDatabase`）上指定，你可以设置 `ReactiveMongoTemplate` 用于写操作的 `com.mongodb.WriteConcern` 属性。如果 `ReactiveMongoTemplate` 的 `WriteConcern` 属性未被设置，
则默认为 MongoDB 驱动程序的 `MongoDatabase` 或 `MongoCollection` 设置中的设置。

[[mongo.reactive.template.writeconcernresolver]]
=== `WriteConcernResolver`

对于更高级的情况，即你想在每个操作的基础上设置不同的 `WriteConcern` 值（对于删除、更新、插入和保存操作），可以在 `ReactiveMongoTemplate` 上配置一个叫做 `WriteConcernResolver` 的策略接口。由于 `ReactiveMongoTemplate` 是用来持久化 POJO 的，`WriteConcernResolver` 让你创建一个策略，可以将特定的 POJO 类映射到 `WriteConcern` 值。下面的列表显示了 `WriteConcernResolver` 的接口。

[source,java]
----
public interface WriteConcernResolver {
  WriteConcern resolve(MongoAction action);
}
----

参数 `MongoAction` 决定了要使用的 `WriteConcern` 值以及是否使用模板本身的值作为默认值。`MongoAction` 包含被写入的集合名称、POJO 的 `java.lang.Class`、转换后的 `DBObject`、作为 `MongoActionOperation` 枚举值的操作（`REMOVE`、`UPDATE`、`INSERT`、`INSERT_LIST` 和 `SAVE` 之一）以及其他一些上下文信息。下面的例子显示了如何创建一个 `WriteConcernResolver`。

[source]
----
private class MyAppWriteConcernResolver implements WriteConcernResolver {

  public WriteConcern resolve(MongoAction action) {
    if (action.getEntityClass().getSimpleName().contains("Audit")) {
      return WriteConcern.NONE;
    } else if (action.getEntityClass().getSimpleName().contains("Metadata")) {
      return WriteConcern.JOURNAL_SAFE;
    }
    return action.getDefaultWriteConcern();
  }
}
----


[[mongo.reactive.template.save-update-remove]]
== 保存、更新和删除文档

`ReactiveMongoTemplate` 让你可以保存、更新和删除你的 domain 对象，并将这些对象映射到存储在 MongoDB 中的文档。

考虑以下 `Person` 类。

[source,java]
----
public class Person {

  private String id;
  private String name;
  private int age;

  public Person(String name, int age) {
    this.name = name;
    this.age = age;
  }

  public String getId() {
    return id;
  }
  public String getName() {
    return name;
  }
  public int getAge() {
    return age;
  }

  @Override
  public String toString() {
    return "Person [id=" + id + ", name=" + name + ", age=" + age + "]";
  }

}
----

下面的列表显示了你如何保存、更新和删除 `Person` 对象。

[source,java]
----
public class ReactiveMongoApp {

  private static final Logger log = LoggerFactory.getLogger(ReactiveMongoApp.class);

  public static void main(String[] args) throws Exception {

    CountDownLatch latch = new CountDownLatch(1);

    ReactiveMongoTemplate mongoOps = new ReactiveMongoTemplate(MongoClients.create(), "database");

    mongoOps.insert(new Person("Joe", 34)).doOnNext(person -> log.info("Insert: " + person))
      .flatMap(person -> mongoOps.findById(person.getId(), Person.class))
      .doOnNext(person -> log.info("Found: " + person))
      .zipWith(person -> mongoOps.updateFirst(query(where("name").is("Joe")), update("age", 35), Person.class))
      .flatMap(tuple -> mongoOps.remove(tuple.getT1())).flatMap(deleteResult -> mongoOps.findAll(Person.class))
      .count().doOnSuccess(count -> {
        log.info("Number of people: " + count);
        latch.countDown();
      })

      .subscribe();

    latch.await();
  }
}
----

前面的例子包括存储在数据库中的 `String` 和 `ObjectId` 之间的隐式转换（通过使用 `MongoConverter`），并认识到属性 `Id` 名称的惯例。

NOTE: 前面的例子是为了展示在 `ReactiveMongoTemplate` 上使用 `save`、`update` 和 `remove` 操作，而不是为了展示复杂的映射或链式功能。

"`<<mongo.query,Querying Documents>>`" 更详细地解释了前面的例子中使用的查询语法。其他文档可以在 <<mongo-template, 阻塞式 `MongoTemplate`>>  部分找到。

[[mongo.reactive.executioncallback]]
== Execution 回调

所有 Spring template 类的一个共同设计特点是，所有功能都被路由到运行回调方法的模板之一。这有助于确保异常和任何可能需要的资源管理的执行一致性。虽然这在 JDBC 和 JMS 的情况下比在 MongoDB 的情况下更有必要，
但它仍然提供了一个发生异常转换和记录的单一地点。因此，使用 `execute` 回调是访问 MongoDB 驱动程序的 `MongoDatabase` 和 `MongoCollection` 对象的首选方式，
以执行未在 `ReactiveMongoTemplate` 上作为方法公开的不常见操作。

这里有一个 `execute` 回调方法的列表。

* `<T> Flux<T>` *execute* `(Class<?> entityClass, ReactiveCollectionCallback<T> action)`: 为指定类别的实体集合运行给定的 `ReactiveCollectionCallback`。

* `<T> Flux<T>` *execute* `(String collectionName, ReactiveCollectionCallback<T> action)`: 在给定名称的集合上运行给定的 `ReactiveCollectionCallback`。

* `<T> Flux<T>` *execute* `(ReactiveDatabaseCallback<T> action)`: 运行一个 `ReactiveDatabaseCallback`，必要时转换任何异常。

下面的例子使用 `ReactiveCollectionCallback` 来返回关于一个索引的信息。

[source,java]
----
Flux<Boolean> hasIndex = operations.execute("geolocation",
    collection -> Flux.from(collection.listIndexes(Document.class))
      .filter(document -> document.get("name").equals("fancy-index-name"))
      .flatMap(document -> Mono.just(true))
      .defaultIfEmpty(false));
----

[[reactive.gridfs]]
== GridFS 支持

MongoDB 支持在其文件系统 GridFS 内存储二进制文件。Spring Data MongoDB 提供了一个 `ReactiveGridFsOperations` 接口以及相应的实现，即 `ReactiveGridFsTemplate`，让你与文件系统互动。你可以通过将 `ReactiveMongoDatabaseFactory` 以及 `MongoConverter` 交给它来设置一个 `ReactiveGridFsTemplate` 实例，如下例所示。

.为 `ReactiveGridFsTemplate` 设置 `JavaConfig`
====
[source,java]
----
class GridFsConfiguration extends AbstractReactiveMongoConfiguration {

  // … further configuration omitted

  @Bean
  public ReactiveGridFsTemplate reactiveGridFsTemplate() {
    return new ReactiveGridFsTemplate(reactiveMongoDbFactory(), mappingMongoConverter());
  }
}
----
====

现在，该 template 可以被注入并用于执行存储和检索操作，如下例所示。

.使用 `ReactiveGridFsTemplate` 来存储文件
====
[source,java]
----
class ReactiveGridFsClient {

  @Autowired
  ReactiveGridFsTemplate operations;

  @Test
  public Mono<ObjectId> storeFileToGridFs() {

    FileMetadata metadata = new FileMetadata();
    // populate metadata
    Publisher<DataBuffer> file = … // lookup File or Resource

    return operations.store(file, "filename.txt", metadata);
  }
}
----
====

`store(…)` 操作接收一个 `Publisher<DataBuffer>`、一个文件名以及（可选）关于要存储的文件的元数据信息。元数据可以是一个任意的对象，它将被配置有 `ReactiveGridFsTemplate` 的 `MongoConverter` 所处理。另外，你也可以提供一个 `Document`。

NOTE: MongoDB 的驱动程序使用 `AsyncInputStream` 和 `AsyncOutputStream` 接口来交换二进制流。Spring Data MongoDB 将这些接口调整为 `Publisher<DataBuffer>`。在 https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#databuffers[Spring 的参考文档] 中阅读更多关于 `DataBuffer` 的信息。

你可以通过 `find(…)` 或 `getResources(…)` 方法从文件系统中读取文件。让我们先看一下 `find(…)` 方法。你可以找到一个文件，也可以找到符合查询条件的多个文件。你可以使用 `GridFsCriteria` helper 类来定义查询。它提供了静态的工厂方法来封装默认的元数据字段（如 `whereFilename()` 和 `whereContentType()`），或者通过 `whereMetaData()` 封装一个自定义的元数据。下面的例子显示了如何使用 `ReactiveGridFsTemplate` 来查询文件。

.使用 `ReactiveGridFsTemplate` 来查询文件
====
[source,java]
----
class ReactiveGridFsClient {

  @Autowired
  ReactiveGridFsTemplate operations;

  @Test
  public Flux<GridFSFile> findFilesInGridFs() {
    return operations.find(query(whereFilename().is("filename.txt")))
  }
}
----
====

NOTE: 目前，MongoDB 不支持在从 GridFS 检索文件时定义排序标准。出于这个原因，任何定义在 `Query` 实例上的排序 criteria 都会被忽略，而这些排序标准会被交给 `find(…)` 方法来处理。


从GridFs读取文件的另一个选择是使用沿着 `ResourcePatternResolver` 的思路建模的方法。`ReactiveGridFsOperations` 使用响应式类型来推迟运行，而 `ResourcePatternResolver` 使用同步接口。这些方法允许将 Ant 路径交到方法中，从而可以检索到与给定模式（pattern）相匹配的文件。
下面的例子显示了如何使用 `ReactiveGridFsTemplate` 来读取文件。

.使用 `ReactiveGridFsTemplate` 来读取文件
====
[source,java]
----
class ReactiveGridFsClient {

  @Autowired
  ReactiveGridFsOperations operations;

  @Test
  public void readFilesFromGridFs() {
     Flux<ReactiveGridFsResource> txtFiles = operations.getResources("*.txt");
  }
}
----
====
