[[sharding]]
= 分片

MongoDB 通过分片支持大型数据集，这是一种将数据分布在多个数据库服务器上的方法。请参考 https://docs.mongodb.com/manual/sharding/[MongoDB Documentation]，了解如何设置分片集群、其要求和限制。

Spring Data MongoDB 使用 `@Sharded` 注解来识别存储在 sharded 集合中的实体，如下图所示。

====
[source,java]
----
@Document("users")
@Sharded(shardKey = { "country", "userId" }) <1>
public class User {

	@Id
	Long id;

	@Field("userid")
	String userId;

	String country;
}
----
<1> shardKey 的属性会被映射到实际的字段名。
====

[[sharding.sharded-collections]]
== 集合的分片

Spring Data MongoDB 不会自动设置集合的分片，也不会设置所需的索引。下面的片段显示了如何使用 MongoDB 客户端 API 来实现这一目的。

====
[source,java]
----
MongoDatabase adminDB = template.getMongoDbFactory()
    .getMongoDatabase("admin");                                     <1>

adminDB.runCommand(new Document("enableSharding", "db"));           <2>

Document shardCmd = new Document("shardCollection", "db.users")     <3>
	.append("key", new Document("country", 1).append("userid", 1)); <4>

adminDB.runCommand(shardCmd);
----
<1> 分片命令需要针对 admin 数据库运行。
<2> 如有必要，为特定的数据库启用分片。
<3> 分片是数据库中启用了分片的集合。
<4> 指定分片 key。这个例子使用基于 `range` 的分片。
====

[[sharding.shard-key]]
== 分片 key 处理

分片 key 由一个或多个属性组成，这些属性必须存在于目标集合中的每个文档中。它被用来在不同的分片中分配文档。

将 `@Sharded` 注解添加到实体中，使 Spring Data MongoDB 能够应用分片场景所需的最佳努力优化。这意味着在上传实体时，如果尚未存在的话，基本上可以将所需的分片 key 信息添加到 `replaceOne` 过滤器查询中。
这可能需要一个额外的服务器往返，以确定当前分片 key 的实际值。


TIP: 通过设置 `@Sharded(immutableKey = true)`，Spring Data 不会试图检查一个实体的分片 key 是否被改变。

请参阅 https://docs.mongodb.com/manual/reference/method/db.collection.replaceOne/#upsert[MongoDB Documentation] 以了解更多细节。下面的列表包含了哪些操作有资格被分片 key 自动包含。

* `(Reactive)CrudRepository.save(…)`
* `(Reactive)CrudRepository.saveAll(…)`
* `(Reactive)MongoTemplate.save(…)`





