// carry over the old bookmarks to prevent external links from failing
[[tailable-cursors]]
== [[mongo.reactive.repositories.infinite-streams]] 具有可追踪游标的无限流

默认情况下，当客户端用完游标提供的所有结果时，MongoDB 会自动关闭游标。在耗尽时关闭游标会使流变成一个有限的流。对于 https://docs.mongodb.com/manual/core/capped-collections/[有上限的集合] ，你可以使用一个 https://docs.mongodb.com/manual/core/tailable-cursors/[Tailable Cursor]，
它在客户端消耗了所有最初返回的数据后仍然保持开放。

TIP: 可以用 `MongoOperations.createCollection` 来创建有上限的集合。要做到这一点，提供所需的 `CollectionOptions.empty().capped()...`.

可跟踪的游标可以通过强制性的和反应性的 MongoDB API 来使用。强烈建议使用响应式风格，因为它的资源密集度较低。然而，如果你不能使用响应式 API，你仍然可以使用 Spring 生态系统中已经普遍存在的消息传递概念。

[[tailable-cursors.sync]]
=== 使用 `MessageListener` 的可追踪游标

使用同步驱动监听一个有上限的集合会产生一个长期运行的、阻塞的任务，需要委托给一个单独的组件。在这种情况下，我们需要首先创建一个 `MessageListenerContainer`，
它将是运行特定的 `SubscriptionRequest` 的主要入口点。Spring Data MongoDB 已经提供了一个默认的实现，它在 `MongoTemplate` 上运行，能够为 `TailableCursorRequest` 创建和运行 `Task` 实例。

下面的例子显示了如何用 `MessageListener` 实例来使用可跟踪的游标。

.具有 `MessageListener` 实例的可跟踪游标
====
[source,java]
----
MessageListenerContainer container = new DefaultMessageListenerContainer(template);
container.start();                                                                  <1>

MessageListener<Document, User> listener = System.out::println;                     <2>

TailableCursorRequest request = TailableCursorRequest.builder()
  .collection("orders")                                                             <3>
  .filter(query(where("value").lt(100)))                                            <4>
  .publishTo(listener)                                                              <5>
  .build();

container.register(request, User.class);                                            <6>

// ...

container.stop();                                                                   <7>
----
<1> 启动容器会启动资源并为已经注册的 `SubscriptionRequest` 实例启动 Task 实例。启动后添加的请求会立即运行。
<2> 定义当收到一个 `Message` 时被调用的监听器。`Message#getBody()` 被转换为请求的 domain 类型。使用 `Document` 来接收未经转换的原始结果。
<3> 设置要听的集合。
<4> 为要接收的文档提供一个可选的过滤器。
<5> 设置消息监听器来发布传入的 `Message`。
<6> 注册该请求。返回的 `Subscription` 可以用来检查当前的 `Task` 状态，并取消它以释放资源。
<7> 一旦你确定你不再需要这个容器，不要忘记停止它。这样做可以停止容器内所有正在运行的 Task 实例。
====

[[tailable-cursors.reactive]]
=== 响应式可跟踪游标

使用具有响应式数据类型的可跟踪游标可以构建无限的流。一个可跟踪的游标保持开放，直到它被外部关闭。当新的文档到达一个封顶的集合时，它就会释放出数据。

如果查询没有返回匹配，或者游标在集合的 "末端" 返回文档，而应用程序随后删除了该文档，那么可跟踪的游标可能会变成死的，或无效的。下面的例子显示了如何创建和使用一个无限流查询。

.使用 ReactiveMongoOperations 的无限流查询
====
[source,java]
----
Flux<Person> stream = template.tail(query(where("name").is("Joe")), Person.class);

Disposable subscription = stream.doOnNext(person -> System.out.println(person)).subscribe();

// …

// Later: Dispose the subscription to close the stream
subscription.dispose();
----
====

Spring Data MongoDB 响应式 repository 通过用 `@Tailable` 注解查询方法来支持无限的流。这适用于返回 `Flux` 和其他能够发出多个元素的响应式类型的方法，如下例所示。

.使用 ReactiveMongoRepository 的无限流查询
====
[source,java]
----

public interface PersonRepository extends ReactiveMongoRepository<Person, String> {

  @Tailable
  Flux<Person> findByFirstname(String firstname);

}

Flux<Person> stream = repository.findByFirstname("Joe");

Disposable subscription = stream.doOnNext(System.out::println).subscribe();

// …

// Later: Dispose the subscription to close the stream
subscription.dispose();
----
====
