[[unwrapped-entities]]
== 解构的类型

解构的实体用于在你的 Java domain 模型中设计 value 对象，其属性被平铺到父方的 MongoDB 文档中。

[[unwrapped-entities.mapping]]
=== 解构类型映射

考虑以下 domain 模型，其中 `User.name` 被注解为 `@Unwrapped`。`@Unwrapped` 注解预示着 `UserName` 的所有属性应该被平铺到拥有 `name` 属性的 `user` 文档中。

.解构对象的示例代码
====
[source,java]
----
class User {

    @Id
    String userId;

    @Unwrapped(onEmpty = USE_NULL) <1>
    UserName name;
}

class UserName {

    String firstname;

    String lastname;

}
----

[source,json]
----
{
  "_id" : "1da2ba06-3ba7",
  "firstname" : "Emma",
  "lastname" : "Frost"
}
----
<1> 当加载 `name` 属性时，如果 `firstname` 和 `lastname` 都是 `null` 的或不存在，其值将被设置为 `null`。通过使用 `onEmpty=USE_EMPTY`，一个空的 `UserName` 将被创建，其属性值可能为 `null`。
====

对于不那么冗长的可嵌入类型声明，请使用 `@Unwrapped.Nullable` 和 `@Unwrapped.Empty` 来代替 `@Unwrapped(onEmpty = USE_NULL)` 和 `@Unwrapped(onEmpty = USE_EMPTY)` 。
这两个注解都用 JSR-305 的 `@javax.annotation.Nonnull` 进行了元注解，以帮助进行无效性检查。

[WARNING]
====
在一个解构的对象中使用复杂类型是可能的。但是，这些类型本身不能是，也不能包含解构的字段。
====

[[unwrapped-entities.mapping.field-names]]
=== 解构的类型字段名

通过使用 `@Unwrapped` 注解的可选 `prefix` 属性，一个值对象可以被多次解构。通过这样做，所选择的前缀会被前置到解构对象中的每个属性或 `@Field("…")` 名称上。请注意，如果多个属性渲染到相同的字段名，值将相互覆盖。

.带有名称前缀的解构对象的示例代码
====
[source,java]
----
class User {

    @Id
    String userId;

    @Unwrapped.Nullable(prefix = "u_") <1>
    UserName name;

    @Unwrapped.Nullable(prefix = "a_") <2>
    UserName name;
}

class UserName {

    String firstname;

    String lastname;
}
----

[source,json]
----
{
  "_id" : "a6a805bd-f95f",
  "u_firstname" : "Jean",             <1>
  "u_lastname" : "Grey",
  "a_firstname" : "Something",        <2>
  "a_lastname" : "Else"
}
----
<1> `UserName` 的所有属性都以 `u_` 为前缀。
<2> `UserName` 的所有属性都以 `a_` 为前缀。
====

而在同一个属性上将 `@Field` 注解和 `@Unwrapped` 结合起来是没有意义的，因此会导致错误。在任何一个解构类型的属性上使用 `@Field` 是一个完全有效的方法。

.使用 `@Field` 注解解构对象的示例代码
====
[source,java]
----
public class User {

	@Id
    private String userId;

    @Unwrapped.Nullable(prefix = "u-") <1>
    UserName name;
}

public class UserName {

	@Field("first-name")              <2>
    private String firstname;

	@Field("last-name")
    private String lastname;
}
----

[source,json]
----
{
  "_id" : "2647f7b9-89da",
  "u-first-name" : "Barbara",         <2>
  "u-last-name" : "Gordon"
}
----
<1> `UserName` 的所有属性都以 `u-` 为前缀。
<2> 最终的字段名是 `@Unwrapped(prefix)` 和 `@Field(name)` 连接的结果。
====

[[unwrapped-entities.queries]]
=== 对解构的对象进行查询

在类型和字段级别上可以定义对解构的属性的查询，因为提供的 `Criteria` 与 domain 类型相匹配。前缀和潜在的自定义字段名在渲染实际查询时将被考虑。使用解构对象的属性名称与所有包含的字段进行匹配，如下面的例子所示。

.对解构的对象进行查询
====
[source,java]
----
UserName userName = new UserName("Carol", "Danvers")
Query findByUserName = query(where("name").is(userName));
User user = template.findOne(findByUserName, User.class);
----

[source,json]
----
db.collection.find({
  "firstname" : "Carol",
  "lastname" : "Danvers"
})
----
====

也可以直接使用其属性名称来寻址解构对象的任何字段，如下面的片段所示。

.对解构的对象的字段进行查询
====
[source,java]
----
Query findByUserFirstName = query(where("name.firstname").is("Shuri"));
List<User> users = template.findAll(findByUserFirstName, User.class);
----

[source,json]
----
db.collection.find({
  "firstname" : "Shuri"
})
----
====

[[unwrapped-entities.queries.sort]]
==== 按解构的字段排序

解除包装的对象的字段可以通过其属性路径用于排序，如下面的例子所示。

.对解构的字段进行排序
====
[source,java]
----
Query findByUserLastName = query(where("name.lastname").is("Romanoff"));
List<User> user = template.findAll(findByUserName.withSort(Sort.by("name.firstname")), User.class);
----

[source,json]
----
db.collection.find({
  "lastname" : "Romanoff"
}).sort({ "firstname" : 1 })
----
====

[NOTE]
====
尽管有可能，但使用解构对象本身作为排序标准包括其所有字段的不可预测的顺序，并可能导致不准确的排序。
====

[[unwrapped-entities.queries.project]]
==== 解构对象的字段投影

解构的对象的字段可以作为一个整体或通过单个字段进行投影，如下面的示例所示。

.解构对象的投影
====
[source,java]
----
Query findByUserLastName = query(where("name.firstname").is("Gamora"));
findByUserLastName.fields().include("name");                             <1>
List<User> user = template.findAll(findByUserName, User.class);
----

[source,json]
----
db.collection.find({
  "lastname" : "Gamora"
},
{
  "firstname" : 1,
  "lastname" : 1
})
----
<1> 在一个解构的对象上的字段投影包括其所有的属性。
====

.投影在一个解构的对象的字段上
====
[source,java]
----
Query findByUserLastName = query(where("name.lastname").is("Smoak"));
findByUserLastName.fields().include("name.firstname");                   <1>
List<User> user = template.findAll(findByUserName, User.class);
----

[source,json]
----
db.collection.find({
  "lastname" : "Smoak"
},
{
  "firstname" : 1
})
----
<1> 在一个解构的对象上的字段投影包括其所有的属性。
====

[[unwrapped-entities.queries.by-example]]
==== 对解构的对象进行 Example 查询

解构的对象可以像其他类型的对象一样，在一个 `Example` probe 中使用。请查看 <<query-by-example.running,Query By Example>> 部分，以了解更多关于这一功能的信息。

[[unwrapped-entities.queries.repository]]
==== Repository 对解构对象的查询

`Repository` 抽象允许衍生出对解构对象的字段以及整个对象的查询。

.Repository 对解构对象的查询。
====
[source,java]
----
interface UserRepository extends CrudRepository<User, String> {

	List<User> findByName(UserName username);         <1>

	List<User> findByNameFirstname(String firstname); <2>
}
----
<1> 与解构对象的所有字段相匹配。
<2> 与 `firstname` 相匹配。。
====

[NOTE]
====
即使 repository 的 `create-query-indexes` 命名空间属性被设置为 `true`，也会暂停创建解构对象的索引。
====

[[unwrapped-entities.update]]
=== 解构对象的更新

解构的对象可以像任何其他属于domain模型的对象一样被更新。映射层负责将结构平铺到其周围环境中。如下面的例子所示，可以更新解构对象的单个属性，也可以更新整个值。

.更新一个解构的对象的单个字段。
====
[source,java]
----
Update update = new Update().set("name.firstname", "Janet");
template.update(User.class).matching(where("id").is("Wasp"))
   .apply(update).first()
----

[source,json]
----
db.collection.update({
  "_id" : "Wasp"
},
{
  "$set" { "firstname" : "Janet" }
},
{ ... }
)
----
====

.更新一个解构对象。
====
[source,java]
----
Update update = new Update().set("name", new Name("Janet", "van Dyne"));
template.update(User.class).matching(where("id").is("Wasp"))
   .apply(update).first()
----

[source,json]
----
db.collection.update({
  "_id" : "Wasp"
},
{
  "$set" {
    "firstname" : "Janet",
    "lastname" : "van Dyne",
  }
},
{ ... }
)
----
====

[[unwrapped-entities.aggregations]]
=== 对解构对象进行聚合

<<mongo.aggregation,Aggregation Framework>> 将尝试映射类型聚合的解构值。在引用其中一个值时，请确保与包括 wrapper 对象在内的属性路径一起工作。除此以外，不需要特别的操作。

[[unwrapped-entities.indexes]]
=== 解构对象的索引

我们可以将 `@Indexed` 注解附加到解构类型的属性上，就像对普通对象那样。不可能在拥有的属性上同时使用 `@Indexed` 和 `@Unwrapped` 注解。

====
[source,java]
----
public class User {

	@Id
    private String userId;

    @Unwrapped(onEmpty = USE_NULL)
    UserName name;                    <1>

    // Invalid -> InvalidDataAccessApiUsageException
    @Indexed                          <2>
    @Unwrapped(onEmpty = USE_Empty)
    Address address;
}

public class UserName {

    private String firstname;

    @Indexed
    private String lastname;           <1>
}
----
<1> 在 `users` 集合中为 `lastname` 创建索引。
<2> 无效的 `@Indexed` 和 `@Unwrapped` 一起使用。
====


