= 如何向 Jcohy Docs 贡献代码

Jcohy Docs 是在 Apache 2.0 许可证下发布。如果你想贡献一些东西，或者只是想修改代码，这个文档应该可以帮助到你。

== 行为准则

该项目的贡献者需要遵守以下行为准则: link:CODE_OF_CONDUCT.adoc[code of conduct].
如果有特殊情况，请将特殊的情况报告给 jia_chao23@126.com.

== 使用 GitHub Issues

我们使用 GitHub Issues 来对问题进行跟踪和改进。如果您要报告问题，或者有新的建议或意见，请在 https://github.com/jcohy/jcohy-gradle-plugins/issues[Github Issues] 上汇报问题。

关于新增功能或增强功能，请详细描述您的意向，以便我们能更好的理解您的想法。

如果您发现了一些 Bug，请尽可能的提供更多的关于问题的详细信息，最好能可以提供一个可以重现问题的小 Demo。

== 如何贡献代码

=== 讨论

如果你认为存在一个问题，通过一些不同的方法来搜索现有的 https://github.com/jcohy/jcohy-gradle-plugins/issues[issues]，找到过去或现在与该问题相关的讨论。阅读这些讨论可以帮助你了解这个问题，并帮助我们做出决定。

=== 创建一个 Issues

报告问题或提出功能请求是一种很好的贡献方式。您的反馈和由此产生的讨论会为我们提供源源不断的想法。但是，在创建正式的 ticket 之前，让我们先花些时间讨论和研究。

待一切准备好后，可以在 Github 上创建一个 issue

=== Issue 生命周期

首次创建 issue 时，它会自动被标记为 waiting-for-triage (等待分类)，等待团队成员对其进行分类。在问题被审核后，团队可能会需要您提供提供更多的详细信息，并根据调查结果为问题分配目标里程碑或以特殊的状态关闭。

在修复了这个问题之后，此 issue 将被关闭，但是在修复发布之前可能仍会重新打开。之后，该问题通常将不再重新打开。在极少数情况下，如果问题根本没有解决，问题可能会重新打开。然而，在大多数情况下，任何后续的报告都需要创建具有新描述的新问题。

=== 提交一个 Pull Request

. 你应该先创建一个 issue 吗？不需要，您只需要创建  pull request 通过一些文字描述来提供上下文和动机，就像处理问题一样。如果您想先开始讨论或已经创建了一个问题，一旦创建了  pull request，我们将关闭该问题，并由  pull request 取代，关于该问题的讨论将在 pull request 下继续。
. 始终检查主分支并针对它提交 pull requests （目标版本参见 settings.gradle）。将根据具体情况考虑向后移植到先前版本，并在问题跟踪器中反映为修复版本。
. 有意识地选择提交的粒度，压缩同一逻辑更改的多次编辑或更正的提交。有关简化提交历史的概述，请参阅 https://git-scm.com/book/en/Git-Tools-Rewriting-History[Pro Git] 中 Rewriting History  一节。
. 格式化提交信息，在主题的一行使用 55 个字符，描述每行为 72 个字符，然后是问题修复，例如. Closes gh-22276。 请参阅 https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#Commit-Guidelines[Pro Git] 的 Commit Guidelines 部分，以便在提交消息周围的最佳实践，并使用 `git log` 查看一些示例。
. 如果有之前的问题，请在拉取请求的描述中引用 GitHub 问题编号。
. 如果请求被接受，您的贡献可能会在合并之前根据需要进行大量修改。如果您的大部分更改保持不变，您可能会保留 Git 提交的作者归属。您也可能会被要求重新提交。
. 如果要求进行更正，只需将更改推送到同一分支，您的拉取请求就会更新。换句话说，当被要求进行更改时，您不需要创建新的拉取请求。

=== 参与评论
帮助审查拉取请求是另一种很好的贡献方式。您的反馈有助于塑造新功能的实现。但是，在审查拉取请求时，除非您是 Jcohy Team 的核心提交者，否则请不要批准或拒绝 PR。

== 构建源码

=== 从源码构建
Jcohy Docs 的源码可以使用 Gradle 的命令行构建。我们在项目中包含了 Gradle’s wrapper scripts (./gradlew 或 gradlew.bat)，这样您可以不用下载安装 Gradle 也可以在本地构建。

Jcohy Plugins 是基于 JDK 1.8 编写的。您应该使用 HotSpot JVM JDK 1.8 或更高的版本构建.

=== 构建参考文档

项目的参考文档也在此项目中，每个项目的下面的 `src/docs/asciidoc`。我们使用 https://asciidoctor.org/docs/asciidoc-writers-guide/[Asciidoc]，您可以使用以下命令在本地构建文档：

[indent=0]
----
$ ./gradlew asciidoc asciidocPdf -Dfile.encoding=UTF-8
----

[NOTE]
====
生成的 HTML , Api Doc 和 PDF 文档在每个项目的 `/build/docs/` 目录中对应的文件夹中。
====

=== 构建指定项目的文档

==== 构建 html 文档

[indent=0]
----
$  ./gradlew clean :spring-boot:spring-boot:asciidoctor -D'file.encoding'=UTF-8
----

==== 构建 pdf 文档

[indent=0]
----
$ ./gradlew clean spring-hateoas:asciidoctorPdf -Dfile.encoding=UTF-8
----

=== 构建聚合文档

另外我们可以构建聚合文档

[source]
----
$ ./gradlew clean aggregatedAsciidoctor -Dfile.encoding=UTF-8
----

NOTE:: 在 IDEA 的 powershell 窗口中， file.encoding 需要添加双引号