[[architecture]]
== 体系结构

[[architecture-overview]]
=== 概述

image::{image-resource}/architecture/data_access_layers.svg[Data Access Layers]

Hibernate 作为一种 ORM 解决方案，它处于 Java 应用程序数据访问层和关系数据库之间，如上面的图表所示。Java 应用程序使用 Hibernate api 来加载、存储、查询等它的域数据。在这里，我们将介绍基本的 Hibernate api。这将是一个简单的介绍;我们稍后将详细讨论这些。

作为 JPA 提供者，Hibernate 实现了 Java Persistence API 规范，JPA 接口和 Hibernate 特定实现之间的关联如下图:

image::{image-resource}/architecture/JPA_Hibernate.svg[image]

SessionFactory (`org.hibernate.SessionFactory`):: 线程安全的 (不可变的) ,用来表示应用程序 domain  模型到数据库之间的映射。同时，他也是生成  `org.hibernate.Session` 实例的工厂. JPA 中的 `EntityManagerFactory` 和 `SessionFactory` 是等价的, 基本上，这两者融合到同一个 `SessionFactory` 实现中。
+
创建 `SessionFactory` 的代价非常昂贵，因此，对于任何给定的数据库，应用程序应该只有一个关联的 `SessionFactory`。`SessionFactory` 维护 `Hibernate` 在所有会话中使用的服务，如二级缓存、连接池、事务系统集成等。

Session (`org.hibernate.Session`):: 概念上建模 "Unit of Work" (<<Bibliography.adoc#PoEAA,PoEAA>>) 的单线程、生存期短的对象。 在 JPA 术语中，`Session` 由 `EntityManager` 表示。
+
在幕后，Hibernate `Session` 包装了一个 JDBC `java.sql.Connection` 并充当 `org.hibernate.Transaction` 实例的工厂。 它维护应用程序域模型的一般 "可重复读取" 持久性上下文（第一级缓存）。

Transaction (`org.hibernate.Transaction`):: 应用程序使用的一个单线程的、短命的对象，用于划分各个物理事务边界。 `EntityTransaction` 是 JPA 的等价物，两者都充当抽象 API，将应用程序与正在使用的底层事务系统（JDBC 或 JTA）隔离开来。
