= SRANDMEMBER

**语法**

[source,text]
----
SRANDMEMBER key [count]
----

**可用版本**：1.0.0

**时间复杂度**：没有 count 参数 为 O(1)，否则 O(N)，其中 N 是传递的 count 值。

**ACL 类别**：**@read, @set, @slow**

当仅使用 key 参数调用时，从存储在 key 处的设置值返回一个随机元素。

如果提供的 count 参数为正，则返回不同元素的数组。 数组的长度是计数或集合的基数 (SCARD)，以较小者为准。

如果使用 count 为负，则行为会发生变化，并且允许该命令多次返回相同的元素。 在这种情况下，返回的元素数量是指定 count 的绝对值。

== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-bulk-strings[批量字符串]：如果没有附加的 count 参数，该命令将返回带有随机选择的元素的批量回复，或者当键不存在时返回 nil。

https://redis.io/docs/reference/protocol-spec/#resp-arrays[数组]: 当传递额外的 count 参数时，该命令返回一个元素数组，或者当 key 不存在时返回一个空数组。

== 示例

[source,text]
----
redis> SADD myset one two three
(integer) 3
redis> SRANDMEMBER myset
"three"
redis> SRANDMEMBER myset 2
1) "one"
2) "two"
redis> SRANDMEMBER myset -5
1) "three"
2) "one"
3) "one"
4) "one"
5) "three"
redis>
----

== 传递 count 参数时的行为规范

当传递了一个值为正数的 `count` 参数，该命令的行为如下：

* 不会返回重复的元素。
* 如果 count 参数的值大于集合内的元素数量，此命令将会仅返回整个集合，没有额外的元素。
* 返回中元素的顺序并不是真正随机的，因此客户端可以根据需要对它们进行打乱顺序。

当 count 为负值时，行为将发生如下变化：

* 重复元素是可能的。
* 始终返回精确计数的元素，或者如果集合为空（不存在的键）则返回空数组。
* 回复中元素的顺序确实是随机的。

== 返回元素分布


注意：本节仅与 Redis 5 或更低版本相关，因为 Redis 6 实现了更公平的算法。

当集合中的元素数量较少时，返回元素的分布远非完美，这是因为我们使用了近似随机元素函数，但它并不能真正保证良好的分布。

使用的算法在 dict.c 内部实现，对哈希表桶进行采样以查找非空桶。 一旦找到非空桶，由于我们在哈希表实现中使用链接，因此会检查桶内的元素数量并选择随机元素。

这意味着，如果整个哈希表中有两个非空桶，其中一个包含 3 个元素，而另一个只有 1 个元素，则返回该桶中唯一的元素的概率要高得多。

== 历史

* 从 Redis 版本 2.6.0 开始：添加了可选的 count 参数。
