
[[nsa-web]]
= Web Application Security

[[nsa-debug]]
== <debug>
启用 Spring Security 调试基础结构.  这将提供人类可读的 (多行) 调试信息,以监视进入安全过滤器的请求.  这可能包括敏感信息,例如请求参数或 header,并且仅应在开发环境中使用.

[[nsa-http]]
== <http>

如果在应用程序中使用 `<http>` 元素,则会创建一个名为 "springSecurityFilterChain" 的 `FilterChainProxy` bean,并且该元素中的配置用于在 `FilterChainProxy` 中构建过滤器链.  从 Spring Security 3.1 开始,可以使用附加的 `http` 元素添加附加的过滤器链 footnote:[有关如何从 `web.xml` 中设置映射的信息,请参见 pass:specialcharacters,macros[<<ns-web-xml,introductory chapter>>]]. ].
某些核心过滤器始终在过滤器链中创建,而其他核心过滤器将根据存在的属性和子元素添加到堆栈中.  标准过滤器的位置是固定的 (请参见命名空间介绍中的<<filter-stack,过滤器顺序表>>) ,当用户必须在 `FilterChainProxy` bean 中显式配置过滤器链时,消除了框架以前版本的常见错误源.  当然,如果需要完全控制配置,您仍然可以这样做.

所有需要引用  <<servlet-authentication-authenticationmanager,`AuthenticationManager`>>  的过滤器都会自动注入由命名空间配置创建的内部实例.

每个 `<http>` 命名空间块始终创建一个 `SecurityContextPersistenceFilter`,一个 `ExceptionTranslationFilter` 和一个 `FilterSecurityInterceptor`.  这些是固定的,不能用替代方法替代.

[[nsa-http-attributes]]
=== <http> 属性
`<http>` 元素上的属性控制核心过滤器上的某些属性.

[[nsa-http-use-authorization-manager]]
* **use-authorization-manager**
使用 AuthorizationManager API 而不是 SecurityMetadataSource（默认为 true）

[[nsa-http-authorization-manager-ref]]
* **access-decision-manager-ref**
使用此 AuthorizationManager 而不是从 <intercept-url> 元素派生一个

[[nsa-http-access-decision-manager-ref]]
* **access-decision-manager-ref**
可选属性,用于指定应用于授权 HTTP 请求的 `AccessDecisionManager` 实现的 ID. 默认情况下,`AffirmativeBased` 实现用于 `RoleVoter` 和 `AuthenticatedVoter`.

[[nsa-http-authentication-manager-ref]]
* **authentication-manager-ref**
对用于此 http 元素创建的 `FilterChain` 的 `AuthenticationManager` 的引用.

[[nsa-http-observation-registry-ref]]
* **observation-registry-ref**
对用于 `FilterChain` 和相关组件的  `ObservationRegistry`  的引用

[[nsa-http-auto-config]]
* **auto-config**
自动注册登录表单,BASIC 身份验证,注销服务.  如果设置为 "true",则会添加所有这些功能 (尽管您仍然可以通过提供相应的元素来自定义每个功能的配置) .  如果未指定,则默认为 "false".  不建议使用此属性.  请使用显式配置元素来避免混淆.

[[nsa-http-create-session]]
* **create-session**
控制 Spring Security 类创建 HTTP 会话的迫切性. 选项包括:

** `always` - 如果不存在会话,Spring Security 将主动创建一个会话.
** `ifRequired` - 仅在需要一个会话时,Spring Security 才会创建一个会话 (默认值) .
** `never` - Spring Security 永远不会创建会话,但如果应用程序创建会话,它将使用一个会话.
** `stateless` - Spring Security 不会创建会话,并且会忽略该会话以获取 Spring `Authentication`.

[[nsa-http-disable-url-rewriting]]
* **disable-url-rewriting**
防止将会话 ID 附加到应用程序中的 URL. 如果此属性设置为 `true`,则客户端必须使用 cookie. 默认值为 `true`.

[[nsa-http-entry-point-ref]]
* **entry-point-ref**
通常,将根据已配置的身份验证机制来设置使用的 `AuthenticationEntryPoint`.  此属性允许通过定义自定义的 `AuthenticationEntryPoint` bean来覆盖此行为,该 bean 将启动身份验证过程.


[[nsa-http-jaas-api-provision]]
* **jaas-api-provision**
如果可用,则将请求作为从 `JaasAuthenticationToken` 获取的 `Subject` 运行,该请求是通过将 `JaasApiIntegrationFilter` bean 添加到堆栈中来实现的.  默认为 `false`.


[[nsa-http-name]]
* **name**
Bean 标识符,用于引用上下文中其他位置的 Bean.


[[nsa-http-once-per-request]]
* **once-per-request**
对应于 `FilterSecurityInterceptor` 的 `observeOncePerRequest` 属性.
默认为 `false`.


[[nsa-http-filter-all-dispatcher-types]]
* **filter-all-dispatcher-types**
对应于 `AuthorizationFilter` 的 `shouldFilterAllDispatcherTypes` 属性。 当 `use-authorization-manager=false` 时不起作用。
默认为 `true`.


[[nsa-http-pattern]]
* **pattern**
为<<nsa-http,http>>元素定义模式可控制将通过其定义的过滤器列表进行过滤的请求.  解释取决于配置的 <<nsa-http-request-matcher,request-matcher>>.  如果未定义任何模式,则将匹配所有请求,因此应首先声明最具体的模式.

[[nsa-http-realm]]
* **realm**
设置用于基本身份验证的领域名称 (如果启用) . 对应于 `BasicAuthenticationEntryPoint` 上的 `realmName` 属性.


[[nsa-http-request-matcher]]
* **request-matcher**
定义在 `FilterChainProxy` 中使用的 `RequestMatcher` 策略以及由 `intercept-url` 创建的 Bean,以匹配传入的请求.  当前,Spring MVC 的选项分别是 `mvc`,`ant`,`regex` 和 `ciRegex`,ant,regular-expression 和不区分大小写的正则表达式.
使用其<<nsa-intercept-url-pattern,pattern>>,<<nsa-intercept-url-method,method>> 和<<nsa-intercept-url-servlet-path,servlet-path>>属性为每个<<nsa-intercept-url,intercept-url>>元素创建一个单独的实例.
使用 `AntPathRequestMatcher` 匹配 Ant 路径,使用 `RegexRequestMatcher` 匹配正则表达式,对于 Spring MVC 路径,使用 `MvcRequestMatcher` 匹配.  有关这些类的确切执行方式的更多详细信息,请参见 Javadoc.  蚂蚁路径是默认策略.
如果类路径中存在 Spring MVC，则 MVC 是默认策略，否则，将使用 Ant 路径。

[[nsa-http-request-matcher-ref]]
* **request-matcher-ref**
对实现 `RequestMatcher` 的 bean 的引用,该请求将确定是否应使用此 `FilterChain`. 这是<<nsa-http-pattern,pattern>>的更强大替代方案.

[[nsa-http-security]]
* **security**
通过将此属性设置为 `none`,可以将请求模式映射到一个空的过滤器链. 不会应用任何安全性,并且 Spring Security 的任何功能都不可用.

[[nsa-http-security-context-holder-strategy-ref]]
* **security-context-repository-ref**
允许将自定义的 `SecurityContextHolderStrategy` 注入到 `SecurityContextPersistenceFilter`, `SecurityContextHolderFilter`, `BasicAuthenticationFilter`, `UsernamePasswordAuthenticationFilter`, `ExceptionTranslationFilter`, `LogoutFilter` 等。

[[nsa-http-security-context-explicit-save]]
* **security-context-explicit-save**
如果为 true，请使用 `SecurityContextHolderFilter` 而不是 `SecurityContextPersistenceFilter` 。

[[nsa-http-security-context-repository-ref]]
* **security-context-repository-ref**
允许将自定义 `SecurityContextRepository` 注入 `SecurityContextPersistenceFilter`.


[[nsa-http-servlet-api-provision]]
* **servlet-api-provision**
提供 `HttpServletRequest` 安全方法的版本,例如 `isUserInRole()` 和 `getPrincipal()`,这些方法是通过将 `SecurityContextHolderAwareRequestFilter` bean添加到堆栈中来实现的. 默认为 `true`.

[[nsa-http-use-expressions]]
* **use-expressions**
如关于<<el-access-web,基于表达式的访问控制>>一章所述,在访问属性中启用 EL 表达式. 默认值是 `true`.

[[nsa-http-children]]
===  <http> 子元素
* <<nsa-access-denied-handler,access-denied-handler>>
* <<nsa-anonymous,anonymous>>
* <<nsa-cors,cors>>
* <<nsa-csrf,csrf>>
* <<nsa-custom-filter,custom-filter>>
* <<nsa-expression-handler,expression-handler>>
* <<nsa-form-login,form-login>>
* <<nsa-headers,headers>>
* <<nsa-http-basic,http-basic>>
* <<nsa-intercept-url,intercept-url>>
* <<nsa-jee,jee>>
* <<nsa-logout,logout>>
* <<nsa-oauth2-client,oauth2-client>>
* <<nsa-oauth2-login,oauth2-login>>
* <<nsa-oauth2-resource-server,oauth2-resource-server>>
* <<nsa-password-management,password-management>>
* <<nsa-port-mappings,port-mappings>>
* <<nsa-remember-me,remember-me>>
* <<nsa-request-cache,request-cache>>
* <<nsa-saml2-login,saml2-login>>
* <<nsa-saml2-logout,saml2-logout>>
* <<nsa-session-management,session-management>>
* <<nsa-x509,x509>>

[[nsa-access-denied-handler]]
== <access-denied-handler>
该元素允许您使用 `error-page` 属性为 `ExceptionTranslationFilter` 所使用的默认 `AccessDeniedHandler` 设置 <<nsa-access-denied-handler-error-page,error-page>> 属性,或者使用 <<nsa-access-denied-handler-ref,ref>> 属性提供您自己的实现.  在 <<servlet-exceptiontranslationfilter,ExceptionTranslationFilter>> 的部分中对此进行了更详细的讨论.

[[nsa-access-denied-handler-parents]]
=== <access-denied-handler> 的父元素

* <<nsa-http,http>>

[[nsa-access-denied-handler-attributes]]
=== <access-denied-handler> 属性


[[nsa-access-denied-handler-error-page]]
* **error-page**
如果身份验证的用户请求他们无权访问的页面,则重定向到该页面的访问被拒绝页面.


[[nsa-access-denied-handler-ref]]
* **ref**
定义对类型为 `AccessDeniedHandler` 的 Spring bean 的引用.

[[nsa-cors]]
== <cors>

该元素允许配置 `CorsFilter`. 如果未指定 `CorsFilter` 或 `CorsConfigurationSource` 且 Spring MVC 在类路径上,则将 `HandlerMappingIntrospector` 用作 `CorsConfigurationSource`.

[[nsa-cors-attributes]]
=== <cors> 属性
`<cors>` 元素上的属性控制 `headers` 元素.

[[nsa-cors-ref]]
* **ref**
指定 `CorsFilter` 的 bean 名称的可选属性.

[[nsa-cors-configuration-source-ref]]
* **cors-configuration-source-ref**
可选属性,用于指定要注入到XML命名空间创建的 `CorsFilter` 中的 `CorsConfigurationSource` 的 Bean 名称.

[[nsa-cors-parents]]
=== <cors> 的父元素

* <<nsa-http,http>>

[[nsa-headers]]
== <headers>
此元素允许配置要与响应一起发送的其他 (安全) header.  它可以轻松配置多个 header,还可以通过 <<nsa-header,header>>元素设置自定义 header.  可以在 <<headers,Security Headers>>部分中找到其他信息.

** `Cache-Control`, `Pragma`, and `Expires` - 可以使用<<nsa-cache-control,cache-control>>元素进行设置. 这样可以确保浏览器不会缓存您的安全页面.
** `Strict-Transport-Security` - 可以使用 <<nsa-hsts,hsts>>元素进行设置. 这样可以确保浏览器自动为将来的请求请求HTTPS.
** `X-Frame-Options` - 可以使用 <<nsa-frame-options,frame-options>> 元素进行设置.  https://en.wikipedia.org/wiki/Clickjacking#X-Frame-Options[X-Frame-Options]  头可用于防止点击劫持攻击.
** `X-XSS-Protection` - 可以使用<<nsa-xss-protection,xss-protection>> 元素进行设置. 浏览器可以使用 https://en.wikipedia.org/wiki/Cross-site_scripting[X-XSS-Protection ] 头进行基本控制.
** `X-Content-Type-Options` - 可以使用<<nsa-content-type-options,content-type-options>>元素进行设置.  https://blogs.msdn.com/b/ie/archive/2008/09/02/ie8-security-part-vi-beta-2-update.aspx[X-Content-Type-Options] 头可防止 Internet Explorer MIME 嗅探远离已声明内容类型的响应. 下载扩展程序时,这也适用于 Google Chrome 浏览器.
** `Public-Key-Pinning` or `Public-Key-Pinning-Report-Only` - 可以使用<<nsa-hpkp,hpkp>> 元素进行设置. 这允许 HTTPS 网站使用错误签发或欺诈性证书来抵制攻击者的冒名顶替.
** `Content-Security-Policy` 或 `Content-Security-Policy-Report-Only` - 可以使用<<nsa-content-security-policy,content-security-policy>>元素进行设置. https://www.w3.org/TR/CSP2/[Content Security Policy (CSP)]是 Web 应用程序可以利用的一种机制,可以缓解诸如跨站点脚本 (XSS) 之类的内容注入漏洞.
** `Referrer-Policy` - 可以使用<<nsa-referrer-policy,referrer-policy>>元素进行设置, https://www.w3.org/TR/referrer-policy/[Referrer-Policy]是Web应用程序可以用来管理 Referrer 字段的机制,该字段包含用户所在的最后一页.
** `Feature-Policy` - 可以使用<<nsa-feature-policy,feature-policy>>元素进行设置, https://wicg.github.io/feature-policy/[Feature-Policy]是一种机制,允许 Web 开发人员在浏览器中选择性地启用,禁用和修改某些 API 和 Web 功能的行为.
** `Cross-Origin-Opener-Policy` - Can be set using the <<nsa-cross-origin-opener-policy,cross-origin-opener-policy>> element, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy[Cross-Origin-Opener-Policy] is a mechanism that allows you to ensure a top-level document does not share a browsing context group with cross-origin documents.
** `Cross-Origin-Embedder-Policy` - Can be set using the <<nsa-cross-origin-embedder-policy,cross-origin-embedder-policy>> element, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy[Cross-Origin-Embedder-Policy] is a mechanism that prevents a document from loading any cross-origin resources that don't explicitly grant the document permission.
** `Cross-Origin-Resource-Policy` - Can be set using the <<nsa-cross-origin-resource-policy,cross-origin-resource-policy>> element, https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy[Cross-Origin-Resource-Policy] is a mechanism that conveys a desire that the browser blocks no-cors cross-origin/cross-site requests to the given resource.

[[nsa-headers-attributes]]
=== <headers> 属性
`<headers>` 元素上的属性控制 headers 元素.


[[nsa-headers-defaults-disabled]]
* **defaults-disabled**
可选属性,用于指定默认的 Spring Security 的 HTTP 响应头. 默认值为 false (包括默认标题) .

[[nsa-headers-disabled]]
* **disabled**
可选属性,用于指定禁用 Spring Security 的 HTTP 响应头. 默认值为 false (已启用 header ) .

[[nsa-headers-parents]]
=== <headers> 的父元素

* <<nsa-http,http>>

[[nsa-headers-children]]
=== <headers> 的子元素


* <<nsa-cache-control,cache-control>>
* <<nsa-content-security-policy,content-security-policy>>
* <<nsa-content-type-options,content-type-options>>
* <<nsa-cross-origin-embedder-policy,cross-origin-embedder-policy>>
* <<nsa-cross-origin-opener-policy,cross-origin-opener-policy>>
* <<nsa-cross-origin-resource-policy,cross-origin-resource-policy>>
* <<nsa-feature-policy,feature-policy>>
* <<nsa-frame-options,frame-options>>
* <<nsa-header,header>>
* <<nsa-hpkp,hpkp>>
* <<nsa-hsts,hsts>>
* <<nsa-permissions-policy,permission-policy>>
* <<nsa-referrer-policy,referrer-policy>>
* <<nsa-xss-protection,xss-protection>>

[[nsa-cache-control]]
== <cache-control>
添加 `Cache-Control`,`Pragma` 和 `Expires` 头,以确保浏览器不缓存您的安全页面.

[[nsa-cache-control-attributes]]
=== <cache-control> 属性

[[nsa-cache-control-disabled]]
* **disabled**
指定是否应禁用缓存控制. 默认为 `false`.

[[nsa-cache-control-parents]]
===  <cache-control> 的父元素


* <<nsa-headers,headers>>

[[nsa-hsts]]
== <hsts>
启用后,会将 https://tools.ietf.org/html/rfc6797[Strict-Transport-Security] 头添加到任何安全请求的响应中. 这允许服务器指示浏览器自动将 HTTPS 用于将来的请求.

[[nsa-hsts-attributes]]
=== <hsts> 属性

[[nsa-hsts-disabled]]
* **disabled**
指定是否应禁用 "严格传输安全性". 默认为 `false`.

[[nsa-hsts-include-subdomains]]
* **include-sub-domains**
指定是否应包含子域. 默认为 `true`.


[[nsa-hsts-max-age-seconds]]
* **max-age-seconds**
指定应将主机视为已知 HSTS 主机的最长时间. 默认一年.


[[nsa-hsts-request-matcher-ref]]
* **request-matcher-ref**
用于确定是否应设置 header 的 RequestMatcher 实例. 默认值为 `HttpServletRequest.isSecure()` 为 `true`.

[[nsa-hsts-preload]]
* **preload**
指定是否应包含预加载. 默认为 false.

[[nsa-hsts-parents]]
=== <hsts> 的父元素

* <<nsa-headers,headers>>

[[nsa-hpkp]]
== <hpkp>
启用后,会将 https://tools.ietf.org/html/rfc7469[HTTP头的 "公钥固定扩展"] 添加到任何安全请求的响应中. 这允许 HTTPS 网站使用错误签发或欺诈性证书来抵制攻击者的冒名顶替.

[[nsa-hpkp-attributes]]
=== <hpkp> 属性

[[nsa-hpkp-disabled]]
* **disabled**
指定是否应禁用 HTTP 公钥固定 (HPKP) .  默认为true.

[[nsa-hpkp-include-subdomains]]
* **include-sub-domains**
指定是否应包含子域.  默认为 `false`.


[[nsa-hpkp-max-age-seconds]]
* **max-age-seconds**
设置 Public-Key-Pins header 的 max-age 指令的值.  默认为 60 天.


[[nsa-hpkp-report-only]]
* **report-only**
指定浏览器是否仅应报告引脚验证失败.  默认为 `true`.


[[nsa-hpkp-report-uri]]
* **report-uri**
指定浏览器应向其报告引脚验证失败的 URI.

[[nsa-hpkp-parents]]
===  <hpkp> 的父元素

* <<nsa-headers,headers>>

[[nsa-pins]]
== <pins>
引脚列表

[[nsa-pins-children]]
===  <pins> 的子元素

* <<nsa-pin,pin>>

[[nsa-pin]]
== <pin>
使用 base64 编码的 SPKI 指纹作为值并使用密码哈希算法作为属性来指定引脚

[[nsa-pin-attributes]]
=== <pin> 属性

[[nsa-pin-algorithm]]
* **algorithm**
密码哈希算法. 默认值为 SHA256.


[[nsa-pin-parents]]
===  <pin> 的父元素

* <<nsa-pins,pins>>

[[nsa-content-security-policy]]
== <content-security-policy>
启用后,将 https://www.w3.org/TR/CSP2/[Content Security Policy (CSP)] 头添加到响应中.  CSP 是 Web 应用程序可以用来缓解内容注入漏洞 (例如跨站点脚本 (XSS)) 的一种机制.

[[nsa-content-security-policy-attributes]]
=== <content-security-policy> 属性

[[nsa-content-security-policy-policy-directives]]
* **policy-directives**
Content-Security-Policy header 的安全策略指令,或者如果仅报告设置为 true,则使用 Content-Security-Policy-Report-Only header .

[[nsa-content-security-policy-report-only]]
* **report-only**
设置为 true,启用 Content-Security-Policy-Report-Only header 仅用于报告策略违例. 默认为 false.

[[nsa-content-security-policy-parents]]
===  <content-security-policy> 的父元素

* <<nsa-headers,headers>>

[[nsa-referrer-policy]]
== <referrer-policy>
启用后,将 https://www.w3.org/TR/referrer-policy/[Referrer Policy] 头添加到响应中.

[[nsa-referrer-policy-attributes]]
=== <referrer-policy> 属性

[[nsa-referrer-policy-policy]]
* **policy**
Referrer-Policy header 的策略. 默认为 "no-referrer".

[[nsa-referrer-policy-parents]]
===  <referrer-policy> 的父元素

* <<nsa-headers,headers>>

[[nsa-feature-policy]]
== <feature-policy>
启用后,将 https://wicg.github.io/feature-policy/[Feature Policy] 头添加到响应中.

[[nsa-feature-policy-attributes]]
=== <feature-policy> 属性

[[nsa-feature-policy-policy-directives]]
* **policy-directives**
Feature-Policy 头的安全策略指令.

[[nsa-feature-policy-parents]]
===  <feature-policy> 的父元素

* <<nsa-headers,headers>>

[[nsa-frame-options]]
== <frame-options>
启用后,将 https://tools.ietf.org/html/draft-ietf-websec-x-frame-options[X-Frame-Options header] 头添加到响应中,这使较新的浏览器可以进行一些安全检查并防止 https://en.wikipedia.org/wiki/Clickjacking[clickjacking]攻击.

[[nsa-frame-options-attributes]]
=== <frame-options> 属性

[[nsa-frame-options-disabled]]
* **disabled**
如果禁用,则不包括 X-Frame-Options 头. 默认为 `false`.

[[nsa-frame-options-policy]]
* **policy**
** `DENY` 该页面无法显示在框架中,无论站点尝试这样做.  当指定 frame-options-policy 时,这是默认设置.
** `SAMEORIGIN` 该页面只能以与页面本身相同的原点显示在框架中

+

换句话说,如果指定 DENY,则从其他站点加载时,不仅尝试在框架中加载页面失败,而且从同一站点加载时,尝试也会失败.  另一方面,如果指定SAMEORIGIN,则只要框架中包含该站点的页面与提供该页面的站点相同,您仍可以在框架中使用该页面.

[[nsa-frame-options-parents]]
===  <frame-options> 的父元素

* <<nsa-headers,headers>>

[[nsa-permissions-policy]]
== <permissions-policy>
将https://w3c.github.io/webappsec-permissions-policy/[Permissions-Policy header] 添加到响应中.

[[nsa-permissions-policy-attributes]]
=== <permissions-policy> 属性

[[nsa-permissions-policy-policy]]
* **policy**
为 `Permissions-Policy` 头写入的策略值

[[nsa-permissions-policy-parents]]
=== <permissions-policy> 的父元素

* <<nsa-headers,headers>>

[[nsa-xss-protection]]
== <xss-protection>
将 https://blogs.msdn.com/b/ie/archive/2008/07/02/ie8-security-part-iv-the-xss-filter.aspx[X-XSS-Protection header] 添加到响应中,以帮助防止 https://en.wikipedia.org/wiki/Cross-site_scripting#Non-Persistent[reflected / Type-1 Cross-Site Scripting (XSS)]攻击. 这绝不是对 XSS 攻击的全面保护！

[[nsa-xss-protection-attributes]]
=== <xss-protection> 属性


[[nsa-xss-protection-disabled]]
* **xss-protection-disabled**
不要包括用于 https://en.wikipedia.org/wiki/Cross-site_scripting#Non-Persistent[reflected / Type-1 Cross-Site Scripting (XSS)] 保护的头.

[[nsa-xss-protection-header-value]]
* **xss-protection-header-value**
显示设置 https://en.wikipedia.org/wiki/Cross-site_scripting#Non-Persistent[reflected / Type-1 Cross-Site Scripting (XSS)] header.
其值为以下之一: "0", "1", "1; mode=block". 默认为 "0".

[[nsa-xss-protection-parents]]
===  <xss-protection> 的父元素

* <<nsa-headers,headers>>

[[nsa-content-type-options]]
== <content-type-options>
将带有 nosniff 值的 X-Content-Type-Options header 添加到响应中. 这将禁用 IE8+ 和 Chrome 扩展的 https://blogs.msdn.com/b/ie/archive/2008/09/02/ie8-security-part-vi-beta-2-update.aspx[disables MIME-sniffing].

[[nsa-content-type-options-attributes]]
=== <content-type-options> 属性

[[nsa-content-type-options-disabled]]
* **disabled**
指定是否应禁用 "内容类型选项". 默认为 false.

[[nsa-content-type-options-parents]]
===  <content-type-options> 的父元素


* <<nsa-headers,headers>>

[[nsa-cross-origin-embedder-policy]]
==== <cross-origin-embedder-policy>
启用后，将 https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy[Cross-Origin-Embedder-Policy] 头添加到响应中。

[[nsa-cross-origin-embedder-policy-attributes]]
===== <cross-origin-embedder-policy> 属性

[[nsa-cross-origin-embedder-policy-policy]]
* **policy**
`Cross-Origin-Embedder-Policy` header 的策略。

[[nsa-cross-origin-embedder-policy-parents]]
===== <cross-origin-embedder-policy> 的父元素


* <<nsa-headers,headers>>



[[nsa-cross-origin-opener-policy]]
==== <cross-origin-opener-policy>
启用后，将 https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy[Cross-Origin-Opener-Policy] 头添加到响应中.


[[nsa-cross-origin-opener-policy-attributes]]
===== <cross-origin-opener-policy> 属性

[[nsa-cross-origin-opener-policy-policy]]
* **policy**
`Cross-Origin-Opener-Policy` header 的策略.

[[nsa-cross-origin-opener-policy-parents]]
===== <cross-origin-opener-policy> 的父元素


* <<nsa-headers,headers>>



[[nsa-cross-origin-resource-policy]]
==== <cross-origin-resource-policy>
启用后，将 https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Resource-Policy[Cross-Origin-Resource-Policy] 头添加到响应中.


[[nsa-cross-origin-resource-policy-attributes]]
===== <cross-origin-resource-policy> 属性

[[nsa-cross-origin-resource-policy-policy]]
* **policy**
`Cross-Origin-Resource-Policy` header 的策略.

[[nsa-cross-origin-resource-policy-parents]]
===== <cross-origin-resource-policy> 的父元素


* <<nsa-headers,headers>>

[[nsa-header]]
== <header>
向响应添加其他 header ,名称和值都需要指定.


[[nsa-header-attributes]]
=== <header-attributes> 属性


[[nsa-header-name]]
* **header-name**
header 名称


[[nsa-header-value]]
* **value**
要添加的 header 的值.


[[nsa-header-ref]]
* **ref**
引用 `HeaderWriter` 接口的自定义实现.


[[nsa-header-parents]]
===  <header> 的父元素


* <<nsa-headers,headers>>

[[nsa-anonymous]]
== <anonymous>
将 `AnonymousAuthenticationFilter` 添加到堆栈和 `AnonymousAuthenticationProvider`. 如果使用 `IS_AUTHENTICATED_ANONYMOUSLY` 属性,则为必需.

[[nsa-anonymous-parents]]
===  <anonymous> 的父元素


* <<nsa-http,http>>

[[nsa-anonymous-attributes]]
=== <anonymous> 属性


[[nsa-anonymous-enabled]]
* **enabled**
使用默认的命名空间设置,将自动启用匿名 "身份验证" 功能. 您可以使用此属性禁用它.


[[nsa-anonymous-granted-authority]]
* **granted-authority**
应该分配给匿名请求的授权权限. 通常,这用于为匿名请求分配特定角色,随后可以在授权决策中使用这些角色. 如果未设置,则默认为 `ROLE_ANONYMOUS`.

[[nsa-anonymous-key]]
* **key**
提供者和过滤器之间共享的密钥.  通常不需要设置.  如果未设置,则默认为安全随机生成的值.  这意味着在使用匿名功能时设置此值可以缩短启动时间,因为生成安全随机值可能需要一段时间.


[[nsa-anonymous-username]]
* **username**
应该分配给匿名请求的用户名. 这样可以确定主体,这对于日志记录和审核可能很重要. 如果未设置,则默认为 `anonymousUser`.

[[nsa-csrf]]
== <csrf>
该元素将向应用程序添加 https://en.wikipedia.org/wiki/Cross-site_request_forgery[Cross Site Request Forger (CSRF)] 保护.  它还将默认的 RequestCache 更新为仅在成功身份验证后重播 "GET" 请求.  可以在<<csrf,跨站点请求伪造 (CSRF) >>部分中找到其他信息.

[[nsa-csrf-parents]]
===  <csrf> 的父元素


* <<nsa-http,http>>

[[nsa-csrf-attributes]]
=== <csrf> 属性

[[nsa-csrf-disabled]]
* **disabled**
可选属性,用于指定禁用 Spring Security 的 CSRF 保护. 默认值为 `false` (启用 CSRF 保护) . 强烈建议使 CSRF 保护处于启用状态.

[[nsa-csrf-token-repository-ref]]
* **token-repository-ref**
要使用的 `CsrfTokenRepository`. 默认值为 `HttpSessionCsrfTokenRepository`.

[[nsa-csrf-request-handler-ref]]
* **request-handler-ref**
The optional `CsrfTokenRequestHandler` to use. The default is `CsrfTokenRequestAttributeHandler`.

[[nsa-csrf-request-matcher-ref]]
* **request-matcher-ref**
用于确定是否应应用 CSRF 的 RequestMatcher 实例. 默认为除 "GET", "TRACE", "HEAD", "OPTIONS" 之外的任何 HTTP 方法.

[[nsa-custom-filter]]
== <custom-filter>

该元素用于向过滤器链添加过滤器.  它不会创建任何其他 bean,而是用于选择 `jakarta.servlet.Filter` 类型的 bean (已在应用程序上下文中定义) ,并将其添加到 Spring Security 维护的过滤器链中的特定位置.  完整的详细信息可以在<<ns-custom-filters,命名空间>>一章中找到.

[[nsa-custom-filter-parents]]
===  <custom-filter> 的父元素


* <<nsa-http,http>>

[[nsa-custom-filter-attributes]]
=== <custom-filter> 属性


[[nsa-custom-filter-after]]
* **after**
紧随其后的过滤器,应将自定义过滤器放置在链中.  只有希望将自己的过滤器混入安全过滤器链并了解标准 Spring Security 过滤器的高级用户才需要使用此功能.  过滤器名称映射到特定的 Spring Security 实现过滤器.


[[nsa-custom-filter-before]]
* **before**
紧接在过滤器之前的自定义过滤器应放置在链中的过滤器


[[nsa-custom-filter-position]]
* **position**
自定义过滤器应放置在链中的明确位置. 如果要更换标准过滤器,请使用.


[[nsa-custom-filter-ref]]
* **ref**
定义对实现 `Filter` 的 Spring bean 的引用.

[[nsa-expression-handler]]
== <expression-handler>
定义 `SecurityExpressionHandler` 实例,如果启用了基于表达式的访问控制,则将使用该实例. 如果未提供,则将使用默认实现 (不支持 ACL) .

[[nsa-expression-handler-parents]]
===  <expression-handler> 的父元素


* <<nsa-global-method-security,global-method-security>>
* <<nsa-http,http>>
* <<nsa-method-security,method-security>>
* <<nsa-websocket-message-broker,websocket-message-broker>>

[[nsa-expression-handler-attributes]]
=== <expression-handler> 属性


[[nsa-expression-handler-ref]]
* **ref**

定义对实现 `SecurityExpressionHandler` 的 Spring bean 的引用.

[[nsa-form-login]]
== <form-login>
用于将 `UsernamePasswordAuthenticationFilter` 添加到过滤器堆栈,并将 `LoginUrlAuthenticationEntryPoint` 添加到应用程序上下文,以按需提供身份验证.
这将始终优先于其他由命名空间创建的入口点.  如果未提供任何属性,则将在 URL "/login" footnote:[此功能实际上只是为了方便起见而提供的,并不打算用于生产 (在该功能中,将选择一种查看技术,并可用于呈现自定义的登录页面) .  类 `DefaultLoginPageGeneratingFilter` 负责呈现登录页面,并在需要时提供用于普通表单登录和/或 OIDC 的登录表单. ] 上自动生成登录页面.
可以使用 <<nsa-form-login-attributes, `<form-login>` 属性>> 自定义行为.

[[nsa-form-login-parents]]
===  <form-login> 的父元素


* <<nsa-http,http>>

[[nsa-form-login-attributes]]
=== <form-login> 属性


[[nsa-form-login-always-use-default-target]]
* **always-use-default-target**
如果设置为 `true`,则无论用户如何到达登录页面,用户将始终从 <<nsa-form-login-default-target-url,default-target-url>> 给定的值开始. 映射到 `UsernamePasswordAuthenticationFilter` 的 `alwaysUseDefaultTargetUrl` 属性. 默认值为 `false`.

[[nsa-form-login-authentication-details-source-ref]]
* **authentication-details-source-ref**
对将由身份验证过滤器使用的 `AuthenticationDetailsSource` 的引用


[[nsa-form-login-authentication-failure-handler-ref]]
* **authentication-failure-handler-ref**
可以用作<<nsa-form-login-authentication-failure-url,authentication-failure-url>> 的替代方法,从而使您可以在身份验证失败后完全控制导航流程. 该值应该是应用程序上下文中的 `AuthenticationFailureHandler` bean的名称.

[[nsa-form-login-authentication-failure-url]]
* **authentication-failure-url**
映射到 `UsernamePasswordAuthenticationFilter` 的 `authenticationFailureUrl` 属性.  定义登录失败时浏览器将重定向到的URL.  默认值为 `/login?error`,它将由自动登录页面生成器自动处理,并使用错误消息重新呈现登录页面.

[[nsa-form-login-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
这可以用作<<nsa-form-login-default-target-url,default-target-url>> 和<<nsa-form-login-always-use-default-target,always-use-default-target>>的替代方法,使您在成功认证后完全控制导航流程.  该值应该是应用程序上下文中 `AuthenticationSuccessHandler` bean的名称.  默认情况下,将使用 `SavedRequestAwareAuthenticationSuccessHandler` 的实现,并将其注入<<nsa-form-login-default-target-url,default-target-url >>.

[[nsa-form-login-default-target-url]]
* **default-target-url**
映射到 `UsernamePasswordAuthenticationFilter` 的 `defaultTargetUrl` 属性.  如果未设置,则默认值为 "/" (应用程序根目录) .  如果将用户带到最初请求的URL,则在尝试访问受保护的资源时不要求用户登录后,将在登录后将其带到该URL.


[[nsa-form-login-login-page]]
* **login-page**
用于呈现登录页面的 URL. 映射到 `LoginUrlAuthenticationEntryPoint` 的 `loginFormUrl` 属性. 默认为 "/login".

[[nsa-form-login-login-processing-url]]
* **login-processing-url**
映射到 `UsernamePasswordAuthenticationFilter` 的 `filterProcessesUrl` 属性. 默认值为 "/login".

[[nsa-form-login-password-parameter]]
* **password-parameter**
包含密码的请求参数的名称. 默认为 "password".


[[nsa-form-login-username-parameter]]
* **username-parameter**
包含用户名的请求参数的名称. 默认为 "username".

[[nsa-form-login-authentication-success-forward-url]]
* **authentication-success-forward-url**
将 `ForwardAuthenticationSuccessHandler` 映射到 `UsernamePasswordAuthenticationFilter` 的 `authenticationSuccessHandler` 属性.

[[nsa-form-login-authentication-failure-forward-url]]
* **authentication-failure-forward-url**
将 `ForwardAuthenticationFailureHandler` 映射到 `UsernamePasswordAuthenticationFilter` 的 `authenticationFailureHandler` 属性.

[[nsa-oauth2-login]]
== <oauth2-login>
<<oauth2login,OAuth 2.0 Login>> 功能使用 OAuth 2.0 和/或 OpenID Connect 1.0 提供程序配置身份验证支持.

[[nsa-oauth2-login-parents]]
=== <oauth2-login> 的父元素

* <<nsa-http,http>>

[[nsa-oauth2-login-attributes]]
=== <oauth2-login> 属性


[[nsa-oauth2-login-client-registration-repository-ref]]
* **client-registration-repository-ref**
对 `ClientRegistrationRepository` 的引用.


[[nsa-oauth2-login-authorized-client-repository-ref]]
* **authorized-client-repository-ref**
引用 `OAuth2AuthorizedClientRepository`.


[[nsa-oauth2-login-authorized-client-service-ref]]
* **authorized-client-service-ref**
引用 `OAuth2AuthorizedClientService`.


[[nsa-oauth2-login-authorization-request-repository-ref]]
* **authorization-request-repository-ref**
引用 `AuthorizationRequestRepository`.


[[nsa-oauth2-login-authorization-request-resolver-ref]]
* **authorization-request-resolver-ref**
引用 `OAuth2AuthorizationRequestResolver`.

[[nsa-oauth2-login-authorization-redirect-strategy-ref]]
* **authorization-redirect-strategy-ref**
引用  authorization `RedirectStrategy`.

[[nsa-oauth2-login-access-token-response-client-ref]]
* **access-token-response-client-ref**
引用 `OAuth2AccessTokenResponseClient`.


[[nsa-oauth2-login-user-authorities-mapper-ref]]
* **user-authorities-mapper-ref**
引用 `GrantedAuthoritiesMapper`.


[[nsa-oauth2-login-user-service-ref]]
* **user-service-ref**
引用 `OAuth2UserService`.


[[nsa-oauth2-login-oidc-user-service-ref]]
* **oidc-user-service-ref**
对 OpenID Connect `OAuth2UserService` 的引用.


[[nsa-oauth2-login-login-processing-url]]
* **login-processing-url**
过滤器在其中处理身份验证请求的 URI.


[[nsa-oauth2-login-login-page]]
* **login-page**
发送用户登录的 URI.


[[nsa-oauth2-login-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
引用 `AuthenticationSuccessHandler`.


[[nsa-oauth2-login-authentication-failure-handler-ref]]
* **authentication-failure-handler-ref**
引用 `AuthenticationFailureHandler`.


[[nsa-oauth2-login-jwt-decoder-factory-ref]]
* **jwt-decoder-factory-ref**
引用由 `OidcAuthorizationCodeAuthenticationProvider` 使用的 `JwtDecoderFactory`.

[[nsa-oauth2-client]]
== <oauth2-client>
配置  <<oauth2client,OAuth 2.0 Client>>  支持.

[[nsa-oauth2-client-parents]]
=== <oauth2-client> 父元素

* <<nsa-http,http>>

[[nsa-oauth2-client-attributes]]
=== <oauth2-client> 属性


[[nsa-oauth2-client-client-registration-repository-ref]]
* **client-registration-repository-ref**
引用 `ClientRegistrationRepository`.


[[nsa-oauth2-client-authorized-client-repository-ref]]
* **authorized-client-repository-ref**
引用 `OAuth2AuthorizedClientRepository`.


[[nsa-oauth2-client-authorized-client-service-ref]]
* **authorized-client-service-ref**
引用 `OAuth2AuthorizedClientService`.


[[nsa-oauth2-client-children]]
=== <oauth2-client> 的子元素

* <<nsa-authorization-code-grant,authorization-code-grant>>

[[nsa-authorization-code-grant]]
== <authorization-code-grant>
配置 <<servlet-oauth2Client-auth-grant-support,OAuth 2.0 Authorization Code Grant>>.

[[nsa-authorization-code-grant-parents]]
=== <authorization-code-grant> 的父元素

* <<nsa-oauth2-client,oauth2-client>>

[[nsa-authorization-code-grant-attributes]]
=== <authorization-code-grant> 属性


[[nsa-authorization-code-grant-authorization-request-repository-ref]]
* **authorization-request-repository-ref**
引用 `AuthorizationRequestRepository`.

[[nsa-authorization-code-grant-authorization-redirect-strategy-ref]]
* **authorization-redirect-strategy-ref**
引用授权 `RedirectStrategy`。

[[nsa-authorization-code-grant-authorization-request-resolver-ref]]
* **authorization-request-resolver-ref**
引用 `OAuth2AuthorizationRequestResolver`.


[[nsa-authorization-code-grant-access-token-response-client-ref]]
* **access-token-response-client-ref**
引用 `OAuth2AccessTokenResponseClient`.

[[nsa-client-registrations]]
== <client-registrations>
已向 OAuth 2.0 或 OpenID Connect 1.0 提供程序注册的客户端 (<<oauth2Client-client-registration,ClientRegistration>>)  的容器元素.

[[nsa-client-registrations-children]]
=== <client-registrations> 子元素

* <<nsa-client-registration,client-registration>>
* <<nsa-provider,provider>>

[[nsa-client-registration]]
== <client-registration>
代表在 OAuth 2.0 或 OpenID Connect 1.0 提供程序中注册的客户端.

[[nsa-client-registration-parents]]
=== <client-registration> 父元素

* <<nsa-client-registrations,client-registrations>>

[[nsa-client-registration-attributes]]
=== <client-registration> 属性


[[nsa-client-registration-registration-id]]
* **registration-id**
唯一标识 `ClientRegistration` 的ID.


[[nsa-client-registration-client-id]]
* **client-id**
客户端标识符.


[[nsa-client-registration-client-secret]]
* **client-secret**
客户端 secret.


[[nsa-client-registration-client-authentication-method]]
* **client-authentication-method**
使用提供者对客户端进行身份验证的方法.
支持的值为  *client_secret_basic*, *client_secret_post*, *private_key_jwt*, *client_secret_jwt* and *none*  https://tools.ietf.org/html/rfc6749#section-2.1[(public clients)]

[[nsa-client-registration-authorization-grant-type]]
* **authorization-grant-type**
OAuth 2.0 授权框架定义了四种 https://tools.ietf.org/html/rfc6749#section-1.3[Authorization Grant] 类型.
支持的值是  `authorization_code`, `client_credentials` 和  `password`.  以及扩展类型 `urn:ietf:params:oauth:grant-type:jwt-bearer`.

[[nsa-client-registration-redirect-uri]]
* **redirect-uri**
_Authorization Server_ 在最终用户对客户端进行身份验证和授权访问之后,_Authorization Server_ 将最终用户的用户代理重定向到的客户端的注册重定向 URI.

[[nsa-client-registration-scope]]
* **scope**
客户在授权请求流程中请求的范围,例如 openid,电子邮件或配置文件.


[[nsa-client-registration-client-name]]
* **client-name**
用于客户端的描述性名称.
该名称可能在某些情况下使用,例如在自动生成的登录页面中显示客户端名称时.

[[nsa-client-registration-provider-id]]
* **provider-id**
对关联提供者的引用.  可以引用 `<provider>` 元素或使用常见的提供程序之一 (google,github,facebook,okta) .

[[nsa-provider]]
== <provider>
OAuth 2.0 或 OpenID Connect 1.0 提供程序的配置信息.

[[nsa-provider-parents]]
=== <provider> 父元素

* <<nsa-client-registrations,client-registrations>>

[[nsa-provider-attributes]]
=== <provider> 属性


[[nsa-provider-provider-id]]
* **provider-id**
唯一标识提供者的 ID.


[[nsa-provider-authorization-uri]]
* **authorization-uri**
授权服务器的授权端点 URI.


[[nsa-provider-token-uri]]
* **token-uri**
授权服务器的令牌端点 URI.


[[nsa-provider-user-info-uri]]
* **user-info-uri**
UserInfo 端点 URI,用于访问经过身份验证的最终用户的  claims/attributes.

[[nsa-provider-user-info-authentication-method]]
* **user-info-authentication-method**
将访问令牌发送到 UserInfo 端点时使用的身份验证方法.
支持的值为  *header*, *form* 和 *query*.

[[nsa-provider-user-info-user-name-attribute]]
* **user-info-user-name-attribute**
在 UserInfo 响应中返回的属性名称,该属性引用了最终用户的名称或标识符.


[[nsa-provider-jwk-set-uri]]
* **jwk-set-uri**
用于从授权服务器检索 JSON Web 密钥 (https://tools.ietf.org/html/rfc7517[JSON Web Key (JWK)] ) 集的 URI,其中包含用于验证 ID 令牌的 JSON Web 签名 (https://tools.ietf.org/html/rfc7515[JSON Web Signature (JWS)] ) 以及用户信息响应 (可选) 的加密密钥.

[[nsa-provider-issuer-uri]]
* **issuer-uri**
用于发现 OpenID Connect 提供程序的 https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Configuration endpoint]或授权服务器的  https://tools.ietf.org/html/rfc8414#section-3[Metadata endpoint] 的 URI,用于初始配置 `ClientRegistration`.

[[nsa-oauth2-resource-server]]
== <oauth2-resource-server>
将 `BearerTokenAuthenticationFilter`,`BearerTokenAuthenticationEntryPoint` 和 `BearerTokenAccessDeniedHandler` 添加到配置中.  另外,必须指定 `<jwt>` 或 `<opaque-token>`.

[[nsa-oauth2-resource-server-parents]]
=== <oauth2-resource-server> 的父元素

* <<nsa-http,http>>

[[nsa-oauth2-resource-server-children]]
===  <oauth2-resource-server> 的子元素

* <<nsa-jwt,jwt>>
* <<nsa-opaque-token,opaque-token>>

[[nsa-oauth2-resource-server-attributes]]
=== <oauth2-resource-server> 属性

[[nsa-oauth2-resource-server-authentication-manager-resolver-ref]]
* **authentication-manager-resolver-ref**
引用 `AuthenticationManagerResolver`,它将在请求时解析 `AuthenticationManager`

[[nsa-oauth2-resource-server-bearer-token-resolver-ref]]
* **bearer-token-resolver-ref**
引用 `BearerTokenResolver`,它将从请求中获取承载令牌.

[[nsa-oauth2-resource-server-entry-point-ref]]
* **entry-point-ref**
引用将处理未授权请求的 `AuthenticationEntryPoint`

[[nsa-jwt]]
== <jwt>
表示将授权 JWT 的 OAuth 2.0 资源服务器

[[nsa-jwt-parents]]
===  <jwt> 的父元素

* <<nsa-oauth2-resource-server,oauth2-resource-server>>

[[nsa-jwt-attributes]]
=== <jwt> 属性

[[nsa-jwt-jwt-authentication-converter-ref]]
* **jwt-authentication-converter-ref**
对  `Converter<Jwt, AbstractAuthenticationToken>` 的引用

[[nsa-jwt-decoder-ref]]
* **jwt-decoder-ref**
引用 `JwtDecoder`.  这是一个较大的组件,它会覆盖 `jwk-set-uri`

[[nsa-jwt-jwk-set-uri]]
* **jwk-set-uri**
用于从 OAuth 2.0 授权服务器加载签名验证密钥的 JWK 集 Uri

[[nsa-opaque-token]]
== <opaque-token>
表示将授权不透明令牌的 OAuth 2.0 资源服务器

[[nsa-opaque-token-parents]]
=== <opaque-token> 的父元素

* <<nsa-oauth2-resource-server,oauth2-resource-server>>

[[nsa-opaque-token-attributes]]
=== <opaque-token> 属性

[[nsa-opaque-token-introspector-ref]]
* **introspector-ref**
引用 `OpaqueTokenIntrospector`. 这是一个较大的组件,它会覆盖 `introspection-uri`, `client-id`, 和 `client-secret`.

[[nsa-opaque-token-introspection-uri]]
* **introspection-uri**
内省 Uri 用来内省不透明令牌的详细信息.  应随附 `client-id` 和 `client-secret`.

[[nsa-opaque-token-client-id]]
* **client-id**
用于针对提供的 `introspection-uri` 进行客户端身份验证的客户端 ID.

[[nsa-opaque-token-client-secret]]
* **client-secret**
用于根据提供的 `introspection-uri` 进行客户端身份验证的客户端密钥.

[[nsa-opaque-token-authentication-converter-ref]]
* **authentication-converter-ref**
对 `OpaqueTokenAuthenticationConverter` 的引用。 负责将成功的 introspection 结果转换为 `Authentication` 实例。

[[nsa-relying-party-registrations]]
== <relying-party-registrations>
使用 SAML 2.0 身份提供者注册 (<<servlet-saml2login-relyingpartyregistration,ClientRegistration>>) 的依赖的容器元素。

[[nsa-relying-party-registrations-children]]
=== <relying-party-registrations> 的子元素

* <<nsa-asserting-party,asserting-party>>
* <<nsa-relying-party-registration,relying-party-registration>>


[[nsa-relying-party-registration]]
== <relying-party-registration>
表示向 SAML 2.0 身份提供者注册的依赖方


[[nsa-relying-party-registration-parents]]
=== <relying-party-registration> 的父元素

* <<nsa-relying-party-registrations,relying-party-registrations>>


[[nsa-relying-party-registration-attributes]]
=== <relying-party-registration> 属性


[[nsa-relying-party-registration-registration-id]]
* **registration-id**
唯一标识 `RelyingPartyRegistration` 的 ID.

[[nsa-relying-party-registration-metadata-location]]
* **metadata-location**
The asserting party metadata location.

[[nsa-relying-party-registration-entity-id]]
* **client-id**
依赖方的 https://www.oasis-open.org/committees/download.php/51890/SAML%20MD%20simplified%20overview.pdf#2.9%20EntityDescriptor[EntityID].


[[nsa-relying-party-registration-assertion-consumer-service-location]]
* **assertion-consumer-service-location**
AssertionConsumerService 位置. 当于在依赖方的 `&lt;SPSSODescriptor&gt;` 中的 `&lt;AssertionConsumerService Location="..."/&gt;`


[[nsa-relying-party-registration-assertion-consumer-service-binding]]
* **assertion-consumer-service-binding**
AssertionConsumerService 绑定。 相当于在依赖方的 `&lt;SPSSODescriptor&gt;` 中的 `&lt;AssertionConsumerService Binding="..."/&gt;` 中找到的值。 支持的值为 *POST* 和 *REDIRECT*。

[[nsa-relying-party-registration-single-logout-service-location]]
* **single-logout-service-location**
SingleLogoutService 位置。 相当于在依赖方的 &lt;SPSSODescriptor&gt; 中的  &lt;SingleLogoutService Location="..."/&gt; 中找到的值。

[[nsa-relying-party-registration-single-logout-service-response-location]]
* **single-logout-service-response-location**
SingleLogoutService ResponseLocation。 相当于在依赖方的 &lt;SPSSODescriptor&gt; 中的 &lt;SingleLogoutService ResponseLocation="..."/&gt; 中找到的值。

[[nsa-relying-party-registration-single-logout-service-binding]]
* **single-logout-service-binding**
SingleLogoutService 绑定。 相当于在依赖方的 &lt;SPSSODescriptor&gt; 中的 &lt;SingleLogoutService Binding="..."/&gt; 中找到的值。 支持的值为 *POST* 和 *REDIRECT*。

[[nsa-relying-party-registration-asserting-party-id]]
* **asserting-party-id**
对相关断言方的引用。 必须引用 `<asserting-party>` 元素。

[[nsa-relying-party-registration-children]]
=== Child Elements of <relying-party-registration>

* <<nsa-decryption-credential,decryption-credential>>
* <<nsa-signing-credential,signing-credential>>


[[nsa-decryption-credential]]
== <decryption-credential>
与依赖方关联的解密凭证。


[[nsa-decryption-credential-parents]]
=== <decryption-credential> 的父元素

* <<nsa-relying-party-registration,relying-party-registration>>


[[nsa-decryption-credential-attributes]]
=== <decryption-credential> 属性


[[nsa-decryption-credential-certificate-location]]
* **certificate-location**
获得此证书的位置

[[nsa-decryption-credential-private-key-location]]
* **private-key-location**
获取依赖方私钥的位置


[[nsa-signing-credential]]
== <signing-credential>
与依赖方关联的签名凭据。


[[nsa-signing-credential-parents]]
=== <verification-credential> 的父元素

* <<nsa-relying-party-registration,relying-party-registration>>


[[nsa-signing-credential-attributes]]
=== <verification-credential> 属性


[[nsa-signing-credential-certificate-location]]
* **certificate-location**
获得此证书的位置

[[nsa-signing-credential-private-key-location]]
* **private-key-location**
获取依赖方私钥的位置



[[nsa-asserting-party]]
== <asserting-party>
SAML 2.0 断言方的配置信息。


[[nsa-asserting-party-parents]]
=== <asserting-party> 的父元素

* <<nsa-relying-party-registrations,relying-party-registrations>>


[[nsa-asserting-party-attributes]]
=== <asserting-party> 属性


[[nsa-asserting-party-asserting-party-id]]
* **asserting-party-id**
唯一标识断言方的 ID。


[[nsa-asserting-party-entity-id]]
* **entity-id**
断言方的 EntityID


[[nsa-asserting-party-want-authn-requests-signed]]
* **want-authn-requests-signed**
`WantAuthnRequestsSigned` 设置，指示断言方的偏好，依赖方应在发送前签署 `AuthnRequest`。


[[nsa-asserting-party-single-sign-on-service-location]]
* **single-sign-on-service-location**
https://www.oasis-open.org/committees/download.php/51890/SAML%20MD%20simplified%20overview.pdf#2.5%20Endpoint[SingleSignOnService] Location.


[[nsa-asserting-party-single-sign-on-service-binding]]
* **single-sign-on-service-binding**
https://www.oasis-open.org/committees/download.php/51890/SAML%20MD%20simplified%20overview.pdf#2.5%20Endpoint[SingleSignOnService] Binding.
支持 *POST* 和 *REDIRECT*.


[[nsa-asserting-party-signing-algorithms]]
* **signing-algorithms**
断言方 `org.opensaml.saml.ext.saml2alg.SigningMethod` 算法列表, 按优先顺序排列。.


[[nsa-asserting-party-single-logout-service-location]]
* **single-logout-service-location**
SingleLogoutService 位置。 相当于在断言方的 &lt;IDPSSODescriptor&gt; 中的 &lt;SingleLogoutService Location="..."/&gt; 中找到的值。

[[nsa-asserting-party-single-logout-service-response-location]]
* **single-logout-service-response-location**
SingleLogoutService ResponseLocation。 相当于在断言方的 &lt;IDPSSODescriptor&gt; 中的 &lt;SingleLogoutService ResponseLocation="..."/&gt; 中找到的值。

[[nsa-asserting-party-single-logout-service-binding]]
* **single-logout-service-binding**
SingleLogoutService 绑定。 相当于在断言方的 &lt;IDPSSODescriptor&gt; 中的 &lt;SingleLogoutService Binding="..."/&gt;  中找到的值。 支持的值为 *POST* 和 *REDIRECT*。

[[nsa-asserting-party-children]]
=== Child Elements of <asserting-party>

* <<nsa-encryption-credential,encryption-credential>>
* <<nsa-verification-credential,verification-credential>>


[[nsa-encryption-credential]]
== <encryption-credential>
与断言方关联的加密凭证。


[[nsa-encryption-credential-parents]]
=== <encryption-credential> 的父元素

* <<nsa-asserting-party,asserting-party>>


[[nsa-encryption-credential-attributes]]
=== <encryption-credential> 属性


[[nsa-encryption-credential-certificate-location]]
* **certificate-location**
获取证书的位置

[[nsa-encryption-credential-private-key-location]]
* **private-key-location**
获取依赖方私钥的位置


[[nsa-verification-credential]]
== <verification-credential>
与断言方关联的验证凭据。


[[nsa-verification-credential-parents]]
=== <verification-credential> 的父元素

* <<nsa-asserting-party,asserting-party>>


[[nsa-verification-credential-attributes]]
=== <verification-credential> 属性


[[nsa-verification-credential-certificate-location]]
* **certificate-location**
获得此证书的位置

[[nsa-verification-credential-private-key-location]]
* **private-key-location**
获取依赖方私钥的位置

[[nsa-http-basic]]
== <http-basic>
将 `BasicAuthenticationFilter` 和 `BasicAuthenticationEntryPoint` 添加到配置中. 如果未启用基于表单的登录,则后者将仅用作配置入口点.

[[nsa-http-basic-parents]]
===  <http-basic> 的父元素

* <<nsa-http,http>>

[[nsa-http-basic-attributes]]
=== <http-basic> 属性


[[nsa-http-basic-authentication-details-source-ref]]
* **authentication-details-source-ref**
对将由身份验证过滤器使用 的 `AuthenticationDetailsSource` 的引用


[[nsa-http-basic-entry-point-ref]]
* **entry-point-ref**
设置 `BasicAuthenticationFilter` 使用的 `AuthenticationEntryPoint`.

[[nsa-http-firewall]]
== <http-firewall> 元素
这是一个顶级元素,可用于将 `HttpFirewall` 的自定义实现注入到由命名空间创建的 `FilterChainProxy` 中. 默认实现应适合大多数应用程序.

[[nsa-http-firewall-attributes]]
=== <http-firewall> 属性


[[nsa-http-firewall-ref]]
* **ref**
定义对实现 `HttpFirewall` 的Spring bean的引用.

[[nsa-intercept-url]]
== <intercept-url>
此元素用于定义应用程序感兴趣的 URL 模式集,并配置应如何处理它们.  它用于构造 `FilterSecurityInterceptor` 使用的 `FilterInvocationSecurityMetadataSource`.  例如,如果需要通过 HTTPS 访问特定的 URL,它还负责配置 `ChannelProcessingFilter`.  当将指定的模式与传入的请求进行匹配时,将按照声明元素的顺序进行匹配.
因此,最具体的模式应该放在首位,最一般的模式应该放在最后.

[[nsa-intercept-url-parents]]
===  <intercept-url> 的父元素


* <<nsa-filter-security-metadata-source,filter-security-metadata-source>>
* <<nsa-http,http>>

[[nsa-intercept-url-attributes]]
=== <intercept-url> 属性


[[nsa-intercept-url-access]]
* **access**
列出访问属性,这些属性将为定义的 URL 模式/方法组合存储在 `FilterInvocationSecurityMetadataSource` 中. 这应该是安全配置属性 (例如角色名称) 的逗号分隔列表.

[[nsa-intercept-url-method]]
* **method**
HTTP 方法将与模式和 servlet 路径 (可选) 结合使用,以匹配传入的请求.  如果省略,则任何方法都将匹配.  如果使用和不使用方法指定了相同的模式,则特定于方法的匹配将优先.

[[nsa-intercept-url-pattern]]
* **pattern**
定义 URL 路径的模式. 内容将取决于包含 http 元素的 `request-matcher` 属性,因此如果 Spring MVC 在类路径中，则默认为 MVC 匹配器.

[[nsa-intercept-url-request-matcher-ref]]
* **request-matcher-ref**
对 `RequestMatcher` 的引用,该引用将用于确定是否使用此 `<intercept-url>`.

[[nsa-intercept-url-requires-channel]]
* **requires-channel**
可以为 "http"  或 "https",具体取决于应分别通过 HTTP 还是 HTTPS 访问特定的 URL 模式.  或者,在没有首选项时可以使用值 "any".  如果任何 `<intercept-url>` 元素上都存在此属性,则将 `ChannelProcessingFilter` 添加到过滤器堆栈中,并将其附加依赖添加到应用程序上下文中.

如果添加了 `<port-mappings>` 配置,则 `SecureChannelProcessor` 和 `InsecureChannelProcessor` Bean 将使用此配置来确定用于重定向到 `HTTP/HTTPS` 的端口.

NOTE: 此属性对于<<nsa-filter-security-metadata-source,filter-security-metadata-source>>无效

[[nsa-intercept-url-servlet-path]]
* **servlet-path**
Servlet 路径将与模式和 HTTP 方法结合使用,以匹配传入的请求.  仅当<<nsa-http-request-matcher,请求匹配>>为 `mvc` 时,此属性才适用.  另外,仅在以下两个用例中需要该值: 1) 在 `ServletContext` 中注册了2个或更多 `HttpServlet`,它们的映射以 `/` 开头并且不同.
2) 模式以已注册 `HttpServlet` 路径的相同值开头,但不包括默认 (根)  `HttpServlet` `'/'`.


NOTE: 此属性对于<<nsa-filter-security-metadata-source,filter-security-metadata-source>>无效

[[nsa-jee]]
== <jee>
将 J2eePreAuthenticatedProcessingFilter 添加到过滤器链以提供与容器身份验证的集成.


[[nsa-jee-parents]]
===  <jee> 的父元素

* <<nsa-http,http>>

[[nsa-jee-attributes]]
=== <jee> 属性

[[nsa-jee-mappable-roles]]
* **mappable-roles**
在传入的 HttpServletRequest 中寻找以逗号分隔得 Role 列表.


[[nsa-jee-user-service-ref]]
* **user-service-ref**
对用户服务 (或 UserDetailsService bean) ID的引用

[[nsa-logout]]
== <logout>
将 `LogoutFilter` 添加到过滤器堆栈. 这是使用 `SecurityContextLogoutHandler` 配置的.

[[nsa-logout-parents]]
===  <logout> 的父元素

* <<nsa-http,http>>

[[nsa-logout-attributes]]
=== <logout> 属性


[[nsa-logout-delete-cookies]]
* **delete-cookies**
Cookie 的名称的逗号分隔列表,当用户注销时应删除.


[[nsa-logout-invalidate-session]]
* **invalidate-session**
映射到 `SecurityContextLogoutHandler` 的 `invalidateHttpSession`. 默认为 "true",因此会话将在注销时失效.

[[nsa-logout-logout-success-url]]
* **logout-success-url**
用户注销后将被带到的目标 URL.  默认为 `<form-login-login-page>/?logout` (即 `/login?logout`)

+

设置此属性将注入配置有属性值的 `SimpleRedirectInvalidSessionStrategy` 的 `SessionManagementFilter`.  提交无效的会话 ID 后,将调用该策略,并重定向到配置的 URL.


[[nsa-logout-logout-url]]
* **logout-url**
导致注销的网址 (即由过滤器处理的网址) .  默认为 "/logout".

[[nsa-logout-success-handler-ref]]
* **success-handler-ref**
可用于提供 `LogoutSuccessHandler` 的实例,注销后将调用该实例来控制导航.

[[nsa-saml2-login]]
== <saml2-login>
<<servlet-saml2login,SAML 2.0 Login>> 使用 SAML 2.0 服务提供商配置身份验证支持。

[[nsa-saml2-login-parents]]
=== <saml2-login> 的父元素

* <<nsa-http,http>>

[[nsa-saml2-login-attributes]]
=== <saml2-login> Attributes


[[nsa-saml2-login-relying-party-registration-repository-ref]]
* **relying-party-registration-repository-ref**
引用 `RelyingPartyRegistrationRepository`.


[[nsa-saml2-login-authentication-request-repository-ref]]
* **authentication-request-repository-ref**
引用 `Saml2AuthenticationRequestRepository`.


[[nsa-saml2-login-authentication-request-resolver-ref]]
* **authentication-request-context-resolver-ref**
引用 `Saml2AuthenticationRequestResolver`.


[[nsa-saml2-login-authentication-converter-ref]]
* **authentication-converter-ref**
引用 `AuthenticationConverter`.


[[nsa-saml2-login-login-processing-url]]
* **login-processing-url**
过滤器处理身份验证请求的 URI。


[[nsa-saml2-login-login-page]]
* **login-page**
发送用户登录的 URI。


[[nsa-saml2-login-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
引用 `AuthenticationSuccessHandler`.


[[nsa-saml2-login-authentication-failure-handler-ref]]
* **authentication-failure-handler-ref**
引用 `AuthenticationFailureHandler`.


[[nsa-saml2-login-authentication-manager-ref]]
* **authentication-manager-ref**
引用 `AuthenticationManager`.


[[nsa-saml2-logout]]
== <saml2-logout>
<<servlet-saml2login-logout,SAML 2.0 Single Logout>> 功能配置对 RP 和 AP 发起的 SAML 2.0 单点注销的支持。


[[nsa-saml2-logout-parents]]
=== <saml2-logout> 的父元素

* <<nsa-http,http>>

[[nsa-saml2-logout-attributes]]
=== <saml2-logout> 属性


[[nsa-saml2-logout-logout-url]]
* **logout-url**
依赖方或断言方可以触发注销的 URL。


[[nsa-saml2-logout-logout-request-url]]
* **logout-request-url**
断言方可以用来发送 SAML 2.0 注销请求的 URL。


[[nsa-saml2-logout-logout-response-url]]
* **logout-response-url**
断言方可以用来发送 SAML 2.0 注销响应的 URL。


[[nsa-saml2-logout-relying-party-registration-repository-ref]]
* **relying-party-registration-repository-ref**
引用  `RelyingPartyRegistrationRepository`.


[[nsa-saml2-logout-logout-request-validator-ref]]
* **logout-request-validator-ref**
引用  `Saml2LogoutRequestValidator`.


[[nsa-saml2-logout-logout-request-resolver-ref]]
* **logout-request-resolver-ref**
引用  `Saml2LogoutRequestResolver`.


[[nsa-saml2-logout-logout-request-repository-ref]]
* **logout-request-repository-ref**
引用  `Saml2LogoutRequestRepository`.


[[nsa-saml2-logout-logout-response-validator-ref]]
* **logout-response-validator-ref**
引用  `Saml2LogoutResponseValidator`.


[[nsa-saml2-logout-logout-response-resolver-ref]]
* **logout-response-resolver-ref**
引用  `Saml2LogoutResponseResolver`.

[[nsa-password-management]]
== <password-management>
此元素配置密码管理。

[[nsa-password-management-parents]]
=== <password-management> 的父元素

* <<nsa-http,http>>

[[nsa-password-management-attributes]]
=== <password-management> 属性

[[nsa-password-management-change-password-page]]
* **change-password-page**
更改密码页面。 默认为 "/change-password".

[[nsa-port-mappings]]
== <port-mappings>
默认情况下,会将 `PortMapperImpl` 的实例添加到配置中,以用于重定向到安全和不安全的URL.  可以选择使用此元素来覆盖该类定义的默认映射.  每个子 `<port-mapping>` 元素都定义一对 HTTP: HTTPS 端口.  默认映射为 80: 443 和 8080: 8443.  在 <<servlet-http-redirect>> 中可以找到覆盖这些示例.

[[nsa-port-mappings-parents]]
===  <port-mappings> 的父元素

* <<nsa-http,http>>

[[nsa-port-mappings-children]]
===  <port-mappings> 的子元素


* <<nsa-port-mapping,port-mapping>>

[[nsa-port-mapping]]
== <port-mapping>
提供一种在强制重定向时将 http 端口映射到 https 端口的方法.

[[nsa-port-mapping-parents]]
===  <port-mapping> 的父元素

* <<nsa-port-mappings,port-mappings>>

[[nsa-port-mapping-attributes]]
=== <port-mapping> 属性


[[nsa-port-mapping-http]]
* **http**
要使用的 http 端口.


[[nsa-port-mapping-https]]
* **https**
要使用的 https 端口.

[[nsa-remember-me]]
== <remember-me>
将 `RememberMeAuthenticationFilter` 添加到堆栈中.  反过来,将根据属性设置,使用 `TokenBasedRememberMeServices`,`PersistentTokenBasedRememberMeServices` 或由用户指定的实现 `RememberMeServices` 的 bea n进行配置.

[[nsa-remember-me-parents]]
===  <remember-me> 的父元素


* <<nsa-http,http>>

[[nsa-remember-me-attributes]]
=== <remember-me> 属性


[[nsa-remember-me-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
如果需要自定义导航,则在 `RememberMeAuthenticationFilter` 上设置 `authenticationSuccessHandler` 属性. 该值应该是应用程序上下文中 `AuthenticationSuccessHandler` bean的名称.

[[nsa-remember-me-data-source-ref]]
* **data-source-ref**
对 `DataSource` bean 的引用. 如果设置此选项,将使用 `PersistentTokenBasedRememberMeServices` 并通过 `JdbcTokenRepositoryImpl` 实例进行配置.

[[nsa-remember-me-remember-me-parameter]]
* **remember-me-parameter**
切换 "记住我" 身份验证的请求参数的名称. 默认为 "remember-me". 映射到 `AbstractRememberMeServices` 的 "parameter" 属性.

[[nsa-remember-me-remember-me-cookie]]
* **remember-me-cookie**
存储用于记住我身份验证的令牌的 cookie 的名称. 默认为 "remember-me". 映射到 `AbstractRememberMeServices` 的 "cookieName" 属性.


[[nsa-remember-me-key]]
* **key**
映射到 `AbstractRememberMeServices` 的 "key" 属性.  应将其设置为唯一值,以确保 "记住我的Cookie" 仅在一个应用程序中有效 footnote:[这不会影响 `PersistentTokenBasedRememberMeServices` 的使用,因为令牌存储在服务器端. ].  如果未设置,将生成一个安全的随机值.
由于生成安全的随机值可能需要一段时间,因此,在使用 "记住我" 功能时,显式设置该值有助于缩短启动时间.

[[nsa-remember-me-services-alias]]
* **services-alias**
将内部定义的 `RememberMeServices` 导出为 bean 别名,从而允许应用程序上下文中的其他 bean 使用它.


[[nsa-remember-me-services-ref]]
* **services-ref**
允许完全控制过滤器将使用的 `RememberMeServices` 实现.  该值应该是实现此接口的应用程序上下文中的 bean 的 `ID`.  如果正在使用注销过滤器,则还应该实现 `LogoutHandler`.

[[nsa-remember-me-token-repository-ref]]
* **token-repository-ref**
`PersistentTokenBasedRememberMeServices`,但允许使用自定义 `PersistentTokenRepository` bean.

[[nsa-remember-me-token-validity-seconds]]
* **token-validity-seconds**
映射到 `AbstractRememberMeServices` 的 `tokenValiditySeconds` 属性. 指定记住我的 cookie 有效的时间段 (以秒为单位) . 默认情况下,有效期为14天.

[[nsa-remember-me-use-secure-cookie]]
* **use-secure-cookie**
建议记住我的 cookie 仅通过 HTTPS 提交,因此应将其标记为 "安全".  默认情况下,如果发出登录请求的连接是安全的 (应该如此) ,则将使用安全 cookie.  如果将此属性设置为 `false`,将不使用安全 cookie.  将其设置为 `true` 将始终在 cookie 上设置安全标志.  此属性映射到 `AbstractRememberMeServices` 的 `useSecureCookie` 属性.


[[nsa-remember-me-user-service-ref]]
* **user-service-ref**
"记住我" 服务实现要求访问 `UserDetailsService`,因此在应用程序上下文中必须定义一个.  如果只有一个,它将由命名空间配置自动选择和使用.  如果有多个实例,则可以使用此属性显式指定bean `ID`.

[[nsa-request-cache]]
== <request-cache> 元素
设置 `RequestCache` 实例,在调用 `AuthenticationEntryPoint` 之前,`ExceptionTranslationFilter` 将使用该实例存储请求信息.

[[nsa-request-cache-parents]]
===  <request-cache> 的父元素

* <<nsa-http,http>>

[[nsa-request-cache-attributes]]
=== <request-cache> 属性


[[nsa-request-cache-ref]]
* **ref**
定义对作为 `RequestCache` 的 Spring bean 的引用.

[[nsa-session-management]]
== <session-management>
与会话管理相关的功能是通过在过滤器堆栈中添加 `SessionManagementFilter` 来实现的.

[[nsa-session-management-parents]]
===  <session-management> 的父元素

* <<nsa-http,http>>

[[nsa-session-management-attributes]]
=== <session-management> 属性

[[nsa-session-management-authentication-strategy-explicit-invocation]]
* **authentication-strategy-explicit-invocation**
Setting this attribute to true will mean that `SessionManagementFilter` will not be injected and explicit invocation of SessionAuthenticationStrategy is required.


[[nsa-session-management-invalid-session-url]]
* **invalid-session-url**
设置此属性将注入配置有属性值的 `SimpleRedirectInvalidSessionStrategy` 的 `SessionManagementFilter`. 提交无效的会话 ID 后,将调用该策略,并重定向到配置的 URL.

[[nsa-session-management-invalid-session-strategy-ref]]
* **invalid-session-url**
允许注入由 `SessionManagementFilter` 使用的 `InvalidSessionStrategy` 实例. 使用此属性或 `invalid-session-url` 属性,但不能同时使用.

[[nsa-session-management-session-authentication-error-url]]
* **session-authentication-error-url**

定义错误页面的 URL,当 `SessionAuthenticationStrategy` 引发异常时应显示该页面.  如果未设置,则将未经授权的 (401) 错误代码返回给客户端.  请注意,如果在基于表单的登录过程中发生错误,则该属性将不适用,在该表单中,身份验证失败的 URL 将优先.

[[nsa-session-management-session-authentication-strategy-ref]]
* **session-authentication-strategy-ref**
允许注入由 SessionManagementFilter 使用的 SessionAuthenticationStrategy 实例


[[nsa-session-management-session-fixation-protection]]
* **session-fixation-protection**

指示用户认证时如何应用会话固定保护.  如果设置为 "none",则不会应用任何保护.  "newSession" 将创建一个新的空会话,仅迁移与 Spring Security 相关的属性.  "migrateSession" 将创建一个新会话并将所有会话属性复制到新会话.
在 Servlet 3.1 (Java EE 7) 和更高版本的容器中,指定 "changeSessionId" 将保留现有会话并使用容器提供的会话固定保护 (`HttpServletRequest#changeSessionId()`) .  在 Servlet 3.1 和更高版本的容器中,默认值为 "changeSessionId"; 在较旧的容器中,
默认值为 "migrateSession".  如果在较旧的容器中使用 "changeSessionId",则抛出异常.

+

如果启用了会话固定保护,则会向 `SessionManagementFilter` 注入适当配置的 `DefaultSessionAuthenticationStrategy`.  有关更多详细信息,请参见此类的 Javadoc.

[[nsa-session-management-children]]
===  <session-management> 的子元素


* <<nsa-concurrency-control,concurrency-control>>

[[nsa-concurrency-control]]
== <concurrency-control>
增加了对并发会话控制的支持,从而可以限制用户可以拥有的 active 会话的数量.  将创建一个 `ConcurrentSessionFilter`,并将 `ConcurrentSessionControlAuthenticationStrategy` 与 `SessionManagementFilter` 一起使用.  如果声明了 `form-login` 元素,则策略对象也将注入到创建的身份验证过滤器中.  将创建一个 `SessionRegistry` 实例 (除非用户希望使用自定义 bean,否则将为 `SessionRegistryImpl` 实例) 供该策略使用.

[[nsa-concurrency-control-parents]]
===  <concurrency-control> 的父元素

* <<nsa-session-management,session-management>>

[[nsa-concurrency-control-attributes]]
=== <concurrency-control> 属性


[[nsa-concurrency-control-error-if-maximum-exceeded]]
* **error-if-maximum-exceeded**
如果设置为 "true",则当用户尝试超过允许的最大会话数时,将引发 `SessionAuthenticationException`. 默认行为是使原始会话到期.


[[nsa-concurrency-control-expired-url]]
* **expired-url**
如果用户尝试使用并发会话控制器已 "过期" 的会话,则该用户将被重定向到该 URL,因为该用户已超过允许的会话数,并已在其他位置再次登录.  除非设置了 `if-if-maximum-exceeded`,否则应设置.  如果未提供任何值,则到期消息将直接写回到响应中.

[[nsa-concurrency-control-expired-session-strategy-ref]]
* **expired-url**
允许注入 ConcurrentSessionFilter 使用的 ExpiredSessionStrategy 实例

[[nsa-concurrency-control-max-sessions]]
* **max-sessions**
映射到 `ConcurrentSessionControlAuthenticationStrategy` 的 `maximumSessions` 属性. 指定 `-1` 作为支持无限会话的值.


[[nsa-concurrency-control-session-registry-alias]]
* **session-registry-alias**
引用内部会话注册表以在自己的 bean 或管理界面中使用也很有用.  您可以使用 `session-registry-alias` 属性暴露内部 bean,为其提供一个名称,您可以在配置中的其他位置使用它.

[[nsa-concurrency-control-session-registry-ref]]
* **session-registry-ref**
用户可以使用 `session-registry-ref` 属性提供自己的 `SessionRegistry` 实现.  其他并发会话控制 bean 将被连接起来以使用它.

[[nsa-x509]]
== <x509>
添加了对 X.509 身份验证的支持.  `X509AuthenticationFilter` 将添加到堆栈中,并将创建 `Http403ForbiddenEntryPoint` bean.  仅当不使用其他身份验证机制时才使用后者 (它的唯一功能是返回 HTTP 403 错误代码) .
还将创建一个 `PreAuthenticatedAuthenticationProvider`,它将用户权限的加载委派给 `UserDetailsService`.

[[nsa-x509-parents]]
===  <x509> 的父元素

* <<nsa-http,http>>

[[nsa-x509-attributes]]
=== <x509> 属性


[[nsa-x509-authentication-details-source-ref]]
* **authentication-details-source-ref**
对 `AuthenticationDetailsSource` 的引用


[[nsa-x509-subject-principal-regex]]
* **subject-principal-regex**
定义一个正则表达式,该正则表达式将用于从证书中提取用户名 (与 `UserDetailsService` 一起使用) .

[[nsa-x509-user-service-ref]]
* **user-service-ref**
如果配置了多个实例,则允许特定的 `UserDetailsService` 与X.509一起使用. 如果未设置,将尝试自动查找并使用合适的实例.

[[nsa-filter-chain-map]]
== <filter-chain-map>
用于通过 FilterChainMap 显式配置 FilterChainProxy 实例

[[nsa-filter-chain-map-attributes]]
=== <filter-chain-map> 属性


[[nsa-filter-chain-map-request-matcher]]
* **request-matcher**
定义用于匹配传入请求的策略. 当前,选项为 `ant` (用于ant路径模式) ,`regex` 用于正则表达式,`ciRegex` 用于不区分大小写的正则表达式.

[[nsa-filter-chain-map-children]]
===  <filter-chain-map> 的子元素


* <<nsa-filter-chain,filter-chain>>

[[nsa-filter-chain]]
== <filter-chain>
用于内部以定义特定的 URL 模式以及适用于与该模式匹配的 URL 的过滤器列表.  当在列表中组合多个过滤器链元素以配置 FilterChainProxy 时,最特定的模式必须放在列表的顶部,最普通的模式应放在底部.

[[nsa-filter-chain-parents]]
===  <filter-chain> 的父元素


* <<nsa-filter-chain-map,filter-chain-map>>

[[nsa-filter-chain-attributes]]
=== <filter-chain> 属性


[[nsa-filter-chain-filters]]
* **filters**
以逗号分隔的实现过滤器的 Spring bean 引用列表. 值 "none" 表示此 `FilterChain` 不应使用任何过滤器.

[[nsa-filter-chain-pattern]]
* **pattern**
一种与<<nsa-filter-chain-map-request-matcher,request-matcher>> 结合创建 RequestMatcher 的模式

[[nsa-filter-chain-request-matcher-ref]]
* **request-matcher-ref**
对 `RequestMatcher` 的引用,该引用将用于确定是否应调用 `filter` 属性中的任何 `Filter`.

[[nsa-filter-security-metadata-source]]
== <filter-security-metadata-source>
用于显式配置 FilterSecurityMetadataSource bean 与 FilterSecurityInterceptor 一起使用.  通常仅在显式配置 FilterChainProxy 而不是使用 `<http>` 元素时才需要.  使用的拦截 URL 元素应仅包含模式,方法和访问属性.  其他任何情况都将导致配置错误.

[[nsa-filter-security-metadata-source-attributes]]
=== <filter-security-metadata-source> 属性


[[nsa-filter-security-metadata-source-id]]
* **id**
Bean 标识符,用于引用上下文中其他位置的 Bean.


[[nsa-filter-security-metadata-source-request-matcher]]
* **request-matcher**
定义用于匹配传入请求的策略. 当前,选项为 `ant` (用于 ant 路径模式) ,`regex` 用于正则表达式,`ciRegex` 用于不区分大小写的正则表达式.


[[nsa-filter-security-metadata-source-use-expressions]]
* **use-expressions**
允许在 `<intercept-url>` 元素的 `access` 属性中使用表达式,而不是传统的配置属性列表.  默认为 `true`.  如果启用,则每个属性应包含一个布尔表达式.  如果表达式的计算结果为 `true`,则将授予访问权限.

[[nsa-filter-security-metadata-source-children]]
===  <filter-security-metadata-source> 的子元素


* <<nsa-intercept-url,intercept-url>>