[[io.hazelcast]]
== Hazelcast
如果  https://hazelcast.com/[Hazelcast] 在 classpath 上并有合适的配置,则 Spring Boot 会自动配置一个可以在应用程序中注入的 `HazelcastInstance`.

Spring Boot 首先尝试通过检查以下配置选项来创建一个客户端:

* 存在 `com.hazelcast.client.config.ClientConfig` bean.
* `spring.hazelcast.config` 属性定义的配置文件.
* 存在 `hazelcast.client.config` 系统属性.
* 工作目录中或 classpath 根目录下的 `hazelcast-client.xml`.
* 工作目录中或 classpath 根目录下的 `hazelcast-client.yaml`  (或 `hazelcast-client.yml`) .

WARNING: Spring Boot 支持 Hazelcast 4 和 Hazelcast 3. 如果降级到 Hazelcast 3, 应该将 `hazelcast-client` 添加到类路径中以配置客户端.

如果无法创建客户端，则 Spring Boot 尝试配置嵌入式服务器.

如果定义了 `com.hazelcast.config.Config` bean,则 Spring Boot 会使用它. 如果您的配置定义了实例名称,Spring Boot 会尝试查找现有的实例,而不是创建新实例.

您还可以指定通过配置使用的 Hazelcast 配置文件,如以下示例所示:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  hazelcast:
	    config: "classpath:config/my-hazelcast.xml"
----

否则,Spring Boot 会尝试从默认位置查找 Hazelcast 配置: 工作目录或 classpath 根目录中的 `hazelcast.xml`,或相同位置中的 `.yaml`/`.yml` 文件.  我们还检查是否设置了 `hazelcast.config` 系统属性.  有关更多详细信息,请参见 https://docs.hazelcast.org/docs/latest/manual/html-single/[Hazelcast documentation].

TIP: 默认情况下，支持 Hazelcast 组件上的  `@SpringAware` 。
可以通过声明 `@Order` 大于零的  `HazelcastConfigCustomizer` bean 来覆盖 `ManagementContext` 。

NOTE: Spring Boot 还为 <<io#io.caching.provider.hazelcast,Hazelcast 提供了缓存支持>>. 如果启用了缓存,`HazelcastInstance` 将自动包装在 `CacheManager` 实现中.
