[[jc-authentication-authenticationprovider]]
== AuthenticationProvider

=== AuthenticationProvider Java 配置
您可以通过一个自定义的 `AuthenticationProvider` 为bean定义自定义身份验证。 例如， 下面这个例子假设自定义身份验证 `SpringAuthenticationProvider` 实现了 `AuthenticationProvider`:

NOTE: 仅在未填充 `AuthenticationManagerBuilder` 时使用

[source,java]
----
@Bean
public SpringAuthenticationProvider springAuthenticationProvider() {
	return new SpringAuthenticationProvider();
}
----

[[ns-auth-providers]]
=== AuthenticationProvider XML 配置
实际上，与添加到应用程序上下文文件中的几个名称相比，您将需要更具扩展性的用户信息源。
您很可能希望将用户信息存储在数据库或LDAP服务器之类的文件中。
LDAP命名空间配置将在<<ldap,LDAP 一章>>中介绍，因此在此不再赘述。 如果您在应用程序上下文中具有Spring Security的 `UserDetailsService` 的自定义实现（称为 "myUserDetailsService"），则可以使用以下方法对此进行身份验证

[source,xml]
----

<authentication-manager>
	<authentication-provider user-service-ref='myUserDetailsService'/>
</authentication-manager>

----

如果要使用数据库，则可以使用

[source,xml]
----
<authentication-manager>
<authentication-provider>
	<jdbc-user-service data-source-ref="securityDataSource"/>
</authentication-provider>
</authentication-manager>
----

其中，"securityDataSource" 是应用程序上下文中的 `DataSource` bean的名称，指向包含标准Spring Security<<user-schema,用户表的数据库>>。 另外，您可以配置一个Spring Security `JdbcDaoImpl` bean并使用 `user-service-ref` 属性指向它：

[source,xml]
----
<authentication-manager>
<authentication-provider user-service-ref='myUserDetailsService'/>
</authentication-manager>

<beans:bean id="myUserDetailsService"
	class="org.springframework.security.core.userdetails.jdbc.JdbcDaoImpl">
<beans:property name="dataSource" ref="dataSource"/>
</beans:bean>
----

您还可以如下使用标准的 `AuthenticationProvider` bean：

[source,xml]
----

<authentication-manager>
	<authentication-provider ref='myAuthenticationProvider'/>
</authentication-manager>

----

其中 `myAuthenticationProvider` 是您的应用程序上下文中实现 `AuthenticationProvider` 的bean的名称。 您可以使用多个身份验证提供程序元素，在这种情况下，将按照声明它们的顺序来查询提供程序。 有关如何使用命名空间配置Spring Security `AuthenticationManager` 的更多信息，
请参见<<ns-auth-manager,第10.11节 "身份验证管理器和命名空间">>。
