[[basic]]
== Basic 和 Digest 认证
Basic 和 digest authentication 是在Web应用程序中流行的替代身份验证机制。
Basic 认证通常与无状态客户端一起使用，无状态客户端会在每个请求中传递其凭据。
通常将其与基于表单的身份验证结合使用，在这种情况下，既可以通过基于浏览器的用户界面也可以通过网络服务来使用应用程序。 但是，Basic 认证以纯文本形式传输密码，因此，仅应在诸如HTTPS之类的加密传输层上实际使用该密码。

[[basic-processing-filter]]
=== BasicAuthenticationFilter
`BasicAuthenticationFilter` 负责处理HTTP请求头中提供的基本身份验证凭据。 这可用于验证Spring远程协议（例如H essian 和 Burlap）以及普通浏览器用户代理（例如Firefox和Internet Explorer）发出的调用。
RFC 1945第11节定义了管理HTTP基本身份验证的标准，并且 `BasicAuthenticationFilter` 符合此RFC。 Basic 认证是一种有吸引力的身份验证方法，因为它已广泛部署在用户代理中，并且实现极其简单（它只是在HTTP头中指定的 username:password 的Base64编码）。

[[basic-config]]
=== 配置
要实现 HTTP Basic 认证, 你需要将 `BasicAuthenticationFilter` 添加到过滤器链中.
应用程序上下文应包含 `BasicAuthenticationFilter` 及其必需的协作者：


[source,xml]
----
<bean id="basicAuthenticationFilter"
class="org.springframework.security.web.authentication.www.BasicAuthenticationFilter">
<property name="authenticationManager" ref="authenticationManager"/>
<property name="authenticationEntryPoint" ref="authenticationEntryPoint"/>
</bean>

<bean id="authenticationEntryPoint"
class="org.springframework.security.web.authentication.www.BasicAuthenticationEntryPoint">
<property name="realmName" value="Name Of Your Realm"/>
</bean>
----

配置的 `AuthenticationManager` 处理每个身份验证请求。 如果身份验证失败，则将使用配置的 `AuthenticationEntryPoint` 重试身份验证过程。 通常，您将过滤器与 `BasicAuthenticationEntryPoint` 结合使用，后者会返回带有适当标头的401响应以重试HTTP Basic身份验证。 如果身份验证成功，则照常将生成的 `Authentication` 对象放置到 `SecurityContextHolder` 中。

如果身份验证事件成功，或者由于HTTP头不包含受支持的身份验证请求而未尝试进行身份验证，则过滤器链将照常继续。 唯一的中断过滤器链的方法是验证失败并调用 `AuthenticationEntryPoint`。
