[[jc-form]]
== 表单登录

=== 表单登录 Java Configuration

你可能会想知道系统提示您登录表单从哪里来的，因为我们都没有提供任何的HTML或JSP文件。由于Spring Security的默认配置并没有明确设定一个登录页面的URL，Spring Security自动生成一个，基于这个功能被启用，使用默认URL处理登录的提交内容，登录后跳转的URL等等。

自动生成的登录页面可以方便应用的快速启动和运行，大多数应用程序都需要提供自己的登录页面。当我们想要更改默认配置时，我们可以通过扩展它来定制我们前面提到的 `WebSecurityConfigurerAdapter`，如下所示：

[source,java]
----
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
	// ...
}
----

And then override the `configure` method as seen below:

[source,java]
----
protected void configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests(authorizeRequests ->
		    authorizeRequests
			    .anyRequest().authenticated()
		)
		.formLogin(formLogin ->
		    formLogin
			    .loginPage("/login") // <1>
			    .permitAll()         // <2>
	    );
}
----

<1> 更新的配置指定登录页面的位置。
<2> 我们必须授予所有用户（即未经身份验证的用户）访问我们登录页面的权限。  `formLogin().permitAll()`  方法允许向所有用户授予与基于表单的登录相关联的所有URL的访问权限。

下面是使用JSP为当前配置实现的示例登录页面：

NOTE: 下面的登录页面代表我们当前的配置。 如果某些默认设置不能满足我们的需求，我们可以轻松地更新我们的配置。

[source,html]
----
<c:url value="/login" var="loginUrl"/>
<form action="${loginUrl}" method="post">       <1>
	<c:if test="${param.error != null}">        <2>
		<p>
			Invalid username and password.
		</p>
	</c:if>
	<c:if test="${param.logout != null}">       <3>
		<p>
			You have been logged out.
		</p>
	</c:if>
	<p>
		<label for="username">Username</label>
		<input type="text" id="username" name="username"/>	<4>
	</p>
	<p>
		<label for="password">Password</label>
		<input type="password" id="password" name="password"/>	<5>
	</p>
	<input type="hidden"                        <6>
		name="${_csrf.parameterName}"
		value="${_csrf.token}"/>
	<button type="submit" class="btn">Log in</button>
</form>
----

<1> 一个POST请求到 `/login` 用来验证用户
<2> 如果参数有 `error`, 验证尝试失败
<3> 如果请求参数 `logout` 存在,则登出
<4> 登录名参数必须被命名为 __username__
<5> T码参数必须被命名为 __password__
<6> CSRF参数，了解更多查阅后续 包括<<servlet-csrf-include,包含CSRF令牌>> 和<<csrf,第5.1.1节 跨站点请求伪造（CSRF）>> 相关章节

=== 表单登录 XML 配置

[[ns-form-and-basic]]
==== Form and Basic 登录选项
你可能会想知道系统提示您登录表单从哪里来的，因为我们都没有提供任何的HTML或JSP文件。由于Spring Security的默认配置并没有明确设定一个登录页面的URL，Spring Security自动生成一个，基于这个功能被启用，使用默认URL处理登录的提交内容，登录后跳转的URL等等。

但是，命名空间提供了大量支持，可让您自定义这些选项。 例如，如果要提供自己的登录页面，则可以使用：

[source,xml]
----
<http>
<intercept-url pattern="/login.jsp*" access="IS_AUTHENTICATED_ANONYMOUSLY"/>
<intercept-url pattern="/**" access="ROLE_USER" />
<form-login login-page='/login.jsp'/>
</http>
----

还要注意，我们添加了一个额外的 `intercept-url` 元素，表示对登录页面的任何请求都应对匿名用户可用 footnote:[See the chapter on pass:specialcharacters,macros[<<anonymous>>]]，并且对于如何处理值 `IS_AUTHENTICATED_ANONYMOUSLY` 的更多详细信息，还可以使用  <<authz-authenticated-voter,AuthenticatedVoter>>  类。
否则，请求将使用 /** 模式匹配，并且无法访问登录页面本身！ 这是一个常见的配置错误，将导致应用程序中的无限循环。 如果您的登录页面受到保护，Spring Security将在日志中发出警告。 通过为模式定义一个单独的http元素，也可以使所有匹配特定模式的请求完全绕过安全过滤器链，如下所示：


[source,xml]
----
<http pattern="/css/**" security="none"/>
<http pattern="/login.jsp*" security="none"/>

<http use-expressions="false">
<intercept-url pattern="/**" access="ROLE_USER" />
<form-login login-page='/login.jsp'/>
</http>
----

从Spring Security 3.1开始，现在可以使用多个 `http` 元素为不同的请求模式定义单独的安全过滤器链配置。 如果从 `http` 元素中省略了 `pattern` 属性，则它匹配所有请求。
创建一个不安全的模式是此语法的一个简单示例，其中该模式被映射到一个空的过滤器链 footnote:[例如，使用多个 `<http>` 元素是一项重要功能，例如，允许命名空间同时支持同一应用程序中的有状态和无状态路径。 先前的语法在 `intercept-url` 元素上使用属性 `filters ="none"` 与此更改不兼容，并且在3.1中不再受支持。]。

我们将在<<filter-chains-with-ns,安全过滤器链>>一章中详细介绍这种新语法。

必须意识到，这些不安全的请求将完全不考虑任何与Spring Security Web相关的配置或诸如 `require-channel` 之类的其他属性，因此您将无法在请求期间访问当前用户的信息或调用安全方法。 如果您仍然希望应用安全过滤器链，请使用 `access ='IS_AUTHENTICATED_ANONYMOUSLY'` 作为替代。

如果要使用基本身份验证而不是表单登录，则将配置更改为

[source,xml]
----
<http use-expressions="false">
<intercept-url pattern="/**" access="ROLE_USER" />
<http-basic />
</http>
----

然后，基本身份验证将具有优先权，并将在用户尝试访问受保护资源时用于提示登录。 如果您希望使用表单登录，则在此配置中仍然可用，例如通过嵌入在另一个网页中的登录表单。
