[[servlet-authentication]]
= 认证

Spring Security提供了对身份验证的全面支持。 本节讨论：

[[servlet-authentication-architecture]]
*架构组件*

本部分描述了Servlet身份验证中使用的Spring Security的主要架构组件。 如果您需要解释这些部分如何组合的具体流程，请查看“身份验证机制”特定部分。

* <<servlet-authentication-securitycontextholder>> - Spring Security在其中存储 `SecurityContextHolder`，用于存储通过<<authentication,身份验证>>的人员的详细信息。 .
* <<servlet-authentication-securitycontext>> - 从 `SecurityContextHolder` 获得，并包含当前经过身份验证的用户的 `Authentication` 。
* <<servlet-authentication-authentication>> - 可以是 `AuthenticationManager` 的输入，以提供用户提供的用于身份验证的凭据或来自 `SecurityContext` 的当前用户。
* <<servlet-authentication-granted-authority>> - 在`Authentication` 授予委托人的权限（即角色，作用域等）
* <<servlet-authentication-authenticationmanager>> -  定义Spring Security的过滤器如何执行<<authentication,身份验证>>的API。  .
* <<servlet-authentication-providermanager>> -  `AuthenticationManager` 的最常见实现。
* <<servlet-authentication-authenticationprovider>> - 由 `ProviderManager` 用于执行特定类型的身份验证。
* <<servlet-authentication-authenticationentrypoint>> -带 `AuthenticationEntryPoint` 的请求凭据-用于从客户端请求凭据（即重定向到登录页面，发送 WWW-Authenticate 响应等）
* <<servlet-authentication-abstractprocessingfilter>> - 用于验证的基本过滤器。 这也为高级别的身份验证流程以及各个部分如何协同工作提供了一个好主意。

[[servlet-authentication-mechanisms]]
*认证机制*

// FIXME: brief description

* <<servlet-authentication-unpwd,Username and Password>> - 如何使用用户名/密码进行身份验证
* <<oauth2login,OAuth 2.0 Login>> - 使用OpenID Connect和非标准OAuth 2.0登录进行OAuth 2.0登录（即GitHub）
* <<servlet-saml2,SAML 2.0 Login>> - SAML 2.0登录
* <<servlet-cas,Central Authentication Server (CAS)>> - 中央身份验证服务器（CAS）支持
* <<servlet-rememberme, Remember Me>> - 如何记住用户过期的会话
* <<servlet-jaas, JAAS Authentication>> - 使用JAAS进行认证
* <<servlet-openid,OpenID>> - OpenID身份验证（请勿与OpenID Connect混淆）
* <<servlet-preauth>> - 使用诸如 https://www.siteminder.com/[SiteMinder] 或Java EE安全性之类的外部机制进行身份验证，但仍使用Spring Security进行授权并防范常见漏洞。
* <<servlet-x509,X509 Authentication>> - X509验证

// FIXME: Add other mechanisms

// We intentionally do not increase leveloffset, this is just for organization vs document structure
include::architecture/index.adoc[]

include::unpwd/index.adoc[leveloffset=+1]

include::session-management.adoc[]

include::rememberme.adoc[]

include::openid.adoc[]

include::anonymous.adoc[]

include::preauth.adoc[]

include::jaas.adoc[]

include::cas.adoc[]

include::x509.adoc[]

include::runas.adoc[]

include::logout.adoc[]
