[[servlet-jaas]]
== Java Authentication Authorization Service（JAAS，Java验证和授权API） 提供者


=== 概述
Spring Security提供一个包可以将身份验证请求委托给Java身份验证和授权服务(JAAS).这个包是在下面详细讨论.


[[jaas-abstractjaasauthenticationprovider]]
=== AbstractJaasAuthenticationProvider
`AbstractJaasAuthenticationProvider` 提供了 JAAS `AuthenticationProvider` 实现的基础。 子类实现必须创建 `LoginContext` 的方法。 `AbstractJaasAuthenticationProvider` 具有许多可以注入其中的依赖，下面将对其进行讨论。

[[jaas-callbackhandler]]
==== JAAS 回调处理
大多数JAAS `LoginModule` 都需要某种回调。 这些回调通常用于从用户中获取用户名和密码。

在Spring Security部署中，Spring Security负责此用户交互（通过身份验证机制）。 因此，在将身份验证请求委派给JAAS时，Spring Security的身份验证机制将已经完全填充了 `Authentication` 对象，其中包含JAAS `LoginModule` 所需的所有信息。

因此，Spring Security的JAAS包提供了两个默认的回调处理程序，`JaasNameCallbackHandler` 和 `JaasPasswordCallbackHandler`。 这些回调处理程序中的每一个都实现 `JaasAuthenticationCallbackHandler`。 在大多数情况下，无需了解内部机制即可简单地使用这些回调处理程序。

对于那些需要完全控制回调行为的用户，内部 `AbstractJaasAuthenticationProvider` 将这些 `JaasAuthenticationCallbackHandler` 封装为 `InternalCallbackHandler`。 `InternalCallbackHandler` 是实际实现JAAS常规 `CallbackHandler` 接口的类。
每当使用JAAS `LoginModule` 时，都会向其传递配置了 `InternalCallbackHandler` 的应用程序上下文列表。 如果 `LoginModule` 请求针对 `InternalCallbackHandler` 的回调，则该回调又传递给正在包装的 `JaasAuthenticationCallbackHandler`。

[[jaas-authoritygranter]]
==== JAAS 授权者
JAAS与主体合作。 JAAS中甚至将 "roles" 表示为主体。 另一方面，Spring Security与 `Authentication` 对象一起使用。
每个 `Authentication` 对象都包含一个主体和多个 `GrantedAuthority`。 为了促进这些不同概念之间的映射，Spring Security的JAAS软件包包含了 `AuthorityGranter` 接口。

`AuthorityGranter` 负责检查JAAS主体并返回一组 `String`，它们代表分配给主体的授权。 对于每个返回的授权字符串，`AbstractJaasAuthenticationProvider` 创建一个 `JaasGrantedAuthority`（它实现Spring Security的 `GrantedAuthority` 接口），其中包含授权字符串和已通过 `AuthorityGranter` 的JAAS主体。
`AbstractJaasAuthenticationProvider` 通过首先使用JAAS `LoginModule` 成功验证用户的凭据，然后访问它返回的 `LoginContext` 来获取JAAS主体。 调用 `LoginContext.getSubject().getPrincipals()`，并将每个结果主体传递给针对 `AbstractJaasAuthenticationProvider.setAuthorityGranters(List)` 属性定义的每个 `AuthorityGranter`。

鉴于每个JAAS主体都具有特定于实现的含义，因此Spring Security不包含任何生产 `AuthorityGranter`。 但是，单元测试中有一个 `TestAuthorityGranter`，它演示了一个简单的 `AuthorityGranter` 实现。

[[jaas-defaultjaasauthenticationprovider]]
=== DefaultJaasAuthenticationProvider

`DefaultJaasAuthenticationProvider` 允许将JAAS配置对象作为依赖注入到该对象中。 然后，它使用注入的JAAS配置创建 `LoginContext`。 这意味着 `DefaultJaasAuthenticationProvider` 不像 `JaasAuthenticationProvider` 那样绑定任何特定的 `Configuration` 实现。

[[jaas-inmemoryconfiguration]]
==== InMemoryConfiguration
为了易于将配置注入 `DefaultJaasAuthenticationProvider`，提供了一个名为 `InMemoryConfiguration` 的默认内存实现。
实现构造函数接受Map，其中每个键代表一个登录配置名称，该值代表一个 `AppConfigurationEntry` 数组。 `InMemoryConfiguration` 还支持默认的 `AppConfigurationEntry` 对象数组，如果在提供的Map中找不到映射，则将使用该对象。 有关详细信息，请参阅 `InMemoryConfiguration` 的类级别javadoc。

[[jaas-djap-config]]
==== DefaultJaasAuthenticationProvider 示例配置
尽管 `InMemoryConfiguration` 的Spring配置比标准JAAS配置文件更冗长，但与 `DefaultJaasAuthenticationProvider` 结合使用时，它比 `JaasAuthenticationProvider` 更灵活，因为它不依赖于默认的 `Configuration` 实现。

下面提供了使用 `InMemoryConfiguration` 的 `DefaultJaasAuthenticationProvider` 配置示例。 请注意，配置的自定义实现也可以轻松地注入到 `DefaultJaasAuthenticationProvider` 中。

[source,xml]
----

<bean id="jaasAuthProvider"
class="org.springframework.security.authentication.jaas.DefaultJaasAuthenticationProvider">
<property name="configuration">
<bean class="org.springframework.security.authentication.jaas.memory.InMemoryConfiguration">
<constructor-arg>
	<map>
	<!--
	SPRINGSECURITY is the default loginContextName
	for AbstractJaasAuthenticationProvider
	-->
	<entry key="SPRINGSECURITY">
	<array>
	<bean class="javax.security.auth.login.AppConfigurationEntry">
		<constructor-arg value="sample.SampleLoginModule" />
		<constructor-arg>
		<util:constant static-field=
			"javax.security.auth.login.AppConfigurationEntry$LoginModuleControlFlag.REQUIRED"/>
		</constructor-arg>
		<constructor-arg>
		<map></map>
		</constructor-arg>
		</bean>
	</array>
	</entry>
	</map>
	</constructor-arg>
</bean>
</property>
<property name="authorityGranters">
<list>
	<!-- You will need to write your own implementation of AuthorityGranter -->
	<bean class="org.springframework.security.authentication.jaas.TestAuthorityGranter"/>
</list>
</property>
</bean>

----



[[jaas-jaasauthenticationprovider]]
=== JaasAuthenticationProvider
`JaasAuthenticationProvider` 假定默认配置是ConfigFile的实例。 进行此假设是为了尝试更新配置。 然后，`JaasAuthenticationProvider` 使用默认的 `Configuration` 创建 https://download.oracle.com/javase/1.4.2/docs/guide/security/jaas/spec/com/sun/security/auth/login/ConfigFile.html[ ConfigFile].

假设我们有一个JAAS登录配置文件 `/WEB-INF/login.conf`，其内容如下：

[source,txt]
----
JAASTest {
	sample.SampleLoginModule required;
};
----

像所有Spring Security bean一样，`JaasAuthenticationProvider` 是通过应用程序上下文配置的。 以下定义将对应于上述JAAS登录配置文件：

[source,xml]
----

<bean id="jaasAuthenticationProvider"
class="org.springframework.security.authentication.jaas.JaasAuthenticationProvider">
<property name="loginConfig" value="/WEB-INF/login.conf"/>
<property name="loginContextName" value="JAASTest"/>
<property name="callbackHandlers">
<list>
<bean
	class="org.springframework.security.authentication.jaas.JaasNameCallbackHandler"/>
<bean
	class="org.springframework.security.authentication.jaas.JaasPasswordCallbackHandler"/>
</list>
</property>
<property name="authorityGranters">
	<list>
	<bean class="org.springframework.security.authentication.jaas.TestAuthorityGranter"/>
	</list>
</property>
</bean>
----

[[jaas-apiprovision]]
=== Subject 运行
如果配置, `JaasApiIntegrationFilter` 将试图运行 `JaasAuthenticationToken` 上的 `Subject`。这意味着可以使用访问 `Subject`:

[source,java]
----
Subject subject = Subject.getSubject(AccessController.getContext());
----

这种集成可以很容易地使用<<nsa-http-jaas-api-provision,jaas-api-provision>>配置属性。当集成遗留或外部依赖JAAS Subject API被填充,这个特性很有用
This integration can easily be configured using the  attribute.