[[runas]]
== Run-As 验证替换

[[runas-overview]]
=== 概述
`AbstractSecurityInterceptor` 能够暂时取代 `Authentication` 对象在 `SecurityContext` 和 `SecurityContextHolder` 安全对象回调阶段.
这只发生如果最初的 `Authentication` 对象是成功处理的 `AuthenticationManager` 和 `AccessDecisionManager.RunAsManager` 将指示更换 `Authentication` 对象,如果有的话,应该使用在 `SecurityInterceptorCallback`.

通过在安全对象回调阶段临时替换 `Authentication` 对象，安全调用将能够调用需要不同身份验证和授权凭证的其他对象.  它还将能够对特定的 `GrantedAuthority` 对象执行任何内部安全检查.
由于 Spring Security 提供了许多帮助程序类，这些类根据 `SecurityContextHolder` 的内容自动配置远程协议，因此这些运行方式替换在调用远程Web服务时特别有用

[[runas-config]]
=== 配置
Spring Security 提供 `RunAsManager` 接口:

[source,java]
----
Authentication buildRunAs(Authentication authentication, Object object,
	List<ConfigAttribute> config);

boolean supports(ConfigAttribute attribute);

boolean supports(Class clazz);
----

第一个方法返回 `Authentication` 对象应该取代现有的身份验证的对象方法调用的持续时间.
如果方法返回 `null`,它表明你没有更换. 第二种方法是使用 `AbstractSecurityInterceptor` 启动验证配置属性的一部分.  `supports(Class)` 的方法被调用以确保安全拦截器将安全对象实现配置的 `RunAsManager` 支持的类型安全拦截器.

Spring Security 提供了 `RunAsManager` 的一种具体实现.  如果任何 `ConfigAttribute以RUN_AS_` 开头，则 `RunAsManagerImpl` 类将返回替换 `RunAsUserToken`.  如果找到任何这样的 `ConfigAttribute`，
则替换的 `RunAsUserToken` 将包含与原始 `Authentication` 对象相同的主体，凭据和授予的权限，以及每个 RUN_AS_ `ConfigAttribute` 的新 `SimpleGrantedAuthority`.  每个新的 `SimpleGrantedAuthority` 将以 `ROLE_` 为前缀，后跟 `RUN_AS` `ConfigAttribute`.  例如，`RUN_AS_SERVER` 将导致替换的 `RunAsUserToken` 包含 `ROLE_RUN_AS_SERVER` 授予的权限.

替换 `RunAsUserToken` 就像其他任何 `Authentication` 对象一样.  它需要由 `AuthenticationManager` 进行身份验证，可能需要通过委派给合适的 `AuthenticationProvider` 来进行.  `RunAsImplAuthenticationProvider` 执行此类身份验证.  它只是简单地接受任何出现的 `RunAsUserToken`.

为了确保恶意代码不会创建 `RunAsUserToken` 并将其提供给 `RunAsImplAuthenticationProvider` 保证接受，密钥的哈希存储在所有生成的令牌中.  使用相同的密钥在Bean上下文中创建 `RunAsManagerImpl` 和 `RunAsImplAuthenticationProvider`:

[source,xml]
----

<bean id="runAsManager"
	class="org.springframework.security.access.intercept.RunAsManagerImpl">
<property name="key" value="my_run_as_password"/>
</bean>

<bean id="runAsAuthenticationProvider"
	class="org.springframework.security.access.intercept.RunAsImplAuthenticationProvider">
<property name="key" value="my_run_as_password"/>
</bean>
----



通过使用相同的密钥，可以验证每个 `RunAsUserToken` 是否由批准的 `RunAsManagerImpl` 创建.  出于安全原因，`RunAsUserToken` 在创建后是不可变的