[[servlet-x509]]
== X.509 认证


[[x509-overview]]
=== 概述
最常用的 X.509 证书身份验证是验证服务器在使用SSL的身份,从浏览器通常在使用 HTTPS. 浏览器会自动检查服务器证书的已发布(即数字签名)的一个受信任的证书颁发机构的列表维护.

您还可以使用SSL与 "mutual authentication";服务器将请求从客户端作为一个有效的证书的SSL握手. 服务器将验证客户端通过检查其签署的证书是一个可接受的权威. 如果提供了一个有效的证书,它可以通过 servlet API的应用程序. Spring Security X.509 模块提取证书使用一个过滤器. 它将证书映射到一个应用程序用户和加载用户的组授予机关使用标准的 Spring 安全基础设施.

在尝试将其与 Spring Security 结合使用之前,您应该熟悉使用证书并为 Servlet 容器设置客户端身份验证.  大多数工作是在创建和安装合适的证书和密钥.
例如,如果您使用的是 Tomcat,请阅读 https://tomcat.apache.org/tomcat-6.0-doc/ssl-howto.html[https://tomcat.apache.org/tomcat-6.0-doc/ssl-howto.html] 上的说明.  在使用 Spring Security 进行尝试之前,一定要先做好这项工作,这一点很重要

=== 向您的Web应用程序添加X.509身份验证
启用X.509客户端身份验证非常简单.  只需将 `<x509/>` 元素添加到您的http安全命名空间配置中即可.

[source,xml]
----
<http>
...
	<x509 subject-principal-regex="CN=(.*?)," user-service-ref="userService"/>;
</http>
----

元素具有两个可选属性:

* `subject-principal-regex`.
用于从证书主题名称中提取用户名的正则表达式.  默认值如上所示.  这是用户名,该用户名将传递给 `UserDetailsService` 以加载用户的权限.
* `user-service-ref`.
这是与X.509一起使用的 `UserDetailsService` 的bean ID.  如果您的应用程序上下文中仅定义了一个,则不需要.

`subject-principal-regex` 应该包含一个组.  例如,默认表达式 "CN=(.*?)," 与通用名称字段匹配.  因此,如果证书中的使用者名称为 "CN=Jimi Hendrix, OU=...",则用户名称为 "Jimi Hendrix".
匹配不区分大小写.  因此,"emailAddress=(+.*?+),"  将与 "EMAILADDRESS=jimi@hendrix.org,CN=..." 匹配,并给出用户名 "jimi@hendrix.org".  如果客户端出示证书并且成功提取了有效的用户名,则安全上下文中应该有一个有效的 `Authentication` 对象.  如果找不到证书,或者找不到相应的用户,则安全上下文将保持为空.  这意味着您可以轻松地将X.509身份验证与其他选项 (例如基于表单的登录名) 一起使用.

[[x509-ssl-config]]
=== 在Tomcat中设置SSL
Spring Security 项目的 `samples/certificate` 目录中有一些预先生成的证书.  如果您不想生成自己的SSL,可以使用它们启用SSL进行测试.  文件 `server.jks` 包含服务器证书,私钥和颁发证书颁发机构的证书.  示例应用程序中还为用户提供了一些客户端证书文件.  您可以将它们安装在浏览器中以启用SSL客户端身份验证.

要运行具有 SSL 支持的 tomcat,请将 `server.jks` 文件拖放到tomcat `conf` 目录中,并将以下连接器添加到 `server.xml` 文件中

[source,xml]
----

<Connector port="8443" protocol="HTTP/1.1" SSLEnabled="true" scheme="https" secure="true"
			clientAuth="true" sslProtocol="TLS"
			keystoreFile="${catalina.home}/conf/server.jks"
			keystoreType="JKS" keystorePass="password"
			truststoreFile="${catalina.home}/conf/server.jks"
			truststoreType="JKS" truststorePass="password"
/>

----

如果您仍然希望 SSL 连接成功,即使客户端不提供证书,也可以将 `clientAuth` 设置为 `want`.  除非您使用非X.509身份验证机制 (例如表单身份验证) ,否则没有证书的客户端将无法访问 Spring Security 保护的任何对象.
