// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[dependency_management_for_java_projects]]
= 管理 JVM 项目的依赖关系

本章解释了如何将基本的依赖管理概念应用到基于 JVM 的项目中。 有关依赖管理的详细介绍，请参阅<<core_dependency_management.adoc#,Gradle 中的依赖管理>>。

[[sec:setting_up_a_standard_build_script_java_tutorial]]
== 剖析构建脚本

让我们看一个非常简单的基于 JVM 项目的构建脚本。
它应用了<<java_library_plugin.adoc#java_library_plugin,Java Library plugin>>，自动引入标准项目布局，提供执行典型工作的任务和对依赖管理的充分支持。

.Dependency declarations for a JVM-based project
====
include::{snippets-dir}/artifacts/dependencyBasics/groovy/build.gradle[]
include::{snippets-dir}/artifacts/dependencyBasics/kotlin/build.gradle.kts[]
====

link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:dependencies(groovy.lang.Closure)[Project.dependencies{}] 代码块声明 Hibernate core 3.6.7.Final  是编译项目的源代码所必需的。
它还指出，编译项目的测试需要 junit &gt;= 4.0 。 所有的依赖都应该在 Maven 中央存储库中查找，如 link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:repositories(groovy.lang.Closure)[Project.repositories{}]。
以下为更详细地解释。

[[sec:module_dependencies_java_tutorial]]
== 声明模块依赖

您可以声明各种 <<declaring_dependencies.adoc#sec:dependency-types,类型的依赖>>。 其中一种类型是 _模块依赖_。
<<declaring_dependencies.adoc#sub:module_dependencies,模块依赖>> 表示对当前构建之外的构建的特定版本的模块的依赖。
模块通常存储在存储库中，例如 Maven Central、企业 Maven 或 Ivy 存储库，或本地文件系统中的目录。

要定义模块依赖，请将其添加到 <<#sec:configurations_java_tutorial,dependency configuration>>：

.Definition of a module dependency
====
include::{snippets-dir}/artifacts/externalDependencies/groovy/build.gradle[tags=define-dependency]
include::{snippets-dir}/artifacts/externalDependencies/kotlin/build.gradle.kts[tags=define-dependency]
====

要了解有关定义依赖的更多信息，请查看 <<declaring_dependencies.adoc#,Declaring Dependencies>>.

[[sec:configurations_java_tutorial]]
== 使用依赖配置

link:{groovyDslPath}/org.gradle.api.artifacts.Configuration.html[Configuration] 是一组命名的依赖和构件。 _configuration_ 有三个主要目的:

声明依赖::
插件使用 configurations，使作者可以轻松地声明在执行插件定义的任务期间，出于各种目的需要哪些其他子项目或外部构件。 例如，插件可能需要 Spring Web 框架依赖来编译源代码。
解析依赖::
插件使用 configurations 来查找（并可能下载）其定义的任务的输入。 例如 Gradle 需要从 Maven Central 下载 Spring Web 框架 JAR 文件。
给使用者暴露构件::
插件使用配置来定义它为其他项目生成的 _artifacts_。 例如，该项目希望将打包在 JAR 文件中的已编译源代码发布到内部 Artifactory 存储库。

考虑到这三个目的，让我们看一下 <<java_library_plugin.adoc#sec:java_library_configurations_graph,Java 库插件定义的标准配置>>。

implementation::
编译项目源代码所需的依赖， _不是_ 项目暴露的 API 的一部分，只在其内部使用。例如，该项目将 Hibernate 用于其内部持久层实现。
api::
编译项目源代码所需的依赖，它们 _是_ 项目公开的 API 的一部分，可以继承。例如，该项目使用 Guava 并在其方法签名中公开带有 Guava 类的公共接口。
testImplementation::
编译和运行项目的测试源代码所需的依赖。例如，该项目决定使用测试框架 JUnit 编写测试代码。

各种插件添加了进一步的标准配置。 您还可以通过  link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:configurations(groovy.lang.Closure)[Project.configurations{}] 在构建中定义自己的自定义配置。
有关定义和自定义依赖配置的详细信息，请参阅 <<declaring_dependencies.adoc#sec:what-are-dependency-configurations,什么是依赖配置>>。

[[sec:repositories_java_tutorial]]
== 声明通用 Java 存储库

Gradle 如何知道在哪里可以找到外部依赖的文件？ Gradle 在 _repository_ 中查找它们。
存储库是由  `group`, `name` 和 `version`. 组织的模块的集合。
Gradle 理解不同的 <<declaring_repositories.adoc#sec:repository-types,repository types>>，例如 Maven 和 Ivy，并支持通过 HTTP 或其他协议访问存储库的各种方式。

默认情况下，Gradle 不定义任何存储库。 您需要在 link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:repositories(groovy.lang.Closure)[Project.repositories{}]  下定义至少一个：

.Usage of Maven central repository
====
include::{snippets-dir}/artifacts/defineRepository/groovy/build.gradle[tags=maven-central]
include::{snippets-dir}/artifacts/defineRepository/kotlin/build.gradle.kts[tags=maven-central]
====

您还可以在本地文件系统上拥有存储库。 这适用于 Maven 和 Ivy 存储库。.

.Usage of a local Ivy directory
====
include::{snippets-dir}/artifacts/defineRepository/groovy/build.gradle[tags=local-ivy-repo]
include::{snippets-dir}/artifacts/defineRepository/kotlin/build.gradle.kts[tags=local-ivy-repo]
====

一个项目可以有多个存储库。 Gradle 将按照指定的顺序在每个存储库中查找依赖，并在包含所请求模块的第一个存储库处停止。

要了解有关定义存储库的更多信息，请查看 <<declaring_repositories.adoc#,Declaring Repositories>>。

[[sec:publishing_artifacts_java_tutorial]]
== 发布构件（artifacts）

要了解有关发布构件的更多信息，请查看 <<publishing_setup.adoc#,publishing plugins>>。