[[webtestclient]]
= WebTestClient
include::../attributes.adoc[]

`WebTestClient` 是围绕  <<web-reactive.adoc#webflux-client, WebClient>> 的薄壳,可用于执行请求并暴露专用的流式API来验证响应.  `WebTestClient` 通过使用<<testing.adoc#mock-objects-web-reactive, mock 请求和响应>>绑定到 `WebFlux` 应用程序,或者它可以通过HTTP连接测试任何Web服务器.

TIP: Kotlin用户: 请参阅<<languages.adoc#kotlin-webtestclient-issue, 本节>>与 `WebTestClient` 的使用有关.


[[webtestclient-setup]]
== 设置

要创建 `WebTestClient`,必须选择多个服务器设置选项之一.  实际上,您是在配置WebFlux应用程序以绑定到或使用URL连接到正在运行的服务器.



[[webtestclient-controller-config]]
=== 绑定到控制器

以下示例显示如何创建服务器设置以一次测试一个 `@Controller` :

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	client = WebTestClient.bindToController(new TestController()).build();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	client = WebTestClient.bindToController(TestController()).build()
----

前面的示例加载<<web-reactive.adoc#webflux-config, WebFlux Java配置>>并注册给定的控制器.  通过使用模拟请求和响应对象,可以在没有HTTP服务器的情况下测试生成的WebFlux应用程序.  构建器上有更多方法可以定制默认WebFlux Java配置.

[[webtestclient-fn-config]]
=== 绑定到路由方法

以下示例显示如何通过<<web-reactive.adoc#webflux-fn, RouterFunction>>设置服务器:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	RouterFunction<?> route = ...
	client = WebTestClient.bindToRouterFunction(route).build();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val route: RouterFunction<*> = ...
	val client = WebTestClient.bindToRouterFunction(route).build()
----

在内部,配置被传递到 `RouterFunctions.toWebHandler`.  通过使用模拟请求和响应对象,可以在没有HTTP服务器的情况下测试生成的WebFlux应用程序.

[[webtestclient-context-config]]
=== 绑定到 `ApplicationContext`

以下示例显示了如何从应用程序或其部分子集的Spring配置中设置服务器:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@SpringJUnitConfig(WebConfig.class) // <1>
	class MyTests {

		WebTestClient client;

		@BeforeEach
		void setUp(ApplicationContext context) {  // <2>
			client = WebTestClient.bindToApplicationContext(context).build(); // <3>
		}
	}
----
<1> 指定要加载的配置
<2> 注入配置
<3> 创建 `WebTestClient`

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@SpringJUnitConfig(WebConfig::class) // <1>
	class MyTests {

		lateinit var client: WebTestClient

		@BeforeEach
		fun setUp(context: ApplicationContext) { // <2>
			client = WebTestClient.bindToApplicationContext(context).build() // <3>
		}
	}
----
<1> 指定要加载的配置
<2> 注入配置
<3> 创建 `WebTestClient`

在内部,配置被传递到 `WebHttpHandlerBuilder` 以建立请求处理链.  有关更多详细信息,请参见 <<web-reactive.adoc#webflux-web-handler-api, WebHandler API>>.  通过使用模拟请求和响应对象,可以在没有HTTP服务器的情况下测试生成的WebFlux应用程序.

[[webtestclient-server-config]]
=== 绑定到服务器

以下服务器设置选项使您可以连接到正在运行的服务器:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	client = WebTestClient.bindToServer().baseUrl("http://localhost:8080").build();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	client = WebTestClient.bindToServer().baseUrl("http://localhost:8080").build()
----



[[webtestclient-client-config]]
=== 客户端 Builder

除了前面描述的服务器设置选项之外,您还可以配置客户端选项,包括基本URL,默认标头,客户端过滤器等.  这些选项在 `bindToServer` 之后很容易获得.  对于所有其他服务器,您需要使用 `configureClient()` 从服务器配置过渡到客户端配置,如下所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	client = WebTestClient.bindToController(new TestController())
			.configureClient()
			.baseUrl("/test")
			.build();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	client = WebTestClient.bindToController(TestController())
			.configureClient()
			.baseUrl("/test")
			.build()
----


[[webtestclient-tests]]
== 编写测试

`WebTestClient` 提供了与<<web-reactive.adoc#webflux-client, WebClient>>相同的API,直到使用 `exchange()` 执行请求为止.  `exchange()` 之后是链接的API工作流,用于验证响应.

通常,首先声明响应状态和标头,如下所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	client.get().uri("/persons/1")
				.accept(MediaType.APPLICATION_JSON)
				.exchange()
				.expectStatus().isOk()
				.expectHeader().contentType(MediaType.APPLICATION_JSON)
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	client.get().uri("/persons/1")
			.accept(MediaType.APPLICATION_JSON)
			.exchange()
			.expectStatus().isOk()
			.expectHeader().contentType(MediaType.APPLICATION_JSON)
----

然后,您指定如何解码和使用响应主体:

* `expectBody(Class<T>)`: 解码为单个对象
* `expectBodyList(Class<T>)`: 解码并将对象收集到 `List<T>`.
* `expectBody()`: 解码为 `byte[]`  以 <<webtestclient-json,获取JSON内容>>或一个空的正文.

然后,您可以对主体使用内置的断言.  下面的示例显示了一种方法:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	client.get().uri("/persons")
			.exchange()
			.expectStatus().isOk()
			.expectBodyList(Person.class).hasSize(3).contains(person);
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	import org.springframework.test.web.reactive.server.expectBodyList

	client.get().uri("/persons")
			.exchange()
			.expectStatus().isOk()
			.expectBodyList<Person>().hasSize(3).contains(person)
----

您还可以超越内置的断言并创建自己的断言,如以下示例所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
    import org.springframework.test.web.reactive.server.expectBody

	client.get().uri("/persons/1")
			.exchange()
			.expectStatus().isOk()
			.expectBody(Person.class)
			.consumeWith(result -> {
				// custom assertions (e.g. AssertJ)...
			});
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	client.get().uri("/persons/1")
			.exchange()
			.expectStatus().isOk()
			.expectBody<Person>()
			.consumeWith {
				// custom assertions (e.g. AssertJ)...
			}
----

您还可以退出工作流程并获得结果,如下所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	EntityExchangeResult<Person> result = client.get().uri("/persons/1")
			.exchange()
			.expectStatus().isOk()
			.expectBody(Person.class)
			.returnResult();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	import org.springframework.test.web.reactive.server.expectBody

	val result = client.get().uri("/persons/1")
			.exchange()
			.expectStatus().isOk
			.expectBody<Person>()
			.returnResult()
----

TIP: 当需要使用泛型解码为目标类型时,请寻找接受 {api-spring-framework}/core/ParameterizedTypeReference.html[`ParameterizedTypeReference`] 而不是 `Class<T>` 的重载方法.

[[webtestclient-no-content]]
=== 无内容

如果响应没有内容(或者您不在乎) ,请使用 `Void.class`,以确保释放资源.  以下示例显示了如何执行此操作:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	client.get().uri("/persons/123")
			.exchange()
			.expectStatus().isNotFound()
			.expectBody(Void.class);
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	client.get().uri("/persons/123")
			.exchange()
			.expectStatus().isNotFound
			.expectBody<Unit>()
----

或者,如果要断言没有响应内容,则可以使用类似于以下内容的代码:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	client.post().uri("/persons")
			.body(personMono, Person.class)
			.exchange()
			.expectStatus().isCreated()
			.expectBody().isEmpty();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	client.post().uri("/persons")
			.bodyValue(person)
			.exchange()
			.expectStatus().isCreated()
			.expectBody().isEmpty()
----


[[webtestclient-json]]
=== JSON 内容

当您使用 `expectBody()` 时,响应以  `byte[]` 的形式使用.  这对于原始内容声明很有用.  例如,您可以使用 https://jsonassert.skyscreamer.org[JSONAssert] 来验证JSON内容,如下所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	client.get().uri("/persons/1")
			.exchange()
			.expectStatus().isOk()
			.expectBody()
			.json("{\"name\":\"Jane\"}")
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	client.get().uri("/persons/1")
			.exchange()
			.expectStatus().isOk()
			.expectBody()
			.json("{\"name\":\"Jane\"}")
----

您还可以使用 https://github.com/jayway/JsonPath[JSONPath] 表达式,如下所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	client.get().uri("/persons")
			.exchange()
			.expectStatus().isOk()
			.expectBody()
			.jsonPath("$[0].name").isEqualTo("Jane")
			.jsonPath("$[1].name").isEqualTo("Jason");
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	client.get().uri("/persons")
			.exchange()
			.expectStatus().isOk()
			.expectBody()
			.jsonPath("$[0].name").isEqualTo("Jane")
			.jsonPath("$[1].name").isEqualTo("Jason")
----



[[webtestclient-stream]]
=== 流式响应

要测试无限流(例如, `"text/event-stream"` 或 `"application/stream+json"`) ,需要在响应状态和标头断言之后立即退出链接的API(使用 `returnResult`) ,如下所示 示例显示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	FluxExchangeResult<MyEvent> result = client.get().uri("/events")
			.accept(TEXT_EVENT_STREAM)
			.exchange()
			.expectStatus().isOk()
			.returnResult(MyEvent.class);

----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	import org.springframework.test.web.reactive.server.returnResult

	val result = client.get().uri("/events")
			.accept(TEXT_EVENT_STREAM)
			.exchange()
			.expectStatus().isOk()
			.returnResult<MyEvent>()
----

现在,您可以使用 `Flux<T>`,在到达解码对象时对其进行断言,然后在达到测试目标时在某个时候取消.  我们建议使用 `reactor-test` 模块中的 `StepVerifier` 进行此操作,如以下示例所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	Flux<Event> eventFlux = result.getResponseBody();

	StepVerifier.create(eventFlux)
			.expectNext(person)
			.expectNextCount(4)
			.consumeNextWith(p -> ...)
			.thenCancel()
			.verify();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val eventFlux = result.getResponseBody()

	StepVerifier.create(eventFlux)
			.expectNext(person)
			.expectNextCount(4)
			.consumeNextWith { p -> ... }
			.thenCancel()
			.verify()
----



[[webtestclient-request-body]]
=== 请求体

当涉及到构建请求时,`WebTestClient` 提供了与 `WebClient` 相同的API,并且实现主要是简单的传递.  有关如何使用正文准备请求的示例,请参见 <<web-reactive.adoc#webflux-client-body, WebClient 文档>>,包括提交表单数据,多部分请求等.
