[[unit-testing]]
= 单元测试

与传统的 Jakarta EE 开发相比,依赖注入应该使您的代码对容器的依赖程度降低. 组成应用程序的 POJO 应该可以在 JUnit 或 TestNG 测试中进行测试,并且可以使用 `new` 运算符实例化对象,而无需使用 Spring 或任何其他容器.
您可以使用 <<mock-objects, Mock Objects(模拟对象)>> (结合其他有价值的测试技术) 来单独测试代码.  如果您遵循 Spring 的体系结构建议,那么代码库的最终分层和组件化将使单元测试更加容易.  例如,您需要在进行单元测试时不访问持久性数据,您可以通过 stubbing 或 mocking  DAO 或 repository  接口来测试服务层对象.

真正的单元测试通常运行非常快,因为没有设置运行时基础架构. 将真正的单元测试作为开发方法的一部分可以提高生产率.  您可能不需要测试章节的这一部分来帮助您为基于 IoC 的应用程序编写有效的单元测试.  但是,对于某些单元测试方案,Spring 框架提供了模拟对象和测试支持类,本章对此进行了介绍.


[[mock-objects]]
== 模拟对象

Spring 包含许多专用于模拟的包:

* <<mock-objects-env>>
* <<mock-objects-jndi>>
* <<mock-objects-servlet>>
* <<mock-objects-web-reactive>>


[[mock-objects-env]]
=== Environment

`org.springframework.mock.env` 包包含 `Environment` 和 `PropertySource` 抽象的模拟实现 (请参阅<<core.adoc#beans-definition-profiles, Bean 定义配置文件>> 和 <<core.adoc#beans-property-source-abstraction, `PropertySource` 抽象>>) .
`MockEnvironment` 和 `MockPropertySource` 对于编写那些依赖于特定环境或属性的测试非常有用.

[[mock-objects-jndi]]
=== JNDI

`org.springframework.mock.jndi` 包包含 JNDI SPI 的部分实现,可用于为测试套件或独立应用程序设置简单的 JNDI 环境.  例如,如果 JDBC `DataSource` 实例在测试代码中与在 Jakarta EE 容器中绑定到相同的 JNDI 名称,则可以在测试场景中重用应用程序代码和配置,而无需进行修改.

WARNING: 从 Spring Framework 5.2 开始,正式弃用了 `org.springframework.mock.jndi` 包中对模拟 JNDI 支持,而希望使用第三方的完整解决方案,例如 https://github.com/h-thurow/Simple-JNDI[Simple-JNDI].

[[mock-objects-servlet]]
=== Servlet API

`org.springframework.mock.web` 包包含一组全面的 Servlet API 模拟对象,这些对象对于测试 Web 上下文,控制器和过滤器非常有用.  这些模拟对象是针对 Spring 的 Web MVC 框架使用的,通常比动态模拟对象 (例如 http://easymock.org/[EasyMock]) 或其他 Servlet API 模拟对象 (例如 http://www.mockobjects.com[MockObjects]) 更方便使用.

TIP: 从 Spring Framework 6.0 开始,`org.springframework.mock.web` 中的模拟对象基于 Servlet 6.0 API.

Spring MVC 测试框架建立在模拟 Servlet API 对象的基础上,为 Spring MVC 提 供了集成测试框架. 参见<<spring-mvc-test-framework,Spring MVC 测试框架>>.

[[mock-objects-web-reactive]]
=== Spring Web Reactive

`org.springframework.mock.http.server.reactive` 包包含 `ServerHttpRequest` 和 `ServerHttpResponse` 的模拟实现,供 `WebFlux` 应用程序使用.  `org.springframework.mock.web.server` 包包含一个模拟 `ServerWebExchange`,它依赖于那些模拟请求和响应对象.

`MockServerHttpRequest` 和 `MockServerHttpResponse` 都从与特定于服务器的实现相同的抽象基类扩展,并与它们共享行为.  例如,模拟请求一旦创建便是不可变的,但是您可以使用 `ServerHttpRequest` 中的 `mutate()` 方法来创建修改后的实例.

为了使模拟响应正确实现写约定并返回写完成句柄 (即 `Mono<Void>`) ,默认情况下,它使用带有 `Flux` 的 `cache()`. `then()` 来对数据进行缓冲并使其 可用于测试中的断言.  应用程序可以设置自定义写入功能 (例如,测试无限流) .

<<webtestclient>> 建立在模拟请求和响应的基础上,为不使用 HTTP 服务器的 `WebFlux` 应用程序测试提供支持.  客户端还可以用于正在运行的服务器的端到端测试.

[[unit-testing-support-classes]]
== 单元测试支持的类

Spring 包含许多可以帮助进行单元测试的类. 它们分为两类:

* <<unit-testing-utilities>>
* <<unit-testing-spring-mvc>>


[[unit-testing-utilities]]
=== 通用测试工具

`org.springframework.test.util` 包包含几个通用的实用程序,用于单元测试和集成测试.

{api-spring-framework}/test/util/AopTestUtils.html[`AopTestUtils`] 是与 AOP 相关的实用程序方法的集合.  您可以使用这些方法来获取对隐藏在一个或多个 Spring 代理后面的目标对象的引用.
例如,如果您已通过使用 EasyMock 或 Mockito 之类的库将 bean 配置为动态模拟,并且该模拟包装在 Spring 代理中,则可能需要直接访问基础模拟以在其上配置期望并执行验证 .  有关 Spring 的核心 AOP 实用程序,请参阅 {api-spring-framework}/aop/support/AopUtils.html[`AopUtils`]和 {api-spring-framework}/aop/framework/AopProxyUtils.html[`AopProxyUtils`].

`ReflectionTestUtils` 是基于反射的实用程序方法的集合.  您可以在测试场景中使用这些方法,在这些场景中,当测试应用程序代码时,需要更改常量的值,设置非公共字段,调用非公共 setter 方法或调用非公共配置或生命周期回调方法.  用例如下:

* ORM 框架 (例如 JPA 和 Hibernate) 提供了 `private` 或 `protected` 的字段访问,而不是实体属性的 `public` setter 方法.
* Spring 支持注解 (例如 `@Autowired`,`@Inject` 和 `@Resource`) ,这些注解为 `private` 或 `protected` 的字段,setter 方法和配置方法提供依赖注入.
* 将诸如 `@PostConstruct` 和 `@PreDestroy` 之类的注解用于生命周期回调方法

{api-spring-framework}/test/util/TestSocketUtils.html[`TestSocketUtils`] 是一个简单的工具类，可以在 `localhost` 上查找可用的 TCP 端口。

[NOTE]
====
`TestSocketUtils` 可以在可用的随机端口上启动外部服务器来进行集成测试。 但是，这并不保证指定端口的后续可用性，因此不可靠。
建议您不要使用 `TestSocketUtils` 来为服务器查找可用的本地端口，而是依靠服务器在它选择或由操作系统分配的随机临时端口上启动的能力。 要与该服务器交互，您应该向服务器查询它当前使用的端口。
====

[[unit-testing-spring-mvc]]
=== Spring MVC 测试实用程序


`org.springframework.test.web` 包包含 {api-spring-framework}/test/web/ModelAndViewAssert.html[`ModelAndViewAssert`],您可以将其与 JUnit,TestNG 或任何其他测试框架结合使用,以进行处理 Spring MVC `ModelAndView` 对象的单元测试.

.单元测试 Spring MVC 控制器
TIP: 要对作为 POJO 的 Spring MVC `Controller` 类进行单元测试,请将 `ModelAndViewAssert` 与 Spring 的<<mock-objects-servlet, Servlet API mocks>>模拟中的 `MockHttpServletRequest`,`MockHttpSession` 等结合使用.
为了与 Spring MVC 的 `WebApplicationContext` 配置一起对 Spring MVC 和 REST `Controller` 类进行全面的集成测试,请改用<<spring-mvc-test-framework, Spring MVC Test Framework>>.