[[messaging.amqp]]
== AMQP
高级消息队列协议 (Advanced Message Queuing Protocol,AMQP) 是一个平台无关,面向消息中间件的连接级协议. Spring AMQP 项目将核心 Spring 概念应用于基于 AMQP 消息传递解决方案的开发. Spring Boot 为通过 RabbitMQ 使用 AMQP 提供了一些快捷方法,包括 `spring-boot-starter-amqp` starter.

[[messaging.amqp.rabbitmq]]
=== RabbitMQ 支持
https://www.rabbitmq.com/[RabbitMQ] 是一个基于 AMQP 协议的轻量级、可靠、可扩展且可移植的消息代理. Spring 使用 RabbitMQ 通过 AMQP 协议进行通信.

RabbitMQ 配置由 `+spring.rabbitmq.*+` 中的外部配置属性控制. 例如,您可以在 `application.properties` 中声明以下部分:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  rabbitmq:
	    host: "localhost"
	    port: 5672
	    username: "admin"
	    password: "secret"
----

另外,您可以配置相同 `addresses` 属性的连接:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  rabbitmq:
	    addresses: "amqp://admin:secret@localhost"
----

NOTE: 当以这种方式指定 addresses 时,`host` 和 `port` 属性将被忽略. 如果地址使用 `amqps` 协议,则会自动启用 SSL 支持

有关更多支持的选项,请参阅 {spring-boot-autoconfigure-module-code}/amqp/RabbitProperties.java[`RabbitProperties`] .
要配置 Spring AMQP 使用的 RabbitMQ `ConnectionFactory` 的详细信息，请定义一个 `ConnectionFactoryCustomizer` bean。

如果上下文中存在 `ConnectionNameStrategy` bean，它将自动用于命名由自动配置的 `CachingConnectionFactory` 创建的连接。

TIP: 有关详细信息,请参阅理解  https://spring.io/blog/2010/06/14/understanding-amqp-the-protocol-used-by-rabbitmq/[AMQP、RabbitMQ 使用的协议].

[[messaging.amqp.sending]]
=== 发送消息
Spring 的 `AmqpTemplate` 和 `AmqpAdmin` 是自动配置的,您可以将它们直接注入自己的 bean 中,如下所示:

include::code:MyBean[]

NOTE: {spring-amqp-api}/rabbit/core/RabbitMessagingTemplate.html[`RabbitMessagingTemplate`] 可以以类似的方式注入. 如果定义了 `MessageConverter` bean,它将自动关联到自动配置的 `AmqpTemplate`.

如有必要,所有定义为 bean 的 `org.springframework.amqp.core.Queue` 都会自动在 RabbitMQ 实例上声明相应的队列.

要重试操作,可以在 `AmqpTemplate` 上启用重试 (例如,在 broker 连接丢失的情况下) :

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  rabbitmq:
	    template:
	      retry:
	        enabled: true
	        initial-interval: "2s"
----

默认情况下禁用重试. 您还可以通过声明 `RabbitRetryTemplateCustomizer` bean 以编程方式自定义 `RetryTemplate`.

如果您需要创建更多的 `RabbitTemplate` 实例,或者想覆盖默认实例,Spring Boot 提供了一个 `RabbitTemplateConfigurer` bean,您可以使用它来初始化一个 `RabbitTemplate`,其设置与自动配置所使用的工厂相同.

[[messaging.amqp.sending-stream]]
=== 向流发送消息
若要将消息发送到特定流，请指定流的名称，如以下示例所示：

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  rabbitmq:
	    stream:
	      name: "my-stream"
----

如果定义了 `MessageConverter`, `StreamMessageConverter`, 或 `ProducerCustomizer` bean，它将自动关联到自动配置的 `RabbitStreamTemplate`。

如果你需要创建更多的  `RabbitStreamTemplate` 实例，或者如果你想覆盖默认值，Spring Boot 提供了一个 `RabbitStreamTemplateConfigurer` bean，
你可以用它来初始化一个 `RabbitStreamTemplate`，其设置与自动配置使用的工厂相同。

[[messaging.amqp.receiving]]
=== 接收消息
当 Rabbit 基础设施存在时,可以使用 `@RabbitListener` 注解任何 bean 以创建监听器端点. 如果未定义 `RabbitListenerContainerFactory`,则会自动配置一个默认的 `SimpleRabbitListenerContainerFactory`,您可以使用 `spring.rabbitmq.listener.type` 属性切换到一个直接容器. 如果定义了 `MessageConverter` 或 `MessageRecoverer` bean,它将自动与默认 factory 关联.

以下示例组件在 `someQueue` 队列上创建一个监听器端点:

include::code:MyBean[]

TIP: 有关更多详细信息,请参阅 {spring-amqp-api}/rabbit/annotation/EnableRabbit.html[the Javadoc of `@EnableRabbit`] 的 Javadoc.

如果需要创建更多 `RabbitListenerContainerFactory` 实例或覆盖默认值,Spring Boot 提供了一个 `SimpleRabbitListenerContainerFactoryConfigurer` 和一个 `DirectRabbitListenerContainerFactoryConfigurer`,您可以使用它来初始化 `SimpleRabbitListenerContainerFactory` 和 `DirectRabbitListenerContainerFactory`,其设置与使用自动配置的 factory 相同.

TIP: 这两个 bean 与您选择的容器类型没有关系,它们通过自动配置暴露.

例如,以下配置类暴露了另一个使用特定 `MessageConverter` 的 factory:

include::code:custom/MyRabbitConfiguration[]

然后,您可以在任何 `@RabbitListener` 注解的方法中使用该 factory,如下所示:

include::code:custom/MyBean[]

您可以启用重试机制来处理监听器的异常抛出情况. 默认情况下使用 `RejectAndDontRequeueRecoverer`,但您可以定义自己的 `MessageRecoverer`. 如果 broker 配置了重试机制,当重试次数耗尽时,则拒绝消息并将其丢弃或路由到死信 (dead-letter) exchange 中.
默认情况下重试机制为禁用. 您还可以通过声明 `RabbitRetryTemplateCustomizer` bean 以编程方式自定义 `RetryTemplate`.

IMPORTANT: 默认情况下,如果禁用重试并且监听器异常抛出,则会无限期地重试传递. 您可以通过两种方式修改此行为: 将 `defaultRequeueRejected` 属性设置为 `false`,以便尝试零重传或抛出 `AmqpRejectAndDontRequeueException` 以指示拒绝该消息. 后者是启用重试并且达到最大传递尝试次数时使用的机制.
