[[messaging.spring-integration]]
== Spring Integration
Spring Boot 为 {spring-integration}[Spring Integration] 提供了一些便捷的使用方式,它们包含在 `spring-boot-starter-integration` starter 中. Spring Integration 为消息传递以及其他传输 (如 HTTP、TCP 等) 提供了抽象.
如果 classpath 上存在 Spring Integration,则 Spring Boot 会通过 `@EnableIntegration` 注解对其进行初始化.

Spring Integration polling logic 轮询逻辑依赖于 <<features#features.task-execution-and-scheduling, 自动配置的 `TaskScheduler`>>。
默认的 `PollerMetadata`（每秒轮询无限数量的消息）可以使用 `spring.integration.poller.*` 配置属性进行自定义。

Spring Boot 还配置了一些由其他 Spring Integration 模块触发的功能. 如果 `spring-integration-jmx` 也在 classpath 上,则消息处理统计信息将通过 JMX 发布. 如果 `spring-integration-jdbc` 可用,则可以在启动时创建默认数据库模式,如下所示:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  integration:
	    jdbc:
	      initialize-schema: "always"
----

如果可用 `spring-integration-rsocket`,则开发人员可以使用 `"spring.rsocket.server.*"` 属性配置 RSocket 服务器,并使其使用 `IntegrationRSocketEndpoint` 或 `RSocketOutboundGateway` 组件来处理传入的 RSocket 消息. 该基础结构可以处理 Spring Integration RSocket 通道适配器和 `@MessageMapping` 处理程序 (已配置 `"spring.integration.rsocket.server.message-mapping-enabled"`) .

Spring Boot 还可以使用配置属性来自动配置 `ClientRSocketConnector`:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	# Connecting to a RSocket server over TCP
	spring:
	  integration:
	    rsocket:
	      client:
	        host: "example.org"
	        port: 9898
----

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	# Connecting to a RSocket Server over WebSocket
	spring:
	  integration:
	    rsocket:
	      client:
	        uri: "ws://example.org"
----

有关更多详细信息,请参阅 {spring-boot-autoconfigure-module-code}/integration/IntegrationAutoConfiguration.java[`IntegrationAutoConfiguration`] 和 {spring-boot-autoconfigure-module-code}/integration/IntegrationProperties.java[`IntegrationProperties`]  类.
