[[webflux-oauth2-login]]
= OAuth 2.0 Login

OAuth 2.0登录功能为应用程序提供了让用户可以在提供了OAuth 2.0 (例如GitHub) 或OpenID Connect 1.0 (例如Google) 协议的第三方平台，使用平台现有帐户登录该应用程序的功能.  OAuth 2.0登录实现了以下用例: "使用Google登录" 或 "使用GitHub登录".


NOTE: OAuth 2.0登录是通过使用 https://tools.ietf.org/html/rfc6748#section-4.1[OAuth 2.0 Authorization Framework] 和 https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth[OpenID Connect Core 1.0].中指定的授权码授权来实现的.

[[webflux-oauth2-login-sample]]
== Spring Boot 2.0 示例

Spring Boot 2.x为OAuth 2.0登录带来了完整的自动配置功能.

本部分显示了如何使用Google作为身份验证提供程序来配置 {gh-samples-url}/boot/oauth2login[*OAuth 2.0 Login sample*]，并涵盖以下主题:

* <<webflux-oauth2-login-sample-setup,初始设置>>
* <<webflux-oauth2-login-sample-redirect,设置重定向URI>>
* <<webflux-oauth2-login-sample-config,配置 `application.yml`>>
* <<webflux-oauth2-login-sample-start,启动应用程序>>


[[webflux-oauth2-login-sample-setup]]
=== 初始设置

要使用Google的OAuth 2.0身份验证系统登录，您必须在Google API控制台中设置一个项目以获得OAuth 2.0凭据.

NOTE: https://developers.google.com/identity/protocols/OpenIDConnect[Google's OAuth 2.0 实现] 符合 https://openid.net/connect/[OpenID Connect 1.0] 规范，并且已通过 https://openid.net/certification/[OpenID Certified].

请按照设置 https://developers.google.com/identity/protocols/OpenIDConnect[OpenID Connect]  (需要翻墙才能访问，链接打开是 Google 的开发者平台控制台) 部分开始的OpenID Connect页面上的说明进行操作.

完成 "获取OAuth 2.0凭据" 说明后，您应该拥有一个新的OAuth客户端，其凭据由 Client ID 和 Client Secret.组成.

[[webflux-oauth2-login-sample-redirect]]
=== 设置重定向URI

重定向URI是用户的在通过Google身份验证并在授权页面上同意 (_(<<oauth2login-sample-initial-setup,在上一步中创建>>)_) OAuth客户端的访问权限后，由Google重定向的回调链接地址

在 设置重定向URI子章节中，确保将  *Authorized redirect URIs* 字段设置为 `http://localhost:8080/login/oauth2/code/google`.

TIP: 默认重定向URI模板为 `{baseUrl}/login/oauth2/code/{registrationId}`..  *_registrationId_* 是 <<oauth2Client-client-registration,ClientRegistration>> 的唯一标识符.

IMPORTANT: 如果OAuth客户端在代理服务器 (例如: Nginx) 后面运行，建议检查<<http-proxy-server, 代理服务器配置>>以确保正确配置了应用程序.  另外，请参阅 `redirect-uri` 支持的<<oauth2Client-auth-code-redirect-uri, `URI` 模板变量>>.

[[webflux-oauth2-login-sample-config]]
=== Configure `application.yml`

现在，您有了Google的新OAuth客户端，您需要配置应用程序以将OAuth客户端用于身份验证流程.  为此:

. 转到 `application.yml` 并设置以下配置:
+
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:	<1>
          google:	<2>
            client-id: google-client-id
            client-secret: google-client-secret
----
+
.OAuth客户端属性
====
<1> `spring.security.oauth2.client.registration` 是OAuth客户端属性的基本属性前缀.
<2> 基本属性前缀后面是<<oauth2Client-client-registration,ClientRegistration>>的ID，例如google
====

. 将 `client-id` 和 `client-secret` 属性中的值替换为您先前创建的OAuth 2.0凭据.


[[webflux-oauth2-login-sample-start]]
=== 启动应用程序

启动Spring Boot 2.0 示例并转到 `http://localhost:8080`.  然后，您将会被重定向到默认自动生成的登录页面，该页面显示Google的链接.

单击Google链接，然后您将重定向到Google进行身份验证.

在使用您的Google帐户凭据进行身份验证之后，显示给您的下一页是 *Allow* 页面.   *Allow* 页面要求您允许或拒绝之前创建的OAuth客户端的访问权限.  点击 *Allow* 以授权OAuth客户端访问您的电子邮件地址和基本个人资料信息.

此时，OAuth客户端将从 https://openid.net/specs/openid-connect-core-1_0.html#UserInfo[UserInfo Endpoint] 检索您的电子邮件地址和基本个人资料信息，并建立经过身份验证的会话.

[[webflux-oauth2-login-openid-provider-configuration]]
== 使用OpenID提供程序配置

对于知名的提供商，Spring Security为OAuth授权提供商的配置提供了必要的默认值.  如果您正在使用支持 https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[OpenID Provider Configuration] 或 https://tools.ietf.org/html/rfc8414#section-3[授权服务器]，
则可以使用 https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationResponse[OpenID Provider Configuration Response]的 `issuer-uri` 来配置应用程序.

[source,yml]
----
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://idp.example.com/auth/realms/demo
        registration:
          keycloak:
            client-id: spring-security
            client-secret: 6cea952f-10d0-4d00-ac79-cc865820dc2c
----

`issuer-uri` 指示Spring Security依次查询端点 `https://idp.example.com/auth/realms/demo/.well-known/openid-configuration`, `https://idp.example.com/.well-known/openid-configuration/auth/realms/demo`, or  `https://idp.example.com/.well-known/oauth-authorization-server/auth/realms/demo` 来发现配置.


[NOTE]
Spring Security将一次查询一个端点，并在第一个端点发出200响应时停止.

`client-id` 和 `client-secret` 链接到提供程序，因为 `keycloak` 用于提供程序和注册.

[[webflux-oauth2-login-explicit]]
== 显式OAuth2登录配置

最小的OAuth2登录配置如下所示:

[source,java]
----
@Bean
ReactiveClientRegistrationRepository clientRegistrations() {
	ClientRegistration clientRegistration = ClientRegistrations
			.fromIssuerLocation("https://idp.example.com/auth/realms/demo")
			.clientId("spring-security")
			.clientSecret("6cea952f-10d0-4d00-ac79-cc865820dc2c")
			.build();
	return new InMemoryReactiveClientRegistrationRepository(clientRegistration);
}

@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		// ...
		.oauth2Login(withDefaults());
	return http.build();
}
----

其他配置选项如下所示:

[source,java]
----
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		// ...
		.oauth2Login(oauth2 -> oauth2
			.authenticationConverter(converter)
			.authenticationManager(manager)
			.authorizedClientRepository(authorizedClients)
			.clientRegistrationRepository(clientRegistrations)
		);
	return http.build();
}
----
