[[get-started]]
= 入门

本部分提供了易于使用的 Spring Data Redis 模块入门指南。

[[get-started:first-steps]]
== 第一步

如 <<why-spring-redis>> 中所述，Spring Data Redis (SDR) 提供了 Spring 框架与 Redis 键值存储之间的集成。因此，您应该熟悉这两个框架。 在整个 SDR 文档中，每个部分都提供了指向相关资源的链接。 但是，在阅读本指南之前，您应该熟悉这些主题。

[[get-started:first-steps:spring]]
=== 学习 Spring

Spring Data 使用 Spring 框架的 https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html[核心] 功能，例如 https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html[IoC] 容器， https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#resources[resource]  抽象和 https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#aop[AOP] 基础结构。
虽然了解 Spring API 并不重要，但了解它们背后的概念很重要。 至少，应该了解 IoC 背后的想法。 话虽如此，您对 Spring 的了解越多，您就能更快地获取 Spring Data Redis。 除了 Spring 框架的全面文档之外，还有很多有关此问题的文章，博客条目和书籍。
Spring Guides https://spring.io/guides[主页] 提供了一个很好的起点。 通常，这应该是想要尝试使用Spring Data Redis的开发人员的起点。

[[get-started:first-steps:nosql]]
=== 学习 NoSQL 和 Key Value 存储

NoSQL 存储席卷了存储世界。 它是一个广阔的领域，具有许多解决方案，术语和模式（更糟糕的是，甚至术语本身也具有 https://www.google.com/search?q=nosoql+acronym[多种含义]）。
尽管某些原则很普遍，但一定程度上要熟悉 SDR 支持的 处处，这一点至关重要。 熟悉这些解决方案的最佳方法是阅读其文档并遵循其示例。 通常需要花费五到十分钟的时间来完成这些步骤，而且，如果您具有 RDMBS 的背景，那么这些练习通常会使人大开眼界。

[[get-started:first-steps:samples]]
=== 尝试示例

您可以在 Spring Data 示例存储库中找到各种用于键值存储的示例，网址为 https://github.com/spring-projects/spring-data-keyvalue-examples[https://github.com/spring-projects/spring-data-keyvalue-examples]。
对于 Spring Data Redis，您应该特别注意 `retwisj` 示例，该示例是在 Redis 之上构建的 Twitter-clone，可以在本地运行或部署到云中。 有关更多信息，请参阅其 https://docs.spring.io/spring-data/data-keyvalue/examples/retwisj/current/[文档]，以下 https://spring.io/blog/2011/04/27/getting-started-redis-spring-cloud-foundry/[博客]。

[[get-started:help]]
== 需求帮助?

如果您遇到问题或只是在寻求建议，请使用以下链接之一：

[[get-started:help:community]]
=== 社区帮助

https://stackoverflow.com/questions/tagged/spring-data[Stack Overflow] 上的 Spring Data 标签是一个留言板，供所有 Spring Data（不仅仅是 Redis）用户共享信息并互相帮助。 请注意，只有注册了才能发布。

[[get-started:help:professional]]
=== 专业支持

可从 Spring Data 和 Spring 背后的公司  https://www.pivotal.io/[Pivotal Software, Inc.] 获得专业的支持。

[[get-started:up-to-date]]
== 后续发展

有关 Spring Data 源代码存储库，每夜构建和 snapshot 构件 的信息，请参见 Spring Data https://spring.io/spring-data[主页]。

通过在 https://stackoverflow.com/questions/tagged/spring-data[spring-data] 或 https://stackoverflow.com/questions/tagged/spring-data-redis[spring-data-redis] 上的 Stack Overflow 上与开发人员进行交互，可以帮助使 Spring Data 最好地满足 Spring 社区的需求。

如果您遇到错误或要提出改进建议（包括本文档中的内容），请在 Spring Data 问题跟踪器上创建 https://jira.spring.io/browse/DATAREDIS[tracker]。

要了解 Spring 生态系统中的最新新闻和公告，请订阅 Spring Community https://spring.io/[Portal]。

最后，您可以在 Twitter 上关注 Spring  https://spring.io/blog/[blog] 或项目团队(https://twitter.com/SpringData[@SpringData])。