[[web-uricomponents]]
= UriComponents
[.small]#Spring MVC and Spring WebFlux#

`UriComponentsBuilder` 有助于从URI模板变量构建URI。 如下例所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	UriComponents uriComponents = UriComponentsBuilder
			.fromUriString("https://example.com/hotels/{hotel}")  // <1>
			.queryParam("q", "{q}")  // <2>
			.encode() // <3>
			.build(); // <4>

	URI uri = uriComponents.expand("Westin", "123").toUri();  // <5>
----
<1> 带有URI模板的静态工厂方法
<2> 添加或替换URI组件。
<3> 请求编码URI模板和URI变量。
<4> 构建一个 `UriComponents`。
<5> 暴露变量并获取 `URI`。

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val uriComponents = UriComponentsBuilder
			.fromUriString("https://example.com/hotels/{hotel}")  // <1>
			.queryParam("q", "{q}")  // <2>
			.encode() // <3>
			.build() // <4>

	val uri = uriComponents.expand("Westin", "123").toUri()  // <5>
----
<1> 带有URI模板的静态工厂方法
<2> 添加或替换URI组件。
<3> 请求编码URI模板和URI变量。
<4> 构建一个 `UriComponents`。
<5> 暴露变量并获取 `URI`。

前面的示例可以合并到一个链中，并使用 `buildAndExpand` 缩短，如下例所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	URI uri = UriComponentsBuilder
			.fromUriString("https://example.com/hotels/{hotel}")
			.queryParam("q", "{q}")
			.encode()
			.buildAndExpand("Westin", "123")
			.toUri();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val uri = UriComponentsBuilder
			.fromUriString("https://example.com/hotels/{hotel}")
			.queryParam("q", "{q}")
			.encode()
			.buildAndExpand("Westin", "123")
			.toUri()
----

您可以通过直接转到URI（这意味着编码）来进一步缩短它，如下例所示：

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	URI uri = UriComponentsBuilder
			.fromUriString("https://example.com/hotels/{hotel}")
			.queryParam("q", "{q}")
			.build("Westin", "123");
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val uri = UriComponentsBuilder
			.fromUriString("https://example.com/hotels/{hotel}")
			.queryParam("q", "{q}")
			.build("Westin", "123")
----

您使用完整的URI模板进一步缩短它，如下例所示：

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	URI uri = UriComponentsBuilder
			.fromUriString("https://example.com/hotels/{hotel}?q={q}")
			.build("Westin", "123");
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
val uri = UriComponentsBuilder
		.fromUriString("https://example.com/hotels/{hotel}?q={q}")
		.build("Westin", "123")
----




[[web-uribuilder]]
= UriBuilder
[.small]#Spring MVC and Spring WebFlux#

<<web-uricomponents, `UriComponentsBuilder`>> 实现了  `UriBuilder`。 您可以使用 `UriBuilderFactory` 创建一个 `UriBuilder`。 `UriBuilderFactory` 和 `UriBuilder` 一起提供了一种可插入机制，可以根据共享配置（例如基本URL，编码首选项和其他详细信息）从URI模板构建URI。

您可以使用 `UriBuilderFactory` 配置 `RestTemplate` 和 `WebClient` ,为自定义URI做准备。 `DefaultUriBuilderFactory` 是 `UriBuilderFactory` 的默认实现，该实现在内部使用 `UriComponentsBuilder` 并公开共享的配置选项。

以下示例显示如何配置 `RestTemplate`：

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	// import org.springframework.web.util.DefaultUriBuilderFactory.EncodingMode;

	String baseUrl = "https://example.org";
	DefaultUriBuilderFactory factory = new DefaultUriBuilderFactory(baseUrl);
	factory.setEncodingMode(EncodingMode.TEMPLATE_AND_VALUES);

	RestTemplate restTemplate = new RestTemplate();
	restTemplate.setUriTemplateHandler(factory);
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	// import org.springframework.web.util.DefaultUriBuilderFactory.EncodingMode
	
	val baseUrl = "https://example.org"
	val factory = DefaultUriBuilderFactory(baseUrl)
	factory.encodingMode = EncodingMode.TEMPLATE_AND_VALUES

	val restTemplate = RestTemplate()
	restTemplate.uriTemplateHandler = factory
----

下面的示例配置一个 `WebClient`：

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	// import org.springframework.web.util.DefaultUriBuilderFactory.EncodingMode;

	String baseUrl = "https://example.org";
	DefaultUriBuilderFactory factory = new DefaultUriBuilderFactory(baseUrl);
	factory.setEncodingMode(EncodingMode.TEMPLATE_AND_VALUES);

	WebClient client = WebClient.builder().uriBuilderFactory(factory).build();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	// import org.springframework.web.util.DefaultUriBuilderFactory.EncodingMode

	val baseUrl = "https://example.org"
	val factory = DefaultUriBuilderFactory(baseUrl)
	factory.encodingMode = EncodingMode.TEMPLATE_AND_VALUES

	val client = WebClient.builder().uriBuilderFactory(factory).build()
----

此外，您也可以直接使用 `DefaultUriBuilderFactory`。它类似于使用 `UriComponentsBuilder`，但它不是静态工厂方法，而是一个保存配置和首选项的实际实例，如下例所示：

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	String baseUrl = "https://example.com";
	DefaultUriBuilderFactory uriBuilderFactory = new DefaultUriBuilderFactory(baseUrl);

	URI uri = uriBuilderFactory.uriString("/hotels/{hotel}")
			.queryParam("q", "{q}")
			.build("Westin", "123");
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val baseUrl = "https://example.com"
	val uriBuilderFactory = DefaultUriBuilderFactory(baseUrl)

	val uri = uriBuilderFactory.uriString("/hotels/{hotel}")
			.queryParam("q", "{q}")
			.build("Westin", "123")
----



[[web-uri-encoding]]
= URI Encoding
[.small]#Spring MVC and Spring WebFlux#

`UriComponentsBuilder` 在两个级别公开编码选项：

* {api-spring-framework}/web/util/UriComponentsBuilder.html#encode--[UriComponentsBuilder#encode()]: 首先对URI模板进行预编码，然后在扩展时严格编码URI变量。
* {api-spring-framework}/web/util/UriComponents.html#encode--[UriComponents#encode()]: 扩展URI变量后对URI组件进行编码。

这两个选项都使用转义的八位字节替换非ASCII和非法字符。 但是，第一个选项还会替换出现在URI变量中的保留含义的字符。

TIP: 考虑 ";"，这在路径中是合法的但具有保留意义。第一个选项取代  ";" 在URI变量中使用 "％3B"，但URI模板中没有。但在URI模板中没有。 相比之下，第二个选项永远不会替换 ";"，因为它是路经中的合法字符。

对于大多数情况，第一个选项可能会给出预期结果，因为它将URI变量视为完全编码的不透明数据，而选项2仅在URI变量故意包含保留字符时才有用。

以下示例使用第一个选项:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	URI uri = UriComponentsBuilder.fromPath("/hotel list/{city}")
			.queryParam("q", "{q}")
			.encode()
			.buildAndExpand("New York", "foo+bar")
			.toUri();

	// Result is "/hotel%20list/New%20York?q=foo%2Bbar"
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val uri = UriComponentsBuilder.fromPath("/hotel list/{city}")
			.queryParam("q", "{q}")
			.encode()
			.buildAndExpand("New York", "foo+bar")
			.toUri()

	// Result is "/hotel%20list/New%20York?q=foo%2Bbar"
----

您可以通过直接转到URI（这意味着编码）来缩短前面的示例，如以下示例所示：

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	URI uri = UriComponentsBuilder.fromPath("/hotel list/{city}")
			.queryParam("q", "{q}")
			.build("New York", "foo+bar")
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val uri = UriComponentsBuilder.fromPath("/hotel list/{city}")
			.queryParam("q", "{q}")
			.build("New York", "foo+bar")
----

您可以使用完整的URI模板进一步缩短它，如以下示例所示：

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	URI uri = UriComponentsBuilder.fromPath("/hotel list/{city}?q={q}")
			.build("New York", "foo+bar")
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val uri = UriComponentsBuilder.fromPath("/hotel list/{city}?q={q}")
			.build("New York", "foo+bar")
----

`WebClient` 和 `RestTemplate` 通过 `UriBuilderFactory` 策略在内部扩展和编码URI模板。两者都可以配置自定义策略。 如下例所示：

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	String baseUrl = "https://example.com";
	DefaultUriBuilderFactory factory = new DefaultUriBuilderFactory(baseUrl)
	factory.setEncodingMode(EncodingMode.TEMPLATE_AND_VALUES);

	// Customize the RestTemplate..
	RestTemplate restTemplate = new RestTemplate();
	restTemplate.setUriTemplateHandler(factory);

	// Customize the WebClient..
	WebClient client = WebClient.builder().uriBuilderFactory(factory).build();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val baseUrl = "https://example.com"
	val factory = DefaultUriBuilderFactory(baseUrl).apply {
		encodingMode = EncodingMode.TEMPLATE_AND_VALUES
	}

	// Customize the RestTemplate..
	val restTemplate = RestTemplate().apply {
		uriTemplateHandler = factory
	}

	// Customize the WebClient..
	val client = WebClient.builder().uriBuilderFactory(factory).build()
----

`DefaultUriBuilderFactory` 实现在内部使用 `UriComponentsBuilder` 来扩展和编码URI模板。 作为工厂，它提供了一个单独的位置来配置编码方法，基于以下编码模式之一：

* `TEMPLATE_AND_VALUES`: 使用 `UriComponentsBuilder#encode()` （对应于较早列表中的第一个选项）对URI模板进行预编码，并在扩展时严格编码URI变量。
* `VALUES_ONLY`: 不对URI模板进行编码，而是在将其扩展到模板之前通过 `UriUtils#encodeUriUriVariables` 对URI变量进行严格编码。
* `URI_COMPONENTS`: 在扩展URI变量后，使用 `UriComponents#encode()`（对应于先前列表中的第二个选项）对URI组件值进行编码。
* `NONE`: 未应用编码。

由于历史原因和向后兼容性，将 `RestTemplate` 设置为 `EncodingMode.URI_COMPONENTS`。 `WebClient` 依赖于 `DefaultUriBuilderFactory` 中的默认值，该默认值已从5.0.x中的 `EncodingMode.URI_COMPONENTS` 更改为5.1中的 `EncodingMode.TEMPLATE_AND_VALUES`。
