= 介绍

欢迎来到响应式革命，本书将会带您走入 Spring 广阔而美妙的响应式世界。

响应式编程的目的是帮助您构建更高效，更具弹性的服务，这些服务通常会作为云原生，分布式和微服务。现在的架构和以往是不同的，他们需要面临一些比以往
任何时候都要严厉的要求，需要有新的架构来支持。架构必须支持敏捷性，因此，他们通常被分解为更小的，单一的，有界的上下文或微服务，以更好的
适应团队规模。微服务支持持续交付，微服务还意味着更多的网络通信。这也意味这更多的风险，更多的波动性。服务可能会频繁的进行修改，也可能会突然消失（遭遇停电）等。

响应式编程是解决这些需求的一种方式，它为您提供了一种包含分布式系统易变性的模式和范例。他引入了一种新的建筑思想的新方法。请记住，计算机
资源是有限的，即使是云端的也是如此。响应式编程改变了我们对系统中参与者之间交互的看法，从基于推送的方法转变为基于拉取的方法。

我喜欢响应式编程，多年来我一遍又一遍的尝试接受它。Reactor 在 2011 年发布第一个版本，在 2013 年 Spring Framework 4 中发布基于 Reactor 的 WebSocket 支持，我已经看到了它的潜力，但似乎还没准备好。
我看不出有什么方法可以将响应式编程与 Spring 的组件模型结合起来。直到 Spring Framework 5，它将响应式编程作为 Spring 抽象核心部分，这次的发布我改变了我的看法。突然之间可以编写端到端的响应式应用程序，
突然之间，我可以做一个全面的演示，然后，我做到了。这些年来，我一直再做演讲，博客，文章，播客，现在编写了一本有关响应式编程的书，其中部分原因是
我对这个主题的天然热爱，部分原因是由于我在这个生态系统中的知名度，我得到了许多社区的反馈。

我喜欢响应式编程，它帮助我完成了云原生的转变，从单体到微服务，再到弹性的云原生系统，它有更多的功能，安全性和弹性，可扩展性。但我并没有参与设计它，一开始我甚至都不知道这个主题，我不是什么先行者，我也是在等着别人铺路。
如果你有一直关注，你就会知道 Netflix 是地球上规模最大的服务之一（有大量服务构建在 Spring 之上），它在近 10 年前就采用了响应式编程。你会知道阿里巴巴（有大量基于 Spring 的服务）也接受
了响应式编程。你会看到还有很多大的网站都选择接受响应式编程，因为他们可以构建更好，更适合生产的软件。

如果你在 Spring 上构建响应式服务，你同样可以享受到这样的好处，朋友们，这不是假设，地球上已经有人证明了这一点。现在，加入我们的冒险行列吧，
我们将一起构建响应式驱动的 Spring 应用程序和服务。

现在就是最好的时机，我对大多数应用程序现在支持的许多用例充满信心，现在是接受范式转变的最佳时机，你会加入和你志同道合的关键人群，并未后来者铺平道路

下一章，我们将开始使用 Reactive Spring 进行生产之旅