= 先决条件

别那么快，朋友！我知道你想跳过，我不怪你！但是，在我们进行下一步之前，让我们先花几分钟时间建立一些约定

== 这本书适合谁

本书假设您对编写和运行 Java 有一定的了解，仅此而已。本书的主要目标是帮助人们构建能够投入生产的更好，更具响应力的服务。也许您听说过响应式编程，但也只是相对的对其进行解释，
并且希望这些解释与实际应用相结合。如果是这样，我很高兴您正在阅读这本书

== 这本书需要你做什么

要试用本书中的一些示例代码，您需要一台运行最新操作系统的计算机（Windows、Linux、Mac OS X）。您需要 Java 8 或更高版本，以及 Maven 3.3 或更高版本。我们
会介绍额外的依赖，例如 `MongoDB` 这样的数据库，我们需要的时候我会单独列出来。

== 约定

我们在本书中使用了一些印刷惯例来区分不同类型的信息。

文本块，include 指令，变量，文件名，Css 类名，属性名如下：

[source,text]
----
Spring Boot uses a public static void main entry-point that launches an embedded web server for you.
----

一段代码如下所示。 它可能是彩色的，这取决于您阅读本书的格式。 如果我想提醒您注意某些代码行，这些行将使用带有简短描述的数字进行注释。

[source,java]
----

@Service // <1>
class SimpleService {

}
----
====
<1> 这是一个 Spring 原型注解
====

[TIP]
====
使用这样的标注显示提示。
====

[NOTE]
====
使用这样的标注显示警告。
====

.Sidebar
****
关于某个主题的附加信息可能会显示在像这样的侧边栏中
****

最后，这段文字显示了引用：

[quote,Me]
Spring Boot lets you pair-program with the Spring team


== 反馈

很高兴收到你的反馈

要提交反馈，请发送邮件至 ReactiveSpring@joshlong.com 或 发送推文至 @ReactiveSpring

== 获取源码

本书中所有内容的源码（包括用来构建这本书本身的发布），都可以在 https://github.com/Reactive-Spring-Book[github.com/Reactive-Spring-Book] 上获得。
都是基于 Apache 2 许可，我鼓励你使用它。

== 构建源码

您需要使用 Java 11 +，Maven 3+ 构建和使用此代码。您可以跳转到每个模块的目录中并运行 `mvn clean install` 命令。如果过程中存在任何差异，我
会在每个模块的 README 文件中记录这些差异

== 运行源码

任何 IDE 都可以运行代码，因为他们只不过 `public static void main` 方法和一些类。您可能会使用 Spring Boot Maven 插件的 `mvn spring-boot:run` 运行它们，
但是，许多模块不止一种 `main` 方法，使用插件会破坏插件自动检测应该运行的响应式 Spring 的 `main` 类

此外，某些代码可能对您的系统要求很高！请记住，我们的目标是编写尽可能多的代码，因此这可能是您很长一段时间以来第一次有很多机会看到您的 CPU 能跟上进度。这是一个
很好的问题！这意味着由于您从响应式构建中获得了令人难以置信的效率，您正在全面运行您的系统服务。空闲 CPU 用于服务的日子已经一去不返了

我还注意到，有些东西往往比其他东西消失的更慢。尤其是，我发现从 IDE 中取消时，RSocket 服务有时会缓慢终止。检查您的 `*NIX` 操作系统或者 Windows 的任务管理器，
以确保没有失控的 Java 进程正在运行。我有一些我认为我已经杀死的 RSocket 服务（我点击了 IntelliJ 中的红色按钮！，当然，这意味这它们已经完成并清除了，对吧？）仍然
在运行，占用内存和电量，当我注意到我的 MacBook Pro 2019 无法保持充电时，我才意识到这个问题，即使插上电源也是如此。CPU 负担太重，以至于电流的电荷足够了，所以开始从电池
中汲取电量，而且速度很快。`pkill <PROCESS_ID>` 或者 `sudo kill -9 <PROCESS_ID>` 。或者 Windows 的任务管理器（CTRL + ALT + DELETE），在生成的
任务列表中，找到 java 进程，然后结束任务。

[[java]]
== Java 基础

如果你还没有使用过 Java 8 或更高版本中的一些新特性，那么你可能会喜欢下面的复习

=== 类型推断

Java 11 或更高版本支持一种新形式的类型推断，其中可以推断类型，在赋值的右侧提供足够的信息，然后在左侧中删除定义。

.常规的
[source,java]
----
Customer customer = new Customer(1L,"Jane");
----

类似的

[source,java]
----
var customer = new Customer(1L,"Jane");
----

=== 函数接口，Lambda，和方法引用

Java 8 以后支持 Lambda，Lambda 的方法定义就和类中的匿名类定义一样。它让我们将函数视为一等公民。在 Java 中， Lambda 有一些限制，它们并不是一等公民，但是
也足够接近了。它们必须具有与接口上唯一抽象方法的签名的返回值和参数兼容。这成为函数接口。（接口可能有默认，非抽象的方法，其中接口提供了实现）

JDK 本身提供了一些非常方便且经常使用的函数接口：

* java.util.function.Function<I,O>: 接收 `I` 类型，返回 `O` 类型。这作为通用函数很有用。理论上，所有的其他函数都可以从中衍生。值得庆幸的是，我们没有必要这么做，因为还有其他几个方便的函数接口。
* java.util.function.Predicate<T>：此函数接口接收 `T` 类型，并返回 `boolean`。
* java.util.function.Supplier<T>：没有输入有返回值
* java.util.function.Consumer<T>：`Supplier<T>` 的镜像。接收一个输入，没有返回值

您还可以创建和使用自己定义的函数接口

假如您有以下函数接口

[source,java]
----
@FunctionalInterface
interface MyHandler {
    String handle(String one,int two);
}
----
// link:code:MyHandler[]

这可以用 Java 表示为:

[source,java]
----
MyHandler handler = (one,two) -> "hello";
----

`MyHandler` 类型中的任何方法的任何参数也可以作为 lambda

[source,java]
----
void process(MyHandler mh) {...}

...

process((one,two) -> "Hello");
----

如果您已经有了一个想要使用的方法，它接收一个 `int` 值，并返回一个 `String`，然后只将其输入参数转发给该方法，那么表达这样的一个 lambda 似乎毫无意义，您可以删除 `lambda` 中间的箭头， 并使用方法引用指向该方法。所有的现代 JVM 语言（包括 Java）都支持方法引用

[source,java]
----
class Delegate {
    String pleaseHandle(int one,Date two) {
        return one + ":" + two;
    }
}

// ...

Delegate delegate = new Delegate();
process(delegate::pleaseHandle);
----

=== Lombok（翻译代码时已弃用）

本书中许多代码都使用了 Lombok，一种编译时注解处理器，来扩充 Java 代码。在使用其他 JVM 语言（如 Kotlin）时，Lombok 可能没用。但它可以节省许多空间，在 Java 中，
可以使用  `@Data` 注解来为对象创建一个 `equals()`, `hashCode()` 和 `toString()` 方法。它提供像 `@NoArgsConstructor` 和 `@AllArgsConstructor` 这样的注解来创建
构造函数。它提供了 `@Log4j` 或 `@Log` 这样的注解创建一个名为 `log` 的字段- 在注解使用类中使用日志框架。Lombok 使用 Java 注解处理器来执行此操作。如果你只是
使用 Maven 编译代码。如果您打算编辑代码，请确保为你的 IDE 安装了相关的插件。