[[jc-method]]
= 方法的安全

从 2.0 版开始,Spring Security 大大改进了对为服务层方法增加安全性的支持.
它提供对 JSR-250 注解安全性以及框架原始 `@Secured` 注解的支持.  从 3.0 开始,您还可以使用新的基于表达式的<<el-access,基于表达式的注解>>.  您可以使用 `intercept-methods` 元素来修饰 bean 声明,从而将安全性应用于单个 bean,或者可以使用 AspectJ 样式切入点在整个服务层中保护多个 bean.

[[jc-enable-method-security]]
== EnableMethodSecurity

在 Spring Security 5.6 中，我们可以在任何 `@Configuration` 实例上使用 `@EnableMethodSecurity` 注解启用基于注解的安全。

这以多种方式改进了 `@EnableGlobalMethodSecurity`。 `@EnableMethodSecurity`:

1. 1. 使用简化的 `AuthorizationManager` API 代替元数据, config 属性, decision managers, 和 voters. 这大大方便了进行自定义和重用.
2. 支持基于 bean 的配置，而不是需要扩展 `GlobalMethodSecurityConfiguration` 来自定义 bean
3. 使用原生 Spring AOP 构建，移除抽象，允许您使用 Spring AOP 构建块进行自定义
4. 检查冲突注解以确保明确的安全配置
5. 符合 JSR-250
6. 默认启用 `@PreAuthorize`、`@PostAuthorize`、`@PreFilter` 和 `@PostFilter`

[NOTE]
====
对于早期版本，请阅读 <<jc-enable-global-method-security, @EnableGlobalMethodSecurity>> 的类似支持。
====

例如，以下将启用 Spring Security 的 `@PreAuthorize` 注解：

.Method Security Configuration
====
.Java
[source,java,role="primary"]
----
@Configuration
@EnableMethodSecurity
public class MethodSecurityConfig {
	// ...
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Configuration
@EnableMethodSecurity
class MethodSecurityConfig {
	// ...
}
----

.Xml
[source,xml,role="secondary"]
----
<sec:method-security/>
----
====

向方法（在类或接口上）添加注解将相应地限制对该方法的访问。 Spring Security 的原生注解支持为方法定义了一组属性。
这些将被传递给 `DefaultAuthorizationMethodInterceptorChain` 以做出实际决定:

.Method Security Annotation Usage
====
.Java
[source,java,role="primary"]
----
public interface BankService {
	@PreAuthorize("hasRole('USER')")
	Account readAccount(Long id);

	@PreAuthorize("hasRole('USER')")
	List<Account> findAccounts();

	@PreAuthorize("hasRole('TELLER')")
	Account post(Account account, Double amount);
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
interface BankService {
	@PreAuthorize("hasRole('USER')")
	fun readAccount(id : Long) : Account

	@PreAuthorize("hasRole('USER')")
	fun findAccounts() : List<Account>

	@PreAuthorize("hasRole('TELLER')")
	fun post(account : Account, amount : Double) : Account
}
----
====

您可以使用以下方法启用对 Spring Security 的 `@Secured` 注解的支持：

.@Secured Configuration
====
.Java
[source,java,role="primary"]
----
@Configuration
@EnableMethodSecurity(securedEnabled = true)
public class MethodSecurityConfig {
	// ...
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Configuration
@EnableMethodSecurity(securedEnabled = true)
class MethodSecurityConfig {
	// ...
}
----

.Xml
[source,xml,role="secondary"]
----
<sec:method-security secured-enabled="true"/>
----
====

或使用 JSR-250:

.JSR-250 Configuration
====
.Java
[source,java,role="primary"]
----
@Configuration
@EnableMethodSecurity(jsr250Enabled = true)
public class MethodSecurityConfig {
	// ...
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Configuration
@EnableMethodSecurity(jsr250Enabled = true)
class MethodSecurityConfig {
	// ...
}
----

.Xml
[source,xml,role="secondary"]
----
<sec:method-security jsr250-enabled="true"/>
----
====

=== 自定义 Authorization

Spring Security 的 `@PreAuthorize`, `@PostAuthorize`, `@PreFilter`, 和 `@PostFilter` 提供了丰富的基于表达式的支持.

[[jc-method-security-custom-expression-handler]]
如果您需要自定义处理表达式的方式，您可以暴露一个自定义的 `MethodSecurityExpressionHandler`，如下所示:

.Custom MethodSecurityExpressionHandler
====
.Java
[source,java,role="primary"]
----
@Bean
static MethodSecurityExpressionHandler methodSecurityExpressionHandler() {
	DefaultMethodSecurityExpressionHandler handler = new DefaultMethodSecurityExpressionHandler();
	handler.setTrustResolver(myCustomTrustResolver);
	return handler;
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
companion object {
	@Bean
	fun methodSecurityExpressionHandler() : MethodSecurityExpressionHandler {
		val handler = DefaultMethodSecurityExpressionHandler();
		handler.setTrustResolver(myCustomTrustResolver);
		return handler;
	}
}
----

.Xml
[source,xml,role="secondary"]
----
<sec:method-security>
	<sec:expression-handler ref="myExpressionHandler"/>
</sec:method-security>

<bean id="myExpressionHandler"
		class="org.springframework.security.messaging.access.expression.DefaultMessageSecurityExpressionHandler">
	<property name="trustResolver" ref="myCustomTrustResolver"/>
</bean>
----
====

[TIP]
====
我们使用 `static` 方法暴露 `MethodSecurityExpressionHandler`，以确保 Spring 在初始化 Spring Security 的方法安全 `@Configuration` 类之前公布它
====

此外，对于基于角色的授权，Spring Security 添加了一个默认的 `ROLE_` 前缀，用于评估像 `hasRole` 这样的表达式。

[[jc-method-security-custom-granted-authority-defaults]]
您可以通过公开 `GrantedAuthorityDefaults` bean 来配置授权规则以使用不同的前缀，如下所示：

.Custom MethodSecurityExpressionHandler
====
.Java
[source,java,role="primary"]
----
@Bean
static GrantedAuthorityDefaults grantedAuthorityDefaults() {
	return new GrantedAuthorityDefaults("MYPREFIX_");
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
companion object {
	@Bean
	fun grantedAuthorityDefaults() : GrantedAuthorityDefaults {
		return GrantedAuthorityDefaults("MYPREFIX_");
	}
}
----

.Xml
[source,xml,role="secondary"]
----
<sec:method-security/>

<bean id="grantedAuthorityDefaults" class="org.springframework.security.config.core.GrantedAuthorityDefaults">
	<constructor-arg value="MYPREFIX_"/>
</bean>
----
====

[TIP]
====
我们使用 `static` 方法暴露 `GrantedAuthorityDefaults` 以确保 Spring 在初始化 Spring Security 的方法 security `@Configuration` 类之前公布它
====

[[jc-method-security-custom-authorization-manager]]
=== 自定义授权管理器

方法授权是方法前授权和方法后授权的组合。

[NOTE]
====
方法前授权是在调用方法之前执行的。 如果该授权拒绝访问，则不调用该方法，并抛出 `AccessDeniedException`
方法后授权是在方法被调用之后，但在方法返回给调用者之前执行的。 如果该授权拒绝访问，则不返回该值，并抛出 `AccessDeniedException`
====

要重新创建默认情况下添加 `@EnableMethodSecurity` 所做的事情，您将公布以下配置:

.Full Pre-post Method Security Configuration
====
.Java
[source,java,role="primary"]
----
@Configuration
@EnableMethodSecurity(prePostEnabled = false)
class MethodSecurityConfig {
	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	Advisor preFilterAuthorizationMethodInterceptor() {
		return new PreFilterAuthorizationMethodInterceptor();
	}

	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	Advisor preAuthorizeAuthorizationMethodInterceptor() {
		return AuthorizationManagerBeforeMethodInterceptor.preAuthorize();
	}

	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	Advisor postAuthorizeAuthorizationMethodInterceptor() {
		return AuthorizationManagerAfterMethodInterceptor.postAuthorize();
	}

	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	Advisor postFilterAuthorizationMethodInterceptor() {
		return new PostFilterAuthorizationMethodInterceptor();
	}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Configuration
@EnableMethodSecurity(prePostEnabled = false)
class MethodSecurityConfig {
	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	fun preFilterAuthorizationMethodInterceptor() : Advisor {
		return PreFilterAuthorizationMethodInterceptor();
	}

	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	fun preAuthorizeAuthorizationMethodInterceptor() : Advisor {
		return AuthorizationManagerBeforeMethodInterceptor.preAuthorize();
	}

	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	fun postAuthorizeAuthorizationMethodInterceptor() : Advisor {
		return AuthorizationManagerAfterMethodInterceptor.postAuthorize();
	}

	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	fun postFilterAuthorizationMethodInterceptor() : Advisor {
		return PostFilterAuthorizationMethodInterceptor();
	}
}
----

.Xml
[source,xml,role="secondary"]
----
<sec:method-security pre-post-enabled="false"/>

<aop:config/>

<bean id="preFilterAuthorizationMethodInterceptor"
		class="org.springframework.security.authorization.method.PreFilterAuthorizationMethodInterceptor"/>
<bean id="preAuthorizeAuthorizationMethodInterceptor"
		class="org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor"
		factory-method="preAuthorize"/>
<bean id="postAuthorizeAuthorizationMethodInterceptor"
		class="org.springframework.security.authorization.method.AuthorizationManagerAfterMethodInterceptor"
		factory-method="postAuthorize"/>
<bean id="postFilterAuthorizationMethodInterceptor"
		class="org.springframework.security.authorization.method.PostFilterAuthorizationMethodInterceptor"/>
----
====

请注意，Spring Security 的方法安全性是使用 Spring AOP 构建的。 因此，拦截器是根据指定的顺序调用的。 这可以通过在拦截器实例上调用 `setOrder` 来指定，如下所示:

.Publish Custom Advisor
====
.Java
[source,java,role="primary"]
----
@Bean
@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
Advisor postFilterAuthorizationMethodInterceptor() {
	PostFilterAuthorizationMethodInterceptor interceptor = new PostFilterAuthorizationMethodInterceptor();
	interceptor.setOrder(AuthorizationInterceptorOrders.POST_AUTHORIZE.getOrder() - 1);
	return interceptor;
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
fun postFilterAuthorizationMethodInterceptor() : Advisor {
	val interceptor = PostFilterAuthorizationMethodInterceptor();
	interceptor.setOrder(AuthorizationInterceptorOrders.POST_AUTHORIZE.getOrder() - 1);
	return interceptor;
}
----

.Xml
[source,xml,role="secondary"]
----
<bean id="postFilterAuthorizationMethodInterceptor"
		class="org.springframework.security.authorization.method.PostFilterAuthorizationMethodInterceptor">
	<property name="order"
			value="#{T(org.springframework.security.authorization.method.AuthorizationInterceptorsOrder).POST_AUTHORIZE.getOrder() -1}"/>
</bean>
----
====

您可能只想在应用程序中支持 `@PreAuthorize`，在这种情况下，您可以执行以下操作:


.Only @PreAuthorize Configuration
====
.Java
[source,java,role="primary"]
----
@Configuration
@EnableMethodSecurity(prePostEnabled = false)
class MethodSecurityConfig {
	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	Advisor preAuthorize() {
		return AuthorizationManagerBeforeMethodInterceptor.preAuthorize();
	}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Configuration
@EnableMethodSecurity(prePostEnabled = false)
class MethodSecurityConfig {
	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	fun preAuthorize() : Advisor {
		return AuthorizationManagerBeforeMethodInterceptor.preAuthorize()
	}
}
----

.Xml
[source,xml,role="secondary"]
----
<sec:method-security pre-post-enabled="false"/>

<aop:config/>

<bean id="preAuthorizeAuthorizationMethodInterceptor"
	class="org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor"
	factory-method="preAuthorize"/>
----
====

或者，您可能有一个要添加到列表中的自定义前方法 `AuthorizationManager`。

在这种情况下，您需要告诉 Spring Security `AuthorizationManager` 以及您的授权管理器适用于哪些方法和类。

因此，您可以配置 Spring Security 以在 `@PreAuthorize` 和 `@PostAuthorize` 之间调用您的 `AuthorizationManager`，如下所示:

.Custom Before Advisor
====

.Java
[source,java,role="primary"]
----
@Configuration
@EnableMethodSecurity
class MethodSecurityConfig {
	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	public Advisor customAuthorize() {
		JdkRegexpMethodPointcut pattern = new JdkRegexpMethodPointcut();
		pattern.setPattern("org.mycompany.myapp.service.*");
		AuthorizationManager<MethodInvocation> rule = AuthorityAuthorizationManager.isAuthenticated();
		AuthorizationManagerBeforeMethodInterceptor interceptor = new AuthorizationManagerBeforeMethodInterceptor(pattern, rule);
		interceptor.setOrder(AuthorizationInterceptorsOrder.PRE_AUTHORIZE_ADVISOR_ORDER.getOrder() + 1);
		return interceptor;
    }
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Configuration
@EnableMethodSecurity
class MethodSecurityConfig {
	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	fun customAuthorize() : Advisor {
		val pattern = JdkRegexpMethodPointcut();
		pattern.setPattern("org.mycompany.myapp.service.*");
		val rule = AuthorityAuthorizationManager.isAuthenticated();
		val interceptor = AuthorizationManagerBeforeMethodInterceptor(pattern, rule);
		interceptor.setOrder(AuthorizationInterceptorsOrder.PRE_AUTHORIZE_ADVISOR_ORDER.getOrder() + 1);
		return interceptor;
	}
}
----

.Xml
[source,xml,role="secondary"]
----
<sec:method-security/>

<aop:config/>

<bean id="customAuthorize"
		class="org.springframework.security.authorization.method.AuthorizationManagerBeforeMethodInterceptor">
	<constructor-arg>
		<bean class="org.springframework.aop.support.JdkRegexpMethodPointcut">
			<property name="pattern" value="org.mycompany.myapp.service.*"/>
		</bean>
	</constructor-arg>
	<constructor-arg>
		<bean class="org.springframework.security.authorization.AuthorityAuthorizationManager"
				factory-method="isAuthenticated"/>
	</constructor-arg>
	<property name="order"
			value="#{T(org.springframework.security.authorization.method.AuthorizationInterceptorsOrder).PRE_AUTHORIZE_ADVISOR_ORDER.getOrder() + 1}"/>
</bean>
----
====

[TIP]
====
您可以使用 `AuthorizationInterceptorsOrder` 中指定的顺序常量将拦截器放置在 Spring Security 方法拦截器之间。
====

对于方法后授权也可以这样做。 方法后授权通常涉及分析返回值以验证访问。

例如，您可能有一个方法可以确认请求的帐户实际上属于登录用户，如下所示:

.@PostAuthorize example
====
.Java
[source,java,role="primary"]
----
public interface BankService {

	@PreAuthorize("hasRole('USER')")
	@PostAuthorize("returnObject.owner == authentication.name")
	Account readAccount(Long id);
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
interface BankService {

	@PreAuthorize("hasRole('USER')")
	@PostAuthorize("returnObject.owner == authentication.name")
	fun readAccount(id : Long) : Account
}
----
====

您可以提供自己的 `AuthorizationMethodInterceptor` 来自定义如何评估对返回值的访问。
例如，如果你有自己的自定义注解，你可以像这样配置它：:

.Custom After Advisor
====
.Java
[source,java,role="primary"]
----
@Configuration
@EnableMethodSecurity
class MethodSecurityConfig {
	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	public Advisor customAuthorize(AuthorizationManager<MethodInvocationResult> rules) {
		AnnotationMethodMatcher pattern = new AnnotationMethodMatcher(MySecurityAnnotation.class);
		AuthorizationManagerAfterMethodInterceptor interceptor = new AuthorizationManagerAfterMethodInterceptor(pattern, rules);
		interceptor.setOrder(AuthorizationInterceptorsOrder.POST_AUTHORIZE_ADVISOR_ORDER.getOrder() + 1);
		return interceptor;
	}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Configuration
@EnableMethodSecurity
class MethodSecurityConfig {
	@Bean
	@Role(BeanDefinition.ROLE_INFRASTRUCTURE)
	fun customAuthorize(rules : AuthorizationManager<MethodInvocationResult>) : Advisor {
		val pattern = AnnotationMethodMatcher(MySecurityAnnotation::class.java);
		val interceptor = AuthorizationManagerAfterMethodInterceptor(pattern, rules);
		interceptor.setOrder(AuthorizationInterceptorsOrder.POST_AUTHORIZE_ADVISOR_ORDER.getOrder() + 1);
		return interceptor;
	}
}
----

.Xml
[source,xml,role="secondary"]
----
<sec:method-security/>

<aop:config/>

<bean id="customAuthorize"
		class="org.springframework.security.authorization.method.AuthorizationManagerAfterMethodInterceptor">
	<constructor-arg>
		<bean class="org.springframework.aop.support.annotation.AnnotationMethodMatcher">
			<constructor-arg value="#{T(org.mycompany.MySecurityAnnotation)}"/>
		</bean>
	</constructor-arg>
	<constructor-arg>
		<bean class="org.springframework.security.authorization.AuthorityAuthorizationManager"
				factory-method="isAuthenticated"/>
	</constructor-arg>
	<property name="order"
		value="#{T(org.springframework.security.authorization.method.AuthorizationInterceptorsOrder).PRE_AUTHORIZE_ADVISOR_ORDER.getOrder() + 1}"/>
</bean>
----
====

它将在 `@PostAuthorize` 拦截器之后被调用。

[[jc-enable-global-method-security]]
== EnableGlobalMethodSecurity

我们可以在任何 `@Configuration` 实例上使用 `@EnableGlobalMethodSecurity` 注解启用基于注解的安全性.  例如,以下将启用Spring Security的 `@Secured` 注解.

====
.Java
[source,java,role="primary"]
----
@Configuration
@EnableGlobalMethodSecurity(securedEnabled = true)
public class MethodSecurityConfig {
// ...
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Configuration
@EnableGlobalMethodSecurity(securedEnabled = true)
open class MethodSecurityConfig {
	// ...
}
----
====

向方法(在类或接口上) 添加注解将相应地限制对该方法的访问.  Spring Security 的内置注解支持为该方法定义了一组属性.  这些将被传递给 `AccessDecisionManager` 做出实际决定:

====
.Java
[source,java,role="primary"]
----
public interface BankService {

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
public Account readAccount(Long id);

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
public Account[] findAccounts();

@Secured("ROLE_TELLER")
public Account post(Account account, double amount);
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
interface BankService {
    @Secured("IS_AUTHENTICATED_ANONYMOUSLY")
    fun readAccount(id: Long): Account

    @Secured("IS_AUTHENTICATED_ANONYMOUSLY")
    fun findAccounts(): Array<Account>

    @Secured("ROLE_TELLER")
    fun post(account: Account, amount: Double): Account
}
----
====

可以使用以下命令启用对 JSR-250 注解的支持

====
.Java
[source,java,role="primary"]
----
@Configuration
@EnableGlobalMethodSecurity(jsr250Enabled = true)
public class MethodSecurityConfig {
// ...
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Configuration
@EnableGlobalMethodSecurity(jsr250Enabled = true)
open class MethodSecurityConfig {
	// ...
}
----
====

这些是基于标准的,并允许应用基于角色的简单约束,但是没有 Spring Security 的内置注解的强大功能.
要使用新的基于表达式的语法,可以使用

====
.Java
[source,java,role="primary"]
----
@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class MethodSecurityConfig {
// ...
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true)
open class MethodSecurityConfig {
	// ...
}
----
====

而等效的 Java 代码将是

====
.Java
[source,java,role="primary"]
----
public interface BankService {

@PreAuthorize("isAnonymous()")
public Account readAccount(Long id);

@PreAuthorize("isAnonymous()")
public Account[] findAccounts();

@PreAuthorize("hasAuthority('ROLE_TELLER')")
public Account post(Account account, double amount);
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
interface BankService {
    @PreAuthorize("isAnonymous()")
    fun readAccount(id: Long): Account

    @PreAuthorize("isAnonymous()")
    fun findAccounts(): Array<Account>

    @PreAuthorize("hasAuthority('ROLE_TELLER')")
    fun post(account: Account, amount: Double): Account
}
----
====

== GlobalMethodSecurityConfiguration

有时您可能需要执行比 `@EnableGlobalMethodSecurity` 注解允许的操作更复杂的操作.  对于这些实例,可以扩展 `GlobalMethodSecurityConfiguration`,以确保 `@EnableGlobalMethodSecurity` 注解出现在子类中.
例如,如果您想提供一个自定义的 `MethodSecurityExpressionHandler`,则可以使用以下配置:

====
.Java
[source,java,role="primary"]
----
@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class MethodSecurityConfig extends GlobalMethodSecurityConfiguration {
	@Override
	protected MethodSecurityExpressionHandler createExpressionHandler() {
		// ... create and return custom MethodSecurityExpressionHandler ...
		return expressionHandler;
	}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Configuration
@EnableGlobalMethodSecurity(prePostEnabled = true)
open class MethodSecurityConfig : GlobalMethodSecurityConfiguration() {
    override fun createExpressionHandler(): MethodSecurityExpressionHandler {
        // ... create and return custom MethodSecurityExpressionHandler ...
        return expressionHandler
    }
}
----
====

有关可以覆盖的方法的其他信息,请参考 {security-api-url}org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.html[`GlobalMethodSecurityConfiguration`] Javadoc.

[[ns-global-method]]
== <global-method-security> 元素
此元素用于在您的应用程序中启用基于注解的安全性(通过在该元素上设置适当的属性) ,并将用于整个应用程序上下文的安全性切入点声明组合在一起.  您只应声明一个 `<global-method-security>` 元素.
以下声明将启用对 Spring Security 的 `@Secured` 的支持:

====
[source,xml]
----
<global-method-security secured-annotations="enabled" />
----
====

向方法(在类或接口上) 添加注解将相应地限制对该方法的访问.  Spring Security 的内置注解支持为该方法定义了一组属性.  这些将被传递给 `AccessDecisionManager` 做出实际决定:

====
.Java
[source,java,role="primary"]
----
public interface BankService {

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
public Account readAccount(Long id);

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
public Account[] findAccounts();

@Secured("ROLE_TELLER")
public Account post(Account account, double amount);
}
----


.Kotlin
[source,kotlin,role="secondary"]
----
interface BankService {
    @Secured("IS_AUTHENTICATED_ANONYMOUSLY")
    fun readAccount(id: Long): Account

    @Secured("IS_AUTHENTICATED_ANONYMOUSLY")
    fun findAccounts(): Array<Account>

    @Secured("ROLE_TELLER")
    fun post(account: Account, amount: Double): Account
}
----
====

可以使用以下命令启用对 JSR-250 注解的支持

====
[source,xml]
----
<global-method-security jsr250-annotations="enabled" />
----
====

这些是基于标准的,并允许应用基于角色的简单约束,但是没有 Spring Security 的内置注解的强大功能.  要使用新的基于表达式的语法,可以使用

====
[source,xml]
----
<global-method-security pre-post-annotations="enabled" />
----
====

而等效的 Java 代码将是

====
.Java
[source,java,role="primary"]
----
public interface BankService {

@PreAuthorize("isAnonymous()")
public Account readAccount(Long id);

@PreAuthorize("isAnonymous()")
public Account[] findAccounts();

@PreAuthorize("hasAuthority('ROLE_TELLER')")
public Account post(Account account, double amount);
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
interface BankService {
    @PreAuthorize("isAnonymous()")
    fun readAccount(id: Long): Account

    @PreAuthorize("isAnonymous()")
    fun findAccounts(): Array<Account>

    @PreAuthorize("hasAuthority('ROLE_TELLER')")
    fun post(account: Account, amount: Double): Account
}
----
====

如果您需要定义简单的规则,而不是根据用户的权限列表检查角色名称,则基于表达式的注解是一个不错的选择.

[NOTE]
====
带注解的方法仅对于定义为 Spring Bean 的实例(在启用方法安全性的同一应用程序上下文中) 是安全的.  如果要保护不是由 Spring 创建的实例(例如,使用 new 运算符) ,则需要使用 AspectJ.
====

[NOTE]
====
您可以在同一应用程序中启用不止一种类型的注解,但是任何接口或类都只能使用一种类型的注解,否则将无法很好地定义行为.  如果找到两个适用于特定方法的注解,则将仅应用其中一个
====

[[ns-protect-pointcut]]
== 使用  protect-pointcut 添加安全的切点

`protect-pointcut` 的使用特别强大,因为它允许您仅通过简单的声明就可以将安全性应用于许多 bean.  考虑以下示例:

====
[source,xml]
----
<global-method-security>
<protect-pointcut expression="execution(* com.mycompany.*Service.*(..))"
	access="ROLE_USER"/>
</global-method-security>
----
====

此配置保护在应用程序上下文中声明的 bean(其类位于 `com.mycompany` 包中且其类名以 "Service" 结尾) 上的所有方法.  只有具有 `ROLE_USER` 角色的用户才能调用这些方法.  与 URL 匹配一样,最具体的匹配项必须在切入点列表中排在第一位,因为将使用第一个匹配表达式.  安全注解优先于切入点.
