[[declaring-component-capabilities]]
= Declaring Capabilities of a Library

== Capabilities as first-level concept

组件提供了许多功能，这些功能通常与用于提供那些功能的软件体系结构正交。 例如，一个库可能在单个工件中包含多个功能。 但是，这样的库将以单个 GAV（组，工件和版本）坐标发布。
 这意味着，在单个坐标处，可能会共存组件的不同“特征”。

使用 Gradle，显式声明组件提供的功能变得很有趣。为此，Gradle 提供了 <<dependency_constraints.adoc#sec:adding-constraints-transitive-deps,capability>> 的概念。

通常通过组合不同的  _capabilities_ 来构建功能。.

在理想情况下，组件不应声明对显式 GAV 的依赖，而应在功能方面表达其要求：

- "give me a component which provides logging"
- "give me a scripting engine"
- "give me a scripting engine that supports Groovy"

通过对 _capabilities_ 进行建模，依赖管理引擎可以更智能，并在依赖图中具有 _incompatible capabilities_ 时告诉您，或者让您选择何时图中的不同模块提供相同功能。

[[sec:declaring-capabilities-external-modules]]
== 声明外部模块的 capabilities

值得注意的是，Gradle 支持声明的功能可用于构建的组件，也可以声明外部的组件（如果没有）。

例如，如果您的构建文件包含以下依赖项：

.A build file with an implicit conflict of logging frameworks
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/groovy/build.gradle[tags=dependencies]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/kotlin/build.gradle.kts[tags=dependencies]
====

实际上，很难想象在类路径中会出现两个日志框架。实际上，`zookeeper` 将引入 `log4j`，我们想在其中使用的是 `log4j-over-slf4j`。我们可以通过添加一条规则来预先检测冲突，
该规则将声明这两个日志框架提供相同的功能

.A build file with an implicit conflict of logging frameworks
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/groovy/build.gradle[tags=declare_capability]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/kotlin/build.gradle.kts[tags=declare_capability]
====

通过添加此规则，我们将确保 Gradle 将检测到冲突并适当地失败：

----
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve org.slf4j:log4j-over-slf4j:1.7.10.
     Required by:
         project :
      > Module 'org.slf4j:log4j-over-slf4j' has been rejected:
           Cannot select module with conflict on capability 'log4j:log4j:1.7.10' also provided by [log4j:log4j:1.2.16(compile)]
   > Could not resolve log4j:log4j:1.2.16.
     Required by:
         project : > org.apache.zookeeper:zookeeper:3.4.9
      > Module 'log4j:log4j' has been rejected:
           Cannot select module with conflict on capability 'log4j:log4j:1.2.16' also provided by [org.slf4j:log4j-over-slf4j:1.7.10(compile)]
----

请参阅文档的  <<dependency_capability_conflict.adoc#sub:selecting-between-candidates, capabilities section of the documentation>>  部分，以了解如何解决功能冲突。

== 声明本地组件的其他 capabilities

所有组件都具有与该组件相同的 GAV 坐标对应的隐式功能。 只要在不同 GAV 坐标处发布的库是同一 API 的替代实现，就很方便。 但是，也可以为组件声明其他显式功能：

.Declaring capabilities of a component
====
include::{snippets-dir}/dependencyManagement/modelingFeatures-outgoingCapabilities/groovy/build.gradle[tags=declare-outgoing-capabilities]
include::{snippets-dir}/dependencyManagement/modelingFeatures-outgoingCapabilities/kotlin/build.gradle.kts[tags=declare-outgoing-capabilities]
====

Capabilities 必须附加到输出配置，这是组件的可 <<declaring_dependencies.adoc#sec:resolvable-consumable-configs,consumable configurations>>。这个例子说明了我们声明了两个功能

此示例显示我们声明了两个 capabilities:

1. `com.acme:my-library:1.0`, 对应于库的隐​​式功能
2. `com.other:module:1.1`, 这对应于该库的另一个功能

值得注意的是，我们需要执行 1.，因为一旦您开始声明显式功能，就需要声明 能，包括 _explicit_ capabilities。

第二 capability 可以特定于此库，也可以对应于外部组件提供的功能。 在这种情况下，如果 `com.other：module` 出现在同一依赖关系图中，则构建将失败，<<dependency_capability_conflict.adoc#sub:selecting-between-candidates,并且使用者将不得不选择要使用的模块>>。

Capabilities 已发布到 Gradle 模块元数据。 但是，它们在 POM 或 Ivy 元数据文件中没有等效项。 因此，发布此类组件时，Gradle 将警告您该功能仅适用于 Gradle 使用者：

----
Maven publication 'maven' contains dependencies that cannot be represented in a published pom file.
  - Declares capability com.acme:my-library:1.0
  - Declares capability com.other:module:1.1
----
