[[howto.application]]
== Spring Boot Application
本部分包括与 Spring Boot 应用程序直接相关的主题.

[[howto.application.failure-analyzer]]
=== 创建自己的 FailureAnalyzer
{spring-boot-module-api}/diagnostics/FailureAnalyzer.html[`FailureAnalyzer`] 这是拦截启动时将异常转化为人类可读消息 (包装在) 的一种好方法 {spring-boot-module-api}/diagnostics/FailureAnalysis.html[`FailureAnalysis`].
Spring Boot 为与应用程序上下文相关的异常,JSR-303 验证等提供了此类分析器. 您也可以创建自己的.  .

`AbstractFailureAnalyzer` 是一个方便的扩展,`FailureAnalyzer` 它检查要处理的异常中是否存在指定的异常类型. 您可以对此进行扩展,以便您的实现只有在异常出现时才有机会处理该异常. 如果由于某种原因无法处理该异常,请返回 `null` 以使另一个实现有机会处理该异常.

`FailureAnalyzer` 实现必须在 `META-INF/spring.factories` 中注册. 以下示例注册 `ProjectConstraintViolationFailureAnalyzer`:

[source,properties,indent=0,subs="verbatim"]
----
	org.springframework.boot.diagnostics.FailureAnalyzer=\
	com.example.ProjectConstraintViolationFailureAnalyzer
----

NOTE: 如果您需要访问 `BeanFactory` 或 `Environment`,则 `FailureAnalyzer` 可以分别实现 `BeanFactoryAware` 或 `EnvironmentAware`.

[[howto.application.troubleshoot-auto-configuration]]
=== 自动配置故障排除
Spring Boot 自动配置会尽力 "做正确的事",但有时会失败,并且很难说出原因.

`ConditionEvaluationReport` 任何 Spring Boot 都有一个非常有用的功能 `ApplicationContext`. 如果启用 `DEBUG` 日志记录输出,则可以看到它. 如果使用 `spring-boot-actuator` (请参阅  <<actuator#actuator, Actuator >> 一章) ,
那么还有一个 `conditions` 端点,该端点以 JSON 形式呈现报告. 使用该端点来调试应用程序,并在运行时查看 Spring Boot 添加了哪些功能 (尚未添加) .

通过查看源代码和 Javadoc,可以回答更多问题. 阅读代码时,请记住以下经验法则:

* 查找被调用的类 `+*AutoConfiguration+` 并阅读其源代码. 特别注意 `+@Conditional*+` 注解,以了解它们启用了哪些功能以及何时启用.
添加 `--debug` 到命令行或系统属性 `-Ddebug` 以在控制台上获取在您的应用中做出的所有自动配置决策的日志. 在启用了 Actuator 的运行应用程序中,查看 `conditions` 端点 (`/actuator/conditions` 或等效的JMX) 以获取相同信息.
* 查找属于 `@ConfigurationProperties` (例如 {spring-boot-autoconfigure-module-code}/web/ServerProperties.java[`ServerProperties`]) 的类,然后从中读取可用的外部配置选项.
该 `@ConfigurationProperties` 注解具有一个 `name` 充当前缀外部性能属性. 因此,`ServerProperties` 拥有 `prefix="server"` 和它的配置性能 `server.port,server.address` 以及其他. 在启用了 Actuator 的运行应用程序中,查看 `configprops` 端点.
* 寻找对 `bind` 方法的使用,以一种轻松的方式 `Binder` 将配置值明确地拉出 `Environment`. 它通常与前缀一起使用.
* 查找 `@Value` 直接绑定到的注解 `Environment`.
* 寻找 `@ConditionalOnExpression` 注解以响应SpEL表达式来打开或关闭功能,这些注解通常使用从中解析的占位符进行评估 `Environment`.

[[howto.application.customize-the-environment-or-application-context]]
=== 启动之前自定义环境或 ApplicationContext
一个 `SpringApplication` 具有 `ApplicationListeners` 与 `ApplicationContextInitializers` 被用于应用自定义的上下文或环境. Spring Boot 加载了许多此类自定义项,以供内部使用 `META-INF/spring.factories` . 注册其他自定义项的方法有多种:

* 在运行之前,通过对每个应用程序进行编程,方法是调用 `SpringApplication` 的 `addListeners` 和 `addInitializers` 方法.
* 通过设置 `context.initializer.classes` 或 `context.listener.classes` 属性,以声明的方式针对每个应用程序.
* 声明性地,对于所有应用程序,通过添加 `META-INF/spring.factories` 和打包一个 jar 文件,这些文件都被应用程序库.

该 `SpringApplication` 将一些特殊的 `ApplicationEvents` 发送给监听器 (有些甚至在上下文创建之前) ,然后为 `ApplicationContext` 发布的事件注册监听器. 有关完整列表,请参见 '`Spring Boot 特性`'  部分中的 "`<<features#features.spring-application.application-events-and-listeners,应用程序事件和监听器>>`" .

还可以使用来自定义 `Environment` 刷新应用程序上下文之前的 `EnvironmentPostProcessor`. 每个实现都应在 `META-INF/spring.factories` 中注册,如以下示例所示:

[indent=0]
----
	org.springframework.boot.env.EnvironmentPostProcessor=com.example.YourEnvironmentPostProcessor
----

该实现可以加载任意文件并将其添加到中 `Environment`. 例如,以下示例从类路径加载 YAML 配置文件:

include::code:MyEnvironmentPostProcessor[]

TIP: 在 `Environment` 已经准备好了 Spring Boot 默认加载的所有常用属性源. 因此可以从环境中获取文件的位置. 前面的示例将 `custom-resource` 属性源添加到列表的末尾,以便在其他任何常见位置定义的 key 具有优先权. 自定义实现可以定义另一个顺序.

CAUTION: 虽然在 `@SpringBootApplication` 上使用 `@PropertySource` 似乎是在环境中加载自定义资源的便捷方法， 但我们不建议您这样做. 在刷新应用程序上下文之前， 不会将此类属性源添加到 `Environment` 中. 现在配置某些属性 (如 `+logging.*+` 和 `+spring.main.*+` ) 为时已晚,这些属性在刷新开始之前已读取. .

[[howto.application.context-hierarchy]]
=== 建立 ApplicationContext 层次结构 (添加父上下文或根上下文)
您可以使用 `ApplicationBuilder` 类创建父/子 `ApplicationContext` 层次结构. 有关更多信息,请参见  '`Spring Boot 特性`' 部分中的 "`<<features#features.spring-application.fluent-builder-api>>`".

[[howto.application.non-web-application]]
=== 创建一个非 Web 应用程序
并非所有的 Spring 应用程序都必须是 Web 应用程序 (或 Web 服务) . 如果要在 `main` 方法中执行一些代码,又要引导 Spring 应用程序以设置要使用的基础结构,则可以使用 Spring Boot 的 `SpringApplication` 功能.
`SpringApplication` 根据是否认为需要 Web 应用程序来更改其 `ApplicationContext` 类. 您可以做的第一件事是让服务器相关的依赖 (例如 Servlet API) 脱离类路径.
如果你不能做到这一点 (例如,您从相同的代码库的两个应用程序) ,则可以在 `SpringApplication` 实例上显式调用 `setWebApplicationType(WebApplicationType.NONE)` 或设置 `applicationContextClass` 属性 (通过 Java API 或与外部属性) .
您可以将要作为业务逻辑运行的应用程序代码实现为 `CommandLineRunner` 并作为 `@Bean` 定义放到上下文中.
