[[howto.batch]]
== Batch Applications
当人们从 Spring Boot 应用程序中使用 Spring Batch 时,经常会出现许多问题.  本节解决这些问题.

[[howto.batch.specifying-a-data-source]]
=== 指定批处理数据源
默认情况下,批处理应用程序需要一个 `DataSource` 来存储作业详细信息.  批处理在您的上下文中自动装配单个数据源,并将其用于处理.  要使批处理使用应用程序的主  `DataSource` 以外的其他  `DataSource` ,请声明一个  `DataSource` bean,并用 `@BatchDataSource` 注解其 `@Bean` 方法.
如果这样做并想要两个数据源,请记住创建另一个数据源并将其标记为 `@Primary`.  为了更好地控制,请实现 `BatchConfigurer`.  有关更多详细信息,请参见 {spring-batch-api}/core/configuration/annotation/EnableBatchProcessing.html[The Javadoc of `@EnableBatchProcessing`] 的Javadoc.

有关 Spring Batch 的更多信息,请参见 {spring-batch}[Spring Batch 项目页面].

[[howto.batch.running-jobs-on-startup]]
=== 在启动时执行 Spring Batch 作业
通过在 `@Configuration` 类的某个位置添加 `@EnableBatchProcessing`,可以启用 Spring Batch 自动配置.

如果在应用上下文中发现单个 `Job`,则会在启动时执行（有关详细信息，请参见 {spring-boot-autoconfigure-module-code}/batch/JobLauncherApplicationRunner.java[`JobLauncherApplicationRunner`]）。
如果有多个 `Job`,  则必须使用 `spring.batch.job.name` 指定应执行的作业。

要禁用运行在应用程序内容中找到的 `Job`，请将 `spring.batch.job.enabled` 设置为 `false`。

[[howto.batch.running-from-the-command-line]]
=== 在命令行上运行
Spring Boot 将任何以 `--` 开头的命令行参数转换为一个属性以添加到 `Environment` 中,请参见 <<features#features.external-config.command-line-args,访问命令行属性>>.
不应该将其作为参数传递给批处理作业.
要在命令行上指定批处理参数,请使用常规格式 (即不使用 `--` ) ,如以下示例所示:

[source,shell,indent=0,subs="verbatim"]
----
	$ java -jar myapp.jar someParameter=someValue anotherParameter=anotherValue
----

如果在命令行上指定 `Environment` 的属性,它将被作业忽略.
考虑以下命令:

[source,shell,indent=0,subs="verbatim"]
----
	$ java -jar myapp.jar --server.port=7070 someParameter=someValue
----

这仅为批处理作业提供了一个参数: `someParameter=someValue`

[[howto.batch.storing-job-repository]]
=== 存储 Job Repository
Spring Batch 需要一个用于 Job 仓库的数据存储.
如果使用 Spring Boot,则必须使用实际的数据库.
请注意,它可以是内存数据库,请参见 {spring-batch-docs} job.html#configuringJobRepository[配置作业存储库].
