[[howto.build]]
== 构建
Spring Boot 包括 Maven 和 Gradle 的构建插件.  本部分回答有关这些插件的常见问题.

[[howto.build.generate-info]]
=== 生成构建信息
Maven 插件和 Gradle 插件都允许生成包含项目的坐标,名称和版本的构建信息.  还可以将插件配置为通过配置添加其他属性.  当存在这样的文件时,Spring Boot 会自动配置 `BuildProperties` bean.

要使用 Maven 生成构建信息,请为 `build-info` 目标添加执行,如以下示例所示:

[source,xml,indent=0,subs="verbatim,attributes"]
----
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>{spring-boot-version}</version>
				<executions>
					<execution>
						<goals>
							<goal>build-info</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
----

TIP: 有关更多详细信息,请参见 {spring-boot-maven-plugin-docs}#goals-build-info[Spring Boot Maven 插件文档].

下面的示例对 Gradle 执行相同的操作:

[source,gradle,indent=0,subs="verbatim"]
----
	springBoot {
		buildInfo()
	}
----

TIP: 有关更多详细信息,请参见 {spring-boot-gradle-plugin-docs}#integrating-with-actuator-build-info[Spring Boot Gradle 插件文档] .

[[howto.build.generate-git-info]]
=== 生成 Git 信息
Maven 和 Gradle 都允许生成一个 `git.properties` 文件,其中包含有关构建项目时 git 源代码仓库状态的信息.

对于 Maven 用户,`spring-boot-starter-parent` POM包含一个预先配置的插件,用于生成 `git.properties` 文件.  要使用它,请将以下声明添加到您的 POM 中:

[source,xml,indent=0,subs="verbatim"]
----
	<build>
		<plugins>
			<plugin>
				<groupId>io.github.git-commit-id</groupId>
				<artifactId>git-commit-id-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
----

Gradle 用户可以使用 https://plugins.gradle.org/plugin/com.gorylenko.gradle-git-properties[`gradle-git-properties`] 插件获得相同的结果,如以下示例所示:

[source,gradle,indent=0,subs="verbatim"]
----
	plugins {
		id "com.gorylenko.gradle-git-properties" version "2.3.2"
	}
----

Maven 和 Gradle 插件都允许配置 `git.properties` 中包含的属性.

TIP: `git.properties` 中的提交时间应与以下格式匹配: `yyyy-MM-dd'T'HH:mm:ssZ`.  这是上面列出的两个插件的默认格式.  使用这种格式,可以将时间解析为  `Date`,并将其序列化为 JSON 后,由杰克逊的日期序列化配置设置控制.

[[howto.build.customize-dependency-versions]]
=== 自定义依赖版本
spring-boot-dependencies POM 管理常见依赖的版本. Maven 和 Gradle 的 Spring Boot 插件允许使用构建属性来自定义这些托管依赖版本.

WARNING: 每个 Spring Boot 发行版均针对这组特定的第三方依赖进行了设计和测试. 覆盖版本可能会导致兼容性问题.

要在 Maven 中覆盖依赖版本,请参阅  Maven 插件文档的  {spring-boot-maven-plugin-docs}#using[这一部分].

要在 Gradle 中覆盖依赖版本,请参阅 Gradle 插件文档的 {spring-boot-gradle-plugin-docs}#managing-dependencies-dependency-management-plugin-customizing[这一部分].

[[howto.build.create-an-executable-jar-with-maven]]
=== 使用 Maven 创建可执行 JAR
`spring-boot-maven-plugin` 可用于创建可执行的  "`fat`"  JAR.  如果使用 `spring-boot-starter-parent` 父POM,则可以声明插件,然后将 jar 重新打包,如下所示:

[source,xml,indent=0,subs="verbatim"]
----
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
----

如果您不使用父 POM,则仍然可以使用该插件.  但是,您必须另外添加一个  `<executions>` 部分,如下所示:

[source,xml,indent=0,subs="verbatim"]
----
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>{spring-boot-version}</version>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
----

有关完整用法的详细信息,请参阅 {spring-boot-maven-plugin-docs}#repackage[插件文档] .

[[howto.build.use-a-spring-boot-application-as-dependency]]
=== 使用 Spring Boot 应用程序作为依赖
像 war 文件一样,Spring Boot 应用程序也不打算用作依赖.  如果您的应用程序包含要与其他项目共享的类,则建议的方法是将该代码移到单独的模块中.  然后,您的应用程序和其他项目可以依赖单独的模块.

如果您无法按照上面的建议重新排列代码,则必须配置 Spring Boot 的 Maven 和 Gradle 插件以生成单独的 artifacts ,该 artifacts 适合用作依赖.  可执行存档不能用作依赖,因为 <<executable-jar#appendix.executable-jar.nested-jars.jar-structure,可执行jar格式>>  `BOOT-INF/classes` 中的应用程序类打包.
这意味着当将可执行 jar 用作依赖时,找不到它们.

为了产生两个 artifacts ,一个可以用作依赖,另一个可以执行,必须指定分类器.  该分类器应用于可执行归档文件的名称,保留默认归档文件以用作依赖.

要在 Maven 中配置 `exec` 的 classifier,可以使用以下配置:

[source,xml,indent=0,subs="verbatim"]
----
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<classifier>exec</classifier>
				</configuration>
			</plugin>
		</plugins>
	</build>
----

[[howto.build.extract-specific-libraries-when-an-executable-jar-runs]]
=== 运行可执行 jar 时提取特定的库
可执行 jar 中的大多数嵌套库不需要解压即可运行.  但是,某些库可能会有问题.  例如,JRuby 包含其自己的嵌套 jar 支持,它假定 `jruby-complete.jar` 始终可以直接作为文件直接使用.

为了处理任何有问题的库,您可以标记在可执行 jar 首次运行时应自动解压缩特定的嵌套 jar.  这种嵌套的 jar 会写在 `java.io.tmpdir` 系统属性标识的临时目录下.

WARNING: 应注意确保已配置您的操作系统,以便在应用程序仍在运行时,它不会删除已解压缩到临时目录中的 jar.

例如,为了指示应该使用 Maven 插件将 JRuby 标记为要解包,您可以添加以下配置:

[source,xml,indent=0,subs="verbatim"]
----
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<requiresUnpack>
						<dependency>
							<groupId>org.jruby</groupId>
							<artifactId>jruby-complete</artifactId>
						</dependency>
					</requiresUnpack>
				</configuration>
			</plugin>
		</plugins>
	</build>
----

[[howto.build.create-a-nonexecutable-jar]]
=== 创建带有排除项的不可执行的 JAR
通常,如果您具有一个可执行文件和一个不可执行的 jar 作为两个单独的构建产品,则可执行版本具有库 jar 中不需要的其他配置文件.  例如,`application.yml` 配置文件可能被排除在不可执行的 JAR 中.

在 Maven 中,可执行 jar 必须是主要 artifacts ,您可以为库添加一个 classified jar,如下所示:

[source,xml,indent=0,subs="verbatim"]
----
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<artifactId>maven-jar-plugin</artifactId>
				<executions>
					<execution>
						<id>lib</id>
						<phase>package</phase>
						<goals>
							<goal>jar</goal>
						</goals>
						<configuration>
							<classifier>lib</classifier>
							<excludes>
								<exclude>application.yml</exclude>
							</excludes>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
----

[[howto.build.remote-debug-maven]]
=== 远程调试以 Maven 开头的 Spring Boot 应用程序
要将远程调试器附加到使用 Maven 启动的 Spring Boot 应用程序,可以使用 {spring-boot-maven-plugin-docs}[maven 插件] 的 `jvmArguments` 属性.

有关更多详细信息,请参见此 {spring-boot-maven-plugin-docs}#run-example-debug[示例].

[[howto.build.build-an-executable-archive-with-ant-without-using-spring-boot-antlib]]
=== 在不使用 spring-boot-antlib 的情况下从 Ant 构建可执行归档文件
要使用 Ant 进行构建,您需要获取依赖,进行编译,然后创建一个 jar 或 war 存档.  要使其可执行,可以使用 `spring-boot-antlib` 模块,也可以按照以下说明进行操作:

. 如果您要构建 jar,请将应用程序的类和资源打包在嵌套的 `BOOT-INF/classes` 目录中.  如果要打仗,请照常将应用程序的类打包在嵌套的 `WEB-INF/classes` 目录中.
. 将运行时依赖添加到 jar 的嵌套  `BOOT-INF/lib` 目录中,或将其添加到 war 的 `WEB-INF/lib` 中.  切记不要压缩存档中的条目.
. 将  `provided` 的 (嵌入式容器) 依赖添加到jar的嵌套 `BOOT-INF/lib` 目录中,或将 war 添加到  `WEB-INF/lib` 提供的嵌套目录中.  切记不要压缩存档中的条目.
. 在归档文件的根目录中添加 `spring-boot-loader` 类 (以便可以使用 `Main-Class`) .
. 使用适当的启动器 (例如 jar 文件的 `JarLauncher`) 作为清单中的 `Main-Class` 属性,并通过设置 `Start-Class` 属性指定它作为清单条目所需的其他属性.

以下示例显示了如何使用 Ant 构建可执行归档文件:

[source,xml,indent=0,subs="verbatim"]
----
	<target name="build" depends="compile">
		<jar destfile="target/${ant.project.name}-${spring-boot.version}.jar" compress="false">
			<mappedresources>
				<fileset dir="target/classes" />
				<globmapper from="*" to="BOOT-INF/classes/*"/>
			</mappedresources>
			<mappedresources>
				<fileset dir="src/main/resources" erroronmissingdir="false"/>
				<globmapper from="*" to="BOOT-INF/classes/*"/>
			</mappedresources>
			<mappedresources>
				<fileset dir="${lib.dir}/runtime" />
				<globmapper from="*" to="BOOT-INF/lib/*"/>
			</mappedresources>
			<zipfileset src="${lib.dir}/loader/spring-boot-loader-jar-${spring-boot.version}.jar" />
			<manifest>
				<attribute name="Main-Class" value="org.springframework.boot.loader.JarLauncher" />
				<attribute name="Start-Class" value="${start-class}" />
			</manifest>
		</jar>
	</target>
----
