[[howto.hotswapping]]
== Hot Swapping(热交换)
Spring Boot 支持热插拔.  本部分回答有关其工作方式的问题.



[[howto.hotswapping.reload-static-content]]
=== 重新加载静态内容
有几种热加载选项.  推荐的方法是使用 <<using#using.devtools,`spring-boot-devtools`>>,因为它提供了其他开发时功能,例如对应用程序快速重启和LiveReload 的支持以及合理的开发时配置 (例如模板缓存) .
Devtools通过监视类路径的更改来工作.  这意味着必须 "构建" 静态资源更改才能使更改生效.  默认情况下,当您保存更改时,这在 Eclipse 中自动发生.  在 IntelliJ IDEA中,"生成项目" 命令将触发必要的构建.  由于<<using#using.devtools.restart.excluding-resources, 默认的重新启动排除项>>,
对静态资源的更改不会触发应用程序的重新启动.  但是,它们确实会触发实时重新加载.

另外,在 IDE 中运行 (特别是在调试时打开) 是进行开发的好方法 (所有现代 IDE 都允许重新加载静态资源,并且通常还允许热交换 Java 类更改) .

最后,可以配置 <<build-tool-plugins#build-tool-plugins, Maven 和 Gradle 插件>>  (请参见 `addResources` 属性) 以支持从命令行运行,并直接从源代码重新加载静态文件.  如果要使用高级工具编写该代码,则可以将其与外部 css/js 编译器进程一起使用.

[[howto.hotswapping.reload-templates]]
=== 重新加载模板,而无需重新启动容器
Spring Boot 支持的大多数模板技术都包含用于禁用缓存的配置选项 (在本文档的后面介绍) .  如果您使用 `spring-boot-devtools` 模块,那么在开发时会 <<using#using.devtools.property-defaults,自动配置>> 这些属性.

[[howto.hotswapping.reload-templates.thymeleaf]]
==== Thymeleaf 模板
If you use Thymeleaf, set `spring.thymeleaf.cache` to `false`.
See {spring-boot-autoconfigure-module-code}/thymeleaf/ThymeleafAutoConfiguration.java[`ThymeleafAutoConfiguration`] for other Thymeleaf customization options.



[[howto.hotswapping.reload-templates.freemarker]]
==== FreeMarker 模板
如果使用 FreeMarker,请将 `spring.freemarker.cache` 设置为 `false`.  有关其他 FreeMarker 定制选项,请参见  {spring-boot-autoconfigure-module-code}/freemarker/FreeMarkerAutoConfiguration.java[`FreeMarkerAutoConfiguration`].

[[howto.hotswapping.reload-templates.groovy]]
==== Groovy 模板
如果使用 Groovy 模板,请将 `spring.groovy.template.cache` 设置为 `false`.  有关其他 Groovy 定制选项,请参见  {spring-boot-autoconfigure-module-code}/groovy/template/GroovyTemplateAutoConfiguration.java[`GroovyTemplateAutoConfiguration`] .

[[howto.hotswapping.fast-application-restarts]]
=== 快速重启应用程序
`spring-boot-devtools` 模块包括对应用程序自动重启的支持.  尽管不如 https://www.jrebel.com/products/jrebel[JRebel]  这样的技术快,但通常比  "`cold start`" 要快得多.  在研究本文档后面讨论的一些更复杂的重载选项之前,您可能应该先尝试一下.

有关更多详细信息,请参见 <<using#using.devtools>> 部分.

[[howto.hotswapping.reload-java-classes-without-restarting]]
=== 重新加载 Java 类而无需重新启动容器
许多现代的 IDE (Eclipse,IDEA等) 都支持字节码的热交换.  因此,如果所做的更改不影响类或方法的签名,则应干净地重新加载而没有副作用.
