[[howto.logging]]
== Logging
除了通常由 Spring Framework 的 spring-jcl 模块提供的 Commons Logging API 之外,Spring Boot 没有强制性的日志记录依赖性.  要使用 https://logback.qos.ch[Logback],您需要在类路径中包括它和 `spring-jcl`.
最简单的方法是通过启动程序,所有启动程序都依赖于 `spring-boot-starter-logging`.  对于 Web 应用程序,只需要 `spring-boot-starter-web`,因为它暂时依赖于日志记录启动器.  如果使用 Maven,则以下依赖会为您添加日志记录:

[source,xml,indent=0,subs="verbatim"]
----
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-web</artifactId>
	</dependency>
----

Spring Boot 有一个 `LoggingSystem` 抽象,它试图根据类路径的内容来配置日志.  如果可以使用 Logback,则它是首选.

如果您需要对日志记录进行的唯一更改是设置各种记录器的级别,则可以使用 "logging.level" 前缀在 `application.properties` 中进行设置,如以下示例所示:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	logging:
	  level:
	    org.springframework.web: "debug"
	    org.hibernate: "error"
----

您还可以使用 `logging.file.name` 来设置要写入日志的文件的位置 (除了控制台) .

要配置日志记录系统的更细粒度的设置,您需要使用所讨论的 `LoggingSystem` 支持的本地配置格式.  默认情况下,Spring Boot 从系统的默认位置 (例如,用于 Logback 的 `classpath:logback.xml`) 拾取本地配置,但是您可以使用 `logging.config` 属性设置配置文件的位置.

[[howto.logging.logback]]
=== 配置 Logback Logging
如果您需要对 logback 进行自定义，假如超出了 `application.properties` 可以实现的范围，则需要添加一个标准的 logback 配置文件.  您可以将 `logback.xml` 文件添加到类路径的根目录中,以进行 logback 查找.
如果要使用 <<features#features.logging.logback-extensions,Spring Boot Logback 扩展>>,也可以使用 `logback-spring.xml`.

TIP: Logback 文档有一个特定的部分,其中 https://logback.qos.ch/manual/configuration.html[详细介绍了配置].

Spring Boot 提供了许多您自己的配置中  `included` 的 logback 配置.  这些包括旨在允许重新应用某些常见的 Spring Boot 约定.

`org/springframework/boot/logging/logback/` 下提供了以下文件:

* `defaults.xml` - 提供转换规则,模式属性和通用记录器配置.
* `console-appender.xml` - 使用 `CONSOLE_LOG_PATTERN` 添加一个 `ConsoleAppender`.
* `file-appender.xml` - 使用具有适当设置的 `FILE_LOG_PATTERN` 和 `ROLLING_FILE_NAME_PATTERN` 添加 `RollingFileAppender`.

另外,还提供了旧版 `base.xml` 文件,以与早期版本的 Spring Boot 兼容.

典型的自定义 `logback.xml` 文件如下所示:

[source,xml,indent=0,subs="verbatim"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<configuration>
		<include resource="org/springframework/boot/logging/logback/defaults.xml"/>
		<include resource="org/springframework/boot/logging/logback/console-appender.xml" />
		<root level="INFO">
			<appender-ref ref="CONSOLE" />
		</root>
		<logger name="org.springframework.web" level="DEBUG"/>
	</configuration>
----

您的日志配置文件也可以利用 `LoggingSystem` 为您创建的 System 属性:

* `$\{PID}`: The 当前进程 ID.
* `$\{LOG_FILE}`: 是否在 Boot 的外部配置中设置了 `logging.file.name`.
* `$\{LOG_PATH}`: 是否在 Boot 的外部配置中设置了 `logging.file.path` (代表要存放日志文件的目录) .
* `$\{LOG_EXCEPTION_CONVERSION_WORD}`: 是否在 Boot 的外部配置中设置了 `logging.exception-conversion-word`.
* `$\{ROLLING_FILE_NAME_PATTERN}`: 是否在 Boot 的外部配置中设置了 `logging.pattern.rolling-file-name`.

通过使用自定义的 Logback 转换器,Spring Boot 还可以在控制台上提供一些不错的 ANSI 颜色终端输出 (但不在日志文件中) .  有关示例,请参见 `defaults.xml` 配置中的 `CONSOLE_LOG_PATTERN`.

如果 Groovy 在类路径中,则还应该能够使用 `logback.groovy` 配置 Logback.  如果存在,则优先考虑此设置.

NOTE: Groovy 配置不支持 Spring 扩展.  不会检测到任何 `logback-spring.groovy` 文件.

[[howto.logging.logback.file-only-output]]
==== 配置仅文件输出的 Logback
如果要禁用控制台日志记录并将输出仅写入文件,则需要一个自定义的 `logback-spring.xml`,该文件将导入 `file-appender.xml` 而不是 `console-appender.xml`,如以下示例所示:

[source,xml,indent=0,subs="verbatim"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<configuration>
		<include resource="org/springframework/boot/logging/logback/defaults.xml" />
		<property name="LOG_FILE" value="${LOG_FILE:-${LOG_PATH:-${LOG_TEMP:-${java.io.tmpdir:-/tmp}}/}spring.log}"/>
		<include resource="org/springframework/boot/logging/logback/file-appender.xml" />
		<root level="INFO">
			<appender-ref ref="FILE" />
		</root>
	</configuration>
----

您还需要将 `logging.file.name` 添加到 `application.properties` 或 `application.yaml` 中,如以下示例所示:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	logging:
	  file:
	    name: "myapplication.log"
----

[[howto.logging.log4j]]
=== 配置 Log4j 日志
如果 Spring Boot 在类路径上,则它支持 https://logging.apache.org/log4j/2.x/[Log4j 2] 进行日志记录配置.  如果使用 starters 来组装依赖,则必须排除 Logback,然后改为包括 log4j 2.
如果您不使用 starters,则除了 Log4j 2 外,还需要 (至少) 提供 `spring-jcl`.

推荐的方法可能是通过 starters 程序,即使它需要对排除对象进行一些调整.  以下示例显示了如何在 Maven 中设置 starters:

[source,xml,indent=0,subs="verbatim"]
----
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-web</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter</artifactId>
		<exclusions>
			<exclusion>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-logging</artifactId>
			</exclusion>
		</exclusions>
	</dependency>
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-log4j2</artifactId>
	</dependency>
----

Gradle 提供了几种不同的方法来设置 starters。
一种方法是使用 {gradle-docs}/resolution_rules.html#sec:module_replacement[module replacement]。 为此，请声明对 Log4j 2 starter 的依赖，并告诉 Gradle 任何出现的默认日志记录 starter 都应替换为 Log4j 2 starter，如以下示例所示:

[source,gradle,indent=0,subs="verbatim"]
----
	dependencies {
		implementation "org.springframework.boot:spring-boot-starter-log4j2"
		modules {
			module("org.springframework.boot:spring-boot-starter-logging") {
				replacedBy("org.springframework.boot:spring-boot-starter-log4j2", "Use Log4j2 instead of Logback")
			}
		}
	}
----


NOTE: Log4j 入门人员将依赖集中在一起,以满足常见的日志记录要求 (例如让 Tomcat 使用 `java.util.logging`,但使用 Log4j 2 配置输出) .

NOTE: 为了确保将使用 `java.util.logging` 执行的调试日志记录路由到 Log4j 2,请通过将 `java.util.logging.manager` 系统属性设置为 `org.apache.logging.log4j.jul.LogManager` 来配置其 https://logging.apache.org/log4j/2.x/log4j-jul/index.html[JDK logging adapter].

[[howto.logging.log4j.yaml-or-json-config]]
==== 使用 YAML 或 JSON 配置 Log4j 2
除了默认的 XML 配置格式外,Log4j 2 还支持 YAML 和 JSON 配置文件.  要将 Log4j 2 配置为使用备用配置文件格式,请将适当的依赖添加到类路径中,并命名您的配置文件以匹配您选择的文件格式,如以下示例所示:

[cols="10,75a,15a"]
|===
| Format | Dependencies | File names

|YAML
| `com.fasterxml.jackson.core:jackson-databind` + `com.fasterxml.jackson.dataformat:jackson-dataformat-yaml`
| `log4j2.yaml` + `log4j2.yml`

|JSON
| `com.fasterxml.jackson.core:jackson-databind`
| `log4j2.json` + `log4j2.jsn`
|===



[[howto.logging.log4j.composite-configuration]]
==== 使用复合配置来配置 Log4j 2
Log4j 2 支持将多个配置文件组合成一个复合配置。
要在 Spring Boot 中使用此支持，请配置一个或多个辅助配置文件的位置 `logging.log4j2.config.override`。
辅助配置文件将与主配置合并，无论主配置的源是 Spring Boot 的默认值、标准位置（例如 `log4j.xml`）还是 `logging.config` 属性配置的位置。
