[[howto.properties-and-configuration]]
== 属性和配置
本部分包括有关设置和读取属性,配置设置以及它们与 Spring Boot 应用程序的交互的主题.

[[howto.properties-and-configuration.expand-properties]]
=== 在构建时自动扩展属性
您可以使用现有的构建配置自动扩展它们,而不是对项目的构建配置中也指定的某些属性进行硬编码. 在 Maven 和 Gradle 中都是可能的.

[[howto.properties-and-configuration.expand-properties.maven]]
==== 使用 Maven 自动扩展属性
您可以使用资源过滤从 Maven 项目自动扩展属性. 如果使用 `spring-boot-starter-parent`,则可以使用 `@..@` 占位符引用 Maven 的  '`project properties`',如以下示例所示:

[source,yaml,indent=0,subs="verbatim",configblocks]
----
	app:
	  encoding: "@project.build.sourceEncoding@"
	  java:
	    version: "@java.version@"
----

NOTE: 这样只会过滤生产配置 (也就是说,不会对进行过滤 `src/test/resources`) .

TIP: 如果启用该 `addResources` 标志,则 `spring-boot:run` 目标可以 `src/main/resources` 直接添加到类路径中 (用于热重载) . 这样做避免了资源过滤和此功能. 相反,您可以使用 `exec:java` 目标或自定义插件的配置. 有关更多详细信息,请参见 {spring-boot-maven-plugin-docs}#getting-started[插件使用页面] .

如果您不使用入门级父级,则需要在 `<build/>` 元素中包括以下元素 `pom.xml`:

[source,xml,indent=0,subs="verbatim"]
----
	<resources>
		<resource>
			<directory>src/main/resources</directory>
			<filtering>true</filtering>
		</resource>
	</resources>
----

您还需要在其中包含以下元素 `<plugins/>`:

[source,xml,indent=0,subs="verbatim"]
----
	<plugin>
		<groupId>org.apache.maven.plugins</groupId>
		<artifactId>maven-resources-plugin</artifactId>
		<version>2.7</version>
		<configuration>
			<delimiters>
				<delimiter>@</delimiter>
			</delimiters>
			<useDefaultDelimiters>false</useDefaultDelimiters>
		</configuration>
	</plugin>
----

NOTE: `useDefaultDelimiters` 如果在配置中使用标准的 Spring 占位符 (例如 `$\{placeholder}`) ,则 该属性很重要. 如果该属性未设置为 `false`,则可以通过构建扩展它们.

[[howto.properties-and-configuration.expand-properties.gradle]]
==== 使用 Gradle 自动扩展属性
您可以通过配置 Java 插件的 `processResources` 任务来自动扩展 Gradle 项目中的属性,如以下示例所示:

[source,gradle,indent=0,subs="verbatim"]
----
	tasks.named('processResources') {
		expand(project.properties)
	}
----

然后,您可以使用占位符来引用 Gradle 项目的属性,如以下示例所示:

[source,yaml,indent=0,subs="verbatim",configblocks]
----
	app:
	  name: "${name}"
	  description: "${description}"
----

NOTE: Gradle 的 `expand` 方法使用 Groovy 的方法 `SimpleTemplateEngine` 来转换 `${..}` 令牌. 该 `${..}` 风格 与 Spring 自己的属性占位符机制冲突. 要将 Spring 属性占位符与自动扩展一起使用,请按以下步骤对 Spring 属性占位符进行转义: `\${..}`.

[[howto.properties-and-configuration.externalize-configuration]]
=== 外部化配置 SpringApplication
`SpringApplication` 具有 bean 属性 (主要是 setter) ,因此在创建应用程序时可以使用其 Java API 修改其行为. 或者,您可以通过在中设置属性来外部化配置 `+spring.main.*+`. 例如,在中 `application.properties`,您可能具有以下设置:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  main:
	    web-application-type: "none"
	    banner-mode: "off"
----

然后,启动时不会打印 Spring Boot 标语,并且应用程序也没有启动嵌入式 Web 服务器.

外部配置中定义的属性会覆盖用 Java API 指定的值,但用于创建 `SpringApplication` 的数据源除外. 考虑以下应用程序:

include::code:application/MyApplication[]

或者到 `SpringApplicationBuilder` 的 `sources(...)` 方法：

include::code:builder/MyApplication[]

给定上面的例子，如果我们有以下配置:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  main:
	    sources: "com.example.MyDatabaseConfig,com.example.MyJmsConfig"
	    banner-mode: "console"
----

实际应用中,现在示出的 banner (如通过配置覆盖) ,并为 `ApplicationContext` 使用三个源(按以下顺序) :

. `MyApplication` (from the code)
. `MyDatabaseConfig` (from the external config)
. `MyJmsConfig`(from the external config)

[[howto.properties-and-configuration.external-properties-location]]
=== 更改应用程序外部属性的位置
默认情况下,来自不同来源的属性将以定义的顺序添加到  Spring 的 `Environment` 中 (有关确切顺序,请参见  '`Spring Boot 特性`'  部分中的 "`<<features#features.external-config>>`") .

您还可以提供以下系统属性 (或环境变量) 来更改行为:

* `spring.config.name` (`spring.config.name[format=envvar]`): 默认为 `application` 作为文件名的根.
* `spring.config.location` (`spring.config.location[format=envvar]`): 要加载的文件 (例如类路径资源或 URL) . `Environment` 为此文档设置了单独的属性源,可以通过系统属性,环境变量或命令行来覆盖它.

无论您在环境中进行什么设置,Spring Boot 都将始终 `application.properties` 如上所述进行加载. 默认情况下,如果使用 YAML,则扩展名为 `'.yml'` 的文件也将添加到列表中.

提示：如果您想要有关正在加载的文件的详细信息，您可以 <<features#features.logging.log-levels,将 `org.springframework.boot.context.config` 的日志级别>>设置为 `trace` .

[[howto.properties-and-configuration.short-command-line-arguments]]
=== 使用 '`Short`' 命令行参数
有些人喜欢使用 (例如) `--port=9000` 而不是 `--server.port=9000` 在命令行上设置配置属性. 您可以通过使用占位符来启用此行为 `application.properties` ,如以下示例所示:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	server:
	  port: "${port:8080}"
----

TIP: 如果您从 `spring-boot-starter-parent` POM 继承,则将的默认过滤器令牌 `maven-resources-plugins` 从更改 `+${*}+` 为 `@`  (即,`@maven.token@` 而不是 `${maven.token}`) ,
以防止与 Spring 样式的占位符冲突. 如果 `application.properties` 直接启用了 Maven 过滤,则可能还需要更改默认过滤器令牌以使用 https://maven.apache.org/plugins/maven-resources-plugin/resources-mojo.html#delimiters[其他定界符].

NOTE: 在这种特定情况下,端口绑定可在 PaaS 环境 (例如 Heroku 或 Cloud Foundry) 中工作. 在这两个平台中,`PORT` 环境变量是自动设置的,Spring 可以绑定到大写的 `Environment` 属性同义词.

[[howto.properties-and-configuration.yaml]]
=== 对外部属性使用 YAML
YAML 是 JSON 的超集,因此是一种方便的语法,用于以分层格式存储外部属性,如以下示例所示:

[source,yaml,indent=0,subs="verbatim"]
----
	spring:
	  application:
	    name: "cruncher"
	  datasource:
	    driver-class-name: "com.mysql.jdbc.Driver"
	    url: "jdbc:mysql://localhost/test"
	server:
	  port: 9000
----

创建一个名为 `application.yml` 的文件 ,并将其放在类路径的根目录中. 然后添加 `snakeyaml` 到您的依赖 (Maven 坐标 `org.yaml:snakeyaml`,如果使用,则已经包含在内 `spring-boot-starter`) .
将 YAML 文件解析为 Java `Map<String,Object>` (如 JSON 对象) ,然后 Spring Boot 将 Map 压平,使其只具有一层,并使用句号作为分隔键,这是许多人习惯使用 Java 中的 `Properties` 文件的原因.

前面的示例 YAML 对应于以下 `application.properties` 文件:

[source,properties,indent=0,subs="verbatim",configprops]
----
	spring.application.name=cruncher
	spring.datasource.driver-class-name=com.mysql.jdbc.Driver
	spring.datasource.url=jdbc:mysql://localhost/test
	server.port=9000
----

有关 YAML  的更多信息,请参见 "`Spring Boot 特性`" 部分中的 "`<<features#features.external-config.yaml>>`".

[[howto.properties-and-configuration.set-active-spring-profiles]]
=== 设置 Active Spring Profiles
Spring `Environment` 为此提供了一个 API,但是您通常会设置一个 `System` 属性 (`spring.profiles.active`) 或 OS 环境变量 (`SPRING_PROFILES_ACTIVE`) . 另外,您可以使用 `-D` 参数启动应用程序 (请记住将其放在主类或 jar 存档之前) ,如下所示:

[source,shell,indent=0,subs="verbatim"]
----
	$ java -jar -Dspring.profiles.active=production demo-0.0.1-SNAPSHOT.jar
----

在 Spring Boot 中,您还可以设置激活的配置文件 `application.properties`,如以下示例所示:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  profiles:
	    active: "production"
----

以这种方式设置的值将由系统属性或环境变量代替,而不由 `SpringApplicationBuilder.profiles()` 方法替代. 因此,后一种 Java API 可用于扩充配置文件,而无需更改默认值.

有关更多信息,请参见 "`Spring Boot 特性`" 部分中的 "`<<features#features.profiles>>`"

[[howto.properties-and-configuration.set-default-spring-profile-name]]
=== 设置默认的 Profile Name
default 配置文件是在没有配置文件处于活动状态时启用的配置文件。
默认情况下，默认配置文件的名称是 `default`，但可以使用系统属性 (`spring.profiles.default`) 或操作系统环境变量 (`spring.profiles.default[format=envvar]`）。

在 Spring Boot 中，您还可以在 `application.properties` 中设置默认配置文件名称，如下例所示：

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  profiles:
	    default: "dev"
----

有关更多信息，请参阅 "`Spring Boot features`" 部分中的 ”部分中的“`<<features#features.profiles>>`”。
See 。

[[howto.properties-and-configuration.change-configuration-depending-on-the-environment]]
=== 根据环境更改配置
Spring Boot 支持多文档 YAML 和 Properties 文件(详细信息请参见 <<features#features.external-config.files.multi-document>>)， 可以根据激活的配置文件选择性的使用它们.

如果 YAML 文档包含  `spring.config.activate.on-profile` 配置,则将配置文件值 (以逗号分隔的配置文件列表或配置文件表达式) 输入到 Spring `Environment.acceptsProfiles()` 方法中.
如果配置文件表达式匹配， 则该文档将被包含在最终的合并中(否则， 则不包含) ,如以下示例所示:

[source,yaml,indent=0,subs="verbatim,attributes",configprops,configblocks]
----
	server:
	  port: 9000
	---
	spring:
	  config:
	    activate:
	      on-profile: "development"
	server:
	  port: 9001
	---
	spring:
	  config:
	    activate:
	      on-profile: "production"
	server:
	  port: 0
----

在前面的示例中,默认端口为 9000. 但是,如果名为 '`development`' 的 Spring profile 处于 active 状态,则端口为 9001. 如果 '`production`'  为 active 状态,则该端口为 0.

NOTE: 文档按照它们遇到的顺序进行合并. 以后的值将覆盖以前的值.

[[howto.properties-and-configuration.discover-build-in-options-for-external-properties]]
=== 发现外部属性的内置选项
Spring Boot 在运行时将 `application.properties` (或 `.yml` 文件和其他位置) 的外部属性绑定到应用程序中.  在一个位置上没有 (而且从技术上来说不是) 所有受支持属性的详尽列表， 因为他有可能来自类路径上的其他 jar 文件.

具有 Actuator 功能的正在运行的应用程序具有一个 `configprops` 端点,该端点显示了可通过访问的所有绑定和可绑定属性 `@ConfigurationProperties` .

附录中包含一个 <<application-properties#appendix.application-properties, `application.properties`>>  示例,其中列出了 Spring Boot 支持的最常见属性.
最终列表来自搜索源代码中的 `@ConfigurationProperties` 和 `@Value` 注解,以及偶尔使用 `Binder`. 有关加载属性的确切顺序的更多信息,请参见 ""<<features#features.external-config>>".
