[[howto.testing]]
== 测试
Spring Boot 包括许多测试实用程序和支持类，以及提供常见测试依赖项的 starter。
本节回答有关测试的常见问题。

[[howto.testing.with-spring-security]]
=== 使用 Spring Security 进行测试
Spring Security 提供了对以特定用户身份运行测试的支持.  例如,下面的代码段中的测试将与具有 `ADMIN` 角色的经过身份验证的用户一起运行.

include::code:MySecurityTests[]

Spring Security 提供了与 Spring MVC Test 的全面集成,并且在使用 `@WebMvcTest` slice 和 `MockMvc` 测试控制器时也可以使用它.

有关 Spring Security 的测试支持的更多详细信息,请参阅 Spring Security 的 {spring-security-docs}/servlet/test/index.html[参考文档].

[[howto.testing.testcontainers]]
===  在集成测试中使用 Testcontainers
https://www.testcontainers.org/[Testcontainers] 库提供了一种方法来管理在 Docker 容器中运行的服务. 它与 JUnit 集成,允许您编写一个测试类,该类可以在运行任何测试之前启动容器. Testcontainers 在编写与真实的后端服务 (例如 MySQL,MongoDB,Cassandra 等) 进行通信的集成测试时特别有用.Testcontainers 可以在 Spring Boot 测试中使用,如下所示:

include::code:vanilla/MyIntegrationTests[]

在运行任何测试之前,这将启动运行 Neo4j 的 Docker 容器 (如果 Docker 在本地运行) . 在大多数情况下,您将需要使用正在运行的容器中的详细信息 (例如容器 IP 或端口) 来配置应用程序.

这可以通过静态 `@DynamicPropertySource` 方法完成,该方法允许向 Spring Environment 添加动态属性值.

include::code:dynamicproperties/MyIntegrationTests[]

上面的配置允许应用程序中与 Neo4j 相关的 Bean 与在 Testcontainers 管理的 Docker 容器中运行的 Neo4j 通信.

[[howto.testing.slice-tests]]
=== Structure `@Configuration` classes for inclusion in slice tests
切片测试通过将 Spring Framework 的组件扫描限制为基于其类型的一组有限组件来工作。
对于不是通过组件扫描创建的任何 bean，例如，使用 `@Bean` 注解创建的 bean，切片测试将无法从应用程序上下文中包含/排除它们。
考虑这个例子：

include::code:MyConfiguration[]

对于具有上述 `@Configuration` 类的应用程序的 `@WebMvcTest`，您可能希望在应用程序上下文中有 `SecurityFilterChain` bean，以便您可以测试您的控制器端点是否得到正确保护。
但是，@WebMvcTest 的组件扫描过滤器不会选择 `MyConfiguration`，因为它与过滤器指定的任何类型都不匹配。
您可以通过使用 `@Import(MyConfiguration.class)` 注解测试类来显式包含配置。
这将加载 `MyConfiguration` 中的所有 bean，包括测试 Web 层时不需要的 `BasicDataSource` bean。
将配置类拆分为两个将启用仅导入安全配置。

include::code:MySecurityConfiguration[]

include::code:MyDatasourceConfiguration[]

当某个 domain 的 bean 需要包含在切片测试中时，拥有单个配置类可能效率低下。
相反，将应用程序的配置构建为具有特定 domain 的 bean 的多个粒度类可以启用仅针对特定切片测试导入它们。

