= Spring Cloud Stream Reference Documentation
Sabby Anandan; Marius Bogoevici; Eric Bottard; Mark Fisher; Ilayaperumal Gopinathan; Mark Heckler; Gunnar Hillert; Mark Pollack; Patrick Peralta; Glenn Renfro; Thomas Risberg; Dave Syer; David Turanski; Janne Valkealahti; Benjamin Klein; Vinicius Carvalho; Gary Russell; Oleg Zhurakousky; Jay Bryant; Soby Chacko; Domenico Sibilio

*{project-version}*

:docinfo: shared

参看文档包含一下章节:

[horizontal]
<<spring-cloud-stream.adoc#spring-cloud-stream-reference,Overview>> :: 历史, 快速入门, 概念, 架构概述, Binder 抽象, 核心特性

<<spring-cloud-stream-binder-rabbit#spring-cloud-stream-binder-rabbit-reference,Rabbit MQ Binder>> :: Rabbit MQ 的 Spring Cloud Stream binder 文档
<<spring-cloud-stream-binder-kafka#_apache_kafka_binder,Apache Kafka Binder>> :: Apache Kafka 的 Spring Cloud Stream binder 文档
<<spring-cloud-stream-binder-kafka#_kafka_streams_binder,Apache Kafka Streams binder>> :: Apache Kafka Streams 的 Spring Cloud Stream binder 参考

<<binders.adoc#binders,Additional Binders>> :: 合作伙伴实现的 Spring Cloud Stream binder (例如., Azure Event Hubs, Google PubSub, Solace PubSub+)
<<spring-cloud-stream-schema-registry.adoc#spring-cloud-stream-schema-registry-reference,Schema Registry>> :: Spring Cloud Stream Schema 注册表参考
https://github.com/spring-cloud/spring-cloud-stream-samples/[Spring Cloud Stream Samples]  :: 示例

相关链接:

[horizontal]
https://cloud.spring.io/spring-cloud-dataflow/[Spring Cloud Data Flow] :: Spring Cloud Data Flow
http://www.enterpriseintegrationpatterns.com/[Enterprise Integration Patterns]  :: 企业集成的模式和最佳实践
https://spring.io/projects/spring-integration[Spring Integration]  :: Spring Integration framework

