[[using.build-systems]]
== 构建系统
强烈推荐您选择一个支持 <<using#using.build-systems.dependency-management,_依赖管理_>> 的构建系统, 您可以使用它将 artifact 发布到 Maven Central 仓库. 我们建议您选择 Maven 或者 Gradle. Spring Boot 虽然也可以使用其它构建系统 (如 Ant) 配合工作,但它们不会得到特别好的支持.

[[using.build-systems.dependency-management]]
=== 依赖管理
每一次 Spring Boot 发行版都提供了一个它所支持的依赖清单. 实际上,您不需要为构建配置提供任何依赖的版本,因为 Spring Boot 已经帮您管理这些了. 当您升级 Spring Boot 时,这些依赖也将以一致的方式进行升级.

NOTE: 如果您觉得有必要,您仍然可以指定一个版本并覆盖 Spring Boot 所推荐的.

该清单包含了全部可以与 Spring Boot 一起使用的 spring 模块以及第三方类库,可作为 标准依赖清单 (`spring-boot-dependencies`) ,并且可以与 <<using#using.build-systems.maven,Maven>> 和 <<using#using.build-systems.gradle,Gradle>> 一起使用.

WARNING: Spring Boot 的每一次发行都会基于一个 Spring Framework 版本,因此我们强烈建议您不要指定它的版本.

[[using.build-systems.maven]]
要了解有关将 Spring Boot 与 Maven 结合使用的信息,请参阅 Spring Boot 的 Maven 插件的文档

* 参考文档 ({spring-boot-maven-plugin-docs}[HTML] 和 {spring-boot-maven-plugin-pdfdocs}[PDF])
* {spring-boot-maven-plugin-api}[API]

[[using.build-systems.gradle]]
=== Gradle
要了解如何使用 Spring Boot 和 Gradle,请参阅 Spring Boot 的 Gradle 插件文档:

* 参考文档 ({spring-boot-gradle-plugin-docs}[HTML] 和 {spring-boot-gradle-plugin-pdfdocs}[PDF])
* {spring-boot-gradle-plugin-api}[API]

[[using.build-systems.ant]]
===  Ant
可以使用 Apache Ant+Ivy 构建 Spring Boot 项目. `spring-boot-antlib`  "`AntLib`" 模块也可以帮助 Ant 创建可执行 jar 文件.

要声明依赖,可参考以下一个典型的 `ivy.xml` 文件内容:

[source,xml,indent=0,subs="verbatim"]
----
	<ivy-module version="2.0">
		<info organisation="org.springframework.boot" module="spring-boot-sample-ant" />
		<configurations>
			<conf name="compile" description="everything needed to compile this module" />
			<conf name="runtime" extends="compile" description="everything needed to run this module" />
		</configurations>
		<dependencies>
			<dependency org="org.springframework.boot" name="spring-boot-starter"
				rev="${spring-boot.version}" conf="compile" />
		</dependencies>
	</ivy-module>
----

一个典型的 `build.xml` 大概是这样:

[source,xml,indent=0,subs="verbatim,attributes"]
----
	<project
		xmlns:ivy="antlib:org.apache.ivy.ant"
		xmlns:spring-boot="antlib:org.springframework.boot.ant"
		name="myapp" default="build">

		<property name="spring-boot.version" value="{spring-boot-version}" />

		<target name="resolve" description="--> retrieve dependencies with ivy">
			<ivy:retrieve pattern="lib/[conf]/[artifact]-[type]-[revision].[ext]" />
		</target>

		<target name="classpaths" depends="resolve">
			<path id="compile.classpath">
				<fileset dir="lib/compile" includes="*.jar" />
			</path>
		</target>

		<target name="init" depends="classpaths">
			<mkdir dir="build/classes" />
		</target>

		<target name="compile" depends="init" description="compile">
			<javac srcdir="src/main/java" destdir="build/classes" classpathref="compile.classpath" />
		</target>

		<target name="build" depends="compile">
			<spring-boot:exejar destfile="build/myapp.jar" classes="build/classes">
				<spring-boot:lib>
					<fileset dir="lib/runtime" />
				</spring-boot:lib>
			</spring-boot:exejar>
		</target>
	</project>
----

TIP: 如果您不想使用 `spring-boot-antlib` 模块,请参阅 _<<howto#howto.build.build-an-executable-archive-with-ant-without-using-spring-boot-antlib>>_ "`How-to`".

[[using.build-systems.starters]]
=== Starters
Starter 是一组惯例依赖描述资源, 可以包含在应用程序中. 从 starter 中,您可以获得所需的所有 Spring 和相关技术的一站式支持,无须通过示例代码和复制粘贴来获取依赖. 比如,如果您要使用 Spring 和 JPA 进行数据库访问,那么只需要在项目中包含 `spring-boot-starter-data-jpa` 依赖即可.

starter 包含了许多依赖可以使您的项目快速启动和运行,并且支持的依赖的可传递性.

.命名含义
****
**官方** 的所有 starter 都遵循类似的命名规则: `+spring-boot-starter-*+` ,其中  `+*+` 是特定类型的应用. 这个命名结构可以帮助您找到您需要的 starter. 许多 IDE 中 Maven 集成允许您按名称搜索依赖. 例如,安装了 Eclipse 或者 STS 插件后,您可以简单地在 POM 编辑器中按下 `ctrl-space` 并输入 `spring-boot-starter` 来获取完整的列表.

正如 "`<<features#features.developing-auto-configuration.custom-starter,创建自己的 starter>>`" 章节所述,第三方的 starter 命名不应该以 `spring-boot` 开头, 因为它是官方 Spring Boot artifacts 所保留的规则. 例如,有一个第三方 starter 项目叫做 `thirdpartyproject`,它通常会命名为 `thirdpartyproject-spring-boot-starter`.
****

Spring Boot 在 `org.springframework.boot` 组下提供了以下 starter:

.Spring Boot 应用类 starters
include::starters/application-starters.adoc[]

除了应用程序的 starter 外,以下 starter 可用于添加 _<<actuator#actuator, 生产就绪>>_ 特性:

.Spring Boot 生产类 starters
include::starters/production-starters.adoc[]

最后,Spring Boot 还包含以下 starter,如果您想要排除或切换其他特定技术,可以使用以下 starter:

.Spring Boot 技术类 starters
include::starters/technical-starters.adoc[]

要了解如何交换技术方面的信息,请参阅 <<howto#howto.webserver.use-another, swapping web server>> 和 <<howto#howto.logging.log4j, logging system>>.

TIP: 有关其它社区贡献的 starter 列表,请参阅 GitHub 上的 `spring-boot-starters` 模块中的 {spring-boot-master-code}/spring-boot-project/spring-boot-starters/README.adoc[README file] 文件.
