[[using.using-the-springbootapplication-annotation]]
== 使用 @SpringBootApplication 注解
很多 Spring Boot 开发者总是希望他们的应用程序使用自动配置、组件扫描并能够在他们的 "application class" 上定义额外的配置.
可以使用单个 `@SpringBootApplication` 注解来启用这三个功能，即：

* `@EnableAutoConfiguration`: <<using#using.auto-configuration,启用 Spring Boot 的自动配置机制>>
* `@ComponentScan`: 在应用程序所在的包上启用 `@Component` 扫描 (<<using#using.structuring-your-code,请参阅最佳实践>>)
* `@Configuration`: 允许在上下文中注册额外的 bean 或导入其他配置类

* `@EnableAutoConfiguration`: enable <<using#using.auto-configuration,Spring Boot's auto-configuration mechanism>>
* `@ComponentScan`: enable `@Component` scan on the package where the application is located (see <<using#using.structuring-your-code,the best practices>>)
* `@SpringBootConfiguration`: enable registration of extra beans in the context or the import of additional configuration classes.
Spring 标准 `@Configuration` 的替代方案，可在您的集成测试中帮助 <<features#features.testing.spring-boot-applications.detecting-configuration,configuration detection>>。

include::code:springapplication/MyApplication[]

NOTE: `@SpringBootApplication` 还提供别名以自定义 `@EnableAutoConfiguration` 和 `@ComponentScan` 的属性.

[NOTE]
====
这些功能都不是强制性的,您可以选择单个注解来启用他特定的特性. 例如,您可能不想在应用程序中使用组件扫描或配置属性扫描：

include::code:individualannotations/MyApplication[]

在此示例中,除了程序没有自动检测到 `@Component` 注解的类和 `@ConfigurationProperties` 注解的类和显式导入了用户定义的 Bean 之外, `MyApplication` 就像其他任何 Spring Boot 应用程序一样 (请参阅 `@Import`) .
====
