= ZADD

**语法**

[source,text]
----
ZADD key [NX | XX] [GT | LT] [CH] [INCR] score member [score member
  ...]
----

**可用版本**：1.2.0

**时间复杂度**：O(log(N))，其中N是已有序集合中的元素数。

**ACL 类别**：**@write, @sortedset, @fast**

将指定分数的所有指定成员添加到存储在 key 处的有序集中。 可以指定多个 score/member 对。 如果指定的成员已经是有序集的成员，则更新分数并将元素重新插入到正确的位置以确保正确的排序。

如果 key 不存在，则会创建一个新的有序集，其中指定的成员作为唯一成员，就像有序集为空一样。 如果键存在但不包含有序集，则返回错误。

分数值应该是双精度浮点数的字符串表示形式。 `+inf` 和 `-inf` 值也是有效值。


== ZADD 选项

ZADD 支持选项列表，在 key 名称之后和第一个 score 参数之前指定。 选项有：

* XX：只更新已经存在的元素。 不添加新元素。
* NX：仅添加新元素。 不更新已经存在的元素。
* LT：如果新分数小于当前分数，则仅更新现有元素。 该标志不会阻止添加新元素。
* GT：仅当新分数大于当前分数时才更新现有元素。 该标志不会阻止添加新元素。
* CH：返回变更成员的数量。变更的成员是指 新增成员 和 score值更新的成员，命令指明的和之前score值相同的成员不计在内。注意：通常ZADD的返回值只统计添加的新元素的数量。
* INCR：指定此选项时，ZADD 的作用类似于 ZINCRBY。 在此模式下只能指定一对 score-element 对。

注意：GT、LT 和 NX 选项是互斥的。

== scores 有效值范围

Redis 有序集使用双 64 位浮点数来表示分数。 在我们支持的所有架构中，这都表示为 IEEE 754 浮点数，能够精确表示 -(2^53) 和 +(2^53) 之间的整数。 更实际地说，-9007199254740992 和 9007199254740992 之间的所有整数都可以完美表示。
较大的整数或分数在内部以指数形式表示，因此您可能只能得到设置为分数的十进制数或非常大的整数的近似值。

== 有序集 101

有序集按其分数升序排序。 相同的元素只存在一次，不允许有重复的元素。 分数可以通过 ZADD 和 ZINCRBY 来修改，ZADD 会更新元素分数，作为副作用，它在有序集上的位置也可以通过 ZINCRBY 来修改，ZINCRBY 可用于相对于其先前值更新分数。

可以使用 ZSCORE 命令检索元素的当前分数，该命令也可用于验证元素是否已存在。

有关有序集的介绍，请参阅 https://redis.io/topics/data-types#sorted-sets[有序集的数据类型] 页面。

== 具有相同分数的元素

虽然相同的元素不能在有序集中重复，因为每个元素都是唯一的，但可以添加具有相同分数的多个不同元素。 当多个元素具有相同的分数时，它们按字典顺序排序（仍由分数作为第一排序条件，然后，相同分数的成员按照字典序排序）。

字典顺序排序用的是二进制，它比较的是字符串的字节数组。

如果用户将所有元素设置相同分数（例如 0），有序集合里面的所有元素将按照字典顺序进行排序，范围查询元素可以使用 ZRANGEBYLEX 命令（注：范围查询分数可以使用 ZRANGEBYSCORE 命令）。

== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-integers[整数]：

* 当不带可选参数使用时，添加到有序集中的元素数量（不包括分数更新）。
* 如果指定了 CH 选项，则为已更改（添加或更新）的元素数。

如果指定了 INCR 选项，则返回值为 https://redis.io/docs/reference/protocol-spec/#resp-bulk-strings[批量字符串]：

* 成员的新分数（双精度浮点数）表示为字符串，如果操作被中止（当使用 XX 或 NX 选项调用时），则为零。

== 示例

[source,text]
----
redis> ZADD myzset 1 "one"
(integer) 1
redis> ZADD myzset 1 "uno"
(integer) 1
redis> ZADD myzset 2 "two" 3 "three"
(integer) 2
redis> ZRANGE myzset 0 -1 WITHSCORES
1) "one"
2) "1"
3) "uno"
4) "1"
5) "two"
6) "2"
----

== 历史

* 从 Redis 版本 2.4.0 开始：接受多个元素。
* 从 Redis 版本 3.0.2 开始：添加了 XX、NX、CH 和 INCR 选项。
* 从 Redis 6.2.0 版本开始：添加了 GT 和 LT 选项。