= OAuth 2.0 Resource Server JWT

[[webflux-oauth2resourceserver-jwt-minimaldependencies]]
== JWT 的最小依赖

大多数资源服务器支持都收集在 `spring-security-oauth2-resource-server` 中.
但是,`spring-security-oauth2-jose` 中支持对JWT进行解码和验证,这意味着,对于拥有支持 JWT 编码的 Bearer Token 的工作资源服务器而言,两者都是必需的.

[[webflux-oauth2resourceserver-jwt-minimalconfiguration]]
== JWT 的最小配置

使用 https://spring.io/projects/spring-boot[Spring Boot] 时,将应用程序配置为资源服务器包括两个基本步骤.  首先,包括所需的依赖,其次,指示授权服务器的位置.

=== 指定授权服务器

在 Spring Boot 应用程序中,要指定要使用的授权服务器,只需执行以下操作:

====
[source,yml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com/issuer
----
====

其中 `https://idp.example.com/issuer` 是授权服务器将颁发的JWT令牌的 `iss` 声明中包含的值.  资源服务器将使用此属性进行进一步的自我配置,发现授权服务器的公钥,然后验证传入的JWT.


[NOTE]
====
要使用 `issuer-uri` 属性,还必须确保 `https://idp.example.com/issuer/.well-known/openid-configuration`, `https://idp.example.com/.well-known/openid-configuration/issuer`, 或  `https://idp.example.com/.well-known/oauth-authorization-server/issuer` 是授权服务器支持的端点.
此端点称为 https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Provider Configuration]  端点或授权服务器 https://tools.ietf.org/html/rfc8414#section-3[Authorization Server Metadata] 端点.
====

=== 启动预期

使用此属性和这些依赖时,资源服务器将自动配置自身以验证 JWT 编码的 Bearer 令牌.

它通过确定性的启动过程来实现:

1. 点击提供者配置或授权服务器元数据端点,处理 `jwks_url` 属性的响应
2. 配置验证策略以查询 `jwks_url` 以获取有效的公共密钥
3. 配置验证策略,以根据 `https://idp.example.com` 验证每个JWT的 `iss` 声明.

此过程的结果是,授权服务器必须启动并接收请求,才能成功启动资源服务器.

[NOTE]
====
如果在资源服务器查询授权服务器时授权服务器已关闭 (给出适当的超时) ,则启动将失败.
====

=== 运行时预期

应用程序启动后,资源服务器将尝试处理任何包含 `Authorization: Bearer`  头的请求:

====
[source,html]
----
GET / HTTP/1.1
Authorization: Bearer some-token-value # Resource Server will process this
----
====

只要指示了此方案,资源服务器就会尝试根据 Bearer Token 规范处理请求.

给定格式正确的JWT,资源服务器将:

. 在启动期间根据从 `jwks_url` 端点获取并与 JWTs 请求头匹配的公钥验证其签名
. 验证 JWT 的 `exp` 和 `nbf` 时间戳以及 JWT 的 `iss` 声明,以及
. 将每个范围映射到具有前缀 `SCOPE_` 的权限.

[NOTE]
====
当授权服务器提供新的密钥时,Spring Security 将自动旋转用于验证 JWT 令牌的密钥.
====

默认情况下,生成的  `Authentication#getPrincipal` 是 Spring Security `Jwt` 对象,并且  `Authentication#getName` 映射到 JWT 的 `sub` 属性 (如果存在) .

从这里,考虑跳到:

* <<webflux-oauth2resourceserver-jwt-jwkseturi,如何在不使资源服务器启动受限于授权服务器的可用性的情况下进行配置>>
* <<webflux-oauth2resourceserver-jwt-sansboot,如何在没有 Spring Boot 的情况下进行配置>>

[[webflux-oauth2resourceserver-jwt-jwkseturi]]
=== 直接指定授权服务器JWK设置Uri

如果授权服务器不支持任何配置端点,或者如果资源服务器必须能够独立于授权服务器启动,那么还可以提供 `jwk-set-uri`:

====
[source,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com
          jwk-set-uri: https://idp.example.com/.well-known/jwks.json
----
====

[NOTE]
====
JWK Set uri 尚未标准化,但通常可以在授权服务器的文档中找到
====

因此,资源服务器在启动时不会对授权服务器执行 ping 操作.  我们仍然指定 `issuer-uri`,以便 Resource Server 仍然验证传入 JWT 上的 `iss` 声明.

[NOTE]
====
此属性也可以直接在<<webflux-oauth2resourceserver-jwt-jwkseturi-dsl,DSL>>上提供.
====

[[webflux-oauth2resourceserver-jwt-sansboot]]
=== 覆盖或替换引导自动配置

Spring Boot 代表 Resource Server 生成了两个 `@Bean` 对象.

第一个 bean 是 `SecurityWebFilterChain`,它将应用程序配置为资源服务器. 当包含 `spring-security-oauth2-jose` 时,此 `SecurityWebFilterChain` 看起来像:

.Resource Server SecurityWebFilterChain
====
.Java
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		.authorizeExchange(exchanges -> exchanges
			.anyExchange().authenticated()
		)
		.oauth2ResourceServer(OAuth2ResourceServerSpec::jwt)
	return http.build();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            jwt { }
        }
    }
}
----
====

如果应用程序未暴露 `SecurityWebFilterChain` Bean,则 Spring Boot 将暴露以上默认的 bean.

替换它就像在应用程序中暴露 `@Bean` 一样简单:

.Replacing SecurityWebFilterChain
====
.Java
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		.authorizeExchange(exchanges -> exchanges
			.pathMatchers("/message/**").hasAuthority("SCOPE_message:read")
			.anyExchange().authenticated()
		)
		.oauth2ResourceServer(oauth2 -> oauth2
			.jwt(withDefaults())
		);
	return http.build();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize("/message/**", hasAuthority("SCOPE_message:read"))
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            jwt { }
        }
    }
}
----
====

以上要求 `message.read` 的范围: 以 `/messages/` 开头的所有 URL.

`oauth2ResourceServer` DSL 上的方法还将覆盖或替换自动配置.

例如,第二个 `@Bean` Spring Boot 创建的是 `ReactiveJwtDecoder`,它将 String 令牌解码为经过验证的 `Jwt` 实例:


.ReactiveJwtDecoder
====
.Java
[source,java,role="primary"]
----
@Bean
public ReactiveJwtDecoder jwtDecoder() {
    return ReactiveJwtDecoders.fromIssuerLocation(issuerUri);
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    return ReactiveJwtDecoders.fromIssuerLocation(issuerUri)
}
----
====

[NOTE]
====
调用 `{security-api-url}org/springframework/security/oauth2/jwt/ReactiveJwtDecoders.html#fromIssuerLocation-java.lang.String-[ReactiveJwtDecoders#fromIssuerLocation]` 会调用提供者配置或授权服务器元数据端点,以 扩展 JWK 设置 Uri.  如果该应用程序未暴露 `ReactiveJwtDecoder` Bean,则 Spring Boot 将暴露上述默认值.
====

可以使用 `jwkSetUri()` 覆盖其配置,也可以使用 `decoder()` 替换其配置.

[[webflux-oauth2resourceserver-jwt-jwkseturi-dsl]]
==== 使用 `jwkSetUri()`

授权服务器的 JWK 设置 Uri 可以配置为 <<webflux-oauth2resourceserver-jwt-jwkseturi,配置属性>> ,也可以在 DSL 中提供:

====
.Java
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		.authorizeExchange(exchanges -> exchanges
			.anyExchange().authenticated()
		)
		.oauth2ResourceServer(oauth2 -> oauth2
			.jwt(jwt -> jwt
				.jwkSetUri("https://idp.example.com/.well-known/jwks.json")
			)
		);
	return http.build();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            jwt {
                jwkSetUri = "https://idp.example.com/.well-known/jwks.json"
            }
        }
    }
}
----
====


使用 `jwkSetUri()` 优先于任何配置属性.

[[webflux-oauth2resourceserver-jwt-decoder-dsl]]
==== 使用 `decoder()`

比 `jwkSetUri()`  更强大的是 `decoder()`,它将完全替代 `JwtDecoder` 的所有 Boot 自动配置:

====
.Java
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		.authorizeExchange(exchanges -> exchanges
			.anyExchange().authenticated()
		)
		.oauth2ResourceServer(oauth2 -> oauth2
			.jwt(jwt -> jwt
				.decoder(myCustomDecoder())
			)
		);
    return http.build();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            jwt {
                jwtDecoder = myCustomDecoder()
            }
        }
    }
}
----
====


当需要更深入的配置 (例如<<webflux-oauth2resourceserver-jwt-validation,validation>>) 时,这非常方便.

[[webflux-oauth2resourceserver-decoder-bean]]
==== 暴露一个 `ReactiveJwtDecoder` `@Bean`

或者,暴露 `ReactiveJwtDecoder`  `@Bean` 与 `decoder()` 具有相同的效果:

====
.Java
[source,java,role="primary"]
----
@Bean
public ReactiveJwtDecoder jwtDecoder() {
    return NimbusReactiveJwtDecoder.withJwkSetUri(jwkSetUri).build();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    return ReactiveJwtDecoders.fromIssuerLocation(issuerUri)
}
----
====

[[webflux-oauth2resourceserver-jwt-decoder-algorithm]]
== 配置可信算法

默认情况下,`NimbusReactiveJwtDecoder` 以及资源服务器将仅使用RS256信任和验证令牌.

您可以通过<<webflux-oauth2resourceserver-jwt-boot-algorithm,Spring Boot>> 或  <<webflux-oauth2resourceserver-jwt-decoder-builder,`NimbusJwtDecoder` 构建器>>对此进行自定义.

[[webflux-oauth2resourceserver-jwt-boot-algorithm]]
=== 使用 Spring Boot 自定义可信算法

设置算法的最简单方法是作为属性:

====
[source,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: RS512
          jwk-set-uri: https://idp.example.org/.well-known/jwks.json
----
====

[[webflux-oauth2resourceserver-jwt-decoder-builder]]
=== 使用 Builder 自定义可信算法

但是,为了获得更大的功能,我们可以使用 `NimbusReactiveJwtDecoder` 附带的构建器:

====
.Java
[source,java,role="primary"]
----
@Bean
ReactiveJwtDecoder jwtDecoder() {
    return NimbusReactiveJwtDecoder.withJwkSetUri(this.jwkSetUri)
            .jwsAlgorithm(RS512).build();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    return NimbusReactiveJwtDecoder.withJwkSetUri(this.jwkSetUri)
            .jwsAlgorithm(RS512).build()
}
----
====

多次调用 `jwsAlgorithm` 会将 `NimbusReactiveJwtDecoder` 配置为信任多个算法,如下所示:

====
.Java
[source,java,role="primary"]
----
@Bean
ReactiveJwtDecoder jwtDecoder() {
    return NimbusReactiveJwtDecoder.withJwkSetUri(this.jwkSetUri)
            .jwsAlgorithm(RS512).jwsAlgorithm(ES512).build();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    return NimbusReactiveJwtDecoder.withJwkSetUri(this.jwkSetUri)
            .jwsAlgorithm(RS512).jwsAlgorithm(ES512).build()
}
----
====

或者,您可以调用 `jwsAlgorithms`:

====
.Java
[source,java,role="primary"]
----
@Bean
ReactiveJwtDecoder jwtDecoder() {
    return NimbusReactiveJwtDecoder.withJwkSetUri(this.jwkSetUri)
            .jwsAlgorithms(algorithms -> {
                    algorithms.add(RS512);
                    algorithms.add(ES512);
            }).build();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    return NimbusReactiveJwtDecoder.withJwkSetUri(this.jwkSetUri)
            .jwsAlgorithms {
                it.add(RS512)
                it.add(ES512)
            }
            .build()
}
----
====

[[webflux-oauth2resourceserver-jwt-decoder-public-key]]
=== 信任单个非对称密钥

比使用 JWK Set 端点备份资源服务器更简单的方法是对RSA公钥进行硬编码. 可以通过<<oauth2resourceserver-jwt-decoder-public-key-boot,Spring Boot>> 或<<oauth2resourceserver-jwt-decoder-public-key-builder,使用 Builder>>提供公共密钥.

[[webflux-oauth2resourceserver-jwt-decoder-public-key-boot]]
==== 通过 Spring Boot

您可以使用 Spring Boot 指定密钥：

====
[source,yaml]
----
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:my-key.pub
----
====

或者,为了进行更复杂的查找,可以对 `RsaKeyConversionServicePostProcessor` 进行后置处理:

.BeanFactoryPostProcessor
====
.Java
[source,java,role="primary"]
----
@Bean
BeanFactoryPostProcessor conversionServiceCustomizer() {
    return beanFactory ->
        beanFactory.getBean(RsaKeyConversionServicePostProcessor.class)
                .setResourceLoader(new CustomResourceLoader());
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun conversionServiceCustomizer(): BeanFactoryPostProcessor {
    return BeanFactoryPostProcessor { beanFactory: ConfigurableListableBeanFactory ->
        beanFactory.getBean<RsaKeyConversionServicePostProcessor>()
                .setResourceLoader(CustomResourceLoader())
    }
}
----
====

指定密钥的位置:

====
[source,yaml]
----
key.location: hfds://my-key.pub
----
====

然后自动装配值:

====
.Java
[source,java,role="primary"]
----
@Value("${key.location}")
RSAPublicKey key;
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Value("\${key.location}")
val key: RSAPublicKey? = null
----
====

[[webflux-oauth2resourceserver-jwt-decoder-public-key-builder]]
==== 使用 Builder

要直接连接 `RSAPublicKey`,只需使用适当的 `NimbusJwtDecoder` builder,如下所示:

====
.Java
[source,java,role="primary"]
----
@Bean
public ReactiveJwtDecoder jwtDecoder() {
    return NimbusReactiveJwtDecoder.withPublicKey(this.key).build();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    return NimbusReactiveJwtDecoder.withPublicKey(key).build()
}
----
====

[[webflux-oauth2resourceserver-jwt-decoder-secret-key]]
=== 信任单个对称密钥

使用单个对称密钥也很简单. 您可以简单地加载 `SecretKey` 并使用适当的 `NimbusJwtDecoder` 构建器,如下所示:

====
.Java
[source,java,role="primary"]
----
@Bean
public ReactiveJwtDecoder jwtDecoder() {
    return NimbusReactiveJwtDecoder.withSecretKey(this.key).build();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    return NimbusReactiveJwtDecoder.withSecretKey(this.key).build()
}
----
====

[[webflux-oauth2resourceserver-jwt-authorization]]
=== 配置授权

从 OAuth 2.0 授权服务器发出的JWT通常具有 `scope` 或 `scp` 属性,指示其被授予的作用域 (或权限) ,例如:

====
[source,json]
----
{ ..., "scope" : "messages contacts"}
----
====

在这种情况下,资源服务器将尝试将这些作用域强制为已授予权限的列表,并为每个作用域添加字符串 "SCOPE_" 作为前缀.

这意味着为了保护具有从 JWT 扩展的作用域的端点或方法,相应的表达式应包含以下前缀:


====
.Java
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		.authorizeExchange(exchanges -> exchanges
			.mvcMatchers("/contacts/**").hasAuthority("SCOPE_contacts")
			.mvcMatchers("/messages/**").hasAuthority("SCOPE_messages")
			.anyExchange().authenticated()
		)
		.oauth2ResourceServer(OAuth2ResourceServerSpec::jwt);
    return http.build();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize("/contacts/**", hasAuthority("SCOPE_contacts"))
            authorize("/messages/**", hasAuthority("SCOPE_messages"))
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            jwt { }
        }
    }
}
----
====

或类似地具有方法安全性:

====
.Java
[source,java,role="primary"]
----
@PreAuthorize("hasAuthority('SCOPE_messages')")
public Flux<Message> getMessages(...) {}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@PreAuthorize("hasAuthority('SCOPE_messages')")
fun getMessages(): Flux<Message> { }
----
====

[[webflux-oauth2resourceserver-jwt-authorization-extraction]]
==== 手动提取权限

但是,在许多情况下,此默认设置不足.
例如,某些授权服务器不使用 `scope` 属性,而是使用自己的自定义属性.
或者,在其他时候,资源服务器可能需要将属性或属性组成调整为内部化的权限.

为此,DSL暴露了 `jwtAuthenticationConverter()`:

====
.Java
[source,java,role="primary"]
----
@Bean
SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http) {
	http
		.authorizeExchange(exchanges -> exchanges
			.anyExchange().authenticated()
		)
		.oauth2ResourceServer(oauth2 -> oauth2
			.jwt(jwt -> jwt
				.jwtAuthenticationConverter(grantedAuthoritiesExtractor())
			)
		);
	return http.build();
}

Converter<Jwt, Mono<AbstractAuthenticationToken>> grantedAuthoritiesExtractor() {
    JwtAuthenticationConverter jwtAuthenticationConverter =
            new JwtAuthenticationConverter();
    jwtAuthenticationConverter.setJwtGrantedAuthoritiesConverter
            (new GrantedAuthoritiesExtractor());
    return new ReactiveJwtAuthenticationConverterAdapter(jwtAuthenticationConverter);
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun springSecurityFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
    return http {
        authorizeExchange {
            authorize(anyExchange, authenticated)
        }
        oauth2ResourceServer {
            jwt {
                jwtAuthenticationConverter = grantedAuthoritiesExtractor()
            }
        }
    }
}

fun grantedAuthoritiesExtractor(): Converter<Jwt, Mono<AbstractAuthenticationToken>> {
    val jwtAuthenticationConverter = JwtAuthenticationConverter()
    jwtAuthenticationConverter.setJwtGrantedAuthoritiesConverter(GrantedAuthoritiesExtractor())
    return ReactiveJwtAuthenticationConverterAdapter(jwtAuthenticationConverter)
}
----
====

负责将 `Jwt` 转换为 `Authentication`. 作为其配置的一部分,我们可以提供一个辅助转换器,从 `Jwt` 到授权的 `Collection`.

最终的转换器可能类似于下面的 `GrantedAuthoritiesExtractor`:

====
.Java
[source,java,role="primary"]
----
static class GrantedAuthoritiesExtractor
        implements Converter<Jwt, Collection<GrantedAuthority>> {

    public Collection<GrantedAuthority> convert(Jwt jwt) {
        Collection<?> authorities = (Collection<?>)
                jwt.getClaims().getOrDefault("mycustomclaim", Collections.emptyList());

        return authorities.stream()
                .map(Object::toString)
                .map(SimpleGrantedAuthority::new)
                .collect(Collectors.toList());
    }
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
internal class GrantedAuthoritiesExtractor : Converter<Jwt, Collection<GrantedAuthority>> {
    override fun convert(jwt: Jwt): Collection<GrantedAuthority> {
        val authorities: List<Any> = jwt.claims
                .getOrDefault("mycustomclaim", emptyList<Any>()) as List<Any>
        return authorities
                .map { it.toString() }
                .map { SimpleGrantedAuthority(it) }
    }
}
----
====

为了获得更大的灵活性,DSL 支持使用实现  `Converter<Jwt, Mono<AbstractAuthenticationToken>>` 的任何类完全替换该转换器:

====
.Java
[source,java,role="primary"]
----
static class CustomAuthenticationConverter implements Converter<Jwt, Mono<AbstractAuthenticationToken>> {
    public AbstractAuthenticationToken convert(Jwt jwt) {
        return Mono.just(jwt).map(this::doConversion);
    }
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
internal class CustomAuthenticationConverter : Converter<Jwt, Mono<AbstractAuthenticationToken>> {
    override fun convert(jwt: Jwt): Mono<AbstractAuthenticationToken> {
        return Mono.just(jwt).map(this::doConversion)
    }
}
----
====

[[webflux-oauth2resourceserver-jwt-validation]]
=== 配置验证

使用 <<webflux-oauth2resourceserver-jwt-minimalconfiguration,Spring Boot 最小配置>>,  (指示授权服务器的 issuer uri) ,Resource Server将默认验证 `iss` 声明以及 `exp` 和 `nbf` 时间戳声明.

在需要自定义验证的情况下,资源服务器附带两个标准验证器,并且还接受自定义 `OAuth2TokenValidator` 实例.

[[webflux-oauth2resourceserver-jwt-validation-clockskew]]
==== 自定义时间戳验证

JWT 通常具有有效期窗口,该窗口的开始在 `nbf` 声明中指示,而结束在 `exp` 声明中指示.

但是,每台服务器都会经历时钟漂移,这可能导致令牌在一个服务器上已经过期,而在另一台服务器上没有过期. 随着分布式系统中服务器数量的增加,这可能会导致某些实现上的不良反应.

资源服务器使用 `JwtTimestampValidator` 验证令牌的有效性窗口,并且可以将它配置为 `ClockSkew` 来缓解上述问题:

====
.Java
[source,java,role="primary"]
----
@Bean
ReactiveJwtDecoder jwtDecoder() {
     NimbusReactiveJwtDecoder jwtDecoder = (NimbusReactiveJwtDecoder)
             ReactiveJwtDecoders.fromIssuerLocation(issuerUri);

     OAuth2TokenValidator<Jwt> withClockSkew = new DelegatingOAuth2TokenValidator<>(
            new JwtTimestampValidator(Duration.ofSeconds(60)),
            new IssuerValidator(issuerUri));

     jwtDecoder.setJwtValidator(withClockSkew);

     return jwtDecoder;
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    val jwtDecoder = ReactiveJwtDecoders.fromIssuerLocation(issuerUri) as NimbusReactiveJwtDecoder
    val withClockSkew: OAuth2TokenValidator<Jwt> = DelegatingOAuth2TokenValidator(
            JwtTimestampValidator(Duration.ofSeconds(60)),
            JwtIssuerValidator(issuerUri))
    jwtDecoder.setJwtValidator(withClockSkew)
    return jwtDecoder
}
----
====

[NOTE]
====
默认情况下,资源服务器将时钟偏差配置为 60 秒.
====

[[webflux-oauth2resourceserver-validation-custom]]
==== 配置自定义验证器

使用 `OAuth2TokenValidator` API 为 `aud` 声明添加检查很简单:

====
.Java
[source,java,role="primary"]
----
public class AudienceValidator implements OAuth2TokenValidator<Jwt> {
    OAuth2Error error = new OAuth2Error("invalid_token", "The required audience is missing", null);

    public OAuth2TokenValidatorResult validate(Jwt jwt) {
        if (jwt.getAudience().contains("messaging")) {
            return OAuth2TokenValidatorResult.success();
        } else {
            return OAuth2TokenValidatorResult.failure(error);
        }
    }
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
class AudienceValidator : OAuth2TokenValidator<Jwt> {
    var error: OAuth2Error = OAuth2Error("invalid_token", "The required audience is missing", null)
    override fun validate(jwt: Jwt): OAuth2TokenValidatorResult {
        return if (jwt.audience.contains("messaging")) {
            OAuth2TokenValidatorResult.success()
        } else {
            OAuth2TokenValidatorResult.failure(error)
        }
    }
}
----
====


然后,要添加到资源服务器中,只需指定 `ReactiveJwtDecoder` 实例即可:

====
.Java
[source,java,role="primary"]
----
@Bean
ReactiveJwtDecoder jwtDecoder() {
    NimbusReactiveJwtDecoder jwtDecoder = (NimbusReactiveJwtDecoder)
            ReactiveJwtDecoders.fromIssuerLocation(issuerUri);

    OAuth2TokenValidator<Jwt> audienceValidator = new AudienceValidator();
    OAuth2TokenValidator<Jwt> withIssuer = JwtValidators.createDefaultWithIssuer(issuerUri);
    OAuth2TokenValidator<Jwt> withAudience = new DelegatingOAuth2TokenValidator<>(withIssuer, audienceValidator);

    jwtDecoder.setJwtValidator(withAudience);

    return jwtDecoder;
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun jwtDecoder(): ReactiveJwtDecoder {
    val jwtDecoder = ReactiveJwtDecoders.fromIssuerLocation(issuerUri) as NimbusReactiveJwtDecoder
    val audienceValidator: OAuth2TokenValidator<Jwt> = AudienceValidator()
    val withIssuer: OAuth2TokenValidator<Jwt> = JwtValidators.createDefaultWithIssuer(issuerUri)
    val withAudience: OAuth2TokenValidator<Jwt> = DelegatingOAuth2TokenValidator(withIssuer, audienceValidator)
    jwtDecoder.setJwtValidator(withAudience)
    return jwtDecoder
}
----
====
