= GEOADD

**语法**

[source,text]
----
GEOADD key [NX | XX] [CH] longitude latitude member [longitude
  latitude member ...]
----

**可用版本**：3.2.0

**时间复杂度**：添加的每个元素的 O(log(N))，其中 N 是有序集中的元素数量。

**ACL 类别**：**@write, @geo, @slow**

Redis GEOADD 用于将给定的空间元素（纬度、经度、名字）添加到指定的 key 里面。 这样就可以使用 `GEOSEARCH` 命令查询元素。

GEOADD 命令以标准的 x,y 格式接受参数， 所以用户必须先输入经度， 然后再输入纬度。 GEOADD 能够记录的坐标是有限的：非常接近两极的区域是无法被索引的。

精确的坐标限制由 EPSG:900913 / EPSG:3785 / OSGEO:41001 等坐标系统定义， 具体如下：

* 有效经度范围为 -180 到 180 度。
* 有效纬度范围为 -85.05112878 到 85.05112878 度。

当用户尝试输入一个超出范围的经度或者纬度时， GEOADD 命令将返回一个错误。

NOTE: 没有 `GEODEL` 命令，因为您可以使用 `ZREM` 删除元素。 Geo 索引结构只是一个有序集。

== GEOADD 选项

GEOADD 还提供以下选项：

* XX：只更新已经存在的元素。 切勿添加元素。
* NX：不要更新已经存在的元素。 始终添加新元素。
* CH：将返回值从新增元素的数量修改为已更改元素的总数（CH 是changed 的缩写）。 更改的元素是添加的新元素和坐标已更新的已存在元素。 因此，在命令行中指定的与过去具有相同分数的元素不被计算在内。 注意：通常情况下，GEOADD的返回值只统计新增元素的数量。

NOTE: XX 和 NX 选项是互斥的。

== 它是如何工作的？

sorted set使用一种称为 https://en.wikipedia.org/wiki/Geohash[Geohash]  的技术进行填充。经度和纬度的位是交错的，以形成一个独特的 52 位整数. 我们知道，一个 sorted set 的 double score 可以代表一个 52 位的整数，而不会失去精度。

这种格式允许半径查询检查的1 + 8个领域需要覆盖整个半径，并丢弃元素以外的半径。通过计算该区域的范围，通过计算所涵盖的范围，从不太重要的部分的有序集的得分，并计算得分范围为每个区域的sorted set中的查询。

== 它使用什么地球模型？

这只是假设地球是一个球体，因为使用的距离公式是Haversine公式。这个公式仅适用于地球，而不是一个完美的球体。当在社交网站和其他大多数需要查询半径的应用中使用时，这些偏差都不算问题。但是，在最坏的情况下的偏差可能是0.5%，所以一些地理位置很关键的应用还是需要谨慎考虑。

== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-integers[整数]:

* 当不带可选参数使用时，添加到有序集中的元素数量（不包括分数更新）。
* 如果指定了 CH 选项，则为已更改（添加或更新）的元素数。

== 示例

[source,text]
----
redis> GEOADD Sicily 13.361389 38.115556 "Palermo" 15.087269 37.502669 "Catania"
(integer) 2
redis> GEODIST Sicily Palermo Catania
"166274.1516"
redis> GEORADIUS Sicily 15 37 100 km
1) "Catania"
redis> GEORADIUS Sicily 15 37 200 km
1) "Palermo"
2) "Catania"
redis>
----

== 历史

* 从 Redis 版本 6.2.0 开始：添加了 CH、NX 和 XX 选项。
