= GEORADIUS

NOTE: 从 Redis 版本 6.2.0 开始，此命令被视为已弃用。 迁移或编写新代码时，可以使用 BYRADIUS 参数将其替换为 GEOSEARCH 和 GEOSEARCHSTORE。

**语法**

[source,text]
----
GEORADIUS key longitude latitude radius <M | KM | FT | MI>
  [WITHCOORD] [WITHDIST] [WITHHASH] [COUNT count [ANY]] [ASC | DESC]
  [STORE key | STOREDIST key]
----

**可用版本**：3.2.0

**时间复杂度**：O(N+log(M))，其中 N 是由中心和半径分隔的圆形区域的边界框内的元素数量，M 是索引内的项目数量。

**ACL 类别**：**@write, @geo, @slow**

Redis GEORADIUS 命令以给定的经纬度为中心， 返回键包含的位置元素当中， 与中心的距离不超过给定最大距离的所有位置元素。

本手册页还涵盖 GEORADIUS_RO 和 GEORADIUSBYMEMBER_RO（有关详细信息，请参阅下面的部分）。

此命令的常见用例是检索指定点附近不超过给定米（或其他单位）的地理空间元素。 例如，这可以向移动用户推荐附近地点的应用程序。

半径以下列单位之一指定：

* m 代表米。
* km 为公里。
* mi 为英里。
* ft 为英尺。

在给定以下可选项时， 命令会返回额外的信息：

* WITHDIST：在返回位置元素的同时， 将位置元素与中心之间的距离也一并返回。 距离的单位和用户给定的范围单位保持一致。
* WITHCOORD：将位置元素的经度和维度也一并返回。
* WITHHASH：以 52 位有符号整数的形式， 返回位置元素经过原始 geohash 编码的有序集合分值。 这个选项主要用于底层应用或者调试， 实际中的作用并不大。

该命令默认返回未排序的项目。 可以使用以下两个选项调用两种不同的排序方法：

* ASC：根据中心的位置， 按照从近到远的方式返回位置元素。
* DESC：根据中心的位置， 按照从远到近的方式返回位置元素。

默认情况下返回所有匹配的项目。 通过使用 COUNT <count> 选项，可以将结果限制为前 N 个匹配项。 当提供 `ANY` 时，一旦找到足够的匹配项，该命令将立即返回，因此结果可能不是最接近指定点的结果，但另一方面，服务器投入的工作量明显较低。
当未提供 `ANY` 时，该命令将执行与指定区域匹配的项目数量成正比的工作并对它们进行排序，因此使用非常小的 COUNT 选项查询非常大的区域可能会很慢，即使只有几个结果返回。

默认情况下，该命令将元素返回给客户端。 可以使用以下选项之一存储结果：

* STORE：将元素存储在填充有地理空间信息的有序集中。
* STOREDIST：将元素存储在有序集中，并以浮点数形式填充距中心的距离，并采用半径中指定的相同单位。

== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-arrays[数组]:

* 在没有给定任何 `WITH` 选项的情况下， 命令只会返回一个像 `["New York","Milan","Paris"]` 这样的线性（linear）列表。
* 在指定了 `WITHCOORD` 、 `WITHDIST` 、 `WITHHASH` 等选项的情况下， 命令返回一个二层嵌套数组， 内层的每个子数组就表示一个元素。

在返回嵌套数组时， 子数组的第一个元素总是位置元素的名字。 至于额外的信息， 则会作为子数组的后续元素， 按照以下顺序被返回：

. 以浮点数格式返回的中心与位置元素之间的距离， 单位与用户指定范围时的单位一致。
. geohash 整数。
. 由两个元素组成的坐标，分别为经度和纬度。

举个例子， GEORADIUS Sicily 15 37 200 km WITHCOORD WITHDIST  这样的命令返回的每个子数组都是类似以下格式的：

[source,text]
----
["Palermo","190.4424",["13.361389338970184","38.115556395496299"]]
----

== 只读形式

由于 GEORADIUS 和 GEORADIUSBYMEMBER 有 STORE 和 STOREDIST 选项，它们在技术上被标记为 Redis 命令表中的写入命令。 因此，只读副本会对它们进行标记，并且即使连接处于只读模式，Redis 集群副本也会将它们重定向到主实例（请参阅 Redis 集群的 READONLY 命令）。

至少对于 Redis 4.0，曾考虑过打破与过去的兼容性，但遭到拒绝，因此添加了命令的两个只读变体。 它们与原始命令完全相同，但拒绝 STORE 和 STOREDIST 选项。 这两个变体称为 GEORADIUS_RO 和 GEORADIUSBYMEMBER_RO，可以安全地在副本中使用。

== 示例

[source,text]
----
redis> GEOADD Sicily 13.361389 38.115556 "Palermo" 15.087269 37.502669 "Catania"
(integer) 2
redis> GEORADIUS Sicily 15 37 200 km WITHDIST
1) 1) "Palermo"
   2) "190.4424"
2) 1) "Catania"
   2) "56.4413"
redis> GEORADIUS Sicily 15 37 200 km WITHCOORD
1) 1) "Palermo"
   2) 1) "13.36138933897018433"
      2) "38.11555639549629859"
2) 1) "Catania"
   2) 1) "15.08726745843887329"
      2) "37.50266842333162032"
redis> GEORADIUS Sicily 15 37 200 km WITHDIST WITHCOORD
1) 1) "Palermo"
   2) "190.4424"
   3) 1) "13.36138933897018433"
      2) "38.11555639549629859"
2) 1) "Catania"
   2) "56.4413"
   3) 1) "15.08726745843887329"
      2) "37.50266842333162032"
redis>
----

== 历史

* 从 Redis 版本 6.2.0 开始：为 COUNT 添加了 ANY 选项。
* 从 Redis 版本 7.0.0 开始：添加了对大写单位名称的支持。
