= GEOSEARCH

**语法**

[source,text]
----
GEOSEARCH key <FROMMEMBER member | FROMLONLAT longitude latitude>
  <BYRADIUS radius <M | KM | FT | MI> | BYBOX width height <M | KM |
  FT | MI>> [ASC | DESC] [COUNT count [ANY]] [WITHCOORD] [WITHDIST]
  [WITHHASH]
----

**可用版本**：6.2.0

**时间复杂度**：O(N+log(M))，其中 N 是由中心和半径分隔的圆形区域的边界框内的元素数量，M 是索引内的项目数量

**ACL 类别**：**@read, @geo, @slow**

使用 GEOADD 返回填充有地理空间信息的有序集的成员，这些成员位于给定形状指定的区域的边界内。 该命令扩展了GEORADIUS命令，除了支持圆形区域内搜索外，还支持矩形区域内搜索。

应使用此命令代替已弃用的 GEORADIUS 和 GEORADIUSBYMEMBER 命令。

查询的中心点由以下强制选项之一提供：

* FROMMEMBER：使用给定现有 <member> 在有序集中的位置。
* FROMLONLAT：使用给定的 <longitude> 和 <latitude> 位置。

查询的形状由以下强制选项之一提供：

* BYRADIUS：与 GEORADIUS 类似，根据给定的<半径>在圆形区域内搜索。
* BYBOX：在轴对齐的矩形内搜索，由 <height> 和 <width> 确定。

该命令可以选择使用以下选项返回附加信息：

* WITHDIST：在返回位置元素的同时， 将位置元素与中心之间的距离也一并返回。 距离的单位和用户给定的范围单位保持一致。
* WITHCOORD：将位置元素的经度和维度也一并返回。
* WITHHASH：以 52 位有符号整数的形式， 返回位置元素经过原始 geohash 编码的有序集合分值。 这个选项主要用于底层应用或者调试， 实际中的作用并不大。

默认情况下，匹配项返回时未排序。 要对它们进行排序，请使用以下两个选项之一：

* ASC：根据中心的位置， 按照从近到远的方式返回位置元素。
* DESC：根据中心的位置， 按照从远到近的方式返回位置元素。

默认情况下返回所有匹配的项目。 要将结果限制为前 N 个匹配项，请使用 COUNT <count> 选项。 使用 ANY 选项时，一旦找到足够的匹配项，该命令就会返回。 这意味着返回的结果可能不是最接近指定点的结果，但服务器生成它们所投入的精力要少得多。 当未提供 ANY 时，该命令将执行与指定区域匹配的项目数量成正比的工作并对它们进行排序，因此使用非常小的 COUNT 选项查询非常大的区域可能会很慢，即使只有几个结果 回。

== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-arrays[数组]:

* 在没有给定任何 `WITH` 选项的情况下， 命令只会返回一个像 `["New York","Milan","Paris"]` 这样的线性（linear）列表。
* 在指定了 `WITHCOORD` 、 `WITHDIST` 、 `WITHHASH` 等选项的情况下， 命令返回一个二层嵌套数组， 内层的每个子数组就表示一个元素。

在返回嵌套数组时， 子数组的第一个元素总是位置元素的名字。 至于额外的信息， 则会作为子数组的后续元素， 按照以下顺序被返回：

. 以浮点数格式返回的中心与位置元素之间的距离， 单位与用户指定范围时的单位一致。
. geohash 整数。
. 由两个元素组成的坐标，分别为经度和纬度。

== 示例

[source,text]
----
redis> GEOADD Sicily 13.361389 38.115556 "Palermo" 15.087269 37.502669 "Catania"
(integer) 2
redis> GEOADD Sicily 12.758489 38.788135 "edge1"   17.241510 38.788135 "edge2"
(integer) 2
redis> GEOSEARCH Sicily FROMLONLAT 15 37 BYRADIUS 200 km ASC
1) "Catania"
2) "Palermo"
redis> GEOSEARCH Sicily FROMLONLAT 15 37 BYBOX 400 400 km ASC WITHCOORD WITHDIST
1) 1) "Catania"
   2) "56.4413"
   3) 1) "15.08726745843887329"
      2) "37.50266842333162032"
2) 1) "Palermo"
   2) "190.4424"
   3) 1) "13.36138933897018433"
      2) "38.11555639549629859"
3) 1) "edge2"
   2) "279.7403"
   3) 1) "17.24151045083999634"
      2) "38.78813451624225195"
4) 1) "edge1"
   2) "279.7405"
   3) 1) "12.7584877610206604"
      2) "38.78813451624225195"
redis>
----

== 历史

* 从 Redis 版本 7.0.0 开始：添加了对大写单位名称的支持。
