// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[gradle_daemon]]
= Gradle Daemon

[quote, Wikipedia]
守护进程是一种计算机程序，它作为后台进程运行，而不是受交互式用户的直接控制。

Gradle 在 Java 虚拟机(JVM)上运行，并使用几个支持库，它们需要很短的初始化时间。结果，有时启动似乎有些慢。这个问题的解决方案是 Gradle _Daemon_: 一个长期存在的后台进程，比起其他情况，它可以更快地执行构建。
通过避免昂贵的引导过程以及利用缓存(将有关项目的数据保留在内存中)，我们可以实现这一目标。使用 Daemon 运行 Gradle 构建与没有运行没有什么不同。只需配置您是否要使用它-其他所有事情都由 Gradle 透明地处理。

[[sec:why_the_daemon]]
== 为什么 Gradle Daemon 对性能很重要

Daemon 是一个长期存在的进程，因此我们不仅可以避免每次构建都需要启动 JVM 的成本，而且还可以在内存中缓存有关项目结构，文件，任务等信息。

推理很简单: 通过重用以前构建的计算来提高构建速度。但是，这样做的好处是巨大的: 我们通常会在以后的构建中将构建时间减少 15-75％。我们建议您使用 `--profile` 对构建进行概要分析，以了解 Gradle Daemon 对您的影响。

Gradle Daemon 从 Gradle 3.0 开始默认启用，因此您无需做任何事情即可从中受益。

[[sec:status]]
== Daemon 运行状态

要获取正在运行的Gradle守护程序及其状态的列表，请使用--status命令。

输出:
[source]
----
    PID VERSION                 STATUS
  28411 3.0                     IDLE
  34247 3.0                     BUSY
----

当前，给定的 Gradle 版本只能连接到相同版本的 Daemon。这意味着状态输出将仅显示正在调用的 Gradle 版本的 Daemon，而不显示任何其他版本的 Daemon。 Gradle 的未来版本将解除此约束，并将显示所有 Gradle 版本的正在运行的 Daemon。

[[sec:disabling_the_daemon]]
== 禁用 Daemon

Gradle Daemon 默认情况下处于启用状态，我们建议始终启用它。有几种方法可以禁用守护程序，但是最常见的一种方法是添加该行

[source]
----
org.gradle.daemon=false
----

到文件  `«USER_HOME»/.gradle/gradle.properties`，其中 `«USER_HOME»`  是您的主目录。通常是以下之一，具体取决于您的平台:

* `C:\Users\<username>` (Windows Vista & 7+)
* `/Users/<username>` (macOS)
* `/home/<username>` (Linux)

如果该文件不存在，只需使用文本编辑器创建它即可。您可以在下面的 <<#daemon_faq,Daemon FAQ>> 中找到其他禁用(启用)Daemon 的方法的详细信息。该部分还包含有关 Daemon 如何工作的更多详细信息。

请注意，启用了 Daemon 后，无论特定构建使用的 Gradle 版本如何，所有构建都将利用速度提升。

[TIP]
.Continuous integration(持续集成, CI)
====

从 Gradle 3.0 开始，我们默认启用 Daemon 并建议将其用于开发人员的计算机和 Continuous Integration 服务器。但是，如果您怀疑 Daemon 使 CI 构建不稳定，则可以将其禁用以对每个构建使用全新的运行时，因为运行时与任何先前的构建完全隔离。

====


[[sec:stopping_an_existing_daemon]]
== 停止现有的 Daemon

如前所述，Daemon 是一个后台进程。不过，您不必担心计算机上会建立 Gradle 进程。与可用的系统内存总量相比，每个 Daemon 都会监视其内存使用情况，如果可用系统内存不足，则每个空闲进程都会在空闲时停止运行。
如果您出于任何原因要明确停止运行 Daemon 进程，只需使用命令 `gradle --stop`。

这将终止所有与用于执行命令的相同 Gradle 版本一起启动的 Daemon 进程。如果安装了 Java Development Kit (JDK)，则可以通过运行 `jps` 命令轻松地验证守护程序是否已停止。您会看到所有名为 `GradleDaemon` 的正在运行的Daemon。

[[daemon_faq]]
== FAQ


[[sec:ways_to_disable_gradle_daemon]]
=== 如何禁用Gradle Daemon?

有两种建议的方法可以永久禁用 Daemon:

* 通过环境变量: 将 `-Dorg.gradle.daemon=false` 添加到 `GRADLE_OPTS` 环境变量
* 通过属性文件: 将 `org.gradle.daemon=false` 添加到 `«GRADLE_USER_HOME»/gradle.properties` 文件中

[NOTE]
====

注意， `«GRADLE_USER_HOME»` 默认为 `«USER_HOME»/.gradle`，其中  `«USER_HOME»` 是当前用户的主目录。可以通过 `-g` 和 `--gradle-user-home` 命令行开关以及 `GRADLE_USER_HOME` 环境变量和 `org.gradle.user.home` JVM 系统属性来配置此位置。

====

两种方法具有相同的效果。使用哪一个取决于个人喜好。大多数Gradle用户选择第二个选项，并将条目添加到用户 `gradle.properties` 文件中。

在 Windows 上，此命令将为当前用户禁用 Daemon:

[source]
----
(if not exist "%USERPROFILE%/.gradle" mkdir "%USERPROFILE%/.gradle") && (echo. >> "%USERPROFILE%/.gradle/gradle.properties" && echo org.gradle.daemon=false >> "%USERPROFILE%/.gradle/gradle.properties")
----

在类似 UNIX 的操作系统上，以下 Bash shell 命令将为当前用户禁用 Daemon:

[source,bash]
----
mkdir -p ~/.gradle && echo "org.gradle.daemon=false" >> ~/.gradle/gradle.properties
----

一旦以这种方式为构建环境禁用了守护程序，除非使用 `--daemon` 选项明确请求，否则不会启动 Gradle 守护程序。

使用 Gradle 命令行界面时，`--daemon` 和 `--no-daemon` 命令行选项启用和禁用对单个构建调用的守护程序使用。在考虑构建环境时，这些命令行选项具有最高优先级。通常，为环境(例如用户帐户)启用 Daemon 更为方便，以便所有构建都使用 Daemon，而无需记住提供 `--daemon` 选项。

[[sec:why_is_there_more_than_one_daemon_process_on_my_machine]]
=== 为什么我的机器上有多个Daemon进程?

Gradle 为什么要创建一个新的 Daemon，而不是使用已经运行的 Daemon，有几个原因。基本规则是，如果没有可用的空闲或兼容 Daemon，则 Gradle 将启动新的 Daemon。 Gradle 将杀死任何闲置 3 个小时或更长时间的 Daemon，因此您不必担心手动清理它们。

idle::
空闲的 Daemon 是当前未执行构建或未执行其他有用工作的进程。
compatible::
兼容的 Daemon 是可以(或可以使其)满足所请求构建环境的要求的 Daemon。用于执行构建的 Java 运行时是构建环境的一个示例方面。另一个示例是构建运行时所需的 JVM 系统属性集。

Daemon 可能无法满足所请求的构建环境的某些方面。如果 Daemon 与 Java 8 运行时一起运行，但是请求的环境要求 Java 10，则该 Daemon 不兼容，必须启动另一个 Daemon。而且，一旦 JVM 启动，就无法更改 Java 运行时的某些属性。例如，无法更改正在运行的JVM的内存分配(例如 `-Xmx1024m`)，默认文本编码，默认语言环境等。

通常，“请求的构建环境”是从构建客户端(例如 Gradle 命令行客户端，IDE 等)环境的各个方面隐式构建的，并且是通过命令行开关和设置显式构建的。有关如何指定和控制构建环境的详细信息，请参见 <<build_environment.adoc#build_environment,构建环境>>。

以下 JVM 系统属性实际上是不可变的。如果请求的构建环境需要这些属性中的任何一个，且其值与 Daemon 的 JVM 具有的此属性不同，则该 Daemon 不兼容。

* file.encoding
* user.language
* user.country
* user.variant
* java.io.tmpdir
* javax.net.ssl.keyStore
* javax.net.ssl.keyStorePassword
* javax.net.ssl.keyStoreType
* javax.net.ssl.trustStore
* javax.net.ssl.trustStorePassword
* javax.net.ssl.trustStoreType
* com.sun.management.jmxremote

由启动参数控制的以下 JVM 属性也实际上是不可变的。 为了使 Daemon 兼容，所请求的构建环境和 Daemon 的环境的相应属性必须完全匹配。

* The maximum heap size (i.e. the -Xmx JVM argument)
* The minimum heap size (i.e. the -Xms JVM argument)
* The boot classpath (i.e. the -Xbootclasspath argument)
* The “assertion” status (i.e. the -ea argument)

所需的 Gradle 版本是所请求的构建环境的另一方面。Daemon 进程与特定的 Gradle 运行时耦合。在使用不同 Gradle 版本的会话中处理多个 Gradle 项目是导致多个 Daemon 进程运行的常见原因。

[[sec:how_much_memory_does_the_daemon_use_and_can_i_give_it_more]]
=== Daemon 使用多少内存，可以分配更多空间吗?

如果请求的构建环境未指定最大堆大小，则 Daemon 将使用最多 `512MB` 的堆。它将使用 JVM 的默认最小堆大小。对于大多数构建来说，512MB 绰绰有余。具有数百个子项目的较大内部版本，大量配置和源代码可能需要或具有更好的性能，并具有更多的内存。

要增加 Daemon 可以使用的内存量，请在请求的构建环境中指定适当的标志。有关详细信息，请参见<<build_environment.adoc#build_environment,构建环境>> 。

[[sec:how_can_i_stop_a_daemon]]
=== 如何停止Daemon?

闲置 3 个小时或更短的时间后，Daemon 进程将自动终止。如果您希望在此之前停止 Daemon 进程，则可以通过操作系统终止该进程或运行 `gradle --stop` 命令。`--stop` 开关使 Gradle 请求 所有正在运行 的，与用于运行命令的 Gradle 版本相同的 Daemon 进程自行终止。

[[sec:what_can_go_wrong_with_daemon]]
=== Daemon 会有什么问题?

在日常开发过程中，为了使守护进程健壮、透明和不引人注目，已经进行了大量的工程工作。然而，Daemon 进程有时会被破坏或耗尽。Gradle 构建从多个源执行任意代码。虽然 Gradle 本身是为 Daemon 进程设计的，并通过 Daemon 进程进行了大量测试，但是用户构建脚本和第三方插件可能会通过内存泄漏或全局状态损坏等缺陷破坏Daemon进程的稳定。

通过运行无法正确释放资源的构建，还可能破坏Daemon程序的稳定性(通常是构建环境)。当使用 Microsoft Windows 时，这是一个特别棘手的问题，因为它对读取或写入后无法关闭文件的程序的宽容度较小。

Gradle 主动监视堆使用情况，并尝试检测何时泄漏开始耗尽守护程序中的可用堆空间。当检测到问题时，Gradle Daemon 将完成当前正在运行的构建，并在下一个构建中主动重新启动该 Daemon。默认情况下启用此监视，但是可以通过将org.gradle.daemon.performance.enable-monitoring系统属性设置为false来禁用此监视。

如果怀疑 Daemon 进程变得不稳定，则可以将其杀死。回想一下，可以为构建指定 `--no-daemon` 开关，以防止使用 Daemon。这对于诊断 Daemon 是否为问题的罪魁祸首非常有用。

[[sec:tools_and_ides]]
== Tools & IDEs

IDE 和其他工具用于与 Gradle 集成的 <<third_party_integration.adoc#embedding,Gradle Tooling API>> 始终使用 Gradle Daemon 来执行构建。如果要在 IDE 中执行 Gradle 构建，则使用的是 Gradle Daemon，而无需为您的环境启用它。

[[sec:how_does_the_gradle_daemon_make_builds_faster]]
== Gradle Daemon如何使构建更快?

Gradle Daemon 是一个 长期存在的构建进程。在两次构建之间，它空闲地等待下一次构建。这具有明显的好处，即对于多个构建只需要一次将 Gradle 加载到内存中，而不是对于每个构建加载一次。这本身就是一项重大的性能优化， 但并非止于此。

现代 JVM 性能的一个重要方面是运行时代码优化。例如，HotSpot(Oracle 提供的 JVM 实现，用作 OpenJDK 的基础)在运行时对代码进行优化。优化是渐进的，不是瞬时的。也就是说，在执行过程中对代码进行了逐步优化，
这意味着纯粹由于此优化过程而使得后续构建可以更快。使用HotSpot进行的实验表明，需要 5 到 10 次构建才能稳定优化。守护程序的第一个构建和第 10 个构建之间的可感知构建时间差异可能非常明显。

Daemon 还允许跨构建更有效地进行内存缓存。例如，构建所需的类(例如插件，构建脚本)可以保存在构建之间的内存中。同样，Gradle 可以维护构建数据的内存缓存，例如用于增量构建的任务输入和输出的哈希值。




为了<<sec:daemon_watch_fs,监视文件系统>> 上的更改并计算需要重建的内容，Gradle 会在每次构建过程中收集有关文件系统状态的大量信息。 观看文件系统启用后，Daemon 可以重新使用上次构建中已收集的信息。
这可以为增量构建节省大量时间，而两次构建之间对文件系统的更改次数通常很少。

[[sec:daemon_watch_fs]]
== 监视文件系统

为了检测文件系统上的更改并计算需要重建的内容，Gradle 会在每次构建(即  _Virtual File System_)期间收集有关内存中文件系统的信息。 通过监视文件系统，Gradle 可以使虚拟文件系统与文件系统保持同步，即使在两次构建之间也是如此。
这样做可以使 Daemon 节省时间来从磁盘重建虚拟文件系统以进行下一个构建。 对于增量构建，构建之间通常只有几处更改。 因此，增量构建可以重用上一次构建中的大部分虚拟文件系统，并从监视文件系统中获得最大收益。

Gradle 使用操作系统功能来监视文件系统。它支持以下操作系统和文件系统上的功能:

- Windows 10 with NTFS,
- Linux (Ubuntu 16.04 or later, CentOS 8 or later, Red Hat Enterprise Linux 8 or later, Amazon Linux 2) using ext3 and ext4,
- macOS 10.14 (Mojave) or later on APFS and HFS+.

不支持 NFS 和 SMB 等网络文件系统。 不支持FAT文件系统。

监视文件系统是一项实验性功能，默认情况下处于禁用状态。 您可以通过以下两种方式启用该功能:

Run with `--watch-fs` on the command line::
这样就可以仅监视此构建的文件系统。
Put `org.gradle.vfs.watch=true` in your `gradle.properties`::
除非使用 `--no-watch-fs` 明确将其禁用，否则这将允许监视文件系统的所有构建。

[[sec:daemon_watch_fs_troubleshooting]]
=== 对文件系统监视进行故障排除

局限性::
当前监视文件系统具有以下限制:
- 如果您的版本中包含符号链接，则这些位置将不会带来性能优势。
- 在Windows上，我们不支持网络驱动器(它们可能会工作，但我们尚未对其进行测试)。

启用详细日志记录::
您可以使用 `org.gradle.vfs.verbose`  标志指示 Gradle 提供有关虚拟文件系统状态以及从文件系统接收到的事件的更多信息。:

这将在构建的开始和结束时产生以下输出:
+
----
$ gradle assemble --watch-fs -Dorg.gradle.vfs.verbose=true
Received 3 file system events since last build while watching 1 hierarchies
Virtual file system retained information about 2 files, 2 directories and 0 missing files since last build
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :assemble UP-TO-DATE

BUILD SUCCESSFUL in 58ms
1 actionable task: 1 up-to-date
Received 5 file system events during the current build while watching 1 hierarchies
Virtual file system retains information about 3 files, 2 directories and 2 missing files until next build
----
+
请注意，在 Windows 和 macOS 上，即使您没有进行任何更改，Gradle 可能也会报告自上次构建以来收到的更改。这些是有关 Gradle 自己的缓存更改的无害通知，可以安全地忽略。

Gradle 无法接收我的某些更改::
如果您遇到这种情况，https://gradle-community.slack.com/app_redirect?channel=file-system-watching[请在 Gradle 社区 Slack 上告诉我们]。 如果您的构建正确地声明了其输入和输出，则不应发生这种情况。 因此，这可能是我们需要修复的错误，或者您的构建缺少一些输入或输出的声明。

由于丢失状态，VFS状态被丢弃::
如果您在构建过程中收到 `Dropped VFS state due to lost state` ，https://gradle-community.slack.com/app_redirect?channel=file-system-watching[请在 Gradle 社区 Slack 上告诉我们] ，如果您遇到这种情况。 此消息表示
+
--
- daemon 收到一些未知的文件系统事件，
- 发生了太多更改，并且监视 API 无法处理它。
--
在这两种情况下，构建都无法从文件系统监视中受益。

macOS上的打开文件过多::
如果您在 macOS 上收到 `java.io.IOException: Too many open files` ，则需要提高打开文件的限制，请参见 https://superuser.com/a/443168/8117[此处]。

[[sec:inotify_watches_limit]]
=== Linux专用说明

文件系统监视在 Linux 上使用 http://en.wikipedia.org/wiki/Inotify[inotify]。根据构建的大小，可能有必要增加 inotify 限制。如果您使用的是 IDE，那么过去您可能已经不得不增加限制。

文件系统监视对每个监视目录使用一个 inotify 监视。您可以通过运行以下命令查看每个用户当前的 inotify 监视限制:

[source,bash]
----
cat /proc/sys/fs/inotify/max_user_watches
----

将限制增加到 `512K` ,运行以下命令:

[source,bash]
----
echo 524288 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p --system
----

每个使用的 inotify 监视最多占用 1KB 的内存。假设 inotify 使用所有 512K 监视，那么将使用大约 500MB 的空间来监视文件系统。如果环境受内存限制，则可能要禁用文件系统监视。