// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[intro_multi_project_builds]]
= 执行 Multi-Project 构建

除非碰巧是一个庞大的整体应用程序，否则只有最小的项目具有单个构建文件和源树。 消化和理解一个项目的过程通常要容易得多，这些项目被分为多个较小的，相互依赖的模块。 但是，“相互依赖”一词很重要，这就是为什么您通常希望通过单个构建将模块链接在一起。

Gradle 通过多项目构建来支持此方案。

有关创建 多项目构建的详细信息，请参阅 <<multi_project_builds#multi_project_builds,用户手册的 "创建多项目构建">>部分。

[[sec:identifying_project_structure]]
== 确定项目结构

要确定项目结构，可以使用 `gradle projects` 命令。例如，我们使用具有以下结构的多项目构建:

----
> gradle -q projects
include::{snippetsPath}/java/multiproject/tests/listProjects.out[]
----

从用户的角度来看，多项目构建仍然是您可以运行的任务的集合。不同之处在于你可能想要控制执行哪个项目的任务。下面的部分将介绍在多项目构建中执行任务的两个选项。

[[sec:executing_tasks_by_name]]
== 按名称执行任务

`gradle test` 命令将在相对于具有该任务的当前工作目录的任何子项目中执行 `test`  任务。 如果您从根项目目录运行命令，则将在 _api_, _shared_, _services:shared_ and _services:webservice_ 中运行 `test` 。
如果您从 _services_  项目目录中运行命令，则仅在 _services:shared_ 和 _services:webservice_ 中执行任务。

Gradle 行为的基本规则是: 执行具有此名称的层次结构中的所有任务。仅在遍历的任何子项目中都找不到这样的任务时才抱怨。

Gradle 从当前目录开始向下查找具有给定名称的任务的层次结构并执行它们。 需要注意的一件事很重要。 Gradle 始终评估多项目构建中的每个项目并创建所有现有任务对象。
然后，根据任务名称参数和当前目录，Gradle 筛选应执行的任务。 由于 Gradle 具有 <<sharing_build_logic_between_subprojects#sec:convention_plugins_vs_cross_configuration,跨项目配置>>，因此必须在执行任何任务之前对每个项目进行评估。

使用 Gradle wrapper 时，通过从子项目目录运行 Gradle 为特定子项目执行任务的效果不佳，因为如果不在项目根目录中，则必须指定包装器脚本的路径。
例如，如果要为 _webservice_ 子项目运行 `build` 任务，并且您位于 _webservice_ 子项目目录中，则必须运行 `../../gradlew build`。 下一部分说明如何直接从项目的根目录中实现此目标。

[[sec:executing_tasks_by_fully_qualified_name]]
== 通过完全限定的名称执行任务

您可以使用任务的全限定名来执行特定子项目中的特定任务。 例如: `gradle :services:webservice:build`  将运行 `webservice` 子项目的构建任务。 任务的完全限定名称只是其项目路径加上任务名称。

项目路径具有以下模式: 它以一个可选的冒号开头，该冒号表示根项目。 根项目是路径中唯一未由其名称指定的项目。 项目路径的其余部分是用冒号分隔的项目名称序列，其中下一个项目是上一个项目的子项目。 运行 `gradle projects` 时，您可以看到项目路径，如 <<sec:identifying_project_structure,识别项目结构>> 部分所示。

这种方法适用于任何任务，因此如果您想知道特定子项目中的任务，只需使用 `tasks` 即可，例如 `gradle :services:webservice:tasks`。

无论您使用哪种技术来执行任务，Gradle 都会负责构建目标依赖的任何子项目。 您不必自己担心项目间的依赖性。 如果您对配置方式感兴趣，可以<<multi_project_builds.adoc#multi_project_builds,稍后在用户手册>>中阅读有关编写多项目构建的信息。

作为构建用户，您真正需要了解的有关多项目构建的所有信息。现在，您可以确定一个构建是否是一个多项目构建，并可以发现其结构。最后，您可以在特定子项目中执行任务。

[[sec:multiproject_build_and_test]]
== 多项目构建和测试

Java 插件的  `build` 任务通常用于编译，测试和执行单个项目的代码样式检查(如果使用了 CodeQuality 插件)。 在多项目构建中，您可能经常想在一系列项目中执行所有这些任务。 `buildNeeded` 和 `buildDependents` 任务可以对此提供帮助。

<<declaring_dependencies_between_subprojects#javadependencies_2,在此例中>>，`:services:person-service` 项目同时取决于 `:api` 和 `:shared` 项目。`:api`  项目还依赖于 `:shared` 项目。

假设您正在处理一个项目 `:api` 项目。 自进行清理以来，您一直在进行更改，但尚未构建整个项目。 您想要构建任何必要的支持 jar，但仅对已更改的项目执行代码质量和单元测试。 `build` 任务将执行此操作。

.Build and Test Single Project
====
[.multi-language-sample]
=====
.Output of **`gradle :api:build`**
----
> gradle :api:build
include::{snippetsPath}/multiproject/dependencies-java/tests/multitestingBuild.out[]
----
=====
====

如果您刚刚从版本控制系统获得了最新版本的源代码，其中包括 `:api` 依赖的其他项目中的更改，则您可能不仅要构建您依赖的所有项目，还要对其进行测试。 `buildNeeded` 任务还从 `testRuntime` 配置的项目依赖项测试所有项目。

.Build and Test Depended On Projects
====
[.multi-language-sample]
=====
.Output of **`gradle :api:buildNeeded`**
----
> gradle :api:buildNeeded
include::{snippetsPath}/multiproject/dependencies-java/tests/multitestingBuildNeeded.out[]
----
=====
====

您可能还想重构其他项目中使用的 `:api` 项目的某些部分。 如果进行这些类型的更改，仅测试 `:api` 项目是不够的，还需要测试依赖于 `:api` 项目的所有项目。 `buildDependents` 任务还测试在指定项目上具有项目依赖项的所有项目(在testRuntime配置中)。

.Build and Test Dependent Projects
====
[.multi-language-sample]
=====
.Output of **`gradle :api:buildDependents`**
----
> gradle :api:buildDependents
include::{snippetsPath}/multiproject/dependencies-java/tests/multitestingBuildDependents.out[]
----
=====
====

最后，您可能要构建和测试所有项目中的所有内容。您在根项目文件夹中运行的任何任务都将使相同的命名任务在所有子项上运行。因此，您可以运行 `gradle build` 来构建和测试所有项目。