[[integration.appendix]]
= Appendix

[[integration.appendix.xsd-schemas]]
== XML Schemas

附录的这一部分列出了与集成技术相关的 XML Schemas.

[[integration.appendix.xsd-schemas-jee]]
=== `jee` Schema

`jee` 元素处理与 Jakarta EE(Enterprise Edition) 配置相关的问题,例如查找 JNDI 对象和定义 EJB 引用.

要使用 `jee` schema 中的元素,您需要在 Spring XML 配置文件的顶部包含以下前导码. 以下代码段中的文本引用了正确的 schema,以便 `jee` 命名空间中的元素可供您使用:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:jee="http://www.springframework.org/schema/jee"
		xsi:schemaLocation="
			http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/jee https://www.springframework.org/schema/jee/spring-jee.xsd">

		<!-- bean definitions here -->

	</beans>
----

[[integration.appendix.xsd-schemas-jee-jndi-lookup]]
==== <jee:jndi-lookup/> (simple)

以下示例显示如何使用 JNDI 在没有 `jee` schema 的情况下查找数据源:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="dataSource" class="org.springframework.jndi.JndiObjectFactoryBean">
		<property name="jndiName" value="jdbc/MyDataSource"/>
	</bean>
	<bean id="userDao" class="com.foo.JdbcUserDao">
		<!-- Spring will do the cast automatically (as usual) -->
		<property name="dataSource" ref="dataSource"/>
	</bean>
----

以下示例显示如何使用 JNDI 使用 `jee` schema查找数据源:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<jee:jndi-lookup id="dataSource" jndi-name="jdbc/MyDataSource"/>

	<bean id="userDao" class="com.foo.JdbcUserDao">
		<!-- Spring will do the cast automatically (as usual) -->
		<property name="dataSource" ref="dataSource"/>
	</bean>
----

[[integration.appendix.xsd-schemas-jee-jndi-lookup-environment-single]]
==== `<jee:jndi-lookup/>` (使用单个 JNDI 环境设置)

以下示例显示如何使用 JNDI 查找没有 `jee` 的环境变量 :

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="simple" class="org.springframework.jndi.JndiObjectFactoryBean">
		<property name="jndiName" value="jdbc/MyDataSource"/>
		<property name="jndiEnvironment">
			<props>
				<prop key="ping">pong</prop>
			</props>
		</property>
	</bean>
----

以下示例显示如何使用 JNDI 使用 `jee` 查找环境变量:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<jee:jndi-lookup id="simple" jndi-name="jdbc/MyDataSource">
		<jee:environment>ping=pong</jee:environment>
	</jee:jndi-lookup>
----

[[integration.appendix.xsd-schemas-jee-jndi-lookup-environment-multiple]]
==== `<jee:jndi-lookup/>` (多个JNDI环境设置)

以下示例显示如何使用 JNDI 在没有 `jee` 的情况下查找多个环境变量:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="simple" class="org.springframework.jndi.JndiObjectFactoryBean">
		<property name="jndiName" value="jdbc/MyDataSource"/>
		<property name="jndiEnvironment">
			<props>
				<prop key="sing">song</prop>
				<prop key="ping">pong</prop>
			</props>
		</property>
	</bean>
----

以下示例显示如何使用 JNDI 通过 `jee` 查找多个环境变量:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<jee:jndi-lookup id="simple" jndi-name="jdbc/MyDataSource">
		<!-- newline-separated, key-value pairs for the environment (standard Properties format) -->
		<jee:environment>
			sing=song
			ping=pong
		</jee:environment>
	</jee:jndi-lookup>
----

[[integration.appendix.xsd-schemas-jee-jndi-lookup-complex]]
==== `<jee:jndi-lookup/>` (复杂)

以下示例显示如何使用 JNDI 使用 `jee` 查找多个环境变量:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="simple" class="org.springframework.jndi.JndiObjectFactoryBean">
		<property name="jndiName" value="jdbc/MyDataSource"/>
		<property name="cache" value="true"/>
		<property name="resourceRef" value="true"/>
		<property name="lookupOnStartup" value="false"/>
		<property name="expectedType" value="com.myapp.DefaultThing"/>
		<property name="proxyInterface" value="com.myapp.Thing"/>
	</bean>
----

以下示例显示如何使用 JNDI 在没有 `jee` 的情况下查找数据源和许多不同的属性:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<jee:jndi-lookup id="simple"
			jndi-name="jdbc/MyDataSource"
			cache="true"
			resource-ref="true"
			lookup-on-startup="false"
			expected-type="com.myapp.DefaultThing"
			proxy-interface="com.myapp.Thing"/>
----

[[integration.appendix.xsd-schemas-jee-local-slsb]]
==== `<jee:local-slsb/>` (简单)

`<jee:local-slsb/>` 元素配置对本地 EJB Stateless SessionBean 的引用.

以下示例显示如何在没有 `jee` 的情况下配置对本地 EJB Stateless SessionBean 的引用:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="simple"
			class="org.springframework.ejb.access.LocalStatelessSessionProxyFactoryBean">
		<property name="jndiName" value="ejb/RentalServiceBean"/>
		<property name="businessInterface" value="com.foo.service.RentalService"/>
	</bean>
----

以下示例显示如何使用 `jee` 配置对本地 EJB Stateless SessionBean 的引用:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<jee:local-slsb id="simpleSlsb" jndi-name="ejb/RentalServiceBean"
			business-interface="com.foo.service.RentalService"/>
----

[[integration.appendix.xsd-schemas-jee-local-slsb-complex]]
==== `<jee:local-slsb/>` (复杂)

`<jee:local-slsb/>` 元素配置对本地 EJB Stateless SessionBean 的引用.

以下示例显示如何配置对本地 EJB Stateless SessionBean 的引用以及许多不带 `jee` 的属性:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="complexLocalEjb"
			class="org.springframework.ejb.access.LocalStatelessSessionProxyFactoryBean">
		<property name="jndiName" value="ejb/RentalServiceBean"/>
		<property name="businessInterface" value="com.example.service.RentalService"/>
		<property name="cacheHome" value="true"/>
		<property name="lookupHomeOnStartup" value="true"/>
		<property name="resourceRef" value="true"/>
	</bean>
----

以下示例显示如何使用 `jee` 配置对本地 EJB Stateless SessionBean 和许多属性的引用:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<jee:local-slsb id="complexLocalEjb"
			jndi-name="ejb/RentalServiceBean"
			business-interface="com.foo.service.RentalService"
			cache-home="true"
			lookup-home-on-startup="true"
			resource-ref="true">
----

[[integration.appendix.xsd-schemas-jee-remote-slsb]]
==== <jee:remote-slsb/>

`<jee:remote-slsb/>` 元素配置对 remoteEJB Stateless SessionBean 的引用.

以下示例显示如何在不使用 `jee` 的情况下配置对远程 EJB Stateless SessionBean 的引用

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="complexRemoteEjb"
			class="org.springframework.ejb.access.SimpleRemoteStatelessSessionProxyFactoryBean">
		<property name="jndiName" value="ejb/MyRemoteBean"/>
		<property name="businessInterface" value="com.foo.service.RentalService"/>
		<property name="cacheHome" value="true"/>
		<property name="lookupHomeOnStartup" value="true"/>
		<property name="resourceRef" value="true"/>
		<property name="homeInterface" value="com.foo.service.RentalService"/>
		<property name="refreshHomeOnConnectFailure" value="true"/>
	</bean>
----

以下示例显示如何使用 `jee` 配置对远程 EJB Stateless SessionBean 的引用:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<jee:remote-slsb id="complexRemoteEjb"
			jndi-name="ejb/MyRemoteBean"
			business-interface="com.foo.service.RentalService"
			cache-home="true"
			lookup-home-on-startup="true"
			resource-ref="true"
			home-interface="com.foo.service.RentalService"
			refresh-home-on-connect-failure="true">
----

[[integration.appendix.xsd-schemas-jms]]
=== `jms` Schema

`jms` 元素处理配置与JMS相关的 bean,例如 Spring 的 <<integration.adoc#jms-mdp, Message Listener Containers>>. 这些元素在 <<integration.adoc#jms, JMS 命名空间支持>> 中详细介绍. 有关此支持和 `jms` 元素本身的完整详细信息,请参阅<<integration.adoc#jms-namespace, 该章节>>.

为了完整性,要使用 `jms` schema 中的元素,您需要在 Spring XML 配置文件的顶部包含以下前导码. 以下代码段中的文本引用了正确的 schema,以便您可以使用 `jms` 命名空间中的元素:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:jms="http://www.springframework.org/schema/jms"
		xsi:schemaLocation="
			http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/jms https://www.springframework.org/schema/jms/spring-jms.xsd">

		<!-- bean definitions here -->

	</beans>
----

[[integration.appendix.xsd-schemas-context-mbe]]
=== 使用 `<context:mbean-export/>`

<<integration.adoc#jmx-context-mbeanexport, 配置基于注解的 MBean 导出>>中详细介绍了此元素.

[[integration.appendix.xsd-schemas-cache]]
=== `cache` Schema

您可以使用 `cache` 元素来启用对 Spring 的 `@CacheEvict`, `@CachePut`,和 `@Caching` 注解的支持.
它还支持基于声明的基于 XML 的缓存. 有关详细信息,请参阅<<integration.adoc#cache-annotation-enable, 启用缓存注解>>和<<integration.adoc#cache-declarative-xml, 基于XML的声明性缓存>> .

要使用 `cache` schema 中的元素,需要在 Spring XML 配置文件的顶部包含以下前导码. 以下代码段中的文本引用了正确的 schema,以便您可以使用 `cache` 命名空间中的元素:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:cache="http://www.springframework.org/schema/cache"
		xsi:schemaLocation="
			http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/cache https://www.springframework.org/schema/cache/spring-cache.xsd">

		<!-- bean definitions here -->

	</beans>
----
