// Copyright 2018 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[getting_started]]
= 入门手册

每个人都必须从某个地方开始,如果您是 Gradle 的新手,那么这就是开始的地方.

== 开始之前

为了有效地使用 Gradle,您需要了解 Gradle 是什么并了解其一些基本概念.因此,在您开始认真使用 Gradle 之前,我们强烈建议您阅读 <<what_is_gradle#what_is_gradle>>.

即使您有使用 Gradle 的经验,我们还是建议您阅读 <<what_is_gradle#five_things>>,因为它可以消除一些常见的误解.

[[gs:installation]]
== 安装

如果你只想运行一个已存在 Gradle 构建，如果此构建有 <<gradle_wrapper#gradle_wrapper,Gradle Wrapper>>，则您无需安装 Gradle，可以通过根目录中的 _gradlew_ 或 _gradlew.bat_ 文件构建。你只需要确保你的系统满足  <<installation#sec:prerequisites,Gradle 的要求>>

Android Studio 已经自带了 Gradle 的安装，所以在这种情况下你不需要单独安装 Gradle。

为了创建一个新的构建或向现有的构建添加一个Wrapper，这时，您需要 <<installation#installation,按照以下方法>> 安装 Gradle。注意，除了下面描述的方法之外，可能还有其他安装 Gradle 的方法，因为我们几乎不可能跟踪所有的包管理器。

[[try_gradle]]
== Gradle 尝鲜

了解 Gradle 最好的方法就是使用它，所以一旦你安装了 Gradle，可以试试入门教程:

 * link:../samples/sample_building_android_apps.html[构建 Android apps]
 * link:../samples/sample_building_java_applications.html[构建 Java 应用程序]
 * link:../samples/sample_building_java_libraries.html[构建 Java 库]
 * link:../samples/sample_building_groovy_applications.html[构建 Groovy 应用程序]
 * link:../samples/sample_building_groovy_libraries.html[构建 Groovy 库]
 * link:../samples/sample_building_scala_applications.html[构建 Scala 应用程序]
 * link:../samples/sample_building_scala_libraries.html[构建 Scala 库]
 * link:../samples/sample_building_kotlin_applications.html[构建 Kotlin JVM 应用程序]
 * link:../samples/sample_building_kotlin_libraries.html[构建 Kotlin JVM 库]
 * link:../samples/sample_building_cpp_applications.html[构建 C++ 应用程序]
 * link:../samples/sample_building_cpp_libraries.html[构建 C++ 库]
 * link:../samples/sample_building_swift_applications.html[构建 Swift 应用程序]
 * link:../samples/sample_building_swift_libraries.html[构建 Swift 库]
 * link:https://scans.gradle.com/[创建构建扫描]

这里有一些可用的示例： link:../samples/index.html[samples pages].

== 命令行 vs IDEs

有些人是铁杆的命令行用户，而另一些人则使用 IDE。也有许多人可以使用两者，Gradle 将同等对待。 Gradle 得到了 <<third_party_integration#ides,几个主要的 IDEs>> 的支持，所有可以通过 <<command_line_interface#command_line_interface,命令行>> 完成的工作都可以通过 <<third_party_integration.adoc#embedding,Tooling API>> 提供给 IDEs.

Android Studio 和 IntelliJ IDEA 用户在编辑他们时应该考虑使用 <<kotlin_dsl#kotlin_dsl,Kotlin DSL 构建脚本>>，以获得高级 IDE 支持。

== 执行 Gradle 构建

如果您遵循 <<#try_gradle,上面链接的>> 教程中的任何一个，您将执行一个 Gradle 构建。但是，如果你在没有任何说明的情况下得到一个Gradle 构建，你该怎么办呢?

以下是一些有用的步骤:

 1. 确定项目是否有 Gradle wrapper，<<gradle_wrapper#sec:using_wrapper,如果有就使用它>>  —— 当包装器可用时，IDEs 默认使用它。
 2. 发现项目结构
+
要么用 IDE 导入构建，要么从命令行运行 `gradle projects`。如果只列出根项目，则为单个项目构建。否则它就是<<intro_multi_project_builds#intro_multi_project_builds,一个多项目构建>>。
 3. 查找可以运行的 task.
+
如果您已经将构建导入到 IDE 中，那么您应该可以访问显示所有可用任务的视图。从命令行运行 `gradle tasks`。
 4. 通过 `gradle help --task <taskname>` 了解更多关于任务的信息.
+
`help` 任务可以显示关于任务的额外信息，包括哪些项目包含该任务以及该任务支持哪些选项。
 5. 运行您感兴趣的任务.
+
许多基于约定的构建与 Gradle 的 <<base_plugin#sec:base_tasks,生命周期任务>> 集成在一起，所以当你在构建中没有更具体的事情要做时，可以使用这些。例如，大多数构建都有 `clean`, `check`, `assemble` 和 `build` 任务。
+
从命令行中，通过运行 `gradle <taskname>` 来执行特定的任务。您可以在 <<command_line_interface#command_line_interface,对应用户手册章节>> 了解更多关于命令行执行的信息。如果您正在使用IDE，请查看其文档，了解如何运行任务。

Gradle 构建通常遵循项目结构和任务的标准约定，所以如果你熟悉其他相同类型的构建——如 Java、Android 或原生构建——那么构建的文件和目录结构应该熟悉，以及许多任务和项目属性。

对于特定的构建或那些具有重要自定义的构建，理想情况下，您应该能够访问关于如何运行构建以及您可以配置哪些<<build_environment#build_environment,build 属性>>  的文档。

== 编写 Gradle 构建

学习创建和维护 Gradle 构建是一个艰难的过程，它需要一点时间。我们建议您从适合您的项目的核心插件和它们的约定开始，然后随着您对该工具的了解越来越多，逐渐加入定制。

以下是掌握 Gradle 的一些有用信息的第一步:

 1. 尝试一两个 <<#try_gradle,基本的教程>>，看看 Gradle 的构建是什么样子的，特别是那些与你工作的项目类型相匹配的(Java，原生，Android 等)。
 2. 确保您已经阅读了 <<what_is_gradle#five_things,关于 Gradle 您需要知道的 5 件事>>!
 3. 了解Gradle构建的基本元素: <<tutorial_using_tasks#sec:projects_and_tasks,projects>>, <<more_about_tasks#more_about_tasks,tasks>>, 和 <<working_with_files#working_with_files,file API>>.
 4. 如果您正在构建基于 JVM 的软件, 请务必阅读 <<building_java_projects#building_java_projects,Building Java & JVM projects>> 和 <<java_testing#java_testing,Testing in Java & JVM projects>> 中有关这些类型项目的详细信息。.
 5. 熟悉 <<plugin_reference#plugin_reference,核心插件>>，因为它们提供了许多开箱即用的有用功能。
 6. 学习如何 <<authoring_maintainable_build_scripts#authoring_maintainable_build_scripts,编写可维护的构建脚本>> 和 <<organizing_gradle_projects#organizing_gradle_projects,最好地组织你的 Gradle 项目>>.

用户手册包含了许多其他有用的信息，你可以在链接中找到各种 Gradle 特性的示例。 link:../samples/index.html[samples pages].。

== 在 Gradle 中集成第三方工具

Gradle 具有很高的灵活性，意味着它很容易与其他工具一起工作，比如我们在 <<third_party_integration#third_party_integration,Gradle & Third-party Tools>> 页面中列出的那些工具。

有两种主要的集成模式::

 * 一个驱动 Gradle 的工具 — 通过使工具可以来提取关于构建的信息并运行 gradle — 例如 <<third_party_integration.adoc#embedding,Tooling API>>
 * Gradle 通过第三方工具的 api 为工具调用或生成信息——这通常是通过插件和自定义任务类型完成的。

基于 java api 的工具通常很容易集成。你可以在 Gradle 的 https://plugins.gradle.org/[plugin portal] 上找到许多这样的集成。
