// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[installation]]
= 安装 gradle

您可以在 Linux，macOS 或 Windows 上安装 Gradle 构建工具. 本文档覆盖了使用像 SDKMAN!,Homebrew 这样的软件包管理器以及手动安装

建议使用 <<gradle_wrapper.adoc#sec:upgrading_wrapper,Gradle Wrapper>> 升级 Gradle.

您可以在 link:{website}/releases[releases page] 上找到所有版本及其校验.

[[sec:prerequisites]]
== 要求

Gradle 可在所有主要操作系统上运行，并且仅需要 link:{jdkDownloadUrl}[Java Development Kit] 版本 {minJdkVersion} 或更高版本即可运行.要进行检查，请运行 `java -version`.您应该会看到以下内容:

----
❯ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
----

Gradle 附带了自己的 Groovy 库，因此不需要安装 Groovy. Gradle 将忽略任何现有的 Groovy 安装.

Gradle 使用在路径中找到的任何 JDK.另外，您可以将 `JAVA_HOME` 环境变量设置为指向所需 JDK 的安装目录.

<<compatibility.adoc#compatibility,请参阅 Java，Groovy，Kotlin 和 Android 的完整兼容性说明.>>

== 使用软件包管理器进行安装

link:http://sdkman.io[SDKMAN!] 是用于在大多数类 Unix 系统(macOS，Linux，Cygwin，Solaris 和 FreeBSD)上管理多个软件开发套件的并行版本的工具.我们部署并维护可从 SDKMAN! 获得的版本.

----
❯ sdk install gradle
----

link:http://brew.sh[Homebrew]  是 "macOS缺少的软件包管理器".

----
❯ brew install gradle
----

可以使用其他软件包管理器，但是它们分发的 Gradle 版本不受 Gradle, Inc. 的控制.Linux 软件包管理器可能会分发与正式版本相比不兼容或不完整的 Gradle 修改版(从 SDKMAN! 或更低版本提供).

<<#sec:installation_next_steps,↓ 下一步>>


== 手动安装

=== Step 1. link:{website}/releases[下载] 最新的 Gradle 发行版

发行的ZIP文件有两种形式:

 - Binary-only (bin): 仅有可运行的二进制文件
 - Complete (all) with docs and sources : 附带文档和源码

如需使用旧版本，请参阅 link:{website}/releases[releases page]

=== Step 2. 解压

==== Linux & MacOS 用户

在您选择的目录中解压缩发行版zip文件，例如:

[subs="attributes"]
----
❯ mkdir /opt/gradle
❯ unzip -d /opt/gradle gradle-{gradleVersion}-bin.zip
❯ ls /opt/gradle/gradle-{gradleVersion}
LICENSE  NOTICE  bin  README  init.d  lib  media
----

==== Microsoft Windows 用户

使用文件资源管理器创建一个新目录 `C:\Gradle`.

打开第二个 **File Explorer** 窗口，然后转到下载 Gradle 发行版的目录.双击ZIP存档以显示内容.将内容文件夹 `gradle-{gradleVersion}` 拖到新创建的 `C:\Gradle` 文件夹中.

另外，您可以使用压缩工具将 Gradle 发行版 ZIP 解压至 `C:\Gradle`.

=== Step 3. 配置系统环境

要运行 Gradle，从 Gradle 网站到解压缩文件的路径必须在您的终端路径上.对于每个操作系统，执行此操作的步骤都不同.

==== Linux & MacOS 用户

配置 `PATH` 环境变量以包含解压后的 Gradle 的 `bin` 目录，例如:

[subs="attributes"]
----
❯ export PATH=$PATH:/opt/gradle/gradle-{gradleVersion}/bin
----

或者，您也可以添加环境变量 `GRADLE_HOME` 并将其指向解压后的文件夹.可以将 `__$GRADLE_HOME__/bin` 添加到 `PATH`，而不是将特定版本的 `Gradle` 添加到 `PATH`.
升级到其他版本的 `Gradle` 时，只需更改 `GRADLE_HOME` 环境变量即可.

==== Microsoft Windows 用户

在文件资源管理器中，右键单击 "此电脑(或我的电脑)" 图标，然后单击 `属性`→`高级系统设置`→`环境变量`.

在 "系统变量" 下，选择 `Path`，然后单击 `编辑` .为 `C:\Gradle\gradle-{gradleVersion}\bin` 添加一个条目.单击确定保存.

或者，您也可以添加环境变量 `GRADLE_HOME` 并将其指向解压后的文件夹.可以将 `__%GRADLE_HOME%__/bin` 添加到您的 `Path` 中，而不是将特定版本的 `Gradle` 添加到 `Path` 中.升级到其 他版本的 `Gradle` 时，只需更改 `GRADLE_HOME` 环境变量即可.

<<#sec:installation_next_steps,↓ 下一步>>


[[sec:running_and_testing_your_installation]]
== 验证安装

打开控制台(或 Windows 命令提示符)并运行 `gradle -v` 以运行 gradle 并显示版本，例如:

[subs="attributes"]
----
❯ gradle -v

------------------------------------------------------------
Gradle {gradleVersion}
------------------------------------------------------------

(environment specific information)

----

如果遇到任何麻烦，请参阅 <<troubleshooting.adoc#sec:troubleshooting_installation,section on troubleshooting installation>> 部分.

您可以通过下载 SHA-256 文件(可从 link:{website}/releases[releases page] 中获得)并按照以下 <<gradle_wrapper.adoc#sec:verification,verification instructions>> Gradle 发行版的完整性.

[[sec:installation_next_steps]]
== 下一步

现在您已经安装了 Gradle，请使用以下资源进行入门:

* 按照 link:../samples/index.html[step-by-step samples] 教程创建第一个 Gradle 项目.
* 注册 link:{website}/training/intro-to-gradle/[Gradle 现场入门培训] 与资深工程师交流.
* 了解如何通过 <<command_line_interface.adoc#command_line_interface,命令行接口>> 完成常见任务.
* <<build_environment.adoc#build_environment,配置 Gradle 环境>>，例如使用e HTTP 代理下载依赖项.
* 订阅 link:https://newsletter.gradle.com/[Gradle Newsletter] 以获取每月发布和社区更新.