[[appendix.configuration-metadata.format]]
== Metadata 格式
配置元数据文件位于 jars 文件中的 `META-INF/spring-configuration-metadata.json` .  它们使用一个具有 "`groups`" 或 "`properties`" 分类节点的简单 JSON 格式,并将其他值提示归类为 "hints",如以下示例所示:

[source,json,indent=0,subs="verbatim"]
----
	{"groups": [
		{
			"name": "server",
			"type": "org.springframework.boot.autoconfigure.web.ServerProperties",
			"sourceType": "org.springframework.boot.autoconfigure.web.ServerProperties"
		},
		{
			"name": "spring.jpa.hibernate",
			"type": "org.springframework.boot.autoconfigure.orm.jpa.JpaProperties$Hibernate",
			"sourceType": "org.springframework.boot.autoconfigure.orm.jpa.JpaProperties",
			"sourceMethod": "getHibernate()"
		}
		...
	],"properties": [
		{
			"name": "server.port",
			"type": "java.lang.Integer",
			"sourceType": "org.springframework.boot.autoconfigure.web.ServerProperties"
		},
		{
			"name": "server.address",
			"type": "java.net.InetAddress",
			"sourceType": "org.springframework.boot.autoconfigure.web.ServerProperties"
		},
		{
			  "name": "spring.jpa.hibernate.ddl-auto",
			  "type": "java.lang.String",
			  "description": "DDL mode. This is actually a shortcut for the \"hibernate.hbm2ddl.auto\" property.",
			  "sourceType": "org.springframework.boot.autoconfigure.orm.jpa.JpaProperties$Hibernate"
		}
		...
	],"hints": [
		{
			"name": "spring.jpa.hibernate.ddl-auto",
			"values": [
				{
					"value": "none",
					"description": "Disable DDL handling."
				},
				{
					"value": "validate",
					"description": "Validate the schema, make no changes to the database."
				},
				{
					"value": "update",
					"description": "Update the schema if necessary."
				},
				{
					"value": "create",
					"description": "Create the schema and destroy previous data."
				},
				{
					"value": "create-drop",
					"description": "Create and then destroy the schema at the end of the session."
				}
			]
		}
	]}
----

每个  "`property`"  都是用户使用给定值指定的配置项.  例如,可以在 `application.properties`/`application.yaml` 中指定 `server.port` 和 `server.address`,如下所示:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	server:
	  port: 9090
	  address: 127.0.0.1
----

"`groups`" 是高级别的节点,它们本身不指定一个值,但为 properties 提供一个有上下文关联的分组.  例如,`server.port` 和 `server.address` 属性是 `server` 组的一部分.

NOTE: 不需要每个  "`property`" 都有一个 "`group`".  一些属性可以以自己的形式存在.

最后, "`hints`" 是用于帮助用户配置给定属性的其他信息.  例如,当开发人员配置 `spring.jpa.hibernate.ddl-auto` 属性时,工具可以使用提示 `none`, `validate`, `update`, `create` 和 `create-drop` 值 .

[[appendix.configuration-metadata.format.group]]
=== Group 属性
`groups` 数组包含的 JSON 对象可以由以下属性组成:

[cols="1,1,4"]
|===
| 名称 | 类型 | 目的

| `name`
| String
| 组的全名.  此属性是必需的.

| `type`
| String
| 组数据类型的类名.  group 数据类型的类名.例如,如果 group 是基于一个被 `@ConfigurationProperties` 注解的类,该属性将包含该类的全限定名.如果基于一个 `@Bean` 方法,它将是该方法的返回类型.如果该类型未知,则该属性将被忽略

| `description`
| String
| 一个简短的 group 描述,用于展示给用户.如果没有可用描述,该属性将被忽略.推荐使用一个简短的段落描述,第一行提供一个简洁的总结,最后一行以句号结尾

| `sourceType`
| String
| 贡献该组的来源类名.例如,如果组基于一个被 `@ConfigurationProperties` 注解的 `@Bean` 方法,该属性将包含 `@Configuration` 类的全限定名,该类包含此方法.如果来源类型未知,则该属性将被忽略

| `sourceMethod`
| String
| 贡献该组的方法的全名(包含括号及参数类型).例如,被 `@ConfigurationProperties` 注解的 `@Bean` 方法名.如果源方法未知,该属性将被忽略
|===

[[appendix.configuration-metadata.format.property]]
=== Property 属性
`properties` 数组中包含的 JSON 对象可由以下属性构成:

[cols="1,1,4"]
|===
| 名称 | 类型 | 目的

| `name`
| String
| 属性的全名.  名称以小写的句点分隔(例如,`server.address`) .  此属性是必需的.

| `type`
| String
| property 数据类型的类名(例如,`java.lang.String`) ,还具有完整的泛型类型(例如,`java.util.Map<java.lang.String,com.example.MyEnum>`) .
该属性可以用来指导用户他们可以输入值的类型.为了保持一致,原生类型使用它们的包装类代替(例如,`boolean`  变为 `java.lang.Boolean`) .  注意,这个类可能是个从一个字符串转换而来的复杂类型.如果类型未知则该属性会被忽略

| `description`
| String
| 一个简短的组的描述,用于展示给用户.如果没有描述可用则该属性会被忽略.推荐使用一个简短的段落描述,开头提供一个简洁的总结,最后一行以 `.` 结束

| `sourceType`
| String
| contributed property 的来源类名.例如,如果 property 来自一个被 `@ConfigurationProperties` 注解的类,该属性将包括该类的全限定名.如果来源类型未知则该属性会被忽略

| `defaultValue`
| Object
| 当 property 没有定义时使用的默认值.如果 property 类型是个数组则该属性也可以是个数组.如果默认值未知则该属性会被忽略

| `deprecation`
| Deprecation
| 指定该 property 是否过期.如果该字段没有过期或该信息未知则该属性会被忽略.  下表提供了有关  `deprecation` 属性的更多详细信息.
|===

每个 `properties` 元素的 `deprecation` 属性中包含的JSON对象可以包含以下属性:

[cols="1,1,4"]
|===
| 名称 | 类型 | 目的

| `level`
| String
| 弃用级别,可以是 `warning`(默认) 或 `error`.  当某个属性具有 `warning` 级别时,它仍应绑定在环境中.  但是,当它具有 `error` 级别时,该属性将不再受管理且未绑定.

| `reason`
| String
| 简短描述了该资源被弃用的原因.如果没有理由可以省略.建议描述是一个简短的段落,第一行提供简明扼要的摘要.说明中的最后一行应以(`.`) 结尾.

| `replacement`
| String
| 正在替换此不推荐使用的属性的属性的全名.如果没有替换此属性,可以省略.
|===

NOTE: 在 Spring Boot 1.3 之前,可以使用单个  `deprecated` 使用的布尔属性来代替 `deprecation` 元素.  这仍然以不推荐的方式支持,不应再使用.如果没有理由和替换可用, `deprecation` 应该设置一个空的对象.

也可以在代码中以声明方式指定弃用,方法是将 `@DeprecatedConfigurationProperty` 注解添加到暴露弃用属性的 getter 中.  例如,假设 `my.app.target` 属性令人困惑,并将其重命名为 `app.app.name`.  以下示例显示了如何处理这种情况:

include::code:MyProperties[]

NOTE: 无法设置 `level`.  由于代码仍在处理该属性,因此始终 `warning` .

前面的代码确保不推荐使用的属性仍然有效(将其委托给幕后的 `name` 属性) .  一旦可以从公共 API 中删除 `getTarget` 和 `setTarget` 方法,元数据中的自动弃用提示也将消失.
如果要保留提示,请添加具有 `error` 级别的手动元数据,以确保仍然向用户通知该属性.  当提供 `replacement` 时,这样做特别有用.

[[appendix.configuration-metadata.format.hints]]
=== Hint 属性
`hints` 数组中包含的 JSON 对象可以包含以下属性:

[cols="1,1,4"]
|===
| 名称 | 类型 | 目的

| `name`
| String
| 该提示所引用的属性的全名.  名称采用小写的句点分隔形式(例如 `spring.mvc.servlet.path`) .  如果属性引用映射(例如 `system.contexts`) ,则提示将应用于映射的键(`system.contexts.keys`) 或映射的值(`system.contexts.values`) . 此属性是必需的.

| `values`
| ValueHint[]
| 由 `ValueHint` 对象定义的有效值列表(如下表所述) .  每个条目都定义该值,并且可以具有描述.

| `providers`
| ValueProvider[]
| 由 `ValueProvider` 对象定义的提供者列表(在本文档的后面介绍) .  每个条目定义提供者的名称及其参数(如果有) .
|===

每个  `hint` 元素的 `values` 属性中包含的 JSON 对象可以包含下表中描述的属性:

[cols="1,1,4"]
|===
| 名称 | 类型 | 目的

| `value`
| Object
| 提示所引用元素的有效值.  如果属性的类型是数组,则它也可以是值的数组.  此属性是必需的.

| `description`
| String
| 可以显示给用户的值的简短描述.  如果没有可用的描述,则可以省略.  建议使用简短的描述,第一行提供简要的摘要.  说明中的最后一行应以句点(`.`) 结尾.
|===

每个 `hint` 元素的 `providers` 属性中包含的 JSON 对象可以包含下表中描述的属性:

[cols="1,1,4"]
|===
| 名称 | 类型 | 目的

| `name`
| String
| 用于为提示所引用的元素提供附加内容帮助的提供者的名称.

| `parameters`
| JSON object
| provider 支持的任何其他参数(有关更多详细信息,请参阅 provider 的文档) .
|===

[[appendix.configuration-metadata.format.repeated-items]]
=== 重复的元数据项
具有相同 "`property`" 和 "`group`" 名称的对象可以在元数据文件中多次出现.  例如,您可以将两个单独的类绑定到同一前缀,每个类具有可能重叠的属性名称.  虽然相同的名称多次出现在元数据中应该不常见,但元数据的使用者应注意确保它们支持该名称.
