[[appendix.configuration-metadata.manual-hints]]
== 提供手动提示
为了改善用户体验并进一步帮助用户配置给定属性,您可以提供其他元数据,这些元数据可以:

* 描述属性的潜在值列表.
* 关联提供者,以将定义良好的语义附加到属性,以便工具可以根据项目的上下文来发现潜在值的列表.

[[appendix.configuration-metadata.manual-hints.value-hint]]
=== Value Hint
每个提示的 `name` 属性是指属性的名称.  在 <<configuration-metadata#appendix.configuration-metadata.format,前面显示的初始示例>>中,我们为 `spring.jpa.hibernate.ddl-auto` 属性提供了五个值: `none`, `validate`, `update`, `create`, 和 `create-drop`.  每个值也可以具有描述.

如果您的属性属于 `Map` 类型,则可以提供键和值的提示(但不提供 map 本身的提示) .  特殊的 `.keys` 和 `.values` 后缀必须分别引用键和值.

假设 `my.contexts` 将 `String` 值映射到整数，如以下示例所示：

假设有一个 `my.contexts` 的 Map<String,Integer>,如以下示例所示:

include::code:MyProperties[]

String (在此示例中) 为 `sample1` 和 `sample2`.  为了为 key 提供其他内容提示,您可以将以下 JSON <<configuration-metadata#appendix.configuration-metadata.annotation-processor.adding-additional-metadata,添加到模块的手动元数据>>中:

[source,json,indent=0,subs="verbatim"]
----
	{"hints": [
		{
			"name": "my.contexts.keys",
			"values": [
				{
					"value": "sample1"
				},
				{
					"value": "sample2"
				}
			]
		}
	]}
----

TIP: 我们建议您对这两个值使用 `Enum`.  如果您的 IDE 支持,这是迄今为止最有效的自动完成方法.

[[appendix.configuration-metadata.manual-hints.value-providers]]
=== Value Providers

Providers  是一种将语义附加到属性的强有力的方法,我们将定义可以用于您自己的提示的官方 Providers.  但是,您最喜欢的 IDE 可能只实现其中一些,也可能没有实现.

NOTE: 由于这是一项新功能,IDE 供应商必须赶上它的工作方式.  采用时间自然会有所不同.

下表总结了受支持的 provider 的列表:

[cols="2,4"]
|===
| 名字 | 描述

| `any`
| 允许提供任何附加值.

| `class-reference`
| 自动完成项目中可用的类.  通常受 `target` 参数指定的基类的约束.

| `handle-as`
| 如同按强制  `target`  参数定义的类型定义属性一样处理属性.

| `logger-name`
| 自动完成有效的记录器名称和  <<features#features.logging.log-groups,记录器组>>.  通常,可以自动完成当前项目中可用的包和类名以及定义的组. .

| `spring-bean-reference`
| 自动完成当前项目中的可用 bean 名称.  通常受 `target` 参数指定的基类的约束.

| `spring-profile-name`
| 自动完成项目中可用的 Spring profile 名称.
|===

TIP: 对于给定的属性,只有一个 provider 可以处于 active 状态,但是如果它们都可以通过某种方式管理该属性,则可以指定多个 provider .  确保将最有用的 provider 放在首位,因为 IDE 必须使用它可以处理的JSON部分中的第一个.  如果不支持给定属性的 provider ,则也不提供特殊的内容帮助.

[[appendix.configuration-metadata.manual-hints.value-providers.any]]
==== Any

这个特殊的 provider 允许提供任何其他值.  如果支持,则应基于属性类型进行常规值验证.

如果您具有值列表,并且任何其他值应视为有效,则通常使用此 provider .

以下示例提供了 `system.state` 的自动完成值的 `on` 和 `off`:

[source,json,indent=0,subs="verbatim"]
----
	{"hints": [
		{
			"name": "system.state",
			"values": [
				{
					"value": "on"
				},
				{
					"value": "off"
				}
			],
			"providers": [
				{
					"name": "any"
				}
			]
		}
	]}
----

注意,在前面的示例中,还允许任何其他值.

[[appendix.configuration-metadata.manual-hints.value-providers.class-reference]]
==== Class Reference
**类引用**  provider 自动完成项目中可用的类.  此 provider 支持以下参数:

[cols="1,1,2,4"]
|===
| 参数 | 类型 | 默认值 | 描述

| `target`
| `String` (`Class`)
| _none_
| 应分配给所选值的类的完全限定名称.  通常用于过滤掉非候选类.  请注意,可以通过暴露具有适当上限的类来由类型本身提供此信息.

| `concrete`
| `boolean`
| true
| 指定是否仅将具体类视为有效候选者.
|===

以下元数据片段对应于标准 `server.servlet.jsp.class-name` 属性,该属性定义了要使用的 `JspServlet` 类名称:

[source,json,indent=0,subs="verbatim"]
----
	{"hints": [
		{
			"name": "server.servlet.jsp.class-name",
			"providers": [
				{
					"name": "class-reference",
					"parameters": {
						"target": "jakarta.servlet.http.HttpServlet"
					}
				}
			]
		}
	]}
----

[[appendix.configuration-metadata.manual-hints.value-providers.handle-as]]
==== Handle As
**handle-as**  provider 使您可以将属性的类型替换为更高级的类型.  当该属性具有 `java.lang.String` 类型时,通常会发生这种情况,因为您不希望配置类依赖于可能不在类路径中的类.  此 provider 支持以下参数:

[cols="1,1,2,4"]
|===
| 参数 | 类型 | 默认值 | 描述

| **`target`**
| `String` (`Class`)
| _none_
| 要为属性考虑的类型的标准名称.  此参数是必需的.
|===

可以使用以下类型:

* 任何 `java.lang.Enum`: 列出属性的可能值.  (我们建议使用 `Enum` 类型定义属性,因为 IDE 不需要其他提示即可自动完成值)
* `java.nio.charset.Charset`: 支持字符集/编码值(例如 `UTF-8`) 的自动完成
* `java.util.Locale`: 语言环境的自动完成(例如 `en_US`)
* `org.springframework.util.MimeType`: 支持内容类型值(例如 `text/plain`) 的自动完成
* `org.springframework.core.io.Resource`: 支持自动完成 Spring 资源抽象以引用文件系统或类路径上的文件(例如 `classpath:/sample.properties`)

TIP: 如果可以提供多个值,请使用 `Collection` 或 `Array` 类型向IDE讲解.

以下元数据片段对应于标准 `spring.liquibase.change-log` 属性,该属性定义了要使用的更改日志的路径.  实际上,它在内部用作 `org.springframework.core.io.Resource`,但不能这样暴露,因为我们需要保留原始的 String 值以将其传递给 Liquibase API.

[source,json,indent=0,subs="verbatim"]
----
	{"hints": [
		{
			"name": "spring.liquibase.change-log",
			"providers": [
				{
					"name": "handle-as",
					"parameters": {
						"target": "org.springframework.core.io.Resource"
					}
				}
			]
		}
	]}
----

[[appendix.configuration-metadata.manual-hints.value-providers.logger-name]]
==== Logger Name
**logger-name** provider 会自动完成有效的记录器名称和 <<features#features.logging.log-groups,记录器组>>.  通常,可以自动完成当前项目中可用的程序包和类名.  如果启用了组(默认) ,并且在配置中标识了自定义记录程序组,则应为其提供自动完成功能.  特定的框架可能还具有其他可以支持的魔法值记录器名称.

此 provider 支持以下参数:

[cols="1,1,2,4"]
|===
| 参数 | 类型 | 默认值 | 描述

| `group`
| `boolean`
| `true`
| 指定是否应考虑已知组.
|===

由于记录器名称可以是任意名称,因此该 provider 应允许使用任何值,但可以突出显示项目的类路径中不可用的有效程序包和类名称.

以下元数据片段对应于标准 `logging.level` 属性.  键是记录器名称,其值对应于标准日志级别或任何自定义级别.  当 Spring Boot 开箱即用地定义了一些记录器组时,已经为它们添加了专用的值提示.

[source,json,indent=0,subs="verbatim"]
----
	{"hints": [
		{
			"name": "logging.level.keys",
			"values": [
				{
					"value": "root",
					"description": "Root logger used to assign the default logging level."
				},
				{
					"value": "sql",
					"description": "SQL logging group including Hibernate SQL logger."
				},
				{
					"value": "web",
					"description": "Web logging group including codecs."
				}
			],
			"providers": [
				{
					"name": "logger-name"
				}
			]
		},
		{
			"name": "logging.level.values",
			"values": [
				{
					"value": "trace"
				},
				{
					"value": "debug"
				},
				{
					"value": "info"
				},
				{
					"value": "warn"
				},
				{
					"value": "error"
				},
				{
					"value": "fatal"
				},
				{
					"value": "off"
				}

			],
			"providers": [
				{
					"name": "any"
				}
			]
		}
	]}
----

[[appendix.configuration-metadata.manual-hints.value-providers.spring-bean-reference]]
==== Spring Bean Reference
**spring-bean-reference** provider 自动完成在当前项目的配置中定义的 bean.  此 provider 支持以下参数:

[cols="1,1,2,4"]
|===
| 参数 | 类型 | 默认值 | 描述

| `target`
| `String` (`Class`)
| _none_
| 应分配给候选者的Bean类的完全限定名称.  通常用于过滤掉非候选 bean.
|===

以下元数据片段对应于标准 `spring.jmx.server` 属性,该属性定义了要使用的 `MBeanServer` bean 的名称:

[source,json,indent=0,subs="verbatim"]
----
	{"hints": [
		{
			"name": "spring.jmx.server",
			"providers": [
				{
					"name": "spring-bean-reference",
					"parameters": {
						"target": "javax.management.MBeanServer"
					}
				}
			]
		}
	]}
----

NOTE: binder 不会自动装配日这些元数据,如果提供了该提示,则仍需要使用 `ApplicationContext` 将 Bean 名称转换为实际的 Bean 引用. .

[[appendix.configuration-metadata.manual-hints.value-providers.spring-profile-name]]
==== Spring Profile Name
**spring-profile-name** provider 自动完成在当前项目的配置中定义的 Spring profile.

以下元数据片段对应于标准 `spring.profiles.active` 属性,该属性定义了要启用的 Spring profile 的名称:

[source,json,indent=0,subs="verbatim"]
----
	{"hints": [
		{
			"name": "spring.profiles.active",
			"providers": [
				{
					"name": "spring-profile-name"
				}
			]
		}
	]}
----
