[[servlet-jackson]]
= Jackson 支持

Spring Security 提供了 Jackson 持久化支持与 Spring Security 相关的类.  在使用分布式会话(即会话复制,Spring Session 等) 时,这可以提高序列化与 Spring Security 相关的类的性能.

要使用它,请使用 `ObjectMapper` 将 `SecurityJackson2Modules.getModules(ClassLoader)` 注册为 https://wiki.fasterxml.com/JacksonFeatureModules[Jackson Modules].

====
[source,java]
----
ObjectMapper mapper = new ObjectMapper();
ClassLoader loader = getClass().getClassLoader();
List<Module> modules = SecurityJackson2Modules.getModules(loader);
mapper.registerModules(modules);

// ... use ObjectMapper as normally ...
SecurityContext context = new SecurityContextImpl();
// ...
String json = mapper.writeValueAsString(context);
----
====

[NOTE]
====
以下 Spring Security 模块提供 Jackson 支持:

- spring-security-core ({security-api-url}org/springframework/security/jackson2/CoreJackson2Module.html[`CoreJackson2Module`])
- spring-security-web ({security-api-url}org/springframework/security/web/jackson2/WebJackson2Module.html[`WebJackson2Module`], {security-api-url}org/springframework/security/web/jackson2/WebServletJackson2Module.html[`WebServletJackson2Module`], {security-api-url}org/springframework/security/web/server/jackson2/WebServerJackson2Module.html[`WebServerJackson2Module`])
- <<oauth2client, spring-security-oauth2-client>> ({security-api-url}org/springframework/security/oauth2/client/jackson2/OAuth2ClientJackson2Module.html[`OAuth2ClientJackson2Module`])
- spring-security-cas ({security-api-url}org/springframework/security/cas/jackson2/CasJackson2Module.html[`CasJackson2Module`])
====