[[servlet-localization]]
= 国际化

Spring Security 支持本地化最终用户可能会看到的异常消息.  如果您的应用程序是为说英语的用户设计的,则您无需执行任何操作,因为默认情况下,所有安全消息均以英语显示.
如果您需要支持其他语言环境,则本节包含您需要了解的所有内容.

可以对所有异常消息进行本地化,包括与身份验证失败和访问被拒绝(授权失败) 有关的消息.  针对开发人员或系统部署人员的异常和日志消息(包括不正确的属性,违反接口合同,使用不正确的构造函数,启动时间验证,调试级别的日志记录) 未本地化,而是在 Spring Security 的代码中以英文进行了硬编码.

在 `spring-security-core-xx.jar` 中,您将找到 `org.springframework.security` 包,该包反过来包含 `messages.properties` 文件以及某些通用语言的本地化版本.  由于 Spring Security 类实现了 Spring 的 `MessageSourceAware` 接口,并希望消息解析器在应用程序上下文启动时被注入依赖,因此应该由 `ApplicationContext` 引用.  通常,您要做的就是在应用程序上下文中注册一个 bean 来引用消息.  一个例子如下所示:

====
[source,xml]
----
<bean id="messageSource"
	class="org.springframework.context.support.ReloadableResourceBundleMessageSource">
<property name="basename" value="classpath:org/springframework/security/messages"/>
</bean>
----
====

`messages.properties` 是根据标准资源包命名的,表示 Spring Security 消息支持的默认语言.  该默认文件为英文.

如果希望自定义 `messages.properties` 文件或支持其他语言,则应复制该文件,进行相应的重命名,然后在上述 bean 定义中注册它.  此文件中没有大量的消息密钥,因此不应将本地化视为主要举措.  如果您确实对此文件进行了本地化,请考虑通过记录 JIRA 任务并附加适当命名的 `messages.properties` 本地化版本与社区共享您的工作.

Spring Security 依靠 Spring 的本地化支持来实际查找适当的消息.  为了使它起作用,您必须确保来自传入请求的语言环境存储在 Spring 的 `org.springframework.context.i18n.LocaleContextHolder` 中.  Spring MVC 的 `DispatcherServlet` 自动为您的应用程序执行此操作,但是由于在此之前调用了 Spring Security 的过滤器,因此需要在调用过滤器之前将 `LocaleContextHolder` 设置为包含正确的 `Locale`.
您可以自己在过滤器中执行此操作(该过滤器必须位于 `web.xml` 中的 Spring Security 过滤器之前) ,也可以使用 Spring 的 `RequestContextFilter`.  请参阅 Spring Framework 文档以获取有关在 Spring 中使用本地化的更多详细信息.

 "contacts" 示例应用程序被设置为使用本地化消息.