[[mvc]]
= Spring MVC 整合

Spring Security 提供了许多与 Spring MVC 的可选集成. 本节将详细介绍集成.

[[mvc-enablewebmvcsecurity]]
== @EnableWebMvcSecurity

NOTE: 从 Spring Security 4.0 开始, `@EnableWebMvcSecurity` 已经标记为 过时注解. 替换为 `@EnableWebSecurity`,它将根据类路径确定添加 Spring MVC 功能.

要启用与 Spring MVC 的 Spring Security 集成,请在配置中添加 `@EnableWebSecurity` 注解.

NOTE: Spring Security 使用 Spring MVC 的 https://docs.spring.io/spring/docs/5.0.0.RELEASE/spring-framework-reference/web.html#mvc-config-customize[WebMvcConfigurer]提供配置.  这意味着,如果您使用的是更高级的选项,例如直接与 `WebMvcConfigurationSupport` 集成,那么您将需要手动提供 Spring Security 配置.

[[mvc-requestmatcher]]
== MvcRequestMatcher

Spring Security 提供了与 Spring MVC 如何使用 `MvcRequestMatcher` 在 URL 上进行匹配的深度集成.  这有助于确保您的安全规则与用于处理请求的逻辑相匹配.

为了使用 MvcRequestMatcher,必须将 Spring Security Configuration 与 DispatcherServlet 放在同一 `ApplicationContext` 中.  这是必需的,因为 Spring Security 的 `MvcRequestMatcher` 希望您的 Spring MVC 配置会注册一个名称为 `mvcHandlerMappingIntrospector` 的 `HandlerMappingIntrospector` Bean,用于执行匹配.

对于 `web.xml`,这意味着您应该将配置放在 `DispatcherServlet.xml` 中.

[source,xml]
----
<listener>
  <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
</listener>

<!-- All Spring Configuration (both MVC and Security) are in /WEB-INF/spring/ -->
<context-param>
  <param-name>contextConfigLocation</param-name>
  <param-value>/WEB-INF/spring/*.xml</param-value>
</context-param>

<servlet>
  <servlet-name>spring</servlet-name>
  <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
  <!-- Load from the ContextLoaderListener -->
  <init-param>
    <param-name>contextConfigLocation</param-name>
    <param-value></param-value>
  </init-param>
</servlet>

<servlet-mapping>
  <servlet-name>spring</servlet-name>
  <url-pattern>/</url-pattern>
</servlet-mapping>
----

在 `WebSecurityConfiguration` 下面的 `DispatcherServlets` 中放置 `ApplicationContext`.

====
.Java
[source,java,role="primary"]
----
public class SecurityInitializer extends
    AbstractAnnotationConfigDispatcherServletInitializer {

  @Override
  protected Class<?>[] getRootConfigClasses() {
    return null;
  }

  @Override
  protected Class<?>[] getServletConfigClasses() {
    return new Class[] { RootConfiguration.class,
        WebMvcConfiguration.class };
  }

  @Override
  protected String[] getServletMappings() {
    return new String[] { "/" };
  }
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
class SecurityInitializer : AbstractAnnotationConfigDispatcherServletInitializer() {
    override fun getRootConfigClasses(): Array<Class<*>>? {
        return null
    }

    override fun getServletConfigClasses(): Array<Class<*>> {
        return arrayOf(
            RootConfiguration::class.java,
            WebMvcConfiguration::class.java
        )
    }

    override fun getServletMappings(): Array<String> {
        return arrayOf("/")
    }
}
----
====

[NOTE]
====
始终建议通过匹配 `HttpServletRequest` 和方法安全性来提供授权规则.

通过在 `HttpServletRequest` 上进行匹配来提供授权规则是一件好事,因为它发生在代码路径的早期,并且有助于减少 https://en.wikipedia.org/wiki/Attack_surface[攻击面].
方法安全性可确保如果有人绕过了 Web 授权规则,则您的应用程序仍然受到保护.  这就是所谓的 https://en.wikipedia.org/wiki/Defense_in_depth_(computing)[深度防御]

====

考虑一个映射如下的控制器:

====
.Java
[source,java,role="primary"]
----
@RequestMapping("/admin")
public String admin() {
----

.Kotlin
[source,kotlin,role="secondary"]
----
@RequestMapping("/admin")
fun admin(): String {
----
====

如果我们想将对这种控制器方法的访问限制为管理员用户,则开发人员可以通过在 `HttpServletRequest` 上匹配以下内容来提供授权规则:

====
.Java
[source,java,role="primary"]
----
protected configure(HttpSecurity http) throws Exception {
	http
		.authorizeHttpRequests(authorize -> authorize
			.antMatchers("/admin").hasRole("ADMIN")
		);
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
override fun configure(http: HttpSecurity) {
    http {
        authorizeRequests {
            authorize(AntPathRequestMatcher("/admin"), hasRole("ADMIN"))
        }
    }
}
----
====

或使用 xml

[source,xml]
----
<http>
	<intercept-url pattern="/admin" access="hasRole('ADMIN')"/>
</http>
----

无论采用哪种配置,URL  `/admin`  都将要求经过身份验证的用户为 admin 用户.  但是,根据我们的 Spring MVC 配置,URL `/admin.html` 也将映射到我们的 `admin()` 方法.  另外,根据我们的 Spring MVC 配置,URL `/admin/` 也将映射到我们的 `admin()` 方法.

问题在于我们的安全规则仅保护 `/admin` .  我们可以为 Spring MVC 的所有排列添加其他规则,但这将非常冗长而乏味.

相反,我们可以利用 Spring Security 的 `MvcRequestMatcher`.  以下配置通过使用 Spring MVC 在 URL 上进行匹配来保护与 Spring MVC 匹配的 URL.

====
.Java
[source,java,role="primary"]
----
protected configure(HttpSecurity http) throws Exception {
	http
		.authorizeHttpRequests(authorize -> authorize
			.mvcMatchers("/admin").hasRole("ADMIN")
		);
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
override fun configure(http: HttpSecurity) {
    http {
        authorizeRequests {
            authorize("/admin", hasRole("ADMIN"))
        }
    }
}
----
====

或使用 xml

[source,xml]
----
<http request-matcher="mvc">
	<intercept-url pattern="/admin" access="hasRole('ADMIN')"/>
</http>
----

[[mvc-authentication-principal]]
== @AuthenticationPrincipal

Spring Security 提供了 `AuthenticationPrincipalArgumentResolver`,它可以为 Spring MVC 参数自动解析当前的 `Authentication.getPrincipal()` .  通过使用 `@EnableWebSecurity`,您将自动将其添加到 Spring MVC 配置中.  如果使用基于 XML 的配置,则必须自己添加.  例如:

[source,xml]
----
<mvc:annotation-driven>
		<mvc:argument-resolvers>
				<bean class="org.springframework.security.web.method.annotation.AuthenticationPrincipalArgumentResolver" />
		</mvc:argument-resolvers>
</mvc:annotation-driven>
----

正确配置 `AuthenticationPrincipalArgumentResolver` 之后,您就可以在 Spring MVC 层中与 Spring Security 完全脱钩.

考虑一种情况,其中自定义 `UserDetailsService` 返回一个实现 `UserDetails` 的对象和您自己的 `CustomUser` 对象.  可以使用以下代码访问当前已认证用户的 `CustomUser`:

====
.Java
[source,java,role="primary"]
----
@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser() {
	Authentication authentication =
	SecurityContextHolder.getContext().getAuthentication();
	CustomUser custom = (CustomUser) authentication == null ? null : authentication.getPrincipal();

	// .. find messages for this user and return them ...
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@RequestMapping("/messages/inbox")
open fun findMessagesForUser(): ModelAndView {
    val authentication: Authentication = SecurityContextHolder.getContext().authentication
    val custom: CustomUser? = if (authentication as CustomUser == null) null else authentication.principal

    // .. find messages for this user and return them ...
}
----
====

从 Spring Security 3.2 开始,我们可以通过添加注解来更直接地解析参数. 例如:

====
.Java
[source,java,role="primary"]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal;

// ...

@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser(@AuthenticationPrincipal CustomUser customUser) {

	// .. find messages for this user and return them ...
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@RequestMapping("/messages/inbox")
open fun findMessagesForUser(@AuthenticationPrincipal customUser: CustomUser?): ModelAndView {

    // .. find messages for this user and return them ...
}
----
====

有时可能需要以某种方式转换主体.  例如,如果 `CustomUser` 需要为 `final`,则无法扩展.  在这种情况下,`UserDetailsService` 可能返回一个实现 `UserDetails` 的对象,并提供一个名为 `getCustomUser` 的方法来访问 `CustomUser`.  例如,它可能看起来像:

====
.Java
[source,java,role="primary"]
----
public class CustomUserUserDetails extends User {
		// ...
		public CustomUser getCustomUser() {
				return customUser;
		}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
class CustomUserUserDetails(
    username: String?,
    password: String?,
    authorities: MutableCollection<out GrantedAuthority>?
) : User(username, password, authorities) {
    // ...
    val customUser: CustomUser? = null
}
----
====

然后,我们可以使用 https://docs.spring.io/spring/docs/current/spring-framework-reference/html/expressions.html[SpEL 表达式] 访问 `CustomUser`,该表达式使用 `Authentication.getPrincipal()` 作为根对象:

====
.Java
[source,java,role="primary"]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal;

// ...

@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser(@AuthenticationPrincipal(expression = "customUser") CustomUser customUser) {

	// .. find messages for this user and return them ...
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal

// ...

@RequestMapping("/messages/inbox")
open fun findMessagesForUser(@AuthenticationPrincipal(expression = "customUser") customUser: CustomUser?): ModelAndView {

    // .. find messages for this user and return them ...
}
----
====

我们还可以在 SpEL 表达式中引用 Bean. 例如,如果我们使用 JPA 来管理用户,并且想要修改并保存当前用户的属性,则可以使用以下内容.

====
.Java
[source,java,role="primary"]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal;

// ...

@PutMapping("/users/self")
public ModelAndView updateName(@AuthenticationPrincipal(expression = "@jpaEntityManager.merge(#this)") CustomUser attachedCustomUser,
		@RequestParam String firstName) {

	// change the firstName on an attached instance which will be persisted to the database
	attachedCustomUser.setFirstName(firstName);

	// ...
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal

// ...

@PutMapping("/users/self")
open fun updateName(
    @AuthenticationPrincipal(expression = "@jpaEntityManager.merge(#this)") attachedCustomUser: CustomUser,
    @RequestParam firstName: String?
): ModelAndView {

    // change the firstName on an attached instance which will be persisted to the database
    attachedCustomUser.setFirstName(firstName)

    // ...
}
----
====

通过使 `@AuthenticationPrincipal` 成为我们自己的注解的元注解,我们可以进一步消除对 Spring Security 的依赖. 下面我们演示如何在名为 `@CurrentUser` 的注解上执行此操作.

NOTE: 重要的是要意识到,为了消除对 Spring Security 的依赖,创建 `@CurrentUser` 的是消耗者的应用程序.  并非严格要求执行此步骤,但可以帮助您将对 Spring Security 的依赖隔离到更中央的位置.

====
.Java
[source,java,role="primary"]
----
@Target({ElementType.PARAMETER, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@AuthenticationPrincipal
public @interface CurrentUser {}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Target(AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.TYPE)
@Retention(AnnotationRetention.RUNTIME)
@MustBeDocumented
@AuthenticationPrincipal
annotation class CurrentUser
----
====

现在已经指定了 `@CurrentUser`,我们可以用它来通知解析当前已认证用户的 `CustomUser`. 我们还将对 Spring Security 的依赖隔离到一个文件中.

====
.Java
[source,java,role="primary"]
----
@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser(@CurrentUser CustomUser customUser) {

	// .. find messages for this user and return them ...
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@RequestMapping("/messages/inbox")
open fun findMessagesForUser(@CurrentUser customUser: CustomUser?): ModelAndView {

    // .. find messages for this user and return them ...
}
----
====

[[mvc-async]]
== Spring MVC 异步整合

Spring Web MVC 3.2+ 对 https://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/mvc.html#mvc-ann-async[异步请求处理]提供了出色的支持.  无需其他配置,Spring Security 就会自动将 `SecurityContext` 设置为执行由您的控制器返回的 `Callable` 的线程.
例如,以下方法将自动使用创建 `Callable` 时可用的 `SecurityContext` 执行其 `Callable`:

====
.Java
[source,java,role="primary"]
----
@RequestMapping(method=RequestMethod.POST)
public Callable<String> processUpload(final MultipartFile file) {

return new Callable<String>() {
	public Object call() throws Exception {
	// ...
	return "someView";
	}
};
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@RequestMapping(method = [RequestMethod.POST])
open fun processUpload(file: MultipartFile?): Callable<String> {
    return Callable {
        // ...
        "someView"
    }
}
----
====

[NOTE]
.将 SecurityContext 与 Callable 的关联
====
从技术上讲,Spring Security 与 `WebAsyncManager` 集成. 用于处理 `Callable` 的 `SecurityContext` 是在调用 `startCallableProcessing` 时 `SecurityContextHolder` 上存在的 `SecurityContext`.
====

没有与控制器返回的 `DeferredResult` 自动集成.  这是因为 `DeferredResult` 由用户处理,因此无法自动与其集成.  但是,您仍然可以使用<<concurrency,并发支持>> 来提供与 Spring Security 的透明集成.

[[mvc-csrf]]
== Spring MVC 和 CSRF 整合

=== 自动包含令牌

Spring Security 将在使用 https://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/view.html#view-jsp-formtaglib-formtag[Spring MVC form tag]中自动<<servlet-csrf-include,包含 CSRF 令牌>>. 例如,以下 JSP:

[source,xml]
----
<jsp:root xmlns:jsp="http://java.sun.com/JSP/Page"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:form="http://www.springframework.org/tags/form" version="2.0">
	<jsp:directive.page language="java" contentType="text/html" />
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
	<!-- ... -->

	<c:url var="logoutUrl" value="/logout"/>
	<form:form action="${logoutUrl}"
		method="post">
	<input type="submit"
		value="Log out" />
	<input type="hidden"
		name="${_csrf.parameterName}"
		value="${_csrf.token}"/>
	</form:form>

	<!-- ... -->
</html>
</jsp:root>
----

将输出类似于以下内容的 HTML:

[source,xml]
----
<!-- ... -->

<form action="/context/logout" method="post">
<input type="submit" value="Log out"/>
<input type="hidden" name="_csrf" value="f81d4fae-7dec-11d0-a765-00a0c91e6bf6"/>
</form>

<!-- ... -->
----

[[mvc-csrf-resolver]]
===  CsrfToken 解析

Spring Security 提供了 `CsrfTokenArgumentResolver`,它可以自动为 Spring MVC 参数解析当前的 `CsrfToken`.  通过使用 <<jc-hello-wsca,@EnableWebSecurity>> ,您将自动将其添加到 Spring MVC 配置中.  如果使用基于 XML 的配置,则必须自己添加.

正确配置 `CsrfTokenArgumentResolver` 后,即可将 `CsrfToken` 暴露给基于静态 HTML 的应用程序.

====
.Java
[source,java,role="primary"]
----
@RestController
public class CsrfController {

	@RequestMapping("/csrf")
	public CsrfToken csrf(CsrfToken token) {
		return token;
	}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@RestController
class CsrfController {
    @RequestMapping("/csrf")
    fun csrf(token: CsrfToken): CsrfToken {
        return token
    }
}
----
====

保持 `CsrfToken` 对其他域的秘密非常重要. 这意味着,如果您使用 https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS[跨源共享(CORS) ],则不应将 `CsrfToken` 暴露给任何外部域.