[[nsa-authentication]]
=== Authentication Services
在 Spring Security 3.0 之前,`AuthenticationManager` 是在内部自动注册的.  现在,您必须使用 `<authentication-manager>` 元素显式注册一个.  这将创建 Spring Security 的 `ProviderManager` 类的实例,该实例需要配置一个或多个 `AuthenticationProvider` 实例的列表.
这些可以使用命名空间提供的语法元素创建,也可以是标准 bean 定义,并使用 `authentication-provider` 元素标记为添加到列表中.


[[nsa-authentication-manager]]
==== <authentication-manager>

每个使用命名空间的 Spring Security 应用程序都必须在某处包含此元素.  它负责注册为应用程序提供身份验证服务的 `AuthenticationManager`.  创建 `AuthenticationProvider` 实例的所有元素都应该是该元素的子级.

[[nsa-authentication-manager-attributes]]
===== <authentication-manager> 属性


[[nsa-authentication-manager-alias]]
* **alias**
此属性使您可以定义内部实例的别名,以在您自己的配置中使用.

[[nsa-authentication-manager-erase-credentials]]
* **erase-credentials**

如果设置为 `true`,则在验证用户身份之后,`AuthenticationManager` 将尝试清除返回的 Authentication 对象中的所有凭据数据.  从字面上看,它映射到 <<servlet-authentication-providermanager,`ProviderManager`>> 的 `eraseCredentialsAfterAuthentication` 属性.

[[nsa-authentication-manager-id]]
* **id**
此属性允许您定义内部实例的 ID,以在您自己的配置中使用. 它与 alias 元素相同,但是使用 id 属性的元素提供了更一致的体验.


[[nsa-authentication-manager-children]]
=====  <authentication-manager> 的子元素


* <<nsa-authentication-provider,authentication-provider>>
* <<nsa-ldap-authentication-provider,ldap-authentication-provider>>


[[nsa-authentication-provider]]
==== <authentication-provider>
除非与 `ref` 属性一起使用,否则此元素是配置 `DaoAuthenticationProvider` 的简写.  `DaoAuthenticationProvider` 从 `UserDetailsService` 加载用户信息,并将用户名/密码组合与登录时提供的值进行比较.
可以通过使用可用的命名空间元素 (`jdbc-user-service` 或通过使用 `user-service-ref` 属性指向应用程序上下文中其他位置定义的bean) 来定义 `UserDetailsService` 实例.

[[nsa-authentication-provider-parents]]
=====  <authentication-provider> 的父元素

* <<nsa-authentication-manager,authentication-manager>>

[[nsa-authentication-provider-attributes]]
===== <authentication-provider> 属性


[[nsa-authentication-provider-ref]]
* **ref**
定义对实现 `AuthenticationProvider` 的 Spring bean 的引用.

如果您已经编写了自己的 `AuthenticationProvider` 实现 (或者出于某种原因想要将 Spring Security 自己的实现之一配置为传统 Bean,则可以使用以下语法将其添加到 `ProviderManager` 的内部列表中:

[source,xml]
----

<security:authentication-manager>
<security:authentication-provider ref="myAuthenticationProvider" />
</security:authentication-manager>
<bean id="myAuthenticationProvider" class="com.something.MyAuthenticationProvider"/>

----




[[nsa-authentication-provider-user-service-ref]]
* **user-service-ref**
对实现 UserDetailsService 的 bean 的引用,该 UserDetailsService 可以使用标准 bean 元素或自定义 user-service 元素创建.


[[nsa-authentication-provider-children]]
=====  <authentication-provider> 的子元素


* <<nsa-jdbc-user-service,jdbc-user-service>>
* <<nsa-ldap-user-service,ldap-user-service>>
* <<nsa-password-encoder,password-encoder>>
* <<nsa-user-service,user-service>>



[[nsa-jdbc-user-service]]
==== <jdbc-user-service>
导致创建基于 JDBC 的 UserDetailsService.


[[nsa-jdbc-user-service-attributes]]
===== <jdbc-user-service> 属性


[[nsa-jdbc-user-service-authorities-by-username-query]]
* **authorities-by-username-query**
用于查询给定用户名的用户授予权限的 SQL 语句.

默认是

[source]
----
select username, authority from authorities where username = ?
----




[[nsa-jdbc-user-service-cache-ref]]
* **cache-ref**
定义对与 UserDetailsService 一起使用的缓存的引用.


[[nsa-jdbc-user-service-data-source-ref]]
* **data-source-ref**
提供所需表的数据源的Bean ID.


[[nsa-jdbc-user-service-group-authorities-by-username-query]]
* **group-authorities-by-username-query**
给定用户名的 SQL 语句,用于查询用户的组权限. 默认是

+

[source]
----
select
g.id, g.group_name, ga.authority
from
groups g, group_members gm, group_authorities ga
where
gm.username = ? and g.id = ga.group_id and g.id = gm.group_id
----




[[nsa-jdbc-user-service-id]]
* **id**
Bean 标识符,用于引用上下文中其他位置的 Bean.


[[nsa-jdbc-user-service-role-prefix]]
* **role-prefix**
一个非空字符串前缀,将添加到从持久性存储加载的角色字符串中 (默认为 "ROLE_") . 在默认为非空的情况下,将值 "none" 用于无前缀.


[[nsa-jdbc-user-service-users-by-username-query]]
* **users-by-username-query**
用于查询用户名,密码和给定用户名的启用状态的 SQL 语句. 默认是

+

[source]
----
select username, password, enabled from users where username = ?
----

[[nsa-password-encoder]]
==== <password-encoder>
如<<authentication-password-storage>>中所述,可以选择将身份验证提供程序配置为使用密码编码器. 这将导致使用适当的 `PasswordEncoder` 实例注入 Bean.

[[nsa-password-encoder-parents]]
=====  <password-encoder> 的父元素


* <<nsa-authentication-provider,authentication-provider>>
* <<nsa-password-compare,password-compare>>

[[nsa-password-encoder-attributes]]
===== <password-encoder> 属性


[[nsa-password-encoder-hash]]
* **hash**
定义用于用户密码的哈希算法. 我们强烈建议您不要使用 MD4,因为它是一种非常弱的哈希算法.


[[nsa-password-encoder-ref]]
* **ref**
定义对实现 `PasswordEncoder` 的 Spring bean 的引用.


[[nsa-user-service]]
==== <user-service>
从属性文件或 "user"  子元素列表创建内存 UserDetailsService. 用户名在内部会转换为小写形式,以允许不区分大小写的查找,因此如果需要区分大小写,则不应使用此名称.

[[nsa-user-service-attributes]]
===== <user-service> 属性


[[nsa-user-service-id]]
* **id**
Bean 标识符,用于引用上下文中其他位置的 Bean.


[[nsa-user-service-properties]]
* **properties**
属性文件的位置,其中每一行的格式为

+

[source]
----
username=password,grantedAuthority[,grantedAuthority][,enabled|disabled]
----

[[nsa-user-service-children]]
=====  <user-service> 的子元素

* <<nsa-user,user>>

[[nsa-user]]
==== <user>
代表应用程序中的用户.


[[nsa-user-parents]]
=====  <user> 的父元素

* <<nsa-user-service,user-service>>

[[nsa-user-attributes]]
===== <user> 属性


[[nsa-user-authorities]]
* **authorities**
授予用户的其他权限之一. 用逗号隔开 (但不能有空格) . 例如, "ROLE_USER,ROLE_ADMINISTRATOR"

[[nsa-user-disabled]]
* **disabled**
可以设置为 "true" 以将帐户标记为禁用和不可用.


[[nsa-user-locked]]
* **locked**
可以设置为 "true" 以将帐户标记为已锁定且无法使用.


[[nsa-user-name]]
* **name**
分配给用户的用户名.


[[nsa-user-password]]
* **password**
分配给用户的密码.  如果相应的身份验证提供程序支持哈希 (请记住要设置 "user-service" 元素的 "hash" 属性) ,则可以对此进行哈希处理.  在数据将不用于认证而仅用于访问权限的情况下,将忽略此属性.  如果省略,则命名空间将生成一个随机值,以防止其偶然用于身份验证.  不能为空. .