[[nsa-ldap]]
=== LDAP Namespace 选项
LDAP 在<<servlet-authentication-ldap,其自己的章节中>>进行了一些详细介绍.  我们将在此扩展它,并提供一些有关命名空间选项如何映射到 Spring Bean 的解释.  LDAP 实现广泛使用 Spring LDAP,因此熟悉该项目的API可能会有用.

[[nsa-ldap-server]]
==== Defining the LDAP Server using the
`<ldap-server>` 元素此元素设置一个供其他 LDAP Bean 使用的 Spring LDAP `ContextSource`,用于定义 LDAP 服务器的位置以及其他信息 (例如用户名和密码,如果不允许匿名访问) 用于连接到它.
它还可以用于创建嵌入式服务器以进行测试.   <<servlet-authentication-ldap,LDAP 一章>>介绍了这两个选项的语法详细信息.  实际的 `ContextSource` 实现是 `DefaultSpringSecurityContextSource`,它扩展了 Spring LDAP 的 `LdapContextSource` 类.
`manager-dn` 和 `manager-password` 属性分别映射到后者的 `userDn` 和密码属性.

如果在应用程序上下文中仅定义了一个服务器,则其他 LDAP 命名空间定义的 Bean 将自动使用它.  否则,您可以为元素赋予 "id" 属性,并使用 `server-ref` 属性从其他命名空间 Bean 引用该元素.  如果要在其他传统 Spring Bean 中使用它,则实际上是 `ContextSource` 实例的 Bean ID.

[[nsa-ldap-server-attributes]]
===== <ldap-server> 属性

[[nsa-ldap-server-mode]]
* **mode**
明确指定应使用哪个嵌入式 ldap 服务器. 值是固定的和无限制的. 默认情况下,将取决于该库在类路径中是否可用.

[[nsa-ldap-server-id]]
* **id**
Bean 标识符,用于引用上下文中其他位置的 Bean.


[[nsa-ldap-server-ldif]]
* **ldif**
明确指定一个 ldif 文件资源以加载到嵌入式 LDAP 服务器中.  ldif 应该是 Spring 资源模式 (即 `classpath:init.ldif`) .  默认值为 `classpath*:*.ldif`


[[nsa-ldap-server-manager-dn]]
* **manager-dn**
"manager" 用户身份的用户名 (DN) ,将用于向 (非嵌入式) LDAP 服务器进行身份验证. 如果省略,将使用匿名访问.

[[nsa-ldap-server-manager-password]]
* **manager-password**
管理员DN的密码. 如果指定了 manager-dn,则这是必需的.


[[nsa-ldap-server-port]]
* **port**
指定 IP 端口号. 例如,用于配置嵌入式 LDAP 服务器. 默认值为 33389.


[[nsa-ldap-server-root]]
* **root**
嵌入式 LDAP 服务器的可选根后缀. 默认值为 "dc=springframework,dc=org"

[[nsa-ldap-server-url]]
* **url**
不使用嵌入式LDAP服务器时,指定ldap服务器URL.


[[nsa-ldap-authentication-provider]]
==== <ldap-authentication-provider>
此元素是创建 `LdapAuthenticationProvider` 实例的简写.  默认情况下,它将使用 `BindAuthenticator` 实例和 `DefaultAuthoritiesPopulator` 配置.  与所有命名空间身份验证提供程序一样,必须将其作为 `authentication-provider` 元素的子元素包括在内.

[[nsa-ldap-authentication-provider-parents]]
=====  <ldap-authentication-provider> 的父元素


* <<nsa-authentication-manager,authentication-manager>>



[[nsa-ldap-authentication-provider-attributes]]
===== <ldap-authentication-provider> 属性


[[nsa-ldap-authentication-provider-group-role-attribute]]
* **group-role-attribute**
LDAP 属性名称,其中包含将在 Spring Security 中使用的角色名称. 映射到 `DefaultLdapAuthoritiesPopulator` 的 `groupRoleAttribute` 属性. 默认为 "cn".

[[nsa-ldap-authentication-provider-group-search-base]]
* **group-search-base**
组成员资格搜索的搜索基础. 映射到 `DefaultLdapAuthoritiesPopulator` 的 `groupSearchBase` 构造函数参数. 默认为 "" (从根目录搜索) .


[[nsa-ldap-authentication-provider-group-search-filter]]
* **group-search-filter**
组搜索过滤器. 映射到 `DefaultLdapAuthoritiesPopulator` 的 `groupSearchFilter` 属性. 默认为 ( `+(uniqueMember={0})+` ) . 替换的参数是用户的DN.

[[nsa-ldap-authentication-provider-role-prefix]]
* **role-prefix**
非空字符串前缀,将添加到从持久性加载的角色字符串中. 映射到 `DefaultLdapAuthoritiesPopulator` 的 `rolePrefix` 属性. 默认为 "ROLE_". 在默认为非空的情况下,将值 "none" 用于无前缀.

[[nsa-ldap-authentication-provider-server-ref]]
* **server-ref**
要使用的可选服务器. 如果省略,并且注册了默认的 LDAP 服务器 (使用没有 ID 的 <ldap-server>) ,则将使用该服务器.


[[nsa-ldap-authentication-provider-user-context-mapper-ref]]
* **user-context-mapper-ref**
通过指定 UserDetailsContextMapper bean 来对加载的用户对象进行显式定制,该 bean 将与用户目录条目中的上下文信息一起调用

[[nsa-ldap-authentication-provider-user-details-class]]
* **user-details-class**
允许指定用户条目的 objectClass. 如果设置,框架将尝试将已定义类的标准属性加载到返回的 UserDetails 对象中


[[nsa-ldap-authentication-provider-user-dn-pattern]]
* **user-dn-pattern**
如果您的用户位于目录中的固定位置 (即您可以直接从用户名计算出 DN,而无需进行目录搜索) ,则可以使用此属性直接映射到 DN.  它直接映射到 `AbstractLdapAuthenticator` 的 `userDnPatterns` 属性.
该值是用于构建用户 DN 的特定模式,例如 `+uid={0},ou=people+`.  键  `+{0}+` 必须存在,并将被用户名替换.

[[nsa-ldap-authentication-provider-user-search-base]]
* **user-search-base**
用户搜索的搜索库.  默认为 "".  仅与 `user-search-filter` 一起使用.

+

如果需要执行搜索以在目录中找到用户,则可以设置这些属性来控制搜索.  `BindAuthenticator` 将使用 `FilterBasedLdapUserSearch` 配置,并且属性值直接映射到该 bean 的构造函数的前两个参数.
如果未设置这些属性,并且未提供任何 `user-dn-pattern` 作为替代,则默认搜索值为 `user-search-filter="(uid={0})"` 和 `user-search-base=""`  将会被使用.

[[nsa-ldap-authentication-provider-user-search-filter]]
* **user-search-filter**

用于搜索用户的 LDAP 过滤器 (可选) .  例如 "(uid={0})".  替换的参数是用户的登录名.

+

如果需要执行搜索以在目录中找到用户,则可以设置这些属性来控制搜索.  `BindAuthenticator` 将使用 `FilterBasedLdapUserSearch` 配置,并且属性值直接映射到该 bean 的构造函数的前两个参数.
如果未设置这些属性,并且未提供任何 `user-dn-pattern` 作为替代,则默认搜索值为 `user-search-filter="(uid={0})"` 和 `user-search-base=""` 将会被使用.

[[nsa-ldap-authentication-provider-children]]
=====  <ldap-authentication-provider> 的子元素


* <<nsa-password-compare,password-compare>>



[[nsa-password-compare]]
==== <password-compare>
用作 `<ldap-provider>` 的子元素,并将身份验证策略从 `BindAuthenticator` 切换到 `PasswordComparisonAuthenticator`.


[[nsa-password-compare-parents]]
=====  <password-compare> 的父元素


* <<nsa-ldap-authentication-provider,ldap-authentication-provider>>



[[nsa-password-compare-attributes]]
===== <password-compare> 属性


[[nsa-password-compare-hash]]
* **hash**
定义用于用户密码的哈希算法. 我们强烈建议您不要使用 MD4,因为它是一种非常弱的哈希算法.


[[nsa-password-compare-password-attribute]]
* **password-attribute**
目录中包含用户密码的属性. 默认为 "userPassword".


[[nsa-password-compare-children]]
=====  <password-compare> 的子元素


* <<nsa-password-encoder,password-encoder>>



[[nsa-ldap-user-service]]
==== <ldap-user-service>
此元素配置 LDAP `UserDetailsService`.  使用的类是 `LdapUserDetailsService`,它是 `FilterBasedLdapUserSearch` 和 `DefaultLdapAuthoritiesPopulator` 的组合.  它支持的属性与 `<ldap-provider>` 中的用法相同.

[[nsa-ldap-user-service-attributes]]
===== <ldap-user-service> 属性


[[nsa-ldap-user-service-cache-ref]]
* **cache-ref**
定义对与 UserDetailsService 一起使用的缓存的引用.


[[nsa-ldap-user-service-group-role-attribute]]
* **group-role-attribute**
LDAP 属性名称,其中包含将在 Spring Security 中使用的角色名称. 默认为 "cn".


[[nsa-ldap-user-service-group-search-base]]
* **group-search-base**
组成员资格搜索的搜索基础. 默认为 "" (从根目录搜索) .


[[nsa-ldap-user-service-group-search-filter]]
* **group-search-filter**
组搜索过滤器. 默认为 (uniqueMember={0}) . 替换的参数是用户的 DN.

[[nsa-ldap-user-service-id]]
* **id**
Bean 标识符,用于引用上下文中其他位置的 Bean.


[[nsa-ldap-user-service-role-prefix]]
* **role-prefix**
非空字符串前缀,将添加到从持久性存储 (例如 "ROLE_") 加载的角色字符串中. 在默认为非空的情况下,将值 "none" 用于无前缀.

[[nsa-ldap-user-service-server-ref]]
* **server-ref**
要使用的可选服务器. 如果省略,并且注册了默认的 LDAP 服务器 (使用没有 ID 的 <ldap-server>) ,则将使用该服务器.

[[nsa-ldap-user-service-user-context-mapper-ref]]
* **user-context-mapper-ref**
通过指定 UserDetailsContextMapper bean 允许显式自定义已加载的用户对象,该 bean 将与用户目录条目中的上下文信息一起调用

[[nsa-ldap-user-service-user-details-class]]
* **user-details-class**
允许指定用户条目的 objectClass. 如果设置,框架将尝试将已定义类的标准属性加载到返回的 UserDetails 对象中


[[nsa-ldap-user-service-user-search-base]]
* **user-search-base**
用户搜索的搜索库. 默认为 "". 仅与  `user-search-filter` 一起使用.

[[nsa-ldap-user-service-user-search-filter]]
* **user-search-filter**
用于搜索用户的 LDAP 过滤器 (可选) . 例如 "(uid={0})". 替换的参数是用户的登录名.