[[nsa-websocket-security]]
=== WebSocket Security

Spring Security 4.0+ 提供了对消息授权的支持. 一个有用的具体示例是在基于 WebSocket 的应用程序中提供授权.

[[nsa-websocket-message-broker]]
==== <websocket-message-broker>

websocket-message-broker 元素具有两种不同的模式. 如果未指定<<nsa-websocket-message-broker-id,websocket-message-broker@id>>,则它将执行以下操作:

* 确保任何 SimpAnnotationMethodMessageHandler 都将 AuthenticationPrincipalArgumentResolver 注册为自定义参数解析器.  这允许使用 `@AuthenticationPrincipal` 来解析当前 `Authentication` 的主体
* 确保已为 clientInboundChannel 自动注册 SecurityContextChannelInterceptor.  这将使用 Message 中找到的用户填充 SecurityContextHolder
* 确保 ChannelSecurityInterceptor 已向 clientInboundChannel 注册.  这允许为消息指定授权规则.
* 确保 CsrfChannelInterceptor 已在 clientInboundChannel 中注册.  这样可以确保仅启用来自原始域的请求.
* 确保已向 WebSocketHttpRequestHandler,TransportHandlingSockJsService 或 DefaultSockJsService 注册 CsrfTokenHandshakeInterceptor.  这样可以确保将来自 HttpServletRequest 的预期 CsrfToken 复制到 WebSocket 会话属性中.

如果需要其他控制,则可以指定 ID,并将 ChannelSecurityInterceptor 分配给指定的 ID.  然后,可以手动完成与 Spring 的消息传递基础结构的所有连接.  这比较麻烦,但是可以更好地控制配置.


[[nsa-websocket-message-broker-attributes]]
===== <websocket-message-broker> 属性

[[nsa-websocket-message-broker-id]]
* **id** Bean 标识符,用于在上下文中的其他地方引用 `ChannelSecurityInterceptor` Bean.  如果指定,Spring Security 需要在 Spring Messaging 中进行显式配置.  如果未指定,Spring Security 将自动与消息传递基础结构集成,如<<nsa-websocket-message-broker>>部分中所述

[[nsa-websocket-message-broker-same-origin-disabled]]
* **same-origin-disabled** 禁用 Stomp header 中必须存在 CSRF 令牌的要求 (默认为 false) . 如果需要允许其他来源建立 SockJS 连接,则更改默认值很有用.

[[nsa-websocket-message-broker-children]]
=====  <websocket-message-broker> 的子元素


* <<nsa-expression-handler,expression-handler>>
* <<nsa-intercept-message,intercept-message>>

[[nsa-intercept-message]]
==== <intercept-message>

定义消息的授权规则.


[[nsa-intercept-message-parents]]
=====  <intercept-message> 的父元素


* <<nsa-websocket-message-broker,websocket-message-broker>>


[[nsa-intercept-message-attributes]]
===== <intercept-message> 属性

[[nsa-intercept-message-pattern]]
* **pattern** 在消息目标上匹配的基于 Ant 的模式. 例如,"/" 将任何消息与目标匹配;  "/admin/" 与目标以 "/admin/**" 开头的任何邮件匹配.

[[nsa-intercept-message-type]]
* **type** 要匹配的消息类型. 有效值在 SimpMessageType 中定义 (即 CONNECT,CONNECT_ACK,HEARTBEAT,MESSAGE,SUBSCRIBE,UNSUBSCRIBE,DISCONNECT,DISCONNECT_ACK,OTHER) .

[[nsa-intercept-message-access]]
* **access** 用于保护消息的表达式.  例如, "denyAll" 将拒绝访问所有匹配的消息;  "permitAll" 将授予对所有匹配消息的访问权限;  "hasRole('ADMIN') 要求当前用户具有匹配消息的角色 'ROLE_ADMIN'.