[[dynamic-language]]
= 动态语言支持

Spring 为使用已经被使用过的类和对象提供了全面的支持. 通过在 Spring 中使用动态语言(例如 Groovy)进行定义. 这种支持让您可以使用受支持的动态语言编写任意数量的类,并具有 Spring 容器透明地实例化,配置并依赖注入结果对象.

Spring 的脚本支持主要针对 Groovy 和 BeanShell. 超越那些特别支持的语言,支持 JSR-223 脚本编制机制 用于与任何支持 JSR-223 的语言提供者集成(自 Spring 4.2 起), 例如 JRuby.

您可以找到完全可行的示例,这些示例可以在<<dynamic-language-scenarios>>中立即使用这种动态语言支持.

[[dynamic-language-a-first-example]]
== 第一个示例

本章的大部分内容与详细描述动态语言支持有关. 在深入探讨动态语言支持的所有内容之前,我们来看一个使用动态语言定义的 bean 的简单示例. 这个第一个 bean 的动态语言是 Groovy. (该示例的基础取自 Spring 测试套件.如果要查看其他任何受支持语言的等效示例,请查看源代码).

下一个示例显示了 Groovy bean 将要实现的 `Messenger` 接口. 请注意,此接口是用纯 Java 定义的。注入了对 `Messenger` 的引用的依赖对象不知道底层的实现是一个 Groovy 脚本。 以下清单显示了 `Messenger` 接口:

[source,groovy,indent=0,subs="verbatim,quotes"]
----
	package org.springframework.scripting;

	public interface Messenger {

		String getMessage();
	}
----

`Messenger` 接口的实现:

[source,java,indent=0,subs="verbatim,quotes"]
----
	package org.springframework.scripting;

	public class DefaultBookingService implements BookingService {

		private Messenger messenger;

		public void setMessenger(Messenger messenger) {
			this.messenger = messenger;
		}

		public void processBooking() {
			// use the injected Messenger object...
		}
	}
----

在 Groovy 中实现 `Messenger` 接口

[source,groovy,indent=0,subs="verbatim,quotes"]
----
	// from the file 'Messenger.groovy'
	package org.springframework.scripting.groovy;

	// import the Messenger interface (written in Java) that is to be implemented
	import org.springframework.scripting.Messenger

	// define the implementation in Groovy
	class GroovyMessenger implements Messenger {

		String message
	}
----

[NOTE]
====
要使用定制的动态语言标签来定义动态语言的 Bean,您需要在 Spring XML 配置文件的顶部具有 XML Schema 声明. 您还需要使用 Spring `ApplicationContext` 实现作为 IoC 容器. 支持将动态语言支持的 bean 与纯 `BeanFactory` 实现一起使用,但是您必须管理 Spring 内部.

有关基于 schema 的配置的更多信息,请参见<<xsd-schemas-lang,基于XML schema 的配置>>.
====

最后,以下示例显示了将 Groovy 定义的 `Messenger` 实现注入到 `DefaultBookingService` 类的实例中:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:lang="http://www.springframework.org/schema/lang"
		xsi:schemaLocation="
			http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/lang https://www.springframework.org/schema/lang/spring-lang.xsd">

		<!-- this is the bean definition for the Groovy-backed Messenger implementation -->
		<lang:groovy id="messenger" script-source="classpath:Messenger.groovy">
			<lang:property name="message" value="I Can Do The Frug" />
		</lang:groovy>

		<!-- an otherwise normal bean that will be injected by the Groovy-backed Messenger -->
		<bean id="bookingService" class="x.y.DefaultBookingService">
			<property name="messenger" ref="messenger" />
		</bean>

	</beans>
----

`bookingService` bean(`DefaultBookingService`)现在可以照常使用其 private `Messenger` 成员变量,因为注入到其中的 `Messenger` 实例是 `Messenger` 实例. 这里没有什么特别的事情-只是普通的 Java 和普通的 Groovy.

希望你能看懂上面的 XML 定义,如果看不懂,请继续往下阅读.

[[dynamic-language-beans]]
== 定义由动态语言支持的 Bean

本节准确地描述了如何使用任何受支持的动态语言来定义 Spring 托管的 bean.

注意,本章并不试图解释受支持的动态语言的语法和惯用语. 例如,如果您想使用 Groovy 在您的应用程序中编写某些类,我们假设您已经了解 Groovy. 如果您需要有关动态语言本身的更多详细信息,请参阅本章末尾的 <<dynamic-language-resources>> .

[[dynamic-language-beans-concepts]]
=== 相关概念

使用动态语言定义 bean 涉及的步骤如下:

. 为动态语言源代码编写测试 (naturally).
. 然后编写动态语言源代码本身
. 通过在 XML 配置中使用适当的 `<lang:language/>` 元素来定义支持动态语言的 Bean(您可以使用 Spring API 以编程方式定义此类 Bean,尽管您将不得不参考源代码以获取有关如何 请执行此操作,因为本章不介绍此类高级配置. 请注意,这是一个迭代步骤. 每个动态语言源文件至少需要一个 bean 定义(尽管多个 bean 定义可以引用同一个动态语言源文件).

前两个步骤(测试和编写动态语言源文件)超出了范围 本章的范围. 请参阅语言规范和参考手册 您选择的动态语言,并继续开发动态语言源文件. 您首先要阅读本章的其余部分,因为 Spring 的动态语言支持确实对内容做了一些(小的)假设动态语言源文件.

[[dynamic-language-beans-concepts-xml-language-element]]
==== <lang:language/> 元素

<<dynamic-language-beans-concepts, 上一节>>最后一步涉及到定义动态语言支持的 bean 定义， 每个要配置的 bean 定义一个(这与常规 JavaBean 配置没有什么不同).  但是， 可以使用 `<lang:language />` 元素定义动态语言支持的 bean， 而不是指定由容器实例化和配置的类的完全限定类名.


每种支持的语言都有一个相对于的 `<lang:language/>` 元素:

* `<lang:groovy/>` (Groovy)
* `<lang:bsh/>` (BeanShell)
* `<lang:std/>` (JSR-223, e.g. with JRuby)

可用于配置的属性和子元素完全取决于定义该 bean 所使用的语言(本章稍后的特定于语言的部分对此进行了详细说明).

[[dynamic-language-refreshable-beans]]
==== Refreshable Beans

Spring 对动态语言的支持(也许是唯一)最引人注目的功能之一就是 "`refreshable bean`" 特性.

可刷新的 bean 是动态语言支持的 bean.  通过少量配置， 支持动态语言的 Bean 可以监视其源文件资源中的更改， 然后在更改动态语言源文件时(例如， 当您在 Windows 上编辑并保存对文件的更改时)重新加载自身文件系统).

这使您可以将任何数量的动态语言源文件部署为应用程序的一部分， 配置 Spring 容器以创建由动态语言源文件支持的 bean(使用本章中描述的机制)， 以及(随后， 随着需求的变化或其他一些变化) 外部因素起作用)编辑动态语言源文件， 并使它们所做的任何更改都反映在更改后的动态语言源文件支持的 Bean 中.  无需关闭正在运行的应用程序(或在 Web 应用程序的情况下重新部署).  如此修改的支持动态语言的 Bean 从更改后的动态语言源文件中获取了新的状态和逻辑.

NOTE: 此特性默认是关闭的.

现在我们来看一个例子， 看看使用可刷新 bean 是多么容易.  要打开可刷新 bean 功能， 必须在 bean 定义的 `<lang:language />` 元素上指定一个附加属性.  因此， 如果我们坚持使用本章前面的<<dynamic-language-a-first-example, 示例>>， 则以下示例显示了我们将在 Spring XML 配置中进行哪些更改以实现可刷新的 bean:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<beans>

		<!-- this bean is now 'refreshable' due to the presence of the 'refresh-check-delay' attribute -->
		<lang:groovy id="messenger"
				refresh-check-delay="5000" <!-- switches refreshing on with 5 seconds between checks -->
				script-source="classpath:Messenger.groovy">
			<lang:property name="message" value="I Can Do The Frug" />
		</lang:groovy>

		<bean id="bookingService" class="x.y.DefaultBookingService">
			<property name="messenger" ref="messenger" />
		</bean>

	</beans>
----

这确实是您要做的.  在 `messenger` Bean 定义上定义的 `refresh-check-delay` 属性是毫秒数， 在该毫秒数之后， 对基础动态语言源文件进行的任何更改都会刷新 Bean.  您可以通过为 `refresh-check-delay` 属性分配一个负值来关闭刷新行为.  请记住， 默认情况下， 刷新行为是禁用的.  如果您不希望刷新行为， 则不要定义属性.

然后运行以下应用程序， 则可以使用可刷新功能.  (请在下一段代码中使用 "`jumping-through-hoops-to-pause-the-execution`" 的恶作剧. )`System.in.read()` 调用仅存在， 以便在您执行该程序时暂停执行.  (在这种情况下， 开发人员)关闭并编辑基础动态语言源文件， 以便在程序恢复执行时在由动态语言支持的 bean 上触发刷新.

以下清单显示了此示例应用程序:

[source,java,indent=0,subs="verbatim,quotes"]
----
	import org.springframework.context.ApplicationContext;
	import org.springframework.context.support.ClassPathXmlApplicationContext;
	import org.springframework.scripting.Messenger;

	public final class Boot {

		public static void main(final String[] args) throws Exception {
			ApplicationContext ctx = new ClassPathXmlApplicationContext("beans.xml");
			Messenger messenger = (Messenger) ctx.getBean("messenger");
			System.out.println(messenger.getMessage());
			// pause execution while I go off and make changes to the source file...
			System.in.read();
			System.out.println(messenger.getMessage());
		}
	}
----

然后， 出于本示例的目的， 假定必须更改对 `Messenger` 实现的 `getMessage()` 方法的所有调用， 以使 message 用引号引起来.  以下清单显示了您(开发人员)在暂停程序执行时应对 `Messenger.groovy` 源文件进行的更改:

[source,groovy,indent=0,subs="verbatim,quotes"]
----
	package org.springframework.scripting

	class GroovyMessenger implements Messenger {

		private String message = "Bingo"

		public String getMessage() {
			// change the implementation to surround the message in quotes
			return "'" + this.message + "'"
		}

		public void setMessage(String message) {
			this.message = message
		}
	}
----

程序运行时， 输入暂停之前的输出将为 `I Can Do The Frug`.  更改并保存对源文件的更改并恢复执行程序之后， 在支持动态语言的 `Messenger` 实现上调用 `getMessage()` 方法的结果为 `'I Can Do The Frug'`(请注意包含其他内容-引号).

如果更改发生在 `refresh-check-delay` 值的窗口内， 则对脚本所做的更改不会触发刷新.  直到在支持动态语言的 Bean 上调用方法之前， 实际上不会进行对脚本的更改.  只有在支持动态语言的 Bean 上调用方法时， 它才会检查其基础脚本源是否已更改.  与刷新脚本有关的任何异常(例如遇到编译错误或发现脚本文件已被删除)都会导致致命异常传播到调用代码.

前面描述的可刷新 bean 行为不适用于使用 `<lang:inline-script/>` 元素表示法定义的动态语言源文件(请参阅<<dynamic-language-beans-inline>>).  此外， 它仅适用于实际上可以检测到基础源文件的更改的 Bean(例如， 通过检查文件系统上存在的动态语言源文件的最后修改日期的代码).

[[dynamic-language-beans-inline]]
==== Inline Dynamic Language Source Files

动态语言支持还可以直接嵌入在 Spring bean 定义中的动态语言源文件.  更具体地说， 使用 `<lang:inline-script/>` 元素， 您可以在 Spring 配置文件中立即定义动态语言源.  下面示例可以阐明内联脚本功能的工作方式:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<lang:groovy id="messenger">
		<lang:inline-script>

	package org.springframework.scripting.groovy;

	import org.springframework.scripting.Messenger

	class GroovyMessenger implements Messenger {
		String message
	}

		</lang:inline-script>
		<lang:property name="message" value="I Can Do The Frug" />
	</lang:groovy>
----

如果将有关在 Spring 配置文件中定义动态语言源是否是一种好习惯的问题放在一边， 在某些情况下，  `<lang:inline-script/>` 元素可能会有用.  例如， 我们可能想将 Spring Validator 实现快速添加到 Spring MVC Controller.  这只是使用嵌入式源代码的工作.  (有关此类示例， 请参见<<dynamic-language-scenarios-validators>>. )

[[dynamic-language-beans-ctor-injection]]
==== 在动态语言支持的 Bean 的上下文中了解构造函数注入

关于 Spring 的动态语言支持， 有一件非常重要的事情要注意.  也就是说， 您不能(当前)向动态语言支持的 bean 提供构造函数参数(因此， 构造函数注入不适用于动态语言支持的 bean).  为了使对构造函数和属性的特殊处理 100％ 清晰， 以下代码和配置的混合将不起作用:

.An approach that cannot work
[source,groovy,indent=0,subs="verbatim,quotes"]
----
	// from the file 'Messenger.groovy'
	package org.springframework.scripting.groovy;

	import org.springframework.scripting.Messenger

	class GroovyMessenger implements Messenger {

		GroovyMessenger() {}

		// this constructor is not available for Constructor Injection
		GroovyMessenger(String message) {
			this.message = message;
		}

		String message

		String anotherMessage
	}
----

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<lang:groovy id="badMessenger"
		script-source="classpath:Messenger.groovy">
		<!-- this next constructor argument will not be injected into the GroovyMessenger -->
		<!-- in fact, this isn't even allowed according to the schema -->
		<constructor-arg value="This will not work" />

		<!-- only property values are injected into the dynamic-language-backed object -->
		<lang:property name="anotherMessage" value="Passed straight through to the dynamic-language-backed object" />

	</lang>
----

在实践中， 这种限制并不像它最初出现的那样重要， 因为 setter 注入是绝大多数开发人员所偏爱的注入方式(我们将讨论是否对另一天来说是一件好事).

[[dynamic-language-beans-groovy]]
=== Groovy Beans

本节描述了如何在 Spring 中使用 Groovy 中定义的 bean.

Groovy 主页包含以下描述:

"`Groovy is an agile dynamic language for the Java 2 Platform that has many of the
features that people like so much in languages like Python, Ruby and Smalltalk, making
them available to Java developers using a Java-like syntax.`"

如果您从上至下直接阅读了本章， 那么您已经看到了 Groovy 动态语言支持的 bean 的 <<dynamic-language-a-first-example, 示例>>.  现在考虑另一个示例(再次使用 Spring 测试套件中的示例):

[source,java,indent=0,subs="verbatim,quotes"]
----
	package org.springframework.scripting;

	public interface Calculator {

		int add(int x, int y);
	}
----

以下实例使用 Groovy 实现了 `Calculator` 接口:

[source,groovy,indent=0,subs="verbatim,quotes"]
----
	// from the file 'calculator.groovy'
	package org.springframework.scripting.groovy

	class GroovyCalculator implements Calculator {

		int add(int x, int y) {
			x + y
		}
	}
----

以下 bean 定义使用 Groovy 中定义的 calculator:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<!-- from the file 'beans.xml' -->
	<beans>
		<lang:groovy id="calculator" script-source="classpath:calculator.groovy"/>
	</beans>
----

最后， 应用程序将执行上述配置:

[source,java,indent=0,subs="verbatim,quotes"]
----
	package org.springframework.scripting;

	import org.springframework.context.ApplicationContext;
	import org.springframework.context.support.ClassPathXmlApplicationContext;

	public class Main {

		public static void main(String[] args) {
			ApplicationContext ctx = new ClassPathXmlApplicationContext("beans.xml");
			Calculator calc = ctx.getBean("calculator", Calculator.class);
			System.out.println(calc.add(2, 8));
		}
	}
----

运行上述程序得到的结果是 `10`(很正常). (有关更多有趣的示例， 请参见 <<dynamic-language-scenarios>> 以获得更复杂的示例， 或参见本章后面的示例场景).

每个 Groovy 源文件中定义的类不得超过一个.  尽管这在 Groovy 中是完全合法的， 但(可以说)这是一种不好的做法.  为了采用一致的方法， 您(在 Spring 小组看来)应该遵守每个源文件一个 (public) 类的标准 Java 约定.

[[dynamic-language-beans-groovy-customizer]]
==== 通过使用回调自定义 Groovy 对象

`GroovyObjectCustomizer` 接口是一个回调， 您可以将其他创建逻辑挂接到创建 Groovy 支持的 bean 的过程中.  例如， 此接口的实现可以调用任何必需的初始化方法， 设置一些默认属性值或指定自定义 `MetaClass`.  以下清单显示了 `GroovyObjectCustomizer` 接口定义:

[source,java,indent=0,subs="verbatim,quotes"]
----
	public interface GroovyObjectCustomizer {

		void customize(GroovyObject goo);
	}
----

Spring 框架实例化您的 Groovy 支持的 bean 的实例， 然后将创建的 `GroovyObject` 传递到指定的 `GroovyObjectCustomizer`(如果已定义).  您可以使用提供的 `GroovyObject` 参考来做任何您想做的事情.  我们希望大多数人都希望使用此回调来设置自定义 `MetaClass`， 以下示例说明了如何进行设置:

[source,java,indent=0,subs="verbatim,quotes"]
----
	public final class SimpleMethodTracingCustomizer implements GroovyObjectCustomizer {

		public void customize(GroovyObject goo) {
			DelegatingMetaClass metaClass = new DelegatingMetaClass(goo.getMetaClass()) {

				public Object invokeMethod(Object object, String methodName, Object[] arguments) {
					System.out.println("Invoking '" + methodName + "'.");
					return super.invokeMethod(object, methodName, arguments);
				}
			};
			metaClass.initialize();
			goo.setMetaClass(metaClass);
		}

	}
----

Groovy 中对元编程的完整讨论超出了 Spring 参考手册的范围.  请参阅 Groovy 参考手册的相关部分， 或在线进行搜索.  大量文章讨论了该主题.  实际上， 如果使用 Spring 命名空间支持， 使用 `GroovyObjectCustomizer` 很容易， 如以下示例所示:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<!-- define the GroovyObjectCustomizer just like any other bean -->
	<bean id="tracingCustomizer" class="example.SimpleMethodTracingCustomizer"/>

		<!-- ... and plug it into the desired Groovy bean via the 'customizer-ref' attribute -->
		<lang:groovy id="calculator"
			script-source="classpath:org/springframework/scripting/groovy/Calculator.groovy"
			customizer-ref="tracingCustomizer"/>
----

如果不使用 Spring 命名空间支持， 则仍然可以使用 `GroovyObjectCustomizer` 功能， 如以下示例所示:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<bean id="calculator" class="org.springframework.scripting.groovy.GroovyScriptFactory">
		<constructor-arg value="classpath:org/springframework/scripting/groovy/Calculator.groovy"/>
		<!-- define the GroovyObjectCustomizer (as an inner bean) -->
		<constructor-arg>
			<bean id="tracingCustomizer" class="example.SimpleMethodTracingCustomizer"/>
		</constructor-arg>
	</bean>

	<bean class="org.springframework.scripting.support.ScriptFactoryPostProcessor"/>
----

NOTE: 您还可以在与 Spring 的 `GroovyObjectCustomizer` 相同的位置指定一个 Groovy CompilationCustomizer(例如 `ImportCustomizer`)或是完整的 Groovy `CompilerConfiguration` 对象.  此外， 您可以在 `ConfigurableApplicationContext.setClassLoader` 级别为您的 bean 设置具有自定义配置的通用 `GroovyClassLoader`.  这也导致了 `GroovyClassLoader` 的共享使用， 因此建议在有大量脚本化 bean 的情况下使用(避免每个 bean 使用隔离的 `GroovyClassLoader` 实例).


[[dynamic-language-beans-bsh]]
=== BeanShell Beans

本节描述如何在 Spring 中使用 BeanShell bean.

https://beanshell.github.io/intro.html[BeanShell 主页] 包括以下描述:

----
BeanShell is a small, free, embeddable Java source interpreter with dynamic language
features, written in Java. BeanShell dynamically executes standard Java syntax and
extends it with common scripting conveniences such as loose types, commands, and method
closures like those in Perl and JavaScript.
----


与 Groovy 相比， BeanShell 支持的 bean 定义需要一些(小的)附加配置.  在 Spring 中实现 BeanShell 动态语言支持很有趣， 因为 Spring 创建了一个 JDK 动态代理， 该代理实现了 `<lang:bsh>` 元素的 s`script-interfaces` 属性值中指定的所有接口(这就是为什么必须 在属性值中提供至少一个接口， 因此在使用 BeanShell 支持的 bean 时对接口进行编程).  这意味着对 BeanShell 支持的对象的每个方法调用都将通过 JDK 动态代理调用机制进行.

现在， 我们可以展示一个使用基于 BeanShell 的 Bean 的完整工作示例， 该 Bean 实现了本章前面定义的 `Messenger` 接口.  我们再次显示 `Messenger` 接口的定义:

[source,java,indent=0,subs="verbatim,quotes"]
----
	package org.springframework.scripting;

	public interface Messenger {

		String getMessage();
	}
----

下面的示例显示了 `Messenger` 接口的 `BeanShell` "`implementation`":

[source,java,indent=0,subs="verbatim,quotes"]
----
	String message;

	String getMessage() {
		return message;
	}

	void setMessage(String aMessage) {
		message = aMessage;
	}
----

The following example shows the Spring XML that defines an "`instance`" of the above
"`class`" (again, we use these terms very loosely here):

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<lang:bsh id="messageService" script-source="classpath:BshMessenger.bsh"
		script-interfaces="org.springframework.scripting.Messenger">

		<lang:property name="message" value="Hello World!" />
	</lang:bsh>
----

有关可能需要使用基于 BeanShell 的 bean 的某些方案， 请参阅 <<dynamic-language-scenarios>>.

[[dynamic-language-scenarios]]
== Scenarios

用脚本语言定义 Spring 托管 Bean 可能会有所裨益的方案有很多， 而且也各不相同.  本节描述了 Spring 中对动态语言支持的两种可能的用例.

[[dynamic-language-scenarios-controllers]]
=== 脚本 Spring MVC Controllers

可以从使用动态语言支持的 bean 中受益的一组类是 Spring MVC 控制器的类.  在纯 Spring MVC 应用程序中， 通过 Web 应用程序的导航流在很大程度上取决于封装在 Spring MVC 控制器中的代码.  由于需要更新 Web 应用程序的导航流和其他表示层逻辑以响应支持问题或不断变化的业务需求， 因此通过编辑一个或多个动态语言源文件并查看它们， 很容易实现任何此类必需的更改.  更改立即反映在正在运行的应用程序的状态中.

请记住， 在像 Spring 这样的项目所拥护的轻量级架构模型中， 您通常旨在拥有一个非常浅的表示层， 而应用程序的所有繁琐的业务逻辑都包含在 domain 和服务层类中.  将 Spring MVC 控制器开发为支持动态语言的 Bean， 使您可以通过编辑和保存文本文件来更改表示层逻辑.  对此类动态语言源文件的任何更改(取决于配置)都会自动反映在由动态语言源文件支持的 Bean 中.

NOTE: 要对动态语言支持的 bean 进行任何更改的这种自动 "`pickup`"， 必须启用  "`refreshable beans`"  功能.  有关此功能的完整处理， 请参见 <<dynamic-language-refreshable-beans>>.

以下示例显示了使用 Groovy 动态语言实现的 `org.springframework.web.servlet.mvc.Controller`:

[source,groovy,indent=0,subs="verbatim,quotes"]
----
	// from the file '/WEB-INF/groovy/FortuneController.groovy'
	package org.springframework.showcase.fortune.web

	import org.springframework.showcase.fortune.service.FortuneService
	import org.springframework.showcase.fortune.domain.Fortune
	import org.springframework.web.servlet.ModelAndView
	import org.springframework.web.servlet.mvc.Controller

	import jakarta.servlet.http.HttpServletRequest
	import jakarta.servlet.http.HttpServletResponse

	class FortuneController implements Controller {

		@Property FortuneService fortuneService

		ModelAndView handleRequest(HttpServletRequest request,
				HttpServletResponse httpServletResponse) {
			return new ModelAndView("tell", "fortune", this.fortuneService.tellFortune())
		}
	}
----

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<lang:groovy id="fortune"
			refresh-check-delay="3000"
			script-source="/WEB-INF/groovy/FortuneController.groovy">
		<lang:property name="fortuneService" ref="fortuneService"/>
	</lang:groovy>
----



[[dynamic-language-scenarios-validators]]
=== 脚本验证

可以从动态语言支持的 bean 提供的灵活性中受益的， 使用 Spring 进行应用程序开发的另一个领域是验证领域. 与常规 Java 相比， 使用松散类型的动态语言(可能还支持内联正则表达式)来表达复杂的验证逻辑会更容易.

同样， 将验证器开发为动态语言支持的 bean， 使您可以通过编辑和保存简单的文本文件来更改验证逻辑. 任何此类更改(取决于配置)都会自动反映在正在运行的应用程序的执行中， 而无需重新启动应用程序

NOTE: 要对动态语言支持的 bean 进行任何更改的这种自动 "`pickup`"， 必须启用  "`refreshable beans`"  功能.  有关此功能的完整处理， 请参见 <<dynamic-language-refreshable-beans>>.

以下示例显示了使用 Groovy 动态语言实现的 Spring `org.springframework.validation.Validator`(请参阅 <<core.adoc#validator,
使用 Spring 的 `Validator` 接口进行验证>>， 以了解 `Validator` 接口):

[source,groovy,indent=0,subs="verbatim,quotes"]
----
	import org.springframework.validation.Validator
	import org.springframework.validation.Errors
	import org.springframework.beans.TestBean

	class TestBeanValidator implements Validator {

		boolean supports(Class clazz) {
			return TestBean.class.isAssignableFrom(clazz)
		}

		void validate(Object bean, Errors errors) {
			if(bean.name?.trim()?.size() > 0) {
				return
			}
			errors.reject("whitespace", "Cannot be composed wholly of whitespace.")
		}
	}
----




[[dynamic-language-final-notes]]
== 额外细节

最后一部分包含与动态语言支持有关的一些其他详细信息.

[[dynamic-language-final-notes-aop]]
=== AOP -- Advising Scripted Beans

您可以使用 Spring AOP 框架来通知脚本化 Bean.  实际上， Spring AOP 框架没有意识到通知使用的 Bean 可能是脚本 Bean， 因此您使用(或打算使用)的所有 AOP 用例和功能都可以与脚本 Bean 一起使用.  当通知脚本 bean 时， 不能使用基于类的代理.  您必须使用<<core.adoc#aop-proxying, interface-based proxies>>.

您不仅限于通知脚本化的 bean.  您还可以使用受支持的动态语言自己编写方面， 并使用此类 Bean 来通知其他 Spring Bean.  不过， 这确实是对动态语言支持的高级使用.

[[dynamic-language-final-notes-scopes]]
=== Scoping

万一这不是立即显而易见的话， 可以以与任何其他 Bean 相同的方式确定脚本 Bean 的范围.  各种 `<lang:language/>` 元素上的 `scope` 属性使您可以像使用常规 bean 一样控制基础脚本 bean 的范围.  (默认范围是 <<core.adoc#beans-factory-scopes-singleton, singleton>>， 与 "常规" bean一样. )

以下示例使用 `scope` 属性定义范围为 <<core.adoc#beans-factory-scopes-prototype, prototype>> 的 Groovy:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:lang="http://www.springframework.org/schema/lang"
		xsi:schemaLocation="
			http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/lang https://www.springframework.org/schema/lang/spring-lang.xsd">

		<lang:groovy id="messenger" script-source="classpath:Messenger.groovy" scope="prototype">
			<lang:property name="message" value="I Can Do The RoboCop" />
		</lang:groovy>

		<bean id="bookingService" class="x.y.DefaultBookingService">
			<property name="messenger" ref="messenger" />
		</bean>

	</beans>
----

有关 Spring 框架中作用域支持的完整讨论， 请参见 <<core.adoc#beans, The IoC Container>> 中的 <<core.adoc#beans-factory-scopes, Bean Scopes>>.

[[xsd-schemas-lang]]
=== The `lang` XML schema

Spring XML 配置中的 `lang` 元素用于处理以动态语言(例如 Groovy 或 BeanShell )编写的对象作为 Spring 容器中的 bean.

这些元素(和动态语言支持)在 <<dynamic-language, Dynamic Language Support>> 中全面介绍.  有关此支持和 `lang` 元素的完整详细信息， 请参见该章.

要使用 `lang` schema 中的元素， 您需要在 Spring XML 配置文件的顶部具有以下序言.  以下代码段中的文本引用了正确的架构， 以便您可以使用 `lang` 命名空间中的标记:

[source,xml,indent=0,subs="verbatim,quotes"]
----
    <?xml version="1.0" encoding="UTF-8"?>
    <beans xmlns="http://www.springframework.org/schema/beans"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:lang="http://www.springframework.org/schema/lang"
        xsi:schemaLocation="
            http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
            http://www.springframework.org/schema/lang https://www.springframework.org/schema/lang/spring-lang.xsd">

        <!-- bean definitions here -->

    </beans>
----

[[dynamic-language-resources]]
== Further Resources

以下链接提供了有关本章中引用的各种动态语言的更多资源:

* The https://www.groovy-lang.org/[Groovy] homepage
* The https://beanshell.github.io/intro.html[BeanShell] homepage
* The https://www.jruby.org[JRuby] homepage
