[[build-image]]
== 打包 OCI 镜像
该插件可以使用 https://buildpacks.io[Cloud Native Buildpacks] (CNB) 从可执行 jar 文件创建 https://github.com/opencontainers/image-spec[OCI image]。可以使用 `build-image` 目标来构建镜像。

NOTE: 出于安全原因，镜像以非 root 用户身份构建和运行。有关更多详细信息，请参见 {buildpacks-reference}/reference/spec/platform-api/#users[CNB specification]。

NOTE: `build-image` 任务不支持 <<packaging-executable-wars, 打包成 war>>.

最简单的入门方法是在项目上调用 `mvn spring-boot:build-image`。 每当调用 `package` 阶段时，都可以自动创建映像，如以下示例所示：

[source,xml,indent=0,subs="verbatim,attributes"]
----
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>build-image</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
----

TIP: 尽管 buildpack 是从  <<repackage,executable archive>> 运行的，但不必先执行 `repackage` 目标，因为必要时会自动创建可执行存档。 当构建映像重新打包应用程序时，它将应用与重新打包目标相同的设置，即可以使用 exclude 选项之一排除依赖项，并且默认情况下会自动排除 Devtools（您可以使用 `excludeDevtools`  属性进行控制）。

[[build-image-docker-daemon]]
=== Docker Daemon
`build-image` 任务需要访问 Docker 守护程序。 默认情况下，它将通过本地连接与 Docker 守护程序通信。 无需配置即可在所有支持的平台上使用 https://docs.docker.com/install/[Docker Engine]。

可以设置环境变量以将 `build-image` 任务配置为使用 https://minikube.sigs.k8s.io/docs/tasks/docker_daemon/[minikube 提供的 Docker 守护程序] 。 下表显示了环境变量及其值：

|===
| Environment variable | Description

| DOCKER_HOST
| URL containing the host and port for the Docker daemon - e.g. `tcp://192.168.99.100:2376`

| DOCKER_TLS_VERIFY
| Enable secure HTTPS protocol when set to `1` (optional)

| DOCKER_CERT_PATH
| Path to certificate and key files for HTTPS (required if `DOCKER_TLS_VERIFY=1`, ignored otherwise)
|===

在 Linux 和 macOS 上，启动 minikube 之后，可以使用命令 `eval $(minikube docker-env)` 设置这些环境变量。

[[build-image-customization]]
=== Image Customizations

该插件调用一个 {buildpacks-reference}/concepts/components/builder/[builder] 来协助镜像的生成。 该构建器包括多个  {buildpacks-reference}/concepts/components/buildpack[buildpacks]，可以检查应用程序以影响生成的镜像。 默认情况下，插件选择一个生成镜像。 生成的镜像名称是从项目属性推导出的。

`image` 属性可用于配置构建器应如何在项目上运行。下表总结了可用的属性及其默认值：

|===
| Parameter | Description | User property | Default value

| `builder`
| Name of the Builder image to use.
| `spring-boot.build-image.builder`
| `gcr.io/paketo-buildpacks/builder:base-platform-api-0.3`

| `runImage`
| Name of the run image to use.
| `spring-boot.build-image.runImage`
| No default value, indicating the run image specified in Builder metadata should be used.

| `name`
| {spring-boot-api}/buildpack/platform/docker/type/ImageReference.html#of-java.lang.String-[Image name] for the generated image.
| `spring-boot.build-image.imageName`
| `docker.io/library/${project.artifactId}:${project.version}`

| `env`
| Environment variables that should be passed to the builder.
|
|

| `cleanCache`
| Whether to clean the cache before building.
|
| `false`

| `verboseLogging`
| Enables verbose logging of builder operations.
|
| `false`
|===

NOTE: 该插件使用编译器的插件配置或 `maven.compiler.target` 属性检测项目的目标 Java 兼容性。 当使用默认的 Paketo 构建器和 buildpacks 时，插件会指示buildpacks 安装相同的 Java 版本。 您可以覆盖此行为，如 <<build-image-example-builder-configuration,builder configuration>>  示例中所示。

有关更多详细信息，另请参见 <<build-image-example-custom-image-builder,custom image builder>> 和 <<build-image-example-custom-image-name,custom image name>>。

include::goals/build-image.adoc[leveloffset=+1]


[[build-image-examples]]
=== 示例

[[build-image-example-custom-image-builder]]
==== Custom Image Builder
If you need to customize the builder used to create the image or the run image used to launch the built image, configure the plugin as shown in the following example:

[source,xml,indent=0,subs="verbatim,attributes"]
----
	<project>
		<build>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
					<configuration>
						<image>
							<builder>mine/java-cnb-builder</builder>
							<runImage>mine/java-cnb-run</runImage>
						</image>
					</configuration>
				</plugin>
			</plugins>
		</build>
	</project>
----

This configuration will use a builder image with the name `mine/java-cnb-builder` and the tag `latest`, and the run image named `mine/java-cnb-run` and the tag `latest`.

The builder and run image can be specified on the command line as well, as shown in this example:

[indent=0]
----
	$ mvn spring-boot:build-image -Dspring-boot.build-image.builder=mine/java-cnb-builder -Dspring-boot.build-image.runImage=mine/java-cnb-run
----



[[build-image-example-builder-configuration]]
==== Builder Configuration
If the builder exposes configuration options using environment variables, those can be set using the `env` attributes.

The following is an example of {paketo-java-reference}/#configuring-the-jvm-version[configuring the JVM version] used by the Paketo Java buildpacks at build time:

[source,xml,indent=0,subs="verbatim,attributes"]
----
	<project>
		<build>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
					<configuration>
						<image>
							<env>
								<BP_JVM_VERSION>8.*</BP_JVM_VERSION>
							</env>
						</image>
					</configuration>
				</plugin>
			</plugins>
		</build>
	</project>
----

In a similar way, Paketo Java buildpacks support {paketo-java-reference}/#runtime-jvm-configuration[configuring JVM runtime behavior].
Refer to the {paketo-java-reference}[Paketo documentation] for additional configuration options supported by Paketo Java buildpacks.

If there is a network proxy between the Docker daemon the builder runs in and network locations that buildpacks download artifacts from, you will need to configure the builder to use the proxy.
When using the Paketo builder, this can be accomplished by setting the `HTTPS_PROXY` and/or `HTTP_PROXY` environment variables as show in the following example:

[source,xml,indent=0,subs="verbatim,attributes"]
----
	<project>
		<build>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
					<configuration>
						<image>
							<env>
								<HTTP_PROXY>http://proxy.example.com</HTTP_PROXY>
								<HTTPS_PROXY>https://proxy.example.com</HTTPS_PROXY>
							</env>
						</image>
					</configuration>
				</plugin>
			</plugins>
		</build>
	</project>
----



[[build-image-example-custom-image-name]]
==== Custom Image Name
By default, the image name is inferred from the `artifactId` and the `version` of the project, something like `docker.io/library/${project.artifactId}:${project.version}`.
You can take control over the name, as shown in the following example:

[source,xml,indent=0,subs="verbatim,attributes"]
----
	<project>
		<build>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
					<configuration>
						<image>
							<name>example.com/library/${project.artifactId}</name>
						</image>
					</configuration>
				</plugin>
			</plugins>
		</build>
	</project>
----

NOTE: This configuration does not provide an explicit tag so `latest` is used.
It is possible to specify a tag as well, either using `${project.version}`, any property available in the build or a hardcoded version.

The image name can be specified on the command line as well, as shown in this example:

[indent=0]
----
	$ mvn spring-boot:build-image -Dspring-boot.build-image.imageName=example.com/library/my-app:v1
----

