[[build-image]]
== 打包 OCI 镜像
该插件可以使用 https://buildpacks.io[Cloud Native Buildpacks] (CNB) 从可执行 jar 文件创建 https://github.com/opencontainers/image-spec[OCI image]。可以使用 `build-image` 目标来构建镜像。

NOTE: 出于安全原因，镜像以非 root 用户身份构建和运行。有关更多详细信息，请参见 {buildpacks-reference}/reference/spec/platform-api/#users[CNB specification]。

NOTE: `build-image` 任务不支持 <<packaging-executable-wars, 打包成 war>>.

最简单的入门方法是在项目上调用 `mvn spring-boot:build-image`。 每当调用 `package` 阶段时，都可以自动创建映像，如以下示例所示：

[source,xml,indent=0,subs="verbatim,attributes"]
----
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<executions>
					<execution>
						<goals>
							<goal>build-image</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
----

TIP: 尽管 buildpack 是从  <<repackage,executable archive>> 运行的，但不必先执行 `repackage` 目标，因为必要时会自动创建可执行存档。 当构建映像重新打包应用程序时，它将应用与重新打包目标相同的设置，即可以使用 exclude 选项之一排除依赖项，并且默认情况下会自动排除 Devtools（您可以使用 `excludeDevtools`  属性进行控制）。

[[build-image-docker-daemon]]
=== Docker Daemon
`build-image` 任务需要访问 Docker 守护程序。 默认情况下，它将通过本地连接与 Docker 守护程序通信。 无需配置即可在所有支持的平台上使用 https://docs.docker.com/install/[Docker Engine]。

可以设置环境变量以将 `build-image` 任务配置为使用 https://minikube.sigs.k8s.io/docs/tasks/docker_daemon/[minikube 提供的 Docker 守护程序] 。 下表显示了环境变量及其值：

|===
| Environment variable | Description

| DOCKER_HOST
| URL containing the host and port for the Docker daemon - e.g. `tcp://192.168.99.100:2376`

| DOCKER_TLS_VERIFY
| Enable secure HTTPS protocol when set to `1` (optional)

| DOCKER_CERT_PATH
| Path to certificate and key files for HTTPS (required if `DOCKER_TLS_VERIFY=1`, ignored otherwise)
|===

在 Linux 和 macOS 上，启动 minikube 之后，可以使用命令 `eval $(minikube docker-env)` 设置这些环境变量。

[[build-image-customization]]
=== Image Customizations

该插件调用一个 {buildpacks-reference}/concepts/components/builder/[builder] 来协助镜像的生成。 该构建器包括多个  {buildpacks-reference}/concepts/components/buildpack[buildpacks]，可以检查应用程序以影响生成的镜像。 默认情况下，插件选择一个生成镜像。 生成的镜像名称是从项目属性推导出的。

`image` 属性可用于配置构建器应如何在项目上运行。下表总结了可用的属性及其默认值：

|===
| Parameter | Description | User property | Default value

| `builder`
| Name of the Builder image to use.
| `spring-boot.build-image.builder`
| `gcr.io/paketo-buildpacks/builder:base-platform-api-0.3`

| `runImage`
| Name of the run image to use.
| `spring-boot.build-image.runImage`
| No default value, indicating the run image specified in Builder metadata should be used.

| `name`
| {spring-boot-api}/buildpack/platform/docker/type/ImageReference.html#of-java.lang.String-[Image name] for the generated image.
| `spring-boot.build-image.imageName`
| `docker.io/library/${project.artifactId}:${project.version}`

| `env`
| Environment variables that should be passed to the builder.
|
|

| `cleanCache`
| Whether to clean the cache before building.
|
| `false`

| `verboseLogging`
| Enables verbose logging of builder operations.
|
| `false`
|===

NOTE: 该插件使用编译器的插件配置或 `maven.compiler.target` 属性检测项目的目标 Java 兼容性。 当使用默认的 Paketo 构建器和 buildpacks 时，插件会指示buildpacks 安装相同的 Java 版本。 您可以覆盖此行为，如 <<build-image-example-builder-configuration,builder configuration>>  示例中所示。

有关更多详细信息，另请参见 <<build-image-example-custom-image-builder,custom image builder>> 和 <<build-image-example-custom-image-name,custom image name>>。

include::goals/build-image.adoc[leveloffset=+1]


[[build-image-examples]]
=== 示例

[[build-image-example-custom-image-builder]]
==== Custom Image Builder
如果需要自定义用于创建映像的 Builder 或用于启动生成的映像的运行映像，请使用如下配置插件：

[source,xml,indent=0,subs="verbatim,attributes"]
----
	<project>
		<build>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
					<configuration>
						<image>
							<builder>mine/java-cnb-builder</builder>
							<runImage>mine/java-cnb-run</runImage>
						</image>
					</configuration>
				</plugin>
			</plugins>
		</build>
	</project>
----

此配置将使用名称为 `mine/java-cnb-builder` 的构建器映像的最新版本(`latest` tag)，以及名为 `mine/java-cnb-run`  的运行映像的最新版本(`latest` tag)。

构建器和运行映像也可以在命令行上指定，如本示例所示：

[indent=0]
----
	$ mvn spring-boot:build-image -Dspring-boot.build-image.builder=mine/java-cnb-builder -Dspring-boot.build-image.runImage=mine/java-cnb-run
----



[[build-image-example-builder-configuration]]
==== 构建器配置
如果构建器使用环境变量暴露配置选项，则可以使用 `env` 属性进行设置。

以下是配置在构建时由 Paketo Java buildpack {paketo-java-reference}/#configuring-the-jvm-version[configuring the JVM version]  的示例：

[source,xml,indent=0,subs="verbatim,attributes"]
----
	<project>
		<build>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
					<configuration>
						<image>
							<env>
								<BP_JVM_VERSION>8.*</BP_JVM_VERSION>
							</env>
						</image>
					</configuration>
				</plugin>
			</plugins>
		</build>
	</project>
----

以类似的方式，Paketo Java buildpacks 支持 {paketo-java-reference}/#runtime-jvm-configuration[配置 JVM 运行时行为]。 请参阅 {paketo-java-reference}[Paketo 文档] 以获取 Paketo Java buildpacks 支持的其他配置选项。

如果构建器在其运行的 Docker 守护程序与构建打包下载工件的网络位置之间存在网络代理，则需要将构建器配置为使用代理。 使用 Paketo 构建器时，可以通过设置 `HTTPS_PROXY` and/or `HTTP_PROXY` 环境变量来实现，如以下示例所示：

[source,xml,indent=0,subs="verbatim,attributes"]
----
	<project>
		<build>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
					<configuration>
						<image>
							<env>
								<HTTP_PROXY>http://proxy.example.com</HTTP_PROXY>
								<HTTPS_PROXY>https://proxy.example.com</HTTPS_PROXY>
							</env>
						</image>
					</configuration>
				</plugin>
			</plugins>
		</build>
	</project>
----

[[build-image-example-custom-image-name]]
==== 自定义镜像名称
默认情况下，镜像名称是根据 `artifactId` 和项目版本来推断的，例如 `docker.io/library/${project.artifactId}:${project.version}`。您可以控制名称，如以下示例所示：

[source,xml,indent=0,subs="verbatim,attributes"]
----
	<project>
		<build>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
					<configuration>
						<image>
							<name>example.com/library/${project.artifactId}</name>
						</image>
					</configuration>
				</plugin>
			</plugins>
		</build>
	</project>
----

NOTE: 此配置未显式提供标签，因此使用最新的。也可以使用 `${project.version}`，构建中可用的任何属性或硬编码版本来指定标签。


镜像名称也可以在命令行上指定，如以下示例所示:

[indent=0]
----
	$ mvn spring-boot:build-image -Dspring-boot.build-image.imageName=example.com/library/my-app:v1
----

