[[getting]]
= Getting Spring Security

本节讨论了有关获取Spring Security二进制文件的所有信息。 有关如何获取源代码的信息，请参见<<community-source,第2.3节 "源代码">> 。

== Release 版本号

Spring Security版本的格式为MAJOR.MINOR.PATCH，如下：

* MAJOR 版本可能包含重大更改。通常，这样做是为了提供改进的安全性以匹配现代安全性实践
* MINOR 版本包含增强功能，但被视为被动更新
* PATCH 级别应该是完全兼容的，向前和向后兼容，可能存在修正错误的更改除外。


[[maven]]
== 使用 Maven
与大多数开源项目一样，Spring Security将其依赖部署为Maven工件。 本节中的主题提供有关使用Maven时如何使用Spring Security的详细信息。

[[getting-maven-boot]]
=== 使用 Spring Boot

Spring Boot提供了一个 `spring-boot-starter-security` 起步依赖，它将 Spring Security 相关的依赖聚合在一起。
使用起步依赖最简单且首选的方法是通过使用IDE集成(https://joshlong.com/jl/blogPost/tech_tip_geting_started_with_spring_boot.html[Eclipse], https://www.jetbrains.com/help/idea/spring-boot.html#d1489567e2[IntelliJ], https://github.com/AlexFalappa/nb-springboot/wiki/Quick-Tour[NetBeans])或通过 `https://start.spring.io` 使用 https://docs.spring.io/initializr/docs/current/reference/htmlsingle/[Spring Initializr]。

另外，您可以手动添加启动依赖，如以下示例所示:


.pom.xml
====
[source,xml,subs="verbatim,attributes"]
----
<dependencies>
	<!-- ... other dependency elements ... -->
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-security</artifactId>
	</dependency>
</dependencies>
----
====

由于Spring Boot提供了Maven BOM来管理依赖版本，因此您无需指定版本。 如果您希望覆盖Spring Security版本，可以通过提供Maven属性来实现，如以下示例所示：

.pom.xml
====
[source,xml,subs="verbatim,attributes"]
----
<properties>
	<!-- ... -->
	<spring-security.version>{spring-security-version}</spring-security.version>
</dependencies>
----
====

由于Spring Security仅在主要版本中进行重大更改，因此可以将较新版本的Spring Security与Spring Boot一起使用是安全的。 但是，有时您可能还需要更新Spring Framework的版本。 您可以通过添加Maven属性来执行此操作，如以下示例所示：

.pom.xml
====
[source,xml,subs="verbatim,attributes"]
----
<properties>
	<!-- ... -->
	<spring.version>{spring-core-version}</spring.version>
</dependencies>
----
====

如果使用其他功能（例如LDAP，OpenID和其他功能），则还需要包括相应 <<modules,项目模块>>。

[[getting-maven-no-boot]]
=== 不使用 Spring Boot

使用不带Spring Boot的Spring Security时，首选方法是使用Spring Security的BOM，以确保在整个项目中使用一致的Spring Security版本。 以下示例显示了如何执行此操作：

.pom.xml
====
[source,xml,ubs="verbatim,attributes"]
----
<dependencyManagement>
	<dependencies>
		<!-- ... other dependency elements ... -->
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-bom</artifactId>
			<version>{spring-security-version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
----
====

最小化的Spring Security Maven依赖关系集通常如下所示：

.pom.xml
====
[source,xml,subs="verbatim,attributes"]
----
<dependencies>
	<!-- ... other dependency elements ... -->
	<dependency>
		<groupId>org.springframework.security</groupId>
		<artifactId>spring-security-web</artifactId>
	</dependency>
	<dependency>
		<groupId>org.springframework.security</groupId>
		<artifactId>spring-security-config</artifactId>
	</dependency>
</dependencies>
----
====

如果使用其他功能（例如LDAP，OpenID和其他功能），则还需要包括相应 <<modules,项目模块>>。

Spring Security是根据Spring Framework {spring-core-version} 构建的，但通常应与任何较新版本的Spring Framework 5.x一起使用。
Spring Security的可传递依赖解决了Spring Framework {spring-core-version} 的事实，这可能会引起奇怪的类路径问题，因此许多用户可能会误以为是。 解决此问题的最简单方法是在 `pom.xml` 的 `<dependencyManagement>` 部分中使用 `spring-framework-bom`，如以下示例所示：

.pom.xml
====
[source,xml,subs="verbatim,attributes"]
----
<dependencyManagement>
	<dependencies>
		<!-- ... other dependency elements ... -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-framework-bom</artifactId>
			<version>{spring-core-version}</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>
	</dependencies>
</dependencyManagement>
----
====

前面的示例确保Spring Security的所有传递依赖都使用Spring  {spring-core-version} 模块。

NOTE: 这种方法使用了Maven的 "`bill of materials`" (BOM)概念，并且仅在Maven 2.0.9+中可用。 有关如何解决依赖关系的其他详细信息，请参阅 https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html[Maven的 依赖关系机制简介]文档。

[[maven-repositories]]
=== Maven 仓库
所有GA版本（即以.RELEASE结尾的版本）均已部署到Maven Central，因此无需在pom中声明其他Maven存储库。

如果使用SNAPSHOT版本，则需要定义Spring Snapshot存储库，如以下示例所示：

.pom.xml
====
[source,xml]
----
<repositories>
	<!-- ... possibly other repository elements ... -->
	<repository>
		<id>spring-snapshot</id>
		<name>Spring Snapshot Repository</name>
		<url>https://repo.spring.io/snapshot</url>
	</repository>
</repositories>
----
====

如果使用里程碑版本或候选版本，则需要定义Spring Milestone存储库，如以下示例所示：

.pom.xml
====
[source,xml]
----
<repositories>
	<!-- ... possibly other repository elements ... -->
	<repository>
		<id>spring-milestone</id>
		<name>Spring Milestone Repository</name>
		<url>https://repo.spring.io/milestone</url>
	</repository>
</repositories>
----
====

[[getting-gradle]]
== 使用 Gradle

作为大多数开源项目，Spring Security将其依赖部署为Maven工件，从而提供了一流的Gradle支持。 以下主题详细介绍了使用Gradle时如何使用Spring Security。

[[getting-gradle-boot]]
=== 使用 Spring Boot

Spring Boot提供了一个 `spring-boot-starter-security` 起步依赖，它将 Spring Security 相关的依赖聚合在一起。
使用起步依赖最简单且首选的方法是通过使用IDE集成( https://joshlong.com/jl/blogPost/tech_tip_geting_started_with_spring_boot.html[Eclipse], https://www.jetbrains.com/help/idea/spring-boot.html#d1489567e2[IntelliJ], https://github.com/AlexFalappa/nb-springboot/wiki/Quick-Tour[NetBeans])或通过 `https://start.spring.io` 使用 https://docs.spring.io/initializr/docs/current/reference/htmlsingle/[Spring Initializr]。

另外，您可以手动添加起步依赖，如以下示例所示：

.build.gradle
====
[source,groovy]
[subs="verbatim,attributes"]
----
dependencies {
	compile "org.springframework.boot:spring-boot-starter-security"
}
----
====

由于Spring Boot提供了Maven BOM来管理依赖版本，因此您无需指定版本。 如果您希望覆盖Spring Security版本，可以通过提供Gradle属性来实现，如以下示例所示：

.build.gradle
====
[source,groovy]
[subs="verbatim,attributes"]
----
ext['spring-security.version']='{spring-security-version}'
----
====

由于Spring Security仅在主要版本中进行重大更改，因此可以将较新版本的Spring Security与Spring Boot一起使用是安全的。 但是，有时您可能还需要更新Spring Framework的版本。 您可以通过添加Gradle属性来执行此操作，如以下示例所示：

.build.gradle
====
[source,groovy]
[subs="verbatim,attributes"]
----
ext['spring.version']='{spring-core-version}'
----
====

如果使用其他功能（例如LDAP，OpenID和其他功能），则还需要包括相应 <<modules,项目模块>>。

=== 不使用 Spring Boot

使用不带Spring Boot的Spring Security时，首选方法是使用Spring Security的BOM，以确保在整个项目中使用一致的Spring Security版本。
您可以使用 https://github.com/spring-gradle-plugins/dependency-management-plugin[Dependency Management Plugin] 插件来做到这一点，如以下示例所示：

.build.gradle
====
[source,groovy]
[subs="verbatim,attributes"]
----
plugins {
	id "io.spring.dependency-management" version "1.0.6.RELEASE"
}

dependencyManagement {
	imports {
		mavenBom 'org.springframework.security:spring-security-bom:{spring-security-version}'
	}
}
----
====

最小的Spring Security Maven依赖关系集通常如下所示:

.build.gradle
====
[source,groovy]
[subs="verbatim,attributes"]
----
dependencies {
	compile "org.springframework.security:spring-security-web"
	compile "org.springframework.security:spring-security-config"
}
----
====

如果使用其他功能（例如LDAP，OpenID和其他功能），则还需要包括相应 <<modules,项目模块>>。


Spring Security是根据Spring Framework {spring-core-version} 构建的，但通常应与任何较新版本的Spring Framework 5.x一起使用。
Spring Security的可传递依赖解决了Spring Framework {spring-core-version} 的事实，这可能会引起奇怪的类路径问题，因此许多用户可能会误以为是。 解决此问题的最简单方法是在 `pom.xml` 的 `<dependencyManagement>` 部分中使用 `spring-framework-bom`，如以下示例所示：

.build.gradle
====
[source,groovy]
[subs="verbatim,attributes"]
----
plugins {
	id "io.spring.dependency-management" version "1.0.6.RELEASE"
}

dependencyManagement {
	imports {
		mavenBom 'org.springframework:spring-framework-bom:{spring-core-version}'
	}
}
----
====

前面的示例确保Spring Security的所有传递依赖都使用Spring {spring-core-version} 模块。

[[gradle-repositories]]
=== Gradle 仓库
所有GA版本（即以.RELEASE结尾的版本）均已部署到Maven Central，因此使用 mavenCentral() 存储库足以满足GA版本的要求。 以下示例显示了如何执行此操作：

.build.gradle
====
[source,groovy]
----
repositories {
	mavenCentral()
}
----
====

如果使用SNAPSHOT版本，则需要定义Spring Snapshot存储库，如以下示例所示：

.build.gradle
====
[source,groovy]
----
repositories {
	maven { url 'https://repo.spring.io/snapshot' }
}
----
====

如果使用里程碑版本或候选版本，则需要定义 Spring Milestone存储库，如以下示例所示：

.build.gradle
====
[source,groovy]
----
repositories {
	maven { url 'https://repo.spring.io/milestone' }
}
----
====
