// FIXME: This might make sense in Getting Spring Security along with the artifact information

[[modules]]
= 项目模块
在 Spring Security 3.0, 代码库被分割到单独的jar，这样可以更清楚的分隔不用功能区域和第三方依赖。如果你使用Maven构建你的项目，那么这些都是需要你添加到你的 `pom.xml` 中的. 甚至你没有使用Maven，我们建议你请求 `pom.xml` 文件来获取第三方依赖和版本。另一个好办法是检查实例应用程序的库。

[[spring-security-core]]
== 核心模块 -- `spring-security-core.jar`
包含核心的验证和访问控制类和接口，远程支持和基本的配置API。任何使用Spring Security的应用程序都需要这个模块。支持独立应用程序、远程客户端、服务层方法安全和JDBC用户配置。包含以下顶层包:

* `org.springframework.security.core`
* `org.springframework.security.access`
* `org.springframework.security.authentication`
* `org.springframework.security.provisioning`

[[spring-security-remoting]]
== 远程调用 -- `spring-security-remoting.jar`
提供与 Spring Remoting 的集成，通常你不需要这个模块，除非你挣使用 Spring Remoting 编写远程客户端。主要的包是 `org.springframework.security.remoting`.


[[spring-security-web]]
== Web -- `spring-security-web.jar`
该模块包含过滤器和相关的 Web 安全基础结构代码。 它包含任何与 Servlet API 相关的内容。 如果需要 Spring Security Web 认证服务和基于URL的访问控制，则需要它。 主要包是 `org.springframework.security.web`.


[[spring-security-config]]
== 配置 -- `spring-security-config.jar`
包含安全命名空间的解析和 Java 配置代码。如果您使用 Spring Security XML 命名空间进行配置或 Spring Security 的Java配置支持，则需要它。 主包名为  `org.springframework.security.config`.这些类都不打算直接在应用程序中使用。


[[spring-security-ldap]]
== LDAP -- `spring-security-ldap.jar`
LDAP 验证和配置代码，如果你需要使用 LDAP 验证和管理 LDAP 用户实体，你需要这个模块。主包名为 `org.springframework.security.ldap`.


[[spring-security-oauth2-core]]
== OAuth 2.0 核心包 -- `spring-security-oauth2-core.jar`
`spring-security-oauth2-core.jar` 包含核心类和接口，这些类和接口提供对 OAuth 2.0授权框架和 OpenID Connect Core 1.0的支持。 使用 OAuth 2.0 或 OpenID Connect Core 1.0的应用程序（例如客户端，资源服务器和授权服务器）需要它。 顶层的包是 `org.springframework.security.oauth2.core`.


[[spring-security-oauth2-client]]
== OAuth 2.0 客户端 -- `spring-security-oauth2-client.jar`
`spring-security-oauth2-client.jar` 包含 Spring Security 对 OAuth 2.0 授权框架和 OpenID Connect Core 1.0的客户端支持。 使用 OAuth 2.0登录 或 OAuth客户端支持的应用程序需要使用它。 顶层的包是 `org.springframework.security.oauth2.client`.


[[spring-security-oauth2-jose]]
== OAuth 2.0 JOSE -- `spring-security-oauth2-jose.jar`
`spring-security-oauth2-jose.jar` 包含 Spring Security 对 JOSE（Javascript对象签名和加密）框架的支持。 JOSE 框架旨在提供一种在各方之间安全地转移 `claims` 的方法。 它是根据一系列规范构建的：

* JSON Web Token (JWT)
* JSON Web Signature (JWS)
* JSON Web Encryption (JWE)
* JSON Web Key (JWK)

它包含以下顶级包:

* `org.springframework.security.oauth2.jwt`
* `org.springframework.security.oauth2.jose`

[[spring-security-oauth2-resource-server]]
== OAuth 2.0 资源 服务器 -- `spring-security-oauth2-resource-server.jar`
`spring-security-oauth2-resource-server.jar` 包含 Spring Security对OAuth 2.0资源服务器的支持。 它用于通过 OAuth 2.0 Bearer 令牌保护API。 顶层的包是 `org.springframework.security.oauth2.server.resource`.

[[spring-security-acl]]
== ACL -- `spring-security-acl.jar`
ACL专门的领域对象的实现。用来在你的应用程序中应用安全特定的领域对象实例。主包名为 `org.springframework.security.acls`.


[[spring-security-cas]]
== CAS -- `spring-security-cas.jar`
Spring Security 的 CAS 客户端集成。如果你想用 CAS 的 SSO 服务器使用 Spring Security 网页验证需要该模块。顶层的包是 `org.springframework.security.cas`.


[[spring-security-openid]]
== OpenID -- `spring-security-openid.jar`
该模块包含 OpenID Web 身份验证支持。 它用于根据外部 OpenID 服务器对用户进行身份验证。 顶层的包是 `org.springframework.security.openid`。 它需要OpenID4Java。

[[spring-security-test]]
== 测试 -- `spring-security-test.jar`
该模块包含对使用 Spring Security 进行测试的支持。
