[[data.access.appendix]]
= 附录

[[data.access.xsd-schemas]]
== XML Schemas

附录的这一部分列出了用于数据访问的 XML schema,包括以下内容:

* <<xsd-schemas-tx>>
* <<xsd-schemas-jdbc>>

[[xsd-schemas-tx]]
=== `tx` Schema

`tx` 标签处理 Spring 对事务的全面支持中所有这些 bean 的配置. 这些标签在标题为<<data-access.adoc#transaction, 事务管理>>的章节中介绍.
.

TIP: 我们强烈建议您查看 Spring 发行版附带的 `spring-tx.xsd` 文件.
此文件包含 Spring 的事务配置的 XML schema,并涵盖 `tx` 命名空间中的所有各种元素,包括属性默认值和类似信息.
该文件以内联方式记录,因此,为了遵守 DRY(不要重复自己) 原则,此处不再重复这些信息.

为了完整性,要使用 `tx` schema 中的元素,您需要在 Spring XML 配置文件的顶部包含以下代码. 以下代码段中的文本引用了正确的 schema,以便您可以使用 `tx` 命名空间中的标记:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:aop="http://www.springframework.org/schema/aop"
		xmlns:tx="http://www.springframework.org/schema/tx" <1>
		xsi:schemaLocation="
			http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/tx https://www.springframework.org/schema/tx/spring-tx.xsd <2>
			http://www.springframework.org/schema/aop https://www.springframework.org/schema/aop/spring-aop.xsd">

		<!-- bean definitions here -->

	</beans>
----

<1> 声明 `tx` 命名空间的使用.
<2> 指定位置(使用其他 schema 位置) .

NOTE: 通常,当您使用 `tx` 命名空间中的元素时,您还使用了 `aop` 命名空间中的元素(因为 Spring 中的声明式事务支持是通过使用 AOP 实现的) . 前面的 XML 片段包含引用 `aop` schema 所需的相关行,以便您可以使用 `aop` 命名空间中的元素.

[[xsd-schemas-jdbc]]
=== `jdbc` Schema

jdbc 元素使您可以快速配置嵌入式数据库 或初始化现有数据源. 这些元素分别记录在<<data-access.adoc#jdbc-embedded-database-support, 嵌入式数据库支持>> 和<<data-access.adoc#jdbc-initializing-datasource, 初始化数据源>>中.

要使用 jdbc Schema 中的元素,需要在 Spring XML 配置文件的顶部包含以下代码.
以下代码段中的文本引用了正确的 Schema,以便您可以使用 jdbc 命名空间中的元素:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:jdbc="http://www.springframework.org/schema/jdbc" <1>
		xsi:schemaLocation="
			http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/jdbc https://www.springframework.org/schema/jdbc/spring-jdbc.xsd"> <2>

		<!-- bean definitions here -->

	</beans>
----
<1> 声明 `jdbc` 的命名空间.
<2> 指定位置(使用其他 Schema 位置) .

