[[getting-started]]
= 入门

想要开始插件, 首先需要把下面的代码加入你的程序中

ifeval::["{version-type}" == "RELEASE"]
该插件已发布到  https://plugins.gradle.org/plugin/org.springframework.boot[Gradle 的插件管理中心] , 可以使用 `plugins` 块进行应用:
[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/getting-started/apply-plugin-release.gradle[]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/getting-started/apply-plugin-release.gradle.kts[]
----
endif::[]
ifeval::["{version-type}" == "MILESTONE"]
该插件已发布到 Spring milestones repository , 可以使用 `plugins` 块进行应用:

将以下配置添加到 `settings.gradle` (Groovy) 或 `settings.gradle.kts` (Kotlin) 脚本中:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/getting-started/milestone-settings.gradle[]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/getting-started/milestone-settings.gradle.kts[]
----

The plugin can then be applied using the `plugins` block:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/getting-started/apply-plugin-release.gradle[]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/getting-started/apply-plugin-release.gradle.kts[]
----
endif::[]
ifeval::["{version-type}" == "SNAPSHOT"]
该插件已发布到 Spring 快照存储库。 Gradle 可以配置为使用快照存储库，然后可以使用 `plugins` 块应用插件。要将 Gradle 配置为使用快照存储库，请将以下内容添加到您的 `settings.gradle` (Groovy) 或 `settings.gradle.kts` (Kotlin):

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/getting-started/snapshot-settings.gradle[]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/getting-started/snapshot-settings.gradle.kts[]
----

然后可以使用  `plugins` 块应用插件:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/getting-started/apply-plugin-release.gradle[]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/getting-started/apply-plugin-release.gradle.kts[]
----
endif::[]

使用这个插件可以让减少项目的改动. 而且, 会检测其他插件的使用或者更新. 比如, 当应用了 java 插件, 会自动在构建时打包成可执行的 jar.
一个经典的 Spring Boot 项目至少会使用  {groovy-plugin}[`groovy`], {java-plugin}[`java`] 或 {kotlin-plugin}[`org.jetbrains.kotlin.jvm`] 和 {dependency-management-plugin}[`io.spring.dependency-management`] 插件

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/getting-started/typical-plugins.gradle[tags=apply]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/getting-started/typical-plugins.gradle.kts[tags=apply]
----

在使用其他插件的时候, Spring Boot 插件会有怎样的行为?
要了解有关在应用其他插件时 Spring Boot 插件的行为的更多信息, 请参见 <<reacting-to-other-plugins, reacting to other plugins>>.