[[integrating-with-actuator]]
= 整合 Actuator


[[integrating-with-actuator.build-info]]
== 生成构建信息

Spring Boot Actuator 的 `info` endpoint 自动发布 `META-INF/build-info.properties` 文件里的信息. {build-info-javadoc}[`BuildInfo`] 任务可以用来生成这个文件. 最简单的方式是通过插件的 DSL 使用任务:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/integrating-with-actuator/build-info-basic.gradle[tags=build-info]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/integrating-with-actuator/build-info-basic.gradle.kts[tags=build-info]
----

这会配置一个  bootBuildInfo  的任务  {build-info-javadoc}[`BuildInfo`], 并且如果他存在, 会让 Java 插件的 `classes` 任务基于它. 任务的目标目录将会是 `META-INF` 在主源设置的资源的输出目录(通常是 `build/resources/main`).

默认的, 生成的信息是从项目里扩展 出来的:

|===
| Property | Default value

| `build.artifact`
| `bootJar` 或者 `bootWar` 任务的 base name,

| `build.group`
| The group of the project

| `build.name`
| The name of the project

| `build.version`
| The version of the project

| `build.time`
| The time at which the project is being built

|===

可以使用 DSL 自定义属性:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/integrating-with-actuator/build-info-custom-values.gradle[tags=custom-values]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/integrating-with-actuator/build-info-custom-values.gradle.kts[tags=custom-values]
----

要从生成的构建信息中省略任何默认属性，请将其名称添加到 excludes 中。
例如，可以按如下方式排除  `time` 属性：

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/integrating-with-actuator/build-info-exclude-time.gradle[tags=exclude-time]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/integrating-with-actuator/build-info-exclude-time.gradle.kts[tags=exclude-time]
----

`build.time` 的默认值为构建项目的瞬间.  这样做的副作用是该任务永远不会是最新的.  结果, 构建将花费更长的时间, 因为必须执行更多的任务, 包括项目的测试.
另一个副作用是任务的输出将始终更改, 因此构建将不会真正可重复.  如果您对构建性能或可重复性的重视程度高于 `build.time` 属性的准确性, 请 exclude `time` 属性.

可以添加额外的构建信息:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/integrating-with-actuator/build-info-additional.gradle[tags=additional]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/integrating-with-actuator/build-info-additional.gradle.kts[tags=additional]
----
