[[packaging-executable]]
= 打包可执行文件

插件可以创建可执行文件( jar 文件或者 war 文件), 里面包含所有应用的依赖并且可以使用 `java -jar` 执行.

[[packaging-executable.jars]]
== 打包可执行 jars

可以使用 `bootJar` 任务构建可执行的 jars. 如果应用了 java 插件, 这个任务会自动的创建, 并且是 {boot-jar-javadoc}[`BootJar`] 的实例. `assemble` 任务会自动配置依赖于 `bootJar` 任务, 所以运行 `assemble` (or `build`)  也会运行 `bootJar` 任务.

[[packaging-executable.wars]]
== 打包可执行 wars

可以使用 `bootWar` 任务构建可执行的 wars.如果应用了 `war` 插件,  这个任务会自动的创建, 并且是 {boot-war-javadoc}[`BootWar`] 的实例. `assemble` 任务会自动配置依赖于 `bootWar` 任务, 所以运行 `assemble` (or `build`)  也会运行 `bootWar` 任务.

[[packaging-executable.wars.deployable]]
=== 打包可执行和可部署的 wars

可以打包 war 文件, 以便可以使用 `java -jar` 执行该文件并将其部署到外部容器中.  为此, 应将嵌入式 Servlet 容器依赖添加到提供的 Runtime 配置中, 例如:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/war-container-dependency.gradle[tags=dependencies]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/war-container-dependency.gradle.kts[tags=dependencies]
----

这样可以确保在打包后的 war 文件中的 `WEB-INF/lib-provided` 提供的目录中不会与外部容器自己的类冲突.

NOTE: `providedRuntime` 优先于 Gradle 的  `compileOnly` 配置, 因为除其他限制外, compileOnly 依赖不在测试类路径上, 因此任何基于 Web 的集成测试都将失败.

[[packaging-executable.and-plain-archives]]
== 打包可执行和 Plain 构件

默认情况下，当配置了 `bootJar` 或 `bootWar` 任务时，`jar` 或 `war` 任务配置为使用 `plain` 作为其归档分类器的约定。
这确保了 `bootJar` 和 `jar` 或 `bootWar` 和 `war` 具有不同的输出位置，允许同时构建可执行存档和普通存档。

如果您希望可执行存档而不是普通存档使用分类器，请按照以下示例中的 `jar` 和 `bootJar` 任务配置分类器：

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-jar-and-jar-classifiers.gradle[tags=classifiers]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-jar-and-jar-classifiers.gradle.kts[tags=classifiers]
----

或者，如果您希望根本不构建普通构件，请禁用其任务，如下面的 `jar` 任务示例所示：

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/only-boot-jar.gradle[tags=disable-jar]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/only-boot-jar.gradle.kts[tags=disable-jar]
----

WARNING: 创建原生镜像时，请勿禁用 `jar` `任务。 有关详细信息，请参阅 https://github.com/spring-projects/spring-boot/issues/33238[#33238]。

[[packaging-executable.configuring]]
== 配置可执行文件打包

BootJar 和 BootWar

{boot-jar-javadoc}[`BootJar`] 和 {boot-war-javadoc}[`BootWar`] 任务分别是 Gradle 的 `jar` 或者 `war` 任务的子类. 所以, 所有的在打包 `jar` 或者 `war` 时用的标准配置都对可执行的 `jar` 或者 `war` 可用.
当然也有对可执行 jars 或者 wars 的特殊配置.

[[packaging-executable.configuring.main-class]]
=== 配置主类

默认的, 可执行文件的主类会自动的在 main source set(源集)的输出里查找一个带有 `public static void main(String[])` 的方法. 主类也可以显示的使用 `mainClass` 设置:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-jar-main-class.gradle[tags=main-class]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-jar-main-class.gradle.kts[tags=main-class]
----

或者, 可以使用 Spring Boot DSL 的 `mainClass` 属性在项目范围内配置主类名称:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/spring-boot-dsl-main-class.gradle[tags=main-class]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/spring-boot-dsl-main-class.gradle.kts[tags=main-class]
----

另外, 如果应用了 {application-plugin}[`application` plugin] 可以这么设置 `mainClass` 属性:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/application-plugin-main-class.gradle[tags=main-class]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/application-plugin-main-class.gradle.kts[tags=main-class]
----

最后, `Start-Class` 属性可以在任务的 manifest 里配置:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-jar-manifest-main-class.gradle[tags=main-class]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-jar-manifest-main-class.gradle.kts[tags=main-class]
----

NOTE: 如果主类是用 Kotlin 编写的,则应使用生成的 Java 类的名称. 默认情况下,这是添加了 `Kt` 后缀的 Kotlin 类的名称. 例如,`ExampleApplication` `变为ExampleApplicationKt`. 如果使用 `@JvmName` 定义了另一个名称,则应使用该名称.

[[packaging-executable.configuring.including-development-only-dependencies]]
=== Including Development-only Dependencies

默认情况下,`developmentOnly` 配置中声明的所有依赖将从可执行 jar 或 war 中排除.

如果要在归档中包括在 `developmentOnly` 配置中声明的依赖,请配置其任务的类路径以包括该配置,如 `bootWar` 任务的以下示例所示:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-war-include-devtools.gradle[tags=include-devtools]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-war-include-devtools.gradle.kts[tags=include-devtools]
----

[[packaging-executable.configuring.unpacking]]
=== 配置需要移除的库

大多数库可以直接嵌套进可执行的文件里, 但是某些库可能有问题. 比如,JRuby 引入了它自己的内嵌 jar 支持, 比如 `jruby-complete.jar` 总是直接在文件系统上可用.

处理这个问题库, 可执行文件可以配置在运行(run)的时候移除指定的嵌套 jars 到临时目录. 库可以使用 Ant-style 模式匹配源 jar 文件的绝对路径移除需要的包:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-jar-requires-unpack.gradle[tags=requires-unpack]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-jar-requires-unpack.gradle.kts[tags=requires-unpack]
----

为了更好地控制, 也可以使用 closure.  该 closure 传递了一个 `FileTreeElement`, 并且应返回一个 `boolean`, 指示是否需要打包.

[[packaging-executable.configuring.launch-script]]
=== 让文件完全可执行

Spring Boot 对完全可执行文件提供支持. 通过已知的如何启动应用的预 shell 脚步来制造完全可执行. 在类 Unix 平台上, 这个启动脚本运行文件可以像任何可执行文件直接运行或者作为服务安装.

NOTE: 当前,某些工具不接受此格式,因此您可能无法始终使用此技术. 例如,`jar -xf` 可能在无提示的情况下无法提取出已成为完全可执行的 jar 或 war. 建议仅在打算直接执行此选项时才启用此选项,而不是使用 `java -jar` 运行它,将其部署到 servlet 容器或将其包含在 OCI 镜像中.

启用这个特性, launchScript 必须启用:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-jar-include-launch-script.gradle[tags=include-launch-script]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-jar-include-launch-script.gradle.kts[tags=include-launch-script]
----

这将添加 Spring Boot 的默认脚本到文件里. 默认的启动脚本包含若干个属性并且设置了合适的默认值, 当然也可以通过 `properties` 属性自定义默认值:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-jar-launch-script-properties.gradle[tags=launch-script-properties]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-jar-launch-script-properties.gradle.kts[tags=launch-script-properties]
----

如果启动脚本没有你想要的, `script` 属性可以提供一个自定义的启动脚本:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-jar-custom-launch-script.gradle[tags=custom-launch-script]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-jar-custom-launch-script.gradle.kts[tags=custom-launch-script]
----


[[packaging-executable.configuring.properties-launcher]]
=== 使用 `PropertiesLauncher`

要想使用 `PropertiesLauncher` 启动可执行 jar 或者 war, 配置任务的 manifest 来设置 `Main-Class` 属性:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-war-properties-launcher.gradle[tags=properties-launcher]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-war-properties-launcher.gradle.kts[tags=properties-launcher]
----


[[packaging-executable.configuring.layered-archives]]
=== 打包分层的 Jar 或 War

默认情况下,`bootJar`  任务会构建一个 archive 文件,其中包含应用程序的类和依赖关系,分别位于 `BOOT-INF/classes` 和 `BOOT-INF/lib` 中. 类似地，`bootWar` 会构建一个 archive 文件，其中包含 `WEB-INF/classes` 中的应用程序类以及 `WEB-INF/lib` 和 `WEB-INF/lib-provided` 中的依赖项。 对于需要从 jar 的内容中构建 docker 镜像的情况,能够进一步分隔这些目录以便将它们写入不同的层中很有用.

分层的 jar 使用与常规重新打包的 jar 相同的布局,但是包括了描述每个层的附加元数据文件. 要使用此功能,必须启用分层功能:

默认情况下,定义了以下层:

* `dependencies`:  包含所有的依赖,但不包括 `SNAPSHOT` 版本的依赖.
* `spring-boot-loader`:  用于加载 jar.
* `snapshot-dependencies`:  包含所有的 `SNAPSHOT` 版本依赖 .
* `application`:  应用程序类和资源.

层的顺序很重要,因为它确定了部分应用程序更改时可以缓存先前的层的可能性. 默认顺序是 `dependencies`, `spring-boot-loader`, `snapshot-dependencies`, `application`. 应该首先添加最不可能更改的内容,然后添加有可能更改的层.

要禁用此功能, 您可以通过以下方式执行此操作:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-jar-layered-disabled.gradle[tags=layered]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-jar-layered-disabled.gradle.kts[tags=layered]
----

创建分层 jar 或 war 时,`spring-boot-jarmode-layertools` jar 将作为依赖添加到 jar 中. 将此 jar 放在类路径上,您可以在特殊模式下启动应用程序,该模式允许引导代码运行与您的应用程序完全不同的内容,例如,提取层的内容. 如果要排除此依赖关系,可以按以下方式进行:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-jar-layered-exclude-tools.gradle[tags=layered]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-jar-layered-exclude-tools.gradle.kts[tags=layered]
----

[[packaging-executable.configuring.layered-archives.configuration]]
==== 自定义层的配置
根据您的应用程序,您可能想要调整层的创建方式和添加新层的方式.

这可以通过使用配置来完成,该配置描述了如何将 jar 或 war 分为几层,以及这些层的顺序.下面的示例显示如何显式定义上述默认顺序:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-jar-layered-custom.gradle[tags=layered]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-jar-layered-custom.gradle.kts[tags=layered]
----

`layered` DSL 包含三部分:

* `<application>` 定义应如何对应用程序类和资源进行分层.
* `<dependencies>` 定义应层之间的依赖关系.
* `<layerOrder>` 定义应写入层的顺序.

嵌套的 `intoLayer` 用于 `application` 和 `dependencies` 中,以声明层的内容. 从上到下,按照定义的顺序评估. 较早的块未声明的任何内容仍然可供后续块使用.

`intoLayer` 块使用嵌套的 `include` 和 `exclude` 元素声明内容. `application` 对 include/exclude  表达式使用 Ant 风格的匹配路径模式. `dependencies` 使用 `group:artifact[:version]` 模式.它还提供了 `includeProjectDependencies()` 和 `excludeProjectDependencies()` 元素, 可以用来包含或排除项目依赖.

如果未定义 `include`,则将考虑所有内容 (较早的块未声明) .

如果未定义 `exclude`,则不应用任何排除项.

查看上面的 `dependencies` 示例,我们可以看到第一个 `intoLayer` 将声明所有的项目依赖, 第二个 `intoLayer` 将声明上又有 `snapshot-dependencies` 层的 SNAPSHOT 依赖. 最后的 `intoLayer` 将声明 `dependencies` 层的所有剩余内容 (在这种情况下,不是 项目 或 SNAPSHOT 的任何依赖) .

`application` 块具有相似的规则. 首先声明 `spring-boot-loader` 层的 `org/springframework/boot/loader/**`  内容. 然后为 `application` 层声明所有剩余的类和资源.

NOTE: `intoLayer` 块的定义顺序通常与层的写入顺序不同. 因此,必须始终包含 `layerOrder` 元素,并且必须覆盖 `intoLayer` 块引用的所有层.