[[reacting-to-other-plugins]]
= 其他插件行为

当应用另一个插件时，Spring Boot 插件会通过对项目配置进行各种更改来做出反应。本节介绍这些更改.

[[reacting-to-other-plugins.java]]
== Java 插件行为

当项目里使用了 {java-plugin}[`java` plugin],Spring Boot 插件会:

1. C创建一个名为 `bootJar` 的 {boot-jar-javadoc}[`BootJar`] 任务, 它会为项目创建一个可执行的 fat jar. jar会包含所有 main source set 下运行时的类路径; 类会被打包进 `BOOT-INF/classes` 里, jars 会被打包进 `BOOT-INF/lib` 里.
2. 配置一个依赖于 `bootJar` 任务的 `assemble` 任务.
3. 配置 `jar` 任务以使用 `plain` 作为其归档分类器。
4. 创建一个名为 `bootBuildImage` 的 {boot-build-image-javadoc}[`BootBuildImage`] 任务,该任务将使用 https://buildpacks.io[buildpack] 创建一个 OCI 镜像..
5. 创建一个名为 `bootRun` 的 {boot-run-javadoc}[`BootRun`] 任务,  用来运行你的程序.
6. 创建一个名为 `bootArchives` 的配置包含通过 `bootJar` 产生的 artifact.
7. 创建一个名为 `developmentOnly` 的配置,为仅在开发时需要的依赖 (例如 Spring Boot 的 Devtools) ,不应将其打包在可执行的 jar 和 wars 中.
8. 创建一个名为 `productionRuntimeClasspath` 的配置。 它相当于 `runtimeClasspath` 减去仅出现在 `developmentOnly` 配置中的任何依赖项。
9. 无需配置, 所有的 `JavaCompile` 任务都使用 `UTF-8`.
10. 无需配置, 所有的 `JavaCompile` 任务都使用 `-parameters` 编译器参数.

[[reacting-to-other-plugins.kotlin]]
== Kotlin 插件行为

当项目里使用了 {kotlin-plugin}[Kotlin's Gradle plugin] ,Spring Boot 插件会:

1. 将 Spring Boot 的依赖管理中使用的 Kotlin 版本与该插件的版本保持一致.  这可以通过将  `kotlin.version` 属性设置为与 Kotlin 插件的版本匹配的值来实现.
   This is achieved by setting the `kotlin.version` property with a value that matches the version of the Kotlin plugin.
2. 将任何 `KotlinCompile` 任务配置为使用 `-java-parameters` 编译器参数.

[[reacting-to-other-plugins.war]]
== war 插件行为

当项目里使用了 {war-plugin}[`war` plugin] ,Spring Boot 插件会:

1. 创建一个名为 `bootWar` 的  {boot-war-javadoc}[`BootWar`] 任务, 用来为项目创建可执行的, far war. 另外对于标准的打包, 所以是 `providedRuntime` 的配置都会打包进 `WEB-INF/lib-provided` 里;
2. 配置一个依赖于 `bootWar` 任务的 `assemble` 任务;
3. 配置 `war` 任务以使用 `plain` 作为其存档分类器。
4. 配置 `bootArchives` 任务包含通过 `bootWar` 任务产生的 `artifact`.

[[reacting-to-other-plugins.dependency-management]]
== 依赖管理插件行为

当项目里使用了 {dependency-management-plugin}[`io.spring.dependency-management` plugin] ,Spring Boot 插件会自动导入 `spring-boot-dependencies` bom

[[reacting-to-other-plugins.application]]
== application 插件行为

当项目里使用了 {application-plugin}[`application` plugin] ,Spring Boot 插件会:


1. 创建一个名为 `bootStartScripts` 的 `CreateStartScripts` 的任务, 它会创建一个脚本用来使用 `java -jar` 命令启动在 `bootArchives` 配置里的 artifact. 该任务使用配置的 `applicationDefaultJvmArgs` 属性作为其 `defaultJvmOpts` 属性.
2. 创建一个名为 `boot` 的新的 distribution , 并将其配置为在其 `lib` 目录的 `bootArchives` 配置中包含 artifact, 在其 `bin` 目录中包含启动脚本.
3. 使用 `mainClassName` 作为 `main` 属性配置 `bootRun` 任务.
4. 使用 `applicationDefaultJvmArgs` 参数作为 `jvmArgs` 属性配置 `bootRun` 任务.
5. 使用 `mainClassName` 属性在 `mainifest` 作为 `Start-Class` 入口配置 `bootJar` 任务.
6. 使用 `mainClassName` 作为 `mainifest` 的 `Start-Class` 入口配置 bootWar 任务.

[[reacting-to-other-plugins.nbt]]
== GraalVM Native Image Plugin 行为
当 {nbt-gradle-plugin}[GraalVM Native Image plugin] 应用于项目时，Spring Boot 插件：

. 应用 `org.springframework.boot.aot` 插件，该插件会:
.. 注册 `aot` 和 `aotTest` 源集.
.. 注册一个名为 `processAot` 的 `ProcessAot` 任务，该任务将为 `aot` 源集中的应用程序代码生成 AOT 优化的源集.
.. 配置  `aot`  源代码集的 Java 编译和处理资源任务依赖于 `processAot` 。
.. 注册一个名为 `processTestAot` 的  `ProcessTestAot` 任务，该任务将为 `aotTest` 源集中的应用程序测试生成 AOT 优化的源集。
.. 配置 `aotTest` 源代码集的 Java 编译和处理资源任务依赖于 `processTestAot`.
. 将 `aot` 源集的输出添加到 `main` GraalVM 本地二进制文件的类路径中。
. 将 `aotTest` 源集的输出添加到 `test` GraalVM 本地二进制文件的类路径中。
. 配置 GraalVM 扩展以禁用工具链检测。
. 配置每个 GraalVM 本地二进制文件需要 GraalVM 22.3 或更高版本。
. 配置  `bootJar` 任务在其 jar 中包含由  `collectReachabilityMetadata` 任务生成的可达性元数据。
. 配置 `bootBuildImage` 任务使用 `paketobuildpacks/builder:tiny`  作为其构建器，并在其环境中将  `BP_NATIVE_IMAGE`  设置为 `true`。
