[[running-your-application]]
= 使用 Gradle 运行程序

使用 `bootRun` 任务来运行程序, 不需要产生文件:

[source,bash,indent=0,subs="verbatim"]
----
	$ ./gradlew bootRun
----

`bootRun` 任务是 JavaExec 子类的 {boot-run-javadoc}[`BootRun`] 的实例. 所以, 所有的 {gradle-dsl}/org.gradle.api.tasks.JavaExec.html[usual configuration options] 在 Gradle 里执行 Java 处理都可用.
任务会使用主源文件的运行期类路径自动配置.

默认的, 通过查找源集输出下的 `public static void main(String[])` 会自动配置.

主类也可以显示的配置:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/running/boot-run-main.gradle[tags=main]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/running/boot-run-main.gradle.kts[tags=main]
----

或者, 可以使用 Spring Boot DSL 的 `mainClass` 属性在项目范围内配置主类名称:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/running/spring-boot-dsl-main-class-name.gradle[tags=main-class]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/running/spring-boot-dsl-main-class-name.gradle.kts[tags=main-class]
----

默认情况下, `bootRun` 将配置 JVM 以优化其启动, 以在开发过程中加快启动速度.  可以通过使用 `optimizedLaunch` 属性来禁用此行为, 如以下示例所示:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/running/boot-run-disable-optimized-launch.gradle[tags=launch]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/running/boot-run-disable-optimized-launch.gradle.kts[tags=launch]
----

另外, 如果使用了 {application-plugin}[`application` plugin], `mainClass` 项目属性可以被使用:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/running/application-plugin-main-class-name.gradle[tags=main-class]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/running/application-plugin-main-class-name.gradle.kts[tags=main-class]
----


[[running-your-application.passing-arguments]]
== 将参数传递给您的应用程序

与所有 `JavaExec` 任务一样, 在使用 Gradle 4.9 或更高版本时, 可以使用 `--args='<arguments>'` 从命令行将参数传递到 `bootRun` 中.  例如, 要使用名为 `dev` 环境运行您的应用程序, 可以使用以下命令:

[source,bash,indent=0,subs="verbatim"]
----
	$ ./gradlew bootRun --args='--spring.profiles.active=dev'
----

有关更多详细信息, 请参见 {gradle-api}/org/gradle/api/tasks/JavaExec.html#setArgsString-java.lang.String-[`JavaExec.setArgsString` 的 javadoc]

[[running-your-application.passing-system-properties]]
== Passing System properties to your application

由于 bootRun 是标准的 JavaExec 任务,因此可以通过在构建脚本中指定系统属性来将它们传递给应用程序的 JVM.
要使系统属性的值可配置,请使用  {gradle-dsl}/org.gradle.api.Project.html#N14FE1[project property] 设置其值. 若要使项目属性为可选,请使用 `findProperty` . 这样做还允许使用 `?:`  运算符提供默认值,如以下示例所示:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/running/boot-run-system-property.gradle[tags=system-property]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/running/boot-run-system-property.gradle.kts[tags=system-property]
----

前面的示例将 `com.example.property` 系统属性设置为 example 属性的值. 如果未设置 example 属性,则系统属性的值为默认值.

Gradle 允许以多种方式设置项目属性,可以使用 `-P` 标志将这些值参数化并作为命令行上的属性传递.

[source,bash,indent=0,subs="verbatim,attributes"]
----
$ ./gradlew bootRun -Pexample=custom
----

前面的示例将 example 属性的值设置为 `custom`.然后,`bootRun` 将使用它作为 `com.example.property` 系统属性的值.

[[running-your-application.reloading-resources]]
== 重加载资源

如果项目里加入了 devtools, 它会自动的监控你的程序类路径变化.。
请注意，修改后的文件需要重新编译才能更新类路径，以便触发使用 devtools 重新加载。
有关使用 devtools 的更多详细信息，请参阅 {spring-boot-reference}#using.devtools.restart[参考文档的这一部分]。

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/running/boot-run-source-resources.gradle[tags=source-resources]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/running/boot-run-source-resources.gradle.kts[tags=source-resources]
----

这在开发时很有用.
