[[features.json]]
== JSON
Spring Boot 为三个 JSON 映射库提供了内置集成:

- Gson
- Jackson
- JSON-B

Jackson 是首选和默认的库.

[[features.json.jackson]]
=== Jackson
Spring Boot 提供了 Jackson 的自动配置,Jackson 是 `spring-boot-starter-json` 的一部分. 当 Jackson 在 classpath 上时,会自动配置 `ObjectMapper` bean. Spring Boot 提供了几个配置属性来 <<howto#howto.spring-mvc.customize-jackson-objectmapper,自定义 `ObjectMapper` 的配置>>.

[[features.json.jackson.custom-serializers-and-deserializers]]
==== 自定义序列化和反序列化器
如果使用 Jackson 序列化和反序列化 JSON 数据，则可能需要编写自己的 `JsonSerializer` 和 `JsonDeserializer` 类。
自定义序列化器通常是 https://github.com/FasterXML/jackson-docs/wiki/JacksonHowToCustomSerializers[通过模块向 Jackson 注册]，但 Spring Boot 提供了一个替代的  `@JsonComponent` 注解， 使得直接注册 Spring Beans 变得更加容易。

您可以直接在 `JsonSerializer`, `JsonDeserializer` 或 `KeyDeserializer` 实现上使用  `@JsonComponent`  注解。
还可以在包含序列化器/反序列化器作为内部类的类上使用它，如以下示例所示：

include::code:MyJsonComponent[]

`ApplicationContext` 中的所有 `@JsonComponent` bean 都会自动向 Jackson 注册。
由于 `@JsonComponent` 是用  `@Component` 进行元注解的，因此通常的组件扫描规则适用。

Spring Boot 还提供了 {spring-boot-module-code}/jackson/JsonObjectSerializer.java[`JsonObjectSerializer`] 和 {spring-boot-module-code}/jackson/JsonObjectDeserializer.java[`JsonObjectDeserializer`] 基类，
它们在序列化对象时提供了标准 Jackson 版本的有用替代方案。
有关详细信息，请参阅 Javadoc 中的{spring-boot-module-api}/jackson/JsonObjectSerializer.html[`JsonObjectSerializer`] 和 {spring-boot-module-api}/jackson/JsonObjectDeserializer.html[`JsonObjectDeserializer`]。

上面的示例可以重写为使用  `JsonObjectSerializer`/`JsonObjectDeserializer` ，如下所示：

include::code:object/MyJsonComponent[]

[[features.json.jackson.mixins]]
==== Mixins
Jackson 支持混合，可用于将其他注解混合到已在目标类上声明的注解中。
Spring Boot 的 Jackson 自动配置将扫描应用程序的包以查找带有  `@JsonMixin`  注解的类，并将它们注册到自动配置的 `ObjectMapper`。
注册由 Spring Boot 的  `JsonMixinModule` 执行。

[[features.json.gson]]
=== Gson
Spring Boot 提供 Gson 的自动配置. 当 `Gson` 在 classpath 上时,会自动配置 Gson bean. Spring Boot 提供了几个 `+spring.gson.*+` 配置属性来自定义配置. 为了获得更多控制,可以使用一个或多个 `GsonBuilderCustomizer` bean.

[[features.json.json-b]]
=== JSON-B
Spring Boot 提供了 JSON-B 的自动配置. 当 JSON-B API 和实现在 classpath 上时,将自动配置 `Jsonb` bean. 首选的 JSON-B 实现是 Apache Johnzon,它提供了依赖管理.
