[[features.kotlin]]
== Kotlin 支持
https://kotlinlang.org[Kotlin] 是一种针对 JVM (和其他平台) 的静态类型语言,它可编写出简洁而优雅的代码,同时提供与使用 Java 编写的现有库的 {kotlin-docs}java-interop.html[互通性].

Spring Boot 通过利用其他 Spring 项目 (如 Spring Framework、Spring Data 和 Reactor) 的支持来提供 Kotlin 支持. 有关更多信息,请参阅 {spring-framework-docs}/languages.html#kotlin[Spring Framework Kotlin 支持文档] .

开始学习 Spring Boot 和 Kotlin 最简单方法是遵循这个 https://spring.io/guides/tutorials/spring-boot-kotlin/[全面教程]. 您可以通过 https://start.spring.io/#!language=kotlin[start.spring.io] 创建新的 Kotlin 项目. 如果您需要支持,请免费加入 https://slack.kotlinlang.org/[Kotlin Slack]  的 #spring 频道或使用 https://stackoverflow.com/questions/tagged/spring+kotlin[Stack Overflow]  上的 `spring` 和 `kotlin` 标签提问.

[[features.kotlin.requirements]]
=== 要求
Spring Boot 支持 Kotlin 1.7.x. 要使用 Kotlin,classpath 下必须存在 `org.jetbrains.kotlin:kotlin-stdlib` 和 `org.jetbrains.kotlin:kotlin-reflect`. 也可以使用 `kotlin-stdlib` 的变体 `kotlin-stdlib-jdk7` 和 `kotlin-stdlib-jdk8`.

由于 https://discuss.kotlinlang.org/t/classes-final-by-default/166[Kotlin 类默认为 final],因此您可能需要配置 {kotlin-docs}compiler-plugins.html#spring-support[kotlin-spring] 插件以自动打开 `Spring-annotated` 类,以便可以代理它们.

在 Kotlin 中序列化/反序列化 JSON 数据需要使用 https://github.com/FasterXML/jackson-module-kotlin[Jackson 的 Kotlin 模块]. 在 classpath 中找到它时会自动注册. 如果 Jackson 和 Kotlin 存在但 Jackson Kotlin 模块不存在,则会记录警告消息.

TIP: 如果在 https://start.spring.io/#!language=kotlin[start.spring.io] 上创建 Kotlin 项目,则默认提供这些依赖和插件.

[[features.kotlin.null-safety]]
=== Null 安全
Kotlin 的一个关键特性是  {kotlin-docs}null-safety.html[null-safety]. 它在编译时处理空值,而不是将问题推迟到运行时并遇到 `NullPointerException`. 这有助于消除常见的错误来源,而无需支付像 `Optional` 这样的包装器的成本. Kotlin 还允许使用有可空值的,如 Kotlin `null` https://www.baeldung.com/kotlin-null-safety[安全综合指南中]所述.

虽然 Java 不允许在其类型系统中表示 `null` 安全,但 Spring Framework、Spring Data 和 Reactor 现在通过易于使用的工具的注解提供其 API 的安全性. 默认情况下,Kotlin 中使用的 Java API 类型被识别为放宽空检查的 {kotlin-docs}java-interop.html#null-safety-and-platform-types[平台类型]. Kotlin 对 {kotlin-docs}java-interop.html#jsr-305-support[JSR 305 注解]  的支持与可空注解相结合,为 Kotlin 中 Spring API 相关的代码提供了空安全.

可以通过使用以下选项添加 `-Xjsr305` 编译器标志来配置 JSR 305 检查: `-Xjsr305={strict|warn|ignore}`. 默认行为与 `-Xjsr305=warn` 相同. 在从 Spring API 推断出的 Kotlin 类型中需要考虑 null 安全的 `strict` 值,但是应该使用 Spring API 可空声明甚至可以在次要版本之间发展并且将来可能添加更多检查的方案.

WARNING: 尚不支持泛型类型参数、varargs 和数组元素可空性. 有关最新信息,请参见 https://jira.spring.io/browse/SPR-15942[SPR-15942]. 另请注意,Spring Boot 自己的 API {github-issues}10712[尚未注解].

[[features.kotlin.api]]
=== Kotlin API

[[features.kotlin.api.run-application]]
==== runApplication
Spring Boot 提供了使用 `runApplication<MyApplication>(*args)` 运行应用程序的惯用方法,如下所示:

[source,kotlin,indent=0,subs="verbatim"]
----
	import org.springframework.boot.autoconfigure.SpringBootApplication
	import org.springframework.boot.runApplication

	@SpringBootApplication
	class MyApplication

	fun main(args: Array<String>) {
		runApplication<MyApplication>(*args)
	}
----

这是 `SpringApplication.run(MyApplication::class.java, *args)` 的替代方式. 它还允许自定义应用程序,如下所示:

[source,kotlin,indent=0,subs="verbatim"]
----
	runApplication<MyApplication>(*args) {
		setBannerMode(OFF)
	}
----

[[features.kotlin.api.extensions]]
==== 扩展
Kotlin {kotlin-docs}extensions.html[扩展]  提供了使用附加功能扩展现有类的能力. Spring Boot Kotlin API 利用这些扩展为现有 API 添加新的 Kotlin 特定便利.

提供的 `TestRestTemplate` 扩展类似于 Spring Framework 为 `RestOperations` 提供的. 除此之外,扩展使得利用 Kotlin reified 类型参数变为可能.

[[features.kotlin.dependency-management]]
=== 依赖管理
为了避免在 classpath 上混合不同版本的 Kotlin 依赖,Spring Boot会导入Kotlin BOM.

使用Maven,可以通过 `kotlin.version` 属性自定义 Kotlin 版本,并且为 `kotlin-maven-plugin` 提供了插件管理.  使用 Gradle,Spring Boot 插件会自动将 `kotlin.version` 与 Kotlin 插件的版本保一致.

Spring Boot 还通过导入 Kotlin Coroutines BOM 管理 Coroutines 依赖的版本.  可以通过 `kotlin-coroutines.version` 属性自定义版本.

TIP: 如果在 https://start.spring.io/#!language=kotlin[start.spring.io] 上构建的 Kotlin 项目有至少一个响应式依赖,则默认提供 `org.jetbrains.kotlinx:kotlinx-coroutines-reactor` 依赖.

[[features.kotlin.configuration-properties]]
=== @ConfigurationProperties
`@ConfigurationProperties` 与 <<features#features.external-config.typesafe-configuration-properties.constructor-binding,`@ConstructorBinding`>>  结合使用时,`@ConfigurationProperties` 支持具有不变 `val` 属性的类,如以下示例所示:

[source,kotlin,indent=0,subs="verbatim"]
----
@ConfigurationProperties("example.kotlin")
data class KotlinExampleProperties(
		val name: String,
		val description: String,
		val myService: MyService) {

	data class MyService(
			val apiToken: String,
			val uri: URI
	)
}
----

TIP: 为了使用注解处理器 <<configuration-metadata#appendix.configuration-metadata.annotation-processor,生成自己的元数据>> ,应该使用 `spring-boot-configuration-processor` 依赖配置 {kotlin-docs}kapt.html[`kapt`] .  请注意,由于 kapt 提供的模型的限制,某些功能 (例如检测默认值或不推荐使用的项目) 无法正常工作.

[[features.kotlin.testing]]
=== 测试
虽然可以使用 JUnit 4 来测试 Kotlin 代码,但建议使用 JUnit 5. JUnit 5 允许测试类实例化一次,并在所有类的测试中复用. 这使得可以在非静态方法上使用 `@BeforeAll` 和 `@AfterAll` 注解,这非常适合 Kotlin.

要模拟 Kotlin 类,建议使用 MockK.  如果您需要与 Mockito 特定的  <<features#features.testing.spring-boot-applications.mocking-beans,`@MockBean` 和 `@SpyBean` 注解>>相对应的 Mockk,则可以使用 SpringMockK,它提供类似的 `@MockkBean` 和 `@SpykBean` 注解.

[[features.kotlin.resources]]
=== 资源

[[features.kotlin.resources.further-reading]]
==== 进阶阅读
* {kotlin-docs}[Kotlin 语言参考]
* https://kotlinlang.slack.com/[Kotlin Slack]  (有专用的 #spring 频道)
* https://stackoverflow.com/questions/tagged/spring+kotlin[Stackoverflow 上 `spring` 和 `kotlin` 标签]
* https://try.kotlinlang.org/[在浏览器中尝试 Kotlin]
* https://blog.jetbrains.com/kotlin/[Kotlin 博客]
* https://kotlin.link/[Awesome Kotlin]
* https://spring.io/guides/tutorials/spring-boot-kotlin/[教程: 使用 Spring Boot 和 Kotlin 构建 Web 应用程序]
* https://spring.io/blog/2016/02/15/developing-spring-boot-applications-with-kotlin[使用 Kotlin 开发 Spring Boot 应用程序]
* https://spring.io/blog/2016/03/20/a-geospatial-messenger-with-kotlin-spring-boot-and-postgresql[使用 Kotlin、Spring Boot 和 PostgreSQL 开发地理信息]
* https://spring.io/blog/2017/01/04/introducing-kotlin-support-in-spring-framework-5-0[在 Spring Framework 5.0 中引入 Kotlin 支持]
* https://spring.io/blog/2017/08/01/spring-framework-5-kotlin-apis-the-functional-way[Spring Framework 5 Kotlin API 实现函数式]



[[features.kotlin.resources.examples]]
==== 示例
* https://github.com/sdeleuze/spring-boot-kotlin-demo[spring-boot-kotlin-demo]: regular Spring Boot + Spring Data JPA project
* https://github.com/mixitconf/mixit[mixit]: Spring Boot 2 + WebFlux + Reactive Spring Data MongoDB
* https://github.com/sdeleuze/spring-kotlin-fullstack[spring-kotlin-fullstack]: WebFlux Kotlin fullstack example with Kotlin2js for frontend instead of JavaScript or TypeScript
* https://github.com/spring-petclinic/spring-petclinic-kotlin[spring-petclinic-kotlin]: Kotlin version of the Spring PetClinic Sample Application
* https://github.com/sdeleuze/spring-kotlin-deepdive[spring-kotlin-deepdive]: a step by step migration for Boot 1.0 + Java to Boot 2.0 + Kotlin
* https://github.com/sdeleuze/spring-boot-coroutines-demo[spring-boot-coroutines-demo]: Coroutines sample project
