[[features.logging]]
== 日志记录
Spring Boot 使用 https://commons.apache.org/logging[Commons Logging]  记录所有内部日志,但保留底层日志实现. 其为 {java-api}/java/util/logging/package-summary.html[Java Util Logging], https://logging.apache.org/log4j/2.x/[Log4J2] 和 https://logback.qos.ch/[Logback] 提供了默认配置. 每种日志记录器都预先配置为使用控制台输出,并且还提供可选的文件输出.

默认情况下,如果您使用了 `Starter`,则使用 Logback 进行日志记录.还包括合适的 Logback 路由,以确保在使用 Java Util Logging、Commons Logging、Log4J 或 SLF4J 的依赖库都能正常工作.

TIP: Java 有很多日志框架可供使用. 如果以上列表让您感到困惑,请不要担心. 通常,您不需要更改日志依赖,并且 Spring Boot 提供的默认配置可以保证日志正常工作.

TIP: 将应用程序部署到 Servlet 容器或应用程序服务器时,通过 Java Util Logging API 执行的日志记录不会路由到应用程序的日志中.  这样可以防止容器或其他已部署到容器中的应用程序执行的日志记录出现在应用程序的日志中.

[[features.logging.log-format]]
=== 日志格式
Spring Boot 默认日志输出类似于以下示例:

[indent=0]
----
2019-03-05 10:57:51.112  INFO 45469 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/7.0.52
2019-03-05 10:57:51.253  INFO 45469 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2019-03-05 10:57:51.253  INFO 45469 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1358 ms
2019-03-05 10:57:51.698  INFO 45469 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2019-03-05 10:57:51.702  INFO 45469 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
----

输出以下项:

* 日期和时间: 毫秒精度,易于排序.
* 日志级别: `ERROR`、`WARN`、`INFO`、`DEBUG` 或 `TRACE`.
* 进程 ID.
* 一个 `---` 分隔符,用于区分实际日志内容的开始.
* 线程名称: 在方括号中 (可能会截断控制台输出) .
* 日志记录器名称: 这通常是源类名称 (通常为缩写) .
* 日志内容.

NOTE: Logback 没有 `FATAL` 级别. 该级别映射到 `ERROR`.

[[features.logging.console-output]]
=== 控制台输出
默认日志配置会在写入时将消息回显到控制台. 默认情况下,会记录 `ERROR`、`WARN` 和 `INFO` 级别的日志. 您还可以通过使用 `--debug` 标志启动应用程序来启用调试模式.

[source,shell,indent=0,subs="verbatim"]
----
	$ java -jar myapp.jar --debug
----

NOTE: 您还可以在 `application.properties` 中指定 `debug=true`.

启用调试模式后,核心日志记录器 (内嵌容器、Hibernate 和 Spring Boot) 将被配置为输出更多日志信息. 启用调试模式不会将应用程序配置为使用 `DEBUG` 级别记录所有日志内容.

或者,您可以通过使用 `--trace` 标志 (或在 `application.properties` 中的设置 `trace=true`) 启动应用程序来启用跟踪模式. 这样做可以为选择的核心日志记录器 (内嵌容器、Hibernate 模式生成和整个 Spring 组合) 启用日志追踪.

[[features.logging.console-output.color-coded]]
==== 着色输出
如果您的终端支持 ANSI,则可以使用颜色输出来提高可读性. 您可以将 `spring.output.ansi.enabled` 设置为 {spring-boot-module-api}/ansi/AnsiOutput.Enabled.html[受支持的值] 以覆盖自动检测:

[source,indent=0,subs="verbatim"]
----
%clr(%5p)
----

下表描述日志级别与颜色的映射关系:

|===
| Level | Color

| `FATAL`
| Red

| `ERROR`
| Red

| `WARN`
| Yellow

| `INFO`
| Green

| `DEBUG`
| Green

| `TRACE`
| Green
|===

或者,您可以通过将其作为转换选项指定应使用的颜色或样式. 例如,要将文本变为黄色,请使用以下设置:

[source,indent=0,subs="verbatim"]
----
	%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){yellow}
----

支持以下颜色和样式:

* `blue`
* `cyan`
* `faint`
* `green`
* `magenta`
* `red`
* `yellow`



[[features.logging.file-output]]
=== 文件输出
默认情况下,Spring Boot 仅记录到控制台,不会写入日志文件. 想除了控制台输出之外还要写入日志文件,则需要设置 `logging.file.name` 或 `logging.file.path` 属性 (例如,在 `application.properties` 中) .

下表展示了如何与 `logging.*` 属性一起使用:

.Logging 属性
[cols="1,1,1,4"]
|===
| configprop:logging.file.name[] | configprop:logging.file.path[] | Example | Description

| _(none)_
| _(none)_
|
| 仅在控制台输出

| 指定文件
| _(none)_
| `my.log`
| 写入指定的日志文件. 名称可以是绝对位置或相对于当前目录.

| _(none)_
| 指定目录
| `/var/log`
| 将 `spring.log` 写入指定的目录. 名称可以是绝对位置或相对于当前目录.
|===

日志文件在达到 `10MB` 时会轮转,并且与控制台输出一样,默认情况下会记录 `ERROR`、`WARN` 和 `INFO` 级别的内容.

TIP: 日日志属性独立于实际的日志底层. 因此,spring Boot 不管理特定的配置 key (例如 Logback 的 `logback.configurationFile`) .

[[features.logging.file-rotation]]
=== File Rotation
如果您正在使用 Logback，则可以使用 `application.properties` 或 `application.yaml`  设置 log rotation. 对于所有其他日志系统，您需要自己直接配置 rotation 设置(例如，如果您使用 Log4J2，那么您可以添加一个 `log4j.xml` 或 `log4j2-spring.xml` 文件).

支持以下 rotation 策略属性:

|===
| Name | Description

| configprop:logging.logback.rollingpolicy.file-name-pattern[]
| The filename pattern used to create log archives.

| configprop:logging.logback.rollingpolicy.clean-history-on-start[]
| If log archive cleanup should occur when the application starts.

| configprop:logging.logback.rollingpolicy.max-file-size[]
| The maximum size of log file before it is archived.

| configprop:logging.logback.rollingpolicy.total-size-cap[]
| The maximum amount of size log archives can take before being deleted.

| configprop:logging.logback.rollingpolicy.max-history[]
| The maximum number of archive log files to keep (defaults to 7).
|===



[[features.logging.log-levels]]
=== 日志等级
所有受支持的日志记录系统都可以使用 `+logging.level.<logger-name>=<level>+`  来设置 Spring `Environment` 中的记录器等级 (例如,在 `application.properties` 中) . 其中 level 是 `TRACE`、`DEBUG`、`INFO`、`WARN`、`ERROR`、`FATAL` 和 `OFF` 其中之一. 可以使用 `logging.level.root` 配置 `root` 记录器.

以下示例展示了 `application.properties` 中默认的日志记录设置:

[source,properties,indent=0,subs="verbatim",configprops,role="primary"]
.Properties
----
	logging.level.root=warn
	logging.level.org.springframework.web=debug
	logging.level.org.hibernate=error
----

[source,properties,indent=0,subs="verbatim",role="secondary"]
.Yaml
----
	logging:
	  level:
	    root: "warn"
	    org.springframework.web: "debug"
	    org.hibernate: "error"
----

也可以使用环境变量设置日志记录级别.  例如, `LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=DEBUG` 会将 `org.springframework.web` 设置为 `DEBUG`.

NOTE: 以上方法仅适用于程序包级别的日志记录.  由于宽松的绑定总是将环境变量转换为小写,因此无法以这种方式为单个类配置日志记录.  如果需要为类配置日志记录,则可以使用  <<features#features.external-config.application-json, `SPRING_APPLICATION_JSON`>> 变量.

[[features.logging.log-groups]]
=== 日志组
将相关记录器组合在一起以便可以同时配置,这通常很有用. 例如,您可以更改所有 Tomcat 相关记录器的日志记录级别,但您无法轻松记住顶层的包名.

为了解决这个问题,Spring Boot 允许您在 Spring `Environment` 中定义日志记录组. 例如,以下通过将 "`tomcat`" 组添加到 `application.properties` 来定义 tomcat 组:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	logging:
	  group:
	    tomcat: "org.apache.catalina,org.apache.coyote,org.apache.tomcat"
----

定义后,您可以使用一行配置来更改组中所有记录器的级别:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	logging:
	  level:
	    tomcat: "trace"
----

Spring Boot 包含以下预定义的日志记录组,可以直接使用:

[cols="1,4"]
|===
| 名称 | 日志记录器

| web
| `org.springframework.core.codec`, `org.springframework.http`, `org.springframework.web`, `org.springframework.boot.actuate.endpoint.web`, `org.springframework.boot.web.servlet.ServletContextInitializerBeans`

| sql
| `org.springframework.jdbc.core`, `org.hibernate.SQL`, `org.jooq.tools.LoggerListener`
|===



[[features.logging.shutdown-hook]]
=== 使用日志 Shutdown 钩子
为了在您的应用程序终止时释放日志记录资源，提供了一个 shutdown hook（勾子），该勾子将在 JVM 退出时触发日志系统清理。
除非您的应用程序部署为 war 文件，否则此 shutdown 勾子会自动注册。
如果您的应用程序具有复杂的上下文层次结构，则 shutdown 勾子可能无法满足您的需求。
如果没有，请禁用 shutdown 勾子 并调查底层日志记录系统直接提供的选项。
例如，Logback 提供  https://logback.qos.ch/manual/loggingSeparation.html[context selectors]，它允许在自己的上下文中创建每个 Logger。

您可以使用 `logging.register-shutdown-hook` 属性来禁用 shutdown 勾子。将其设置为 `false` 将禁用注册。
您可以在 `application.properties` 或 `application.yaml` 文件中设置属性：

对于在自己的 JVM 中部署的简单 “jar” 应用程序， 可以使用 `logging.register-shutdown-hook`  属性.
将 `logging.register-shutdown-hook` 设置为 `true` 将注册一个关闭钩子， 当 JVM 退出时， 该钩子将触发日志系统清理.

您可以在 `application.properties` 或 `application.yaml` 文件中设置属性:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	logging:
	  register-shutdown-hook: false
----

[[features.logging.custom-log-configuration]]
=== 自定义日志配置
可以通过在 classpath 中引入适合的库来激活各种日志记录系统,并且可以通过在 classpath 的根目录中或在以下 Spring Environment 属性指定的位置提供合适的配置文件来进一步自定义:  `logging.config`.

您可以使用 `org.springframework.boot.logging.LoggingSystem` 系统属性强制 Spring Boot 使用特定的日志记录系统. 该值应该是一个实现了 `LoggingSystem` 的类的完全限定类名. 您还可以使用 `none` 值完全禁用 Spring Boot 的日志记录配置.

NOTE: 由于日志记录在创建 `ApplicationContext` 之前初始化,因此无法在 Spring `@Configuration` 文件中控制来自 `@PropertySources` 的日志记录. 更改日志记录系统或完全禁用它的唯一方法是通过系统属性设置.

根据您的日志记录系统,将加载以下文件:

|===
| 日志记录系统 | 文件

| Logback
| `logback-spring.xml`, `logback-spring.groovy`, `logback.xml`, 或者 `logback.groovy`

| Log4j2
| `log4j2-spring.xml` 或者 `log4j2.xml`

| JDK (Java Util Logging)
| `logging.properties`
|===

NOTE: 如果可能,我们建议您使用 `-spring` 的形式来配置日志记录 (比如 `logback-spring.xml` 而不是 `logback.xml`) . 如果使用标准的配置位置,Spring 无法完全控制日志初始化.

WARNING: Java Util Logging 存在已知的类加载问题,这些问题在以 'executable jar' 运行时会触发. 如果可能的话,我们建议您在使用可执行 jar 方式运行时避免使用它.  .

为了进行自定义,部分其他属性会从 Spring `Environment` 传输到 `System` 属性,如下表所述:

|===
| Spring Environment | 系统属性 | 说明

| `logging.exception-conversion-word`
| `LOG_EXCEPTION_CONVERSION_WORD`
| 记录异常时使用的转换字.

| `logging.file.name`
| `LOG_FILE`
| 如果已定义,则在默认日志配置中使用它.

| `logging.file.path`
| `LOG_PATH`
| 如果已定义,则在默认日志配置中使用它.

| `logging.pattern.console`
| `CONSOLE_LOG_PATTERN`
| 要在控制台上使用的日志模式 (stdout) .

| `logging.pattern.dateformat`
| `LOG_DATEFORMAT_PATTERN`
| 日志日期格式的 Appender 模式.  (仅支持默认的 Logback 设置. )

| configprop:logging.charset.console[]
| `CONSOLE_LOG_CHARSET`
| The charset to use for console logging.

| `logging.pattern.file`
| `FILE_LOG_PATTERN`
| 要在文件中使用的日志模式 (如果启用了 `LOG_FILE`) .

| configprop:logging.charset.file[]
| `FILE_LOG_CHARSET`
| The charset to use for file logging (if `LOG_FILE` is enabled).

| `logging.pattern.level`
| `LOG_LEVEL_PATTERN`
| 渲染日志级别时使用的格式 (默认值为 `%5p`) .

| `PID`
| `PID`
| 当前进程 ID (如果可能,则在未定义为 OS 环境变量时发现) .
|===

如果您使用的是 Logback，以下属性也会被转移:

|===
| Spring Environment | System Property | Comments

| configprop:logging.logback.rollingpolicy.file-name-pattern[]
| `LOGBACK_ROLLINGPOLICY_FILE_NAME_PATTERN`
| Pattern for rolled-over log file names (default `$\{LOG_FILE}.%d\{yyyy-MM-dd}.%i.gz`).

| configprop:logging.logback.rollingpolicy.clean-history-on-start[]
| `LOGBACK_ROLLINGPOLICY_CLEAN_HISTORY_ON_START`
| Whether to clean the archive log files on startup.

| configprop:logging.logback.rollingpolicy.max-file-size[]
| `LOGBACK_ROLLINGPOLICY_MAX_FILE_SIZE`
| Maximum log file size.

| configprop:logging.logback.rollingpolicy.total-size-cap[]
| `LOGBACK_ROLLINGPOLICY_TOTAL_SIZE_CAP`
| Total size of log backups to be kept.

| configprop:logging.logback.rollingpolicy.max-history[]
| `LOGBACK_ROLLINGPOLICY_MAX_HISTORY`
| Maximum number of archive log files to keep.
|===

所有受支持的日志记录系统在解析其配置文件时都可以参考系统属性. 有关示例,请参阅 `spring-boot.jar` 中的默认配置:

* {spring-boot-code}/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/logback/defaults.xml[Logback]
* {spring-boot-code}/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/log4j2/log4j2.xml[Log4j 2]
* {spring-boot-code}/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/java/logging-file.properties[Java Util logging]

[TIP]
====
如果要在日志记录属性中使用占位符,则应使用 <<features#features.external-config.files.property-placeholders,Spring Boot 的语法>>,而不是使用底层框架的语法. 值得注意的是,如果使用 Logback,则应使用 `:` 作为属性名称与其默认值之间的分隔符,而不是使用 `:-`.
====

[TIP]
====
您可以通过仅覆盖 `LOG_LEVEL_PATTERN` (或带 Logback 的 `logging.pattern.level`) 将 MDC 和其他特别的内容添加到日志行. 例如,如果使用 `logging.pattern.level=user:%X\{user} %5p`,则默认日志格式包含 user MDC 项 (如果存在) ,如下所示:

[indent=0]
----
	2019-08-30 12:30:04.031 user:someone INFO 22174 --- [  nio-8080-exec-0] demo.Controller
	Handling authenticated request
----
====

[[features.logging.logback-extensions]]
=== Logback 扩展
Spring Boot 包含许多 Logback 扩展,可用于进行高级配置. 您可以在 `logback-spring.xml` 配置文件中使用这些扩展.

NOTE: 由于标准的 `logback.xml` 配置文件加载过早,因此无法在其中使用扩展. 您需要使用 `logback-spring.xml` 或定义 `logging.config` 属性.

WARNING: 扩展不能与 Logback 的 https://logback.qos.ch/manual/configuration.html#autoScan[配置扫描] 一起使用. 如果尝试这样做,更改配置文件会导致发生类似以下错误日志:  .

[indent=0]
----
	ERROR in ch.qos.logback.core.joran.spi.Interpreter@4:71 - no applicable action for [springProperty], current ElementPath is [[configuration][springProperty]]
	ERROR in ch.qos.logback.core.joran.spi.Interpreter@4:71 - no applicable action for [springProfile], current ElementPath is [[configuration][springProfile]]
----

[[features.logging.logback-extensions.profile-specific]]
==== 特定 Profile 配置
`<springProfile>` 标签允许您根据激活的 Spring profile 选择性地包含或排除配置部分. 在 `<configuration>` 元素中的任何位置都支持配置 profile. 使用 `name` 属性指定哪个 profile 接受配置. `<springProfile>` 标记可以包含简单的 proifle 名称 (例如 `staging`) 或 profile 表达式. profile 表达式允许表达更复杂的 profile 逻辑,
例如 `production & (eu-central | eu-west)`. 有关详细信息,请查阅 {spring-framework-docs}/core.html#beans-definition-profiles-java[Spring Framework 参考指南] . 以下清单展示了三个示例 profile:

[source,xml,subs="verbatim",indent=0]
----
	<springProfile name="staging">
		<!-- configuration to be enabled when the "staging" profile is active -->
	</springProfile>

	<springProfile name="dev | staging">
		<!-- configuration to be enabled when the "dev" or "staging" profiles are active -->
	</springProfile>

	<springProfile name="!production">
		<!-- configuration to be enabled when the "production" profile is not active -->
	</springProfile>
----

[[features.logging.logback-extensions.environment-properties]]
==== 环境属性
使用 `<springProperty>` 标签可以让您暴露 Spring 环境 (`Environment`) 中的属性,以便在 Logback 中使用. 如果在 Logback 配置中访问来自 `application.properties` 文件的值,这样做很有用. 标签的工作方式与 Logback 的标准 `<property>` 标签类似. 但是,您可以指定属性 (来自 `Environment`) 的 `source`,而不是指定直接的 `value`. 如果需要将属性存储在 `local` 作用域以外的其他位置,则可以使用 `scope` 属性.
如果需要回退值 (如果未在 `Environment` 中设置该属性) ,则可以使用 `defaultValue` 属性. 以下示例展示了如何暴露属性以便在 Logback 中使用:

[source,xml,subs="verbatim",indent=0]
----
	<springProperty scope="context" name="fluentHost" source="myapp.fluentd.host"
			defaultValue="localhost"/>
	<appender name="FLUENT" class="ch.qos.logback.more.appenders.DataFluentAppender">
		<remoteHost>${fluentHost}</remoteHost>
		...
	</appender>
----

NOTE: 必须以 kebab 风格 (短横线小写风格) 指定 `source` (例如 `my.property-name`) . 但可以使用宽松规则将属性添加到 `Environment` 中.

[[features.logging.log4j2-extensions]]
=== Log4j2 扩展
Spring Boot 包括许多对 Log4j2 的扩展，可以进行高级配置。您可以在任何 `log4j2-spring.xml` 配置文件中使用这些扩展。

NOTE: 由于标准 `log4j2.xml` 配置文件加载得太早，因此不能在其中使用扩展。您需要使用  `log4j2-spring.xml` 或定义 `logging.config` 属性。

NOTE: 这些扩展取代了 https://logging.apache.org/log4j/2.x/log4j-spring-boot/index.html[Spring Boot 提供的对] Log4J 的支持。你应该确保在你的构建中不包含 ``org.apache.logging.log4j:log4j-spring-boot`` 模块。

[[features.logging.log4j2-extensions.profile-specific]]
==== Profile-specific Configuration

`<SpringProfile>` 标签允许您根据激活的 Spring profile 选择性地包含或排除部分配置。Profile 部分在  `<Configuration>` 元素中的任何位置都受支持。
使用 `name` 属性指定哪个配置文件接受配置。 `<SpringProfile>` 标签可以包含配置文件名称（例如 `staging`）或配置文件表达式。 配置文件表达式允许表达更复杂的配置文件逻辑，例如  `production & (eu-central | eu-west)`。
查看 {spring-framework-docs}/core.html#beans-definition-profiles-java[Spring Framework 参考指南] 以获取更多详细信息。 以下清单显示了三个示例配置文件：

[source,xml,subs="verbatim",indent=0]
----
	<SpringProfile name="staging">
		<!-- configuration to be enabled when the "staging" profile is active -->
	</SpringProfile>

	<SpringProfile name="dev | staging">
		<!-- configuration to be enabled when the "dev" or "staging" profiles are active -->
	</SpringProfile>

	<SpringProfile name="!production">
		<!-- configuration to be enabled when the "production" profile is not active -->
	</SpringProfile>
----

[[features.logging.log4j2-extensions.environment-properties-lookup]]
==== Environment Properties Lookup
如果你想在 Log4j2 配置中引用 Spring `Environment`中的属性，你可以使用前缀 `spring:` https://logging.apache.org/log4j/2.x/manual/lookups.html[lookups]。
如果要访问 Log4j2 配置中的  `application.properties` 文件中的值，这样做会很有用。

下面的示例演示如何设置一个名为  `applicationName` 的 Log4j2 属性，该属性从 Spring `Environment` 中读取 `spring.application.name`：

[source,xml,subs="verbatim",indent=0]
----
	<Properties>
		<Property name="applicationName">${spring:spring.application.name}</property>
	</Properties>
----

NOTE: 查找的 key 应该以 kebab case 命名 (such as `my.property-name`).



[[features.logging.log4j2-extensions.environment-property-source]]
==== Log4j2 系统属性
Log4j2 支持许多可用于配置各种项目的 https://logging.apache.org/log4j/2.x/manual/configuration.html#SystemProperties[System Properties] 。
例如， `log4j2.skipJansi` 系统属性可用于配置  `ConsoleAppender`  是否将尝试在 Windows 上使用 https://github.com/fusesource/jansi[Jansi]  输出流。

在 Log4j2 初始化后加载的所有系统属性都可以从 Spring 的 `Environment` 中获得。
例如，您可以将  `log4j2.skipJansi=false`  添加到  `application.properties` 文件中，以使  `ConsoleAppender`  在 Windows 上使用 Jansi。

NOTE: 仅当系统属性和操作系统环境变量不包含正在加载的值时，才会考虑 Spring `Environment`

WARNING: 在早期 Log4j2 初始化期间加载的系统属性不能引用 Spring 的 `Environment`。 例如，在 Spring 环境可用之前，将使用 Log4j2 用于允许选择默认 Log4j2 实现的属性。
