[[features.spring-application]]
== SpringApplication
`SpringApplication` 类提供了一种可通过运行 `main()` 方法来启动 Spring 应用的简单方式. 大多数情况下,您只需要委托给静态的 `SpringApplication.run` 方法:

include::code:MyApplication[]

当应用启动时,您应该会看到类似以下的内容输出:

[indent=0,subs="verbatim,attributes"]
----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.0.0)

2022-11-24T17:03:48.214Z  INFO 20764 --- [           main] o.s.b.d.f.s.MyApplication                : Starting MyApplication using Java 17.0.5 with PID 20764 (/opt/apps/myapp.jar started by myuser in /opt/apps/)
2022-11-24T17:03:48.219Z  INFO 20764 --- [           main] o.s.b.d.f.s.MyApplication                : No active profile set, falling back to 1 default profile: "default"
2022-11-24T17:03:50.511Z  INFO 20764 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-11-24T17:03:50.524Z  INFO 20764 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-11-24T17:03:50.524Z  INFO 20764 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.1]
2022-11-24T17:03:50.623Z  INFO 20764 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-11-24T17:03:50.625Z  INFO 20764 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2269 ms
2022-11-24T17:03:51.380Z  INFO 20764 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2022-11-24T17:03:51.418Z  INFO 20764 --- [           main] o.s.b.d.f.s.MyApplication                : Started MyApplication in 3.872 seconds (process running for 5.008)
2022-11-24T17:03:51.506Z  INFO 20764 --- [ionShutdownHook] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
----

默认情况下,将显示 `INFO` 级别的日志信息,包括一些应用启动相关信息. 如果您需要修改 `INFO` 日志级别,请参考 <<features#features.logging.log-levels>>.

使用主应用程序类包中的实现版本来确定应用程序版本.  可以通过将 `spring.main.log-startup-info` 设置为 `false` 来关闭启动信息记录.  这还将关闭对应用程序 active 配置文件的日志记录.

TIP: 要在启动期间添加其他日志记录,可以在 `SpringApplication` 的子类中重写 `logStartupInfo(boolean)`.

[[features.spring-application.startup-failure]]
=== 启动失败
如果您的应用无法启动,注册的 `FailureAnalyzers` 可能会提供有相关的错误信息和解决问题的具体方法. 例如,如果您在已经被占用的 `8080` 端口上启动了一个 web 应用,会看到类似以下的错误信息:
[indent=0]
----
	***************************
	APPLICATION FAILED TO START
	***************************

	Description:

	Embedded servlet container failed to start. Port 8080 was already in use.

	Action:

	Identify and stop the process that is listening on port 8080 or configure this application to listen on another port.
----

NOTE: Spring Boot 提供了许多的 `FailureAnalyzer` 实现,您也可以 <<howto#howto.application.failure-analyzer,添加自己的实现>>.

如果没有失败分析器能够处理的异常, 您仍然可以显示完整的条件报告以便更好地了解出现的问题. 为此,您需要针对 `org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener` <<features#features.external-config,启用 `debug` 属性>> 或者 <<features#features.logging.log-levels,开启 `DEBUG` 日志>>.

例如,如果您使用 `java -jar` 运行应用,可以按以下方式启用 `debug` 属性:

[source,shell,indent=0,subs="verbatim"]
----
	$ java -jar myproject-0.0.1-SNAPSHOT.jar --debug
----

[[features.spring-application.lazy-initialization]]
=== 延迟初始化
`SpringApplication` 允许延迟地初始化应用程序. 启用延迟初始化后,将根据需要创建 bean,而不是在应用程序启动期间创建 bean.  因此,启用延迟初始化可以减少应用程序启动所需的时间.  在 Web 应用程序中,启用延迟初始化将导致许多与 Web 相关的 Bean 在收到 HTTP 请求后才被初始化.

延迟初始化的缺点是,它可能会延迟发现应用程序问题的时间.  如果配置错误的 Bean 延迟初始化,则在启动期间不会发生问题,并且只有在初始化 Bean 时问题才会变得明显.  还必须注意确保 JVM 有足够的内存来容纳所有应用程序的 bean,而不仅仅是启动期间初始化的 bean.  由于这些原因,默认情况下不会启用延迟初始化,因此建议在启用延迟初始化之前先对 JVM 的堆大小进行微调.

可以使用 `SpringApplicationBuilder` 上的 `lazyInitialization` 方法或 `SpringApplication` 上的 `setLazyInitialization` 方法以编程方式启用延迟初始化.  另外,可以使用 `spring.main.lazy-initialization` 属性启用它,如以下示例所示:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  main:
	    lazy-initialization: true
----

TIP: 如果您禁用了延迟初始化，但对应用程序其余部分使用延迟初始化时, 则可以使用 `@Lazy(false)` 注解将它们的延迟属性显式设置为 `false`.

[[features.spring-application.banner]]
=== 自定义 banner
可以通过在 classpath 下添加一个 `banner.txt` 文件,或者将 `spring.banner.location`  属性指向该文件的位置来更改启动时打印的 banner. 如果文件采用了非 UTF-8 编码,
您可以设置 `spring.banner.charset` 来解决.

您可以在 `banner.txt` 文件中使用 `Environment` 环境变量以及以下占位符:

.Banner 变量
|===
| 变量 | 描述

| `${application.version}`
| 您的应用版本号,声明在 `MANIFEST.MF` 中. 例如,`Implementation-Version: 1.0` 将被打印为 `1.0`.

| `${application.formatted-version}`
| 您的应用版本号,声明在 `MANIFEST.MF` 中,格式化之后打印 (用括号括起来,以 `v` 为前缀) ,例如 `(v1.0)`.

| `${spring-boot.version}`
| 您使用的 Spring Boot 版本. 例如 `{spring-boot-version}`.

| `${spring-boot.formatted-version}`
| 您使用的 Spring Boot 版本格式化之后显示 (用括号括起来,以 `v` 为前缀) . 例如 `(v{spring-boot-version})`.

| `${Ansi.NAME}` (or `${AnsiColor.NAME}`, `${AnsiBackground.NAME}`, `${AnsiStyle.NAME}`)
| 其中 `NAME` 是 ANSI 转义码的名称. 有关详细信息,请参阅 {spring-boot-module-code}/ansi/AnsiPropertySource.java[`AnsiPropertySource`].

| `${application.title}`
| 您的应用标题,声明在 `MANIFEST.MF` 中,例如 `Implementation-Title: MyApp` 打印为 `MyApp`.
|===

TIP: 如果您想以编程的方式生成 banner,可以使用 `SpringApplication.setBanner(...)` 方法. 使用 `org.springframework.boot.Banner` 接口并实现自己的 `printBanner()` 方法.

您还可以使用 `spring.main.banner-mode` 属性来确定是否必须在  `System.out` (`console`) 上打印 banner, 还是使用日志记录器 (`log`) 或者都不打印 (`off`).

打印的 banner 的单例 bean 为：  `springBootBanner` .

[NOTE]
====
只有在使用 Spring Boot 启动时， `$ {application.version}` 和 `${application.formatted-version}` 属性才可用.
如果您运行的是未打包的 jar 并以 `java -cp <classpath> <mainclass>` 开头， 则无法解析这些值.

这就是为什么我们建议您始终使用通过 `java org.springframework.boot.loader.JarLauncher` 来启动未打包的 jar 的原因.
这将在构建类路径并启动您的应用程序之前初始化 `application.*` 变量.
====

[[features.spring-application.customizing-spring-application]]
=== 自定义 SpringApplication

如果 `SpringApplication` 的默认设置不符合您的想法,您可以创建本地实例进行定制化. 例如,要关闭 banner,您可以这样:

include::code:MyApplication[]

NOTE: 传入 `SpringApplication` 的构造参数是 Spring beans 的配置源. 大多情况下是引用 `@Configuration` 类,但您也可以引用 XML 配置或者被扫描的包.

也可以使用 `application.properties` 文件配置 `SpringApplication`. 有关详细信息,请参见 _<<features#features.external-config>>_.

关于配置选项的完整列表,请参阅  {spring-boot-module-api}/SpringApplication.html[`SpringApplication` Javadoc].

[[features.spring-application.fluent-builder-api]]
=== Fluent Builder API(流式构建 API)
如果您需要构建一个有层级关系的 `ApplicationContext` (具有父/子关系的多上下文) ,或者偏向使用 fluent (流式) 构建器 API,可以使用 `SpringApplicationBuilder`.

`SpringApplicationBuilder` 允许您链式调用多个方法,包括能创建出具有层次结构的 `parent` 和 `child` 方法.

例如:

include::code:MyApplication[tag=*]

NOTE: 创建层级的 `ApplicationContext` 时有部分限制,比如 Web 组件必须包含在子上下文中,并且相同的 `Environment` 将作用于父子上下文. 有关详细信息,请参阅 {spring-boot-module-api}/builder/SpringApplicationBuilder.html[`SpringApplicationBuilder` Javadoc] .

[[features.spring-application.application-availability]]
=== 应用程序的可用性
在平台上部署后,应用程序可以使用诸如 https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/[Kubernetes Probes] 之类的基础结构向平台提供有关其可用性的信息. Spring Boot 对常用的 "`liveness`"  和 "`readiness`" 可用性状态提供了开箱即用的支持. 如果您使用了 Spring Boot 的 "`actuator`" 支持,则这些状态将显示为运行状况端点组.

另外,您还可以通过将 `ApplicationAvailability` 接口注入到您自己的bean中来获取可用性状态.

[[features.spring-application.application-availability.liveness]]
==== Liveness State
应用程序的 "`Liveness`"  状态表明其内部是否正常运行,或者在当前出现故障时自行恢复. 一个 broken （损坏）的 "`Liveness`"  状态意味着应用程序处于无法恢复的状态,并且应重新启动应用程序.

NOTE: 通常,"Liveness" 状态不应基于外部检查 (例如  <<actuator#actuator.endpoints.health, Health checks>>) . 如果确实如此,则发生故障的外部系统 (数据库,Web API,外部缓存) 将触发整个平台的大量重启和级联故障.

Spring Boot 应用程序的内部状态主要由 Spring `ApplicationContext` 表示. 如果应用程序上下文已成功启动,则 Spring Boot 会假定该应用程序处于有效状态. 刷新上下文后,应用程序即被视为活动应用程序,请参阅 <<features#features.spring-application.application-events-and-listeners, Spring Boot 应用程序生命周期和相关的应用程序事件>>.

[[features.spring-application.application-availability.readiness]]
==== Readiness State
应用程序的 "`Readiness`" 状态告诉应用程序是否已准备好处理流量. failing（失败的） "`Readiness`" 状态告诉平台当前不应将流量路由到应用程序. 这通常发生在启动过程中,正在处理 `CommandLineRunner` 和 `ApplicationRunner` 组件时,或者在应用程序认为它太忙而无法获得额外流量的情况下.

一旦调用了应用程序和命令行运行程序,就认为该应用程序已准备就绪,请参阅 <<features#features.spring-application.application-events-and-listeners, Spring Boot 应用程序生命周期和相关的应用程序事件>>.

TIP: 预期在启动期间运行的任务应由 `CommandLineRunner` 和 `ApplicationRunner` 组件执行,而不是使用 Spring 组件生命周期回调 (如 `@PostConstruct`) 执行.

[[features.spring-application.application-availability.managing]]
==== 管理应用程序可用性状态
通过注入 `ApplicationAvailability` 接口并调用其方法,应用程序组件可以随时检索当前的可用性状态. 应用程序通常会希望监听状态更新或更新应用程序的状态.

例如,我们可以将应用程序的  "Readiness" 状态导出到文件中,以便 Kubernetes 的 "exec Probe" 可以查看此文件:

include::code:MyReadinessStateExporter[]

当应用程序崩溃且无法恢复时,我们还可以更新应用程序的状态:

include::code:MyLocalCacheVerifier[]

Spring Boot 通过 <<actuator#actuator.endpoints.kubernetes-probes,Kubernetes HTTP probes for "Liveness" and "Readiness" with Actuator Health Endpoints>>.您可以在专用部分中获得 <<deployment#deployment.cloud.kubernetes,有关在 Kubernetes 上部署 Spring Boot 应用程序的更多指南>>.

[[features.spring-application.application-events-and-listeners]]
=== 应用程序事件与监听器
除了常见的 Spring Framework 事件,比如  {spring-framework-api}/context/event/ContextRefreshedEvent.html[`ContextRefreshedEvent`], `SpringApplication` 还会发送其他应用程序事件.

[NOTE]
====
在 `ApplicationContext` 创建之前,实际上触发了一些事件,因此您不能像 `@Bean` 一样注册监听器. 您可以通过 `SpringApplication.addListeners(...)` 或者 `SpringApplicationBuilder.listeners(...)` 方法注册它们.

如果您希望无论应用使用何种创建方式都能自动注册这些监听器,您都可以将 `META-INF/spring.factories` 文件添加到项目中,并使用 `org.springframework.context.ApplicationListener` 属性键指向您的监听器. 比如:

[indent=0]
----
	org.springframework.context.ApplicationListener=com.example.project.MyListener
----

====

当您运行应用时,应用程序事件将按照以下顺序发送:

. 在开始应用开始运行但还没有进行任何处理时 (除了注册 listeners 和 initializers ) ,将发送 `ApplicationStartingEvent`.
. 当 `Environment` 被上下文使用,但是在上下文创建之前,将发送 `ApplicationEnvironmentPreparedEvent`.
. 准备 `ApplicationContext` 并调用 `ApplicationContextInitializers` 之后但在加载任何 bean 定义之前,将发送 `ApplicationContextInitializedEvent`.
. 开始刷新之前,bean 定义被加载之后发送 `ApplicationPreparedEvent`.
. 在上下文刷新之后且所有的应用和命令行运行器 (command-line runner) 被调用之前发送 `ApplicationStartedEvent`.
. 紧随其后发送带有 `LivenessState.CORRECT` 的 `AvailabilityChangeEvent`,以指示该应用程序处于活动状态.
. 在 <<features#features.spring-application.command-line-runner,应用程序和命令行运行器 (command-line runner)>>  被调用之后,将发出,将发送 `ApplicationReadyEvent`.
. 随即在 `ReadinessState.ACCEPTING_TRAFFIC` 之后发送 `AvailabilityChangeEvent`,以指示该应用程序已准备就绪,可以处理请求.
. 如果启动时发生异常,则发送 `ApplicationFailedEvent`.

上面的列表仅包含绑定到 `SpringApplication` 的 ``SpringApplicationEvent``s.  除这些以外,以下事件也在 `ApplicationPreparedEvent` 之后和 `ApplicationStartedEvent` 之前发布:

. `WebServer` 准备就绪后,将发送 `WebServerInitializedEvent`.  `ServletWebServerInitializedEvent` 和 `ReactiveWebServerInitializedEvent` 分别是 servlet 和 reactive 变量.
. 刷新 `ApplicationContext` 时,将发送 `ContextRefreshedEvent` 事件.

TIP: 您可能不会经常使用应用程序事件,但了解他们的存在还是很有必要的. 在框架内部,Spring Boot 使用这些事件来处理各种任务.

NOTE: 默认情况下,事件监听器不应该运行可能很长的任务,因为它们在同一个线程中执行.考虑改用 <<features#features.spring-application.command-line-runner,application and command-line runners>>.

应用程序事件发送使用了 Spring Framework 的事件发布机制. 该部分机制确保在子上下文中发布给监听器的事件也会发布给所有祖先上下文中的监听器. 因此,如果您的应用程序使用有层级结构的 `SpringApplication` 实例,则监听器可能会收到同种类型应用程序事件的多个实例.

为了让监听器能够区分其上下文事件和后代上下文事件,您应该注入其应用程序上下文,然后将注入的上下文与事件的上下文进行比较. 可以通过实现 `ApplicationContextAware` 来注入上下文,如果监听器是 bean,则使用 `@Autowired` 注入上下文.

[[features.spring-application.web-environment]]
=== Web 环境
`SpringApplication` 试图为您创建正确类型的 `ApplicationContext`. 确定 `WebApplicationType` 的算法非常简单:

* 如果存在 Spring MVC,则使用 `AnnotationConfigServletWebServerApplicationContext`
* 如果 Spring MVC 不存在且存在 Spring WebFlux,则使用 `AnnotationConfigReactiveWebServerApplicationContext`
* 否则,使用 `AnnotationConfigApplicationContext`

这意味着如果您在同一个应用程序中使用了 Spring MVC 和 Spring WebFlux 中的新 `WebClient`, 默认情况下将使用 Spring MVC. 您可以通过调用 `setWebApplicationType(WebApplicationType)` 修改默认行为.

也可以调用 `setApplicationContextClass(...)` 来完全控制 `ApplicationContext` 类型.

TIP: 在 JUnit 测试中使用 `SpringApplication` 时,通常需要调用 `setWebApplicationType(WebApplicationType.NONE)`.

[[features.spring-application.application-arguments]]
=== 访问应用程序参数

如果您需要访问从 `SpringApplication.run(...)` 传入的应用程序参数,可以注入一个 `org.springframework.boot.ApplicationArguments` bean. `ApplicationArguments` 接口提供了访问原始 `String[]` 参数以及解析后的 `option` 和 `non-option` 参数的方法:

include::code:MyBean[]

TIP: Spring Boot 还向 Spring `Environment` 注册了一个 `CommandLinePropertySource`. 这允许您可以使用 `@Value` 注解注入单个应用参数.

[[features.spring-application.command-line-runner]]
=== 使用 ApplicationRunner 或 CommandLineRunner

如果您需要在 `SpringApplication` 启动时运行一些代码,可以实现 `ApplicationRunner` 或者 `CommandLineRunner` 接口. 这两个接口的工作方式是一样的,都提供了一个单独的 `run` 方法,它将在 `SpringApplication.run(...)` 完成之前调用.

NOTE: 这个契约非常适合那些应该在应用程序启动后但在它开始接受流量之前运行的任务.

`CommandLineRunner` 接口提供了访问应用程序字符串数组形式参数的方法,而 `ApplicationRunner` 则使用了上述的 `ApplicationArguments` 接口. 以下示例展示 `CommandLineRunner` 和 `run` 方法的使用:

include::code:MyCommandLineRunner[]

如果您定义了多个 `CommandLineRunner` 或者 `ApplicationRunner` bean,则必须指定调用顺序,您可以实现 `org.springframework.core.Ordered` 接口,也可以使用 `org.springframework.core.annotation.Order` 注解解决顺序问题.

[[features.spring-application.application-exit]]
=== 应用程序退出
每个 `SpringApplication` 注册了一个 JVM 关闭钩子,以确保 `ApplicationContext` 在退出时可以优雅关闭. 所有标准的 Spring 生命周期回调 (比如 `DisposableBean` 接口,或者 `@PreDestroy` 注解) 都可以使用.

此外,如果希望在调用 `SpringApplication.exit()` 时返回特定的退出码,则 bean 可以实现 `org.springframework.boot.ExitCodeGenerator` 接口. 之后退出码将传递给 `System.exit()` 以将其作为状态码返回,如示例所示:

include::code:MyApplication[]

此外,`ExitCodeGenerator` 接口可以通过异常实现. 遇到这类异常时,Spring Boot 将返回实现的 `getExitCode()` 方法提供的退出码.

如果有多个  `ExitCodeGenerator`，则使用生成的第一个非零退出代码。
要控制调用生成器的顺序，请另外实现 `org.springframework.core.Ordered` 接口或使用 `org.springframework.core.annotation.Order`  注解。

[[features.spring-application.admin]]
=== Admin Features（管理功能）
可以通过指定 `spring.application.admin.enabled`  属性来为应用程序启用管理相关的功能. 其将在 `MBeanServer` 平台上暴露  {spring-boot-module-code}/admin/SpringApplicationAdminMXBean.java[`SpringApplicationAdminMXBean`]. 您可以使用此功能来远程管理 Spring Boot 应用. 该功能对服务包装器的实现也是非常有用的.

TIP: 如果您想知道应用程序在哪一个 HTTP 端口上运行,请使用 `local.server.port` 键获取该属性.

[[features.spring-application.startup-tracking]]
=== Application Startup tracking（应用程序启动跟踪）
在应用程序启动期间，`SpringApplication` 和 `ApplicationContext` 执行许多与应用程序生命周期、bean 生命周期甚至处理应用程序事件相关的任务. 使用 {spring-framework-api}/core/metrics/ApplicationStartup.html[`ApplicationStartup`], Spring 框架允许你使用 {spring-framework-docs}/core.html#context-functionality-startup[`StartupStep` 对象跟踪应用程序的启动顺序]. 收集这些数据可以用于分析目的，或者只是为了更好地理解应用程序启动过程.

您可以在设置 `SpringApplication` 实例时选择 `ApplicationStartup` 实现. 例如，要使用 `BufferingApplicationStartup`，您可以编写:

include::code:MyApplication[]

第一个可用的实现是由 Spring 框架提供的 `FlightRecorderApplicationStartup`. 它将特定于 Spring 的启动事件添加到 Java Flight Recorder 会话中，用于分析应用程序，并将其 Spring 上下文生命周期与 JVM 事件(如 allocations、gc、类加载……)关联起来. 一旦配置好，你就可以通过启用 Flight Recorder 运行应用程序来记录数据:

[source,shell,indent=0,subs="verbatim"]
----
	$ java -XX:StartFlightRecording:filename=recording.jfr,duration=10s -jar demo.jar
----

Spring Boot 附带 `BufferingApplicationStartup` ,这个实现的目的是缓冲启动步骤，并将它们抽取到外部指标系统中. 应用程序可以在任何组件中请求 `BufferingApplicationStartup` 类型的bean. 此外，Spring Boot Actuator 将 {spring-boot-actuator-restapi-docs}/#startup[将暴露一个 `startup` 端点以将此信息公开为 JSON 文档].
