[[features.testing]]
== 测试

Spring Boot 提供了许多工具类和注解,可以在测试应用程序时提供帮助.  主要由两个模块提供: `spring-boot-test` 包含核心项,`spring-boot-test-autoconfigure` 支持测试的自动配置.

大多数开发人员都使用 `spring-boot-starter-test` "`Starter`",它会导入 Spring Boot 测试模块以及 JUnit Jupiter, AssertJ, Hamcrest 和许多其他有用的库.

[TIP]
====
如果您有使用 JUnit 4 的测试，可以使用 JUnit 5 的  vintage engine 来运行它们。要使用 vintage engine，添加一个依赖 `junit-vintage-engine`，如下所示:

[source,xml,indent=0,subs="verbatim"]
----
	<dependency>
		<groupId>org.junit.vintage</groupId>
		<artifactId>junit-vintage-engine</artifactId>
		<scope>test</scope>
		<exclusions>
			<exclusion>
				<groupId>org.hamcrest</groupId>
				<artifactId>hamcrest-core</artifactId>
			</exclusion>
		</exclusions>
	</dependency>
----
====

`hamcrest-core` 被排除在外，因为  `spring-boot-starter-test`  默认支持 `org.hamcrest:hamcrest` 。

[[features.testing.test-scope-dependencies]]
=== 测试依赖
`spring-boot-starter-test` "`Starter`" (在 `test` `scope`) 包含以下的库:

* https://junit.org/junit5/[JUnit 5]: Java 应用程序单元测试的标准。
* {spring-framework-docs}/testing.html#integration-testing[Spring 测试] & Spring Boot 测试: 对 Spring Boot 应用程序的实用程序和集成测试支持.
* https://assertj.github.io/doc/[AssertJ]: 流式的断言库.
* https://github.com/hamcrest/JavaHamcrest[Hamcrest]: 匹配对象库 (也称为约束或断言) .
* https://site.mockito.org/[Mockito]: 一个 Java 模拟框架.
* https://github.com/skyscreamer/JSONassert[JSONassert]: JSON 的断言库.
* https://github.com/jayway/JsonPath[JsonPath]: JSON 的 XPath.

通常,我们发现这些通用库在编写测试时很有用.  如果这些库不满足您的需求,则可以添加自己的其他测试依赖.

[[features.testing.spring-applications]]
=== 测试 Spring 应用程序
依赖注入的主要优点之一是,它应该使您的代码更易于进行单元测试. 您可以不使用 Spring， 使用 `new` 运算符实例化对象. 您还可以使用 _mock objects_ 而不是实际的依赖.

通常,您可能不仅仅需要单元测试，也需要集成测试 (使用 Spring `ApplicationContext`) . 能够进行集成测试而无需部署应用程序或连接到其他基础结构是很有用的.

Spring 框架包括用于此类集成测试的专用测试模块.  您可以直接声明 `org.springframework:spring-test` 依赖,也可以使用 `spring-boot-starter-test` "`Starter`" 将其传递.

如果您以前没有使用过 `spring-test` 模块,则应先阅读 {spring-framework-docs}/testing.html#testing[Spring Framework 参考文档的相关部分] .

[[features.testing.spring-boot-applications]]
=== 测试 Spring Boot 应用程序
Spring Boot 应用程序是 Spring `ApplicationContext`, 因此除了对普通 Spring 上下文进行常规测试以外,无需执行任何其他特殊操作即可对其进行测试.

NOTE: 默认情况下,仅当您使用 `SpringApplication` 创建 Spring Boot 的外部属性,日志记录和其他功能时,才将它们安装在上下文中.

Spring Boot 提供了 `@SpringBootTest` 注解,当您需要 Spring Boot 功能时,可以将其用作标准 `spring-test` `@ContextConfiguration` 注解的替代方法.  <<features#features.testing.spring-boot-applications.detecting-configuration,注解通过 `SpringApplication` 在测试中创建 `ApplicationContext` 来使用>>.
除了 `@SpringBootTest` 之外,还提供了许多其他注解来测试应用程序的 <<features#features.testing.spring-boot-applications.autoconfigured-tests,特定的部分>>.

TIP: 如果您使用的是 JUnit 4,请不要忘记也将 `@RunWith(SpringRunner.class)` 添加到测试中,否则注解将被忽略.  如果您使用的是 JUnit 5,则无需将等效的 `@ExtendWith(SpringExtension.class)`  添加为 `@SpringBootTest`,而其他 `@...Test` 注解已经在其中进行了注解.

默认情况下,`@SpringBootTest` 将不会启动服务器.  您可以使用 `@SpringBootTest` 的 `webEnvironment` 属性来进一步完善测试的运行方式:

* `MOCK`(默认) : 加载 Web ApplicationContext 并提供模拟 Web 环境.  使用此注解时,不会启动嵌入式服务器.
如果您的类路径上没有 Web 环境,则此模式将透明地退回到创建常规的非 Web `ApplicationContext`.  它可以与  <<features#features.testing.spring-boot-applications.with-mock-environment, `@AutoConfigureMockMvc` 或 `@AutoConfigureWebTestClient`>> 结合使用,以对 Web 应用程序进行基于 Mock 的测试.
* `RANDOM_PORT`: 加载 `WebServerApplicationContext` 并提供真实的 Web 环境.  在随机的端口启动并监听嵌入式服务器.
* `DEFINED_PORT`: 加载 `WebServerApplicationContext` 并提供真实的 Web 环境.  在定义的端口(来自 `application.properties`) 或 `8080` 端口启动并监听嵌入式服务器
* `NONE`: 使用 `SpringApplication` 加载 `ApplicationContext`,但不提供任何 Web 环境 (模拟或其他方式) .

NOTE: 如果您测试的是 `@Transactional`,则默认情况下它将在每个测试方法的末尾回滚事务. 但是,由于将这种安排与 `RANDOM_PORT` 或 `DEFINED_PORT` 一起使用隐式提供了一个真实的 Servlet 环境,因此 HTTP 客户端和服务器在单独的线程中运行,因此在单独的事务中运行.  在这种情况下,服务器上启动的任何事务都不会回滚.

NOTE: 如果您的应用程序将不同的端口用于管理服务器,则 `@SpringBootTest` 的 `webEnvironment=WebEnvironment.RANDOM_PORT` 也将在单独的随机端口上启动管理服务器.

[[features.testing.spring-boot-applications.detecting-web-app-type]]
==== 检测 Web 应用程序类型
如果 Spring MVC 可用,则配置基于常规 MVC 的应用程序上下文. 如果您只有 Spring WebFlux,我们将检测到该情况并配置基于 WebFlux 的应用程序上下文.

如果两者都存在,则 Spring MVC 优先.  如果要在这种情况下测试响应式 Web 应用程序,则必须设置 `spring.main.web-application-type` 属性:

include::code:MyWebFluxTests[]

[[features.testing.spring-boot-applications.detecting-configuration]]
==== 检测测试配置

如果您熟悉 Spring Test Framework,则可能习惯于使用 `@ContextConfiguration(classes=...)` 以指定要加载哪个Spring `@Configuration`.  另外,您可能经常在测试中使用嵌套的 `@Configuration` 类.

在测试 Spring Boot 应用程序时,通常不需要这样做.  只要您没有明确定义,Spring Boot 的 `@*Test` 注解就会自动搜索您的主要配置.

搜索算法从包含测试的程序包开始工作,直到找到带有 `@SpringBootApplication` 或 `@SpringBootConfiguration` 注解的类.  只要您以合理的方式对  <<using#using.structuring-your-code,代码进行结构化>>,通常就可以找到您的主要配置.

[NOTE]
====
如果您使用 <<features#features.testing.spring-boot-applications.autoconfigured-tests, 测试注解来测试应用程序的特定部分>> , 则应避免在 <<features#features.testing.spring-boot-applications.user-configuration-and-slicing, 应用程序的 main 方法>> 中添加特定于特定区域的配置设置.

`@SpringBootApplication` 的基础组件扫描配置定义了排除过滤器,这些过滤器用于确保切片按预期工作.  如果在 `@SpringBootApplication` 注解的类上使用显式的 `@ComponentScan` 指令,请注意这些过滤器将被禁用.  如果使用切片,则应再次定义它们.
====

如果要自定义主要配置类,则可以使用嵌套的 `@TestConfiguration` 类. 与嵌套的 `@Configuration` 类不同，它将用于代替应用程序的主要配置 , 嵌套的 `@TestConfiguration` 类用于应用程序的主要配置之外。

NOTE: Spring 的测试框架在测试之间缓存应用程序上下文.  因此,只要您的测试共享相同的配置 (无论如何发现) ,加载上下文的潜在耗时过程就只会发生一次.

[[features.testing.spring-boot-applications.using-main]]
==== 使用测试配置主方法
通常， `@SpringBootTest` 发现的测试配置将是您的主要  `@SpringBootApplication`。 在大多数的应用程序中，此配置类还将包括用于启动应用程序的 `main` 方法。

例如，以下是一个典型的 Spring Boot 应用程序非常常见的代码模式：

include::code:typical/MyApplication[]

在上面的示例中，`main` 方法除了委托给 `SpringApplication.run` 之外没有做任何事情。
但是，可以有一个更复杂的 `main` 方法，在调用 `SpringApplication.run` 之前应用定制。

例如，这是一个更改 banner 模式并设置其他配置文件的应用程序：

include::code:custom/MyApplication[]

由于 `main` 方法中的自定义会影响生成的 `ApplicationContext`，因此您可能还想使用 `main` 方法来创建用于测试的 `ApplicationContext`。
默认情况下， `@SpringBootTest` 不会调用您的 `main` 方法，而是直接使用类本身来创建 `ApplicationContext`

如果要更改此行为，可以将 `@SpringBootTest` 的 `useMainMethod` 属性更改为 `UseMainMethod.ALWAYS` 或 `UseMainMethod.WHEN_AVAILABLE`。
当设置为 `ALWAYS` 时，如果找不到 `main` 方法，测试将失败。
当设置为 `WHEN_AVAILABLE` 时，如果可用，将使用 `main` 方法，否则将使用标准加载机制。

例如，以下测试将调用 `MyApplication` 的 `main` 方法来创建 `ApplicationContext`。
如果 main 方法设置了额外的配置文件，那么这些配置文件将在 `ApplicationContext` 启动时处于活动状态。

include::code:always/MyApplicationTests[]

[[features.testing.spring-boot-applications.excluding-configuration]]
==== 排除测试配置
如果您的应用程序使用了组件扫描 (例如,如果使用 `@SpringBootApplication` 或 `@ComponentScan` ) ,则可能会发现偶然为各地创建的仅为特定测试创建的顶级配置类.

<<features#features.testing.spring-boot-applications.detecting-configuration,如前所述>>,`@TestConfiguration` 可以用于测试的内部类以自定义主要配置.  当放置在顶级类上时, `@TestConfiguration` 指示不应通过扫描选择 `src/test/java` 中的类.  然后,可以在需要的位置显式导入该类,如以下示例所示:

include::code:MyTests[]

NOTE: 如果直接使用 `@ComponentScan` (即不是通过 `@SpringBootApplication`) ,则需要向其中注册 `TypeExcludeFilter`.  有关详细信息,请参见 {spring-boot-module-api}/context/TypeExcludeFilter.html[ Javadoc].

[[features.testing.spring-boot-applications.using-application-arguments]]
==== 使用应用程序参数
如果您的应用程序需要 <<features#features.spring-application.application-arguments,参数>>,则可以使用 `args` 属性让 `@SpringBootTest` 注入参数.

include::code:MyApplicationArgumentTests[]

[[features.testing.spring-boot-applications.with-mock-environment]]
==== 在模拟环境中进行测试
默认情况下, `@SpringBootTest` 不会启动服务器. 而是设置一个模拟环境来测试 Web 端点.

使用 Spring MVC，我们可以使用 {spring-framework-docs}/testing.html#spring-mvc-test-framework[`MockMvc`] 或 `WebTestClient` 查询我们的 Web 端点，如下例所示:

include::code:MyMockMvcTests[]

TIP: 如果只想关注 Web 层而不希望启动完整的 `ApplicationContext`,请考虑使用  <<features#features.testing.spring-boot-applications.spring-mvc-tests, `@WebMvcTest`>>.

使用 Spring WebFlux 端点, 您可以配置 {spring-framework-docs}/testing.html#webtestclient-tests[`WebTestClient`] ,如以下示例所示:

include::code:MyMockWebTestClientTests[]

[TIP]
====
在模拟环境中进行测试通常比在完整的 Servlet 容器中运行更快.但是, 由于模拟发生在 Spring MVC 层,因此无法使用 MockMvc 直接测试依赖于较低级别 Servlet 容器行为的代码.

例如,Spring Boot 的错误处理基于 Servlet 容器提供的  "`error page`"  支持.  这意味着, 尽管您可以按预期测试 MVC 层引发并处理异常,但是您无法直接测试是否呈现了特定的 <<web#web.servlet.spring-mvc.error-handling.error-pages, 自定义错误页面>>.  如果需要测试这些较低级别的问题,则可以按照下一节中的描述启动一个完全运行的服务器.
====

[[features.testing.spring-boot-applications.with-running-server]]
==== 使用正在运行的服务器进行测试
如果需要启动完全运行的服务器, 建议您使用随机端口. 如果使用 `@SpringBootTest(webEnvironment=WebEnvironment.RANDOM_PORT)`, 则每次运行测试时都会随机选择一个可用端口.

`@LocalServerPort` 注解可用于将  <<howto#howto.webserver.discover-port,将实际使用的端口注入>> 测试中. 为了方便起见,需要对已启动的服务器进行 REST 调用的测试可以 `@Autowire` 附加地使用 `WebTestClient`,
该 {spring-framework-docs}/testing.html#webtestclient-tests[`WebTestClient`] 解析到正在运行的服务器的相对链接,并带有用于验证响应的专用 API,如以下示例所示:

include::code:MyRandomPortWebTestClientTests[]

TIP: `WebTestClient` 可用于实时服务器和 <<features#features.testing.spring-boot-applications.with-mock-environment, mock 环境>>.

这种设置需要在类路径上使用 `spring-webflux`.  如果您不能 webflux,则 Spring Boot 还提供了 `TestRestTemplate` 工具:

include::code:MyRandomPortTestRestTemplateTests[]

[[features.testing.spring-boot-applications.customizing-web-test-client]]
==== 自定义 WebTestClient
要定制 `WebTestClient` bean,请配置 `WebTestClientBuilderCustomizer` bean.  将使用用于创建 `WebTestClient` 的 `WebTestClient.Builder` 调用任何此类 bean.

[[features.testing.spring-boot-applications.jmx]]
==== 使用 JMX
由于测试上下文框架缓存上下文,因此默认情况下禁用 JMX 以防止相同组件在同一 domain 上注册.  如果此类测试需要访问 `MBeanServer`,请考虑将其标记为 dirty:

include::code:MyJmxTests[]

[[features.testing.spring-boot-applications.metrics]]
==== 使用 Metrics
无论您的类路径是什么，在使用 `@SpringBootTest` 时，meter 注册表(内存中支持的除外)都不会自动配置。

如果您需要将指标作为集成测试的一部分导出到不同的后端，请使用 `@AutoConfigureMetrics` 注解它。

[[features.testing.spring-boot-applications.tracing]]
==== Using Tracing
无论您的类路径如何，使用 `@SpringBootTest` 时都不会自动配置追踪。

如果您需要将跟踪作为集成测试的一部分，请使用 `@AutoConfigureObservability` 对其进行注解。

[[features.testing.spring-boot-applications.mocking-beans]]
==== Mocking（模拟） 和 Spying（检测） Beans
运行测试时,有时有必要在应用程序上下文中模拟某些组件.  例如, 您可能在开发过程中无法使用某些远程服务的 facade.  当您要模拟在实际环境中可能难以触发的故障时,模拟也很有用.

Spring Boot 包含一个 `@MockBean` 注解,可用于为 `ApplicationContext` 中的 bean 定义 `Mockito` 模拟.  您可以使用注解添加新 bean 或替换单个现有 bean 定义.  注解可以直接用于测试类,测试中的字段或 `@Configuration` 类和字段.
在字段上使用时,还将注入创建的模拟的实例.  每种测试方法后,模拟 Bean 都会自动重置.

[NOTE]
====
如果您的测试使用 Spring Boot 的测试注解之一 (例如 `@SpringBootTest`) ,则会自动启用此功能.  要以其他方式使用此功能,必须显式添加监听器,如以下示例所示:

include::code:listener/MyTests[]
====

下面的示例用模拟实现替换现有的 `RemoteService` bean:

include::code:bean/MyTests[]

NOTE: `@MockBean` 不能用于模拟应用程序上下文刷新期间执行的 bean 的行为.  到执行测试时,应用程序上下文刷新已完成,并且配置模拟行为为时已晚.  我们建议在这种情况下使用 `@Bean` 方法创建和配置模拟.

此外,您可以使用 `@SpyBean` 用 Mockito  `spy` 包装任何现有的 bean.  有关完整的详细信息,请参见 {spring-boot-test-module-api}/mock/mockito/SpyBean.html[Javadoc].

NOTE: CGLib代理 (例如为作用域内的 Bean 创建的代理) 将代理方法声明为 `final`.  这将阻止 Mockito 正常运行,因为它无法在其默认配置中模拟或监视最终方法.
如果要模拟或监视这样的 bean,请通过将 `org.mockito:mockito-inline` 添加到应用程序的测试依赖中,将 Mockito 配置为使用其嵌入式模拟生成器.  这允许 Mockito 模拟和监视  `final`  方法.

NOTE: Spring 的测试框架在测试之间缓存应用程序上下文,并为共享相同配置的测试重用上下文,而 `@MockBean` 或 `@SpyBean` 的使用会影响缓存键,这很可能会增加上下文数量.

TIP: 如果您使用 `@SpyBean` 通过 `@Cacheable` 方法监视通过名称引用参数的 bean,则必须使用 `-parameters` 编译应用程序.  这样可以确保一旦侦察到 bean,参数名称就可用于缓存基础结构.

TIP: 当您使用 `@SpyBean` 监视由 Spring 代理的 bean 时,在某些情况下,例如使用 `given` 或 `when` 设置期望值时,您可能需要删除 Spring 的代理. 使用 `AopTestUtils.getTargetObject(yourProxiedSpy)`

[[features.testing.spring-boot-applications.autoconfigured-tests]]
==== 自动配置测试
Spring Boot 的自动配置适用于应用程序,但有时对测试来说可能有点过多. 它通常仅有助于加载测试应用程序 "切片" 所需的配置部分.  例如,您可能想要在测试运行时测试 Spring MVC 控制器是否正确映射了 URL,并且您不想在这些测试中涉及数据库调用,或者您想要测试 JPA 实体.

`spring-boot-test-autoconfigure` 模块包括许多注解,可用于自动配置此类 "切片".  它们中的每一个都以相似的方式工作,提供了一个  `@...Test` 注解 (该注解加载了 `ApplicationContext`) 以及一个或多个  `@AutoConfigure...`  (可用于自定义自动配置设置的注解) .

NOTE: 每个 "`slicing`" 将组件扫描限制为适当的组件,并加载一组非常受限制的自动配置类.  如果您需要排除其中之一,大多数  `@...Test` 注解提供了 `excludeAutoConfiguration` 属性.  或者,您可以使用 `@ImportAutoConfiguration#exclude`.

NOTE: 不支持在一个测试中使用多个 `@...Test` 注解来包含多个 "片段".  如果您需要多个 "`slices`",请选择  `@...Test` 注解之一,并手动添加其他  "`slices`" 的 `@AutoConfigure...` 注解.

TIP: 也可以将 `@AutoConfigure...` 注解与标准的 `@SpringBootTest` 注解一起使用.  如果您对 "`slicing`" 应用程序不感兴趣,但需要一些自动配置的测试 bean,则可以使用此组合.

[[features.testing.spring-boot-applications.json-tests]]
==== 自动配置的 JSON 测试
要测试对象 JSON 序列化和反序列化是否按预期工作,可以使用 `@JsonTest` 注解.  `@JsonTest` 自动配置可用的受支持的 JSON 映射器,该映射器可以是以下库之一:

* Jackson `ObjectMapper`, 任何使用 `@JsonComponent` 的 beans 和 任何 Jackson ``Module``
* `Gson`
* `Jsonb`

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录>>中找到由 `@JsonTest` 启用的自动配置列表.

如果需要配置自动配置的元素,则可以使用 `@AutoConfigureJsonTesters` 注解.

Spring Boot 包含基于 AssertJ 的帮助程序,这些帮助程序可与 JSONAssert 和 JsonPath 库一起使用,以检查 JSON 是否按预期方式显示.
`JacksonTester`, `GsonTester`, `JsonbTester` 和 `BasicJsonTester` 类可以分别用于 Jackson, Gson, Jsonb 和 Strings.  使用 `@JsonTest` 时,可以使用 `@Autowired` 测试类上的任何帮助程序字段.  以下示例显示了 Jackson 的测试类:

include::code:MyJsonTests[]

NOTE: JSON 帮助程序类也可以直接在标准单元测试中使用.  为此,如果不使用 `@JsonTest`,请在 `@Before` 方法中调用帮助程序的 `initFields` 方法.

如果您使用的是 Spring Boot 基于 AssertJ 的帮助器,以给定的 JSON 路径对数字值进行断言,则取决于类型,您可能无法使用 `isEqualTo`.  相反,您可以使用 AssertJ 的满足条件来断言该值符合给定条件.  例如,以下示例断言实际数是一个偏移量为 `0.01` 且接近 `0.15` 的浮点值.

include::code:MyJsonAssertJTests[tag=*]

[[features.testing.spring-boot-applications.spring-mvc-tests]]
==== 自动配置的 Spring MVC 测试
要测试 Spring MVC 控制器是否按预期工作,请使用 `@WebMvcTest` 注解.  `@WebMvcTest` 自动配置 Spring MVC 基础结构,并将扫描的 bean 限制为 `@Controller`, `@ControllerAdvice`, `@JsonComponent`, `Converter`, `GenericConverter`, `Filter`, `HandlerInterceptor`, `WebMvcConfigurer`,  `WebMvcRegistrations` 和 `HandlerMethodArgumentResolver`.  使用此注解时,不扫描常规 `@Component` ,`@ConfigurationProperties` bean. `@EnableConfigurationProperties` 可用于包含 `@ConfigurationProperties` 的 bean

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>>找到 `@WebMvcTest` 启用的自动配置设置的列表.

TIP: 如果需要注册其他组件,例如 Jackson `Module`,则可以在测试中使用 `@Import` 导入其他配置类.

`@WebMvcTest` 通常仅限于单个控制器,并与 `@MockBean` 结合使用,以为所需的协作者提供模拟实现.

`@WebMvcTest` 还可以自动配置 `MockMvc`.  Mock MVC 提供了一种强大的方法来快速测试 MVC 控制器,而无需启动完整的 HTTP 服务器.

TIP: 您还可以通过在非 `@WebMvcTest` (例如 `@SpringBootTest`) 中使用 `@AutoConfigureMockMvc` 对其进行注解来自动配置 `MockMvc`.  以下示例使用 `MockMvc`:

include::code:MyControllerTests[]

TIP: 如果您需要配置自动配置的元素 (例如,当应该应用 servlet 过滤器时) ,则可以使用 `@AutoConfigureMockMvc` 注解中的属性.

如果使用 HtmlUnit 或 Selenium,则自动配置还会提供 HtmlUnit `WebClient` bean 和/或 Selenium `WebDriver` bean.  以下示例使用 HtmlUnit:

include::code:MyHtmlUnitTests[]

NOTE: 默认情况下,Spring Boot 将 `WebDriver` bean 放在特殊的 "`scope`" 中,以确保驱动程序在每次测试后退出并注入新实例.  如果您不希望出现这种情况,则可以将 `@Scope("singleton")` 添加到 `WebDriver` `@Bean` 定义中.

WARNING: Spring Boot 创建的 `webDriver` 作用域将替换任何用户定义的同名作用域.  如果定义自己的 `webDriver` 作用域,则使用 `@WebMvcTest` 时可能会发现它停止工作.

如果您在类路径上具有 Spring Security,则 `@WebMvcTest` 还将扫描 `WebSecurityConfigurer` Bean.  您可以使用 Spring Security 的测试支持来代替完全禁用此类测试的安全性.  有关如何使用 Spring Security 的 `MockMvc` 支持的更多详细信息,请参见  _<<howto#howto.testing.with-spring-security>>_ 操作方法部分.

TIP: 有时编写 Spring MVC 测试是不够的.  Spring Boot 可以帮助您在 <<features#features.testing.spring-boot-applications.with-running-server, 实际服务器上运行完整的端到端测试>>.

[[features.testing.spring-boot-applications.spring-webflux-tests]]
==== 自动配置的 Spring WebFlux 测试
要测试 {spring-framework-docs}/web-reactive.html[Spring WebFlux] 控制器是否按预期工作,可以使用 `@WebFluxTest` 注解.  `@WebFluxTest` 自动配置 Spring WebFlux 基础结构,
并将扫描的 bean 限制为 `@Controller`, `@ControllerAdvice`, `@JsonComponent`, `Converter`, `GenericConverter`, `WebFilter` 和 `WebFluxConfigurer`.  使用 `@WebFluxTest` 注解时,不扫描常规 `@Component` 和 `@ConfigurationProperties` bean.`@EnableConfigurationProperties` 可用于包含 `@ConfigurationProperties` 的 bean

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>>找到 `@WebFluxTest` 启用的自动配置的列表.  .

TIP: 如果需要注册其他组件,例如 Jackson `Module`,则可以在测试中使用 `@Import` 导入其他配置类.

通常,`@WebFluxTest` 仅限于单个控制器,并与 `@MockBean` 注解结合使用,以为所需的协作者提供模拟实现.

`@WebFluxTest` 还可以自动配置  {spring-framework-docs}/testing.html#webtestclient[`WebTestClient`],它提供了一种强大的方法来快速测试 WebFlux 控制器,而无需启动完整的 HTTP 服务器.

TIP: 您还可以通过在非 `@WebFluxTest` (例如 `@SpringBootTest`) 中自动配置 `WebTestClient`,方法是使用 `@AutoConfigureWebTestClient` 对其进行注解.  下面的示例显示一个同时使用 `@WebFluxTest` 和 `WebTestClient` 的类:

include::code:MyControllerTests[]

TIP: WebFlux 应用程序仅支持此设置,因为在模拟的 Web 应用程序中使用 `WebTestClient` 目前仅与 WebFlux 一起使用.

NOTE: `@WebFluxTest` 无法检测通过功能 Web 框架注册的路由.  为了在上下文中测试 `RouterFunction` bean,请考虑自己通过 `@Import` 或使用 `@SpringBootTest` 导入 `RouterFunction`.

NOTE: `@WebFluxTest` 无法检测通过 `SecurityWebFilterChain` 类型的 `@Bean` 注册的自定义安全配置.  要将其包括在测试中,您将需要通过 `@Import` 导入或使用 `@SpringBootTest` 导入用于注册 bean 的配置.

TIP: 有时编写 Spring WebFlux 测试是不够的.  Spring Boot可以帮助您在 <<features#features.testing.spring-boot-applications.with-running-server, 实际服务器上运行完整的端到端测试>>.

[[features.testing.spring-boot-applications.spring-graphql-tests]]
==== Spring GraphQL 测试自动配置
Spring GraphQL 提供了专门的测试支持模块； 你需要将它添加到你的项目中：

.Maven
[source,xml,indent=0,subs="verbatim"]
----
  <dependencies>
    <dependency>
      <groupId>org.springframework.graphql</groupId>
      <artifactId>spring-graphql-test</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- Unless already present in the compile scope -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
----

.Gradle
[source,gradle,indent=0,subs="verbatim"]
----
  dependencies {
    testImplementation("org.springframework.graphql:spring-graphql-test")
    // Unless already present in the implementation configuration
    testImplementation("org.springframework.boot:spring-boot-starter-webflux")
  }
----

这个测试模块附带了 {spring-graphql-docs}/#testing-graphqltester[GraphQlTester].
spring-boot-project/spring-boot-docs/src/docs/asciidoc/features/testing.adoc

[[features.testing.spring-boot-applications.autoconfigured-spring-data-cassandra]]
==== 自动配置 Cassandra 测试
您可以使用 `@DataCassandraTest` 注解来测试 Cassandra 应用程序.  默认情况下,它将配置一个 `CassandraTemplate` 来扫描 `@Table` 类并配置 Spring Data Cassandra 存储库.
使用 `@DataCassandraTest` 注解时,不扫描常规 `@Component` 和 `@ConfigurationProperties` bean.`@EnableConfigurationProperties` 可用于包含 `@ConfigurationProperties` 的 bean（有关在 Spring Boot 中使用 Cassandra 的更多信息，请参阅本章前面的 "<<data#data.nosql.cassandra>>"）

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>> 找到由 `@DataCassandraTest` 启用的自动配置设置的列表.

以下示例显示了在 Spring Boot 中使用 Cassandra 测试的典型设置:

include::code:MyDataCassandraTests[]

[[features.testing.spring-boot-applications.autoconfigured-spring-data-couchbase]]
==== 自动配置 Data Couchbase 测试
您可以使用 `@DataCouchbaseTest` 注解来测试 Couchbase 应用程序.
默认情况下,它将配置一个 `CouchbaseTemplate` 或 `ReactiveCouchbaseTemplate`, 来扫描 `@Document` 类并配置 Spring Data Couchbase 存储库.
使用 `@DataCouchbaseTest` 注解时,不扫描常规 `@Component` 和 `@ConfigurationProperties` bean.`@EnableConfigurationProperties` 可用于包含 `@ConfigurationProperties` 的 bean（有关在 Spring Boot 中使用 Cassandra 的更多信息，请参阅本章前面的 "<<data#data.nosql.couchbase>>"）

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>> 找到由 `@DataCouchbaseTest` 启用的自动配置设置的列表.

以下示例显示了在 Spring Boot 中使用 Couchbase 测试的典型设置:

include::code:MyDataCouchbaseTests[]

[[features.testing.spring-boot-applications.autoconfigured-spring-data-elasticsearch]]
==== 自动配置 Data Elasticsearch 测试
您可以使用 `@DataElasticsearchTest` 注解来测试 Elasticsearch 应用程序.
默认情况下,它将配置一个 `ElasticsearchRestTemplate`, 来扫描 `@Document` 类并配置 Spring Data Elasticsearch 存储库.
使用 `@DataElasticsearchTest` 注解时,不扫描常规 `@Component` 和 `@ConfigurationProperties` bean.`@EnableConfigurationProperties` 可用于包含 `@ConfigurationProperties` 的 bean（有关在 Spring Boot 中使用 Elasticsearch 的更多信息，请参阅本章前面的 "<<data#data.nosql.elasticsearch>>"）

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>> 找到由 `@DataElasticsearchTest` 启用的自动配置设置的列表.

以下示例显示了在 Spring Boot 中使用 Elasticsearch 测试的典型设置:

include::code:MyDataElasticsearchTests[]

[[features.testing.spring-boot-applications.autoconfigured-spring-data-jpa]]
==== 自动配置的 Data JPA 测试
您可以使用 `@DataJpaTest` 注解来测试 JPA 应用程序.  默认情况下,它将扫描 `@Entity` 类并配置 Spring Data JPA 存储库.  如果在类路径上有嵌入式数据库,也会配置.
默认情况下， 通过将 `spring.jpa.show-sql` 属性设置为 `true` 来记录 SQL 查询.
可以使用注解的 `showSql()` 属性禁用此功能.

使用 `@DataJpaTest` 注解时,不扫描常规 `@Component` 和 `@ConfigurationProperties` bean.`@EnableConfigurationProperties` 可用于包含 `@ConfigurationProperties` 的 bean

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>>找到由 `@DataJpaTest` 启用的自动配置设置的列表.

默认情况下,数据 JPA 测试是事务性的,并在每次测试结束时回滚.  有关更多详细信息,请参见《Spring Framework 参考文档》中的 {spring-framework-docs}/testing.html#testcontext-tx-enabling-transactions[相关部分] .  如果这不是您想要的,则可以按以下方式禁用测试或整个类的事务管理:

include::code:MyNonTransactionalTests[]

JPA 测试也可以注入 {spring-boot-test-autoconfigure-module-code}/orm/jpa/TestEntityManager.java[`TestEntityManager`] bean,它为专门为测试设计的标准 JPA `EntityManager` 提供了替代方法.

TIP:  `TestEntityManager` 也可以通过添加 `@AutoConfigureTestEntityManager` 自动配置到任何基于 Spring 的测试类。 这样做时，请确保您的测试在事务中运行，例如通过在测试类或方法上添加 `@Transactional`。

如果需要,还可以使用 `JdbcTemplate`.  以下示例显示了正在使用的 `@DataJpaTest` 注解:

include::code:withoutdb/MyRepositoryTests[]

内存嵌入式数据库通常运行良好,不需要任何安装,因此通常可以很好地进行测试.  但是,如果您希望对真实数据库运行测试,则可以使用 `@AutoConfigureTestDatabase` 注解,如以下示例所示:

include::code:withdb/MyRepositoryTests[]

[[features.testing.spring-boot-applications.autoconfigured-jdbc]]
==== 自动配置的 JDBC 测试
`@JdbcTest` 与 `@DataJpaTest` 相似,但适用于仅需要 `DataSource` 并且不使用 Spring Data JDBC 的测试.  默认情况下,它配置一个内存嵌入式数据库和一个 `JdbcTemplate`. 使用 `@JdbcTest` 注解时,不扫描常规 `@Component` 和 `@ConfigurationProperties` bean.`@EnableConfigurationProperties` 可用于包含 `@ConfigurationProperties` 的 bean

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>> 找到 `@JdbcTest` 启用的自动配置的列表.

默认情况下,JDBC 测试是事务性的,并在每个测试结束时回滚.  有关更多详细信息,请参见《 Spring Framework 参考文档》中的 {spring-framework-docs}/testing.html#testcontext-tx-enabling-transactions[相关部分].  如果这不是您想要的,则可以为测试或整个类禁用事务管理,如下所示:

include::code:MyTransactionalTests[]

如果您希望测试针对真实数据库运行,则可以使用 `@AutoConfigureTestDatabase` 注解,其方式与 `DataJpaTest` 相同.   (请参阅 "<<features#features.testing.spring-boot-applications.autoconfigured-spring-data-jpa>>". )。

[[features.testing.spring-boot-applications.autoconfigured-spring-data-jdbc]]
==== 自动配置的 Data JDBC 测试
`@DataJdbcTest` 与 `@JdbcTest` 相似,但适用于使用 Spring Data JDBC 存储库的测试.  默认情况下,它配置一个内存嵌入式数据库,一个 `JdbcTemplate` 和 Spring Data JDBC 存储库.
使用 `@DataJdbcTest` 注释时仅扫描 `AbstractJdbcConfiguration` 子类，不扫描常规 `@Component` 和 `@ConfigurationProperties` bean。 `@EnableConfigurationProperties` 可用于包含 `@ConfigurationProperties` 的 bean

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>>找到由 `@DataJdbcTest` 启用的自动配置的列表.

默认情况下,Data JDBC 测试是事务性的,并在每个测试结束时回滚.  有关更多详细信息,请参见《Spring Framework 参考文档》中的 {spring-framework-docs}/testing.html#testcontext-tx-enabling-transactions[相关部分].  如果这不是您想要的,则可以禁用测试或整个测试类的事务管理,<<features#features.testing.spring-boot-applications.autoconfigured-jdbc,如 JDBC 示例所示>>.

如果您希望测试针对真实数据库运行,则可以使用 `@AutoConfigureTestDatabase` 注解,其方式与 `DataJpaTest` 相同.   (请参阅 "<<features#features.testing.spring-boot-applications.autoconfigured-spring-data-jpa>>". )。

[[features.testing.spring-boot-applications.autoconfigured-jooq]]
==== 自动配置的 jOOQ Tests
您可以以与 `@JdbcTest` 类似的方式使用 `@JooqTest`,但可以用于与 jOOQ 相关的测试. 由于 jOOQ 严重依赖与数据库模式相对应的基于 Java 的模式,因此将使用现有的 `DataSource`.
如果要将其替换为内存数据库,则可以使用 `@AutoConfigureTestDatabase` 覆盖这些设置.   (有关在 Spring Boot 中使用 jOOQ 的更多信息,请参阅  "<<data#data.sql.jooq>>". ) 使用 `@JooqTest` 注解时,不扫描常规 `@Component` 和 `@ConfigurationProperties` bean.`@EnableConfigurationProperties` 可用于包含 `@ConfigurationProperties` 的 bean

TIP: 可以在  <<test-auto-configuration#appendix.test-auto-configuration,附录中>> 找到 `@JooqTest` 启用的自动配置的列表.

`@JooqTest` 配置 `DSLContext`. .  以下示例显示了正在使用的 `@JooqTest` 注解:

include::code:MyJooqTests[]

JOOQ 测试是事务性的,默认情况下会在每个测试结束时回滚.  如果这不是您想要的,则可以禁用测试或整个测试类的事务管理, <<features#features.testing.spring-boot-applications.autoconfigured-jdbc,如 JDBC 示例所示>>.

[[features.testing.spring-boot-applications.autoconfigured-spring-data-mongodb]]
==== 自动配置的 Data MongoDB 测试
您可以使用 `@DataMongoTest` 测试 MongoDB 应用程序.  默认情况下,它配置内存嵌入式 MongoDB (如果可用) ,配置 `MongoTemplate`,扫描 `@Document` 类,并配置 Spring Data MongoDB 存储库.  使用 `@DataMongoTest` 注解时,不扫描常规 `@Component` 和 `@ConfigurationProperties` bean.`@EnableConfigurationProperties` 可用于包含 `@ConfigurationProperties` 的 bean
(有关将 MongoDB 与 Spring Boot 结合使用的更多信息,请参阅 "<<data#data.nosql.mongodb>>")

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>>找到由 `@DataMongoTest` 启用的自动配置设置的列表.

此类显示正在使用的 `@DataMongoTest` 注解:

include::code:MyDataMongoDbTests[]

[[features.testing.spring-boot-applications.autoconfigured-spring-data-neo4j]]
==== Auto-configured Data Neo4j Tests
您可以使用 `@DataNeo4jTest` 来测试 Neo4j 应用程序.  默认情况下, 他会扫描 `@Node` 类,并配置 Spring Data Neo4j 存储库.
使用 `@DataNeo4jTest` 注解时,不扫描常规 `@Component` 和 `@ConfigurationProperties` bean.`@EnableConfigurationProperties` 可用于包含 `@ConfigurationProperties` 的 bean.   (有关将 Neo4J 与 Spring Boot 结合使用的更多信息,请参阅  "<<data#data.nosql.neo4j>>". )

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>>找到由 `@DataNeo4jTest` 启用的自动配置设置的列表.

以下示例显示了在 Spring Boot 中使用 Neo4J 测试的典型设置:

include::code:propagation/MyDataNeo4jTests[]

默认情况下,Data Neo4j 测试是事务性的,并在每次测试结束时回滚.  有关更多详细信息,请参见《Spring Framework 参考文档》中的  {spring-framework-docs}/testing.html#testcontext-tx-enabling-transactions[相关部分] .  如果这不是您想要的,则可以为测试或整个类禁用事务管理,如下所示:

include::code:nopropagation/MyDataNeo4jTests[]

NOTE: 响应式访问不支持事务性测试。如果您正在使用这种样式，您必须如上所述配置 `@DataNeo4jTest` 测试.

[[features.testing.spring-boot-applications.autoconfigured-spring-data-redis]]
==== 自动配置的 Data Redis 测试
您可以使用 `@DataRedisTest` 测试 Redis 应用程序.  默认情况下,它会扫描 `@RedisHash` 类并配置 Spring Data Redis 存储库.  使用 `@DataRedisTest` 注解时,不扫描常规 `@Component` 和 `@ConfigurationProperties` bean.`@EnableConfigurationProperties` 可用于包含 `@ConfigurationProperties` 的 bean.  (有关将 Redis 与 Spring Boot 结合使用的更多信息,请参阅 "<<data#data.nosql.redis>>". )

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>>找到由 `@DataRedisTest` 启用的自动配置设置的列表.


下面的例子展示了使用中的 `@DataRedisTest` 注解:

include::code:MyDataRedisTests[]

[[features.testing.spring-boot-applications.autoconfigured-spring-data-ldap]]
==== 自动配置的 Data LDAP 测试
您可以使用 `@DataLdapTest` 来测试 LDAP 应用程序.  默认情况下,它配置内存嵌入式 LDAP (如果可用) ,配置 `LdapTemplate`,扫描 `@Entry` 类,并配置 Spring Data LDAP 存储库.
使用 `@DataLdapTest` 注解时,不扫描常规 `@Component` 和 `@ConfigurationProperties` bean.`@EnableConfigurationProperties` 可用于包含 `@ConfigurationProperties` 的 bean.   (有关将 LDAP 与 Spring Boot 结合使用的更多信息,请参阅 "<<data#data.nosql.ldap>>". )

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>>找到由 `@DataLdapTest` 启用的自动配置设置的列表.

以下示例显示了正在使用的 `@DataLdapTest` 注解:

include::code:inmemory/MyDataLdapTests[]

内存嵌入式 LDAP 通常非常适合测试,因为它速度快并且不需要安装任何开发人员.  但是,如果您希望针对真实的 LDAP 服务器运行测试,则应排除嵌入式 LDAP 自动配置,如以下示例所示:

include::code:server/MyDataLdapTests[]

[[features.testing.spring-boot-applications.autoconfigured-rest-client]]
==== 自动配置 REST Clients
您可以使用 `@RestClientTest` 注解来测试 REST 客户端.  默认情况下,它会自动配置 Jackson,GSON 和 Jsonb 支持,配置 `RestTemplateBuilder`,并添加对 `MockRestServiceServer` 的支持.  使用 `@RestClientTest` 注解时,不扫描常规 `@Component` 和 `@ConfigurationProperties` bean.`@EnableConfigurationProperties` 可用于包含 `@ConfigurationProperties` 的 bean.

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>>找到由 `@RestClientTest` 启用的自动配置设置的列表.

应该使用 `@RestClientTest` 的 `value` 或 `components` 属性来指定要测试的特定 bean,如以下示例所示:

include::code:MyRestClientTests[]

[[features.testing.spring-boot-applications.autoconfigured-spring-restdocs]]
==== 自动配置的 Spring REST Docs 测试
您可以使用 `@AutoConfigureRestDocs` 注解在 Mock MVC,REST Assured 或 `WebTestClient` 的测试中使用 {spring-restdocs}[Spring REST Docs].  它消除了 Spring REST Docs 中对 JUnit 扩展的需求.

`@AutoConfigureRestDocs` 可用于覆盖默认输出目录 (如果使用 Maven,则为 `target/generated-snippets` 如果使用 Gradle,则为 `build/generated-snippets` ) .  它也可以用于配置出现在任何记录的 URI 中的 host, scheme, 和 port.

[[features.testing.spring-boot-applications.autoconfigured-spring-restdocs.with-mock-mvc]]
===== 使用 Mock MVC 自动配置的 Spring REST Docs 测试
`@AutoConfigureRestDocs` 自定义 `MockMvc` bean 以使用 Spring REST Docs.  您可以使用 `@Autowired` 注入它,并像通常使用 Mock MVC 和 Spring REST Docs 一样,在测试中使用它,如以下示例所示:

include::code:MyUserDocumentationTests[]

如果需要对 Spring REST Docs 配置进行更多控制,而不是 `@AutoConfigureRestDocs` 属性提供的控制,则可以使用 `RestDocsMockMvcConfigurationCustomizer` bean,如以下示例所示:

include::code:MyRestDocsConfiguration[]

如果要使用 Spring REST Docs 对参数化输出目录的支持,可以创建 `RestDocumentationResultHandler` bean.  自动配置使用此结果处理程序调用 `alwaysDo`,从而使每个 `MockMvc` 调用自动生成默认片段.  以下示例显示了定义的 `RestDocumentationResultHandler`:

include::code:MyResultHandlerConfiguration[]

[[features.testing.spring-boot-applications.autoconfigured-spring-restdocs.with-web-test-client]]
===== 使用 WebTestClient 自动配置的 Spring REST Docs 测试
`@AutoConfigureRestDocs` 也可以与 `WebTestClient` 一起使用.  您可以使用 `@Autowired` 注入它,并像通常使用 `@WebFluxTest` 和 Spring REST Docs 一样在测试中使用它,如以下示例所示:

include::code:MyUsersDocumentationTests[]

如果需要对 Spring REST Docs 配置进行更多控制,而不是 `@AutoConfigureRestDocs` 属性提供的控制,则可以使用 `RestDocsWebTestClientConfigurationCustomizer` bean,如以下示例所示:

include::code:MyRestDocsConfiguration[]

如果您想利用 Spring REST Docs 对参数化输出目录的支持，您可以使用 `WebTestClientBuilderCustomizer` 为每个实体 exchange 结果配置消费者。 下面的例子展示了一个被定义的 `WebTestClientBuilderCustomizer`:

include::code:MyWebTestClientBuilderCustomizerConfiguration[]

[[features.testing.spring-boot-applications.autoconfigured-spring-restdocs.with-rest-assured]]
===== 使用 RES TAssured 自动配置的 Spring REST Docs 测试
`@AutoConfigureRestDocs` 使一个 `RequestSpecification` Bean (可预配置为使用 Spring REST Docs) 可用于您的测试.  您可以使用 `@Autowired` 注入它,并像在使用 REST Assured 和 Spring REST Docs 时一样,在测试中使用它,如以下示例所示:

include::code:MyUserDocumentationTests[]

如果您需要对 Spring REST Docs 配置进行更多控制,而不是 `@AutoConfigureRestDocs` 属性所提供的控制,则可以使用 `RestDocsRestAssuredConfigurationCustomizer` bean,如以下示例所示:

include::code:MyRestDocsConfiguration[]

[[features.testing.spring-boot-applications.autoconfigured-webservices]]
==== Auto-configured Spring Web Services Tests


[[features.testing.spring-boot-applications.autoconfigured-webservices.client]]
===== 自动配置的 Spring Web Services Client 测试
您可以使用 `@WebServiceClientTest` 来通过 Spring Web Services 项目测试使用呼叫 Web 服务的应用程序. 默认情况下,它配置模拟 `WebServiceServer` bean 并自动自定义 `WebServiceTemplateBuilder`.  (有关在 Spring Boot 中结合使用 Web 服务的更多信息,请参阅 "<<io#io.webservices>>".)

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>> 找到由 `@WebServiceClientTest` 启用的自动配置设置的列表.

以下示例显示了正在使用的 `@WebServiceClientTest` 注解:

include::code:MyWebServiceClientTests[]

[[features.testing.spring-boot-applications.autoconfigured-webservices.server]]
===== 自动配置的 Spring Web Services Server 测试

您可以使用 `@WebServiceServerTest` 来测试使用 Spring Web Services 项目实现 Web 服务的应用程序。 默认情况下，它配置了一个 `MockWebServiceClient` bean，可用于调用您的 Web 服务端点。
（有关在 Spring Boot 中使用 Web 服务的更多信息，请参阅 "<<io#io.webservices>>"。）

TIP: 可以在 <<test-auto-configuration#appendix.test-auto-configuration,附录中>> 找到由 `@WebServiceServerTest` 启用的自动配置设置的列表.

以下示例显示了正在使用的 `@WebServiceServerTest` 注解:

include::code:MyWebServiceServerTests[]

[[features.testing.spring-boot-applications.additional-autoconfiguration-and-slicing]]
==== 其他的自动配置和切片
每个切片提供一个或多个 `@AutoConfigure...` 注解,即定义应包含在切片中的自动配置.  可以通过创建自定义 `@AutoConfigure...` 注解来添加其他自动配置,也可以简单地通过将 `@ImportAutoConfiguration` 添加到测试中来添加其他自动配置,如以下示例所示:

include::code:MyJdbcTests[]

NOTE: 确保不要使用常规的 `@Import` 注解导入自动配置,因为它们是由 Spring Boot 以特定方式处理的.

或者,可以通过在 `META-INF/spring.factories` 中注册切片注解的任何使用来添加其他自动配置,如以下示例所示:

.META-INF/spring/org.springframework.boot.test.autoconfigure.jdbc.JdbcTest.imports
[indent=0]
----
	com.example.IntegrationAutoConfiguration
----

在此示例中，在每个用 `@JdbcTest` 注解的测试上启用了 `com.example.IntegrationAutoConfiguration`。

TIP: 您可以在此文件中通过 `#` 使用注释。

TIP: 切片或 `@AutoConfigure...` 注解可以通过这种方式自定义,只要使用 `@ImportAutoConfiguration` 对其进行元注解即可.

[[features.testing.spring-boot-applications.user-configuration-and-slicing]]
==== 用户配置和切片
如果您以合理的方式 <<using#using.structuring-your-code, 组织代码>> ,则 <<features#features.testing.spring-boot-applications.detecting-configuration,默认情况下>> 将 `@SpringBootApplication` 类用作测试的配置.

因此,变得重要的是,不要使用特定于其功能特定区域的配置设置来乱扔应用程序的主类.

假设您正在使用 Spring Batch,并且依赖于它的自动配置.  您可以如下定义 `@SpringBootApplication`:

include::code:MyApplication[]

因为此类是测试的源配置,所以任何切片测试实际上都尝试启动 Spring Batch,这绝对不是您想要执行的操作.  建议的方法是将特定于区域的配置移动到与您的应用程序处于同一级别的单独的 `@Configuration` 类,如以下示例所示:

include::code:MyBatchConfiguration[]

NOTE: 根据您应用程序的复杂性,您可以为您的自定义设置一个 `@Configuration` 类,或者每个域区域一个类.  后一种方法使您可以在其中一个测试中使用 `@Import` 注解启用它.请参阅 <<howto#howto.testing.slice-tests,this how-to section>> 了解有关何时可能需要为切片测试启用特定 `@Configuration` 类的更多详细信息。

测试片将 `@Configuration` 类从扫描中排除.  例如,对于 `@WebMvcTest`,以下配置将在测试切片加载的应用程序上下文中不包括给定的 `WebMvcConfigurer` Bean:

include::code:MyWebConfiguration[]

但是,以下配置将导致自定义 `WebMvcConfigurer` 由测试片加载.

include::code:MyWebMvcConfigurer[]

混乱的另一个来源是类路径扫描.  假定在以合理的方式组织代码的同时,您需要扫描其他程序包.  您的应用程序可能类似于以下代码:

include::code:scan/MyApplication[]

这样做有效地覆盖了默认的组件扫描指令,并且具有扫描这两个软件包的副作用,而与您选择的切片无关.  例如,`@DataJpaTest` 似乎突然扫描了应用程序的组件和用户配置.  同样,将自定义指令移至单独的类是解决此问题的好方法.

TIP: 如果这不是您的选择,则可以在测试层次结构中的某个位置创建 `@SpringBootConfiguration`,以便代替使用它.  或者,您可以为测试指定一个源,从而禁用查找默认源的行为.

[[features.testing.spring-boot-applications.spock]]
==== 使用 Spock 测试 Spring Boot 应用程序
如果您希望使用 Spock 2.x 来测试 Spring Boot 应用程序,则应在应用程序的构建中添加对 Spock 的 `spock-spring` 模块的 `-groovy-4.0` 版本依赖.  `spock-spring` 将 Spring 的测试框架集成到了 Spock 中.
有关更多详细信息,请参见 https://spockframework.org/spock/docs/2.2-M1/modules.html#_spring_module[Spock 的 Spring 模块的文档]..

[[features.testing.utilities]]
=== 测试实用工具
一些测试实用工具类通常在测试您的应用程序时有用,它们被打包为 `spring-boot` 的一部分.

[[features.testing.utilities.config-data-application-context-initializer]]
==== ConfigDataApplicationContextInitializer
`ConfigFileApplicationContextInitializer` 是一个 `ApplicationContextInitializer`,您可以将其应用于测试以加载 Spring Boot `application.properties` 文件.  当不需要 `@SpringBootTest` 提供的全部功能时,可以使用它,如以下示例所示:

include::code:MyConfigFileTests[]

NOTE: 单独使用 `ConfigFileApplicationContextInitializer` 不能提供对 `@Value("${...}")` 注入的支持.  唯一的工作就是确保将 `application.properties` 文件加载到 Spring 的环境中.  为了获得 `@Value` 支持,您需要另外配置 `PropertySourcesPlaceholderConfigurer` 或使用 `@SpringBootTest`,后者会为您自动配置一个.

[[features.testing.utilities.test-property-values]]
==== TestPropertyValues
使用 `TestPropertyValues`,可以快速将属性添加到 `ConfigurableEnvironment` 或 `ConfigurableApplicationContext`.  您可以使用 `key=value` 字符串来调用它,如下所示:

include::code:MyEnvironmentTests[]

[[features.testing.utilities.output-capture]]
==== OutputCapture
`OutputCapture` 是一个 JUnit 扩展,可用于捕获 `System.out` 和 `System.err` 输出.  要使用 add `@ExtendWith(OutputCaptureExtension.class)` 并将 `CapturedOutput` 作为参数注入测试类构造函数或测试方法,如下所示:

include::code:MyOutputCaptureTests[]

[[features.testing.utilities.test-rest-template]]
==== TestRestTemplate
`TestRestTemplate` 是Spring `RestTemplate` 的一种便捷替代方案,在集成测试中非常有用.  您可以使用普通模板或发送基本 HTTP 身份验证 (带有用户名和密码) 的模板. 在任何一种情况下, 模版都具有容错性，这意味着它以一种测试友好的方式运行，不会在 4xx 和 5xx 错误上抛出异常。相反，可以通过返回的 `ResponseEntity` 及其状态码检测此类错误。

TIP: Spring Framework 5.0 提供了一个新的 `WebTestClient`,可用于  <<features#features.testing.spring-boot-applications.spring-webflux-tests, WebFlux 集成测试>> 和 <<features#features.testing.spring-boot-applications.with-running-server, WebFlux 和 MVC 端到端测试>>.  与 `TestRestTemplate` 不同,它为声明提供了流式的 API.

建议 (但不是强制性的) 使用 Apache HTTP Client (版本 4.3.2 或更高版本) . 如果您在类路径中具有该名称,则 `TestRestTemplate` 会通过适当配置客户端进行响应.  如果您确实使用 Apache 的 HTTP 客户端,则会启用一些其他易于测试的功能:

* 不支持重定向(因此可以断言响应位置).
* 忽略 cookie(因此模板是无状态的).

`TestRestTemplate` 可以在你的集成测试中直接实例化,如下面的例子所示:

include::code:MyTests[]

或者,如果将 `@SpringBootTest` 注解与 `WebEnvironment.RANDOM_PORT` 或 `WebEnvironment.DEFINED_PORT` 一起使用,则可以注入完全配置的 `TestRestTemplate` 并开始使用它.
如有必要,可以通过 `RestTemplateBuilder` bean 应用其他定制.  未指定主机和端口的所有 URL 都会自动连接到嵌入式服务器,如以下示例所示:

include::code:MySpringBootTests[]
