= 核心配置

[[servlet-oauth2login-sample-boot]]
== Spring Boot 2.x 示例

Spring Boot 2.x 为 OAuth 2.0 登录带来了完整的自动配置功能.

本部分显示了如何使用 Google 作为身份验证提供程序来配置 {gh-samples-url}/boot/oauth2login[*OAuth 2.0 Login sample*],并涵盖以下主题:

* <<servlet-oauth2login-sample-initial-setup>>
* <<servlet-oauth2login-sample-redirect-uri>>
* <<servlet-oauth2login-sample-application-config>>
* <<servlet-oauth2login-sample-boot-application>>

[[servlet-oauth2login-sample-initial-setup]]
=== 初始设置

要使用 Google 的 OAuth 2.0 身份验证系统登录,您必须在 Google API 控制台中设置一个项目以获得 OAuth 2.0 凭据.

[NOTE]
====
https://developers.google.com/identity/protocols/OpenIDConnect[Google's OAuth 2.0 实现] 符合 https://openid.net/connect/[OpenID Connect 1.0] 规范,并且已通过 https://openid.net/certification/[OpenID Certified].
====

请按照设置 https://developers.google.com/identity/protocols/OpenIDConnect[OpenID Connect]  (需要翻墙才能访问,链接打开是 Google 的开发者平台控制台) 部分开始的 OpenID Connect 页面上的说明进行操作.

完成 "获取 OAuth 2.0 凭据" 说明后,您应该拥有一个新的 OAuth 客户端,其凭据由 Client ID 和 Client Secret.组成.

[[servlet-oauth2login-sample-redirect-uri]]
=== 设置重定向URI

重定向URI是用户的在通过 Google 身份验证并在授权页面上同意 (_(<<servlet-oauth2login-sample-initial-setup,在上一步中创建>>)_) OAuth 客户端的访问权限后,由 Google 重定向的回调链接地址

在 设置重定向 URI 子章节中,确保将  *Authorized redirect URIs* 字段设置为 `http://localhost:8080/login/oauth2/code/google`.

[TIP]
====
默认重定向 URI 模板为 `+{baseUrl}/login/oauth2/code/{registrationId}+` .  *_registrationId_* 是 <<oauth2Client-client-registration,ClientRegistration>> 的唯一标识符.
====

[IMPORTANT]
====
如果 OAuth 客户端在代理服务器 (例如: Nginx) 后面运行,建议检查<<http-proxy-server, 代理服务器配置>>以确保正确配置了应用程序.  另外,请参阅 `redirect-uri` 支持的<<servlet-oauth2Client-auth-code-redirect-uri, `URI` 模板变量>>.
====

[[servlet-oauth2login-sample-application-config]]
=== 配置 application.yml

现在,您有了 Google 的新 OAuth 客户端,您需要配置应用程序以将 OAuth 客户端用于身份验证流程.  为此:

. 转到 `application.yml` 并设置以下配置:
+
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:	<1>
          google:	<2>
            client-id: google-client-id
            client-secret: google-client-secret
----
+
.OAuth客户端属性
====
<1> `spring.security.oauth2.client.registration` 是 OAuth 客户端属性的基本属性前缀.
<2> 基本属性前缀后面是<<oauth2Client-client-registration,ClientRegistration>>的 ID,例如 google
====

. 将 `client-id` 和 `client-secret` 属性中的值替换为您先前创建的 OAuth 2.0 凭据.

[[servlet-oauth2login-sample-boot-application]]
=== 启动应用程序

启动 Spring Boot 2.x 示例并转到 `http://localhost:8080`.  然后,您将会被重定向到默认自动生成的登录页面,该页面显示 Google 的链接.

单击 Google 链接,然后您将重定向到 Google 进行身份验证.

在使用您的 Google 帐户凭据进行身份验证之后,显示给您的下一页是 *Allow* 页面.   *Allow* 页面要求您允许或拒绝之前创建的 OAuth 客户端的访问权限.  点击 *Allow* 以授权 OAuth 客户端访问您的电子邮件地址和基本个人资料信息.

此时,OAuth 客户端将从 https://openid.net/specs/openid-connect-core-1_0.html#UserInfo[UserInfo Endpoint] 检索您的电子邮件地址和基本个人资料信息,并建立经过身份验证的会话.

[[servlet-oauth2login-boot-property-mappings]]
== Spring Boot 2.x 属性映射

下表概述了 Spring Boot 2.x OAuth 客户端属性到 <<oauth2Client-client-registration,ClientRegistration>> 属性的映射.

|===
|Spring Boot 2.x |ClientRegistration

|`spring.security.oauth2.client.registration._[registrationId]_`
|`registrationId`

|`spring.security.oauth2.client.registration._[registrationId]_.client-id`
|`clientId`

|`spring.security.oauth2.client.registration._[registrationId]_.client-secret`
|`clientSecret`

|`spring.security.oauth2.client.registration._[registrationId]_.client-authentication-method`
|`clientAuthenticationMethod`

|`spring.security.oauth2.client.registration._[registrationId]_.authorization-grant-type`
|`authorizationGrantType`

|`spring.security.oauth2.client.registration._[registrationId]_.redirect-uri`
|`redirectUri`

|`spring.security.oauth2.client.registration._[registrationId]_.scope`
|`scopes`

|`spring.security.oauth2.client.registration._[registrationId]_.client-name`
|`clientName`

|`spring.security.oauth2.client.provider._[providerId]_.authorization-uri`
|`providerDetails.authorizationUri`

|`spring.security.oauth2.client.provider._[providerId]_.token-uri`
|`providerDetails.tokenUri`

|`spring.security.oauth2.client.provider._[providerId]_.jwk-set-uri`
|`providerDetails.jwkSetUri`

|`spring.security.oauth2.client.provider._[providerId]_.issuer-uri`
|`providerDetails.issuerUri`

|`spring.security.oauth2.client.provider._[providerId]_.user-info-uri`
|`providerDetails.userInfoEndpoint.uri`

|`spring.security.oauth2.client.provider._[providerId]_.user-info-authentication-method`
|`providerDetails.userInfoEndpoint.authenticationMethod`


|`spring.security.oauth2.client.provider._[providerId]_.user-name-attribute`
|`providerDetails.userInfoEndpoint.userNameAttributeName`
|===

[TIP]
====
可以通过 OpenID Connect 提供商的 https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Configuration endpoint] 或授权服务器的 https://tools.ietf.org/html/rfc8414#section-3[Metadata endpoint],来初始配置 `ClientRegistration`,指定  `spring.security.oauth2.client.provider._[providerId]_.issuer-uri` 属性
====

[[servlet-oauth2login-common-oauth2-provider]]
== CommonOAuth2Provider

`CommonOAuth2Provider` 为许多著名提供了 Oauth2.0 登录程序的服务商 (Google,GitHub,Facebook 和 Okta) 预定义了一组默认客户端属性.

例如,对于提供者,`authorization-uri`,`token-uri` 和 `user-info-uri` 不会经常更改.  因此,提供默认值以减少所需的配置是有意义的.

如前所述,当我们 <<servlet-oauth2login-sample-application-config,配置Google客户端>>时,仅需要 `client-id` 和 `client-secret` 属性.

以下清单显示了一个示例:

====
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret
----
====

[TIP]
====
客户端属性会自动默认配置,因为 `registrationId` (google) 与 `CommonOAuth2Provider` 中的 `GOOGLE` 枚举 (不区分大小写) 匹配.
====

对于您可能想要指定其他 `registrationId` 的情况 (例如 `google-login`) ,您仍然可以通过配置 `provider` 属性来利用客户端属性的自动默认设置.

以下清单显示了一个示例:

====
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          google-login:	<1>
            provider: google	<2>
            client-id: google-client-id
            client-secret: google-client-secret
----
<1> `registrationId` 设置为 `google-login`.
<2> `provider` 属性设置为 `google`,这将利用 `CommonOAuth2Provider.GOOGLE.getBuilder()` 中设置的客户端属性的自动默认设置.
====

[[servlet-oauth2login-custom-provider-properties]]
== 配置自定义 提供者 属性

有些 OAuth 2.0 提供程序支持多租户,这会导致每个租户 (或子域) 使用不同的 Protocol Endpoints .

例如,向 Okta 注册的 OAuth 客户端被分配给特定的子域,并拥有自己的 Protocol Endpoint.

对于这些情况,Spring Boot 2.x 提供以下用于配置自定义提供程序属性的基本属性:  `spring.security.oauth2.client.provider._[providerId]_`.

以下清单显示了一个示例:

====
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
        provider:
          okta:	<1>
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
----
<1> 基本属性 (`spring.security.oauth2.client.provider.okta`) 允许自定义 Protocol Endpoint 位置的配置.
====

[[servlet-oauth2login-override-boot-autoconfig]]
== 覆盖Spring Boot 2.x自动配置

用于 OAuth 客户端支持的 Spring Boot 2.x 自动配置类是 `OAuth2ClientAutoConfiguration`.

它执行以下任务:

* 从配置的 OAuth 客户端属性中注册由 `ClientRegistration` 组成的 `ClientRegistrationRepository` `@Bean`.
* 注册一个 `SecurityFilterChain` `@Bean` , 并通过 `httpSecurity.oauth2Login()` 启用 OAuth 2.0 登录.

如果您需要根据自己的特定要求覆盖自动配置,则可以通过以下方式进行:

* <<servlet-oauth2login-register-clientregistrationrepository-bean>>
* <<servlet-oauth2login-provide-securityfilterchain-bean>>
* <<servlet-oauth2login-completely-override-autoconfiguration>>


[[servlet-oauth2login-register-clientregistrationrepository-bean]]
=== 注册一个 ClientRegistrationRepository @Bean

下面例子展示如何注册一个 `ClientRegistrationRepository` `@Bean`:

====
.Java
[source,java,role="primary",attrs="-attributes"]
----
@Configuration
public class OAuth2LoginConfig {

	@Bean
	public ClientRegistrationRepository clientRegistrationRepository() {
		return new InMemoryClientRegistrationRepository(this.googleClientRegistration());
	}

	private ClientRegistration googleClientRegistration() {
		return ClientRegistration.withRegistrationId("google")
			.clientId("google-client-id")
			.clientSecret("google-client-secret")
			.clientAuthenticationMethod(ClientAuthenticationMethod.BASIC)
			.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
			.redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
			.scope("openid", "profile", "email", "address", "phone")
			.authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
			.tokenUri("https://www.googleapis.com/oauth2/v4/token")
			.userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
			.userNameAttributeName(IdTokenClaimNames.SUB)
			.jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
			.clientName("Google")
			.build();
	}
}
----

.Kotlin
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Configuration
class OAuth2LoginConfig {
    @Bean
    fun clientRegistrationRepository(): ClientRegistrationRepository {
        return InMemoryClientRegistrationRepository(googleClientRegistration())
    }

    private fun googleClientRegistration(): ClientRegistration {
        return ClientRegistration.withRegistrationId("google")
                .clientId("google-client-id")
                .clientSecret("google-client-secret")
                .clientAuthenticationMethod(ClientAuthenticationMethod.BASIC)
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
                .scope("openid", "profile", "email", "address", "phone")
                .authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
                .tokenUri("https://www.googleapis.com/oauth2/v4/token")
                .userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
                .userNameAttributeName(IdTokenClaimNames.SUB)
                .jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
                .clientName("Google")
                .build()
    }
}
----
====

[[servlet-oauth2login-provide-securityfilterchain-bean]]
=== 注册一个 SecurityFilterChain @Bean

以下示例显示如何使用 `@EnableWebSecurity` 注册 `SecurityFilterChain` `@Bean` 并通过 `httpSecurity.oauth2Login()` 启用 OAuth 2.0 登录：

.OAuth2 Login Configuration
====
.Java
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class OAuth2LoginSecurityConfig {

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
			.authorizeHttpRequests(authorize -> authorize
				.anyRequest().authenticated()
			)
			.oauth2Login(withDefaults());
		return http.build();
	}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebSecurity
class OAuth2LoginSecurityConfig {

    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            authorizeRequests {
                authorize(anyRequest, authenticated)
            }
            oauth2Login { }
        }
        return http.build()
    }
}
----
====


[[servlet-oauth2login-completely-override-autoconfiguration]]
=== 完全覆盖自动配置

下面的示例演示如何通过注册 `ClientRegistrationRepository` `@Bean` 和 `SecurityFilterChain` `@Bean` 来完全覆盖自动配置.

.Overriding the auto-configuration
====
.Java
[source,java,role="primary",attrs="-attributes"]
----
@Configuration
public class OAuth2LoginConfig {

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
			.authorizeHttpRequests(authorize -> authorize
				.anyRequest().authenticated()
			)
			.oauth2Login(withDefaults());
		return http.build();
	}

	@Bean
	public ClientRegistrationRepository clientRegistrationRepository() {
		return new InMemoryClientRegistrationRepository(this.googleClientRegistration());
	}

	private ClientRegistration googleClientRegistration() {
		return ClientRegistration.withRegistrationId("google")
			.clientId("google-client-id")
			.clientSecret("google-client-secret")
			.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
			.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
			.redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
			.scope("openid", "profile", "email", "address", "phone")
			.authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
			.tokenUri("https://www.googleapis.com/oauth2/v4/token")
			.userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
			.userNameAttributeName(IdTokenClaimNames.SUB)
			.jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
			.clientName("Google")
			.build();
	}
}
----

.Kotlin
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Configuration
class OAuth2LoginConfig {

    @Bean
    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            authorizeRequests {
                authorize(anyRequest, authenticated)
            }
            oauth2Login { }
        }
        return http.build()
    }

    @Bean
    fun clientRegistrationRepository(): ClientRegistrationRepository {
        return InMemoryClientRegistrationRepository(googleClientRegistration())
    }

    private fun googleClientRegistration(): ClientRegistration {
        return ClientRegistration.withRegistrationId("google")
                .clientId("google-client-id")
                .clientSecret("google-client-secret")
                .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
                .scope("openid", "profile", "email", "address", "phone")
                .authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
                .tokenUri("https://www.googleapis.com/oauth2/v4/token")
                .userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
                .userNameAttributeName(IdTokenClaimNames.SUB)
                .jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
                .clientName("Google")
                .build()
    }
}
----
====


[[servlet-oauth2login-javaconfig-wo-boot]]
== 低于 Spring Boot 2.x 使用 Java 配置

如果您无法使用 Spring Boot 2.x,并且想在 `CommonOAuth2Provider` 中配置预定义的提供程序之一 (例如 `Google`) ,请应用以下配置:

.OAuth2 Login Configuration
====
.Java
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class OAuth2LoginConfig {

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
			.authorizeHttpRequests(authorize -> authorize
				.anyRequest().authenticated()
			)
			.oauth2Login(withDefaults());
		return http.build();
	}

	@Bean
	public ClientRegistrationRepository clientRegistrationRepository() {
		return new InMemoryClientRegistrationRepository(this.googleClientRegistration());
	}

	@Bean
	public OAuth2AuthorizedClientService authorizedClientService(
			ClientRegistrationRepository clientRegistrationRepository) {
		return new InMemoryOAuth2AuthorizedClientService(clientRegistrationRepository);
	}

	@Bean
	public OAuth2AuthorizedClientRepository authorizedClientRepository(
			OAuth2AuthorizedClientService authorizedClientService) {
		return new AuthenticatedPrincipalOAuth2AuthorizedClientRepository(authorizedClientService);
	}

	private ClientRegistration googleClientRegistration() {
		return CommonOAuth2Provider.GOOGLE.getBuilder("google")
			.clientId("google-client-id")
			.clientSecret("google-client-secret")
			.build();
	}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebSecurity
open class OAuth2LoginConfig {
    @Bean
    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            authorizeRequests {
                authorize(anyRequest, authenticated)
            }
            oauth2Login { }
        }
        return http.build()
    }

    @Bean
    open fun clientRegistrationRepository(): ClientRegistrationRepository {
        return InMemoryClientRegistrationRepository(googleClientRegistration())
    }

    @Bean
    open fun authorizedClientService(
        clientRegistrationRepository: ClientRegistrationRepository?
    ): OAuth2AuthorizedClientService {
        return InMemoryOAuth2AuthorizedClientService(clientRegistrationRepository)
    }

    @Bean
    open fun authorizedClientRepository(
        authorizedClientService: OAuth2AuthorizedClientService?
    ): OAuth2AuthorizedClientRepository {
        return AuthenticatedPrincipalOAuth2AuthorizedClientRepository(authorizedClientService)
    }

    private fun googleClientRegistration(): ClientRegistration {
        return CommonOAuth2Provider.GOOGLE.getBuilder("google")
            .clientId("google-client-id")
            .clientSecret("google-client-secret")
            .build()
    }
}
----

.Xml
[source,xml,role="secondary"]
----
<http auto-config="true">
	<intercept-url pattern="/**" access="authenticated"/>
	<oauth2-login authorized-client-repository-ref="authorizedClientRepository"/>
</http>

<client-registrations>
	<client-registration registration-id="google"
						 client-id="google-client-id"
						 client-secret="google-client-secret"
						 provider-id="google"/>
</client-registrations>

<b:bean id="authorizedClientService"
		class="org.springframework.security.oauth2.client.InMemoryOAuth2AuthorizedClientService"
		autowire="constructor"/>

<b:bean id="authorizedClientRepository"
		class="org.springframework.security.oauth2.client.web.AuthenticatedPrincipalOAuth2AuthorizedClientRepository">
	<b:constructor-arg ref="authorizedClientService"/>
</b:bean>
----
====