
[[jc]]
= Java Configuration

Spring 3.1在Spring Framework中添加了对 https://docs.spring.io/spring/docs/3.1.x/spring-framework-reference/html/beans.html#beans-java[Java Configuration]的常规支持.  从Spring Security 3.2开始,已经有Spring Security Java Configuration支持,它使用户可以轻松配置Spring Security,而无需使用任何XML.

如果您熟悉 <<ns-config,第17章 "security 命名空间配置">>,则应该发现它与Security Java Configuration支持之间有很多相似之处.


NOTE:Spring Security提供了 https://github.com/spring-projects/spring-security/tree/master/samples/javaconfig[许多示例应用程序] ,它们演示了Spring Security Java Configuration的使用.

== Hello Web Security Java配置

第一步是创建我们的Spring Security Java配置.  该配置将创建一个称为 `springSecurityFilterChain` 的Servlet过滤器,该过滤器负责应用程序内的所有安全性 (保护应用程序URL,验证提交的用户名和密码,重定向到登录表单等) .  您可以在下面找到Spring Security Java配置的最基本示例:

[[jc-hello-wsca]]
[source,java]
----
import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.context.annotation.*;
import org.springframework.security.config.annotation.authentication.builders.*;
import org.springframework.security.config.annotation.web.configuration.*;

@EnableWebSecurity
public class WebSecurityConfig {

	@Bean
	public UserDetailsService userDetailsService() {
		InMemoryUserDetailsManager manager = new InMemoryUserDetailsManager();
		manager.createUser(User.withDefaultPasswordEncoder().username("user").password("password").roles("USER").build());
		return manager;
	}
}
----

这个配置确实没什么,但是它做了很多.  您可以找到以下功能的摘要:

* 要求对应用程序中的每个URL进行身份验证
* 为您生成一个登录表单
* 允许用 *用户名* _user_ 和 *密码* _password_ 的用户使用基于表单的身份验证进行身份验证
* 允许用户注销
* https://en.wikipedia.org/wiki/Cross-site_request_forgery[CSRF attack] 预防
* https://en.wikipedia.org/wiki/Session_fixation[Session Fixation] 保护
* Security Header 集成
** https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security[HTTP Strict Transport Security] for secure requests
** https://msdn.microsoft.com/en-us/library/ie/gg622941(v=vs.85).aspx[X-Content-Type-Options] 集成
** 缓存控制 (以后可以由您的应用程序覆盖,以允许缓存您的静态资源)
** https://msdn.microsoft.com/en-us/library/dd565647(v=vs.85).aspx[X-XSS-Protection] 集成
** X-Frame-Options 集成有助于防止 https://en.wikipedia.org/wiki/Clickjacking[Clickjacking]
* 与以下Servlet API方法集成
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getRemoteUser()[HttpServletRequest#getRemoteUser()]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getUserPrincipal()[HttpServletRequest#getUserPrincipal()]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#isUserInRole(java.lang.String)[HttpServletRequest#isUserInRole(java.lang.String)]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#login(java.lang.String,%20java.lang.String)[HttpServletRequest#login(java.lang.String, java.lang.String)]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#logout()[HttpServletRequest#logout()]

=== AbstractSecurityWebApplicationInitializer

下一步是向 war 注册 `springSecurityFilterChain`.  可以在Java配置中,在Servlet 3.0+环境中使用Spring的 https://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/mvc.html#mvc-container-config[Spring's WebApplicationInitializer support] .
毫无疑问,Spring Security提供了一个基类 `AbstractSecurityWebApplicationInitializer`,它将确保 `springSecurityFilterChain` 为您注册.  我们使用 `AbstractSecurityWebApplicationInitializer` 的方式有所不同,这取决于我们是否已经在使用Spring,或者Spring Security是应用程序中唯一的Spring组件.

* <<abstractsecuritywebapplicationinitializer-without-existing-spring>> - 如果您尚未使用 Spring,请按照以下说明进行操作
* <<abstractsecuritywebapplicationinitializer-with-spring-mvc>> - 如果您已经在使用 Spring,请按照以下说明进行操作

[[abstractsecuritywebapplicationinitializer-without-existing-spring]]]
=== 没有 Spring 的 AbstractSecurityWebApplicationInitializer

如果您不使用Spring或Spring MVC,则需要将 `WebSecurityConfig` 传递到超类中,以确保配置被选中. 您可以在下面找到一个示例:

[source,java]
----
import org.springframework.security.web.context.*;

public class SecurityWebApplicationInitializer
	extends AbstractSecurityWebApplicationInitializer {

	public SecurityWebApplicationInitializer() {
		super(WebSecurityConfig.class);
	}
}
----

`SecurityWebApplicationInitializer` 将执行以下操作:

* 为应用程序中的每个URL自动注册 `springSecurityFilterChain` 过滤器
* 添加一个用于加载 <<jc-hello-wsca,WebSecurityConfig>> 的 `ContextLoaderListener`.

[[abstractsecuritywebapplicationinitializer-with-spring-mvc]]]
=== Spring MVC 的 AbstractSecurityWebApplicationInitializer

如果我们在应用程序的其他地方使用Spring,则可能已经有一个 `WebApplicationInitializer` 正在加载Spring配置.  如果我们使用以前的配置,将会得到一个错误.  相反,我们应该向现有的 `ApplicationContext` 注册Spring Security.  例如,如果我们使用的是Spring MVC,则 `SecurityWebApplicationInitializer` 看起来将类似于以下内容:

[source,java]
----
import org.springframework.security.web.context.*;

public class SecurityWebApplicationInitializer
	extends AbstractSecurityWebApplicationInitializer {

}
----

这只会为应用程序中的每个URL仅注册 `springSecurityFilterChain` 过滤器.  之后,我们将确保将 `WebSecurityConfig` 加载到我们现有的 `ApplicationInitializer` 中.  例如,如果我们使用的是Spring MVC,则将其添加到  `getRootConfigClasses()` 中.

[[message-web-application-inititializer-java]]
[source,java]
----
public class MvcWebApplicationInitializer extends
		AbstractAnnotationConfigDispatcherServletInitializer {

	@Override
	protected Class<?>[] getRootConfigClasses() {
		return new Class[] { WebSecurityConfig.class };
	}

	// ... other overrides ...
}
----

[[jc-httpsecurity]]
== HttpSecurity

到目前为止,我们的  <<jc-hello-wsca,WebSecurityConfig>> 仅包含有关如何验证用户身份的信息.  Spring Security如何知道我们要要求所有用户进行身份验证?  Spring Security如何知道我们要支持基于表单的身份验证?  实际上,在后台调用了一个名为 `WebSecurityConfigurerAdapter` 的配置类.  它具有一种名为 `configure` 的方法,具有以下默认实现:

[source,java]
----
protected void configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests(authorize -> authorize
			.anyRequest().authenticated()
		)
		.formLogin(withDefaults())
		.httpBasic(withDefaults());
}
----

上面的默认配置:

* 确保对我们应用程序的任何请求都需要对用户进行身份验证
* 允许用户使用基于表单的登录进行身份验证
* 允许用户使用HTTP Basic身份验证进行身份验证

您会注意到此配置与XML Namespac非常相似

[source,xml]
----
<http>
	<intercept-url pattern="/**" access="authenticated"/>
	<form-login />
	<http-basic />
</http>
----

== Multiple HttpSecurity

我们可以配置多个 `HttpSecurity` 实例,就像我们可以具有多个 `<http>`  块一样.  关键是多次扩展 `WebSecurityConfigurerAdapter`.  例如,以下示例说明了以 `/api/` 开头的URL具有不同的配置.

[source,java]
----
@EnableWebSecurity
public class MultiHttpSecurityConfig {
	@Bean                                                             <1>
	public UserDetailsService userDetailsService() throws Exception {
		// ensure the passwords are encoded properly
		UserBuilder users = User.withDefaultPasswordEncoder();
		InMemoryUserDetailsManager manager = new InMemoryUserDetailsManager();
		manager.createUser(users.username("user").password("password").roles("USER").build());
		manager.createUser(users.username("admin").password("password").roles("USER","ADMIN").build());
		return manager;
	}

	@Configuration
	@Order(1)                                                        <2>
	public static class ApiWebSecurityConfigurationAdapter extends WebSecurityConfigurerAdapter {
		protected void configure(HttpSecurity http) throws Exception {
			http
				.antMatcher("/api/**")                               <3>
				.authorizeRequests(authorize -> authorize
					.anyRequest().hasRole("ADMIN")
			    )
				.httpBasic(withDefaults());
		}
	}

	@Configuration                                                   <4>
	public static class FormLoginWebSecurityConfigurerAdapter extends WebSecurityConfigurerAdapter {

		@Override
		protected void configure(HttpSecurity http) throws Exception {
			http
				.authorizeRequests(authorize -> authorize
					.anyRequest().authenticated()
				)
				.formLogin(withDefaults());
		}
	}
}
----

<1> 正常配置身份验证
<2> 创建一个包含 `@Order` 的 `WebSecurityConfigurerAdapter` 实例,以指定应首先考虑哪个 `WebSecurityConfigurerAdapter`.
<3> `http.antMatcher` 声明此 `HttpSecurity` 仅适用于以 `/api/` 开头的URL
<4> 创建 `WebSecurityConfigurerAdapter的另一个实例`.  如果网址不是以 `/api/` 开头,则将使用此配置.  在 `ApiWebSecurityConfigurationAdapter` 之后考虑此配置,因为它的@Order值在 `1` 以后 (没有 `@Order` 默认为 `last`) .

[[jc-custom-dsls]]
== 自定义 DSLs

您可以在Spring Security中提供自己的自定义DSL. 例如,您可能会有类似以下内容的内容:

[source,java]
----
public class MyCustomDsl extends AbstractHttpConfigurer<MyCustomDsl, HttpSecurity> {
	private boolean flag;

	@Override
	public void init(H http) throws Exception {
		// any method that adds another configurer
		// must be done in the init method
		http.csrf().disable();
	}

	@Override
	public void configure(H http) throws Exception {
		ApplicationContext context = http.getSharedObject(ApplicationContext.class);

		// here we lookup from the ApplicationContext. You can also just create a new instance.
		MyFilter myFilter = context.getBean(MyFilter.class);
		myFilter.setFlag(flag);
		http.addFilterBefore(myFilter, UsernamePasswordAuthenticationFilter.class);
	}

	public MyCustomDsl flag(boolean value) {
		this.flag = value;
		return this;
	}

	public static MyCustomDsl customDsl() {
		return new MyCustomDsl();
	}
}
----

NOTE: 实际上,这就是实现诸如 `HttpSecurity.authorizeRequests()` 之类的方法的方式.

然后可以像下面这样使用自定义DSL:

[source,java]
----
@EnableWebSecurity
public class Config extends WebSecurityConfigurerAdapter {
	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.apply(customDsl())
				.flag(true)
				.and()
			...;
	}
}
----

该代码按以下顺序调用:

* 调用 `Config` 的configure方法中的代码
* MyCustomDsl的init方法中的代码被调用
* MyCustomDsl的configure方法中的代码被调用

如果需要,可以使用 `SpringFactories` 在默认情况下使 `WebSecurityConfigurerAdapter` 添加 `MyCustomDsl`. 例如,您将在具有以下内容的类路径上创建名为 `META-INF/spring.factories` 的资源:

.META-INF/spring.factories
----
org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer = sample.MyCustomDsl
----

希望禁用默认设置的用户可以明确地这样做.

[source,java]
----
@EnableWebSecurity
public class Config extends WebSecurityConfigurerAdapter {
	@Override
	protected void configure(HttpSecurity http) throws Exception {
		http
			.apply(customDsl()).disable()
			...;
	}
}
----

[[post-processing-configured-objects]]
== 配置对象后置处理器

Spring Security的Java配置并未暴露其配置的每个对象的每个属性.  这简化了大多数用户的配置.  毕竟,如果每个属性都暴露,则用户可以使用标准Bean配置.

尽管有充分的理由不直接暴露每个属性,但用户可能仍需要更多高级配置选项.  为了解决这个问题,Spring Security引入了 `ObjectPostProcessor` 的概念,该概念可用于修改或替换Java配置创建的许多Object实例.
例如,如果要在 `FilterSecurityInterceptor` 上配置 `filterSecurityPublishAuthorizationSuccess` 属性,则可以使用以下内容:

[source,java]
----
@Override
protected void configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests(authorize -> authorize
			.anyRequest().authenticated()
			.withObjectPostProcessor(new ObjectPostProcessor<FilterSecurityInterceptor>() {
				public <O extends FilterSecurityInterceptor> O postProcess(
						O fsi) {
					fsi.setPublishAuthorizationSuccess(true);
					return fsi;
				}
			})
		);
}
----
