[[servlet-hello-jc]]
= Hello Spring Security (Java Configuration)

本节介绍如何在Java配置中使用Spring Security。 有关如何在XML配置中使用Spring Security，
请参见<<servlet-hello-xml,第8.3节 "Hello Spring Security（XML">>.。
有关如何在Spring Boot配置中使用Spring Security的信息，请参见<<servlet-hello-boot,第8.1节 "Hello Spring Security（ Boot）">>。

NOTE: 您可以在 {gh-samples-url}/javaconfig/helloworld[samples/javaconfig/helloworld] 中找到完整的应用程序。

== 更新依赖

第一步是使用<<getting-maven-no-boot,Maven>>或<<gradle-without-spring-boot,Gradle>>更新依赖关系。


[[servlet-hello-jc-ews]]
== 最小化 `@EnableWebSecurity` 配置

第一步是创建我们的Spring Security Java配置.
这个配置在你的应用程序中创建一个 `springSecurityFilterChain` 的Servlet的过滤器 `springSecurityFilterChain` 负责所有安全（例如 保护应用程序的URL，验证提交的用户名和密码，重定向到登陆的表单等等）。
以下示例显示了Spring Security Java配置的最基本示例：:

.WebSecurity.java
====
[source,java]
----
import org.springframework.context.annotation.*;
import org.springframework.security.config.annotation.web.configuration.*;
import org.springframework.security.core.userdetails.*;
import org.springframework.security.provisioning.*;

@EnableWebSecurity
public class WebSecurityConfig {

	// @formatter:off
	@Bean
	public UserDetailsService userDetailsService() {
		UserDetails user = User.withDefaultPasswordEncoder()
			.username("user")
			.password("password")
			.roles("USER")
			.build();
		return  new InMemoryUserDetailsManager(user);
	}
	// @formatter:on
}
----
====

此配置的确没有太多，但是却做了很多。 功能摘要如下：:

* 要求经过身份验证的用户才能与应用程序进行任何交互
* 为您生成一个默认的登录表单
* 让用户使用用户名为 `user` 和密码为 `password` 进行表单登录
* 使用 BCrypt 加密算法进行密码保存
* 让用户注销
* https://en.wikipedia.org/wiki/Cross-site_request_forgery[CSRF 攻击] 防御
* https://en.wikipedia.org/wiki/Session_fixation[会话固定攻击] 防御
* 安全 Header 集成
** 为安全请求使用 https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security[HTTP Strict Transport Security]
** https://msdn.microsoft.com/en-us/library/ie/gg622941(v=vs.85).aspx[X-Content-Type-Options] 集成
** 缓存控制（以后可以由您的应用程序覆盖，以允许缓存您的静态资源）
** https://msdn.microsoft.com/en-us/library/dd565647(v=vs.85).aspx[X-XSS-Protection] 集成
** X-Frame-Options 集成防止点击劫持 https://en.wikipedia.org/wiki/Clickjacking[Clickjacking]
* 与以下Servlet API方法集成:
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getRemoteUser()[`HttpServletRequest#getRemoteUser()`]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getUserPrincipal()[`HttpServletRequest.html#getUserPrincipal()`]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#isUserInRole(java.lang.String)[`HttpServletRequest.html#isUserInRole(java.lang.String)`]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#login(java.lang.String,%20java.lang.String)[`HttpServletRequest.html#login(java.lang.String, java.lang.String)`]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#logout()[`HttpServletRequest.html#logout()`]

// FIXME: After completed rewriting, link to all the sections of doc that this relates to

== 使用 `AbstractSecurityWebApplicationInitializer`

下一步是向war注册 `springSecurityFilterChain`。 Spring Security提供了一个基类（`AbstractSecurityWebApplicationInitializer`），它利用了 https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-servlet[Spring的 `WebApplicationInitializer` 支持]。

以下示例显示了示例配置:

.SecurityInitializer.java
====
[source,java]
----
import org.springframework.security.web.context.*;

public class SecurityInitializer
	extends AbstractSecurityWebApplicationInitializer {

	public SecurityInitializer() {
		super(WebSecurityConfig.class);
	}
}
----
====

`SecurityInitializer` 执行以下操作：

* 添加一个 `ContextLoaderListener` 来加载 <<servlet-hello-jc-ews,`WebSecurityConfig`>>。
* 查找名为 `SpringSecurityFilterChain` 的Filter类型的bean，并将其注册，然后可以处理应用程序中的每个URL。


[NOTE]
====
如果要与Spring MVC应用程序集成，请确保配置 `DispatcherServlet` 从根 `ApplicationContext` 加载配置。 以下示例显示了如何执行此操作：

.MvcInitializer.java
=====
[source,java]
----
public class MvcInitializer extends
		AbstractAnnotationConfigDispatcherServletInitializer {

	// the Root Config is registered in SecurityInitializer
	@Override
	protected Class<?>[] getRootConfigClasses() {
		return null;
	}

	// the Spring MVC configuration should be added to SecurityInitializer constructor
	// i.e.
	// super(MvcConfig.class, WebSecurityConfig.class);
	@Override
	protected Class<?>[] getServletConfigClasses() {
		return null;
	}

	@Override
	protected String[] getServletMappings() {
		return new String[] { "/" };
	}

}

----
=====
====
