[[packaging-executable]]
== 打包可执行文件

插件可以创建可执行文件(jar文件或者war文件), 里面包含所有应用的依赖并且可以使用 `java -jar` 执行.

[[packaging-executable-jars]]
=== 打包可执行 jars

可以使用 `bootJar` 任务构建可执行的 jars. 如果应用了 java 插件, 这个任务会自动的创建, 并且是 {boot-jar-javadoc}[`BootJar`] 的实例. `assemble` 任务会自动配置依赖于 `bootJar` 任务, 所以运行 `assemble` (or `build`)  也会运行 `bootJar` 任务.

[[packaging-executable-wars]]
=== 打包可执行 wars

可以使用 `bootWar` 任务构建可执行的 wars.如果应用了 `war` 插件,  这个任务会自动的创建, 并且是 {boot-war-javadoc}[`BootWar`] 的实例. `assemble` 任务会自动配置依赖于 `bootWar` 任务, 所以运行 `assemble` (or `build`)  也会运行 `bootWar` 任务.

[[packaging-executable-wars-deployable]]
==== 打包可执行和可部署的 wars

可以打包 war 文件, 以便可以使用 `java -jar` 执行该文件并将其部署到外部容器中.  为此, 应将嵌入式 Servlet 容器依赖添加到提供的 Runtime 配置中, 例如:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../../gradle/packaging/war-container-dependency.gradle[tags=dependencies]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../../gradle/packaging/war-container-dependency.gradle.kts[tags=dependencies]
----

这样可以确保在打包后的 war 文件中的 `WEB-INF/lib-provided` 提供的目录中不会与外部容器自己的类冲突.

NOTE: `providedRuntime` 优先于 Gradle 的  `compileOnly` 配置, 因为除其他限制外, compileOnly 依赖不在测试类路径上, 因此任何基于 Web 的集成测试都将失败.

[[packaging-executable-and-normal]]
=== 打包可执行和普通文件

默认的, 当 `bootJar` 或者 `bootWar` 任务配置了, `jar` 或者 `war` 任务会被禁用掉. 但是可以同时构建一个可执行和普通的文件通过设置 `jar` 或者 `war` 任务可用

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../../gradle/packaging/boot-jar-and-jar.gradle[tags=enable-jar]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../../gradle/packaging/boot-jar-and-jar.gradle.kts[tags=enable-jar]
----

为了避免可执行文件和普通文件生成在同一个目录, 其中一个应该使用不同的位置. 一种方法就是配置一个 classifier:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../../gradle/packaging/boot-jar-and-jar.gradle[tags=classifier]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../../gradle/packaging/boot-jar-and-jar.gradle.kts[tags=classifier]
----


[[packaging-executable-configuring]]
=== 配置可执行文件打包

BootJar
和 BootWar

{boot-jar-javadoc}[`BootJar`] 和 {boot-war-javadoc}[`BootWar`] 任务分别是 Gradle 的 `jar` 或者 `war` 任务的子类. 所以, 所有的在打包 `jar` 或者 `war` 时用的标准配置都对可执行的 `jar` 或者 `war` 可用.
当然也有对可执行 jars 或者 wars 的特殊配置.

[[packaging-executable-configuring-main-class]]
==== 配置主类

默认的, 可执行文件的主类会自动的在任务的类路径目录里查找一个带有 `public static void main(String[])` 的方法. 主类也可以显示的使用 `mainCalss` 设置:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../../gradle/packaging/boot-jar-main-class.gradle[tags=main-class]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../../gradle/packaging/boot-jar-main-class.gradle.kts[tags=main-class]
----

或者, 可以使用 Spring Boot DSL 的 `mainClassName` 属性在项目范围内配置主类名称:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../../gradle/packaging/spring-boot-dsl-main-class.gradle[tags=main-class]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../../gradle/packaging/spring-boot-dsl-main-class.gradle.kts[tags=main-class]
----

另外, 如果应用了 {application-plugin}[`application` plugin] 可以这么设置 `mainClassName` 属性:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../../gradle/packaging/application-plugin-main-class.gradle[tags=main-class]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../../gradle/packaging/application-plugin-main-class.gradle.kts[tags=main-class]
----

最后, `Start-Class` 属性可以在任务的 manifest 里配置:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../../gradle/packaging/boot-jar-manifest-main-class.gradle[tags=main-class]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../../gradle/packaging/boot-jar-manifest-main-class.gradle.kts[tags=main-class]
----


[[packaging-executable-configuring-excluding-devtools]]
==== Excluding Devtools

默认 SpringBoot 的 Devtools 模块 `org.springframework.boot:spring-boot-devtools` 不会被打包进可执行的 jar 或者 war. 如果打包 Devtools 到文件里, 设置 `excludeDevtools` 属性为 `false`:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../../gradle/packaging/boot-war-include-devtools.gradle[tags=include-devtools]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../../gradle/packaging/boot-war-include-devtools.gradle.kts[tags=include-devtools]
----


[[packaging-executable-configuring-unpacking]]
==== 配置需要移除的库

大多数库可以直接嵌套进可执行的文件里, 但是某些库可能有问题. 比如,JRuby 引入了它自己的内嵌jar支持, 比如 `jruby-complete.jar` 总是直接在文件系统上可用.

处理这个问题库, 可执行文件可以配置在运行(run)的时候移除指定的嵌套 jars 到临时目录. 库可以使用 Ant-style 模式匹配源jar文件的绝对路径移除需要的包:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../../gradle/packaging/boot-jar-requires-unpack.gradle[tags=requires-unpack]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../../gradle/packaging/boot-jar-requires-unpack.gradle.kts[tags=requires-unpack]
----

为了更好地控制, 也可以使用 closure.  该 closure 传递了一个 `FileTreeElement`, 并且应返回一个 `boolean`, 指示是否需要打包.

[[packaging-executable-configuring-launch-script]]
==== 让文件完全可执行

Spring Boot 对完全可执行文件提供支持. 通过已知的如何启动应用的预 shell 脚步来制造完全可执行. 在类 Unix 平台上, 这个启动脚本运行文件可以像任何可执行文件直接运行或者作为服务安装.

启用这个特性, launchScript 必须启用:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../../gradle/packaging/boot-jar-include-launch-script.gradle[tags=include-launch-script]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../../gradle/packaging/boot-jar-include-launch-script.gradle.kts[tags=include-launch-script]
----

这将添加Spring Boot的默认脚本到文件里. 默认的启动脚本包含若干个属性并且设置了合适的默认值, 当然也可以通过 `properties` 属性自定义默认值:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../../gradle/packaging/boot-jar-launch-script-properties.gradle[tags=launch-script-properties]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../../gradle/packaging/boot-jar-launch-script-properties.gradle.kts[tags=launch-script-properties]
----

如果启动脚本没有你想要的, `script` 属性可以提供一个自定义的启动脚本:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../../gradle/packaging/boot-jar-custom-launch-script.gradle[tags=custom-launch-script]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../../gradle/packaging/boot-jar-custom-launch-script.gradle.kts[tags=custom-launch-script]
----


[[packaging-executable-configuring-properties-launcher]]
==== 使用 `PropertiesLauncher`

要想使用 `PropertiesLauncher` 启动可执行 jar 或者 war, 配置任务的 manifest 来设置 `Main-Class` 属性:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../../gradle/packaging/boot-war-properties-launcher.gradle[tags=properties-launcher]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../../gradle/packaging/boot-war-properties-launcher.gradle.kts[tags=properties-launcher]
----

