

[[observability-metrics-flow-duration]]
= Flow Duration

____
Times the duration elapsed between a subscription and the termination or cancellation of the sequence. A TerminationTags#STATUS tag is added to specify what event caused the timer to end ( `"completed"`, `"completedEmpty"`, `"error"` or `"cancelled"`).
____


**Metric name** `%s.flow.duration` - since it contains `%s`, the name is dynamic and will be resolved at runtime. **Type** `distribution summary`.


IMPORTANT: KeyValues that are added after starting the Observation might be missing from the *.active metrics.






.Low cardinality Keys
[cols="a,a"]
|===
|Name | Description
|`exception` _(required)_|Tag used by FLOW_DURATION when STATUS is `"error"`, to store the exception that occurred.
|`status` _(required)_|The termination status:

 - `"completed"` for a sequence that terminates with an onComplete, with onNext(s)
 - `"completedEmpty"` for a sequence that terminates without any onNext before the onComplete
 - `"error"` for a sequence that terminates with an onError
 - `"cancelled"` for a sequence that has cancelled its subscription
|`type` _(required)_|The type of the sequence ( `"Flux"` or `"Mono"`).
|===



[[observability-metrics-malformed-source-events]]
= Malformed Source Events

____
Counts the number of events received from a malformed source (ie an onNext after an onComplete).
____


**Metric name** `%s.malformed.source` - since it contains `%s`, the name is dynamic and will be resolved at runtime. **Type** `counter`.


IMPORTANT: KeyValues that are added after starting the Observation might be missing from the *.active metrics.






.Low cardinality Keys
[cols="a,a"]
|===
|Name | Description
|`type` _(required)_|The type of the sequence ( `"Flux"` or `"Mono"`).
|===



[[observability-metrics-on-next-delay]]
= On Next Delay

____
Measures the delay between each onNext (or between the first onNext and the onSubscribe event).
____


**Metric name** `%s.onNext.delay` - since it contains `%s`, the name is dynamic and will be resolved at runtime. **Type** `timer` and **base unit** `nanoseconds`.


IMPORTANT: KeyValues that are added after starting the Observation might be missing from the *.active metrics.


IMPORTANT: Micrometer internally uses `nanoseconds` for the baseunit. However, each backend determines the actual baseunit. (i.e. Prometheus uses seconds)





.Low cardinality Keys
[cols="a,a"]
|===
|Name | Description
|`type` _(required)_|The type of the sequence ( `"Flux"` or `"Mono"`).
|===



[[observability-metrics-requested-amount]]
= Requested Amount

____
Counts the amount requested to a named sequence (eg. `Flux.name(String)`) by all subscribers, until at least one requests an unbounded amount.
____


**Metric name** `%s.requested` - since it contains `%s`, the name is dynamic and will be resolved at runtime. **Type** `distribution summary`.


IMPORTANT: KeyValues that are added after starting the Observation might be missing from the *.active metrics.






.Low cardinality Keys
[cols="a,a"]
|===
|Name | Description
|`type` _(required)_|The type of the sequence ( `"Flux"` or `"Mono"`).
|===



[[observability-metrics-subscribed]]
= Subscribed

____
Counts the number of subscriptions to a sequence.
____


**Metric name** `%s.subscribed` - since it contains `%s`, the name is dynamic and will be resolved at runtime. **Type** `counter`.


IMPORTANT: KeyValues that are added after starting the Observation might be missing from the *.active metrics.






.Low cardinality Keys
[cols="a,a"]
|===
|Name | Description
|`type` _(required)_|The type of the sequence ( `"Flux"` or `"Mono"`).
|===




