

[[observability-metrics-tasks-active]]
= Tasks Active

____
LongTaskTimer reflecting tasks currently running. Note that this reflects all types of active tasks, including tasks scheduled with a delay or periodically (each iteration being considered an active task).
____


**Metric name** `%s.scheduler.tasks.active` - since it contains `%s`, the name is dynamic and will be resolved at runtime. **Type** `long task timer`.


IMPORTANT: KeyValues that are added after starting the Observation might be missing from the *.active metrics.


IMPORTANT: Micrometer internally uses `nanoseconds` for the baseunit. However, each backend determines the actual baseunit. (i.e. Prometheus uses seconds)









[[observability-metrics-tasks-completed]]
= Tasks Completed

____
Timer reflecting tasks that have finished execution. Note that this reflects all types of active tasks, including tasks with a delay or periodically (each iteration being considered a separate completed task).
____


**Metric name** `%s.scheduler.tasks.completed` - since it contains `%s`, the name is dynamic and will be resolved at runtime. **Type** `timer`.


IMPORTANT: KeyValues that are added after starting the Observation might be missing from the *.active metrics.


IMPORTANT: Micrometer internally uses `nanoseconds` for the baseunit. However, each backend determines the actual baseunit. (i.e. Prometheus uses seconds)









[[observability-metrics-tasks-pending]]
= Tasks Pending

____
LongTaskTimer reflecting tasks that were submitted for immediate execution but couldn't be started immediately because the scheduler is already at max capacity. Note that only immediate submissions via Scheduler#schedule(Runnable) and Scheduler.Worker#schedule(Runnable) are considered.
____


**Metric name** `%s.scheduler.tasks.pending` - since it contains `%s`, the name is dynamic and will be resolved at runtime. **Type** `long task timer`.


IMPORTANT: KeyValues that are added after starting the Observation might be missing from the *.active metrics.


IMPORTANT: Micrometer internally uses `nanoseconds` for the baseunit. However, each backend determines the actual baseunit. (i.e. Prometheus uses seconds)









[[observability-metrics-tasks-submitted]]
= Tasks Submitted

____
Counter that increments by one each time a task is submitted (via any of the schedule methods on both Scheduler and Scheduler.Worker).

Note that there are actually 4 counters, which can be differentiated by the SubmittedTags#SUBMISSION tag. The sum of all these can thus be compared with the TASKS_COMPLETED counter.
____


**Metric name** `%s.scheduler.tasks.submitted` - since it contains `%s`, the name is dynamic and will be resolved at runtime. **Type** `counter`.


IMPORTANT: KeyValues that are added after starting the Observation might be missing from the *.active metrics.






.Low cardinality Keys
[cols="a,a"]
|===
|Name | Description
|`submission.type` _(required)_|The type of submission:

 - `"direct"` for `Scheduler#schedule(Runnable)`
 - `"delayed"` for `Scheduler#schedule(Runnable,long,TimeUnit)`
 - `"periodic_initial"` for `Scheduler#schedulePeriodically(Runnable,long,long,TimeUnit)` after the initial delay
 - `"periodic_iteration"` for `Scheduler#schedulePeriodically(Runnable,long,long,TimeUnit)` further periodic iterations
|===




