[[single-version-declarations]]
= 声明版本范围

最简单的声明版本的方式就是使用 version 字符串表示，Gradle 支持不同的方式来声明版本字符串：:

* 确定的版本: e.g. `1.3`, `1.3.0-beta3`, `1.0-20150201.131010-1`
* Maven 风格的声明: e.g. `[1.0,)`, `[1.1, 2.0)`, `(1.2, 1.5]`
** `[` and `]` 符号表示版本范围; `(` and `)` 表示界限
** 缺少上限或下限时，范围没有上限或下限。
** 可以使用符号 `]`  代表 `(` 表示下限, 使用 `[` 代替 `)` 表示上限. 例如 `]1.0, 2.0[`
* 版本前缀范围: e.g. `1.+`, `1.3.+`
** 仅包括与 `+` 之前的版本匹配.
** `+` 本身将包含任何版本.
* `latest-status` 版本: e.g. `latest.integration`, `latest.release`
** 将版本最高的模块与指定状态匹配 link:{javadocPath}/org/gradle/api/artifacts/ComponentMetadata.html#getStatus--[ComponentMetadata.getStatus()].
* Maven `SNAPSHOT` 版本标识符: e.g. `1.0-SNAPSHOT`, `1.4.9-beta1-SNAPSHOT`

[NOTE]
====
Gradle 6.5支持版本范围的备用选择加入行为。

当上限排除版本时，它还充当前缀排除。 这意味着 `[1.0, 2.0[` 也将排除所有以 `2.0` 开头且小于 `2.0` 的版本。 例如，该范围中不再包括 `2.0-dev1` 或 `2.0-SNAPSHOT` 之类的版本。
This means that  will also exclude all versions starting with `2.0` that are smaller than `2.0`.
For example versions like `2.0-dev1` or `2.0-SNAPSHOT` are no longer included in the range.

在  `settings.gradle(.kts)` 中激活预览功能 `VERSION_ORDERING_V2`:
```
enableFeaturePreview("VERSION_ORDERING_V2")
```

此项更改将成为 Gradle 7.0 中的默认设置.
====

== Version 排序

版本具有隐式排序。 版本排序用于:

* 确定范围内是否包括特定版本。.
* 解决冲突时，确定哪个版本是“最新的”.

版本根据以下规则排序:

* 每个版本由不同部分组成 "parts":
** `[. - _ +]` 用于分隔版本的不同 "parts".
** 同时包含数字和字母的部分都将分为以下各部分: `1a1 == 1.a.1`
** 仅比较版本的各个部分。实际的分隔符并不重要: `1.a.1 == 1-a+1 == 1.a-1 == 1a1`
* 使用以下规则比较2个版本的相同部分:
** 如果两个部分都是数字，则最高数值较高: `1.1` < `1.2`
** 如果一个部分是数字部分，则认为它高于非数字部分: `1.a` < `1.1`
** 如果两者都不是数字，则按字母顺序比较零件，区分大小写: `1.A` < `1.B` < `1.a` < `1.b`
** 具有额外数​​字部分的版本被认为高于没有以下内容的版本: `1.1` < `1.1.0`
** 具有额外的非数字部分的版本被认为低于没有以下版本的版本: `1.1.a` < `1.1`
* 某些字符串值出于排序目的具有特殊含义:
** `dev` 认为低于任何其他字符串部分: `1.0-dev` < `1.0-alpha` < `1.0-rc`.
** `rc`, `release` and `final` 被认为高于任何其他字符串部分（按该顺序排序）: `1.0-zeta` < `1.0-rc` < `1.0-release` < `1.0-final` < `1.0`.
** `SNAPSHOT` 没有特殊含义，并且像其他字符串部分一样按字母顺序排序: `1.0-alpha` < `1.0-SNAPSHOT` < `1.0-zeta` < `1.0-rc` < `1.0`.
** 数值快照版本没有特殊含义，其排序方式与任何其他数值部分一样: `1.0` < `1.0-20150201.121010-123` < `1.1`.

[NOTE]
====
Gradle 6.5 支持替代的，选择加入的版本排序方案，在特殊情况下，它们具有更多后缀:

：1.0-RC <1.0-SNAPSHOT <1.0

：1.0-RC <1.0-FINAL <1.0-GA <1.0-RELEASE <1.0

：1.0-RELEASE <1.0-SP1 <1.0



* 字符串 `SNAPSHOT` 的顺序应高于 `rc`: `1.0-RC` < `1.0-SNAPSHOT` < `1.0`
* 字符串 `GA` 将按字母顺序在 `FINAL` 和 `RELEASE` 旁边排序: `1.0-RC` < `1.0-FINAL` < `1.0-GA` < `1.0-RELEASE` < `1.0`
* 字符串 `SP` 的排序将高于 `RELEASE`，但仍低于未限定的版本，将其使用限制为使用 `FINAL`，`GA` 或 `RELEASE` 的版本控制方案 `FINAL`, `GA` or `RELEASE`: `1.0-RELEASE` < `1.0-SP1` < `1.0`

在  `settings.gradle(.kts)` 中激活预览功能 `VERSION_ORDERING_V2`:
```
enableFeaturePreview("VERSION_ORDERING_V2")
```

此项更改将成为 Gradle 7.0 中的默认设置.
====

== 简单的版本声明语义

使用缩写符号声明版本时，例如:

.A simple declaration
====
include::{snippets-dir}/dependencyManagement/declaringDependencies-concreteVersion/groovy/build.gradle[tags=required-version]
include::{snippets-dir}/dependencyManagement/declaringDependencies-concreteVersion/kotlin/build.gradle.kts[tags=required-version]
====

然后将该版本视为必需版本，这意味着它至少应为 `1.7.15`，但可以由引擎进行升级（乐观升级）。

但是，对于 <<rich_versions.adoc#sec:required-version,required version>>，使用 `!!` 来表示：

.Shorthand notation for strict dependencies
====
include::{snippets-dir}/dependencyManagement/declaringDependencies-concreteVersion/groovy/build.gradle[tags=strict-shorthand]
include::{snippets-dir}/dependencyManagement/declaringDependencies-concreteVersion/kotlin/build.gradle.kts[tags=strict-shorthand]
====

严格版本无法升级，并且会覆盖源自此依赖提供的任何传递性依赖。建议对严格版本使用范围。

上面的符号 `[1.7, 1.8[!!1.7.25` 等效于:

* strictly `[1.7, 1.8[`
* prefer `1.7.25`

这意味着引擎必须在 1.7（包括）和 1.8（排除）之间选择一个版本，并且如果图中的其他组件都不需要其他版本，则它应该首选 `1.7.25`。

[[sec:declaring_without_version]]
== 声明没有版本的依赖

对于较大的项目，建议的做法是声明没有版本的依赖，并将 <<dependency_constraints.adoc#sec:adding-constraints-transitive-deps,dependency constraints>> 用于版本声明。 优势在于，依赖约束使您可以在一处管理所有依赖的版本，包括可传递的依赖。

.Declaring a dependency without version
====
include::{snippets-dir}/dependencyManagement/declaringDependencies-withoutVersion/groovy/build.gradle[tags=dependencies-without-version]
include::{snippets-dir}/dependencyManagement/declaringDependencies-withoutVersion/kotlin/build.gradle.kts[tags=dependencies-without-version]
====
