[[conditional]]
= Headers 的条件运算
:spring-data-rest-root: ../../../..

本节说明 Spring Data REST 如何使用标准 HTTP 标头来提高性能，对操作进行条件化并为更复杂的前端做贡献。

[[conditional.etag]]
== `ETag`, `If-Match`, 和 `If-None-Match` Headers

该 https://tools.ietf.org/html/rfc7232#section-2.3[`ETag` header] 提供了一种方法来标记资源。这可以防止客户端相互覆盖，同时也可以减少不必要的请求。

考虑以下例子:

.具有版本号的POJO
====
[source,java,indent=0]
----
include::{spring-data-rest-root}/spring-data-rest-webmvc/src/test/java/org/springframework/data/rest/webmvc/support/ETagUnitTests.java[tag=versioned-sample]
----

<1>  `@Version` 注解（如果您使用的是 Spring Data JPA，则为 JPA，对于所有其他模块，则为 Spring Data org.springframework.data.annotation.Version），将该字段标记为版本标记。
====

该 POJO 由 Spring Data REST 提供为 REST 资源时，将具有带有版本字段值的 `ETag` 标头。

如果我们提供这样的 `If-Match` header，我们可以有条件地 `PUT`，`PATCH` 或 `DELETE` 该资源：

====
----
curl -v -X PATCH -H 'If-Match: <value of previous ETag>' ...
----
====

只有当资源的当前 `ETag` 状态与此 `If-Match` 头匹配时，才能执行操作。此保护措施可防止客户端相互踩踏。两个不同的客户端可以获取资源并具有相同的 `ETag`。如果一个客户端更新资源，它将在响应中获取一个新的 `ETag`。
但是第一个客户端仍然有旧的头。如果该客户端尝试使用 `If-Match` header 进行更新，则更新将失败，因为它们不再匹配。相反，该客户端将收到要发回的 HTTP  `412 Precondition Failed`  消息。然而，客户端可以赶上，但是是必要的。

WARNING: 术语  "`version,`"  可以使用不同的数据存储，甚至在应用程序中使用不同的语义来处理不同的语义。 Spring Data REST 有效地委托给数据存储的元模型，以辨别字段是否被版本化，如果是，则只允许列表的更新如果 `ETag` 匹配。

https://tools.ietf.org/html/rfc7232#section-3.2[`If-None-Match` header] 头提供了一种替代。`If-None-Match` 代替条件更新，允许进行条件查询。

====
----
curl -v -H 'If-None-Match: <value of previous etag>' ...
----
====

此命令（默认情况下）执行 GET。Spring Data REST 将在执行 `GET` 时检查 `If-None-Match` header。如果匹配 `ETag`，它将不会完成任何改变，而不是发送资源的副本，而是响应 HTTP `304 Not Modified` 状态码。
从语法上看，它显示为 "`如果这个提供的 header 与服务器端版本不匹配，那么给我发送整个资源，否则不要给我任何东西。`"

NOTE: 该POJO来自于基于 `ETag` 的单元测试，因此在应用程序代码中没有预期的  `@Entity` (JPA) 或  `@Document` (MongoDB) 注解。它只关注如何使用 `@Version` 的字段导致一个 `ETag` 头。

[[conditional.if-modified-since]]
== `If-Modified-Since` header

https://tools.ietf.org/html/rfc7232#section-3.3[`If-Modified-Since` header] 头提供了一种方法来检查，如果资源已经自上次请求更新，以避免重新发送相同的数据。

.在实体类型中捕获的最后修改日期
====
[source,java]
----
include::{spring-data-rest-root}/spring-data-rest-tests/spring-data-rest-tests-mongodb/src/main/java/org/springframework/data/rest/tests/mongodb/Receipt.java[tag=code]
----

<1>  Spring Data Commons 的  `@LastModifiedDate` 注解允许以多种格式捕获此信息（JodaTime的 `DateTime`，旧版 Java `Date` 和 `Calendar`，JDK8 date/time 类型以及  `long`/`Long`）。
====

使用此字段，Spring Data REST 将返回一个  `Last-Modified` header，如下所示：

----
Last-Modified: Wed, 24 Jun 2015 20:28:15 GMT
----

该值可以被捕获并用于后续查询，以避免在没有更新的时候提取相同的数据两次。

====
----
curl -H "If-Modified-Since: Wed, 24 Jun 2015 20:28:15 GMT" ...
----
====

使用这个简单的命令，您要求仅在此时才更改资源。如果是这样，您将得到一个修改后的  `Last-Modified`  头来更新客户端。如果没有，您将收到HTTP  `304 Not Modified`  状态码。

header 格式完美，可以发送给将来的查询。

WARNING: 不要混合和匹配 header 与不同的查询。结果可能是灾难性的。当您请求完全相同的 URI 和参数时，只能使用 header 值。

[[headers.better-client-architecture]]
== 建立一个更有效率的前端

`ETags` 与 `If-Match` 和 `If-None-Match` header 相结合，使您能够构建对消费者的数据规划和存活时间更长，更加友好的前端。

. 确定需要锁定的实体并添加版本属性。
+
HTML5 很好地支持 `data-*` 属性, 因此将其存储在DOM中，例如 `data-etag` 属性。
. 识别可以跟踪最近的更新.。获取这些资源时，请将  `Last-Modified` 存储在DOM（`data-last-modified` ）中。
. 在获取资源时，也可以将  `self` URI插入DOM节点（也许是 `data-uri` 或 `data-self`），因此很容易返回资源。
. 调整 `PUT`/`PATCH`/`DELETE` 操作以使用 `If-Match` 并处理 HTTP `412 Precondition Failed` 状态码.
. 调整 `GET` 操作以使用 `If-None-Match` 和 `If-Modified-Since` 并处理 HTTP `304 Not Modified` 状态码.

通过将 `ETags` 和 `Last-Modified` 值嵌入到您的 DOM 中（或者可能在本地移动应用程序的其他位置），您可以通过不再检索相同的东西来减少数据/流量的消耗。您还可以避免与其他客户端冲突，而应在需要调和差异时收到警报。

因此，只要稍微调整您的前端和一些实体编辑，后端就可以提供对时间敏感的详细信息，您可以在建立客户友好型客户时从中获利。
