[[paging-and-sorting]]
= 分页和排序

本部分记录了 Spring Data REST 对 Spring Data Repository 分页和排序抽象的用法。 要熟悉这些功能，请参阅 Spring Data 您正在使用的 Repository 实现的文档（例如 Spring Data JPA）。

== 分页

而不是从大型结果集中返回所有内容，Spring Data REST 会识别一些会影响页面大小和起始页码的 URL 参数。

如果扩展  `PagingAndSortingRepository<T, ID>`  并访问所有实体的列表，则将获得指向前 20 个实体的链接。 要将页面大小设置为任何其他数字，请添加 `size` 参数，如下所示：


====
----
http://localhost:8080/people/?size=5
----
====

前面的示例将页面大小设置为 5。

要在您自己的查询方法中使用分页，您需要更改方法签名以接受其他 `Pageable` 参数并返回 `Page` 而不是 `List`。 例如，暴露以下查询方法 `/people/search/nameStartsWith`  并支持分页：

====
[source,java]
----
@RestResource(path = "nameStartsWith", rel = "nameStartsWith")
public Page findByNameStartsWith(@Param("name") String name, Pageable p);
----
====

Spring Data REST 导出器可以识别返回的 `Page`，并在响应的正文中为您提供结果，就像在非分页的响应中一样，但是会将其他链接添加到资源中以表示数据的前一页和后一页。

[[paging-and-sorting.prev-and-next-links]]
=== 上一个和下一个链接

每个分页的响应都使用 IANA 定义的链接关系 https://www.w3.org/TR/html5/links.html#link-type-prev[`prev`]  和 https://www.w3.org/TR/html5/links.html#link-type-next[`next`]，根据当前页面返回到结果的前一页和后一页的链接。
但是，如果您当前位于结果的第一页，则不会显示上一个链接。 对于结果的最后一页，不会显示下一个链接。

考虑以下示例，其中我们将页面大小设置为 5：

====
----
curl localhost:8080/people?size=5
----
====

====
[source,javascript]
----
{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/persons{&sort,page,size}", <1>
      "templated" : true
    },
    "next" : {
      "href" : "http://localhost:8080/persons?page=1&size=5{&sort}", <2>
      "templated" : true
    }
  },
  "_embedded" : {
  	... data ...
  },
  "page" : { <3>
    "size" : 5,
    "totalElements" : 50,
    "totalPages" : 10,
    "number" : 0
  }
}
----

在顶部，我们看到 `_links`:

<1> `self` 链接通过一些选项为整个集合提供服务。
<2> `next` 链接指向下一页，假设页面大小相同。
<3> 底部是有关页面设置的额外数据，包括页面大小，元素总数，页面总数和当前正在查看的页面号。
====

NOTE: 在命令行上使用诸如 `curl` 之类的工具时，如果语句中有 `＆` 号，则需要将整个 URI 括在引号中。

注意，`self` 和 `next` URI实际上是 URI 模板。 它们不仅接受  `size`，还接受 `page` 和  `sort` 作为可选标志。

如前所述，HAL 文档的底部包括有关该页面的详细信息的集合。 这些额外的信息使您可以轻松配置UI工具（例如滑块或指示器），以反映用户查看数据时的总体位置。 例如，前面示例中的文档显示我们正在查看第一页（页码从0开始）。

以下示例显示了当我们点击  `next`  链接时会发生什么：

====
----
$ curl "http://localhost:8080/persons?page=1&size=5"
----
====

====
[source,javascript]
----
{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/persons{&sort,projection,page,size}",
      "templated" : true
    },
    "next" : {
      "href" : "http://localhost:8080/persons?page=2&size=5{&sort,projection}", <1>
      "templated" : true
    },
    "prev" : {
      "href" : "http://localhost:8080/persons?page=0&size=5{&sort,projection}", <2>
      "templated" : true
    }
  },
  "_embedded" : {
	... data ...
  },
  "page" : {
    "size" : 5,
    "totalElements" : 50,
    "totalPages" : 10,
    "number" : 1 <3>
  }
}
----

除了以下区别外，这看起来非常相似：

<1> 现在，`next`  链接指向另一个页面，指示其相对于  `self`  链接的相对角度。
<2> 现在会出现一个 `prev`  链接，为我们提供了上一页的路径。
<3> 现在，当前数字为1（表示第二页）。
====

此功能使您可以将屏幕上的可选按钮映射到这些超媒体控件，从而使您可以实现UI体验的导航功能，而不必对 URI 进行硬编码。 实际上，可以授权用户从页面大小列表中进行选择，动态更改所提供的内容，而不必重写顶部或底部的 `next` 和 `prev` 控件。

[[paging-and-sorting.sorting]]
== 排序

Spring Data REST 可以识别使用存储库排序支持的排序参数。

若要对特定属性进行结果排序，请在 URL 添加一个 `sort` 参数，并在其中添加要对结果进行排序的属性的名称。 您可以通过在属性名称后加上逗号（`,`）或 `asc` 或 `desc` 来控制排序的方向。
以下将对所有名称以字母 "`K`" 开头的 `Person` 实体，使用在 `PersonRepository` 上定义的 `findByNameStartsWith` 查询方法，并添加对结果进行排序的排序数据，该排序数据在 `name` 属性上按降序排列：

====
----
curl -v "http://localhost:8080/people/search/nameStartsWith?name=K&sort=name,desc"
----
====

要通过多个属性对结果进行排序，请根据需要继续添加尽可能多的  `sort=PROPERTY`  参数。 将它们在查询字符串中出现的顺序添加到 `Pageable` 中。 结果可以通过顶级和嵌套属性进行排序。使用属性路径表示法表达嵌套的排序属性。不支持按可链接关联排序（即资源到顶级资源）。