[[projections-excerpts]]
= 投影和摘录

Spring Data REST 提供了暴露你的的实体的默认视图.  但是，有时出于各种原因，您可能需要更改该实体的视图.  本节介绍如何定义投影和摘录，以提供简化和缩小的资源视图.

[[projections-excerpts.projections]]
== 投影

请考虑以下实体模型:

====
[source,java]
----
@Entity
public class Person {

  @Id @GeneratedValue
  private Long id;
  private String firstName, lastName;

  @OneToOne
  private Address address;
  …
}
----
====

`Person` 对象有以下几个属性

* `id` 主键
* `firstName` 和 `lastName` 是实体属性.
* `address` 指向另一个实体模型.

假设我们创建一个相应的存储库，如下所示:

====
[source,java]
----
interface PersonRepository extends CrudRepository<Person, Long> {}
----
====

默认情况下，Spring Data REST 暴露该实体对象的所有属性.  `firstName` 和 `lastName` 被当作实体的基本属性.  关于 `address` 属性有两个选项.  一种选择是为 `Address` 对象定义一个存储库，如下所示:

====
[source,java]
----
interface AddressRepository extends CrudRepository<Address, Long> {}
----
====

在这种情况下， `Person`  资源将 `address`  属性作为 `URI` 呈现给其对应的 `Address`  资源.  如果我们要在系统中查找  "`Frodo`" i，则可以期望看到这样的 HAL 文档:

====
[source,javascript]
----
{
  "firstName" : "Frodo",
  "lastName" : "Baggins",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/persons/1"
    },
    "address" : {
      "href" : "http://localhost:8080/persons/1/address"
    }
  }
}
----
====

还有另一种方式.  如果 `Address` 实体对象没有定义自己的存储库，则 Spring Data REST 会在 `Person` 资源内包括数据字段，如以下示例所示:

====
[source,javascript]
----
{
  "firstName" : "Frodo",
  "lastName" : "Baggins",
  "address" : {
    "street": "Bag End",
    "state": "The Shire",
    "country": "Middle Earth"
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/persons/1"
    }
  }
}
----
====

但是，如果您根本不想要 `address` 详细信息怎么办?  同样，默认情况下，Spring Data REST 暴露其所有属性 (`id` 除外) .  您可以通过定义一个或多个投影来为 REST 服务的使用者提供一种替代方法.  以下示例显示了不包含地址的投影:

====
[source,java]
----
@Projection(name = "noAddresses", types = { Person.class }) <1>
interface NoAddresses { <2>

  String getFirstName(); <3>

  String getLastName(); <4>
}
----

<1> ``@Projection` 注解将其标记为投影.  `name` 属性提供了投影的名称，我们将在稍后详细介绍.   `types` 属性将此投影定位为仅应用于 `Person` 对象.
<2> 它是一个声明性的Java接口.
<3> 暴露 `firstName`.
<4> 暴露 `lastName`.
====

`NoAddresses` 投影仅具有 `firstName` 和 `lastName` 的 getters，这意味着它不提供任何地址信息.  假设您有一个单独的  `Address` 资源存储库，Spring Data REST 的默认视图与先前的表示形式略有不同，如以下示例所示:

====
[source,javascript]
----
{
  "firstName" : "Frodo",
  "lastName" : "Baggins",
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/persons/1{?projection}", <1>
      "templated" : true <2>
    },
    "address" : {
      "href" : "http://localhost:8080/persons/1/address"
    }
  }
}
----

<1> 此资源有一个新选项: `{?projection}`.
<2> `self` URI是URI模板. .
====

要查看对资源的投影，请查找  `http://localhost:8080/persons/1?projection=noAddresses`.

NOTE: 提供给 `projection` 查询参数的值与 `@Projection(name = "noAddress")` 中指定的值相同. 它与投影接口的名称无关.

您可以有多个投影.

NOTE: 请参阅  <<spring-data-examples.projections>> 以查看示例项目.  我们鼓励您尝试一下.

Spring Data REST 如何找到投影定义?

* 与实体定义在相同的包 (或其中一个子包) 中找到的任何 `@Projection`  接口都会被注册.
* 您可以使用 `RepositoryRestConfiguration.getProjectionConfiguration().addProjection(…)` 手动注册投影.

无论哪种情况，投影接口都必须具有 `@Projection` 注解.

[[projections-excerpts.finding-projections]]
=== 查找现有投影

Spring Data REST 暴露了  <<metadata.alps>>  文档，这是一种微元数据格式. 请按照根资源公开的  `profile` 链接. 如果您向下导航至 `Person` 资源 (即 `/alps/persons`) 的ALPS文档，则可以找到有关 `Person` 资源的许多详细信息. 将列出投影以及关于 `GET` REST 转换的详细信息，如下所示:

====
[source,javascript]
----
{ …
  "id" : "get-person", <1>
  "name" : "person",
  "type" : "SAFE",
  "rt" : "#person-representation",
  "descriptors" : [ {
    "name" : "projection", <2>
    "doc" : {
      "value" : "The projection that shall be applied when rendering the response. Acceptable values available in nested descriptors.",
      "format" : "TEXT"
    },
    "type" : "SEMANTIC",
    "descriptors" : [ {
      "name" : "noAddresses", <3>
      "type" : "SEMANTIC",
      "descriptors" : [ {
        "name" : "firstName", <4>
        "type" : "SEMANTIC"
      }, {
        "name" : "lastName", <4>
        "type" : "SEMANTIC"
      } ]
    } ]
  } ]
},
…
----

<1> ALPS 文档的此部分显示有关 `GET` 和 `Person` 资源的详细信息.
<2> 这部分包含  `projection` 选项.
<3> 这部分包含 `noAddresses` 投影.
<4> 该投影提供的实际属性包括 `firstName` 和 `lastName`.
====

[NOTE]
====
如果满足以下条件，则可以选择定投影义并将其提供给客户使用:

* 标有  `@Projection` 注解，并和实体类在同一包 (或子包) 中
* 使用  `RepositoryRestConfiguration.getProjectionConfiguration().addProjection(…)`手动注册.
====

[[projections-excerpts.projections.hidden-data]]
=== 引入隐藏数据

到目前为止，在本节中，我们已经介绍了如何使用投影来减少提供给用户的信息.  投影也可以带来通常看不见的数据.  例如，Spring Data REST 会忽略使用 ``@JsonIgnore` 注解标记的字段或 getter 方法.  考虑以下实体对象:

====
[source,java]
----
@Entity
public class User {

	@Id @GeneratedValue
	private Long id;
	private String name;

	@JsonIgnore private String password; <1>

	private String[] roles;
  …
----

<1> Jackson 的 `@JsonIgnore` 用于防止将 `password` 字段序列化为JSON
====

前面示例中的 `User` 类可用于存储用户信息以及与 Spring Security 集成.  如果创建 `UserRepository`，将 `password` 字段暴露出去通常是不好的.  在前面的示例中，我们通过在  `password`  字段上应用 Jackson 的 ``@JsonIgnore` 来防止这种情况的发生.

NOTE: 如果 `@JsonIgnore` 位于相应字段的 getter 函数上，Jackson 也不会将该字段序列化为JSON.

然而，投影介绍了仍然服务于这一领域的能力. 可以创建如下投影:

====
[source,java]
----
@Projection(name = "passwords", types = { User.class })
interface PasswordProjection {

  String getPassword();
}
----
====

如果创建和使用这样的投影，它将侧面放置在 `User.password` 上的 ``@JsonIgnore` 指令.

If such a projection is created and used, it sidesteps the `@JsonIgnore` directive placed on `User.password`.

IMPORTANT: 这个例子可能看起来有点诡异，但是可以通过更丰富的实体模型和许多投影来意外泄露这些细节. 由于 Spring Data REST 无法辨别这些数据的敏感度，所以由开发人员来避免这种情况.

投影也可以生成虚拟数据.  假设您具有以下实体定义:

====
[source,java]
----
@Entity
public class Person {

  ...
  private String firstName;
  private String lastName;

  ...
}
----
====

您可以创建一个将前面示例中的两个数据字段组合在一起的投影，如下所示:

====
[source,java]
----
@Projection(name = "virtual", types = { Person.class })
public interface VirtualProjection {

  @Value("#{target.firstName} #{target.lastName}") <1>
  String getFullName();

}
----

<1> Spring的 `@Value` 注解可让您使用 SpEL 表达式，该表达式采用目标对象并将其 `firstName` 和 `lastName` 属性拼接在一起，以呈现只读的 `fullName`.
====

[[projections-excerpts.excerpts]]
== 摘录

摘录是自动应用于资源集合的投影.  例如，您可以按以下方式更改 `PersonRepository`:

====
[source,java]
----
@RepositoryRestResource(excerptProjection = NoAddresses.class)
interface PersonRepository extends CrudRepository<Person, Long> {}
----
====

在将 `Person` 资源嵌入到集合或相关资源中时，上述示例指示 Spring Data REST 使用 `NoAddresses` 投影.
摘录投影不会自动应用于单个资源，必须指明应用它们.  摘录投影主要是提供了集合数据的默认预览，但在获取单个资源时不提供.  请参阅 https://stackoverflow.com/questions/30220333/why-is-an-excerpt-projection-not-applied-automatically-for-a-spring-data-rest-it[为什么摘录投影不会自动应用于 Spring Data REST 单个资源? ]对此主题进行讨论.

除了更改默认视图外，摘录还有其他视图选项，如下一节所示.

[[projections-excerpts.excerpting-commonly-accessed-data]]
=== 摘录常用数据

组合实体对象时，会出现 REST 服务的常见情况.  例如， `Person` 信息存储在一个表中，而与其相关的 `Address` 存储在另一个表中.  默认情况下，Spring Data REST 将用户的 `address` 属性作为 URI 提供.  浏览器必须访问 URI 才能获取.
但是，这总会获取到一些额外的数据，那么摘录投影可以将这些额外的数据内联，从而为您节省了额外的 `GET`.  为此，您可以定义另一个摘录投影，如下所示:

====
[source,java]
----
@Projection(name = "inlineAddress", types = { Person.class }) <1>
interface InlineAddress {

  String getFirstName();

  String getLastName();

  Address getAddress(); <2>
}
----

<1> 名字为 `inlineAddress` 的投影
<2> 投影添加 `getAddress` 属性, 它返回  `Address` 字段.  在投影内部使用时，它将使信息内联.
====

您可以将其插入 `PersonRepository` 定义中，如下所示:

====
[source,java]
----
@RepositoryRestResource(excerptProjection = InlineAddress.class)
interface PersonRepository extends CrudRepository<Person, Long> {}
----
====

这样做会使 HAL 文档显示如下:

====
[source,javascript]
----
{
  "firstName" : "Frodo",
  "lastName" : "Baggins",
  "address" : { <1>
    "street": "Bag End",
    "state": "The Shire",
    "country": "Middle Earth"
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/persons/1"
    },
    "address" : { <2>
      "href" : "http://localhost:8080/persons/1/address"
    }
  }
}
----

<1> `address` 数据内联, 因此您无需浏览即可.
<2> 仍然提供到 `Address` 资源的链接，使其仍然可以导航到自己的资源.
====

注意，前面的示例是本章前面的示例的结合.  您可能需要通读它们，跟随进行到最后一个示例.

WARNING: 为存储库配置  `@RepositoryRestResource(excerptProjection=...)` 会更改默认行为.  如果您已经发布了版本，则可能对您的服务使用者造成重大更改.
