[[servlet-saml2-login]]
== SAML 2.0 Login

SAML 2.0登录名 `saml2Login()` 功能为应用程序提供了使用户能够通过使用其在SAML 2.0身份提供程序(Okta,ADFS等) 上的现有帐户登录到该应用程序的功能.

NOTE: SAML 2.0登录是通过使用 https://www.oasis-open.org/committees/download.php/35389/sstc-saml-profiles-errata-2.0-wd-06-diff.pdf#page=15[SAML 2 Profiles]中指定的 *Web浏览器SSOProfile* 来实现的.  目前,我们的实现仅限于简单的身份验证方案.

[[servlet-saml2-spring-security-history]]
=== Spring Security 对 SAML 2 的支持

自2009年以来,作为 https://github.com/spring-projects/spring-security-saml/tree/1e013b07a7772defd6a26fcfae187c9bf661ee8f#spring-saml[independent project]的SAML 2 Service Provider(SP a.k.a. 依赖方) 的支持就一直存在.
1.0.x分支仍在使用中,包括在 https://github.com/cloudfoundry/uaa[Cloud Foundry User Account and Authentication Server]中,在SP实现上,该分支还创建了基于SAML 2.0 Identity Provider的实现.  .

在2018年,我们尝试将 https://github.com/spring-projects/spring-security-saml#spring-saml[服务提供商和身份提供商]的更新实现为分别创建独立库.  经过认真,冗长的讨论,我们Spring Security团队决定停止这项工作.  尽管这项工作为该独立的1.0.x库创建了替代品,但我们并不认为应该在另一个库之上构建一个库.

相反,我们选择提供对SAML 2身份验证的框架支持,作为 https://github.com/spring-projects/spring-security[core Spring Security]的一部分.

[[servlet-saml2-login-concepts]]
=== Saml 2 Login - 高级概念

`saml2Login()`  旨在支持一部分 https://saml.xml.org/saml-specifications[SAML 2功能集],重点是作为身份验证方,即服务提供方SP,依赖方,从身份提供方(也称为声明方) 接收XML声明.

SAML 2登录或身份验证是SP接收并验证称为以下内容的XML消息的概念:
来自IDP的断言.

当前有两种支持的身份验证流程

1. IDP启动的流程-示例: 您直接登录Okta,然后选择要进行身份验证的Web应用程序.  Okta,IDP,将一个断言发送到Web应用程序SP.
2. SP发起的流程-示例: 您访问一个Web应用程序,一个SP,该应用程序将身份验证请求发送到IDP,以请求断言.  在IDP上成功身份验证后,IDP会向SP发送一个断言.

[[servlet-saml2-login-feature-set]]
=== Saml 2 Login - 当前功能集

1. 服务提供者(SP/依赖方) 由 `entityId = {baseUrl}/saml2/service-provider-metadata/{registrationId}` 标识
2. 通过 `{baseUrl}/login/saml2/sso/{registrationId}` 上的Http-POST或Http-Redirect接收嵌入在SAML响应中的断言
3. 要求对断言进行签名,除非响应已签名
4. 支持加密的断言
5. 支持加密的NameId元素
6. 允许使用 `Converter<Assertion, Collection<? extends GrantedAuthority>>`
7. 允许使用 `GrantedAuthoritiesMapper` 映射和授权的白名单
8. 公钥,格式为 `java.security.cert.X509Certificate` format.
9. SP通过 `AuthNRequest` 发起的身份验证

[[servlet-saml2-login-tbd]]
==== Saml 2 Login - 尚不支持

1. 将断言条件和属性映射到会话功能(超时,跟踪等)
2. 单点注销
3. 动态元数据生成
4. 接收和验证独立断言(未包装在响应对象中)

[[servlet-saml2-javaconfig]]
=== Saml 2 Login - Java配置简介

要将 `saml2Login()` 添加到Spring Security过滤器链,最小的Java配置需要配置存储库 `RelyingPartyRegistrationRepository`,其中包含SAML配置和 `HttpSecurity.saml2Login()` 方法的调用:

[source,java]
----
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Bean
    public RelyingPartyRegistrationRepository relyingPartyRegistrationRepository() {
        //SAML configuration
        //Mapping this application to one or more Identity Providers
        return new InMemoryRelyingPartyRegistrationRepository(...);
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .authorizeRequests(authorize -> authorize
                .anyRequest().authenticated()
            )
            .saml2Login(withDefaults())
        ;
    }
}
----

bean声明是一种方便但可选的方法.
您可以使用方法调用直接连接存储库

[source,java]
----
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
            .authorizeRequests(authorize -> authorize
                .anyRequest().authenticated()
            )
            .saml2Login(saml2 -> saml2
                .relyingPartyRegistrationRepository(...)
            )
        ;
    }
}
----

[[servlet-saml2-relyingpartyregistration]]
==== RelyingPartyRegistration
The https://github.com/spring-projects/spring-security/blob/5.2.0.RELEASE/saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistration.java[`RelyingPartyRegistration`]
对象表示此应用程序SP和声明方IDP之间的映射.

[[servlet-saml2-rpr-uripatterns]]
===== URI模式

URI模式经常用于根据以下内容自动生成URI:
传入请求.  `saml2 Login` 中的URI模式可以包含以下变量

* `baseUrl`
* `registrationId`
* `baseScheme`
* `baseHost`
* `basePort`

For example:
```
{baseUrl}/login/saml2/sso/{registrationId}
```

[[servlet-saml2-rpr-relyingparty]]
===== 依赖方


* `registrationId` - (必需) 此配置映射的唯一标识符.  该标识符可以在URI路径中使用,因此应注意不需要URI编码.
* `localEntityIdTemplate` - (可选) 一个URI模式,它根据传入的请求为此应用程序创建一个实体ID.  默认值为 `{baseUrl}/saml2/service-provider-metadata/{registrationId}`,对于小型示例应用程序,它看起来像

```
http://localhost:8080/saml2/service-provider-metadata/my-test-configuration
```
不需要此配置选项是一种模式,它可以是固定的URI值.

* `remoteIdpEntityId` - (必需) 身份提供者的实体ID.  始终是固定的URI值或字符串, 不允许使用任何模式.
* `assertionConsumerServiceUrlTemplate` - (可选) 一个URI模式,它表示在SP启动流程期间要与任何 `AuthNRequest` 从SP发送到IDP的断言使用者服务URI.  尽管这可能是一种模式,但实际的URI必须解析为SP上的ACS端点.  默认值为  `{baseUrl}/login/saml2/sso/{registrationId}` ,并直接映射到 https://github.com/spring-projects/spring-security/blob/5.2.0.RELEASE/saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/servlet/filter/Saml2WebSsoAuthenticationFilter.java#L42[`Saml2WebSsoAuthenticationFilter`] 端点
* `idpWebSsoUrl`  - (必需) 用于SP发送 `AuthNRequest` 消息的IDP单一登录端点的固定URI值.
* `credentials` - 凭证,私钥和x509证书的列表,用于 消息签名,验证,加密和解密.  该列表可以包含冗余凭据,以便轻松回转凭据.  例如
** [0] - X509Certificate{VERIFICATION,ENCRYPTION} - IDP的第一个公钥用于 验证和加密.
** [1] - X509Certificate/{VERIFICATION,ENCRYPTION} - IDP的第二个验证密钥用于验证.  始终使用列表中的第一个 `ENCRYPTION` 密钥进行加密.
** [2] - PrivateKey/X509Certificate{SIGNING,DECRYPTION} - SP的第一个签名和解密凭据.
** [3] - PrivateKey/X509Certificate{SIGNING,DECRYPTION} - SP的第二个解密凭据.  始终使用列表中的第一个 `SIGNING` 键进行签名.

收到传入消息时,始终需要签名,系统将首先尝试
使用索引[0]处的证书来验证签名,并且仅移至第二个
如果第一个失败,则为凭据.

以类似的方式,将SP配置的私钥用于解密并以相同的顺序尝试.
当对IDP的消息进行签名时,将使用第一个SP凭据 (`type=SIGNING`) .

[[servlet-saml2-rpr-duplicated]]
===== 重复的依赖方配置

在应用程序使用多个身份提供者的用例中,它变为
显然,在两个 `RelyingPartyRegistration` 对象之间重复了一些配置

* localEntityIdTemplate
* credentials (all SP credentials, IDP credentials change)
* assertionConsumerServiceUrlTemplate

尽管复制配置值有一些缺点,但后端配置存储库不需要复制此数据存储模型.

此设置附带一个好处.  与某些身份提供者相比,某些身份提供者的凭据更容易轮换.  该对象模型可以确保在多IDP用例中更改配置时不会中断,并且您不能在所有身份提供者上轮换使用凭据.

[[servlet-saml2-serviceprovider-metadata]]
==== 服务提供商元数据

Spring Security SAML 2实现尚未提供下载端点
XML格式的SP元数据.  最小的配置

* *entity ID* - 默认为 `{baseUrl}/saml2/service-provider-metadata/{registrationId}` 其他也使用相同值的已知配置名称
** Audience Restriction
* *single signon URL* - 默认为 `{baseUrl}/login/saml2/sso/{registrationId}` 其他也使用相同值的已知配置名称
** Recipient URL
** Destination URL
** Assertion Consumer Service URL
* X509Certificate - 您在{SIGNING,DECRYPTION}中配置的证书 凭据必须与身份提供者共享

[[servlet-saml2-sp-initiated]]
==== 身份验证请求 - SP启动的流程

要从Web应用程序启动身份验证,只需重定向到
```
{baseUrl}/saml2/authenticate/{registrationId}
```

根据您的 `RelyingPartyRegistration`，此端点将生成 `AuthNRequest` 作为重定向或 POST 路径。

[[servlet-saml2-sp-initiated-factory]]
==== Customizing the AuthNRequest

要调整 `AuthNRequest`，您可以发布 `Saml2AuthenticationRequestFactory` 的实例。

例如，如果您想配置 `AuthNRequest` 以请求 IDP 通过 REDIRECT 发送 SAML 声明，则可以执行以下操作：

[source,java]
----
@Bean
public Saml2AuthenticationRequestFactory authenticationRequestFactory() {
    OpenSamlAuthenticationRequestFactory authenticationRequestFactory =
        new OpenSamlAuthenticationRequestFactory();
    authenticationRequestFactory.setProtocolBinding("urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect");
    return authenticationRequestFactory;
}
----

[[servlet-saml2-sp-initiated-factory-delegate]]
==== 委托给 AuthenticationRequestFactory

或者，在需要更多控制作为参数发送到 `AuthenticationRequestFactory` 的内容的情况下，可以使用委托：

[source,java]
----
@Component
public class IssuerSaml2AuthenticationRequestFactory implements Saml2AuthenticationRequestFactory {
	private OpenSamlAuthenticationRequestFactory delegate = new OpenSamlAuthenticationRequestFactory();

	@Override
	public String createAuthenticationRequest(Saml2AuthenticationRequest request) {
		return this.delegate.createAuthenticationRequest(request);
	}

	@Override
    public Saml2PostAuthenticationRequest createPostAuthenticationRequest
        (Saml2AuthenticationRequestContext context) {

		String issuer = // ... calculate issuer

		Saml2AuthenticationRequestContext customIssuer = Saml2AuthenticationRequestContext.builder()
                .assertionConsumerServiceUrl(context.getAssertionConsumerServiceUrl())
                .issuer(issuer)
                .relayState(context.getRelayState())
                .relyingPartyRegistration(context.getRelyingPartyRegistration())
                .build();

		return this.delegate.createPostAuthenticationRequest(customIssuer);
	}

	@Override
    public Saml2RedirectAuthenticationRequest createRedirectAuthenticationRequest
        (Saml2AuthenticationRequestContext context) {

		throw new UnsupportedOperationException("unsupported");
	}
}
----

[[servlet-saml2-login-customize]]
=== 自定义身份验证逻辑

默认情况下,Spring Security将 `OpenSamlAuthenticationProvider` 配置为验证和解析接收到的SAML 2响应和断言.  该提供程序具有三个配置选项

1. 权限提取器 - 从断言中提取组信息
2. 权限映射器 - 将提取的组信息映射到内部权限
3. 响应时间验证持续时间 - 可能存在时间同步问题时,应使用时间戳验证的内置公差.

一种自定义策略是使用 `ObjectPostProcessor`,它允许您修改实现创建的对象.  另一个选择是为拦截SAMLResponse的过滤器覆盖身份验证管理器.

[[servlet-saml2-opensamlauthenticationprovider]]
==== OpenSamlAuthenticationProvider ObjectPostProcessor

[source,java]
----
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        ObjectPostProcessor<OpenSamlAuthenticationProvider> processor = new ObjectPostProcessor<>() {
            @Override
            public <O extends OpenSamlAuthenticationProvider> O postProcess(O provider) {
                provider.setResponseTimeValidationSkew(RESPONSE_TIME_VALIDATION_SKEW);
                provider.setAuthoritiesMapper(AUTHORITIES_MAPPER);
                provider.setAuthoritiesExtractor(AUTHORITIES_EXTRACTOR);
                return provider;
            }
        };

        http
            .authorizeRequests(authorize -> authorize
                .anyRequest().authenticated()
            )
            .saml2Login(saml2 -> saml2
               .addObjectPostProcessor(processor)
            )
        ;
    }
}
----

[[servlet-saml2-opensamlauthenticationprovider-authenticationmanager]]
==== 将OpenSamlAuthenticationProvider配置为身份验证管理器
我们可以利用相同的方法 `authenticationManager` 来覆盖和自定义默认的 `OpenSamlAuthenticationProvider`.

[source,java]
----
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        OpenSamlAuthenticationProvider authProvider = new OpenSamlAuthenticationProvider();
        authProvider.setResponseTimeValidationSkew(RESPONSE_TIME_VALIDATION_SKEW);
        authProvider.setAuthoritiesMapper(AUTHORITIES_MAPPER);
        authProvider.setAuthoritiesExtractor(AUTHORITIES_EXTRACTOR);
        http
            .authorizeRequests(authorize -> authorize
                .anyRequest().authenticated()
            )
            .saml2Login(saml2 -> saml2
                .authenticationManager(new ProviderManager(asList(authProvider)))
            )
        ;
    }
}
----

[[servlet-saml2-custom-authenticationmanager]]
==== 自定义身份验证管理器
还可以使用您自己的自定义 `AuthenticationManager` 实现覆盖安全过滤器的身份验证管理器.  该身份验证管理器应期望包含SAML 2响应XML数据的 `Saml2AuthenticationToken` 对象.

[source,java]
----
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        AuthenticationManager authenticationManager = new MySaml2AuthenticationManager(...);
        http
            .authorizeRequests(authorize -> authorize
                .anyRequest().authenticated()
            )
            .saml2Login(saml2 -> saml2
                .authenticationManager(authenticationManager)
            )
        ;
    }
}
----

[[servlet-saml2-sample-boot]]
=== Spring Boot 2.x 示例

我们目前正在与Spring Boot团队合作进行 https://github.com/spring-projects/spring-boot/issues/18260[Spring Security SAML登录的自动配置].  同时,我们提供了一个支持Yaml配置的Spring Boot示例.

若要运行该示例,请按照以下三个步骤

1. 启动Spring Boot应用程序
** `./gradlew :spring-security-samples-boot-saml2login:bootRun`
2. 打开浏览器
** http://localhost:8080/[http://localhost:8080/]
3. 这将带您到身份提供者,使用以下方式登录:
** User: `user`
** Password: `password`

[[servlet-saml2-sample-idps]]
==== 多身份提供者示例

使用多个提供程序非常简单,但是如果您不注意,会有一些默认设置可能会使您失望.  在 `RelyingPartyRegistration` 对象的SAML配置中,我们默认将SP实体ID设置为

`+{baseUrl}/saml2/service-provider-metadata/{registrationId}+`

这意味着在我们的两个提供程序配置中,我们的系统看起来像

```
registration-1 (Identity Provider 1) - Our local SP Entity ID is:
http://localhost:8080/saml2/service-provider-metadata/registration-1

registration-2 (Identity Provider 2) - Our local SP Entity ID is:
http://localhost:8080/saml2/service-provider-metadata/registration-2
```

在此配置中(如下例所示) ,我们实际上已经创建了两个虚拟服务提供商标识,托管在同一应用程序中.

[source,yaml]
----
spring:
  security:
    saml2:
      login:
        relying-parties:
          - entity-id: &idp-entity-id https://simplesaml-for-spring-saml.cfapps.io/saml2/idp/metadata.php
            registration-id: simplesamlphp
            web-sso-url: &idp-sso-url https://simplesaml-for-spring-saml.cfapps.io/saml2/idp/SSOService.php
            signing-credentials: &service-provider-credentials
              - private-key: |
                  -----BEGIN PRIVATE KEY-----
                  MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBANG7v8QjQGU3MwQE
                  ...................SHORTENED FOR READ ABILITY...................
                  INrtuLp4YHbgk1mi
                  -----END PRIVATE KEY-----
                certificate: |
                  -----BEGIN CERTIFICATE-----
                  MIICgTCCAeoCCQCuVzyqFgMSyDANBgkqhkiG9w0BAQsFADCBhDELMAkGA1UEBhMC
                  ...................SHORTENED FOR READ ABILITY...................
                  RZ/nbTJ7VTeZOSyRoVn5XHhpuJ0B
                  -----END CERTIFICATE-----
            verification-credentials: &idp-certificates
              - |
                -----BEGIN CERTIFICATE-----
                MIIEEzCCAvugAwIBAgIJAIc1qzLrv+5nMA0GCSqGSIb3DQEBCwUAMIGfMQswCQYD
                ...................SHORTENED FOR READ ABILITY...................
                lx13Y1YlQ4/tlpgTgfIJxKV6nyPiLoK0nywbMd+vpAirDt2Oc+hk
                -----END CERTIFICATE-----
          - entity-id: *idp-entity-id
            registration-id: simplesamlphp2
            web-sso-url: *idp-sso-url
            signing-credentials: *service-provider-credentials
            verification-credentials: *idp-certificates
----

如果不希望这样做,则可以使用以下命令手动覆盖本地SP实体ID:

[source,attrs="-attributes"]
----
localEntityIdTemplate = {baseUrl}/saml2/service-provider-metadata
----

如果我们将本地SP实体ID更改为该值,则仍然非常重要的是,我们应根据注册ID为每个注册的身份提供者提供正确的单一URL URL(断言消费者服务URL) .  `{baseUrl}/login/saml2/sso/{registrationId}`



