[[build-tool-plugins.antlib]]
== Spring Boot AntLib 模块
Spring Boot AntLib 模块为 Apache Ant 提供了基本的 Spring Boot 支持. 您可以使用该模块创建可执行 jar. 要使用该模块,您需要在中声明一个额外的 `spring-boot` 命名空间 `build.xml`,如以下示例所示:

[source,xml,indent=0,subs="verbatim"]
----
	<project xmlns:ivy="antlib:org.apache.ivy.ant"
		xmlns:spring-boot="antlib:org.springframework.boot.ant"
		name="myapp" default="build">
		...
	</project>
----

您需要记住使用该 `-lib` 选项启动 Ant ,如以下示例所示:

[source,shell,indent=0,subs="verbatim,attributes"]
----
	$ ant -lib <directory containing spring-boot-antlib-{spring-boot-version}.jar>
----

TIP: 使用 Spring Boot 部分包含将 Apache Ant 与结合 <<using#using.build-systems.ant, 使用 `spring-boot-antlib` 的更完整示例>>.

[[build-tool-plugins.antlib.tasks]]
=== Spring Boot Ant 任务
一旦 `spring-boot-antlib` 命名空间已申报,以下附加任务:

* <<build-tool-plugins#build-tool-plugins.antlib.tasks.exejar>>
* <<build-tool-plugins#build-tool-plugins.antlib.findmainclass>>

[[build-tool-plugins.antlib.tasks.exejar]]
==== 使用 "`exejar`" Task
您可以使用该 `exejar` 任务创建一个 Spring Boot 可执行 jar. 任务支持以下属性:

[cols="1,2,2"]
|====
| 属性 | 描述 | 是否需要

| `destfile`
| 要创建的目标 jar 文件
| Yes

| `classes`
| Java 类文件的根目录
| Yes

| `start-class`
| 要运行的主要应用程序类
| No _(否 (默认为找到的第一个声明 `main` 方法的类) )_
|====

以下嵌套元素可用于任务:

[cols="1,4"]
|====
| 元素 | 描述

| `resources`
| 一个或多个 {ant-docs}/Types/resources.html#collection[资源集合],描述应添加到创建的 jar 文件内容中的一组 {ant-docs}/Types/resources.html[Resources] .

| `lib`
| 应将一个或多个 {ant-docs}/Types/resources.html#collection[资源集合] 添加到组成应用程序运行时依赖类路径的 jar 库集合中.
|====

[[build-tool-plugins.antlib.tasks.examples]]
==== 例子
本节显示了两个 Ant 任务示例.

.Specify +start-class+
[source,xml,indent=0,subs="verbatim"]
----
	<spring-boot:exejar destfile="target/my-application.jar"
			classes="target/classes" start-class="com.example.MyApplication">
		<resources>
			<fileset dir="src/main/resources" />
		</resources>
		<lib>
			<fileset dir="lib" />
		</lib>
	</spring-boot:exejar>
----

.Detect +start-class+
[source,xml,indent=0,subs="verbatim"]
----
	<exejar destfile="target/my-application.jar" classes="target/classes">
		<lib>
			<fileset dir="lib" />
		</lib>
	</exejar>
----



[[build-tool-plugins.antlib.findmainclass]]
=== 使用 "`findmainclass`" Task
该 `findmainclass` 任务在内部 `exejar` 用于查找声明的类 `main`. 如有必要,您也可以在构建中直接使用此任务. 支持以下属性:

[cols="1,2,2"]
|====
| 属性 | 描述 | 是否需要

| `classesroot`
| Java 类文件的根目录
| Yes _(除非 `mainclass` 指定)_

| `mainclass`
| 可用于短路 `main` class 搜索
| No

| `property`
| 应该与结果一起设置的Ant属性
| No _(如果未指定,将记录结果)_
|====

[[build-tool-plugins.antlib.findmainclass.examples]]
==== 例子
本节包含三个使用 `findmainclass` 的示例。

.Find and log
[source,xml,indent=0,subs="verbatim"]
----
	<findmainclass classesroot="target/classes" />
----

.Find and set
[source,xml,indent=0,subs="verbatim"]
----
	<findmainclass classesroot="target/classes" property="main-class" />
----

.Override and set
[source,xml,indent=0,subs="verbatim"]
----
	<findmainclass mainclass="com.example.MainClass" property="main-class" />
----
