[[build-tool-plugins.other-build-systems]]
== 支持其他构建系统
如果要使用 Maven,Gradle 或 Ant 以外的构建工具,则可能需要开发自己的插件. 可执行的 jar 需要遵循特定的格式,某些条目需要以未压缩的形式编写 (有关详细信息,请参见附录中的 "`<<executable-jar#appendix.executable-jar, 可执行 jar 格式>>`" 部分) .

Spring Boot Maven 和 Gradle 插件都利用它们 `spring-boot-loader-tools` 来生成 jar. 如果需要,可以直接使用此库.

[[build-tool-plugins.other-build-systems.repackaging-archives]]
=== 重新打包 Archives
要重新打包现有构件,使其成为独立的可执行构件,请使用 `org.springframework.boot.loader.tools.Repackager`. 该 `Repackager` class 采取的是指现有的 jar 或 war archive 单个构造函数的参数.
使用两种可用 `repackage()` 方法之一替换原始文件或写入新目标. 在重新打包程序运行之前,还可以对其进行各种设置.

[[build-tool-plugins.other-build-systems.nested-libraries]]
=== 嵌套库
重新打包 存档 时,可以使用该 `org.springframework.boot.loader.tools.Libraries` 接口包括对依赖文件的引用. 我们 `Libraries` 这里不提供任何具体的实现,因为它们通常是特定于构建系统的.

如果归档文件中已经包含库,则可以使用 `Libraries.NONE`.

[[build-tool-plugins.other-build-systems.finding-main-class]]
=== 查找 Main Class
如果您不用于 `Repackager.setMainClass()` 指定主类,则重新包装器将使用 https://asm.ow2.io/[ASM] 读取类文件,并尝试使用一种  `public static void main(String[] args)` 方法找到合适的类. 如果找到多个候选者,则会引发异常.


[[build-tool-plugins.other-build-systems.example-repackage-implementation]]
=== 重新打包示例实现
以下示例显示了典型的重新打包实现:

include::code:MyBuildTool[]
