[[redis.repositories]]
= Redis 存储库

通过使用 Redis 存储库,您可以无缝地在 Redis 哈希中转换和存储域对象,应用自定义映射策略以及使用二级索引.

IMPORTANT: Redis存储库至少需要 Redis Server 版本2.8.0,并且不适用于事务. 确保使用的 `RedisTemplate` <<tx.spring,禁用了事务支持>>.

[[redis.repositories.usage]]
== 使用

Spring Data Redis 使您可以轻松实现域实体,如以下示例所示:

.Sample Person Entity
====
[source,java]
----
@RedisHash("people")
public class Person {

  @Id String id;
  String firstname;
  String lastname;
  Address address;
}
----
====

我们在这里有一个非常简单的域对象. 请注意,它的类型上带有 `@RedisHash` 批注,并带有 `org.springframework.data.annotation.Id` 批注的名为 `id` 的属性. 这两个选项负责创建实际的 key.

NOTE: 用 `@Id` 注释的属性以及名为 `id` 的属性被视为标识符属性.

现在要真正拥有负责存储和检索的组件,我们需要定义一个存储库接口,如以下示例所示:

.Basic Repository Interface To Persist Person Entities
====
[source,java]
----
public interface PersonRepository extends CrudRepository<Person, String> {

}
----
====

随着我们的存储库扩展 `CrudRepository`,它提供了基本的 CRUD 和 finder 操作.我们需要将它们粘合在一起的是对应的 Spring 配置,如以下示例所示:

.JavaConfig for Redis Repositories
====
[source,java]
----
@Configuration
@EnableRedisRepositories
public class ApplicationConfig {

  @Bean
  public RedisConnectionFactory connectionFactory() {
    return new JedisConnectionFactory();
  }

  @Bean
  public RedisTemplate<?, ?> redisTemplate() {

    RedisTemplate<byte[], byte[]> template = new RedisTemplate<byte[], byte[]>();
    return template;
  }
}
----
====

给定前面的设置,我们可以将 `PersonRepository` 注入到我们的组件中,如以下示例所示:

.Access to Person Entities
====
[source,java]
----
@Autowired PersonRepository repo;

public void basicCrudOperations() {

  Person rand = new Person("rand", "al'thor");
  rand.setAddress(new Address("emond's field", "andor"));

  repo.save(rand);                                         <1>

  repo.findOne(rand.getId());                              <2>

  repo.count();                                            <3>

  repo.delete(rand);                                       <4>
}
----
<1> 如果当前值为 `null` 或已经存在 `id` 值,并在 Redis Hash 中存储类型为 Person 的属性,并使用  `keyspace:id` 的 key,则生成新的id:id-在这种情况下,可能是 `people:5d67b7e1-8640-4475-beeb-c666fab4c0e5`.
<2> 使用提供的 `ID` 在 `keyspace:id` 中搜索对象 .
<3> 计算 keyspace 可用的实体总数,由 `@RedisHash` 在 `Person` 上定义.
<4> 从Redis中删除给定对象的 key.
====

include::{spring-data-commons-docs}/object-mapping.adoc[leveloffset=+1]

[[redis.repositories.mapping]]
== 对象到哈希的映射

Redis 存储库支持将对象保留为哈希. 这需要由 `RedisConverter` 完成的对象到哈希的转换. 默认实现使用 `Converter` 将属性值与 Redis 本地 `byte[]` 之间进行映射.

给定前面几节中的 `Person` 类型,默认映射如下所示:

====
[source,text]
----
_class = org.example.Person                 <1>
id = e2c7dcee-b8cd-4424-883e-736ce564363e
firstname = rand                            <2>
lastname = al’thor
address.city = emond's field                <3>
address.country = andor
----
<1> `_class` 属性包含在根级别以及任何嵌套接口或抽象类型中.
<2> 简单属性值按路径映射.
<3> 复杂类型的属性按其点路径进行映射.
====

下表描述了默认映射规则:

[cols="1,2,3", options="header"]
.默认映射规则
|===
| Type
| Sample
| Mapped Value

| Simple Type +
(for example, String)
| String firstname = "rand";
| firstname = "rand"

| Complex Type +
(for example, Address)
| Address address = new Address("emond's field");
| address.city = "emond's field"

| List +
of Simple Type
| List<String> nicknames = asList("dragon reborn", "lews therin");
| nicknames.[0] = "dragon reborn", +
nicknames.[1] = "lews therin"

| Map +
of Simple Type
| Map<String, String> atts = asMap({"eye-color", "grey"}, {"...
| atts.[eye-color] = "grey", +
atts.[hair-color] = "...

| List +
of Complex Type
| List<Address> addresses = asList(new Address("em...
| addresses.[0].city = "emond's field", +
addresses.[1].city  = "...

| Map +
of Complex Type
| Map<String, Address> addresses = asMap({"home", new Address("em...
| addresses.[home].city = "emond's field", +
addresses.[work].city  = "...
|===

CAUTION: 由于采用平面表示结构,因此 `Map` 的 key 必须是简单的类型,例如 `String` 或 `Number`.

可以通过在 `RedisCustomConversions` 中注册相应的 `Converter` 来自定义映射行为. 这些转换器可以处理与单个 `byte[]` 和 `Map<String,byte[]>` 之间的转换.
第一个适用于(例如)将复杂类型转换为(例如)仍使用默认映射哈希结构的二进制JSON表示形式. 第二个选项提供对生成的哈希的完全控制.

WARNING: 将对象写入 Redis 哈希会删除哈希中的内容,并重新创建整个哈希,因此尚未映射的数据会丢失.

下面的示例显示了两个示例字节数组转换器:

.Sample byte[] Converters
====
[source,java]
----
@WritingConverter
public class AddressToBytesConverter implements Converter<Address, byte[]> {

  private final Jackson2JsonRedisSerializer<Address> serializer;

  public AddressToBytesConverter() {

    serializer = new Jackson2JsonRedisSerializer<Address>(Address.class);
    serializer.setObjectMapper(new ObjectMapper());
  }

  @Override
  public byte[] convert(Address value) {
    return serializer.serialize(value);
  }
}

@ReadingConverter
public class BytesToAddressConverter implements Converter<byte[], Address> {

  private final Jackson2JsonRedisSerializer<Address> serializer;

  public BytesToAddressConverter() {

    serializer = new Jackson2JsonRedisSerializer<Address>(Address.class);
    serializer.setObjectMapper(new ObjectMapper());
  }

  @Override
  public Address convert(byte[] value) {
    return serializer.deserialize(value);
  }
}
----
====

使用前面的字节数组 `Converter` 产生的输出类似于以下内容:
====
[source,text]
----
_class = org.example.Person
id = e2c7dcee-b8cd-4424-883e-736ce564363e
firstname = rand
lastname = al’thor
address = { city : "emond's field", country : "andor" }
----
====

以下示例显示了两个 `Map` 转换器示例:

.Sample Map<String,byte[]> Converters
====
[source,java]
----
@WritingConverter
public class AddressToMapConverter implements Converter<Address, Map<String,byte[]>> {

  @Override
  public Map<String,byte[]> convert(Address source) {
    return singletonMap("ciudad", source.getCity().getBytes());
  }
}

@ReadingConverter
public class MapToAddressConverter implements Converter<Address, Map<String, byte[]>> {

  @Override
  public Address convert(Map<String,byte[]> source) {
    return new Address(new String(source.get("ciudad")));
  }
}
----
====

使用前面的 Map `Converter` 产生的输出类似于以下内容:

====
[source,text]
----
_class = org.example.Person
id = e2c7dcee-b8cd-4424-883e-736ce564363e
firstname = rand
lastname = al’thor
ciudad = "emond's field"
----
====

NOTE: 自定义转换对索引解析没有影响. 即使对于自定义转换类型, <<redis.repositories.indexes>> 仍会创建.

=== 自定义类型映射

如果要避免将整个 Java 类名称写为类型信息,并且希望使用键,则可以在要保留的实体类上使用 `@TypeAlias` 批注. 如果您需要进一步自定义映射,请查看 https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/convert/TypeInformationMapper.html[`TypeInformationMapper`] 接口. 可以在 `DefaultRedisTypeMapper` 上配置该接口的实例,该实例可以在 `MappingRedisConverter` 上配置.

以下示例显示如何为实体定义类型别名:

.为实体定义 `@TypeAlias`
====
[source,java]
----
@TypeAlias("pers")
class Person {

}
----
====

生成的文档将 `pers` 作为 `_class` 字段中的值.

==== 配置自定义类型映射

以下示例演示如何在 `MappingRedisConverter` 中配置自定义 `RedisTypeMapper`:

.通过Spring Java Config配置自定义 `RedisTypeMapper`
====
[source,java]
----
class CustomRedisTypeMapper extends DefaultRedisTypeMapper {
  //implement custom type mapping here
}
----

[source,java]
----
@Configuration
class SampleRedisConfiguration {

  @Bean
  public MappingRedisConverter redisConverter(RedisMappingContext mappingContext,
        RedisCustomConversions customConversions, ReferenceResolver referenceResolver) {

    MappingRedisConverter mappingRedisConverter = new MappingRedisConverter(mappingContext, null, referenceResolver,
            customTypeMapper());

    mappingRedisConverter.setCustomConversions(customConversions);

    return mappingRedisConverter;
  }

  @Bean
  public RedisTypeMapper customTypeMapper() {
    return new CustomRedisTypeMapper();
  }
}
----
====

[[redis.repositories.keyspaces]]
== Keyspaces
Keyspaces 定义用于为 Redis 哈希创建实际 key 的前缀.

默认情况下,前缀设置为  `getClass().getName()`. 您可以通过在聚合根级别上设置 `@RedisHash` 或设置程序配置来更改此默认设置. 但是,带注释的 keyspaces 将取代任何其他配置.

下面的示例演示如何使用 `@EnableRedisRepositories` 批注设置密钥空间配置:

.通过 `@EnableRedisRepositories` 进行 Keyspaces 设置
====
[source,java]
----
@Configuration
@EnableRedisRepositories(keyspaceConfiguration = MyKeyspaceConfiguration.class)
public class ApplicationConfig {

  //... RedisConnectionFactory and RedisTemplate Bean definitions omitted

  public static class MyKeyspaceConfiguration extends KeyspaceConfiguration {

    @Override
    protected Iterable<KeyspaceSettings> initialConfiguration() {
      return Collections.singleton(new KeyspaceSettings(Person.class, "people"));
    }
  }
}
----
====

下面的示例演示如何以编程方式设置 keyspace:

.Programmatic Keyspace setup
====
[source,java]
----
@Configuration
@EnableRedisRepositories
public class ApplicationConfig {

  //... RedisConnectionFactory and RedisTemplate Bean definitions omitted

  @Bean
  public RedisMappingContext keyValueMappingContext() {
    return new RedisMappingContext(
      new MappingConfiguration(new IndexConfiguration(), new MyKeyspaceConfiguration()));
  }

  public static class MyKeyspaceConfiguration extends KeyspaceConfiguration {

    @Override
    protected Iterable<KeyspaceSettings> initialConfiguration() {
      return Collections.singleton(new KeyspaceSettings(Person.class, "people"));
    }
  }
}
----
====

[[redis.repositories.indexes]]
== 二级索引
https://redis.io/topics/indexes[二级索引] 用于启用基于 本地 Redis结构的查找操作. 每次保存时,值都会写入相应的索引,并在删除或  <<redis.repositories.expirations,过期>> 对象时将其删除..

[[redis.repositories.indexes.simple]]
=== 简单属性索引

给定前面显示的示例 `Person` 实体,我们可以通过使用 `@Indexed` 注释属性来为  `firstname` 创建索引,如以下示例所示:

.Annotation driven indexing
====
[source,java]
----
@RedisHash("people")
public class Person {

  @Id String id;
  @Indexed String firstname;
  String lastname;
  Address address;
}
----
====

为实际属性值建立索引. 保存两个人(例如,"rand" 和 "aviendha")会导致建立类似于以下内容的索引:

====
[source,text]
----
SADD people:firstname:rand e2c7dcee-b8cd-4424-883e-736ce564363e
SADD people:firstname:aviendha a9d4b3a0-50d3-4538-a2fc-f7fc2581ee56
----
====

也可以在嵌套元素上使用索引.假定 `Address` 具有以 `@Indexed` 注释的 `city` 属性.在这种情况下,一旦 `person.address.city` 不为 `null`,我们将为每个城市设置 `Set`,如以下示例所示:

====
[source,text]
----
SADD people:address.city:tear e2c7dcee-b8cd-4424-883e-736ce564363e
----
====

此外,通过编程设置,您可以定义 map keys 和列表属性的索引,如以下示例所示:

====
[source,java]
----
@RedisHash("people")
public class Person {

  // ... other properties omitted

  Map<String,String> attributes;      <1>
  Map<String Person> relatives;       <2>
  List<Address> addresses;            <3>
}
----
<1> `SADD people:attributes.map-key:map-value e2c7dcee-b8cd-4424-883e-736ce564363e`
<2> `SADD people:relatives.map-key.firstname:tam e2c7dcee-b8cd-4424-883e-736ce564363e`
<3> `SADD people:addresses.city:tear e2c7dcee-b8cd-4424-883e-736ce564363e`
====

CAUTION: 索引无法在 <<redis.repositories.references,References>> 上解析.

与 keyspaces 一样,您可以配置索引而无需注释实际的域类型,如以下示例所示:

.Index Setup with @EnableRedisRepositories
====
[source,java]
----
@Configuration
@EnableRedisRepositories(indexConfiguration = MyIndexConfiguration.class)
public class ApplicationConfig {

  //... RedisConnectionFactory and RedisTemplate Bean definitions omitted

  public static class MyIndexConfiguration extends IndexConfiguration {

    @Override
    protected Iterable<IndexDefinition> initialConfiguration() {
      return Collections.singleton(new SimpleIndexDefinition("people", "firstname"));
    }
  }
}
----
====

再次,与 keyspaces 一样,您可以以编程方式配置索引,如以下示例所示:

.Programmatic Index setup
====
[source,java]
----
@Configuration
@EnableRedisRepositories
public class ApplicationConfig {

  //... RedisConnectionFactory and RedisTemplate Bean definitions omitted

  @Bean
  public RedisMappingContext keyValueMappingContext() {
    return new RedisMappingContext(
      new MappingConfiguration(
        new KeyspaceConfiguration(), new MyIndexConfiguration()));
  }

  public static class MyIndexConfiguration extends IndexConfiguration {

    @Override
    protected Iterable<IndexDefinition> initialConfiguration() {
      return Collections.singleton(new SimpleIndexDefinition("people", "firstname"));
    }
  }
}
----
====

[[redis.repositories.indexes.geospatial]]
=== 地理空间索引

假设 `Address`  类型包含 `Point`  类型的  `location`  属性,其中包含特定地址的地理坐标. 通过使用 `@GeoIndexed` 注释属性,Spring Data Redis 使用 Redis GEO 命令添加这些值,如以下示例所示:

====
[source,java]
----
@RedisHash("people")
public class Person {

  Address address;

  // ... other properties omitted
}

public class Address {

  @GeoIndexed Point location;

  // ... other properties omitted
}

public interface PersonRepository extends CrudRepository<Person, String> {

  List<Person> findByAddressLocationNear(Point point, Distance distance);     <1>
  List<Person> findByAddressLocationWithin(Circle circle);                    <2>
}

Person rand = new Person("rand", "al'thor");
rand.setAddress(new Address(new Point(13.361389D, 38.115556D)));

repository.save(rand);                                                        <3>

repository.findByAddressLocationNear(new Point(15D, 37D), new Distance(200)); <4>
----
<1> 使用 `Point` 和 `Distance` 在嵌套属性上的查询方法声明, .
<2> 嵌套属性上的查询方法声明, 使用 `Circle` 进行搜索.
<3> `GEOADD people:address:location 13.361389 38.115556 e2c7dcee-b8cd-4424-883e-736ce564363e`
<4> `GEORADIUS people:address:location 15.0 37.0 200.0 km`
====

在前面的示例中,经度和纬度值是通过使用 `GEOADD` 存储的,而 `GEOADD` 使用对象的 `id` 作为成员的名称.查找器方法允许使用 `Circle` 或  `Point, Distance` 组合查询这些值.

NOTE: 不可能将附近和内部与其他条件组合.

include::{spring-data-commons-docs}/query-by-example.adoc[leveloffset=+1]
include::query-by-example.adoc[leveloffset=+1]

[[redis.repositories.expirations]]
== 生存时间

Redis 中存储的对象可能仅在一定时间内有效. 这对于在 Redis 中持久保存短寿命的对象特别有用,而无需在寿命到期时手动将其删除. 可以使用 `@RedisHash(timeToLive=...)` 以及使用 `KeyspaceSettings`(请参见  <<redis.repositories.keyspaces>>)来设置以秒为单位的到期时间.

可以通过在数字属性或方法上使用 `@TimeToLive` 注释来设置更灵活的到期时间. 但是,不要将 `@TimeToLive` 应用于同一类中的方法和属性. 以下示例显示了属性和方法上的 `@TimeToLive` 批注:

.Expirations
====
[source,java]
----
public class TimeToLiveOnProperty {

  @Id
  private String id;

  @TimeToLive
  private Long expiration;
}

public class TimeToLiveOnMethod {

  @Id
  private String id;

  @TimeToLive
  public long getTimeToLive() {
  	return new Random().nextLong();
  }
}
----
====

NOTE: 使用 `@TimeToLive` 显式注释属性会从 Redis 中读取实际的 `TTL` 或 `PTTL` 值. -1 表示该对象没有关联的到期时间.

存储库实现可确保通过 `RedisMessageListenerContainer` 订阅 https://redis.io/topics/notifications[Redis keyspace notifications]

当到期设置为正值时,将执行相应的 `EXPIRE` 命令. 除了保留原始副本外,幻影副本还将保留在 Redis 中,并设置为在原始副本后五分钟到期. 这样做是为了使存储库支持能够发布 `RedisKeyExpiredEvent`,并在键过期时将过期值保存在Spring的 `ApplicationEventPublisher` 中,
即使原始值已被删除也是如此. 在使用 Spring Data Redis 存储库的所有已连接应用程序上都会收到到期事件.

默认情况下,初始化应用程序时禁用密钥过期侦听器. 可以在 `@EnableRedisRepositories` 或 `RedisKeyValueAdapter` 中调整启动模式,以通过应用程序或在第一次插入带有TTL的实体时启动侦听器. 有关可能的值,请参见 https://docs.spring.io/spring-data/redis/docs/{revnumber}/api/org/springframework/data/redis/core/RedisKeyValueAdapter.EnableKeyspaceEvents.html[`EnableKeyspaceEvents`].

`RedisKeyExpiredEvent` 包含过期的域对象以及密钥的副本.

NOTE: 延迟或禁用到期事件侦听器的启动会影响 `RedisKeyExpiredEvent` 发布.禁用的事件侦听器不会发布到期事件.由于延迟的侦听器初始化,延迟的启动可能导致事件丢失.

NOTE: keyspace notification 消息侦听器会更改Redis中的 `notify-keyspace-events` 设置(如果尚未设置). 现有设置不会被覆盖,因此您必须正确设置这些设置(或将其保留为空). 请注意,在AWS `ElastiCache` 上禁用了 `CONFIG`,并且启用侦听器会导致错误.

NOTE: Redis Pub/Sub messages 消息不是持久性的.如果在应用程序关闭时密钥过期,则不会处理过期事件,这可能会导致二级索引包含对过期对象的引用.

[[redis.repositories.references]]
== 持久引用
使用 `@Reference` 标记属性允许存储简单的键引用,而不是将值复制到哈希本身中.从 Redis 加载时,引用将自动解析并映射回该对象,如以下示例所示:

.Sample 属性参考
====
[source,text]
----
_class = org.example.Person
id = e2c7dcee-b8cd-4424-883e-736ce564363e
firstname = rand
lastname = al’thor
mother = people:a9d4b3a0-50d3-4538-a2fc-f7fc2581ee56      <1>
----
<1> Reference stores the whole key (`keyspace:id`) of the referenced object.
====

WARNING: 保存引用对象时,引用对象不会保留.由于仅存储引用,因此您必须分别对引用的对象进行更改.无法解析在引用类型的属性上设置的索引

[[redis.repositories.partial-updates]]
== 持续部分更新

在某些情况下,您无需加载和重写整个实体就可以在其中设置新值. 最后一个活动时间的会话时间戳可能就是您要更改一个属性的情况. PartialUpdate 使您可以定义现有对象的 `set` 和  `delete` 操作,同时注意更新实体本身和索引结构的潜在到期时间. 以下示例显示了部分更新:

.Sample Partial Update
====
[source,java]
----
PartialUpdate<Person> update = new PartialUpdate<Person>("e2c7dcee", Person.class)
  .set("firstname", "mat")                                                           <1>
  .set("address.city", "emond's field")                                              <2>
  .del("age");                                                                       <3>

template.update(update);

update = new PartialUpdate<Person>("e2c7dcee", Person.class)
  .set("address", new Address("caemlyn", "andor"))                                   <4>
  .set("attributes", singletonMap("eye-color", "grey"));                             <5>

template.update(update);

update = new PartialUpdate<Person>("e2c7dcee", Person.class)
  .refreshTtl(true);                                                                 <6>
  .set("expiration", 1000);

template.update(update);
----
<1> 将 `firstname` 属性设置为 `mat`.
<2> 将 'address.city' 属性设置为 'emond's field' 而不必传入整个对象. 注册自定义转换时,此功能不起作用.
<3> 删除 `age` 属性.
<4> 设置复杂的 `address` 属性.
<5> 设置值的映射,该映射将删除先前存在的映射,并将值替换为给定的值.
<6> 更改<<redis.repositories.expirations>>时,将自动更新服务器的到期时间.Automatically update the server expiration time when altering .
====

NOTE: 更新复杂对象以及地图(或其他集合)结构需要与Redis进行进一步交互以确定现有值,这意味着重写整个实体可能会更快.

[[redis.repositories.queries]]
== 查询和查询方法

查询方法允许从方法名称自动继承 简单查找程序查询,如以下示例所示:

.Sample Repository finder Method
====
[source,java]
----
public interface PersonRepository extends CrudRepository<Person, String> {

  List<Person> findByFirstname(String firstname);
}
----
====


NOTE: 请确保设置查找程序方法中使用的属性以建立索引.

NOTE: Redis存储库的查询方法仅支持对实体的查询以及带分页的实体集合.

使用继承 的查询方法可能并不总是足以为要执行的查询建模. `RedisCallback` 提供了对索引结构甚至自定义索引的实际匹配的更多控制. 为此,提供一个 `RedisCallback`,它返回一组或一组可迭代的 `id` 值,如以下示例所示:

.Sample finder using RedisCallback
====
[source,java]
----
String user = //...

List<RedisSession> sessionsByUser = template.find(new RedisCallback<Set<byte[]>>() {

  public Set<byte[]> doInRedis(RedisConnection connection) throws DataAccessException {
    return connection
      .sMembers("sessions:securityContext.authentication.principal.username:" + user);
  }}, RedisSession.class);
----
====

下表概述了Redis支持的关键字以及包含该关键字的方法的基本含义:

====
.方法名称中支持的关键字
[options = "header, autowidth"]
|===============
|Keyword|Sample|Redis snippet
|`And`|`findByLastnameAndFirstname`|`SINTER …:firstname:rand …:lastname:al’thor`
|`Or`|`findByLastnameOrFirstname`|`SUNION …:firstname:rand …:lastname:al’thor`
|`Is, Equals`|`findByFirstname`, `findByFirstnameIs`, `findByFirstnameEquals`|`SINTER …:firstname:rand`
|`IsTrue` | `FindByAliveIsTrue` | `SINTER …:alive:1`
|`IsFalse` | `findByAliveIsFalse` | `SINTER …:alive:0`
|`Top,First`|`findFirst10ByFirstname`,`findTop5ByFirstname`|
|===============
====

[[redis.repositories.cluster]]
== 在集群上运行的Redis存储库

您可以在集群 Redis 环境中使用 Redis 存储库支持. 有关 ConnectionFactory 配置的详细信息,请参见  "`<<cluster>>`"  部分. 但是,还必须进行一些其他配置,因为默认的密钥分发会在整个群集及其 slot 中扩展实体和二级索引.

下表显示了群集上数据的详细信息(基于先前的示例):

[options = "header, autowidth"]
|===============
|Key|Type|Slot|Node
|people:e2c7dcee-b8cd-4424-883e-736ce564363e|id for hash|15171|127.0.0.1:7381
|people:a9d4b3a0-50d3-4538-a2fc-f7fc2581ee56|id for hash|7373|127.0.0.1:7380
|people:firstname:rand|index|1700|127.0.0.1:7379
|
|===============
====

当所有涉及的键都映射到同一 slot 时,某些命令(例如 `SINTER` 和 `SUNION`)只能在服务器端处理. 否则,必须在客户端进行计算. 因此,将 keyspaces 固定到单个 slot 非常有用,这样可以立即利用 Redis 服务器端计算.
下表显示了您执行此操作时发生的情况(请注意 slot 列中的更改以及节点列中的端口值):

[options = "header, autowidth"]
|===============
|Key|Type|Slot|Node
|{people}:e2c7dcee-b8cd-4424-883e-736ce564363e|id for hash|2399|127.0.0.1:7379
|{people}:a9d4b3a0-50d3-4538-a2fc-f7fc2581ee56|id for hash|2399|127.0.0.1:7379
|{people}:firstname:rand|index|2399|127.0.0.1:7379
|
|===============
====

TIP: 使用Redis集群时,通过使用 `@RedisHash("{yourkeyspace}")` 将 keyspaces 定义和固定到特定 slots.

[[redis.repositories.cdi-integration]]
== CDI 集成

存储库接口的实例通常由容器创建,在使用 Spring Data 时,Spring 是最自然的选择. Spring 提供了用于创建bean实例的高级工具. Spring Data Redis 附带了一个自定义 CDI 扩展,使您可以在 CDI 环境中使用存储库抽象. 该扩展是JAR的一部分,因此要激活它,请将Spring Data Redis JAR放到您的类路径中.

然后,您可以通过为 `RedisConnectionFactory` 和 `RedisOperations` 实现CDI生产者来设置基础结构,如以下示例所示:

[source, java]
----
class RedisOperationsProducer {


  @Produces
  RedisConnectionFactory redisConnectionFactory() {

    JedisConnectionFactory jedisConnectionFactory = new JedisConnectionFactory(new RedisStandaloneConfiguration());
    jedisConnectionFactory.afterPropertiesSet();

    return jedisConnectionFactory;
  }

  void disposeRedisConnectionFactory(@Disposes RedisConnectionFactory redisConnectionFactory) throws Exception {

    if (redisConnectionFactory instanceof DisposableBean) {
      ((DisposableBean) redisConnectionFactory).destroy();
    }
  }

  @Produces
  @ApplicationScoped
  RedisOperations<byte[], byte[]> redisOperationsProducer(RedisConnectionFactory redisConnectionFactory) {

    RedisTemplate<byte[], byte[]> template = new RedisTemplate<byte[], byte[]>();
    template.setConnectionFactory(redisConnectionFactory);
    template.afterPropertiesSet();

    return template;
  }

}
----

必要的设置可能会有所不同,具体取决于您的 JavaEE 环境.

每当容器请求存储库类型的bean时,Spring Data Redis CDI 扩展都将所有可用的存储库用作 CDI bean,并为 Spring Data 存储库创建代理. 因此,获取 Spring Data 存储库的实例只需声明一个 `@Injected` 属性即可,如以下示例所示:

[source, java]
----
class RepositoryClient {

  @Inject
  PersonRepository repository;

  public void businessMethod() {
    List<Person> people = repository.findAll();
  }
}
----

Redis存储库需要 `RedisKeyValueAdapter` 和 `RedisKeyValueTemplate` 实例. 如果找不到提供的 bean,那么这些 bean 由 Spring Data CDI 扩展创建和管理. 但是,您可以提供自己的 bean 来配置 `RedisKeyValueAdapter` 和 `RedisKeyValueTemplate` 的特定属性.

== Redis存储库原理

Redis作为村书库本身提供了一个非常狭窄的低级API,留给用户的是高级功能,例如二级索引和查询操作.

本节提供了由存储库抽象发出的命令的更详细视图,以更好地了解潜在的性能影响.

将以下实体类视为所有操作的起点:

.Example entity
====
[source,java]
----
@RedisHash("people")
public class Person {

  @Id String id;
  @Indexed String firstname;
  String lastname;
  Address hometown;
}

public class Address {

  @GeoIndexed Point location;
}
----
====

=== 插入新值

====
[source, java]
----
repository.save(new Person("rand", "al'thor"));
----

[source, text]
----
HMSET "people:19315449-cda2-4f5c-b696-9cb8018fa1f9" "_class" "Person" "id" "19315449-cda2-4f5c-b696-9cb8018fa1f9" "firstname" "rand" "lastname" "al'thor" <1>
SADD  "people" "19315449-cda2-4f5c-b696-9cb8018fa1f9"                           <2>
SADD  "people:firstname:rand" "19315449-cda2-4f5c-b696-9cb8018fa1f9"            <3>
SADD  "people:19315449-cda2-4f5c-b696-9cb8018fa1f9:idx" "people:firstname:rand" <4>
----
<1> 将展开的条目另存为哈希.
<2> 将用 <1> 编写的哈希键添加到同一 keyspaces 中的实体的辅助索引中.
<3> 将用<2>编写的哈希键添加到具有属性值的名字的二级索引中.
<4> 将<3>的索引添加到帮助程序结构集以供输入,以跟踪删除/更新时要清理的索引.
====

=== 替换存在的

====
[source, java]
----
repository.save(new Person("e82908cf-e7d3-47c2-9eec-b4e0967ad0c9", "Dragon Reborn", "al'thor"));
----

[source, text]
----
DEL       "people:e82908cf-e7d3-47c2-9eec-b4e0967ad0c9"                           <1>
HMSET     "people:e82908cf-e7d3-47c2-9eec-b4e0967ad0c9" "_class" "Person" "id" "e82908cf-e7d3-47c2-9eec-b4e0967ad0c9" "firstname" "Dragon Reborn" "lastname" "al'thor" <2>
SADD      "people" "e82908cf-e7d3-47c2-9eec-b4e0967ad0c9"                         <3>
SMEMBERS  "people:e82908cf-e7d3-47c2-9eec-b4e0967ad0c9:idx"                       <4>
TYPE      "people:firstname:rand"                                                 <5>
SREM      "people:firstname:rand" "e82908cf-e7d3-47c2-9eec-b4e0967ad0c9"          <6>
DEL       "people:e82908cf-e7d3-47c2-9eec-b4e0967ad0c9:idx"                       <7>
SADD      "people:firstname:Dragon Reborn" "e82908cf-e7d3-47c2-9eec-b4e0967ad0c9" <8>
SADD      "people:e82908cf-e7d3-47c2-9eec-b4e0967ad0c9:idx" "people:firstname:Dragon Reborn" <9>
----
<1> 删除现有的散列,以避免可能不再存在的散列键剩余.
<2> 将展开的条目另存为哈希.
<3> 将用<1>编写的哈希键添加到同一 keyspaces 中的实体的辅助索引中.
<4> 获取可能需要更新的现有索引结构.
<5> 检查索引是否存在以及它是什么类型(文本,地理位置,…).
<6> 从索引中删除潜在的现有键.
<7> 删除辅助程序持有索引信息.
<8> 将在<2>中添加的哈希键添加到具有属性值的名字的二级索引中.
<9> 将索引<6>添加到帮助程序结构集中,以进行输入,以跟踪删除/更新时要清除的索引.
====

=== 保存 Geo 数据

地理索引遵循与基于普通文本的规则相同的规则,但是使用地理结构来存储值. 保存使用地理索引属性的实体将导致以下命令:

====
[source, text]
----
GEOADD "people:hometown:location" "13.361389" "38.115556" "76900e94-b057-44bc-abcf-8126d51a621b"  <1>
SADD   "people:76900e94-b057-44bc-abcf-8126d51a621b:idx" "people:hometown:location"               <2>
----
<1> 将已保存条目的键添加到地理位置索引
<2> 跟踪索引结构.
====

=== 使用简单索引查找

====
[source, java]
----
repository.findByFirstname("egwene");
----

[source, text]
----
SINTER  "people:firstname:egwene"                     <1>
HGETALL "people:d70091b5-0b9a-4c0a-9551-519e61bc9ef3" <2>
HGETALL ...
----
<1> 提取二级索引中包含的键.
<2> 分别获取<1>返回的每个键.
====

=== 使用地理位置索引查找

====
[source, java]
----
repository.findByHometownLocationNear(new Point(15, 37), new Distance(200, KILOMETERS));
----

[source, text]
----
GEORADIUS "people:hometown:location" "15.0" "37.0" "200.0" "km" <1>
HGETALL   "people:76900e94-b057-44bc-abcf-8126d51a621b"         <2>
HGETALL   ...
----
<1> 提取二级索引中包含的键.
<2> 分别获取<1>返回的每个键.
====
