[[howtoReadMarbles]]
= 如何阅读 marble diagrams(弹珠图)?

当我们介绍 `Flux` 和 `Mono` 时，我们展示了一个 "弹珠图" 的例子。为了以更直观的方式解释操作符的行为，在 javadoc 中可以找到这些操作符.

在本节中，我们将更深入地研究 Reactor 文档对这些弹珠图所使用的约定。首先，让我们看看最常见的运算符模式是如何表示的.

有些操作符是实例方法:它们的输出是通过调用 `Flux` 实例上的一个方法产生的(比如 `Flux<T> output = source.fluxOperator()`):

image::{image-dir}/legend-operator-method.svg[A common operator]

其他操作符是静态方法。它们仍然可以将 `Flux` 作为输入参数，如  `Flux<T> output = Flux.merge(sourceFlux1, sourcePublisher2)`。如下所示:

image::{image-dir}/legend-operator-static.svg[A static operator]

注意，有时我们根据操作符的输入表示多个变量或行为，在这种情况下有一个操作符 "框"，source 变量和输出变量像下面这样分开:

image::{image-dir}/legend-operator-double-source.svg[An operator with two examples of input]

这些都是基本情况，但有些操作符显示的模式稍微高级一些。

例如，`ParallelFlux` 创建了多个 rails，因此它们有多个 `Flux` 输出。如下图所示:

image::{image-dir}/legend-operator-parallel.svg[A parallel operator]

Windowing 操作符产生一个 `Flux<Flux<T>>` :每个 windows 打开的主要 `Flux` 通知，而内部 `Flux` 表示 windows 内容和终止。windows 被表示为主要 `Flux` 的分支，如下图所示:

image::{image-dir}/legend-operator-windowing.svg[The output of a windowing operator]

有时，操作符将 "companion publisher" 作为输入(`Flux`、`Mono` 或任意的 Reactive Stream 发布者)。这样的 "companion publisher" 帮助您自定义操作符的行为，这将使用 companion 的一些信号作为其内部行为的触发器。它们如下图所示:

image::{image-dir}/legend-operator-companion.svg[An operator with a companion Publisher]

现在我们已经看到了最常见的操作模式，让我们来展示 `Flux` 或 `Mono` 中可能发生的所有不同信号、事件和元素的图形表示:

image::{image-dir}/legend-events.svg[All types of signals and events]

最后，以同样的方式，我们有  _side effects_ 的图形表示，这发生在 Reactive Stream 信号:

image::{image-dir}/legend-sideEffects1.svg[Side effects: representation of doOn* handlers]
image::{image-dir}/legend-sideEffects2.svg[Side effects: in a diagram]

