[[debugging]]
= 调试 Reactor

从命令式和同步式编程切换到响应式和异步式编程有时候是令人生畏的. 学习曲线中最陡峭的异步就是出错时如何分析和调试.

在命令式世界,调试通常都是非常直观的: 直接看 stack trace 就可以找到问题出现的位置, 以及是否问题责任全部出在你自己的代码? 问题是不是发生在某些库代码? 如果是, 那你的哪部分代码调用了库,是不是传参不合适导致的问题?

== 典型的 Reactor Stack Trace

当你切换到异步代码,事情就变得复杂的多了.

看一下下边的 stack trace:

.A typical Reactor stack trace
====
[source,java]
----
java.lang.IndexOutOfBoundsException: Source emitted more than one item
    at reactor.core.publisher.MonoSingle$SingleSubscriber.onNext(MonoSingle.java:129)
    at reactor.core.publisher.FluxFlatMap$FlatMapMain.tryEmitScalar(FluxFlatMap.java:445)
    at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:379)
    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:121)
    at reactor.core.publisher.FluxRange$RangeSubscription.slowPath(FluxRange.java:154)
    at reactor.core.publisher.FluxRange$RangeSubscription.request(FluxRange.java:109)
    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:162)
    at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:332)
    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)
    at reactor.core.publisher.FluxRange.subscribe(FluxRange.java:68)
    at reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)
    at reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:97)
    at reactor.core.publisher.MonoSingle.subscribe(MonoSingle.java:58)
    at reactor.core.publisher.Mono.subscribe(Mono.java:3096)
    at reactor.core.publisher.Mono.subscribeWith(Mono.java:3204)
    at reactor.core.publisher.Mono.subscribe(Mono.java:3090)
    at reactor.core.publisher.Mono.subscribe(Mono.java:3057)
    at reactor.core.publisher.Mono.subscribe(Mono.java:3029)
    at reactor.guide.GuideTests.debuggingCommonStacktrace(GuideTests.java:995)
----
====

这里边有好多信息,我们得到了一个 `IndexOutOfBoundsException`,内容是 "源发出了 不止一个元素".

我们也许可以很快假定这个源是一个 `Flux/Mono`,并通过下一行提到的 `MonoSingle` 确定是 `Mono`. 看上去是来自一个 `single` 操作符的抱怨.

查看 Javadoc 中关于操作符 `Mono#single` 的说明,我们看到 `single` 有一个规定:  源必须只能发出一个元素.看来是有一个源发出了多于一个元素,从而违反了这一规定.

我们可以更进一步找出那个源吗? 下边的这些内容帮不上什么忙,只是打印了一些内部的似乎是一个响应式链的信息, 主要是一些 `subscribe` 和 `request` 的调用.

粗略过一下这些行,我们至少可以勾画出一个大致的出问题的链: 大概涉及一个 `MonoSingle`、一个 `FluxFlatMap`,以及一个 `FluxRange`(每一个都对应 trace 中的几行,但总体涉及这三个类). 所以难道是 `range().flatMap().single()`  这样的链?

但是如果在我们的应用中多处都用到这一模式,那怎么办? 通过这些还是不能确定什么, 搜索 `single` 也找不到问题所在.最后一行指向了我们的代码.我们似乎终于接近真相了.

不过,等等… 当我们找到源码文件,我们只能找到一个已存在的 `Flux` 被订阅了,如下:

====
[source,java]
----
toDebug
    .subscribeOn(Schedulers.immediate())
    .subscribe(System.out::println, Throwable::printStackTrace);
----
====

所有这些都发生在订阅时,但是 `Flux` 本身没有在这里 声明 .更糟的是, 当我们找到变量声明的地方,我们看到:

====
[source,java]
----
public Mono<String> toDebug; //please overlook the public class attribute
----
====

变量声明的地方并没有 实例化 .我们必须做最坏的打算,那就是在这个应用中, 可能在几个不同的代码路径上对这个变量赋了值,但我们不确定是哪一个导致了问题.

NOTE: 这是一种 Reactor 运行时错误,而不是编译错误.

我们希望找到的是操作符在哪里添加到操作链上的 —— 也就是 `Flux` 在哪里 声明的.我们通常说这个 `Flux` 是被 组装(assembly) 的.

[[debug-activate]]
== 开启调试模式 - aka tracebacks

WARNING: 本节介绍了启用调试功能的最简单但最慢的方法,因为它捕获了每个运算符上的 stacktrace. 有关更精细的调试方法,请参见 <<checkpoint-alternative>> 替代方法; 有关更高级和更高性能的全局选项, 请参见生产就绪的 <<reactor-tools-debug>>.


即便 stack trace 能够对有些许经验的开发者传递一些信息,但是在一些复杂的情况下, 这并不是一种理想的方式.

幸运的是,Reactor 内置了一种面向调试的能力—— 操作期测量(assembly-time instrumentation).

这通过 在应用启动的时候 (或至少在有问题的 `Flux` 或 `Mono` 实例化之前) 通过 `Hooks.onOperatorDebug()` 方法激活全局调试模式来完成的,如下:

====
[source,java]
----
Hooks.onOperatorDebug();
----
====

这行代码——通过包装操作符的构造方法,并在此捕捉 stack trace —— 来监测对这个 Reactor 操作符的调用(也就是“组装”链的地方).由于这些在 操作链被声明的地方就搞定,这个 hook 应该在 早于 声明的时候被激活, 最保险的方式就是在你程序的最开始就激活它.

之后,如果发生了异常,导致失败的操作符能够找到捕捉点并补充 stack trace.

TIP: 我们将此捕获的程序集信息 (以及由常规的 Reactor 添加到异常的附加信息) 称为 *traceback*.

在下一小节,我们看一下 stack trace 会有什么不同,以及如何对其进行分析.

== 阅读调试模式的 Stack Trace

我们在对上边的例子激活 `operatorStacktrace` 调试功能后,stack trace 如下:
发生了几件事：

1. 指向订阅站点的堆栈跟踪不用太关系，在第一帧之后会被裁剪。
2. 将一个特殊的 suppressed exception（抑制异常）添加到原始异常中（或者如果已经存在则进行修改）。
3. 为该特殊异常构造一条消息，其中包含多个部分。
4. 第一部分将追溯至失败操作符的组装地点。
5. 第二部分将尝试显示从该运算符构建的链并且已经看到错误传播
6. 最后一部分是原始堆栈跟踪

打印后的完整堆栈跟踪如下：

====
[source]
----
java.lang.IndexOutOfBoundsException: Source emitted more than one item
    at reactor.core.publisher.MonoSingle$SingleSubscriber.onNext(MonoSingle.java:127) <1>
    Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: <2>
Assembly trace from producer [reactor.core.publisher.MonoSingle] : <3>
    reactor.core.publisher.Flux.single(Flux.java:7915)
    reactor.guide.GuideTests.scatterAndGather(GuideTests.java:1017)
Error has been observed at the following site(s): <4>
    *_______Flux.single ⇢ at reactor.guide.GuideTests.scatterAndGather(GuideTests.java:1017) <5>
    |_ Mono.subscribeOn ⇢ at reactor.guide.GuideTests.debuggingActivated(GuideTests.java:1071) <6>
Original Stack Trace: <7>
        at reactor.core.publisher.MonoSingle$SingleSubscriber.onNext(MonoSingle.java:127)
...
<8>
...
        at reactor.core.publisher.Mono.subscribeWith(Mono.java:4363)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4223)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4159)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4131)
        at reactor.guide.GuideTests.debuggingActivated(GuideTests.java:1067)
----
<1> 原始堆栈跟踪被截断为单个帧.
<2> 这一条是新的: 可以发现外层操作符捕捉到了 stack trace. 这是回溯开始出现的地方。
<3> 首先我们获得了关于操作符组装的信息。
<4> 以及错误沿着操作链传播的轨迹，从第一个到最后一个(从错误点到订阅点).
<5> 每一个看到这个错误的操作符都会列出,包括类和行信息. 这里我们有一个 "root".
<6> 这里我们有链的一个简单部分.
<7> 堆栈跟踪的其余部分被移动到最后...
<8> ...显示了一些操作符的内部结构（所以我们在这里删除了一些片段）。.
====

可见,捕获的 stack trace 作为 `OnAssemblyException` 添加到原始错误信息的之后.有三部分, 但是第一部分更加有意思.它显示了操作符触发异常的路径.这里显示的是 `scatterAndGather` 方法中的 `single` 导致的问题

既然我们已经有足够的信息来查出罪魁祸首,我们就来看一下 `scatterAndGather` 方法吧:

====
[source,java]
----
private Mono<String> scatterAndGather(Flux<String> urls) {
    return urls.flatMap(url -> doRequest(url))
           .single(); <1>
}
----
<1> 找到了,就是这个 `single`.
====

现在我们可以发现错误的根源是将多个 HTTP 请求转化为 URLs 的 `flatMap` 方法后边接的是 `single`, 这太严格了.使用  `git blame` 找到代码作者,并同他讨论过后,发现他是本来是想用不那么严格的 `take(1)` 方法的.

我们解决了问题.

现在考虑 stack trace 中的以下部分:

====
[source]
----
Error has been observed at the following site(s):
----
====

调试信息的第二部分在这个例子中意义不大,因为错误实际发生在最后一个操作符上(离 `subscribe` 最近的一个). 另一个例子可能更加清楚:

====
[source,java]
----
FakeRepository.findAllUserByName(Flux.just("pedro", "simon", "stephane"))
              .transform(FakeUtils1.applyFilters)
              .transform(FakeUtils2.enrichUser)
              .blockLast();
----
====

现在想象一下在 `findAllUserByName` 内部有个 `map` 方法报错了.我们可能会在第二部分中看到如下的 trace:

====
[source]
----
Error has been observed at the following site(s):
    *________Flux.map ⇢ at reactor.guide.FakeRepository.findAllUserByName(FakeRepository.java:27)
    |_       Flux.map ⇢ at reactor.guide.FakeRepository.findAllUserByName(FakeRepository.java:28)
    |_    Flux.filter ⇢ at reactor.guide.FakeUtils1.lambda$static$1(FakeUtils1.java:29)
    |_ Flux.transform ⇢ at reactor.guide.GuideDebuggingExtraTests.debuggingActivatedWithDeepTraceback(GuideDebuggingExtraTests.java:39)
    |_   Flux.elapsed ⇢ at reactor.guide.FakeUtils2.lambda$static$0(FakeUtils2.java:30)
    |_ Flux.transform ⇢ at reactor.guide.GuideDebuggingExtraTests.debuggingActivatedWithDeepTraceback(GuideDebuggingExtraTests.java:40)
----
====

这与 (s) 上收到错误通知的操作符是一致:

. 异常源自第一个 `map`. `*` 表示为 root，而 `_` 用于缩进。
. 第二个 `map` 看到异常(都在 `findAllUserByName` 方法中).
. 接着被一个 `filter` 和一个 `transform` 看到,说明链的这部分是由一个可重复使用的转换方法组装的 (这里是 `applyFilters` 工具方法).
. 最后被一个 `elapsed` 和一个 `transform` 看到,类似的, `elapsed` 由第二个转换方法(`enrichUser`) 组装.

在某些情况下，相同的异常通过多个链传播，"root" 使用 `*_` 标记。使我们能够更好地分离这些链。
如果一个站点被多次查看，调用站点信息后会有一个 `(observed x times)`。

例如，让我们考虑以下片段:

====
[source,java]
----
public class MyClass {
    public void myMethod() {
        Flux<String> source = Flux.error(sharedError);
        Flux<String> chain1 = source.map(String::toLowerCase).filter(s -> s.length() < 4);
        Flux<String> chain2 = source.filter(s -> s.length() > 5).distinct();

        Mono<Void> when = Mono.when(chain1, chain2);
    }
}
----
====

在上面的代码中，错误传播到 `when`，通过两个独立的链 `chain1` 和 `chain2`。
这将导致包含以下内容的回溯：

====
[source]
----
Error has been observed at the following site(s):
    *_____Flux.error ⇢ at myClass.myMethod(MyClass.java:3) (observed 2 times)
    |_      Flux.map ⇢ at myClass.myMethod(MyClass.java:4)
    |_   Flux.filter ⇢ at myClass.myMethod(MyClass.java:4)
    *_____Flux.error ⇢ at myClass.myMethod(MyClass.java:3) (observed 2 times)
    |_   Flux.filter ⇢ at myClass.myMethod(MyClass.java:5)
    |_ Flux.distinct ⇢ at myClass.myMethod(MyClass.java:5)
    *______Mono.when ⇢ at myClass.myMethod(MyClass.java:7)
----
====

我们可以看到:

. 这里有 3 "root" 元素 ( `when` 才是真正的 root).
. 从 `Flux.error` 开始的两条链是可见的。.
. 两条链似乎都基于相同的 `Flux.error` 来源（`observed 2 times`）。
. 第一条链是 `Flux.error().map().filter`
. 第二条链是 `Flux.error().filter().distinct()

TIP: *关于回溯和抑制异常的解释*:
由于回溯作为被抑制的异常附加到原始错误，这可能会在某种程度上干扰使用此机制的另一种类型的异常：复合异常。
此类异常可以通过 `Exceptions.multiple(Throwable...)` 直接创建，或者由一些可能加入多个错误源的操作符（如  `Flux#flatMapDelayError`）创建。 他们
可以通过 `Exceptions.unwrapMultiple(Throwable)` 展开到一个 `List` 中，在这种情况下，traceback 将被视为复合的一个组件，并且是返回的 `List` 的一部分。
如果这在某种程度上是不可取的，tracebacks 可以由于 `Exceptions.isTraceback(Throwable)` 检查而被识别，
并通过使用 `Exceptions.unwrapMultipleExcludingTracebacks(Throwable)` 而被排除在这样的 unwrap 之外。

用这种形式的检测方式构造 stack trace 是成本较高的.也因此这种调试模式作为最终大招, 只应该在可控的方式下激活.

[[checkpoint-alternative]]
=== 用 `checkpoint()` 方式替代

调试模式是全局性的,会影响到程序中每一个组装到一个 `Flux` 或 `Mono` 的操作符.好处在于可以进行 事后调试(after-the-fact debugging): 无论错误是什么,我们都会得到足够的调试信息.

就像前边见到的那样,这种全局性的调试会因为成本较高而影响性能(其影响在于生成的 stack traces 数量). 如果我们能大概定位到疑似出问题的操作符的话就可以不用花那么大的成本.然而,问题出现后, 我们通常无法定位到哪一个操作符可能存在问题,因为缺少一些 trace 信息,我们得修改代码, 打开调试模式,期望能够复现问题.

这种情况下,我们需要切换到调试模式,并进行一些必要的准备工作以便能够更好的发现复现的问题, 并捕捉到所有的信息.(译者加: 这两段感觉有点废话...)

如果你能确定是在你的代码中组装的响应式链存在问题,而且程序的可服务性又是很重要的, 那么你可以 使用 `checkpoint()` 操作符,它有两种调试技术可用.

你可以把这个操作符加到链中.这时 `checkpoint` 操作符就像是一个 hook,但只对它所在的链起作用.

还有一个 `checkpoint(String)` 的方法变体,你可以传入一个独特的字符串以方便在 assembly traceback 中识别信息. 这样会省略 stack trace,你可以依赖这个字符串(以下改称“定位描述符”)来定位到组装点.
`checkpoint(String)` 比 `checkpoint` 有更低的执行成本.

最后的但同样重要的是,如果你既想通过 checkpoint 添加定位描述符,同时又依赖于 stack trace 来定位组装点,你可以使用 `checkpoint("description", true)` 来实现这一点.这时回溯信息又出来了, 同时附加了定位描述符,如下例所示:

====
[source]
----
Assembly trace from producer [reactor.core.publisher.ParallelSource], described as [descriptionCorrelation1234] : <1>
	reactor.core.publisher.ParallelFlux.checkpoint(ParallelFlux.java:215)
	reactor.core.publisher.FluxOnAssemblyTest.parallelFluxCheckpointDescriptionAndForceStack(FluxOnAssemblyTest.java:225)
Error has been observed at the following site(s):
	|_	ParallelFlux.checkpoint ⇢ reactor.core.publisher.FluxOnAssemblyTest.parallelFluxCheckpointDescriptionAndForceStack(FluxOnAssemblyTest.java:225)
----
<1> `descriptionCorrelation1234` 是通过 `checkpoint` 给出的定位描述符.
====

定位描述符可以是静态的字符串、或人类可读的描述、或一个 correlation ID(例如, 来自 HTTP 请求头的信息).

NOTE: 当全局调试模式和 `checkpoint()` 都开启的时候,将应用全局调试回溯样式，并且 checkpoint 仅反映在 "Error has been observed..." 部分中,因此，在这种情况下，heavy checkpoints 的名称是不可见的。.

[[reactor-tools-debug]]
== 用于生产环境的全局调试
Project Reactor 带有一个单独的 Java 代理,可对您的代码进行检测并添加调试信息. 该行为与<<debug-activate>>(也称为回溯)非常相似,但没有运行时性能开销.

要在您的应用程序中使用它,必须将其添加为依赖.

以下示例显示如何在 Maven 中将  `reactor-tools` 添加为依赖:

.reactor-tools in Maven, in `<dependencies>`
====
[source,xml]
----
<dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-tools</artifactId>
    <1>
</dependency>
----
<1> 如果你使用 <<getting,BOM>>, 你无需指定 `<version>`.
====

在 Gradle 中添加 `reactor-tools' 依赖:

.reactor-tools in Gradle, amend the `dependencies` block
====
[source,groovy]
----
dependencies {
   compile 'io.projectreactor:reactor-tools'
}
----
====

还需要使用以下命令初始化它:

====
[source,java]
----
ReactorDebugAgent.init();
----
====

TIP: 由于该实现将在加载类时对其进行检测,因此放置它的最佳位置是在 main(String[]) 方法中的所有其他项之前:
====
[source,java]
----
public static void main(String[] args) {
    ReactorDebugAgent.init();
    SpringApplication.run(Application.class, args);
}
----
====

如果您不着急执行初始化(例如在测试中),也可以使用 `processExistingClasses()` 重新处理现有的类，
例如，在 https://junit.org/junit5/docs/current/user-guide/#launcher-api-listeners-custom[来自 `TestExecutionListener` 的 JUnit5 测试] 甚至在类 `static` 初始化程序块中：


====
[source,java]
----
ReactorDebugAgent.init();
ReactorDebugAgent.processExistingClasses();
----
====

WARNING: 请注意,由于需要遍历所有已加载的类并应用转换,因此重新处理需要花费几秒钟的时间.仅当看到某些 call-sites 没有检测到时才使用它.

=== 局限性
`ReactorDebugAgent` 被实现为Java代理,并使用 https://bytebuddy.net/#/[ByteBuddy] 进行自连接.自连接可能不适用于某些 JVM,有关更多详细信息,请参考 ByteBuddy 的文档.

=== 将 ReactorDebugAgent 作为 Java代 理运行
如果您的环境不支持 ByteBuddy 的自连接,则可以将 `reactor-tools` 作为 Java 代理运行:
====
[source,shell]
----
java -javaagent reactor-tools.jar -jar app.jar
----
====

=== 在构建时运行 ReactorDebugAgent
也可以在构建时运行 `reactor-tools`.为此,您需要将其作为 ByteBuddy 的构建工具的插件来应用.

WARNING: 只会应用于您项目中的类.不会检测类路径库.

.reactor-tools with https://github.com/raphw/byte-buddy/tree/byte-buddy-1.10.9/byte-buddy-maven-plugin[ByteBuddy's Maven plugin]
====
[source,xml]
----
<dependencies>
	<dependency>
		<groupId>io.projectreactor</groupId>
		<artifactId>reactor-tools</artifactId>
		<1>
		<classifier>original</classifier> <2>
		<scope>runtime</scope>
	</dependency>
</dependencies>

<build>
	<plugins>
		<plugin>
			<groupId>net.bytebuddy</groupId>
			<artifactId>byte-buddy-maven-plugin</artifactId>
			<configuration>
				<transformations>
					<transformation>
						<plugin>reactor.tools.agent.ReactorDebugByteBuddyPlugin</plugin>
					</transformation>
				</transformations>
			</configuration>
		</plugin>
	</plugins>
</build>
----
<1> 如果使用 <<getting,BOM>>,则无需指定  `<version>`.
<2> `classifier` 在这里很重要.
====

.reactor-tools with https://github.com/raphw/byte-buddy/tree/byte-buddy-1.10.9/byte-buddy-gradle-plugin[ByteBuddy's Gradle plugin]
====
[source,groovy]
----
plugins {
	id 'net.bytebuddy.byte-buddy-gradle-plugin' version '1.10.9'
}

configurations {
	byteBuddyPlugin
}

dependencies {
	byteBuddyPlugin(
			group: 'io.projectreactor',
			name: 'reactor-tools',
			<1>
			classifier: 'original', <2>
	)
}

byteBuddy {
	transformation {
		plugin = "reactor.tools.agent.ReactorDebugByteBuddyPlugin"
		classPath = configurations.byteBuddyPlugin
	}
}
----
<1> 如果使用 <<getting,BOM>>,则无需指定  `<version>`.
<2> `classifier` 在这里很重要.
====


== 记录流的日志

除了基于 stack trace 的调试和分析,还有一个有效的工具可以跟踪异步序列并记录日志.

就是 `log()` 操作符.将其加到操作链上之后,它会读(只读,peek)每一个 在其上游的 `Flux` 或 `Mono` 事件(包括 `onNext`、`onError`、 `onComplete`, 以及 订阅、 取消、和 请求).

.关于 logging 的具体实现
****
`log` 操作符通过使用 Loggers 工具类,该类会自动选择通用的日志记录框架 例如通过 SLF4J 使用的 Log4J 和 Logback , 如果 SLF4J 不存在的话,则直接将日志输出到控制台.

控制台使用 `System.err` 记录 `WARN` 和 `ERROR` 级别的日志,使用 `System.out` 记录其他级别的日志.

如果你喜欢使用 JDK `java.util.logging`,在 3.0.x 你可以设置 JDK 的系统属性 `reactor.logging.fallback`.

在所有情况下,在生产环境中记录日志时,都应小心配置底层日志记录框架,以使用其最异步和非阻塞的方法(例如,Logback 中的 `AsyncAppender` 或 Log4j 2 中的 `AsyncLogger`).
****

假设我们配置并激活了 logback,以及一个形如 `range(1,10).take(3)` 的操作链.通过将 `log()` 放在 `take` 之前, 我们就可以看到它内部是如何运行的,以及什么样的事件会向上游传播给 range,如下所示:

====
[source,java]
----
Flux<Integer> flux = Flux.range(1, 10)
                         .log()
                         .take(3);
flux.subscribe();
----
====

输出如下(通过 logger 的 console appender):

====
----
10:45:20.200 [main] INFO  reactor.Flux.Range.1 - | onSubscribe([Synchronous Fuseable] FluxRange.RangeSubscription) <1>
10:45:20.205 [main] INFO  reactor.Flux.Range.1 - | request(3) <2>
10:45:20.205 [main] INFO  reactor.Flux.Range.1 - | onNext(1) <3>
10:45:20.205 [main] INFO  reactor.Flux.Range.1 - | onNext(2)
10:45:20.205 [main] INFO  reactor.Flux.Range.1 - | onNext(3)
10:45:20.205 [main] INFO  reactor.Flux.Range.1 - | cancel() <4>
----

这里,除了 logger 自己的格式(时间、线程、级别、消息),`log()` 操作符 还输出了其他一些格式化的东西:

<1> `reactor.Flux.Range.1` 是自动生成的日志 类别(category),以防你在操作链中多次使用 同一个操作符.通过它你可以分辨出来是哪个操作符的事件(这里是 `range` 的). 你可以调用 `log(String)` 方法用自定义的类别替换这个标识符.在几个用于分隔的字符之后, 打印出了实际的事件.
这里是一个 `onSubscribe` 调用、一个 `request` 调用、三个 `onNext` 调用, 以及一个 `cancel` 调用.对于第一行的 `onSubscribe`,我们知道了 `Subscriber` 的具体实现,
通常与操作符指定的实现是一致的,在方括号内有一些额外信息,包括这个操作符是否能够 通过同步或异步融合的方式进行自动优化.
<2> 第二行,我们可以看到 take 将向上游的请求限制为 3。.
<3> 然后 range 一下发出三个值.
<4> 最后一行,我们看到了 `cancel()`.
====

第二行 (2) 和最后一行 (4) 是最有趣的。 我们可以看到 `take` 的动作。它利用背压来向源询问准确的预期元素数量。 在收到足够的元素后，它会通过调用 `cancel()` 告诉源不再需要任何元素。
请注意，如果下游本身使用背压，例如。 通过仅请求 `1` 个元素，`take` 运算符会尊重这一点（它在从下游传播请求时 _caps_ 请求到上游）。