= Reactor 3 Reference Guide
Stephane Maldini <https://twitter.com/smaldini[@smaldini]>; Simon Baslé <https://twitter.com/simonbasle[@simonbasle]>; Jcohy <https://https://github.com/jiachao23[@Jcohy]>
:revnumber: {reactor-version}
:revdate: {localdate}
:image-dir: {resource-url}/jcohy-docs/images/reactor

include::aboutDoc.adoc[leveloffset=1]
https://github.com/reactor/reactor-core/edit/main/docs/asciidoc/aboutDoc.adoc[Suggest Edit^,title="Suggest an edit to the above section via github",role="fa fa-edit"]
to "<<about-doc>>"

include::gettingStarted.adoc[leveloffset=1]
https://github.com/reactor/reactor-core/edit/main/docs/asciidoc/gettingStarted.adoc[Suggest Edit^,title="Suggest an edit to the above section via github",role="fa fa-edit"]
to "<<getting-started>>"

include::reactiveProgramming.adoc[leveloffset=1]
https://github.com/reactor/reactor-core/edit/main/docs/asciidoc/reactiveProgramming.adoc[Suggest Edit^,title="Suggest an edit to the above section via github",role="fa fa-edit"]
to "<<intro-reactive>>"

include::coreFeatures.adoc[leveloffset=1]
https://github.com/reactor/reactor-core/edit/main/docs/asciidoc/coreFeatures.adoc[Suggest Edit^,title="Suggest an edit to the above section via github",role="fa fa-edit"]
to "<<core-features>>"

//TODO see other sections from consuming.adoc

include::kotlin.adoc[leveloffset=1]
https://github.com/reactor/reactor-core/edit/main/docs/asciidoc/kotlin.adoc[Suggest Edit^,title="Suggest an edit to the above section via github",role="fa fa-edit"]
to "<<kotlin>>"

include::testing.adoc[leveloffset=1]
https://github.com/reactor/reactor-core/edit/main/docs/asciidoc/testing.adoc[Suggest Edit^,title="Suggest an edit to the above section via github",role="fa fa-edit"]
to "<<testing>>"

include::debugging.adoc[leveloffset=1]
https://github.com/reactor/reactor-core/edit/main/docs/asciidoc/debugging.adoc[Suggest Edit^,title="Suggest an edit to the above section via github",role="fa fa-edit"]
to "<<debugging>>"

include::metrics.adoc[leveloffset=1]
https://github.com/reactor/reactor-core/edit/main/docs/asciidoc/metrics.adoc[Suggest Edit^,title="Suggest an edit to the above section via github",role="fa fa-edit"]
to "<<metrics>>"

include::metrics-details.adoc[]

include::advancedFeatures.adoc[leveloffset=1]
https://github.com/reactor/reactor-core/edit/main/docs/asciidoc/advancedFeatures.adoc[Suggest Edit^,title="Suggest an edit to the above section via github",role="fa fa-edit"]
to "<<advanced>>"


[appendix]
include::apdx-operatorChoice.adoc[leveloffset=1]
https://github.com/reactor/reactor-core/edit/main/docs/asciidoc/apdx-operatorChoice.adoc[Suggest Edit^,title="Suggest an edit to the above section via github",role="fa fa-edit"]
to "<<which-operator>>"

[appendix]
include::apdx-howtoReadMarbles.adoc[leveloffset=1]
https://github.com/reactor/reactor-core/edit/main/docs/asciidoc/apdx-howtoReadMarbles.adoc[Suggest Edit^, title="Suggest an edit to the above section via github", role="fa fa-edit"]
to "<<howtoReadMarbles>>"

[appendix]
include::faq.adoc[leveloffset=1]
https://github.com/reactor/reactor-core/edit/main/docs/asciidoc/faq.adoc[Suggest Edit^,title="Suggest an edit to the above section via github",role="fa fa-edit"]
to "<<faq>>"

[appendix]
include::apdx-reactorExtra.adoc[leveloffset=1]
https://github.com/reactor/reactor-core/edit/main/docs/asciidoc/apdx-reactorExtra.adoc[Suggest Edit^,title="Suggest an edit to the above section via github",role="fa fa-edit"]
to "<<reactor-extra>>"

//TODO later add appendices about internals, writing operators, fusion
//[appendix]
//include::apdx-implem.adoc[]
//
//[appendix]
//include::apdx-writingOperator.adoc[]
//[appendix]
//include::apdx-optimizations.adoc[]

//TODO later add appendix about migrating from RxJava?
//[appendix]
//include::apdx-migrating.adoc[]