[[metrics]]
= 暴漏 Reactor 指标

Project Reactor 是一个旨在提高性能和更好地利用资源的库.但是要真正了解系统的性能,最好是能够监视其各种组件.

这就是为什么 Reactor 提供与 https://micrometer.io[Micrometer] 的内置集成的原因.

TIP: 如果 Micrometer 不在类路径中,则指标什么也不会发生.

== Scheduler metrics

Reactor 中的每个异步操作都是通过 Threading and Schedulers 中描述的 <<schedulers>> 抽象来完成的. 这就是为什么监视您的 `Scheduler`

要启用 Scheduler metrics,您将需要使用以下方法:
====
[source,java]
----
Schedulers.enableMetrics();
----
====

WARNING: 创建调度程序时将执行检测.建议尽早调用此方法.

TIP: 如果您使用的是 Spring Boot,则最好将调用放在 `SpringApplication.run(Application.class, args)` 调用之前.

一旦启用了 scheduler metrics 并将其提供到类路径中,Reactor 将使用 `Micrometer` 的支持来检测执行程序.

请参阅 https://micrometer.io/docs/ref/jvm[Micrometer 的文档] 以了解公开的指标,例如:

- executor_active_threads
- executor_completed_tasks_total
- executor_pool_size_threads
- executor_queued_tasks
- executor_secounds_{count, max, sum}

由于一个调度程序可能具有多个执行程序,因此每个执行程序指标都有一个 `reactor_scheduler_id` 标记.


TIP: Grafana + Prometheus 用户可以使用 https://raw.githubusercontent.com/reactor/reactor-monitoring-demo/master/dashboards/schedulers.json[a pre-built dashboard],其中包括用于线程,已完成任务,任务队列和其他方面指标的面板.

== Publisher metrics
有时,能够在 reactive pipeline 的某个阶段记录指标很有用.

一种方法是将值手动推送到您选择的指标后端. 另一种选择是将 Reactor 的内置指标集成用于 `Flux/Mono` 并对其进行解释.

Consider the following pipeline:
====
[source,java]
----
listenToEvents()
    .doOnNext(event -> log.info("Received {}", event))
    .delayUntil(this::processEvent)
    .retry()
    .subscribe();
----
====

要启用此源 `Flux` 的 metrics(从 `listenToEvents()` 返回),我们需要为其命名并打开收集的 metrics:
====
[source,java]
----
listenToEvents()
    .name("events") <1>
    .metrics() <2>
    .doOnNext(event -> log.info("Received {}", event))
    .delayUntil(this::processEvent)
    .retry()
    .subscribe();
----
<1> 此阶段的每个指标都将被标识为 "events" (可选的).
<2> `Flux#metrics` 运算符可启用指标报告,使用调用 `Flux#name` 操作符时提供的名称。如果没有使用 `Flux#name` 操作符，默认名称将是 `reactor`。
====

只需将这两个运算符相加,便可以揭示一大堆有用的指标！

[width="100%",options="header"]
|=======
| metric name | type | description

| [name].subscribed | Counter | Counts how many Reactor sequences have been subscribed to

| [name].malformed.source | Counter | Counts the number of events received from a malformed source (ie an onNext after an onComplete)

| [name].requested | DistributionSummary | Counts the amount requested to a named Flux by all subscribers, until at least one requests an unbounded amount

| [name].onNext.delay | Timer | Measures delays between onNext signals (or between onSubscribe and first onNext)

| [name].flow.duration | Timer | Times the duration elapsed between a subscription and the termination or cancellation of the sequence. A status tag is added to specify what event caused the timer to end (`completed`, `completedEmpty`, `error`, `cancelled`).
|=======

是否想知道由于某些错误您的事件处理已重新启动了多少次?  读取 `[name].subscribed`,因为 `retry()` 运算符将在发生错误时重新订阅源发布者.

对 "每秒事件数" 指标感兴趣吗?  测量 `[name].onNext.delay` 计数的速率.

是否希望在监听器引发错误时收到警报?  使用带有 `status=error` 标签的 `[name].flow.duration` .

类似的, `status=completed` 和 `status=completedEmpty` 可以让您区分以完成的元素序列和已完成的空元素序列

请注意，给序列命名时，该序列不能再与其他序列聚合。如果您想识别您的序列但仍然可以与其他视图聚合，作为一种妥协，您可以通过调用 `(tag("flow", "events"))`  来使用 <<Tags>> 作为名称例子。.

=== Tags

Every metric will have a `type` tag in common, which value will be either `Flux` or `Mono` depending on the publisher's nature.

允许用户向其响应式链中添加自定义标签:
====
[source,java]
----
listenToEvents()
    .name("events") <1>
    .tag("source", "kafka") <2>
    .metrics() <3>
    .doOnNext(event -> log.info("Received {}", event))
    .delayUntil(this::processEvent)
    .retry()
    .subscribe();
----
<1> 此阶段的每个指标都将被标识为 "events".
<2> 设置自定义标签 "source" 值为 "kafka".
<3> 除上述常见标签外,所有报告的指标还将分配有 "source = kafka" 标签.
====

Please note that depending on the monitoring system you're using, using a name can be considered mandatory when using tags, since it would otherwise result in a different set of tags between two default-named sequences.
Some systems like Prometheus might also require to have the exact same set of tags for each metric with the same name.
