在 Reactor 中，sink 是一个允许以独立方式安全手动触发信号的类，创建一个类似 `Publisher` 的结构，能够处理多个 `Subscriber`（`unicast()` 类型除外）。

在 3.5.0 之前，还有一套已经被淘汰的 `Processor` 实现。

[[sinks-intro]]
= 使用 `Sinks.One` 和 `Sinks.Many` 从多个线程安全地生产

从下游订阅者的角度来看，由 reactor-core 暴露的 `Sinks` 需要确保多线程使用被检测到，并且不会导致违反规范或未定义的行为。当使用 `tryEmit*`  API 时，并行调用会快速失败。当使用 `emit*`  API 时，提供的 `EmissionFailureHandler` 可能允许重试连接(例如。busy looping)，否则 sink 将以一个错误终止.

这是对 `Processor.onNext` 的改进。它必须从外部同步，否则从下游订阅者的角度来看会导致未定义的行为.

[NOTE]
====
Processors 既是一种特别的发布者(`Publisher`)又是一种订阅者(`Subscriber`).
它们最初的目的是作为一个中间步骤的可能表示，然后可以在 Reactive Streams 实现之间共享。然而，在 Reactor 中，这些步骤是由 `Publisher` 之类的操作符表示的。

第一次遇到 `Processor` 时，一个常见的错误是试图直接从 `Subscriber` 接口调用公开的 `onNext`, `onComplete` 和 `onError`  方法。

这样的手动调用应该小心进行，特别是在 Reactive Streams 规范之外的同步调用。Processors 实际上可能略微有用，除非遇到需要传递基于 Reactive Streams 的 API 的 `Subscriber` 而不是公开 `Publisher` 的.

Sinks 通常是更好的选择。在 Reactor 中，sink 是一个允许安全手动触发信号的类。它可以与订阅关联(从操作符内部)，也可以完全独立.
====

`Sinks` 建造者对象(builder) 为主要支持的 producer 类型提供了一个引导性 API.
您可以发现 `Flux` 中识别一些行为,例如 `onBackpressureBuffer`.

====
[source,java]
----
Sinks.Many<Integer> replaySink = Sinks.many().replay().all();
----
====

多个生产者线程可以通过执行以下操作在接收器上并发生成数据：

====
[source,java]
----
//thread1
replaySink.emitNext(1, EmitFailureHandler.FAIL_FAST);

//thread2, later
replaySink.emitNext(2, EmitFailureHandler.FAIL_FAST);

//thread3, concurrently with thread 2
//would retry emitting for 2 seconds and fail with EmissionException if unsuccessful
replaySink.emitNext(3, EmitFailureHandler.busyLooping(Duration.ofSeconds(2)));

//thread3, concurrently with thread 2
//would return FAIL_NON_SERIALIZED
EmitResult result = replaySink.tryEmitNext(4);


----
====

[NOTE]
====
使用 `busyLooping` 时，请注意返回的 `EmitFailureHandler` 实例不能重复使用，例如，
它应该是每个 `emitNext` 调用一次 `busyLooping`。
此外，建议使用 100 毫秒以上的超时，因为较小的值没有实际意义。
====

`Sinks.Many` 可以作为 `Flux` 展现给下游消费者, 如下:

====
[source,java]
----
Flux<Integer> fluxView = replaySink.asFlux();
fluxView
	.takeWhile(i -> i < 10)
	.log()
	.blockLast();
----
====

相似的, `Sinks.Empty` 和 `Sinks.One` 可以使用 `asMono()` 方法 将其视为 `Mono`.


`Sinks` 分类:

. `many().multicast()`: a sink that will transmit only newly pushed data to its subscribers, honoring their backpressure (newly pushed as in "after the subscriber's subscription").
. `many().unicast()`: same as above, with the twist that data pushed before the first subscriber registers is buffered.
. `many().replay()`: a sink that will replay a specified history size of pushed data to new subscribers then continue pushing new data live.
. `one()`: a sink that will play a single element to its subscribers
. `empty()`: a sink that will play a terminal signal only to its subscribers (error or complete), but can still be viewed as a `Mono<T>` (notice the generic type `<T>`).

[[sinks-overview]]
= 可用的 Sinks 的概述

== Sinks.many().unicast().onBackpressureBuffer(args?)

A unicast `Sinks.Many` can deal with backpressure by using an internal buffer.
The trade-off is that it can have _at most one_ `Subscriber`.

The basic unicast sink is created via `Sinks.many().unicast().onBackpressureBuffer()`.
But there are a few additional `unicast` static factory methods in `Sinks.many().unicast()` allowing finer tuning.

For instance, by default, it is unbounded: if you push any amount of data through it while
its `Subscriber` has not yet requested data, it buffers all of the data.
You can change this by providing a custom `Queue` implementation for the internal
buffering in the `Sinks.many().unicast().onBackpressureBuffer(Queue)` factory m



ethod.
If that queue is bounded, the sink could reject the push of a value when the buffer
is full and not enough requests from downstream have been received.

== Sinks.many().multicast().onBackpressureBuffer(args?)

A multicast `Sinks.Many` can emit to several subscribers while honoring backpressure for each of its subscribers.
Subscribers receive only the signals pushed through the sink after they have subscribed.

The basic multicast sink is created via `Sinks.many().multicast().onBackpressureBuffer()`.

By default, if all of its subscribers are cancelled (which basically means they have all
un-subscribed), it clears its internal buffer and stops accepting new subscribers.
You can tune this by using the `autoCancel` parameter in the `multicast` static factory methods
under `Sinks.many().multicast()`.

== Sinks.many().multicast().directAllOrNothing()

A multicast `Sinks.Many` with a simplistic handling of backpressure: if *any* of the subscribers
is too slow (has zero demand), the `onNext` is dropped for *all* subscribers.

However, the slow subscribers are not terminated and once the slow subscribers have started
requesting again, all will resume receiving elements pushed from there on.

Once the `Sinks.Many` has terminated (usually through its `emitError(Throwable)` or
`emitComplete()` methods being called), it lets more subscribers subscribe but replays the
termination signal to them immediately.

== Sinks.many().multicast().directBestEffort()

A multicast `Sinks.Many` with a best effort handling of backpressure: if a subscriber
is too slow (has zero demand), the `onNext` is dropped for *this slow subscriber only*.

However, the slow subscribers are not terminated and once they have started requesting again
they will resume receiving newly pushed elements.

Once the `Sinks.Many` has terminated (usually through its `emitError(Throwable)` or
`emitComplete()` methods being called), it lets more subscribers subscribe but replays the
termination signal to them immediately.

== Sinks.many().replay()

A replay `Sinks.Many` caches emitted elements and replays them to late subscribers.

It can be created in multiple configurations:

* Caching a limited history (`Sinks.many().replay().limit(int)`) or an unbounded history (`Sinks.many().replay().all()`).
* Caching a time-based replay window (`Sinks.many().replay().limit(Duration)`).
* Caching a combination of history size and time window (`Sinks.many().replay().limit(int, Duration)`).

Additional overloads for fine tuning of the above can also be found under `Sinks.many().replay()`, as well
as a variant that allows caching of a single element (`latest()` and `latestOrDefault(T)`).

== Sinks.unsafe().many()

Advanced users and operators builders might want to consider using `Sinks.unsafe().many()`
which will provide the same `Sinks.Many` factories _without_ the extra producer thread safety.
As a result there will be less overhead per sink, since thread-safe sinks have to detect multi-threaded access.

Library developers should not expose unsafe sinks but can use them internally in a controlled
calling environment where they can ensure external synchronization of the calls that lead to
`onNext`, `onComplete` and `onError` signals, in respect of the Reactive Streams specification.

== Sinks.one()

This method directly construct a simple instance of `Sinks.One<T>`.
This flavor of `Sinks` is viewable as a `Mono` (through its `asMono()` view method), and
has slightly different `emit` methods to better convey this Mono-like semantics:

* `emitValue(T value)` generates an `onNext(value)` signal and - in most implementations - will also trigger an implicit `onComplete()`
* `emitEmpty()` generates an isolated `onComplete()` signal, intended as generating the equivalent of an empty `Mono`
* `emitError(Throwable t)` generates an `onError(t)` signal

`Sinks.one()` accepts _one_ call of any of these methods, effectively generating a `Mono`
that either completed with a value, completed empty or failed.

== Sinks.empty()

This method directly constructs a simple instance of `Sinks.Empty<T>`.
This flavor of `Sinks` is like `Sinks.One<T>`, except it doesn't offer the `emitValue` method.

As a result, it can only generates a `Mono` that completes empty or fails.

The sink is still typed with a generic `<T>` despite being unable to trigger an `onNext`,
because it allows easy composition and inclusion in chains of operators that require a specific type.
