=== 关于背压和重塑请求的方法


在 Reactor 中实现背压时,通过向上游发送请求,将消费者压力传播回源. 当前请求的总和有时被称为当前 "`demand`" 或 "`pending request`". 需求的上限为 `Long.MAX_VALUE`,表示无限制的请求(意思是 "尽可能快地生成"-基本禁用背压).

在订阅时,当第一个请求来自 final subscriber ,但是以下最直接的订阅方式立即触发 `了Long.MAX_VALUE` 的无限制请求:

* `subscribe()` 大多数基于 lambda 的变体(具有 `Consumer<Subscription>` 的变体除外)
* `block()`, `blockFirst()` 和 `blockLast()`
* 遍历一个 `toIterable()` 或 `toStream()`

自定义原始请求的最简单方法是使用 `BaseSubscriber` 进行预订,并覆盖 `hookOnSubscribe` 方法,如以下示例所示:

====
[source,java]
----
Flux.range(1, 10)
    .doOnRequest(r -> System.out.println("request of " + r))
    .subscribe(new BaseSubscriber<Integer>() {

      @Override
      public void hookOnSubscribe(Subscription subscription) {
        request(1);
      }

      @Override
      public void hookOnNext(Integer integer) {
        System.out.println("Cancelling after having received " + integer);
        cancel();
      }
    });
----
====

上面的代码段打印出以下内容:

====
[source]
----
request of 1
Cancelling after having received 1
----
====

WARNING: 当你修改请求操作的时候,你必须注意让 `subscriber` 向上提出足够的需求, 否则上游的 `Flux` 可能会被“卡住”.所以 `BaseSubscriber` 在进行扩展的时候要覆盖 `hookOnSubscribe` 和 `onNext`,这样你至少会调用 `request` 一次.

==== 使用操作符改变下游需求

要记住的一件事是,上游链中的每个操作符都可以调整在订阅表达的需求. 一个典型的情况是 `buffer(N)` 运算符: 如果接收到一个  `request(2)`,则解释为对两个完整缓冲区的需求.
结果,由于缓冲区需要将 `N` 个元素视为已满,因此缓冲区运算符会将请求重塑为 `2 x N`.

您可能还已经注意到,某些运算符的变体采用了  `prefetch` 的 `int` 输入参数. 这是另一类修改下游请求的运算符. 这些通常是处理内部序列的运算符,是从每个传入元素(例如 `flatMap`)扩展 出 `Publisher` 的.

*Prefetch* 是一种调整对这些内部序列发出的初始请求的方法.如果未指定,则大多数这些运算符的开头为 `32`.

这些操作符通常还会实现  *replenishing optimization*: 一旦操作符看到预请求的 `75%` 得到满足,它就会从上游重新请求 `75%`. 进行启发式优化,以便这些操作能够主动预测即将到来的请求.

最后,几个运算符可让您直接调整请求: `limitRate` and `limitRequest`.

`limitRate(N)` 拆分下游请求,以便将它们以较小的速度传到上游. 例如,对 `limitRate(10)` 发出的 `100` 个请求最多将导致 `10` 个 `10` 个请求传到上游.
注意,以这种形式,`limitRate` 实际上实现了前面讨论的补充优化.

运算符还有一个变体,还可以让您调整数量(在变体中称为 `lowTide`): `limitRate(highTide, lowTide)`. 选择 `lowTide` 0 会导致严格的  `highTide` 请求批次,
而不是通过 replenishing 策略进一步重做的批次.

`limitRequest(N)`, 另一方面,将下游请求限制为最大总需求. 它将总计达 `N` 个请求.如果单个请求未使总需求超过 `N`,则该特定请求将完全传到上游. 源地址发出该 amount 后,`limitRequest` 认为序列已完成,向下游发送 `onComplete` 信号, 然后取消源.