[[deployment.cloud]]
== 部署到云端
Spring Boot 的可执行 jar 已为大多数流行的云 PaaS (平台即服务) 提供商提供.  这些提供程序往往要求您 "自带容器".  他们管理应用程序流程 (不是专门用于 Java 应用程序) ,因此他们需要一个中间层,以使您的应用程序适应云中正在运行的流程的概念.

两家受欢迎的云提供商,Heroku 和 Cloud Foundry,采用了 "`buildpack`" 方法.  buildpack 将部署的代码包装在启动应用程序所需的任何内容中.  它可能是 JDK,可能是对 `Java`,嵌入式 Web 服务器或成熟的应用程序服务器的调用.
一个 buildpack 是可插入的,但是理想情况下,您应该能够通过尽可能少的自定义来获得它.  这减少了您无法控制的功能的占用空间.  它使开发和生产环境之间的差异最小化.

理想情况下,您的应用程序像 Spring Boot 可执行 jar 一样,具有打包运行所需的一切.

在本节中,我们研究如何使在 "`Getting Started`" 部分中开发的 <<getting-started#getting-started.first-application, 简单应用程序>>启动并在云中运行.

[[deployment.cloud.cloud-foundry]]
=== Cloud Foundry
如果未指定其他 buildpacks,Cloud Foundry 将提供默认的 buildpacks.  Cloud Foundry https://github.com/cloudfoundry/java-buildpack[Java buildpack] 对 Spring 应用程序 (包括 Spring Boot) 提供了出色的支持.  您可以部署独立的可执行 jar 应用程序以及传统的 `.war` 打包应用程序.

一旦构建了应用程序 (例如,使用 `mvn clean package`) 并 https://docs.cloudfoundry.org/cf-cli/install-go-cli.html[安装了 `cf` 命令行工具],就可以使用 `cf push` 命令部署应用程序,并替换已编译的 `.jar` 的路径.
推送应用程序之前,请确保已使用 https://docs.cloudfoundry.org/cf-cli/getting-started.html#login[`cf` 命令行客户端登录].  下面的行显示了使用 `cf push` 命令部署应用程序:

[source,shell,indent=0,subs="verbatim"]
----
	$ cf push acloudyspringtime -p target/demo-0.0.1-SNAPSHOT.jar
----

NOTE: 在前面的示例中,我们用 `acloudyspringtime` 替换您给 `cf` 作为应用程序名称的任何值.

有关更多选项,请参阅 https://docs.cloudfoundry.org/cf-cli/getting-started.html#push[`cf push` 文档].  如果在同一目录中存在 Cloud Foundry https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html[`manifest.yml`] 文件,则将其考虑.

此时,`cf` 开始上载您的应用程序,产生类似于以下示例的输出:

[indent=0,subs="verbatim,quotes"]
----
	Uploading acloudyspringtime... *OK*
	Preparing to start acloudyspringtime... *OK*
	-----> Downloaded app package (*8.9M*)
	-----> Java Buildpack Version: v3.12 (offline) | https://github.com/cloudfoundry/java-buildpack.git#6f25b7e
	-----> Downloading Open Jdk JRE
	       Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.6s)
	-----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (found in cache)
	       Memory Settings: -Xss349K -Xmx681574K -XX:MaxMetaspaceSize=104857K -Xms681574K -XX:MetaspaceSize=104857K
	-----> Downloading Container Certificate Trust Store 1.0.0_RELEASE from https://java-buildpack.cloudfoundry.org/container-certificate-trust-store/container-certificate-trust-store-1.0.0_RELEASE.jar (found in cache)
	       Adding certificates to .java-buildpack/container_certificate_trust_store/truststore.jks (0.6s)
	-----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (found in cache)
	Checking status of app 'acloudyspringtime'...
	  0 of 1 instances running (1 starting)
	  ...
	  0 of 1 instances running (1 starting)
	  ...
	  0 of 1 instances running (1 starting)
	  ...
	  1 of 1 instances running (1 running)

	App started
----


恭喜你！ 该应用程序现已上线！

应用程序上线后,可以使用 `cf apps` 命令验证已部署应用程序的状态,如以下示例所示:

[source,shell,indent=0,subs="verbatim"]
----
	$ cf apps
	Getting applications in ...
	OK

	name                 requested state   instances   memory   disk   urls
	...
	acloudyspringtime    started           1/1         512M     1G     acloudyspringtime.cfapps.io
	...
----

一旦 Cloud Foundry 确认已部署了您的应用程序,您就应该能够在给定的URI上找到该应用程序.  在前面的示例中,您可以在  `\https://acloudyspringtime.cfapps.io/` 上找到它.

[[deployment.cloud.cloud-foundry.binding-to-services]]
==== 绑定到服务
默认情况下,有关正在运行的应用程序的元数据以及服务连接信息作为环境变量 (例如: `$VCAP_SERVICES`) 暴露给应用程序.  该架构决定是由于 Cloud Foundry 的多语言 (可以将任何语言和平台支持为 buildpack) 所决定的.  过程范围的环境变量与语言无关.

环境变量并非总是使用最简单的 API,因此 Spring Boot 会自动提取它们并将数据平整为可通过 Spring 的 `Environment` 抽象访问的属性,如以下示例所示:

include::code:MyBean[]

所有 Cloud Foundry 属性均以 `vcap` 为前缀.  您可以使用 `vcap` 属性来访问应用程序信息 (例如,应用程序的公共 URL) 和服务信息 (例如,数据库凭据) .  有关完整的详细信息,请参见  {spring-boot-module-api}/cloud/CloudFoundryVcapEnvironmentPostProcessor.html['`CloudFoundryVcapEnvironmentPostProcessor`'] Javadoc.

TIP: https://github.com/pivotal-cf/java-cfenv/[Java CFEnv] 项目更适合诸如配置数据源之类的任务.

[[deployment.cloud.kubernetes]]
=== Kubernetes

Spring Boot 通过检查环境中的 `"*_SERVICE_HOST"` 和 `"*_SERVICE_PORT"` 变量来自动检测 Kubernetes 部署环境. 您可以使用  `spring.main.cloud-platform` 配置属性覆盖此检测.

Spring Boot 帮助您 <<features#features.spring-application.application-availability,管理应用程序的状态>>,并 <<actuator#actuator.endpoints.kubernetes-probes,使用 Actuator 通过 HTTP Kubernetes 探针>>将其导出.

[[deployment.cloud.kubernetes.container-lifecycle]]
==== Kubernetes 容器生命周期
当 Kubernetes 删除应用程序实例时,关机过程会同时涉及多个子系统: shutdown hooks,注销服务,将实例从负载均衡器中删除... 因为这些关机进程并行发生 (并且由于分布式系统的性质) , 有一个窗口,在此期间可以将流量路由到也已开始其关闭处理的 Pod.

您可以在 preStop 处理程序中配置睡眠执行,以避免将请求路由到已经开始关闭的 Pod. 此睡眠时间应足够长,以使新请求停止路由到 Pod,并且其持续时间因部署而异. 可以通过 pod 配置文件中的 PodSpec 来配置 preStop 处理程序,如下所示:

[source,yaml,indent=0,subs="verbatim"]
----
	spec:
	  containers:
	  - name: "example-container"
	    image: "example-image"
	    lifecycle:
	      preStop:
	        exec:
	          command: ["sh", "-c", "sleep 10"]
----

一旦停止前挂钩完成,SIGTERM 将 被发送到容器,并且将 <<web#web.graceful-shutdown,正常关机>>,从而允许完成所有剩余的运行中请求.

NOTE: 当 Kubernetes 向 pod 发送 SIGTERM 信号时，它会等待一个称为终止宽限期的指定时间（默认为 30 秒）。
如果容器在宽限期后仍在运行，则会向它们发送 SIGKILL 信号并强制删除。
如果 pod 需要超过 30 秒才能关闭，这可能是因为您增加了 `spring.lifecycle.timeout-per-shutdown-phase`，请确保通过设置 `terminationGracePeriodSeconds` 选项来增加终止宽限期 在 Pod YAML 中。

[[deployment.cloud.heroku]]
=== Heroku
Heroku 是另一个流行的 PaaS 平台.  要自定义 Heroku 构建,您需要提供一个 `Procfile`,该文件提供了部署应用程序所需的内容.   Heroku 为 Java 应用程序分配了一个要使用的 `port` ,然后确保可以路由到外部 URI.

您必须配置您的应用程序以监听正确的端口.  以下示例显示了我们的入门 REST 应用程序的 `Procfile`:

[indent=0]
----
	web: java -Dserver.port=$PORT -jar target/demo-0.0.1-SNAPSHOT.jar
----

Spring Boot 使 `-D` 参数成为可从Spring `Environment` 实例访问的属性.  `server.port` 配置属性被馈送到嵌入式 Tomcat,Jetty  或 Undertow 实例,然后在启动时使用该端口.  `$PORT` 环境变量是由 Heroku PaaS 分配给我们的.

这应该是您需要的一切.  Heroku 部署最常见的部署工作流程是  `git push` 将代码推送生产环境,如以下示例所示:

[source,shell,indent=0,subs="verbatim"]
----
	$ git push heroku main
----

Which will result in the following:

[indent=0,subs="verbatim,quotes"]
----
	Initializing repository, *done*.
	Counting objects: 95, *done*.
	Delta compression using up to 8 threads.
	Compressing objects: 100% (78/78), *done*.
	Writing objects: 100% (95/95), 8.66 MiB | 606.00 KiB/s, *done*.
	Total 95 (delta 31), reused 0 (delta 0)

	-----> Java app detected
	-----> Installing OpenJDK... *done*
	-----> Installing Maven... *done*
	-----> Installing settings.xml... *done*
	-----> Executing: mvn -B -DskipTests=true clean install

	       [INFO] Scanning for projects...
	       Downloading: https://repo.spring.io/...
	       Downloaded: https://repo.spring.io/... (818 B at 1.8 KB/sec)
			....
	       Downloaded: https://s3pository.heroku.com/jvm/... (152 KB at 595.3 KB/sec)
	       [INFO] Installing /tmp/build_0c35a5d2-a067-4abc-a232-14b1fb7a8229/target/...
	       [INFO] Installing /tmp/build_0c35a5d2-a067-4abc-a232-14b1fb7a8229/pom.xml ...
	       [INFO] ------------------------------------------------------------------------
	       [INFO] *BUILD SUCCESS*
	       [INFO] ------------------------------------------------------------------------
	       [INFO] Total time: 59.358s
	       [INFO] Finished at: Fri Mar 07 07:28:25 UTC 2014
	       [INFO] Final Memory: 20M/493M
	       [INFO] ------------------------------------------------------------------------

	-----> Discovering process types
	       Procfile declares types -> *web*

	-----> Compressing... *done*, 70.4MB
	-----> Launching... *done*, v6
	       https://agile-sierra-1405.herokuapp.com/ *deployed to Heroku*

	To git@heroku.com:agile-sierra-1405.git
	 * [new branch]      main -> main
----

您的应用程序现在应该已经在 Heroku 上启动并运行了.  有关更多详细信息,请参阅将Spring Boot https://devcenter.heroku.com/articles/deploying-spring-boot-apps-to-heroku[应用程序部署到 Heroku].

[[deployment.cloud.openshift]]
=== OpenShift
https://www.openshift.com/[OpenShift] 是 Kubernetes 容器编排平台的 Red Hat 公共 (和企业) 扩展.  与 Kubernetes 相似,OpenShift 具有许多用于安装基于 Spring Boot 的应用程序的选项.

OpenShift 提供了许多资源来描述如何部署 Spring Boot 应用程序,包括:

* https://blog.openshift.com/using-openshift-enterprise-grade-spring-boot-deployments/[使用 S2I 构建器]
* https://access.redhat.com/documentation/en-us/reference_architectures/2017/html-single/spring_boot_microservices_on_red_hat_openshift_container_platform_3/[Architecture 指南]
* https://blog.openshift.com/using-spring-boot-on-openshift/[在 Wildfly 上作为传统的 Web 应用程序运行]
* https://blog.openshift.com/openshift-commons-briefing-96-cloud-native-applications-spring-rhoar/[OpenShift Commons Briefing]

[[deployment.cloud.aws]]
=== Amazon Web Services (AWS)
Amazon Web Services 提供了多种安装基于 Spring Boot 的应用程序的方式,既可以作为传统的 Web 应用程序 (war) ,也可以作为具有嵌入式 Web 服务器的可执行 jar 文件安装.  选项包括:

* AWS Elastic Beanstalk
* AWS Code Deploy
* AWS OPS Works
* AWS Cloud Formation
* AWS Container Registry

每个都有不同的功能和定价模型.  在本文档中,我们仅描述最简单的选项: AWS Elastic Beanstalk.

[[deployment.cloud.aws.beanstalk]]
==== AWS Elastic Beanstalk
如官方的 https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_Java.html[Elastic Beanstalk Java 指南] 中所述,部署Java 应用程序有两个主要选项.  您可以使用 "`Tomcat Platform`" 或 "`Java SE platform`".

[[deployment.cloud.aws.beanstalk.tomcat-platform]]
===== 使用 Tomcat 平台
该选项适用于产生 war 文件的 Spring Boot 项目.  无需特殊配置.  您只需要遵循官方指南即可.

[[deployment.cloud.aws.beanstalk.java-se-platform]]
===== 使用 Java SE 平台
此选项适用于产生 jar 文件并运行嵌入式 Web 容器的 Spring Boot 项目.  Elastic Beanstalk 环境在端口 80 上运行 nginx 实例来代理在端口 5000 上运行的实际应用程序. 要对其进行配置,请将以下行添加到 `application.properties` 文件:

[indent=0]
----
	server.port=5000
----


[TIP]
.上传二进制文件而不是源文件
====
默认情况下,Elastic Beanstalk 上传源码并在 AWS 中进行编译.  但是,最好改为上传二进制文件.  为此,请在 `.elasticbeanstalk/config.yml` 文件中添加类似于以下内容的行:

[source,xml,indent=0,subs="verbatim"]
----
	deploy:
		artifact: target/demo-0.0.1-SNAPSHOT.jar
----
====

[TIP]
.通过设置环境类型来降低成本
====
默认情况下,Elastic Beanstalk 环境是负载平衡的.  负载均衡器的成本很高.  为避免该费用,请按照 https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-create-wizard.html#environments-create-wizard-capacity[Amazon文档中] 的说明将环境类型设置为  "`Single instance`".  您还可以使用 CLI 和以下命令来创建单实例环境:

[indent=0]
----
	eb create -s
----
====

[[deployment.cloud.aws.summary]]
==== 简介
这是使用 AWS 的最简单方法之一,但还有更多内容需要介绍,例如如何将 Elastic Beanstalk 集成到任何 CI/CD 工具中,如何使用Elastic Beanstalk Maven 插件而不是 CLI 等等.  有一篇 https://exampledriven.wordpress.com/2017/01/09/spring-boot-aws-elastic-beanstalk-example/[博客文章] 详细介绍了这些主题.

[[deployment.cloud.boxfuse]]
=== CloudCaptain 和 Amazon Web Services
https://cloudcaptain.sh/[CloudCaptain] 的工作原理是将您的 Spring Boot 可执行 jar 或 war 变成一个最小的 VM 镜像,该镜像可以在 VirtualBox 或 AWS 上部署.  CloudCaptain 与 Spring Boot 进行了深度集成,并使用 Spring Boot 配置文件中的信息自动配置端口和运行状况检查 URL.  CloudCaptain 在生成的镜像以及它提供的所有资源 (实例,安全组,弹性负载均衡器等) 中都利用了此信息.

创建 https://console.cloudcaptain.sh[CloudCaptain  帐户],将其连接到您的 AWS 帐户,安装 Boxfuse Client 的最新版本,并确保该应用程序已由 Maven 或 Gradle 构建 (通过使用例如 `mvn clean package`) 后,您可以 使用与以下类似的命令将您的 Spring Boot 应用程序部署到AWS:

[source,shell,indent=0,subs="verbatim"]
----
	$ boxfuse run myapp-1.0.jar -env=prod
----

有关更多选项,请参见 https://cloudcaptain.sh/docs/commandline/run.html[`boxfuse run` documentation].  如果当前目录中存在 https://cloudcaptain.sh/docs/commandline/#configuration[`boxfuse.conf`]   文件,则将其考虑.

TIP: 默认情况下,CloudCaptain 在启动时会激活一个名为 `boxfuse` 的 Spring 配置文件.  如果您的可执行 jar 或 war 包含  https://cloudcaptain.sh/docs/payloads/springboot.html#configuration[`application-boxfuse.properties`]  文件,则 CloudCaptain 的配置将基于其包含的属性.

此时,CloudCaptain 为您的应用程序创建一个镜像,然后上传该镜像,并在 AWS 上配置和启动必要的资源,其输出类似于以下示例:

[indent=0,subs="verbatim"]
----
	Fusing Image for myapp-1.0.jar ...
	Image fused in 00:06.838s (53937 K) -> axelfontaine/myapp:1.0
	Creating axelfontaine/myapp ...
	Pushing axelfontaine/myapp:1.0 ...
	Verifying axelfontaine/myapp:1.0 ...
	Creating Elastic IP ...
	Mapping myapp-axelfontaine.boxfuse.io to 52.28.233.167 ...
	Waiting for AWS to create an AMI for axelfontaine/myapp:1.0 in eu-central-1 (this may take up to 50 seconds) ...
	AMI created in 00:23.557s -> ami-d23f38cf
	Creating security group boxfuse-sg_axelfontaine/myapp:1.0 ...
	Launching t2.micro instance of axelfontaine/myapp:1.0 (ami-d23f38cf) in eu-central-1 ...
	Instance launched in 00:30.306s -> i-92ef9f53
	Waiting for AWS to boot Instance i-92ef9f53 and Payload to start at https://52.28.235.61/ ...
	Payload started in 00:29.266s -> https://52.28.235.61/
	Remapping Elastic IP 52.28.233.167 to i-92ef9f53 ...
	Waiting 15s for AWS to complete Elastic IP Zero Downtime transition ...
	Deployment completed successfully. axelfontaine/myapp:1.0 is up and running at https://myapp-axelfontaine.boxfuse.io/
----

您的应用程序现在应该已启动并在 AWS 上运行.

请参阅有关在 https://cloudcaptain.sh/blog/spring-boot-ec2.html[EC2 上部署 Spring Boot 应用程序] 的博客文章以及 https://cloudcaptain.sh/docs/payloads/springboot.html[CloudCaptain Spring Boot 集成的文档] ,以开始使用 Maven 构建来运行该应用程序.

[[deployment.cloud.azure]]
=== Azure
此 https://spring.io/guides/gs/spring-boot-for-azure/[入门指南] 将引导您将 Spring Boot 应用程序部署到 https://azure.microsoft.com/en-us/ services/spring-cloud/[Azure Spring Cloud] 或 https://docs.microsoft.com/en-us/azure/app-service/overview[Azure App Service]。

[[deployment.cloud.google]]
=== Google Cloud
Google Cloud 有多个选项可用于启动 Spring Boot 应用程序.  最容易上手的可能是 App Engine,但您也可以找到在 Container Engine 的容器中或 Compute Engine 的虚拟机上运行 Spring Boot 的方法.

要在 App Engine 中运行,您可以先在用户界面中创建一个项目,该项目将为您设置一个唯一的标识符,并还设置 HTTP 路由.  将 Java 应用程序添加到项目中,并将其保留为空,然后使用  https://cloud.google.com/sdk/install[Google Cloud SDK] 从命令行或 CI 构建将 Spring Boot 应用程序推送到该插槽中.

App Engine Standard 要求您使用 WAR 包装.  请按照 https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/appengine-java8/springboot-helloworld/README.md[这些步骤]  将 App Engine 标准应用程序部署到 Google Cloud.

另外,App Engine Flex 要求您创建一个 `app.yaml` 文件来描述您的应用程序所需的资源.  通常,您将此文件放在 `src/main/appengine` 中,它应类似于以下文件:

[source,yaml,indent=0,subs="verbatim"]
----
	service: "default"

	runtime: "java"
	env: "flex"

	runtime_config:
	  jdk: "openjdk8"

	handlers:
	- url: "/.*"
	  script: "this field is required, but ignored"

	manual_scaling:
	  instances: 1

	health_check:
	  enable_health_check: false

	env_variables:
	  ENCRYPT_KEY: "your_encryption_key_here"
----

您可以通过将项目 ID 添加到构建配置中来部署应用程序 (例如,使用 Maven 插件) ,如以下示例所示:

[source,xml,indent=0,subs="verbatim"]
----
	<plugin>
		<groupId>com.google.cloud.tools</groupId>
		<artifactId>appengine-maven-plugin</artifactId>
		<version>1.3.0</version>
		<configuration>
			<project>myproject</project>
		</configuration>
	</plugin>
----

然后使用  `mvn appengine:deploy` 进行部署 (如果您需要先进行身份验证,则构建会失败) .
