[[deployment.installing]]
== 安装 Spring Boot 应用程序
除了使用 `java -jar` 运行 Spring Boot 应用程序之外,还可以为 Unix 系统制作完全可执行的应用程序.  完全可执行的 jar 可以像其他可执行二进制文件一样执行,也可以在 <<deployment#deployment.installing.nix-services,,`init.d` 或 `systemd` 中注册>>.  这使得在普通生产环境中安装和管理 Spring Boot 应用程序变得非常容易.

CAUTION: 完全可执行的 jar 通过将额外的脚本嵌入文件的开头来工作.  当前,某些工具不接受此格式,因此您可能无法始终使用此技术.  例如,`jar -xf` 可能在无提示的情况下无法提取出已完全可执行的 jar 或 war.
建议仅当您打算直接执行 jar 或 war 时才使其完全可执行,而不是使用 `java -jar` 来运行它或将其部署到 servlet 容器中.

CAUTION: 不能使 zip64 格式的 jar 文件完全可执行.  尝试这样做将导致直接或使用 `java -jar` 执行时将 jar 文件报告为已损坏.  包含一个或多个 zip64 格式嵌套 jar 的标准格式 jar 文件可以完全执行.

要使用 Maven 创建 "`完全可执行`" 的 jar,请使用以下插件配置:

[source,xml,indent=0,subs="verbatim"]
----
	<plugin>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-maven-plugin</artifactId>
		<configuration>
			<executable>true</executable>
		</configuration>
	</plugin>
----

以下示例显示了等效的 Gradle 配置:

[source,gradle,indent=0,subs="verbatim"]
----
	tasks.named('bootJar') {
		launchScript()
	}
----

然后,您可以通过输入 `./my-application.jar` (其中 `my-application` 是 artifacts 的名称) 来运行您的应用程序.  包含 jar 的目录用作应用程序的工作目录.

[[deployment.installing.supported-operating-systems]]
=== 支持的操作系统
默认脚本支持大多数 Linux 发行版,并已在 CentOS 和 Ubuntu 上进行了测试.  其他平台,例如 OS X 和 FreeBSD,则需要使用自定义的 `EmbeddedLaunchScript`.

[[deployment.installing.nix-services]]
=== Unix/Linux 服务
通过使用 `init.d` 或 `systemd`,可以轻松地将 Spring Boot 应用程序作为 `Unix/Linux` 服务启动.

[[deployment.installing.nix-services.init-d]]
==== 作为 init.d 服务安装 (System V)
如果您将 Spring Boot 的 Maven 或 Gradle 插件配置为生成 <<deployment#deployment.installing, 完全可执行的 jar>>,并且不使用自定义的 `EmbeddedLaunchScript`,则您的应用程序可以用作 `init.d` 服务.  为此,将 jar 链接到 `init.d` 以支持标准的 `start`, `stop`, `restart`, 和 `status` 命令.

该脚本支持以下功能:

* 以拥有 jar 文件的用户身份启动服务
* 使用 `/var/run/<appname>/<appname>.pid` 跟踪应用程序的 PID
* 将控制台日志写入 `/var/log/<appname>.log`

假设您在 `/var/myapp` 中安装了 Spring Boot 应用程序,要将 Spring Boot 应用程序安装为 `init.d` 服务,请创建一个符号链接,如下所示:

[source,shell,indent=0,subs="verbatim"]
----
	$ sudo ln -s /var/myapp/myapp.jar /etc/init.d/myapp
----

安装后,您可以按照通常的方式启动和停止服务.  例如,在基于 Debian 的系统上,可以使用以下命令启动它:

[source,shell,indent=0,subs="verbatim"]
----
	$ service myapp start
----

TIP: 如果您的应用程序无法启动,请检查写入  `/var/log/<appname>.log` 的日志文件中是否有错误.

您还可以使用标准操作系统工具将应用程序标记为自动启动.  例如,在 Debian 上,您可以使用以下命令:

[source,shell,indent=0,subs="verbatim"]
----
	$ update-rc.d myapp defaults <priority>
----

[[deployment.installing.nix-services.init-d.securing]]
===== 保护 init.d 服务
NOTE: 以下是一组有关如何保护作为 `init.d` 服务运行的 Spring Boot 应用程序的准则.  它并不旨在详尽列出增强应用程序及其运行环境所应进行的所有工作.

当以 root 身份执行时 (例如使用 root 来启动 init.d 服务时) ,默认的可执行脚本以 `RUN_AS_USER` 环境变量中指定的用户身份运行应用程序.
如果未设置环境变量,则使用拥有 jar 文件的用户.  您永远不要以 `root` 用户身份运行Spring Boot应用程序,因此 `RUN_AS_USER` 绝不应该是 root 用户,并且应用程序的 jar 文件也绝不应该由 root 用户拥有.  而是创建一个特定用户来运行您的应用程序并设置 `RUN_AS_USER` 环境变量,或使用 `chown` 使其成为 jar 文件的所有者,如以下示例所示:

[source,shell,indent=0,subs="verbatim"]
----
	$ chown bootapp:bootapp your-app.jar
----

在这种情况下,默认的可执行脚本以 `bootapp` 用户身份运行该应用程序.

TIP: 为了减少应用程序的用户帐户被盗的机会,您应该考虑阻止它使用登录外壳程序.  例如,您可以将帐户的外壳程序设置为 `/usr/sbin/nologin`.

您还应该采取措施防止修改应用程序的 jar 文件.  首先,配置其权限,使其不能被写入,只能由其所有者读取或执行,如以下示例所示:

[source,shell,indent=0,subs="verbatim"]
----
	$ chmod 500 your-app.jar
----

其次,如果您的应用程序或运行该应用程序的帐户受到威胁,您还应采取措施限制损害.  如果攻击者确实获得了访问权限,则他们可以使 jar 文件可写并更改其内容.  防止这种情况发生的一种方法是使用 `chattr` 使其不可变,如以下示例所示:

[source,shell,indent=0,subs="verbatim"]
----
	$ sudo chattr +i your-app.jar
----

这将阻止任何用户 (包括 root 用户) 修改 jar.

如果使用 root 来控制应用程序的服务,并且您使用 <<deployment#deployment.installing.nix-services.script-customization.when-running.conf-file, 使用 `.conf` 文件>> 来自定义其启动,则 root 用户将读取并评估 `.conf` 文件.
应该相应地对其进行保护.  使用 `chmod`,以便文件只能由所有者读取,并使用 `chown` 使 root 用户成为所有者,如以下示例所示:

[source,shell,indent=0,subs="verbatim"]
----
	$ chmod 400 your-app.conf
	$ sudo chown root:root your-app.conf
----

[[deployment.installing.nix-services.system-d]]
==== 作为 systemd 服务安装
`systemd` 是 System V init 系统的后继产品,现在被许多现代Linux发行版使用.  尽管您可以继续在 `systemd` 中使用 `init.d` 脚本,但也可以通过使用 `systemd` 的 '`service`' 脚本来启动 Spring Boot 应用程序.

假设您在 `/var/myapp` 中安装了 Spring Boot 应用程序,要将 Spring Boot 应用程序安装为 `systemd` 服务,请创建一个名为 `myapp.service` 的脚本并将其放在 `/etc/systemd/system` 目录中.  以下脚本提供了一个示例:

[indent=0]
----
	[Unit]
	Description=myapp
	After=syslog.target

	[Service]
	User=myapp
	ExecStart=/var/myapp/myapp.jar
	SuccessExitStatus=143

	[Install]
	WantedBy=multi-user.target
----

IMPORTANT: 切记更改应用程序的 `Description`, `User` 和  `ExecStart` 字段.

NOTE: `ExecStart` 字段未声明脚本操作命令,这意味着默认情况下使用 `run` 命令.

请注意,与作为 `init.d` 服务运行时不同,运行应用程序的用户,PID 文件和控制台日志文件由 `systemd` 本身管理,因此必须通过在  '`service`'  脚本中使用适当的字段进行配置.  有关更多详细信息,请查阅 https://www.freedesktop.org/software/systemd/man/systemd.service.html[服务单元配置手册页] .

要将应用程序标记为在系统启动时自动启动,请使用以下命令:

[source,shell,indent=0,subs="verbatim"]
----
	$ systemctl enable myapp.service
----

有关更多详细信息,请参考 `man systemctl`.

[[deployment.installing.nix-services.script-customization]]
==== 自定义启动脚本
由 Maven 或 Gradle 插件编写的默认嵌入式启动脚本可以通过多种方式进行自定义.  对于大多数人来说,使用默认脚本以及一些自定义设置通常就足够了.  如果发现无法自定义所需的内容,请使用 `embeddedLaunchScript` 选项完全编写自己的文件.

[[deployment.installing.nix-services.script-customization.when-written]]
===== 编写后自定义启动脚本
在将启动脚本写入 jar 文件时,自定义启动脚本的元素通常很有意义.  例如,`init.d` 脚本可以提供  "`description`".  由于您已经预先了解了描述 (并且无需更改) ,因此在生成jar时也可以提供它.

要自定义书面元素,请使用 Spring Boot Maven 插件的 `embeddedLaunchScriptProperties` 选项或 {spring-boot-gradle-plugin-docs}#packaging-executable-configuring-launch-script[Spring Boot Gradle插件的 `launchScript` 的 `properties` 属性].

默认脚本支持以下属性替换:

[cols="1,3,3,3"]
|===
| Name | Description | Gradle default | Maven default

| `mode`
| The script mode.
| `auto`
| `auto`

| `initInfoProvides`
| The `Provides` section of "`INIT INFO`"
| `${task.baseName}`
| `${project.artifactId}`

| `initInfoRequiredStart`
| `Required-Start` section of "`INIT INFO`".
| `$remote_fs $syslog $network`
| `$remote_fs $syslog $network`

| `initInfoRequiredStop`
| `Required-Stop` section of "`INIT INFO`".
| `$remote_fs $syslog $network`
| `$remote_fs $syslog $network`

| `initInfoDefaultStart`
| `Default-Start` section of "`INIT INFO`".
| `2 3 4 5`
| `2 3 4 5`

| `initInfoDefaultStop`
| `Default-Stop` section of "`INIT INFO`".
| `0 1 6`
| `0 1 6`

| `initInfoShortDescription`
| `Short-Description` section of "`INIT INFO`".
| Single-line version of `${project.description}` (falling back to `${task.baseName}`)
| `${project.name}`

| `initInfoDescription`
| `Description` section of "`INIT INFO`".
| `${project.description}` (falling back to `${task.baseName}`)
| `${project.description}` (falling back to `${project.name}`)

| `initInfoChkconfig`
| `chkconfig` section of "`INIT INFO`"
| `2345 99 01`
| `2345 99 01`

| `confFolder`
| The default value for `CONF_FOLDER`
| Folder containing the jar
| Folder containing the jar

| `inlinedConfScript`
| Reference to a file script that should be inlined in the default launch script.
  This can be used to set environmental variables such as `JAVA_OPTS` before any external config files are loaded
|
|

| `logFolder`
| Default value for `LOG_FOLDER`.
  Only valid for an `init.d` service
|
|

| `logFilename`
| Default value for `LOG_FILENAME`.
  Only valid for an `init.d` service
|
|

| `pidFolder`
| Default value for `PID_FOLDER`.
  Only valid for an `init.d` service
|
|

| `pidFilename`
| Default value for the name of the PID file in `PID_FOLDER`.
  Only valid for an `init.d` service
|
|

| `useStartStopDaemon`
| Whether the `start-stop-daemon` command, when it is available, should be used to control the process
| `true`
| `true`

| `stopWaitTime`
| Default value for `STOP_WAIT_TIME` in seconds.
  Only valid for an `init.d` service
| 60
| 60
|===



[[deployment.installing.nix-services.script-customization.when-running]]
===== 运行时自定义脚本
对于在编写 jar 之后需要自定义脚本的项目,可以使用环境变量或 <<deployment#deployment.installing.nix-services.script-customization.when-running.conf-file, 配置文件>>.

默认脚本支持以下环境属性:

[cols="1,6"]
|===
| 变量 | 描述

| `MODE`
| 操作的 `mode`.  默认值取决于 jar 的构建方式,但通常是自动的 (这意味着它会通过检查 `init.d` 目录中的符号链接来尝试猜测它是否为初始化脚本) .  如果要在前台运行脚本,可以将其显式设置为服务,以便 `stop\|start\|status\|restart` 命令可以运行或 `run`.

| `RUN_AS_USER`
| 将用于运行应用程序的用户.  未设置时,将使用拥有 jar 文件的用户.

| `USE_START_STOP_DAEMON`
| 是否可以使用 `start-stop-daemon` 命令来控制该过程.  默认为 `true`.

| `PID_FOLDER`
| pid 目录的根名称 (默认为 `/var/run`) .

| `LOG_FOLDER`
| 放置日志文件的目录的名称 (默认为 `/var/log`) .

| `CONF_FOLDER`
| 从中读取 `.conf` 文件的目录的名称 (默认情况下与 jar 文件相同的目录) .

| `LOG_FILENAME`
| `LOG_FOLDER` 中的日志文件名 (默认为 `<appname>.log`) .

| `APP_NAME`
| 应用程序的名称.  如果 jar 是从符号链接运行的,则脚本会猜测应用程序名称.  如果它不是符号链接,或者您要显式设置应用程序名称,则这将很有用.

| `RUN_ARGS`
| 传递给程序 (Spring Boot 应用程序) 的参数.

| `JAVA_HOME`
| 默认情况下,使用 `PATH` 查找 `Java` 可执行文件的位置,但是如果 `$JAVA_HOME/bin/java` 中有可执行文件,则可以显式设置它.

| `JAVA_OPTS`
| 启动 JVM 时传递给 JVM 的选项.

| `JARFILE`
| jar 文件的显式位置,以防脚本用于启动实际上未嵌入的 jar.

| `DEBUG`
| 如果不为空,则在 shell 进程中设置 `-x` 标志,从而易于查看脚本中的逻辑.

| `STOP_WAIT_TIME`
| 停止应用程序之前强制关闭的等待时间 (以秒为单位)  (默认为 `60` ) .
|===

NOTE:  `PID_FOLDER`, `LOG_FOLDER`, 和 `LOG_FILENAME` 变量仅对 `init.d` 服务有效.  对于 `systemd`,通过使用  '`service`' 脚本进行等效的自定义.  有关更多详细信息,请参见 https://www.freedesktop.org/software/systemd/man/systemd.service.html[服务单元配置手册页] .

[[deployment.installing.nix-services.script-customization.when-running.conf-file]]
除了 `JARFILE` 和 `APP_NAME`,可以使用 `.conf` 文件配置上一节中列出的设置.  该文件应位于 jar 文件的旁边,并且具有相同的名称,但后缀为 `.conf` 而不是 `.jar`.  例如,名为 `/var/myapp/myapp.jar` 的 jar 使用名为 `/var/myapp/myapp.conf` 的配置文件,如以下示例所示:

.myapp.conf
[indent=0,subs="verbatim"]
----
	JAVA_OPTS=-Xmx1024M
	LOG_FOLDER=/custom/log/folder
----

TIP:  如果您不喜欢将配置文件放在 jar 文件旁边,则可以设置 `CONF_FOLDER` 环境变量以自定义配置文件的位置.

要了解有关适当保护此文件的信息,请参阅 <<deployment#deployment.installing.nix-services.init-d.securing,保护 init.d 服务的准则>>.

[[deployment.installing.windows-services]]
=== Microsoft Windows 服务

可以使用 https://github.com/kohsuke/winsw[`winsw`] 将 Spring Boot 应用程序作为 Windows 服务启动.

(https://github.com/snicoll-scratches/spring-boot-daemon[一个单独维护的示例]) 逐步说明了如何为 Spring Boot 应用程序创建 Windows 服务.
