[[servlet-authentication-ldap]]
= LDAP 认证

LDAP(Lightweight Directory Access Protocol)  通常被组织用作用户信息的中央存储库和身份验证服务.  它还可以用于存储应用程序用户的角色信息.

当 Spring Security 配置为 <<servlet-authentication-unpwd-input,接受用户名/密码>> 进行身份验证时,将使用 Spring Security 的基于 LDAP 的身份验证.  但是,尽管利用了用户名/密码进行身份验证,它也无法使用 `UserDetailsService` 集成,
因为在 <<servlet-authentication-ldap-bind,绑定身份验证>> 中 LDAP 服务器不会返回密码,因此应用程序无法执行密码验证.

关于如何配置 LDAP 服务器,有许多不同的方案,以便 Spring Security 的 LDAP 提供程序是完全可配置的.  它使用单独的策略接口进行身份验证和角色检索,并提供可配置为处理各种情况的默认实现.

[[servlet-authentication-ldap-prerequisites]]
== 前提条件

在尝试将其与 Spring Security 结合使用之前,您应该熟悉 LDAP.  以下链接很好地介绍了相关概念,并提供了使用免费 LDAP 服务器 OpenLDAP 设置目录的指南:  http://www.zytrax.com/books/ldap/[http://www.zytrax.com/books/ldap/].
熟悉用于从 Java 访问 LDAP 的 JNDI API 可能也很有用.  我们在 LDAP 提供程序中未使用任何第三方 LDAP 库(Mozilla,JLDAP 等) ,但是 Spring LDAP 被广泛使用,因此如果您计划添加自己的自定义项,则对该项目有些熟悉可能会很有用.

使用 LDAP 身份验证时,重要的是要确保正确配置 LDAP 连接池.  如果您不熟悉该操作,可以参考 https://docs.oracle.com/javase/jndi/tutorial/ldap/connect/config.html[Java LDAP 文档].

// FIXME:
// ldap server
//	embedded (both java and xml)
//	external
// authentication
//	bind
//	password
//	roles
//	search, etc (other APIs)

[[servlet-authentication-ldap-embedded]]
== 设置嵌入式 LDAP 服务器

您需要做的第一件事是确保您有一个 LDAP 服务器来指向您的配置.  为简单起见,通常最好从嵌入式 LDAP 服务器开始.  Spring Security 支持使用以下任一方法:

* <<servlet-authentication-ldap-unboundid,嵌入式 UnboundID 服务器>>
* <<servlet-authentication-ldap-apacheds,嵌入式 ApacheDS 服务器>>

在下面的示例中,我们将以下内容作为  `users.ldif`  暴露为类路径资源,以使用用户 `user` 和 `admin` 来初始化嵌入式 LDAP 服务器,这两个用户的密码均为 `password`.

.users.ldif
====
[source,ldif]
----
dn: ou=groups,dc=springframework,dc=org
objectclass: top
objectclass: organizationalUnit
ou: groups

dn: ou=people,dc=springframework,dc=org
objectclass: top
objectclass: organizationalUnit
ou: people

dn: uid=admin,ou=people,dc=springframework,dc=org
objectclass: top
objectclass: person
objectclass: organizationalPerson
objectclass: inetOrgPerson
cn: Rod Johnson
sn: Johnson
uid: admin
userPassword: password

dn: uid=user,ou=people,dc=springframework,dc=org
objectclass: top
objectclass: person
objectclass: organizationalPerson
objectclass: inetOrgPerson
cn: Dianne Emu
sn: Emu
uid: user
userPassword: password

dn: cn=user,ou=groups,dc=springframework,dc=org
objectclass: top
objectclass: groupOfNames
cn: user
uniqueMember: uid=admin,ou=people,dc=springframework,dc=org
uniqueMember: uid=user,ou=people,dc=springframework,dc=org

dn: cn=admin,ou=groups,dc=springframework,dc=org
objectclass: top
objectclass: groupOfNames
cn: admin
uniqueMember: uid=admin,ou=people,dc=springframework,dc=org
----
====

[[servlet-authentication-ldap-unboundid]]
=== 嵌入式 UnboundID 服务器

如果您希望使用 https://ldap.com/unboundid-ldap-sdk-for-java/[UnboundID],请指定以下依赖:

.UnboundID Dependencies
====
.Maven
[source,xml,role="primary",subs="verbatim,attributes"]
----
<dependency>
	<groupId>com.unboundid</groupId>
	<artifactId>unboundid-ldapsdk</artifactId>
	<version>{unboundid-ldapsdk-version}</version>
	<scope>runtime</scope>
</dependency>
----

.Gradle
[source,groovy,role="secondary",subs="verbatim,attributes"]
----
depenendencies {
	runtimeOnly "com.unboundid:unboundid-ldapsdk:{unboundid-ldapsdk-version}"
}
----
====

然后,您可以使用 `EmbeddedLdapServerContextSourceFactoryBean` 配置嵌入式 LDAP 服务器，这将指示 Spring Security 启动内存中的 LDAP 服务器：

.嵌入式 LDAP 服务器配置
====
.Java
[source,java,role="primary"]
----
@Bean
public EmbeddedLdapServerContextSourceFactoryBean contextSourceFactoryBean() {
	return EmbeddedLdapServerContextSourceFactoryBean.fromEmbeddedLdapServer();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun contextSourceFactoryBean(): EmbeddedLdapServerContextSourceFactoryBean {
    return EmbeddedLdapServerContextSourceFactoryBean.fromEmbeddedLdapServer()
}
----
====

或者，您可以手动配置嵌入式 LDAP 服务器。
如果您选择这种方法，您将负责管理嵌入式 LDAP 服务器的生命周期。

.Explicit Embedded LDAP Server Configuration
====
.Java
[source,java,role="primary"]
----
@Bean
UnboundIdContainer ldapContainer() {
	return new UnboundIdContainer("dc=springframework,dc=org",
				"classpath:users.ldif");
}
----

.XML
[source,xml,role="secondary"]
----
<b:bean class="org.springframework.security.ldap.server.UnboundIdContainer"
	c:defaultPartitionSuffix="dc=springframework,dc=org"
	c:ldif="classpath:users.ldif"/>
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun ldapContainer(): UnboundIdContainer {
    return UnboundIdContainer("dc=springframework,dc=org","classpath:users.ldif")
}
----
====

[[servlet-authentication-ldap-apacheds]]
=== 嵌入式 ApacheDS 服务器

[NOTE]
====
Spring Security 使用不再维护的 ApacheDS1.x.  不幸的是,ApacheDS 2.x 仅发布了里程碑版本,没有稳定版本.  一旦有稳定的ApacheDS 2.x 版本可用,我们将考虑进行更新.
====

如果希望使用 https://directory.apache.org/apacheds/[Apache DS],请指定以下依赖:

.ApacheDS Dependencies
====
.Maven
[source,xml,role="primary",subs="+attributes"]
----
<dependency>
	<groupId>org.apache.directory.server</groupId>
	<artifactId>apacheds-core</artifactId>
	<version>{apacheds-core-version}</version>
	<scope>runtime</scope>
</dependency>
<dependency>
	<groupId>org.apache.directory.server</groupId>
	<artifactId>apacheds-server-jndi</artifactId>
	<version>{apacheds-core-version}</version>
	<scope>runtime</scope>
</dependency>
----

.Gradle
[source,groovy,role="secondary",subs="+attributes"]
----
depenendencies {
	runtimeOnly "org.apache.directory.server:apacheds-core:{apacheds-core-version}"
	runtimeOnly "org.apache.directory.server:apacheds-server-jndi:{apacheds-core-version}"
}
----
====

然后,您可以配置嵌入式 LDAP 服务器

.Embedded LDAP Server Configuration
====
.Java
[source,java,role="primary"]
----
@Bean
ApacheDSContainer ldapContainer() {
	return new ApacheDSContainer("dc=springframework,dc=org",
				"classpath:users.ldif");
}
----

.XML
[source,xml,role="secondary"]
----
<b:bean class="org.springframework.security.ldap.server.ApacheDSContainer"
	c:defaultPartitionSuffix="dc=springframework,dc=org"
	c:ldif="classpath:users.ldif"/>
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun ldapContainer(): ApacheDSContainer {
    return ApacheDSContainer("dc=springframework,dc=org", "classpath:users.ldif")
}
----
====

[[servlet-authentication-ldap-contextsource]]
== LDAP ContextSource

一旦有了 LDAP 服务器来将您的配置指向,就需要配置 Spring Security 来指向应该用于认证用户的 LDAP 服务器.
这是通过创建 LDAP  `ContextSource` 来完成的,该 LDAP `ContextSource` 等效于 JDBC `DataSource`.
如果您已经配置了一个 `EmbeddedLdapServerContextSourceFactoryBean`，Spring Security 将创建一个指向嵌入式 LDAP 服务器的 LDAP `ContextSource`。

.LDAP Context Source with Embedded LDAP Server
====
.Java
[source,java,role="primary"]
----
@Bean
public EmbeddedLdapServerContextSourceFactoryBean contextSourceFactoryBean() {
	EmbeddedLdapServerContextSourceFactoryBean contextSourceFactoryBean =
			EmbeddedLdapServerContextSourceFactoryBean.fromEmbeddedLdapServer();
	contextSourceFactoryBean.setPort(0);
	return contextSourceFactoryBean;
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun contextSourceFactoryBean(): EmbeddedLdapServerContextSourceFactoryBean {
    val contextSourceFactoryBean = EmbeddedLdapServerContextSourceFactoryBean.fromEmbeddedLdapServer()
    contextSourceFactoryBean.setPort(0)
    return contextSourceFactoryBean
}
----
====

或者，您可以显式配置 LDAP `ContextSource` 以连接到提供的 LDAP 服务器：

.LDAP Context Source
====
.Java
[source,java,role="primary"]
----
ContextSource contextSource(UnboundIdContainer container) {
	return new DefaultSpringSecurityContextSource("ldap://localhost:53389/dc=springframework,dc=org");
}
----

.XML
[source,xml,role="secondary"]
----
<ldap-server
	url="ldap://localhost:53389/dc=springframework,dc=org" />
----

.Kotlin
[source,kotlin,role="secondary"]
----
fun contextSource(container: UnboundIdContainer): ContextSource {
    return DefaultSpringSecurityContextSource("ldap://localhost:53389/dc=springframework,dc=org")
}
----
====

[[servlet-authentication-ldap-authentication]]
== 认证

Spring Security 的 LDAP 不支持使用 <<servlet-authentication-userdetailsservice,UserDetailsService>>,因为 LDAP 绑定身份验证不允许客户端读取密码,甚至不允许散列密码.  这意味着 Spring Security 无法读取密码然后对其进行身份验证.

因此,使用 `LdapAuthenticator` 接口实现了对 LDAP 支持.  `LdapAuthenticator` 接口还负责检索任何必需的用户属性.  这是因为对属性的权限可能取决于所使用的身份验证类型.
例如,如果以用户身份进行绑定,则可能有必要在用户自己的权限下阅读属性.

Spring Security 提供了两个 `LdapAuthenticator` 实现:

* <<servlet-authentication-ldap-bind>>
* <<servlet-authentication-ldap-pwd>>

[[servlet-authentication-ldap-bind]]
== 使用绑定身份验证

https://ldap.com/the-ldap-bind-operation/[绑定身份验证] 是使用 LDAP 身份验证用户的最常用机制.  在绑定身份验证中,用户凭据(即用户名和密码) 将提交给LDAP服务器以对其进行身份验证.
使用绑定身份验证的优点是不需要将用户的机密信息(即密码) 暴露给客户端,这有助于防止客户端泄露.

绑定身份验证配置的示例可以在下面找到.

.Bind Authentication
====
.Java
[source,java,role="primary",attrs="-attributes"]
----
@Bean
AuthenticationManager authenticationManager(BaseLdapPathContextSource contextSource) {
	LdapBindAuthenticationManagerFactory factory = new LdapBindAuthenticationManagerFactory(contextSource);
	factory.setUserDnPatterns("uid={0},ou=people");
	return factory.createAuthenticationManager();
}
----

.XML
[source,xml,role="secondary",attrs="-attributes"]
----
<ldap-authentication-provider
	user-dn-pattern="uid={0},ou=people"/>
----

.Kotlin
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Bean
fun authenticationManager(contextSource: BaseLdapPathContextSource): AuthenticationManager {
    val factory = LdapBindAuthenticationManagerFactory(contextSource)
    factory.setUserDnPatterns("uid={0},ou=people")
    return factory.createAuthenticationManager()
}
----
====

这个简单的示例将通过使用提供的模式替换用户登录名并尝试使用该登录密码将该用户绑定来获取该用户的DN.  如果所有用户都存储在目录中的单个节点下,这样做是可以的.  相反,如果您希望配置 LDAP 搜索过滤器来定位用户,则可以使用以下方法:

.Bind Authentication with Search Filter
====
.Java
[source,java,role="primary",attrs="-attributes"]
----
@Bean
AuthenticationManager authenticationManager(BaseLdapPathContextSource contextSource) {
	LdapBindAuthenticationManagerFactory factory = new LdapBindAuthenticationManagerFactory(contextSource);
	factory.setUserSearchFilter("(uid={0})");
	factory.setUserSearchBase("ou=people");
	return factory.createAuthenticationManager();
}
----

.XML
[source,xml,role="secondary",attrs="-attributes"]
----
<ldap-authentication-provider
		user-search-filter="(uid={0})"
	user-search-base="ou=people"/>
----

.Kotlin
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Bean
fun authenticationManager(contextSource: BaseLdapPathContextSource): AuthenticationManager {
    val factory = LdapBindAuthenticationManagerFactory(contextSource)
    factory.setUserSearchFilter("(uid={0})")
    factory.setUserSearchBase("ou=people")
    return factory.createAuthenticationManager()
}
----
====

如果与上面的 `ContextSource` <<servlet-authentication-ldap-contextsource,定义>> 一起使用,它将使用  `+(uid={0})+` 作为过滤器在DN `ou=people,dc=springframework,dc=org` 下执行搜索.
再次用用户登录名代替过滤器名称中的参数,因此它将搜索 `uid` 属性等于用户名的条目.  如果未提供用户搜索库,则将从根目录执行搜索.

[[servlet-authentication-ldap-pwd]]
== 使用密码认证

密码比较是将用户提供的密码与存储库中存储的密码进行比较.  可以通过检索 password 属性的值并在本地对其进行检查来完成此操作,也可以通过执行 LDAP "`compare`" 操作来完成,在该操作中,将提供的密码传递给服务器进行比较,并且永远不会检索到真实的密码值.  如果使用随机盐正确地对密码进行了哈希处理,则无法进行 LDAP 比较.

.Minimal Password Compare Configuration
====
.Java
[source,java,role="primary"]
----
@Bean
AuthenticationManager authenticationManager(BaseLdapPathContextSource contextSource) {
	LdapPasswordComparisonAuthenticationManagerFactory factory = new LdapPasswordComparisonAuthenticationManagerFactory(
			contextSource, NoOpPasswordEncoder.getInstance());
	factory.setUserDnPatterns("uid={0},ou=people");
	return factory.createAuthenticationManager();
}
----

.XML
[source,xml,role="secondary",attrs="-attributes"]
----
<ldap-authentication-provider
		user-dn-pattern="uid={0},ou=people">
	<password-compare />
</ldap-authentication-provider>
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun authenticationManager(contextSource: BaseLdapPathContextSource?): AuthenticationManager? {
    val factory = LdapPasswordComparisonAuthenticationManagerFactory(
        contextSource, NoOpPasswordEncoder.getInstance()
    )
    factory.setUserDnPatterns("uid={0},ou=people")
    return factory.createAuthenticationManager()
}
----
====

可以在下面找到带有一些自定义设置的更高级的配置.

.Password Compare Configuration
====
.Java
[source,java,role="primary"]
----
@Bean
AuthenticationManager authenticationManager(BaseLdapPathContextSource contextSource) {
	LdapPasswordComparisonAuthenticationManagerFactory factory = new LdapPasswordComparisonAuthenticationManagerFactory(
			contextSource, new BCryptPasswordEncoder());
	factory.setUserDnPatterns("uid={0},ou=people");
	factory.setPasswordAttribute("pwd");  // <1>
	return factory.createAuthenticationManager();
}
----

.XML
[source,xml,role="secondary",attrs="-attributes"]
----
<ldap-authentication-provider
		user-dn-pattern="uid={0},ou=people">
	<password-compare password-attribute="pwd"> <!--1-->
		<password-encoder ref="passwordEncoder" /> <!--2-->
	</password-compare>
</ldap-authentication-provider>
<b:bean id="passwordEncoder"
	class="org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder" />
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun authenticationManager(contextSource: BaseLdapPathContextSource): AuthenticationManager {
    val factory = LdapPasswordComparisonAuthenticationManagerFactory(
        contextSource, BCryptPasswordEncoder()
    )
    factory.setUserDnPatterns("uid={0},ou=people")
    factory.setPasswordAttribute("pwd") // <1>
    return factory.createAuthenticationManager()
}
----
====

<1> 将密码属性指定为 `pwd`


== LdapAuthoritiesPopulator

Spring Security 的 `LdapAuthoritiesPopulator` 用于确定返回给用户的授权.
以下示例显示了如何配置 `LdapAuthoritiesPopulator`：

.LdapAuthoritiesPopulator Configuration
====
.Java
[source,java,role="primary",attrs="-attributes"]
----
@Bean
LdapAuthoritiesPopulator authorities(BaseLdapPathContextSource contextSource) {
	String groupSearchBase = "";
	DefaultLdapAuthoritiesPopulator authorities =
		new DefaultLdapAuthoritiesPopulator(contextSource, groupSearchBase);
	authorities.setGroupSearchFilter("member={0}");
	return authorities;
}

@Bean
AuthenticationManager authenticationManager(BaseLdapPathContextSource contextSource, LdapAuthoritiesPopulator authorities) {
	LdapBindAuthenticationManagerFactory factory = new LdapBindAuthenticationManagerFactory(contextSource);
	factory.setUserDnPatterns("uid={0},ou=people");
	factory.setLdapAuthoritiesPopulator(authorities);
	return factory.createAuthenticationManager();
}
----

.XML
[source,xml,role="secondary",attrs="-attributes"]
----
<ldap-authentication-provider
	user-dn-pattern="uid={0},ou=people"
	group-search-filter="member={0}"/>
----

.Kotlin
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Bean
fun authorities(contextSource: BaseLdapPathContextSource): LdapAuthoritiesPopulator {
    val groupSearchBase = ""
    val authorities = DefaultLdapAuthoritiesPopulator(contextSource, groupSearchBase)
    authorities.setGroupSearchFilter("member={0}")
    return authorities
}

@Bean
fun authenticationManager(
    contextSource: BaseLdapPathContextSource,
    authorities: LdapAuthoritiesPopulator): AuthenticationManager {
    val factory = LdapBindAuthenticationManagerFactory(contextSource)
    factory.setUserDnPatterns("uid={0},ou=people")
    factory.setLdapAuthoritiesPopulator(authorities)
    return factory.createAuthenticationManager()
}
----
====

== 激活目录

Active Directory 支持其自己的非标准身份验证选项,并且正常使用模式与标准 `LdapAuthenticationProvider` 不太吻合.
通常,身份验证是使用域用户名(格式为 `user@domain`) 而不是使用 LDAP 可分辨名称来执行的.  为了简化此操作,Spring Security 3.1 具有一个身份验证提供程序,该身份验证提供程序是针对典型的 Active Directory 设置而定制的.

配置 `ActiveDirectoryLdapAuthenticationProvider` 非常简单.  您只需要提供域名和提供服务器地址的 LDAP URL footnote:[也可以使用DNS查找来获取服务器的IP地址.  目前尚不支持此功能,但希望在以后的版本中可用.].  配置示例如下所示:

[NOTE]
====
还可以通过使用 DNS 查找来获取服务器的 IP 地址。
目前不支持，但希望在未来的版本中支持。
====

以下示例配置 Active Directory：

.Example Active Directory Configuration
====
.Java
[source,java,role="primary"]
----
@Bean
ActiveDirectoryLdapAuthenticationProvider authenticationProvider() {
	return new ActiveDirectoryLdapAuthenticationProvider("example.com", "ldap://company.example.com/");
}
----

.XML
[source,xml,role="secondary"]
----
<bean id="authenticationProvider"
        class="org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider">
	<constructor-arg value="example.com" />
	<constructor-arg value="ldap://company.example.com/" />
</bean>
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun authenticationProvider(): ActiveDirectoryLdapAuthenticationProvider {
    return ActiveDirectoryLdapAuthenticationProvider("example.com", "ldap://company.example.com/")
}
----
====
