[[appendix-faq]]
= Spring Security 常见问题解答

本章包含以下章节

* <<appendix-faq-general-questions>>
* <<appendix-faq-common-problems>>
* <<appendix-faq-architecture>>
* <<appendix-faq-howto>>

[[appendix-faq-general-questions]]
== 一般问题

本章回答了以下常见问题

* <<appendix-faq-other-concerns>>
* <<appendix-faq-web-xml>>
* <<appendix-faq-requirements>>
* <<appendix-faq-start-simple>>

[[appendix-faq-other-concerns]]
=== Spring Security 会满足我所有的应用程序安全性要求吗?

Spring Security 为您的身份验证和授权要求提供了一个非常灵活的框架,但是在构建安全应用程序时还需要考虑许多其他因素.  Web 应用程序容易受到各种您应该熟悉的攻击的攻击,最好在开始开发之前就进行攻击,因此您可以从一开始就在设计和编写代码时就牢记在心.  请访问 https://www.owasp.org/[OWASP web site],以获取有关 Web 应用程序开发人员面临的主要问题的信息,以及可以对他们使用的对策.

[[appendix-faq-web-xml]]
=== 为什么不使用 web.xml 安全性？

假设您正在开发基于 Spring 的企业应用程序.  您通常需要解决四个安全问题: 身份验证,Web 请求安全性,服务层安全性 (即,实现业务逻辑的方法) 和域对象实例安全性 (即不同的域对象具有不同的权限) .  牢记以下典型要求:

. __身份验证__: Servlet 规范提供了一种身份验证方法.  但是,您将需要配置容器以执行身份验证,这通常需要编辑特定于容器的 "realm" 设置.  这样就构成了不可移植的配置,如果您需要编写实际的 Java 类来实现容器的身份验证接口,则它甚至变得更加不可移植.
使用 Spring Security,您可以实现完全的可移植性-一直到 WAR 级别.  此外,Spring Security 还提供了经过生产验证的身份验证提供程序和机制,供您选择,这意味着您可以在部署时切换身份验证方法.  对于编写需要在未知目标环境中工作的产品的软件供应商而言,这特别有价值.

. __Web请求安全性:__ Servlet 规范提供了一种保护请求 URI 的方法.  但是,这些 URI 只能以 Servlet 规范自己的受限 URI 路径格式表示.  Spring Security 提供了一种更为全面的方法.
例如,您可以使用 Ant 路径或正则表达式,可以考虑 URI 的部分,而不仅仅是请求的页面 (例如,可以考虑 HTTP GET 参数) ,并且可以实现自己的配置数据的运行时源.
这意味着您的 Web 请求安全性可以在 Webapp 的实际执行过程中动态更改.

. __服务层和域对象安全性:__ Servlet 规范中缺少对服务层安全性或域对象实例安全性的支持,这表示对多层应用程序的严重限制.  通常,开发人员要么忽略这些要求,要么在其 MVC 控制器代码中实现安全逻辑 (或者更糟的是在视图内部) .  这种方法有严重的缺点:

.. __关注点分离:__ 授权是一个横切关注点,应照此实施.  MVC 控制器或实现授权代码的视图使测试控制器和授权逻辑更加困难,调试更加困难,并且通常会导致代码重复.

.. __对富客户端和 Web 服务的支持:__ 如果最终必须支持其他客户端类型,则嵌入在 Web 层中的任何授权代码都是不可重用的.  应该考虑到 Spring 远程出口商仅出口服务层 bean (而不是 MVC 控制器) .  这样,授权逻辑需要位于服务层中以支持多种客户端类型.

.. __分层问题:__ MVC 控制器或视图只是错误的体系结构层,无法实现有关服务层方法或域对象实例的授权决策.  尽管可以将主体传递到服务层以使其能够做出授权决策,但这样做会在每个服务层方法上引入一个附加参数.  一种更优雅的方法是使用 ThreadLocal 来容纳 Principal,尽管这可能会增加开发时间,以至于仅使用专用的安全框架就变得更加经济 (基于成本效益) .

.. __授权代码质量:__ Web 框架经常被提及为 "它们使做正确的事变得更容易,而做错事则更难".  安全框架是相同的,因为它们以抽象的方式设计用于多种用途.  从头开始编写自己的授权代码不会提供框架会提供的 "设计检查",而且内部授权代码通常将缺乏广泛部署,同行评审和新版本带来的改进.


对于简单的应用程序,servlet 规范安全性可能就足够了.  尽管在 Web 容器可移植性,配置要求,有限的 Web 请求安全性以及不存在的服务层和域对象实例安全性的上下文中进行考虑,但很清楚的是,为什么开发人员经常寻求替代解决方案.

[[appendix-faq-requirements]]
=== 需要哪些 Java 和 Spring Framework 版本?

Spring Security 3.0 和 3.1 至少需要 JDK 1.5,还至少需要 Spring 3.0.3.  理想情况下,您应该使用最新版本,以避免出现问题.

Spring Security 2.0.x 要求最低 JDK 版本为 1.4,并且是针对 Spring 2.0.x 构建的.  它也应该与使用 Spring 2.5.x 的应用程序兼容.

[[appendix-faq-start-simple]]
==== 我有一个复杂的场景。 有什么问题吗？

（这个答案通过处理特定场景来解决一般的复杂场景。）

假设您是 Spring Security 的新手，需要构建一个支持通过 HTTPS 进行 CAS 单点登录的应用程序，同时允许对某些 URL 在本地进行基本身份验证，并针对多个后端用户信息源（LDAP 和 JDBC）进行身份验证。
您复制了一些配置文件，但发现它不起作用。 有什么问题吗？

实际上,您需要先了解要使用的技术,然后才能成功使用它们构建应用程序.  安全性很复杂.  使用登录表单设置简单的配置,并使用 Spring Security 的命名空间来设置一些硬编码的用户,这是相当简单的.
转向使用支持的 JDBC 数据库也很容易。 但是，如果您试图直接跳到像这个场景这样复杂的部署场景，您几乎肯定会感到沮丧。 设置 CAS 等系统、配置 LDAP 服务器和正确安装 SSL 证书所需的学习曲线有了很大的提高。
所以你需要一步一个脚印。

从 Spring Security 的角度来看，您应该做的第一件事是遵循网站上的 "入门" 指南。 这将带您完成一系列启动和运行步骤，并了解框架的运作方式。 如果您使用其他您不熟悉的技术，
您应该做一些研究并尝试确保在将它们组合到一个复杂的系统之前可以单独使用它们。

[[appendix-faq-common-problems]]

本节解决人们在使用 Spring Security 时遇到的最常见问题：

== 常见问题

* 认证
** <<appendix-faq-bad-credentials>>
** <<appendix-faq-login-loop>>
** <<appendix-faq-anon-access-denied>>
** <<appendix-faq-cached-secure-page>>
** <<auth-exception-credentials-not-found>>
** <<appendix-faq-ldap-authentication>>
* 会话管理
** <<appendix-faq-concurrent-session-same-browser>>
** <<appendix-faq-new-session-on-authentication>>
** <<appendix-faq-tomcat-https-session>>
** <<appendix-faq-session-listener-missing>>
** <<appendix-faq-unwanted-session-creation>>
* 其他
** <<appendix-faq-forbidden-csrf>>
** <<appendix-faq-no-security-on-forward>>
** <<appendix-faq-method-security-in-web-context>>
** <<appendix-faq-no-filters-no-context>>
** <<appendix-faq-method-security-with-taglib>>

[[appendix-faq-bad-credentials]]
=== 当我尝试登录时,出现一条错误消息,提示"Bad Credentials".  怎么了?

这意味着认证失败.  并没有说明原因,因为最好避免提供可能有助于攻击者猜测帐户名或密码的详细信息.

这也意味着,如果您在论坛中提出此问题,除非您提供其他信息,否则您将无法获得答案.  与任何问题一样,您应该检查调试日志的输出,注意所有异常堆栈跟踪和相关消息.
在调试器中单步执行代码以查看身份验证失败的原因以及原因.
编写一个测试案例,在应用程序外部练习您的身份验证配置.  如果使用哈希密码,请确保存储在数据库中的值与应用程序中配置的 `PasswordEncoder` 产生的值完全相同.

[[appendix-faq-login-loop]]
=== 当我尝试登录时,我的应用程序进入 "endless loop(无限循环)",这是怎么回事?

无限循环和重定向到登录页面的常见用户问题是由于不小心将登录页面配置为 "`secured`" 资源引起的.  通过从安全过滤器链中排除登录页面或将其标记为需要 `ROLE_ANONYMOUS`,确保您的配置允许匿名访问登录页面.

如果您的 `AccessDecisionManager` 包含 `AuthenticatedVoter`,则可以使用属性 "IS_AUTHENTICATED_ANONYMOUSLY".  如果您使用标准命名空间配置设置,则该选项自动可用.

从 Spring Security 2.0.1 开始,当您使用基于命名空间的配置时,将在加载应用程序上下文时进行检查,并且如果登录页面似乎受到保护,则会记录一条警告消息.

[[appendix-faq-anon-access-denied]]
=== 我收到一条消息 "访问被拒绝 (用户是匿名用户) " 的异常. 怎么了?

这是调试级别的消息,它在匿名用户首次尝试访问受保护的资源时发生.

====
[source]
----
DEBUG [ExceptionTranslationFilter] - Access is denied (user is anonymous); redirecting to authentication entry point
org.springframework.security.AccessDeniedException: Access is denied
at org.springframework.security.vote.AffirmativeBased.decide(AffirmativeBased.java:68)
at org.springframework.security.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:262)
----
====

这是正常现象,无需担心.

[[appendix-faq-cached-secure-page]]
=== 为什么即使我退出了应用程序,仍然可以看到受保护的页面?

造成这种情况的最常见原因是您的浏览器已经缓存了该页面,并且您看到的是从浏览器缓存中检索到的副本.  通过检查浏览器是否确实在发送请求来验证这一点 (检查服务器访问日志,调试日志或使用合适的浏览器调试插件,例如 Firefox 的 "Tamper Data") .  这与 Spring Security 无关,您应该配置应用程序或服务器以设置适当的 Cache-Control 响应头.  请注意,永远不会缓存 SSL 请求.

[[auth-exception-credentials-not-found]]
=== 我收到一条消息  "An Authentication object was not found in the SecurityContext" 的异常. 怎么了?

这是另一条调试级别消息,该消息在匿名用户首次尝试访问受保护的资源时出现,但是在您的过滤器链配置中没有 `AnonymousAuthenticationFilter` 时出现.

====
[source]
----
DEBUG [ExceptionTranslationFilter] - Authentication exception occurred; redirecting to authentication entry point
org.springframework.security.AuthenticationCredentialsNotFoundException:
							An Authentication object was not found in the SecurityContext
at org.springframework.security.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:342)
at org.springframework.security.intercept.AbstractSecurityInterceptor.beforeInvocation(AbstractSecurityInterceptor.java:254)
----
====

这是正常现象,无需担心.

[[appendix-faq-ldap-authentication]]
=== 我无法使用 LDAP 身份验证.
我的配置有什么问题?

请注意,LDAP 目录的权限通常不允许您读取用户密码.  因此,通常无法使用 <<appendix-faq-what-is-userdetailservice,什么是 `UserDetailsService`>> 这一节,Spring Security 将存储的密码与用户提交的密码进行比较.  最常见的方法是使用 LDAP "绑定",这是 https://en.wikipedia.org/wiki/Lightweight_Directory_Access_Protocol[the LDAP protocol]支持的操作之一.
通过这种方法,Spring Security 通过尝试以用户身份验证目录来验证密码.

LDAP 认证最常见的问题是缺乏对目录服务器树结构和配置的了解.  不同公司的情况会有所不同,因此您必须自己找出来.  在将 Spring Security LDAP 配置添加到应用程序之前,最好使用标准 Java LDAP 代码 (不涉及 Spring Security) 编写一个简单的测试,并确保您可以使其首先工作.  例如,要验证用户身份,可以使用以下代码:

====
.Java
[source,java,role="primary"]
----

@Test
public void ldapAuthenticationIsSuccessful() throws Exception {
		Hashtable<String,String> env = new Hashtable<String,String>();
		env.put(Context.SECURITY_AUTHENTICATION, "simple");
		env.put(Context.SECURITY_PRINCIPAL, "cn=joe,ou=users,dc=mycompany,dc=com");
		env.put(Context.PROVIDER_URL, "ldap://mycompany.com:389/dc=mycompany,dc=com");
		env.put(Context.SECURITY_CREDENTIALS, "joespassword");
		env.put(Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.ldap.LdapCtxFactory");

		InitialLdapContext ctx = new InitialLdapContext(env, null);

}

----

.Kotlin
[source,kotlin,role="secondary"]
----
@Test
fun ldapAuthenticationIsSuccessful() {
    val env = Hashtable<String, String>()
    env[Context.SECURITY_AUTHENTICATION] = "simple"
    env[Context.SECURITY_PRINCIPAL] = "cn=joe,ou=users,dc=mycompany,dc=com"
    env[Context.PROVIDER_URL] = "ldap://mycompany.com:389/dc=mycompany,dc=com"
    env[Context.SECURITY_CREDENTIALS] = "joespassword"
    env[Context.INITIAL_CONTEXT_FACTORY] = "com.sun.jndi.ldap.LdapCtxFactory"
    val ctx = InitialLdapContext(env, null)
}
----
====

=== 会话管理

会话管理问题是论坛问题的常见来源.  如果您正在开发 Java Web 应用程序,则应了解如何在 Servlet 容器和用户浏览器之间维护会话.
您还应该了解安全和非安全 Cookie 的区别,以及使用 HTTP/HTTPS 以及在两者之间进行切换的含义.  Spring Security 与维护会话或提供会话标识符无关.  这完全由 servlet 容器处理.

[[appendix-faq-concurrent-session-same-browser]]
=== 我正在使用 Spring Security 的并发会话控制来防止用户一次登录多次.
登录后打开另一个浏览器窗口时,并不会阻止我再次登录.  为什么我可以多次登录?

浏览器通常每个浏览器实例维护一个会话.  您不能一次有两个单独的会话.  因此,如果您再次在另一个窗口或选项卡中登录,那么您将在同一会话中重新进行身份验证.  服务器对标签,窗口或浏览器实例一无所知.
它所看到的只是 HTTP 请求,并根据它们所包含的 `JSESSIONID` cookie 的值将它们与特定会话相关联.  当用户在会话期间进行身份验证时,Spring Security 的并发会话控件会检查其拥有的其他已身份验证会话的数量.  如果它们已经通过同一会话进行了身份验证,则重新身份验证将无效.

[[appendix-faq-new-session-on-authentication]]
=== 通过 Spring Security 进行身份验证时,为什么会话 ID 会更改?

使用默认配置,Spring Security 在用户认证时更改会话 ID.  如果您使用的是 Servlet 3.1 或更高版本的容器,则只需更改会话 ID.  如果您使用的是较旧的容器,Spring Security 将使现有会话无效,创建一个新会话,并将会话数据传输到新会话.  以这种方式改变会话标识符可以防止 "会话固定" 攻击.  您可以在网上和参考手册中找到有关此内容的更多信息.

[[appendix-faq-tomcat-https-session]]
=== 我正在使用 Tomcat (或其他一些 servlet 容器) ,并且已为登录页面启用 HTTPS,然后再切换回 HTTP.
它不起作用-经过身份验证后,我只能回到登录页面.

发生这种情况是因为在 HTTPS下创建的会话 (会话 cookie 标记为 "安全") 无法随后在 HTTP 下使用.  浏览器不会将 cookie 发送回服务器,并且任何会话状态都将丢失 (包括安全上下文信息) .  首先使用HTTP启动会话应该可以,因为会话 cookie 不会被标记为安全.
但是,Spring Security 的会话固定保护可能会对此产生干扰,因为它会导致通常使用安全标志将新的会话 ID Cookie 发送回用户的浏览器.
要解决此问题,您可以禁用 https://docs.spring.io/spring-security/site/docs/3.1.x/reference/springsecurity-single.html#ns-session-fixation[会话固定保护] ,但是在较新的 Servlet 容器中,您也可以配置会话 cookie,使其从不使用安全标志.  请注意,在 HTTP 和 HTTPS 之间切换通常不是一个好主意,因为任何完全使用 HTTP 的应用程序都容易受到中间人攻击.

[IMPORTANT]
====
为了真正确保安全,用户应开始使用 HTTPS 访问您的站点并继续使用它,直到注销为止.  即使从通过 HTTP 访问的页面上单击 HTTPS 链接也可能存在风险.
如果您需要更多说服力,请查看 https://github.com/moxie0/sslstrip/[sslstrip]之类的工具.
====

=== 我没有在 HTTP 和 HTTPS 之间切换,但是我的会话仍然丢失，发生了什么

通过交换会话 cookie 或向 URL 添加 `jsessionid` 参数来维护会话 (如果使用 JSTL 输出 URL,或者在 URL 上调用 `HttpServletResponse.encodeUrl` (例如,在重定向之前) ,则会自动发生.  禁用 cookie,并且您不重写 URL 以包含 `jsessionid`,则会话将丢失. 请注意,出于安全原因,首选使用 cookie,因为它不会在 URL 中暴露会话信息.

[[appendix-faq-session-listener-missing]]
=== 我正在尝试使用并发会话控制支持,但是即使我确定我已经注销并且没有超出允许的会话,它也不允许我重新登录.

确保已将监听器添加到 `web.xml` 文件. 必须确保在会话被销毁时通知 Spring Security 会话注册表. 没有它,会话信息将不会从注册表中删除.

以下示例在 `web.xml` 文件中添加了一个监听器：

====
[source,xml]
----
<listener>
		<listener-class>org.springframework.security.web.session.HttpSessionEventPublisher</listener-class>
</listener>
----
====

[[appendix-faq-unwanted-session-creation]]
=== 通过将 create-session 属性设置为 never,即使我未配置,Spring Security 也会在某个地方创建会话.

这通常意味着用户的应用程序正在某个地方创建会话,但是他们不知道该会话.  最常见的罪魁祸首是 JSP.  许多人不知道 JSP 默认创建会话.  为了防止 JSP 创建会话,请在页面顶部添加指令 `<%@ page session="false" %>` .

如果在确定创建会话的位置时遇到麻烦,可以添加一些调试代码来跟踪位置.  一种方法是将 `javax.servlet.http.HttpSessionListener` 添加到您的应用程序,该应用程序在 `sessionCreated` 方法中调用 `Thread.dumpStack()`.

[[appendix-faq-forbidden-csrf]]
=== 执行POST时收到403 Forbidden

如果为 HTTP POST 返回了 HTTP 403 Forbidden,但对于 HTTP GET 适用,则该问题很可能与 https://docs.spring.io/spring-security/site/docs/3.2.x/reference/htmlsingle/#csrf[CSRF]有关. 提供 CSRF 令牌或禁用 CSRF 保护 (不建议) .

[[appendix-faq-no-security-on-forward]]
=== 我正在使用RequestDispatcher将请求转发到另一个URL,但没有应用我的安全约束.

过滤器默认情况下不应用于转发或包含.  如果您确实希望将安全过滤器应用于转发和/或包含,则必须使用 `<dispatcher>` 元素 (`<filter-mapping>` 的子元素) 在 `web.xml` 中显式配置这些过滤器.

[[appendix-faq-method-security-in-web-context]]
=== 我已经在应用程序上下文中添加了 Spring Security 的 <global-method-security> 元素,但是如果我在 Spring MVC 控制器bean (Struts 操作等) 中添加了安全注解,那么它们似乎没有效果.

在 Spring Web 应用程序中,保存用于调度程序 Servlet 的 Spring MVC bean 的应用程序上下文通常与主应用程序上下文分开.  它通常在名为 `myapp-servlet.xml` 的文件中定义,其中 "myapp" 是在 `web.xml` 中分配给 Spring `DispatcherServlet` 的名称.
一个应用程序可以有多个 `DispatcherServlet`,每个都有自己独立的应用程序上下文.  这些  "`child`" 上下文中的 Bean 对应用程序的其余部分不可见.  "`parent`" 应用程序上下文由您在 `web.xml` 中定义的 `ContextLoaderListener` 加载,并且对所有子上下文可见.
通常在此父上下文中定义安全性配置,包括 `<global-method-security>` 元素) .  结果,由于无法从 `DispatcherServlet` 上下文中看到这些 bean,因此不会强制应用到这些 Web bean 中的方法的任何安全性约束.  您需要将 `<global-method-security>` 声明移至 Web 上下文,
或者将要保护的 bean 移至主应用程序上下文.

通常,我们建议在服务层而不是单个 Web 控制器上应用方法安全性.

[[appendix-faq-no-filters-no-context]]
=== 我有一个已经通过身份验证的用户,但是当我在某些请求期间尝试访问 SecurityContextHolder 时,`Authentication` 为 null.
为什么看不到用户信息?

如果使用与 URL 模式匹配的 `<intercept-url>` 元素中的属性 `filter ='none'` 从安全过滤器链中排除了该请求,则不会为该请求填充 `SecurityContextHolder`.  检查调试日志以查看请求是否正在通过过滤器链.   (您正在阅读调试日志,对吗? ) .

[[appendix-faq-method-security-with-taglib]]
=== 使用 URL 属性时,授权 JSP 标记不遵守我的方法安全注解.

当使用 `<sec:authorize>` 中的 `url` 属性时,方法安全性不会隐藏链接,因为我们不能轻易反向工程哪个 URL 映射到哪个控制器端点,因为控制器可以依赖 header,当前用户等来确定要调用的方法.

[[appendix-faq-architecture]]
== Spring Security Architecture Questions

本节解决常见的 Spring Security 架构问题：

. <<appendix-faq-where-is-class-x>>
. <<appendix-faq-namespace-to-bean-mapping>>
. <<appendix-faq-role-prefix>>
. <<appendix-faq-what-dependencies>>
. <<appendix-faq-apacheds-deps>>
. <<appendix-faq-what-is-userdetailservice>>


[[appendix-faq-where-is-class-x]]
=== 我怎么知道 X 属于哪个包类?

定位类的最佳方法是在 IDE 中安装 Spring Security 源代码.  该发行版包括项目分成的每个模块的源 jar.  将它们添加到项目源路径中,然后您可以直接导航到 Spring Security 类 (在 Eclipse 中为 `Ctrl-Shift-T`) .  这也使调试更加容易,并允许您通过直接查看异常发生的地方来查看异常情况,从而对异常进行故障排除.

[[appendix-faq-namespace-to-bean-mapping]]
=== 命名空间元素如何映射到常规 bean 配置?

在参考指南的命名空间附录中,概述了由命名空间创建的 bean.  在 https://spring.io/blog/2010/03/06/behind-the-spring-security-namespace/[blog.springsource.com] 上还有一篇详细的博客文章,名为 "Spring Security 命名空间的背后".
如果想知道全部细节,那么代码在 Spring Security 3.0 发行版的 `spring-security-config` 模块中.  您可能应该先阅读标准Spring Framework 参考文档中有关命名空间解析的章节.

[[appendix-faq-role-prefix]]
=== "ROLE_" 是什么意思,为什么我在角色名称上需要它?

Spring Security 具有基于投票者的架构,这意味着访问决策由一系列 `AccessDecisionVoters` 做出.  投票者根据为安全资源指定的 "`configuration attributes`" (例如方法调用) 进行操作.
使用这种方法,并非所有属性都可能与所有选民相关,并且选民需要知道何时应该忽略属性 (弃权) 以及何时应该投票基于属性值授予或拒绝访问权限.  最常见的投票者是 `RoleVoter`,默认情况下,只要找到带有 "ROLE_" 前缀的属性,投票者便会投票.  它将属性 (例如 "ROLE_USER") 与当前用户已分配的权限名称进行简单比较.  如果找到匹配项 (它们具有称为 "ROLE_USER" 的权限) ,则投票批准授予访问权限,否则投票拒绝访问.

可以通过设置 `RoleVoter` 的 `rolePrefix` 属性来更改前缀.  如果只需要在应用程序中使用角色,而无需其他自定义投票者,则可以将前缀设置为空字符串,在这种情况下,`RoleVoter` 会将所有属性视为角色.

[[appendix-faq-what-dependencies]]
=== 我如何知道要添加到我的应用程序中的哪些依赖才能与 Spring Security 一起使用?

这将取决于您使用的功能以及所开发的应用程序类型.  使用 Spring Security 3.0,将项目 jar 分为明显不同的功能区域,因此可以很容易地从应用程序需求中确定所需的 Spring Security jar.
所有应用程序都将需要 `spring-security-core` jar.  如果您要开发网络应用程序,则需要 `spring-security-web` jar.  如果您使用的是安全命名空间配置,则需要 `spring-security-config` jar; 要获得 LDAP 支持,则需要 `spring-security-ldap` jar等.

对于第三方 jar,情况并不总是那么明显.  一个好的起点是从预先构建的示例应用程序 `WEB-INF/lib` 目录之一复制那些目录.  对于基本应用程序,您可以从教程示例开始.  如果要对嵌入式测试服务器使用 LDAP,请以 LDAP 示例为起点.
参考手册还包括 {security-reference-url}#modules[附录]  列出了每个 Spring 的第一级依赖 安全模块,其中包含有关它们是否可选以及所需功能的一些信息.

如果您正在使用 maven 构建项目,则将适当的 Spring Security 模块作为依赖添加到 `pom.xml` 中,将自动提取框架所需的核心 jar.  如果需要, 任何在 Spring Security POM 文件中标记为 "可选" 的文件都必须添加到您自己的 `pom.xml` 文件中.

[[appendix-faq-apacheds-deps]]
=== 运行嵌入式 ApacheDS LDAP 服务器需要什么依赖?

如果您使用 Maven，则需要将以下内容添加到您的 `pom.xml` 文件中：

====
[source]
----

<dependency>
		<groupId>org.apache.directory.server</groupId>
		<artifactId>apacheds-core</artifactId>
		<version>1.5.5</version>
		<scope>runtime</scope>
</dependency>
<dependency>
		<groupId>org.apache.directory.server</groupId>
		<artifactId>apacheds-server-jndi</artifactId>
		<version>1.5.5</version>
		<scope>runtime</scope>
</dependency>

----
====

The other required jars should be pulled in transitively.

[[appendix-faq-what-is-userdetailservice]]
=== 什么是 UserDetailsService,我需要一个吗?

`UserDetailsService` 是 DAO 接口,用于加载特定于用户帐户的数据.  除了加载该数据以供框架中的其他组件使用外,它没有其他功能.  它不负责验证用户身份.  使用用户名/密码组合对用户进行身份验证通常由 `DaoAuthenticationProvider` 执行,该服务注入了 `UserDetailsService`,以允许它加载用户的密码 (和其他数据) ,以便将其与提交的值进行比较.
请注意,如果您使用的是 LDAP,<<appendix-faq-ldap-authentication,则此方法可能不起作用>>.

如果要自定义身份验证过程,则应自己实现 `AuthenticationProvider`.  请参阅此 https://spring.io/blog/2010/08/02/spring-security-in-google-app-engine/[博客文章],以获取将 Spring Security 身份验证与 Google App Engine 集成的示例.

[[appendix-faq-howto]]
== 常见的 "操作方法" 请求

本节解决有关 Spring Security 的最常见的 "How to" （或 "How do I"）问题：

. <<appendix-faq-extra-login-fields>>
. <<appendix-faq-matching-url-fragments>>
. <<appendix-faq-request-details-in-user-service>>
. <<appendix-faq-access-session-from-user-service>>
. <<appendix-faq-password-in-user-service>>
. <<appendix-faq-dynamic-url-metadata>>
. <<appendix-faq-ldap-authorities>>
. <<appendix-faq-namespace-post-processor>>


[[appendix-faq-extra-login-fields]]
=== 我需要登录的信息不仅仅是用户名.
如何添加对额外登录字段 (例如公司名称) 的支持?

这个问题在 Spring Security 论坛中反复出现,因此您可以通过搜索 存档 (或通过 google) 在那里找到更多信息.

提交的登录信息由 `UsernamePasswordAuthenticationFilter` 的实例处理.  您将需要自定义此类以处理额外的数据字段.  一种选择是使用您自己的自定义认证令牌类 (而不是标准的 `UsernamePasswordAuthenticationToken`) ,另一种选择是简单地将多余的字段与用户名连接起来 (例如,使用 ":" 作为分隔符) ,并将其传递给 `username` 属性 的 `UsernamePasswordAuthenticationToken`.

您还需要自定义实际的身份验证过程.  例如,如果使用的是自定义身份验证令牌类,则必须编写 `AuthenticationProvider` 来处理它 (或扩展标准的 `DaoAuthenticationProvider`) .  如果已串联字段,则可以实现自己的 `UserDetailsService`,将其拆分并加载适当的用户数据以进行身份验证.

[[appendix-faq-matching-url-fragments]]
=== 在只有所请求的 URL 的片段值不同的地方 (e.g./foo#bar and /foo#blah?) ,我如何应用不同的拦截 URL 约束?

您无法执行此操作,因为该片段不会从浏览器传输到服务器. 从服务器的角度来看,上述网址是相同的. 这是 GWT 用户的常见问题.

[[appendix-faq-request-details-in-user-service]]
=== 如何在 UserDetailsService 中访问用户的 IP 地址 (或其他网络请求数据) ?

显然,您不能 (不求助于线程局部变量) ,因为提供给界面的唯一信息就是用户名.  而不是实现 `UserDetailsService`,应直接实现 `AuthenticationProvider` 并从提供的 `Authentication` 令牌中提取信息.

在标准的 Web 设置中,`Authentication` 对象上的 `getDetails()` 方法将返回 `WebAuthenticationDetails` 的实例.  如果需要其他信息,可以将自定义 `AuthenticationDetailsSource` 注入正在使用的身份验证过滤器中.  如果使用命名空间 (例如,使用 `<form-login>` 元素) ,则应删除该元素,并用 `<custom-filter>` 声明替换它,该声明指向显式配置的 `UsernamePasswordAuthenticationFilter`.

[[appendix-faq-access-session-from-user-service]]
=== 如何从UserDetailsService访问HttpSession?

您不能,因为 `UserDetailsService` 不了解 Servlet API.  如果要存储自定义用户数据,则应自定义返回的 `UserDetails` 对象.  然后可以通过本地线程的 `SecurityContextHolder` 在任何时候访问它.  调用 `SecurityContextHolder.getContext().getAuthentication().getPrincipal()` 将返回此自定义对象.

如果您确实需要访问该会话,则必须通过自定义 Web 层来完成.

[[appendix-faq-password-in-user-service]]
=== 如何在UserDetailsService中访问用户密码?

您不能 (也不应该) . 您可能会误解其目的. 请参阅<<appendix-faq-what-is-userdetailservice,什么是 UserDetailsService?>>

[[appendix-faq-dynamic-url-metadata]]
=== 如何动态定义应用程序中的安全 URL?

人们经常问如何在数据库中而不是在应用程序上下文中存储安全 URL 和安全元数据属性之间的映射.

您应该问自己的第一件事是您是否真的需要这样做.  如果应用程序需要安全保护,则还要求根据定义的策略对安全性进行彻底测试.  在将其推广到生产环境之前,可能需要进行审核和验收测试.  一个安全意识强的组织应该意识到,通过更改配置数据库中的一两行,可以在运行时修改安全设置,
可以立即消除其辛苦的测试过程的好处.  如果考虑到这一点 (可能在应用程序中使用多层安全性) ,那么 Spring Security 允许您完全自定义安全性元数据的来源.  您可以选择使其完全动态.

方法和 Web 安全都受 `AbstractSecurityInterceptor` 的子类保护,该子类配置有 `SecurityMetadataSource`,可以从 `SourceMSource` 获取特定方法或过滤器调用的元数据.
对于 Web 安全,拦截器类是 `FilterSecurityInterceptor`,它使用标记接口 `FilterInvocationSecurityMetadataSource`.
它操作的 "受保护对象" 类型是 `FilterInvocation`.  使用的默认实现 (在命名空间 `<http>` 中,并且在显式配置拦截器时) 都将 URL 模式列表及其对应的 "配置属性" 列表 (`ConfigAttribute` 的实例) 存储在内存映射中.

要从备用源加载数据,必须使用显式声明的安全过滤器链 (通常是 Spring Security 的 `FilterChainProxy`) 才能自定义 `FilterSecurityInterceptor` bean.  您不能使用命名空间.  然后,您将实现 `FilterInvocationSecurityMetadataSource` 以根据需要为特定的 FilterInvocation footnote:[FilterInvocation 对象包含 HttpServletRequest,因此您可以获取 URL 或任何其他相关信息,并根据这些信息来决定返回的属性列表将包含哪些内容. ] 加载数据.  一个非常基本的轮廓如下所示:

====
.Java
[source,java,role="primary"]
----

	public class MyFilterSecurityMetadataSource implements FilterInvocationSecurityMetadataSource {

		public List<ConfigAttribute> getAttributes(Object object) {
			FilterInvocation fi = (FilterInvocation) object;
				String url = fi.getRequestUrl();
				String httpMethod = fi.getRequest().getMethod();
				List<ConfigAttribute> attributes = new ArrayList<ConfigAttribute>();

				// Lookup your database (or other source) using this information and populate the
				// list of attributes

				return attributes;
		}

		public Collection<ConfigAttribute> getAllConfigAttributes() {
			return null;
		}

		public boolean supports(Class<?> clazz) {
			return FilterInvocation.class.isAssignableFrom(clazz);
		}
	}

----

.Kotlin
[source,kotlin,role="secondary"]
----
class MyFilterSecurityMetadataSource : FilterInvocationSecurityMetadataSource {
    override fun getAttributes(securedObject: Any): List<ConfigAttribute> {
        val fi = securedObject as FilterInvocation
        val url = fi.requestUrl
        val httpMethod = fi.request.method

        // Lookup your database (or other source) using this information and populate the
        // list of attributes
        return ArrayList()
    }

    override fun getAllConfigAttributes(): Collection<ConfigAttribute>? {
        return null
    }

    override fun supports(clazz: Class<*>): Boolean {
        return FilterInvocation::class.java.isAssignableFrom(clazz)
    }
}
----
====


有关更多信息,请查看 `DefaultFilterInvocationSecurityMetadataSource` 的代码.


[[appendix-faq-ldap-authorities]]
=== 如何针对LDAP进行身份验证,但如何从数据库中加载用户角色?

`LdapAuthenticationProvider` bean (在 Spring Security 中处理普通的 LDAP 身份验证) 配置有两个单独的策略接口,一个用于执行身份验证,另一个用于加载用户权限,分别称为 `LdapAuthenticator` 和 `LdapAuthoritiesPopulator`.  `DefaultLdapAuthoritiesPopulator` 从 LDAP 目录加载用户权限,并具有各种配置参数,使您可以指定如何检索这些权限.

要改为使用 JDBC,您可以使用适合您的模式的任何 SQL 自己实现接口:

====
.Java
[source,java,role="primary"]
----
public class MyAuthoritiesPopulator implements LdapAuthoritiesPopulator {
    @Autowired
    JdbcTemplate template;

    List<GrantedAuthority> getGrantedAuthorities(DirContextOperations userData, String username) {
        return template.query("select role from roles where username = ?",
                new String[] {username},
                new RowMapper<GrantedAuthority>() {
             /**
             *  We're assuming here that you're using the standard convention of using the role
             *  prefix "ROLE_" to mark attributes which are supported by Spring Security's RoleVoter.
             */
            @Override
            public GrantedAuthority mapRow(ResultSet rs, int rowNum) throws SQLException {
                return new SimpleGrantedAuthority("ROLE_" + rs.getString(1));
            }
        });
    }
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
class MyAuthoritiesPopulator : LdapAuthoritiesPopulator {
    @Autowired
    lateinit var template: JdbcTemplate

    override fun getGrantedAuthorities(userData: DirContextOperations, username: String): MutableList<GrantedAuthority?> {
        return template.query("select role from roles where username = ?",
            arrayOf(username)
        ) { rs, _ ->
            /**
             * We're assuming here that you're using the standard convention of using the role
             * prefix "ROLE_" to mark attributes which are supported by Spring Security's RoleVoter.
             */
            SimpleGrantedAuthority("ROLE_" + rs.getString(1))
        }
    }
}
----
====

然后,您可以将这种类型的 bean 添加到您的应用程序上下文中,并将其注入 `LdapAuthenticationProvider`.  在参考手册的 LDAP 章节中有关使用显式 Spring Bean 配置 LDAP 的部分中对此进行了介绍.  请注意,在这种情况下,您不能使用命名空间进行配置.  您还应该向 Javadoc 查询相关的类和接口.


[[appendix-faq-namespace-post-processor]]
=== 我想修改由命名空间创建的 bean 的属性,但是架构中没有任何东西可以支持它.
除了放弃使用命名空间外,我还能做什么?

命名空间功能是有意限制的,因此无法涵盖使用普通 bean 可以做的所有事情.  如果您想做一些简单的事情,例如修改 Bean 或注入其他依赖,则可以通过在配置中添加 BeanPostProcessor 来实现.  更多信息可以在 https://docs.spring.io/spring/docs/3.0.x/spring-framework-reference/htmlsingle/spring-framework-reference.html#beans-factory-extension-bpp[Spring 参考手册]中找到.
为了做到这一点,您需要对创建哪些 bean 有一点了解,因此您还应该阅读上述问题中有关 <<appendix-faq-namespace-to-bean-mapping,命名空间如何映射到 Spring bean>>的博客文章.

通常,您需要将所需的功能添加到 `BeanPostProcessor` 的 `postProcessBeforeInitialization` 方法中.  假设您要自定义 `UsernamePasswordAuthenticationFilter` (由 `form-login` 元素创建) 所使用的 `AuthenticationDetailsSource`.
您想要从请求中提取一个名为 `CUSTOM_HEADER` 的特定 header,并在验证用户身份时使用它.  处理器类如下所示:

====
.Java
[source,java,role="primary"]
----
public class CustomBeanPostProcessor implements BeanPostProcessor {

		public Object postProcessAfterInitialization(Object bean, String name) {
				if (bean instanceof UsernamePasswordAuthenticationFilter) {
						System.out.println("********* Post-processing " + name);
						((UsernamePasswordAuthenticationFilter)bean).setAuthenticationDetailsSource(
										new AuthenticationDetailsSource() {
												public Object buildDetails(Object context) {
														return ((HttpServletRequest)context).getHeader("CUSTOM_HEADER");
												}
										});
				}
				return bean;
		}

		public Object postProcessBeforeInitialization(Object bean, String name) {
				return bean;
		}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
class CustomBeanPostProcessor : BeanPostProcessor {
    override fun postProcessAfterInitialization(bean: Any, name: String): Any {
        if (bean is UsernamePasswordAuthenticationFilter) {
            println("********* Post-processing $name")
            bean.setAuthenticationDetailsSource(
                AuthenticationDetailsSource<HttpServletRequest, Any?> { context -> context.getHeader("CUSTOM_HEADER") })
        }
        return bean
    }

    override fun postProcessBeforeInitialization(bean: Any, name: String?): Any {
        return bean
    }
}
----
====

然后,您将在应用程序上下文中注册此 bean.  Spring 将在应用程序上下文中定义的 bean 上自动调用它.
