= Reactive Streams 规范

http://www.reactive-streams.org/[原文地址]

Reactive Streams is an initiative to provide a standard for asynchronous stream processing with non-blocking back pressure. This encompasses efforts aimed at runtime environments (JVM and JavaScript) as well as network protocols.

Reactive Streams 是一个作为提供非阻塞背压的异步流处理标准的倡议，它包括针对运行时环境（JVM和JavaScript）以及网络协议的工作。

== JDK9 java.util.concurrent.Flow

JDK 9 以上提供了 https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/Flow.html[`java.util.concurrent.Flow`] 的接口。 这个接口在语义上与各自对应的响应式流(Reactive Streams)是 1:1 等价的。这意味着将有一个将库适配到 JDK 提供的新类型的迁移过程，这个过程不会很长 - 因为库的语义完成相等，并且 Reactive Streams <-> Flow adapter 库以及 JDK Flow 类型与 TCK 兼容。

Read this if you are interested in learning more about Reactive Streams for the JVM.

如果您有兴趣了解更多关于 JVM 的响应流，请 https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.4/README.md[阅读本文]。

== The Problem（问题）

Handling streams of data—especially “live” data whose volume is not predetermined—requires special care in an asynchronous system. The most prominent issue is that resource consumption needs to be controlled such that a fast data source does not overwhelm the stream destination. Asynchrony is needed in order to enable the parallel use of computing resources, on collaborating network hosts or multiple CPU cores within a single machine.

在异步系统中，处理流数据，尤其是容量不是预先确定的 “live” 数据时需要特别小心。最突出的问题是需要控制资源消耗，保证一个“快速”流数据不会搞垮流输出目标。为了对计算机资源（网络上的多台机器或一台机器上的多个CPU）的并发使用引入异步是必要的。

The main goal of Reactive Streams is to govern the exchange of stream data across an asynchronous boundary—think passing elements on to another thread or thread-pool—while ensuring that the receiving side is not forced to buffer arbitrary amounts of data. In other words, back pressure is an integral part of this model in order to allow the queues which mediate between threads to be bounded. The benefits of asynchronous processing would be negated if the communication of back pressure were synchronous (see also the Reactive Manifesto), therefore care has to be taken to mandate fully non-blocking and asynchronous behavior of all aspects of a Reactive Streams implementation.

Reactive Streams 管理跨异步边界的流数据交换 - 即将元素传递到另一个线程或线程池，确保接收方不会强制缓冲任意数量的数据。 换句话说，背压是该模型的一个组成部分，他可以限制线程之间的队列边界。 如果背压的通信是同步的（另请参见 http://reactivemanifesto.org/[Reactive Manifesto]），会导致异步处理无效，因此在实现响应流标准时所有各方面都强制要求是完全非阻塞和异步行为。

It is the intention of this specification to allow the creation of many conforming implementations, which by virtue of abiding by the rules will be able to interoperate smoothly, preserving the aforementioned benefits and characteristics across the whole processing graph of a stream application.

此规范的可以有多个实现，这些实现通过遵守一定的规则可以进行相互操作，在流应用程序的整个处理图上保留上述优点和特性。

== Scope(范围)

The scope of Reactive Streams is to find a minimal set of interfaces, methods and protocols that will describe the necessary operations and entities to achieve the goal—asynchronous streams of data with non-blocking back pressure.

Reactive Streams 的范围是找到一组最小的接口、方法和协议，这些接口、方法和协议将描述所需的操作和实体来达到我们的目的 — 具有非阻塞背压的异步数据流。

End-user DSLs or protocol binding APIs have purposefully been left out of the scope to encourage and enable different implementations that potentially use different programming languages to stay as true as possible to the idioms of their platform.

为了鼓励和支持使用不同的编程语言的不同实现尽可能地符合其平台的习惯用法，终端用户 DSL 或协议绑定 API 已被排除在此规范范围之外，

We anticipate that acceptance of this Reactive Streams specification and experience with its implementations will together lead to wide integration, for example including Java platform support in future JDK releases or network protocol support in future web browsers.

我们期望 Reactive Streams 规范及其实现可以被广泛的集成，例如对未来 JDK 版本中的 Java 平台支持或未来 Web 浏览器中的网络协议支持。

=== Working Groups（工作组）

==== Basic Semantics（基本语义）

The basic semantics define how the transmission of stream elements is regulated through back-pressure. How elements are transmitted, their representation during transfer, or how back-pressure is signaled is not part of this specification.

基本语义定义了如何通过背压调节流元素的传输。至于流元素如何传输，在传输过程中如何表示，或者背压如何发出信号不是本规范的一部分。

==== JVM Interfaces (Completed)

This working group applies the basic semantics to a set of programming interfaces whose main purpose is to allow the interoperation of different conforming implementations and language bindings for passing streams between objects and threads within the JVM, using the shared memory heap.

这个工作组将基本语义应用到一组编程接口，这些接口的主要目的是允许不同的一致性实现和语言绑定进行互操作，以便使用共享内存堆在 JVM 中的对象和线程之间传递流。

As of May 26th, 2022 we have released version 1.0.4 of Reactive Streams for the JVM, including Java API, a textual Specification, a TCK and implementation examples.

截至 2022 年 5 月 26 日，我们已经发布了 JVM Reactive Streams 1.0.4 版本，包括 https://www.reactive-streams.org/reactive-streams-1.0.4-javadoc[Java API]、 https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.4/README.md#specification[文本规范]、
https://www.reactive-streams.org/reactive-streams-tck-1.0.4-javadoc[TCK] 和 https://www.reactive-streams.org/reactive-streams-examples-1.0.4-javadoc/[实现示例]。

Corresponding code artifacts are available on Maven Central:

相应的代码构件可在 Maven Central 上获得:

[source,xml]
----
<dependency>
  <groupId>org.reactivestreams</groupId>
  <artifactId>reactive-streams</artifactId>
  <version>1.0.4</version>
</dependency>
<dependency>
  <groupId>org.reactivestreams</groupId>
  <artifactId>reactive-streams-tck</artifactId>
  <version>1.0.4</version>
</dependency>
<dependency>
  <groupId>org.reactivestreams</groupId>
  <artifactId>reactive-streams-tck-flow</artifactId>
  <version>1.0.4</version>
</dependency>
<dependency>
  <groupId>org.reactivestreams</groupId>
  <artifactId>reactive-streams-examples</artifactId>
  <version>1.0.4</version>
</dependency>
----

The source code for these is available on github. Please use github issues for providing feedback.

源代码可以在 https://github.com/reactive-streams/reactive-streams-jvm/tree/v1.0.4[github] 上找到。请使用 github issues 提供反馈。

All artifacts and specifications are released under MIT No Attribution (SPDX: MIT-0).

所有构件和规范都遵循 MIT No Attribution (SPDX: MIT-0) License。

Read more about Reactive Streams 1.0.4 for the JVM here.

在 https://www.reactive-streams.org/announce-1.0.4[这里] 阅读更多关于 JVM 的  Reactive Streams 1.0.4 的信息。

=== A Note for Implementors(实现注意事项)

To get started implementing the final specification, it is recommended to start by reading the README and the Java API documentation, then taking a look at the Specification then taking a look at the TCK and the example implementations. If you have an issue with any of the above, please take a look at closed issues and then open a new issue if it has not already been answered.

要开始实现最终规范，建议首先阅读 https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.4/README.md[README] 和 https://www.reactive-streams.org/reactive-streams-1.0.4-javadoc/org/reactivestreams/package-summary.html[Java API 文档]，
然后查看 https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.4/README.md#specification[规范]，然后查看 https://github.com/reactive-streams/reactive-streams-jvm/tree/v1.0.4/tck[TCK] 和 https://github.com/reactive-streams/reactive-streams-jvm/tree/v1.0.4/examples/src/main/java/org/reactivestreams/example/unicast[示例实现]。
如果您对上述任何一个问题有疑问，请查看 https://github.com/reactive-streams/reactive-streams-jvm/issues?q=is%3Aclosed[已关闭的问题]，如果它还没有得到回答，可以 https://github.com/reactive-streams/reactive-streams-jvm/issues/new[打开一个新的问题]。

This work was performed in the reactive-streams-jvm repository.

这项工作是在 https://github.com/reactive-streams/reactive-streams-jvm/[reactive-streams-jvm] 存储库中执行的。

==== JavaScript Interfaces(JavaScript 接口)

This working group defines a minimal set of object properties for observing a stream of elements within a JavaScript runtime environment. The goal is to provide a testable specification that allows different implementations to interoperate within that same runtime environment.

该工作组定义了一组最小的对象属性，用于观察 JavaScript 运行时环境中的元素流。 目标是提供一个可测试的规范，允许不同的实现在同一个运行时环境中进行互操作。

This work is performed in the reactive-streams-js repository.

这项工作在 https://github.com/reactive-streams/reactive-streams-js/[reactive-streams-js] 存储库中执行。

==== Network Protocols(网络协议)

This working group defines network protocols for passing reactive streams over various transport media that involve serialization and deserialization of the data elements. Examples of such transports are TCP, UDP, HTTP and WebSockets.

该工作组定义了网络协议，用于在涉及数据元素的序列化和反序列化的各种传输媒体上传递 reactive streams。 此类传输的示例是 TCP、UDP、HTTP 和 WebSockets。

This work is performed in the reactive-streams-io repository.

这项工作在 https://github.com/reactive-streams/reactive-streams-io/[reactive-streams-io] 存储库中执行。

== 参考资料(此部分不在规范中)

http://www.ypk1226.com/2019/07/01/reactive/reactive-streams/[http://www.ypk1226.com/2019/07/01/reactive/reactive-streams/]