[[sec:component_metadata_rules]]
= 使用组件元数据规则修复元数据

从存储库中提取的每个模块都有与之关联的元数据，例如其 group，name，version 以及它提供的带有工件和依赖项的不同变体。 有时，此元数据不完整或不正确。 为了从构建脚本中处理这种不完整的元数据，Gradle 提供了一个 API 来编写组件元数据规则。 这些规则在下载模块的元数据之后但在依赖关系解析中使用之前生效。

== 编写组件元数据规则的基础

组件元数据规则应用于构建脚本的依赖关系块 (link:{groovyDslPath}/org.gradle.api.artifacts.dsl.DependencyHandler.html[DependencyHandler]) 的组件 (link:{groovyDslPath}/org.gradle.api.artifacts.dsl.ComponentMetadataHandler.html[ComponentMetadataHandler]) 部分中。可以用两种不同的方式定义规则：

1. 直接在组件部分中应用它们时作为操作
2. 实现 link:{javadocPath}/org/gradle/api/artifacts/ComponentMetadataRule.html[ComponentMetadataRule] 接口

虽然将规则内联定义为操作可以方便地进行实验，但是通常建议将规则定义为单独的类。 可以使用 `@CacheableRule` 注释作为隔离类编写的规则，以缓存其应用程序的结果，从而使每次解决依赖关系时都无需重新执行它们。

.Example of a configurable component metadata rule
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=config-component-metadata-rule]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=config-component-metadata-rule]
====

从上面的示例可以看出，组件元数据规则是通过实现 link:{javadocPath}/org/gradle/api/artifacts/ComponentMetadataRule.html[ComponentMetadataRule]  来定义的，该组件具有 `execute` 方法，该方法接收 link:{javadocPath}/org/gradle/api/artifacts/ComponentMetadataContext.html[ComponentMetadataContext] 的实例作为参数。 在此示例中，还通过 link:{javadocPath}/org/gradle/api/ActionConfiguration.html[ActionConfiguration] 进一步配置了规则。 通过在 `ComponentMetadataRule` 的实现中使构造函数接受已配置的参数和需要注入的服务，可以支持此功能。

Gradle 强制隔离 `ComponentMetadataRule` 实例。这意味着所有参数都必须是 `Serializable` 的或可以隔离的已知 Gradle 类型。 

另外，可以将 Gradle 服务注入到 `ComponentMetadataRule` 中。 因此，一旦有了构造函数，就必须使用 `@javax.inject.Inject` 对其进行注释。 通常需要使用 link:{javadocPath}/org/gradle/api/model/ObjectFactory.html[ObjectFactory] 服务来创建强类型值对象（例如用于设置 link:{javadocPath}/org/gradle/api/attributes/Attribute.html[Attribute] 的值）的实例。 link:{javadocPath}/org/gradle/api/artifacts/repositories/RepositoryResourceAccessor.html[RepositoryResourceAccessor] 是有助于组件元数据规则与自定义元数据的高级使用的服务。

组件元数据规则可以通过 `withModule(groupAndName, rule)` 应用于所有模块— `all(rule)` —或选定的模块。 通常，专门编写一条规则以丰富一个特定模块的元数据，因此 `withModule` API应该是首选。

[[sec:component_metadata_rules_details]]
== 元数据的哪些部分可以修改？

组件元数据规则 API 面向 link:https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/design/gradle-module-metadata-latest-specification.md[Gradle Module Metadata] 和构建脚本中的依赖项 API 支持的功能。 编写规则与在构建脚本中定义依赖项和工件之间的主要区别在于，组件元数据规则遵循 Gradle Module 元数据的结构，直接对 <<variant_model.adoc#understanding-variant-selection,variants>> 进行操作。 相反，在构建脚本中，您经常一次影响多个变量的形状（例如，将 api 依赖项添加到 Java 库的 api 和运行时变量中，由 jar 任务生成的工件也添加到这两个变量中） 。


Variants 可以通过以下方法进行修改：

- `allVariants`: 修改组件的所有 variants
- `withVariant(name)`: 修改由其名称标识的单个 variant
- `addVariant(name)` or `addVariant(name, base)`: 从头开始或通过复制现有 variant 的详细信息（基础）向组件添加新 variant

可以调整每个 variant 的以下详细信息：:

- variant <<variant_model.adoc#sec:abm_configuration_attributes,attributes>> — `attributes {}` block
- variant 提供的 <<component_capabilities.adoc#declaring-component-capabilities,capabilities>> — `withCapabilities { }` block
- variant 的 <<declaring_dependencies.adoc#,依赖>>, 包括 <<rich_versions.adoc#,rich versions>> — `withDependencies {}` block
- variant <<dependency_constraints.adoc#sec:adding-constraints-transitive-deps,依赖约束>>, 包括 <<rich_versions.adoc#,rich versions>> — `withDependencyConstraints {}` block
- 组成该 variant 实际内容的已发布文件的位置 — `withFiles { }` block

整个组件的一些属性也可以更改:

- 组件级属性，目前唯一有意义的属性是 `org.gradle.status`
- 在版本选择期间影响 `org.gradle.status` 属性解释的状态方案
- 通过 <<component_capabilities.adoc#sec:declaring-capabilities-external-modules,虚拟平台进行版本对齐>> 的 belongsTo 属性 

根据模块元数据的格式，它以不同的方式映射到元数据的以变量为中心的表示形式:

- 如果模块具有 Gradle 模块元数据，则规则所依据的数据结构与您在模块的 `.module` 文件中找到的数据结构非常相似.
- 如果仅使用 `.pom` 元数据发布该模块，则会派生许多固定的变体，如 <<variant_model.adoc#sub:maven-mapping-to-variants,mapping of POM files to variants>>  部分中所述.
- 如果仅使用 `ivy.xml` 文件发布该模块，则可以访问文件中定义的 Ivy 配置，而不是 variant。 它们的依赖性，依赖性约束和文件可以修改
  另外，如果需要，可以使用 `addVariant(name, baseVariantOrConfiguration) { }` API 从 Ivy 配置派生 variant（例如，可以使用此方法定义 <<variant_model.adoc#sub:ivy-mapping-to-variants,_compile_ and _runtime_ variants for the Java library plugin>>）。

== 何时使用组件元数据规则？

通常，如果您考虑使用组件元数据规则来调整某个模块的元数据，则应首先检查该模块是使用 Gradle 模块元数据（`.module` 文件）还是仅使用传统元数据（`.pom` or `ivy.xml`）发布的。

如果使用 Gradle Module Metadata 发布了模块，则尽管有时仍然存在某些明显错误的情况，但元数据可能已完成。 对于这些模块，只有在明确确定元数据本身存在问题的情况下，才应使用组件元数据规则。 如果您对依赖项解析结果有疑问，则应首先通过 <<rich_versions.adoc#,dependency constraints with rich versions>>. 来检查是否可以解决问题。 特别是，如果您正在开发要发布的库，则应记住，与组件元数据规则相反，依赖关系约束是作为您自己的库的元数据的一部分发布的。 因此，在具有依赖关系约束的情况下，您可以自动与使用者共享依赖关系解决方案的解决方案，而组件元数据规则仅应用于自己的内部版本。

如果模块是使用传统的元数据发布的（仅 `.pom` 或 `ivy.xml`，没有 `.module` 文件），则元数据很可能不完整，因为这些格式不支持诸如变体或依赖项约束之类的功能。 仍然，从概念上讲，此类模块可以包含不同的变体，或者可能具有它们刚刚被忽略（或错误地定义为依赖项）的依赖项约束。 在下一部分中，我们将探讨许多现有的 oss 模块，这些模块具有不完整的元数据以及添加缺少的元数据信息的规则。

根据经验，您应该考虑所编写的规则是否也适用于构建环境。 也就是说，如果将规则应用到任何其他使用受其影响的模块的内部版本中，该规则是否仍会产生正确且有用的结果？

== 修复错误的依赖项详细信息

让我们以 link:https://repo1.maven.org/maven2/jaxen/jaxen[Maven central] 上 Jaxen XPath Engine 的发布为例。 版本 1.1.3 的 pom 在编译范围内声明了许多依赖关系，而这些依赖关系实际上并不是编译所必需的。 这些已在 1.1.4 pom 中删除。 假设由于某种原因需要使用 1.1.3，我们可以使用以下规则来修复元数据：

.Rule to remove unused dependencies of Jaxen metadata
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=jaxen-rule-1]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=jaxen-rule-1]
====

在 `withDependencies` 块中，您可以访问依赖关系的完整列表，并且可以使用 Java 集合界面上可用的所有方法来检查和修改该列表。 此外，还有 `add(notation, configureAction)` 方法接受通常的表示法，类似于在构建脚本中 <<declaring_dependencies.adoc#,declaring dependencies>>。 可以在 `withDependencyConstraints`  块中以相同的方式检查和修改依赖性约束。

如果仔细研究 Jaxen 1.1.4 pom，我们会发现  _dom4j_, _jdom_ and _xerces_ 赖项仍然存在，但标记为可选。 poms 中的可选依赖项不会被 Gradle 或 Maven 自动处理。原因是它们表明 Jaxen 库提供了一些可选的 <<feature_variants.adoc#,optional feature variants>>，它们需要一个或多个这样的依赖项，但是缺少了这些特性是什么以及哪些依赖项属于哪些的信息。这样的信息不能在 pom 文件中表示，而是在 Gradle 模块元数据中通过变体和 <<component_capabilities.adoc#declaring-component-capabilities,capabilities>> 表示。因此,

.Rule to add optional feature to Jaxen metadata
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=jaxen-rule-2]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=jaxen-rule-2]
====

在这里，我们首先使用 `addVariant(name, baseVariant)` 方法创建一个额外的变体，通过定义一个新功能 _jaxen-dom4j_  来表示 Jaxen 的可选 dom4j 集成特性，我们将其标识为特性变体。这类似于在构建脚本中 <<feature_variants.adoc#sec::declare_feature_variants,defining optional feature variants>> 。

然后我们使用一个 `add` 方法来添加依赖项，以定义这个可选特性需要哪些依赖项。在构建脚本中，我们可以向可选特性添加一个依赖项，Gradle 将使用丰富的元数据来发现正确的传递依赖项

.Applying and utilising rules for Jaxen metadata
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=jaxen-dependencies]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=jaxen-dependencies]
====

== Making variants published as classified jars explicit

在上一个示例中，所有变体（"main variants" 和可选功能）都打包在一个 jar 文件中，但通常会将某些变体发布为单独的文件。 特别是，当变体是互斥的时，即它们不是功能变体，而是提供替代选择的不同变体。 所有基于 pom 的库都已经存在的一个示例是运行时和编译变体，其中 Gradle 只能根据手头的任务选择一个。 在 Java 生态系统中经常发现的此类替代方法中的另一个是针对不同 Java 版本的 jar。

例如，我们看一下在 link:https://repo1.maven.org/maven2/co/paralleluniverse/quasar-core/0.7.9[Maven central] 上发布的异步编程库 Quasar 的 0.7.9版 本。 如果检查目录列表，则会发现除了 `quasar-core-0.7.9.jar` 之外，还发布了 `quasar-core-0.7.9-jdk8.jar`。 使用 _classifier_（此处为 jdk8）发布其他 jar 是 maven 存储库中的常见做法。 尽管 Maven 和 Gradle 都允许您通过分类器引用此类 jar，但它们在元数据中根本没有提及。 因此，不存在这些 jar 存在的信息，以及此类 jar 表示的变体之间是否存在其他差异（如不同的依赖项）。

在 Gradle 模块元数据中，将显示此变体信息，对于已经发布的 Quasar 库，我们可以使用以下规则添加它：

.Rule to add JDK 8 variants to Quasar metadata
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=quasar-rule]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=quasar-rule]
====

在这种情况下，很明显，classifier 代表目标 Java 版本，这是已知的 <<variant_model.adoc#sec:variant-aware-matching,Java 生态系统属性>> 。 因为我们还需要 Java 8 的编译和运行时，所以我们创建了两个新的变体，但将现有的编译和运行时变体用作基础。
这样，所有其他 Java 生态系统属性都已经正确设置，并且所有依赖项都被继承。 然后，将两个变体的 `TARGET_JVM_VERSION_ATTRIBUTE` 都设置为 `8`，使用 `removeAllFiles()` 从新变体中删除任何现有文件，
并使用 `addFile()` 添加 jdk8 jar 文件。 需要 `removeAllFiles()`，因为从相应的基本变量中复制了对主jar `quasar-core-0.7.5.jar` 的引用。

我们还利用针对 Java 7 的信息 `attribute(TARGET_JVM_VERSION_ATTRIBUTE, 7)` 丰富了现有的编译和运行时变体。

现在，我们可以为构建脚本中的所有依赖于编译类路径的依赖项请求 Java 8 版本，并且 Gradle 会自动为每个库选择最合适的变体。 在 Quasar 的情况下，它将是 jdk8Compile 变体，
公开了 `quasar-core-0.7.9-jdk8.jar`。

.Applying and utilising rule for Quasar metadata
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=quasar-dependencies]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=quasar-dependencies]
====

== 使版本中编码的变体明确

为同一个库发布多个替代方案的另一种解决方案是使用流行的 Guava 库所做的版本控制模式。 在这里，通过将分类器（而不是 jar 工件）附加到版本，每个新版本都会发布两次。 以 Guava 28 为例，
我们可以在 link:https://repo1.maven.org/maven2/com/google/guava/guava[Maven central] 上找到 28.0-jre（Java 8）和 28.0-android（Java 6）版本。 仅使用 pom 元数据时使用此模式的优点是，
两个变体都可以通过该版本发现。 缺点是没有信息表明不同版本的后缀在语义上意味着什么。 因此，在发生冲突的情况下，Gradle 在比较版本字符串时只会选择最高版本。

将其转换为适当的变体会比较棘手，因为 Gradle 首先选择模块的版本，然后选择最合适的变体。 因此，不直接支持将变体编码为版本的概念。 但是，由于两个变体始终一起发布，
因此我们可以假定文件实际上位于同一存储库中。 由于它们是按照 Maven 存储库约定发布的，因此如果知道模块名称和版本，我们就知道每个文件的位置。 我们可以编写以下规则：

.Rule to add JDK 6 and JDK 8 variants to Guava metadata
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=guava-rule]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=guava-rule]
====

与前面的示例类似，我们为两个 Java 版本都添加了运行时和编译变体。 但是，在 `withFiles` 块中，我们现在还为相应的 jar 文件指定了相对路径，无论 Gradle 选择了 -jre 还是 -android 版本，
它都允许 Gradle 查找该文件。 该路径始终相对于选择模块版本的元数据（在这种情况下为 `pom`）文件的位置。 因此，使用此规则，Guava 28 "versions" 都携带 _jdk6_ and _jdk8_ 变体。 因此，Gradle 解决哪个问题都没有关系。
根据请求的 `TARGET_JVM_VERSION_ATTRIBUTE` 值确定该变体以及正确的 jar 文件。

.Applying and utilising rule for Guava metadata
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=guava-dependencies]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=guava-dependencies]
====

== 为本地 jar 添加 variants

带有 classifiers 的 Jars 还用于将库中存在多个替代方案（例如本机代码）与主要工件分离的部分。 例如，这是由轻量级 Java 游戏库（LWGJ）完成的，该库将一些特定于平台的 jar 发布到 link:https://repo1.maven.org/maven2/org/lwjgl/lwjgl/3.2.3[Maven central]，
在运行时，除了主 jar 之外，始终需要其中的一个。 由于没有通过元数据关联多个工件的概念，因此无法在 pom 元数据中传达此信息。 在 Gradle 模块元数据中，每个变体可以具有任意多个文件，
我们可以通过编写以下规则来利用它：

.Rule to add native runtime variants to LWGJ metadata
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=lwgj-rule]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=lwgj-rule]
====

此规则与上面的 Quasar 库示例非常相似。 仅这次，我们添加了五个不同的运行时变体，而对于编译变体则无需更改。 运行时变体全部基于现有的运行时变体，并且我们不更改任何现有信息。 
所有 Java 生态系统属性，依赖项和主 jar 文件都属于每个运行时变体的一部分。 我们仅设置其他属性 `OPERATING_SYSTEM_ATTRIBUTE` 和 `ARCHITECTURE_ATTRIBUTE`，它们被定义为 Gradle <<building_cpp_projects.adoc#,native support>> 的一部分。
然后，我们添加相应的本机 jar 文件，以使每个运行时变体现在都包含两个文件：主 jar 和本机 jar。

在构建脚本中，我们现在可以请求特定的变体，如果需要更多信息来做出决定，则 Gradle 将失败，并显示选择错误。

.Applying and utilising rule for LWGJ metadata
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=lwgj-dependencies]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=lwgj-dependencies]
====

.Gradle fails to select a variant because a machine architecture needs to be chosen
----
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not resolve org.lwjgl:lwjgl:3.2.3.
     Required by:
         project :
      > Cannot choose between the following variants of org.lwjgl:lwjgl:3.2.3:
          - natives-windows-runtime
          - natives-windows-x86-runtime
----

== 通过功能提供不同风格的库

由于很难将 <<feature_variants.adoc#,optional feature variants>> 建模为带有 pom 元数据的单独 jar，因此库有时会组成具有不同功能集的不同 jar。 也就是说，不是从不同的功能变体中组合出库的风格，
而是选择一种预先组合的变体（在一个 jar 中提供所有内容）。 这样的库之一就是在 link:https://repo1.maven.org/maven2/com/google/inject/guice/4.2.2[Maven central] 上发布的著名的依赖项注入框架 Guice，
它提供了完整的风格（ main jar）和简化的变体，而没有面向方面的编程支持 (`guice-4.2.2-no_aop.jar`)。 pom 元数据中未提及带有分类器的第二种变体。 遵循以下规则，我们将基于该文件创建编译和运行时变体，
并通过名为 `com.google.inject:guice-no_aop` 的功能使它可选。

.Rule to add no_aop feature variant to Guice metadata
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=guice-rule]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=guice-rule]
====

新的变体还依赖于标准化的 aop 接口库 `aopalliance:aopalliance`，因为这些变体显然不需要这样做。 同样，这是无法在 pom 元数据中表达的信息。 
现在，我们可以选择 `guice-no_aop` 变体，并将获得正确的 jar 文件和正确的依赖关系。

.Applying and utilising rule for Guice metadata
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=guice-dependencies]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=guice-dependencies]
====

== 添加缺少的功能来检测冲突

功能的另一种用法是表示两个不同的模块（例如 `log4j` 和 `log4j-over-slf4j`）提供同一事物的替代实现。 通过声明两者都提供相同的功能，Gradle 在依赖图中仅接受其中之一。 
此示例以及如何用组件元数据规则解决该示例，在 <<component_capabilities.adoc#sec:declaring-capabilities-external-modules,feature modelling>> 部分中进行了详细说明。


== 使 Ivy 模块能够感知变体

默认情况下，具有 Ivy 元数据的模块没有变体。但是，Ivy 配置可以被映射到变体，因为 `addVariant(name, baseVariantOrConfiguration)` 接受作为 base 发布的任何 Ivy 配置。
例如，可以使用它来定义运行时和编译变量。相应规则的示例可以在 <<variant_model.adoc#sub:ivy-mapping-to-variants,here>> 找到。Ivy 配置的 Ivy 细节(例如依赖项和文件)也可以使用 `withVariant(configurationName)`  API修改。
但是，修改 Ivy 配置上的属性或功能没有任何效果。对于非常特殊的 Ivy 用例，

对于非常特定于Ivy的用例，组件元数据规则 API 还提供了对仅在 Ivy 元数据中发现的其他细节的访问。它们可以通过 link:{javadocPath}/org/gradle/api/artifacts/ivy/IvyModuleDescriptor.html[IvyModuleDescriptor] 接口获得，
并且可以使用 link:{javadocPath}/org/gradle/api/artifacts/ComponentMetadataContext.html[ComponentMetadataContext] 上的 `getDescriptor(IvyModuleDescriptor)` 来访问。

.Ivy component metadata rule
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=ivy-component-metadata-rule]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=ivy-component-metadata-rule]
====

== 使用 Maven 元数据过滤

对于特定于 Maven 的用例，组件元数据规则 API 还提供了对仅在 POM 元数据中发现的其他细节的访问。它们可以通过 link:{javadocPath}/org/gradle/api/artifacts/maven/PomModuleDescriptor.html[PomModuleDescriptor] 接口获得，
并且可以使用 link:{javadocPath}/org/gradle/api/artifacts/ComponentMetadataContext.html[ComponentMetadataContext] 上的 `getDescriptor(PomModuleDescriptor)` 访问。

.Access pom packaging type in component metadata rule
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=maven-packaging-component-metadata-rule]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=maven-packaging-component-metadata-rule]
====

== 在组件级别修改元数据以进行对齐

尽管以上所有示例都对组件的变体进行了修改，但也可以对组件本身的元数据进行有限的修改。 此信息可能会影响相关性解析期间模块的 <<dependency_resolution.adoc#,version selection>> 过程，该过程在选择组件的一个或多个变体之前执行。

组件上可用的第一个 API 是 `belongsTo()`，用于创建虚拟平台，以对齐没有 Gradle Module Metadata 的多个模块的版本。 在 <<dependency_version_alignment.adoc#sec:align-versions-unpublished,aligning versions of modules not published with Gradle>> 部分中对此进行了详细说明。

[[sec:custom_status_scheme]]
== 在组件级别上修改元数据以根据状态选择版本

Gradle 和 Gradle 模块元数据还允许在整个组件上设置属性，而不是单个变量。 这些属性中的每一个都具有特殊的语义，因为它们影响版本选择，而版本选择是在变量选择之前完成的。 
尽管变体选择可以处理 <<variant_attributes.adoc#sec:declaring_attributes,任何自定义属性>> ，但版本选择仅考虑实现了特定语义的属性。 目前，这里唯一有意义的属性是 `org.gradle.status`。 
因此，建议仅在组件级别上修改此属性（如果有）。 为此可以使用专用的 API `setStatus(value)`。 要使用 `withAllVariants { attributes {} }` 修改组件的所有变体的另一个属性。

当解析 <<single_versions.adoc#,_latest_ version selector>> 时，将考虑模块的状态。具体来说,最新的。`someStatus` 将解析为具有状态 `someStatus` 或更成熟状态的最高模块版本。例如，`latest.integration` 将选择最高的模块版本，
而不管它的状态如何(因为 `integration` 是下面解释的最不成熟的状态)，而不是 `latest.release` 将选择状态为 `release` 的最高模块版本。

通过 `setStatusScheme(valueList)` API更改模块的状态方案，可以影响状态的解释。 这个概念模拟了模块在不同出版物上随着时间推移而转变的不同成熟度。 
默认状态方案（从最低状态到最成熟状态排列）为  `integration`, `milestone`, `release`.。 必须将 `org.gradle.status` 属性设置为组件状态方案中的值之一。 因此，每个组件始终具有从元数据确定的状态，如下所示：

- Gradle Module Metadata: 为组件上的 `org.gradle.status` 属性发布的值
- Ivy metadata: `status` 在 `ivy.xml` 中定义的状态，如果缺少则默认为 `integration`
- Pom metadata: `integration` 具有 `SNAPSHOT` 版本的模块，为所有其他版本 `release` 

下面的示例演示了基于在适用于所有模块的组件元数据规则中声明的自定义状态方案的 `latest` 选择：

.Custom status scheme
====
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/groovy/build.gradle[tags=custom-status-scheme]
include::{snippets-dir}/dependencyManagement/customizingResolution-metadataRule/kotlin/build.gradle.kts[tags=custom-status-scheme]
====

与默认方案相比，该规则会插入一个新的状态 `rc`，并将集成替换为  `nightly`。具有状态 `integration` 的现有模块被映射为  `nightly`。


