[[dependency-constraints]]
= 依赖传递的版本升级

[[sec:direct-vs-transitive-deps]]
== 直接依赖与依赖约束

组件可能具有两种不同的依赖关系:

- 直接依赖关系是组件直接需要的.
直接依赖关系也称为第一级依赖关系. 例如,如果您的项目源代码需要 Guava,则应将 Guava 声明为直接依赖.
- 传递依赖关系是组件所需的依赖关系,但这仅是因为另一个依赖关系需要它们.

依赖管理的问题与传递依赖有关是很常见的. 开发人员经常通过添加直接依赖来错误地解决传递依赖问题. 为了避免这种情况,Gradle提供了依赖性约束的概念.

[[sec:adding-constraints-transitive-deps]]
== 在依赖传递项添加约束

依赖关系约束允许您定义在构建脚本中声明的依赖关系和传递性依赖关系的版本或版本范围. 表达约束的首选方法是应将约束应用于配置的所有依赖. 当 Gradle 尝试将对模块版本的依赖解析为该模块的所有 <<rich_versions.adoc#,依赖声明>> ,
所有传递性依赖和所有依赖约束时,都应考虑在内. 选择符合所有条件的最高版本. 如果找不到这样的版本,Gradle 将失败,并显示一条错误的声明.
如果发生这种情况,您可以调整依赖或依赖约束声明,或者根据需要对传递性依赖进行其他调整. 与依赖声明类似,依赖约束声明受 <<declaring_dependencies.adoc#sec:what-are-dependency-configurations,scoped by configurations>> 限制,因此可以为构建的某些部分选择性地定义.
如果依赖性约束影响了解析结果,则以后仍然可以应用任何类型的 <<resolution_rules.adoc#sec:dependency_resolve_rules,依赖性解析规则>>.

.Define dependency constraints
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-versionsWithConstraints/groovy/build.gradle[tags=dependency-constraints]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-versionsWithConstraints/kotlin/build.gradle.kts[tags=dependency-constraints]
====

在该示例中,所有版本都从依赖声明中省略. 而是在约束块中定义版本. 仅在将 `commons-codec:1.11` 作为传递依赖引入时,才考虑 `commons-codec` 的版本定义,因为在项目中没有将 `commons-codec` 定义为依赖.
否则,约束无效. 依赖关系约束还可以定义 <<rich_versions.adoc#,rich version constraint>>,并支持 <<rich_versions.adoc#sec:strict-version,strict versions>>  以强制执行版本,即使它与传递依赖关系定义的版本相抵触 (例如,如果版本需要降级) .

[NOTE]
====
依赖性约束仅在使用 <<publishing_gradle_module_metadata.adoc#sec:understanding-gradle-module-md,Gradle Module Metadata>> 时发布. 这意味着当前仅在将 Gradle 用于发布和使用时才完全支持它们 (即,在使用 Maven 或 Ivy 使用模块时它们会"丢失" ) .
====

依赖性约束本身也可以传递地添加.
