= 降级版本和排除依赖

[[sec:enforcing_dependency_version]]
== 覆盖传递依赖版本

Gradle 通过选择在依赖关系图中找到的最新版本来解决任何依赖关系版本冲突. 某些项目可能需要偏离默认行为并强制实施较早版本的依赖,例如 如果项目的源代码依赖于比某些外部库更旧的API.

[WARNING]
====
强制版本的依赖需要有意识的决定. 如果外部库没有它们而无法正常运行,则更改可传递依赖的版本可能会导致运行时错误. 考虑将源代码升级为使用库的较新版本作为替代方法.
====

通常,执行强制依赖关系可以降级依赖关系.降级可能会有不同的用例:

- 在最新版本中发现了一个错误
- 您的代码取决于与二进制不兼容的较低版本
- 您的代码不依赖于需要更高版本依赖的代码路径

在所有情况下,最好的表述是您的代码严格依赖于可传递代码的版本.使用 <<rich_versions.adoc#sec:strict-version,strict versions>>,即使传递依赖另有说明,您也将有效地依赖于声明的版本.

[NOTE]
====
严格的依赖关系在某种程度上类似于 Maven 最接近的优先策略,但存在细微的差异:

- 严格的依存关系不会遇到排序问题: 它们可传递地应用于子图,并且声明依存关系的顺序无关紧要.
- 严格的依存关系冲突将触发构建失败,您必须解决
- 严格的依赖可以与丰富的版本一起使用, <<#sec:strict-version-consequences,这意味着最好在严格范围内结合单个首选版本来表达需求>>.
====

假设一个项目使用 link:https://hc.apache.org/httpcomponents-client-ga/[HttpClient library] 执行 HTTP 调用. HttpClient 从 1.10 版引入 link:https://commons.apache.org/proper/commons-codec/[Commons Codec] 作为传递依赖. 但是,项目的生产源代码需要 Commons Codec 1.9 中的 API,该 API 在 1.10 中不再可用.
可以通过在构建脚本中将其声明为严格来强制实施依赖版本:

.Setting a strict version
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-forceForDependency/groovy/build.gradle[tags=force-using-strictly]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-forceForDependency/kotlin/build.gradle.kts[tags=force-using-strictly]
====

[[sec:strict-version-consequences]]
=== 使用严格版本的后果

必须仔细考虑使用严格的版本,尤其是图书馆作者. 作为生产者,严格版本实际上将表现得像一种力量: 版本声明优先于可传递依赖关系图中发现的任何内容. 特别是,严格版本将覆盖可传递地找到的同一模块上的任何其他严格版本.

但是,对于消费者,在图形解析期间仍会严格考虑严格版本,如果消费者不同意,则可能会触发错误.

例如,假设您的项目 `B` 严格取决于 `C:1.0`. 现在,消费者 `A` 依赖于 `B` 和 `C:1.1`.

然后,这将引发解析错误,因为 `A` 表示需要 `C:1.1`,而 `B` 在其子图中严格要求 `1.0`. 这意味着,如果您在严格限制条件下选择单个版本,则该版本将无法再升级,除非使用者也对同一模块设置了严格版本限制.

在上面的示例中, `A` 必须说它严格取决于1.1.

因此,一个好的做法是,如果您使用严格的版本,则应使用范围和该范围内的首选版本来表达它们. 例如,`B` 可能会说严格地依赖 `[1.0, 2.0[`,而不是 `1.0`,而不是 `strictly 1.0` . 然后,如果使用者选择1.1 (或该范围内的任何其他版本) ,则构建将不再失败 (约束已解决) .

[[forced_dependencies_vs_strict_dependencies]]
=== 强制依赖与严格依赖

[WARNING]
====
不建议使用 link:{javadocPath}/org/gradle/api/artifacts/ExternalDependency.html#setForce-boolean-[ExternalDependency.setForce(boolean)] 强制依赖,并且不再建议使用: 强制依赖存在一个排序问题,该问题很难诊断,
并且无法与其他 <<#sec:enforcing_dependency_version,strict versions>> 一起很好地工作. 您应该选择严格的版本. 如果要编写和 <<library_vs_application.adoc#,library>>,则还需要注意没有发布强制.
====

如果由于某种原因不能使用  <<#sec:enforcing_dependency_version,strict versions>> ,则可以强制执行依赖操作:

.Enforcing a dependency version
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-forceForDependency/groovy/build.gradle[tags=force-per-dependency]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-forceForDependency/kotlin/build.gradle.kts[tags=force-per-dependency]
====

如果项目要求在配置级别上具有特定版本的依赖关系,则可以通过调用方法 link:{groovyDslPath}/org.gradle.api.artifacts.ResolutionStrategy.html#org.gradle.api.artifacts.ResolutionStrategy:force(java.lang.Object++[]++)[ResolutionStrategy.force(java.lang.Object++[]++)] 来实现.

.Enforcing a dependency version on the configuration-level
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-forceForConfiguration/groovy/build.gradle[tags=force-per-configuration]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-forceForConfiguration/kotlin/build.gradle.kts[tags=force-per-configuration]
====

[[sec:excluding-transitive-deps]]
== 排除传递依赖

尽管上一节显示了如何强制实施某个版本的可传递依赖,但本节将排除作为完全删除可传递依赖的一种方式.

[WARNING]
====
与强制依赖版本类似,完全排除依赖需要有意识的决定. 如果外部库没有它们而无法正常运行,则排除传递依赖关系可能会导致运行时错误. 如果您使用排除,请确保您没有通过足够的测试覆盖率来利用任何需要排除依赖的代码路径.
====

可以在声明的依赖级别上排除传递性依赖. 排除通过属性 `group` 和/或 `module` 作为键​​/值对拼出,如以下示例所示. 有关更多信息,请参见  link:{javadocPath}/org/gradle/api/artifacts/ModuleDependency.html#exclude-java.util.Map-[ModuleDependency.exclude(java.util.Map)].

.Excluding a transitive dependency for a particular dependency declaration
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-excludeForDependency/groovy/build.gradle[tags=exclude-transitive-dependencies-1]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-excludeForDependency/kotlin/build.gradle.kts[tags=exclude-transitive-dependencies-1]
====

在此示例中,我们向 `commons-beanutils`  添加了一个依赖关系,但不包括传递依赖 `commons-collections`. 在下面显示的代码中,我们仅使用 beanutils 库中的一种方法 `PropertyUtils.setSimpleProperty()`.
通过我们的测试覆盖范围进行验证,将这种方法用于现有的设置员不需要从 `commons-collections` 获得任何功能.

.Using a utility from the beanutils library
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-excludeForDependency/groovy/src/main/java/Main.java"]
====

实际上,我们表示仅使用该库的一个子集,而该子集不需要 `commons-collection` 库. 可以将其视为隐式定义了 `commons-beanutils` 本身未明确声明的 <<feature_variants.adoc#,feature variant>>. 但是,这样做会增加破坏未经测试的代码路径的风险.

例如,这里我们使用 `setSimpleProperty()` 方法来修改 `Person` 类中 setter 定义的属性,效果很好. 如果尝试设置类中不存在的属性,则会出现 `Unknown property on class Person` 的错误.
但是,由于错误处理路径使用 `commons-collections` 中的类,所以我们现在得到的错误是 `NoClassDefFoundError: org/apache/commons/collections/FastHashMap`. 因此,如果我们的代码更具动态性,而我们忘记了充分涵盖错误情况,则库的使用者可能会遇到意外错误.

这仅仅是说明潜在陷阱的一个示例. 实际上,较大的库或框架会带来大量的依赖关系. 如果这些库未能分别声明功能,并且只能以"全有或全无" 的方式使用,则排除可能是将库缩减为实际所需功能集的有效方法.

从好的方面来看,与 Maven 相比,Gradle 的排除处理考虑了整个依赖关系图. 因此,如果库上有多个依赖,则仅当所有依赖都对它们都同意时才执行排除. 例如,如果我们将 `opencsv` 作为另一个依赖添加到上面的项目中,
而该依赖还取决于 `commons-beanutils`,则不再排除 `commons-collection` ,因为 `opencsv`  本身并不排除它.

.Excludes only apply if all dependency declarations agree on an exclude
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-excludeForDependency/groovy/build.gradle[tags=exclude-transitive-dependencies-2]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-excludeForDependency/kotlin/build.gradle.kts[tags=exclude-transitive-dependencies-2]
====

如果我们仍然希望排除 `commons-collections`,因为  `commons-beanutils`  和 `opencsv` 的组合用法不需要​​它,我们也需要将其从 `opencsv` 的传递依赖中排除.

.Excluding a transitive dependency for multiple dependency declaration
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-excludeForDependency/groovy/build.gradle[tags=exclude-transitive-dependencies-3]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-excludeForDependency/kotlin/build.gradle.kts[tags=exclude-transitive-dependencies-3]
====

从历史上看,排除项还用作解决某些依赖管理系统不支持的其他问题的辅助工具. 但是,Gradle提供了可能更适合解决特定用例的各种功能. 您可以考虑研究以下功能:

- <<#sec:enforcing_dependency_version,Update>> or <<#sec:enforcing_dependency_version,downgrade>> dependency versions:
如果依赖性版本发生冲突,通常最好通过依赖性约束来调整版本,而不是尝试用不需要的版本排除依赖性.
- <<component_metadata_rules.adoc#,Component Metadata Rules>>:
  如果库的元数据明显错误,例如,如果库的元数据包含编译时从不需要的编译时相关性,则可能的解决方案是删除组件元数据规则中的相关性. 这样,您便告诉Gradle不再需要两个模块之间的依赖关系 (即元数据是错误的) ,因此不应考虑. 如果要开发库,则必须注意该信息不会发布,因此有时排除是更好的选择.
- <<dependency_capability_conflict.adoc#,Resolving mutually exclusive dependency conflicts>>:
  您经常看到用排除法解决的另一种情况是,两个依赖不能一起使用,因为它们表示同一事物 ( <<dependency_capability_conflict.adoc#sub:capabilities,capability>) 的两个实现. 一个流行的示例是冲突的日志记录 API 实现
   (例如 `log4j` 和 `log4j-over-slf4j` ) 或在不同版本中具有不同坐标的模块
  (例如 `com.google.collections` 和 `guava` ). 在这种情况下,如果 Gradle 不知道此信息,则建议通过组件元数据规则添加缺少的能力信息,如 <<dependency_capability_conflict.adoc#sub:declaring-component-capabilities,声明组件功能>> 部分中所述. 即使您正在开发库时,
  而您的使用者也不得不再次解决冲突,将决定权交给库的最终使用者通常是正确的解决方案. 即 作为库的作者,您最终不必决定消费者使用哪种日志记录实现.

