[[sec:handling-mutually-exclusive-deps]]
= 处理互斥依赖性

[[sub:capabilities]]
== 组件功能介绍

依赖图通常会偶然包含同一API的多个实现. 这在日志记录框架中尤其常见,在日志记录框架中有多个绑定可用,并且当另一个传递依赖选择另一个时,一个库选择一个绑定. 由于这些实现位于不同的 GAV 坐标下,
因此构建工具通常无法找出这些库之间是否存在冲突. 为了解决这个问题,Gradle 提供了 _capability_ 的概念.

在单个依赖关系图中找到两个提供相同功能的组件是非法的. 直观地讲,这意味着如果 Gradle 在类路径上找到两个提供相同功能的组件,它将失败并显示一条错误消息,指出哪些模块发生冲突.
在我们的示例中,这意味着日志记录框架的不同绑定提供了相同的功能.

== Capability coordinates

_capability_ 是由 `(group, module, version)` 组成的.
每个组件都定义一个与其 GAV 坐标 (group, artifact, version) 相对应的隐式功能.
例如, `org.apache.commons:commons-lang3:3.8` 模块具有 group `org.apache.commons`, name `commons-lang3` and version `3.8` 的隐式功能.
重要的是要认识到功能是版本化的..

[[sub:declaring-component-capabilities]]
== 声明组件功能

默认情况下,如果依赖关系图中的两个组件提供相同的功能,则 Gradle 将失败. 因为当前发布的大多数模块都没有 Gradle 模块元数据,所以 Gradle 并不总是自动发现功能.
但是,使用规则声明组件功能以便在构建而不是运行时尽快发现冲突很有趣.

一个典型的例子是在新版本中,只要将组件重新放置在不同的坐标上. 例如,ASM 库位于 `asm:asm` 坐标处,直到版本 `3.3.1`,然后从 `4.0` 开始更改为 `org.ow2.asm:asm`. 在类路径上同时具有  ASM \<= 3.3.1 and 4.0+ 是非法的,
因为它们提供相同的功能,只是组件已被重定位. 因为每个组件都具有与其 GAV 坐标相对应的隐式功能,所以我们可以通过具有一条规则来 "fix" 此问题,该规则将声明 `asm:asm`  模块提供  `org.ow2.asm:asm` 功能:

.Conflict resolution by capability
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/groovy/build.gradle[tags=fix_asm]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/kotlin/build.gradle.kts[tags=fix_asm]
====

现在,只要在同一个依赖图中找到两个组件,构建就将失败.

[NOTE]
====
在这个阶段,Gradle 只会让更多的构建失败.它不会自动帮你解决问题,但它会帮助你意识到你有问题.建议在插件中编写这样的规则,然后应用到您的构建中.然后,用户必须表达他们的首选项(如果可能的话),或者解决类路径上不兼容的问题,这将在下一节中解释.
====

[[sub:selecting-between-candidates]]
== 在候选者之间进行选择

在某个时候,依赖图将包含不兼容的模块或相互排斥的模块. 例如,您可能有不同的记录器实现,并且需要选择一种绑定. <<#sub:capabilities,Capabilities>> 有助于您意识到自己有冲突,
但是 Gradle 还提供了表达如何解决冲突的工具.

[[sub:selecting-preferred-capability-provider]]
=== 在不同能力的 capability 之间进行选择

在上面的重定位示例中,Gradle 能够告诉您在类路径上有两个版本的同一API: 一个 "old"  模块和一个 "relocated" 模块. 现在,我们可以通过自动选择功能最高的组件来解决冲突:

.Conflict resolution by capability versioning
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/groovy/build.gradle[tags=use_highest_asm]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/kotlin/build.gradle.kts[tags=use_highest_asm]
====

但是,通过选择最高性能的版本冲突解决方法进行修复并不总是适合的.例如,对于日志记录框架,我们使用什么版本的日志记录框架都没关系,我们应始终选择 Slf4j.

在这种情况下,我们可以通过明确选择 slf4j 作为赢家来解决此问题:

.Substitute log4j with slf4j
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/groovy/build.gradle[tags=use_slf4j]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-declaringCapabilities/kotlin/build.gradle.kts[tags=use_slf4j]
====

请注意,如果您在类路径上具有多个 Slf4j 绑定,则此方法也很好用: 绑定本质上是不同的记录器实现,并且只需要一个. 但是,所选的实现可能取决于要解决的配置. 例如,对于测试而言,`slf4j-simple` 可能就足够了,
但对于生产而言,`slf4-over-log4j` 可能会更好.

[NOTE]
====
只能使用图中找到的模块来进行解析.

`select` 方法仅接受当前候选中找到的模块. 如果要选择的模块不是冲突的一部分,则可以放弃选择,从而无法有效解决此冲突. 对于相同的功能,图中可能存在另一个冲突,并且将具有您要选择的模块.

如果没有针对给定功能上的所有冲突给出解决方案,则由于为解决方案选择的模块根本不是图形的一部分,构建将失败.

另外 `select(null)` 将导致错误,因此应避免使用.
====

有关更多信息,请查看 link:{javadocPath}/org/gradle/api/artifacts/ResolutionStrategy.html#capabilitiesResolution[the capabilities resolution API].
