[[sec:sharing-dep-versions-between-projects]]
= 在项目之间共享依赖版本

[[sub:using-platform-to-control-transitive-deps]]
== 使用 platform 控制传递版本

<<dependency_management_terminology.adoc#sub::terminology_platform,platform>> 是一种特殊的软件组件,可用于控制传递依赖版本.
在大多数情况下,它完全由 <<dependency_constraints.adoc#sec:adding-constraints-transitive-deps,依赖约束>> 组成,这些约束要么建议依赖版本,要么强制执行某些版本.因此,当您需要在项目之间共享依赖版本时,这是一个完美的工具.在这种情况下,项目通常是这样组织的

- 一个为不同子项目中发现的各种依赖关系定义约束的 `platform` 项目
- 许多子项目依赖于 `platform` 并声明依赖关系而不声明版本

在Java生态系统中,Gradle 为此提供了一个 <<java_platform_plugin.adoc#java_platform_plugin,plugin>> .

通常 Gradle <<#sub:bom_import,Gradle supports natively>> 也支持的发布为 Maven BOMs 的 platform

`platform` 关键字创建对 platform 的依赖:

.Getting versions declared in a platform
====
include::{snippets-dir}/java-platform/recommender/groovy/consumer/build.gradle[tags=get-recommendations]
include::{snippets-dir}/java-platform/recommender/kotlin/consumer/build.gradle.kts[tags=get-recommendations]
====

[NOTE]
====
这是 `platform` 的简写,它实际上在底层执行几个操作:

* 它将 link:{javadocPath}/org/gradle/api/attributes/Category.html[org.gradle.category attribute] 属性设置为 `platform`, 这意味着 Gradle 将选择依赖的 platform 组件
* 它默认设置 link:{javadocPath}/org/gradle/api/artifacts/ModuleDependency.html#endorseStrictVersions--[endorseStrictVersions] 行为,这意味着如果 platform 声明了严格的依赖关系,则将强制执行它们.

这意味着默认情况下,对 platform 的依赖会触发该 platform 中定义的所有 <<rich_versions.adoc#sec:strict-version,strict versions>>  的继承,这对于 platform 的作者确保所有使用者在依赖的版本方面都遵循自己的决定很有用.
可以通过显式调用 `doNotEndorseStrictVersions`  方法将其关闭.
====

[[sub:bom_import]]
== 导入 Maven BOMs

Gradle为导入 https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Importing_Dependencies[bill of materials (BOM) files] 文件提供支持,该文件是有效的 `.pom` 文件,
使用 `<dependencyManagement>` 来控制直接和传递依赖的依赖版本. 当依赖于 Maven 中的 BOM 时,Gradle 中的 BOM 支持与使用 `<scope>import</scope>`  相似. 但是,在 Gradle 中,这是通过 BOM 上的常规依赖声明完成的:

.Depending on a BOM to import its dependency constraints
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-constraintsFromBOM/groovy/build.gradle[tags=dependency-on-bom]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-constraintsFromBOM/kotlin/build.gradle.kts[tags=dependency-on-bom]
====

在示例中,Spring Boot BOM 提供了 `gson` 和 `dom4j` 的版本.这样,如果您正在开发像 Spring Boot 这样的平台,则不必自己声明任何版本,而可以依赖平台提供的版本.

Gradle 对 BOM 的 `<dependencyManagement>` 块中的所有条目的方式类似于  <<dependency_constraints.adoc#sec:adding-constraints-transitive-deps,Gradle 的依赖约束>> . 这意味着 `<dependencyManagement>` 块中定义的任何版本都可能影响依赖性解析结果. 为了有资格作为 BOM,`.pom` 文件需要设置 `<packaging>pom</packaging>`.

但是,BOM 通常不仅提供版本作为建议,而且还提供一种方法来覆盖图中找到的任何其他版本.导入 BOM 时,可以通过使用 `enforcedPlatform` 关键字而不是 `platform` 来启用此行为:

.Importing a BOM, making sure the versions it defines override any other version found
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-enforcedConstraintsFromBOM/groovy/build.gradle[tags=dependency-on-bom]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-enforcedConstraintsFromBOM/kotlin/build.gradle.kts[tags=dependency-on-bom]
====
