[[resolution_rules]]
= 直接自定义依赖解析

[WARNING]
====
本节介绍了 Gradle 提供的直接影响依赖关系解析引擎行为的机制. 与本章介绍的其他概念 (例如 <dependency_constraints.adoc#,dependency constraints>> or <<component_metadata_rules.adoc#,component metadata rules>>) 都是解析的输入相反,以下机制使您可以编写直接注入解析引擎的规则.
因此,它们可以看作是蛮力解决方案,可能会隐藏未来的问题 (例如,如果添加了新的依赖) . 因此,一般建议仅在其他手段不足的情况下使用以下机制.
如果要编写 <<library_vs_application.adoc#,library>>,则应始终首选 <<dependency_constraints.adoc#,dependency constraints>>,因为它们是为用户发布的.
====

[[sec:dependency_resolve_rules]]
== 使用依赖解决规则

为每个已解析的依赖执行一个依赖解析规则,并提供了一个强大的 api,用于在解析依赖之前处理请求的依赖. 该功能当前提供了更改请求的依赖的group, name and/or version 的功能,从而允许在解析过程中将依赖替换为完全不同的模块.

依赖关系解析规则提供了一种非常强大的方法来控制依赖关系解析过程,并且可用于实现依赖关系管理中的各种高级模式. 下面概述了其中一些模式. 有关更多信息和代码示例,请参阅 API 文档中的
link:{groovyDslPath}/org.gradle.api.artifacts.ResolutionStrategy.html[ResolutionStrategy] 类.

[[sec:custom_versioning_scheme]]
=== 实现自定义版本管理方案

在某些公司环境中,可以在 Gradle 构建中声明的模块版本列表由外部维护和审核. 依赖性解析规则为这种模式提供了一种简洁的实现方式:

In some corporate environments, the list of module versions that can be declared in Gradle builds is maintained and audited externally.
Dependency resolve rules provide a neat implementation of this pattern:

* 在构建脚本中,开发人员使用模块组和名称声明依赖关系,但使用占位符版本,例如: `default`.
* 通过依赖关系解析规则将 `default` 版本解析为特定版本,该规则在已批准模块的公司目录中查找该版本.

这个规则实现可以被巧妙地封装在企业插件中,并在各个插件之间共享

.Using a custom versioning scheme
====
include::{snippets-dir}/dependencyManagement/customizingResolution-resolutionStrategy/groovy/build.gradle[tags=custom-versioning-scheme]
include::{snippets-dir}/dependencyManagement/customizingResolution-resolutionStrategy/kotlin/build.gradle.kts[tags=custom-versioning-scheme]
====

[[sec:denying_version]]
=== 拒绝替换特定版本

依赖性解析规则提供了一种机制,用于拒绝依赖性的特定版本并提供替代版本. 如果某个依赖版本已损坏并且不应使用,当依赖解析规则导致该版本被已知的良好版本替换时,这将很有用. 损坏的模块的一个示例是声明对库的依赖关系,该依赖关系在任何公共存储库中都找不到,但是还有许多其他原因导致不需要特定的模块版本,而首选其他版本.

在下面的示例中,假设 `1.2.1` 版包含重要的修复程序,应该始终优先使用 `1.2` 版. 提供的规则将强制执行此操作: 只要遇到 `1.2` 版,就会将其替换为 `1.2.1`.
请注意,这与如上所述的强制版本不同,因为此模块的任何其他版本都不会受到影响. 这意味着,'newest' 冲突解决策略将仍然选择 `1.3` 版,前提是该版本也被以可传递方式拉出.

.Example: Blacklisting a version with a replacement
====
include::{snippets-dir}/dependencyManagement/customizingResolution-resolutionStrategy/groovy/build.gradle[tags=denying_version]
include::{snippets-dir}/dependencyManagement/customizingResolution-resolutionStrategy/kotlin/build.gradle.kts[tags=denying_version]
====

[NOTE]
====
使用  <<rich_versions.adoc#rich-version-constraints,rich version constraints>>: 的 _reject_  是有区别的: 如果在图中找到了拒绝版本,则富版本将导致构建失败,
或者在使用动态依赖时选择非拒绝版本. 在这里,我们处理请求的版本,以便在找到被拒绝的版本时选择其他版本. 换句话说,这是针对拒绝版本的解决方案,
而丰富版本限制允许声明意图 (您不应使用此版本) .
====

[[sec:module_replacement]]
== 使用模块替换规则

就功能冲突而言,最好表达 <<dependency_capability_conflict.adoc#sub:capabilities, capabilities conflicts>>. 但是,如果没有声明这样的规则,或者您正在使用不支持功能的 Gradle 版本,则 Gradle 提供了解决这些问题的工具.
 
模块替换规则允许构建声明旧库已被新库替换. 新库取代旧库的一个很好的例子是 `google-collections` -&gt; `guava` . 创建Google集合的团队决定将模块名称从
`com.google.collections:google-collections` 更改为 `com.google.guava:guava`. 这是行业中的一种合法情况: 团队需要能够更改其维护的产品名称,包括模块坐标. 重命名模块坐标会影响冲突解决.

为了解释对解决冲突的影响,让我们考虑 `google-collections` -&gt; `guava`  的场景.这两个库可能会被拉到同一个依赖关系图中.例如,我们的项目依赖于 guava,
但是我们的一些依赖引入了 `google-collections` 的遗留版本.这可能会导致运行时错误,例如在测试或应用程序执行期间.Gradle 不会自动解决 `google-collections` -&gt; `guava`  冲突,
因为它不被认为是版本冲突.这是因为这两个库的模块坐标是完全不同的.并且当 `group` and `module` 坐标相同时会激活冲突解决方案,
但是在依赖关系图中有不同的版本可用 (有关更多信息,请参阅冲突解决部分) . 解决此问题的传统方法是:

* 声明排除规则,以避免将 `google-collections`  中. 这可能是最流行的方法.
* 避免引入旧式库的依赖.
* 如果新版本不再引入旧版库,请升级依赖版本.
* 降级为 `google-collections`. 出于完整性考虑,不建议使用.

传统方法行之有效,但它们不够笼统. 例如,一个组织想要解决所有项目中的 `google-collections` -&gt; `guava`  冲突解决问题. 可以声明某些模块已被其他模块替代.
这使组织能够将有关模块更换的信息包括在公司插件套件中,并全面解决企业中所有由 Gradle 支持的项目的问题.

.Declaring a module replacement
====
include::{snippets-dir}/dependencyManagement/customizingResolution-replacementRule/groovy/build.gradle[tags=module_replacement_declaration]
include::{snippets-dir}/dependencyManagement/customizingResolution-replacementRule/kotlin/build.gradle.kts[tags=module_replacement_declaration]
====

有关更多示例和详细 API,请参考  link:{javadocPath}/org/gradle/api/artifacts/dsl/ComponentMetadataHandler.html[ComponentMetadataHandler] 的 DSL 引用.

当我们声明 `google-collections` 被 `guava` 取代时会发生什么? Gradle 可以使用这些信息来解决冲突.Gradle 会认为每一个版本的番石榴都比任何一个版本的 `google-collections` 要更新/更好.
另外,Gradle 将确保类路径/解析文件列表中只有 guava jar.请注意,如果只有 `google-collections` 出现在依赖图中(例如没有 `guava`),Gradle 不会急切地用 `guava` 代替它.
模块替换是 Gradle 用来解决冲突的信息.如果没有冲突(例如图中只 有 `google-collections` 或只有 `guava`),则不使用替换信息.

目前,不可能声明给定的模块被一组模块替换.但是,可以声明多个模块被单个模块替换.

[[sec:dependency_substitution_rules]]
== 使用依赖替换规则

依赖关系替换规则的工作方式与依赖关系解决规则相似. 实际上,可以使用依赖关系替换规则来实现依赖关系解析规则的许多功能. 它们允许将项目和模块依赖透明地替换为指定的替换项. 与依赖关系解析规则不同,依赖关系替换规则允许项目和模块依赖关系可以互换替换.

向配置中添加依赖替换规则会更改解析该配置的时间. 在构造任务图时,无需解析首次使用的配置,而是解析配置. 如果在任务执行期间对配置进行了进一步修改,或者配置依赖于在执行另一任务期间发布的模块,则可能会产生意外的后果.

解释:

* 可以将 `Configuration` 声明为任何任务的输入,并且在解决配置时,该配置可以包括项目依赖.
* 如果项目依赖是任务的输入 (通过配置) ,则必须将用于构建项目 artifacts 的任务添加到任务依赖中.
* 为了确定作为任务输入的项目依赖关系,Gradle 需要解析 `Configuration`  输入.
* 由于 Gradle 任务图在任务执行开始后便是固定的,因此 Gradle 需要在执行任何任务之前执行此解决方案.

在没有依赖替换规则的情况下,Gradle 知道外部模块依赖永远不会传递引用项目依赖. 这样就可以通过简单的图形遍历轻松确定配置的完整项目依赖集合. 使用此功能,Gradle 不能再进行此假设,并且必须执行完全解析才能确定项目依赖.

[[sub:module_to_project_substitution]]
=== 将外部模块依赖替换为项目依赖

一种替代依赖的用例是使用模块的本地开发版本来代替从外部存储库下载的模块. 这对于测试依赖的本地修补版本可能很有用..

可以在指定版本或不指定版本的情况下声明要替换的模块.

.Substituting a module with a project
====
include::{snippets-dir}/dependencyManagement/customizingResolution-substitutionRule/groovy/build.gradle[tags=module_to_project_substitution]
include::{snippets-dir}/dependencyManagement/customizingResolution-substitutionRule/kotlin/build.gradle.kts[tags=module_to_project_substitution]
====

请注意,替代项目必须包含在多项目构建中 (通过 `settings.gradle`) . 依赖关系替换规则负责将模块依赖关系替换为项目依赖关系,并连接所有任务依赖关系,但不将项目隐式包含在构建中.

[[sub:project_to_module_substitution]]
=== 用模块替换代替项目依赖

使用替换规则的另一种方法是用多项目构建中的模块替换项目依赖. 通过允许从存储库中下载而不是构建项目依赖的子集,这对于加快大型多项目构建的开发速度可能非常有用.

必须使用指定的版本声明要用作替换模块的模块.

.Substituting a project with a module
====
include::{snippets-dir}/dependencyManagement/customizingResolution-substitutionRule/groovy/build.gradle[tags=project_to_module_substitution]
include::{snippets-dir}/dependencyManagement/customizingResolution-substitutionRule/kotlin/build.gradle.kts[tags=project_to_module_substitution]
====

当项目依赖关系已替换为模块依赖关系时,该项目仍将包含在整个多项目构建中. 但是,为了解决依赖的 `Configuration`,将不会执行构建替换后的依赖的任务.

[[sub:conditional_dependency_substitution]]
=== 有条件地替换依赖

依赖替换的一个常见用例是允许在多项目构建中更灵活地组装子项目. 这对于开发外部依赖的本地修补版本或在大型多项目构建中构建模块的子集很有用.

以下示例使用依赖替换规则将任何模块依赖替换为 `org.example` 组,但前提是必须找到与依赖名称匹配的本地项目.

.Conditionally substituting a dependency
====
include::{snippets-dir}/dependencyManagement/customizingResolution-conditionalSubstitutionRule/groovy/consumer/build.gradle[tags=project_substitution]
include::{snippets-dir}/dependencyManagement/customizingResolution-conditionalSubstitutionRule/kotlin/consumer/build.gradle.kts[tags=project_substitution]
====

请注意,替代项目必须包含在多项目构建中 (通过 `settings.gradle`) . 依赖关系替换规则负责将模块依赖关系替换为项目依赖关系,但不将项目隐式包含在构建中.

[[sec:variant_aware_substitutions]]
=== 用另一个变量替换依赖

Gradle 的依赖管理引擎具有 <<variant_model.adoc#understanding-variant-selection,variant-aware>> 功能,这意味着对于单个组件,该引擎可以选择不同的 artifacts 和可传递的依赖.

选择什么取决于使用者配置的属性和在生产者端找到的变体的属性. 但是,某些特定的依赖关系可能会覆盖配置本身的属性. 使用 <<java_platform_plugin.adoc#java_platform_plugin,Java Platform plugin>> 时通常是这种情况: 该插件构建一种特殊的组件,称为"平台" ,可以通过将组件类别属性设置为Platform来解决,这与作为目标库的典型依赖相反.

因此,您可能会遇到想要用常规依赖替换平台依赖或其他方式的情况.

[[sec:substitution_with_attributes]]
==== 用属性替换依赖

假设您要用常规依赖替换平台依赖.这意味着您正在使用的库声明如下:

.An incorrect dependency on a platform
====
include::{snippets-dir}/dependencyManagement/customizingResolution-attributeSubstitutionRule/groovy/lib/build.gradle[tags=dependencies]
include::{snippets-dir}/dependencyManagement/customizingResolution-attributeSubstitutionRule/kotlin/lib/build.gradle.kts[tags=dependencies]
====

`platform` 关键字实际上是带有属性的依赖的简写形式. 如果要用常规依赖关系替换此依赖关系,则需要精确选择具有 `platform` 属性的依赖关系

这可以通过使用替换规则来完成:

.Substitute a platform dependency with a regular dependency
====
include::{snippets-dir}/dependencyManagement/customizingResolution-attributeSubstitutionRule/groovy/consumer/build.gradle[tags=substitution_rule]
include::{snippets-dir}/dependencyManagement/customizingResolution-attributeSubstitutionRule/kotlin/consumer/build.gradle.kts[tags=substitution_rule]
====

同一条没有 `platform` 关键字的规则会尝试用常规依赖替换常规依赖,这不是您想要的,因此,重要的是要了解替代规则适用于依赖规范: 它将匹配的请求依赖 (替换为 XXX) 与 替代品 (使用 YYY) .

您可以在请求的依赖或替代项上都具有属性,并且替代项不仅限于 `platform`: 实际上,您可以使用变体符号来指定整个依赖属性集. 以下规则与上述规则严格等效:

.Substitute a platform dependency with a regular dependency using the variant notation
====
include::{snippets-dir}/dependencyManagement/customizingResolution-attributeSubstitutionRule/groovy/consumer/build.gradle[tags=substitution_rule_alternative]
include::{snippets-dir}/dependencyManagement/customizingResolution-attributeSubstitutionRule/kotlin/consumer/build.gradle.kts[tags=substitution_rule_alternative]
====

请参考 link:{javadocPath}/org/gradle/api/artifacts/DependencySubstitutions.html#variant-org.gradle.api.artifacts.component.ComponentSelector-org.gradle.api.Action-[Substitution DSL API docs] 文档,以获取变体替代 API 的完整参考.

[WARNING]
====
在 <<composite_builds.adoc#composite_build_intro,composite builds>> 中,不应用必须与请求的确切依赖属性完全匹配的规则: 使用复合时,Gradle 将自动匹配请求的属性. 换句话说,
如果您包含另一个构建,则意味着您要用包含的构建中的等效变体替换替换模块的所有变体.
====

[[sec:substitution_with_capabilities]]
==== 用具有功能的依赖替换依赖

与 <<resolution_rules.adoc#sec:substitution_with_attributes,attributes substitution>> 类似,Gradle 允许您将具有或不具有功能的依赖替换为具有或不具有功能的另一个依赖.

例如,假设您需要将常规依赖替换为其 <<java_testing.adoc#sec:java_test_fixtures,test fixtures>> . 您可以使用以下依赖替换规则来实现:

.Substitute a dependency with its test fixtures
====
include::{snippets-dir}/dependencyManagement/customizingResolution-capabilitySubstitutionRule/groovy/build.gradle[tags=substitution_rule]
include::{snippets-dir}/dependencyManagement/customizingResolution-capabilitySubstitutionRule/kotlin/build.gradle.kts[tags=substitution_rule]
====

在替代规则中对所请求的依赖声明的功能构成了依赖匹配规范的一部分,因此不需要这些功能的依赖将不匹配.

请参考 link:{javadocPath}/org/gradle/api/artifacts/DependencySubstitutions.html#variant-org.gradle.api.artifacts.component.ComponentSelector-org.gradle.api.Action-[Substitution DSL API docs] 文档,以获取变体替代API的完整参考.

[WARNING]
====
在 <<composite_builds.adoc#composite_build_intro,composite builds>> 中,不应用您必须匹配确切的请求依赖功能的规则: 使用组合时,Gradle 将自动匹配请求的功能. 换句话说,如果您包括另一个版本,则意味着您要用包含的版本中的等效变体替换替换模块的所有 _variants_.]
====

[[sec:substitution_with_classifier]]
=== 用 classifier 或 artifact 替换依赖

虽然通常通过 group/artifact/version 坐标来访问外部模块,但是通常会发布此类模块并附带其他 artifacts ,您可能希望使用它们来代替主 artifacts . 对于分类的 artifacts ,通常是这种情况,
但是您可能还需要选择具有不同文件类型或扩展名的 artifacts . Gradle 不鼓励在依赖中使用分类器,而是更喜欢将这些 artifacts 建模为 <<variant_model.adoc#understanding-variant-selection,variants additional variants of a module>>. 使用变体代替分类的 artifacts 有很多优点,
包括但不仅限于这些 artifacts 的一组不同的依赖关系.

但是,为了帮助桥接两个模型,Gradle 提供了在替换规则中更改或删除分类器的方法.

.Dependencies which will lead to a resolution error
====
include::{snippets-dir}/dependencyManagement/customizingResolution-classifierSubstitutionRule/groovy/consumer/build.gradle[tags=dependencies]
include::{snippets-dir}/dependencyManagement/customizingResolution-classifierSubstitutionRule/kotlin/consumer/build.gradle.kts[tags=dependencies]
====

在上面的示例中,对 `quasar` 的第一级依赖使我们认为 Gradle 将解析 `quasar-core-0.8.0.jar`,但事实并非如此: 构建将因以下消息而失败:

[source]
----
Execution failed for task ':resolve'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find quasar-core-0.8.0-jdk8.jar (co.paralleluniverse:quasar-core:0.8.0).
     Searched in the following locations:
         https://jcenter.bintray.com/co/paralleluniverse/quasar-core/0.8.0/quasar-core-0.8.0-jdk8.jar
----

这是因为存在对另一个项目 `lib` 的依赖,它本身依赖于不同版本的 `quasar-core`:

.A "classified" dependency
====
include::{snippets-dir}/dependencyManagement/customizingResolution-classifierSubstitutionRule/groovy/lib/build.gradle[tags=dependencies]
include::{snippets-dir}/dependencyManagement/customizingResolution-classifierSubstitutionRule/kotlin/lib/build.gradle.kts[tags=dependencies]
====

发生的是,Gradle 将在 `quasar-core` 0.8.0  和 `quasar-core` 0.7.12_r3 之间执行冲突解决. 因为 `0.8.0` 更高,所以我们选择此版本,但是 `lib` 中的依赖具有分类器 jdk8,
并且此分类器在 `0.8.0` 版中不再存在.

要解决此问题,您可以要求 Gradle 在没有分类器的情况下解决这两个依赖:

.A resolution rule to disable selection of a classifier
====
include::{snippets-dir}/dependencyManagement/customizingResolution-classifierSubstitutionRule/groovy/consumer/build.gradle[tags=substitution_rule]
include::{snippets-dir}/dependencyManagement/customizingResolution-classifierSubstitutionRule/kotlin/consumer/build.gradle.kts[tags=substitution_rule]
====

该规则有效地用没有分类器的依赖关系替换了在图中找到的对 `quasar-core` 的依赖关系.

另外,也可以选择具有特定分类器的依赖,或者,对于更特定的用例,可以替换为非常特定的 artifacts  (类型,扩展名和分类器) .

有关更多信息,请参考以下API文档:

- artifact selection via the link:{javadocPath}/org/gradle/api/artifacts/DependencySubstitutions.Substitution.html[Substitution DSL]
- artifact selection via the link:{javadocPath}/org/gradle/api/artifacts/DependencySubstitution.html#artifactSelection-org.gradle.api.Action-[DependencySubstitution API]
- artifact selection via the link:{javadocPath}/org/gradle/api/artifacts/ResolutionStrategy.html#dependencySubstitution-org.gradle.api.Action-[ResolutionStrategy API]

[[sec:disabling_resolution_transitive_dependencies]]
== 禁用传递解析

默认情况下,Gradle 解析依赖元数据指定的所有传递依赖. 有时这种行为可能是不希望的,例如 如果元数据不正确或定义了较大的传递依赖关系图.
您可以通过将 link:{javadocPath}/org/gradle/api/artifacts/ModuleDependency.html#setTransitive-boolean-[ModuleDependency.setTransitive(boolean)] 设置为 `false` 来告诉 Gradle 为依赖禁用传递依赖管理. 结果,只有主 artifacts 才可以解决声明的依赖.

.Disabling transitive dependency resolution for a declared dependency
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-disableForDependency/groovy/build.gradle[tags=transitive-per-dependency]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-disableForDependency/kotlin/build.gradle.kts[tags=transitive-per-dependency]
====

[NOTE]
====
禁用传递依赖解析可能需要您在构建脚本中声明必要的运行时依赖,否则将自动解决.否则可能会导致运行时类路径问题.
====

项目可以决定完全禁用传递依赖解析. 您或者不想依赖发布到已使用的存储库的元数据,或者想要完全控制图形中的依赖. 有关更多信息,请参见 link:{javadocPath}/org/gradle/api/artifacts/Configuration.html#setTransitive-boolean-[Configuration.setTransitive(boolean)].

.Disabling transitive dependency resolution on the configuration-level
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-disableForConfiguration/groovy/build.gradle[tags=transitive-per-configuration]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-disableForConfiguration/kotlin/build.gradle.kts[tags=transitive-per-configuration]
====

== Changing configuration dependencies prior to resolution

有时,插件可能要在解析配置之前先修改其相关性. `withDependencies` 方法允许以编程方式添加,删除或修改依赖.

.Modifying dependencies on a configuration
====
include::{snippets-dir}/dependencyManagement/customizingResolution-withDependencies/groovy/build.gradle[tags=configuration-with-dependencies]
include::{snippets-dir}/dependencyManagement/customizingResolution-withDependencies/kotlin/build.gradle.kts[tags=configuration-with-dependencies]
====

[[sec:configuration_defaults]]
== 设置默认配置依赖

如果未为配置显式设置依赖,则可以使用默认依赖来配置配置. 此功能的主要用例是开发使用用户可能会覆盖的版本控制工具的插件. 通过指定默认依赖关系,只有在用户未指定要使用的特定版本时,插件才能使用该工具的默认版本.

.Specifying default dependencies on a configuration
====
include::{snippets-dir}/dependencyManagement/customizingResolution-defaultDependency/groovy/build.gradle[tags=configuration-default-dependencies]
include::{snippets-dir}/dependencyManagement/customizingResolution-defaultDependency/kotlin/build.gradle.kts[tags=configuration-default-dependencies]
====

== 从配置中完全排除依赖

与 <<dependency_downgrade_and_exclude.adoc#sec:excluding-transitive-deps,excluding a dependency in a dependency declaration>> 类似,您可以使用 link:{groovyDslPath}/org.gradle.api.artifacts.Configuration.html#org.gradle.api.artifacts.Configuration:exclude(java.util.Map)[Configuration.exclude(java.util.Map)] 完全排除特定配置的传递性依赖. 对于配置上声明的所有依赖关系,这将自动排除传递依赖关系.

.Excluding transitive dependency for a particular configuration
====
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-excludeForConfiguration/groovy/build.gradle[tags=exclude-transitive-dependencies]
include::{snippets-dir}/dependencyManagement/managingTransitiveDependencies-excludeForConfiguration/kotlin/build.gradle.kts[tags=exclude-transitive-dependencies]
====

== 将依赖与存储库进行匹配

Gradle 公开了一个 API,以声明存储库可能包含或不包含的内容. 此功能提供了对哪个存储库提供哪些 artifacts 的精细控制,这可以是控制依赖来源的一种方法.

请转至有关 <<declaring_repositories.adoc#sec:repository-content-filtering,存储库内容过滤的部分>> ,以了解有关此功能的更多信息.

[[sec:ivy_dynamic_resolve_mode]]
== 启用 Ivy 动态解析模式

Gradle 的 Ivy 存储库实施支持与 Ivy 的动态解析模式等效的功能. 通常,Gradle 将对 `ivy.xml` 文件中包含的每个依赖定义使用 `rev` 属性. 在动态解析模式下,对于给定的依赖定义,Gradle 将更喜欢 `revConstraint` 属性而不是 `rev` 属性.
 如果 `revConstraint` 属性不存在,则使用 `rev` 属性.

要启用动态解析模式,您需要在存储库定义中设置适当的选项. 下面显示了两个示例. 请注意,动态解析模式仅适用于 Gradle 的 Ivy 存储库. 它不适用于 Maven 存储库或自定义 Ivy `DependencyResolver` 实现.

.Enabling dynamic resolve mode
====
include::{snippets-dir}/dependencyManagement/customizingResolution-ivyDynamicMode/groovy/build.gradle[tags=ivy-repo-dynamic-mode]
include::{snippets-dir}/dependencyManagement/customizingResolution-ivyDynamicMode/kotlin/build.gradle.kts[tags=ivy-repo-dynamic-mode]
====
