= 核心配置


[[webflux-oauth2-login-sample]]
== Spring Boot 2.x 示例

Spring Boot 2.x 为 OAuth 2.0 登录带来了完整的自动配置功能.

本部分显示了如何使用 Google 作为身份验证提供程序来配置 {gh-samples-url}/reactive/webflux/java/oauth2/login[*OAuth 2.0 Login sample*],并涵盖以下主题:

* <<webflux-oauth2-login-sample-setup,初始设置>>
* <<webflux-oauth2-login-sample-redirect,设置重定向 URI>>
* <<webflux-oauth2-login-sample-config,配置 `application.yml`>>
* <<webflux-oauth2-login-sample-start,启动应用程序>>


[[webflux-oauth2-login-sample-setup]]
=== 初始设置

要使用 Google 的 OAuth 2.0 身份验证系统登录,您必须在 Google API 控制台中设置一个项目以获得 OAuth 2.0 凭据.

NOTE: https://developers.google.com/identity/protocols/OpenIDConnect[Google's OAuth 2.0 实现] 符合 https://openid.net/connect/[OpenID Connect 1.0] 规范,并且已通过 https://openid.net/certification/[OpenID Certified].

请按照设置 https://developers.google.com/identity/protocols/OpenIDConnect[OpenID Connect]  (需要翻墙才能访问,链接打开是 Google 的开发者平台控制台) 部分开始的 OpenID Connect 页面上的说明进行操作.

完成 "获取 OAuth 2.0 凭据" 说明后,您应该拥有一个新的 OAuth 客户端,其凭据由 Client ID 和 Client Secret.组成.

[[webflux-oauth2-login-sample-redirect]]
=== 设置重定向URI

重定向 URI 是用户的在通过 Google 身份验证并在授权页面上同意 (_(<<oauth2login-sample-initial-setup,在上一步中创建>>)_) OAuth 客户端的访问权限后,由 Google 重定向的回调链接地址

在 设置重定向 URI 子章节中,确保将  *Authorized redirect URIs* 字段设置为 `http://localhost:8080/login/oauth2/code/google`.

TIP: 默认重定向 URI 模板为 `{baseUrl}/login/oauth2/code/{registrationId}`..  *_registrationId_* 是 <<oauth2Client-client-registration,ClientRegistration>> 的唯一标识符.

IMPORTANT: 如果 OAuth 客户端在代理服务器 (例如: Nginx) 后面运行,建议检查<<http-proxy-server, 代理服务器配置>>以确保正确配置了应用程序.  另外,请参阅 `redirect-uri` 支持的<<oauth2Client-auth-code-redirect-uri, `URI` 模板变量>>.

[[webflux-oauth2-login-sample-config]]
=== Configure `application.yml`

现在,您有了 Google 的新 OAuth 客户端,您需要配置应用程序以将 OAuth 客户端用于身份验证流程.  为此:

. 转到 `application.yml` 并设置以下配置:
+
[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:	<1>
          google:	<2>
            client-id: google-client-id
            client-secret: google-client-secret
----
+
.OAuth 客户端属性
====
<1> `spring.security.oauth2.client.registration` 是 OAuth 客户端属性的基本属性前缀.
<2> 基本属性前缀后面是<<oauth2Client-client-registration,ClientRegistration>>的 ID,例如 google
====

. 将 `client-id` 和 `client-secret` 属性中的值替换为您先前创建的OAuth 2.0凭据.


[[webflux-oauth2-login-sample-start]]
=== 启动应用程序

启动 Spring Boot 2.x 示例并转到 `http://localhost:8080`.  然后,您将会被重定向到默认自动生成的登录页面,该页面显示Google的链接.

单击 Google 链接,然后您将重定向到 Google 进行身份验证.

在使用您的 Google 帐户凭据进行身份验证之后,显示给您的下一页是 *Allow* 页面.   *Allow* 页面要求您允许或拒绝之前创建的 OAuth 客户端的访问权限.  点击 *Allow* 以授权 OAuth 客户端访问您的电子邮件地址和基本个人资料信息.

此时,OAuth 客户端将从 https://openid.net/specs/openid-connect-core-1_0.html#UserInfo[UserInfo Endpoint] 检索您的电子邮件地址和基本个人资料信息,并建立经过身份验证的会话.


[[oauth2login-boot-property-mappings]]
== Spring Boot 2.x 属性映射

下表概述了 Spring Boot 2.x OAuth Client 属性到 <<oauth2Client-client-registration,ClientRegistration>> 属性的映射。

|===
|Spring Boot 2.x | ClientRegistration

|`spring.security.oauth2.client.registration._[registrationId]_`
|`registrationId`

|`spring.security.oauth2.client.registration._[registrationId]_.client-id`
|`clientId`

|`spring.security.oauth2.client.registration._[registrationId]_.client-secret`
|`clientSecret`

|`spring.security.oauth2.client.registration._[registrationId]_.client-authentication-method`
|`clientAuthenticationMethod`

|`spring.security.oauth2.client.registration._[registrationId]_.authorization-grant-type`
|`authorizationGrantType`

|`spring.security.oauth2.client.registration._[registrationId]_.redirect-uri`
|`redirectUri`

|`spring.security.oauth2.client.registration._[registrationId]_.scope`
|`scopes`

|`spring.security.oauth2.client.registration._[registrationId]_.client-name`
|`clientName`

|`spring.security.oauth2.client.provider._[providerId]_.authorization-uri`
|`providerDetails.authorizationUri`

|`spring.security.oauth2.client.provider._[providerId]_.token-uri`
|`providerDetails.tokenUri`

|`spring.security.oauth2.client.provider._[providerId]_.jwk-set-uri`
|`providerDetails.jwkSetUri`

|`spring.security.oauth2.client.provider._[providerId]_.issuer-uri`
|`providerDetails.issuerUri`

|`spring.security.oauth2.client.provider._[providerId]_.user-info-uri`
|`providerDetails.userInfoEndpoint.uri`

|`spring.security.oauth2.client.provider._[providerId]_.user-info-authentication-method`
|`providerDetails.userInfoEndpoint.authenticationMethod`

|`spring.security.oauth2.client.provider._[providerId]_.user-name-attribute`
|`providerDetails.userInfoEndpoint.userNameAttributeName`
|===

[TIP]
通过指定 `spring.security.oauth2.client.provider._[providerId]_.issuer-uri` 属性,可以使用 OpenID Connect 提供者的 https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[配置端点] 或授权服务器的
https://tools.ietf.org/html/rfc8414#section-3[Metadata endpoint]。

[[webflux-oauth2-login-common-oauth2-provider]]
== CommonOAuth2Provider

`CommonOAuth2Provider` 为许多知名提供商预定义了一组默认客户端属性：Google、GitHub、Facebook 和 Okta。

例如，对于 Provider，`authorization-uri`、`token-uri` 和 `user-info-uri` 不会经常更改。 因此，提供默认值以减少所需的配置是有意义的。

如前所述，当我们 <<webflux-oauth2-login-sample-config,configured a Google client>> 时，只需要 `client-id` 和 `client-secret` 属性。

以下显示了一个示例:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret
----

[TIP]
客户端的默认属性会自动添加，因为 `registrationId` (`google`) 匹配 `CommonOAuth2Provider` 中的 `GOOGLE` `enum`（不区分大小写）。

对于您可能想要指定不同的 `registrationId` 的情况，例如 `google-login`，您仍然可以通过配置 `provider` 属性来利用客户端属性的自动默认设置。

以下显示了一个示例:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          google-login:	<1>
            provider: google	<2>
            client-id: google-client-id
            client-secret: google-client-secret
----
<1> `registrationId` 设置为 `google-login`.
<2> `provider` 属性为 `google`, 这会利用在 `CommonOAuth2Provider.GOOGLE.getBuilder()` 中设置客户端属性的默认值.

[[webflux-oauth2-login-custom-provider-properties]]
== 配置自定义 Provider 属性

有一些 OAuth 2.0 提供程序支持多租户，这导致每个租户（或子域）的协议端点不同。

例如，向 Okta 注册的 OAuth 客户端被分配到特定的子域并拥有自己的协议端点。

对于这些情况，Spring Boot 2.x 提供了以下用于配置自定义提供程序属性的基本属性：`spring.security.oauth2.client.provider._[providerId]_`。

以下显示了一个示例:

[source,yaml]
----
spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
        provider:
          okta:	<1>
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
----

<1> (`spring.security.oauth2.client.provider.okta`) 允许自定义配置协议端点位置。.

[[webflux-oauth2-login-override-boot-autoconfig]]
== 重写 Spring Boot 2.x 自动配置

用于 OAuth 客户端支持的自动配置类是 `ReactiveOAuth2ClientAutoConfiguration`.

它执行以下任务：:

* 从配置的  OAuth Client 属性中注册一个由   `ClientRegistration` 组成的 `ReactiveClientRegistrationRepository` `@Bean`。
* 注册一个 `SecurityWebFilterChain` `@Bean` 并通过 `serverHttpSecurity.oauth2Login()` 启用 OAuth 2.0 登录。

如果您需要根据您的具体要求重写自动配置，您可以通过以下方式进行:

* <<webflux-oauth2-login-register-reactiveclientregistrationrepository-bean,注册一个 ReactiveClientRegistrationRepository @Bean>>
* <<webflux-oauth2-login-register-securitywebfilterchain-bean,注册一个 SecurityWebFilterChain @Bean>>
* <<webflux-oauth2-login-completely-override-autoconfiguration,完全重写自动配置>>


[[webflux-oauth2-login-register-reactiveclientregistrationrepository-bean]]
=== 注册一个 ReactiveClientRegistrationRepository @Bean

以下示例显示如何注册一个 `ReactiveClientRegistrationRepository` `@Bean`:

====
.Java
[source,java,role="primary",attrs="-attributes"]
----
@Configuration
public class OAuth2LoginConfig {

	@Bean
	public ReactiveClientRegistrationRepository clientRegistrationRepository() {
		return new InMemoryReactiveClientRegistrationRepository(this.googleClientRegistration());
	}

	private ClientRegistration googleClientRegistration() {
		return ClientRegistration.withRegistrationId("google")
				.clientId("google-client-id")
				.clientSecret("google-client-secret")
				.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
				.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
				.redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
				.scope("openid", "profile", "email", "address", "phone")
				.authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
				.tokenUri("https://www.googleapis.com/oauth2/v4/token")
				.userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
				.userNameAttributeName(IdTokenClaimNames.SUB)
				.jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
				.clientName("Google")
				.build();
	}
}
----

.Kotlin
[source,kotlin,role="secondary",attrs="-attributes"]
----
@Configuration
class OAuth2LoginConfig {

    @Bean
    fun clientRegistrationRepository(): ReactiveClientRegistrationRepository {
        return InMemoryReactiveClientRegistrationRepository(googleClientRegistration())
    }

    private fun googleClientRegistration(): ClientRegistration {
        return ClientRegistration.withRegistrationId("google")
                .clientId("google-client-id")
                .clientSecret("google-client-secret")
                .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
                .scope("openid", "profile", "email", "address", "phone")
                .authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
                .tokenUri("https://www.googleapis.com/oauth2/v4/token")
                .userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
                .userNameAttributeName(IdTokenClaimNames.SUB)
                .jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
                .clientName("Google")
                .build()
    }
}
----
====


[[webflux-oauth2-login-register-securitywebfilterchain-bean]]
=== 注册一个 SecurityWebFilterChain @Bean

以下示例显示如何使用 `@EnableWebFluxSecurity` 注册 `SecurityWebFilterChain` `@Bean` 并通过 `serverHttpSecurity.oauth2Login()` 启用 OAuth 2.0 登录：

.OAuth2 Login Configuration
====
.Java
[source,java,role="primary"]
----
@EnableWebFluxSecurity
public class OAuth2LoginSecurityConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			.authorizeExchange(authorize -> authorize
				.anyExchange().authenticated()
			)
			.oauth2Login(withDefaults());

		return http.build();
	}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@EnableWebFluxSecurity
class OAuth2LoginSecurityConfig {

    @Bean
    fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        return http {
            authorizeExchange {
                authorize(anyExchange, authenticated)
            }
            oauth2Login { }
        }
    }
}
----
====


[[webflux-oauth2-login-completely-override-autoconfiguration]]
=== 完全重写自动配置

以下示例显示了如何通过注册 `ReactiveClientRegistrationRepository` `@Bean` 和 `SecurityWebFilterChain` `@Bean` 来完全重写自动配置。

.Overriding the auto-configuration
====
.Java
[source,java,role="primary",attrs="-attributes"]
----
@EnableWebFluxSecurity
public class OAuth2LoginConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			.authorizeExchange(authorize -> authorize
				.anyExchange().authenticated()
			)
			.oauth2Login(withDefaults());

		return http.build();
	}

	@Bean
	public ReactiveClientRegistrationRepository clientRegistrationRepository() {
		return new InMemoryReactiveClientRegistrationRepository(this.googleClientRegistration());
	}

	private ClientRegistration googleClientRegistration() {
		return ClientRegistration.withRegistrationId("google")
				.clientId("google-client-id")
				.clientSecret("google-client-secret")
				.clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
				.authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
				.redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
				.scope("openid", "profile", "email", "address", "phone")
				.authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
				.tokenUri("https://www.googleapis.com/oauth2/v4/token")
				.userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
				.userNameAttributeName(IdTokenClaimNames.SUB)
				.jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
				.clientName("Google")
				.build();
	}
}
----

.Kotlin
[source,kotlin,role="secondary",attrs="-attributes"]
----
@EnableWebFluxSecurity
class OAuth2LoginConfig {

    @Bean
    fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        return http {
            authorizeExchange {
                authorize(anyExchange, authenticated)
            }
            oauth2Login { }
        }
    }

    @Bean
    fun clientRegistrationRepository(): ReactiveClientRegistrationRepository {
        return InMemoryReactiveClientRegistrationRepository(googleClientRegistration())
    }

    private fun googleClientRegistration(): ClientRegistration {
        return ClientRegistration.withRegistrationId("google")
                .clientId("google-client-id")
                .clientSecret("google-client-secret")
                .clientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC)
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .redirectUri("{baseUrl}/login/oauth2/code/{registrationId}")
                .scope("openid", "profile", "email", "address", "phone")
                .authorizationUri("https://accounts.google.com/o/oauth2/v2/auth")
                .tokenUri("https://www.googleapis.com/oauth2/v4/token")
                .userInfoUri("https://www.googleapis.com/oauth2/v3/userinfo")
                .userNameAttributeName(IdTokenClaimNames.SUB)
                .jwkSetUri("https://www.googleapis.com/oauth2/v3/certs")
                .clientName("Google")
                .build()
    }
}
----
====

[[webflux-oauth2-login-javaconfig-wo-boot]]
== Java Configuration without Spring Boot 2.x

如果您无法使用 Spring Boot 2.x 并且想在 `CommonOAuth2Provider` 中配置预定义的提供程序之一（例如，Google），请应用以下配置：

.OAuth2 Login Configuration
====
.Java
[source,java,role="primary"]
----
@EnableWebFluxSecurity
public class OAuth2LoginConfig {

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http
			.authorizeExchange(authorize -> authorize
				.anyExchange().authenticated()
			)
			.oauth2Login(withDefaults());

		return http.build();
	}

	@Bean
	public ReactiveClientRegistrationRepository clientRegistrationRepository() {
		return new InMemoryReactiveClientRegistrationRepository(this.googleClientRegistration());
	}

	@Bean
	public ReactiveOAuth2AuthorizedClientService authorizedClientService(
			ReactiveClientRegistrationRepository clientRegistrationRepository) {
		return new InMemoryReactiveOAuth2AuthorizedClientService(clientRegistrationRepository);
	}

	@Bean
	public ServerOAuth2AuthorizedClientRepository authorizedClientRepository(
			ReactiveOAuth2AuthorizedClientService authorizedClientService) {
		return new AuthenticatedPrincipalServerOAuth2AuthorizedClientRepository(authorizedClientService);
	}

	private ClientRegistration googleClientRegistration() {
		return CommonOAuth2Provider.GOOGLE.getBuilder("google")
				.clientId("google-client-id")
				.clientSecret("google-client-secret")
				.build();
	}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@EnableWebFluxSecurity
class OAuth2LoginConfig {

    @Bean
    fun securityWebFilterChain(http: ServerHttpSecurity): SecurityWebFilterChain {
        return http {
            authorizeExchange {
                authorize(anyExchange, authenticated)
            }
            oauth2Login { }
        }
    }

    @Bean
    fun clientRegistrationRepository(): ReactiveClientRegistrationRepository {
        return InMemoryReactiveClientRegistrationRepository(googleClientRegistration())
    }

    @Bean
    fun authorizedClientService(
        clientRegistrationRepository: ReactiveClientRegistrationRepository
    ): ReactiveOAuth2AuthorizedClientService {
        return InMemoryReactiveOAuth2AuthorizedClientService(clientRegistrationRepository)
    }

    @Bean
    fun authorizedClientRepository(
        authorizedClientService: ReactiveOAuth2AuthorizedClientService
    ): ServerOAuth2AuthorizedClientRepository {
        return AuthenticatedPrincipalServerOAuth2AuthorizedClientRepository(authorizedClientService)
    }

    private fun googleClientRegistration(): ClientRegistration {
        return CommonOAuth2Provider.GOOGLE.getBuilder("google")
                .clientId("google-client-id")
                .clientSecret("google-client-secret")
                .build()
    }
}
----
====

