[[auditing]]
= 审计

[[auditing.basics]]
== 基础
Spring Data提供了完善的支持，可以透明地跟踪创建或更改实体的人员以及更改发生的时间。 要利用该功能，您必须为实体类配备审核元数据，该审核元数据可以使用批注或通过实现接口来定义。

[[auditing.annotations]]
=== 基于注释的审核元数据

我们提供 `@CreatedBy` 和 `@LastModifiedBy` 来捕获创建或修改实体的用户，并提供 `@CreatedDate` 和 `@LastModifiedDate` 来捕获更改发生的时间。

.被审计实体
====
[source, java]
----
class Customer {

  @CreatedBy
  private User user;

  @CreatedDate
  private DateTime createdDate;

  // … further properties omitted
}
----
====

如您所见，可以根据要捕获的信息有选择地应用注释。 捕获更改时捕获的注释可用于类型 `Joda-Time`，`DateTime`，旧版Java `Date` 和 `Calendar`，JDK8日期和时间类型以及 `long` 或 `Long` 的属性。

[[auditing.interfaces]]
=== 基于接口的审核元数据
如果您不想使用注释来定义审核元数据，则可以让您的域类实现 `Auditable` 接口。 它为所有审核属性公开了setter方法。

还有一个便捷的基类 `AbstractAuditable`，可以对其进行扩展，以避免需要手动实现接口方法。 这样做会增加您的域类与Spring Data的耦合，这可能是您要避免的事情。 通常，首选基于注释的方式来定义审核元数据，因为它侵入性较小且更灵活。

[[auditing.auditor-aware]]
=== `AuditorAware`

如果使用 `@CreatedBy` 或 `@LastModifiedBy`，则审计基础结构需要以某种方式了解当前的主体。 为此，我们提供了 `AuditorAware<T>` SPI接口，您必须实现该接口以告知基础结构与应用程序交互的当前用户或系统是谁。
通用类型T定义必须使用 `@CreatedBy` 或 `@LastModifiedBy` 注释的属性的类型。

以下示例显示了使用Spring Security的 `Authentication` 对象的接口的实现：

.基于Spring Security的AuditorAware的实现
====
[source, java]
----
class SpringSecurityAuditorAware implements AuditorAware<User> {

  public Optional<User> getCurrentAuditor() {

    return Optional.ofNullable(SecurityContextHolder.getContext())
			  .map(SecurityContext::getAuthentication)
			  .filter(Authentication::isAuthenticated)
			  .map(Authentication::getPrincipal)
			  .map(User.class::cast);
  }
}
----
====

该实现访问Spring Security提供的 `Authentication` 对象，并查找您在 `UserDetailsService` 实现中创建的自定义 `UserDetails` 实例。 我们在这里假设您通过 `UserDetails` 实现公开域用户，但是根据找到的身份验证，您还可以从任何地方查找它。