[appendix]
[[migration-guide]]
= Migration Guide

下面几节解释如何迁移到更新版本的 Spring Data R2DBC。

[[upgrading.1.1-1.2]]
== 从 1.1.x 升级到 1.2.x

Spring Data R2DBC 的开发目的是评估 R2DBC 与 Spring 应用程序的集成情况。主要的方面之一是，一旦 R2DBC 支持被证明是有用的，就将核心支持转移到 Spring Framework 中。Spring Framework 5.3 附带了一个新模块:Spring R2DBC (`spring-r2dbc`)。

`spring-r2dbc` 提供了核心的 R2DBC 功能(`DatabaseClient` 的一个小变体，事务管理器，连接工厂初始化，异常转换)，这些功能最初是由 Spring Data R2DBC 提供的。1.2.0 版本与 Spring R2DBC 提供的内容保持一致，在下面几节中进行了一些修改。

Spring R2DBC 的 `DatabaseClient` 是一种更轻量级的实现，它封装了一个纯面向 sql 的接口。您会注意到运行 SQL 语句的方法从 `DatabaseClient.execute(…)` 更改为  `DatabaseClient.sql(…)`。用于 CRUD 操作的 fluent API 已经转移到 `R2dbcEntityTemplate` 中。

[[upgrading.1.1-1.2.deprecation]]
=== 弃用

* 弃用 `o.s.d.r2dbc.core.DatabaseClient` 及其支持类 `ConnectionAccessor`, `FetchSpec`, `SqlProvider` 等等。命名参数支持类(如 `NamedParameterExpander`)是由 Spring R2DBC 的 `DatabaseClient` 实现封装的，因此我们不提供替换，因为这首先是内部 API。使用 `org.springframework.r2dbc.core` 提供的 `o.s.r2dbc.core.DatabaseClient` 和它们的 Spring R2DBC 替代品。。基于实体的方法((`select`/`insert`/`update`/`delete`)可以通过 1.1 版本引入的 `R2dbcEntityTemplate` 获得。
* 弃用 `o.s.d.r2dbc.connectionfactory`, `o.s.d.r2dbc.connectionfactory.init`, 和 `o.s.d.r2dbc.connectionfactory.lookup` 包。使用 Spring R2DBC 的变体，您可以在 `o.s.r2dbc.connection` 找到它。
* 弃用 `o.s.d.r2dbc.convert.ColumnMapRowMapper`.
使用 `o.s.r2dbc.core.ColumnMapRowMapper` 代替.
* 弃用绑定支持类 `o.s.d.r2dbc.dialect.Bindings`, `BindMarker`, `BindMarkers`, `BindMarkersFactory` 和相关类型.
使用 `org.springframework.r2dbc.core.binding` 包中的替换.
* 弃用 `o.s.d.r2dbc.support` 包中的 `BadSqlGrammarException`, `UncategorizedR2dbcException` 和 异常转换 .
Spring R2DBC 提供了一个没有 SPI 的简介的异常转换，现在可以通过 `o.s.r2dbc.connection.ConnectionFactoryUtils#convertR2dbcException` 获得。

[[upgrading.1.1-1.2.replacements]]
=== 使用 Spring R2DBC 提供的替换

为了简化迁移，一些已弃用的类型现在是 Spring R2DBC 提供的替代类型的子类型。Spring Data R2DBC 改变了几个方法，或者引入了接受 Spring R2DBC 类型的新方法。具体来说，以下类进行了更改:

* `R2dbcEntityTemplate`
* `R2dbcDialect`
* `org.springframework.data.r2dbc.query` 中的类型

如果您直接使用这些类型，我们建议您检查并更新导入。

=== 重大变化

* `OutboundRow` 和语句映射器从使用 `SettableValue` 切换到 `Parameter`。
* 存储库工厂支持需要 `o.s.r2dbc.core.DatabaseClient` 而不是 `o.s.data.r2dbc.core.DatabaseClient`。

[[upgrading.1.1-1.2.dependencies]]
=== 依赖变更

要使用 Spring R2DBC，请确保包含以下依赖项：

* `org.springframework:spring-r2dbc`
