R2DBC 包含广泛的特性:

* Spring 的配置支持使用基于 Java 的  `@Configuration` 类对 R2DBC driver 实例的配置.
* `R2dbcEntityTemplate` 为绑定实体操作的核心类，在执行具有 rows 和 POJOs 之间的集成对象映射常见的 R2DBC 操作时，它可以提高生产效率。
* Spring Conversion Service 集成功能丰富的对象映射.
* 可扩展的基于注解的元数据映射，以支持其他元数据格式。
* 自动实现 Repository 接口，包括支持自定义查询方法。

对于大多数任务，您应该使用 `R2dbcEntityTemplate` 或存储库支持，它们都使用丰富的映射功能。 `R2dbcEntityTemplate` 是寻找访问功能（例如特别的 CRUD 操作）的地方。

[[r2dbc.getting-started]]
== 入门

设置 working environment 的一个简单方法是通过 https://start.spring.io[start.spring.io] 创建一个基于 Spring 的项目。

如果这样做:

. 将以下  `dependencies` 元素添加到 pom.xml 文件:
+
====
[source,xml,subs="+attributes"]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.r2dbc</groupId>
      <artifactId>r2dbc-bom</artifactId>
      <version>${r2dbc-releasetrain.version}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

<dependencies>

  <!-- other dependency elements omitted -->

  <dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-r2dbc</artifactId>
    <version>{spring-data-r2dbc-version}</version>
  </dependency>

  <!-- a R2DBC driver -->
  <dependency>
    <groupId>io.r2dbc</groupId>
    <artifactId>r2dbc-h2</artifactId>
    <version>{r2dbcVersion}</version>
  </dependency>

</dependencies>
----
====

. 将 pom.xml 中 Spring 的版本改为
+
====
[source,xml,subs="+attributes"]
----
<spring-framework.version>{spring-framework-version}</spring-framework.version>
----
====

. 将 Spring Milestone 存储库的位置添加到您的 `pom.xml` 文件中，它与 `<dependencies>` 元素处于同一层级:
+
====
[source,xml]
----
<repositories>
  <repository>
    <id>spring-milestone</id>
    <name>Spring Maven MILESTONE Repository</name>
    <url>https://repo.spring.io/libs-milestone</url>
  </repository>
</repositories>
----
====

repository 也可以在这里 https://repo.spring.io/milestone/org/springframework/data/[浏览]。

您可能还想将日志记录级别设置为 `DEBUG` 以查看一些附加信息。为此，请编辑 `application.properties` 文件并包含以下内容:

====
[source]
----
logging.level.org.springframework.r2dbc=DEBUG
----
====

然后你可以，例如，创建一个持久化的 `Person` 类，如下所示:

====
[source,java,indent=0]
----
include::{example-root}/Person.java[tags=class]
----
====

接下来，您需要在您的数据库中创建一个表结构，如下所示：

====
[source,sql]
----
CREATE TABLE person
  (id VARCHAR(255) PRIMARY KEY,
   name VARCHAR(255),
   age INT);
----
====

您还需要一个主应用程序来运行，如下所示:


====
[source,java,indent=0]
----
include::{example-root}/R2dbcApp.java[tags=class]
----
====

运行主程序时，前面的示例会生成类似于以下内容的输出:

====
[source]
----
2018-11-28 10:47:03,893 DEBUG amework.core.r2dbc.DefaultDatabaseClient: 310 - Executing SQL statement [CREATE TABLE person
  (id VARCHAR(255) PRIMARY KEY,
   name VARCHAR(255),
   age INT)]
2018-11-28 10:47:04,074 DEBUG amework.core.r2dbc.DefaultDatabaseClient: 908 - Executing SQL statement [INSERT INTO person (id, name, age) VALUES($1, $2, $3)]
2018-11-28 10:47:04,092 DEBUG amework.core.r2dbc.DefaultDatabaseClient: 575 - Executing SQL statement [SELECT id, name, age FROM person]
2018-11-28 10:47:04,436  INFO        org.spring.r2dbc.example.R2dbcApp:  43 - Person [id='joe', name='Joe', age=34]
----
====

即使在这个简单的例子中，也有几件事需要注意:

* 您可以使用标准的 `io.r2dbc.spi.ConnectionFactory` 对象在 Spring Data R2DBC (`R2dbcEntityTemplate`) 中创建 central helper 类的实例。
* 针对标准 POJO 对象映射，无需任何额外的元数据（尽管您可以选择提供该信息 — 请参阅<<mapping,此处>>）。
* 映射可以使用的字段访问。注意 Person 类只有 getter。
* 如果构造函数参数名称与存储行的列名称匹配，则使用它们实例化对象。

[[r2dbc.examples-repo]]
== Examples Repository

有一个 GitHub 存储库，https://github.com/spring-projects/spring-data-examples[其中有几个示例]，您可以下载并尝试一下，以了解这个库是如何工作的。

[[r2dbc.connecting]]
== 使用 Spring 连接到关系数据库

使用 Spring 和关系数据库时的第一件事是创建 `io.r2dbc.spi.ConnectionFactory`。通过使用 IoC 容器来创建 `ConnectionFactory` 对象。确保使用的是<<r2dbc.drivers,支持的数据库和驱动程序>>。

[[r2dbc.connectionfactory]]
=== 使用基于 Java 元数据注册 `ConnectionFactory` 实例

以下示例使用了基于 Java 的 bean 元数据注册 `io.r2dbc.spi.ConnectionFactory` 实例的示例：

.Registering a `io.r2dbc.spi.ConnectionFactory` object using Java-based bean metadata
====
[source,java]
----
@Configuration
public class ApplicationConfiguration extends AbstractR2dbcConfiguration {

  @Override
  @Bean
  public ConnectionFactory connectionFactory() {
    return …
  }
}
----
====

这种方法允许使用标准的 `io.r2dbc.spi.ConnectionFactory 实例`，容器使用 Spring 的 `AbstractR2dbcConfiguration`。与直接注册 `ConnectionFactory` 实例相比，配置支持还有一个额外的优势，即还为容器提供了一个 `ExceptionTranslator` 实现，该实现将 R2DBC 异常转换为 Spring 的 `DataAccessException` 层次结构中的异常，用于使用 `@Repository` 注解注解的数据访问类。{spring-framework-ref}/data-access.html[Spring 的 DAO 支持功能]中描述了此层次结构和 `@Repository` 的使用。

`AbstractR2dbcConfiguration` 还注册了 `DatabaseClient`，这是数据库交互和 Repository 实现所必需的。

[[r2dbc.drivers]]
=== R2DBC Drivers

Spring Data R2DBC 通过 R2DBC 的可插拔 SPI 机制支持驱动程序。 您可以使用任何通过 Spring Data R2DBC 实现 R2DBC 规范的驱动程序。 由于 Spring Data R2DBC 会对每个数据库的特定功能做出响应，所以它需要一个Dialect实现，否则应用程序将无法启动。 Spring Data R2DBC 附带了以下驱动程序的 dialect 实现:

* https://github.com/r2dbc/r2dbc-h2[H2] (`io.r2dbc:r2dbc-h2`)
* https://github.com/mariadb-corporation/mariadb-connector-r2dbc[MariaDB] (`org.mariadb:r2dbc-mariadb`)
* https://github.com/r2dbc/r2dbc-mssql[Microsoft SQL Server] (`io.r2dbc:r2dbc-mssql`)
* https://github.com/mirromutth/r2dbc-mysql[MySQL] (`dev.miku:r2dbc-mysql`)
* https://github.com/jasync-sql/jasync-sql[jasync-sql MySQL] (`com.github.jasync-sql:jasync-r2dbc-mysql`)
* https://github.com/r2dbc/r2dbc-postgresql[Postgres] (`io.r2dbc:r2dbc-postgresql`)
* https://github.com/oracle/oracle-r2dbc[Oracle] (`com.oracle.database.r2dbc:oracle-r2dbc`)

Spring Data R2DBC 通过检查 `ConnectionFactory` 对数据库细节做出反应，并相应地选择适当的数据库。 如果 Spring Data R2DBC 还不知道您使用的驱动程序，则需要配置您自己的 {spring-data-r2dbc-javadoc}/api/org/springframework/data/r2dbc/dialect/R2dbcDialect.html[`R2dbcDialect`]。

TIP: Dialects 由 `ConnectionFactory` 中的 {spring-data-r2dbc-javadoc}/org/springframework/data/r2dbc/dialect/DialectResolver.html[`DialectResolver`] 解析，通常通过检查 `ConnectionFactoryMetadata`。 + 您可以通过 `META-INF/spring.factories` 注册一个实现 `org.springframework.data.r2dbc.dialect.DialectResolver$R2dbcDialectProvider` 的类，让 Spring 自动发现您的 `R2dbcDialect`。 `DialectResolver` 使用 Spring 的 `SpringFactoriesLoader` 从类路径中发现 dialect 提供程序实现。
