[[mvc]]
== Spring MVC 整合

Spring Security提供了许多与Spring MVC的可选集成. 本节将详细介绍集成.

[[mvc-enablewebmvcsecurity]]
=== @EnableWebMvcSecurity

NOTE: 从Spring Security 4.0开始, `@EnableWebMvcSecurity` 已经标记为 过时注解. 替换为 `@EnableWebSecurity`,它将根据类路径确定添加Spring MVC功能.

要启用与Spring MVC的Spring Security集成,请在配置中添加 `@EnableWebSecurity` 注解.

NOTE: Spring Security使用Spring MVC的 https://docs.spring.io/spring/docs/5.0.0.RELEASE/spring-framework-reference/web.html#mvc-config-customize[WebMvcConfigurer]提供配置.  这意味着,如果您使用的是更高级的选项,例如直接与 `WebMvcConfigurationSupport` 集成,那么您将需要手动提供Spring Security配置.

[[mvc-requestmatcher]]
=== MvcRequestMatcher

Spring Security提供了与Spring MVC如何使用 `MvcRequestMatcher` 在URL上进行匹配的深度集成.  这有助于确保您的安全规则与用于处理请求的逻辑相匹配.

为了使用MvcRequestMatcher,必须将Spring Security Configuration与DispatcherServlet放在同一 `ApplicationContext` 中.  这是必需的,因为Spring Security的 `MvcRequestMatcher` 希望您的Spring MVC配置会注册一个名称为 `mvcHandlerMappingIntrospector` 的 `HandlerMappingIntrospector` Bean,用于执行匹配.

对于 `web.xml`,这意味着您应该将配置放在 `DispatcherServlet.xml` 中.

[source,xml]
----
<listener>
  <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
</listener>

<!-- All Spring Configuration (both MVC and Security) are in /WEB-INF/spring/ -->
<context-param>
  <param-name>contextConfigLocation</param-name>
  <param-value>/WEB-INF/spring/*.xml</param-value>
</context-param>

<servlet>
  <servlet-name>spring</servlet-name>
  <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
  <!-- Load from the ContextLoaderListener -->
  <init-param>
    <param-name>contextConfigLocation</param-name>
    <param-value></param-value>
  </init-param>
</servlet>

<servlet-mapping>
  <servlet-name>spring</servlet-name>
  <url-pattern>/</url-pattern>
</servlet-mapping>
----

在 `WebSecurityConfiguration` 下面的 `DispatcherServlets` 中放置 `ApplicationContext`.

[source,java]
----
public class SecurityInitializer extends
    AbstractAnnotationConfigDispatcherServletInitializer {

  @Override
  protected Class<?>[] getRootConfigClasses() {
    return null;
  }

  @Override
  protected Class<?>[] getServletConfigClasses() {
    return new Class[] { RootConfiguration.class,
        WebMvcConfiguration.class };
  }

  @Override
  protected String[] getServletMappings() {
    return new String[] { "/" };
  }
}
----

[NOTE]
====
始终建议通过匹配 `HttpServletRequest` 和方法安全性来提供授权规则.

通过在 `HttpServletRequest` 上进行匹配来提供授权规则是一件好事,因为它发生在代码路径的早期,并且有助于减少 https://en.wikipedia.org/wiki/Attack_surface[攻击面].
方法安全性可确保如果有人绕过了Web授权规则,则您的应用程序仍然受到保护.  这就是所谓的 https://en.wikipedia.org/wiki/Defense_in_depth_(computing)[深度防御]

====

考虑一个映射如下的控制器:

[source,java]
----
@RequestMapping("/admin")
public String admin() {
----

如果我们想将对这种控制器方法的访问限制为管理员用户,则开发人员可以通过在 `HttpServletRequest` 上匹配以下内容来提供授权规则:

[source,java]
----
protected configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests(authorize -> authorize
			.antMatchers("/admin").hasRole("ADMIN")
		);
}
----

或使用xml

[source,xml]
----
<http>
	<intercept-url pattern="/admin" access="hasRole('ADMIN')"/>
</http>
----

无论采用哪种配置,URL  `/admin`  都将要求经过身份验证的用户为admin用户.  但是,根据我们的Spring MVC配置,URL `/admin.html` 也将映射到我们的 `admin()` 方法.  另外,根据我们的Spring MVC配置,URL `/admin/` 也将映射到我们的 `admin()` 方法.

问题在于我们的安全规则仅保护 `/admin` .  我们可以为Spring MVC的所有排列添加其他规则,但这将非常冗长而乏味.

相反,我们可以利用Spring Security的 `MvcRequestMatcher`.  以下配置通过使用Spring MVC在URL上进行匹配来保护与Spring MVC匹配的URL.

[source,java]
----
protected configure(HttpSecurity http) throws Exception {
	http
		.authorizeRequests(authorize -> authorize
			.mvcMatchers("/admin").hasRole("ADMIN")
		);
}
----

或使用xml

[source,xml]
----
<http request-matcher="mvc">
	<intercept-url pattern="/admin" access="hasRole('ADMIN')"/>
</http>
----

[[mvc-authentication-principal]]
=== @AuthenticationPrincipal

Spring Security提供了 `AuthenticationPrincipalArgumentResolver`,它可以为Spring MVC参数自动解析当前的 `Authentication.getPrincipal()` .  通过使用 `@EnableWebSecurity`,您将自动将其添加到Spring MVC配置中.  如果使用基于XML的配置,则必须自己添加.  例如:

[source,xml]
----
<mvc:annotation-driven>
		<mvc:argument-resolvers>
				<bean class="org.springframework.security.web.method.annotation.AuthenticationPrincipalArgumentResolver" />
		</mvc:argument-resolvers>
</mvc:annotation-driven>
----

正确配置 `AuthenticationPrincipalArgumentResolver` 之后,您就可以在Spring MVC层中与Spring Security完全脱钩.

考虑一种情况,其中自定义 `UserDetailsService` 返回一个实现 `UserDetails` 的对象和您自己的 `CustomUser` 对象.  可以使用以下代码访问当前已认证用户的 `CustomUser`:

[source,java]
----
@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser() {
	Authentication authentication =
	SecurityContextHolder.getContext().getAuthentication();
	CustomUser custom = (CustomUser) authentication == null ? null : authentication.getPrincipal();

	// .. find messages for this user and return them ...
}
----

从Spring Security 3.2开始,我们可以通过添加注解来更直接地解析参数. 例如:

[source,java]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal;

// ...

@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser(@AuthenticationPrincipal CustomUser customUser) {

	// .. find messages for this user and return them ...
}
----

有时可能需要以某种方式转换主体.  例如,如果 `CustomUser` 需要为 `final`,则无法扩展.  在这种情况下,`UserDetailsService` 可能返回一个实现 `UserDetails` 的对象,并提供一个名为 `getCustomUser` 的方法来访问 `CustomUser`.  例如,它可能看起来像:

[source,java]
----
public class CustomUserUserDetails extends User {
		// ...
		public CustomUser getCustomUser() {
				return customUser;
		}
}
----

然后,我们可以使用 https://docs.spring.io/spring/docs/current/spring-framework-reference/html/expressions.html[SpEL表达式] 访问 `CustomUser`,该表达式使用 `Authentication.getPrincipal()` 作为根对象:

[source,java]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal;

// ...

@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser(@AuthenticationPrincipal(expression = "customUser") CustomUser customUser) {

	// .. find messags for this user and return them ...
}
----

我们还可以在SpEL表达式中引用Bean. 例如,如果我们使用JPA来管理用户,并且想要修改并保存当前用户的属性,则可以使用以下内容.

[source,java]
----
import org.springframework.security.core.annotation.AuthenticationPrincipal;

// ...

@PutMapping("/users/self")
public ModelAndView updateName(@AuthenticationPrincipal(expression = "@jpaEntityManager.merge(#this)") CustomUser attachedCustomUser,
		@RequestParam String firstName) {

	// change the firstName on an attached instance which will be persisted to the database
	attachedCustomUser.setFirstName(firstName);

	// ...
}
----

通过使 `@AuthenticationPrincipal` 成为我们自己的注解的元注解,我们可以进一步消除对Spring Security的依赖. 下面我们演示如何在名为 `@CurrentUser` 的注解上执行此操作.

NOTE: 重要的是要意识到,为了消除对Spring Security的依赖,创建 `@CurrentUser` 的是消耗者的应用程序.  并非严格要求执行此步骤,但可以帮助您将对Spring Security的依赖隔离到更中央的位置.

[source,java]
----
@Target({ElementType.PARAMETER, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@AuthenticationPrincipal
public @interface CurrentUser {}
----

现在已经指定了 `@CurrentUser`,我们可以用它来通知解析当前已认证用户的 `CustomUser`. 我们还将对Spring Security的依赖关系隔离到一个文件中.

[source,java]
----
@RequestMapping("/messages/inbox")
public ModelAndView findMessagesForUser(@CurrentUser CustomUser customUser) {

	// .. find messages for this user and return them ...
}
----


[[mvc-async]]
=== Spring MVC 异步整合

Spring Web MVC 3.2+对 https://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/mvc.html#mvc-ann-async[异步请求处理]提供了出色的支持.  无需其他配置,Spring Security就会自动将 `SecurityContext` 设置为执行由您的控制器返回的 `Callable` 的线程.
例如,以下方法将自动使用创建 `Callable` 时可用的 `SecurityContext` 执行其 `Callable`:

[source,java]
----
@RequestMapping(method=RequestMethod.POST)
public Callable<String> processUpload(final MultipartFile file) {

return new Callable<String>() {
	public Object call() throws Exception {
	// ...
	return "someView";
	}
};
}
----

[NOTE]
.A将SecurityContext与Callable的关联
====
从技术上讲,Spring Security与 `WebAsyncManager` 集成. 用于处理 `Callable` 的 `SecurityContext` 是在调用 `startCallableProcessing` 时 `SecurityContextHolder` 上存在的 `SecurityContext`.
====

没有与控制器返回的 `DeferredResult` 自动集成.  这是因为 `DeferredResult` 由用户处理,因此无法自动与其集成.  但是,您仍然可以使用<<concurrency,并发支持>> 来提供与Spring Security的透明集成.

[[mvc-csrf]]
=== Spring MVC 和 CSRF 整合

==== 自动包含令牌

Spring Security将在使用 https://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/view.html#view-jsp-formtaglib-formtag[Spring MVC form tag]中自动<<servlet-csrf-include,包含CSRF令牌>>. 例如,以下JSP:

[source,xml]
----
<jsp:root xmlns:jsp="http://java.sun.com/JSP/Page"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:form="http://www.springframework.org/tags/form" version="2.0">
	<jsp:directive.page language="java" contentType="text/html" />
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
	<!-- ... -->

	<c:url var="logoutUrl" value="/logout"/>
	<form:form action="${logoutUrl}"
		method="post">
	<input type="submit"
		value="Log out" />
	<input type="hidden"
		name="${_csrf.parameterName}"
		value="${_csrf.token}"/>
	</form:form>

	<!-- ... -->
</html>
</jsp:root>
----

将输出类似于以下内容的HTML:

[source,xml]
----
<!-- ... -->

<form action="/context/logout" method="post">
<input type="submit" value="Log out"/>
<input type="hidden" name="_csrf" value="f81d4fae-7dec-11d0-a765-00a0c91e6bf6"/>
</form>

<!-- ... -->
----

[[mvc-csrf-resolver]]
====  CsrfToken 解析

Spring Security提供了 `CsrfTokenArgumentResolver`,它可以自动为Spring MVC参数解析当前的 `CsrfToken`.  通过使用 <<jc-hello-wsca,@EnableWebSecurity>> ,您将自动将其添加到Spring MVC配置中.  如果使用基于XML的配置,则必须自己添加.

正确配置 `CsrfTokenArgumentResolver` 后,即可将 `CsrfToken` 暴露给基于静态HTML的应用程序.

[source,java]
----
@RestController
public class CsrfController {

	@RequestMapping("/csrf")
	public CsrfToken csrf(CsrfToken token) {
		return token;
	}
}
----

保持 `CsrfToken` 对其他域的秘密非常重要. 这意味着,如果您使用 https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS[跨源共享(CORS) ],则不应将 `CsrfToken` 暴露给任何外部域.