[[data.sql]]
== 使用 SQL 数据库
{spring-framework}[Spring Framework]  为 SQL 数据库提供了广泛的支持. 从直接使用 `JdbcTemplate` 进行 JDBC 访问到完全的对象关系映射 (object relational mapping) 技术,比如 Hibernate. {spring-data}[Spring Data] 提供了更多级别的功能,直接从接口创建的 `Repository` 实现,并使用了约定从方法名生成查询.

[[data.sql.datasource]]
=== 配置数据源
Java 的 `javax.sql.DataSource` 接口提供了一个使用数据库连接的标准方法. 通常,数据源使用 `URL` 和一些凭据信息来建立数据库连接.

TIP: 查看 <<howto#howto.data-access.configure-custom-datasource,"`How-to`" 部分>> 获取更多高级示例,通常您可以完全控制数据库的配置.

[[data.sql.datasource.embedded]]
==== 嵌入式数据库支持
使用内嵌内存数据库来开发应用程序非常方便的. 显然,内存数据库不提供持久存储. 在应用启动时,您需要填充数据库,并在应用程序结束时丢弃数据.

TIP: How-to 部分包含了 <<howto#howto.data-initialization, 如何初始化数据库>>方面的内容.

Spring Boot 可以自动配置内嵌 https://www.h2database.com[H2], https://hsqldb.org/[HSQL], 和 https://db.apache.org/derby/[Derby]  数据库. 您不需要提供任何连接 URL,只需为您想要使用的内嵌数据库引入特定的构建依赖.如果类路径上有多个嵌入式数据库，请设置 `spring.datasource.embedded-database-connection` 配置属性来控制使用哪一个。 将该属性设置为 `none` 会禁用嵌入式数据库的自动配置。

[NOTE]
====
如果您在测试中使用此功能,您可能会注意到,无论使用了多少应用程序上下文,整个测试套件都会重复使用相同的数据库. 如果您想确保每个上下文都有一个单独的内嵌数据库,则应该将 `spring.datasource.generate-unique-name` 设置为 `true`.
====

以下是 POM 依赖示例:

[source,xml,indent=0,subs="verbatim"]
----
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-data-jpa</artifactId>
	</dependency>
	<dependency>
		<groupId>org.hsqldb</groupId>
		<artifactId>hsqldb</artifactId>
		<scope>runtime</scope>
	</dependency>
----

NOTE: 要自动配置内嵌数据库,您需要一个 `spring-jdbc` 依赖. 在这个例子中,它是通过 `spring-boot-starter-data-jpa` 引入.

TIP: 如果出于某些原因,您需要配置内嵌数据库的连接 URL,则应注意确保禁用数据库的自动关闭功能.
如果您使用 H2,则应该使用 `DB_CLOSE_ON_EXIT=FALSE` 来设置. 如果您使用 HSQLDB,则确保不使用 `shutdown=true`. 禁用数据库的自动关闭功能允许 Spring Boot 控制数据库何时关闭,从而确保一旦不再需要访问数据库时就触发.

[[data.sql.datasource.production]]
==== 连接生产数据库
生产数据库连接也可以使用使用 `DataSource` 自动配置. Spring Boot 使用以下算法来选择一个特定的实现:

[[data.sql.datasource.configuration]]
==== DataSource 配置
DataSource 配置由 `+spring.datasource.*+`. 中的外部配置属性控制。例如，你可以在 `application.yaml` 中声明以下部分:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  datasource:
	    url: "jdbc:mysql://localhost/test"
	    username: "dbuser"
	    password: "dbpass"
----

NOTE: 您至少应该使用 `spring.datasource.url` 属性来指定 URL,否则 Spring Boot 将尝试自动配置内嵌数据库.

TIP: Spring Boot 可以从 URL 推导出大多数数据库的 JDBC 驱动程序类。如果需要指定特定的类，可以使用 `spring.datasource.driver-class-name`  属性。

NOTE: 对于要创建的池 `DataSource`,我们需要能够验证有效的 Driver 类是否可用,因此我们在使用之前进行检查. 例如,如果您设置了 `spring.datasource.driver-class-name=com.mysql.jdbc.Driver`,那么该类必须可加载.

有关更多支持选项,请参阅  {spring-boot-autoconfigure-module-code}/jdbc/DataSourceProperties.java[`DataSourceProperties`] .
这些都是标准选项,与 <<features#data.sql.datasource.connection-pool, 实际的实现>> 无关. 还可以使用各自的前缀 (`spring.datasource.hikari.*`、`spring.datasource.tomcat.*` ， `spring.datasource.dbcp2.*` 和 `+spring.datasource.oracleucp.*+` ) 微调实现特定的设置. 请参考您现在使用的连接池实现的文档来获取更多信息.

例如,如果你使用  {tomcat-docs}/jdbc-pool.html#Common_Attributes[Tomcat connection pool],则可以自定义许多其他设置,如下:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  datasource:
	    tomcat:
	      max-wait: 10000
	      max-active: 50
	      test-on-borrow: true
----

如果没有可用连接，则会将连接池设置为等待 `10000ms` 的释放，然后丢弃异常，请将最大连接数限制为 `50`，并在从池中使用它之前验证连接。

[[data.sql.datasource.connection-pool]]
==== 连接池支持
Spring Boot 使用以下算法来选择连接池的实现:

. 出于性能和并发性的考虑,我们更喜欢 https://github.com/brettwooldridge/HikariCP[HikariCP]  连接池. 如果 HikariCP 可用,我们总是选择它.
. 否则,如果 Tomcat 池 DataSource 可用,我们将使用它.
. 如果 HikariCP 和 Tomcat 连接池数据源不可用,但 https://commons.apache.org/proper/commons-dbcp/[Commons DBCP2]  可用,我们将使用它.
. 如果没有 HikariCP，Tomcat 和 DBCP2，并且如果有 Oracle UCP，我们将使用它。

NOTE: 如果使用 `spring-boot-starter-jdbc` 或 `spring-boot-starter-data-jpa` "`starters`", 您将自动获得对 `HikariCP` 的依赖

您完全可以绕过该算法,并通过 `spring.datasource.type` 属性指定要使用的连接池. 如果您在 Tomcat 容器中运行应用程序,默认提供 `tomcat-jdbc`,这点尤其重要.

可以使用 `DataSourceBuilder` 手动配置其他连接池. 如果您定义了自己的 `DataSource` bean,则自动配置将不会触发.`DataSourceBuilder` 支持以下连接池:

* HikariCP
* Tomcat pooling `Datasource`
* Commons DBCP2
* Oracle UCP & `OracleDataSource`
* Spring Framework's `SimpleDriverDataSource`
* H2 `JdbcDataSource`
* PostgreSQL `PGSimpleDataSource`
* C3P0

[[data.sql.datasource.jndi]]
==== 连接 JNDI 数据源
如果要将 Spring Boot 应用程序部署到应用服务器 (Application Server) 上,您可能想使用应用服务器的内置功能和 JNDI 访问方式来配置和管理数据源.

`spring.datasource.jndi-name` 属性可作为 `spring.datasource.url`、`spring.datasource.username` 和 `spring.datasource.password` 属性的替代方法,用于从特定的 JNDI 位置访问 `DataSource`. 例如,`application.properties` 中的以下部分展示了如何访问 JBoss AS 定义的 `DataSource`:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  datasource:
	    jndi-name: "java:jboss/datasources/customers"
----

[[data.sql.jdbc-template]]
=== 使用 JdbcTemplate
Spring 的 `JdbcTemplate` 和 `NamedParameterJdbcTemplate` 类是自动配置的,您可以使用 `@Autowire` 将它们直接注入您的 bean 中:

include::code:MyBean[]

您可以使用 `spring.jdbc.template.*` 属性来自定义一些 template 的属性,如下:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  jdbc:
	    template:
	      max-rows: 500
----

NOTE: `NamedParameterJdbcTemplate` 在底层重用了相同的 `JdbcTemplate` 实例. 如果定义了多个 `JdbcTemplate` 且没有声明 primary 主候选,则不会自动配置 `NamedParameterJdbcTemplate`.

[[data.sql.jpa-and-spring-data]]
=== JPA 与 Spring Data JPA
Java Persistence API (Java 持久化 API) 是一项标准技术,可让您将对象映射到关系数据库. `spring-boot-starter-data-jpa` POM 提供了一个快速起步的方法. 它提供了以下关键依赖:

* Hibernate:  最受欢迎的 JPA 实现之一.
* Spring Data JPA: 帮助你实现基于 JPA 的资源库.
* Spring ORM: Spring Framework 的核心 ORM 支持

TIP: 我们不会在这里介绍太多关于 JPA 或者  {spring-data}[Spring Data]  的相关内容. 您可以在 https://spring.io 上查看使用 https://spring.io/guides/gs/accessing-data-jpa/["`JPA 访问数据`"],获取阅读 {spring-data-jpa}[Spring Data JPA] 和 https://hibernate.org/orm/documentation/[Hibernate] 的参考文档.

[[data.sql.jpa-and-spring-data.entity-classes]]
==== 实体类
通常,JPA Entity (实体) 类是在 `persistence.xml` 文件中指定的. 使用了 Spring Boot,该文件将不是必需的,可以使用 Entity Scanning (实体扫描) 来代替. 默认情况下,将搜索主配置类 (使用了 `@EnableAutoConfiguration` 或 `@SpringBootApplication` 注解) 下面的所有包.

任何用了 `@Entity`、`@Embeddable` 或者 `@MappedSuperclass` 注解的类将被考虑. 一个典型的实体类如下:

include::code:City[]

TIP: 您可以使用 `@EntityScan` 注解自定义实体类的扫描位置. 请参见 "`<<howto#howto.data-access.separate-entity-definitions-from-spring-configuration>>`"  章节.

[[data.sql.jpa-and-spring-data.repositories]]
==== Spring Data JPA 存储库
{spring-data-jpa}[Spring Data JPA]  存储库 (repository) 是一个接口,您可以定义用于访问数据. JAP 查询是根据您的方法名自动创建. 例如,`CityRepository` 接口可以声明 `findAllByState(String state)` 方法来查找指定状态下的所有城市.

对于更加复杂的查询,您可以使用 Spring Data 的 {spring-data-jpa-api}/repository/Query.html[`Query`] 注解

Spring Data 存储库通常继承自 {spring-data-commons-api}/repository/Repository.html[`Repository`] 或者 {spring-data-commons-api}/repository/CrudRepository.html[`CrudRepository`] 接口. 如果您使用了自动配置,则将从包含主配置类 (使用了 `@EnableAutoConfiguration` 或 `@SpringBootApplication` 注解) 的包中搜索存储库:

以下是一个典型的 Spring Data 存储库接口定义:

include::code:CityRepository[]

Spring Data JPA 存储库支持三种不同的引导模式: `default`、`deferred` 和 `lazy`. 要启用 deferred （延迟）或 lazy（懒）加载,请将 `spring.data.jpa.repositories.bootstrap-mode` 分别设置为 `deferred` 或 `lazy`. 使用延迟或懒加载时,自动配置的 `EntityManagerFactoryBuilder` 将使用上下文的 `AsyncTaskExecutor`  (如果有) 作为 `applicationTaskExecutor`.

[NOTE]
====
使用 deferred 或 lazy 加载时,请确保在应用程序上下文阶段之后,延迟对 JPA 的任何访问.
您可以使用  `SmartInitializingSingleton`  来调用任何需要 JPA 基础结构的初始化.
对于以 Spring Bean 创建的 JPA 组件 (例如转换器) ， 请使用 `ObjectProvider` 延迟对依赖项的解析(如果有)
====

TIP: 我们几乎没有接触到 Spring Data JPA 的表面内容. 有关详细信息,请查阅 {spring-data-jdbc-docs}[Spring Data JPA 参考文档].

[[data.sql.jpa-and-spring-data.envers-repositories]]
==== Spring Data Envers 存储库
如果 {spring-data-envers}[Spring Data Envers] 可用，JPA 存储库将自动配置为支持典型的 Envers 查询。

要使用 Spring Data Envers，请确保您的存储库从 `RevisionRepository` 扩展，如以下示例所示:

include::code:CountryRepository[]

NOTE: 有关更多详细信息，请查看 {spring-data-envers-doc}[Spring Data Envers 参考文档]。

[[data.sql.jpa-and-spring-data.creating-and-dropping]]
==== 创建和删除 JPA 数据库
默认情况下,仅当您使用了内嵌数据库 (H2、HSQL 或 Derby) 时才会自动创建 JPA 数据库. 您可以使用 `+spring.jpa.*+` 属性显式配置 JPA 设置. 例如,要创建和删除表,您可以将以下内容添加到 `application.properties` 中:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  jpa:
	    hibernate.ddl-auto: "create-drop"
----

NOTE: 关于上述功能,Hibernate 自己的内部属性名称 (如果您记住更好) 为 `hibernate.hbm2ddl.auto`. 您可以使用 `+spring.jpa.properties.*+` (在添加到实体管理器之前,该前缀将被删除) 来将 Hibernate 原生属性一同设置:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  jpa:
	    properties:
	      hibernate:
	        "globally_quoted_identifiers": "true"
----

上面示例中将 `true` 值设置给 `hibernate.globally_quoted_identifiers` 属性,该属性将传给 Hibernate 实体管理器.

默认情况下,DDL 执行 (或验证) 将延迟到 `ApplicationContext` 启动后. 还有一个 `spring.jpa.generate-ddl` 标志,如果 Hibernate 自动配置是激活的,那么它将不会被使用,因为 `ddl-auto` 设置更细粒度.

[[data.sql.jpa-and-spring-data.open-entity-manager-in-view]]
==== 在视图中打开 EntityManager
如果您正在运行 web 应用程序,Spring Boot 将默认注册  {spring-framework-api}/orm/jpa/support/OpenEntityManagerInViewInterceptor.html[`OpenEntityManagerInViewInterceptor`] 用于在视图中打开 EntityManager 模式,即运允许在 web 视图中延迟加载. 如果您不想开启这个行为,则应在 `application.properties` 中将 `spring.jpa.open-in-view` 设置为 `false`.

[[data.sql.jdbc]]
=== Spring Data JDBC
Spring Data 包含了对 JDBC 资源库的支持,并将自动为 `CrudRepository` 上的方法生成 SQL. 对于更高级的查询,它提供了 `@Query` 注解.

当 classpath 下存在必要的依赖时,Spring Boot 将自动配置 Spring Data 的 JDBC 资源库. 可以通过添加单个 `spring-boot-starter-data-jdbc` 依赖引入到项目中. 如有必要,可通过在应用程序中添加 `@EnableJdbcRepositories` 注解或 `JdbcConfiguration` 子类来控制 Spring Data JDBC 的配置.

TIP: 有关 Spring Data JDBC 的完整详细信息,请参阅 {spring-data-jdbc-docs}[参考文档].

[[data.sql.h2-web-console]]
=== 使用 H2 的 Web 控制台
https://www.h2database.com[H2 database] 数据库提供了一个 https://www.h2database.com/html/quickstart.html#h2_console[基于浏览器的控制台],Spring Boot 可以为您自动配置. 当满足以下条件时,控制台将自动配置:

* 您开发的是一个基于 servlet 的 web 应用程序
* `com.h2database:h2` 在 classpath 上
* 您使用了 <<using#using.devtools,Spring Boot 的开发者工具>>.

TIP: 如果您不使用 Spring Boot 的开发者工具,但仍希望使用 H2 的控制台,则可以通过将 `spring.h2.console.enabled` 属性设置为 `true` 来实现.

NOTE: H2 控制台仅用于开发期间,因此应注意确保 `spring.h2.console.enabled` 在生产环境中没有设置为 `true`.

[[data.sql.h2-web-console.custom-path]]
==== 更改 H2 控制台的路径
默认情况下,控制台的路径为 `/h2-console`. 你可以使用 `spring.h2.console.path` 属性来自定义控制台的路径.

[[data.sql.h2-web-console.spring-security]]
==== 在安全应用程序中访问 H2 控制台
H2 控制台使用框架，并且仅用于开发，而且不实现 CSRF 保护措施。 如果您的应用程序使用 Spring Security，则需要将其配置为

* 禁用针对控制台请求的 CSRF 保护，
* 在来自控制台的响应中，将标题 `X-Frame-Options` 设置为 `SAMEORIGIN`。

更多关于 {spring-security-docs}/features/exploits/csrf.html[CSRF] 和 header {spring-security-docs}/features/exploits/headers.html#headers-frame-options[X-Frame-Options]可以在 Spring Security 参考指南中找到。

在简单的设置中，可以使用如下所示的 `SecurityFilterChain`：

include::code:DevProfileSecurityConfiguration[tag=!customizer]

WARNING: H2 控制台仅供开发期间使用。 在生产中，禁用 CSRF 保护或允许网站使用框架可能会造成严重的安全风险。

TIP: `PathRequest.toH2Console()` 在自定义控制台路径时也会返回正确的请求匹配器。

[[data.sql.jooq]]
=== 使用 jOOQ
Java 面向对象查询 (Java Object Oriented Querying, https://www.jooq.org/[jOOQ]) 是一款广受欢迎的产品,出自  https://www.datageekery.com/[Data Geekery],它可以通过数据库生成 Java 代码,并允许您使用流式 API 来构建类型安全的 SQL 查询. 商业版和开源版都可以与 Spring Boot 一起使用.

[[data.sql.jooq.codegen]]
==== 代码生成
要使用 jOOQ 的类型安全查询,您需要从数据库模式生成 Java 类. 您可以按照 {jooq-docs}/#jooq-in-7-steps-step3[jOOQ 用户手册]中的说明进行操作. 如果您使用了 `jooq-codegen-maven` 插件,并且还使用了 `spring-boot-starter-parent` 父 POM,则可以安全地省略掉插件的 `<version>` 标签.
您还可以使用 Spring Boot 定义的版本变量 (例如 `h2.version`) 来声明插件的数据库依赖. 以下是一个示例:

[source,xml,indent=0,subs="verbatim"]
----
	<plugin>
		<groupId>org.jooq</groupId>
		<artifactId>jooq-codegen-maven</artifactId>
		<executions>
			...
		</executions>
		<dependencies>
			<dependency>
				<groupId>com.h2database</groupId>
				<artifactId>h2</artifactId>
				<version>${h2.version}</version>
			</dependency>
		</dependencies>
		<configuration>
			<jdbc>
				<driver>org.h2.Driver</driver>
				<url>jdbc:h2:~/yourdatabase</url>
			</jdbc>
			<generator>
				...
			</generator>
		</configuration>
	</plugin>
----

[[data.sql.jooq.dslcontext]]
==== 使用 DSLContext
jOOQ 提供的流式 API 是通过 `org.jooq.DSLContext` 接口初始化的. Spring Boot 将自动配置一个 `DSLContext` 作为 Spring Bean,并且将其连接到应用程序的 `DataSource`. 要使用 `DSLContext`,您只需要注入它:

include::code:MyBean[tag=!method]

TIP: jOOQ 手册建议使用名为 `create` 的变量来保存 `DSLContext`.

您可以使用 `DSLContext` 构建查询:

include::code:MyBean[tag=method]

[[data.sql.jooq.sqldialect]]
==== jOOQ SQL 方言
除非配置了 `spring.jooq.sql-dialect` 属性,否则 Spring Boot 会自动判定用于数据源的 SQL 方言. 如果 Spring Boot 无法检测到方言,则使用 `DEFAULT`.

NOTE: Spring Boot 只能自动配置 jOOQ 开源版本支持的方言.

[[data.sql.jooq.customizing]]
==== 自定义 jOOQ
更高级的自定义可以通过定义您自己的 `DefaultConfigurationCustomizer` bean 来实现，该 bean 将在创建 `org.jooq.Configuration` `@Bean` 之前被调用。
这优先于自动配置应用的任何内容。

如果您想完全控制 jOOQ 配置，您还可以创建自己的 `org.jooq.Configuration` `@Bean`

[[data.sql.r2dbc]]
=== 使用 R2DBC
响应式关系数据库连接 (https://r2dbc.io[R2DBC]) 项目将响应式编程 API 引入关系数据库. R2DBC 的 `io.r2dbc.spi.Connection` 提供了一种处理非阻塞数据库连接的标准方法. 通过 `ConnectionFactory` 提供连接,类似于使用 jdbc 的数据源.

`ConnectionFactory` 配置由 `+spring.r2dbc.*+` 中的外部配置属性控制. 例如,您可以在 `application.properties` 中声明以下部分:

[source,yaml,indent=0,subs="verbatim",configprops,configblocks]
----
	spring:
	  r2dbc:
	    url: "r2dbc:postgresql://localhost/test"
	    username: "dbuser"
	    password: "dbpass"
----

TIP: 您不需要指定驱动程序类名称,因为 Spring Boot 从 R2DBC 的 Connection Factory 发现中获取驱动程序.

NOTE: 您应该至少提供 url. URL 中指定的信息优先于各个属性,即 `name`, `username`, `password`  和连接池选项.

TIP: "`How-to`" 章节包括有关如何  <<howto#howto.data-initialization.using-basic-sql-scripts, 初始化数据库的部分>>

要自定义由 `ConnectionFactory` 创建的连接,即设置不需要 (或无法) 在中央数据库配置中配置的特定参数,可以使用 `ConnectionFactoryOptionsBuilderCustomizer` `@Bean`. 以下示例显示了如何从应用程序配置中获取其余选项的同时手动覆盖数据库端口:

include::code:MyR2dbcConfiguration[]

以下示例显示了如何设置一些 PostgreSQL 连接选项:

include::code:MyPostgresR2dbcConfiguration[]

当 `ConnectionFactory` bean 可用时,常规 JDBC DataSource 自动配置将退出. 如果要保留 JDBC `DataSource` 自动配置,并且对在响应式应用程序中使用阻塞 JDBC API 的风险感到满意,请在应用程序的 `@Configuration` 类上添加 `@Import(DataSourceAutoConfiguration.class)` 以重新启用它.

[[data.sql.r2dbc.embedded]]
==== 嵌入式数据库支持
与 <<features#data.sql.datasource.embedded,JDBC 支持类似>>,Spring Boot 可以自动配置嵌入式数据库进行响应式使用. 您无需提供任何连接 URL. 您只需要包括要使用的嵌入式数据库的构建依赖关系,如以下示例所示:

[source,xml,indent=0,subs="verbatim"]
----
	<dependency>
		<groupId>io.r2dbc</groupId>
		<artifactId>r2dbc-h2</artifactId>
		<scope>runtime</scope>
	</dependency>
----

[NOTE]
====
如果您在测试中使用此功能,则可能会注意到,整个测试套件将重复使用同一数据库,而不管您使用的应用程序上下文有多少. 如果要确保每个上下文都有一个单独的嵌入式数据库,则应将 `spring.r2dbc.generate-unique-name` 设置为 `true`.
====

[[data.sql.r2dbc.using-database-client]]
==== 使用 DatabaseClient
Spring Data 的 `DatabaseClient` bean 是自动配置的,您可以将其直接 `@Autowire` 到自己的 bean 中,如以下示例所示:

include::code:MyBean[]

[[data.sql.r2dbc.repositories]]
==== Spring Data R2DBC 存储库
https://spring.io/projects/spring-data-r2dbc[Spring Data R2DBC] 存储库是可以定义以访问数据的接口. 查询是根据您的方法名称自动创建的. 例如,`CityRepository` 接口可能声明了 `findAllByState(String state)` 方法来查找给定状态下的所有城市.

对于更复杂的查询,您可以使用 Spring Data 的 {spring-data-r2dbc-api}/repository/Query.html[`Query`] 注解对方法进行注解.

Spring Data 存储库通常从 {spring-data-commons-api}/repository/Repository.html[`Repository`] 或 {spring-data-commons-api}/repository/CrudRepository.html[`CrudRepository`] 接口扩展. 如果您使用自动配置,则会从包含您的主要配置类 (以 `@EnableAutoConfiguration` 或 `@SpringBootApplication` 注解的类) 的包中搜索存储库.

以下示例显示了典型的 Spring Data 存储库接口定义:

include::code:CityRepository[]

TIP: 我们只讨论了 Spring Data R2DBC 的简单的东西. 如果需要详细信息,请参阅 {spring-data-r2dbc-docs}[Spring Data R2DBC reference documentation].
