[[appendix-namespace]]
== Security 命名空间
本附录提供了对安全性命名空间中可用元素的引用以及它们创建的基础Bean的信息 (假定您了解各个类以及它们如何协同工作-您可以在项目Javadoc和本文档的其他地方找到更多信息.  ) .  如果您以前从未使用过命名空间,请阅读有关<<ns-config,命名空间>>配置的介绍性章节,因为这是对此处信息的补充.
建议在编辑基于模式的配置时使用高质量的XML编辑器,因为这将提供有关哪些元素和属性可用的上下文信息,以及说明其用途的注解.  命名空间以 https://relaxng.org/[RELAX NG] Compact格式编写,后来被转换为XSD模式.  如果您熟悉此格式,则可能希望直接检查 https://raw.githubusercontent.com/spring-projects/spring-security/master/config/src/main/resources/org/springframework/security/config/spring-security-4.1.rnc[schema file]文件.

[[nsa-web]]
=== Web Application Security

[[nsa-debug]]
==== <debug>
启用 Spring Security调试基础结构.  这将提供人类可读的 (多行) 调试信息,以监视进入安全过滤器的请求.  这可能包括敏感信息,例如请求参数或 header,并且仅应在开发环境中使用.

[[nsa-http]]
==== <http>

如果在应用程序中使用 `<http>` 元素,则会创建一个名为 "springSecurityFilterChain" 的 `FilterChainProxy` bean,并且该元素中的配置用于在 `FilterChainProxy` 中构建过滤器链.  从Spring Security 3.1开始,可以使用附加的 `http` 元素添加附加的过滤器链 footnote:[有关如何从 `web.xml` 中设置映射的信息,请参见 pass:specialcharacters,macros[<<ns-web-xml,introductory chapter>>]]. ].
某些核心过滤器始终在过滤器链中创建,而其他核心过滤器将根据存在的属性和子元素添加到堆栈中.  标准过滤器的位置是固定的 (请参见命名空间介绍中的<<filter-stack,过滤器顺序表>>) ,当用户必须在 `FilterChainProxy` bean中显式配置过滤器链时,消除了框架以前版本的常见错误源.  当然,如果需要完全控制配置,您仍然可以这样做.

所有需要引用  <<servlet-authentication-authenticationmanager,`AuthenticationManager`>>  的过滤器都会自动注入由命名空间配置创建的内部实例.

每个 `<http>` 命名空间块始终创建一个 `SecurityContextPersistenceFilter`,一个 `ExceptionTranslationFilter` 和一个 `FilterSecurityInterceptor`.  这些是固定的,不能用替代方法替代.

[[nsa-http-attributes]]
===== <http> 属性
`<http>` 元素上的属性控制核心过滤器上的某些属性.


[[nsa-http-access-decision-manager-ref]]
* **access-decision-manager-ref**
可选属性,用于指定应用于授权HTTP请求的 `AccessDecisionManager` 实现的ID. 默认情况下,`AffirmativeBased` 实现用于 `RoleVoter` 和 `AuthenticatedVoter`.

[[nsa-http-authentication-manager-ref]]
* **authentication-manager-ref**
对用于此http元素创建的 `FilterChain` 的 `AuthenticationManager` 的引用.


[[nsa-http-auto-config]]
* **auto-config**
自动注册登录表单,BASIC身份验证,注销服务.  如果设置为 "true",则会添加所有这些功能 (尽管您仍然可以通过提供相应的元素来自定义每个功能的配置) .  如果未指定,则默认为 "false".  不建议使用此属性.  请使用显式配置元素来避免混淆.

[[nsa-http-create-session]]
* **create-session**
控制Spring Security类创建HTTP会话的迫切性. 选项包括:

** `always` - 如果不存在会话,Spring Security将主动创建一个会话.
** `ifRequired` - 仅在需要一个会话时,Spring Security才会创建一个会话 (默认值) .
** `never` - Spring Security永远不会创建会话,但如果应用程序创建会话,它将使用一个会话.
** `stateless` - Spring Security不会创建会话,并且会忽略该会话以获取Spring `Authentication`.

[[nsa-http-disable-url-rewriting]]
* **disable-url-rewriting**
防止将会话ID附加到应用程序中的URL. 如果此属性设置为 `true`,则客户端必须使用cookie. 默认值为 `true`.


[[nsa-http-entry-point-ref]]
* **entry-point-ref**
通常,将根据已配置的身份验证机制来设置使用的 `AuthenticationEntryPoint`.  此属性允许通过定义自定义的 `AuthenticationEntryPoint` bean来覆盖此行为,该bean将启动身份验证过程.


[[nsa-http-jaas-api-provision]]
* **jaas-api-provision**
如果可用,则将请求作为从 `JaasAuthenticationToken` 获取的 `Subject` 运行,该请求是通过将 `JaasApiIntegrationFilter` bean添加到堆栈中来实现的.  默认为 `false`.


[[nsa-http-name]]
* **name**
Bean标识符,用于引用上下文中其他位置的Bean.


[[nsa-http-once-per-request]]
* **once-per-request**
对应于 `FilterSecurityInterceptor` 的 `observeOncePerRequest` 属性. 默认为 `true`.


[[nsa-http-pattern]]
* **pattern**
为<<nsa-http,http>>元素定义模式可控制将通过其定义的过滤器列表进行过滤的请求.  解释取决于配置的 <<nsa-http-request-matcher,request-matcher>>.  如果未定义任何模式,则将匹配所有请求,因此应首先声明最具体的模式.

[[nsa-http-realm]]
* **realm**
设置用于基本身份验证的领域名称 (如果启用) . 对应于 `BasicAuthenticationEntryPoint` 上的 `realmName` 属性.


[[nsa-http-request-matcher]]
* **request-matcher**
定义在 `FilterChainProxy` 中使用的 `RequestMatcher` 策略以及由 `intercept-url` 创建的Bean,以匹配传入的请求.  当前,Spring MVC的选项分别是 `mvc`,`ant`,`regex` 和 `ciRegex`,ant,regular-expression和不区分大小写的正则表达式.
使用其<<nsa-intercept-url-pattern,pattern>>,<<nsa-intercept-url-method,method>> 和<<nsa-intercept-url-servlet-path,servlet-path>>属性为每个<<nsa-intercept-url,intercept-url>>元素创建一个单独的实例.
使用 `AntPathRequestMatcher` 匹配Ant路径,使用 `RegexRequestMatcher` 匹配正则表达式,对于Spring MVC路径,使用 `MvcRequestMatcher` 匹配.  有关这些类的确切执行方式的更多详细信息,请参见Javadoc.  蚂蚁路径是默认策略.

[[nsa-http-request-matcher-ref]]
* **request-matcher-ref**
对实现 `RequestMatcher` 的bean的引用,该请求将确定是否应使用此 `FilterChain`. 这是<<nsa-http-pattern,pattern>>的更强大替代方案.

[[nsa-http-security]]
* **security**
通过将此属性设置为 `none`,可以将请求模式映射到一个空的过滤器链. 不会应用任何安全性,并且Spring Security的任何功能都不可用.


[[nsa-http-security-context-repository-ref]]
* **security-context-repository-ref**
允许将自定义 `SecurityContextRepository` 注入 `SecurityContextPersistenceFilter`.


[[nsa-http-servlet-api-provision]]
* **servlet-api-provision**
提供 `HttpServletRequest` 安全方法的版本,例如 `isUserInRole()` 和 `getPrincipal()`,这些方法是通过将 `SecurityContextHolderAwareRequestFilter` bean添加到堆栈中来实现的. 默认为 `true`.

[[nsa-http-use-expressions]]
* **use-expressions**
如关于<<el-access-web,基于表达式的访问控制>>一章所述,在访问属性中启用EL表达式. 默认值是 `true`.

[[nsa-http-children]]
=====  <http> 子元素
* <<nsa-access-denied-handler,access-denied-handler>>
* <<nsa-anonymous,anonymous>>
* <<nsa-cors,cors>>
* <<nsa-csrf,csrf>>
* <<nsa-custom-filter,custom-filter>>
* <<nsa-expression-handler,expression-handler>>
* <<nsa-form-login,form-login>>
* <<nsa-headers,headers>>
* <<nsa-http-basic,http-basic>>
* <<nsa-intercept-url,intercept-url>>
* <<nsa-jee,jee>>
* <<nsa-logout,logout>>
* <<nsa-oauth2-client,oauth2-client>>
* <<nsa-oauth2-login,oauth2-login>>
* <<nsa-oauth2-resource-server,oauth2-resource-server>>
* <<nsa-openid-login,openid-login>>
* <<nsa-port-mappings,port-mappings>>
* <<nsa-remember-me,remember-me>>
* <<nsa-request-cache,request-cache>>
* <<nsa-session-management,session-management>>
* <<nsa-x509,x509>>


[[nsa-access-denied-handler]]
==== <access-denied-handler>
该元素允许您使用 `error-page` 属性为 `ExceptionTranslationFilter` 所使用的默认 `AccessDeniedHandler` 设置 <<nsa-access-denied-handler-error-page,error-page>> 属性,或者使用 <<nsa-access-denied-handler-ref,ref>> 属性提供您自己的实现.  在 <<servlet-exceptiontranslationfilter,ExceptionTranslationFilter>> 的部分中对此进行了更详细的讨论.

[[nsa-access-denied-handler-parents]]
===== <access-denied-handler> 的父元素

* <<nsa-http,http>>

[[nsa-access-denied-handler-attributes]]
===== <access-denied-handler> 属性


[[nsa-access-denied-handler-error-page]]
* **error-page**
如果身份验证的用户请求他们无权访问的页面,则重定向到该页面的访问被拒绝页面.


[[nsa-access-denied-handler-ref]]
* **ref**
定义对类型为 `AccessDeniedHandler` 的Spring bean的引用.


[[nsa-cors]]
==== <cors>

该元素允许配置 `CorsFilter`. 如果未指定 `CorsFilter` 或 `CorsConfigurationSource` 且Spring MVC在类路径上,则将 `HandlerMappingIntrospector` 用作 `CorsConfigurationSource`.

[[nsa-cors-attributes]]
===== <cors> 属性
`<cors>` 元素上的属性控制 `headers` 元素.

[[nsa-cors-ref]]
* **ref**
指定 `CorsFilte` r的bean名称的可选属性.

[[nsa-cors-configuration-source-ref]]
* **cors-configuration-source-ref**
可选属性,用于指定要注入到XML命名空间创建的 `CorsFilter` 中的 `CorsConfigurationSource` 的Bean名称.

[[nsa-cors-parents]]
===== <cors> 的父元素

* <<nsa-http,http>>

[[nsa-headers]]
==== <headers>
此元素允许配置要与响应一起发送的其他 (安全) header.  它可以轻松配置多个 header,还可以通过 <<nsa-header,header>>元素设置自定义 header.  可以在 <<headers,Security Headers>>部分中找到其他信息.

** `Cache-Control`, `Pragma`, and `Expires` - 可以使用<<nsa-cache-control,cache-control>>元素进行设置. 这样可以确保浏览器不会缓存您的安全页面.
** `Strict-Transport-Security` - 可以使用 <<nsa-hsts,hsts>>元素进行设置. 这样可以确保浏览器自动为将来的请求请求HTTPS.
** `X-Frame-Options` - 可以使用 <<nsa-frame-options,frame-options>>元素进行设置.  https://en.wikipedia.org/wiki/Clickjacking#X-Frame-Options[X-Frame-Options]  头可用于防止点击劫持攻击.
** `X-XSS-Protection` - 可以使用<<nsa-xss-protection,xss-protection>> 元素进行设置. 浏览器可以使用 https://en.wikipedia.org/wiki/Cross-site_scripting[X-XSS-Protection ] 头进行基本控制.
** `X-Content-Type-Options` - 可以使用<<nsa-content-type-options,content-type-options>>元素进行设置.  https://blogs.msdn.com/b/ie/archive/2008/09/02/ie8-security-part-vi-beta-2-update.aspx[X-Content-Type-Options] 头可防止Internet Explorer MIME嗅探远离已声明内容类型的响应. 下载扩展程序时,这也适用于Google Chrome浏览器.
** `Public-Key-Pinning` or `Public-Key-Pinning-Report-Only` - 可以使用<<nsa-hpkp,hpkp>> 元素进行设置. 这允许HTTPS网站使用错误签发或欺诈性证书来抵制攻击者的冒名顶替.
** `Content-Security-Policy` or `Content-Security-Policy-Report-Only` - 可以使用<<nsa-content-security-policy,content-security-policy>>元素进行设置. https://www.w3.org/TR/CSP2/[Content Security Policy (CSP)]是Web应用程序可以利用的一种机制,可以缓解诸如跨站点脚本 (XSS) 之类的内容注入漏洞.
** `Referrer-Policy` - 可以使用<<nsa-referrer-policy,referrer-policy>>元素进行设置, https://www.w3.org/TR/referrer-policy/[Referrer-Policy]是Web应用程序可以用来管理Referrer字段的机制,该字段包含用户所在的最后一页.
** `Feature-Policy` - 可以使用<<nsa-feature-policy,feature-policy>>元素进行设置, https://wicg.github.io/feature-policy/[Feature-Policy]是一种机制,允许Web开发人员在浏览器中选择性地启用,禁用和修改某些API和Web功能的行为.

[[nsa-headers-attributes]]
===== <headers> 属性
`<headers>` 元素上的属性控制headers元素.


[[nsa-headers-defaults-disabled]]
* **defaults-disabled**
可选属性,用于指定默认的 Spring Security 的 HTTP 响应头. 默认值为false (包括默认标题) .

[[nsa-headers-disabled]]
* **disabled**
可选属性,用于指定禁用 Spring Security 的 HTTP 响应头. 默认值为false (已启用 header ) .


[[nsa-headers-parents]]
===== <headers> 的父元素

* <<nsa-http,http>>



[[nsa-headers-children]]
===== <headers> 的子元素


* <<nsa-cache-control,cache-control>>
* <<nsa-content-security-policy,content-security-policy>>
* <<nsa-content-type-options,content-type-options>>
* <<nsa-feature-policy,feature-policy>>
* <<nsa-frame-options,frame-options>>
* <<nsa-header,header>>
* <<nsa-hpkp,hpkp>>
* <<nsa-hsts,hsts>>
* <<nsa-referrer-policy,referrer-policy>>
* <<nsa-xss-protection,xss-protection>>



[[nsa-cache-control]]
==== <cache-control>
添加 `Cache-Control`,`Pragma` 和 `Expires` 头,以确保浏览器不缓存您的安全页面.


[[nsa-cache-control-attributes]]
===== <cache-control> 属性

[[nsa-cache-control-disabled]]
* **disabled**
指定是否应禁用缓存控制. 默认为 `false`.


[[nsa-cache-control-parents]]
=====  <cache-control> 的父元素


* <<nsa-headers,headers>>



[[nsa-hsts]]
==== <hsts>
启用后,会将 https://tools.ietf.org/html/rfc6797[Strict-Transport-Security] 头添加到任何安全请求的响应中. 这允许服务器指示浏览器自动将HTTPS用于将来的请求.

[[nsa-hsts-attributes]]
===== <hsts> 属性

[[nsa-hsts-disabled]]
* **disabled**
指定是否应禁用 "严格传输安全性". 默认为 `false`.

[[nsa-hsts-include-subdomains]]
* **include-sub-domains**
指定是否应包含子域. 默认为 `true`.


[[nsa-hsts-max-age-seconds]]
* **max-age-seconds**
指定应将主机视为已知HSTS主机的最长时间. 默认一年.


[[nsa-hsts-request-matcher-ref]]
* **request-matcher-ref**
用于确定是否应设置 header 的RequestMatcher实例. 默认值为 `HttpServletRequest.isSecure()` 为 `true`.

[[nsa-hsts-preload]]
* **preload**
指定是否应包含预加载. 默认为false.

[[nsa-hsts-parents]]
===== <hsts> 的父元素

* <<nsa-headers,headers>>



[[nsa-hpkp]]
==== <hpkp>
启用后,会将 https://tools.ietf.org/html/rfc7469[HTTP头的 "公钥固定扩展"] 添加到任何安全请求的响应中. 这允许HTTPS网站使用错误签发或欺诈性证书来抵制攻击者的冒名顶替.

[[nsa-hpkp-attributes]]
===== <hpkp> 属性

[[nsa-hpkp-disabled]]
* **disabled**
指定是否应禁用HTTP公钥固定 (HPKP) .  默认为true.

[[nsa-hpkp-include-subdomains]]
* **include-sub-domains**
指定是否应包含子域.  默认为false.


[[nsa-hpkp-max-age-seconds]]
* **max-age-seconds**
设置Public-Key-Pins header 的max-age指令的值.  默认为60天.


[[nsa-hpkp-report-only]]
* **report-only**
指定浏览器是否仅应报告引脚验证失败.  默认为true.


[[nsa-hpkp-report-uri]]
* **report-uri**
指定浏览器应向其报告引脚验证失败的URI.


[[nsa-hpkp-parents]]
=====  <hpkp> 的父元素

* <<nsa-headers,headers>>


[[nsa-pins]]
==== <pins>
引脚列表


[[nsa-pins-children]]
=====  <pins> 的子元素

* <<nsa-pin,pin>>


[[nsa-pin]]
==== <pin>
使用base64编码的SPKI指纹作为值并使用密码哈希算法作为属性来指定引脚

[[nsa-pin-attributes]]
===== <pin> 属性

[[nsa-pin-algorithm]]
* **algorithm**
密码哈希算法. 默认值为SHA256.


[[nsa-pin-parents]]
=====  <pin> 的父元素

* <<nsa-pins,pins>>



[[nsa-content-security-policy]]
==== <content-security-policy>
启用后,将 https://www.w3.org/TR/CSP2/[Content Security Policy (CSP)] 头添加到响应中.  CSP是Web应用程序可以用来缓解内容注入漏洞 (例如跨站点脚本 (XSS) ) 的一种机制.

[[nsa-content-security-policy-attributes]]
===== <content-security-policy> 属性

[[nsa-content-security-policy-policy-directives]]
* **policy-directives**
Content-Security-Policy header 的安全策略指令,或者如果仅报告设置为true,则使用Content-Security-Policy-Report-Only header .

[[nsa-content-security-policy-report-only]]
* **report-only**
设置为true,启用Content-Security-Policy-Report-Only header 仅用于报告策略违例. 默认为false.

[[nsa-content-security-policy-parents]]
=====  <content-security-policy> 的父元素

* <<nsa-headers,headers>>



[[nsa-referrer-policy]]
==== <referrer-policy>
启用后,将 https://www.w3.org/TR/referrer-policy/[Referrer Policy] 头添加到响应中.

[[nsa-referrer-policy-attributes]]
===== <referrer-policy> 属性

[[nsa-referrer-policy-policy]]
* **policy**
Referrer-Policy header 的策略. 默认为"no-referrer".

[[nsa-referrer-policy-parents]]
=====  <referrer-policy> 的父元素

* <<nsa-headers,headers>>



[[nsa-feature-policy]]
==== <feature-policy>
启用后,将 https://wicg.github.io/feature-policy/[Feature Policy] 头添加到响应中.

[[nsa-feature-policy-attributes]]
===== <feature-policy> 属性

[[nsa-feature-policy-policy-directives]]
* **policy-directives**
Feature-Policy 头的安全策略指令.

[[nsa-feature-policy-parents]]
=====  <feature-policy> 的父元素

* <<nsa-headers,headers>>



[[nsa-frame-options]]
==== <frame-options>
启用后,将 https://tools.ietf.org/html/draft-ietf-websec-x-frame-options[X-Frame-Options header] 头添加到响应中,这使较新的浏览器可以进行一些安全检查并防止 https://en.wikipedia.org/wiki/Clickjacking[clickjacking]攻击.

[[nsa-frame-options-attributes]]
===== <frame-options> 属性

[[nsa-frame-options-disabled]]
* **disabled**
如果禁用,则不包括X-Frame-Options 头. 默认为 `false`.

[[nsa-frame-options-policy]]
* **policy**
** `DENY` 该页面无法显示在框架中,无论站点尝试这样做.  当指定frame-options-policy时,这是默认设置.
** `SAMEORIGIN` 该页面只能以与页面本身相同的原点显示在框架中

+

换句话说,如果指定DENY,则从其他站点加载时,不仅尝试在框架中加载页面失败,而且从同一站点加载时,尝试也会失败.  另一方面,如果指定SAMEORIGIN,则只要框架中包含该站点的页面与提供该页面的站点相同,您仍可以在框架中使用该页面.

[[nsa-frame-options-parents]]
=====  <frame-options> 的父元素

* <<nsa-headers,headers>>

[[nsa-xss-protection]]
==== <xss-protection>
将 https://blogs.msdn.com/b/ie/archive/2008/07/02/ie8-security-part-iv-the-xss-filter.aspx[X-XSS-Protection header] 添加到响应中,以帮助防止 https://en.wikipedia.org/wiki/Cross-site_scripting#Non-Persistent[reflected / Type-1 Cross-Site Scripting (XSS)]攻击. 这绝不是对XSS攻击的全面保护！

[[nsa-xss-protection-attributes]]
===== <xss-protection> 属性


[[nsa-xss-protection-disabled]]
* **xss-protection-disabled**
不要包括用于 https://en.wikipedia.org/wiki/Cross-site_scripting#Non-Persistent[reflected / Type-1 Cross-Site Scripting (XSS)] 保护的头.


[[nsa-xss-protection-enabled]]
* **xss-protection-enabled**
明确启用或禁用 https://en.wikipedia.org/wiki/Cross-site_scripting#Non-Persistent[reflected / Type-1 Cross-Site Scripting (XSS)]保护.

[[nsa-xss-protection-block]]
* **xss-protection-block**
如果为true且xss-protection-enabled为true,则将mode = block添加到 header .  这向浏览器指示根本不应加载该页面.  如果为false并且xss-protection-enabled为true,则在检测到反射攻击时仍将呈现页面,但是将修改响应以防止受到攻击.  请注意,有时存在绕过此模式的方法,这些方法常常使阻塞页面更为可取.

[[nsa-xss-protection-parents]]
=====  <xss-protection> 的父元素

* <<nsa-headers,headers>>



[[nsa-content-type-options]]
==== <content-type-options>
将带有nosniff值的X-Content-Type-Options header 添加到响应中. 这将禁用IE8 +和Chrome扩展的 https://blogs.msdn.com/b/ie/archive/2008/09/02/ie8-security-part-vi-beta-2-update.aspx[disables MIME-sniffing].

[[nsa-content-type-options-attributes]]
===== <content-type-options> 属性

[[nsa-content-type-options-disabled]]
* **disabled**
指定是否应禁用 "内容类型选项". 默认为 false.

[[nsa-content-type-options-parents]]
=====  <content-type-options> 的父元素


* <<nsa-headers,headers>>



[[nsa-header]]
==== <header>
向响应添加其他 header ,名称和值都需要指定.


[[nsa-header-attributes]]
===== <header-attributes> 属性


[[nsa-header-name]]
* **header-name**
 header 名称


[[nsa-header-value]]
* **value**
要添加的 header 的值.


[[nsa-header-ref]]
* **ref**
引用 `HeaderWriter` 接口的自定义实现.


[[nsa-header-parents]]
=====  <header> 的父元素


* <<nsa-headers,headers>>



[[nsa-anonymous]]
==== <anonymous>
将 `AnonymousAuthenticationFilter` 添加到堆栈和 `AnonymousAuthenticationProvider`. 如果使用 `IS_AUTHENTICATED_ANONYMOUSLY` 属性,则为必需.

[[nsa-anonymous-parents]]
=====  <anonymous> 的父元素


* <<nsa-http,http>>



[[nsa-anonymous-attributes]]
===== <anonymous> 属性


[[nsa-anonymous-enabled]]
* **enabled**
使用默认的命名空间设置,将自动启用匿名 "身份验证" 功能. 您可以使用此属性禁用它.


[[nsa-anonymous-granted-authority]]
* **granted-authority**
应该分配给匿名请求的授权权限. 通常,这用于为匿名请求分配特定角色,随后可以在授权决策中使用这些角色. 如果未设置,则默认为 `ROLE_ANONYMOUS`.

[[nsa-anonymous-key]]
* **key**
提供者和过滤器之间共享的密钥.  通常不需要设置.  如果未设置,则默认为安全随机生成的值.  这意味着在使用匿名功能时设置此值可以缩短启动时间,因为生成安全随机值可能需要一段时间.


[[nsa-anonymous-username]]
* **username**
应该分配给匿名请求的用户名. 这样可以确定主体,这对于日志记录和审核可能很重要. 如果未设置,则默认为 `anonymousUser`.


[[nsa-csrf]]
==== <csrf>
该元素将向应用程序添加 https://en.wikipedia.org/wiki/Cross-site_request_forgery[Cross Site Request Forger (CSRF)] 保护.  它还将默认的RequestCache更新为仅在成功身份验证后重播 "GET" 请求.  可以在<<csrf,跨站点请求伪造 (CSRF) >>部分中找到其他信息.

[[nsa-csrf-parents]]
=====  <csrf> 的父元素


* <<nsa-http,http>>



[[nsa-csrf-attributes]]
===== <csrf> 属性

[[nsa-csrf-disabled]]
* **disabled**
可选属性,用于指定禁用Spring Security的CSRF保护. 默认值为false (启用CSRF保护) . 强烈建议使CSRF保护处于启用状态.

[[nsa-csrf-token-repository-ref]]
* **token-repository-ref**
要使用的 `CsrfTokenRepository`. 默认值为 `HttpSessionCsrfTokenRepository`.


[[nsa-csrf-request-matcher-ref]]
* **request-matcher-ref**
用于确定是否应应用CSRF的RequestMatcher实例. 默认为除 "GET", "TRACE", "HEAD", "OPTIONS" 之外的任何HTTP方法.

[[nsa-custom-filter]]
==== <custom-filter>

该元素用于向过滤器链添加过滤器.  它不会创建任何其他bean,而是用于选择 `javax.servlet.Filter` 类型的bean (已在应用程序上下文中定义) ,并将其添加到Spring Security维护的过滤器链中的特定位置.  完整的详细信息可以在<<ns-custom-filters,命名空间>>一章中找到.

[[nsa-custom-filter-parents]]
=====  <custom-filter> 的父元素


* <<nsa-http,http>>



[[nsa-custom-filter-attributes]]
===== <custom-filter> 属性


[[nsa-custom-filter-after]]
* **after**
紧随其后的过滤器,应将自定义过滤器放置在链中.  只有希望将自己的过滤器混入安全过滤器链并了解标准Spring Security过滤器的高级用户才需要使用此功能.  过滤器名称映射到特定的Spring Security实现过滤器.


[[nsa-custom-filter-before]]
* **before**
紧接在过滤器之前的自定义过滤器应放置在链中的过滤器


[[nsa-custom-filter-position]]
* **position**
自定义过滤器应放置在链中的明确位置. 如果要更换标准过滤器,请使用.


[[nsa-custom-filter-ref]]
* **ref**
定义对实现 `Filter` 的Spring bean的引用.


[[nsa-expression-handler]]
==== <expression-handler>
定义 `SecurityExpressionHandler` 实例,如果启用了基于表达式的访问控制,则将使用该实例. 如果未提供,则将使用默认实现 (不支持ACL) .

[[nsa-expression-handler-parents]]
=====  <expression-handler> 的父元素


* <<nsa-global-method-security,global-method-security>>
* <<nsa-http,http>>
* <<nsa-websocket-message-broker,websocket-message-broker>>



[[nsa-expression-handler-attributes]]
===== <expression-handler> 属性


[[nsa-expression-handler-ref]]
* **ref**

定义对实现 `SecurityExpressionHandler` 的Spring bean的引用.


[[nsa-form-login]]
==== <form-login>
用于将 `UsernamePasswordAuthenticationFilter` 添加到过滤器堆栈,并将 `LoginUrlAuthenticationEntryPoint` 添加到应用程序上下文,以按需提供身份验证.  这将始终优先于其他由命名空间创建的入口点.  如果未提供任何属性,则将在URL "/login" footnote:[此功能实际上只是为了方便起见而提供的,并不打算用于生产 (在该功能中,将选择一种查看技术,并可用于呈现自定义的登录页面) .  类DefaultLoginPageGeneratingFilter负责呈现登录页面,并在需要时提供用于普通表单登录和/或OpenID的登录表单. ] 上自动生成登录页面.
可以使用<<nsa-form-login-attributes, `<form-login>` 属性>>自定义行为.

[[nsa-form-login-parents]]
=====  <form-login> 的父元素


* <<nsa-http,http>>



[[nsa-form-login-attributes]]
===== <form-login> 属性


[[nsa-form-login-always-use-default-target]]
* **always-use-default-target**
如果设置为 `true`,则无论用户如何到达登录页面,用户将始终从 <<nsa-form-login-default-target-url,default-target-url>> 给定的值开始. 映射到 `UsernamePasswordAuthenticationFilter` 的 `alwaysUseDefaultTargetUrl` 属性. 默认值为 `false`.

[[nsa-form-login-authentication-details-source-ref]]
* **authentication-details-source-ref**
对将由身份验证过滤器使用的 `AuthenticationDetailsSource` 的引用


[[nsa-form-login-authentication-failure-handler-ref]]
* **authentication-failure-handler-ref**
可以用作<<nsa-form-login-authentication-failure-url,authentication-failure-url>>的替代方法,从而使您可以在身份验证失败后完全控制导航流程. 该值应该是应用程序上下文中的 `AuthenticationFailureHandler` bean的名称.

[[nsa-form-login-authentication-failure-url]]
* **authentication-failure-url**
映射到 `UsernamePasswordAuthenticationFilter` 的 `authenticationFailureUrl` 属性.  定义登录失败时浏览器将重定向到的URL.  默认值为 `/login?error`,它将由自动登录页面生成器自动处理,并使用错误消息重新呈现登录页面.

[[nsa-form-login-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
这可以用作<<nsa-form-login-default-target-url,default-target-url>> 和<<nsa-form-login-always-use-default-target,always-use-default-target>>的替代方法,使您在成功认证后完全控制导航流程.  该值应该是应用程序上下文中 `AuthenticationSuccessHandler` bean的名称.  默认情况下,将使用 `SavedRequestAwareAuthenticationSuccessHandler` 的实现,并将其注入<<nsa-form-login-default-target-url,default-target-url >>.

[[nsa-form-login-default-target-url]]
* **default-target-url**
映射到 `UsernamePasswordAuthenticationFilter` 的 `defaultTargetUrl` 属性.  如果未设置,则默认值为 "/" (应用程序根目录) .  如果将用户带到最初请求的URL,则在尝试访问受保护的资源时不要求用户登录后,将在登录后将其带到该URL.


[[nsa-form-login-login-page]]
* **login-page**
用于呈现登录页面的URL. 映射到 `LoginUrlAuthenticationEntryPoint` 的 `loginFormUrl` 属性. 默认为 "/login".

[[nsa-form-login-login-processing-url]]
* **login-processing-url**
映射到 `UsernamePasswordAuthenticationFilter` 的 `filterProcessesUrl` 属性. 默认值为 "/login".

[[nsa-form-login-password-parameter]]
* **password-parameter**
包含密码的请求参数的名称. 默认为 "password".


[[nsa-form-login-username-parameter]]
* **username-parameter**
包含用户名的请求参数的名称. 默认为 "username".

[[nsa-form-login-authentication-success-forward-url]]
* **authentication-success-forward-url**
将 `ForwardAuthenticationSuccessHandler` 映射到 `UsernamePasswordAuthenticationFilter` 的 `authenticationSuccessHandler` 属性.

[[nsa-form-login-authentication-failure-forward-url]]
* **authentication-failure-forward-url**
将 `ForwardAuthenticationFailureHandler` 映射到 `UsernamePasswordAuthenticationFilter` 的 `authenticationFailureHandler` 属性.

[[nsa-oauth2-login]]
==== <oauth2-login>
<<oauth2login,OAuth 2.0 Login>> 功能使用OAuth 2.0 和/或 OpenID Connect 1.0提供程序配置身份验证支持.

[[nsa-oauth2-login-parents]]
===== <oauth2-login> 的父元素

* <<nsa-http,http>>

[[nsa-oauth2-login-attributes]]
===== <oauth2-login> 属性


[[nsa-oauth2-login-client-registration-repository-ref]]
* **client-registration-repository-ref**
对 `ClientRegistrationRepository` 的引用.


[[nsa-oauth2-login-authorized-client-repository-ref]]
* **authorized-client-repository-ref**
引用 `OAuth2AuthorizedClientRepository`.


[[nsa-oauth2-login-authorized-client-service-ref]]
* **authorized-client-service-ref**
引用 `OAuth2AuthorizedClientService`.


[[nsa-oauth2-login-authorization-request-repository-ref]]
* **authorization-request-repository-ref**
引用 `AuthorizationRequestRepository`.


[[nsa-oauth2-login-authorization-request-resolver-ref]]
* **authorization-request-resolver-ref**
引用 `OAuth2AuthorizationRequestResolver`.


[[nsa-oauth2-login-access-token-response-client-ref]]
* **access-token-response-client-ref**
引用 `OAuth2AccessTokenResponseClient`.


[[nsa-oauth2-login-user-authorities-mapper-ref]]
* **user-authorities-mapper-ref**
引用 `GrantedAuthoritiesMapper`.


[[nsa-oauth2-login-user-service-ref]]
* **user-service-ref**
引用 `OAuth2UserService`.


[[nsa-oauth2-login-oidc-user-service-ref]]
* **oidc-user-service-ref**
对OpenID Connect `OAuth2UserService` 的引用.


[[nsa-oauth2-login-login-processing-url]]
* **login-processing-url**
过滤器在其中处理身份验证请求的URI.


[[nsa-oauth2-login-login-page]]
* **login-page**
发送用户登录的URI.


[[nsa-oauth2-login-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
引用 `AuthenticationSuccessHandler`.


[[nsa-oauth2-login-authentication-failure-handler-ref]]
* **authentication-failure-handler-ref**
引用 `AuthenticationFailureHandler`.


[[nsa-oauth2-login-jwt-decoder-factory-ref]]
* **jwt-decoder-factory-ref**
引用由 `OidcAuthorizationCodeAuthenticationProvider` 使用的 `JwtDecoderFactory`.

[[nsa-oauth2-client]]
==== <oauth2-client>
配置  <<oauth2client,OAuth 2.0 Client>>  支持.

[[nsa-oauth2-client-parents]]
===== <oauth2-client> 父元素

* <<nsa-http,http>>

[[nsa-oauth2-client-attributes]]
===== <oauth2-client> 属性


[[nsa-oauth2-client-client-registration-repository-ref]]
* **client-registration-repository-ref**
引用 `ClientRegistrationRepository`.


[[nsa-oauth2-client-authorized-client-repository-ref]]
* **authorized-client-repository-ref**
引用 `OAuth2AuthorizedClientRepository`.


[[nsa-oauth2-client-authorized-client-service-ref]]
* **authorized-client-service-ref**
引用 `OAuth2AuthorizedClientService`.


[[nsa-oauth2-client-children]]
===== <oauth2-client> 的子元素

* <<nsa-authorization-code-grant,authorization-code-grant>>


[[nsa-authorization-code-grant]]
==== <authorization-code-grant>
配置 <<oauth2Client-auth-grant-support,OAuth 2.0 Authorization Code Grant>>.


[[nsa-authorization-code-grant-parents]]
===== <authorization-code-grant> 的父元素

* <<nsa-oauth2-client,oauth2-client>>


[[nsa-authorization-code-grant-attributes]]
===== <authorization-code-grant> 属性


[[nsa-authorization-code-grant-authorization-request-repository-ref]]
* **authorization-request-repository-ref**
引用 `AuthorizationRequestRepository`.


[[nsa-authorization-code-grant-authorization-request-resolver-ref]]
* **authorization-request-resolver-ref**
引用 `OAuth2AuthorizationRequestResolver`.


[[nsa-authorization-code-grant-access-token-response-client-ref]]
* **access-token-response-client-ref**
引用 `OAuth2AccessTokenResponseClient`.


[[nsa-client-registrations]]
==== <client-registrations>
已向OAuth 2.0或OpenID Connect 1.0提供程序注册的客户端 (<<oauth2Client-client-registration,ClientRegistration>>)  的容器元素.

[[nsa-client-registrations-children]]
===== <client-registrations> 子元素

* <<nsa-client-registration,client-registration>>
* <<nsa-provider,provider>>


[[nsa-client-registration]]
==== <client-registration>
代表在OAuth 2.0或OpenID Connect 1.0提供程序中注册的客户端.


[[nsa-client-registration-parents]]
===== <client-registration> 父元素

* <<nsa-client-registrations,client-registrations>>


[[nsa-client-registration-attributes]]
===== <client-registration> 属性


[[nsa-client-registration-registration-id]]
* **registration-id**
唯一标识 `ClientRegistration` 的ID.


[[nsa-client-registration-client-id]]
* **client-id**
客户端标识符.


[[nsa-client-registration-client-secret]]
* **client-secret**
客户端 secret.


[[nsa-client-registration-client-authentication-method]]
* **client-authentication-method**
使用提供者对客户端进行身份验证的方法.
支持的值为  *basic*, *post*  和  *none*  https://tools.ietf.org/html/rfc6749#section-2.1[(public clients)]

[[nsa-client-registration-authorization-grant-type]]
* **authorization-grant-type**
OAuth 2.0授权框架定义了四种 https://tools.ietf.org/html/rfc6749#section-1.3[Authorization Grant] 类型.
支持的值是  `authorization_code`, `client_credentials` 和  `password`.

[[nsa-client-registration-redirect-uri]]
* **redirect-uri**
_Authorization Server_在最终用户对客户端进行身份验证和授权访问之后,_Authorization Server_将最终用户的用户代理重定向到的客户端的注册重定向URI.

[[nsa-client-registration-scope]]
* **scope**
客户在授权请求流程中请求的范围,例如openid,电子邮件或配置文件.


[[nsa-client-registration-client-name]]
* **client-name**
用于客户端的描述性名称.
该名称可能在某些情况下使用,例如在自动生成的登录页面中显示客户端名称时.

[[nsa-client-registration-provider-id]]
* **provider-id**
对关联提供者的引用.  可以引用 `<provider>` 元素或使用常见的提供程序之一 (google,github,facebook,okta) .

[[nsa-provider]]
==== <provider>
OAuth 2.0或OpenID Connect 1.0提供程序的配置信息.


[[nsa-provider-parents]]
===== <provider> 父元素

* <<nsa-client-registrations,client-registrations>>


[[nsa-provider-attributes]]
===== <provider> 属性


[[nsa-provider-provider-id]]
* **provider-id**
唯一标识提供者的ID.


[[nsa-provider-authorization-uri]]
* **authorization-uri**
授权服务器的授权端点URI.


[[nsa-provider-token-uri]]
* **token-uri**
授权服务器的令牌端点URI.


[[nsa-provider-user-info-uri]]
* **user-info-uri**
UserInfo端点URI,用于访问经过身份验证的最终用户的  claims/attributes.

[[nsa-provider-user-info-authentication-method]]
* **user-info-authentication-method**
将访问令牌发送到UserInfo端点时使用的身份验证方法.
支持的值为  *header*, *form* 和 *query*.

[[nsa-provider-user-info-user-name-attribute]]
* **user-info-user-name-attribute**
在UserInfo响应中返回的属性名称,该属性引用了最终用户的名称或标识符.


[[nsa-provider-jwk-set-uri]]
* **jwk-set-uri**
用于从授权服务器检索JSON Web密钥 (https://tools.ietf.org/html/rfc7517[JSON Web Key (JWK)] ) 集的URI,其中包含用于验证ID令牌的JSON Web签名 (https://tools.ietf.org/html/rfc7515[JSON Web Signature (JWS)] ) 以及用户信息响应 (可选) 的加密密钥.

[[nsa-provider-issuer-uri]]
* **issuer-uri**
用于发现OpenID Connect提供程序的 https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Configuration endpoint]或授权服务器的  https://tools.ietf.org/html/rfc8414#section-3[Metadata endpoint] 的URI,用于初始配置 `ClientRegistration`.

[[nsa-oauth2-resource-server]]
==== <oauth2-resource-server>
将 `BearerTokenAuthenticationFilter`,`BearerTokenAuthenticationEntryPoint` 和 `BearerTokenAccessDeniedHandler` 添加到配置中.  另外,必须指定 `<jwt>` 或 `<opaque-token>`.

[[nsa-oauth2-resource-server-parents]]
===== <oauth2-resource-server> 的父元素

* <<nsa-http,http>>

[[nsa-oauth2-resource-server-children]]
=====  <oauth2-resource-server> 的子元素

* <<nsa-jwt,jwt>>
* <<nsa-opaque-token,opaque-token>>

[[nsa-oauth2-resource-server-attributes]]
===== <oauth2-resource-server> 属性

[[nsa-oauth2-resource-server-authentication-manager-resolver-ref]]
* **authentication-manager-resolver-ref**
引用 `AuthenticationManagerResolver`,它将在请求时解析 `AuthenticationManager`

[[nsa-oauth2-resource-server-bearer-token-resolver-ref]]
* **bearer-token-resolver-ref**
引用 `BearerTokenResolver`,它将从请求中获取承载令牌.

[[nsa-oauth2-resource-server-entry-point-ref]]
* **entry-point-ref**
引用将处理未授权请求的 `AuthenticationEntryPoint`

[[nsa-jwt]]
==== <jwt>
表示将授权JWT的OAuth 2.0资源服务器


[[nsa-jwt-parents]]
=====  <jwt> 的父元素

* <<nsa-oauth2-resource-server,oauth2-resource-server>>


[[nsa-jwt-attributes]]
===== <jwt> 属性

[[nsa-jwt-jwt-authentication-converter-ref]]
* **jwt-authentication-converter-ref**
对  `Converter<Jwt, AbstractAuthenticationToken>` 的引用

[[nsa-jwt-decoder-ref]]
* **jwt-decoder-ref**
引用 `JwtDecoder`.  这是一个较大的组件,它会覆盖 `jwk-set-uri`

[[nsa-jwt-jwk-set-uri]]
* **jwk-set-uri**
用于从OAuth 2.0授权服务器加载签名验证密钥的JWK集Uri

[[nsa-opaque-token]]
==== <opaque-token>
表示将授权不透明令牌的OAuth 2.0资源服务器

[[nsa-opaque-token-parents]]
===== <opaque-token> 的父元素

* <<nsa-oauth2-resource-server,oauth2-resource-server>>

[[nsa-opaque-token-attributes]]
===== <opaque-token> 属性

[[nsa-opaque-token-introspector-ref]]
* **introspector-ref**
引用 `OpaqueTokenIntrospector`. 这是一个较大的组件,它会覆盖 `introspection-uri`, `client-id`, 和 `client-secret`.

[[nsa-opaque-token-introspection-uri]]
* **introspection-uri**
内省Uri用来内省不透明令牌的详细信息.  应随附 `client-id` 和 `client-secret`.

[[nsa-opaque-token-client-id]]
* **client-id**
用于针对提供的 `introspection-uri` 进行客户端身份验证的客户端ID.

[[nsa-opaque-token-client-secret]]
* **client-secret**
用于根据提供的 `introspection-uri` 进行客户端身份验证的客户端密钥.


[[nsa-http-basic]]
==== <http-basic>
将 `BasicAuthenticationFilter` 和 `BasicAuthenticationEntryPoint` 添加到配置中. 如果未启用基于表单的登录,则后者将仅用作配置入口点.

[[nsa-http-basic-parents]]
=====  <http-basic> 的父元素


* <<nsa-http,http>>



[[nsa-http-basic-attributes]]
===== <http-basic> 属性


[[nsa-http-basic-authentication-details-source-ref]]
* **authentication-details-source-ref**
对将由身份验证过滤器使用 的 `AuthenticationDetailsSource` 的引用


[[nsa-http-basic-entry-point-ref]]
* **entry-point-ref**
设置 `BasicAuthenticationFilter` 使用的 `AuthenticationEntryPoint`.

[[nsa-http-firewall]]
==== <http-firewall> 元素
这是一个顶级元素,可用于将 `HttpFirewall` 的自定义实现注入到由命名空间创建的 `FilterChainProxy` 中. 默认实现应适合大多数应用程序.

[[nsa-http-firewall-attributes]]
===== <http-firewall> 属性


[[nsa-http-firewall-ref]]
* **ref**
定义对实现 `HttpFirewall` 的Spring bean的引用.


[[nsa-intercept-url]]
==== <intercept-url>
此元素用于定义应用程序感兴趣的URL模式集,并配置应如何处理它们.  它用于构造 `FilterSecurityInterceptor` 使用的 `FilterInvocationSecurityMetadataSource`.  例如,如果需要通过HTTPS访问特定的URL,它还负责配置 `ChannelProcessingFilter`.  当将指定的模式与传入的请求进行匹配时,将按照声明元素的顺序进行匹配.
因此,最具体的模式应该放在首位,最一般的模式应该放在最后.

[[nsa-intercept-url-parents]]
=====  <intercept-url> 的父元素


* <<nsa-filter-security-metadata-source,filter-security-metadata-source>>
* <<nsa-http,http>>



[[nsa-intercept-url-attributes]]
===== <intercept-url> 属性


[[nsa-intercept-url-access]]
* **access**
列出访问属性,这些属性将为定义的URL模式/方法组合存储在 `FilterInvocationSecurityMetadataSource` 中. 这应该是安全配置属性 (例如角色名称) 的逗号分隔列表.

[[nsa-intercept-url-method]]
* **method**
HTTP方法将与模式和servlet路径 (可选) 结合使用,以匹配传入的请求.  如果省略,则任何方法都将匹配.  如果使用和不使用方法指定了相同的模式,则特定于方法的匹配将优先.

[[nsa-intercept-url-pattern]]
* **pattern**
定义URL路径的模式. 内容将取决于包含http元素的 `request-matcher` 属性,因此默认为 ant path语法.

[[nsa-intercept-url-request-matcher-ref]]
* **request-matcher-ref**
对 `RequestMatcher` 的引用,该引用将用于确定是否使用此 `<intercept-url>`.

[[nsa-intercept-url-requires-channel]]
* **requires-channel**
可以为 "http"  或 "https",具体取决于应分别通过HTTP还是HTTPS访问特定的URL模式.  或者,在没有首选项时可以使用值 "any".  如果任何 `<intercept-url>` 元素上都存在此属性,则将 `ChannelProcessingFilter` 添加到过滤器堆栈中,并将其附加依赖添加到应用程序上下文中.

如果添加了 `<port-mappings>` 配置,则 `SecureChannelProcessor` 和 `InsecureChannelProcessor` Bean将使用此配置来确定用于重定向到 `HTTP/HTTPS` 的端口.

NOTE: 此属性对于<<nsa-filter-security-metadata-source,filter-security-metadata-source>>无效

[[nsa-intercept-url-servlet-path]]
* **servlet-path**
Servlet路径将与模式和HTTP方法结合使用,以匹配传入的请求.  仅当<<nsa-http-request-matcher,请求匹配>>为 `mvc` 时,此属性才适用.  另外,仅在以下两个用例中需要该值: 1) 在 `ServletContext` 中注册了2个或更多 `HttpServlet`,它们的映射以 `/` 开头并且不同.
2) 模式以已注册 `HttpServlet` 路径的相同值开头,但不包括默认 (根)  `HttpServlet` `'/'`.


NOTE: 此属性对于<<nsa-filter-security-metadata-source,filter-security-metadata-source>>无效


[[nsa-jee]]
==== <jee>
将J2eePreAuthenticatedProcessingFilter添加到过滤器链以提供与容器身份验证的集成.


[[nsa-jee-parents]]
=====  <jee> 的父元素


* <<nsa-http,http>>



[[nsa-jee-attributes]]
===== <jee> 属性


[[nsa-jee-mappable-roles]]
* **mappable-roles**
在传入的HttpServletRequest中寻找的角色的逗号分隔列表.


[[nsa-jee-user-service-ref]]
* **user-service-ref**
对用户服务 (或UserDetailsService bean) ID的引用


[[nsa-logout]]
==== <logout>
将 `LogoutFilter` 添加到过滤器堆栈. 这是使用 `SecurityContextLogoutHandler` 配置的.

[[nsa-logout-parents]]
=====  <logout> 的父元素


* <<nsa-http,http>>



[[nsa-logout-attributes]]
===== <logout> 属性


[[nsa-logout-delete-cookies]]
* **delete-cookies**
Cookie的名称的逗号分隔列表,当用户注销时应删除.


[[nsa-logout-invalidate-session]]
* **invalidate-session**
映射到 `SecurityContextLogoutHandler` 的 `invalidateHttpSession`. 默认为 "true",因此会话将在注销时失效.

[[nsa-logout-logout-success-url]]
* **logout-success-url**
用户注销后将被带到的目标URL.  默认为 `<form-login-login-page>/?logout` (即 `/login?logout`)

+

设置此属性将注入配置有属性值的 `SimpleRedirectInvalidSessionStrategy` 的 `SessionManagementFilter`.  提交无效的会话ID后,将调用该策略,并重定向到配置的URL.


[[nsa-logout-logout-url]]
* **logout-url**
导致注销的网址 (即由过滤器处理的网址) .  默认为 "/logout".

[[nsa-logout-success-handler-ref]]
* **success-handler-ref**
可用于提供 `LogoutSuccessHandler` 的实例,注销后将调用该实例来控制导航.

[[nsa-openid-login]]
==== <openid-login>
与 `<form-login>` 相似,并且具有相同的属性.  `login-processing-url` 的默认值为 "/login/openid".  将注册一个 `OpenIDAuthenticationFilter` 和 `OpenIDAuthenticationProvider`.  后者需要对 `UserDetailsService` 的引用.
同样,可以使用 `user-service-ref` 属性由 `id` 指定,或者将其自动定位在应用程序上下文中.

[[nsa-openid-login-parents]]
=====  <openid-login> 的父元素


* <<nsa-http,http>>



[[nsa-openid-login-attributes]]
===== <openid-login> 属性


[[nsa-openid-login-always-use-default-target]]
* **always-use-default-target**
登录后是否应始终将用户重定向到default-target-url.


[[nsa-openid-login-authentication-details-source-ref]]
* **authentication-details-source-ref**
对将由身份验证过滤器使用的AuthenticationDetailsSource的引用


[[nsa-openid-login-authentication-failure-handler-ref]]
* **authentication-failure-handler-ref**
对AuthenticationFailureHandler bean的引用,该bean应该用于处理失败的身份验证请求.  不应与authentication-failure-url结合使用,因为实现应始终处理到后续目标的导航


[[nsa-openid-login-authentication-failure-url]]
* **authentication-failure-url**
登录失败页面的URL. 如果未指定登录失败URL,Spring Security将在/ login?login_error处自动创建一个失败登录URL,并创建一个相应的过滤器以在请求时呈现该登录失败URL.


[[nsa-openid-login-authentication-success-forward-url]]
* **authentication-success-forward-url**
将 `ForwardAuthenticationSuccessHandler` 映射到 `UsernamePasswordAuthenticationFilter` 的 `authenticationSuccessHandler` 属性.

[[nsa-openid-login-authentication-failure-forward-url]]
* **authentication-failure-forward-url**
将 `ForwardAuthenticationFailureHandler` 映射到 `UsernamePasswordAuthenticationFilter` 的 `authenticationFailureHandler` 属性.

[[nsa-openid-login-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
引用AuthenticationSuccessHandler bean,应将其用于处理成功的身份验证请求.  不应与<<nsa-openid-login-default-target-url,default-target-url>> (或<<nsa-openid-login-always-use-default-target, always-use-default-target>>) 结合使用,因为实现应始终处理到后续目标的导航

[[nsa-openid-login-default-target-url]]
* **default-target-url**
如果无法恢复用户的先前操作,则在成功认证后将重定向到的URL.  如果用户在未先请求触发身份验证的安全操作的情况下访问登录页面,通常会发生这种情况.  如果未指定,则默认为应用程序的根目录.


[[nsa-openid-login-login-page]]
* **login-page**
登录页面的URL.  如果未指定登录URL,Spring Security将在 `/login` 自动创建一个登录URL,并在请求时自动创建一个相应的过滤器来呈现该登录URL.


[[nsa-openid-login-login-processing-url]]
* **login-processing-url**
登录表单发布到的URL. 如果未指定,则默认为 /login.


[[nsa-openid-login-password-parameter]]
* **password-parameter**
包含密码的请求参数的名称. 默认为 "password".


[[nsa-openid-login-user-service-ref]]
* **user-service-ref**
对用户服务 (或UserDetailsService bean) ID的引用


[[nsa-openid-login-username-parameter]]
* **username-parameter**
包含用户名的请求参数的名称. 默认为 "username".


[[nsa-openid-login-children]]
=====  <openid-login> 的子元素
* <<nsa-attribute-exchange,attribute-exchange>>



[[nsa-attribute-exchange]]
==== <attribute-exchange>
`attribute-exchange` 元素定义应从身份提供者请求的属性列表.  可以在命名空间配置一章的<<servlet-openid,OpenID Support>>部分中找到一个示例.  可以使用多个,在这种情况下,每个必须具有 `identifier-match` 属性,其中包含与提供的OpenID标识符匹配的正则表达式.  这允许从不同的提供程序 (Google,Yahoo等) 获取不同的属性列表.

[[nsa-attribute-exchange-parents]]
=====  <attribute-exchange> 的父元素


* <<nsa-openid-login,openid-login>>



[[nsa-attribute-exchange-attributes]]
===== <attribute-exchange> 属性


[[nsa-attribute-exchange-identifier-match]]
* **identifier-match**
确定在身份验证期间使用哪种属性交换配置时,将与所声明的身份进行比较的正则表达式.


[[nsa-attribute-exchange-children]]
=====  <attribute-exchange> 的子元素


* <<nsa-openid-attribute,openid-attribute>>



[[nsa-openid-attribute]]
==== <openid-attribute>
发出OpenID AX https://openid.net/specs/openid-attribute-exchange-1_0.html#fetch_request[ Fetch Request] 时使用的属性

[[nsa-openid-attribute-parents]]
=====  <openid-attribute> 的父元素


* <<nsa-attribute-exchange,attribute-exchange>>



[[nsa-openid-attribute-attributes]]
===== <openid-attribute> 属性


[[nsa-openid-attribute-count]]
* **count**
指定希望获取的属性数量. 例如,返回3封电子邮件. 预设值为1


[[nsa-openid-attribute-name]]
* **name**
指定要获取的属性的名称. 例如,电子邮件.


[[nsa-openid-attribute-required]]
* **required**
指定该属性是否是OP所必需的,但如果OP不返回该属性,则不会出错. 默认为false.


[[nsa-openid-attribute-type]]
* **type**
指定属性类型. 例如, https://axschema.org/contact/email. 有关有效属性类型,请参见您的OP文档.

[[nsa-port-mappings]]
==== <port-mappings>
默认情况下,会将 `PortMapperImpl` 的实例添加到配置中,以用于重定向到安全和不安全的URL.  可以选择使用此元素来覆盖该类定义的默认映射.  每个子 `<port-mapping>` 元素都定义一对HTTP: HTTPS端口.  默认映射为80: 443和8080: 8443.  在 <<servlet-http-redirect>> 中可以找到覆盖这些示例.

[[nsa-port-mappings-parents]]
=====  <port-mappings> 的父元素


* <<nsa-http,http>>



[[nsa-port-mappings-children]]
=====  <port-mappings> 的子元素


* <<nsa-port-mapping,port-mapping>>



[[nsa-port-mapping]]
==== <port-mapping>
提供一种在强制重定向时将http端口映射到https端口的方法.


[[nsa-port-mapping-parents]]
=====  <port-mapping> 的父元素


* <<nsa-port-mappings,port-mappings>>



[[nsa-port-mapping-attributes]]
===== <port-mapping> 属性


[[nsa-port-mapping-http]]
* **http**
要使用的http端口.


[[nsa-port-mapping-https]]
* **https**
要使用的https端口.


[[nsa-remember-me]]
==== <remember-me>
将 `RememberMeAuthenticationFilter` 添加到堆栈中.  反过来,将根据属性设置,使用 `TokenBasedRememberMeServices`,`PersistentTokenBasedRememberMeServices` 或由用户指定的实现 `RememberMeServices` 的bean进行配置.

[[nsa-remember-me-parents]]
=====  <remember-me> 的父元素


* <<nsa-http,http>>



[[nsa-remember-me-attributes]]
===== <remember-me> 属性


[[nsa-remember-me-authentication-success-handler-ref]]
* **authentication-success-handler-ref**
如果需要自定义导航,则在 `RememberMeAuthenticationFilter` 上设置 `authenticationSuccessHandler` 属性. 该值应该是应用程序上下文中 `AuthenticationSuccessHandler` bean的名称.

[[nsa-remember-me-data-source-ref]]
* **data-source-ref**
对 `DataSource` bean的引用. 如果设置此选项,将使用 `PersistentTokenBasedRememberMeServices` 并通过 `JdbcTokenRepositoryImpl` 实例进行配置.

[[nsa-remember-me-remember-me-parameter]]
* **remember-me-parameter**
切换 "记住我" 身份验证的请求参数的名称. 默认为 "remember-me". 映射到 `AbstractRememberMeServices` 的 "parameter" 属性.

[[nsa-remember-me-remember-me-cookie]]
* **remember-me-cookie**
存储用于记住我身份验证的令牌的cookie的名称. 默认为 "remember-me". 映射到 `AbstractRememberMeServices` 的 "cookieName" 属性.


[[nsa-remember-me-key]]
* **key**
映射到 `AbstractRememberMeServices` 的 "key" 属性.  应将其设置为唯一值,以确保 "记住我的Cookie" 仅在一个应用程序中有效footnote:[这不会影响 `PersistentTokenBasedRememberMeServices` 的使用,因为令牌存储在服务器端. ].  如果未设置,将生成一个安全的随机值.
由于生成安全的随机值可能需要一段时间,因此,在使用 "记住我" 功能时,显式设置该值有助于缩短启动时间.

[[nsa-remember-me-services-alias]]
* **services-alias**
将内部定义的 `RememberMeServices` 导出为bean别名,从而允许应用程序上下文中的其他bean使用它.


[[nsa-remember-me-services-ref]]
* **services-ref**
允许完全控制过滤器将使用的 `RememberMeServices` 实现.  该值应该是实现此接口的应用程序上下文中的bean的 `ID`.  如果正在使用注销过滤器,则还应该实现 `LogoutHandler`.

[[nsa-remember-me-token-repository-ref]]
* **token-repository-ref**
`PersistentTokenBasedRememberMeServices`,但允许使用自定义 `PersistentTokenRepository` bean.

[[nsa-remember-me-token-validity-seconds]]
* **token-validity-seconds**
映射到 `AbstractRememberMeServices` 的 `tokenValiditySeconds` 属性. 指定记住我的cookie有效的时间段 (以秒为单位) . 默认情况下,有效期为14天.

[[nsa-remember-me-use-secure-cookie]]
* **use-secure-cookie**
建议记住我的cookie仅通过HTTPS提交,因此应将其标记为 "安全".  默认情况下,如果发出登录请求的连接是安全的 (应该如此) ,则将使用安全cookie.  如果将此属性设置为 `false`,将不使用安全cookie.  将其设置为 `true` 将始终在cookie上设置安全标志.  此属性映射到 `AbstractRememberMeServices` 的 `useSecureCookie` 属性.


[[nsa-remember-me-user-service-ref]]
* **user-service-ref**
"记住我" 服务实现要求访问 `UserDetailsService`,因此在应用程序上下文中必须定义一个.  如果只有一个,它将由命名空间配置自动选择和使用.  如果有多个实例,则可以使用此属性显式指定bean `ID`.


[[nsa-request-cache]]
==== <request-cache> 元素
设置 `RequestCache` 实例,在调用 `AuthenticationEntryPoint` 之前,`ExceptionTranslationFilter` 将使用该实例存储请求信息.

[[nsa-request-cache-parents]]
=====  <request-cache> 的父元素

* <<nsa-http,http>>

[[nsa-request-cache-attributes]]
===== <request-cache> 属性


[[nsa-request-cache-ref]]
* **ref**
定义对作为 `RequestCache` 的Spring bean的引用.


[[nsa-session-management]]
==== <session-management>
与会话管理相关的功能是通过在过滤器堆栈中添加 `SessionManagementFilter` 来实现的.

[[nsa-session-management-parents]]
=====  <session-management> 的父元素


* <<nsa-http,http>>



[[nsa-session-management-attributes]]
===== <session-management> 属性


[[nsa-session-management-invalid-session-url]]
* **invalid-session-url**
设置此属性将注入配置有属性值的 `SimpleRedirectInvalidSessionStrategy` 的 `SessionManagementFilter`. 提交无效的会话ID后,将调用该策略,并重定向到配置的URL.

[[nsa-session-management-invalid-session-strategy-ref]]
* **invalid-session-url**
允许注入由 `SessionManagementFilter` 使用的 `InvalidSessionStrategy` 实例. 使用此属性或 `invalid-session-url` 属性,但不能同时使用.

[[nsa-session-management-session-authentication-error-url]]
* **session-authentication-error-url**

定义错误页面的URL,当SessionAuthenticationStrategy引发异常时应显示该页面.  如果未设置,则将未经授权的 (401) 错误代码返回给客户端.  请注意,如果在基于表单的登录过程中发生错误,则该属性将不适用,在该表单中,身份验证失败的URL将优先.

[[nsa-session-management-session-authentication-strategy-ref]]
* **session-authentication-strategy-ref**
允许注入由SessionManagementFilter使用的SessionAuthenticationStrategy实例


[[nsa-session-management-session-fixation-protection]]
* **session-fixation-protection**

指示用户认证时如何应用会话固定保护.  如果设置为 "none",则不会应用任何保护.  "newSession" 将创建一个新的空会话,仅迁移与Spring Security相关的属性.  "migrateSession" 将创建一个新会话并将所有会话属性复制到新会话.
在Servlet 3.1 (Java EE 7) 和更高版本的容器中,指定 "changeSessionId" 将保留现有会话并使用容器提供的会话固定保护 (`HttpServletRequest#changeSessionId()`) .  在Servlet 3.1和更高版本的容器中,默认值为 "changeSessionId"; 在较旧的容器中,
默认值为 "migrateSession".  如果在较旧的容器中使用 "changeSessionId",则抛出异常.

+

如果启用了会话固定保护,则会向 `SessionManagementFilter` 注入适当配置的 `DefaultSessionAuthenticationStrategy`.  有关更多详细信息,请参见此类的Javadoc.

[[nsa-session-management-children]]
=====  <session-management> 的子元素


* <<nsa-concurrency-control,concurrency-control>>



[[nsa-concurrency-control]]
==== <concurrency-control>
增加了对并发会话控制的支持,从而可以限制用户可以拥有的 active 会话的数量.  将创建一个 `ConcurrentSessionFilter`,并将 `ConcurrentSessionControlAuthenticationStrategy` 与 `SessionManagementFilter` 一起使用.  如果声明了 `form-login` 元素,则策略对象也将注入到创建的身份验证过滤器中.  将创建一个 `SessionRegistry` 实例 (除非用户希望使用自定义bean,否则将为 `SessionRegistryImpl` 实例) 供该策略使用.

[[nsa-concurrency-control-parents]]
=====  <concurrency-control> 的父元素


* <<nsa-session-management,session-management>>



[[nsa-concurrency-control-attributes]]
===== <concurrency-control> 属性


[[nsa-concurrency-control-error-if-maximum-exceeded]]
* **error-if-maximum-exceeded**
如果设置为 "true",则当用户尝试超过允许的最大会话数时,将引发 `SessionAuthenticationException`. 默认行为是使原始会话到期.


[[nsa-concurrency-control-expired-url]]
* **expired-url**
如果用户尝试使用并发会话控制器已 "过期" 的会话,则该用户将被重定向到该URL,因为该用户已超过允许的会话数,并已在其他位置再次登录.  除非设置了 `if-if-maximum-exceeded`,否则应设置.  如果未提供任何值,则到期消息将直接写回到响应中.

[[nsa-concurrency-control-expired-session-strategy-ref]]
* **expired-url**
允许注入ConcurrentSessionFilter使用的ExpiredSessionStrategy实例

[[nsa-concurrency-control-max-sessions]]
* **max-sessions**
映射到 `ConcurrentSessionControlAuthenticationStrategy` 的 `maximumSessions` 属性. 指定 `-1` 作为支持无限会话的值.


[[nsa-concurrency-control-session-registry-alias]]
* **session-registry-alias**
引用内部会话注册表以在自己的bean或管理界面中使用也很有用.  您可以使用 `session-registry-alias` 属性暴露内部bean,为其提供一个名称,您可以在配置中的其他位置使用它.

[[nsa-concurrency-control-session-registry-ref]]
* **session-registry-ref**
用户可以使用 `session-registry-ref` 属性提供自己的 `SessionRegistry` 实现.  其他并发会话控制bean将被连接起来以使用它.

[[nsa-x509]]
==== <x509>
添加了对X.509身份验证的支持.  `X509AuthenticationFilter` 将添加到堆栈中,并将创建 `Http403ForbiddenEntryPoint` bean.  仅当不使用其他身份验证机制时才使用后者 (它的唯一功能是返回HTTP 403错误代码) .
还将创建一个 `PreAuthenticatedAuthenticationProvider`,它将用户权限的加载委派给 `UserDetailsService`.

[[nsa-x509-parents]]
=====  <x509> 的父元素


* <<nsa-http,http>>



[[nsa-x509-attributes]]
===== <x509> 属性


[[nsa-x509-authentication-details-source-ref]]
* **authentication-details-source-ref**
对 `AuthenticationDetailsSource` 的引用


[[nsa-x509-subject-principal-regex]]
* **subject-principal-regex**
定义一个正则表达式,该正则表达式将用于从证书中提取用户名 (与 `UserDetailsService` 一起使用) .

[[nsa-x509-user-service-ref]]
* **user-service-ref**
如果配置了多个实例,则允许特定的 `UserDetailsService` 与X.509一起使用. 如果未设置,将尝试自动查找并使用合适的实例.

[[nsa-filter-chain-map]]
==== <filter-chain-map>
用于通过FilterChainMap显式配置FilterChainProxy实例


[[nsa-filter-chain-map-attributes]]
===== <filter-chain-map> 属性


[[nsa-filter-chain-map-request-matcher]]
* **request-matcher**
定义用于匹配传入请求的策略. 当前,选项为 `ant` (用于ant路径模式) ,`regex` 用于正则表达式,`ciRegex` 用于不区分大小写的正则表达式.

[[nsa-filter-chain-map-children]]
=====  <filter-chain-map> 的子元素


* <<nsa-filter-chain,filter-chain>>



[[nsa-filter-chain]]
==== <filter-chain>
用于内部以定义特定的URL模式以及适用于与该模式匹配的URL的过滤器列表.  当在列表中组合多个过滤器链元素以配置FilterChainProxy时,最特定的模式必须放在列表的顶部,最普通的模式应放在底部.


[[nsa-filter-chain-parents]]
=====  <filter-chain> 的父元素


* <<nsa-filter-chain-map,filter-chain-map>>



[[nsa-filter-chain-attributes]]
===== <filter-chain> 属性


[[nsa-filter-chain-filters]]
* **filters**
以逗号分隔的实现过滤器的Spring bean引用列表. 值 "none" 表示此 `FilterChain` 不应使用任何过滤器.

[[nsa-filter-chain-pattern]]
* **pattern**
一种与<<nsa-filter-chain-map-request-matcher,request-matcher>>r结合创建RequestMatcher的模式

[[nsa-filter-chain-request-matcher-ref]]
* **request-matcher-ref**
对 `RequestMatcher` 的引用,该引用将用于确定是否应调用 `filter` 属性中的任何 `Filter`.

[[nsa-filter-security-metadata-source]]
==== <filter-security-metadata-source>
用于显式配置FilterSecurityMetadataSource bean与FilterSecurityInterceptor一起使用.  通常仅在显式配置FilterChainProxy而不是使用<http>元素时才需要.  使用的拦截URL元素应仅包含模式,方法和访问属性.  其他任何情况都将导致配置错误.

[[nsa-filter-security-metadata-source-attributes]]
===== <filter-security-metadata-source> 属性


[[nsa-filter-security-metadata-source-id]]
* **id**
Bean标识符,用于引用上下文中其他位置的Bean.


[[nsa-filter-security-metadata-source-request-matcher]]
* **request-matcher**
定义用于匹配传入请求的策略. 当前,选项为 `ant` (用于ant路径模式) ,`regex` 用于正则表达式,`ciRegex` 用于不区分大小写的正则表达式.


[[nsa-filter-security-metadata-source-use-expressions]]
* **use-expressions**
允许在<intercept-url>元素的 `access` 属性中使用表达式,而不是传统的配置属性列表.  默认为 `true`.  如果启用,则每个属性应包含一个布尔表达式.  如果表达式的计算结果为 `true`,则将授予访问权限.

[[nsa-filter-security-metadata-source-children]]
=====  <filter-security-metadata-source> 的子元素


* <<nsa-intercept-url,intercept-url>>

[[nsa-websocket-security]]
=== WebSocket Security

Spring Security 4.0+提供了对消息授权的支持. 一个有用的具体示例是在基于WebSocket的应用程序中提供授权.

[[nsa-websocket-message-broker]]
==== <websocket-message-broker>

websocket-message-broker元素具有两种不同的模式. 如果未指定<<nsa-websocket-message-broker-id,websocket-message-broker@id>>,则它将执行以下操作:

* 确保任何SimpAnnotationMethodMessageHandler都将AuthenticationPrincipalArgumentResolver注册为自定义参数解析器.  这允许使用 `@AuthenticationPrincipal` 来解析当前 `Authentication` 的主体
* 确保已为clientInboundChannel自动注册SecurityContextChannelInterceptor.  这将使用Message中找到的用户填充SecurityContextHolder
* 确保ChannelSecurityInterceptor已向clientInboundChannel注册.  这允许为消息指定授权规则.
* 确保CsrfChannelInterceptor已在clientInboundChannel中注册.  这样可以确保仅启用来自原始域的请求.
* 确保已向WebSocketHttpRequestHandler,TransportHandlingSockJsService或DefaultSockJsService注册CsrfTokenHandshakeInterceptor.  这样可以确保将来自HttpServletRequest的预期CsrfToken复制到WebSocket会话属性中.

如果需要其他控制,则可以指定ID,并将ChannelSecurityInterceptor分配给指定的ID.  然后,可以手动完成与Spring的消息传递基础结构的所有连接.  这比较麻烦,但是可以更好地控制配置.


[[nsa-websocket-message-broker-attributes]]
===== <websocket-message-broker> 属性

[[nsa-websocket-message-broker-id]]
* **id** Bean标识符,用于在上下文中的其他地方引用 `ChannelSecurityInterceptor` Bean.  如果指定,Spring Security需要在Spring Messaging中进行显式配置.  如果未指定,Spring Security将自动与消息传递基础结构集成,如<<nsa-websocket-message-broker>>部分中所述

[[nsa-websocket-message-broker-same-origin-disabled]]
* **same-origin-disabled** D禁用Stomp header 中必须存在CSRF令牌的要求 (默认为false) . 如果需要允许其他来源建立SockJS连接,则更改默认值很有用.

[[nsa-websocket-message-broker-children]]
=====  <websocket-message-broker> 的子元素


* <<nsa-expression-handler,expression-handler>>
* <<nsa-intercept-message,intercept-message>>

[[nsa-intercept-message]]
==== <intercept-message>

定义消息的授权规则.


[[nsa-intercept-message-parents]]
=====  <intercept-message> 的父元素


* <<nsa-websocket-message-broker,websocket-message-broker>>


[[nsa-intercept-message-attributes]]
===== <intercept-message> 属性

[[nsa-intercept-message-pattern]]
* **pattern** 在消息目标上匹配的基于 Ant 的模式. 例如,"/" 将任何消息与目标匹配;  "/admin/" 与目标以 "/admin/**" 开头的任何邮件匹配.

[[nsa-intercept-message-type]]
* **type** 要匹配的消息类型. 有效值在SimpMessageType中定义 (即CONNECT,CONNECT_ACK,HEARTBEAT,MESSAGE,SUBSCRIBE,UNSUBSCRIBE,DISCONNECT,DISCONNECT_ACK,OTHER) .

[[nsa-intercept-message-access]]
* **access** 用于保护消息的表达式.  例如, "denyAll" 将拒绝访问所有匹配的消息;  "permitAll" 将授予对所有匹配消息的访问权限;  "hasRole('ADMIN') 要求当前用户具有匹配消息的角色 'ROLE_ADMIN'.

[[nsa-authentication]]
=== Authentication Services
在Spring Security 3.0之前,`AuthenticationManager` 是在内部自动注册的.  现在,您必须使用 `<authentication-manager>` 元素显式注册一个.  这将创建Spring Security的 `ProviderManager` 类的实例,该实例需要配置一个或多个 `AuthenticationProvider` 实例的列表.
这些可以使用命名空间提供的语法元素创建,也可以是标准bean定义,并使用 `authentication-provider` 元素标记为添加到列表中.


[[nsa-authentication-manager]]
==== <authentication-manager>

每个使用命名空间的Spring Security应用程序都必须在某处包含此元素.  它负责注册为应用程序提供身份验证服务的 `AuthenticationManager`.  创建 `AuthenticationProvider` 实例的所有元素都应该是该元素的子级.

[[nsa-authentication-manager-attributes]]
===== <authentication-manager> 属性


[[nsa-authentication-manager-alias]]
* **alias**
此属性使您可以定义内部实例的别名,以在您自己的配置中使用.

[[nsa-authentication-manager-erase-credentials]]
* **erase-credentials**

如果设置为true,则在验证用户身份之后,`AuthenticationManager` 将尝试清除返回的Authentication对象中的所有凭据数据.  从字面上看,它映射到 <<servlet-authentication-providermanager,`ProviderManager`>> 的 `eraseCredentialsAfterAuthentication` 属性.

[[nsa-authentication-manager-id]]
* **id**
此属性允许您定义内部实例的ID,以在您自己的配置中使用. 它与alias元素相同,但是使用id属性的元素提供了更一致的体验.


[[nsa-authentication-manager-children]]
=====  <authentication-manager> 的子元素


* <<nsa-authentication-provider,authentication-provider>>
* <<nsa-ldap-authentication-provider,ldap-authentication-provider>>



[[nsa-authentication-provider]]
==== <authentication-provider>
除非与 `ref` 属性一起使用,否则此元素是配置 `DaoAuthenticationProvider` 的简写.  `DaoAuthenticationProvider` 从 `UserDetailsService` 加载用户信息,并将用户名/密码组合与登录时提供的值进行比较.
可以通过使用可用的命名空间元素 (`jdbc-user-service` 或通过使用 `user-service-ref` 属性指向应用程序上下文中其他位置定义的bean) 来定义 `UserDetailsService` 实例.

[[nsa-authentication-provider-parents]]
=====  <authentication-provider> 的父元素


* <<nsa-authentication-manager,authentication-manager>>



[[nsa-authentication-provider-attributes]]
===== <authentication-provider> 属性


[[nsa-authentication-provider-ref]]
* **ref**
定义对实现 `AuthenticationProvider` 的Spring bean的引用.

如果您已经编写了自己的 `AuthenticationProvider` 实现 (或者出于某种原因想要将Spring Security自己的实现之一配置为传统Bean,则可以使用以下语法将其添加到 `ProviderManager` 的内部列表中:

[source,xml]
----

<security:authentication-manager>
<security:authentication-provider ref="myAuthenticationProvider" />
</security:authentication-manager>
<bean id="myAuthenticationProvider" class="com.something.MyAuthenticationProvider"/>

----




[[nsa-authentication-provider-user-service-ref]]
* **user-service-ref**
对实现UserDetailsService的bean的引用,该UserDetailsService可以使用标准bean元素或自定义user-service元素创建.


[[nsa-authentication-provider-children]]
=====  <authentication-provider> 的子元素


* <<nsa-jdbc-user-service,jdbc-user-service>>
* <<nsa-ldap-user-service,ldap-user-service>>
* <<nsa-password-encoder,password-encoder>>
* <<nsa-user-service,user-service>>



[[nsa-jdbc-user-service]]
==== <jdbc-user-service>
导致创建基于JDBC的UserDetailsService.


[[nsa-jdbc-user-service-attributes]]
===== <jdbc-user-service> 属性


[[nsa-jdbc-user-service-authorities-by-username-query]]
* **authorities-by-username-query**
用于查询给定用户名的用户授予权限的SQL语句.

默认是

[source]
----
select username, authority from authorities where username = ?
----




[[nsa-jdbc-user-service-cache-ref]]
* **cache-ref**
定义对与UserDetailsService一起使用的缓存的引用.


[[nsa-jdbc-user-service-data-source-ref]]
* **data-source-ref**
提供所需表的数据源的Bean ID.


[[nsa-jdbc-user-service-group-authorities-by-username-query]]
* **group-authorities-by-username-query**
给定用户名的SQL语句,用于查询用户的组权限. 默认是

+

[source]
----
select
g.id, g.group_name, ga.authority
from
groups g, group_members gm, group_authorities ga
where
gm.username = ? and g.id = ga.group_id and g.id = gm.group_id
----




[[nsa-jdbc-user-service-id]]
* **id**
Bean标识符,用于引用上下文中其他位置的Bean.


[[nsa-jdbc-user-service-role-prefix]]
* **role-prefix**
一个非空字符串前缀,将添加到从持久性存储加载的角色字符串中 (默认为 "ROLE_") . 在默认为非空的情况下,将值 "none" 用于无前缀.


[[nsa-jdbc-user-service-users-by-username-query]]
* **users-by-username-query**
用于查询用户名,密码和给定用户名的启用状态的SQL语句. 默认是

+

[source]
----
select username, password, enabled from users where username = ?
----




[[nsa-password-encoder]]
==== <password-encoder>
如<<authentication-password-storage>>中所述,可以选择将身份验证提供程序配置为使用密码编码器. 这将导致使用适当的 `PasswordEncoder` 实例注入Bean.

[[nsa-password-encoder-parents]]
=====  <password-encoder> 的父元素


* <<nsa-authentication-provider,authentication-provider>>
* <<nsa-password-compare,password-compare>>



[[nsa-password-encoder-attributes]]
===== <password-encoder> 属性


[[nsa-password-encoder-hash]]
* **hash**
定义用于用户密码的哈希算法. 我们强烈建议您不要使用MD4,因为它是一种非常弱的哈希算法.


[[nsa-password-encoder-ref]]
* **ref**
定义对实现 `PasswordEncoder` 的Spring bean的引用.


[[nsa-user-service]]
==== <user-service>
从属性文件或 "user"  子元素列表创建内存UserDetailsService. 用户名在内部会转换为小写形式,以允许不区分大小写的查找,因此如果需要区分大小写,则不应使用此名称.

[[nsa-user-service-attributes]]
===== <user-service> 属性


[[nsa-user-service-id]]
* **id**
Bean标识符,用于引用上下文中其他位置的Bean.


[[nsa-user-service-properties]]
* **properties**
属性文件的位置,其中每一行的格式为

+

[source]
----
username=password,grantedAuthority[,grantedAuthority][,enabled|disabled]
----




[[nsa-user-service-children]]
=====  <user-service> 的子元素


* <<nsa-user,user>>



[[nsa-user]]
==== <user>
代表应用程序中的用户.


[[nsa-user-parents]]
=====  <user> 的父元素


* <<nsa-user-service,user-service>>



[[nsa-user-attributes]]
===== <user> 属性


[[nsa-user-authorities]]
* **authorities**
授予用户的其他权限之一. 用逗号隔开 (但不能有空格) . 例如, "ROLE_USER,ROLE_ADMINISTRATOR"

[[nsa-user-disabled]]
* **disabled**
可以设置为 "true" 以将帐户标记为禁用和不可用.


[[nsa-user-locked]]
* **locked**
可以设置为 "true" 以将帐户标记为已锁定且无法使用.


[[nsa-user-name]]
* **name**
分配给用户的用户名.


[[nsa-user-password]]
* **password**
分配给用户的密码.  如果相应的身份验证提供程序支持哈希 (请记住要设置"user-service" 元素的 "hash" 属性) ,则可以对此进行哈希处理.  在数据将不用于认证而仅用于访问权限的情况下,将忽略此属性.  如果省略,则命名空间将生成一个随机值,以防止其偶然用于身份验证.  不能为空. .

[[nsa-method-security]]
=== Method Security


[[nsa-global-method-security]]
==== <global-method-security>
该元素是添加对Spring Security bean上的安全方法的支持的主要方法.  可以使用AspectJ语法通过使用注解 (在接口或类级别定义) 或将一组切入点定义为子元素来保护方法.


[[nsa-global-method-security-attributes]]
===== <global-method-security> 属性


[[nsa-global-method-security-access-decision-manager-ref]]
* **access-decision-manager-ref**
方法安全性使用与Web安全性相同的 `AccessDecisionManager` 配置,但是可以使用此属性来覆盖此方法. 默认情况下,`AffirmativeBased` 实现用于 `RoleVoter` 和 `AuthenticatedVoter`.

[[nsa-global-method-security-authentication-manager-ref]]
* **authentication-manager-ref**
对用于方法安全性的 `AuthenticationManager` 的引用.


[[nsa-global-method-security-jsr250-annotations]]
* **jsr250-annotations**
指定是否使用JSR-250样式属性 (例如  "RolesAllowed") .  这将需要classpath上的 `javax.annotation.security` 类.  将其设置为true还会向 `AccessDecisionManager` 中添加一个 `Jsr250Voter`,因此如果您正在使用自定义实现并希望使用这些注解,则需要确保执行此操作.

[[nsa-global-method-security-metadata-source-ref]]
* **metadata-source-ref**
可以提供一个外部 `MethodSecurityMetadataSource` 实例,该实例的优先级高于其他源 (例如默认注解) .

[[nsa-global-method-security-mode]]
* **mode**
可以将此属性设置为 "aspectj" ,以指定应使用AspectJ代替默认的Spring AOP. 必须使用 `spring-security-aspects` 模块中的 `AnnotationSecurityAspect` 来编织安全方法.

需要特别注意的是,AspectJ遵循Java的规则,即不继承接口上的注解.  这意味着在接口上定义安全性注解的方法将不安全.  相反,在使用AspectJ时,必须在类上放置Security注解.


[[nsa-global-method-security-order]]
* **order**
允许为方法安全性拦截器设置建议 "顺序".


[[nsa-global-method-security-pre-post-annotations]]
* **pre-post-annotations**
指定是否应为此应用程序上下文启用对Spring Security的调用前后注解的使用 (@PreFilter, @PreAuthorize, @PostFilter, @PostAuthorize) . 默认为 "disabled".

[[nsa-global-method-security-proxy-target-class]]
* **proxy-target-class**
如果为true,则将使用基于类的代理而不是基于接口的代理.


[[nsa-global-method-security-run-as-manager-ref]]
* **run-as-manager-ref**
对可选 `RunAsManager` 实现的引用,将由配置的 `MethodSecurityInterceptor` 使用


[[nsa-global-method-security-secured-annotations]]
* **secured-annotations**
指定是否为此应用程序上下文启用Spring Security的 `@Secured` 注解. 默认为 "disabled".


[[nsa-global-method-security-children]]
=====  <global-method-security> 的子元素


* <<nsa-after-invocation-provider,after-invocation-provider>>
* <<nsa-expression-handler,expression-handler>>
* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>
* <<nsa-protect-pointcut,protect-pointcut>>



[[nsa-after-invocation-provider]]
==== <after-invocation-provider>

此元素可用于装饰 `AfterInvocationProvider`,以供 `<global-method-security>` 命名空间维护的安全拦截器使用.  您可以在 `global-method-security` 元素中定义零个或多个元素,每个元素的 `ref` 属性均指向应用程序上下文中的 `AfterInvocationProvider` bean实例.

[[nsa-after-invocation-provider-parents]]
=====  <after-invocation-provider> 的父元素


* <<nsa-global-method-security,global-method-security>>



[[nsa-after-invocation-provider-attributes]]
===== <after-invocation-provider> 属性


[[nsa-after-invocation-provider-ref]]
* **ref**
定义对实现 `AfterInvocationProvider` 的Spring bean的引用.


[[nsa-pre-post-annotation-handling]]
==== <pre-post-annotation-handling>
允许完全替换基于默认表达式的机制来处理Spring Security的调用前后注解 ((@PreFilter, @PreAuthorize, @PostFilter, @PostAuthorize) . 仅在启用这些注解的情况下适用.

[[nsa-pre-post-annotation-handling-parents]]
=====  <pre-post-annotation-handling> 的父元素


* <<nsa-global-method-security,global-method-security>>



[[nsa-pre-post-annotation-handling-children]]
=====  <pre-post-annotation-handling> 的子元素


* <<nsa-invocation-attribute-factory,invocation-attribute-factory>>
* <<nsa-post-invocation-advice,post-invocation-advice>>
* <<nsa-pre-invocation-advice,pre-invocation-advice>>



[[nsa-invocation-attribute-factory]]
==== <invocation-attribute-factory>
定义PrePostInvocationAttributeFactory实例,该实例用于从带注解的方法中生成调用前后的元数据.


[[nsa-invocation-attribute-factory-parents]]
=====  <invocation-attribute-factory> 的父元素


* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>



[[nsa-invocation-attribute-factory-attributes]]
===== <invocation-attribute-factory> 属性


[[nsa-invocation-attribute-factory-ref]]
* **ref**
定义对Spring bean ID的引用.


[[nsa-post-invocation-advice]]
==== <post-invocation-advice>
使用 `<pre-post-annotation-handling>` 元素的 `ref` 作为 `PostInvocationAuthorizationAdvice` 自定义 `PostInvocationAdviceProvider`.

[[nsa-post-invocation-advice-parents]]
=====  <post-invocation-advice> 的父元素


* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>



[[nsa-post-invocation-advice-attributes]]
===== <post-invocation-advice> 属性


[[nsa-post-invocation-advice-ref]]
* **ref**
定义对Spring bean ID的引用.


[[nsa-pre-invocation-advice]]
==== <pre-invocation-advice>
使用 `<pre-post-annotation-handling>` 元素的 `ref` 作为 `PreInvocationAuthorizationAdviceVoter` 自定义 `PreInvocationAuthorizationAdviceVoter`.

[[nsa-pre-invocation-advice-parents]]
=====  <pre-invocation-advice> 的父元素


* <<nsa-pre-post-annotation-handling,pre-post-annotation-handling>>



[[nsa-pre-invocation-advice-attributes]]
===== <pre-invocation-advice> 属性


[[nsa-pre-invocation-advice-ref]]
* **ref**
定义对Spring bean ID的引用.


[[nsa-protect-pointcut]]
==== Securing Methods using
`<protect-pointcut>` 可以使用 `<protect-pointcut>` 元素,而不是使用 `@Secured` 注解在单个方法或类的基础上定义安全属性,而可以跨服务层中的整个方法和接口集定义跨领域安全约束.  您可以在<<ns-protect-pointcut,namespace introduction>>找到一个示例.

[[nsa-protect-pointcut-parents]]
=====  <protect-pointcut> 的父元素


* <<nsa-global-method-security,global-method-security>>



[[nsa-protect-pointcut-attributes]]
===== <protect-pointcut> 属性


[[nsa-protect-pointcut-access]]
* **access**
适用于与切入点匹配的所有方法的访问配置属性列表,例如 "ROLE_A,ROLE_B"


[[nsa-protect-pointcut-expression]]
* **expression**
一个 AspectJ 表达式,包括 `execution` 关键字. 例如,`execution(int com.foo.TargetObject.countLength(String))` (不带引号) .

[[nsa-intercept-methods]]
==== <intercept-methods>
可以在Bean定义内使用,以向该Bean添加安全拦截器并为Bean的方法设置访问配置属性


[[nsa-intercept-methods-attributes]]
===== <intercept-methods> 属性


[[nsa-intercept-methods-access-decision-manager-ref]]
* **access-decision-manager-ref**

创建的方法安全拦截器将使用的可选AccessDecisionManager bean ID.


[[nsa-intercept-methods-children]]
=====  <intercept-methods> 的子元素


* <<nsa-protect,protect>>



[[nsa-method-security-metadata-source]]
==== <method-security-metadata-source>
创建一个MethodSecurityMetadataSource实例


[[nsa-method-security-metadata-source-attributes]]
===== <method-security-metadata-source> 属性


[[nsa-method-security-metadata-source-id]]
* **id**
Bean标识符,用于引用上下文中其他位置的Bean.


[[nsa-method-security-metadata-source-use-expressions]]
* **use-expressions**
允许在<intercept-url>元素的 `access` 属性中使用表达式,而不是传统的配置属性列表.  默认为 `false`.  如果启用,则每个属性应包含一个布尔表达式.  如果表达式的计算结果为 "true",则将授予访问权限.

[[nsa-method-security-metadata-source-children]]
=====  <method-security-metadata-source> 的子元素


* <<nsa-protect,protect>>



[[nsa-protect]]
==== <protect>
定义一个受保护的方法以及适用于该方法的访问控制配置属性. 强烈建议您不要将 "保护" 声明与 "global-method-security" 提供的任何服务混合使用.

[[nsa-protect-parents]]
=====  <protect> 的父元素


* <<nsa-intercept-methods,intercept-methods>>
* <<nsa-method-security-metadata-source,method-security-metadata-source>>



[[nsa-protect-attributes]]
===== <protect> 属性


[[nsa-protect-access]]
* **access**
适用于该方法的访问配置属性列表,例如
"ROLE_A,ROLE_B".


[[nsa-protect-method]]
* **method**
方法名


[[nsa-ldap]]
=== LDAP Namespace 选项
LDAP在<<servlet-authentication-ldap,其自己的章节中>>进行了一些详细介绍.  我们将在此扩展它,并提供一些有关命名空间选项如何映射到Spring Bean的解释.  LDAP实施广泛使用Spring LDAP,因此熟悉该项目的API可能会有用.

[[nsa-ldap-server]]
==== Defining the LDAP Server using the
`<ldap-server>` 元素此元素设置一个供其他LDAP Bean使用的Spring LDAP `ContextSource`,用于定义LDAP服务器的位置以及其他信息 (例如用户名和密码,如果不允许匿名访问) 用于 连接到它.
它还可以用于创建嵌入式服务器以进行测试.   <<servlet-authentication-ldap,LDAP一章>>介绍了这两个选项的语法详细信息.  实际的 `ContextSource` 实现是 `DefaultSpringSecurityContextSource`,它扩展了Spring LDAP的 `LdapContextSource` 类.
 `manager-dn` 和 `manager-password` 属性分别映射到后者的 `userDn` 和密码属性.

如果在应用程序上下文中仅定义了一个服务器,则其他LDAP命名空间定义的Bean将自动使用它.  否则,您可以为元素赋予 "id" 属性,并使用 `server-ref` 属性从其他命名空间Bean引用该元素.  如果要在其他传统Spring Bean中使用它,则实际上是 `ContextSource` 实例的Bean ID.

[[nsa-ldap-server-attributes]]
===== <ldap-server> 属性

[[nsa-ldap-server-mode]]
* **mode**
明确指定应使用哪个嵌入式ldap服务器. 值是固定的和无限制的. 默认情况下,将取决于该库在类路径中是否可用.

[[nsa-ldap-server-id]]
* **id**
Bean标识符,用于引用上下文中其他位置的Bean.


[[nsa-ldap-server-ldif]]
* **ldif**
明确指定一个ldif文件资源以加载到嵌入式LDAP服务器中.  ldif 应该是Spring资源模式 (即classpath:init.ldif) .  默认值为classpath*:*.ldif


[[nsa-ldap-server-manager-dn]]
* **manager-dn**
"manager" 用户身份的用户名 (DN) ,将用于向 (非嵌入式) LDAP服务器进行身份验证. 如果省略,将使用匿名访问.

[[nsa-ldap-server-manager-password]]
* **manager-password**
管理员DN的密码. 如果指定了 manager-dn,则这是必需的.


[[nsa-ldap-server-port]]
* **port**
指定IP端口号. 例如,用于配置嵌入式LDAP服务器. 默认值为33389.


[[nsa-ldap-server-root]]
* **root**
嵌入式LDAP服务器的可选根后缀. 默认值为 "dc=springframework,dc=org"

[[nsa-ldap-server-url]]
* **url**
不使用嵌入式LDAP服务器时,指定ldap服务器URL.


[[nsa-ldap-authentication-provider]]
==== <ldap-authentication-provider>
此元素是创建 `LdapAuthenticationProvider` 实例的简写.  默认情况下,它将使用 `BindAuthenticator` 实例和 `DefaultAuthoritiesPopulator` 配置.  与所有命名空间身份验证提供程序一样,必须将其作为 `authentication-provider` 元素的子元素包括在内.

[[nsa-ldap-authentication-provider-parents]]
=====  <ldap-authentication-provider> 的父元素


* <<nsa-authentication-manager,authentication-manager>>



[[nsa-ldap-authentication-provider-attributes]]
===== <ldap-authentication-provider> 属性


[[nsa-ldap-authentication-provider-group-role-attribute]]
* **group-role-attribute**
LDAP属性名称,其中包含将在Spring Security中使用的角色名称. 映射到 `DefaultLdapAuthoritiesPopulator` 的 `groupRoleAttribute` 属性. 默认为 "cn".

[[nsa-ldap-authentication-provider-group-search-base]]
* **group-search-base**
组成员资格搜索的搜索基础. 映射到 `DefaultLdapAuthoritiesPopulator` 的 `groupSearchBase` 构造函数参数. 默认为 "" (从根目录搜索) .


[[nsa-ldap-authentication-provider-group-search-filter]]
* **group-search-filter**
组搜索过滤器. 映射到 `DefaultLdapAuthoritiesPopulator` 的 `groupSearchFilter` 属性. 默认为 ( `+(uniqueMember={0})+` ) . 替换的参数是用户的DN.

[[nsa-ldap-authentication-provider-role-prefix]]
* **role-prefix**
非空字符串前缀,将添加到从持久性加载的角色字符串中. 映射到 `DefaultLdapAuthoritiesPopulator` 的 `rolePrefix` 属性. 默认为 "ROLE_". 在默认为非空的情况下,将值 "none" 用于无前缀.

[[nsa-ldap-authentication-provider-server-ref]]
* **server-ref**
要使用的可选服务器. 如果省略,并且注册了默认的LDAP服务器 (使用没有ID的<ldap-server>) ,则将使用该服务器.


[[nsa-ldap-authentication-provider-user-context-mapper-ref]]
* **user-context-mapper-ref**
通过指定UserDetailsContextMapper bean来对加载的用户对象进行显式定制,该bean将与用户目录条目中的上下文信息一起调用

[[nsa-ldap-authentication-provider-user-details-class]]
* **user-details-class**
允许指定用户条目的objectClass. 如果设置,框架将尝试将已定义类的标准属性加载到返回的UserDetails对象中


[[nsa-ldap-authentication-provider-user-dn-pattern]]
* **user-dn-pattern**
如果您的用户位于目录中的固定位置 (即您可以直接从用户名计算出DN,而无需进行目录搜索) ,则可以使用此属性直接映射到DN.  它直接映射到 `AbstractLdapAuthenticator` 的 `userDnPatterns` 属性.
 该值是用于构建用户DN的特定模式,例如 `+uid={0},ou=people+`.  键  `+{0}+` 必须存在,并将被用户名替换.

[[nsa-ldap-authentication-provider-user-search-base]]
* **user-search-base**
用户搜索的搜索库.  默认为 "".  仅与 `user-search-filter` 一起使用.

+

如果需要执行搜索以在目录中找到用户,则可以设置这些属性来控制搜索.  `BindAuthenticator` 将使用 `FilterBasedLdapUserSearch` 配置,并且属性值直接映射到该bean的构造函数的前两个参数.
如果未设置这些属性,并且未提供任何 `user-dn-pattern` 作为替代,则默认搜索值为 `user-search-filter="(uid={0})"` 和 `user-search-base=""`  将会被使用.

[[nsa-ldap-authentication-provider-user-search-filter]]
* **user-search-filter**

用于搜索用户的LDAP过滤器 (可选) .  例如 "(uid={0})".  替换的参数是用户的登录名.

+

如果需要执行搜索以在目录中找到用户,则可以设置这些属性来控制搜索.  `BindAuthenticator` 将使用 `FilterBasedLdapUserSearch` 配置,并且属性值直接映射到该bean的构造函数的前两个参数.
如果未设置这些属性,并且未提供任何 `user-dn-pattern` 作为替代,则默认搜索值为 `user-search-filter="(uid={0})"` 和 `user-search-base=""` 将会被使用.

[[nsa-ldap-authentication-provider-children]]
=====  <ldap-authentication-provider> 的子元素


* <<nsa-password-compare,password-compare>>



[[nsa-password-compare]]
==== <password-compare>
用作 `<ldap-provider>` 的子元素,并将身份验证策略从 `BindAuthenticator` 切换到 `PasswordComparisonAuthenticator`.


[[nsa-password-compare-parents]]
=====  <password-compare> 的父元素


* <<nsa-ldap-authentication-provider,ldap-authentication-provider>>



[[nsa-password-compare-attributes]]
===== <password-compare> 属性


[[nsa-password-compare-hash]]
* **hash**
定义用于用户密码的哈希算法. 我们强烈建议您不要使用MD4,因为它是一种非常弱的哈希算法.


[[nsa-password-compare-password-attribute]]
* **password-attribute**
目录中包含用户密码的属性. 默认为 "userPassword".


[[nsa-password-compare-children]]
=====  <password-compare> 的子元素


* <<nsa-password-encoder,password-encoder>>



[[nsa-ldap-user-service]]
==== <ldap-user-service>
此元素配置LDAP `UserDetailsService`.  使用的类是 `LdapUserDetailsService`,它是 `FilterBasedLdapUserSearch` 和 `DefaultLdapAuthoritiesPopulator` 的组合.  它支持的属性与 `<ldap-provider>` 中的用法相同.

[[nsa-ldap-user-service-attributes]]
===== <ldap-user-service> 属性


[[nsa-ldap-user-service-cache-ref]]
* **cache-ref**
定义对与UserDetailsService一起使用的缓存的引用.


[[nsa-ldap-user-service-group-role-attribute]]
* **group-role-attribute**
LDAP属性名称,其中包含将在Spring Security中使用的角色名称. 默认为 "cn".


[[nsa-ldap-user-service-group-search-base]]
* **group-search-base**
组成员资格搜索的搜索基础. 默认为 "" (从根目录搜索) .


[[nsa-ldap-user-service-group-search-filter]]
* **group-search-filter**
组搜索过滤器. 默认为 (uniqueMember={0}) . 替换的参数是用户的DN.

[[nsa-ldap-user-service-id]]
* **id**
Bean标识符,用于引用上下文中其他位置的Bean.


[[nsa-ldap-user-service-role-prefix]]
* **role-prefix**
非空字符串前缀,将添加到从持久性存储 (例如 "ROLE_") 加载的角色字符串中. 在默认为非空的情况下,将值 "none" 用于无前缀.

[[nsa-ldap-user-service-server-ref]]
* **server-ref**
要使用的可选服务器. 如果省略,并且注册了默认的LDAP服务器 (使用没有ID的<ldap-server>) ,则将使用该服务器.

[[nsa-ldap-user-service-user-context-mapper-ref]]
* **user-context-mapper-ref**
通过指定UserDetailsContextMapper bean允许显式自定义已加载的用户对象,该bean将与用户目录条目中的上下文信息一起调用

[[nsa-ldap-user-service-user-details-class]]
* **user-details-class**
允许指定用户条目的objectClass. 如果设置,框架将尝试将已定义类的标准属性加载到返回的UserDetails对象中


[[nsa-ldap-user-service-user-search-base]]
* **user-search-base**
用户搜索的搜索库. 默认为 "". 仅与  `user-search-filter` 一起使用.

[[nsa-ldap-user-service-user-search-filter]]
* **user-search-filter**
用于搜索用户的LDAP过滤器 (可选) . 例如 "(uid={0})". 替换的参数是用户的登录名.
