[[null-safety]]
= Null-safety

尽管 Java 不允许使用类型系统来表示 null 安全,但 Spring 框架现在加入了 `org.springframework.lang` 包,并提供了以下注解,用来声明 API 和字段的 null 特性:

* {api-spring-framework}/lang/Nullable.html[`@Nullable`]: 其中特定参数、返回值或字段可以为 `null`.
* {api-spring-framework}/lang/NonNull.html[`@NonNull`]: 注解指示特定参数,返回值或字段不能为 `null`(对于 `@NonNullApi` 和 `@NonNullFields` 适用的参数和返回值不需要)
* {api-spring-framework}/lang/NonNullApi.html[`@NonNullApi`]: 在包级别将非 `null` 声明为参数和返回值的默认行为
* {api-spring-framework}/lang/NonNullFields.html[`@NonNullFields`]: 在包级别将非 `null` 声明为字段的默认行为

Spring 框架用到这些注解,但它们也可以用于任意基于 Spring 的 Java 项目中,用来声明 null 安全的 API 和可选的 null 安全字段. null 特性对于泛型类型参数、varargs 参数和数组元素是不受支持的,
但可能会包含在即将发布的版本中,请参阅 https://jira.spring.io/browse/SPR-15942[SPR-15942] 以获取最新信息. 在 Spring 框架发行版(包括小版本) 之间. 可以将 fine-tuned 声明为 null. 在方法体内判定类型是否为 null 超出了它的能力范围.

NOTE: 像 Reactor 或者 Spring Data 这样的库也用到了 null 安全的 API.

== 用例

Spring API 除了为 null 提供了显式的声明外,IDE 还可以使用这些注解(如 IDEA 或 Eclipse) 为与 null 安全相关的 Java 开发人员提供有用的警告,用于避免运行时出现 `NullPointerException`.

在 Kotlin 项目中也使用到 Spring API 的 null 安全特性,因为 Kotlin 本身支持 https://kotlinlang.org/docs/reference/null-safety.html[null-safety]. <<languages#kotlin-null-safety, Kotlin 支持文档>>提供了更多的详细信息.

== JSR-305 元注解

Spring 注解是被 https://jcp.org/en/jsr/detail?id=305[JSR 305] 注解的元注解(一个潜在的但广泛使用的JSR) .  JSR 305 元注解允许工具供应商(如 IDEA 或 Kotlin) 以通用方式提供安全支持,而无需为 Spring 注解提供硬编码支持.

为了使用 Spring 的 null 安全 API,其实不需要也不建议在项目类路径中添加 JSR 305 依赖. 而只有在其代码库中使用null安全标识的项目(例如 Spring 基本库)  即可,应该将 `com.google.code.findbugs:jsr305:3.0.2` 添加到 Gradle 的 `compileOnly` 或 Maven 的  `provided`  配置中,就可以避免编译警告了.
