[[auditing]]
= 审计

[[auditing.basics]]
== 基础

Spring Data 提供了完善的支持，可以透明地跟踪谁创建或更改了实体以及更改发生的时间。为了从该功能中获益，你必须为你的实体类配备审计元数据，这些元数据可以使用注解或实现接口来定义。

此外，审计必须通过注解配置或 XML 配置来启用，以注册所需的基础设施组件。关于配置样本，请参考特定 store 部分。

[NOTE]
====
仅跟踪创建和修改日期的应用程序不需要指定 <<auditing.auditor-aware, `AuditorAware`>>.
====

[[auditing.annotations]]
=== 基于注解的审计元数据

我们提供 `@CreatedBy` 和 `@LastModifiedBy` 来捕获创建或修改实体的用户,并提供 `@CreatedDate` 和 `@LastModifiedDate` 来捕获更改发生的时间.

.被审计实体
====
[source,java]
----
class Customer {

  @CreatedBy
  private User user;

  @CreatedDate
  private Instant createdDate;

  // … further properties omitted
}
----
====


如您所见,可以根据要捕获的信息有选择地应用注解.  指示更改时捕获的注解可用于 JDK 8 日期和时间类型, `long` 或 `Long` 以及旧版 Java `Date` 和 `Calendar` 类型的属性.

审计的元数据并不一定要存在于根级实体中， 而是可以添加内嵌的元数据 (取决于所使用的实际存储) ， 如下面的片段所示.

.嵌入实体中的审计元数据
====
[source,java]
----
class Customer {

  private AuditMetadata auditingMetadata;

  // … further properties omitted
}

class AuditMetadata {

  @CreatedBy
  private User user;

  @CreatedDate
  private Instant createdDate;

}
----
====

[[auditing.interfaces]]
=== 基于接口的审计元数据
如果您不想使用注解来定义审核元数据,则可以让您的 domain 类实现 `Auditable` 接口.  它为所有审计属性暴露了 setter 方法.

[[auditing.auditor-aware]]
=== `AuditorAware`

如果使用 `@CreatedBy` 或 `@LastModifiedBy`,则审计基础结构需要以某种方式了解当前的主体.  为此,我们提供了 `AuditorAware<T>` SPI 接口,您必须实现该接口以告知基础结构与应用程序交互的当前用户或系统是谁.
泛型类型 `T` 定义必须使用 `@CreatedBy` 或 `@LastModifiedBy` 注解的属性的类型.

以下示例显示了使用 Spring Security 的 `Authentication` 对象的接口的实现:

.基于 Spring Security 的 `AuditorAware` 的实现
====
[source, java]
----
class SpringSecurityAuditorAware implements AuditorAware<User> {

  @Override
  public Optional<User> getCurrentAuditor() {

    return Optional.ofNullable(SecurityContextHolder.getContext())
            .map(SecurityContext::getAuthentication)
            .filter(Authentication::isAuthenticated)
            .map(Authentication::getPrincipal)
            .map(User.class::cast);
  }
}
----
====

该实现访问 Spring Security 提供的 `Authentication` 对象,并查找您在 `UserDetailsService` 实现中创建的自定义 `UserDetails` 实例.  我们在这里假设您通过 `UserDetails` 实现暴露 domain 用户,但是根据找到的 `Authentication`,您还可以从任何地方查找它.

[[auditing.reactive-auditor-aware]]
=== `ReactiveAuditorAware`

当使用响应式时， 您可能想利用上下文（Context）信息来提供 `@CreatedBy` 或 `@LastModifiedBy` 信息.
我们提供了一个 `ReactiveAuditorAware<T>` SPI 接口， 您必须实现该接口通知应用程序交互的当前用户或系统是谁.  泛型类型 `T` 定义必须使用 `@CreatedBy` 或 `@LastModifiedBy` 注解的属性的类型.

以下示例显示了使用响应式 Spring Security 的 `Authentication` 对象的接口的实现:

.基于 Spring Security 的 `ReactiveAuditorAware` 实现
====
[source, java]
----
class SpringSecurityAuditorAware implements ReactiveAuditorAware<User> {

  @Override
  public Mono<User> getCurrentAuditor() {

    return ReactiveSecurityContextHolder.getContext()
                .map(SecurityContext::getAuthentication)
                .filter(Authentication::isAuthenticated)
                .map(Authentication::getPrincipal)
                .map(User.class::cast);
  }
}
----
====

该实现访问 Spring Security 提供的 `Authentication` 对象,并查找您在 `UserDetailsService` 实现中创建的自定义 `UserDetails` 实例.  我们在这里假设您通过 `UserDetails` 实现暴露 domain 用户,但是根据找到的 `Authentication`,您还可以从任何地方查找它.
