[[auditing]]
= 审计

[[auditing.basics]]
== 基础
Spring Data 提供了完善的支持,可以透明地跟踪创建或更改实体的人员以及更改发生的时间.  要利用该功能,您必须为实体类配备审核元数据,该审核元数据可以使用注解或通过实现接口来定义.

此外， 必须通过注解配置或 XML 配置启用审核， 以注册所需的基础结构组件.
请参阅特定的存储库部分来获取帮助.

[NOTE]
====
仅跟踪创建和修改日期的应用程序不需要指定 <<auditing.auditor-aware>>.
====

[[auditing.annotations]]
=== 基于注解的审核元数据

我们提供 `@CreatedBy` 和 `@LastModifiedBy` 来捕获创建或修改实体的用户,并提供 `@CreatedDate` 和 `@LastModifiedDate` 来捕获更改发生的时间.

.被审计实体
====
[source, java]
----
class Customer {

  @CreatedBy
  private User user;

  @CreatedDate
  private Instant createdDate;

  // … further properties omitted
}
----
====

如您所见,可以根据要捕获的信息有选择地应用注解.  捕获更改时捕获的注解可用于类型 `Joda-Time`,`DateTime`,旧版 Java `Date` 和 `Calendar`,JDK8 日期和时间类型以及 `long` 或 `Long` 的属性.

审计的元数据并不一定要存在于根级实体中， 而是可以添加内嵌的元数据 (取决于所使用的实际存储) ， 如下面的片段所示.

.Audit metadata in embedded entity
====
[source, java]
----
class Customer {

  private AuditMetadata auditingMetadata;

  // … further properties omitted
}

class AuditMetadata {

  @CreatedBy
  private User user;

  @CreatedDate
  private Instant createdDate;

}
----
====

[[auditing.interfaces]]
=== 基于接口的审核元数据
如果您不想使用注解来定义审核元数据,则可以让您的 domain 类实现 `Auditable` 接口.  它为所有审核属性暴露了setter方法.

还有一个便捷的基类 `AbstractAuditable`,可以对其进行扩展,以避免需要手动实现接口方法.  这样做会增加您的 domain 类与 Spring Data 的耦合,这可能是您要避免的事情.  通常,首选基于注解的方式来定义审核元数据,因为它侵入性较小且更灵活.

[[auditing.auditor-aware]]
=== `AuditorAware`

如果使用 `@CreatedBy` 或 `@LastModifiedBy`,则审计基础结构需要以某种方式了解当前的主体.  为此,我们提供了 `AuditorAware<T>` SPI 接口,您必须实现该接口以告知基础结构与应用程序交互的当前用户或系统是谁.
通用类型T定义必须使用 `@CreatedBy` 或 `@LastModifiedBy` 注解的属性的类型.

以下示例显示了使用 Spring Security 的 `Authentication` 对象的接口的实现:

.基于 Spring Security 的 `AuditorAware` 的实现
====
[source, java]
----
class SpringSecurityAuditorAware implements AuditorAware<User> {

  @Override
  public Optional<User> getCurrentAuditor() {

    return Optional.ofNullable(SecurityContextHolder.getContext())
            .map(SecurityContext::getAuthentication)
            .filter(Authentication::isAuthenticated)
            .map(Authentication::getPrincipal)
            .map(User.class::cast);
  }
}
----
====

该实现访问 Spring Security 提供的 `Authentication` 对象,并查找您在 `UserDetailsService` 实现中创建的自定义 `UserDetails` 实例.  我们在这里假设您通过 `UserDetails` 实现暴露 domain 用户,但是根据找到的 `Authentication`,您还可以从任何地方查找它.

[[auditing.reactive-auditor-aware]]
=== `ReactiveAuditorAware`

当使用响应式时， 您可能想利用上下文信息来提供 `@CreatedBy` 或 `@LastModifiedBy` 信息.
我们提供了一个 `ReactiveAuditorAware<T>` SPI 接口， 您必须实现该接口通知应用程序交互的当前用户或系统是谁.  通用类型 `T` 定义必须使用 `@CreatedBy` 或 `@LastModifiedBy` 注解的属性的类型.

以下示例显示了使用响应式 Spring Security 的 `Authentication` 对象的接口的实现:

.Implementation of `ReactiveAuditorAware` based on Spring Security
====
[source, java]
----
class SpringSecurityAuditorAware implements ReactiveAuditorAware<User> {

  @Override
  public Mono<User> getCurrentAuditor() {

    return ReactiveSecurityContextHolder.getContext()
                .map(SecurityContext::getAuthentication)
                .filter(Authentication::isAuthenticated)
                .map(Authentication::getPrincipal)
                .map(User.class::cast);
  }
}
----
====

该实现访问 Spring Security 提供的 `Authentication` 对象,并查找您在 `UserDetailsService` 实现中创建的自定义 `UserDetails` 实例.  我们在这里假设您通过 `UserDetails` 实现暴露 domain 用户,但是根据找到的 `Authentication`,您还可以从任何地方查找它.
