下面是一个 Spring Converter 实现的例子，它将一个 `String` 转换为一个自定义的 `Email` 值对象。

[source,java,subs="verbatim,attributes"]
----
@ReadingConverter
public class EmailReadConverter implements Converter<String, Email> {

  public Email convert(String source) {
    return Email.valueOf(source);
  }
}
----

如果你编写的 `Converter` 的源类型和目标类型都是原生类型，我们无法确定我们应该把它看作是一个读或写的 `Converter`。将 `Converter` 实例注册为这两种类型可能会导致不必要的结果。例如，一个 `Converter<String, Long>` 是模棱两可的，尽管在写入时试图将所有的 `String` 实例转换成 `Long` 实例可能没有意义。
为了让你强制基础设施只为一种方式注册转换器，我们提供了 `@ReadingConverter` 和 `@WritingConverter` 注解，以便在转换器实现中使用。

`Converter` 需要明确注册，因为实例不是从 classpath 或容器扫描中获取的，以避免在转换服务中进行不必要的注册以及这种注册产生的副作用。`Converter` 是通过 `CustomConversions` 注册的，它是一个中央设施，允许根据源和目标类型注册和查询已注册的 `Converter`。

`CustomConversions` 带有一套预先定义的转换器注册（converter registration）。

* JSR-310 Converter 用于 `java.time`、`java.util.Date` 和 `String` 类型之间的转换。

NOTE: 本地时间类型的默认 converter（例如，`LocalDateTime` 到 `java.util.Date`）依靠系统默认的时区设置在这些类型之间进行转换。你可以通过注册你自己的 convert 来覆盖默认的 convert。

[[customconversions.converter-disambiguation]]
== Converter 歧义

一般来说，我们会检查 `Converter` 的实现，看他们转换的源类型和目标类型。根据这些类型中是否有一个是底层数据访问 API 可以原生处理的类型，我们将 converter 实例注册为读或写转换器。
下面的例子显示了一个写 converter 和一个读 converter（注意区别在于 `Converter` 上修饰词的顺序）。

[source,java]
----
// Write converter as only the target type is one that can be handled natively
class MyConverter implements Converter<Person, String> { … }

// Read converter as only the source type is one that can be handled natively
class MyConverter implements Converter<String, Person> { … }
----
