[[dependencies]]
= 依赖

由于各个 Spring Data 模块的初始日期不同,它们中的大多数都带有不同的主版本号和次版本号. 寻找兼容版本的最简单方法是依靠我们随定义的兼容版本提供的 Spring Data Release BOM.
在 Maven 项目中,您将在 `<dependencyManagement />` POM 的部分声明这种依赖,如下所示:

.使用 Spring Data 发行版 BOM
====
[source, xml, subs="+attributes"]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.springframework.data</groupId>
      <artifactId>spring-data-bom</artifactId>
      <version>{releasetrainVersion}</version>
      <scope>import</scope>
      <type>pom</type>
    </dependency>
  </dependencies>
</dependencyManagement>
----
====

[[dependencies.train-version]]
目前的发行版本是 `{releasetrainVersion}`. 版本使用 https://calver.org/overview_zhcn.html[calver] 的格式 `YYYY.MINOR.MICRO`.
对于 GA releases 和 service releases 版本遵循  `${calver}` ， 对于所有其他版本， 其名称遵循以下模式: `${calver}-${modifier}`,  其中 `modifier` 可以是以下内容之一:

* `SNAPSHOT`: 当前快照版本
* `M1`, `M2`, 等: 里程碑
* `RC1`, `RC2`, 等,发布候选

在我们的 https://github.com/spring-projects/spring-data-examples/tree/master/bom[Spring Data 示例存储库] 中可以找到使用 BOM 的一个工作示例. 有了这个,你可以在你的模块中声明 Spring Data 模块而不需要版本 `<dependencies />`,如下所示:

.声明一个依赖 Spring Data 模块
====
[source, xml]
----
<dependencies>
  <dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-jpa</artifactId>
  </dependency>
<dependencies>
----
====

[[dependencies.spring-boot]]
== Spring Boot 的依赖管理

Spring Boot 为您选择最新版本的 Spring Data 模块. 如果您仍想升级到较新版本,请将该属性配置为您要使用  `spring-data-releasetrain.version`  的 <<dependencies.train-version,迭代版本>> .

[[dependencies.spring-framework]]
== Spring Framework

当前版本的 Spring Data 模块需要版本  {spring-framework-version}  或更高版本的 Spring Framework. 这些模块也可能与该次要版本的旧版错误修复版本一起工作. 但是,强烈建议使用该代中的最新版本.