[[kotlin]]
= Kotlin 支持

https://kotlinlang.org[Kotlin] 是针对JVM(和其他平台)的静态类型化语言,它允许编写简洁而优雅的代码,同时提供与Java中编写的现有库的非常好的 https://kotlinlang.org/docs/reference/java-interop.html[互操作性] .

Spring Framework为Kotlin提供了一流的支持,使开发人员可以编写Kotlin应用程序,就像Spring Framework是本地Kotlin框架一样.

用Kotlin构建Spring应用程序的最简单方法是利用Spring Boot及其 https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-kotlin.html[专用的Kotlin支持].  这个 https://spring.io/guides/tutorials/spring-boot-kotlin/[全面的教程]将教您如何使用 https://start.spring.io/#!language=kotlin&type=gradle-project[start.spring.io]使用Kotlin构建Spring Boot应用程序.

[[kotlin.requirements]]
== 要求

Spring Data 支持Kotlin 1.3+并且需要 https://bintray.com/bintray/jcenter/org.jetbrains.kotlin%3Akotlin-stdlib[`kotlin-stdlib`] (或其变体之一, 例如 https://bintray.com/bintray/jcenter/org.jetbrains.kotlin%3Akotlin-stdlib-jdk8[`kotlin-stdlib-jdk8`] )
和 https://bintray.com/bintray/jcenter/org.jetbrains.kotlin%3Akotlin-reflect[`kotlin-reflect`]存在于类路径中.  如果您在 https://start.spring.io/#!language=kotlin&type=gradle-project[start.spring.io]上引导Kotlin项目,则默认提供它们.

[[kotlin.null-safety]]
== Null 安全

Kotlin的一个关键特性是 https://kotlinlang.org/docs/reference/null-safety.html[null-safety],它在编译时干净地处理 `null` 值,而不是在运行时撞上著名的 `NullPointerException` 异常.
这使得应用程序通过可空性声明更安全并表达"有价值或无价值"语义,而无需支付包装器的成本,例如 `Optional`.  (Kotlin允许使用具有可空值的功能构造. 请参阅此https://www.baeldung.com/kotlin-null-safety[综合指南以了解Kotlin null安全性]. )

虽然Java不允许在其类型系统中表示 null 安全,但Spring框架现在通过在 `org.springframework.lang` 包中声明的工具友好注解,为整个<<core#null-safety, Spring框架API提供了null安全>>.
默认情况下,Kotlin中使用的Java API中的类型被识别为可轻松进行null检查的 https://kotlinlang.org/docs/reference/java-interop.html#null-safety-and-platform-types[平台类型].  https://kotlinlang.org/docs/reference/java-interop.html#jsr-305-support[Kotlin支持JSR 305注解], Spring可空性注解为Kotlin开发人员提供了整个Spring框架API的 null安全,其优点是在编译时处理 `null` 的相关问题.

请参阅 << repositories.nullability >> 空安全如何应用于Spring Data Repositories.

[TIP]
====
JSR 305检查可以通过添加 `-Xjsr305` 编译器标志来配置,其中有以下选项: `-Xjsr305={strict|warn|ignore}`.

对于kotlin 1.1+, 默认行为与 `-Xjsr305=warn` 一致. `strict` 的值应该被认为是实验性的(Spring API的null声明在小版本之间可能会发生变化,将来可能会增加更多的检查).
====

NOTE: 泛型类型参数、varargs和数组元素为null性不受支持,但应在即将发布的版本中添加此功能.

[[kotlin.mapping]]
== Object Mapping

有关如何实现Kotlin对象的详细信息,请参见 <<mapping.kotlin>>.
