[[kotlin.coroutines]]
= Coroutines

Kotlin https://kotlinlang.org/docs/reference/coroutines-overview.html[Coroutines] 是Kotlin轻量级线程,允许以命令式方式编写非阻塞代码.  在语言方面,挂起函数为异步操作提供了一种抽象,而在库方面,https://github.com/Kotlin/kotlinx.coroutines[kotlinx.coroutines] 提供了诸如 https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html[`async { }`] 之类的函数以及诸如 https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/index.html[`Flow`] 之类的类型.

Spring Data 模块 在以下范围内提供对 Coroutines 的支持:

* https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-deferred/index.html[Deferred] 和 https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/index.html[Flow] Kotlin扩展中的返回值支持

[[kotlin.coroutines.dependencies]]
== 依赖

当 `kotlinx-coroutines-core` , `kotlinx-coroutines-reactive` 和 `kotlinx-coroutines-reactor` 依赖位于类路径中时,将启用 Coroutines 支持:

.在Maven pom.xml中添加的依赖
====
[source,xml]
----
<dependency>
	<groupId>org.jetbrains.kotlinx</groupId>
	<artifactId>kotlinx-coroutines-core</artifactId>
</dependency>

<dependency>
	<groupId>org.jetbrains.kotlinx</groupId>
	<artifactId>kotlinx-coroutines-reactive</artifactId>
</dependency>

<dependency>
	<groupId>org.jetbrains.kotlinx</groupId>
	<artifactId>kotlinx-coroutines-reactor</artifactId>
</dependency>
----
====

NOTE: 支持 `1.3.0` 及更高版本.

[[kotlin.coroutines.reactive]]
== Reactive 如何转换为 Coroutines?

对于返回值,以下是从 Reactive 到 Coroutines API的转换:

* `fun handler(): Mono<Void>` 变成 `suspend fun handler()`
* `fun handler(): Mono<T>` 变成 `suspend fun handler(): T` 或 `suspend fun handler(): T?` 取决于 `Mono` 是否可以为空 (具有更静态输入的优势)
* `fun handler(): Flux<T>` 变成 `fun handler(): Flow<T>`


在 Coroutines 中, https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/index.html[`Flow`] 和 `Flux` 是等效的, 适用于热流或冷流,有限流或无限流,主要区别如下:

* `Flow` 是基于推式的 `Flux` 是推拉式混合的
* 背压通过暂停功能实现
* `Flow` 只有一个暂停的 https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/-flow/collect.html[收集方法] 并且运算符被实现为 https://kotlinlang.org/docs/reference/extensions.html[扩展]借助 Coroutines,操作员易于实施
* https://github.com/Kotlin/kotlinx.coroutines/tree/master/kotlinx-coroutines-core/common/src/flow/operators[Operators are easy to implement] thanks to Coroutines
* 扩展允许向 `Flow` 添加自定义运算符
* 收集操作正在暂停功能
* https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/map.html[`map` operator] 支持异步操作 (不需要 `flatMap`) ,因为它需要一个暂停函数参数

通过阅读有关 https://spring.io/blog/2019/04/12/going-reactive-with-spring-coroutines-and-kotlin-flow[Spring,Coroutines和Kotlin Flow Reactive]的博客文章,了解更多详细信息,包括如何与Coroutines并发运行代码.

[[kotlin.coroutines.repositories]]
== Repositories

这里是一个关于 Coroutines repository 的示例:

====
[source,kotlin]
----
interface CoroutineRepository : CoroutineCrudRepository<User, String> {

    suspend fun findOne(id: String): User

    fun findByFirstname(firstname: String): Flow<User>
}
----
====

Coroutines repositories 建立在响应式存储库上,以展示通过 Kotlin 的 Coroutines 进行数据访问的非阻塞性.

可以通过查询方法或自定义实现来支持 Coroutines 存储库中的方法.如果自定义方法是 `suspend` 的,则调用自定义实现方法会将 Coroutines 调用传播到实际的实现方法,而无需实现方法返回诸如 `Mono` 或 `Flux` 之类的响应式类型.

NOTE: 只有在 repositories 扩展了 `CoroutineCrudRepository` 接口时,才会发现该存储库.