[[mapping.fundamentals]]
= 对象映射基础

本节介绍了 Spring Data 对象映射，对象创建,字段和属性访问，可变性和不可变性的基础知识。请注意，不使用底层数据存储的对象映射 (例如 JPA) 的对象映射的 Spring Data 模块。
另外，请确保参考存储库特定的部分以获取存储库特定的对象映射，例如索引，自定义列或字段名称等。

Spring Data 对象映射的核心职责是创建领域对象的实例，并将存储的本地数据结构映射到这些对象上。 这意味着我们需要两个基本步骤:

1. 使用暴露的构造函数之一创建实例.
2. 实例填充以实现所有暴露的属性.

[[mapping.object-creation]]
== 创建对象

Spring Data 会自动尝试检测一个持久化实体的构造函数，以用于将该类型的对象具体化。该解析算法的工作原理如下。

1. 如果有一个用 `@PersistenceCreator` 注解的静态工厂方法，则使用它。
2. 如果只有一个构造函数，则使用它。
3. 如果有多个构造函数，并且只有一个被 `@PersistenceCreator` 注解，则使用它。
4. 如果类型是 Java `Record`，则使用规范构造函数。
5. 如果有一个无参构造函数，则使用它。

值解析假定构造器/工厂方法参数名与实体的属性名相匹配，即解析将在属性被填充的情况下进行，包括映射中的所有自定义项（不同的数据存储列或字段名等）。
这也需要在 class 文件中提供参数名称信息，或者在构造函数上提供 `@ConstructorProperties` 注解。

可以通过使用特定于存储的 SpEL 表达式使用 Spring Framework 的 `@Value` 值注解来自定义值解析.
请参阅有关特定存储映射的部分以获取更多详细信息.

[[mapping.object-creation.details]]
.创建内部对象
****

为了避免反射的开销,Spring Data 对象的创建默认情况下使用在运行时生成的工厂类,该工厂类将直接调用 domain 类的构造函数.  即 对于此示例类型:

[source, java]
----
class Person {
  Person(String firstname, String lastname) { … }
}
----

我们将在运行时创建一个语义上等同于此的工厂类:

[source, java]
----
class PersonObjectInstantiator implements ObjectInstantiator {

  Object newInstance(Object... args) {
    return new Person((String) args[0], (String) args[1]);
  }
}
----

与反射相比,这使我们的性能提高了约 10％。为了使 domain 类能进行这种优化，它需要遵守一系列的限制条件。

- 它不能是 private 类
- 它不能是非静态内部类
- 它不能是 CGLib 代理类
- Spring Data 使用的构造函数不能为 private

如果这些条件中的任何一个匹配,Spring Data 将通过反射回退到实体实例化.
****

[[mapping.property-population]]
== 属性填充

创建实体的实例后,Spring Data 会填充该类的所有剩余持久性属性。除非已经由实体的构造函数填充（即通过其构造函数参数列表设置），否则 `identifier` 属性将首先被填充，以允许解决循环对象引用。
之后,在实体实例上设置所有尚未由构造函数填充的非临时属性.  为此,我们使用以下算法:

1. 如果该属性是不可变的，但暴露了一个 `with…` 方法（见下文），我们使用 `with…` 方法来创建一个具有新属性值的新实体实例。
2. 如果定义了属性访问权限 (即通过 getter 和 setter 的访问) ,则我们调用 setter 方法.
3. 如果属性是可变的,则直接设置该字段.
4. 如果属性是不可变的,那么我们将使用持久化操作使用的构造函数 (请参见 <<mapping.object-creation>>) 来创建实例的副本.
5. 默认情况下,直接设置字段值.

[[mapping.property-population.details]]
.属性填充的内部细节
****
与 <<mapping.object-creation.details,构造对象的优化>> 类似,我们还使用 Spring Data 运行时生成的访问器类与实体实例进行交互.

[source,java]
----
class Person {

  private final Long id;
  private String firstname;
  private @AccessType(Type.PROPERTY) String lastname;

  Person() {
    this.id = null;
  }

  Person(Long id, String firstname, String lastname) {
    // Field assignments
  }

  Person withId(Long id) {
    return new Person(id, this.firstname, this.lastame);
  }

  void setLastname(String lastname) {
    this.lastname = lastname;
  }
}
----

.生成的属性访问器
====
[source, java]
----
class PersonPropertyAccessor implements PersistentPropertyAccessor {

  private static final MethodHandle firstname;              <2>

  private Person person;                                    <1>

  public void setProperty(PersistentProperty property, Object value) {

    String name = property.getName();

    if ("firstname".equals(name)) {
      firstname.invoke(person, (String) value);             <2>
    } else if ("id".equals(name)) {
      this.person = person.withId((Long) value);            <3>
    } else if ("lastname".equals(name)) {
      this.person.setLastname((String) value);              <4>
    }
  }
}
----
<1> `PropertyAccessor` 持有底层对象的一个可变实例. 这是为了允许对其他不可变的属性进行更改.
<2> 默认情况下,Spring Data 使用字段访问来读写属性值. 根据  `private` 字段的可见性规则,使用 `MethodHandles` 与字段交互.
<3> 该类暴露了一个  `withId(…)` 方法,该方法用于设置标识符（identifier），例如，当一个实例被插入到数据存储中并生成了一个标识符。调用  `withId(…)` 会创建一个新的 `Person` 对象。 所有后续的修改都将在新的实例中进行，而之前的实例不受影响。
<4> 使用属性访问（property-access）允许直接调用方法而不使用 `MethodHandles`。
====

与反射相比,这使我们的性能提高了约 25％。为了使domain类有能进行这种优化，它需要遵守一系列的限制条件。

- 类不能在默认（default ）或 java 包下。
- 类和它们的构造函数必须是 `public`。
- 内部类的类型必须是静态的.
- 使用的 Java 运行时必须允许在原始 `ClassLoader` 中声明类.  Java 9 和更高版本强加了某些限制.

默认情况下，Spring Data 尝试使用生成的属性访问器，如果检测到限制，则回退到基于反射的属性访问器.
****

让我们来看看以下实体。

.一个简单的实体
====
[source, java]
----
class Person {

  private final @Id Long id;                                                <1>
  private final String firstname, lastname;                                 <2>
  private final LocalDate birthday;
  private final int age;                                                    <3>

  private String comment;                                                   <4>
  private @AccessType(Type.PROPERTY) String remarks;                        <5>

  static Person of(String firstname, String lastname, LocalDate birthday) { <6>

    return new Person(null, firstname, lastname, birthday,
      Period.between(birthday, LocalDate.now()).getYears());
  }

  Person(Long id, String firstname, String lastname, LocalDate birthday, int age) { <6>

    this.id = id;
    this.firstname = firstname;
    this.lastname = lastname;
    this.birthday = birthday;
    this.age = age;
  }

  Person withId(Long id) {                                                  <1>
    return new Person(id, this.firstname, this.lastname, this.birthday, this.age);
  }

  void setRemarks(String remarks) {                                         <5>
    this.remarks = remarks;
  }
}
----
====
<1> 标识符属性是 `final`,但在构造函数中设置为 `null`。 该类暴露了一个 `withId(…)` 方法，用于设置 id。例如，当一个实例被插入到数据存储中并且已经生成了一个 id。当一个新的 `Person` 实例被创建时，
原来的 `Person` 实例保持不变。同样的模式通常适用于其他的属性，这些属性是存储管理的，但可能要为持久化操作而改变。`with` 方法是可选的，
因为持久化构造函数（见 6）实际上是一个复制构造函数，设置该属性将被转化为创建一个新的实例，并应用新的 id 值。
<2> `firstname` 和 `lastname` 属性是普通的不可变的属性，可能通过 getter 暴露。
<3> `age` 属性是一个不变的，但从  `birthday`  属性扩展的属性。 通过显示的设计，数据库值将胜过默认值， 因为 Spring Data 使用唯一声明的构造函数。 因为 Spring Data 使用唯一声明的构造函数。即使意图是优先考虑计算，
重要的是这个构造函数也将 `age` 作为参数（有可能忽略它），否则属性填充步骤将试图设置 `age` 字段，但由于它是不可变的，而且没有 `with…`  方法存在，因此失败了。
<4> `comment` 属性是可变的，通过直接设置其字段来填充。
<5> `remarks` 属性是可变的，通过直接设置  `comment` 字段或通过调用 setter 方法来填充
<6> 该类暴露了一个工厂方法和一个用于创建对象的构造器。这里的核心思想是使用工厂方法而不是额外的构造函数，以避免通过 `@PersistenceCreator` 进行构造函数消歧义的需要。
相反，属性的默认设置是在工厂方法中处理的。如果你想让 Spring Data 使用工厂方法进行对象实例化，请用 `@PersistenceCreator` 来注解它。

[[mapping.general-recommendations]]
== 一般建议

* _尽量使用不可变的对象_ -- 不可变的对象很容易创建，因为实现一个对象只需调用其构造函数即可。 同样，这避免了客户端代码操纵对象状态的 setter 方法扰乱您的领域对象。  如果需要它们,则最好使它们受到 `package` 保护，以便只能由有限数量的同一位置类型调用它们。
仅限构造函数的实现比属性填充快 `30％`.
* _提供一个全参数的构造函数_ -- 即使你不能或不想将你的实体建模为不可变的值，提供一个将实体的所有属性作为参数的构造函数仍有价值，包括可变的属性，因为这允许对象映射跳过属性填充以获得最佳性能。
* _使用工厂方法而不是重载的构造函数来避免  `@PersistenceCreator`_ -- 为了获得最佳性能,需要使用全参数构造函数，我们通常希望暴露更多特定于应用程序用例的构造函数，从而省略了诸如自动生成的标识符等内容。  使用静态工厂方法暴露 `all-args` 构造函数的这些变体.
* _确保您遵守允许使用生成的实例化器和属性访问器类的约束_ --
* _对于要生成的标识符,仍然将 final 字段与全参数构造函数  `with…` 方法结合使用_ --
* _使用 Lombok 来避免样板代码_ -- 由于持久性操作通常需要构造函数使用所有参数,因此它们的声明成为对字段分配的样板参数的繁琐重复,最好使用 Lombok 的 `@AllArgsConstructor` 来避免.

[[mapping.general-recommendations.override.properties]]
=== 重写属性

Java 允许灵活设计 domain 类，其中子类可以定义一个已在其超类中以相同名称声明的属性。 考虑以下示例:

====
[source,java]
----
public class SuperType {

   private CharSequence field;

   public SuperType(CharSequence field) {
      this.field = field;
   }

   public CharSequence getField() {
      return this.field;
   }

   public void setField(CharSequence field) {
      this.field = field;
   }
}

public class SubType extends SuperType {

   private String field;

   public SubType(String field) {
      super(field);
      this.field = field;
   }

   @Override
   public String getField() {
      return this.field;
   }

   public void setField(String field) {
      this.field = field;

      // optional
      super.setField(field);
   }
}
----
====

这两个类都使用可分配类型来定义一个 `field`。然而，`SubType` 会影响 `SuperType.field`。根据类的设计，使用构造函数可能是设置 `SuperType.field` 的唯一默认方法。
另外，在 setter 中调用 `super.setField(…)` 可以在 `SuperType` 中设置 `field`。所有这些机制在某种程度上都会产生冲突，因为这些属性共享相同的名称，但可能代表两个不同的值。
如果类型不可分配，Spring Data 会跳过父类属性。也就是说，被覆盖的属性的类型必须可分配给它的父类的属性类型才能被注册为覆盖（override），否则父类的属性就会被认为是 `transient` 的。
我们一般建议使用不同的属性名称。

Spring Data 模块通常支持覆盖不同值的属性。 从编程模型的角度来看，有几点需要考虑：

1. 哪个属性应该被持久化（默认为所有声明的属性）？ 您可以通过使用 `@Transient` 注解这些属性来排除这些属性。
2. 如何在数据存储中表示属性？对不同的值使用相同的字段/列名通常会导致数据损坏，所以你应该至少使用一个明确的字段/列名来注解其中的一个属性。
3. 不能使用 `@AccessType(PROPERTY)`，因为在不对 setter 实现做任何进一步假设的情况下，一般不能设置父类属性。

[[mapping.kotlin]]
== Kotlin 支持

Spring Data 修改了 Kotlin 的细节以允许对象创建和变异(mutation).

[[mapping.kotlin.creation]]
=== Kotlin 对象创建

支持 Kotlin 类实例化，所有类默认都是不可变的，需要显式的属性声明来定义可变属性。

Spring Data 会自动尝试检测一个持久化实体的构造函数，以用于将该类型的对象具体化。 该解析算法的工作原理如下。

1. 如果有一个构造函数被 `@PersistenceCreator` 注解，则使用它。
2. 如果类型是 <<mapping.kotlin,Kotlin data cass>> 则使用主构造函数。
3. 如果有一个用 `@PersistenceCreator` 注解的静态工厂方法，则使用它。
4. 如果只有一个构造函数，则使用它。
5. 如果有多个构造函数，并且恰好有一个被 `@PersistenceCreator` 注解，则使用它。
6. 如果类型是 Java `Record`，则使用规范构造函数。
7. 如果有一个无参构造函数，则使用它。

其他构造函数将被忽略。

考虑以下  `data`  类 `Person`:

====
[source,kotlin]
----
data class Person(val id: String, val name: String)
----
====

上面的类编译成一个典型的具有显式构造函数的类。  我们可以通过添加另一个构造函数来定制该类，并使用 `@PersistenceCreator` 对其进行注解以指示构造函数的首选项:

====
[source,kotlin]
----
data class Person(var id: String, val name: String) {

    @PersistenceCreator
    constructor(id: String) : this(id, "unknown")
}
----
====

Kotlin 通过允许在未提供参数的情况下使用默认值来支持参数的可选性。  当 Spring Data 检测到带有参数默认值的构造函数时，如果数据存储没有提供值 (或简单地返回 `null`) ，则它将使这些参数不存在，因此 Kotlin 可以应用参数默认值。
考虑下面的类，它对 `name` 应用参数默认值。

====
[source,kotlin]
----
data class Person(var id: String, val name: String = "unknown")
----
====

每当 `name` 参数不是结果的一部分或值为 `null` 时, name` 默认为  `unknown`.

=== Property population of Kotlin data classes

在 Kotlin 中,所有类默认都是不可变的,并且需要显式的属性声明来定义可变属性.  考虑以下 `data` 类 `Person`:

====
[source,kotlin]
----
data class Person(val id: String, val name: String)
----
====

该类实际上是不可变的.  当 Kotlin 生成 `copy(…)` 方法时,它可以创建新的实例,该方法创建新的对象实例,该对象实例从现有对象复制所有属性值,并将作为参数提供的属性值应用于该方法.

[[mapping.kotlin.override.properties]]
=== Kotlin 重写属性

Kotlin 允许声明 https://kotlinlang.org/docs/inheritance.html#overriding-properties[属性覆盖] 以更改子类中的属性。

====
[source,kotlin]
----
open class SuperType(open var field: Int)

class SubType(override var field: Int = 1) :
	SuperType(field) {
}
----
====

这样的显示了两个名为 `field` 的属性。 Kotlin 为每个类中的每个属性生成属性访问器（getter 和 setter）。
实际上，代码如下所示：

====
[source,java]
----
public class SuperType {

   private int field;

   public SuperType(int field) {
      this.field = field;
   }

   public int getField() {
      return this.field;
   }

   public void setField(int field) {
      this.field = field;
   }
}

public final class SubType extends SuperType {

   private int field;

   public SubType(int field) {
      super(field);
      this.field = field;
   }

   public int getField() {
      return this.field;
   }

   public void setField(int field) {
      this.field = field;
   }
}
----
====

`SubType` 上的 getter 和 setter 仅设置 `SubType.field` 而不是 `SuperType.field`。
在这样的安排中，使用构造函数是设置 `SuperType.field` 的唯一默认方法。
通过 `this.SuperType.field = ...` 向 `SubType` 添加方法以设置 `SuperType.field` 是可能的，但不符合支持的约定。
属性覆盖在某种程度上会产生冲突，因为属性使用相同的名称但可能代表两个不同的值。 我们通常建议使用不同的属性名称。

Spring Data 模块通常支持覆盖不同值的属性。 从编程模型的角度来看，有几点需要考虑：

1. 哪个属性应该被持久化（默认为所有声明的属性）？ 您可以通过使用 `@Transient` 注解这些属性来排除这些属性。
2. 如何在数据存储中表示属性？ 对不同的值使用相同的字段/列名通常会导致数据损坏，所以你应该至少使用一个明确的字段/列名来注解其中的一个属性。
3. 不能使用 `@AccessType(PROPERTY)`，因为在不对 setter 实现做任何进一步假设的情况下，一般不能设置父类属性。
