[[query-by-example]]
= 查询例子

[[query-by-example.introduction]]
== 简介

本章对 "按示例查询" 进行了介绍,并说明了如何使用它.

示例查询 (QBE) 是一种具有简单界面的用户友好查询技术.  它允许动态查询创建,并且不需要您编写包含字段名称的查询.  实际上,"示例查询" 根本不需要您使用存储库特定的查询语言编写查询.

[[query-by-example.usage]]
== 使用

示例查询由三部分组成:

* Probe: 带有填充字段的 domain 对象的实际示例.
* `ExampleMatcher`: `ExampleMatcher` 包含有关如何匹配特定字段的详细信息.  可以在多个示例中重复使用它.
* `Example`: 示例包括探针和 `ExampleMatcher`.  它用于创建查询.

示例查询非常适合几种用例:

* 使用一组静态或动态约束来查询数据存储.
* 频繁重构 domain 对象,而不必担心破坏现有查询.
* 独立于基础数据存储 API 进行工作.

示例查询也有一些限制:

* 不支持嵌套或分组属性约束,例如 `firstname = ?0 or (firstname = ?1 and lastname = ?2)`.
* 仅支持字符串的开始/包含/结束/正则表达式匹配,以及其他属性类型的完全匹配.

在开始使用示例查询之前,您需要具有一个 domain 对象.  首先,为您的存储库创建一个接口,如以下示例所示:

.Sample Person 对象
====
[source,java]
----
public class Person {

  @Id
  private String id;
  private String firstname;
  private String lastname;
  private Address address;

  // … getters and setters omitted
}
----
====

前面的示例显示了一个简单的域对象.  您可以使用它来创建一个 `Example`.  默认情况下,具有 `null` 的字段将被忽略,并且使用存储特定的默认值来匹配字符串.  可以使用工厂方法或使用 `ExampleMatcher` 构建示例.  例子是一成不变的.  以下清单显示了一个简单的示例:

NOTE: 由于可空性， 可以将属性包含在 "按示例查询" . 除非 <<query-by-example.matchers,忽略属性路径>>， 否则始终包括使用基本类型(`int`, `double`, …) 的属性 .


.Simple Example
====
[source,java]
----
Person person = new Person();                         <1>
person.setFirstname("Dave");                          <2>

Example<Person> example = Example.of(person);         <3>
----
<1> 创建  domain 对象的新实例.
<2> 设置要查询的属性.
<3> 创建 `Example`.
====

最好在存储库中执行示例.  为此,让您的存储库接口扩展 `QueryByExampleExecutor<T>`.  以下清单显示了 `QueryByExampleExecutor` 接口:

.`QueryByExampleExecutor`
====
[source,java]
----
public interface QueryByExampleExecutor<T> {

  <S extends T> S findOne(Example<S> example);

  <S extends T> Iterable<S> findAll(Example<S> example);

  // … more functionality omitted.
}
----
====

[[query-by-example.matchers]]
== Example 匹配

示例不限于默认设置.  您可以使用 `ExampleMatcher` 为字符串匹配,空值处理和特定于属性的设置指定自己的默认值,如以下示例所示:

.具有定制匹配的例子匹配器
====
[source,java]
----
Person person = new Person();                          <1>
person.setFirstname("Dave");                           <2>

ExampleMatcher matcher = ExampleMatcher.matching()     <3>
  .withIgnorePaths("lastname")                         <4>
  .withIncludeNullValues()                             <5>
  .withStringMatcherEnding();                          <6>

Example<Person> example = Example.of(person, matcher); <7>

----
<1> 创建域对象的新实例.
<2> 设置属性.
<3> 创建一个 `ExampleMatcher` 以期望所有值都匹配.  即使没有进一步的配置,它也可以在此阶段使用.
<4> 构造一个新的 `ExampleMatcher` 以忽略 `lastname` 属性路径.
<5> 构造一个新的 `ExampleMatcher` 以忽略 `lastname` 属性路径并包含空值.
<6> 构造一个新的 `ExampleMatcher` 以忽略 `lastname` 属性路径,包括空值,并执行后缀字符串匹配.
<7> 基于域对象和配置的 `ExampleMatcher` 创建一个新的 `Example`.
====

默认情况下,`ExampleMatcher` 期望设置的所有值都匹配.  如果要获取与隐式定义的任何断言匹配的结果,请使用  `ExampleMatcher.matchingAny()`.

您可以为单个属性 (例如  "firstname" 和 "lastname",或者对于嵌套属性,"address.city") 指定行为.  您可以使用匹配选项和区分大小写对其进行调整,如以下示例所示:

.配置匹配器选项
====
[source,java]
----
ExampleMatcher matcher = ExampleMatcher.matching()
  .withMatcher("firstname", endsWith())
  .withMatcher("lastname", startsWith().ignoreCase());
}
----
====

配置匹配器选项的另一种方法是使用 lambda (在Java 8中引入) .  此方法创建一个回调,要求实现者修改匹配器.  您无需返回匹配器,因为配置选项保存在匹配器实例中.  以下示例显示了使用lambda的匹配器:

.用lambdas配置匹配器选项
====
[source,java]
----
ExampleMatcher matcher = ExampleMatcher.matching()
  .withMatcher("firstname", match -> match.endsWith())
  .withMatcher("firstname", match -> match.startsWith());
}
----
====

由 `Example` 创建的查询使用配置的合并视图.  可以在 `ExampleMatcher` 级别上设置默认的匹配设置,而可以将单个设置应用于特定的属性路径.  除非明确定义,否则 `ExampleMatcher` 上设置的设置将由属性路径设置继承.
属性修补程序上的设置优先于默认设置.  下表描述了各种 `ExampleMatcher` 设置的范围:

表4. `ExampleMatcher` 设置的范围

[cols="1,2",options="header"]
.Scope of `ExampleMatcher` settings
|===
| Setting
| Scope

| Null-handling
| `ExampleMatcher`

| String matching
| `ExampleMatcher` and property path

| Ignoring properties
| Property path

| Case sensitivity
| `ExampleMatcher` and property path

| Value transformation
| Property path

|===
