ifndef::projection-collection[]
:projection-collection: Collection
endif::[]

[[projections]]
= 投影

Spring Data 查询方法通常返回存储库管理的聚合根的一个或多个实例.  但是，有时可能需要根据这些类型的某些属性创建投影。  Spring Data 允许对专用的返回类型进行建模，以更有选择地检索管理的聚合的部分视图.

想象一下一个存储库和聚合根类型,例如以下示例:

.一个示例集合和存储库
====
[source, java, subs="+attributes"]
----
class Person {

  @Id UUID id;
  String firstname, lastname;
  Address address;

  static class Address {
    String zipCode, city, street;
  }
}

interface PersonRepository extends Repository<Person, UUID> {

  {projection-collection}<Person> findByLastname(String lastname);
}
----
====

现在,假设我们只想检索此人的 `name` 属性.  Spring Data 提供什么手段来实现这一目标?  本章的其余部分将回答该问题.

[[projections.interfaces]]
== 基于接口的投影

将查询结果限制为仅 `name` 属性的最简单方法是声明一个接口,该接口暴露要读取的属性的 get 方法,如以下示例所示:

.一个投影接口来检索属性的子集
====
[source, java]
----
interface NamesOnly {

  String getFirstname();
  String getLastname();
}
----
====

此处重要的一点是,此处定义的属性与聚合根中的属性完全匹配.  这样做可以添加一个查询方法:

.一个使用基于接口的投影与查询方法的
====
[source, java, subs="+attributes"]
----
interface PersonRepository extends Repository<Person, UUID> {

  {projection-collection}<NamesOnly> findByLastname(String lastname);
}
----
====

查询执行引擎在运行时为每个返回的元素创建该接口的代理实例，并将对公开方法的调用转发给目标对象。

NOTE: 在 `Repository` 中声明一个覆盖 base 方法的方法（例如，在 `CrudRepository`、特定于存储的存储库接口或 `Simple...Repository` 中声明）会导致调用 base 方法，
而不管声明的内容如何返回类型。 确保使用兼容的返回类型，因为 base 方法不能用于投影。 一些存储模块支持 `@Query` 注解以将覆盖的 base 方法转换为查询方法，然后可用于返回投影。

[[projections.interfaces.nested]]
投影可以递归使用.  如果还希望包括一些 `Address` 信息,则为此创建一个投影接口,并从 `getAddress()` 的声明返回该接口,如以下示例所示:

.检索一个属性子集的投影接口
====
[source, java]
----
interface PersonSummary {

  String getFirstname();
  String getLastname();
  AddressSummary getAddress();

  interface AddressSummary {
    String getCity();
  }
}
----
====

在方法调用时,将获得目标实例的 `address` 属性,并将其包装到投影代理中.

[[projections.interfaces.closed]]
=== 封闭投影

一个投影接口，其访问器（accessor）方法都与目标集合的属性相匹配，被认为是一个封闭的投影。下面的例子（我们在本章前面也用过）就是一个封闭投影。

.一个封闭的投影
====
[source, java]
----
interface NamesOnly {

  String getFirstname();
  String getLastname();
}
----
====

如果您使用封闭投影,Spring Data 可以优化查询执行,因为我们知道支持投影代理所需的所有属性.  有关更多信息,请参见参考文档中特定于模块的部分.

[[projections.interfaces.open]]
=== 打开投影

投影接口中的访问器方法也可以通过使用 `@Value` 注解来计算新值,如以下示例所示:

[[projections.interfaces.open.simple]]
.一个 打开投影
====
[source, java]
----
interface NamesOnly {

  @Value("#{target.firstname + ' ' + target.lastname}")
  String getFullName();
  …
}
----
====

在  `target`  变量中提供了支持投影的聚合根.  使用 `@Value` 的投影接口是开放式投影.  在这种情况下,Spring Data 无法应用查询执行优化,因为 SpEL 表达式可以使用聚合根的任何属性.

`@Value` 中使用的表达式应该不太复杂-您要避免在 `String` 变量中进行编程.  对于非常简单的表达式,一种选择可能是求助于默认方法 (在 Java 8 中引入) ,如以下示例所示:

[[projections.interfaces.open.default]]
.使用默认方法自定义逻辑的投影接口
====
[source, java]
----
interface NamesOnly {

  String getFirstname();
  String getLastname();

  default String getFullName() {
    return getFirstname().concat(" ").concat(getLastname());
  }
}
----
====

这种方法要求您能够完全基于投影接口上暴露的其他访问器方法来实现逻辑。  第二个更灵活的选择是在 Spring bean 中实现自定义逻辑,然后从 SpEL 表达式中调用该自定义逻辑,如以下示例所示:

[[projections.interfaces.open.bean-reference]]
.简单 Person 对象
====
[source, java]
----
@Component
class MyBean {

  String getFullName(Person person) {
    …
  }
}

interface NamesOnly {

  @Value("#{@myBean.getFullName(target)}")
  String getFullName();
  …
}
----
====

请注意 SpEL 表达式如何引用 `myBean` 并调用  `getFullName(…)` 方法,并将投影目标作为方法参数转发.  SpEL 表达式评估支持的方法也可以使用方法参数,然后可以从表达式中引用这些参数.  方法参数可通过名为 `args` 的对象数组获得.
下面的示例演示如何从 `args` 数组获取方法参数:

.简单 Person 对象
====
[source, java]
----
interface NamesOnly {

  @Value("#{args[0] + ' ' + target.firstname + '!'}")
  String getSalutation(String prefix);
}
----
====

同样,对于更复杂的表达式,您应该使用 Spring bean 并让该表达式调用方法，<<projections.interfaces.open.bean-reference,如前所述>>.

[[projections.interfaces.nullable-wrappers]]
=== Nullable Wrappers

投影接口中的 getter 可以使用 nullable 的包装器， 以提高 null-safety 的安全性.  当前支持的包装器类型为:

* `java.util.Optional`
* `com.google.common.base.Optional`
* `scala.Option`
* `io.vavr.control.Option`

.使用 nullable 包装的投影接口
====
[source, java]
----
interface NamesOnly {

  Optional<String> getFirstname();
}
----
====

如果底层投影值不为  `null`， 那么将使用 wrapper 类型的当前表示法返回值。 如果默认值为 `null`， 则 getter 方法将返回使用的包装器类型的空表示形式.

[[projections.dtos]]
== 基于类的投影 (DTO)

定义投影的另一种方法是使用值类型 DTO (数据传输对象) ,它持有应该被检索的字段的属性。这些 DTO 类型的使用方式与投影接口的使用方式完全相同，只是没有代理发生，也不能应用嵌套投影。

如果存储库通过限制要加载的字段来优化查询的执行，要加载的字段是由暴露出来的构造函数的参数名决定的。

下面的例子显示了一个投影的 DTO:

.一个投影的 DTO
====
[source, java]
----
class NamesOnly {

  private final String firstname, lastname;

  NamesOnly(String firstname, String lastname) {

    this.firstname = firstname;
    this.lastname = lastname;
  }

  String getFirstname() {
    return this.firstname;
  }

  String getLastname() {
    return this.lastname;
  }

  // equals(…) and hashCode() implementations
}
----
====

[TIP]
.避免投影 DTO 的样板代码
====

您可以使用 https://projectlombok.org[Project Lombok] 大大简化 DTO 的代码,该项目提供了 `@Value` 注解 (不要与前面的界面示例中显示的 Spring 的 `@Value` 注解混淆) 。
如果您使用 Project Lombok 的 `@Value` 注解,则前面显示的示例 DTO 将变为以下内容:

[source, java]
----
@Value
class NamesOnly {
	String firstname, lastname;
}
----
默认情况下,字段是  `private final` 的,并且该类暴露了一个构造函数,该构造函数接受所有字段并自动获取实现的 `equals(…)` 和 `hashCode()` 方法.
====

ifdef::repository-projections-trailing-dto-fragment[]
include::{repository-projections-trailing-dto-fragment}[]
endif::[]

[[projection.dynamic]]
== 动态投影

到目前为止，我们已经使用投影类型作为集合的返回类型或元素类型。然而，你可能想在调用时选择要使用的类型（这使它成为动态的）。为了应用动态投影，请使用一个查询方法，如下面的例子中所示。

.使用动态投影参数的存储库
====
[source,java,subs="+attributes"]
----
interface PersonRepository extends Repository<Person, UUID> {

  <T> {projection-collection}<T> findByLastname(String lastname, Class<T> type);
}
----
====

通过这种方式,该方法可以按原样或应用投影来获得聚合,如下例所示:

.使用带有动态投影的存储库
====
[source,java,subs="+attributes"]
----
void someMethod(PersonRepository people) {

  {projection-collection}<Person> aggregates =
    people.findByLastname("Matthews", Person.class);

  {projection-collection}<NamesOnly> aggregates =
    people.findByLastname("Matthews", NamesOnly.class);
}
----
====

NOTE: 对 `Class` 类型的查询参数进行检查，看它们是否符合动态投影参数的条件。如果查询的实际返回类型与 `Class` 参数的通用参数类型相同，那么匹配的 `Class` 参数就不能在查询或 SpEL 表达式中使用。
如果你想使用一个 `Class` 参数作为查询参数，那么请确保使用不同的通用参数，例如 `Class<?>`。