[[kafka-connectconfigs]]
= Kafka Connect Configs

Kafka Connect framework 配置如下：

== config.storage.topic

The name of the Kafka topic where connector configurations are stored

|===
| 名称 | 值

| 类型
| string

| 默认值
|

| 有效值
|

| 重要性
| high
|===

== group.id

A unique string that identifies the Connect cluster group this worker belongs to.

|===
| 名称 | 值

| 类型
| string

| 默认值
|

| 有效值
|

| 重要性
| high
|===

== key.converter

Converter class used to convert between Kafka Connect format and the serialized form that is written to Kafka. This controls the format of the keys in messages written to or read from Kafka, and since this is independent of connectors it allows any connector to work with any serialization format. Examples of common formats include JSON and Avro.

|===
| 名称 | 值

| 类型
| class

| 默认值
|

| 有效值
|

| 重要性
| high
|===

== offset.storage.topic

The name of the Kafka topic where connector offsets are stored

|===
| 名称 | 值

| 类型
| string

| 默认值
|

| 有效值
|

| 重要性
| high
|===

== status.storage.topic

The name of the Kafka topic where connector and task status are stored

|===
| 名称 | 值

| 类型
| string

| 默认值
|

| 有效值
|

| 重要性
| high
|===

== value.converter

Converter class used to convert between Kafka Connect format and the serialized form that is written to Kafka. This controls the format of the values in messages written to or read from Kafka, and since this is independent of connectors it allows any connector to work with any serialization format. Examples of common formats include JSON and Avro.

|===
| 名称 | 值

| 类型
| class

| 默认值
|

| 有效值
|

| 重要性
| high
|===

== bootstrap.servers

A list of host/port pairs to use for establishing the initial connection to the Kafka cluster. The client will make use of all servers irrespective of which servers are specified here for bootstrapping—this list only impacts the initial hosts used to discover the full set of servers. This list should be in the form host1:port1,host2:port2,.... Since these servers are just used for the initial connection to discover the full cluster membership (which may change dynamically), this list need not contain the full set of servers (you may want more than one, though, in case a server is down).

|===
| 名称 | 值

| 类型
| list

| 默认值
| localhost:9092

| 有效值
|

| 重要性
| high
|===

== heartbeat.interval.ms

The expected time between heartbeats to the group coordinator when using Kafka's group management facilities. Heartbeats are used to ensure that the worker's session stays active and to facilitate rebalancing when new members join or leave the group. The value must be set lower than session.timeout.ms, but typically should be set no higher than 1/3 of that value. It can be adjusted even lower to control the expected time for normal rebalances.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 3000 (3 seconds)

| 有效值
|

| 重要性
| high
|===

== rebalance.timeout.ms

The maximum allowed time for each worker to join the group once a rebalance has begun. This is basically a limit on the amount of time needed for all tasks to flush any pending data and commit offsets. If the timeout is exceeded, then the worker will be removed from the group, which will cause offset commit failures.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 60000 (1 minute)

| 有效值
|

| 重要性
| high
|===

== session.timeout.ms

The timeout used to detect worker failures. The worker sends periodic heartbeats to indicate its liveness to the broker. If no heartbeats are received by the broker before the expiration of this session timeout, then the broker will remove the worker from the group and initiate a rebalance. Note that the value must be in the allowable range as configured in the broker configuration by group.min.session.timeout.ms and group.max.session.timeout.ms.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 10000 (10 seconds)

| 有效值
|

| 重要性
| high
|===

== ssl.key.password

The password of the private key in the key store file orthe PEM key specified in `ssl.keystore.key'. This is required for clients only if two-way authentication is configured.

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.keystore.certificate.chain

Certificate chain in the format specified by 'ssl.keystore.type'. Default SSL engine factory supports only PEM format with a list of X.509 certificates

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.keystore.key

Private key in the format specified by 'ssl.keystore.type'. Default SSL engine factory supports only PEM format with PKCS#8 keys. If the key is encrypted, key password must be specified using 'ssl.key.password'

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.keystore.location

The location of the key store file. This is optional for client and can be used for two-way authentication for client.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.keystore.password

The store password for the key store file. This is optional for client and only needed if 'ssl.keystore.location' is configured. Key store password is not supported for PEM format.

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.truststore.certificates

Trusted certificates in the format specified by 'ssl.truststore.type'. Default SSL engine factory supports only PEM format with X.509 certificates.

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.truststore.location

The location of the trust store file.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.truststore.password

The password for the trust store file. If a password is not set, trust store file configured will still be used, but integrity checking is disabled. Trust store password is not supported for PEM format.

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== client.dns.lookup

Controls how the client uses DNS lookups. If set to use_all_dns_ips, connect to each returned IP address in sequence until a successful connection is established. After a disconnection, the next IP is used. Once all IPs have been used once, the client resolves the IP(s) from the hostname again (both the JVM and the OS cache DNS name lookups, however). If set to resolve_canonical_bootstrap_servers_only, resolve each bootstrap address into a list of canonical names. After the bootstrap phase, this behaves the same as use_all_dns_ips.

|===
| 名称 | 值

| 类型
| string

| 默认值
| use_all_dns_ips

| 有效值
| [use_all_dns_ips, resolve_canonical_bootstrap_servers_only]

| 重要性
| medium
|===

== connections.max.idle.ms

Close idle connections after the number of milliseconds specified by this config.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 540000 (9 minutes)

| 有效值
|

| 重要性
| medium
|===

== connector.client.config.override.policy

Class name or alias of implementation of ConnectorClientConfigOverridePolicy. Defines what client configurations can be overriden by the connector. The default implementation is `All`, meaning connector configurations can override all client properties. The other possible policies in the framework include `None` to disallow connectors from overriding client properties, and `Principal` to allow connectors to override only client principals.

|===
| 名称 | 值

| 类型
| string

| 默认值
| All

| 有效值
|

| 重要性
| medium
|===

== receive.buffer.bytes

The size of the TCP receive buffer (SO_RCVBUF) to use when reading data. If the value is -1, the OS default will be used.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 32768 (32 kibibytes)

| 有效值
| [0,...]

| 重要性
| medium
|===

== request.timeout.ms

The configuration controls the maximum amount of time the client will wait for the response of a request. If the response is not received before the timeout elapses the client will resend the request if necessary or fail the request if retries are exhausted.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 40000 (40 seconds)

| 有效值
| [0,...]

| 重要性
| medium
|===

== sasl.client.callback.handler.class

The fully qualified name of a SASL client callback handler class that implements the AuthenticateCallbackHandler interface.

|===
| 名称 | 值

| 类型
| class

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.jaas.config

JAAS login context parameters for SASL connections in the format used by JAAS configuration files. JAAS configuration file format is described here. The format for the value is: loginModuleClass controlFlag (optionName=optionValue)*;. For brokers, the config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.jaas.config=com.example.ScramLoginModule required;

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.kerberos.service.name

The Kerberos principal name that Kafka runs as. This can be defined either in Kafka's JAAS config or in Kafka's config.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.login.callback.handler.class

The fully qualified name of a SASL login callback handler class that implements the AuthenticateCallbackHandler interface. For brokers, login callback handler config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.login.callback.handler.class=com.example.CustomScramLoginCallbackHandler

|===
| 名称 | 值

| 类型
| class

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.login.class

The fully qualified name of a class that implements the Login interface. For brokers, login config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.login.class=com.example.CustomScramLogin

|===
| 名称 | 值

| 类型
| class

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.mechanism

SASL mechanism used for client connections. This may be any mechanism for which a security provider is available. GSSAPI is the default mechanism.

|===
| 名称 | 值

| 类型
| string

| 默认值
| GSSAPI

| 有效值
|

| 重要性
| medium
|===

== security.protocol

Protocol used to communicate with brokers. Valid values are: PLAINTEXT, SSL, SASL_PLAINTEXT, SASL_SSL.

|===
| 名称 | 值

| 类型
| string

| 默认值
| PLAINTEXT

| 有效值
|

| 重要性
| medium
|===

== send.buffer.bytes

The size of the TCP send buffer (SO_SNDBUF) to use when sending data. If the value is -1, the OS default will be used.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 131072 (128 kibibytes)

| 有效值
| [0,...]

| 重要性
| medium
|===

== ssl.enabled.protocols

The list of protocols enabled for SSL connections. The default is 'TLSv1.2,TLSv1.3' when running with Java 11 or newer, 'TLSv1.2' otherwise. With the default value for Java 11, clients and servers will prefer TLSv1.3 if both support it and fallback to TLSv1.2 otherwise (assuming both support at least TLSv1.2). This default should be fine for most cases. Also see the config documentation for `ssl.protocol`.

|===
| 名称 | 值

| 类型
| list

| 默认值
| TLSv1.2

| 有效值
|

| 重要性
| medium
|===

== ssl.keystore.type

The file format of the key store file. This is optional for client.

|===
| 名称 | 值

| 类型
| string

| 默认值
| JKS

| 有效值
|

| 重要性
| medium
|===

== ssl.protocol

The SSL protocol used to generate the SSLContext. The default is 'TLSv1.3' when running with Java 11 or newer, 'TLSv1.2' otherwise. This value should be fine for most use cases. Allowed values in recent JVMs are 'TLSv1.2' and 'TLSv1.3'. 'TLS', 'TLSv1.1', 'SSL', 'SSLv2' and 'SSLv3' may be supported in older JVMs, but their usage is discouraged due to known security vulnerabilities. With the default value for this config and 'ssl.enabled.protocols', clients will downgrade to 'TLSv1.2' if the server does not support 'TLSv1.3'. If this config is set to 'TLSv1.2', clients will not use 'TLSv1.3' even if it is one of the values in ssl.enabled.protocols and the server only supports 'TLSv1.3'.

|===
| 名称 | 值

| 类型
| string

| 默认值
| TLSv1.2

| 有效值
|

| 重要性
| medium
|===

== ssl.provider

The name of the security provider used for SSL connections. Default value is the default security provider of the JVM.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== ssl.truststore.type

The file format of the trust store file.

|===
| 名称 | 值

| 类型
| string

| 默认值
| JKS

| 有效值
|

| 重要性
| medium
|===

== worker.sync.timeout.ms

When the worker is out of sync with other workers and needs to resynchronize configurations, wait up to this amount of time before giving up, leaving the group, and waiting a backoff period before rejoining.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 3000 (3 seconds)

| 有效值
|

| 重要性
| medium
|===

== worker.unsync.backoff.ms

When the worker is out of sync with other workers and fails to catch up within worker.sync.timeout.ms, leave the Connect cluster for this long before rejoining.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 300000 (5 minutes)

| 有效值
|

| 重要性
| medium
|===

== access.control.allow.methods

Sets the methods supported for cross origin requests by setting the Access-Control-Allow-Methods header. The default value of the Access-Control-Allow-Methods header allows cross origin requests for GET, POST and HEAD.

|===
| 名称 | 值

| 类型
| string

| 默认值
| ""

| 有效值
|

| 重要性
| low
|===

== access.control.allow.origin

Value to set the Access-Control-Allow-Origin header to for REST API requests.To enable cross origin access, set this to the domain of the application that should be permitted to access the API, or '*' to allow access from any domain. The default value only allows access from the domain of the REST API.

|===
| 名称 | 值

| 类型
| string

| 默认值
| ""

| 有效值
|

| 重要性
| low
|===

== admin.listeners

List of comma-separated URIs the Admin REST API will listen on. The supported protocols are HTTP and HTTPS. An empty or blank string will disable this feature. The default behavior is to use the regular listener (specified by the 'listeners' property).

|===
| 名称 | 值

| 类型
| list

| 默认值
| null

| 有效值
| List of comma-separated URLs, ex: http://localhost:8080,https://localhost:8443.

| 重要性
| low
|===

== client.id

An id string to pass to the server when making requests. The purpose of this is to be able to track the source of requests beyond just ip/port by allowing a logical application name to be included in server-side request logging.

|===
| 名称 | 值

| 类型
| string

| 默认值
| ""

| 有效值
|

| 重要性
| low
|===

== config.providers

Comma-separated names of ConfigProvider classes, loaded and used in the order specified. Implementing the interface ConfigProvider allows you to replace variable references in connector configurations, such as for externalized secrets.

|===
| 名称 | 值

| 类型
| list

| 默认值
| ""

| 有效值
|

| 重要性
| low
|===

== config.storage.replication.factor

Replication factor used when creating the configuration storage topic

|===
| 名称 | 值

| 类型
| short

| 默认值
| 3

| 有效值
| Positive number not larger than the number of brokers in the Kafka cluster, or -1 to use the broker's default

| 重要性
| low
|===

== connect.protocol

Compatibility mode for Kafka Connect Protocol

|===
| 名称 | 值

| 类型
| string

| 默认值
| sessioned

| 有效值
| [eager, compatible, sessioned]

| 重要性
| low
|===

== header.converter

HeaderConverter class used to convert between Kafka Connect format and the serialized form that is written to Kafka. This controls the format of the header values in messages written to or read from Kafka, and since this is independent of connectors it allows any connector to work with any serialization format. Examples of common formats include JSON and Avro. By default, the SimpleHeaderConverter is used to serialize header values to strings and deserialize them by inferring the schemas.

|===
| 名称 | 值

| 类型
| class

| 默认值
| org.apache.kafka.connect.storage.SimpleHeaderConverter

| 有效值
|

| 重要性
| low
|===

== inter.worker.key.generation.algorithm

The algorithm to use for generating internal request keys

|===
| 名称 | 值

| 类型
| string

| 默认值
| HmacSHA256

| 有效值
| Any KeyGenerator algorithm supported by the worker JVM

| 重要性
| low
|===

== inter.worker.key.size

The size of the key to use for signing internal requests, in bits. If null, the default key size for the key generation algorithm will be used.

|===
| 名称 | 值

| 类型
| int

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== inter.worker.key.ttl.ms

The TTL of generated session keys used for internal request validation (in milliseconds)

|===
| 名称 | 值

| 类型
| int

| 默认值
| 3600000 (1 hour)

| 有效值
| [0,...,2147483647]

| 重要性
| low
|===

== inter.worker.signature.algorithm

The algorithm used to sign internal requests

|===
| 名称 | 值

| 类型
| string

| 默认值
| HmacSHA256

| 有效值
| Any MAC algorithm supported by the worker JVM

| 重要性
| low
|===

== inter.worker.verification.algorithms

A list of permitted algorithms for verifying internal requests

|===
| 名称 | 值

| 类型
| list

| 默认值
| HmacSHA256

| 有效值
| A list of one or more MAC algorithms, each supported by the worker JVM

| 重要性
| low
|===

== listeners

List of comma-separated URIs the REST API will listen on. The supported protocols are HTTP and HTTPS.
Specify hostname as 0.0.0.0 to bind to all interfaces.
Leave hostname empty to bind to default interface.
Examples of legal listener lists: HTTP://myhost:8083,HTTPS://myhost:8084

|===
| 名称 | 值

| 类型
| list

| 默认值
| http://:8083

| 有效值
| List of comma-separated URLs, ex: http://localhost:8080,https://localhost:8443

| 重要性
| low
|===

== metadata.max.age.ms

The period of time in milliseconds after which we force a refresh of metadata even if we haven't seen any partition leadership changes to proactively discover any new brokers or partitions.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 300000 (5 minutes)

| 有效值
| [0,...]

| 重要性
| low
|===

== metric.reporters

A list of classes to use as metrics reporters. Implementing the org.apache.kafka.common.metrics.MetricsReporter interface allows plugging in classes that will be notified of new metric creation. The JmxReporter is always included to register JMX statistics.

|===
| 名称 | 值

| 类型
| list

| 默认值
| ""

| 有效值
|

| 重要性
| low
|===

== metrics.num.samples

The number of samples maintained to compute metrics.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 2

| 有效值
| [1,...]

| 重要性
| low
|===

== metrics.recording.level

The highest recording level for metrics.

|===
| 名称 | 值

| 类型
| string

| 默认值
| INFO

| 有效值
| [INFO, DEBUG]

| 重要性
| low
|===

== metrics.sample.window.ms

The window of time a metrics sample is computed over.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 30000 (30 seconds)

| 有效值
| [0,...]

| 重要性
| low
|===

== offset.flush.interval.ms

Interval at which to try committing offsets for tasks.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 60000 (1 minute)

| 有效值
|

| 重要性
| low
|===

== offset.flush.timeout.ms

Maximum number of milliseconds to wait for records to flush and partition offset data to be committed to offset storage before cancelling the process and restoring the offset data to be committed in a future attempt.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 5000 (5 seconds)

| 有效值
|

| 重要性
| low
|===

== offset.storage.partitions

The number of partitions used when creating the offset storage topic

|===
| 名称 | 值

| 类型
| int

| 默认值
| 25

| 有效值
| Positive number, or -1 to use the broker's default

| 重要性
| low
|===

== offset.storage.replication.factor

Replication factor used when creating the offset storage topic

|===
| 名称 | 值

| 类型
| short

| 默认值
| 3

| 有效值
| Positive number not larger than the number of brokers in the Kafka cluster, or -1 to use the broker's default

| 重要性
| low
|===

== plugin.path

List of paths separated by commas (,) that contain plugins (connectors, converters, transformations). The list should consist of top level directories that include any combination of:
a) directories immediately containing jars with plugins and their dependencies
b) uber-jars with plugins and their dependencies
c) directories immediately containing the package directory structure of classes of plugins and their dependencies
Note: symlinks will be followed to discover dependencies or plugins.
Examples: plugin.path=/usr/local/share/java,/usr/local/share/kafka/plugins,/opt/connectors
Do not use config provider variables in this property, since the raw path is used by the worker's scanner before config providers are initialized and used to replace variables.

|===
| 名称 | 值

| 类型
| list

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== reconnect.backoff.max.ms

The maximum amount of time in milliseconds to wait when reconnecting to a broker that has repeatedly failed to connect. If provided, the backoff per host will increase exponentially for each consecutive connection failure, up to this maximum. After calculating the backoff increase, 20% random jitter is added to avoid connection storms.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 1000 (1 second)

| 有效值
| [0,...]

| 重要性
| low
|===

== reconnect.backoff.ms

The base amount of time to wait before attempting to reconnect to a given host. This avoids repeatedly connecting to a host in a tight loop. This backoff applies to all connection attempts by the client to a broker.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 50

| 有效值
| [0,...]

| 重要性
| low
|===

== response.http.headers.config

Rules for REST API HTTP response headers

|===
| 名称 | 值

| 类型
| string

| 默认值
| ""

| 有效值
| Comma-separated header rules, where each header rule is of the form '[action] [header name]:[header value]' and optionally surrounded by double quotes if any part of a header rule contains a comma

| 重要性
| low
|===

== rest.advertised.host.name

If this is set, this is the hostname that will be given out to other workers to connect to.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== rest.advertised.listener

Sets the advertised listener (HTTP or HTTPS) which will be given to other workers to use.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== rest.advertised.port

If this is set, this is the port that will be given out to other workers to connect to.

|===
| 名称 | 值

| 类型
| int

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== rest.advertised.port

If this is set, this is the port that will be given out to other workers to connect to.

|===
| 名称 | 值

| 类型
| int

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== rest.extension.classes

Comma-separated names of ConnectRestExtension classes, loaded and called in the order specified. Implementing the interface ConnectRestExtension allows you to inject into Connect's REST API user defined resources like filters. Typically used to add custom capability like logging, security, etc.

|===
| 名称 | 值

| 类型
| list

| 默认值
| ""

| 有效值
|

| 重要性
| low
|===

== retry.backoff.ms

The amount of time to wait before attempting to retry a failed request to a given topic partition. This avoids repeatedly sending requests in a tight loop under some failure scenarios.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 100

| 有效值
| [0,...]

| 重要性
| low
|===

== sasl.kerberos.kinit.cmd

Kerberos kinit command path.

|===
| 名称 | 值

| 类型
| string

| 默认值
| /usr/bin/kinit

| 有效值
|

| 重要性
| low
|===

== sasl.kerberos.min.time.before.relogin

Login thread sleep time between refresh attempts.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 60000

| 有效值
|

| 重要性
| low
|===

== sasl.kerberos.ticket.renew.jitter

Percentage of random jitter added to the renewal time.

|===
| 名称 | 值

| 类型
| double

| 默认值
| 0.05

| 有效值
|

| 重要性
| low
|===

== sasl.kerberos.ticket.renew.window.factor

Login thread will sleep until the specified window factor of time from last refresh to ticket's expiry has been reached, at which time it will try to renew the ticket.

|===
| 名称 | 值

| 类型
| double

| 默认值
| 0.8

| 有效值
|

| 重要性
| low
|===

== sasl.login.refresh.buffer.seconds

The amount of buffer time before credential expiration to maintain when refreshing a credential, in seconds. If a refresh would otherwise occur closer to expiration than the number of buffer seconds then the refresh will be moved up to maintain as much of the buffer time as possible. Legal values are between 0 and 3600 (1 hour); a default value of 300 (5 minutes) is used if no value is specified. This value and sasl.login.refresh.min.period.seconds are both ignored if their sum exceeds the remaining lifetime of a credential. Currently applies only to OAUTHBEARER.

|===
| 名称 | 值

| 类型
| short

| 默认值
| 300

| 有效值
| [0,...,3600]

| 重要性
| low
|===

== sasl.login.refresh.min.period.seconds

The desired minimum time for the login refresh thread to wait before refreshing a credential, in seconds. Legal values are between 0 and 900 (15 minutes); a default value of 60 (1 minute) is used if no value is specified. This value and sasl.login.refresh.buffer.seconds are both ignored if their sum exceeds the remaining lifetime of a credential. Currently applies only to OAUTHBEARER.

|===
| 名称 | 值

| 类型
| short

| 默认值
| 60

| 有效值
| [0,...,900]

| 重要性
| low
|===

== sasl.login.refresh.window.factor

Login refresh thread will sleep until the specified window factor relative to the credential's lifetime has been reached, at which time it will try to refresh the credential. Legal values are between 0.5 (50%) and 1.0 (100%) inclusive; a default value of 0.8 (80%) is used if no value is specified. Currently applies only to OAUTHBEARER.

|===
| 名称 | 值

| 类型
| double

| 默认值
| 0.8

| 有效值
| [0.5,...,1.0]

| 重要性
| low
|===

== sasl.login.refresh.window.jitter

The maximum amount of random jitter relative to the credential's lifetime that is added to the login refresh thread's sleep time. Legal values are between 0 and 0.25 (25%) inclusive; a default value of 0.05 (5%) is used if no value is specified. Currently applies only to OAUTHBEARER.

|===
| 名称 | 值

| 类型
| double

| 默认值
| 0.05

| 有效值
| [0.0,...,0.25]

| 重要性
| low
|===

== scheduled.rebalance.max.delay.ms

The maximum delay that is scheduled in order to wait for the return of one or more departed workers before rebalancing and reassigning their connectors and tasks to the group. During this period the connectors and tasks of the departed workers remain unassigned

|===
| 名称 | 值

| 类型
| int

| 默认值
| 300000 (5 minutes)

| 有效值
| [0,...,2147483647]

| 重要性
| low
|===

== socket.connection.setup.timeout.max.ms

The maximum amount of time the client will wait for the socket connection to be established. The connection setup timeout will increase exponentially for each consecutive connection failure up to this maximum. To avoid connection storms, a randomization factor of 0.2 will be applied to the timeout resulting in a random range between 20% below and 20% above the computed value.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 30000 (30 seconds)

| 有效值
| [0,...]

| 重要性
| low
|===

== socket.connection.setup.timeout.ms

The amount of time the client will wait for the socket connection to be established. If the connection is not built before the timeout elapses, clients will close the socket channel.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 10000 (10 seconds)

| 有效值
| [0,...]

| 重要性
| low
|===

== ssl.cipher.suites

A list of cipher suites. This is a named combination of authentication, encryption, MAC and key exchange algorithm used to negotiate the security settings for a network connection using TLS or SSL network protocol. By default all the available cipher suites are supported.

|===
| 名称 | 值

| 类型
| list

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== ssl.client.auth

Configures kafka broker to request client authentication. The following settings are common:

* ssl.client.auth=required If set to required client authentication is required.
* ssl.client.auth=requested This means client authentication is optional. unlike required, if this option is set client can choose not to provide authentication information about itself
* ssl.client.auth=none This means client authentication is not needed.

|===
| 名称 | 值

| 类型
| string

| 默认值
| none

| 有效值
|

| 重要性
| low
|===

== ssl.endpoint.identification.algorithm

The endpoint identification algorithm to validate server hostname using server certificate.

|===
| 名称 | 值

| 类型
| string

| 默认值
| https

| 有效值
|

| 重要性
| low
|===

== ssl.engine.factory.class

The class of type org.apache.kafka.common.security.auth.SslEngineFactory to provide SSLEngine objects. Default value is org.apache.kafka.common.security.ssl.DefaultSslEngineFactory

|===
| 名称 | 值

| 类型
| class

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== ssl.keymanager.algorithm

The algorithm used by key manager factory for SSL connections. Default value is the key manager factory algorithm configured for the Java Virtual Machine.

|===
| 名称 | 值

| 类型
| string

| 默认值
| SunX509

| 有效值
|

| 重要性
| low
|===

== ssl.secure.random.implementation

The SecureRandom PRNG implementation to use for SSL cryptography operations.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== ssl.trustmanager.algorithm

The algorithm used by trust manager factory for SSL connections. Default value is the trust manager factory algorithm configured for the Java Virtual Machine.

|===
| 名称 | 值

| 类型
| string

| 默认值
| PKIX

| 有效值
|

| 重要性
| low
|===

== status.storage.partitions

The number of partitions used when creating the status storage topic

|===
| 名称 | 值

| 类型
| int

| 默认值
| 5

| 有效值
| Positive number, or -1 to use the broker's default

| 重要性
| low
|===

== status.storage.replication.factor

Replication factor used when creating the status storage topic

|===
| 名称 | 值

| 类型
| short

| 默认值
| 3

| 有效值
| Positive number not larger than the number of brokers in the Kafka cluster, or -1 to use the broker's default

| 重要性
| low
|===

== task.shutdown.graceful.timeout.ms

Amount of time to wait for tasks to shutdown gracefully. This is the total amount of time, not per task. All task have shutdown triggered, then they are waited on sequentially.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 5000 (5 seconds)

| 有效值
|

| 重要性
| low
|===

== topic.creation.enable

Whether to allow automatic creation of topics used by source connectors, when source connectors are configured with `topic.creation.` properties. Each task will use an admin client to create its topics and will not depend on the Kafka brokers to create topics automatically.

|===
| 名称 | 值

| 类型
| boolean

| 默认值
| true

| 有效值
|

| 重要性
| low
|===

== topic.tracking.allow.reset

If set to true, it allows user requests to reset the set of active topics per connector.

|===
| 名称 | 值

| 类型
| boolean

| 默认值
| true

| 有效值
|

| 重要性
| low
|===

== topic.tracking.enable

Enable tracking the set of active topics per connector during runtime.

|===
| 名称 | 值

| 类型
| boolean

| 默认值
| true

| 有效值
|

| 重要性
| low
|===