[[kafka-consumerconfigs]]
= Consumer Configs（消费者配置）

consumer 配置如下：

== key.deserializer

Deserializer class for key that implements the org.apache.kafka.common.serialization.Deserializer interface.

|===
| 名称 | 值

| 类型
| class

| 默认值
|

| 有效值
|

| 重要性
| high
|===

== value.deserializer

Deserializer class for value that implements the org.apache.kafka.common.serialization.Deserializer interface.

|===
| 名称 | 值

| 类型
| class

| 默认值
|

| 有效值
|

| 重要性
| high
|===

== bootstrap.servers

A list of host/port pairs to use for establishing the initial connection to the Kafka cluster. The client will make use of all servers irrespective of which servers are specified here for bootstrapping—this list only impacts the initial hosts used to discover the full set of servers. This list should be in the form host1:port1,host2:port2,.... Since these servers are just used for the initial connection to discover the full cluster membership (which may change dynamically), this list need not contain the full set of servers (you may want more than one, though, in case a server is down).

|===
| 名称 | 值

| 类型
| list

| 默认值
| ""

| 有效值
| non-null string

| 重要性
| high
|===

== fetch.min.bytes

The minimum amount of data the server should return for a fetch request. If insufficient data is available the request will wait for that much data to accumulate before answering the request. The default setting of 1 byte means that fetch requests are answered as soon as a single byte of data is available or the fetch request times out waiting for data to arrive. Setting this to something greater than 1 will cause the server to wait for larger amounts of data to accumulate which can improve server throughput a bit at the cost of some additional latency.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 1

| 有效值
| [0,...]

| 重要性
| high
|===

== group.id

A unique string that identifies the consumer group this consumer belongs to. This property is required if the consumer uses either the group management functionality by using subscribe(topic) or the Kafka-based offset management strategy.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== heartbeat.interval.ms

The expected time between heartbeats to the consumer coordinator when using Kafka's group management facilities. Heartbeats are used to ensure that the consumer's session stays active and to facilitate rebalancing when new consumers join or leave the group. The value must be set lower than session.timeout.ms, but typically should be set no higher than 1/3 of that value. It can be adjusted even lower to control the expected time for normal rebalances.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 3000 (3 seconds)

| 有效值
|

| 重要性
| high
|===

== max.partition.fetch.bytes

The maximum amount of data per-partition the server will return. Records are fetched in batches by the consumer. If the first record batch in the first non-empty partition of the fetch is larger than this limit, the batch will still be returned to ensure that the consumer can make progress. The maximum record batch size accepted by the broker is defined via message.max.bytes (broker config) or max.message.bytes (topic config). See fetch.max.bytes for limiting the consumer request size.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 1048576 (1 mebibyte)

| 有效值
| [0,...]

| 重要性
| high
|===

== session.timeout.ms

The timeout used to detect client failures when using Kafka's group management facility. The client sends periodic heartbeats to indicate its liveness to the broker. If no heartbeats are received by the broker before the expiration of this session timeout, then the broker will remove this client from the group and initiate a rebalance. Note that the value must be in the allowable range as configured in the broker configuration by group.min.session.timeout.ms and group.max.session.timeout.ms.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 45000 (45 seconds)

| 有效值
|

| 重要性
| high
|===

== ssl.key.password

The password of the private key in the key store file orthe PEM key specified in `ssl.keystore.key'. This is required for clients only if two-way authentication is configured.

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.keystore.certificate.chain

Certificate chain in the format specified by 'ssl.keystore.type'. Default SSL engine factory supports only PEM format with a list of X.509 certificates

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.keystore.key

Private key in the format specified by 'ssl.keystore.type'. Default SSL engine factory supports only PEM format with PKCS#8 keys. If the key is encrypted, key password must be specified using 'ssl.key.password'

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.keystore.location

The location of the key store file. This is optional for client and can be used for two-way authentication for client.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.keystore.password

The store password for the key store file. This is optional for client and only needed if 'ssl.keystore.location' is configured. Key store password is not supported for PEM format.

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.truststore.certificates

Trusted certificates in the format specified by 'ssl.truststore.type'. Default SSL engine factory supports only PEM format with X.509 certificates.

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.truststore.location

The location of the trust store file.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.truststore.password

The password for the trust store file. If a password is not set, trust store file configured will still be used, but integrity checking is disabled. Trust store password is not supported for PEM format.

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== allow.auto.create.topics

Allow automatic topic creation on the broker when subscribing to or assigning a topic. A topic being subscribed to will be automatically created only if the broker allows for it using `auto.create.topics.enable` broker configuration. This configuration must be set to `false` when using brokers older than 0.11.0

|===
| 名称 | 值

| 类型
| boolean

| 默认值
| true

| 有效值
|

| 重要性
| medium
|===

== auto.offset.reset

What to do when there is no initial offset in Kafka or if the current offset does not exist any more on the server (e.g. because that data has been deleted):

* earliest: automatically reset the offset to the earliest offset
* latest: automatically reset the offset to the latest offset
* none: throw exception to the consumer if no previous offset is found for the consumer's group
* anything else: throw exception to the consumer.

|===
| 名称 | 值

| 类型
| string

| 默认值
| latest

| 有效值
| [latest, earliest, none]

| 重要性
| medium
|===

== client.dns.lookup

Controls how the client uses DNS lookups. If set to `use_all_dns_ips`, connect to each returned IP address in sequence until a successful connection is established. After a disconnection, the next IP is used. Once all IPs have been used once, the client resolves the IP(s) from the hostname again (both the JVM and the OS cache DNS name lookups, however). If set to `resolve_canonical_bootstrap_servers_only`, resolve each bootstrap address into a list of canonical names. After the bootstrap phase, this behaves the same as `use_all_dns_ips`.

|===
| 名称 | 值

| 类型
| string

| 默认值
| use_all_dns_ips

| 有效值
| [use_all_dns_ips, resolve_canonical_bootstrap_servers_only]

| 重要性
| medium
|===

== connections.max.idle.ms

Close idle connections after the number of milliseconds specified by this config.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 540000 (9 minutes)

| 有效值
|

| 重要性
| medium
|===

== default.api.timeout.ms

Specifies the timeout (in milliseconds) for client APIs. This configuration is used as the default timeout for all client operations that do not specify a timeout parameter.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 60000 (1 minute)

| 有效值
| [0,...]

| 重要性
| medium
|===

== exclude.internal.topics

Whether internal topics matching a subscribed pattern should be excluded from the subscription. It is always possible to explicitly subscribe to an internal topic.

|===
| 名称 | 值

| 类型
| boolean

| 默认值
| true

| 有效值
|

| 重要性
| medium
|===

== fetch.max.bytes

The maximum amount of data the server should return for a fetch request. Records are fetched in batches by the consumer, and if the first record batch in the first non-empty partition of the fetch is larger than this value, the record batch will still be returned to ensure that the consumer can make progress. As such, this is not a absolute maximum. The maximum record batch size accepted by the broker is defined via message.max.bytes (broker config) or max.message.bytes (topic config). Note that the consumer performs multiple fetches in parallel.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 52428800 (50 mebibytes)

| 有效值
| [0,...]

| 重要性
| medium
|===

== group.instance.id

A unique identifier of the consumer instance provided by the end user. Only non-empty strings are permitted. If set, the consumer is treated as a static member, which means that only one instance with this ID is allowed in the consumer group at any time. This can be used in combination with a larger session timeout to avoid group rebalances caused by transient unavailability (e.g. process restarts). If not set, the consumer will join the group as a dynamic member, which is the traditional behavior.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== isolation.level

Controls how to read messages written transactionally. If set to read_committed, consumer.poll() will only return transactional messages which have been committed. If set to read_uncommitted (the default), consumer.poll() will return all messages, even transactional messages which have been aborted. Non-transactional messages will be returned unconditionally in either mode.

Messages will always be returned in offset order. Hence, in read_committed mode, consumer.poll() will only return messages up to the last stable offset (LSO), which is the one less than the offset of the first open transaction. In particular any messages appearing after messages belonging to ongoing transactions will be withheld until the relevant transaction has been completed. As a result, read_committed consumers will not be able to read up to the high watermark when there are in flight transactions.

Further, when in read_committed the seekToEnd method will return the LSO

|===
| 名称 | 值

| 类型
| string

| 默认值
| read_uncommitted

| 有效值
| [read_committed, read_uncommitted]

| 重要性
| medium
|===

== max.poll.interval.ms

The maximum delay between invocations of poll() when using consumer group management. This places an upper bound on the amount of time that the consumer can be idle before fetching more records. If poll() is not called before expiration of this timeout, then the consumer is considered failed and the group will rebalance in order to reassign the partitions to another member. For consumers using a non-null group.instance.id which reach this timeout, partitions will not be immediately reassigned. Instead, the consumer will stop sending heartbeats and partitions will be reassigned after expiration of session.timeout.ms. This mirrors the behavior of a static consumer which has shutdown.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 300000 (5 minutes)

| 有效值
| [1,...]

| 重要性
| medium
|===

== max.poll.records

The maximum number of records returned in a single call to poll(). Note, that max.poll.records does not impact the underlying fetching behavior. The consumer will cache the records from each fetch request and returns them incrementally from each poll.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 500

| 有效值
| [1,...]

| 重要性
| medium
|===

== partition.assignment.strategy

A list of class names or class types, ordered by preference, of supported partition assignment strategies that the client will use to distribute partition ownership amongst consumer instances when group management is used. Available options are:

* org.apache.kafka.clients.consumer.RangeAssignor: Assigns partitions on a per-topic basis.
* org.apache.kafka.clients.consumer.RoundRobinAssignor: Assigns partitions to consumers in a round-robin fashion.
* org.apache.kafka.clients.consumer.StickyAssignor: Guarantees an assignment that is maximally balanced while preserving as many existing partition assignments as possible.
* org.apache.kafka.clients.consumer.CooperativeStickyAssignor: Follows the same StickyAssignor logic, but allows for cooperative rebalancing.

The default assignor is [RangeAssignor, CooperativeStickyAssignor], which will use the RangeAssignor by default, but allows upgrading to the CooperativeStickyAssignor with just a single rolling bounce that removes the RangeAssignor from the list.

Implementing the org.apache.kafka.clients.consumer.ConsumerPartitionAssignor interface allows you to plug in a custom assignment strategy.

|===
| 名称 | 值

| 类型
| list

| 默认值
| class org.apache.kafka.clients.consumer.RangeAssignor,class org.apache.kafka.clients.consumer.CooperativeStickyAssignor

| 有效值
| non-null string

| 重要性
| non-null string
|===

== receive.buffer.bytes

The size of the TCP receive buffer (SO_RCVBUF) to use when reading data. If the value is -1, the OS default will be used.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 65536 (64 kibibytes)

| 有效值
| [-1,...]

| 重要性
| medium
|===

== request.timeout.ms

The configuration controls the maximum amount of time the client will wait for the response of a request. If the response is not received before the timeout elapses the client will resend the request if necessary or fail the request if retries are exhausted.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 30000 (30 seconds)

| 有效值
| [0,...]

| 重要性
| medium
|===

== sasl.client.callback.handler.class

The fully qualified name of a SASL client callback handler class that implements the AuthenticateCallbackHandler interface.

|===
| 名称 | 值

| 类型
| class

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.jaas.config

JAAS login context parameters for SASL connections in the format used by JAAS configuration files. JAAS configuration file format is described here. The format for the value is: loginModuleClass controlFlag (optionName=optionValue)*;. For brokers, the config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.jaas.config=com.example.ScramLoginModule required;

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.kerberos.service.name

The Kerberos principal name that Kafka runs as. This can be defined either in Kafka's JAAS config or in Kafka's config.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.login.callback.handler.class

The fully qualified name of a SASL login callback handler class that implements the AuthenticateCallbackHandler interface. For brokers, login callback handler config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.login.callback.handler.class=com.example.CustomScramLoginCallbackHandler

|===
| 名称 | 值

| 类型
| class

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.login.class

The fully qualified name of a class that implements the Login interface. For brokers, login config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.login.class=com.example.CustomScramLogin

|===
| 名称 | 值

| 类型
| class

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.mechanism

SASL mechanism used for client connections. This may be any mechanism for which a security provider is available. GSSAPI is the default mechanism.

|===
| 名称 | 值

| 类型
| string

| 默认值
| GSSAPI

| 有效值
|

| 重要性
| medium
|===

== security.protocol

Protocol used to communicate with brokers. Valid values are: PLAINTEXT, SSL, SASL_PLAINTEXT, SASL_SSL.

|===
| 名称 | 值

| 类型
| string

| 默认值
| PLAINTEXT

| 有效值
|

| 重要性
| medium
|===

== send.buffer.bytes

The size of the TCP send buffer (SO_SNDBUF) to use when sending data. If the value is -1, the OS default will be used.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 131072 (128 kibibytes)

| 有效值
| [-1,...]

| 重要性
| medium
|===

== socket.connection.setup.timeout.max.ms

The maximum amount of time the client will wait for the socket connection to be established. The connection setup timeout will increase exponentially for each consecutive connection failure up to this maximum. To avoid connection storms, a randomization factor of 0.2 will be applied to the timeout resulting in a random range between 20% below and 20% above the computed value.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 30000 (30 seconds)

| 有效值
|

| 重要性
| medium
|===

== socket.connection.setup.timeout.ms

The amount of time the client will wait for the socket connection to be established. If the connection is not built before the timeout elapses, clients will close the socket channel.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 10000 (10 seconds)

| 有效值
|

| 重要性
| medium
|===

== ssl.enabled.protocols

The list of protocols enabled for SSL connections. The default is 'TLSv1.2,TLSv1.3' when running with Java 11 or newer, 'TLSv1.2' otherwise. With the default value for Java 11, clients and servers will prefer TLSv1.3 if both support it and fallback to TLSv1.2 otherwise (assuming both support at least TLSv1.2). This default should be fine for most cases. Also see the config documentation for `ssl.protocol`.

|===
| 名称 | 值

| 类型
| list

| 默认值
| TLSv1.2

| 有效值
|

| 重要性
| medium
|===

== ssl.keystore.type

The file format of the key store file. This is optional for client.

|===
| 名称 | 值

| 类型
| string

| 默认值
| JKS

| 有效值
|

| 重要性
| medium
|===

== ssl.protocol

The SSL protocol used to generate the SSLContext. The default is 'TLSv1.3' when running with Java 11 or newer, 'TLSv1.2' otherwise. This value should be fine for most use cases. Allowed values in recent JVMs are 'TLSv1.2' and 'TLSv1.3'. 'TLS', 'TLSv1.1', 'SSL', 'SSLv2' and 'SSLv3' may be supported in older JVMs, but their usage is discouraged due to known security vulnerabilities. With the default value for this config and 'ssl.enabled.protocols', clients will downgrade to 'TLSv1.2' if the server does not support 'TLSv1.3'. If this config is set to 'TLSv1.2', clients will not use 'TLSv1.3' even if it is one of the values in ssl.enabled.protocols and the server only supports 'TLSv1.3'.

|===
| 名称 | 值

| 类型
| string

| 默认值
| TLSv1.2

| 有效值
|

| 重要性
| medium
|===

== ssl.provider

The name of the security provider used for SSL connections. Default value is the default security provider of the JVM.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== ssl.truststore.type

The file format of the trust store file.

|===
| 名称 | 值

| 类型
| string

| 默认值
| JKS

| 有效值
|

| 重要性
| medium
|===

== auto.commit.interval.ms

The frequency in milliseconds that the consumer offsets are auto-committed to Kafka if enable.auto.commit is set to true.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 5000 (5 seconds)

| 有效值
| [0,...]

| 重要性
| low
|===

== check.crcs

Automatically check the CRC32 of the records consumed. This ensures no on-the-wire or on-disk corruption to the messages occurred. This check adds some overhead, so it may be disabled in cases seeking extreme performance.

|===
| 名称 | 值

| 类型
| boolean

| 默认值
| true

| 有效值
|

| 重要性
| low
|===

== client.id

An id string to pass to the server when making requests. The purpose of this is to be able to track the source of requests beyond just ip/port by allowing a logical application name to be included in server-side request logging.

|===
| 名称 | 值

| 类型
| string

| 默认值
| ""

| 有效值
|

| 重要性
| low
|===

== client.rack

A rack identifier for this client. This can be any string value which indicates where this client is physically located. It corresponds with the broker config 'broker.rack'

|===
| 名称 | 值

| 类型
| string

| 默认值
| ""

| 有效值
|

| 重要性
| low
|===

== fetch.max.wait.ms

The maximum amount of time the server will block before answering the fetch request if there isn't sufficient data to immediately satisfy the requirement given by fetch.min.bytes.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 500

| 有效值
| [0,...]

| 重要性
| low
|===

== interceptor.classes

A list of classes to use as interceptors. Implementing the org.apache.kafka.clients.consumer.ConsumerInterceptor interface allows you to intercept (and possibly mutate) records received by the consumer. By default, there are no interceptors.

|===
| 名称 | 值

| 类型
| list

| 默认值
| ""

| 有效值
| non-null string

| 重要性
| low
|===

== metadata.max.age.ms

The period of time in milliseconds after which we force a refresh of metadata even if we haven't seen any partition leadership changes to proactively discover any new brokers or partitions.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 300000 (5 minutes)

| 有效值
| [0,...]

| 重要性
| low
|===

== metric.reporters

A list of classes to use as metrics reporters. Implementing the org.apache.kafka.common.metrics.MetricsReporter interface allows plugging in classes that will be notified of new metric creation. The JmxReporter is always included to register JMX statistics.

|===
| 名称 | 值

| 类型
| list

| 默认值
| ""

| 有效值
| non-null string

| 重要性
| low
|===

== metrics.num.samples

The number of samples maintained to compute metrics.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 2

| 有效值
| [1,...]

| 重要性
| low
|===

== metrics.recording.level

The highest recording level for metrics.

|===
| 名称 | 值

| 类型
| string

| 默认值
| INFO

| 有效值
| [INFO, DEBUG, TRACE]

| 重要性
| low
|===

== metrics.sample.window.ms

The window of time a metrics sample is computed over.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 30000 (30 seconds)

| 有效值
| [0,...]

| 重要性
| low
|===

== reconnect.backoff.max.ms

The maximum amount of time in milliseconds to wait when reconnecting to a broker that has repeatedly failed to connect. If provided, the backoff per host will increase exponentially for each consecutive connection failure, up to this maximum. After calculating the backoff increase, 20% random jitter is added to avoid connection storms.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 1000 (1 second)

| 有效值
| [0,...]

| 重要性
| low
|===

== reconnect.backoff.ms

The base amount of time to wait before attempting to reconnect to a given host. This avoids repeatedly connecting to a host in a tight loop. This backoff applies to all connection attempts by the client to a broker.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 50

| 有效值
| [0,...]

| 重要性
| low
|===

== retry.backoff.ms

The amount of time to wait before attempting to retry a failed request to a given topic partition. This avoids repeatedly sending requests in a tight loop under some failure scenarios.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 100

| 有效值
| [0,...]

| 重要性
| low
|===

== sasl.kerberos.kinit.cmd

Kerberos kinit command path.

|===
| 名称 | 值

| 类型
| string

| 默认值
| /usr/bin/kinit

| 有效值
|

| 重要性
| low
|===

== sasl.kerberos.min.time.before.relogin

Login thread sleep time between refresh attempts.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 60000

| 有效值
|

| 重要性
| low
|===

== sasl.kerberos.ticket.renew.jitter

Percentage of random jitter added to the renewal time.

|===
| 名称 | 值

| 类型
| double

| 默认值
| 0.05

| 有效值
|

| 重要性
| low
|===

== sasl.kerberos.ticket.renew.window.factor

Login thread will sleep until the specified window factor of time from last refresh to ticket's expiry has been reached, at which time it will try to renew the ticket.

|===
| 名称 | 值

| 类型
| double

| 默认值
| 0.8

| 有效值
|

| 重要性
| low
|===

== sasl.login.refresh.buffer.seconds

The amount of buffer time before credential expiration to maintain when refreshing a credential, in seconds. If a refresh would otherwise occur closer to expiration than the number of buffer seconds then the refresh will be moved up to maintain as much of the buffer time as possible. Legal values are between 0 and 3600 (1 hour); a default value of 300 (5 minutes) is used if no value is specified. This value and sasl.login.refresh.min.period.seconds are both ignored if their sum exceeds the remaining lifetime of a credential. Currently applies only to OAUTHBEARER.

|===
| 名称 | 值

| 类型
| short

| 默认值
| 300

| 有效值
| [0,...,3600]

| 重要性
| low
|===

== sasl.login.refresh.min.period.seconds

The desired minimum time for the login refresh thread to wait before refreshing a credential, in seconds. Legal values are between 0 and 900 (15 minutes); a default value of 60 (1 minute) is used if no value is specified. This value and sasl.login.refresh.buffer.seconds are both ignored if their sum exceeds the remaining lifetime of a credential. Currently applies only to OAUTHBEARER.

|===
| 名称 | 值

| 类型
| short

| 默认值
| 60

| 有效值
| [0,...,900]

| 重要性
| low
|===

== sasl.login.refresh.window.factor

Login refresh thread will sleep until the specified window factor relative to the credential's lifetime has been reached, at which time it will try to refresh the credential. Legal values are between 0.5 (50%) and 1.0 (100%) inclusive; a default value of 0.8 (80%) is used if no value is specified. Currently applies only to OAUTHBEARER.

|===
| 名称 | 值

| 类型
| double

| 默认值
| 0.8

| 有效值
| [0.5,...,1.0]

| 重要性
| low
|===

== sasl.login.refresh.window.jitter

The maximum amount of random jitter relative to the credential's lifetime that is added to the login refresh thread's sleep time. Legal values are between 0 and 0.25 (25%) inclusive; a default value of 0.05 (5%) is used if no value is specified. Currently applies only to OAUTHBEARER.

|===
| 名称 | 值

| 类型
| double

| 默认值
| 0.05

| 有效值
| [0.0,...,0.25]

| 重要性
| low
|===

== security.providers

A list of configurable creator classes each returning a provider implementing security algorithms. These classes should implement the org.apache.kafka.common.security.auth.SecurityProviderCreator interface.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== ssl.cipher.suites

A list of cipher suites. This is a named combination of authentication, encryption, MAC and key exchange algorithm used to negotiate the security settings for a network connection using TLS or SSL network protocol. By default all the available cipher suites are supported.

|===
| 名称 | 值

| 类型
| list

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== ssl.endpoint.identification.algorithm

The endpoint identification algorithm to validate server hostname using server certificate.

|===
| 名称 | 值

| 类型
| string

| 默认值
| https

| 有效值
|

| 重要性
| low
|===

== ssl.engine.factory.class

The class of type org.apache.kafka.common.security.auth.SslEngineFactory to provide SSLEngine objects. Default value is org.apache.kafka.common.security.ssl.DefaultSslEngineFactory

|===
| 名称 | 值

| 类型
| class

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== ssl.keymanager.algorithm

The algorithm used by key manager factory for SSL connections. Default value is the key manager factory algorithm configured for the Java Virtual Machine.

|===
| 名称 | 值

| 类型
| string

| 默认值
| SunX509

| 有效值
|

| 重要性
| low
|===

== ssl.secure.random.implementation

The SecureRandom PRNG implementation to use for SSL cryptography operations.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== ssl.trustmanager.algorithm

The algorithm used by trust manager factory for SSL connections. Default value is the trust manager factory algorithm configured for the Java Virtual Machine.

|===
| 名称 | 值

| 类型
| string

| 默认值
| PKIX

| 有效值
|

| 重要性
| low
|===