[[kafka-producerconfigs]]
= Producer Configs

以下是生产者的配置：

== key.serializer

Serializer class for key that implements the org.apache.kafka.common.serialization.Serializer interface.

|===
| 名称 | 值

| 类型
| class

| 默认值
|

| 有效值
|

| 重要性
| high
|===

== value.serializer

Serializer class for value that implements the org.apache.kafka.common.serialization.Serializer interface.

|===
| 名称 | 值

| 类型
| class

| 默认值
|

| 有效值
|

| 重要性
| high
|===

== bootstrap.servers

A list of host/port pairs to use for establishing the initial connection to the Kafka cluster. The client will make use of all servers irrespective of which servers are specified here for bootstrapping—this list only impacts the initial hosts used to discover the full set of servers. This list should be in the form host1:port1,host2:port2,.... Since these servers are just used for the initial connection to discover the full cluster membership (which may change dynamically), this list need not contain the full set of servers (you may want more than one, though, in case a server is down).

|===
| 名称 | 值

| 类型
| list

| 默认值
| ""

| 有效值
| non-null string

| 重要性
| high
|===

== buffer.memory

The total bytes of memory the producer can use to buffer records waiting to be sent to the server. If records are sent faster than they can be delivered to the server the producer will block for max.block.ms after which it will throw an exception.

This setting should correspond roughly to the total memory the producer will use, but is not a hard bound since not all memory the producer uses is used for buffering. Some additional memory will be used for compression (if compression is enabled) as well as for maintaining in-flight requests.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 33554432

| 有效值
| [0,...]

| 重要性
| high
|===

== compression.type

The compression type for all data generated by the producer. The default is none (i.e. no compression). Valid values are none, gzip, snappy, lz4, or zstd. Compression is of full batches of data, so the efficacy of batching will also impact the compression ratio (more batching means better compression).

|===
| 名称 | 值

| 类型
| string

| 默认值
| none

| 有效值
|

| 重要性
| high
|===

== retries

Setting a value greater than zero will cause the client to resend any record whose send fails with a potentially transient error. Note that this retry is no different than if the client resent the record upon receiving the error. Produce requests will be failed before the number of retries has been exhausted if the timeout configured by delivery.timeout.ms expires first before successful acknowledgement. Users should generally prefer to leave this config unset and instead use delivery.timeout.ms to control retry behavior.

Enabling idempotence requires this config value to be greater than 0. If conflicting configurations are set and idempotence is not explicitly enabled, idempotence is disabled.

Allowing retries while setting enable.idempotence to false and max.in.flight.requests.per.connection to 1 will potentially change the ordering of records because if two batches are sent to a single partition, and the first fails and is retried but the second succeeds, then the records in the second batch may appear first.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 2147483647

| 有效值
| [0,...,2147483647]

| 重要性
| high
|===

== ssl.key.password

The password of the private key in the key store file orthe PEM key specified in `ssl.keystore.key'. This is required for clients only if two-way authentication is configured.

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.keystore.certificate.chain

Certificate chain in the format specified by 'ssl.keystore.type'. Default SSL engine factory supports only PEM format with a list of X.509 certificates

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.keystore.key

Private key in the format specified by 'ssl.keystore.type'. Default SSL engine factory supports only PEM format with PKCS#8 keys. If the key is encrypted, key password must be specified using 'ssl.key.password'

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.keystore.location

The location of the key store file. This is optional for client and can be used for two-way authentication for client.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.keystore.password

The store password for the key store file. This is optional for client and only needed if 'ssl.keystore.location' is configured. Key store password is not supported for PEM format.

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.truststore.certificates

Trusted certificates in the format specified by 'ssl.truststore.type'. Default SSL engine factory supports only PEM format with X.509 certificates.

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.truststore.location

The location of the trust store file.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== ssl.truststore.password

The password for the trust store file. If a password is not set, trust store file configured will still be used, but integrity checking is disabled. Trust store password is not supported for PEM format.

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| high
|===

== batch.size

The producer will attempt to batch records together into fewer requests whenever multiple records are being sent to the same partition. This helps performance on both the client and the server. This configuration controls the default batch size in bytes.

No attempt will be made to batch records larger than this size.

Requests sent to brokers will contain multiple batches, one for each partition with data available to be sent.

A small batch size will make batching less common and may reduce throughput (a batch size of zero will disable batching entirely). A very large batch size may use memory a bit more wastefully as we will always allocate a buffer of the specified batch size in anticipation of additional records.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 16384

| 有效值
| [0,...]

| 重要性
| medium
|===

== client.dns.lookup

Controls how the client uses DNS lookups. If set to `use_all_dns_ips`, connect to each returned IP address in sequence until a successful connection is established. After a disconnection, the next IP is used. Once all IPs have been used once, the client resolves the IP(s) from the hostname again (both the JVM and the OS cache DNS name lookups, however). If set to `resolve_canonical_bootstrap_servers_only`, resolve each bootstrap address into a list of canonical names. After the bootstrap phase, this behaves the same as `use_all_dns_ips`.

|===
| 名称 | 值

| 类型
| string

| 默认值
| use_all_dns_ips

| 有效值
| [use_all_dns_ips, resolve_canonical_bootstrap_servers_only]

| 重要性
| medium
|===

== client.id

An id string to pass to the server when making requests. The purpose of this is to be able to track the source of requests beyond just ip/port by allowing a logical application name to be included in server-side request logging.

|===
| 名称 | 值

| 类型
| string

| 默认值
| ""

| 有效值
|

| 重要性
| medium
|===

== connections.max.idle.ms

Close idle connections after the number of milliseconds specified by this config.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 540000 (9 minutes)

| 有效值
|

| 重要性
| medium
|===

== delivery.timeout.ms

An upper bound on the time to report success or failure after a call to send() returns. This limits the total time that a record will be delayed prior to sending, the time to await acknowledgement from the broker (if expected), and the time allowed for retriable send failures. The producer may report failure to send a record earlier than this config if either an unrecoverable error is encountered, the retries have been exhausted, or the record is added to a batch which reached an earlier delivery expiration deadline. The value of this config should be greater than or equal to the sum of request.timeout.ms and linger.ms.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 120000 (2 minutes)

| 有效值
| [0,...]

| 重要性
| medium
|===

== linger.ms

The producer groups together any records that arrive in between request transmissions into a single batched request. Normally this occurs only under load when records arrive faster than they can be sent out. However in some circumstances the client may want to reduce the number of requests even under moderate load. This setting accomplishes this by adding a small amount of artificial delay—that is, rather than immediately sending out a record the producer will wait for up to the given delay to allow other records to be sent so that the sends can be batched together. This can be thought of as analogous to Nagle's algorithm in TCP. This setting gives the upper bound on the delay for batching: once we get batch.size worth of records for a partition it will be sent immediately regardless of this setting, however if we have fewer than this many bytes accumulated for this partition we will 'linger' for the specified time waiting for more records to show up. This setting defaults to 0 (i.e. no delay). Setting linger.ms=5, for example, would have the effect of reducing the number of requests sent but would add up to 5ms of latency to records sent in the absence of load.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 0

| 有效值
| [0,...]

| 重要性
| medium
|===

== max.block.ms

The configuration controls how long the KafkaProducer's send(), partitionsFor(), initTransactions(), sendOffsetsToTransaction(), commitTransaction() and abortTransaction() methods will block. For send() this timeout bounds the total time waiting for both metadata fetch and buffer allocation (blocking in the user-supplied serializers or partitioner is not counted against this timeout). For partitionsFor() this timeout bounds the time spent waiting for metadata if it is unavailable. The transaction-related methods always block, but may timeout if the transaction coordinator could not be discovered or did not respond within the timeout.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 60000 (1 minute)

| 有效值
| [0,...]

| 重要性
| medium
|===

== max.request.size

The maximum size of a request in bytes. This setting will limit the number of record batches the producer will send in a single request to avoid sending huge requests. This is also effectively a cap on the maximum uncompressed record batch size. Note that the server has its own cap on the record batch size (after compression if compression is enabled) which may be different from this.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 1048576

| 有效值
| [0,...]

| 重要性
| medium
|===

== partitioner.class

Partitioner class that implements the org.apache.kafka.clients.producer.Partitioner interface.

|===
| 名称 | 值

| 类型
| class

| 默认值
| org.apache.kafka.clients.producer.internals.DefaultPartitioner

| 有效值
|

| 重要性
| medium
|===

== receive.buffer.bytes

The size of the TCP receive buffer (SO_RCVBUF) to use when reading data. If the value is -1, the OS default will be used.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 32768 (32 kibibytes)

| 有效值
| [-1,...]

| 重要性
| medium
|===

== request.timeout.ms

The configuration controls the maximum amount of time the client will wait for the response of a request. If the response is not received before the timeout elapses the client will resend the request if necessary or fail the request if retries are exhausted. This should be larger than replica.lag.time.max.ms (a broker configuration) to reduce the possibility of message duplication due to unnecessary producer retries.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 30000 (30 seconds)

| 有效值
| [0,...]

| 重要性
| medium
|===

== sasl.client.callback.handler.class

The fully qualified name of a SASL client callback handler class that implements the AuthenticateCallbackHandler interface.

|===
| 名称 | 值

| 类型
| class

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.jaas.config

JAAS login context parameters for SASL connections in the format used by JAAS configuration files. JAAS configuration file format is described here. The format for the value is: loginModuleClass controlFlag (optionName=optionValue)*;. For brokers, the config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.jaas.config=com.example.ScramLoginModule required;

|===
| 名称 | 值

| 类型
| password

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.kerberos.service.name

The Kerberos principal name that Kafka runs as. This can be defined either in Kafka's JAAS config or in Kafka's config.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.login.callback.handler.class

The fully qualified name of a SASL login callback handler class that implements the AuthenticateCallbackHandler interface. For brokers, login callback handler config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.login.callback.handler.class=com.example.CustomScramLoginCallbackHandler

|===
| 名称 | 值

| 类型
| class

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.login.class

The fully qualified name of a class that implements the Login interface. For brokers, login config must be prefixed with listener prefix and SASL mechanism name in lower-case. For example, listener.name.sasl_ssl.scram-sha-256.sasl.login.class=com.example.CustomScramLogin

|===
| 名称 | 值

| 类型
| class

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== sasl.mechanism

SASL mechanism used for client connections. This may be any mechanism for which a security provider is available. GSSAPI is the default mechanism.

|===
| 名称 | 值

| 类型
| string

| 默认值
| GSSAPI

| 有效值
|

| 重要性
| medium
|===

== security.protocol

Protocol used to communicate with brokers. Valid values are: PLAINTEXT, SSL, SASL_PLAINTEXT, SASL_SSL.

|===
| 名称 | 值

| 类型
| string

| 默认值
| PLAINTEXT

| 有效值
|

| 重要性
| medium
|===

== send.buffer.bytes

The size of the TCP send buffer (SO_SNDBUF) to use when sending data. If the value is -1, the OS default will be used.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 131072 (128 kibibytes)

| 有效值
| [-1,...]

| 重要性
| medium
|===

== socket.connection.setup.timeout.max.ms

The maximum amount of time the client will wait for the socket connection to be established. The connection setup timeout will increase exponentially for each consecutive connection failure up to this maximum. To avoid connection storms, a randomization factor of 0.2 will be applied to the timeout resulting in a random range between 20% below and 20% above the computed value.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 30000 (30 seconds)

| 有效值
|

| 重要性
| medium
|===

== socket.connection.setup.timeout.ms

The amount of time the client will wait for the socket connection to be established. If the connection is not built before the timeout elapses, clients will close the socket channel.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 10000 (10 seconds)

| 有效值
|

| 重要性
| medium
|===

== ssl.enabled.protocols

The list of protocols enabled for SSL connections. The default is 'TLSv1.2,TLSv1.3' when running with Java 11 or newer, 'TLSv1.2' otherwise. With the default value for Java 11, clients and servers will prefer TLSv1.3 if both support it and fallback to TLSv1.2 otherwise (assuming both support at least TLSv1.2). This default should be fine for most cases. Also see the config documentation for `ssl.protocol`.

|===
| 名称 | 值

| 类型
| list

| 默认值
| TLSv1.2

| 有效值
|

| 重要性
| medium
|===

== ssl.keystore.type

The file format of the key store file. This is optional for client.

|===
| 名称 | 值

| 类型
| string

| 默认值
| JKS

| 有效值
|

| 重要性
| medium
|===

== ssl.protocol

The SSL protocol used to generate the SSLContext. The default is 'TLSv1.3' when running with Java 11 or newer, 'TLSv1.2' otherwise. This value should be fine for most use cases. Allowed values in recent JVMs are 'TLSv1.2' and 'TLSv1.3'. 'TLS', 'TLSv1.1', 'SSL', 'SSLv2' and 'SSLv3' may be supported in older JVMs, but their usage is discouraged due to known security vulnerabilities. With the default value for this config and 'ssl.enabled.protocols', clients will downgrade to 'TLSv1.2' if the server does not support 'TLSv1.3'. If this config is set to 'TLSv1.2', clients will not use 'TLSv1.3' even if it is one of the values in ssl.enabled.protocols and the server only supports 'TLSv1.3'.

|===
| 名称 | 值

| 类型
| string

| 默认值
| TLSv1.2

| 有效值
|

| 重要性
| medium
|===

== ssl.provider

The name of the security provider used for SSL connections. Default value is the default security provider of the JVM.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| medium
|===

== ssl.truststore.type

The file format of the trust store file.

|===
| 名称 | 值

| 类型
| string

| 默认值
| JKS

| 有效值
|

| 重要性
| medium
|===

== acks

The number of acknowledgments the producer requires the leader to have received before considering a request complete. This controls the durability of records that are sent. The following settings are allowed:

* acks=0 If set to zero then the producer will not wait for any acknowledgment from the server at all. The record will be immediately added to the socket buffer and considered sent. No guarantee can be made that the server has received the record in this case, and the retries configuration will not take effect (as the client won't generally know of any failures). The offset given back for each record will always be set to -1.
* acks=1 This will mean the leader will write the record to its local log but will respond without awaiting full acknowledgement from all followers. In this case should the leader fail immediately after acknowledging the record but before the followers have replicated it then the record will be lost.
* acks=all This means the leader will wait for the full set of in-sync replicas to acknowledge the record. This guarantees that the record will not be lost as long as at least one in-sync replica remains alive. This is the strongest available guarantee. This is equivalent to the acks=-1 setting.

Note that enabling idempotence requires this config value to be 'all'. If conflicting configurations are set and idempotence is not explicitly enabled, idempotence is disabled.

|===
| 名称 | 值

| 类型
| string

| 默认值
| all

| 有效值
| [all, -1, 0, 1]

| 重要性
| low
|===

== enable.idempotence

When set to 'true', the producer will ensure that exactly one copy of each message is written in the stream. If 'false', producer retries due to broker failures, etc., may write duplicates of the retried message in the stream. Note that enabling idempotence requires max.in.flight.requests.per.connection to be less than or equal to 5 (with message ordering preserved for any allowable value), retries to be greater than 0, and acks must be 'all'.

Idempotence is enabled by default if no conflicting configurations are set. If conflicting configurations are set and idempotence is not explicitly enabled, idempotence is disabled. If idempotence is explicitly enabled and conflicting configurations are set, a ConfigException is thrown.

|===
| 名称 | 值

| 类型
| boolean

| 默认值
| true

| 有效值
|

| 重要性
| low
|===

== interceptor.classes

A list of classes to use as interceptors. Implementing the org.apache.kafka.clients.producer.ProducerInterceptor interface allows you to intercept (and possibly mutate) the records received by the producer before they are published to the Kafka cluster. By default, there are no interceptors.

|===
| 名称 | 值

| 类型
| list

| 默认值
| ""

| 有效值
| non-null string

| 重要性
| low
|===

== max.in.flight.requests.per.connection

The maximum number of unacknowledged requests the client will send on a single connection before blocking. Note that if this config is set to be greater than 1 and enable.idempotence is set to false, there is a risk of message re-ordering after a failed send due to retries (i.e., if retries are enabled). Additionally, enabling idempotence requires this config value to be less than or equal to 5. If conflicting configurations are set and idempotence is not explicitly enabled, idempotence is disabled.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 5

| 有效值
| [1,...]

| 重要性
| low
|===

== metadata.max.age.ms

The period of time in milliseconds after which we force a refresh of metadata even if we haven't seen any partition leadership changes to proactively discover any new brokers or partitions.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 300000 (5 minutes)

| 有效值
| [0,...]

| 重要性
| low
|===

== metadata.max.idle.ms

Controls how long the producer will cache metadata for a topic that's idle. If the elapsed time since a topic was last produced to exceeds the metadata idle duration, then the topic's metadata is forgotten and the next access to it will force a metadata fetch request.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 300000 (5 minutes)

| 有效值
| [0,...]

| 重要性
| low
|===

== metadata.max.idle.ms

Controls how long the producer will cache metadata for a topic that's idle. If the elapsed time since a topic was last produced to exceeds the metadata idle duration, then the topic's metadata is forgotten and the next access to it will force a metadata fetch request.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 300000 (5 minutes)

| 有效值
| [5000,...]

| 重要性
| low
|===

== metric.reporters

A list of classes to use as metrics reporters. Implementing the org.apache.kafka.common.metrics.MetricsReporter interface allows plugging in classes that will be notified of new metric creation. The JmxReporter is always included to register JMX statistics.

|===
| 名称 | 值

| 类型
| list

| 默认值
| ""

| 有效值
| non-null string

| 重要性
| low
|===

== metrics.num.samples

The number of samples maintained to compute metrics.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 2

| 有效值
| [1,...]

| 重要性
| low
|===

== metrics.recording.level

The highest recording level for metrics.

|===
| 名称 | 值

| 类型
| string

| 默认值
| INFO

| 有效值
| [INFO, DEBUG, TRACE]

| 重要性
| low
|===

== metrics.sample.window.ms

The window of time a metrics sample is computed over.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 30000 (30 seconds)

| 有效值
| [0,...]

| 重要性
| low
|===

== reconnect.backoff.max.ms

The maximum amount of time in milliseconds to wait when reconnecting to a broker that has repeatedly failed to connect. If provided, the backoff per host will increase exponentially for each consecutive connection failure, up to this maximum. After calculating the backoff increase, 20% random jitter is added to avoid connection storms.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 1000 (1 second)

| 有效值
| [0,...]

| 重要性
| low
|===

== reconnect.backoff.ms

The base amount of time to wait before attempting to reconnect to a given host. This avoids repeatedly connecting to a host in a tight loop. This backoff applies to all connection attempts by the client to a broker.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 50

| 有效值
| [0,...]

| 重要性
| low
|===

== retry.backoff.ms

The amount of time to wait before attempting to retry a failed request to a given topic partition. This avoids repeatedly sending requests in a tight loop under some failure scenarios.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 100

| 有效值
| [0,...]

| 重要性
| low
|===

== sasl.kerberos.kinit.cmd

Kerberos kinit command path.

|===
| 名称 | 值

| 类型
| string

| 默认值
| /usr/bin/kinit

| 有效值
|

| 重要性
| low
|===

== sasl.kerberos.min.time.before.relogin

Login thread sleep time between refresh attempts.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 60000

| 有效值
|

| 重要性
| low
|===

== sasl.kerberos.ticket.renew.jitter

Percentage of random jitter added to the renewal time.

|===
| 名称 | 值

| 类型
| double

| 默认值
| 0.05

| 有效值
|

| 重要性
| low
|===

== sasl.kerberos.ticket.renew.window.factor

Login thread will sleep until the specified window factor of time from last refresh to ticket's expiry has been reached, at which time it will try to renew the ticket.

|===
| 名称 | 值

| 类型
| double

| 默认值
| 0.8

| 有效值
|

| 重要性
| low
|===

== sasl.login.refresh.buffer.seconds

The amount of buffer time before credential expiration to maintain when refreshing a credential, in seconds. If a refresh would otherwise occur closer to expiration than the number of buffer seconds then the refresh will be moved up to maintain as much of the buffer time as possible. Legal values are between 0 and 3600 (1 hour); a default value of 300 (5 minutes) is used if no value is specified. This value and sasl.login.refresh.min.period.seconds are both ignored if their sum exceeds the remaining lifetime of a credential. Currently applies only to OAUTHBEARER.

|===
| 名称 | 值

| 类型
| short

| 默认值
| 300

| 有效值
| [0,...,3600]

| 重要性
| low
|===

== sasl.login.refresh.min.period.seconds

The desired minimum time for the login refresh thread to wait before refreshing a credential, in seconds. Legal values are between 0 and 900 (15 minutes); a default value of 60 (1 minute) is used if no value is specified. This value and sasl.login.refresh.buffer.seconds are both ignored if their sum exceeds the remaining lifetime of a credential. Currently applies only to OAUTHBEARER.

|===
| 名称 | 值

| 类型
| short

| 默认值
| 60

| 有效值
| [0,...,900]

| 重要性
| low
|===

== sasl.login.refresh.window.factor

Login refresh thread will sleep until the specified window factor relative to the credential's lifetime has been reached, at which time it will try to refresh the credential. Legal values are between 0.5 (50%) and 1.0 (100%) inclusive; a default value of 0.8 (80%) is used if no value is specified. Currently applies only to OAUTHBEARER.

|===
| 名称 | 值

| 类型
| double

| 默认值
| 0.8

| 有效值
| [0.5,...,1.0]

| 重要性
| low
|===

== sasl.login.refresh.window.jitter

The maximum amount of random jitter relative to the credential's lifetime that is added to the login refresh thread's sleep time. Legal values are between 0 and 0.25 (25%) inclusive; a default value of 0.05 (5%) is used if no value is specified. Currently applies only to OAUTHBEARER.

|===
| 名称 | 值

| 类型
| double

| 默认值
| 0.05

| 有效值
| [0.0,...,0.25]

| 重要性
| low
|===

== security.providers

A list of configurable creator classes each returning a provider implementing security algorithms. These classes should implement the org.apache.kafka.common.security.auth.SecurityProviderCreator interface.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== ssl.cipher.suites

A list of cipher suites. This is a named combination of authentication, encryption, MAC and key exchange algorithm used to negotiate the security settings for a network connection using TLS or SSL network protocol. By default all the available cipher suites are supported.

|===
| 名称 | 值

| 类型
| list

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== ssl.endpoint.identification.algorithm

The endpoint identification algorithm to validate server hostname using server certificate.

|===
| 名称 | 值

| 类型
| string

| 默认值
| https

| 有效值
|

| 重要性
| low
|===

== ssl.engine.factory.class

The class of type org.apache.kafka.common.security.auth.SslEngineFactory to provide SSLEngine objects. Default value is org.apache.kafka.common.security.ssl.DefaultSslEngineFactory

|===
| 名称 | 值

| 类型
| class

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== ssl.keymanager.algorithm

The algorithm used by key manager factory for SSL connections. Default value is the key manager factory algorithm configured for the Java Virtual Machine.

|===
| 名称 | 值

| 类型
| string

| 默认值
| SunX509

| 有效值
|

| 重要性
| low
|===

== ssl.secure.random.implementation

The SecureRandom PRNG implementation to use for SSL cryptography operations.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
|

| 重要性
| low
|===

== ssl.trustmanager.algorithm

The algorithm used by trust manager factory for SSL connections. Default value is the trust manager factory algorithm configured for the Java Virtual Machine.

|===
| 名称 | 值

| 类型
| string

| 默认值
| PKIX

| 有效值
|

| 重要性
| low
|===

== transaction.timeout.ms

The maximum amount of time in ms that the transaction coordinator will wait for a transaction status update from the producer before proactively aborting the ongoing transaction.If this value is larger than the transaction.max.timeout.ms setting in the broker, the request will fail with a InvalidTxnTimeoutException error.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 60000 (1 minute)

| 有效值
|

| 重要性
| low
|===

== transactional.id

The TransactionalId to use for transactional delivery. This enables reliability semantics which span multiple producer sessions since it allows the client to guarantee that transactions using the same TransactionalId have been completed prior to starting any new transactions. If no TransactionalId is provided, then the producer is limited to idempotent delivery. If a TransactionalId is configured, enable.idempotence is implied. By default the TransactionId is not configured, which means transactions cannot be used. Note that, by default, transactions require a cluster of at least three brokers which is the recommended setting for production; for development you can change this, by adjusting broker setting transaction.state.log.replication.factor.

|===
| 名称 | 值

| 类型
| string

| 默认值
| null

| 有效值
| non-empty string

| 重要性
| low
|===