[[kafka-topicconfigs]]
= Topic-Level Configs（主题级别的配置）

与主题相关的配置既有服务器配置的默认值，也有可以进行重新配置。 如果没有给出主题的配置，则使用服务器配置的默认值。
可以在主题创建时通过提供一个或多个  `--config` 选项来重新配置。 例如创建一个名为 `my-topic` 的主题，具有自定义的消息的最大大小和刷新频率：

[source,shell]
----
> bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --topic my-topic --partitions 1 \
  --replication-factor 1 --config max.message.bytes=64000 --config flush.messages=1
----

也可以稍后使用 `alter configs` 命令更改或重写此配置。 例如更新 `my-topic` 的最大消息大小：

[source,shell]
----
> bin/kafka-configs.sh --bootstrap-server localhost:9092 --entity-type topics --entity-name my-topic
  --alter --add-config max.message.bytes=128000
----

检查是否重写成功，您可以执行

[source,shell]
----
> bin/kafka-configs.sh --bootstrap-server localhost:9092 --entity-type topics --entity-name my-topic --describe
----

以下是主题级配置。 该属性的服务器默认配置在“服务器默认属性”标题下给出。 给定的服务器默认配置值只适用于没有明确指定主题配置的主题。

== cleanup.policy

一个字符串，它是 "delete" 或 "compact" 或两者都有。 此字符串指定用于旧日志段的保留策略。 默认策略（"delete"）将在达到保留时间或大小限制时丢弃旧的部分。 "compact" 将在主题上启用日志压缩。

|===
| 名称 | 值

| 类型
| list

| 默认值
| delete

| 有效值
| [compact, delete]

| 服务器默认属性
| log.cleanup.policy

| 重要性
| medium
|===

== compression.type

指定给定主题的最终压缩类型。 此配置接受标准压缩编解码器（'gzip'、'snappy'、'lz4'、'zstd'）。 它还接受 "uncompressed"，相当于没有压缩； 'producer' 表示保留生产者设置的原始压缩编解码器。

|===
| 名称 | 值

| 类型
| string

| 默认值
| producer

| 有效值
| [uncompressed, zstd, lz4, snappy, gzip, producer]

| 服务器默认属性
| compression.type

| 重要性
| medium
|===


== delete.retention.ms

对于日志压缩的主题保留删除 tombstone 标记的时间量。 如果消费者从偏移量 0 开始以确保他们获得最终阶段的有效快照（否则可能会在他们完成扫描之前收集删除 tombstone ），则此设置还限制了消费者必须完成读取的时间。

|===
| 名称 | 值

| 类型
| long

| 默认值
| 86400000 (1 day)

| 有效值
| [0,...]

| 服务器默认属性
| log.cleaner.delete.retention.ms

| 重要性
| medium
|===

== file.delete.delay.ms

从文件系统中删除文件之前等待的时间

|===
| 名称 | 值

| 类型
| long

| 默认值
| 60000 (1 minute)

| 有效值
| [0,...]

| 服务器默认属性
| log.segment.delete.delay.ms

| 重要性
| medium
|===

== flush.messages

This setting allows specifying an interval at which we will force an fsync of data written to the log. For example if this was set to 1 we would fsync after every message; if it were 5 we would fsync after every five messages. In general we recommend you not set this and use replication for durability and allow the operating system's background flush capabilities as it is more efficient. This setting can be overridden on a per-topic basis (see the per-topic configuration section).

|===
| 名称 | 值

| 类型
| long

| 默认值
| 9223372036854775807

| 有效值
| [0,...]

| 服务器默认属性
| log.flush.interval.messages

| 重要性
| medium
|===

== flush.ms

This setting allows specifying a time interval at which we will force an fsync of data written to the log. For example if this was set to 1000 we would fsync after 1000 ms had passed. In general we recommend you not set this and use replication for durability and allow the operating system's background flush capabilities as it is more efficient.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 9223372036854775807

| 有效值
| [0,...]

| 服务器默认属性
| log.flush.interval.ms

| 重要性
| medium

| 重要性
|
|===

== follower.replication.throttled.replicas

A list of replicas for which log replication should be throttled on the follower side. The list should describe a set of replicas in the form [PartitionId]:[BrokerId],[PartitionId]:[BrokerId]:... or alternatively the wildcard '*' can be used to throttle all replicas for this topic.

|===
| 名称 | 值

| 类型
| list

| 默认值
| ""

| 有效值
| [partitionId]:[brokerId],[partitionId]:[brokerId],...

| 服务器默认属性
| follower.replication.throttled.replicas

| 重要性
| medium
|===

== index.interval.bytes

This setting controls how frequently Kafka adds an index entry to its offset index. The default setting ensures that we index a message roughly every 4096 bytes. More indexing allows reads to jump closer to the exact position in the log but makes the index larger. You probably don't need to change this.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 4096 (4 kibibytes)

| 有效值
| [0,...]

| 服务器默认属性
| log.index.interval.bytes

| 重要性
| medium
|===

== leader.replication.throttled.replicas

A list of replicas for which log replication should be throttled on the leader side. The list should describe a set of replicas in the form [PartitionId]:[BrokerId],[PartitionId]:[BrokerId]:... or alternatively the wildcard '*' can be used to throttle all replicas for this topic.

|===
| 名称 | 值

| 类型
| list

| 默认值
| ""

| 有效值
| [partitionId]:[brokerId],[partitionId]:[brokerId],...

| 服务器默认属性
| leader.replication.throttled.replicas

| 重要性
| medium
|===

== local.retention.bytes

The maximum size of local log segments that can grow for a partition before it deletes the old segments. Default value is -2, it represents `retention.bytes` value to be used. The effective value should always be less than or equal to `retention.bytes` value.

|===
| 名称 | 值

| 类型
| long

| 默认值
| -2

| 有效值
| [-2,...]

| 服务器默认属性
| null

| 重要性
| medium
|===

== max.compaction.lag.ms

The maximum time a message will remain ineligible for compaction in the log. Only applicable for logs that are being compacted.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 9223372036854775807

| 有效值
| [1,...]

| 服务器默认属性
| log.cleaner.max.compaction.lag.ms

| 重要性
| medium
|===

== max.message.bytes

The largest record batch size allowed by Kafka (after compression if compression is enabled). If this is increased and there are consumers older than 0.10.2, the consumers' fetch size must also be increased so that they can fetch record batches this large. In the latest message format version, records are always grouped into batches for efficiency. In previous message format versions, uncompressed records are not grouped into batches and this limit only applies to a single record in that case.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 1048588

| 有效值
| [0,...]

| 服务器默认属性
| message.max.bytes

| 重要性
| medium
|===

== message.format.version

[DEPRECATED] Specify the message format version the broker will use to append messages to the logs. The value of this config is always assumed to be `3.0` if `inter.broker.protocol.version` is 3.0 or higher (the actual config value is ignored). Otherwise, the value should be a valid ApiVersion. Some examples are: 0.10.0, 1.1, 2.8, 3.0. By setting a particular message format version, the user is certifying that all the existing messages on disk are smaller or equal than the specified version. Setting this value incorrectly will cause consumers with older versions to break as they will receive messages with a format that they don't understand.

|===
| 名称 | 值

| 类型
| string

| 默认值
| 3.0-IV1

| 有效值
| [0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.10.0-IV0, 0.10.0-IV1, 0.10.1-IV0, 0.10.1-IV1, 0.10.1-IV2, 0.10.2-IV0, 0.11.0-IV0, 0.11.0-IV1, 0.11.0-IV2, 1.0-IV0, 1.1-IV0, 2.0-IV0, 2.0-IV1, 2.1-IV0, 2.1-IV1, 2.1-IV2, 2.2-IV0, 2.2-IV1, 2.3-IV0, 2.3-IV1, 2.4-IV0, 2.4-IV1, 2.5-IV0, 2.6-IV0, 2.7-IV0, 2.7-IV1, 2.7-IV2, 2.8-IV0, 2.8-IV1, 3.0-IV0, 3.0-IV1]

| 服务器默认属性
| log.message.format.version

| 重要性
| medium
|===

== message.timestamp.difference.max.ms

The maximum difference allowed between the timestamp when a broker receives a message and the timestamp specified in the message. If message.timestamp.type=CreateTime, a message will be rejected if the difference in timestamp exceeds this threshold. This configuration is ignored if message.timestamp.type=LogAppendTime.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 9223372036854775807

| 有效值
| [0,...]

| 服务器默认属性
| log.message.timestamp.difference.max.ms

| 重要性
| medium
|===

== message.timestamp.type

Define whether the timestamp in the message is message create time or log append time. The value should be either `CreateTime` or `LogAppendTime`

|===
| 名称 | 值

| 类型
| string

| 默认值
| CreateTime

| 有效值
| [CreateTime, LogAppendTime]

| 服务器默认属性
| log.message.timestamp.type

| 重要性
| medium
|===

== min.cleanable.dirty.ratio

This configuration controls how frequently the log compactor will attempt to clean the log (assuming log compaction is enabled). By default we will avoid cleaning a log where more than 50% of the log has been compacted. This ratio bounds the maximum space wasted in the log by duplicates (at 50% at most 50% of the log could be duplicates). A higher ratio will mean fewer, more efficient cleanings but will mean more wasted space in the log. If the max.compaction.lag.ms or the min.compaction.lag.ms configurations are also specified, then the log compactor considers the log to be eligible for compaction as soon as either: (i) the dirty ratio threshold has been met and the log has had dirty (uncompacted) records for at least the min.compaction.lag.ms duration, or (ii) if the log has had dirty (uncompacted) records for at most the max.compaction.lag.ms period.

|===
| 名称 | 值

| 类型
| double

| 默认值
| 0.5

| 有效值
| [0,...,1]

| 服务器默认属性
| log.cleaner.min.cleanable.ratio

| 重要性
| medium
|===

== min.compaction.lag.ms

The minimum time a message will remain uncompacted in the log. Only applicable for logs that are being compacted.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 0

| 有效值
| [0,...]

| 服务器默认属性
| log.cleaner.min.compaction.lag.ms

| 重要性
| medium
|===

== min.insync.replicas

When a producer sets acks to "all" (or "-1"), this configuration specifies the minimum number of replicas that must acknowledge a write for the write to be considered successful. If this minimum cannot be met, then the producer will raise an exception (either NotEnoughReplicas or NotEnoughReplicasAfterAppend).
When used together, min.insync.replicas and acks allow you to enforce greater durability guarantees. A typical scenario would be to create a topic with a replication factor of 3, set min.insync.replicas to 2, and produce with acks of "all". This will ensure that the producer raises an exception if a majority of replicas do not receive a write.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 1

| 有效值
| [1,...]

| 服务器默认属性
| min.insync.replicas

| 重要性
| medium
|===

== preallocate

True if we should preallocate the file on disk when creating a new log segment.

|===
| 名称 | 值

| 类型
| boolean

| 默认值
| false

| 有效值
|

| 服务器默认属性
| log.preallocate

| 重要性
| medium
|===

== remote.storage.enable

To enable tier storage for a topic, set `remote.storage.enable` as true. You can not disable this config once it is enabled. It will be provided in future versions.

|===
| 名称 | 值

| 类型
| boolean

| 默认值
| false

| 有效值
|

| 服务器默认属性
| null

| 重要性
| medium
|===

== retention.bytes

This configuration controls the maximum size a partition (which consists of log segments) can grow to before we will discard old log segments to free up space if we are using the "delete" retention policy. By default there is no size limit only a time limit. Since this limit is enforced at the partition level, multiply it by the number of partitions to compute the topic retention in bytes.

|===
| 名称 | 值

| 类型
| long

| 默认值
| -1

| 有效值
|

| 服务器默认属性
| log.retention.bytes

| 重要性
| medium
|===

== retention.ms

This configuration controls the maximum time we will retain a log before we will discard old log segments to free up space if we are using the "delete" retention policy. This represents an SLA on how soon consumers must read their data. If set to -1, no time limit is applied.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 604800000 (7 days)

| 有效值
| [-1,...]

| 服务器默认属性
| log.retention.ms

| 重要性
| medium
|===

== segment.bytes

This configuration controls the segment file size for the log. Retention and cleaning is always done a file at a time so a larger segment size means fewer files but less granular control over retention.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 1073741824 (1 gibibyte)

| 有效值
| [14,...]

| 服务器默认属性
| log.segment.bytes

| 重要性
| medium
|===

== segment.index.bytes

This configuration controls the size of the index that maps offsets to file positions. We preallocate this index file and shrink it only after log rolls. You generally should not need to change this setting.

|===
| 名称 | 值

| 类型
| int

| 默认值
| 10485760 (10 mebibytes)

| 有效值
| [0,...]

| 服务器默认属性
| log.index.size.max.bytes

| 重要性
| medium
|===

== segment.jitter.ms

The maximum random jitter subtracted from the scheduled segment roll time to avoid thundering herds of segment rolling

|===
| 名称 | 值

| 类型
| long

| 默认值
| 0

| 有效值
| [0,...]

| 服务器默认属性
| log.roll.jitter.ms

| 重要性
| medium
|===

== segment.ms

This configuration controls the period of time after which Kafka will force the log to roll even if the segment file isn't full to ensure that retention can delete or compact old data.

|===
| 名称 | 值

| 类型
| long

| 默认值
| 604800000 (7 days)

| 有效值
| [1,...]

| 服务器默认属性
| log.roll.ms

| 重要性
| medium
|===

== unclean.leader.election.enable

Indicates whether to enable replicas not in the ISR set to be elected as leader as a last resort, even though doing so may result in data loss.

|===
| 名称 | 值

| 类型
| boolean

| 默认值
| false

| 有效值
|

| 服务器默认属性
| unclean.leader.election.enable

| 重要性
| medium
|===

== message.downconversion.enable

This configuration controls whether down-conversion of message formats is enabled to satisfy consume requests. When set to false, broker will not perform down-conversion for consumers expecting an older message format. The broker responds with UNSUPPORTED_VERSION error for consume requests from such older clients. This configurationdoes not apply to any message format conversion that might be required for replication to followers.

|===
| 名称 | 值

| 类型
| boolean

| 默认值
| true

| 有效值
|

| 服务器默认属性
| log.message.downconversion.enable

| 重要性
| low
|===
