[[servlet-hello-boot]]
= Hello Spring Security (Boot)

本节介绍了如何将Spring Security与Spring Boot结合使用的最简配置。 有关如何将Spring Security与Java配置一起使用，
请参见<<servlet-hello-jc,第8.2节 "Hello Spring Security（Java配置）">>。
有关如何在XML配置中使用Spring Security，请参见<<servlet-hello-xml,第8.3节 "Hello Spring Security（XML）">>。

NOTE: 完整的应用程序可以在以下位置找到 {gh-samples-url}/boot/helloworld[samples/boot/helloworld]

[[servlet-hello-boot-dependencies]]
== 更新依赖

您需要做的唯一步骤是使用<<getting-maven-boot,Maven>>或<<getting-gradle-boot,Gradle>>更新依赖关系。 为了您的方便，您可以通过 https://start.spring.io/starter.zip?type=maven-project&language=java&bootVersion=2.1.2.RELEASE&baseDir=hello-spring-security&groupId=sample&artifactId=sample&name=hello-spring-security&description=Demo+project+for+Spring+Boot&packageName=sample&packaging=jar&javaVersion=1.8&autocomplete=&style=security&style=web&generate-project=[单击此处]下载最简单的Spring Boot + Spring Security应用程序。

== Starting Hello Spring Security Boot

现在，您可以使用Maven插件来运行 https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-running-with-the-maven-plugin[运行Spring Boot应用程序]。 以下示例显示了如何执行此操作（以及执行此操作的输出的开头）：

.运行Spring Boot应用程序
====
[source,bash]
----
$ ./mvn spring-boot:run
...
INFO 23689 --- [  restartedMain] .s.s.UserDetailsServiceAutoConfiguration :

Using generated security password: 8e557245-73e2-4286-969a-ff57fe326336

...
----
====


[[servlet-hello-boot-auto-configuration]]
== Spring Boot 自动配置

Spring Boot 会自动配置:

* 启用Spring Security的默认配置，该配置会创建 `springSecurityFilterChain` ,然后加入到 `Servlet` 过滤器链中。 此bean负责应用程序内的所有安全性（保护应用程序URL，验证提交的用户名和密码，重定向到登录表单等）。
* 创建一个 `UserDetailsService` bean，其中包含用户名 `user` 和随机生成的密码，该密码将记录到控制台。
* 针对每个请求，使用Servlet容器向 `springSecurityFilterChain` 注册过滤器。

Spring Boot的配置不多，但功能很多。
主要功能如下:

* 要求经过身份验证的用户才能与应用程序进行任何交互
* 为您生成一个默认的登录表单
* 让用户使用用户名为 `user` 和密码为 `8e557245-73e2-4286-969a-ff57fe326336` 进行表单登录
* 使用BCrypt算法进行密码加密保存
* 让用户注销
* https://en.wikipedia.org/wiki/Cross-site_request_forgery[CSRF 攻击] 防御
* https://en.wikipedia.org/wiki/Session_fixation[会话固定攻击] 防御
* 安全 Header 集成
** 为安全请求使用 https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security[HTTP Strict Transport Security]
** https://msdn.microsoft.com/en-us/library/ie/gg622941(v=vs.85).aspx[X-Content-Type-Options] 集成
** 缓存控制（以后可以由您的应用程序覆盖，以允许缓存您的静态资源）
** https://msdn.microsoft.com/en-us/library/dd565647(v=vs.85).aspx[X-XSS-Protection] 集成
** X-Frame-Options 集成防止点击劫持 https://en.wikipedia.org/wiki/Clickjacking[Clickjacking]
* 与以下Servlet API方法集成:
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getRemoteUser()[`HttpServletRequest#getRemoteUser()`]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getUserPrincipal()[`HttpServletRequest.html#getUserPrincipal()`]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#isUserInRole(java.lang.String)[`HttpServletRequest.html#isUserInRole(java.lang.String)`]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#login(java.lang.String,%20java.lang.String)[`HttpServletRequest.html#login(java.lang.String, java.lang.String)`]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#logout()[`HttpServletRequest.html#logout()`]
