[[servlet-hello-xml]]
= Hello Spring Security (XML)

本节介绍如何在XML配置中使用Spring Security。
有关如何在Java配置中使用Spring Security，请参见<<servlet-hello-jc,第8.2节 "Hello Spring Security（Java配置）">>。
有关如何在Spring Boot配置中使用Spring Security的信息，请参见<<servlet-hello-boot,第8.1节 "Hello Spring Security（ Boot）">>。

== 更新依赖

第一步是使用<<getting-maven-no-boot,Maven>>或<<gradle-without-spring-boot,Gradle>>更新依赖关系。


[[servlet-hello-xml-http]]
== 最小化 `<http>` 配置

在本节中，我们讨论如何将Spring Security与XML配置一起使用。

NOTE: 完整的应用程序可以在 {gh-samples-url}/xml/helloworld[samples/xml/helloworld] 中找到
// FIXME: Link to Java Configuration and Boot

第一步是创建我们的Spring Security XML配置。
该配置将创建一个Servlet过滤器（称为 `springSecurityFilterChain`），该过滤器负责应用程序中的所有安全性（保护应用程序URL，验证提交的用户名和密码，重定向到登录表单等）。 以下示例显示了Spring Security XML配置的最基本示例：

.src/main/webapp/WEB-INF/spring/security.xml
====
[source,xml]
----
<b:beans xmlns="http://www.springframework.org/schema/security"
		 xmlns:b="http://www.springframework.org/schema/beans"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
						http://www.springframework.org/schema/security https://www.springframework.org/schema/security/spring-security.xsd">
	<http />

	<user-service>
		<user name="user" password="{noop}password" authorities="ROLE_USER" />
	</user-service>
</b:beans>

----
====


此配置的确没有太多，但是却做了很多。主要功能如下:

* 要求经过身份验证的用户才能与应用程序进行任何交互
* 为您生成一个默认的登录表单
* 让用户使用用户名为 `user` 和密码为 `password` 进行表单登录
* 使用 BCrypt 加密算法进行密码保存
* 让用户注销
* https://en.wikipedia.org/wiki/Cross-site_request_forgery[CSRF 攻击] 防御
* https://en.wikipedia.org/wiki/Session_fixation[会话固定攻击] 防御
* 安全 Header 集成
** 为安全请求使用 https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security[HTTP Strict Transport Security]
** https://msdn.microsoft.com/en-us/library/ie/gg622941(v=vs.85).aspx[X-Content-Type-Options] 集成
** 缓存控制（以后可以由您的应用程序覆盖，以允许缓存您的静态资源）
** https://msdn.microsoft.com/en-us/library/dd565647(v=vs.85).aspx[X-XSS-Protection] 集成
** X-Frame-Options 集成防止点击劫持 https://en.wikipedia.org/wiki/Clickjacking[Clickjacking]
* 与以下Servlet API方法集成:
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getRemoteUser()[`HttpServletRequest#getRemoteUser()`]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#getUserPrincipal()[`HttpServletRequest.html#getUserPrincipal()`]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#isUserInRole(java.lang.String)[`HttpServletRequest.html#isUserInRole(java.lang.String)`]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#login(java.lang.String,%20java.lang.String)[`HttpServletRequest.html#login(java.lang.String, java.lang.String)`]
** https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html#logout()[`HttpServletRequest.html#logout()`]

// FIXME: After completed rewriting, link to all the sections of doc that this relates to


[[servlet-hello-xml-webxml]]
== `web.xml` 配置

下一步是应用程序加载我们的配置文件。为此，我们需要注册 `ContextLoaderListener` 监听器，并且在 `contextConfigLocation` 包括此配置。 以下示例显示了如何执行此操作：

.src/main/webapp/WEB-INF/web.xml
====
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="3.0" xmlns="http://java.sun.com/xml/ns/javaee"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
  http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd">

	<!--
		Loads the Spring configurations from contextConfigLocation
	-->
	<listener>
		<listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
	</listener>

	<!--
		The locations of the Spring Configuration. In this case, all configuration is
		in /WEB-INF/spring/
	-->
	<context-param>
		<param-name>contextConfigLocation</param-name>
		<param-value>
			/WEB-INF/spring/*.xml
		</param-value>
	</context-param>

	<!--
		DelegatingFilterProxy looks for a Spring bean by the name of filter (springSecurityFilterChain) and delegates
		all work to that Bean. This is how the Servlet Container can a Spring Bean to act as a Servlet Filter.
	-->
	<filter>
		<filter-name>springSecurityFilterChain</filter-name>
		<filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
	</filter>
	<filter-mapping>
		<filter-name>springSecurityFilterChain</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>

</web-app>
----
====

[NOTE]
====
如果您与现有的Spring MVC应用程序集成，请确保配置 `DispatcherServlet` 从根 `ApplicationContext` 加载配置。 以下示例显示了如何执行此操作：

=====
.src/main/webapp/WEB-INF/web.xml
[source,xml]
----
<servlet>
	<servlet-name>spring</servlet-name>
	<servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
	<!-- Load Spring MVC configuration from root ApplicationContext (context-param from above) -->
	<init-param>
		<param-name>contextConfigLocation</param-name>
		<param-value></param-value>
	</init-param>
</servlet>

<servlet-mapping>
  <servlet-name>spring</servlet-name>
  <url-pattern>/</url-pattern>
</servlet-mapping>
----
=====
====
