[[test-webflux]]
= Reactive 测试支持

[[test-erms]]
== 测试 Reactive 方法安全

例如,我们可以使用与<<jc-erms, 第18.1节 "测试方法安全性">> 中相同的设置和注解来测试  <<test-method,第27章 `EnableReactiveMethodSecurity` 中>>的示例. 这是我们可以做的最小样本:

[source,java]
----
@RunWith(SpringRunner.class)
@ContextConfiguration(classes = HelloWebfluxMethodApplication.class)
public class HelloWorldMessageServiceTests {
	@Autowired
	HelloWorldMessageService messages;

	@Test
	public void messagesWhenNotAuthenticatedThenDenied() {
		StepVerifier.create(this.messages.findMessage())
			.expectError(AccessDeniedException.class)
			.verify();
	}

	@Test
	@WithMockUser
	public void messagesWhenUserThenDenied() {
		StepVerifier.create(this.messages.findMessage())
			.expectError(AccessDeniedException.class)
			.verify();
	}

	@Test
	@WithMockUser(roles = "ADMIN")
	public void messagesWhenAdminThenOk() {
		StepVerifier.create(this.messages.findMessage())
			.expectNext("Hello World!")
			.verifyComplete();
	}
}
----

[[test-webtestclient]]
== WebTestClientSupport

Spring Security提供了与 `WebTestClient` 的集成. 基本设置如下所示:

[source,java]
----
@RunWith(SpringRunner.class)
@ContextConfiguration(classes = HelloWebfluxMethodApplication.class)
public class HelloWebfluxMethodApplicationTests {
	@Autowired
	ApplicationContext context;

	WebTestClient rest;

	@Before
	public void setup() {
		this.rest = WebTestClient
			.bindToApplicationContext(this.context)
			// add Spring Security test Support
			.apply(springSecurity())
			.configureClient()
			.filter(basicAuthentication())
			.build();
	}
	// ...
}
----

=== 认证
将Spring Security支持应用于 `WebTestClient` 之后,我们可以使用注解或 `mutateWith` 支持. 例如:

[source,java]
----
@Test
public void messageWhenNotAuthenticated() throws Exception {
	this.rest
		.get()
		.uri("/message")
		.exchange()
		.expectStatus().isUnauthorized();
}

// --- WithMockUser ---

@Test
@WithMockUser
public void messageWhenWithMockUserThenForbidden() throws Exception {
	this.rest
		.get()
		.uri("/message")
		.exchange()
		.expectStatus().isEqualTo(HttpStatus.FORBIDDEN);
}

@Test
@WithMockUser(roles = "ADMIN")
public void messageWhenWithMockAdminThenOk() throws Exception {
	this.rest
		.get()
		.uri("/message")
		.exchange()
		.expectStatus().isOk()
		.expectBody(String.class).isEqualTo("Hello World!");
}

// --- mutateWith mockUser ---

@Test
public void messageWhenMutateWithMockUserThenForbidden() throws Exception {
	this.rest
		.mutateWith(mockUser())
		.get()
		.uri("/message")
		.exchange()
		.expectStatus().isEqualTo(HttpStatus.FORBIDDEN);
}

@Test
public void messageWhenMutateWithMockAdminThenOk() throws Exception {
	this.rest
		.mutateWith(mockUser().roles("ADMIN"))
		.get()
		.uri("/message")
		.exchange()
		.expectStatus().isOk()
		.expectBody(String.class).isEqualTo("Hello World!");
}
----


=== CSRF 支持

Spring Security 还为使用 `WebTestClient` 的 CSRF 提供测试支持. 例如:

[source,java]
----
this.rest
	// provide a valid CSRF token
	.mutateWith(csrf())
	.post()
	.uri("/login")
	...
----


[[webflux-testing-oauth2]]
=== 测试 OAuth 2.0

当涉及到 OAuth 2.0 时，仍然可以使用前面介绍的相同原理：最终，它取决于您所测试的方法期望  `SecurityContextHolder`  能做什么。


例如，对于如下所示的控制器：

[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(Principal user) {
    return Mono.just(user.getName());
}
----

没有关于 OAuth2 的特定信息，因此您可能只需使用  <<test-erms,use `@WithMockUser`>>  就可以了。

但是，如果您的控制器绑定 Spring Security 的 OAuth 2.0 支持的一些情况，例如：

[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(@AuthenticationPrincipal OidcUser user) {
    return Mono.just(user.getIdToken().getSubject());
}
----

然后 Spring Security 的测试支持将派上用场。

[[webflux-testing-oidc-login]]
=== 测试 OIDC Login

使用 Spring MVC Test 测试上述方法需要使用授权服务器模拟某种授权流程。 当然，这将是一项艰巨的任务，但是,Spring Security 的 OAuth 2.0 Client 测试支持可以帮助删除大部分样板代码.

例如，我们可以使用  `SecurityMockServerConfigurers#oidcLogin` 方法告诉 Spring Security 包含默认的 `OidcUser`，如下所示：

[source,java]
----
client
    .mutateWith(mockOidcLogin()).get().uri("/endpoint").exchange();
----

这将使用的 `MockHttpServletRequest` 创建关联的 `OidcUser` ，该 `OidcUser` 包括的一个模拟的 `OidcIdToken`，模拟 `OidcUserInfo` 和一个模拟的授权集合。

具体来说，它将包括一个 `OidcIdToken`，并为用户设置了一个 claim

[source,json]
----
assertThat(user.getIdToken().getClaim("sub")).isEqualTo("user");
----

没有 claims 的 `OidcUserInfo` :

[source,json]
----
assertThat(user.getUserInfo().getClaims()).isEmpty();
----

和只有一个权限 `SCOPE_read` 的权限集合：

[source,json]
----
assertThat(user.getAuthorities()).hasSize(1);
assertThat(user.getAuthorities()).containsExactly(new SimpleGrantedAuthority("SCOPE_read"));
----

Spring Security 做了必要的工作，以确保 `OidcUser` 实例可用于  <<mvc-authentication-principal,`@AuthenticationPrincipal` 注解>>。

此外，它还将 `OidcUser` 链接到 `OAuth2AuthorizedClient` 的简单实例，并将其存入 `HttpSessionOAuth2AuthorizedClientRepository`。 如果您的测试 <<webflux-testing-oauth2-client,使用 `@RegisteredOAuth2AuthorizedClient` 注解>>，则此方法很方便。

[[webflux-testing-oidc-login-authorities]]
==== 配置权限

在许多情况下，您的方法受到过滤器或安全方法的保护，并且需要您的身份验证具有某些授予的权限才能允许该请求。

在这种情况下，您可以使用 `authorities()` 方法提供所需的已授予权限：

[source,java]
----
client
    .mutateWith(mockOidcLogin()
        .authorities(new SimpleGrantedAuthority("SCOPE_message:read"))
    )
    .get().uri("/endpoint").exchange();
----

[[webflux-testing-oidc-login-claims]]
==== 配置 Claims

尽管授予的权限在整个 Spring Security 中非常普遍，但在 OAuth 2.0 方面我们也有主张。

举例来说，假设您有一个 `user_id` 声明，该声明指出了系统中的用户 ID。 您可以像在控制器中那样访问它：

[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(@AuthenticationPrincipal OidcUser oidcUser) {
    String userId = oidcUser.getIdToken().getClaim("user_id");
    // ...
}
----

在这种情况下，您需要使用  `idToken()`  方法指定该声明：

[source,java]
----
client
    .mutateWith(mockOidcLogin()
        .idToken(token -> token.claim("user_id", "1234"))
    )
    .get().uri("/endpoint").exchange();
----

因为 `OidcUser` 从 `OidcIdToken` 收集了其 claims。

[[webflux-testing-oidc-login-user]]
==== 其他配置

还有其他方法可用于进一步配置身份验证。 它仅取决于您的控制器需要什么数据：

* `userInfo(OidcUserInfo.Builder)` - 配置 `OidcUserInfo` 实例
* `clientRegistration(ClientRegistration)` - 使用已有 `ClientRegistration` 关联 `OAuth2AuthorizedClient`
* `oidcUser(OidcUser)` - 用于配置完整的 `OidcUser` 实例

如果您:
1. 有自己的 `OidcUser` 的实现,
2. 需要更改 name 属性

例如，假设您的授权服务器在 `user_name` claim 中发送主体名称，而不在 `sub` claim 中发送主体名称。 在这种情况下，您可以手动配置 `OidcUser`：

[source,java]
----
OidcUser oidcUser = new DefaultOidcUser(
        AuthorityUtils.createAuthorityList("SCOPE_message:read"),
        Collections.singletonMap("user_name", "foo_user"),
        "user_name");

client
    .mutateWith(mockOidcLogin().oidcUser(oidcUser))
    .get().uri("/endpoint").exchange();
----

[[webflux-testing-oauth2-login]]
=== 测试 OAuth 2.0 登录

与 <<webflux-testing-oidc-login,测试 OIDC 登录>> 一样，测试 OAuth 2.0 登录也面临着类似需要模拟授权流程挑战。 因此，Spring Security 还对非 OIDC 用例提供了测试支持。

假设我们有一个控制器，可以将登录用户作为 `OAuth2User`：

[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(@AuthenticationPrincipal OAuth2User oauth2User) {
    return Mono.just(oauth2User.getAttribute("sub"));
}
----

在这种情况下，我们可以告诉 Spring Security 使用  `SecurityMockServerConfigurers#oauth2User` 方法包含一个默认的 `OAuth2User`，就像这样

[source,java]
----
client
    .mutateWith(mockOAuth2Login())
    .get().uri("/endpoint").exchange();
----

这将使用 `OAuth2User` 配置关联的 `MockHttpServletRequest`，该 `OAuth2User` 包括简单的属性映射和已授予权限的集合。

具体来说，它将包括一个带有 `sub`/`user` 的键值对：

[source,json]
----
assertThat((String) user.getAttribute("sub")).isEqualTo("user");
----

和只有一个权限 `SCOPE_read` 的权限集合：

[source,json]
----
assertThat(user.getAuthorities()).hasSize(1);
assertThat(user.getAuthorities()).containsExactly(new SimpleGrantedAuthority("SCOPE_read"));
----

Spring Security 做了必要的工作，以确保 `OAuth2User` 实例可用于  <<mvc-authentication-principal, `@AuthenticationPrincipal` 注解>>。

此外，它还将 `OAuth2User` 链接到 `OAuth2AuthorizedClient` 的简单实例，该实例存储在 `HttpSessionOAuth2AuthorizedClientRepository` 中。 如果您的测试使用 <<webflux-testing-oauth2-client,使用 `@RegisteredOAuth2AuthorizedClient` 注解>> ，则这会很方便。

[[webflux-testing-oauth2-login-authorities]]
==== 配置权限

在许多情况下，您的方法受到过滤器或安全方法的保护，并且需要 `Authentication` 具有某些授予的权限才能允许该请求。

在这种情况下，您可以使用 `authorities()` 方法提供所需的已授予权限：

[source,java]
----
client
    .mutateWith(mockOAuth2Login()
        .authorities(new SimpleGrantedAuthority("SCOPE_message:read"))
    )
    .get().uri("/endpoint").exchange();
----

[[webflux-testing-oauth2-login-claims]]
==== 配置 Claims

尽管授予的权限在整个 Spring Security 中非常普遍，但在 OAuth 2.0 方面我们也有主张。

举例来说，假设您有一个 `user_id` 声明，该声明指出了系统中的用户 ID。 您可以像在控制器中那样访问它：

[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(@AuthenticationPrincipal OAuth2User oauth2User) {
    String userId = oauth2User.getAttribute("user_id");
    // ...
}
----

在这种情况下，您需要使用  `attributes()` 方法指定该属性：

[source,java]
----
client
    .mutateWith(mockOAuth2Login()
        .attributes(attrs -> attrs.put("user_id", "1234"))
    )
    .get().uri("/endpoint").exchange();
----

[[webflux-testing-oauth2-login-user]]
==== 其他配置


还有其他方法可用于进一步配置身份验证。 它仅取决于您的控制器需要什么数据：

* `clientRegistration(ClientRegistration)` - 使用已有 `ClientRegistration` 关联 `OAuth2AuthorizedClient`
* `oidcUser(OAuth2User)` - 用于配置完整的 `OAuth2User` 实例

如果您:
1. 有自己的 `OAuth2User` 的实现,
2. 需要更改 name 属性

例如，假设您的授权服务器在 `user_name` claim 中发送主体名称，而不在 `sub` claim 中发送主体名称。 在这种情况下，您可以手动配置 `OAuth2User`：

[source,java]
----
OAuth2User oauth2User = new DefaultOAuth2User(
        AuthorityUtils.createAuthorityList("SCOPE_message:read"),
        Collections.singletonMap("user_name", "foo_user"),
        "user_name");

client
    .mutateWith(mockOAuth2Login().oauth2User(oauth2User))
    .get().uri("/endpoint").exchange();
----

[[webflux-testing-oauth2-client]]
=== 测试 OAuth 2.0 客户端

与用户的身份验证方式无关，对于正在测试的请求，您可能还有其他令牌和客户端注册在起作用。 例如，您的控制器可能依赖于客户端凭据授予来获取与用户完全不相关的令牌：

[source,json]
----
@GetMapping("/endpoint")
public Mono<String> foo(@RegisteredOAuth2AuthorizedClient("my-app") OAuth2AuthorizedClient authorizedClient) {
    return this.webClient.get()
        .attributes(oauth2AuthorizedClient(authorizedClient))
        .retrieve()
        .bodyToMono(String.class);
}
----

使用授权服务器模拟此握手可能很麻烦。 相反，可以使用 `SecurityMockServerConfigurers#oauth2Client` 将 `OAuth2AuthorizedClient` 添加到 `HttpSessionOAuth2AuthorizedClientRepository` 中：

[source,java]
----
client
    .mutateWith(mockOAuth2Client("my-app"))
    .get().uri("/endpoint").exchange();
----

如果您的应用尚未使用 `HttpSessionOAuth2AuthorizedClientRepository`，则可以将其提供为 `@TestConfiguration`：

[source,java]
----
@TestConfiguration
static class AuthorizedClientConfig {
    @Bean
    OAuth2ServerAuthorizedClientRepository authorizedClientRepository() {
        return new WebSessionOAuth2ServerAuthorizedClientRepository();
    }
}
----

这将创建一个具有简单 `ClientRegistration`，`OAuth2AccessToken` 和资源所有者名称的 `OAuth2AuthorizedClient`。

具体来说，它将包括一个 `ClientRegistration`，其客户端ID为 "test-client"，客户端密码为 "test-secret"：

[source,json]
----
assertThat(authorizedClient.getClientRegistration().getClientId()).isEqualTo("test-client");
assertThat(authorizedClient.getClientRegistration().getClientSecret()).isEqualTo("test-secret");
----

资源所有者名字 "user":

[source,json]
----
assertThat(authorizedClient.getPrincipalName()).isEqualTo("user");
----

`OAuth2AccessToken` 只包含一个权限, `read`:

[source,json]
----
assertThat(authorizedClient.getAccessToken().getScopes()).hasSize(1);
assertThat(authorizedClient.getAccessToken().getScopes()).containsExactly("read");
----

Spring Security 做了必要的工作，以确保 `OAuth2AuthorizedClient` 实例在关联的 `HttpSession` 中可用。 这意味着可以从 `HttpSessionOAuth2AuthorizedClientRepository` 中检索它。

[[webflux-testing-oauth2-client-scopes]]
==== 配置 Scopes

在许多情况下，OAuth 2.0 访问令牌都带有一组范围。如果您的控制器检查了这些，如下：

[source,json]
----
@GetMapping("/endpoint")
public Mono<String> foo(@RegisteredOAuth2AuthorizedClient("my-app") OAuth2AuthorizedClient authorizedClient) {
    Set<String> scopes = authorizedClient.getAccessToken().getScopes();
    if (scopes.contains("message:read")) {
        return this.webClient.get()
            .attributes(oauth2AuthorizedClient(authorizedClient))
            .retrieve()
            .bodyToMono(String.class);
    }
    // ...
}
----

然后您可以使用  `accessToken()` 方法配置范围：

[source,java]
----
client
    .mutateWith(mockOAuth2Client("my-app")
        .accessToken(new OAuth2AccessToken(BEARER, "token", null, null, Collections.singleton("message:read"))))
    )
    .get().uri("/endpoint").exchange();
----

[[webflux-testing-oauth2-client-registration]]
==== 其他配置


还有其他方法可用于进一步配置身份验证。 它仅取决于您的控制器需要什么数据：

* `principalName(String)` - 资源所有者名字
* `clientRegistration(Consumer<ClientRegistration.Builder>)` - 用于配置相关的 `ClientRegistration`
* `clientRegistration(ClientRegistration)` - 配置完整的 `ClientRegistration`

如果您想使用真实的 `ClientRegistration`，那么最后一个方便

例如，假设您要使用 `application.yml` 中定义的 `ClientRegistration` 。

在这种情况下，您的测试可以自动连接 `ClientRegistrationRepository` 并查找您的测试所需的一个：

[source,java]
----
@Autowired
ReactiveClientRegistrationRepository clientRegistrationRepository;

// ...

client
    .mutateWith(mockOAuth2Client()
        .clientRegistration(this.clientRegistrationRepository.findByRegistrationId("facebook"))
    )
    .get().uri("/exchange").exchange();
----

[[webflux-testing-jwt]]
=== 测试 JWT 认证

为了在资源服务器上发出授权请求,您需要一个承载令牌.  如果为JWT配置了资源服务器,则这意味着需要对承载令牌进行签名,然后根据JWT规范进行编码.  所有这些都可能令人生畏,尤其是当这不是您的测试重点时.

幸运的是,您可以通过多种简单的方法来克服此困难,并使您的测试专注于授权而不是表示承载令牌.  我们现在来看其中两个:

==== `mockJwt() WebTestClientConfigurer`

第一种方法是通过 `WebTestClientConfigurer`. 其中最简单的如下所示:

[source,java]
----
client
    .mutateWith(mockJwt()).get().uri("/endpoint").exchange();
----

要做的就是创建一个模拟的 `Jwt`,将其正确地通过任何身份验证API传递,以便您的授权机制可以对其进行验证.

默认情况下,它创建的 `JWT` 具有以下特征:

[source,json]
----
{
  "headers" : { "alg" : "none" },
  "claims" : {
    "sub" : "user",
    "scope" : "read"
  }
}
----

经过测试的结果是,`Jwt` 将通过以下方式通过:

[source,java]
----
assertThat(jwt.getTokenValue()).isEqualTo("token");
assertThat(jwt.getHeaders().get("alg")).isEqualTo("none");
assertThat(jwt.getSubject()).isEqualTo("sub");
GrantedAuthority authority = jwt.getAuthorities().iterator().next();
assertThat(authority.getAuthority()).isEqualTo("read");
----

当然可以配置这些值.

可以使用其相应方法配置任何标题或声明:

[source,java]
----
client
	.mutateWith(jwt(jwt -> jwt.header("kid", "one")
		.claim("iss", "https://idp.example.org")))
	.get().uri("/endpoint").exchange();
----

[source,java]
----
client
	.mutateWith(jwt(jwt -> jwt.claims(claims -> claims.remove("scope"))))
	.get().uri("/endpoint").exchange();
----

`scope` 和 `scp` 声明在这里的处理方式与它们在普通承载令牌请求中的处理方式相同.  但是,可以通过提供测试所需的GrantedAuthority实例的列表来覆盖它:

[source,java]
----
client
	.mutateWith(jwt().authorities(new SimpleGrantedAuthority("SCOPE_messages")))
	.get().uri("/endpoint").exchange();
----

或者,如果您有一个自定义的 `Jwt`   `Collection<GrantedAuthority>` 转换器,则还可以使用它来导出授权:

[source,java]
----
client
	.mutateWith(jwt().authorities(new MyConverter()))
	.get().uri("/endpoint").exchange();
----

您还可以指定一个完整的 `Jwt`,为此 `{security-api-url}org/springframework/security/oauth2/jwt/Jwt.Builder.html[Jwt.Builder]` 非常方便:

[source,java]
----
Jwt jwt = Jwt.withTokenValue("token")
    .header("alg", "none")
    .claim("sub", "user")
    .claim("scope", "read");

client
	.mutateWith(jwt(jwt))
	.get().uri("/endpoint").exchange();
----

==== `authentication()` `WebTestClientConfigurer`

第二种方法是使用 `authentication()` `Mutator`.  本质上,您可以实例化自己的 `JwtAuthenticationToken` 并在测试中提供它,如下所示:

[source,java]
----
Jwt jwt = Jwt.withTokenValue("token")
    .header("alg", "none")
    .claim("sub", "user")
    .build();
Collection<GrantedAuthority> authorities = AuthorityUtils.createAuthorityList("SCOPE_read");
JwtAuthenticationToken token = new JwtAuthenticationToken(jwt, authorities);

client
	.mutateWith(authentication(token))
	.get().uri("/endpoint").exchange();
----

请注意,作为替代方法,您还可以使用 `@MockBean` 注解来模拟 `ReactiveJwtDecoder` bean本身.

[[webflux-testing-opaque-token]]
=== 测试 Opaque Token 认证

与 <<webflux-testing-jwt,JWTs>> 相似，不透明令牌需要授权服务器才能验证其有效性，这会使测试更加困难。 为了解决这个问题，Spring Security 提供了对不透明令牌的测试支持。

假设我们有一个控制器，可以将身份验证作为 `BearerTokenAuthentication` 进行检索：

[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(BearerTokenAuthentication authentication) {
    return Mono.just((String) authentication.getTokenAttributes("sub"));
}
----

在这种情况下，我们可以使用 `SecurityMockServerConfigurers#opaqueToken`  方法告诉 Spring Security 包含默认的 `BearerTokenAuthentication`，如下所示：

[source,java]
----
client
    .mutateWith(mockOpaqueToken())
    .get().uri("/endpoint").exchange();
----

这将使用 `BearerTokenAuthentication` 配置关联的 `MockHttpServletRequest`，该 `BearerTokenAuthentication` 包括简单的 `OAuth2AuthenticatedPrincipal`，属性映射和授予的权限集合。

具体来说，它将包括一个带有 `sub`/`user` 键值对：

[source,json]
----
assertThat((String) token.getTokenAttributes().get("sub")).isEqualTo("user");
----

和只有一个权限 `SCOPE_read` 的权限集合：

[source,json]
----
assertThat(token.getAuthorities()).hasSize(1);
assertThat(token.getAuthorities()).containsExactly(new SimpleGrantedAuthority("SCOPE_read"));
----

Spring Security 做了必要的工作，以确保 `BearerTokenAuthentication` 实例可用于您的控制器方法。

[[webflux-testing-opaque-token-authorities]]
==== 配置权限

在许多情况下，您的方法受到过滤器或安全方法的保护，并且需要 `Authentication` 具有某些授予的权限才能允许该请求。

在这种情况下，您可以使用 `authorities()` 方法提供所需的已授予权限：

[source,java]
----
client
    .mutateWith(mockOpaqueToken()
        .authorities(new SimpleGrantedAuthority("SCOPE_message:read"))
    )
    .get().uri("/endpoint").exchange();
----

[[webflux-testing-opaque-token-attributes]]
==== 配置 Claims

尽管授予的权限在整个 Spring Security 中非常普遍，但在 OAuth 2.0 方面我们也有主张。

举例来说，假设您有一个 `user_id` 声明，该声明指出了系统中的用户 ID。 您可以像在控制器中那样访问它：

[source,java]
----
@GetMapping("/endpoint")
public Mono<String> foo(BearerTokenAuthentication authentication) {
    String userId = (String) authentication.getTokenAttributes().get("user_id");
    // ...
}
----

在这种情况下，您需要使用  `attributes()` 方法指定该属性：

[source,java]
----
client
    .mutateWith(mockOpaqueToken()
        .attributes(attrs -> attrs.put("user_id", "1234"))
    )
    .get().uri("/endpoint").exchange();
----

[[webflux-testing-opaque-token-principal]]
==== 其他配置

还有其他方法可用于进一步配置身份验证。 它仅取决于您的控制器需要什么数据：

`principal(OAuth2AuthenticatedPrincipal)` 就是这样的一种，您可以使用它来配置作为 `BearerTokenAuthentication` 基础的完整 `OAuth2AuthenticatedPrincipal` 实例。

如果您:
1. 有自己的 `OAuth2AuthenticatedPrincipal` 实现, 或者
2. 想指定 principal 名字

例如，假设您的授权服务器在 `user_name` claim 中发送主体名称，而不在 `sub` claim 中发送主体名称。 在这种情况下，您可以手动配置 `OAuth2AuthenticatedPrincipal`：

[source,java]
----
Map<String, Object> attributes = Collections.singletonMap("user_name", "foo_user");
OAuth2AuthenticatedPrincipal principal = new DefaultOAuth2AuthenticatedPrincipal(
        (String) attributes.get("user_name"),
        attributes,
        AuthorityUtils.createAuthorityList("SCOPE_message:read"));

client
    .mutateWith(mockOpaqueToken().principal(principal))
    .get().uri("/endpoint").exchange();
----

请注意，作为使用  `mockOpaqueToken()` 测试支持的替代方法，您还可以使用 `@MockBean` 注解来模拟 `OpaqueTokenIntrospector` bean本身。