// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[antlr_plugin]]
= ANTLR 插件

ANTLR 插件扩展了 Java 插件, 添加了对使用  http://www.antlr.org/[ANTLR] 的生成解析.

NOTE: ANTLR 插件支持 ANTLR 2, 3 和 4.

[[sec:antlr_usage]]
== 使用

要使用 ANTLR 插件, 在构建脚本中包含以下内容:

.Using the ANTLR plugin
====
.groovy
[source,groovy,role="primary"]
----
include::{snippets-dir}/antlr/useAntlrPlugin/groovy/build.gradle[tags=use-plugin]
----
.Kotlin
[source,kotlin,role="secondary"]
----
include::{snippets-dir}/antlr/useAntlrPlugin/kotlin/build.gradle.kts[tags=use-plugin]
----
====

[[sec:antlr_tasks]]
== Tasks

ANTLR 为你的项目提供了如下的任务.

`generateGrammarSource` — link:{groovyDslPath}/org.gradle.api.plugins.antlr.AntlrTask.html[AntlrTask]::
Generates the source files for all production ANTLR grammars.

`generateTestGrammarSource` — link:{groovyDslPath}/org.gradle.api.plugins.antlr.AntlrTask.html[AntlrTask]::
Generates the source files for all test ANTLR grammars.

`generate__SourceSet__GrammarSource` — link:{groovyDslPath}/org.gradle.api.plugins.antlr.AntlrTask.html[AntlrTask]::
Generates the source files for all ANTLR grammars for the given source set.

ANTLR 插件将以下依赖添加到 Java 插件的任务中。

.ANTLR plugin - additional task dependencies
[cols="a,a", options="header"]
|===
| Task name
| Depends on
| `compileJava`
| `generateGrammarSource`

| `compileTestJava`
| `generateTestGrammarSource`

| `compile__SourceSet__Java`
| `generate__SourceSet__GrammarSource`
|===


[[sec:antlr_project_layout]]
== 项目布局

`src/main/antlr`::
Production ANTLR grammar files. If the ANTLR grammar is organized in packages, the structure in the antlr folder should reflect the package structure. This ensures that the generated sources end up in the correct target subfolder.

`src/test/antlr`::
Test ANTLR grammar files.

`src/__sourceSet__/antlr`::
ANTLR grammar files for the given source set.


[[sec:antlr_dependency_management]]
== Dependency management

ANTLR 插件添加了一个 `antlr` 依赖配置, 提供了可以使用的 ANTLR 实现。下面的示例展示了如何使用 ANTLR 3.

.Declare ANTLR version
====
.groovy
[source,groovy,role="primary"]
----
include::{snippets-dir}/antlr/useAntlrPlugin/groovy/build.gradle[tags=declare-dependency]
----
.Kotlin
[source,kotlin,role="secondary"]
----
include::{snippets-dir}/antlr/useAntlrPlugin/kotlin/build.gradle.kts[tags=declare-dependency]
----
====

如果没有声明依赖项，则默认值为 `antlr:antlr:2.7.7`。要使用不同的 ANTLR 版本，请向上面的 `antlr` 依赖配置中添加你想要的依赖.

[[sec:antlr_convention_properties]]
== Convention properties

ANTLR 插件不添加任何约定属性.

[[sec:antlr_source_set_properties]]
== Source set properties

ANTLR 插件将以下属性添加到项目中的每个 source set 中.

`antlr` — link:{groovyDslPath}/org.gradle.api.file.SourceDirectorySet.html[SourceDirectorySet]::
The ANTLR grammar files of this source set. Contains all `.g` or `.g4` files found in the ANTLR source directories, and excludes all other types of files. _Default value is non-null._

`antlr.srcDirs` — `Set&lt;File&gt;`::
The source directories containing the ANTLR grammar files of this source set.
Can set using anything <<working_with_files.adoc#sec:specifying_multiple_files, that implicitly converts to a file collection>>.
Default value is `[__projectDir__/src/__name__/antlr]`.

[[sec:controlling_the_antlr_generator_process]]
== Controlling the ANTLR generator process

ANTLR 工具以 forked process 执行。 这允许对 ANTLR 过程的内存设置进行细粒度控制。 要设置 Antlr 进程的堆大小，可以使用 link:{groovyDslPath}/org.gradle.api.plugins.antlr.AntlrTask.html[AntlrTask] 的 `maxHeapSize` 属性。 要传递其他命令行参数，请查看 link:{groovyDslPath}/org.gradle.api.plugins.antlr.AntlrTask.html[AntlrTask] 的 `arguments` 属性.

.Setting custom max heap size and extra arguments for ANTLR
====
.groovy
[source,groovy,role="primary"]
----
include::{snippets-dir}/antlr/useAntlrPlugin/groovy/build.gradle[tags=generate-grammar-settings]
----
.Kotlin
[source,kotlin,role="secondary"]
----
include::{snippets-dir}/antlr/useAntlrPlugin/kotlin/build.gradle.kts[tags=generate-grammar-settings]
----
====