// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[java_gradle_plugin]]
= Gradle 插件开发插件

Java Gradle 插件开发插件可用于协助 Gradle 插件的开发. 它会自动应用 <<java_library_plugin.adoc#,Java Library>> 插件,将 `gradleApi()` 依赖添加到 `api` 配置中,并在执行 `jar` 任务期间执行插件元数据的验证.

该插件还与 <<test_kit.adoc#test_kit,TestKit>> 集成在一起,后者是一个有助于编写和执行插件代码功能测试的库. 它会自动将 `gradleTestKit()` 依赖添加到 `testImplementation` 配置,并生成 `GradleRunner` 实例消耗的插件类路径清单文件 (如果找到) . 有关其用法,配置选项和示例的更多信息,请参阅 <<test_kit.adoc#sub:test-kit-automatic-classpath-injection,Automatic classpath injection with the Plugin Development Plugin>>.

[[sec:gradle_plugin_dev_usage]]
== 使用

要使用 Java Gradle 插件开发插件,请在构建脚本中包括以下内容:

.Using the Java Gradle Plugin Development plugin
====
include::{snippets-dir}/java/javaGradlePlugin/groovy/build.gradle[tags=use-java-gradle-plugin-plugin]
include::{snippets-dir}/java/javaGradlePlugin/kotlin/build.gradle.kts[tags=use-java-gradle-plugin-plugin]
====

应用插件会自动应用  <<java_library_plugin.adoc#,Java Library>> 插件,并将 `gradleApi()` 依赖添加到 `api`  配置中. 它还向构建添加了一些验证.

执行以下验证:

* 有一个为插件定义的插件描述符
* 插件描述符包含一个 `implementation-class`  属性.
* `implementation-class` property 属性引用 jar 中的有效类文件.
* 每个属性 getter o或相应的字段都必须使用 `@InputFile` 和 `@OutputDirectory`. 之类的属性进行注解. 不参与最新检查的属性应使用 `@Internal` 注解.

验证失败将导致警告消息.

对于您正在开发的每个插件,将一个条目添加到  `gradlePlugin {}`  脚本块中:

.Using the gradlePlugin {} block.
====
include::{snippets-dir}/java/javaGradlePlugin/groovy/build.gradle[tags=gradle-plugin-block]
include::{snippets-dir}/java/javaGradlePlugin/kotlin/build.gradle.kts[tags=gradle-plugin-block]
====

`gradlePlugin {}` 块定义由项目构建的插件,包括插件的 `id` 和 `implementationClass`. 根据有关正在开发的插件的数据,Gradle 可以自动:

* 在 `jar`  文件的 `META-INF` 目录中生成插件描述符.
* 配置 <<publishing_maven.adoc#publishing_maven,Maven>> 或 <<publishing_ivy.adoc#publishing_ivy,Ivy Publish Plugins>> 发布插件并为每个发布插件生成 <<plugins.adoc#sec:plugin_markers,Plugin Marker Artifact>>.
* 此外,如果应用了 link:https://plugins.gradle.org/docs/publish-plugin[Plugin Publishing Plugin],它将使用相同的名称插件 ID,显示名称和描述将每个插件发布到 Gradle 插件门户
 (有关详细信息,请参阅 link:https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/[Publishing Plugins to Gradle Plugin Portal]) .
