[[migrating_from_maven]]
= 从 Apache Maven 迁移到 Gradle 构建

TIP: 使用慢的 Maven 构建? 在 https://gradle.com/training/build-cache-deep-dive/?bid=docs-migrating-maven[此处注册] 以参加我们的构建缓存培训课程,以了解 Gradle Enterprise 如何将 Maven 构建速度提高多达90％.

https://maven.apache.org[Apache Maven] 是用于 Java 和其他基于 JVM 的项目的构建工具,这些项目已被广泛使用,因此想要使用 Gradle 的人们通常必须迁移现有的 Maven 构建.
本指南将通过解释这两种工具的模型之间的差异和相似之处,并提供可简化操作的步骤来帮助进行这种迁移.

转化一种构建方式听起来可能会很吓人,但您不必独自完成.您可以从 link:https://gradle.org/help[help.gradle.org] 搜索文档,论坛和 StackOverflow,或者在遇到麻烦时访问 link:https://discuss.gradle.org/c/help-discuss[Gradle 社区论坛].

[[migmvn:making_a_case]]
== 进行迁移

Gradle 和 Maven 之间的主要区别是灵活性,性能,用户体验和依赖管理. link:https://gradle.org/maven-vs-gradle[Maven 与 Gradle 功能比较中] 提供了这些方面的直观概述.

自 Gradle 3.0 以来,Gradle 投入了大量资金,以使 Gradle 的构建速度更快,并具有 link:https://blog.gradle.org/introducing-gradle-build-cache[构建缓存],link:https://blog.gradle.org/incremental-compiler-avoidance[增量编译]和改进的增量 Java 编译器等功能. 对于大多数项目,即使不使用构建缓存,Gradle 的速度也比 Maven 快 2-10 倍. 从此处可以进行深入的 link:https://gradle.org/gradle-vs-maven-performance/[性能比较] 和从 Maven 切换到 Gradle 的业务案例.

[[migmvn:general_guidelines]]
== 一般准则


Gradle 和 Maven 对如何构建项目有根本不同的看法. Gradle 提供了一种灵活且可扩展的构建模型,该模型将实际工作委托给 <<what_is_gradle#the_core_model_is_based_on_tasks,任务依赖图>>. Maven 使用固定的线性阶段模型,可以在其中附加目标(完成工作的事物).
这可能会使两者之间的迁移看起来令人生畏,但迁移也许会出奇的容易,因为 Gradle 遵循许多与 Maven 相同的约定(例如 <<java_plugin#sec:java_project_layout,标准项目结构>>),并且其依赖管理以类似的方式工作.

在这里,我们列出了一系列步骤供您参阅,这将有助于促进将任何 Maven 构建移植到 Gradle:

TIP: 保留旧的 Maven 构建和新的 Gradle 构建. 您知道 Maven 构建可以工作,因此您应该保留它,直到确信 Gradle 构建可以生成所有相同的 artifacts ,然后再做您需要的事情. 这也意味着用户无需获取复制源码即可尝试 Gradle 构建.

 . link:https://scans.gradle.com#maven[为 Maven 构建创建构建扫描].
+
构建扫描提供一种可视化的界面使您能够了解 Maven 构建中发生的情况. 对于 Maven 构建,您将能够查看项目结构,正在使用的插件,构建步骤的时间表等等.
以便您可以将其与转换项目时获得的 Gradle 构建扫描进行比较.
+
. 开发一种机制来验证两个构建产生相同的 artifacts
+
这是确保您的部署和测试连续的至关重要的一步. 即使是很小的更改,例如 JAR 中清单文件的内容,也会引起问题. 如果您的 Gradle 构建生成的输出与 Maven 构建生成的输出相同,
您可以放心的切换了
+
这并不意味着您需要在每个阶段都验证每个 artifacts ,尽管这样做可以帮助您快速确定问题的根源. 您可以只关注关键输出,例如最终报告以及已发布或部署的 artifacts .
+
与 Maven 相比,您需要考虑 Gradle 产生的构建输出中的某些固有差异. 生成的 POM 将仅包含消耗所需的信息,并且它们将针对该方案正确使用 `<compile>` 和 `<runtime>` 作用域.
您可能还会看到存档中文件和类路径中文件顺序的差异. 大多数差异都是良性的,但值得识别它们并确认它们是可以的.
 . <<migmvn:automatic_conversion,执行自动转换>>
+
这将创建您需要的所有 Gradle 构建文件,即使对于 <<migmvn:multimodule_builds,多模块构建>>也是如此. 对于更简单的 Maven 项目,Gradle 构建可以运行.
 . link:https://scans.gradle.com[为 Gradle 构建创建构建扫描].
+
通过构建扫描,可以更轻松地查看构建中发生的情况. 对于 Gradle 构建,您将能够查看项目结构,依赖(常规和项目间的依赖),正在使用的插件以及构建的控制台输出.
+
此时您的构建可能会失败,但是没关系; 扫描仍将运行.将Gradle构建的构建扫描与Maven构建的构建扫描进行比较,然后继续执行此列表以排除故障.
+
我们建议您在迁移过程中定期生成构建扫描,以帮助您确定问题并排除故障. 如果您愿意,您还可以使用 Gradle 构建扫描来确定 https://guides.gradle.org/performance/[提高构建性能] 的机会,毕竟,性能首先是切换到 Gradle 的一个重要原因.
 . <<migmvn:migrating_deps,Verify your dependencies and fix any problems>>
 . <<migmvn:integration_tests,Configure integration and functional tests>>
+
通过配置额外的 source set,可以简单地迁移许多测试. 如果您使用的是第三方库(例如 http://docs.fitnesse.org/FrontPage[FitNesse]),请查看 https://plugins.gradle.org/[Gradle Plugin Portal] 上是否有合适的社区插件.
 . 用 Gradle 插件替换等效的 Maven 插件
+
对于 <<migmvn:common_plugins,流行的插件>>,Gradle 经常有一个等效的插件供您使用. 您可能还会发现可以用 <<migmvn:unnecessary_plugins,内置的 Gradle 功能替换插件>>.
作为最后的选择,您可能需要通过自己的 <<migmvn:custom_plugins,自定义插件和任务类型>>重新实现 Maven 插件.

本章的其余部分更详细地介绍了将构建从 Maven 迁移到 Gradle 的具体方面.

[[migmvn:build_lifecycle]]
== 了解构建生命周期

Maven 构建的 https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html[构建生命周期] 由一组固定阶段组成.
这可能会成为用户迁移到 Gradle 的障碍,因为它的构建生命周期和 Gradle <<build_lifecycle#build_lifecycle,有所不同>>,尽管了解 Gradle 的构建方式如何适合初始化,配置和执行阶段的结构很重要.
幸运的是,Gradle 具有可以模仿 Maven 各个阶段的功能的<<more_about_tasks#sec:lifecycle_tasks,生命周期的任务>>.

这些使您可以通过创建仅依赖于您感兴趣的任务的无操作任务来定义自己的"生命周期" .并且为了使 Maven 用户更轻松地过渡到 Gradle,<<base_plugin#sec:base_tasks,Base 插件>> - 由所有 JVM 语言应用 <<java_library_plugin#java_library_plugin,Java Library 插件>>之类的插件提供了一组与主要 Maven 阶段相对应的生命周期任务.

这是一些主要的 Maven 阶段以及它们映射到的 Gradle 任务的列表:

`clean`::
使用 Base 插件提供的 `clean` 任务.

`compile`::
使用 <<java_plugin.adoc#sec:java_tasks,Java 插件>>提供的 `classes` 任务和其他 JVM 语言插件.这将编译所有语言的所有源文件的所有类,并通过 `processResources` 任务执行 <<migmvn:filtering_resources,资源过滤>>.

`test`::
使用 Java 插件提供的 `test` 任务.它仅运行单元测试,或更具体地说,运行组成  <<java_plugin.adoc#source_sets,`test` source set>> 的测试.

`package`::
使用 Base 插件提供的 `assemble` 任务.这将构建适合该项目的任何软件包,例如 Java 库的 JAR 或传统 Java Webapp 的 WAR.

`verify`::
使用 Base 插件提供的 `check` 任务.这将运行所有附加的验证任务,通常包括单元测试,静态分析任务(如 <<checkstyle_plugin#checkstyle_plugin,Checkstyle>>)和其他任务.
如果要包括集成测试,则必须 <<migmvn:integration_tests,手动配置>>这些,这是一个简单的过程.

`install`::
使用 <<publishing_maven#publishing_maven:tasks, Maven Publish 插件>> 提供的 `publishToMavenLocal` 任务.
+
请注意,Gradle 构建不需要您 "install"  artifacts ,因为您可以使用更合适的功能,例如 <<declaring_dependencies.adoc#sub:project_dependencies,项目间依赖>> 和 <<composite_builds#,组合构建>> . 您只应使用 `publishToMavenLocal` 与 `Maven` 构建进行互操作.
+
Gradle 还允许您解决对本地 Maven 缓存的依赖,如 <<migmvn:declaring_repos,声明仓库>>部分中所述.

`deploy`::
使用 <<publishing_maven#publishing_maven:tasks, Maven Publish 插件>> 提供的 `publish` 任务 - 确保您的构建使用的是旧版本的 Maven 插件(ID: `maven`) . 这会将您的程序包发布到所有已配置的发布存储库.
还有其他一些任务,即使定义了多个资源,也可以将其发布到单个资源库.
+
请注意,默认情况下,Maven Publish Plugin 不会发布源代码和 Javadoc JAR,但是可以按照 <<building_java_projects.adoc#sec:java_packaging,构建 Java 项目>>的指南中的说明轻松激活它.

[[migmvn:automatic_conversion]]
== 执行自动转换

Gradle 的  <<build_init_plugin#build_init_plugin,`init` task>> 通常用于创建新的骨架项目,但是您也可以使用它将现有的 Maven 构建自动转换为 Gradle.在系统上 <<installation#installation,安装>> Gradle 之后,只需执行以下命令

[listing.terminal]
----
> gradle init
----

从根项目目录,并让 Gradle 做它的事情. 这基本上包括解析现有的 POM 并生成相应的 Gradle 构建脚本. 如果您要迁移 <<multi_project_builds#multi_project_builds,构建多项目>>,Gradle 还将创建一个 settings 脚本.

您会发现新的Gradle构建包括以下内容:

 * POM 中指定的所有自定义存储库
 * 您的外部和项目间依赖
 * 用于构建项目的适当插件(仅限于 <<publishing_maven.adoc#,Maven Publish>>,<<java_plugin.adoc#,Java>> 和 <<war_plugin.adoc#,War>> 插件中的一个或多个)

有关自动转换功能的完整列表,请参见 <<build_init_plugin#sec:pom_maven_conversion,Build Init 插件>>一章.

要记住的一件事是有些组件不会自动转换.它们转换时可能有问题,您需要做一些手工工作.选项包括:

 * 使用 <<distribution_plugin#distribution_plugin,Distribution Plugin>>
 * 使用 <<java_library_distribution_plugin#java_library_distribution_plugin,Java Library Distribution Plugin>>
 * 使用 <<application_plugin#application_plugin,Application Plugin>>
 * <<working_with_files#sec:creating_archives_example,创建自定义 archive tasks>>
 * 从 https://plugins.gradle.org/[Gradle 插件网站] 使用合适的社区插件

如果您的 Maven 构建没有使用大量的插件或者自定义的方式,则只需运行

[listing.terminal]
----
> gradle build
----

迁移完成后.这将运行测试并产生所需的 artifacts ,而您无需任何额外的干预.

[[migmvn:migrating_deps]]
== 迁移依赖

Gradle 的依赖管理系统比 Maven 的依赖管理系统更灵活,但是它仍然支持相同的存储库,声明的依赖,作用域(Gradle 中的 <<declaring_dependencies.adoc#sec:what-are-dependency-configurations,依赖配置>>)和可传递依赖的概念.
实际上,Gradle 与 Maven 兼容的存储库完美配合,这使得迁移依赖变得容易.

NOTE: 两种工具之间的一个显着区别是它们如何管理版本冲突. Maven 使用 "最接近" 的匹配算法,而 Gradle 选择 最新 的匹配算法. 不过,请放心,您可以控制选择哪个版本,如 <<dependency_constraints.adoc#,管理依赖传递>>中所述.

在以下各节中,我们将向您展示如何迁移 Maven 构建的依赖管理信息中最常见的元素.

[[migmvn:declaring_deps]]
=== 声明依赖

Gradle 使用与 Maven 相同的依赖标识符组件: group ID, artifact ID 和 version.. 它还支持 classifiers. 因此,您所需要做的就是将标识符的依赖信息替换为 Gradle 的语法,这在 <<declaring_dependencies#,声明依赖>> 一章中进行了介绍.

例如,Log4J 使用 Maven 风格的依赖:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>log4j</groupId>
        <artifactId>log4j</artifactId>
        <version>1.2.12</version>
    </dependency>
</dependencies>
----

在 Gradle 构建脚本中,这种依赖如下所示:

.Declaring a simple compile-time dependency
====
include::{snippets-dir}/mavenMigration/basic/groovy/build.gradle[tags=compile-dependencies]
include::{snippets-dir}/mavenMigration/basic/kotlin/build.gradle.kts[tags=compile-dependencies]
====
<1> 将 Log4J 版本 `1.2.12` 舔加到  `implementation` 配置(作用域)

字符串标识符采用 Maven 的 `groupId`,`artifactId` 和 `version` 值,尽管 Gradle 将它们称为 `group`, `module` 和 `version`.

上面的示例提出了一个明显的问题: 该 `implementation` 配置是什么?  它是 <<java_plugin#tab:configurations,Java 插件>>提供的标准依赖配置之一,通常用于替代 Maven 的默认 `compile` 作用域

Maven 的作用域与 Gradle 的标准配置之间的几个区别归结为 Gradle 区分了构建模块所需的依赖性和构建依赖于该模块的模块所需的依赖性. Maven 没有这种区别,因此已发布的 POM 通常包括库的使用者实际上不需要的依赖.

以下是主要的 Maven 依赖作用域以及如何处理它们的迁移:

`compile`::
Gradle 具有两种可用于代替 `compile` 作用域的配置:  `implementation`  和 `api`. 前者适用于所有应用 Java 插件的项目,而 api 仅适用于专门应用 <<java_library_plugin#java_library_plugin,Java Library Plugin>>的项目.

+
在大多数情况下,您应该只使用 `implementation`  配置,尤其是在构建应用程序或网络应用程序时. 但是,如果您要构建库,则可以在构建 Java 库部分中了解使用 `api` 声明哪些依赖.
上面链接的 <<building_java_projects#sec:building_java_libraries,Java 库插件>> 一章提供了有关 `api` 和 `implementation`  之间区别的更多信息.

`runtime`::
使用 `runtimeOnly` 配置

`test`::
Gradle 区分了 _compile_  项目测试所需的那些依赖和仅  _run_  它们所需的那些依赖.
+
应针对 `testImplementation` 配置声明测试编译所需的依赖.仅运行测试所需的那些应该使用 `testRuntimeOnly`.

`provided`::
使用 `compileOnly` 配置.
+
请注意,<<war_plugin#sec:war_dependency_management,War 插件>>添加了 `provideCompile` 和 `providerRuntime` 依赖配置. 它们的行为与 `compileOnly` 略有不同,只需确保 WAR 文件中没有打包这些依赖即可.
但是,依赖包括在运行时和测试运行时类路径中,因此,如果需要,请使用这些配置.

`import`::
`import` 主用于主要在 `<dependencyManagement>` 块中使用,并且仅适用于仅 POM 的发布. 阅读有关 <<migmvn:using_boms,使用物料清单>>的部分,以了解有关如何复制此行为的更多信息.
+
您还可以指定对 POM-only 的发布的常规依赖性. 在这种情况下,在该 POM 中声明的依赖将被视为构建的常规传递依赖.
+
例如,假设您想在测试中使用 `groovy-all` 的POM.这是仅支持POM的出版物,在 `<dependencies>` 块中列出了自己的依赖. Gradle 构建中的适当配置如下所示:
+
.Consuming a POM-only dependency
====
include::{snippets-dir}/mavenMigration/basic/groovy/build.gradle[tags=pom-dependencies]
include::{snippets-dir}/mavenMigration/basic/kotlin/build.gradle.kts[tags=pom-dependencies]
====
+
这样做的结果是,将所有 `groovy-POM` 中的所有  `compile` 和 `runtime` 作用域依赖都添加到测试运行时类路径中,而仅将 `compile` 作用域依赖添加到测试编译类路径中. 与其他作用域的依赖将被忽略.

[[migmvn:declaring_repos]]
=== 声明仓库

Gradle 允许您从任何与 Maven 兼容或与 Ivy 兼容的存储库中检索已声明的依赖. 与 Maven 不同,它没有默认存储库,因此您必须声明至少一个.
为了具有与 Maven 构建相同的行为,只需在 Gradle 构建中配置 <<declaring_repositories.adoc#sub:maven_central,Maven Central>>,如下所示:

.Configuring the build to use Maven Central
====
include::{snippets-dir}/mavenMigration/basic/groovy/build.gradle[tags=repositories]
include::{snippets-dir}/mavenMigration/basic/kotlin/build.gradle.kts[tags=repositories]
====

您还可以使用 `repositories {}` 块来配置自定义存储库,如 <<declaring_repositories.adoc#sec:maven_repo,存储库类型>>一章中所述.

最后,Gradle 允许您解决对 <<declaring_repositories.adoc#sub:maven_local,本地Maven缓存/存储库>>的依赖. 这有助于 Gradle 构建与 Maven 构建进行互操作,但是如果您不需要这种互操作性,则不应该使用该技术.
如果要通过文件系统共享已发布的 artifacts ,请考虑使用 `file://` URL 配置 <<declaring_repositories.adoc#sec:maven_repo,自定义 Maven 存储库>>.

您可能还对了解 Gradle 自己的 <<dependency_resolution.adoc#sec:dependency_cache,依赖缓存>>感兴趣,该缓存比 Maven 的行为更可靠,并且可以被多个并发的 Gradle 进程安全地使用.

[[migmvn:controlling_dep_versions]]
=== 控制依赖版本

传递依赖的存在意味着您可以轻松地在依赖图中最终获得同一依赖的多个版本. 默认情况下,Gradle 会在图中选择依赖的最新版本,但这并不总是正确的解决方案.
因此,它提供了几种机制来控制解析给定依赖的哪个版本.

在每个项目的基础上,您可以使用:

 * <<dependency_constraints.adoc#sec:adding-constraints-transitive-deps,Dependency constraints(依赖约束)>>
 * <<migmvn:using_boms,Bills of materials>> (Maven BOMs)
 * <<dependency_downgrade_and_exclude.adoc#sec:enforcing_dependency_version,Overriding transitive versions(覆盖版本传递)>>

在 <<dependency_constraints.adoc#,控制依赖传递>>一章中列出了更多专门的选项.

如果要确保多项目构建中所有项目的版本一致性,类似于 Maven 中的 `<dependencyManagement>` 块的工作方式,则可以使用 <<java_platform_plugin#java_platform_plugin,Java Platform Plugin>>. 这允许您声明一组可以应用于多个项目的依赖约束.
您甚至可以将平台发布为 Maven BOM 或使用 Gradle 的元数据格式发布. 有关如何执行此操作的更多信息,请参见插件页面,尤其是在 <<java_platform_plugin#sec:java_platform_consumption,Consuming platforms>>,以了解如何将平台应用于同一构建中的其他项目.

[[migmvn:excluding_deps]]
=== 排除依赖传递

Maven 构建使用排除项将不需要的依赖(或不需要的依赖版本)保留在依赖图之外. 您可以使用 Gradle 做同样的事情,但这不一定是正确的事情. Gradle 提供了其他一些选项,这些选项可能更适合给定的情况,因此您确实需要了解为什么要适当地设置排除项.

如果您出于与版本无关的原因要排除依赖,请查看 <<dependency_downgrade_and_exclude.adoc#sec:excluding-transitive-deps,排除依赖传递>> 中的部分. 它显示了如何将排除项附加到整个配置(通常是最合适的解决方案)或依赖. 您甚至可以轻松地将排除应用于所有配置.

如果您对控制实际解决依赖的版本更感兴趣,请参阅上一节.

[[migmvn:optional_deps]]
=== 处理可选的依赖

关于可选依赖,您可能会遇到两种情况:

 * 一些传递依赖被声明为可选的
 * 您希望在项目发布的 POM 中将一些直接依赖声明为可选的


对于第一种情况,Gradle 的行为与 Maven 相同,只是忽略了声明为可选的任何传递依赖. 如果相同的依存关系在依存关系图中的其他位置显示为非可选,则无法解析它们并且对所选版本没有影响.

至于将依赖发布为可选内容,Gradle 提供了一个更丰富的模型,称为 <<feature_variants#feature_variants,功能变量>>,该模型可以让您声明库提供的 "可选功能".

[[migmvn:using_boms]]
== Using bills of materials (BOMs:物料清单)

Maven 允许您通过在具有 `pom` 打包类型的 POM 文件的 `<dependencyManagement>` 部分内定义依赖来共享依赖约束. 然后可以将这种特殊类型的 POM(物料清单)导入其他 POM 中,以便您在项目中拥有一致的库版本.

Gradle 可以通过基于 link:{groovyDslPath}/org.gradle.api.artifacts.dsl.DependencyHandler.html#org.gradle.api.artifacts.dsl.DependencyHandler:platform(java.lang.Object)[platform()] 和 link:{groovyDslPath}/org.gradle.api.artifacts.dsl.DependencyHandler.html#org.gradle.api.artifacts.dsl.DependencyHandler:enforcedPlatform(java.lang.Object)[enforcedPlatform()]  方法的特殊依赖语法,将此类 BOM 用于相同的目的. 您只需以常规方式声明依赖,然后将依赖标识符包装在适当的方法中,如  "imports"  Spring Boot 依赖 BOM 的示例所示:

.Importing a BOM in a Gradle build
====
include::{snippets-dir}/mavenMigration/importBom/groovy/build.gradle[tags=bom]
include::{snippets-dir}/mavenMigration/importBom/kotlin/build.gradle.kts[tags=bom]
====
<1> 应用 Spring Boot Dependencies BOM
<2> 添加依赖,该依赖的版本由该BOM表定义

您可以在有关从 Maven BOM <<platforms.adoc#sub:bom_import,导入版本建议>>的部分中了解有关此功能以及 `platform()` 和 `forcedPlatform()` 之间的区别的更多信息.

NOTE: 您可以使用此功能将来自任何依赖的 POM 的 `<dependencyManagement>` 信息应用于 Gradle 构建,即使那些没有 `pom` 打包类型的信息也是如此. `platform()` 和 `forcedPlatform()` 都将忽略在 `<dependencies>` 块中声明的所有依赖.

[[migmvn:multimodule_builds]]
== 多项目迁移 (项目聚合)

Maven 的多模块构建与 Gradle 的 <<multi_project_builds#multi_project_builds,多项目构建>>很好地映射. 尝试 link:../samples/sample_jvm_multi_project_build.html[sample] 的示例,以了解如何设置基本的多项目 Gradle 构建.

要迁移多模块 Maven 构建,只需执行以下步骤:

1. 创建一个与根POM的 `<modules>` 块匹配的设置脚本.
+
例如,以下 `<modules>` 块:
+
[source,xml]
----
<modules>
    <module>simple-weather</module>
    <module>simple-webapp</module>
</modules>
----
+
可以通过在设置脚本中添加以下行来迁移:
+
.Declaring which projects are part of the build
====
include::{snippets-dir}/mavenMigration/multiModule/groovy/settings.gradle"]
include::{snippets-dir}/mavenMigration/multiModule/kotlin/settings.gradle.kts"]
====
<1> 设置整个项目的名称
<2> 配置两个子项目作为此构建的一部分
+
. **`gradle projects`** 输出
----
> gradle projects
include::{snippets-dir}/mavenMigration/multiModule/tests/projects.out[]
----
2. 用 <<declaring_dependencies.adoc#sub:project_dependencies,项目依赖>> 替换跨模块依赖.
3. 使用 <<sharing_build_logic_between_subprojects#sec:convention_plugins,约定插件>>复制项目继承.
+
这基本上涉及创建一个根项目构建脚本,该脚本将共享配置注入到适当的子项目中.

[[migmvn:sub:sharing-versions]]
=== 跨项目共享版本

如果要复制在根 POM 文件的 `dependencyManagement` 部分中声明的依赖版本的 Maven 模式,最好的方法是利用 `java-platform` Plugin . 您将需要为此添加一个专用项目,并在构建的常规项目中使用它.
有关此模式的更多详细信息,请 <<java_platform_plugin.adoc#,参见文档>>.

[[migmvn:profiles_and_properties]]
== 迁移 Maven 配置文件和属性

Maven 允许您使用各种属性对构建进行参数化. 一些是项目模型的只读属性,其他是用户在 POM 中定义的属性. 它甚至允许您将系统属性视为项目属性.

Gradle 具有类似的项目属性系统,尽管它可以区分项目属性和系统属性. 例如,您可以在以下位置定义属性:

* the build script
* 根目录的 `gradle.properties`
* `$HOME/.gradle` 目录的 `gradle.properties`

这些不是唯一的选择,因此,如果您有兴趣了解有关如何以及在何处定义属性的更多信息,请查阅 <<build_environment#build_environment,构建环境>> 一章.

您需要了解的一项重要行为是,在构建脚本和一个外部属性文件中定义了相同的属性时会发生什么: 构建脚本值优先. 总是. 幸运的是,您可以模仿配置文件的概念以提供可覆盖的默认值.

这使我们进入了 Maven 配置文件. 这些是根据环境,目标平台或任何其他类似因素启用和禁用不同配置的方法. 从逻辑上讲,它们仅是有限的 "if" 语句. 而且由于 Gradle 具有更强大的声明条件的方法,因此不需要正式支持配置文件(依赖的POM中除外). 如您所见,通过将条件与辅助构建脚本结合使用,您可以轻松获得相同的行为.

假设您根据环境有不同的部署设置: 本地开发(默认),测试环境和生产. 要添加类似配置文件的行为,您首先要在项目根目录中为每个环境创建构建脚本: `profile-default.gradle`, `profile-test.gradle` 和 `profile-prod.gradle`. 然后,您可以根据自己选择的 <<build_environment#sec:project_properties,项目属性>>有条件地应用这些概要文件脚本之一.

下面的示例演示了使用名为 `buildProfile` 的项目属性和配置文件脚本的基本技术,这些脚本仅初始化名为 `message` 的 <<writing_build_scripts#sec:extra_properties,额外项目属性>>:

.Mimicking the behavior of Maven profiles in Gradle
====
include::{snippets-dir}/mavenMigration/profiles/groovy/build.gradle;profile-default.gradle;profile-test.gradle;profile-prod.gradle"]
include::{snippets-dir}/mavenMigration/profiles/kotlin/build.gradle.kts;profile-default.gradle.kts;profile-test.gradle.kts;profile-prod.gradle.kts"]
====
<1> 检查是否存在(Groovy)或绑定(Kotlin)`buildProfile` 项目属性
<2> 使用脚本文件名中的 `buildProfile` 值应用适当的配置文件脚本
<3> 打印出  `message`  额外项目属性的值
<4> 初始化 `message` 额外项目属性,然后可以在主构建脚本中使用其值

完成此设置后,您可以通过传递您所使用的项目属性的值来激活其中一个配置文件-在这种情况下为 `buildProfile`:

. **`gradle greeting`** 输出
----
> gradle greeting
include::{snippets-dir}/mavenMigration/profiles/tests/greeting-default.out[]
----
.**`gradle -PbuildProfile=test greeting`** 的输出
----
> gradle -PbuildProfile=test greeting
include::{snippets-dir}/mavenMigration/profiles/tests/greeting-test.out[]
----

您不仅限于检查项目属性. 您还可以检查环境变量,JDK 版本,运行内部版本的OS或您可以想象的任何其他内容.
要记住的一件事是,高级条件语句使构建更难以理解和维护,类似于它们使面向对象的代码复杂化的方式. 配置文件也是如此. Gradle 提供了许多更好的方法来避免广泛使用 Maven 经常需要的配置文件,例如,
通过配置彼此不同的多个任务. 请参阅由 <<publishing_maven#publishing_maven:tasks,Maven Publish Plugin>> 创建的 `publish__PubName__PublicationTo__RepoName__Repository` 任务.

有关在 Gradle 中使用 Maven 概要文件的冗长讨论,请参阅 https://blog.gradle.org/maven-pom-profiles[此博客文章].

[[migmvn:filtering_resources]]
== 资源过滤

Maven 有一个称为 `process-resources` 的阶段,该阶段具有 `resources:resources`: 默认情况下绑定到它的资源. 这为构建作者提供了对各种文件(例如 Web 资源,打包的属性文件等)执行变量替换的机会.

Gradle 的 Java 插件提供了 `processResources` 任务来执行相同的操作. 这是一个 link:{groovyDslPath}/org.gradle.api.tasks.Copy.html[Copy] 任务,可将文件从配置的资源目录(默认情况下为 `src/main/resources`)复制到输出目录.
与任何 `Copy` 任务一样,您可以对其进行配置以执行 <<working_with_files#filtering_files,文件过滤>>,<<working_with_files#sec:renaming_files,重命名>>和 <<working_with_files#sec:filtering_files,内容过滤>>.

例如,以下配置将源文件视为 https://docs.groovy-lang.org/docs/next/html/documentation/template-engines.html#_simpletemplateengine[Groovy `SimpleTemplateEngine`] 模板,并为这些模板提供了 `version` 和 `buildNumber` 属性:

.Filtering the content of resources via the `processResources` task
====
include::{snippets-dir}/mavenMigration/basic/groovy/build.gradle[tags=process-resources]
include::{snippets-dir}/mavenMigration/basic/kotlin/build.gradle.kts[tags=process-resources]
====

请参阅 link:{javadocPath}/org/gradle/api/file/CopySpec.html[CopySpec] 的 API 文档以查看所有可用选项.

[[migmvn:integration_tests]]
== 配置集成测试

许多 Maven 构建都包含某种形式的集成测试,Maven 通过额外的一组阶段来支持这些 `pre-integration-test`, `integration-test`, `post-integration-test`, and `verify`.
它还使用 Failsafe 插件代替 Surefire,以便失败的集成测试不会自动使构建失败(因为您可能需要清理资源,例如正在运行的应用程序服务器).

正如我们在  <<java_testing#sec:configuring_java_integration_tests,Java & JVM 项目测试>>一章中所解释的那样,这种行为很容易在带有源集的 Gradle 中复制. 然后,您可以使用 link:{groovyDslPath}/org.gradle.api.Task.html#org.gradle.api.Task:finalizedBy(java.lang.Object++[]++)[Task.finalizedBy()] 将清理任务(例如,关闭测试服务器的清理任务)配置为始终在集成测试之后运行,而不管它们是否成功.

如果您确实不希望集成测试使构建失败,那么可以使用 Java 测试一章的 <<java_testing#sec:test_execution,Test execution>> 部分中描述的 link:{groovyDslPath}/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:ignoreFailures[Test.ignoreFailures] 设置.

Source sets 还为您在集成测试中放置源文件的位置提供了很大的灵活性. 您可以轻松地将它们保存在与单元测试相同的目录中,或更优选地,保存在单独的源目录中,例如 `src/integTest/java`. 为了支持其他类型的测试,您只需添加更多的 source sets 和 link:{groovyDslPath}/org.gradle.api.tasks.testing.Test.html[Test] 任务！

[[migmvn:common_plugins]]
== 迁移常用插件

Maven 和 Gradle 共享一种通过插件扩展构建的通用方法. 尽管表面上的插件系统有很大不同,但是它们共享许多基于功能的插件,例如:

* Shade/Shadow
* Jetty
* Checkstyle
* JaCoCo
* AntRun (see further down)

为什么这么重要?  因为许多插件都依赖于标准 Java 约定,所以迁移仅是在 Gradle 中复制 Maven 插件的配置即可. 例如,这是一个简单的 Maven Checkstyle 插件配置:

[source,xml]
----
...
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-checkstyle-plugin</artifactId>
  <version>2.17</version>
  <executions>
    <execution>
      <id>validate</id>
      <phase>validate</phase>
      <configuration>
        <configLocation>checkstyle.xml</configLocation>
        <encoding>UTF-8</encoding>
        <consoleOutput>true</consoleOutput>
        <failsOnError>true</failsOnError>
        <linkXRef>false</linkXRef>
      </configuration>
      <goals>
        <goal>check</goal>
      </goals>
    </execution>
  </executions>
</plugin>
...
----

迁移到 Gradle 时,可以安全地忽略配置块之外的所有内容.
在这种情况下,相应的Gradle配置如下所示:

.Configuring the Gradle Checkstyle Plugin
====
include::{snippets-dir}/mavenMigration/basic/groovy/build.gradle[tags=checkstyle]
include::{snippets-dir}/mavenMigration/basic/kotlin/build.gradle.kts[tags=checkstyle]
====

Checkstyle 任务会自动添加为 `check` 任务的依赖,其中也包括 `test`. 如果要确保Checkstyle在测试之前运行,则只需使用 mustRunAfter() 方法指定顺序:

.Controlling when the `checkstyle` task runs
====
include::{snippets-dir}/mavenMigration/basic/groovy/build.gradle[tags=depends-on]
include::{snippets-dir}/mavenMigration/basic/kotlin/build.gradle.kts[tags=depends-on]
====

如您所见,Gradle 配置通常比 Maven 等效配置短得多. 您还拥有一个更加灵活的执行模型,因为您不再受 Maven 固定阶段的约束.

从 Maven 迁移项目时,请不要忘记  source sets. 与 Maven 相比,它们通常为处理集成测试或生成的源提供了更优雅的解决方案,因此您应将它们纳入迁移计划中.

=== Ant 目标

许多 Maven 构建依赖于 AntRun 插件来自定义构建,而无需实现自定义Maven插件的开销. Gradle 没有等效的插件,因为 Ant 通过 `ant` 对象是 Gradle 构建中的一等公民. 例如,您可以像这样使用 Ant 的 Echo 任务:

.Invoking Ant tasks
====
include::{snippets-dir}/mavenMigration/ant/groovy/build.gradle"]
include::{snippets-dir}/mavenMigration/ant/kotlin/build.gradle.kts"]
====

本机还支持Ant属性和文件集. 要了解更多信息,请参阅 <<ant#ant,在 Gradle 中使用 Ant>>.

[TIP]
====
仅创建 <<custom_tasks#custom_tasks,自定义任务类型>>来替换Ant为您所做的工作可能更简单,更简洁. 然后,您可以更轻松地从 <<more_about_tasks#sec:up_to_date_checks,增量构建>>和其他有用的 Gradle 功能中受益.
====

[[migmvn:unnecessary_plugins]]
== 了解您不需要哪些插件

值得记住的是,Gradle 版本通常比 Maven 版本更易于扩展和自定义. 在这种情况下,这意味着您可能不需要 Gradle 插件来替换 Maven. 例如,Maven Enforcer 插件允许您控制依赖版本和环境因素,
但是可以在常规 Gradle 构建脚本中轻松配置这些内容.

[[migmvn:custom_plugins]]
== 处理不常见和自定义的插件

您可能会遇到在 Gradle 中没有对应版本的 Maven 插件,特别是如果您或组织中的某人已编写了自定义插件. 这种情况取决于您了解 Gradle(以及可能的 Maven)的工作方式,因为您通常必须编写自己的插件.

为了进行迁移,Maven 插件有两种主要类型:

* 那些使用 Maven project 对象的对象.
* 那些没有.

为什么这很重要?  因为如果使用后者之一,则可以轻松地将其重新实现为 <<custom_tasks#custom_tasks,自定义 Gradle 任务类型>>. 只需定义与 mojo 参数相对应的任务输入和输出,然后将执行逻辑转换为任务动作即可.

如果插件依赖于 Maven 项目,那么您将不得不重写它. 不要先考虑 Maven 插件的工作原理,而要看看它正在尝试解决什么问题. 然后尝试解决如何在 Gradle 中解决该问题.
您可能会发现这两个构建模型之间的差异足以使Maven插件代码  "transcribing"  到 Gradle 插件中才有效. 从好的方面来说,该插件可能比原始的 Maven 插件更容易编写,因为 Gradle 具有更丰富的构建模型和API.

如果确实需要通过构建脚本或插件来实现自定义逻辑,请查看与 https://gradle.org/guides/?q=Plugin%20Development[插件开发相关的指南]. 另外,请务必熟悉 Gradle 的 link:{groovyDslPath}/[Groovy DSL Reference],该参考提供了有关您将使用的 API 的全面文档.
它详细介绍了标准配置块(以及支持它们的对象),系统中的核心类型(`Project`, `Task` 等)以及任务类型的标准集. 主要的入口点是 link:{groovyDslPath}/org.gradle.api.Project.html[Project] 接口,它是支持构建脚本的顶级对象.

== 进一步阅读

本章涵盖了将 Maven 构建迁移到 Gradle 的主要主题. 剩下的就是迁移期间或迁移之后可能有用的其他一些方面:

 * 了解如何配置 Gradle 的 <<build_environment#build_environment,构建环境>>,包括用于运行 Gradle 的 JVM 设置
 * 了解如何 <<organizing_gradle_projects#organizing_gradle_projects,有效构建构建>>
 * <<logging#logging,配置 Gradle 的日志>> 并在您的构建中使用

最后,本指南仅涉及 Gradle 的一些功能,我们鼓励您从用户手册的其他章节以及 link:../samples/index.html[step-by-step samples] 中了解其余内容.