== 系统设计面试: 逐步指导

许多软件工程师在系统设计面试（SDI）时遇到困难，主要有以下三个原因：

* SDI的非结构化特性，要求他们处理没有标准答案的开放式设计问题；
* 他们缺少开发大型可扩展系统的经验；
* 他们没有为SDI做准备。

和编码面试一样，应聘者没有有意识地为SDI做准备，大多会表现不佳，尤其是在Google、Facebook、Amazon、Microsoft等顶尖公司中。在这些公司中，表现不及平均水平的应聘者获得offer的机会很渺茫。另一方面，有良好表现的应聘者总会获得更好的offer（更高的职位和薪水），因为它展示了应聘者处理复杂系统的能力。

在这个课程中，我们将循序渐进地解决多个设计问题。首先，让我们了解以下这些步骤：

=== 步骤 1: 需求说明

在我们要解决的问题的精确范围内提出问题总是一个好主意。系统设计问题大多是开放性的，他们没有一个固定的正确答案，这就是为什么面试者在一开始就说明歧义是至关重要的原因。应聘者花费足够的时间定义系统的最终目标，可以使其增加面试成功的机会。另外，由于我们只有30-40分钟来设计（假设）大型系统，因此我们应该弄清楚我们将重点放在系统的哪些部分。


让我们设计一个类似Twitter服务的实际案例来说明这个问题。在进行下一步之前，我们应该先回答下面这些问题：

* 我们服务的用户能否发布推文并关注其他人？
* 我们还应该设计去创建并展示用户的时间轴吗？
* 推文包含照片和视频吗？
* 我们只关注后端逻辑或者我们也要开发前端页面？
* 用户可以搜索推文吗？
* 我们需要显示热门话题吗？
* 对于新的或重要的推文是否要推送通知？

所有这样的问题将决定我们最终设计的外观。

=== Step 2: 系统接口定义

定义系统向外暴露的API。这不仅建立了系统预期的确切目标，而且也保证我们没有错误的需求。我们类似Twitter服务的一些例子如下所示：

[source, text]
----
    postTweet(user_id,  tweet_data,  tweet_location,  user_location,  timestamp,  …)
    generateTimeline(user_id,   current_time,   user_location,   …)
    markTweetFavorite(user_id,  tweet_id,  timestamp,  …)
----

=== Step 3: Back-of-the-envelope estimation
估计我们设计的系统的规模总是一个好主意。当我们将重点放在扩展、分区、负载均衡和缓存时，这将会给我们提供帮助。

* 系统预期的规模是多大（比如：新推文的数量、推文视图的数量、每秒生成的时间轴的数量等等）？
* 我们需要多大的存储空间？如果用户在他们的推文中同时包含图片和视频，我们需要有不同的账号
* 我们预期的网络带宽是多少？这对于我们如何管理服务器之间的网络传输和负载均衡很重要。


=== Step 4: 定义数据模型


尽早定义数据模型将阐明数据如何在系统的不同组件之间进行传输。随后，它将指导对数据的分区和管理。候选人应该可以识别系统的不同实体，它们之间的交互方式，和数据管理的不同方面，例如存储、传输、加密等。下面是我们类似Twitter服务系统的一些实体：

[source,text]
----
User: UserID, Name, Email, DoB, CreationData, LastLogin, etc.
Tweet: TweetID, Content, TweetLocation, NumberOfLikes, TimeStamp, etc.
UserFollowo: UserdID1, UserID2
FavoriteTweets: UserID, TweetID, TimeStamp
----
我们应该使用哪种数据库？像https://en.wikipedia.org/wiki/Apache_Cassandra[Cassandra]这样的NoSQL能否满足我们的需求？或者我们应该使用类似MySQL这样的关系型数据库？我们应该使用哪种块存储来保存图片和视频？

=== Step 5: 高级设计

画一个带有5-6个方框的框图，表示我们系统的核心组件。我们应该确定端到端解决实际问题所需要的足够组件。

对于Twitter而言，在更高级别上，我们将需要多个应用程序服务器来满足所有的读/写请求，并在请求的前面放置负载均衡器以进行流量的分配。假设我们有更多的读取流量（相较于写请求），则可以使用单独的服务器来处理这些读请求。在后端，我们需要足够的数据库来存储所有的推文，并且可以支持大量的读请求。我们也需要一个分布式文件存储系统来保存图片和视频。


=== Step 6: 详细设计

深入理解两到三个组件，面试者的反馈始终是指引我们进一步讨论系统的哪些部分。我们应该提出不同的方法，它们的利弊，并解释为什么要选择这一种方法。请记住，答案不是唯一的，唯一重要的是我们考虑系统约束的同时考虑不同方法的取舍。

* 因为我们将存储巨量的数据，所以我们将如何将数据分区到多个数据库中？我们应该尝试存储一个用户的所有数据在同一个数据库上吗？它会造成什么问题？
* 我们如何处理发送大量推文或关注很多人的热门用户？
* 由于用户的时间轴将包含最新的（相关的）推文，我们是否尝试以优化的方式存储数据以扫描最新的推文？
* 我们应该在那个层级引入缓存以加速访问？
* 哪些组件需要更好的负载均衡？

=== Step 7: 识别并解决瓶颈
尝试讨论尽可能多的瓶颈问题以及缓解这些瓶颈的不同方案。

* 系统是否有单点故障？我们将采取什么方案解决这个问题？
* 我们是否有足够的数据备份，以便于当我们丢失一部分服务器时，仍可以为我们的用户提供服务？
* 类似地，不同服务是否有足够的备份在运行，因此少数的服务故障不会造成系统完全关闭？
* 我们如何监控服务的性能？当关键组件故障或者它的性能下降时，我们能否收到报警？

=== 总结
总而言之，对系统设计面试期间的准备和组织是面试成功的关键。上述提及的步骤应指导你跟踪并覆盖设计一个系统的所有的不同方面。

让我们根据以上指南设计一些SDI中提及到的系统吧。
