= Designing a URL Shortening service like TinyURL

= 设计类似TinyURL的短URL服务

让我们设计一个类似TinyURL的短URL服务。这个服务会将短的别名重定向到长的URL上。类似的服务有：bit.ly、goo.gl、qlink.me等等。困难等级：简单。


== 1.为什么需要简短的URL?

URL压缩服务用于为长URL创建一个更短的别名。我们将这些缩短的别名称之为"短链接"。当用户点击这些短链接时，他们会被重定向到原始的URL上。当在展示、打印、传输或者发推文时，短链接节省了很大的空间。此外，用户很少输错短链接。

例如，我们通过TinyURL缩短这个页面的URL：

https://www.educative.io/collection/page/5668639101419520/5649050225344512/5668600916475904/

我们将得到:

http://tinyurl.com/jlg8zpc

压缩后的URL大约是原始URL的三分之一大小。

URL压缩用于优化设备之间的链接，跟踪单个链接来分析受众和运行性能，并且隐藏相关联的原始URL。

如果你以前没有用过http://tinyurl.com[tinyurl.com]，请尝试创建一个新的压缩URL，并花费一些时间了解网站提供的不同的选项。这有助于你明白这章的内容。

== 2.系统需求和目标

[NOTE]
_你应该在面试开始时阐明系统的需求。确保面试官提出的问题在系统的确切范围之内。_

我们的URL压缩系统应该会有一下需求：


*功能性需求：*

1. 我们系统应该为给定的URL生成一个更短的且唯一的别名。这称之为短链接。
2. 当用户访问短链接时，我们的系统应该将它们重定向到原始URL链接上。
3. 用户应该可以为其URL自定义短链接名。
4. 链接将在默认时间后过期。用户可以指定过期时间

*非功能性需求：*

1. 系统应该高可用。 这是因为，如果服务宕机，那么所有的URL重定向将会失败。
2. URL重定向应该以最小的延迟时间实时进行。
3. 短链接不应该让人猜到（不可预测的）

*扩展需求：*

. 分析；例如，URL重定向发生了多少次？
. 其他服务也可以通过REST APIs访问我们的服务。

== 3.容量估计和约束

我们的系统将会是工作繁重的。与新的URL压缩相比，会有很多重定向的请求。假设读请求和写请求的比率为100：1。

**流量估算：**假设，我们每月有500M个新的压缩URL，以100：1的读写比来计算，这一时期内我们预计有50B个URL重定向：

[source,text]
----
100 * 500M => 50B
----

我们系统的每秒查询数量（QPS）是多少？每秒新URL压缩是：

[source,text]
----
5,000,000,000 / (30 天 * 24 时 * 3600 秒) = ~200 URLs/s
----

考虑到100：1的读/写比，每秒URL重定向是：

[source,text]
----
100 * 200 URLs/s = 20K/s
----

存储空间估算：假设我们将每条URL压缩请求（及其相关的短链接）存储5年。因为我们每月有5亿个新的URL，因此我们希望存储的对象总数是30亿。

[source,text]
----
500 million * 5 years * 12 months = 30 billion
----

假设存储的对象每个大约是500字节（只是一个大概的预估，稍后我们将对其深入研究），我们将需要15TB的存储空间：

[source, text]
----
30 billion * 500 bytes = 15 TB
----

带宽预估：对于写请求，因为我们预估每秒有200个新的URL，所以我们的服务接收到的数据总量是每秒100KB：

[source, text]
----
200 * 500 bytes = 100 KB/s
----

对于读请求，因为我们预估每秒有20K个URL重定向，所以我们的服务总传出的数据量是每秒10MB：

[source, text]
----
20K * 500 bytes = ~10 MB/s
----

内存估算：如果我们想要缓存一些频繁访问的热点URL，我们将需要多大的内存来存储它们呢？如果我们遵循2-8法则，即20%的URL产生80%的流量，我们将会缓存20%的热点URL。

因为每秒有2万个请求，所以一天大约会有17亿个请求。

[source, text]
----
20K * 3600 seconds * 24 hours = ~1.7 billion
----

为了缓存20%的请求URL，我们将需要170GB大小的内存。

[source, text]
----
0.2 * 1.7 billion * 500 bytes = ~170GB
----

要注意的是，因为将会有大量重复的请求（相同的URL），因此，我们实际使用的内存将小于170GB。

*高层级预估：* 假设每月有5亿个新的URL，和100：1的读写比，以下是我们服务的高层级预估的概览：

[source, text]
----
New URLs 200/s
URL redirections 20K/s
Incoming data 100KB/s
Outgoing data 10MB/s
Storage for 5 years 15TB
Memory for cache 170GB
----

== 4.系统APIs
[NOTE]
_一旦我们整理完需求，定义系统API是一个很好的选择。应该显示地声明系统期望的内容。_

我们可以使用SOAP或REST API对外暴露我们服务的功能。以下定义的API用于创建和删除URL：

[source, text]
----
createURL(api_dev_key, original_url, custom_alias=None, user_name=None,
expire_date=None)
----

*参数：*
api_dev_key (string)：注册账户的API开发者密钥。此外，这还用于根据分配的配额限制用户。

original_url (string): 被压缩的原始URL。

custom_alias (string): URL的可选的自定义值。

user_name (string): 编码中使用的可选的用户名。

expire_date (string): 压缩URL可选的过期时间。

*返回值： (string)*
成功新增后返回压缩的URL；否则，返回错误码。

[source, text]
----
deleteURL(api_dev_key, url_key)
----

“url_key”表示一个可被检索的压缩URL字符串。成功删除后将返回“URL Removed”。

*我们如何检测和防止数据滥用？* 在当前的设计中，恶意用户可以通过消耗所有的URL密钥来迫使我们破产。为了防止数据滥用，我们可以通过用户的api_dev_key来限制用户。每一个api_dev_key可以限制URL的创建数量和一段时间内URL重定向的数量（可以为每个开发者的密钥设置不同的时间段）。

== 5. Database Design
[NOTE]
在面试的早期阶段定义数据库模式将有助于理解不同组件之间的数据流，之后会指导数据分区。

关于我们将存储的数据的性质的一些观察如下：

. 我们需要存储数十亿条记录。
. 存储的每个对象都很小（小于1K）。
. 记录与除了存储创建URL的用户有关联，与其他的记录是没有关系的。
. 我们的服务是包含大量读操作的。

*数据库模式：*
我们需要两张表：一个用于存储URL映射的相关信息，一个存储创建短链接的用户数据。



*我们使用哪种数据库呢？* 因为我们预计要存储数十亿行数据，并且我们不需要使用对象之间的关系，NoSQL的键值对存储，如 https://en.wikipedia.org/wiki/Amazon_DynamoDB[DynamoDB] 、 https://en.wikipedia.org/wiki/Apache_Cassandra[Cassandra] 或 https://en.wikipedia.org/wiki/Riak[Riak] 都是一个很好的选择。选择使用NoSQL也更容易扩展。详情请参考 https://www.educative.io/collection/page/5668639101419520/5649050225344512/5728116278296576/[SQL vs NoSQL]。


== 6. 基本系统设计与算法
本节要解决的问题是，如何为给定的URL生成一个短的且唯一的值。

在第一章的TinyURL例子中，压缩的URL是“http://tinyurl.com/jlg8zpc”。这个URL的最后6位字符是我们想生成的短值。我们在这提供了两种解决方案：

=== 6.1. 编码实际的URL

我们计算给定URL的唯一hash值（如： https://en.wikipedia.org/wiki/MD5[MD5] 或者 https://en.wikipedia.org/wiki/SHA-2[SHA256] 等）。然后对hash值进行编码以进行展示。这种编码可以是base36（[a-z, 0-9]）或者base62([A-Z, a-z, 0-9])，并且如果我们添加‘-’和‘.’，那么我们可以使用base64编码。一个合理的问题是，压缩键的长度应该是几个字符？6个、8个或者10个字符。

使用base64编码，一串6个字母长的键将生成64^6=约687亿种不同的字符串。
使用base64编码，一串8个字幕长的键将生成64^8=约281万亿种不同的字符串。

假设有687亿种唯一字符串，那么6个字母的足以满足我们的系统。

If we use the MD5 algorithm as our hash function, it’ll produce a 128-bit hash value. After base64
encoding, we’ll get a string having more than 21 characters (since each base64 character encodes 6 bits
of the hash value). Since we only have space for 8 characters per short key, how will we choose our key
then? We can take the first 6 (or 8) letters for the key. This could result in key duplication though, upon
which we can choose some other characters out of the encoding string or swap some characters.

*What are different issues with our solution?* We have the following couple of problems with our
encoding scheme:

1. If multiple users enter the same URL, they can get the same shortened URL, which is not
acceptable.
2. What if parts of the URL are URL-encoded? e.g., http://www.educative.io/distributed.php?
id=design, and http://www.educative.io/distributed.php%3Fid%3Ddesign are identical except
for the URL encoding.

*Workaround for the issues:* We can append an increasing sequence number to each input URL to
make it unique, and then generate a hash of it. We don’t need to store this sequence number in the
databases, though. Possible problems with this approach could be an ever-increasing sequence number.
Can it overflow? Appending an increasing sequence number will also impact the performance of the
service.

Another solution could be to append user id (which should be unique) to the input URL. However, if
the user has not signed in, we would have to ask the user to choose a uniqueness key. Even after this, if
we have a conflict, we have to keep generating a key until we get a unique one.


=== 6.2. Generating keys offline
We can have a standalone Key Generation Service (KGS) that generates random six letter strings
beforehand and stores them in a database (let’s call it key-DB). Whenever we want to shorten a URL,
we will just take one of the already-generated keys and use it. This approach will make things quite
simple and fast. Not only are we not encoding the URL, but we won’t have to worry about duplications
or collisions. KGS will make sure all the keys inserted into key-DB are unique

*Can concurrency cause problems?* As soon as a key is used, it should be marked in the database to
ensure it doesn’t get used again. If there are multiple servers reading keys concurrently, we might get a
scenario where two or more servers try to read the same key from the database. How can we solve this
concurrency problem?

Servers can use KGS to read/mark keys in the database. KGS can use two tables to store keys: one for
keys that are not used yet, and one for all the used keys. As soon as KGS gives keys to one of the
servers, it can move them to the used keys table. KGS can always keep some keys in memory so that it
can quickly provide them whenever a server needs them.

For simplicity, as soon as KGS loads some keys in memory, it can move them to the used keys table.
This ensures each server gets unique keys. If KGS dies before assigning all the loaded keys to some
server, we will be wasting those keys–which is acceptable, given the huge number of keys we have.
KGS also has to make sure not to give the same key to multiple servers. For that, it must synchronize
(or get a lock on) the data structure holding the keys before removing keys from it and giving them to a
server

*What would be the key-DB size?* With base64 encoding, we can generate 68.7B unique six letters
keys. If we need one byte to store one alpha-numeric character, we can store all these keys in:

[source,text]
----
6 (characters per key) * 68.7B (unique keys) = 412 GB.
----

Isn’t KGS a single point of failure? Yes, it is. To solve this, we can have a standby replica of KGS.
Whenever the primary server dies, the standby server can take over to generate and provide keys.
Can each app server cache some keys from key-DB? Yes, this can surely speed things up. Although
in this case, if the application server dies before consuming all the keys, we will end up losing those
keys. This can be acceptable since we have 68B unique six letter keys.
How would we perform a key lookup? We can look up the key in our database or key-value store to
get the full URL. If it’s present, issue an “HTTP 302 Redirect” status back to the browser, passing the
stored URL in the “Location” field of the request. If that key is not present in our system, issue an
“HTTP 404 Not Found” status or redirect the user back to the homepage.
Should we impose size limits on custom aliases? Our service supports custom aliases. Users can pick
any ‘key’ they like, but providing a custom alias is not mandatory. However, it is reasonable (and often
desirable) to impose a size limit on a custom alias to ensure we have a consistent URL database. Let’s
assume users can specify a maximum of 16 characters per customer key (as reflected in the above
database schema).

High level system design for URL shortening

== 7. Data Partitioning and Replication

To scale out our DB, we need to partition it so that it can store information about billions of URLs. We
need to come up with a partitioning scheme that would divide and store our data to different DB servers.

.. Range Based Partitioning: We can store URLs in separate partitions based on the first letter of the URL or the hash key. Hence we save all the URLs starting with letter ‘A’ in one partition, save those that start with letter ‘B’ in another partition and so on. This approach is called range-based partitioning. We can even combine certain less frequently occurring letters into one database partition. We should come up with a static partitioning scheme so that we can always store/find a file in a predictable manner.

The main problem with this approach is that it can lead to unbalanced servers. For example: we decide to put all URLs starting with letter ‘E’ into a DB partition, but later we realize that we have too many URLs that start with letter ‘E’.

.. Hash-Based Partitioning: In this scheme, we take a hash of the object we are storing. We then calculate which partition to use based upon the hash. In our case, we can take the hash of the ‘key’ or the actual URL to determine the partition in which we store the data object.

Our hashing function will randomly distribute URLs into different partitions (e.g., our hashing function can always map any key to a number between [1…256]), and this number would represent the partition in which we store our object.

This approach can still lead to overloaded partitions, which can be solved by using https://www.educative.io/collection/page/5668639101419520/5649050225344512/5709068098338816/[ConsistentHashing].


== 8. Cache

We can cache URLs that are frequently accessed. We can use some off-the-shelf solution like Memcache, which can store full URLs with their respective hashes. The application servers, before hitting backend storage, can quickly check if the cache has the desired URL.

*How much cache should we have?* We can start with 20% of daily traffic and, based on clients’ usage pattern, we can adjust how many cache servers we need. As estimated above, we need 170GB memory to cache 20% of daily traffic. Since a modern-day server can have 256GB memory, we can easily fit all the cache into one machine. Alternatively, we can use a couple of smaller servers to store all these hot URLs.

*Which cache eviction policy would best fit our needs?* When the cache is full, and we want to replace a link with a newer/hotter URL, how would we choose? Least Recently Used (LRU) can be a reasonable policy for our system. Under this policy, we discard the least recently used URL first. We can use a https://docs.oracle.com/javase/7/docs/api/java/util/LinkedHashMap.html[LinkedHashMap] or a similar data structure to store our URLs and Hashes, which will also keep track of the URLs that have been accessed recently.

To further increase the efficiency, we can replicate our caching servers to distribute load between them.

*How can each cache replica be updated?* Whenever there is a cache miss, our servers would be hitting a backend database. Whenever this happens, we can update the cache and pass the new entry to all the cache replicas. Each replica can update their cache by adding the new entry. If a replica already has that entry, it can simply ignore it.


== 9.Load Balancer (LB)

We can add a Load balancing layer at three places in our system:

. Between Clients and Application servers
. Between Application Servers and database servers
. Between Application Servers and Cache servers

Initially, we could use a simple Round Robin approach that distributes incoming requests equally among backend servers. This LB is simple to implement and does not introduce any overhead. Another benefit of this approach is that if a server is dead, LB will take it out of the rotation and will stop sending any traffic to it.

A problem with Round Robin LB is that server load is not taken into consideration. If a server is overloaded or slow, the LB will not stop sending new requests to that server. To handle this, a more intelligent LB solution can be placed that periodically queries the backend server about its load and adjusts traffic based on that.

== 10. Purging or DB cleanup

Should entries stick around forever or should they be purged? If a user-specified expiration time is reached, what should happen to the link?

If we chose to actively search for expired links to remove them, it would put a lot of pressure on our database. Instead, we can slowly remove expired links and do a lazy cleanup. Our service will make sure that only expired links will be deleted, although some expired links can live longer but will never be returned to users.

* Whenever a user tries to access an expired link, we can delete the link and return an error to the user.
* A separate Cleanup service can run periodically to remove expired links from our storage and
cache. This service should be very lightweight and can be scheduled to run only when the user traffic is expected to be low.
* We can have a default expiration time for each link (e.g., two years).
* After removing an expired link, we can put the key back in the key-DB to be reused.
* Should we remove links that haven’t been visited in some length of time, say six months? This
could be tricky. Since storage is getting cheap, we can decide to keep links forever.

Detailed component design for URL shortening


== 11. Telemetry

How many times a short URL has been used, what were user locations, etc.? How would we store these statistics? If it is part of a DB row that gets updated on each view, what will happen when a popular URL is slammed with a large number of concurrent requests?

Some statistics worth tracking: country of the visitor, date and time of access, web page that refers the click, browser, or platform from where the page was accessed.

== 12.Security and Permissions

Can users create private URLs or allow a particular set of users to access a URL?

We can store permission level (public/private) with each URL in the database. We can also create a separate table to store UserIDs that have permission to see a specific URL. If a user does not have permission and tries to access a URL, we can send an error (HTTP 401) back. Given that we are storing our data in a NoSQL wide-column database like Cassandra, the key for the table storing permissions would be the ‘Hash’ (or the KGS generated ‘key’). The columns will store the UserIDs of those users that have permissions to see the URL.
