[[preface]]
= 前言

Spring Data JDBC 项目将 Spring 的核心概念应用于开发使用符合 <<jdbc.domain-driven-design,领域驱动设计原则>>的 JDBC 数据库的解决方案。我们提供了一个 "`template`"，作为存储和查询聚合体（aggregate）的高级抽象。

本文档是 Spring Data JDBC 支持的参考指南。它解释了概念和语义以及语法。

本节提供了一些基本介绍。文件的其余部分只提到 Spring Data JDBC 的功能，并假设用户熟悉 SQL 和 Spring 的概念。

[[get-started:first-steps:spring]]
== 学习 Spring

Spring Data 使用 Spring framework {spring-framework-docs}/core.html[核心] 功能, 包括:

* {spring-framework-docs}/core.html#beans[IoC] 容器
* {spring-framework-docs}/core.html#validation[类型转换系统]
* {spring-framework-docs}/core.html#expressions[表达式语言]
* {spring-framework-docs}/integration.html#jmx[JMX 集成]
* {spring-framework-docs}/data-access.html#dao-exceptions[DAO 异常层次结构].

虽然您不需要了解 Spring 的 API，但理解它们背后的概念很重要。 至少，控制反转 (IoC) 背后的思想应该很熟悉，而且您应该熟悉您选择使用的任何 IoC 容器。

JDBC Aggregate 支持的核心功能可以直接使用，不需要调用 Spring Container 的 IoC 服务。
这很像 `JdbcTemplate`，它可以 "独立" 使用，不需要 Spring 容器的任何其他服务。
要利用 Spring Data JDBC 的所有功能，例如存储库支持，您需要配置库的某些部分以使用 Spring。

要了解更多有关 Spring 的知识，您可以参考详细解释 Spring Framework 的综合文档。 有很多关于该主题的文章、博客和书籍。 有关详细信息，请参阅 Spring 框架 https://spring.io/docs[主页]。

[[requirements]]
== 要求

Spring Data JDBC 需要 JDK 8.0 及以上版本和 https://spring.io/docs[Spring Framework] {springVersion} 及以上版本。
在数据库方面，Spring Data JDBC 需要一种 <<jdbc.dialects,方言>> 来抽象出通用的 SQL 功能，而不是供应商特定的风格。Spring Data JDBC 包括对以下数据库的直接支持。

* DB2
* H2
* HSQLDB
* MariaDB
* Microsoft SQL Server
* MySQL
* Oracle
* Postgres

如果你使用一个不同的数据库，那么你的应用程序将无法启动。<<jdbc.dialects,方言>> 部分包含在这种情况下如何进行的进一步细节。

[[get-started:help]]
== 额外的帮助资源

学习一个新的框架并不总是简单明了的。在本节中，我们试图提供一个我们认为是简单易行的指南，让大家开始学习 Spring Data JDBC 模块。然而，如果你遇到问题或需要建议，请随时使用以下链接。

[[get-started:help:community]]
社区板块 :: https://stackoverflow.com/questions/tagged/spring-data[Stack Overflow] 上的 Spring Data 标签所有的 Spring Data 项目(不仅仅 Document) 用户分享信息和相互帮助的一个 tag。请注意，只有在发帖时才需要注册。


[[get-started:help:professional]]
专业的支持 :: https://pivotal.io/[Pivotal Sofware, Inc.] 是 Spring Data 和 Spring 背后的公司，可以提供专业的、来自源头的支持，并保证响应时间。

[[get-started:up-to-date]]
== 发展

有关Spring Data JDBC源代码库、每晚构建和快照工件的信息，请参阅 Spring Data JDBC https://spring.io/projects/spring-data-jdbc/[主页]。
您可以通过 https://stackoverflow.com/questions/tagged/spring-data[Stack Overflow] 上的社区与开发人员互动，帮助 Spring Data 最好地满足 Spring 社区的需求。
如果你遇到了一个错误或想提出改进建议，请在 https://github.com/spring-projects/spring-data-jdbc/issues[Spring Data issue tracker] 上创建一个 ticket。
要想了解 Spring 生态中的最新新闻和公告，请订阅 Spring Community https://spring.io[Portal]。你也可以在 Twitter (https://twitter.com/SpringData[SpringData]) 上关注 Spring https://spring.io/blog[博客]或项目团队。

[[project]]
== 项目元数据

* Release repository: https://repo.spring.io/libs-release
* Milestone repository: https://repo.spring.io/libs-milestone
* Snapshot repository: https://repo.spring.io/libs-snapshot
