[[query-by-example.running]]
== 运行 Example

在 Spring Data JDBC 中，你可以使用 Repository 的 Query by Example，如以下例子所示。

.Query by Example using a Repository
====
[source, java]
----
public interface PersonRepository
        extends CrudRepository<Person, String>,
        QueryByExampleExecutor<Person> { … }

public class PersonService {

  @Autowired PersonRepository personRepository;

  public List<Person> findPeople(Person probe) {
    return personRepository.findAll(Example.of(probe));
  }
}
----
====

NOTE: 目前，只有 `SingularAttribute` 属性可用于属性匹配。

property specifier （属性指定器）接受属性名称（如 `firstname` 和 `lastname`）。你可以通过将属性用点连接起来进行导航（`address.city`）。你还可以用匹配选项和大小写敏感性来调整它。

下表显示了你可以使用的各种 `StringMatcher` 选项以及在一个名为 `firstname` 的字段上使用这些选项的结果。

[cols="1,2", options="header"]
.`StringMatcher` options
|===
| Matching
| Logical result

| `DEFAULT` (case-sensitive)
| `firstname = ?0`

| `DEFAULT` (case-insensitive)
| `LOWER(firstname) = LOWER(?0)`

| `EXACT`  (case-sensitive)
| `firstname = ?0`

| `EXACT` (case-insensitive)
| `LOWER(firstname) = LOWER(?0)`

| `STARTING`  (case-sensitive)
| `firstname like ?0 + '%'`

| `STARTING` (case-insensitive)
| `LOWER(firstname) like LOWER(?0) + '%'`

| `ENDING`  (case-sensitive)
| `firstname like '%' + ?0`

| `ENDING` (case-insensitive)
| `LOWER(firstname) like '%' + LOWER(?0)`

| `CONTAINING`  (case-sensitive)
| `firstname like '%' + ?0 + '%'`

| `CONTAINING` (case-insensitive)
| `LOWER(firstname) like '%' + LOWER(?0) + '%'`

|===
