[[authentication-password-storage]]
= 密码存储

Spring Security的 `PasswordEncoder` 接口用于对密码执行单向转换，以允许安全地存储密码。 鉴于 `PasswordEncoder` 是一种单向转换，
因此当密码转换需要采用两种方式（即存储用于向数据库进行身份验证的凭据）时，则不打算使用它。 通常，`PasswordEncoder` 用于存储需要在身份验证时与用户提供的密码进行比较的密码。

[[authentication-password-storage-history]]
== 密码存储历史

多年来，用于存储密码的标准机制已经发展。 最初，密码以纯文本格式存储。 假设密码是安全的，因为密码已保存在访问它所需的凭据中。
但是，恶意用户能够使用SQL 注入 这样的攻击找到方法来获取用户名和密码的大量的 "data dumps"。 随着越来越多的用户凭证成为公共安全专家，我们意识到我们需要做更多的工作来保护用户密码。

然后鼓励开发人员在通过诸如 SHA-256 之类的单向哈希算法加密后存储密码。 当用户尝试进行身份验证时，会将加密后的密码与他们输入的密码的散列值进行比较。 这意味着系统仅需要存储密码的单向哈希。 如果发生违规，则仅暴露密码的一种哈希方式。
由于散列是一种方式，计算出给定哈希值的密码很难计算，因此找出系统中的每个密码都不值得。 为了破解密码，恶意用户决定创建称为  https://en.wikipedia.org/wiki/Rainbow_table[Rainbow Tables] 的查找表。 他们不必每次都猜测每个密码，而是计算一次密码并将其存储在查找表中。

为了预防 彩虹表 的破解攻击，鼓励开发人员使用加盐的密码。 不仅将密码用作哈希函数的输入，还将为每个用户的密码生成随机字节（称为 `salt` ）。 盐和用户密码将通过散列函数运行，从而产生唯一的散列。 盐将以明文形式与用户密码一起存储。
然后，当用户尝试进行身份验证时，会将哈希密码与存储的盐的哈希值和他们输入的密码进行比较。 唯一的盐意味着 `彩虹表` 不再有效，因为每种盐和密码组合的哈希值都不同。

在现代，我们意识到加密哈希（例如SHA-256）不再安全。 原因是使用现代硬件，我们可以每秒执行数十亿次哈希计算。 这意味着我们可以轻松地分别破解每个密码。

现在鼓励开发人员利用自适应单向功能来存储密码。 具有自适应单向功能的密码验证意味着会消耗大量资源（即CPU，内存等）。
自适应单向功能允许配置 "work factor" ，该因数会随着硬件的改进而增加。 建议将 "work factor" 调整为大约1秒钟，以验证系统上的密码。 这种权衡使攻击者难以破解密码，但代价却不高，这给您自己的系统带来了沉重负担。
Spring Security试图为 "work factor" 提供一个良好的起点，但是鼓励用户为自己的系统自定义 "work factor" ，因为不同系统之间的性能会有很大差异。 具有自适应单向功能的有 https://en.wikipedia.org/wiki/Bcrypt[bcrypt],
https://en.wikipedia.org/wiki/PBKDF2[PBKDF2],
https://en.wikipedia.org/wiki/Scrypt[scrypt],
和 https://en.wikipedia.org/wiki/Argon2[Argon2]

由于自适应单向功能有意占用大量资源，因此为每个请求验证用户名和密码都会大大降低应用程序的性能。 Spring Security（或任何其他库）无法采取任何措施来加快密码的验证速度，因为通过增加验证资源的强度来获得安全性。
鼓励用户将长期凭证（即用户名和密码）交换为短期凭证（即会话，OAuth令牌等）。 可以快速验证短期凭证，而不会损失任何安全性。


[[authentication-password-storage-dpe]]
== DelegatingPasswordEncoder

在Spring Security 5.0之前，默认的 `PasswordEncoder` 是 `NoOpPasswordEncoder`，它需要纯文本密码。 根据 <<authentication-password-storage-history,“密码历史记录”>> 所述，您可能希望默认的 `PasswordEncoder` 是 `BCryptPasswordEncoder`。 但是，这忽略了三个现实问题：

- 有许多使用旧密码编码的应用程序无法轻松迁移
- 密码存储的最佳做法将再次更改。
- 作为一个框架，Spring Security不能经常进行重大更改

相反，Spring Security引入了 `DelegatingPasswordEncoder`，它通过以下方式解决了所有问题：

- 确保使用当前密码存储建议对密码进行编码
- 允许以新的和旧式格式验证密码
- 允许将来升级编码

您可以使用 `PasswordEncoderFactories` 轻松构造 `DelegatingPasswordEncoder` 的实例。

[source,java]
----
PasswordEncoder passwordEncoder =
    PasswordEncoderFactories.createDelegatingPasswordEncoder();
----

或者，您可以创建自己的自定义实例。

[source,java]
----
String idForEncode = "bcrypt";
Map encoders = new HashMap<>();
encoders.put(idForEncode, new BCryptPasswordEncoder());
encoders.put("noop", NoOpPasswordEncoder.getInstance());
encoders.put("pbkdf2", new Pbkdf2PasswordEncoder());
encoders.put("scrypt", new SCryptPasswordEncoder());
encoders.put("sha256", new StandardPasswordEncoder());

PasswordEncoder passwordEncoder =
    new DelegatingPasswordEncoder(idForEncode, encoders);
----

[[authentication-password-storage-dpe-format]]
=== 密码存储格式

密码的一般格式是：

.DelegatingPasswordEncoder Storage Format
====
[source,text,attrs="-attributes"]
----
{id}encodedPassword
----
====

这样 `id` 是用于查找应该使用 `PasswordEncoder` 的标识符，`encodedPassword` 是所选 `PasswordEncoder` 的原始编码密码。 `id` 必须位于密码的开头，以 `{` 开头，以 `}` 结束。如果找不到 `id`，则 `id` 将为 `null`。例如，以下可能是使用不同 `id` 编码的密码列表。所有原始密码都是 "password".。


[source,text]
----
{bcrypt}$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG // <1>
{noop}password // <2>
{pbkdf2}5d923b44a6d129f3ddf3e3c8d29412723dcbde72445e8ef6bf3b508fbf17fa4ed4d6b99ca763d8dc // <3>
{scrypt}$e0801$8bWJaSu2IKSn9Z9kM+TPXfOc/9bdYSrN1oD9qfVThWEwdRTnO7re7Ei+fUZRJ68k9lTyuTeUp4of4g24hHnazw==$OAOec05+bXxvuu/1qZ6NUR+xQYvYv7BeL1QxwRpY5Pc=  // <4>
{sha256}97cde38028ad898ebc02e690819fa220e88c62e0699403e94fff291cfffaf8410849f27605abcbc0 // <5>
----

一些用户可能担心为潜在的黑客提供存储格式。这不是问题，因为密码的存储不依赖于算法是 secret。此外，大多数格式很容易让攻击者在没有前缀的情况下弄清楚。例如，BCrypt 密码通常以$2a$开头。

<1> 第一个密码是 id 为 `bcrypt` 的 `PasswordEncoder`，encodedPassword 为 `$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG`。匹配时会委托给 `BCryptPasswordEncoder`
<2> 第二个密码是 id 为 `noop` 的 `PasswordEncoder`，encodedPassword 为 `password`。匹配时会委托给 `NoOpPasswordEncoder`
<3> 第三个密码是 id 为 `pbkdf2` 的 `PasswordEncoder`，encodedPassword 为 `5d923b44a6d129f3ddf3e3c8d29412723dcbde72445e8ef6bf3b508fbf17fa4ed4d6b99ca763d8dc`。匹配时会委托给 `Pbkdf2PasswordEncoder`
<4> 第四个密码是 id 为 `scrypt` 的 `PasswordEncoder`，encodedPassword 为 `$e0801$8bWJaSu2IKSn9Z9kM+TPXfOc/9bdYSrN1oD9qfVThWEwdRTnO7re7Ei+fUZRJ68k9lTyuTeUp4of4g24hHnazw==$OAOec05+bXxvuu/1qZ6NUR+xQYvYv7BeL1QxwRpY5Pc=` ,匹配时它将委托给 `SCryptPasswordEncoder`
<5> 最后一个密码是 id 为 `sha256`  的 `PasswordEncoder` ，encodedPassword 为 `97cde38028ad898ebc02e690819fa220e88c62e0699403e94fff291cfffaf8410849f27605abcbc0`。匹配时会委托给 `StandardPasswordEncoder`


[NOTE]
====
一些用户可能担心为潜在的黑客提供存储格式。这不是问题，因为密码的存储不依赖于算法是 secret。此外，大多数格式很容易让攻击者在没有前缀的情况下弄清楚。例如，BCrypt 密码通常以 `$2a$` 开头。
====

[[authentication-password-storage-dpe-encoding]]
=== 密码编码

传入构造函数的 `idForEncode` 确定将使用哪个 `PasswordEncoder` 来编码密码。在上面构造的 `DelegatingPasswordEncoder` 中，这意味着编码 password 的结果将被委托给 `BCryptPasswordEncoder` 并以 `{bcrypt}` 为前缀。最终结果如下：


.DelegatingPasswordEncoder Encode Example
====
[source,text,attrs="-attributes"]
----
{bcrypt}$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
----
====

[[authentication-password-storage-dpe-matching]]
=== 密码匹配

匹配是基于 `{id}` 以及构造函数中提供的 `id` 到 `PasswordEncoder` 的映射完成的。我们在<<authentication-password-storage-dpe-format,密码存储格式>> 一节中的 example 提供了一个如何完成的工作示例。默认情况下，使用密码调用 `matches(CharSequence, String)` 和未映射的id(包括空 `id`)的结果将导致 `IllegalArgumentException`。
可以使用 `DelegatingPasswordEncoder.setDefaultPasswordEncoderForMatches(PasswordEncoder)` 自定义此行为。

通过使用 `id`，我们可以匹配任何密码编码，但使用最现代的密码编码。这很重要，
因为与加密不同，密码哈希的设计使得没有简单的方法来恢复明文。由于无法恢复明文，因此难以迁移密码。虽然用户很容易迁移 `NoOpPasswordEncoder`，但我们默认选择将其包含在内，但不是默认的 `PasswordEncoder`. 以便简化入门体验。

[[authentication-password-storage-dep-getting-started]]
=== 入门体验

如果您要编写演示或示例，则花一些时间来对用户密码进行哈希运算会很麻烦。 有一些便利机制可以简化此过程，但这仍然不适合生产。

.withDefaultPasswordEncoder Example
====
[source,java,attrs="-attributes"]
----
User user = User.withDefaultPasswordEncoder()
  .username("user")
  .password("password")
  .roles("user")
  .build();
System.out.println(user.getPassword());
// {bcrypt}$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
----
====

如果要创建多个用户，则还可以重复使用该构建器。

.withDefaultPasswordEncoder Reusing the Builder
====
[source,java]
----
UserBuilder users = User.withDefaultPasswordEncoder();
User user = users
  .username("user")
  .password("password")
  .roles("USER")
  .build();
User admin = users
  .username("admin")
  .password("password")
  .roles("USER","ADMIN")
  .build();
----
====

这会散列存储的密码，但是密码仍在内存和已编译的源代码中公开。 因此，对于生产环境它仍然不被认为是安全的。 对于生产，您应该<<authentication-password-storage-boot-cli,在外部对密码进行哈希处理>>。

[[authentication-password-storage-boot-cli]]
=== 使用 Spring Boot CLI 编码

正确编码密码的最简单方法是使用 https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-cli.html[Spring Boot CLI]。

例如，以下将对与 <<authentication-password-storage-dpe,DelegatingPasswordEncoder>> 一起使用的 `password` 密码进行编码：

.Spring Boot CLI encodepassword Example
====
[source,attrs="-attributes"]
----
spring encodepassword password
{bcrypt}$2a$10$X5wFBtLrL/kHcmrOGGTrGufsBX8CJ0WpQpF3pgeuxBB/H73BK1DW6
----
====

[[authentication-password-storage-dpe-troubleshoot]]
=== 故障排除

如果 <<authentication-password-storage-dpe-format,密码存储格式>> 一节中描述的其中一个密码没有 id，则会发生以下错误。.

----
java.lang.IllegalArgumentException: There is no PasswordEncoder mapped for the id "null"
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder$UnmappedIdPasswordEncoder.matches(DelegatingPasswordEncoder.java:233)
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder.matches(DelegatingPasswordEncoder.java:196)
----

解决错误的最简单方法是切换到显式提供密码编码的 `PasswordEncoder`。解决问题的最简单方法是弄清楚当前如何存储密码并明确提供正确的 `PasswordEncoder`。

如果要从 Spring Security 4.2.x 进行迁移，则可以通过 <<authentication-password-storage-configuration,公开 `NoOpPasswordEncoder` bean>> 恢复到先前的行为。

或者，您可以为所有密码加上正确的ID前缀，然后继续使用 `DelegatingPasswordEncoder`。 例如，如果您使用的是 `BCrypt`，则可以从以下方式迁移密码：


----
$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
----

to


[source,attrs="-attributes"]
----
{bcrypt}$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG
----

有关映射的完整列表，请参阅 https://docs.spring.io/spring-security/site/docs/5.0.x/api/org/springframework/security/crypto/factory/PasswordEncoderFactories.html[PasswordEncoderFactories] 上的Javadoc。

[[authentication-password-storage-bcrypt]]
== BCryptPasswordEncoder

`BCryptPasswordEncoder` 实现使用广泛支持的 https://en.wikipedia.org/wiki/Bcrypt[bcrypt] 算法对密码进行哈希处理。 为了使其更能抵抗密码破解，`bcrypt` 故意降低了速度。 与其他自适应单向功能一样，应将其调整为大约1秒钟，以验证系统上的密码。

[source,java]
----
// Create an encoder with strength 16
BCryptPasswordEncoder encoder = new BCryptPasswordEncoder(16);
String result = encoder.encode("myPassword");
assertTrue(encoder.matches("myPassword", result));
----

[[authentication-password-storage-argon2]]
== Argon2PasswordEncoder

`Argon2PasswordEncoder` 实现使用 Argon2 算法对密码进行哈希处理。 https://en.wikipedia.org/wiki/Argon2[Argon2] 是 https://en.wikipedia.org/wiki/Password_Hashing_Competition[Password Hashing Competition] 的获胜者。 为了克服自定义硬件上的密码破解问题，`Argon2` 是一种故意慢速的算法，需要大量内存。
与其他自适应单向功能一样，应将其调整为大约1秒钟，以验证系统上的密码。 如果 `Argon2PasswordEncoder` 需要 BouncyCastle，则为当前实现。

[source,java]
----
// Create an encoder with all the defaults
Argon2PasswordEncoder encoder = new Argon2PasswordEncoder();
String result = encoder.encode("myPassword");
assertTrue(encoder.matches("myPassword", result));
----

[[authentication-password-storage-pbkdf2]]
== Pbkdf2PasswordEncoder

`Pbkdf2PasswordEncoder` 实现使用 https://en.wikipedia.org/wiki/PBKDF2[PBKDF2] 算法对密码进行哈希处理。 为了消除密码破解，PBKDF2是一种故意缓慢的算法。 与其他自适应单向功能一样，应将其调整为大约1秒钟，以验证系统上的密码。 当需要FIPS认证时，此算法是不错的选择。

[source,java]
----
// Create an encoder with all the defaults
Pbkdf2PasswordEncoder encoder = new Pbkdf2PasswordEncoder();
String result = encoder.encode("myPassword");
assertTrue(encoder.matches("myPassword", result));
----

[[authentication-password-storage-scrypt]]
== SCryptPasswordEncoder

`SCryptPasswordEncoder` 实现使用 https://en.wikipedia.org/wiki/Scrypt[scrypt] 算法对密码进行哈希处理。 为了克服自定义硬件scrypt上的密码破解问题，它是一种故意缓慢的算法，需要大量内存。 与其他自适应单向功能一样，应将其调整为大约1秒钟，以验证系统上的密码。

[source,java]
----
// Create an encoder with all the defaults
SCryptPasswordEncoder encoder = new SCryptPasswordEncoder();
String result = encoder.encode("myPassword");
assertTrue(encoder.matches("myPassword", result));
----

[[authentication-password-storage-other]]
== 其他的 PasswordEncoders

还有许多其他的 `PasswordEncoder` 的实现，他们完全是为了保持向后兼容而存在的。 目前均已弃用，以表明它们不再被视为安全。 但是，由于很难迁移现有的旧系统，因此没有删除它们的计划。


[[authentication-password-storage-configuration]]
== 密码存储配置

Spring Security默认使用 <<authentication-password-storage-dpe,DelegatingPasswordEncoder>>。 但是，可以通过将 `PasswordEncoder` 公开为Spring Bean来对其进行自定义。

如果您是从Spring Security 4.2.x迁移的，则可以通过公开 `NoOpPasswordEncoder` bean恢复到以前的行为。

[WARNING]
====
恢复为 `NoOpPasswordEncoder` 不被认为是安全的。 相反，您应该迁移到使用 `DelegatingPasswordEncoder` 来支持安全密码编码。
====

.NoOpPasswordEncoder
====
.Java
[source,java,role="primary"]
----
@Bean
public static NoOpPasswordEncoder passwordEncoder() {
    return NoOpPasswordEncoder.getInstance();
}
----

.XML
[source,xml,role="secondary"]
----
<b:bean id="passwordEncoder"
        class="org.springframework.security.crypto.password.NoOpPasswordEncoder" factory-method="getInstance"/>
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun passwordEncoder(): PasswordEncoder {
    return NoOpPasswordEncoder.getInstance();
}
----
====

[NOTE]
====
XML配置要求 `NoOpPasswordEncoder` Bean名称为 `passwordEncoder`。
====
