[[appendix.executable-jar.launching]]
== 运行可执行 Jars
`org.springframework.boot.loader.Launcher` 类是特殊的引导程序类,用作可执行 jar 的主要入口点.  它是 jar 文件中的实际 `Main-Class`,用于设置适当的 `URLClassLoader` 并最终调用 `main()` 方法.

有三个启动器子类 (`JarLauncher`,`WarLauncher` 和 `PropertiesLauncher`) .  它们的目的是从目录中的嵌套 jar 文件或 war 文件 (而不是在类路径中显式的文件) 加载资源 (`.class` 文件等) .  对于 `JarLauncher` 和 `WarLauncher`,嵌套路径是固定的.  `JarLauncher` 位于 `BOOT-INF/lib/` 中,
而 `WarLauncher` 位于 `WEB-INF/lib/` 和 `WEB-INF/lib-provided/` 中.  如果需要,可以在这些位置添加额外的 jar.  默认情况下,`PropertiesLauncher` 在您的应用程序存档中的 `BOOT-INF/lib/` 中查找.
您可以通过在 `loader.properties` (这是目录,归档文件或归档文件中的目录的逗号分隔列表) 中设置一个称为 `LOADER_PATH` 或 `loader.path` 的环境变量来添加其他位置.

[[appendix.executable-jar.launching.manifest]]
=== 运行 Manifest
您需要指定一个适当的  `Launcher` 作为 `META-INF/MANIFEST.MF` 的 `Main-Class` 属性.  您要启动的实际类 (即包含 `main` 方法的类) 应在 `Start-Class` 属性中指定.

下面的示例显示了一个可执行jar文件的典型 `MANIFEST.MF`:

[indent=0]
----
	Main-Class: org.springframework.boot.loader.JarLauncher
	Start-Class: com.mycompany.project.MyApplication
----

如果是 war 文件,则如下

[indent=0]
----
	Main-Class: org.springframework.boot.loader.WarLauncher
	Start-Class: com.mycompany.project.MyApplication
----

NOTE: 您无需在清单文件中指定 `Class-Path` 条目.  类路径是从嵌套的 jar 中推导出来的.
