[[appendix.executable-jar.property-launcher]]
== PropertiesLauncher 特性
`PropertiesLauncher` 具有一些可以通过外部属性 (系统属性,环境变量,manifest entries 或   `loader.properties`) 启用的特殊功能.  下表描述了这些属性:

|===
| Key | Purpose

| `loader.path`
| 逗号分隔的类路径,例如  `lib,$\{HOME}/app/lib`.  较早的条目具有优先权,就像 `javac` 命令行上的常规 `-classpath` 一样. .

| `loader.home`
| 用于解析 `loader.path` 中的相对路径.  例如,给定 `loader.path=lib`,,则 `${loader.home}/lib` 是类路径位置 (以及该目录中的所有 jar 文件) .
此属性还用于查找 `loader.properties` 文件,如以下示例  `file:///opt/app`  所示. 它默认为 `${user.dir}`.

| `loader.args`
| main 方法的默认参数 (以空格分隔) .

| `loader.main`
| 要启动的主类的名称 (例如 `com.app.Application`) .

| `loader.config.name`
| 属性文件的名称 (例如,`launcher`) .  默认为 `loader`

| `loader.config.location`
| 属性文件的路径 (例如,`classpath:loader.properties`) .  默认为 `loader.properties`. )

| `loader.system`
| 布尔值标志,指示应将所有属性添加到系统属性.  默认为 `false`.
|===

当指定为环境变量或 manifest 时,应使用以下名称:

|===
| Key | Manifest entry | Environment variable

| `loader.path`
| `Loader-Path`
| `LOADER_PATH`

| `loader.home`
| `Loader-Home`
| `LOADER_HOME`

| `loader.args`
| `Loader-Args`
| `LOADER_ARGS`

| `loader.main`
| `Start-Class`
| `LOADER_MAIN`

| `loader.config.location`
| `Loader-Config-Location`
| `LOADER_CONFIG_LOCATION`

| `loader.system`
| `Loader-System`
| `LOADER_SYSTEM`
|===

TIP: 构建 fat jar 时,构建插件会自动将 `Main-Class` 属性移动到 `Start-Class`.  如果使用该名称,请使用 `Main-Class` 属性指定要启动的类的名称,而忽略 `Start-Class`.

以下规则适用于使用 `PropertiesLauncher`:

* 在 `loader.home` 中搜索 `loader.properties`,然后在类路径的根目录中搜索,然后在类路径: `/BOOT-INF/classes` 中搜索.  使用具有该名称的文件的第一个位置.
* 仅当未指定 `loader.config.location` 时,`loader.home` 是其他属性文件的目录位置 (覆盖默认值) .
* `loader.path` 可以包含目录 (对 jar 和 zip 文件进行递归扫描) ,存档路径,存档文件中的对 jar 文件进行扫描的目录 (例如,`dependencies.jar!/lib`) 或通配符模式 (对于 默认 JVM 行为) .  归档路径可以相对于 `loader.home` 或文件系统中任何带有 `jar:file:` 前缀的位置.
* `loader.path` (如果为空) 默认为 `BOOT-INF/lib` (表示本地目录,如果从归档文件运行,则为嵌套目录) .  因此,如果未提供其他配置,则 `PropertiesLauncher` 的行为与 `JarLauncher` 相同.
* `loader.path` 不能用于配置 `loader.properties` 的位置 (用于启动后者的类路径是启动 `PropertiesLauncher` 时的JVM类路径) .
* 占位符的替换是使用系统变量和环境变量以及属性文件本身的所有值完成的,然后再使用.
* 属性 (在多个位置中有意义的查找) 的搜索顺序是环境变量,系统属性,`loader.properties`,暴露的存档清单和存档清单.
