[[mapping-types]]
=== 映射类型
:sourcedir: ../../../../../test/java/org/hibernate/userguide/mapping
:extrasdir: extras/types

Hibernate 了解应用程序数据的 Java 和 JDBC 表示方式。从数据库中读取/写入数据的能力是 Hibernate type 的功能。在这种用法中，type 是 `org.hibernate.type.Type` 接口的实现。这个 Hibernate type 还描述了 Java 类型的各种行为方面，比如如何检查是否相等、如何克隆值等等。

._type_ 的用法
[NOTE]
====
Hibernate type 既不是 Java 类型，也不是 SQL 数据类型。它提供了关于将 Java 类型映射到 SQL 类型以及如何将给定 Java 类型持久化和从关系数据库获取的信息。

当您在 Hibernate 的讨论中遇到术语 type 时，它可能指 Java 类型、JDBC 类型或 Hibernate 类型，具体取决于上下文。
====

为了帮助理解类型分类，让我们看一下一个简单的表和领域模型之间的映射。

[[mapping-types-basic-example]]
.简单的表和领域模型
====
[source, SQL, indent=0]
----
include::{extrasdir}/mapping-types-basic-example.sql[]
----

[source, JAVA, indent=0]
----
include::{sourcedir}/basic/TypeCategoryTest.java[tags=mapping-types-basic-example]
----
====

从广义上讲，Hibernate 将类型分为两类:

* <<categorization-value>>
* <<categorization-entity>>

[[categorization-value]]
==== 值类型

值类型是一段没有定义自己生命周期的数据。 实际上，它由定义其生命周期的实体拥有。

从另一个角度看，一个实体的所有状态完全由值类型组成。这些状态字段或 JavaBean 属性被称为 __persistent attributes（持久属性）__。`Contact` 类的持久属性是值类型。

值类型进一步分为三个子类:

Basic types(基本类型):: 在映射 `Contact` 表时，除了 `name` 之外的所有属性都是基本类型。基本类型在 <<chapters/domain/basic_types.adoc#basic,_Basic types_>> 中进行了详细的讨论
Embeddable types(可嵌入类型):: `name` 属性是可嵌入类型的一个示例，将在 <<chapters/domain/embeddables.adoc#embeddables,_Embeddable types_>> 中详细讨论
*Collection* types(集合类型):: 尽管在上述示例中没有提到集合类型，但集合类型也是值类型中的一个独特类别。集合类型将在 <<chapters/domain/collections.adoc#collections,_Collections_>> 中进一步讨论

[[categorization-entity]]
==== Entity types(实体类型)

实体本质上具有惟一标识符，并独立于其他对象而存在，而值则不然。实体是使用唯一标识符与数据库表中的行相关联的领域模型类。由于对唯一标识符的需求，实体独立存在并定义它们自己的生命周期。`Contact` 类本身就是实体的一个例子。

映射实体将在 <<chapters/domain/entity.adoc#entity,_Entity types_>> 中详细讨论。
