= 附录

[[xsd-schemas]]
== XML Schemas

附录的这一部分列出了用于数据访问的XML schema，包括以下内容:

* <<xsd-schemas-tx,tx schemas>>
* <<xsd-schemas-jdbc,jdbc schemas>>



[[xsd-schemas-tx]]
=== `tx` Schema

`tx` 标签处理Spring对事务的全面支持中所有这些bean的配置. 这些标签在标题为<<data-access.adoc#transaction, 事务管理>>的章节中介绍.
.

TIP: 我们强烈建议您查看Spring发行版附带的 `spring-tx.xsd` 文件.  此文件包含Spring的事务配置的XML schema，并涵盖 `tx` 命名空间中的所有各种元素，包括属性默认值和类似信息.  该文件以内联方式记录，因此，为了遵守DRY(不要重复自己) 原则，此处不再重复这些信息.

为了完整性，要使用 `tx` schema 中的元素，您需要在Spring XML配置文件的顶部包含以下代码.  以下代码段中的文本引用了正确的 schema，以便您可以使用 `tx` 命名空间中的标记:

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:aop="http://www.springframework.org/schema/aop"
		xmlns:tx="http://www.springframework.org/schema/tx" <1>
		xsi:schemaLocation="
			http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/tx https://www.springframework.org/schema/tx/spring-tx.xsd <2>
			http://www.springframework.org/schema/aop https://www.springframework.org/schema/aop/spring-aop.xsd">

		<!-- bean definitions here -->

	</beans>
----
<1> 声明 `tx` 命名空间的使用.
<2> 指定位置(使用其他schema位置) .


NOTE: 通常，当您使用 `tx` 命名空间中的元素时，您还使用了 `aop` 命名空间中的元素(因为Spring中的声明式事务支持是通过使用AOP实现的) .  前面的XML片段包含引用 `aop` schema 所需的相关行，以便您可以使用 `aop` 命名空间中的元素.



[[xsd-schemas-jdbc]]
=== `jdbc` Schema

jdbc元素使您可以快速配置嵌入式数据库 或初始化现有数据源. 这些元素分别记录在<<data-access.adoc#jdbc-embedded-database-support, 嵌入式数据库支持>> 和<<data-access.adoc#jdbc-initializing-datasource, 初始化数据源>>中.

要使用jdbc Schema中的元素，需要在Spring XML配置文件的顶部包含以下代码.  以下代码段中的文本引用了正确的Schema，以便您可以使用jdbc命名空间中的元素:

[source,xml,indent=0]
[subs="verbatim,quotes"]
----
	<?xml version="1.0" encoding="UTF-8"?>
	<beans xmlns="http://www.springframework.org/schema/beans"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:jdbc="http://www.springframework.org/schema/jdbc" <1>
		xsi:schemaLocation="
			http://www.springframework.org/schema/beans https://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/jdbc https://www.springframework.org/schema/jdbc/spring-jdbc.xsd"> <2>

		<!-- bean definitions here -->

	</beans>
----
<1> 声明 `jdbc` 的命名空间.
<2> 指定位置(使用其他Schema位置) .

