= WebClient

[NOTE]
====
以下文档适用于Reactive环境. 对于Servlet环境,请参阅 <<oauth2Client-webclient-servlet, Servlet环境的WebClient>> .
====


Spring Framework内置了对设置Bearer令牌的支持.

[source,java]
----
webClient.get()
    .headers(h -> h.setBearerAuth(token))
    ...
----

Spring Security在此支持的基础上提供了更多好处:

* Spring Security将自动刷新过期的令牌(如果存在刷新令牌)
* 如果请求访问令牌但不存在,则Spring Security将自动请求访问令牌.
** 对于 `authorization_code`,这涉及执行重定向,然后重播原始请求
** 对于 `client_credentials`,只需请求并保存令牌
* 支持透明地包含当前OAuth令牌或显式选择应使用的令牌的功能.

[[webclient-setup]]
== WebClient OAuth2 Setup

第一步是确保正确设置 `WebClient`. 下面是在完全反应性的环境中设置 `WebClient` 的示例:

[source,java]
----
@Bean
WebClient webClient(ReactiveClientRegistrationRepository clientRegistrations,
		ServerOAuth2AuthorizedClientRepository authorizedClients) {
	ServerOAuth2AuthorizedClientExchangeFilterFunction oauth =
			new ServerOAuth2AuthorizedClientExchangeFilterFunction(clientRegistrations, authorizedClients);
	// (optional) explicitly opt into using the oauth2Login to provide an access token implicitly
	// oauth.setDefaultOAuth2AuthorizedClient(true);
	// (optional) set a default ClientRegistration.registrationId
	// oauth.setDefaultClientRegistrationId("client-registration-id");
	return WebClient.builder()
			.filter(oauth)
			.build();
}
----

[[webclient-implicit]]
== 隐式 OAuth2AuthorizedClient

如果我们在设置中将 `defaultOAuth2AuthorizedClient` 设置为 `true`,并且使用 oauth2Login(即OIDC) 对用户进行身份验证,则当前身份验证将用于自动提供访问令牌.  或者,如果我们将 `defaultClientRegistrationId` 设置为有效的 `ClientRegistration` ID,则使用该注册来提供访问令牌.  这很方便,但是在并非所有端点都应获取访问令牌的环境中,这很危险(您可能为端点提供了错误的访问令牌) .

[source,java]
----
Mono<String> body = this.webClient
		.get()
		.uri(this.uri)
		.retrieve()
		.bodyToMono(String.class);
----

[[webclient-explicit]]
== 显式 OAuth2AuthorizedClient

通过在请求属性上设置 `OAuth2AuthorizedClient`,可以显式提供它.  在下面的示例中,我们使用Spring WebFlux或Spring MVC参数解析器支持来解析 `OAuth2AuthorizedClient`.  但是,如何解析 `OAuth2AuthorizedClient` 并不重要.

[source,java]
----
@GetMapping("/explicit")
Mono<String> explicit(@RegisteredOAuth2AuthorizedClient("client-id") OAuth2AuthorizedClient authorizedClient) {
	return this.webClient
			.get()
			.uri(this.uri)
			.attributes(oauth2AuthorizedClient(authorizedClient))
			.retrieve()
			.bodyToMono(String.class);
}
----

[[webclient-clientregistrationid]]
== clientRegistrationId

或者,可以在请求属性上指定 `clientRegistrationId`,然后 `WebClient` 会尝试查找 `OAuth2AuthorizedClient`.  如果找不到,将自动获取一个.

[source,java]
----
Mono<String> body = this.webClient
		.get()
		.uri(this.uri)
		.attributes(clientRegistrationId("client-id"))
		.retrieve()
		.bodyToMono(String.class);
----
