[[anonymous]]
= 匿名认证


[[anonymous-overview]]
== 概述
通常,采用 "默认拒绝" 的做法被认为是一种良好的安全做法,您可以在其中明确指定允许的内容,并禁止其他所有内容. 定义未经身份验证的用户可以访问的内容的情况与此类似,尤其是对于 Web 应用程序.  许多站点要求用户必须通过身份验证才能使用少数几个 URL(例如,主页和登录页面) .  在这种情况下,最简单的是为这些特定的 URL 定义访问配置属性,而不是为每个受保护的资源定义访问配置属性.
换句话说,有时很高兴地说默认情况下需要 `ROLE_SOMETHING`,并且只允许该规则的某些例外,例如应用程序的登录,注销和主页. 您也可以从过滤器链中完全忽略这些页面,从而绕过访问控制检查,但是由于其他原因,这可能是不可取的,特别是如果这些页面对于经过身份验证的用户而言行为不同.

这就是我们所说的匿名身份验证.  请注意,"匿名身份验证" 的用户和未经身份验证的用户之间没有真正的概念差异.  Spring Security 的匿名身份验证只是为您提供了一种更便捷的方式来配置访问控制属性.
即使在 `SecurityContextHolder` 中实际上存在一个匿名身份验证对象,对诸如 `getCallerPrincipal` 之类的 Servlet API 调用的调用仍将返回 `null`.

在其他情况下,匿名身份验证很有用,例如当审核拦截器查询 `SecurityContextHolder` 以确定哪个主体负责给定操作时.  如果类知道 `SecurityContextHolder` 始终包含 `Authentication` 对象并且从不为 `null`,则可以更强大地编写类.

[[anonymous-config]]
== 配置
使用 HTTP 配置（在 Spring Security 3.0 中引入） 时，会自动提供匿名身份验证支持,并且可以使用 `<anonymous>` 元素自定义(或禁用) 匿名身份验证支持.
除非您使用的是传统的 Bean 配置,否则无需配置此处描述的 Bean.

三个类共同提供了匿名身份验证功能.
`AnonymousAuthenticationToken` 是 `Authentication` 的实现,并存储适用于匿名主体的 `GrantedAuthority`.  有一个对应的 `AnonymousAuthenticationProvider`,它已链接到 `ProviderManager` 中,因此可以接受 `AnonymousAuthenticationToken`.
最后,有一个 `AnonymousAuthenticationFilter`,它在常规身份验证机制之后链接,如果那里没有现有的身份验证,则会自动将 `AnonymousAuthenticationToken` 添加到 `SecurityContextHolder`.  过滤器和身份验证提供程序的定义如下所示:

====
[source,xml]
----
<bean id="anonymousAuthFilter"
	class="org.springframework.security.web.authentication.AnonymousAuthenticationFilter">
<property name="key" value="foobar"/>
<property name="userAttribute" value="anonymousUser,ROLE_ANONYMOUS"/>
</bean>

<bean id="anonymousAuthenticationProvider"
	class="org.springframework.security.authentication.AnonymousAuthenticationProvider">
<property name="key" value="foobar"/>
</bean>
----
====

密钥在过滤器和身份验证提供程序之间共享,因此前者创建的令牌将被后者接受.

[NOTE]
====
这里没有为 key 属性提供任何真正的安全性。 这里只是一个简单的练习。 如果在可能进行身份验证的客户端构造 "Authentication" 对象（例如使用 RMI 调用）的情况下共享包含 `AnonymousAuthenticationProvider` 的 `ProviderManager`，
则恶意客户端可以提交它自己创建的 `AnonymousAuthenticationToken`（使用所选的 用户名和权限列表）。 如果 `key`  是可猜测的或可以被发现的，则令牌将被匿名提供者接受。 这不是正常使用的问题。
但是，如果您使用 RMI，则应使用省略匿名提供程序的自定义 `ProviderManager`，而不是共享用于 HTTP 身份验证机制的提供程序。
====

`userAttribute` 以 `usernameInTheAuthenticationToken`, `usernameInTheAuthenticationToken,grantedAuthority[,grantedAuthority]` 的形式表示.  这与 `InMemoryDaoImpl` 的 `userMap` 属性的等号后使用的语法相同. footnote:[

如前所述,匿名身份验证的好处是所有URI模式都可以应用安全性.
例如:

====
[source,xml]
----
<bean id="filterSecurityInterceptor"
	class="org.springframework.security.web.access.intercept.FilterSecurityInterceptor">
<property name="authenticationManager" ref="authenticationManager"/>
<property name="accessDecisionManager" ref="httpRequestAccessDecisionManager"/>
<property name="securityMetadata">
	<security:filter-security-metadata-source>
	<security:intercept-url pattern='/index.jsp' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/hello.htm' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/logoff.jsp' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/login.jsp' access='ROLE_ANONYMOUS,ROLE_USER'/>
	<security:intercept-url pattern='/**' access='ROLE_USER'/>
	</security:filter-security-metadata-source>" +
</property>
</bean>
----
====

[[anonymous-auth-trust-resolver]]
== AuthenticationTrustResolver
完善匿名身份验证讨论的是 `AuthenticationTrustResolver` 接口及其相应的 `AuthenticationTrustResolverImpl` 实现.  该接口提供了 `isAnonymous(Authentication)` 方法,该方法允许感兴趣的类将这种特殊类型的身份验证状态考虑在内.  `ExceptionTranslationFilter` 在处理 `AccessDeniedException` 时使用此接口.  如果抛出 `AccessDeniedException` 且身份验证为匿名类型,则过滤器将代替启动 `AuthenticationEntryPoint`,而不引发 403 (禁止) 响应,以便主体可以正确地进行身份验证.
这是必要的区别,否则主体将始终被视为 "已认证",并且永远不会获得通过表单,基本,摘要或某些其他常规认证机制登录的机会.

您经常会在上述拦截器配置中看到 `ROLE_ANONYMOUS` 属性被 `IS_AUTHENTICATED_ANONYMOUSLY` 替换,这在定义访问控制时实际上是相同的.  这是使用 `AuthenticatedVoter` 的示例,我们将在<<authz-authenticated-voter,授权章节>>中看到.  它使用 `AuthenticationTrustResolver` 来处理此特定配置属性,并将访问权限授予匿名用户.
`AuthenticatedVoter` 方法更强大,因为它使您可以区分匿名用户,记住我的用户和经过完全认证的用户.  如果您不需要此功能,则可以坚持使用 `ROLE_ANONYMOUS`,它将由 Spring Security 的标准 `RoleVoter` 处理.

[[anonymous-auth-mvc-controller]]
== 使用 Spring MVC 获取匿名身份验证

https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-arguments[Spring MVC 使用自己的参数解析器解析 `Principal`类型的参数]。

这意味着像这样的构造:

====
.Java
[source,java,role="primary"]
----
@GetMapping("/")
public String method(Authentication authentication) {
	if (authentication instanceof AnonymousAuthenticationToken) {
		return "anonymous";
	} else {
		return "not anonymous";
	}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun method(authentication: Authentication?): String {
    return if (authentication is AnonymousAuthenticationToken) {
        "anonymous"
    } else {
        "not anonymous"
    }
}
----
====

将始终返回  "not anonymous"，即使对于匿名请求也是如此。 原因是 Spring MVC 使用 `HttpServletRequest#getPrincipal` 解析参数，当请求为匿名时为 `null`。

如果您想在匿名请求中获取 `Authentication`，请改用 `@CurrentSecurityContext`:

.Use CurrentSecurityContext for Anonymous requests
====
.Java
[source,java,role="primary"]
----
@GetMapping("/")
public String method(@CurrentSecurityContext SecurityContext context) {
	return context.getAuthentication().getName();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun method(@CurrentSecurityContext context : SecurityContext) : String =
		context!!.authentication!!.name
----
====
