[[jc-logout]]
= Logout 处理

本节介绍如何自定义注销处理。

[[logout-java-configuration]]
== Logout Java/Kotlin 配置

使用 `{security-api-url}org/springframework/security/config/annotation/web/builders/HttpSecurity.html[WebSecurityConfigurerAdapter]` 时,将自动应用注销功能.  默认是访问 URL `/logout` 将通过以下方式注销用户:

- 使HTTP会话无效
- 清理配置的所有RememberMe身份验证
- 清除 `SecurityContextHolder`
- 重定向 `/login?logout`

但是,与配置登录功能相似,您还可以使用各种选项来进一步自定义注销要求:

.Logout Configuration
====
.Java
[source,java,role="primary"]
----
public SecurityFilterChain filterChain(HttpSecurity http) {
    http
        .logout(logout -> logout                                                // <1>
            .logoutUrl("/my/logout")                                            // <2>
            .logoutSuccessUrl("/my/index")                                      // <3>
            .logoutSuccessHandler(logoutSuccessHandler)                         // <4>
            .invalidateHttpSession(true)                                        // <5>
            .addLogoutHandler(logoutHandler)                                    // <6>
            .deleteCookies(cookieNamesToClear)                                  // <7>
        )
        ...
}
----

.Kotlin
[source,kotlin,role="secondary"]
-----
open fun filterChain(http: HttpSecurity): SecurityFilterChain {
    http {
        logout {                                                  // <1>
            logoutUrl = "/my/logout"                              // <2>
            logoutSuccessUrl = "/my/index"                        // <3>
            logoutSuccessHandler = customLogoutSuccessHandler     // <4>
            invalidateHttpSession = true                          // <5>
            addLogoutHandler(logoutHandler)                       // <6>
            deleteCookies(cookieNamesToClear)                     // <7>
        }
    }
    // ...
}
-----
<1> 提供注销支持.  当使用 `WebSecurityConfigurerAdapter` 时会自动应用.
<2> 触发注销发生的URL(默认为 `/logout`) . 如果启用了 CSRF 保护(默认) ,则请求必须是 POST.  有关更多信息,请查阅 {security-api-url}org/springframework/security/config/annotation/web/configurers/LogoutConfigurer.html#logoutUrl-java.lang.String-[Javadoc] .
<3> 注销发生后重定向到的 URL. 默认 `/login?logout`. 有关更多信息,请查阅 {security-api-url}org/springframework/security/config/annotation/web/configurers/LogoutConfigurer.html#logoutSuccessUrl-java.lang.String-[Javadoc].
<4> 让我们指定一个自定义的 `LogoutSuccessHandler`. 如果指定了此项,`logoutSuccessUrl()` 将被忽略.  有关更多信息,请查阅 {security-api-url}org/springframework/security/config/annotation/web/configurers/LogoutConfigurer.html#logoutSuccessHandler-org.springframework.security.web.authentication.logout.LogoutSuccessHandler-[Javadoc].
<5> 指定在注销时是否使 `HttpSession` 无效. 默认为 `true`. 在幕后配置 `SecurityContextLogoutHandler`.  有关更多信息,请查阅 {security-api-url}org/springframework/security/config/annotation/web/configurers/LogoutConfigurer.html#invalidateHttpSession-boolean-[Javadoc].
<6> 添加 `LogoutHandler`. 默认情况下,`SecurityContextLogoutHandler` 被添加为最后一个 `LogoutHandler`.
<7> 允许指定成功注销后将删除的 cookie 名称. 这是显式添加 `CookieClearingLogoutHandler` 的快捷方式.
====

[NOTE]
====
当然,也可以使用 XML 命名空间配置注销.  请参阅 Spring Security XML 命名空间部分中 <<nsa-logout, logout element>> 的文档以获取更多详细信息.
====

通常,为了自定义注销功能,可以添加 `{security-api-url}org/springframework/security/web/authentication/logout/LogoutHandler.html[LogoutHandler]` 和/或 `{security-api-url}org/springframework/security/web/authentication/logout/LogoutSuccessHandler.html[LogoutSuccessHandler]` 实现.  对于许多常见方案,使用流式的API时会在后台应用这些处理程序.

[[ns-logout]]
== Logout XML 配置
`logout` 元素通过导航到特定 URL 来添加对注销的支持.  默认注销URL为 `/logout`,但是您可以使用 `logout-url` 属性将其设置为其他名称.  有关其他可用属性的更多信息,请参见命名空间附录.

[[jc-logout-handler]]
== LogoutHandler

通常,`{security-api-url}org/springframework/security/web/authentication/logout/LogoutHandler.html[LogoutHandler]` 实现指示能够参与注销处理的类.  预计将调用它们以执行必要的清理.
因此,它们不应引发异常. 提供了各种实现:

- {security-api-url}org/springframework/security/web/authentication/rememberme/PersistentTokenBasedRememberMeServices.html[PersistentTokenBasedRememberMeServices]
- {security-api-url}org/springframework/security/web/authentication/rememberme/TokenBasedRememberMeServices.html[TokenBasedRememberMeServices]
- {security-api-url}org/springframework/security/web/authentication/logout/CookieClearingLogoutHandler.html[CookieClearingLogoutHandler]
- {security-api-url}org/springframework/security/web/csrf/CsrfLogoutHandler.html[CsrfLogoutHandler]
- {security-api-url}org/springframework/security/web/authentication/logout/SecurityContextLogoutHandler.html[SecurityContextLogoutHandler]
- {security-api-url}org/springframework/security/web/authentication/logout/HeaderWriterLogoutHandler.html[HeaderWriterLogoutHandler]

有关详细信息,请参见<<remember-me-impls,第10.13.4节 "记住我的接口和实现">>.

除了直接提供 `LogoutHandler` 实现之外,fluent API 还提供了快捷方式,这些快捷方式在幕后提供了各自的 `LogoutHandler` 实现.
例如.  `deleteCookies()` 允许指定成功注销后要删除的一个或多个 cookie 的名称.  与添加 `CookieClearingLogoutHandler` 相比,这是一种快捷方式.

[[jc-logout-success-handler]]
== LogoutSuccessHandler

`LogoutFilter` 成功注销后,将调用 `LogoutSuccessHandler` 来处理例如 重定向或转发到适当的目的地.  请注意,该接口与 `LogoutHandler` 几乎相同,但可能会引发异常.

提供以下实现:

- {security-api-url}org/springframework/security/web/authentication/logout/SimpleUrlLogoutSuccessHandler.html[SimpleUrlLogoutSuccessHandler]
- HttpStatusReturningLogoutSuccessHandler

如上所述,您无需直接指定 `SimpleUrlLogoutSuccessHandler`.  相反,fluent API 通过设置 `logoutSuccessUrl()` 提供了快捷方式.  这将在幕后设置 `SimpleUrlLogoutSuccessHandler`.  提供的 URL 将在注销后重定向到.  默认值为 `/login?logout`.

在 REST API 类型的场景中,`HttpStatusReturningLogoutSuccessHandler` 可能很有趣.  通过 `LogoutSuccessHandler`,您不必提供在成功注销后重定向到 URL 的方法,而是可以提供要返回的纯HTTP状态代码.  如果未配置,默认情况下将返回状态码200.

[[jc-logout-references]]
== 其他注销相关参考

- <<ns-logout, Logout 处理>>
- <<test-logout, 测试 Logout>>
- <<servletapi-logout, HttpServletRequest.logout()>>
- <<remember-me-impls,"记住我的接口和实现">>
- 在 CSRF 警告<<servlet-considerations-csrf-logout, Logging Out>>
- Spring Security XML 命名空间 <<nsa-logout, logout element>> 的文档
