[[servlet-x509]]
= X.509 认证


[[x509-overview]]
== 概述
最常用的 X.509 证书身份验证是验证服务器在使用 SSL 的身份,从浏览器通常在使用 HTTPS. 浏览器会自动检查服务器证书的已发布(即数字签名)的一个受信任的证书颁发机构的列表维护.

您还可以将 SSL 与“相互验证”结合使用。 然后，作为 SSL 握手的一部分，服务器向客户端请求有效证书。 服务器通过检查其证书是否由可接受的授权机构签名来验证客户端。
如果提供了有效证书，则可以通过应用程序中的 servlet API 获取。 Spring Security X.509 模块使用过滤器提取证书。
它将证书映射到应用程序用户并加载该用户的一组授权权限以与标准 Spring Security 一起使用。

您还可以将 SSL 与 "`mutual authentication`" 结合使用。 然后，作为 SSL 握手的一部分，服务器向客户端请求有效证书。 服务器通过检查其证书是否由可接受的授权机构签名来验证客户端。
例如，如果您使用 Tomcat，则应该阅读 Tomcat SSL 说明。 在尝试使用 Spring Security 之前，您应该让 Tomcat 工作。

== 向您的 Web 应用程序添加X.509身份验证
启用 X.509 客户端身份验证非常简单.  只需将 `<x509/>` 元素添加到您的 http 安全命名空间配置中即可.

====
[source,xml]
----
<http>
...
	<x509 subject-principal-regex="CN=(.*?)," user-service-ref="userService"/>;
</http>
----
====

元素具有两个可选属性:

* `subject-principal-regex`.
用于从证书主题名称中提取用户名的正则表达式.  默认值如上所示.  这是用户名,该用户名将传递给 `UserDetailsService` 以加载用户的权限.
* `user-service-ref`.
这是与X.509一起使用的 `UserDetailsService` 的 bean ID.  如果您的应用程序上下文中仅定义了一个,则不需要.

`subject-principal-regex` 应该包含一个组.  例如,默认表达式 "CN=(.*?)," 与通用名称字段匹配.  因此,如果证书中的使用者名称为 "CN=Jimi Hendrix, OU=...",则用户名称为 "Jimi Hendrix".
匹配不区分大小写.  因此,"emailAddress=(+.*?+),"  将与 "EMAILADDRESS=jimi@hendrix.org,CN=..." 匹配,并给出用户名 "jimi@hendrix.org".  如果客户端出示证书并且成功提取了有效的用户名,则安全上下文中应该有一个有效的 `Authentication` 对象.  如果找不到证书,或者找不到相应的用户,则安全上下文将保持为空.  这意味着您可以轻松地将 X.509 身份验证与其他选项 (例如基于表单的登录名) 一起使用.

[[x509-ssl-config]]
== 在Tomcat中设置SSL
Spring Security 项目的  {gh-samples-url}/servlet/java-configuration/authentication/x509/server[Spring Security Samples repository] 目录中有一些预先生成的证书.  如果您不想生成自己的SSL,可以使用它们启用SSL进行测试.  文件 `server.jks` 包含服务器证书,私钥和颁发证书颁发机构的证书.  示例应用程序中还为用户提供了一些客户端证书文件.  您可以将它们安装在浏览器中以启用 SSL 客户端身份验证.

要运行具有 SSL 支持的 tomcat,请将 `server.jks` 文件拖放到tomcat `conf` 目录中,并将以下连接器添加到 `server.xml` 文件中

====
[source,xml]
----
<Connector port="8443" protocol="HTTP/1.1" SSLEnabled="true" scheme="https" secure="true"
			clientAuth="true" sslProtocol="TLS"
			keystoreFile="${catalina.home}/conf/server.jks"
			keystoreType="JKS" keystorePass="password"
			truststoreFile="${catalina.home}/conf/server.jks"
			truststoreType="JKS" truststorePass="password"
/>
----
====

如果您仍然希望 SSL 连接成功,即使客户端不提供证书,也可以将 `clientAuth` 设置为 `want`.  除非您使用非 X.509 身份验证机制 (例如表单身份验证) ,否则没有证书的客户端将无法访问 Spring Security 保护的任何对象.
