[[build-tool-plugins]]
= 构建工具插件
include::attributes.adoc[]

Spring Boot 为 Maven 和 Gradle 提供了构建工具插件.  插件提供了多种功能,包括可执行jar的打包.  本节提供了有关这两个插件的更多详细信息,以及在扩展不受支持的构建系统时所需的一些帮助.
如果您刚刚入门,则可能需要先阅读 "`<<using-spring-boot.adoc#using-boot-build-systems,using-spring-boot.html>>`" 部分中的 "`<<using-spring-boot.adoc#using-boot,using-spring-boot.html>>`".

[[build-tool-plugins-maven-plugin]]
== Spring Boot Maven 插件
Spring Boot Maven 插件在 Maven 中提供了 Spring Boot 支持,使您可以打包可执行 jar 或 war 归档文件并 "`in-place`" 运行应用程序.  要使用它,必须使用Maven 3.2 (或更高版本) .

请参阅插件的文档以了解更多信息:

* Reference ({spring-boot-maven-plugin-docs}[HTML] 和 {spring-boot-maven-plugin-pdfdocs}[PDF])
* {spring-boot-maven-plugin-api}[API]

[[build-tool-plugins-gradle-plugin]]
== Spring Boot Gradle 插件
Spring Boot Gradle 插件在 Gradle 中提供了 Spring Boot 支持,可让您打包可执行 jar 或 war 归档文件,运行 Spring Boot 应用程序以及使用所提供的依赖管理 `spring-boot-dependencies`.
它需要 Gradle 6 (6.3 或更高版本):

还支持 Gradle 5.6.x，但不建议使用，在未来的版本中将删除该支持。请参阅插件的文档以了解更多信息

* 参考 ({spring-boot-gradle-plugin-docs}[HTML] 和 {spring-boot-gradle-plugin-pdfdocs}[PDF])
* {spring-boot-gradle-plugin-api}[API]

[[build-tool-plugins-antlib]]
== Spring Boot AntLib 模块

Spring Boot AntLib模块为Apache Ant提供了基本的Spring Boot支持. 您可以使用该模块创建可执行jar. 要使用该模块,您需要在中声明一个额外的 `spring-boot` 命名空间 `build.xml`,如以下示例所示:

[source,xml,indent=0]
----
	<project xmlns:ivy="antlib:org.apache.ivy.ant"
		xmlns:spring-boot="antlib:org.springframework.boot.ant"
		name="myapp" default="build">
		...
	</project>
----

您需要记住使用该 `-lib` 选项启动Ant ,如以下示例所示:

[indent=0,subs="verbatim,quotes,attributes"]
----
	$ ant -lib <directory containing spring-boot-antlib-{spring-boot-version}.jar>
----

TIP: 使用Spring Boot 部分包含将Apache Ant与结合<<using-spring-boot.adoc#using-boot-ant, 使用 `spring-boot-antlib` 的更完整示例>>.

[[spring-boot-ant-tasks]]
=== Spring Boot Ant 任务

一旦 `spring-boot-antlib` 命名空间已申报,以下附加任务:

* <<spring-boot-ant-exejar>>
* <<spring-boot-ant-findmainclass>>

[[spring-boot-ant-exejar]]
==== 使用 "`exejar`" Task
您可以使用该 `exejar` 任务创建一个Spring Boot可执行jar. 任务支持以下属性:

[cols="1,2,2"]
|====
| 属性 | 描述 | 是否需要

| `destfile`
| 要创建的目标jar文件
| Yes

| `classes`
| Java类文件的根目录
| Yes

| `start-class`
| 要运行的主要应用程序类
| No _(否 (默认为找到的第一个声明 `main` 方法的类) )_
|====

以下嵌套元素可用于任务:

[cols="1,4"]
|====
| 元素 | 描述

| `resources`
| 一个或多个 {ant-docs}/Types/resources.html#collection[资源集合],描述应添加到创建的jar文件内容中的一组 {ant-docs}/Types/resources.html[Resources] .

| `lib`
| 应将一个或多个 {ant-docs}/Types/resources.html#collection[资源集合] 添加到组成应用程序运行时依赖类路径的jar库集合中.
|====

[[spring-boot-ant-exejar-examples]]
==== 例子
本节显示了两个Ant任务示例.

.Specify +start-class+
[source,xml,indent=0]
----
	<spring-boot:exejar destfile="target/my-application.jar"
			classes="target/classes" start-class="com.example.MyApplication">
		<resources>
			<fileset dir="src/main/resources" />
		</resources>
		<lib>
			<fileset dir="lib" />
		</lib>
	</spring-boot:exejar>
----

.Detect +start-class+
[source,xml,indent=0]
----
	<exejar destfile="target/my-application.jar" classes="target/classes">
		<lib>
			<fileset dir="lib" />
		</lib>
	</exejar>
----



[[spring-boot-ant-findmainclass]]
=== 使用 "`findmainclass`" Task

该 `findmainclass` 任务在内部 `exejar` 用于查找声明的类 `main`. 如有必要,您也可以在构建中直接使用此任务. 支持以下属性:

[cols="1,2,2"]
|====
| 属性 | 描述 | 是否需要

| `classesroot`
| Java类文件的根目录
| Yes _(除非 `mainclass` 指定)_

| `mainclass`
| 可用于短路 `main` class 搜索
| No

| `property`
| 应该与结果一起设置的Ant属性
| No _(如果未指定,将记录结果)_
|====

[[spring-boot-ant-findmainclass-examples]]
==== 例子
本节包含使用的三个示例 `findmainclass`.

.查找并记录
[source,xml,indent=0]
----
	<findmainclass classesroot="target/classes" />
----

.查找并设置
[source,xml,indent=0]
----
	<findmainclass classesroot="target/classes" property="main-class" />
----

.覆盖并设置
[source,xml,indent=0]
----
	<findmainclass mainclass="com.example.MainClass" property="main-class" />
----

[[build-tool-plugins-other-build-systems]]
== 支持其他构建系统
如果要使用Maven,Gradle或Ant以外的构建工具,则可能需要开发自己的插件. 可执行的jar需要遵循特定的格式,某些条目需要以未压缩的形式编写 (有关详细信息,请参见附录中的 "`<<appendix-executable-jar-format.adoc#executable-jar, 可执行jar格式>>`" 部分) .

Spring Boot Maven和Gradle插件都利用它们 `spring-boot-loader-tools` 来实际生成jar. 如果需要,可以直接使用此库.

[[build-tool-plugins-repackaging-archives]]
=== 重新打包 Archives
要重新打包现有存档,使其成为独立的可执行存档,请使用 `org.springframework.boot.loader.tools.Repackager`. 该 `Repackager` class 采取的是指现有的 jar 或 war archive 单个构造函数的参数.
使用两种可用 `repackage()` 方法之一替换原始文件或写入新目标. 在重新打包程序运行之前,还可以对其进行各种设置.

[[build-tool-plugins-nested-libraries]]
=== 嵌套库
重新打包 存档 时,可以使用该 `org.springframework.boot.loader.tools.Libraries` 接口包括对依赖文件的引用. 我们 `Libraries` 这里不提供任何具体的实现,因为它们通常是特定于构建系统的.

如果归档文件中已经包含库,则可以使用 `Libraries.NONE`.

[[build-tool-plugins-find-a-main-class]]
=== 查找 Main Class

如果您不用于 `Repackager.setMainClass()` 指定主类,则重新包装器将使用 https://asm.ow2.io/[ASM] 读取类文件,并尝试使用一种  `public static void main(String[] args)` 方法找到合适的类. 如果找到多个候选者,则会引发异常.

[[build-tool-plugins-repackage-implementation]]
=== 重新打包示例实现
以下示例显示了典型的重新打包实现:

[source,java,indent=0]
----
	Repackager repackager = new Repackager(sourceJarFile);
	repackager.setBackupSource(false);
	repackager.repackage(new Libraries() {
				@Override
				public void doWithLibraries(LibraryCallback callback) throws IOException {
					// Build system specific implementation, callback for each dependency
					// callback.library(new Library(nestedFile, LibraryScope.COMPILE));
				}
			});
----

[[build-tool-plugins-whats-next]]
== 接下来阅读什么
如果您对构建工具插件的工作方式感兴趣,可以查看 {spring-boot-code}/spring-boot-project/spring-boot-tools[`spring-boot-tools`]  上的模块. 可执行jar格式的更多技术细节在 <<appendix-executable-jar-format#executable-jar,附录中>> 介绍.

如果您有与构建相关的特定问题,可以查看  "`<<howto.adoc#howto, how-to>>`" 指南.