[[boot-documentation]]
= Spring Boot 文档
include::attributes.adoc[]

本节简述了 Spring Boot 参考文档的内容,并且可作为文档的导航地图.

[[boot-documentation-about]]
== 关于文档
Spring Boot 参考指南可通过以下方式获得:

* {spring-boot-docs}/html/[Multi-page HTML]
* {spring-boot-docs}/htmlsingle/[Single page HTML]
* {spring-boot-docs}/pdf/spring-boot-reference.pdf[PDF]

最新的文档位于 {spring-boot-current-docs}.

本文档的副本可以供您自己使用,也可以分发给其他人,但前提是您不对此类副本收取任何费用,并且还应确保每份副本均包含本版权声明(无论是印刷版本还是电子版本) .

[[boot-documentation-getting-help]]
== 获取帮助
如果您在使用 Spring Boot 时遇到了麻烦,可参考以下指南.

* 尝试 阅读<<howto.adoc#howto, How-to 文档>>  —— 最常见问题的解决方案都在这里.  .
* 学习 Spring 基础  ——  Spring Boot 是建立在多个 Spring 项目之上, 请查看  https://spring.io[spring.io]  网站以获取更多参考文档. 如果您是刚刚开始使用 Spring, 请尝试其中一个 https://spring.io/guides[guides].
* 提提问题 —— 我们时刻关注着 https://stackoverflow.com[stackoverflow.com]  上有关 https://stackoverflow.com/tags/spring-boot[`spring-boot`] 标签相关的问题.
* 在 https://github.com/spring-projects/spring-boot/issues 报告 Spring Boot 的 bug.

NOTE: Spring Boot 是全部开源的,包括文档！如果您发现文档中存在错误了,或者您想改进它们,请 {spring-boot-code}[参与我们].

[[boot-documentation-upgrading]]
== 从早期版本升级
项目 {github-wiki}[wiki] 提供了有关如何从早期版本的 Spring Boot 升级的说明。 按照 {github-wiki}#release-notes[release notes] 说明部分中的链接查找要升级到的版本。

升级说明始终是发行版本说明中的第一项。 如果您落后多个发行版本，请确保您还查看了所跳版本的发行版本说明。

您应该始终确保运行的是  {github-wiki}/Supported-Versions[受支持的]   Spring Boot 版本。

[[boot-documentation-first-steps]]
== 第一步
如果您是刚开始使用 Spring Boot,或者想对 Spring 有个大体 印象, 您可以从 <<getting-started.adoc#getting-started, 这里开始学习>>!

* *从零开始:* <<getting-started.adoc#getting-started-introducing-spring-boot, 概述>> | <<getting-started.adoc#getting-started-system-requirements, 要求>> | <<getting-started.adoc#getting-started-installing-spring-boot, 安装>>
* *教程:* <<getting-started.adoc#getting-started-first-application, 第 1 部分>> | <<getting-started.adoc#getting-started-first-application-code, 第 2 部分>>
* *运行您的例子:* <<getting-started.adoc#getting-started-first-application-run, 第 1 部分>> | <<getting-started.adoc#getting-started-first-application-executable-jar, 第 2 部分>>

== 使用 Spring Boot
准备开始使用 Spring Boot 了? . <<using-spring-boot.adoc#using-boot, 立即上手>>

* *构建系统:* <<using-spring-boot.adoc#using-boot-maven, Maven>> | <<using-spring-boot.adoc#using-boot-gradle, Gradle>> | <<using-spring-boot.adoc#using-boot-ant, Ant>> | <<using-spring-boot.adoc#using-boot-starter, Starters>>
* *最佳实践:* <<using-spring-boot.adoc#using-boot-structuring-your-code, 代码结构>> | <<using-spring-boot.adoc#using-boot-configuration-classes, @Configuration>> | <<using-spring-boot.adoc#using-boot-auto-configuration, @EnableAutoConfiguration>> | <<using-spring-boot.adoc#using-boot-spring-beans-and-dependency-injection, Bean 与依赖注入>>
* *运行代码:* <<using-spring-boot.adoc#using-boot-running-from-an-ide, IDE>> | <<using-spring-boot.adoc#using-boot-running-as-a-packaged-application, Packaged>> | <<using-spring-boot.adoc#using-boot-running-with-the-maven-plugin, Maven>> | <<using-spring-boot.adoc#using-boot-running-with-the-gradle-plugin, Gradle>>
* *打包应用:* <<using-spring-boot.adoc#using-boot-packaging-for-production, 生产环境下的 jar>>
* *Spring Boot CLI:* <<spring-boot-cli.adoc#cli,使用 CLI>>

== 了解 Spring Boot 新特性
需要更多关于 Spring Boot 核心特性?
<<spring-boot-features.adoc#boot-features, Spring 特性>>:

* *核心特性:* <<spring-boot-features.adoc#boot-features-spring-application, SpringApplication>> | <<spring-boot-features.adoc#boot-features-external-config,  外部配置>> | <<spring-boot-features.adoc#boot-features-profiles, Profiles>> | <<spring-boot-features.adoc#boot-features-logging, 日志>>
* *Web 应用程序:* <<spring-boot-features.adoc#boot-features-spring-mvc, MVC>> | <<spring-boot-features.adoc#boot-features-embedded-container, 嵌入式容器>>
* *使用数据:* <<spring-boot-features.adoc#boot-features-sql, SQL>> | <<spring-boot-features.adoc#boot-features-nosql, NO-SQL>>
* *消息传递:* <<spring-boot-features.adoc#boot-features-messaging, 概述>> | <<spring-boot-features.adoc#boot-features-jms, JMS>>
* *测试:* <<spring-boot-features.adoc#boot-features-testing, 概述>> | <<spring-boot-features.adoc#boot-features-testing-spring-boot-applications, Boot Applications>> | <<spring-boot-features.adoc#boot-features-test-utilities, 实用工具>>
* *扩展:* <<spring-boot-features.adoc#boot-features-developing-auto-configuration, 自动配置>> | <<spring-boot-features.adoc#boot-features-condition-annotations, @Conditions>>



== 生产环境
您如果准备将 Spring Boot 应用推送至生产环境,或许会对以下内容<<production-ready-features.adoc#production-ready, 感兴趣>>.

* *管理端点:* <<production-ready-features.adoc#production-ready-endpoints, 概述>>
* *连接方式:* <<production-ready-features.adoc#production-ready-monitoring, HTTP>> | <<production-ready-features.adoc#production-ready-jmx, JMX>>
* *监控:* <<production-ready-features.adoc#production-ready-metrics, 指标>> | <<production-ready-features.adoc#production-ready-auditing, 审计 >> | <<production-ready-features.adoc#production-ready-http-tracing, HTTP 追踪>> | <<production-ready-features.adoc#production-ready-process-monitoring, 流程>>



== 高级内容
最后,我们为高级用户提供了几个主题.

* *部署 Spring Boot 应用:* <<deployment.adoc#cloud-deployment,云部署>> | <<deployment.adoc#deployment-service, OS 服务>>
* *构建工具插件:* <<build-tool-plugins.adoc#build-tool-plugins-maven-plugin, Maven>> | <<build-tool-plugins.adoc#build-tool-plugins-gradle-plugin, Gradle>>
* *附录:* <<appendix-application-properties.adoc#common-application-properties,应用程序属性>> | <<appendix-configuration-metadata.adoc#configuration-metadata,配置元数据>> | <<appendix-auto-configuration-classes.adoc#auto-configuration-classes,自动配置类>> | <<appendix-test-auto-configuration.adoc#test-auto-configuration,测试自动配置注解>> | <<appendix-executable-jar-format.adoc#executable-jar,可执行 Jars>> | <<appendix-dependency-versions.adoc#appendex-dependency-versions,版本依赖>>
