[[index]]
= Spring Boot 中文文档
include::authors.adoc[]
v{spring-boot-version}
include::attributes.adoc[]

本文档包含 https://docs.jcohy.com/docs/spring-boot/{spring-boot-version}/htmlsingle/zh-cn/index.html[一个单页面] 和 https://docs.jcohy.com/docs/spring-boot/{spring-boot-version}/pdf/zh-cn/index.html[一个 PDF].

参考文档包括以下章节:

[horizontal]
<<legal#legal,Legal>> :: 版权信息.
<<getting-help#getting-help,获取帮助>> :: 获取帮助资源.
<<documentation#documentation,文档概述>> :: 第一步,获取关于文档的帮助.
<<getting-started#getting-started,入门指南>> :: 介绍 Spring Boot,系统要求、Servlet 容器、安装 Spring Boot、开发第一个 Spring Boot 应用程序
<<upgrading#upgrading,更新 Spring Boot 应用程序>> :: 从 1.x 升级、 升级到新特性的版本、 升级 Spring Boot CLI.
<<using#using,使用 Spring Boot>> :: 构建系统、 组织代码、 Configuration、Spring Bean 和 依赖注入、DevTools 等.
<<features#features,核心特性>> :: 配置文件、日志记录、国际化、任务执行和调度、测试等.
<<web#web,Web>> :: Servlet Web、 Reactive Web、 嵌入式容器支持、 优雅关机等等.
<<data#data,Data>> :: SQL 和 NOSQL 数据访问.
<<io#io,IO>> :: 缓存、 Quartz Scheduler、 REST 客户端、 发送邮件、 Spring Web Services、 等等.
<<messaging#messaging,Messaging>> :: JMS、 AMQP、 Apache Kafka、 RSocket、 WebSocket、 和 Spring Integration.
<<container-images#container-images,容器镜像>> :: 高效的容器镜像和使用 Dockerfiles 和 Cloud Native Buildpacks 构建容器镜像。
<<actuator#actuator,生产就绪特性>> :: 监控、指标、审计等.
<<deployment.adoc#deployment,部署 Spring Boot 应用程序>> :: 在云上部署、 在 Linux 上安装应用程序.
<<native-image#native-image,GraalVM Native Image Support>> :: 使用 GraalVM 从应用程序创建原生可执行文件
<<cli#cli,Spring Boot CLI>> :: 安装 CLI、使用 CLI、配置 CLI 等.
<<build-tool-plugins1.adoc#build-tool-plugins,构建工具插件>> :: Maven 插件、 Gradle 插件, Antlib 等.
<<howto1.adoc#howto,"`操作方法`" 指南>> :: 应用程序开发、配置、嵌入式服务器、数据访问等等.

参考文档具有以下附录:

[horizontal]
<<application-properties#appendix.application-properties,应用程序属性>> :: 可用于配置应用程序的通用应用程序属性。
<<configuration-metadata#appendix.configuration-metadata,配置元数据>> :: 用于描述配置属性的元数据.
<<auto-configuration-classes#appendix.auto-configuration-classes,自动配置类>> :: Spring Boot 提供的自动配置类.
<<test-auto-configuration#appendix.test-auto-configuration,测试 自动配置注解>> :: 用于测试应用程序切片的测试自动配置注解.
<<executable-jar#appendix.executable-jar,可执行的 Jars>> :: Spring Boot 的可执行 jar，以及其启动器及其格式.
<<dependency-versions#appendix.dependency-versions,版本依赖>> :: Spring Boot 管理的版本依赖的详细信息.


update  [[production-ready-monitoring]]
