[[rfc2617]]
= rfc2617 - HTTP Authentication: Basic and Digest Access Authentication

原文链接: {ietf-rfc}/ https://tools.ietf.org/html/rfc2617[RFC2617]

[NOTE]
====
本备忘录的状态

本文档为Internet社区指定了标准跟踪协议，并要求讨论并提出改进协议。请参考当前版本的“Internet官方协议标准”（STD 1）了解该协议的当前状态。本备忘录的分发是无限制的。

====

[NOTE]
====
版权声明

版权由Internet协会所有。
====

[NOTE]
====
摘要

“HTTP/1.0”包括Basic访问认证方案的规范。因为用户名和密码使用明文在网络中进行传输，因此本方案不作为用户认证的安全方法（除非结合一些外部安全系统一起使用，如SSL[5]）。该文档还提供了HTTP身份认证框架、原始的基本认证方案和基于哈希加密的方案规范，也称为“摘要访问认证”。因为，它也打算替代 https://tools.ietf.org/html/rfc2069[RFC 2069][6]。由于 https://tools.ietf.org/html/rfc2069[RFC 2069]发布以来发现的一些问题，因此移除了RFC 2069中指定的一些可选元素。为了兼容性，又添加了一些新的可选元素，并且强烈建议使用这些新的可选元素。

和Basic认证方式一样，Digest访问认证会验证通信的双方都知道的一个公钥（一个密码）；和Basic认证不同的是，它不需要以明文的方式发送密码，而这正是Basic认证最大的弱点。和大多数认证协议一样，最大的风险不是在于核心协议的本身，而是在于使用协议的策略以及使用它的过程。

====

:toc: []

[[access-authentication]]
== 访问认证

=== 依赖HTTP/1.1规范

该规范是HTTP/1.1规范的的补充 [2]。它使用了该文档扩充的BNF章节2.1，并且依赖该文档定义的非终端以及HTTP/1.1中的其他知识。

[[access-authentication-framework]]
=== 访问认证框架

HTTP提供一种简单的挑战应答机制，服务器可以使用它来质疑客户端的请求和客户端提供的认证信息。它使用可扩展的、不区分大小写的token来识别认证语义，然后在这个语义中使用逗号分隔的实现认证的必要参数属性-值对。

[source,text]
----
    auth-scheme    = token
    auth-param     = token "=" ( token | quoted-string )
----

服务器使用401（未经授权）的响应消息来询问用户代理的授权。此响应信息必须包含一个 `WWW-Authentication`的首部字段，其中至少包含一个适合的请求资源的质询。代理使用407（必须的代理认证）响应消息来质询客户端的授权，并且必须包含一个 `Proxy-
   Authenticate`的首部字段，它至少包含一个代理向请求资源的适合的询问。
[source,text]
----
    challenge   = auth-scheme 1*SP 1#auth-param
----