[[preface]]
== 前言

同时使用面向对象的软件和关系型数据库进行开发是非常麻烦并且耗时的事。由于数据在对象和关系型数据库中表示方式不一样，所以成本也会相应的提高。Hibernate 是解决 Java 环境中 Object/Relational 之间的映射的一种方案，术语 https://en.wikipedia.org/wiki/Object-relational_mapping[Object/Relational Mapping] 是指将数据从对象模型映射到关系数据模型（反之亦然）的技术。

Hibernate 不仅负责从 Java 类到数据库表（以及从 Java 数据类型到 SQL 数据类型）的映射，而且还提供数据查询和检索功能。 它可以显著减少在 SQL 和 JDBC 中手动处理数据所花费的开发时间。 Hibernate 的设计目标是通过消除使用 SQL 和 JDBC 手动处理数据的需要，使开发人员从 95% 的常见数据持久性相关编程任务中解脱出来。 但是，与许多其他持久性解决方案不同，Hibernate 不会向您隐藏 SQL 的强大功能，并保证您对关系技术和知识的投资一如既往地有效。

对于仅使用存储过程在数据库中实现业务逻辑的以数据为中心的应用程序，Hibernate 可能不是最佳解决方案，它对于面向对象的域模型和基于 Java 的中间层中的业务逻辑最有用。 但是，Hibernate 肯定可以帮助您删除或封装特定于提供商的 SQL 代码，还可以将结果集从表格表示转换为对象表示。

=== 参与其中

* 使用 Hibernate 并报告你发现的任何错误或问题。详情请参阅 https://hibernate.org/issuetracker[Issue Tracker]。
* 尝试修复一些 bug 或实现增强功能。同样，请参阅 https://hibernate.org/issuetracker[Issue Tracker].
* 使用邮件列表、论坛、IRC 或社区部分列出的其他方式 https://hibernate.org/community[Community section]。
* 帮助改进或翻译此文档。如果您有兴趣，请在开发者邮件列表上联系我们.
* 让组织的其他成员了解 Hibernate 的好处。.

== 系统要求

Hibernate 5.2 及更高版本至少需要 Java 1.8 和 JDBC 4.2。

Hibernate 5.1 和更早的版本至少需要 Java 1.6 和 JDBC 4.0。

[TIP]
====
当从源代码构建 Hibernate 5.1 或更早版本时，由于 JDK 1.6 编译器中的一个 bug，您需要 Java 1.7。
====

=== 入门指南

新用户可能需要首先浏览 https://docs.jboss.org/hibernate/orm/{majorMinorVersion}/quickstart/html_single/[Hibernate 入门指南] ，了解基本信息和教程。此外还有一系列 https://docs.jboss.org/hibernate/orm/{majorMinorVersion}/topical/html_single/[专题指南]，深入探讨各种主题。

[NOTE]
====
虽然使用 Hibernate 并不需要强大的 SQL 背景知识，但它确实很有帮助，因为所有这些都将归结为 SQL 语句。更重要的是您需要理解数据建模原则。您可以以以下这些资源作为起点:

* https://en.wikipedia.org/wiki/Data_modeling[Data modeling Wikipedia definition]
* https://www.agiledata.org/essays/dataModeling101.html[Data Modeling 101]

了解事务和设计模式  _Unit of Work_ (<<Bibliography.adoc#PoEAA,PoEAA>>) 或 _Application Transaction_ 的基础知识也很重要。 这些主题将在文档中讨论，但事先了解肯定会有所帮助。
====
