= APPEND

**语法**

[source,text]
----
APPEND key value
----

**可用版本**：2.0.0

**时间复杂度**：O(1)。 假设追加的值很小并且已经存在的值是任意大小，则平摊时间复杂度为 O(1)，因为 Redis 使用的动态字符串库将在每次重新分配时将可用空间加倍。

**ACL 类别**：**@write, @string, @fast**

如果 key 已经存在并且是一个字符串， APPEND 命令将 value 追加到 key 原来的值的末尾。

如果 key 不存在， APPEND 就简单地将给定 key 设为 value ，就像执行 SET key value 一样。

== 返回值

https://redis.io/docs/reference/protocol-spec/#resp-integers[整数]: 追加 value 之后， key 中字符串的长度.


== 示例

[source,text]
----
redis> EXISTS mykey
(integer) 0
redis> APPEND mykey "Hello"
(integer) 5
redis> APPEND mykey " World"
(integer) 11
redis> GET mykey
"Hello World"
redis>
----

== 模式：时间序列

APPEND 可以为一系列定长(fixed-size)数据(sample)提供一种紧凑的表示方式，通常称之为时间序列。 每当一个新数据到达的时候，我们都可以使用命令存储它：

[source,text]
----
APPEND timeseries "fixed-size sample"
----

然后可以通过以下的方式访问时间序列的各项属性：

* 可以使用 STRLEN 获取时间序列中数据的数量。
* `GETRANGE` 允许随机访问元素。 如果我们的时间序列具有关联的时间信息，我们可以轻松地实现二分搜索，以将 `GETRANGE` 与 Redis 2.6 中提供的 Lua 脚本引擎相结合来获取范围。
* `SETRANGE` 可用于覆盖现有时间序列。

这个模式的唯一缺陷是我们只能增长时间序列，而不能对时间序列进行缩短，因为 Redis 目前还没有对字符串进行修剪(tirm)的命令，但是，不管怎么说，这个模式的储存方式还是可以节省下大量的空间。

TIP: 可以根据当前的 Unix 时间切换到不同的键，这样每个键可以只有相对少量的样本，以避免处理非常大的键，并使这种模式更有效 易于分布在多个 Redis 实例中。

使用固定大小字符串对传感器温度进行采样的示例（在实际实现中使用二进制格式更好）。

[source,text]
----
redis> APPEND ts "0043"
(integer) 4
redis> APPEND ts "0035"
(integer) 8
redis> GETRANGE ts 0 3
"0043"
redis> GETRANGE ts 4 7
"0035"
redis>

----