[[domain-acls]]
== 域对象安全 (ACLs)

[[domain-acls-overview]]
=== 概述
复杂的应用程序经常会发现需要定义访问权限，而不仅仅是在Web请求或方法调用级别.  相反，安全决策需要同时包含谁 (`Authentication`) ，哪里 (`MethodInvocation`) 和什么 ((`SomeDomainObject`) .  换句话说，授权决策还需要考虑方法调用的实际域对象实例主题.

假设您正在设计宠物诊所的应用程序.  基于Spring的应用程序将有两个主要的用户组: 宠物诊所的工作人员以及宠物诊所的客户.  工作人员将有权访问所有数据，而您的客户只能看到自己的客户记录.
为了使其更具趣味性，您的客户可以允许其他用户查看其客户记录，例如其 "puppy preschool"  导师或本地 "Pony Club" 的总裁.  以Spring Security为基础，您可以使用几种方法:

* 编写您的业务方法以增强安全性.  您可以在 `Customer`  域对象实例中查询集合，以确定哪些用户有权访问.  通过使用 `SecurityContextHolder.getContext().getAuthentication()`，您将能够访问 `Authentication` 对象.
* 编写一个 `AccessDecisionVoter` 以从存储在 `Authentication` 对象中的 `GrantedAuthority[]` 实施安全性.  这意味着您的 `AuthenticationManager` 将需要使用自定义 `GrantedAuthority[]` 填充 `Authentication`，这些 `GrantedAuthority[]` 代表主体可以访问的每个 `Customer` 域对象实例.
* 编写一个 `AccessDecisionVoter` 来增强安全性并直接打开目标客户域对象.  这意味着您的投票者需要访问DAO，以使其能够检索 `Customer` 对象.  然后，它将访问 `Customer` 对象的已批准用户的集合，并做出适当的决定.

这些方法中的每一种都是完全合法的. 但是，第一个将您的授权检查与您的业务代码结合在一起. 这样做的主要问题包括单元测试的难度增加以及在其他地方重用客户授权逻辑会更加困难. 从 `Authentication` 对象获取 `GrantedAuthority[]` 也可以，但是不能扩展到大量的 `Customer`.
如果用户可能能够访问5000个 `Customer` (在这种情况下不太可能，但是可以想象如果它是大型 "Pony Club" 的受欢迎的兽医！) ，那么构造 `Authentication` 对象所消耗的内存量和所需的时间将是不可取的. 最终的方法 (直接从外部代码打开客户) 可能是这三种方法中的最好方法.
它可以实现关注点分离，并且不会滥用内存或CPU周期，但是仍然效率低下，因为 `AccessDecisionVoter` 和最终的业务方法本身都将执行对负责检索 `Customer` 对象的DAO的调用. 每个方法调用两次访问显然是不可取的. 此外，列出每种方法后，
您都需要从头开始编写自己的访问控制列表 (ACL) 持久性和业务逻辑.

幸运的是，还有另一种选择，我们将在下面讨论.


[[domain-acls-key-concepts]]
=== 关键概念
Spring Security的ACL服务位于 `spring-security-acl-xxx.jar` 中.  您将需要将此JAR添加到类路径中，以使用Spring Security的域对象实例安全功能.

Spring Security的域对象实例安全性功能以访问控制列表 (ACL) 的概念为中心.  系统中的每个域对象实例都有其自己的ACL，并且该ACL记录了谁可以使用该域对象以及不能使用该域对象的详细信息.  考虑到这一点，Spring Security为您的应用程序提供了三个与ACL相关的主要功能:

* 一种有效检索所有域对象的ACL条目 (并修改这些ACL) 的方法
* 确保在调用方法之前允许给定的主体处理对象的方法
* 在调用方法之后，一种确保给定的主体可用于对象 (或它们返回的对象) 的方法

如第一个要点所示，Spring Security ACL模块的主要功能之一就是提供了一种高性能的ACL检索方法.  这个ACL储存库功能非常重要，因为系统中的每个域对象实例都可能有多个访问控制项，并且每个ACL都可能以树状结构从其他ACL继承 (Spring对此提供了开箱即用的支持)  安全性，并且非常常用) .
Spring Security的ACL功能经过精心设计，可提供高性能的ACL检索，以及可插入的缓存，最小化死锁的数据库更新，与ORM框架的独立性 (我们直接使用JDBC) ，适当的封装以及透明的数据库更新.

给定数据库对于ACL模块的操作至关重要，让我们探讨一下实现中默认使用的四个主表.  下面是典型的Spring Security ACL部署中按大小顺序显示的表，最后列出的行数最多:

* ACL_SID允许我们唯一地标识系统中的任何主体或权限 ("SID" 代表 "安全身份") .  唯一的列是ID，SID的文本表示形式以及用于指示文本表示形式是引用主体名称还是 `GrantedAuthority` 的标志.  因此，每个唯一的主体或 `GrantedAuthority` 只有一行.  当在接收许可的上下文中使用SID时，通常将其称为 "收件人".
* ACL_CLASS允许我们唯一地标识系统中的任何域对象类.  唯一的列是ID和Java类名称.  因此，对于每个我们希望为其存储ACL权限的唯一类，都有一行.
* ACL_OBJECT_IDENTITY存储系统中每个唯一域对象实例的信息.  列包括ID，ACL_CLASS表的外键，唯一标识符，因此我们知道我们要为其提供信息的ACL_CLASS实例，父级，ACL_SID表的外键以表示域对象实例的所有者，以及 是否允许ACL条目从任何父ACL继承.  对于要为其存储ACL权限的每个域对象实例，我们只有一行.
* 最后，ACL_ENTRY存储分配给每个收件人的个人权限.  列包括ACL_OBJECT_IDENTITY的外键，接收者 (即ACL_SID的外键) ，是否进行审核以及表示授予或拒绝的实际权限的整数位掩码.  对于每个接收到使用域对象的权限的收件人，我们只有一行.

如上一段所述，ACL系统使用整数位掩码.  不用担心，您不必了解使用ACL系统的位转换的优点，但是只要说我们有32位可以打开或关闭就可以了.
这些位中的每一个代表一个权限，默认情况下，权限为 read (bit 0), write (bit 1), create (bit 2), delete (bit 3) 和 administer (bit 4)..  如果您希望使用其他权限，则可以轻松实现自己的 `Permission` 实例，并且ACL框架的其余部分可以在不了解扩展程序的情况下运行.

请务必了解，系统中域对象的数量与我们选择使用整数位掩码这一事实完全无关.  尽管您有32位可用的权限，但您可能有数十亿个域对象实例 (这意味着ACL_OBJECT_IDENTITY中的数十亿行，很可能是ACL_ENTRY) .  之所以说出这一点，是因为我们发现有时人们会误认为每个潜在的域对象都需要一点东西，事实并非如此.

现在，我们已经基本概述了ACL系统的功能以及它在表结构中的外观，下面我们来探讨关键界面.  关键接口是:


* `Acl`: 每个域对象只有一个 `Acl` 对象，该对象在内部保存 `AccessControlEntry`，并且知道 `Acl` 的所有者.  `Acl` 不直接引用域对象，而是引用 `ObjectIdentity`.  `Acl` 存储在 `ACL_OBJECT_IDENTITY` 表中.
* `AccessControlEntry`: 一个 `Acl` 包含多个 `AccessControlEntry`，在框架中通常缩写为 `ACE`.  每个 `ACE` 都引用 `Permission`，`Sid` 和 `Acl` 的特定元组.  `ACE` 也可以是授予或不授予的，并且包含审核设置.  `ACE` 存储在 `ACL_ENTRY` 表中.
* `Permission`: 权限表示特定的不可变位掩码，并提供用于位掩码和输出信息的便捷功能.  上面显示的基本权限 (第0位至第4位) 包含在 `BasePermission` 类中.
* `Sid`: ACL模块需要引用主体和 `GrantedAuthority[]`.  Sid接口提供了一个间接级别，它是 "安全身份" 的缩写.  常见的类包括 `PrincipalSid` (代表 `Authentication` 对象中的主体) 和 `GrantedAuthoritySid`.  安全标识信息存储在ACL_SID表中.
* `ObjectIdentity`: 每个域对象在ACL模块内部由一个ObjectIdentity表示.  默认实现为 `ObjectIdentityImpl`.
* `AclService`: 检索适用于给定 `ObjectIdentity` 的 `Acl`.  在包含的实现 (`JdbcAclService`) 中，将检索操作委托给 `LookupStrategy`.  `LookupStrategy` 提供了一种高度优化的策略，用于使用批量检索 (`BasicLookupStrategy`) 来检索 `ACL` 信息，并支持利用实例化视图，分层查询和类似的以性能为中心的非ANSI SQL功能的自定义实现.
* `MutableAclService`: 允许显示修改后的 `Acl` 以保持持久性.  如果您不愿意，则不必使用此界面.

请注意，我们现成的AclService和相关数据库类均使用ANSI SQL.  因此，这应该适用于所有主要数据库.  在撰写本文时，已使用Hypersonic SQL，PostgreSQL，Microsoft SQL Server和Oracle成功测试了该系统.

Spring Security附带了两个示例，它们演示了ACL模块.  第一个是联系人样本，另一个是文档管理系统 (DMS) 样本.  我们建议您看一下这些作为示例.

[[domain-acls-getting-started]]
=== 入门
要开始使用Spring Security的ACL功能，您需要将ACL信息存储在某处.  这需要使用Spring实例化 `DataSource`.  然后将 `DataSource` 注入到 `JdbcMutableAclService` 和 `BasicLookupStrategy` 实例中.
后者提供高性能的ACL检索功能，而前者提供了 mutator 功能.  有关示例配置，请参阅Spring Security附带的示例之一.  您还需要使用上一节中列出的四个特定于ACL的表格填充数据库 (有关适当的SQL语句，请参阅ACL示例) .

创建所需的架构并实例化 `JdbcMutableAclService` 之后，接下来需要确保您的域模型支持与Spring Security ACL软件包的互操作性.  希望 `ObjectIdentityImpl` 将证明是足够的，因为它提供了多种使用方式.
大多数人将拥有包含公共 `Serializable getId()` 方法的域对象.  如果返回类型为 long 或与long兼容 (例如int) ，则将发现不需要进一步考虑 `ObjectIdentity` 问题.  ACL模块的许多部分都依赖长标识符.
如果您使用的不是long型 (或int，byte等) ，则很有可能需要重新实现许多类.  我们不打算在Spring Security的ACL模块中支持非长标识符，因为长已经与所有数据库序列 (最常见的标识符数据类型) 兼容，并且长度足以容纳所有常见的使用情况.

以下代码片段显示了如何创建 `Acl` 或修改现有的 `Acl`:

[source,java]
----
// Prepare the information we'd like in our access control entry (ACE)
ObjectIdentity oi = new ObjectIdentityImpl(Foo.class, new Long(44));
Sid sid = new PrincipalSid("Samantha");
Permission p = BasePermission.ADMINISTRATION;

// Create or update the relevant ACL
MutableAcl acl = null;
try {
acl = (MutableAcl) aclService.readAclById(oi);
} catch (NotFoundException nfe) {
acl = aclService.createAcl(oi);
}

// Now grant some permissions via an access control entry (ACE)
acl.insertAce(acl.getEntries().length, p, sid, true);
aclService.updateAcl(acl);
----


在上面的示例中，我们检索了与标识符为44的 "Foo" 域对象相关联的ACL. 然后，我们添加了ACE，以便名为 "Samantha" 的主体可以 "管理" 该对象.
除了insertAce方法外，该代码段是相对不言自明的.  insertAce方法的第一个参数是确定新条目将在Acl中的哪个位置插入.  在上面的示例中，我们只是将新的ACE放在现有ACE的末尾.  最后一个参数是布尔值，指示ACE是授予还是拒绝.  在大多数情况下，它会被授予 (true) ，但是如果它被拒绝 (false) ，则实际上会阻止该权限.

Spring Security没有提供任何特殊的集成来自动创建，更新或删除ACL，这是DAO或存储库操作的一部分.  相反，您将需要为单个域对象编写如上所示的代码.  值得考虑的是在服务层上使用AOP来自动将ACL信息与服务层操作集成在一起.  过去，我们发现这种方法非常有效.

使用上述技术在数据库中存储一些ACL信息后，下一步就是实际将ACL信息用作授权决策逻辑的一部分.  您在这里有很多选择.  您可以编写自己的 `AccessDecisionVoter` 或 `AfterInvocationProvider`，它们分别在方法调用之前或之后触发.
这样的类将使用 `AclService` 来检索相关的ACL，然后调用 `Acl.isGranted(Permission[] permission, Sid[] sids, boolean administrativeMode)`  来确定是否授予权限.  或者，
您可以使用我们的 `AclEntryVoter`，`AclEntryAfterInvocationProvider` 或 `AclEntryAfterInvocationCollectionFilteringProvider` 类.
所有这些类都提供了一种基于声明的方法，用于在运行时评估ACL信息，使您无需编写任何代码.  请参考示例应用程序以了解如何使用这些类.