[[jc-method]]
== 方法的安全

从2.0版开始,Spring Security大大改进了对为服务层方法增加安全性的支持.
它提供对JSR-250注解安全性以及框架原始 `@Secured` 注解的支持.  从3.0开始,您还可以使用新的基于表达式的<<el-access,基于表达式的注解>>.  您可以使用 `intercept-methods` 元素来修饰bean声明,从而将安全性应用于单个bean,或者可以使用AspectJ样式切入点在整个服务层中保护多个bean.

=== EnableGlobalMethodSecurity

我们可以在任何 `@Configuration` 实例上使用 `@EnableGlobalMethodSecurity` 注解启用基于注解的安全性.  例如,以下将启用Spring Security的 `@Secured` 注解.

[source,java]
----
@EnableGlobalMethodSecurity(securedEnabled = true)
public class MethodSecurityConfig {
// ...
}
----

向方法(在类或接口上) 添加注解将相应地限制对该方法的访问.  Spring Security的内置注解支持为该方法定义了一组属性.  这些将被传递给 `AccessDecisionManager` 做出实际决定:

[source,java]
----
public interface BankService {

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
public Account readAccount(Long id);

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
public Account[] findAccounts();

@Secured("ROLE_TELLER")
public Account post(Account account, double amount);
}
----

可以使用以下命令启用对JSR-250注解的支持

[source,java]
----
@EnableGlobalMethodSecurity(jsr250Enabled = true)
public class MethodSecurityConfig {
// ...
}
----

这些是基于标准的,并允许应用基于角色的简单约束,但是没有Spring Security的内置注解的强大功能.
要使用新的基于表达式的语法,可以使用

[source,java]
----
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class MethodSecurityConfig {
// ...
}
----

而等效的Java代码将是

[source,java]
----
public interface BankService {

@PreAuthorize("isAnonymous()")
public Account readAccount(Long id);

@PreAuthorize("isAnonymous()")
public Account[] findAccounts();

@PreAuthorize("hasAuthority('ROLE_TELLER')")
public Account post(Account account, double amount);
}
----

=== GlobalMethodSecurityConfiguration

有时您可能需要执行比 `@EnableGlobalMethodSecurity` 注解允许的操作更复杂的操作.  对于这些实例,可以扩展 `GlobalMethodSecurityConfiguration`,以确保 `@EnableGlobalMethodSecurity` 注解出现在子类中.
例如,如果您想提供一个自定义的 `MethodSecurityExpressionHandler`,则可以使用以下配置:

[source,java]
----
@EnableGlobalMethodSecurity(prePostEnabled = true)
public class MethodSecurityConfig extends GlobalMethodSecurityConfiguration {
	@Override
	protected MethodSecurityExpressionHandler createExpressionHandler() {
		// ... create and return custom MethodSecurityExpressionHandler ...
		return expressionHandler;
	}
}
----

有关可以覆盖的方法的其他信息,请参考 `GlobalMethodSecurityConfiguration` Javadoc.

[[ns-global-method]]
=== <global-method-security> 元素
此元素用于在您的应用程序中启用基于注解的安全性(通过在该元素上设置适当的属性) ,并将用于整个应用程序上下文的安全性切入点声明组合在一起.  您只应声明一个 `<global-method-security>` 元素.  以下声明将启用对Spring Security的 `@Secured` 的支持:

[source,xml]
----
<global-method-security secured-annotations="enabled" />
----

向方法(在类或接口上) 添加注解将相应地限制对该方法的访问.  Spring Security的内置注解支持为该方法定义了一组属性.  这些将被传递给 `AccessDecisionManager` 做出实际决定:

[source,java]
----
public interface BankService {

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
public Account readAccount(Long id);

@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
public Account[] findAccounts();

@Secured("ROLE_TELLER")
public Account post(Account account, double amount);
}
----

可以使用以下命令启用对JSR-250注解的支持

[source,xml]
----
<global-method-security jsr250-annotations="enabled" />
----

这些是基于标准的,并允许应用基于角色的简单约束,但是没有Spring Security的内置注解的强大功能.  要使用新的基于表达式的语法,可以使用

[source,xml]
----
<global-method-security pre-post-annotations="enabled" />
----

而等效的Java代码将是

[source,java]
----
public interface BankService {

@PreAuthorize("isAnonymous()")
public Account readAccount(Long id);

@PreAuthorize("isAnonymous()")
public Account[] findAccounts();

@PreAuthorize("hasAuthority('ROLE_TELLER')")
public Account post(Account account, double amount);
}
----

如果您需要定义简单的规则,而不是根据用户的权限列表检查角色名称,则基于表达式的注解是一个不错的选择.

[NOTE]
====
带注解的方法仅对于定义为Spring Bean的实例(在启用方法安全性的同一应用程序上下文中) 是安全的.  如果要保护不是由Spring创建的实例(例如,使用new运算符) ,则需要使用AspectJ.
====

[NOTE]
====
您可以在同一应用程序中启用不止一种类型的注解,但是任何接口或类都只能使用一种类型的注解,否则将无法很好地定义行为.  如果找到两个适用于特定方法的注解,则将仅应用其中一个
====

[[ns-protect-pointcut]]
=== 使用  protect-pointcut 添加安全的切点

`protect-pointcut` 的使用特别强大,因为它允许您仅通过简单的声明就可以将安全性应用于许多bean.  考虑以下示例:

[source,xml]
----
<global-method-security>
<protect-pointcut expression="execution(* com.mycompany.*Service.*(..))"
	access="ROLE_USER"/>
</global-method-security>
----

这将保护在应用程序上下文中声明的bean(其类位于 `com.mycompany` 包中且其类名以 "Service" 结尾) 上的所有方法.  只有具有 `ROLE_USER` 角色的用户才能调用这些方法.  与URL匹配一样,最具体的匹配项必须在切入点列表中排在第一位,因为将使用第一个匹配表达式.  安全注解优先于切入点.
