[[redis:reactive]]
= Reactive Redis 支持
:referenceDir: .

本节介绍了响应式Redis支持以及入门方法. 响应式 Redis 支持与 <<redis,命令式 Redis 支持>> 有某些重叠.

[[redis:reactive:requirements]]
== Redis 要求

Spring Data Redis当前与 https://github.com/lettuce-io/lettuce-core[Lettuce] 集成为唯一的响应式 Java 连接器. https://projectreactor.io/[Project Reactor] 用作反应成分库.

[[redis:reactive:connectors]]
== 使用反应性驱动程序连接到Redis

使用 Redis 和 Spring 时的首要任务之一是通过IoC容器连接到 store. 为此,需要Java连接器(或绑定).
无论选择哪种库,都必须使用 `org.springframework.data.redis.connection` 包及其 `ReactiveRedisConnection` 和 `ReactiveRedisConnectionFactory` 接口来使用和检索与Redis的活动连接.

[[redis:reactive:connectors:operation-modes]]
=== Redis操作模式

Redis可以使用  <<redis:sentinel,Redis Sentinel>> 作为独立服务器运行,也可以在  <<cluster,Redis 集群>> 模式下运行. https://github.com/lettuce-io/lettuce-core[Lettuce] 支持所有前面提到的连接类型.

[[redis:reactive:connectors:connection]]
=== `ReactiveRedisConnection` 和 `ReactiveRedisConnectionFactory`

`ReactiveRedisConnection` 是 Redis 通信的核心,因为它处理与 Redis 后端的通信. 它还会自动将底层驱动程序异常转换为 Spring 一致的DAO异常层次结构,因此您可以在不更改任何代码的情况下切换连接器,因为操作语义保持不变.

`ReactiveRedisConnectionFactory` 创建活动的 `ReactiveRedisConnection` 实例. 另外,工厂还充当 `PersistenceExceptionTranslator` 实例,这意味着工厂一旦声明,就可以进行透明的异常转换-例如,通过使用 `@Repository` 注解和AOP进行异常转换.
有关更多信息,请参见Spring Framework文档中的 https://docs.spring.io/spring/docs/{spring-framework-version}/spring-framework-reference/data-access.html#orm-exception-translation[特定部分] .

NOTE: 根据基础配置,工厂可以返回新连接或现有连接(如果使用池或共享本地连接).

TIP: 使用 `ReactiveRedisConnectionFactory` 的最简单方法是通过IoC容器配置适当的连接器,并将其注入 using 类.

[[redis:reactive:connectors:lettuce]]
=== 配置 Lettuce 连接器

Spring Data Redis 通过 `org.springframework.data.redis.connection.lettuce` 包支持 https://github.com/lettuce-io/lettuce-core[Lettuce].

您可以按以下步骤配置 Lettuce `ReactiveRedisConnectionFactory`:

[source,java]
----
@Bean
public ReactiveRedisConnectionFactory connectionFactory() {
  return new LettuceConnectionFactory("localhost", 6379);
}
----

以下示例显示了使用 `LettuceClientConfigurationBuilder` 的更复杂的配置,包括SSL和超时:

[source,java]
----
@Bean
public ReactiveRedisConnectionFactory lettuceConnectionFactory() {

  LettuceClientConfiguration clientConfig = LettuceClientConfiguration.builder()
    .useSsl().and()
    .commandTimeout(Duration.ofSeconds(2))
    .shutdownTimeout(Duration.ZERO)
    .build();

  return new LettuceConnectionFactory(new RedisStandaloneConfiguration("localhost", 6379), clientConfig);
}
----

有关更详细的客户端配置调整,请参阅 https://docs.spring.io/spring-data/redis/docs/{revnumber}/api/org/springframework/data/redis/connection/lettuce/LettuceClientConfiguration.html[`LettuceClientConfiguration`].

[[redis:reactive:template]]
== 通过 ReactiveRedisTemplate 处理对象

大多数用户可能会使用 `ReactiveRedisTemplate` 及其相应的包 `org.springframework.data.redis.core`. 由于其丰富的功能集,该模板实际上是 Redis 模块的中心类. 该模板为Redis交互提供了高级抽象.
尽管 `ReactiveRedisConnection` 提供了接受和返回二进制值(ByteBuffer)的低级方法,但该模板负责序列化和连接管理,使您无需处理此类细节.

此外,该模板提供了操作视图(按照 Redis https://redis.io/commands[命令参考]进行分组之后),这些操作视图提供了丰富的通用接口来针对某种类型进行工作,如下表所述:

.Operational views
[width="80%",cols="<1,<2",options="header"]
|====
|Interface
|Description

2+^|_Key Type Operations_

|ReactiveGeoOperations
|Redis geospatial operations such as `GEOADD`, `GEORADIUS`, and others)

|ReactiveHashOperations
|Redis hash operations

|ReactiveHyperLogLogOperations
|Redis HyperLogLog operations such as (`PFADD`, `PFCOUNT`, and others)

|ReactiveListOperations
|Redis list operations

|ReactiveSetOperations
|Redis set operations

|ReactiveValueOperations
|Redis string (or value) operations

|ReactiveZSetOperations
|Redis zset (or sorted set) operations
|====

配置后,该模板是线程安全的,并且可以在多个实例之间重用.

`ReactiveRedisTemplate` 的大多数操作都使用基于 Java 的序列化器. 这意味着通过 `RedisElementWriter` 或 `RedisElementReader` 序列化或反序列化由模板写入或读取的任何对象. 序列化上下文在构建时传递给模板,Redis 模块在 `org.springframework.data.redis.serializer` 包中提供了几种可用的实现. 有关更多信息,请参见  <<redis:serializer>>.

以下示例显示了用于返回 `Mono` 的 `ReactiveRedisTemplate`:

[source,java]
----
@Configuration
class RedisConfiguration {

  @Bean
  ReactiveRedisTemplate<String, String> reactiveRedisTemplate(ReactiveRedisConnectionFactory factory) {
    return new ReactiveRedisTemplate<>(factory, RedisSerializationContext.string());
  }
}
----

[source,java]
----
public class Example {

  @Autowired
  private ReactiveRedisTemplate<String, String> template;

  public Mono<Long> addLink(String userId, URL url) {
    return template.opsForList().leftPush(userId, url.toExternalForm());
  }
}
----

[[redis:reactive:string]]
== String 的便捷操作类

由于 Redis 中存储的键和值通常是 `java.lang.String`,因此 Redis 模块为 `ReactiveRedisTemplate` 提供了基于 String 的扩展:`ReactiveStringRedisTemplate`. 这是用于密集型 String 操作的便捷的一站式解决方案. 除了绑定到字符串键之外,
该模板还使用基于字符串的 `RedisSerializationContext`,这意味着存储的键和值是人类可读的(假定Redis和您的代码使用相同的编码). 以下示例显示了正在使用的 `ReactiveStringRedisTemplate`:

[source,java]
----
@Configuration
class RedisConfiguration {

  @Bean
  ReactiveStringRedisTemplate reactiveRedisTemplate(ReactiveRedisConnectionFactory factory) {
    return new ReactiveStringRedisTemplate<>(factory);
  }
}
----

[source,java]
----
public class Example {

  @Autowired
  private ReactiveStringRedisTemplate redisTemplate;

  public Mono<Long> addLink(String userId, URL url) {
    return redisTemplate.opsForList().leftPush(userId, url.toExternalForm());
  }
}
----

include::{referenceDir}/reactive-messaging.adoc[leveloffset=+1]

== Reactive 脚本

通过反应式基础架构执行 Redis 脚本可以使用通过 `ReactiveRedisTemplate` 最佳访问的 `ReactiveScriptExecutor` 来完成.

[source,java]
----
public class Example {

  @Autowired
  private ReactiveRedisTemplate<String, String> template;

  public Flux<Long> theAnswerToLife() {

    DefaultRedisScript<Long> script = new DefaultRedisScript<>();
    script.setLocation(new ClassPathResource("META-INF/scripts/42.lua"));
    script.setResultType(Long.class);

    return reactiveTemplate.execute(script);
  }
}
----

有关脚本命令的更多详细信息,请参见 <<scripting,脚本部分>>.