[[redis:reactive:pubsub]]
= Redis Messaging/PubSub

Spring Data 为 Redis 提供了专用的消息传递集成,其功能和命名与 Spring Framework 中的 JMS 集成非常相似; 实际上,熟悉 Spring 的 JMS 支持的用户应该有宾至如归的感觉.

Redis消息传递可以大致分为两个功能区域,即消息的产生或发布以及消息的使用或订阅,因此简称为 pubsub(发布/订阅). `ReactiveRedisTemplate` 类用于消息生成. 对于异步接收,Spring Data 提供了一个专用的消息监听器容器,该容器用于消耗消息流.
出于订阅目的,`ReactiveRedisTemplate` 提供了使用监听器容器的简化选择.

`org.springframework.data.redis.connection` 和 `org.springframework.data.redis.listener` 包提供了使用Redis消息传递的核心功能.

[[redis:reactive:pubsub:publish]]
== Sending/Publishing messages

要发布消息,可以与其他操作一样使用底层的 `ReactiveRedisConnection` 或高级 `ReactiveRedisTemplate`. 这两个实体都提供一种发布方法,该方法接受需要发送的消息以及目标通道作为参数. 尽管 `ReactiveRedisConnection` 需要原始数据,但 `ReactiveRedisTemplate` 允许将任意对象作为消息传递:

[source,java]
----
// send message through ReactiveRedisConnection
ByteBuffer msg = …
ByteBuffer channel = …
Mono<Long> publish = con.publish(msg, channel);

// send message through ReactiveRedisTemplate
ReactiveRedisTemplate template = …
Mono<Long> publish = template.convertAndSend("channel", "message");
----

[[redis:reactive:pubsub:subscribe]]
== Receiving/Subscribing for messages

在接收端,可以直接命名一个通道或使用模式匹配来订阅一个或多个通道. 后一种方法非常有用,因为它不仅允许使用一个命令创建多个订阅,而且还可以监听在订阅时尚未创建的通道(只要它们与模式匹配).

在低层,`ReactiveRedisConnection` 提供了 subscription 和 `pSubscribe` 方法,它们映射 Redis 命令以分别按模式按通道进行订阅. 注意,可以将多个通道或模式用作参数. 要更改订阅,只需查询 `ReactiveSubscription` 的通道和模式.

NOTE: Spring Data Redis 中的响应式订阅命令是非阻塞的,可以终止而不会发出任何元素.

如上所述,一旦订阅,连接就会开始等待消息. 除了添加新订阅或修改/取消现有订阅之外,无法在其上调用其他命令. 除 `subscribe`,`pSubscribe`,`unsubscribe` 或 `pUnsubscribe` 以外的命令是非法的,并且会导致异常.

为了接收消息,需要获得消息流. 请注意,订阅仅发布有关在该特定订阅中注册的通道和模式的消息. 消息流本身是一个热序列,它在不考虑需求的情况下生成元素. 确保注册足够的需求,以免耗尽消息缓冲区.

[[redis:reactive:pubsub:subscribe:containers]]
=== Message 监听容器

Spring Data 提供了 `ReactiveRedisMessageListenerContainer`,它代表用户完成所有繁重的转换和订阅状态管理.

`ReactiveRedisMessageListenerContainer` 充当消息监听器容器. 它用于从 Redis 通道接收消息并暴露消息流,该消息流发出应用反序列化的通道消息. 它负责注册接收消息,资源获取和释放,异常转换等. 这使您作为应用程序开发人员, 可以编写与接收消息(并对消息做出响应)相关的(可能很复杂)业务逻辑,并将样板 Redis 基础结构问题委托给框架. 消息流在发布者订阅后在 Redis 中注册一个订阅,如果订阅被取消,则注销.

此外,为了最大程度地减少应用程序占用空间,`ReactiveRedisMessageListenerContainer` 允许一个连接和一个线程由多个监听器共享,即使它们不共享订阅. 因此,无论应用程序跟踪多少个监听器或通道,整个生命周期的运行时间成本都将保持不变.
此外,该容器允许更改运行时配置,因此可以在应用程序运行时添加或删除监听器,而无需重新启动. 此外,容器使用惰性订阅方法,仅在需要时才使用 `ReactiveRedisConnection`---- 如果所有监听器都未订阅,则将自动执行清除.

消息监听器容器本身不需要外部线程资源. 它使用驱动程序线程来发布消息.

[source,java]
----
ReactiveRedisConnectionFactory factory = …
ReactiveRedisMessageListenerContainer container = new ReactiveRedisMessageListenerContainer(factory);

Flux<ChannelMessage<String, String>> stream = container.receive(ChannelTopic.of("my-channel"));
----

要等待并确保正确订阅，您可以使用返回 `Mono<Flux<ChannelMessage>>` 的 `receiveLater` 方法。
作为完成对给定主题的订阅的结果，生成的  `Mono`  与内部发布者一起完成。 通过拦截 `onNext` 信号，您可以同步服务器端订阅。

[source,java]
----
ReactiveRedisConnectionFactory factory = …
ReactiveRedisMessageListenerContainer container = new ReactiveRedisMessageListenerContainer(factory);

Mono<Flux<ChannelMessage<String, String>>> stream = container.receiveLater(ChannelTopic.of("my-channel"));

stream.doOnNext(inner -> // notification hook when Redis subscriptions are synchronized with the server)
    .flatMapMany(Function.identity())
    .…;
----


[[redis:reactive:pubsub:subscribe:template]]
=== 通过模板 API 订阅

如上所述,您可以直接使用 `ReactiveRedisTemplate` 订阅通道/模式. 这种方法提供了一种直接但有限的解决方案,因为您松开了在初始订阅之后添加订阅的选项. 不过,您仍然可以使用例如返回的 `Flux` 控制消息流. 服用(持续时间). 完成读取后,一旦出错或取消,所有绑定的资源将再次释放.

[source,java]
----
redisTemplate.listenToChannel("channel1", "channel2").doOnNext(msg -> {
    // message processing ...
}).subscribe();
----
