[[cluster]]
= Redis 集群

使用 https://redis.io/topics/cluster-spec[Redis Cluster] 需要 Redis Server 3.0+ 版本. 有关更多信息,请参见 https://redis.io/topics/cluster-tutorial[集群教程].

== 启用 Redis 集群

群集支持基于与非群集通信相同的构造块. `RedisClusterConnection` 是 `RedisConnection` 的扩展,用于处理与 Redis 群集的通信,并将错误转换为 Spring DAO 异常层次结构. `RedisClusterConnection` 实例是使用 `RedisConnectionFactory` 创建的,
必须使用关联的 `RedisClusterConfiguration` 对其进行设置,如以下示例所示:

.Redis 集群的示例 RedisConnectionFactory 配置
====
[source,java]
----
@Component
@ConfigurationProperties(prefix = "spring.redis.cluster")
public class ClusterConfigurationProperties {

    /*
     * spring.redis.cluster.nodes[0] = 127.0.0.1:7379
     * spring.redis.cluster.nodes[1] = 127.0.0.1:7380
     * ...
     */
    List<String> nodes;

    /**
     * Get initial collection of known cluster nodes in format {@code host:port}.
     *
     * @return
     */
    public List<String> getNodes() {
        return nodes;
    }

    public void setNodes(List<String> nodes) {
        this.nodes = nodes;
    }
}

@Configuration
public class AppConfig {

    /**
     * Type safe representation of application.properties
     */
    @Autowired ClusterConfigurationProperties clusterProperties;

    public @Bean RedisConnectionFactory connectionFactory() {

        return new JedisConnectionFactory(
            new RedisClusterConfiguration(clusterProperties.getNodes()));
    }
}
----
====

[TIP]
====
`RedisClusterConfiguration` 也可以通过 `PropertySource` 定义,并具有以下属性:

.配置属性
- `spring.redis.cluster.nodes`: 以逗号分隔的 host:port 列表.
- `spring.redis.cluster.max-redirects`: 允许的集群重定向数.
====

NOTE: 初始配置将驱动程序库指向一组初始的群集节点. 由实时群集重新配置导致的更改仅保留在本地驱动程序中,而不会写回到配置中.

[[cluster.working.with.cluster]]
== 使用 Redis 群集连接

如前所述,Redis 群集的行为与单节点 Redis 甚至是 Sentinel 监视的主副本环境不同. 这是因为自动分片将密钥映射到 16384 个 slots 之一,该 slots 分布在节点上. 因此,涉及多个键的命令必须断言所有键都映射到完全相同的 slots ,以避免跨 slots 执行错误.
单个群集节点仅提供一组专用密钥. 针对一台特定服务器发出的命令仅针对该服务器提供的那些键返回结果. 作为一个简单的示例,请考虑  `KEYS`  命令. 当在集群环境中发布给服务器时,它仅返回请求发送到的节点所服务的密钥,而不一定返回集群中的所有密钥.
因此,要在群集环境中获取所有密钥,必须从所有已知的主节点读取密钥.


虽然将特定密钥重定向到相应的 slots 服务节点是由驱动程序库处理的,但是 `RedisClusterConnection` 涵盖了更高级别的功能,例如跨节点收集信息或向集群中的所有节点发送命令. 拾取前面的密钥示例,这意味着keys(pattern)方法将拾取群集中的每个主节点,
并同时在每个主节点上执行 `KEYS` 命令,同时拾取结果并返回累积的键集. 仅请求单个节点的键,`RedisClusterConnection` 为这些方法提供了重载(例如,`keys(node, pattern)`).

可以从 `RedisClusterConnection.clusterGetNodes` 获得 `RedisClusterNode`,也可以使用主机和端口或节点ID来构造它.

以下示例显示了在集群中运行的一组命令:

.跨集群运行命令的示例
====
[source,text]
----
redis-cli@127.0.0.1:7379 > cluster nodes

6b38bb... 127.0.0.1:7379 master - 0 0 25 connected 0-5460                      <1>
7bb78c... 127.0.0.1:7380 master - 0 1449730618304 2 connected 5461-10922       <2>
164888... 127.0.0.1:7381 master - 0 1449730618304 3 connected 10923-16383      <3>
b8b5ee... 127.0.0.1:7382 slave 6b38bb... 0 1449730618304 25 connected          <4>
----

[source,java]
----
RedisClusterConnection connection = connectionFactory.getClusterConnnection();

connection.set("thing1", value);                                               <5>
connection.set("thing2", value);                                               <6>

connection.keys("*");                                                          <7>

connection.keys(NODE_7379, "*");                                               <8>
connection.keys(NODE_7380, "*");                                               <9>
connection.keys(NODE_7381, "*");                                               <10>
connection.keys(NODE_7382, "*");                                               <11>
----
<1> Master node serving slots 0 to 5460 replicated to replica at 7382
<2> Master node serving slots 5461 to 10922
<3> Master node serving slots 10923 to 16383
<4> Replica node holding replicants of the master at 7379
<5> Request routed to node at 7381 serving slot 12182
<6> Request routed to node at 7379 serving slot 5061
<7> Request routed to nodes at 7379, 7380, 7381 -> [thing1, thing2]
<8> Request routed to node at 7379 -> [thing2]
<9> Request routed to node at 7380 -> []
<10> Request routed to node at 7381 -> [thing1]
<11> Request routed to node at 7382 -> [thing2]
====

当所有键都映射到同一 slot 时,本地驱动程序库会自动处理跨 slots 请求,例如 `MGET`. 但是,一旦不是这种情况,`RedisClusterConnection` 会对 slots 服务节点执行多个并行的 `GET` 命令,然后再次返回累积的结果.
这比单 slot 执行的性能要差,因此应谨慎使用. 如有疑问,请考虑通过在大括号中提供前缀(例如 `{my-prefix}.thing1` 和 `{my-prefix}.thing2`)来将密钥固定到同一 slot ,这两者都将映射到相同的 slot 号. 以下示例显示了跨槽请求处理:

.Sample of Cross-Slot Request Handling
====
[source,text]
----
redis-cli@127.0.0.1:7379 > cluster nodes

6b38bb... 127.0.0.1:7379 master - 0 0 25 connected 0-5460                      <1>
7bb...
----

[source,java]
----
RedisClusterConnection connection = connectionFactory.getClusterConnnection();

connection.set("thing1", value);           // slot: 12182
connection.set("{thing1}.thing2", value);  // slot: 12182
connection.set("thing2", value);           // slot:  5461

connection.mGet("thing1", "{thing1}.thing2");                                  <2>

connection.mGet("thing1", "thing2");                                           <3>
----
<1> 与之前示例中的配置相同.
<2> Keys map to same slot -> 127.0.0.1:7381 MGET thing1 {thing1}.thing2
<3> Keys map to different slots and get split up into single slot ones routed to the according nodes +
 -> 127.0.0.1:7379 GET thing2 +
 -> 127.0.0.1:7381 GET thing1
====

TIP: 前面的示例演示了 Spring Data Redis 遵循的一般策略. 请注意,某些操作可能需要将大量数据加载到内存中才能计算所需的命令. 此外,并非所有跨槽请求都可以安全地移植到多个单个槽请求,如果使用不当,则会出错(例如 `PFCOUNT`).

[[cluster.redistemplate]]
== 使用 `RedisTemplate` 和 `ClusterOperations`

有关  <<redis:template>> 的一般用途,配置和用法的信息,请参见通过 `RedisTemplate` 使用对象.

CAUTION: 使用任何 JSON `RedisSerializer` 设置  `RedisTemplate#keySerializer` 时要小心,因为更改 JSON 结构会立即影响哈希槽的计算.

`RedisTemplate` 通过 `ClusterOperations` 接口提供对特定于集群的操作的访问,该接口可以从 `RedisTemplate.opsForCluster()` 获得. 这使您可以在群集内的单个节点上显式运行命令,同时保留为模板配置的序列化和反序列化功能.
它还提供管理命令(例如 `CLUSTER MEET`)或更高级的操作(例如,重新分片).

以下示例显示如何使用 `RedisTemplate` 访问 `RedisClusterConnection`:

.Accessing `RedisClusterConnection` with `RedisTemplate`
====
[source,text]
----
ClusterOperations clusterOps = redisTemplate.opsForCluster();
clusterOps.shutdown(NODE_7379);                                              <1>
----
<1> Shut down node at 7379 and cross fingers there is a replica in place that can take over.
====
