[[scripting]]
= Redis 脚本

Redis 2.6 及更高版本通过 https://redis.io/commands/eval[eval] 和 https://redis.io/commands/evalsha[evalsha] 命令提供了对 Lua 脚本执行的支持. Spring Data Redis 为脚本执行提供了高级抽象,该抽象处理了序列化并自动使用 Redis 脚本缓存.

可以通过调用 `RedisTemplate` 和 `ReactiveRedisTemplate` 的 `execute` 方法来运行脚本.两者都使用可配置的 `ScriptExecutor`(或 `ReactiveScriptExecutor`)来运行提供的脚本.默认情况下,`ScriptExecutor`(或 `ReactiveScriptExecutor`)负责序列化提供的键和参数并反序列化脚本结果.这是通过模板的键和值序列化程序完成的.还有一个额外的重载,可让您传递脚本参数和结果的自定义序列化程序.

默认的 `ScriptExecutor` 通过检索脚本的SHA1并首先尝试运行 evalsha 来优化性能,如果Redis脚本缓存中还没有该脚本,则回退到 eval.

以下示例通过使用 Lua 脚本运行常见的  "`check-and-set`" 方案.这是 Redis 脚本的理想用例,因为它需要原子地运行一组命令,并且一个命令的行为会受到另一个命令的结果的影响.

[source,java]
----
@Bean
public RedisScript<Boolean> script() {

  ScriptSource scriptSource = new ResourceScriptSource(new ClassPathResource("META-INF/scripts/checkandset.lua"));
  return RedisScript.of(scriptSource, Boolean.class);
}
----

[source,java]
----
public class Example {

  @Autowired
  RedisScript<Boolean> script;

  public boolean checkAndSet(String expectedValue, String newValue) {
    return redisTemplate.execute(script, singletonList("key"), asList(expectedValue, newValue));
  }
}
----

[source,lua]
----
-- checkandset.lua
local current = redis.call('GET', KEYS[1])
if current == ARGV[1]
  then redis.call('SET', KEYS[1], ARGV[2])
  return true
end
return false
----

前面的代码配置 `RedisScript` 指向一个名为 `checkandset.lua` 的文件,该文件应返回布尔值. 脚本 `resultType` 应该是 `Long`,`Boolean`,`List` 或反序列化值类型之一. 如果脚本返回抛弃状态(特别是 `OK`),则它也可以为 `null`.

TIP: 理想的是在您的应用程序上下文中配置 `DefaultRedisScript` 的单个实例,以避免在每次执行脚本时重新计算脚本的 SHA1.

然后,上面的 `checkAndSet` 方法运行脚本. 脚本可以在 `SessionCallback` 内作为事务或管道的一部分运行. 有关更多信息,请参见 "`<<tx>>`" 和  "`<<pipeline>>`" .

Spring Data Redis 提供的脚本支持还允许您通过使用 Spring Task 和 Scheduler 抽象来调度 Redis 脚本以定期执行. 有关更多详细信息,请参见 https://projects.spring.io/spring-framework/[Spring Framework] 文档.