[[redis:support:cache-abstraction]]
== 支持 Spring Cache 抽象

NOTE: Changed in 2.0

Spring Redis 通过 `org.springframework.data.redis.cache` 包提供了 Spring {spring-framework-reference}/integration.html#cache[缓存抽象]的实现. 要将 Redis 用作实现,请将 `RedisCacheManager` 添加到您的配置中,如下所示:

[source,java]
----
@Bean
public RedisCacheManager cacheManager(RedisConnectionFactory connectionFactory) {
	return RedisCacheManager.create(connectionFactory);
}
----

可以使用 `RedisCacheManagerBuilder` 配置 `RedisCacheManager` 行为,让您设置默认的 `RedisCacheConfiguration`,事务行为和预定义的缓存.

[source,java]
----
RedisCacheManager cm = RedisCacheManager.builder(connectionFactory)
	.cacheDefaults(defaultCacheConfig())
	.withInitialCacheConfigurations(singletonMap("predefined", defaultCacheConfig().disableCachingNullValues()))
	.transactionAware()
	.build();
----

如前面的示例所示,`RedisCacheManager` 允许在每个缓存的基础上定义配置.

由 `RedisCacheManager` 创建的 `RedisCache` 的行为由 `RedisCacheConfiguration` 定义. 通过该配置,您可以设置 key 到期时间,前缀和 `RedisSerializer` 实现,以实现与二进制存储格式之间的相互转换,如以下示例所示:

[source,java]
----
RedisCacheConfiguration config = RedisCacheConfiguration.defaultCacheConfig()
    .entryTtl(Duration.ofSeconds(1))
	.disableCachingNullValues();
----

`RedisCacheManager` 默认使用无锁 `RedisCacheWriter` 来读写二进制值. 无锁缓存提高了吞吐量. 缺少条目锁定会导致 `putIfAbsent` 和 `clean` 方法的重叠,非原子性命令重叠,因为这些方法需要将多个命令发送到 Redis.
锁定对方通过设置显式锁定键并检查该键是否存在来防止命令重叠,从而导致其他请求和潜在的命令等待时间.

锁定适用于 *cache level*, 而不是每个 *cache entry*

可以选择如下锁定行为:

[source,java]
----
RedisCacheManager cm = RedisCacheManager.build(RedisCacheWriter.lockingRedisCacheWriter())
	.cacheDefaults(defaultCacheConfig())
	...
----

默认情况下,缓存条目的任何 key 都以实际的缓存名称作为前缀,后跟两个冒号. 此行为可以更改为静态前缀和计算前缀.

以下示例显示了如何设置静态前缀:

[source,java]
----
// static key prefix
RedisCacheConfiguration.defaultCacheConfig().prefixKeysWith("( ͡° ᴥ ͡°)");

The following example shows how to set a computed prefix:

// computed key prefix
RedisCacheConfiguration.defaultCacheConfig().computePrefixWith(cacheName -> "¯\_(ツ)_/¯" + cacheName);
----

缓存实现默认使用 `KEYS` 和 `DEL` 来清除缓存。 `KEYS` 可能会导致大键空间出现性能问题。 因此，可以使用 `BatchStrategy` 创建默认的 `RedisCacheWriter` 以切换到基于 `SCAN` 的批处理策略。
`SCAN` 策略需要批量大小以避免过多的 Redis 命令往返：

[source,java]
----
RedisCacheManager cm = RedisCacheManager.build(RedisCacheWriter.nonLockingRedisCacheWriter(connectionFactory, BatchStrategies.scan(1000)))
	.cacheDefaults(defaultCacheConfig())
	...
----

NOTE: 使用任何驱动程序和 Redis 操作模式（独立、集群）完全支持 `KEYS` 批处理策略。 使用 Lettuce 驱动程序时完全支持 `SCAN`。 Jedis 仅在非集群模式下支持 `SCAN`。

下表列出了 `RedisCacheManager` 的默认设置

.`RedisCacheManager` defaults
[width="80%",cols="<1,<2",options="header"]
|====
|Setting
|Value

|Cache Writer
|Non-locking

|Cache Configuration
|`RedisCacheConfiguration#defaultConfiguration`

|Initial Caches
|None

|Transaction Aware
|No
|====

下表列出了 `RedisCacheConfiguration` 的默认设置:

.RedisCacheConfiguration defaults
[width="80%",cols="<1,<2",options="header"]
|====
|Key Expiration
|None

|Cache `null`
|Yes

|Prefix Keys
|Yes

|Default Prefix
|The actual cache name

|Key Serializer
|`StringRedisSerializer`

|Value Serializer
|`JdkSerializationRedisSerializer`

|Conversion Service
|`DefaultFormattingConversionService` with default cache key converters
|====

[NOTE]
====
默认情况下， `RedisCache` 的统计信息是禁用的.
使用 `RedisCacheManagerBuilder.enableStatistics()` 通过 `RedisCache#getStatistics()` 来收集本地 _hits_ 和 _misses_ 返回所收集数据的快照.
====
