spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: guides
          uri: https://spring.io
          predicates:
            - After=2020-09-02T00:00:00.000-00:00[America/Denver]
