// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[ant]]
= 从 Gradle 使用 Ant

Gradle 提供了与 Ant 的出色集成.您可以在 Gradle 构建中使用单个 Ant 任务或整个 Ant 构建.实际上,您会发现,在 Gradle 构建脚本中使用 Ant 任务比使用 Ant 的 XML 格式要容易得多,功能更强大.您甚至可以简单地将 Gradle 用作强大的 Ant 任务脚本工具.

蚂蚁可以分为两层.第一层是 Ant 语言.它提供了 `build.xml` 文件的语法,目标的处理,特殊的构造 (例如 macrodef) 等等.换句话说,除 Ant 任务和类型以外的所有内容.Gradle 理解这种语言,并允许您将 Antbuild.xml 直接导入 Gradle 项目.然后,您可以像使用 Gradle 任务一样使用 Ant 构建的目标.

蚂蚁的第二层是其丰富的 Ant 任务和类型,如 `javac`, `copy` or `jar`.对于这一层,Gradle 只需依靠 Groovy 即可实现集成 `AntBuilder`.

最后,由于构建脚本是 Groovy 脚本,因此您始终可以将 Ant 构建作为外部进程执行.构建脚本会含有类似的语句: `"ant clean compile".execute()`.footnote:[In Groovy you can execute Strings. To learn more about executing external processes with Groovy have a look in 'Groovy in Action' 9.3.2 or at the Groovy wiki]

您可以使用 Gradle 的 Ant 集成作为将构建从 Ant 迁移到 Gradle 的路径.例如,您可以从导入现有的 Ant 构建开始.然后,您可以将依赖声明从 Ant 脚本移至构建文件.最后,您可以将任务移到构建文件中,或将其替换为 Gradle 的某些插件.随着时间的流逝,此过程可以分几步完成,并且在整个过程中,您都可以使用有效的 Gradle 构建.



[[sec:using_ant_tasks]]
== 在构建中使用Ant任务和类型

在您的构建脚本中,`ant` Gradle 提供了一个名为的属性.这是对 link:{javadocPath}/org/gradle/api/AntBuilder.html[AntBuilder] 实例的引用.这 `AntBuilder` 用于从构建脚本访问 Ant 任务,类型和属性.从Ant `build.xml` 格式到 Groovy 有一个非常简单的映射,下面将进行解释.

您可以通过在 `AntBuilder` 实例上调用方法来执行 Ant 任务.您使用任务名称作为方法名称.例如,您可以 `ws` 通过调用 `ant.echo()` 方法来执行 Ant 任务.Ant 任务的属性作为 `Map` 参数传递给方法.下面是 `ws` 任务的示例.注意,我们还可以混合使用 Groovy 代码和 Ant 任务标记.这可能非常强大.

.Using an Ant task
====
include::{snippets-dir}/ant/useAntTask/groovy/build.gradle"
include::{snippets-dir}/ant/useAntTask/kotlin/build.gradle.kts"
====

.`gradle hello` 的输出
----
> gradle hello
include::{snippets-dir}/ant/useAntTask/tests/useAntTask.out[]
----

您可以通过将嵌套的文本作为任务方法调用的参数传递给 Ant 任务.在此示例中,我们 `ws` 以嵌套文本形式传递任务消息:

.Passing nested text to an Ant task
====
include::{snippets-dir}/ant/taskWithNestedText/groovy/build.gradle"
include::{snippets-dir}/ant/taskWithNestedText/kotlin/build.gradle.kts"
====

.`gradle hello` 的输出
----
> gradle hello
include::{snippets-dir}/ant/taskWithNestedText/tests/taskWithNestedText.out[]
----

您将嵌套元素传递给闭包内部的 Ant 任务.通过调用与我们要定义的元素同名的方法,以与任务相同的方式定义嵌套元素.

.Passing nested elements to an Ant task
====
include::{snippets-dir}/ant/taskWithNestedElements/groovy/build.gradle"
include::{snippets-dir}/ant/taskWithNestedElements/kotlin/build.gradle.kts"
====

您可以使用与访问任务相同的方式来访问 Ant 类型,方法是将类型的名称用作方法名称.方法调用返回 Ant 数据类型,然后您可以在构建脚本中直接使用它.在以下示例中,我们创建一个 Ant `path` 对象,然后遍历它的内容.

.Using an Ant type
====
include::{snippets-dir}/ant/useAntType/groovy/build.gradle"
include::{snippets-dir}/ant/useAntType/kotlin/build.gradle.kts"
====

有关更多信息,请 `AntBuilder` 参见 'Groovy in Action' 8.4 或  https://groovy-lang.org/scripting-ant.html[Groovy Wiki].

[[sec:using_custom_ant_tasks]]
=== 在构建中使用定制的Ant任务

要使自定义任务在构建中可用,可以像使用文件一样使用 `taskdef` (通常更容易) 或 `typedef` Ant任务 `build.xml`.然后,您可以像内置 Ant 任务一样引用自定义 Ant 任务

.Using a custom Ant task
====
include::{snippets-dir}/ant/useExternalAntTask/groovy/build.gradle"
include::{snippets-dir}/ant/useExternalAntTask/kotlin/build.gradle.kts"
====

您可以使用 Gradle 的依赖管理来组装用于自定义任务的类路径.为此,您需要为类路径定义一个自定义配置,然后向该配置中添加一些依赖.这在 link:declaring_dependencies.html[声明依赖] 中有更详细的描述.

.Declaring the classpath for a custom Ant task
====
include::{snippets-dir}/ant/useExternalAntTaskWithConfig/groovy/build.gradle[tags=define-classpath]
include::{snippets-dir}/ant/useExternalAntTaskWithConfig/kotlin/build.gradle.kts[tags=define-classpath]
====

要使用类路径配置,请使用 `asPath` 定制配置的属性.

.Using a custom Ant task and dependency management together
====
include::{snippets-dir}/ant/useExternalAntTaskWithConfig/groovy/build.gradle[tags=use-classpath]
include::{snippets-dir}/ant/useExternalAntTaskWithConfig/kotlin/build.gradle.kts[tags=use-classpath]
====

[[sec:import_ant_build]]
== 导入 Ant 构建

您可以使用该 `ant.importBuild()`  方法将 Ant 构建导入到 Gradle 项目中.导入 Ant 构建时,每个 Ant 目标都被视为 Gradle 任务.这意味着您可以按照与 Gradle 任务完全相同的方式来操纵和执行 Ant 目标.

.Importing an Ant build
====
include::{snippets-dir}/ant/hello/groovy/build.gradle"
include::{snippets-dir}/ant/hello/kotlin/build.gradle.kts"
====

====
include::{snippets-dir}/ant/hello/groovy/build.xml"
====

.`gradle hello` 的输出
----
> gradle hello
include::{snippets-dir}/ant/hello/tests/antHello.out[]
----

您可以添加一个依赖于 Ant target 的任务:

.Task that depends on Ant target
====
include::{snippets-dir}/ant/dependsOnAntTarget/groovy/build.gradle"
include::{snippets-dir}/ant/dependsOnAntTarget/kotlin/build.gradle.kts"
====

.`gradle intro` 的输出
----
> gradle intro
include::{snippets-dir}/ant/dependsOnAntTarget/tests/dependsOnAntTarget.out[]
----

或者,您可以将行为添加到 Ant target:

.Adding behaviour to an Ant target
====
include::{snippets-dir}/ant/addBehaviourToAntTarget/groovy/build.gradle"
include::{snippets-dir}/ant/addBehaviourToAntTarget/kotlin/build.gradle.kts"
====

.`gradle hello` 的输出
----
> gradle hello
include::{snippets-dir}/ant/addBehaviourToAntTarget/tests/addBehaviourToAntTarget.out[]
----

Ant target 也有可能依赖 Gradle 任务:

.Ant target that depends on Gradle task
====
include::{snippets-dir}/ant/dependsOnTask/groovy/build.gradle"
include::{snippets-dir}/ant/dependsOnTask/kotlin/build.gradle.kts"
====

====
include::{snippets-dir}/ant/dependsOnTask/groovy/build.xml"
====

.`gradle hello` 的输出
----
> gradle hello
include::{snippets-dir}/ant/dependsOnTask/tests/dependsOnTask.out[]
----

有时可能需要 "rename"  为 Ant target 生成的任务,以避免与现有 Gradle 任务发生命名冲突.为此,请使用 link:{javadocPath}/org/gradle/api/AntBuilder.html#importBuild-java.lang.Object-org.gradle.api.Transformer-[AntBuilder.importBuild(java.lang.Object, org.gradle.api.Transformer)] 方法.

.Renaming imported Ant targets
====
include::{snippets-dir}/ant/renameTask/groovy/build.gradle"
include::{snippets-dir}/ant/renameTask/kotlin/build.gradle.kts"
====

====
include::{snippets-dir}/ant/renameTask/groovy/build.xml"
====

.`gradle a-hello` 的输出
----
> gradle a-hello
include::{snippets-dir}/ant/renameTask/tests/renameAntDelegate.out[]
----

请注意,尽管此方法的第二个参数应该是 link:{javadocPath}/org/gradle/api/Transformer.html[Transformer],但在 Groovy 中进行编程时,由于 http://mrhaki.blogspot.ie/2013/11/groovy-goodness-implicit-closure.html[Groovy 支持将闭包自动强制转换为单抽象方法类型] ,因此我们可以简单地使用闭包而不是匿名内部类 (或类似的内部类) .

[[sec:ant_properties]]
== Ant 属性和引用

有几种方法可以设置 Ant 属性,以便 Ant 任务可以使用该属性.您可以直接在 `AntBuilder` 实例上设置属性.Ant 属性也可以作为 `Map` 来使用,您可以对其进行更改.您还可以使用 `Antproperty` 任务.以下是一些有关如何执行此操作的示例.

.Setting an Ant property
====
include::{snippets-dir}/ant/properties/groovy/build.gradle[tags=set-property]
include::{snippets-dir}/ant/properties/kotlin/build.gradle.kts[tags=set-property]
====

许多 Ant 任务在执行时都会设置属性.有几种方法可以获取这些属性的值.您可以直接从 `AntBuilder` 实例获取属性.Ant 属性也可以作为 `Map` 使用.以下是一些示例.

.Getting an Ant property
====
include::{snippets-dir}/ant/properties/groovy/build.xml[tags=getproperty]
====

====
include::{snippets-dir}/ant/properties/groovy/build.gradle[tags=get-property]
include::{snippets-dir}/ant/properties/kotlin/build.gradle.kts[tags=get-property]
====

有几种方法可以设置 Ant 引用:

.Setting an Ant reference
====
include::{snippets-dir}/ant/properties/groovy/build.gradle[tags=set-reference]
include::{snippets-dir}/ant/properties/kotlin/build.gradle.kts[tags=set-reference]
====

====
include::{snippets-dir}/ant/properties/groovy/build.xml[tags=setreference]
====

有几种获取 Ant 引用的方法:

.Getting an Ant reference
====
include::{snippets-dir}/ant/properties/groovy/build.xml[tags=getreference]
====

====
include::{snippets-dir}/ant/properties/groovy/build.gradle[tags=get-reference]
include::{snippets-dir}/ant/properties/kotlin/build.gradle.kts[tags=get-reference]
====

[[sec:ant_logging]]
== Ant logging

Gradle 将 Ant 消息优先级映射到 Gradle 日志级别,以便从 Ant 日志的消息出现在 Gradle 输出中.默认情况下,这些映射如下:

.Ant message priority mapping
[cols="a,a", options="header"]
|===
| Ant Message Priority
| Gradle Log Level

| _VERBOSE_
| `DEBUG`

| _DEBUG_
| `DEBUG`

| _INFO_
| `INFO`

| _WARN_
| `WARN`

| _ERROR_
| `ERROR`
|===


[[sec:fine_tuning_ant_logging]]
=== 微调 Ant 日志记录

Ant 消息优先级到 Gradle 日志级别的默认映射有时可能会出现问题.例如,没有消息优先级直接映射到 `LIFECYCLE` 日志级别,这是 Gradle 的默认值.许多 Ant 任务以 INFO 优先级记录消息,这意味着要从 Gradle 公开这些消息,必须在将日志级别设置为的情况下运行构建 `INFO`,从而可能记录比期望更多的输出.

相反,如果 Ant 任务记录消息的级别过高,则要抑制这些消息,将需要以更高的日志级别运行构建,例如 `QUIET`.但是,这可能导致其他期望的输出被抑制.

为了解决这个问题,Gradle 允许用户微调 Ant 日志并控制消息优先级到 Gradle 日志级别的映射.这是通过 `LIFECYCLE` 使用 link:{javadocPath}/org/gradle/api/AntBuilder.html#setLifecycleLogLevel-java.lang.String-[AntBuilder.setLifecycleLogLevel(java.lang.String)] 方法设置应映射到默认 Gradle 日志级别的优先级来完成的.设置此值后,以配置的优先级或更高优先级记录的任何 Ant 消息将至少记录在 `LIFECYCLE`.低于此优先级记录的任何Ant消息最多将记录为 `INFO`.

例如,以下内容更改了映射,以便在日志级别公开 Ant INFO 优先级消息 `LIFECYCLE`.

.Fine tuning Ant logging
====
include::{snippets-dir}/ant/antLogging/groovy/build.gradle"
include::{snippets-dir}/ant/antLogging/kotlin/build.gradle.kts"
====

.`gradle hello` 的输出
----
> gradle hello
include::{snippets-dir}/ant/antLogging/tests/antLogging.out[]
----

另一方面,如果将 `lifecycleLogLevel` 设置为 _ERROR_,则将不再以日志级别记录以 _WARN_ 优先级记录的 Ant 消息 `WARN`.现在将以该 `INFO` 级别记录它们,并且默认情况下将其禁止显示.

[[sec:ant_api]]
== API

Ant 集成由 link:{javadocPath}/org/gradle/api/AntBuilder.html[AntBuilder] 提供.
