// Copyright 2018 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[authoring_maintainable_build_scripts]]
= 创作可维护版本的最佳实践

Gradle 具有丰富的 API,其中包含创建构建逻辑的几种方法. 关联的灵活性很容易导致不必要的复杂的构建,而通常直接将自定义代码添加到构建脚本中. 在本章中,我们介绍了几种最佳实践,它们将帮助您开发易于使用的表达性和可维护性版本.

NOTE: 如果您感兴趣的话,第三方 link:https://github.com/nebula-plugins/gradle-lint-plugin[Gradle lint plugin] 可帮助在构建脚本中强制执行所需的代码样式.

[[sec:avoid_imperative_logic_in_scripts]]
== 避免在脚本中使用命令式逻辑

Gradle运行时不对构建逻辑强制执行特定样式. 因此,最终很容易生成将声明性DSL元素与命令性程序代码混合在一起的构建脚本. 让我们谈一些具体的例子.

* _声明式 code:_ 内置的,与语言无关的 DSL 元素 (e.g. link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:dependencies(groovy.lang.Closure)[Project.dependencies{}] or link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:repositories(groovy.lang.Closure)[Project.repositories{}]) 或插件公开的 DSL  or DSLs exposed by plugins
* _命令式 code:_ 条件逻辑或非常复杂的任务动作实现

每个构建脚本的最终目标应该是仅包含声明性语言元素,这使代码更易于理解和维护. 祈使逻辑应该存在于二进制插件中,然后将其应用于构建脚本.
作为辅助产品,如果您将 artifacts 发布到二进制存储库,则可以自动使您的团队在 link:../samples/sample_publishing_convention_plugins.html[其他项目中重用插件逻辑].

以下示例构建显示了直接在构建脚本中使用条件逻辑的否定示例. 尽管此代码段很小,但很容易想象使用大量过程语句的成熟构建脚本及其对可读性和可维护性的影响. 通过将代码移到一个类中,也可以对其进行单独测试.

.A build script using conditional logic to create a task
====
include::{snippets-dir}/bestPractices/conditionalLogic-dont/groovy/build.gradle[]
include::{snippets-dir}/bestPractices/conditionalLogic-dont/kotlin/build.gradle.kts[]
====

让我们比较一下构建脚本和与二进制插件实现的相同逻辑. 该代码起初看起来可能涉及更多,但显然看起来更像是典型的应用程序代码. 这个特定的插件类位于 <<organizing_gradle_projects.adoc#sec:build_sources,`buildSrc` directory>> 中,该目录可自动将其提供给构建脚本.

.A binary plugin implementing imperative logic
====
include::{snippets-dir}/bestPractices/conditionalLogic-do/groovy/buildSrc/src/main/java/com/enterprise/ReleasePlugin.java[]
====

现在,构建逻辑已转换为插件,您可以在构建脚本中应用它. 该构建脚本已从 8 行代码缩减为一行.

.A build script applying a plugin that encapsulates imperative logic
====
include::{snippets-dir}/bestPractices/conditionalLogic-do/groovy/build.gradle[]
include::{snippets-dir}/bestPractices/conditionalLogic-do/kotlin/build.gradle.kts[]
====

[[sec:avoiding_gradle_internal_apis]]
== 避免使用内部 Gradle API

当 Gradle 或插件更改时,在插件和构建脚本中使用 Gradle 内部 API 可能会破坏构建.

link:https://github.com/gradle/gradle/blob/180b9d3fa84b91768364c603380e82947437eda1/buildSrc/subprojects/configuration/src/main/kotlin/org/gradle/gradlebuild/public-api.kt[Gradle public API definition] 定义中列出了以下程序包,但名称中带有 `internal` 的任何子程序包除外:

----
org/gradle/*
org/gradle/api/**
org/gradle/authentication/**
org/gradle/buildinit/**
org/gradle/caching/**
org/gradle/concurrent/**
org/gradle/deployment/**
org/gradle/external/javadoc/**
org/gradle/ide/**
org/gradle/includedbuild/**
org/gradle/ivy/**
org/gradle/jvm/**
org/gradle/language/**
org/gradle/maven/**
org/gradle/nativeplatform/**
org/gradle/normalization/**
org/gradle/platform/**
org/gradle/play/**
org/gradle/plugin/devel/**
org/gradle/plugin/repository/*
org/gradle/plugin/use/*
org/gradle/plugin/management/*
org/gradle/plugins/**
org/gradle/process/**
org/gradle/testfixtures/**
org/gradle/testing/jacoco/**
org/gradle/tooling/**
org/gradle/swiftpm/**
org/gradle/model/**
org/gradle/testkit/**
org/gradle/testing/**
org/gradle/vcs/**
org/gradle/workers/**
----

=== 常用内部 API 的替代方案

要为您的自定义任务提供嵌套的 DSL,请不要使用 `org.gradle.internal.reflect.Instantiator`;  改用 link:{javadocPath}/org/gradle/api/model/ObjectFactory.html[ObjectFactory]. 阅读有关 <<lazy_configuration.adoc#lazy_configuration,延迟配置章节>>可能也会有所帮助.

不要使用 `org.gradle.api.internal.ConventionMapping`. 使用 link:{javadocPath}/org/gradle/api/provider/Provider.html[Provider] 和/或 link:{javadocPath}/org/gradle/api/provider/Property.html[Property]. 您可以在  <<implementing_gradle_plugins.adoc#capturing_user_input_to_configure_plugin_runtime_behavior,implementing plugins section>> 中找到获取用户输入以配置运行时行为的示例.

代替  `org.gradle.internal.os.OperatingSystem` ,使用另一种方法来检测操作系统,例如 Apache commons-lang SystemUtils 或 link:https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/SystemUtils.html[Apache commons-lang SystemUtils] or `System.getProperty("os.name")`

使用其他集合或 I/O 框架代替 `org.gradle.util.CollectionUtils`, `org.gradle.util.GFileUtils` 和 `org.gradle.util.*` 下的其他类.

Gradle 插件作者可能会发现 "设计Gradle插件" 小节对 <<designing_gradle_plugins.adoc#restricting_the_plugin_implementation_to_gradle_s_public_api,将插件实现限制为 Gradle 的公共 API>> 有所帮助.

[[sec:declaring_tasks]]
== 声明任务时遵循约定

Task API 为构建作者提供了很大的灵活性,使其可以在构建脚本中声明任务. 为了获得最佳的可读性和可维护性,请遵循以下规则:

* 任务类型应该是任务名称后面括号内的唯一键值对.
* 其他配置应在任务的配置块中完成.
* 声明任务时添加的 <<tutorial_using_tasks.adoc#sec:hello_world,Task actions>> 只能使用  link:{groovyDslPath}/org.gradle.api.Task.html#org.gradle.api.Task:doFirst(org.gradle.api.Action)[Task.doFirst{}] or link:{groovyDslPath}/org.gradle.api.Task.html#org.gradle.api.Task:doLast(org.gradle.api.Action)[Task.doLast{}] 方法声明..
* 声明临时任务-没有明确类型的任务时-如果仅声明单个操作,则应使用 link:{groovyDslPath}/org.gradle.api.Task.html#org.gradle.api.Task:doLast(org.gradle.api.Action)[Task.doLast{}].
* 一个任务应该 <<#sec:improving_task_discoverability,定义一个组和描述>>.

.Definition of tasks following best practices
====
include::{snippets-dir}/bestPractices/taskDefinition/groovy/build.gradle[]
include::{snippets-dir}/bestPractices/taskDefinition/kotlin/build.gradle.kts[]
====

[[sec:improving_task_discoverability]]
== 提高任务发现能力

即使是构建的新用户,也应该能够快速而轻松地找到关键信息. 在 Gradle 中,您可以为构建的任何 <<command_line_interface.adoc#sec:listing_tasks,tasks report>> 一个 link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:group[group] 和一个 link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:description[description] . 任务报告使用分配的值来组织和呈现任务,以便于发现.
分配组和描述对于您希望构建用户调用的任何任务最有帮助.

示例任务 `generateDocs` 以 HTML 页面的形式为项目生成文档. 该任务应组织在存储桶文档的下方. 该描述应表达其意图.

.A task declaring the group and description
====
include::{snippets-dir}/bestPractices/taskGroupDescription/groovy/build.gradle[]
include::{snippets-dir}/bestPractices/taskGroupDescription/kotlin/build.gradle.kts[]
====

任务报告的输出反映了分配的值.

----
> gradle tasks

> Task :tasks

Documentation tasks
-------------------
generateDocs - Generates the HTML documentation for this project.
----

[[sec:minimize_logic_executed_configuration_phase]]
== 最小化在配置阶段执行的逻辑

每个构建脚本开发人员都必须了解构建 <<build_lifecycle.adoc#build_lifecycle,build lifecycle>> 的不同阶段及其对构建逻辑的性能和评估顺序的影响,这一点很重要. 在配置阶段,
应配置项目及其领域对象,而执行阶段仅执行命令行上请求的任务及其依赖的操作.请注意,任何不属于任务动作的代码都将在每次运行构建时执行. link:https://scans.gradle.com/get-started[build scan] 可以帮助您确定每个生命周期阶段所花费的时间. 这是诊断常见性能问题的宝贵工具.

让我们考虑一下上面描述的反模式. 在构建脚本中,您可以看到分配给配置  `printArtifactNames` 的依赖在任务操作之外已解决.

.Executing logic during configuration should be avoided
====
include::{snippets-dir}/bestPractices/logicDuringConfiguration-dont/groovy/build.gradle[tags=config-logic]
include::{snippets-dir}/bestPractices/logicDuringConfiguration-dont/kotlin/build.gradle.kts[tags=config-logic]
====

解决依赖的代码应移到任务操作中,以避免在实际需要依赖之前解决依赖带来的性能影响.

.Executing logic during execution phase is preferred
====
include::{snippets-dir}/bestPractices/logicDuringConfiguration-do/groovy/build.gradle[tags=config-logic]
include::{snippets-dir}/bestPractices/logicDuringConfiguration-do/kotlin/build.gradle.kts[tags=config-logic]
====

[[sec:avoiding_use_of_gradlebuild]]
== 避免使用 `GradleBuild` 任务类型

link:{groovyDslPath}/org.gradle.api.tasks.GradleBuild.html[GradleBuild] 任务类型允许构建脚本定义调用另一个 Gradle 构建的任务. 通常不建议使用此类型. 在某些极端情况下,所调用的构建与命令行或通过 Tooling API 暴露的运行时行为不同,从而导致意外结果.

通常,有一种更好的方法来对需求进行建模.适当的方法取决于当前的问题.这里有一些选择:

* 如果打算将来自不同模块的任务作为统一构建执行,则将构建建模为<<multi_project_builds.adoc#multi_project_builds,多项目构建>> .
* 对物理上分离但偶尔应作为一个单元构建的项目使用<<composite_builds.adoc#composite_builds,composite builds>>.

[[sec:avoiding_inter_project_configuration]]
== 避免项目间配置

Gradle并不限制构建脚本作者从<<multi_project_builds.adoc#multi_project_builds,多项目构建>>中的一个项目进入另一个项目中的 domain .
高度耦合的项目会损害 <<multi_project_configuration_and_execution.adoc#sec:parallel_execution,构建执行性能>>以及代码的可读性和可维护性.

应避免以下做法:

* 通过 link:{groovyDslPath}/org.gradle.api.Task.html#org.gradle.api.Task:dependsOn(java.lang.Object++[]++)[Task.dependsOn(java.lang.Object++...++)] 显式依赖于另一个项目中的任务.
* 在另一个项目的领域对象上设置属性值或调用方法.
* 用 <<#sec:avoiding_use_of_gradlebuild,GradleBuild>> 执行构建的另一部分.
* 声明不必要的<<declaring_dependencies.adoc#sub:project_dependencies,project dependencies>>.

[[sec:avoiding_passwords_in_plain_text]]
== 外部化和加密您的密码

大多数构建需要使用一个或多个密码. 此需求的原因可能有所不同. 一些构建需要密码才能将 artifacts 发布到安全的二进制存储库,而其他构建则需要密码来下载二进制文件. 密码应始终保持安全,以防止欺诈. 在任何情况下,您都不应以纯文本形式将密码添加到构建脚本中,或者在项目目录的gradle.properties文件中声明该密码. 这些文件通常位于版本控制存储库中,任何有权访问该文件的人都可以查看.

密码以及任何其他敏感数据应保存在版本控制的项目文件外部. Gradle 公开了一个用于在 link:{javadocPath}/org/gradle/api/provider/ProviderFactory.html#credentials-java.lang.Class-java.lang.String-[ProviderFactory] 中提供凭证的 API 以及 <<declaring_repositories.adoc#sec:handling_credentials,Artifact Repositories>>,
该 API 允许在构建需要它们时使用 <<build_environment#sec:gradle_configuration_properties,Gradle properties>> 提供凭证值. 这样,凭据可以存储在用户主目录中的 `gradle.properties` 文件中,也可以使用命令行参数或环境变量注入凭据.

如果您将敏感凭据存储在用户主目录的 `gradle.properties` 中,请考虑对其进行加密. 目前,Gradle 还没有提供用于加密,存储和访问密码的内置机制.
解决此问题的一个很好的解决方案是 link:https://github.com/etiennestuder/gradle-credentials-plugin[Gradle Credentials plugin].
