// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[build_lifecycle]]
= 构建生命周期

我们之前说过 Gradle 的核心是一种基于依赖的编程语言。在 Gradle 术语中，这意味着你可以定义任务和任务之间的依赖关系。Gradle 保证了这些任务按照它们依赖的顺序执行，并且每个任务只执行一次。
这些任务形成了一个 http://en.wikipedia.org/wiki/Directed_acyclic_graph[Directed Acyclic Graph]。有一些构建工具在执行任务时构建这样的依赖关系图。Gradle 在执行任何任务之前建立完整的依赖关系图。这是 Gradle 的核心思想，它使许多其他时候不可能的事情成为可能

您的构建脚本将配置此依赖关系图。因此，严格来说，它们是构建配置脚本。

[[sec:build_phases]]
== 构建阶段

Gradle 构建具有三个不同的阶段。

初始化::
Gradle 支持单项目和多项目构建。在初始化阶段，Gradle 决定要参与构建的项目，并为每个项目创建一个 link:{groovyDslPath}/org.gradle.api.Project.html[Project] 实例。
配置::
在此阶段，将配置项目对象。执行作为构建一部分的所有项目的构建脚本。
执行::
Gradle 确定要在配置阶段创建和配置的任务子集。 子集由传递给 gradle 命令的任务名称参数和当前目录确定。 然后 Gradle 执行每个选定的任务。

[[sec:settings_file]]
== Settings 文件

在构建脚本文件旁边，Gradle 定义了一个 settings 文件。 settings 文件是由 Gradle 通过命名约定确定的。这个文件的默认名称是 `settings.gradle`。在本章的后面，我们将解释 Gradle 如何查找设置文件。

设置文件在初始化阶段执行。 多项目构建必须在多项目层次结构的根项目中具有 `settings.gradle` 文件。 这是必需的，因为设置文件定义了哪些项目正在参与多项目构建（请参阅  <<multi_project_builds.adoc#multi_project_builds,Authoring Multi-Project Builds>> ）。
对于单项目构建，设置文件是可选的。 除了定义包含的项目之外，您可能还需要将库添加到构建脚本类路径中（请参阅 <<organizing_gradle_projects.adoc#organizing_gradle_projects,Organizing Gradle Projects>>）。 

.Single project build
====
include::{snippets-dir}/buildlifecycle/basic/groovy/settings.gradle[]
include::{snippets-dir}/buildlifecycle/basic/groovy/build.gradle[]
include::{snippets-dir}/buildlifecycle/basic/kotlin/settings.gradle.kts[]
include::{snippets-dir}/buildlifecycle/basic/kotlin/build.gradle.kts[]
====

=== **`gradle test testBoth`** 的输出
[source.multi-language-sample,groovy]
----
> gradle test testBoth
include::{snippets-dir}/buildlifecycle/basic/tests-groovy/buildlifecycle.groovy.out[]
----
[source.multi-language-sample,kotlin]
----
> gradle test testBoth
include::{snippets-dir}/buildlifecycle/basic/tests-kotlin/buildlifecycle.kotlin.out[]
----

对于构建脚本，属性访问和方法调用被委托给项目对象。类似地，设置文件中的属性访问和方法调用也被委托给设置对象。有关更多信息，请参阅 API 文档中的 link:{groovyDslPath}/org.gradle.api.initialization.Settings.html[Settings] 类。

[[sec:initialization]]
== 初始化

Gradle 如何知道执行单个项目还是多个项目？ 如果您从具有 `settings.gradle` 文件的目录中触发多项目构建，则 Gradle 使用它来配置构建。 Gradle 还允许您从参与构建的任何子项目中执行构建。footnote:[Gradle supports partial multi-project builds (see <<intro_multi_project_builds.adoc#,Executing Multi-Project Builds>>).]
如果您在没有 `settings.gradle` 文件的项目中执行 Gradle，则 Gradle 会通过以下方式查找 `settings.gradle`文件：

* 它在父目录中查找 `settings.gradle`
* 如果未找到，则该构建将作为单个项目构建执行。
* 如果找到 `settings.gradle` 文件，Gradle 将检查当前项目是否属于找到的 `settings.gradle` 文件中定义的多项目层次结构的一部分。 如果不是，则将构建作为单个项目构建执行。 否则，将执行多项目构建。

这种行为的目的是什么？ Gradle需要确定您所在的项目是否是多项目构建的子项目。 当然，如果它是子项目，则仅构建子项目及其从属项目，但是Gradle需要为整个多项目构建创建构建配置（请参阅 <<multi_project_configuration_and_execution.adoc#configuration_and_execution,Configuration and Execution>>）。
如果当前项目包含 `settings.gradle`  文件，则该构建始终按以下方式执行：

* 如果 `settings.gradle` 文件未定义多项目层次结构，则为单个项目构建
* 如果 `settings.gradle` 文件确实定义了多项目层次结构，则为多项目构建。

自动搜索 `settings.gradle` 文件仅适用于具有默认项目布局的多项目构建，其中项目路径与磁盘上的物理子项目布局匹配。 Gradle 支持多项目构建的任意物理布局，但是对于此类任意布局，您需要从设置文件所在的目录执行构建。
有关如何从根目录运行部分构建的信息，请参阅  <<intro_multi_project_builds.adoc#sec:executing_tasks_by_fully_qualified_name,按任务的完全限定名称执行任务>>。

Gradle 为参与构建的每个项目创建一个Project对象。 对于多项目构建，这些是Settings对象中指定的项目（加上根项目）。 默认情况下，每个项目对象的名称都等于其顶级目录的名称，除根项目外的每个项目都有一个父项目。 任何项目都可以有子项目。

[[sec:configuration_and_execution_of_a_single_project_build]]
== 单个项目构建的配置和执行

对于单个项目构建，初始化后阶段的工作流程非常简单。 将针对初始化阶段创建的项目对象执行构建脚本。 然后Gradle查找名称与作为命令行参数传递的名称相同的任务。 如果存在这些任务名称，则会按照传递它们的顺序将它们作为单独的版本执行。 在 <<multi_project_configuration_and_execution.adoc#configuration_and_execution,配置和执行>>中讨论了多项目构建的配置和执行。

[[build_lifecycle_events]]
== 响应构建脚本中的生命周期

随着构建在生命周期中的进展，您的构建脚本可以接收通知。 这些通知通常采用两种形式：您可以实现特定的侦听器接口，也可以提供一个闭包以在触发通知时执行。 下面的示例使用闭包。 有关如何使用侦听器接口的详细信息，请参阅API文档。

[[sec:project_evaluation]]
=== 项目评估

您可以在评估项目之前和之后立即收到通知。 一旦构建脚本中的所有定义均已应用，这可用于执行其他配置，或用于某些自定义日志记录或性能分析。

下面的示例将 `test` 任务添加到  `hasTests`  属性值为 `true` 的每个项目中。

.Adding of test task to each project which has certain property set
====
include::{snippets-dir}/buildlifecycle/projectEvaluateEvents/groovy/build.gradle[tags=after-evaluate]
include::{snippets-dir}/buildlifecycle/projectEvaluateEvents/groovy/project-a.gradle[]
include::{snippets-dir}/buildlifecycle/projectEvaluateEvents/kotlin/build.gradle.kts[tags=after-evaluate]
include::{snippets-dir}/buildlifecycle/projectEvaluateEvents/kotlin/project-a.gradle.kts[]
====

.`gradle -q test` 的输出
----
> gradle -q test
include::{snippets-dir}/buildlifecycle/projectEvaluateEvents/tests/projectEvaluateEvents.out[]
----

本示例使用 `Project.afterEvaluate()` 方法添加一个闭包，该闭包在评估项目后执行。

评估任何项目时，也可能会收到通知。 本示例对项目评估执行一些自定义日志记录。 请注意，无论项目评估成功还是失败，都将收到  `afterProject` 通知。

.Notifications
====
include::{snippets-dir}/buildlifecycle/buildProjectEvaluateEvents/groovy/build.gradle[tags=evaluate-events]
include::{snippets-dir}/buildlifecycle/buildProjectEvaluateEvents/kotlin/build.gradle.kts[tags=evaluate-events]
====

==== **`gradle -q test`** 的输出
[source.multi-language-sample,groovy]
----
> gradle -q test
include::{snippets-dir}/buildlifecycle/buildProjectEvaluateEvents/tests-groovy/buildProjectEvaluateEvents.groovy.out[]
----
[source.multi-language-sample,kotlin]
----
> gradle -q test
include::{snippets-dir}/buildlifecycle/buildProjectEvaluateEvents/tests-kotlin/buildProjectEvaluateEvents.kotlin.out[]
----

您还可以向 link:{groovyDslPath}/org.gradle.api.invocation.Gradle.html[Gradle] 添加 link:{javadocPath}/org/gradle/api/ProjectEvaluationListener.html[ProjectEvaluationListener] 来接收这些事件。

[[sec:task_creation]]
=== 创建任务  

将任务添加到项目后，您会立即收到通知。 在构建文件中使任务可用之前，这可用于设置一些默认值或添加行为。

下面的示例在创建每个任务时设置其 `srcDir` 属性。

.Setting of certain property to all tasks
====
include::{snippets-dir}/buildlifecycle/taskCreationEvents/groovy/build.gradle[]
include::{snippets-dir}/buildlifecycle/taskCreationEvents/kotlin/build.gradle.kts[]
====

.**`gradle -q a`** 的输出
----
> gradle -q a
include::{snippets-dir}/buildlifecycle/taskCreationEvents/tests/taskCreationEvents.out[]
----

您还可以将 link:{javadocPath}/org/gradle/api/Action.html[Action] 添加到 link:{javadocPath}/org/gradle/api/tasks/TaskContainer.html[TaskContainer] 以接收这些事件。

[[sec:task_execution_graph_ready]]
=== 任务执行图就绪

填充任务执行图后，您会立即收到通知（请参阅 <<tutorial_using_tasks.adoc#configure-by-dag,Configure by DAG>>）。 

您还可以将 link:{javadocPath}/org/gradle/api/execution/TaskExecutionGraphListener.html[TaskExecutionGraphListener] 添加到 link:{javadocPath}/org/gradle/api/execution/TaskExecutionGraph.html[TaskExecutionGraph] 来接收这些事件。

[[sec:task_execution]]
=== Task 执行

您可以在执行任何任务之前和之后立即收到通知。

下面的示例记录每个任务执行的开始和结束。 请注意，无论任务是成功完成还是因异常而失败，都会收到 `afterTask` 通知。

.Logging of start and end of each task execution
====
include::{snippets-dir}/buildlifecycle/taskExecutionEvents/groovy/build.gradle[]
include::{snippets-dir}/buildlifecycle/taskExecutionEvents/kotlin/build.gradle.kts[]
====

==== **`gradle -q broken`** 的输出
[source.multi-language-sample,groovy]
----
> gradle -q broken
include::{snippets-dir}/buildlifecycle/taskExecutionEvents/tests-groovy/taskExecutionEvents.groovy.out[]
----
[source.multi-language-sample,kotlin]
----
> gradle -q broken
include::{snippets-dir}/buildlifecycle/taskExecutionEvents/tests-kotlin/taskExecutionEvents.kotlin.out[]
----

您还可以对 link:{javadocPath}/org/gradle/api/execution/TaskExecutionGraph.html[TaskExecutionGraph] 使用 link:{javadocPath}/org/gradle/api/execution/TaskExecutionListener.html[TaskExecutionListener] 来接收这些事件。
