// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[logging]]
= 日志

日志是构建工具的主要 'UI'。 如果太冗长，则很容易掩盖真正的警告和问题。 另一方面，您需要相关信息来确定是否出错。 Gradle 定义了 6 个日志级别，如 <<#logLevels,日志级别>> 所示。
除了通常可能看到的级别以外，还有两种特定于 Gradle 的日志级别。 这些级别是 QUIET 和 LIFECYCLE。 后者是默认设置，用于报告构建进度。

[[logLevels]]
== 日志级别

[horizontal]
ERROR:: 错误信息
QUIET:: 重要信息
WARNING:: 警告信息
LIFECYCLE:: 进度信息
INFO:: 详情信息
DEBUG:: 调试信息

[NOTE]
====

无论使用什么日志级别，都会显示控制台的丰富组件（构建状态和正在进行的工作区域）。在 Gradle 4.0 之前，这些丰富的组件仅在日志级别 LIFECYCLE 或更低级别显示。

====


[[sec:choosing_a_log_level]]
== 选择一个日志级别

您可以使用 <<#logLevelCommandLineOptions, 日志级别的命令行选项>> 来打开或关闭不同的日志级别。 您还可以使用 `gradle.properties` 配置日志级别，请参阅 <<build_environment.adoc#sec:gradle_configuration_properties,Gradle 属性>>。
在 <<#stacktraces,Stacktrace 命令行选项>> 中，您会找到影响 stacktrace 日志记录的命令行开关。

[[logLevelCommandLineOptions]]
.日志级别的命令行选项
[%header%autowidth,compact]
|===
| 选项 | 输出日志级别
|  | LIFECYCLE 级别及更高
| `-q` 或 `--quiet` | QUIET 级别及更高
| `-w` 或 `--warn` | WARN 级别及更高
| `-i` 或 `--info` | INFO 级别及更高
| `-d` 或 `--debug` | DEBUG 级别及更高 (即所有日志消息)
|===

[CAUTION]
====

`DEBUG` 日志级别可以 <<#sec:debug_security, 将安全性敏感信息公开给控制台>>。

====

[[stacktraces]]

=== Stacktrace 命令行选项

`-s` 或 `--stacktrace`::
打印出 stacktraces 的堆栈跟踪。 我们建议在整个堆栈跟踪中使用此方法。 Groovy 完整的堆栈跟踪非常冗长（由于底层的动态调用机制。但是，它们通常不包含有关代码中发生了什么错误的相关信息。）此选项为过时警告呈现堆栈跟踪。

`-S` 或 `--full-stacktrace`::
完整的堆栈跟踪信息将被打印出来。此选项为过时警告呈现堆栈跟踪。

&lt;No stacktrace options&gt;::
如果发生构建错误（例如，编译错误），则不会将任何堆栈跟踪记录打印到控制台。仅在内部异常的情况下，才会打印堆栈跟踪。如果选择了 `DEBUG` 日志级别，则始终打印被截断的堆栈跟踪

[[sec:debug_security]]
== 记录敏感信息

以 `DEBUG`  日志级别运行Gradle可以向控制台公开安全敏感信息并生成日志。 

此信息可以包括但不限于：

- 环境变量
- Private repository credentials
- Build cache & Gradle Enterprise Credentials
- https://plugins.gradle.org/[Plugin Portal] publishing credentials

在公共连续集成服务上运行时，不应使用DEBUG日志级别。 公共持续集成服务的构建日志在世界范围内可见，并且可以公开此敏感信息。 根据组织的威胁模型，在私有CI中记录敏感凭据也可能是一个漏洞。 请与您组织的安全团队讨论此事。

一些CI提供程序试图从日志中清除敏感的凭证。 但是，这将是不完善的，并且通常仅清除预先配置的机密的完全匹配项。

如果您认为Gradle插件可能会公开敏感信息，请联系 mailto:security@gradle.com[security@gradle.com] 以获取公开帮助。

[[sec:sending_your_own_log_messages]]
== 编写自己的日志消息

记录构建文件的一个简单选项是将消息写入标准输出。 Gradle 在 `QUIET` 日志级别将任何写入标准输出的内容重定向到其日志记录系统。

.Using stdout to write log messages
====
include::{snippets-dir}/tutorial/logging/groovy/build.gradle[tags=use-println]
include::{snippets-dir}/tutorial/logging/kotlin/build.gradle.kts[tags=use-println]
====

Gradle还为构建脚本提供了 `logger` 属性，该脚本是 link:{javadocPath}/org/gradle/api/logging/Logger.html[Logger] 的实例。 该接口扩展了 SLF4J Logger 接口，并向其中添加了一些 Gradle 特定的方法。 以下是在构建脚本中如何使用它的示例：

.Writing your own log messages
====
include::{snippets-dir}/tutorial/logging/groovy/build.gradle[tags=use-logger]
include::{snippets-dir}/tutorial/logging/kotlin/build.gradle.kts[tags=use-logger]
====

使用 link:https://www.slf4j.org/manual.html#typical_usage[典型的SLF4J模式] 将占位符替换为实际值，作为日志消息的一部分。

.Writing a log message with placeholder
====
include::{snippets-dir}/tutorial/logging/groovy/build.gradle[tags=use-logger-placeholder]
include::{snippets-dir}/tutorial/logging/kotlin/build.gradle.kts[tags=use-logger-placeholder]
====

您还可以从构建中使用的其他类（例如，`buildSrc` 目录中的类）中插入 Gradle 的日志系统。 只需使用 SLF4J 记录器。 您可以使用与在构建脚本中使用提供的记录器相同的方式来使用此记录器。

.Using SLF4J to write log messages
====
include::{snippets-dir}/tutorial/logging/groovy/build.gradle[tags=use-slf4j]
include::{snippets-dir}/tutorial/logging/kotlin/build.gradle.kts[tags=use-slf4j]
====

[[sec:external_tools]]
== 从外部工具和库记录

在内部，Gradle 使用 Ant 和 Ivy。 两者都有自己的日志系统。 Gradle 将其日志输出重定向到 Gradle 日志系统。 从 Ant/Ivy 日志级别到 Gradle 日志级别有 1:1 映射，但 Ant/Ivy `TRACE` 日志级别除外，后者已映射到 Gradle `DEBUG` 日志级别。 这意味着默认的 Gradle 日志级别将不会显示任何 Ant/Ivy 输出，除非它是错误或警告。

有许多工具仍然使用标准输出进行日志记录。 默认情况下，Gradle 将标准输出重定向到 `QUIET` 日志级别，并将标准错误重定向到ERROR级别。 此行为是可配置的。 该项目对象提供一个 link:{javadocPath}/org/gradle/api/logging/LoggingManager.html[LoggingManager]，它允许您更改在评估构建脚本时将标准输出或错误重定向到的日志级别

.Configuring standard output capture
====
include::{snippets-dir}/tutorial/logging/groovy/build.gradle[tags=capture-stdout]
include::{snippets-dir}/tutorial/logging/kotlin/build.gradle.kts[tags=capture-stdout]
====

为了在任务执行过程中更改标准输出或错误的日志级别，任务还提供了 link:{javadocPath}/org/gradle/api/logging/LoggingManager.html[LoggingManager]。

.Configuring standard output capture for a task
====
include::{snippets-dir}/tutorial/logging/groovy/build.gradle[tags=task-capture-stdout]
include::{snippets-dir}/tutorial/logging/kotlin/build.gradle.kts[tags=task-capture-stdout]
====

Gradle 还提供与 Java Util 日志记录，Jakarta Commons 日志记录和 Log4j 日志记录工具包的集成。您的构建类使用这些日志记录工具包编写的所有日志消息都将被重定向到 Gradle 的日志记录系统。

[[sec:changing_what_gradle_logs]]
== 更改 Gradle 日志

您可以用自己的 Gradle 替换许多 Logging UI。 例如，如果您想以某种方式自定义 UI，则可以执行此操作-记录更多或更少的信息，或更改格式。 您可以使用 link:{groovyDslPath}/org.gradle.api.invocation.Gradle.html#org.gradle.api.invocation.Gradle:useLogger(java.lang.Object)[Gradle.useLogger(java.lang.Object)] 方法替换日志记录。 可通过构建脚本或初始化脚本或通过嵌入API进行访问。 请注意，这将完全禁用Gradle的默认输出。 下面是一个示例初始化脚本，该脚本更改了记录任务执行和构建完成的方式。

.Customizing what Gradle logs
====
include::{snippets-dir}/initScripts/customLogger/groovy/customLogger.init.gradle[]
include::{snippets-dir}/initScripts/customLogger/kotlin/customLogger.init.gradle.kts[]
====

[.multi-language-text.lang-groovy]
----
$ gradle -I customLogger.init.gradle build
include::{snippets-dir}/initScripts/customLogger/tests/customLogger.out[]
----
[.multi-language-text.lang-kotlin]
----
$ gradle -I customLogger.init.gradle.kts build
include::{snippets-dir}/initScripts/customLogger/tests/customLogger.out[]
----

您的 logger 可以实现下面列出的任何监听器接口。 注册记录器时，只会替换其实现的接口的记录。 其他接口的日志保持不变。 您可以在 <<build_lifecycle.adoc#build_lifecycle_events,构建生命周期事件>> 中找到有关监听器接口的更多信息。

* link:{javadocPath}/org/gradle/BuildListener.html[BuildListener]
* link:{javadocPath}/org/gradle/api/ProjectEvaluationListener.html[ProjectEvaluationListener]
* link:{javadocPath}/org/gradle/api/execution/TaskExecutionGraphListener.html[TaskExecutionGraphListener]
* link:{javadocPath}/org/gradle/api/execution/TaskExecutionListener.html[TaskExecutionListener]
* link:{javadocPath}/org/gradle/api/execution/TaskActionListener.html[TaskActionListener]
