// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[test_kit]]
= 使用 TestKit 测试构建逻辑

Gradle TestKit (也就是 TestKit) 是一个库,可帮助测试 Gradle 插件并一般构建逻辑. 目前,它专注于功能测试. 也就是说,通过将其作为程序执行的构建的一部分进行测试来测试构建逻辑.
随着时间的流逝,TestKit 可能会扩展以方便其他类型的测试.

[[sec:testkit_usage]]
== 使用

要使用 TestKit,请在插件的版本中包含以下内容:

.Declaring the TestKit dependency
====
include::{snippets-dir}/testKit/junitQuickstart/groovy/build.gradle[tags=declare-gradle-testkit-dependency]
include::{snippets-dir}/testKit/junitQuickstart/kotlin/build.gradle.kts[tags=declare-gradle-testkit-dependency]
====

`gradleTestKit()` 包含 TestKit 的类以及 <<third_party_integration.adoc#embedding,Gradle Tooling API client>>. 它不包括 JUnit,http://junit.org[JUnit], http://testng.org[TestNG]  或任何其他测试执行框架的版本. 必须明确声明这种依赖性.

.Declaring the JUnit dependency
====
include::{snippets-dir}/testKit/junitQuickstart/groovy/build.gradle[tags=declare-junit-dependency]
include::{snippets-dir}/testKit/junitQuickstart/kotlin/build.gradle.kts[tags=declare-junit-dependency]
====

[[sec:functional_testing_with_the_gradle_runner]]
== 使用 Gradle Runner 进行功能测试

link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html[GradleRunner] 有助于以编程方式执行 Gradle 构建并检查结果.

可以 (例如以编程方式或从模板) 创建人为构建的练习,该练习可以执行 "logic under test”. 然后可以潜在地以多种方式 (例如,任务和参数的不同组合) 执行该构建. 然后可以通过断言以下内容 (可能组合使用) 来验证逻辑的正确性:

* The build's output;
* The build's logging (i.e. console output);
* The set of tasks executed by the build and their results (e.g. FAILED, UP-TO-DATE etc.).

在创建并配置了Runner实例之后,可以根据预期结果通过 link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html#build--[GradleRunner.build()] 或 link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html#buildAndFail--[GradleRunner.buildAndFail()] 方法执行构建.

以下内容演示了Java JUnit 测试中 GradleRunner 的用法

=== Example: Using GradleRunner with Java and JUnit

[source,java,indent=0]
.BuildLogicFunctionalTest.java
----
include::{snippets-dir}/testKit/junitQuickstart/groovy/src/test/java/org/gradle/sample/BuildLogicFunctionalTest.java[tag=functional-test-junit]
----

以下内容演示了在 Kotlin JUnit 测试中 Gradle runner 的用法:

=== Example: Using GradleRunner with Kotlin and JUnit

[source,kotlin,indent=0]
.BuildLogicFunctionalTest.kt
----
include::{snippets-dir}/testKit/junitQuickstart/kotlin/src/test/kotlin/org/gradle/sample/BuildLogicFunctionalTest.kt[tag=functional-test-junit]
----

可以使用任何测试执行框架.

由于 Gradle 构建脚本也可以用 Groovy 编程语言编写,因此用 Groovy 编写 Gradle 功能测试通常是一种有效的选择. 此外,建议使用 (基于 Groovy 的) https://code.google.com/p/spock/[Spock 测试执行框架] ,因为它比 JUnit 的使用具有许多引人注目的功能.

以下内容演示了Groovy Spock 测试中 Gradle runner 的用法:

=== Example: Using GradleRunner with Groovy and Spock

[source,groovy,indent=0]
.BuildLogicFunctionalTest.groovy
----
include::{snippets-dir}/testKit/spockQuickstart/groovy/src/test/groovy/org/gradle/sample/BuildLogicFunctionalTest.groovy[tag=functional-test-spock]
----

实施任何自定义构建逻辑 (如插件和任务类型) 通常是一种惯例,该逻辑本质上比独立项目中的外部类复杂. 这种方法背后的主要驱动力是将编译后的代码捆绑到一个 JAR 文件中,将其发布到二进制存储库中,并在各个项目中重复使用.

[[sub:test-kit-classpath-injection]]
== Getting the plugin-under-test into the test build

GradleRunner使用  <<third_party_integration.adoc#embedding,Tooling API>>  执行构建. 这意味着构建是在单独的过程中执行的 (即,执行测试的过程不是同一过程) . 因此,测试版本与测试过程不会共享相同的类路径或类加载器,并且测试代码也不能隐式地用于测试版本.

从 2.13 版本开始,Gradle 提供了一种常规机制将被测代码注入测试版本中


[[sub:test-kit-automatic-classpath-injection]]
=== 使用 Java Gradle 插件开发插件自动注入

<<java_gradle_plugin.adoc#java_gradle_plugin,Java Gradle Plugin development plugin>> 可用于协助 Gradle 插件的开发. 从 Gradle 2.13 版本开始,该插件提供了与 TestKit 的直接集成.
当应用于项目时,该插件会自动将 `gradleTestKit()` 依赖添加到测试编译配置中. 此外,它会自动为测试中的代码生成类路径,并通过 link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html#withPluginClasspath--[GradleRunner.withPluginClasspath()] 为用户创建的任何 `GradleRunner`  实例注入该类路径. 需要特别注意的是,该机制目前仅在使用 <<plugins.adoc#sec:plugins_block,plugins DSL>> 应用被测插件时有效. 如果 <<#sub:gradle-runner-gradle-version,目标 Gradle 版本>>是 2.8 之前的版本,则不会执行自动插件类路径注入.

该插件使用以下约定来应用 TestKit 依赖并注入类路径:

* 包含正在测试的代码的源集: `sourceSets.main`
* 用于注入插件类路径的源集: `sourceSets.test`

这些约定中的任何一个都可以在类 link:{javadocPath}/org/gradle/plugin/devel/GradlePluginDevelopmentExtension.html[GradlePluginDevelopmentExtension] 的帮助下进行重新配置.

以下基于 Groovy 的示例演示了如何使用 Java Gradle Plugin Development plugin 应用的标准约定自动注入插件类路径.

Any of these conventions can be reconfigured with the help of the class 
.

The following Groovy-based sample demonstrates how to automatically inject the plugin classpath by using the standard conventions applied by the Java Gradle Plugin Development plugin.

.Using the Java Gradle Development plugin for generating the plugin metadata
====
include::{snippets-dir}/testKit/automaticClasspathInjectionQuickstart/groovy/build.gradle[tags=automatic-classpath]
include::{snippets-dir}/testKit/automaticClasspathInjectionQuickstart/kotlin/build.gradle.kts[tags=automatic-classpath]
====


=== Example: Automatically injecting the code under test classes into test builds

[source,groovy,indent=0]
.src/test/groovy/org/gradle/sample/BuildLogicFunctionalTest.groovy
----
include::{snippets-dir}/testKit/automaticClasspathInjectionQuickstart/groovy/src/test/groovy/org/gradle/sample/BuildLogicFunctionalTest.groovy[tag=functional-test-classpath-setup-automatic]
----

以下构建脚本演示了如何为使用自定义 `Test`  源集的项目重新配置 Java Gradle Plugin Development 插件提供的约定.

.Reconfiguring the classpath generation conventions of the Java Gradle Development plugin
====
include::{snippets-dir}/testKit/automaticClasspathInjectionCustomTestSourceSet/groovy/build.gradle[tags=custom-test-source-set]
include::{snippets-dir}/testKit/automaticClasspathInjectionCustomTestSourceSet/kotlin/build.gradle.kts[tags=custom-test-source-set]
====

[[sec:working_with_gradle_versions_prior_to_213]]
=== 使用 2.13 之前的 Gradle 版本

对于Gradle的早期版本 (2.13之前的版本) ,可以通过一些额外的配置来手动使被测代码可用. 下面的示例演示如何让生成的文件包含被测代码的实现类路径,并使其在测试运行时可用.

.Making the code under test classpath available to the tests
====
include::{snippets-dir}/testKit/manualClasspathInjection/groovy/build.gradle[tags=test-logic-classpath]
include::{snippets-dir}/testKit/manualClasspathInjection/kotlin/build.gradle.kts[tags=test-logic-classpath]
====

然后,测试可以读取该值,并使用方法 link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html#withPluginClasspath-java.lang.Iterable-[GradleRunner.withPluginClasspath(java.lang.Iterable)] 将类路径注入测试版本.
然后可以使用该类路径通过插件DSL (请参阅 <<plugins.adoc#plugins,Plugins>>) 在测试版本中定位插件. 通过插件 DSL 应用插件需要定义插件标识符. 以下是在 Spock Framework `setup()` 方法中执行此操作的示例 (在 Groovy 中) ,该方法类似于 JUnit `@Before` 方法.

=== Example: Injecting the code under test classes into test builds

[source.multi-language-sample,groovy]
.src/test/groovy/org/gradle/sample/BuildLogicFunctionalTest.groovy
----
include::{snippets-dir}/testKit/manualClasspathInjection/groovy/src/test/groovy/org/gradle/sample/BuildLogicFunctionalTest.groovy[tag=functional-test-classpath-setup]
----

当作为 Gradle 构建的一部分执行功能测试时,此方法效果很好. 从 IDE 执行功能测试时,还有一些额外的注意事项. 即,类路径清单文件指向 Gradle 而不是 IDE 生成的类文件等.
这意味着在更改被测代码的源代码之后,必须由Gradle重新编译源代码. 同样,如果被测代码的有效类路径发生变化,则必须重新生成清单. 无论哪种情况,执行构建的testClasses任务都将确保一切都是最新的.

一些 IDE 提供了一个方便的选项,可以将 "test classpath generation and execution" 委派给构建. 在 IntelliJ 中,您可以在 Preferences... > Build, Execution, Deployment > Build Tools > Gradle > Runner > Delegate IDE build/run  下找到该选项. 请查阅 IDE 的文档以获取更多信息.

[[sec:working_with_gradle_versions_prior_to_28]]
=== 使用 2.8 之前的 Gradle 版本

当使用早于 2.8 的 Gradle 版本执行构建时, link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html#withPluginClasspath-java.lang.Iterable-[GradleRunner.withPluginClasspath(java.lang.Iterable)] 方法将不起作用 (请参阅 <<#sub:gradle-runner-gradle-version,The version used to test>>) ,因为在此类 Gradle 版本中不支持此功能.

相反,必须通过构建脚本本身注入代码. 以下示例演示了如何完成此操作

=== Example: Injecting the code under test classes into test builds for Gradle versions prior to 2.8

[source.multi-language-sample,groovy]
.src/test/groovy/org/gradle/sample/BuildLogicFunctionalTest.groovy
----
include::{snippets-dir}/testKit/manualClasspathInjection/groovy/src/test/groovy/org/gradle/sample/BuildLogicFunctionalTest.groovy[tag=functional-test-classpath-setup-older-gradle]
----


[[sec:controlling_the_build_environment]]
== 控制构建环境

runner 通过在 JVM 的 temp 目录 (即 `java.io.tmpdir` 系统属性指定的位置,通常为 `/tmp`) 内的目录中指定专用的 "working directory",在隔离的环境中执行测试构建. 默认的 Gradle 用户主目录中的任何配置 (例如
`~/.gradle/gradle.properties`) 均不用于测试执行. TestKit 没有公开对环境的所有方面进行细粒度控制的机制 (例如 JDK) . 未来版本的 TestKit 将提供改进的配置选项.

TestKit 使用专用的守护程序进程,这些进程在测试执行后会自动关闭.

[[sub:gradle-runner-gradle-version]]
== 用于测试的 Gradle 版本

Gradle runner 需要 Gradle 发行版才能执行构建. TestKit 并不依赖于 Gradle 的所有实现.

默认情况下,运行程序将尝试根据加载 `GradleRunner` 类的位置查找 Gradle 发行版. 也就是说,期望该类是从 Gradle 发行版加载的,就像使用 `gradleTestKit()` 依赖声明时一样.

当将 runner 用作 Gradle 执行的测试的一部分 (例如执行插件项目的 `test` 任务) 时,跑步者将使用与执行测试相同的发行版. 当将运行程序用作由 IDE 执行的测试的一部分时,
将使用与导入项目时相同的 Gradle distribution 版本. 这意味着该插件将使用与其构建时相同的 Gradle 版本进行有效测试.

另外,可以通过以下任何 `GradleRunner` 方法指定要使用的 Gradle 的不同版本和特定版本:

* link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html#withGradleVersion-java.lang.String-[GradleRunner.withGradleVersion(java.lang.String)]
* link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html#withGradleInstallation-java.io.File-[GradleRunner.withGradleInstallation(java.io.File)]
* link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html#withGradleDistribution-java.net.URI-[GradleRunner.withGradleDistribution(java.net.URI)]

它可以潜在地用于跨 Gradle 版本测试构建逻辑. 以下内容演示了编写为 Groovy Spock 测试的跨版本兼容性测试:

=== Example: Specifying a Gradle version for test execution

[source,groovy,indent=0]
.BuildLogicFunctionalTest.groovy
----
include::{snippets-dir}/testKit/gradleVersion/groovy/src/test/groovy/org/gradle/sample/BuildLogicFunctionalTest.groovy[tag=functional-test-spock-gradle-version]
----

[[sub:test-kit-compatibility]]
=== 使用不同的 Gradle 版本进行测试时的功能支持
 
可以使用 GradleRunner 在 Gradle 1.0 及更高版本中执行构建. 但是,早期版本不支持某些 runner 功能. 在这种情况下,runner 在尝试使用功能时会抛出异常.

下表列出了对使用的 Gradle 版本敏感的功能.

.Gradle version compatibility
[%header%autowidth,compact]
|===
| Feature | Minimum Version | Description

| Inspecting executed tasks
| 2.5
| Inspecting the executed tasks, using link:{javadocPath}/org/gradle/testkit/runner/BuildResult.html#getTasks--[BuildResult.getTasks()] and similar methods.

| <<#sub:test-kit-classpath-injection,Plugin classpath injection>>
| 2.8
| Injecting the code under test vialink:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html#withPluginClasspath-java.lang.Iterable-[GradleRunner.withPluginClasspath(java.lang.Iterable)].

| <<#sub:test-kit-debug,Inspecting build output in debug mode>>
| 2.9
| Inspecting the build's text output when run in debug mode, using link:{javadocPath}/org/gradle/testkit/runner/BuildResult.html#getOutput--[BuildResult.getOutput()].

| <<#sub:test-kit-automatic-classpath-injection,Automatic plugin classpath injection>>
| 2.13
| Injecting the code under test automatically via link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html#withPluginClasspath--[GradleRunner.withPluginClasspath()] by applying the Java Gradle Plugin Development plugin.

| Setting environment variables to be used by the build.
| 3.5
| The Gradle Tooling API only supports setting environment variables in later versions.
|===


[[sub:test-kit-debug]]
== 调试构建逻辑

runner 使用 <<third_party_integration.adoc#embedding,Tooling API>> 执行构建. 这意味着构建是在单独的过程中执行的 (即,执行测试的过程不是同一过程) . 因此,以调试方式执行测试不允许您调试调试逻辑. 在 IDE 中设置的任何断点都不会因测试版本执行的代码而跳闸.

TestKit 提供了两种不同的方式来启用调试模式:

* 使用 GradleRunner 将 JVM 的 "`org.gradle.testkit.debug`”  系统属性设置为 `true` (即,不是由运行程序执行构建) ;

* 调用 link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html#withDebug-boolean-[GradleRunner.withDebug(boolean)] 方法.

当需要启用调试支持而不对流道配置进行临时更改时,可以使用系统属性方法. 大多数 IDE 提供了设置 JVM 系统属性以执行测试的功能,并且可以使用此功能来设置此系统属性.

[[sub:test-kit-build-cache]]
== 使用构建缓存进行测试

要在测试中启用 <<build_cache.adoc#build_cache,Build Cache>> ,可以将 `--build-cache` 参数传递给 link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html[GradleRunner] 或使用 <<build_cache.adoc#sec:build_cache_enable,Enable the build cache>> 中所述的其他方法之一.
然后,当您缓存插件的自定义任务时,您可以检查任务结果 link:{javadocPath}/org/gradle/testkit/runner/TaskOutcome.html#FROM_CACHE[TaskOutcome.FROM_CACHE]. 此结果仅对 Gradle 3.5 及更高版本有效.

=== Example: Testing cacheable tasks

[source,groovy,indent=0]
.BuildLogicFunctionalTest.groovy
----
include::{snippets-dir}/testKit/testKitFunctionalTestSpockBuildCache/groovy/src/test/groovy/org/gradle/sample/BuildLogicFunctionalTest.groovy[tag=functional-test-build-cache]
----

请注意,TestKit 在测试之间重用了 Gradle 用户主目录 (请参阅 link:{javadocPath}/org/gradle/testkit/runner/GradleRunner.html#withTestKitDir-java.io.File-[GradleRunner.withTestKitDir(java.io.File)]) ,其中包含本地构建缓存的默认位置. 为了使用构建缓存进行测试,应该在测试之间清理构建缓存目录. 完成此操作的最简单方法是将本地构建缓存配置为使用临时目录.

=== Example: Clean build cache between tests

[source,groovy,indent=0]
.BuildLogicFunctionalTest.groovy
----
include::{snippets-dir}/testKit/testKitFunctionalTestSpockBuildCache/groovy/src/test/groovy/org/gradle/sample/BuildLogicFunctionalTest.groovy[tag=clean-build-cache]
----
