[[tutorial_using_tasks]]
= 构建脚本基础

本章向您介绍编写 Gradle 构建脚本的基础. 以 toy 示例来解释 Gradle 的基本功能，有助于理解基本概念。
特别是如果您从 Ant 等其他构建工具迁移到 Gradle， 并希望了解差异和优势。

但是，要开始使用标准项目设置，您可能不需要详细了解这些概念。 相反，您可以通过我们的 <<getting_started.adoc#try_gradle,step-by-step samples>> 进行快速动手介绍。

[[sec:projects_and_tasks]]
== Projects, plugins  和 tasks

每一个 Gradle 构建都由一个或多个 _projects_ 组成。 一个项目代表什么取决于你用 Gradle 做什么。 例如，一个项目可能代表一个库 JAR 或一个 Web 应用程序。 它也可能代表一个发布的 ZIP 压缩包。
一个 project 不一定代表要构建的事物. 它可能表示要完成的事情，例如将应用程序部署到预发布或生产环境。 不要担心暂时看不懂这些。 Gradle 的 build-by-convention（合约构建） 可以让你来具体定义一个 project 到底该做什么。

Gradle 在一个项目上可以做的工作是由一个或多个 _tasks_ 定义的。 任务代表构建执行的一些原子工作。 这可能是编译一些类、创建 JAR、生成 Javadoc 或将一些存档发布到存储库。

通常，任务由 <<plugins.adoc#sec:plugins_block,applying a plugin>> 提供，因此您不必自己定义它们。 尽管如此，为了让您了解什么是任务，我们将在本章中研究如何在一个项目构建中定义一些简单的任务。

[[sec:hello_world]]
== Hello world

[.multi-language-text.lang-groovy]
您可以使用 `gradle` 命令运行 `Gradle` 构建. `gradle` 命令在当前目录中查找一个名为 `build.gradle` 的文件.footnote:[用命令行开关可以更改此行为. See <<command_line_interface.adoc#command_line_interface,Command-Line Interface>>)] 我们将这个 `build.gradle` 文件称为构建脚本,尽管严格来说它是一个构建配置脚本,我们将在后面看到. 构建脚本定义项目及其任务.

[.multi-language-text.lang-groovy]
要尝试此操作,请创建以下名为 `build.gradle` 的构建脚本.

[.multi-language-text.lang-kotlin]
您可以使用 `gradle` 命令运行 Gradle 构建. `gradle` 命令在当前目录中查找一个名为 `build.gradle.kts` 的文件.footnote:[用命令行开关可以更改此行为. See <<command_line_interface.adoc#command_line_interface,Command-Line Interface>>)]  我们将这个 `build.gradle.kts` 文件称为构建脚本,尽管严格来说,它是一个构建配置脚本,

[.multi-language-text.lang-kotlin]
要尝试此操作,请创建以下名为 `build.gradle.kts` 的构建脚本.

.Your first build script
====
include::{snippets-dir}/tutorial/hello/groovy/build.gradle[]
include::{snippets-dir}/tutorial/hello/kotlin/build.gradle.kts[]
====

在命令行 shell 中,进入脚本所在的文件夹,并使用 `gradle -q hello` 执行构建脚本:

[TIP]
.`-q` 做什么?
====

本用户指南中的大多数示例都使用 `-q` 命令行选项运行. 这样可以取消 Gradle 的日志消息,从而仅显示任务的输出. 这样可以使本用户指南中的示例输出更加清晰.
如果不想,则不需要使用此选项. 有关影响 Gradle 输出的命令行选项的更多详细信息,请参见 <<logging.adoc#logging,Logging>> 记录.
====

.Execution of a build script
====
. **`gradle -q hello`** 输出
----
> gradle -q hello
include::{snippets-dir}/tutorial/hello/tests/hello.out[]
----
====

这里发生了什么? 此构建脚本定义了一个名为 `hello` 的任务,并向其中添加了一个 action. 当您运行 `gradle hello` 时,Gradle 将执行 `hello` 任务,该任务又将执行您提供的 action. 该 action 只是一个包含一些要执行代码的块.

如果您认为这与 Ant 的 targets 相似,那是对的. Gradle 任务等效于 Ant targets,但正如您将看到的那样,它们的功能要强大得多. 我们使用了与 Ant 不同的术语 task,因为我们认为 _task_ 一词比 _target_ 一词更具表现力.
不幸的是,这会引起与 Ant 的术语冲突,因为 Ant 会调用其命令(例如 `javac` 或 `copy`)任务. 因此,当我们谈论任务时,我们总是指 Gradle 任务,它等同于 Ant 的目标. 如果我们谈论 Ant 任务(Ant命令),则明确地说出 _Ant task_.

[[sec:build_scripts_are_code]]
== 构建脚本代码

Gradle 的构建脚本为您提供了 Groovy 和 Kotlin 的全部功能.作为一个开胃菜,看看这个:

.Using Groovy or Kotlin in Gradle's tasks
====
include::{snippets-dir}/tutorial/upper/groovy/build.gradle[]
include::{snippets-dir}/tutorial/upper/kotlin/build.gradle.kts[]

.**`gradle -q upper`** 的输出
----
> gradle -q upper
include::{snippets-dir}/tutorial/upper/tests/upper.out[]
----
====

或者

.Using Groovy or Kotlin in Gradle's tasks
====
include::{snippets-dir}/tutorial/count/groovy/build.gradle[]
include::{snippets-dir}/tutorial/count/kotlin/build.gradle.kts[]

.**`gradle -q count`** 的输出
----
> gradle -q count
include::{snippets-dir}/tutorial/count/tests/count.out[]
----
====


[[sec:task_dependencies]]
== Task 依赖

您可能已经猜到了,您可以声明依赖于其他任务的任务.

.Declaration of task that depends on other task
====
include::{snippets-dir}/tutorial/intro/groovy/build.gradle[]
include::{snippets-dir}/tutorial/intro/kotlin/build.gradle.kts[]

.**`gradle -q intro`** 的输出
----
> gradle -q intro
include::{snippets-dir}/tutorial/intro/tests/intro.out[]
----
====

要添加依赖,不需要存在相应的任务.

.Lazy dependsOn - the other task does not exist (yet)
====
include::{snippets-dir}/tutorial/lazyDependsOn/groovy/build.gradle[]
include::{snippets-dir}/tutorial/lazyDependsOn/kotlin/build.gradle.kts[]

.**`gradle -q taskX`** 的输出
----
> gradle -q taskX
include::{snippets-dir}/tutorial/lazyDependsOn/tests/lazyDependsOn.out[]
----
====

可以在定义 `taskY` 之前声明 `taskX` 对 `taskY` 的依赖. 对于多项目构建, 在 <<more_about_tasks.adoc#sec:adding_dependencies_to_tasks,依赖添加到任务>>中将详细讨论任务依赖.

[[sec:dynamic_tasks]]
== 灵活的注册 tasks

Groovy 或 Kotlin 的功能可用于定义任务以外的其他功能.例如,您可以使用在一个循环中注册多个相同类型的任务。

.Felxible registration of a task
====
include::{snippets-dir}/tutorial/dynamic/groovy/build.gradle[]
include::{snippets-dir}/tutorial/dynamic/kotlin/build.gradle.kts[]

.**`gradle -q task1`** 输出
----
> gradle -q task1
include::{snippets-dir}/tutorial/dynamic/tests/dynamic.out[]
----
====


[[sec:manipulating_existing_tasks]]
== 处理现有任务

创建注册后,即可通过 API 对其进行访问.例如,您可以使用它在运行时为任务动态添加依赖.蚂蚁不允许这样的事情.

.Accessing a task via API - adding a dependency
====
include::{snippets-dir}/tutorial/dynamicDepends/groovy/build.gradle[]
include::{snippets-dir}/tutorial/dynamicDepends/kotlin/build.gradle.kts[]

.**`gradle -q task0`** 输出
----
> gradle -q task0
include::{snippets-dir}/tutorial/dynamicDepends/tests/dynamicDepends.out[]
----
====

或者,您可以将行为添加到现有任务.

.Accessing a task via API - adding behaviour
====
include::{snippets-dir}/tutorial/helloEnhanced/groovy/build.gradle[]
include::{snippets-dir}/tutorial/helloEnhanced/kotlin/build.gradle.kts[]

.**`gradle -q hello`** 的输出
----
> gradle -q hello
include::{snippets-dir}/tutorial/helloEnhanced/tests/helloEnhanced.out[]
----
====

可以多次执行 `doFirst` 和 `doLast` 调用. 他们将操作添加到任务操作列表的开头或结尾. 执行任务时,将按顺序执行操作列表中的操作.

[[sec:using_ant_tasks_tutorial]]
== 使用 Ant Tasks

Ant tasks 是 Gradle 中的一等公民. 仅仅依靠 Groovy,Gradle 就可以为 An t任务提供出色的集成. Groovy 随附了出色的 AntBuilder. 与从 `build.xml` 文件使用 Ant 任务相比,使用 Gradle 中的 Ant 任务既方便又强大. 它也可以从Kotlin使用. 从下面的示例中,您可以学习如何执行Ant任务以及如何访问Ant属性:

.Using AntBuilder to execute ant.loadfile target
====
include::{snippets-dir}/tutorial/antLoadfile/groovy/build.gradle[]
include::{snippets-dir}/tutorial/antLoadfile/kotlin/build.gradle.kts[]

.**`gradle -q loadfile`** 输出
----
> gradle -q loadfile
include::{snippets-dir}/tutorial/antLoadfile/tests/antLoadfile.out[]
----
====

您可以在构建脚本中使用 <<ant.adoc#ant,Ant>> 进行更多操作.您可以在 Ant 中找到更多信息.

[[sec:using_methods]]
== 使用方法

Gradle 扩展了如何组织构建逻辑.上面示例中组织构建逻辑的第一级是提取方法.

.Using methods to organize your build logic
====
include::{snippets-dir}/tutorial/antLoadfileWithMethod/groovy/build.gradle[]
include::{snippets-dir}/tutorial/antLoadfileWithMethod/kotlin/build.gradle.kts[]

.**`gradle -q loadfile`** 输出
----
> gradle -q loadfile
include::{snippets-dir}/tutorial/antLoadfileWithMethod/tests/antLoadfileWithMethod.out[]
----
====

稍后您将看到,这些方法可以在多项目构建中的子项目之间共享. 如果您的构建逻辑变得更加复杂,Gradle 将为您提供其他非常方便的组织方式. 我们为此花了整整一章. 请参阅<<organizing_gradle_projects.adoc#organizing_gradle_projects,Organizing Gradle Projects>>.

[[sec:default_tasks]]
== 默认 tasks

如果未指定其他任务,则 Gradle 允许您定义一个或多个默认任务.

.Defining a default task
====
include::{snippets-dir}/tutorial/defaultTasks/groovy/build.gradle[]
include::{snippets-dir}/tutorial/defaultTasks/kotlin/build.gradle.kts[]

.**`gradle -q`** 输出
----
> gradle -q
include::{snippets-dir}/tutorial/defaultTasks/tests/defaultTasks.out[]
----
====

这相当于运行 `gradle clean run`. 在多项目构建中,每个子项目可以有其自己的特定默认任务. 如果子项目未指定默认任务,则使用父项目的默认任务(如果已定义).

[[configure-by-dag]]
== 通过 DAG 进行配置

如我们稍后详细描述(请参阅 <<build_lifecycle.adoc#build_lifecycle,Build Lifecycle>>),Gradle 具有配置阶段和执行阶段. 在配置阶段之后,Gradle 知道应该执行的所有任务. Gradle 为您提供了一个利用此信息的机会. 一个用例是检查发布任务是否在要执行的任务中. 以此为基础,您可以为某些变量分配不同的值.

在以下示例中, `distribution` 和 `release`  任务的执行导致  `version` 变量的值不同.

.Different outcomes of build depending on chosen tasks
====
include::{snippets-dir}/tutorial/configByDag/groovy/build.gradle[]
include::{snippets-dir}/tutorial/configByDag/kotlin/build.gradle.kts[]

.`gradle -q distribution` 的输出
----
> gradle -q distribution
include::{snippets-dir}/tutorial/configByDag/tests/configByDagNoRelease.out[]
----

.`gradle -q release` 的输出
----
> gradle -q release
include::{snippets-dir}/tutorial/configByDag/tests/configByDag.out[]
----
====

重要的是,在执行 release 任务之前,`whenReady`  会影响 release 任务.即使 release 任务不是主要任务(即传递给 `gradle` 命令的任务)也可以使用.

[NOTE]
====
此示例有效,因为仅在执行时读取  `version` 值. 在实际构建中使用类似的构造时,必须确保在配置过程中不会急切读取该值. 否则,您的构建可能会对配置和执行之间的属性使用不同的值.
====

[[sec:build_script_external_dependencies]]
== 构建脚本的外部依赖

NOTE: 建议不要直接操作脚本类路径，建议 <<plugins.adoc#,使用 plugins>> 操作他们自己的类路径。
对于自定义构建逻辑，建议是 <<sharing_build_logic_between_subprojects.adoc#, 使用自定义插件>>。

如果您的构建脚本需要使用外部库,则可以将其添加到构建脚本本身的脚本的类路径中.您可以使用  `buildscript()` 方法执行此操作,并传入一个声明构建脚本类路径的块.

.Declaring external dependencies for the build script
====
include::{snippets-dir}/tutorial/externalDependency/groovy/build.gradle[tags=declare-classpath]
include::{snippets-dir}/tutorial/externalDependency/kotlin/build.gradle.kts[tags=declare-classpath]
====

传递给 `buildscript()` 方法的块将配置 link:{javadocPath}/org/gradle/api/initialization/dsl/ScriptHandler.html[ScriptHandler] 实例.
您可以通过将依赖添加到类路径配置中来声明构建脚本类路径. 这与您声明 Java 编译类路径的方式相同. 您可以使用除项目依赖以外的任何 <<declaring_dependencies.adoc#sec:dependency-types,dependency types>>.

.A build script with external dependencies
====
include::{snippets-dir}/tutorial/externalDependency/groovy/build.gradle[tags=all]
include::{snippets-dir}/tutorial/externalDependency/kotlin/build.gradle.kts[tags=all]

.**`gradle -q encode`** 的输出
----
> gradle -q encode
include::{snippets-dir}/tutorial/externalDependency/tests/externalBuildDependency.out[]
----
====

对于多项目构建,使用项目的 `buildscript()` 方法声明的依赖可用于其所有子项目的构建脚本.

构建脚本依赖可能是 Gradle 插件.请参阅 <<plugins.adoc#plugins,使用 Gradle 插件>>以获取有关 Gradle 插件的更多信息.

每个项目都会自动具有 link:{groovyDslPath}/org.gradle.api.tasks.diagnostics.BuildEnvironmentReportTask.html[BuildEnvironmentReportTask] 类型的 `buildEnvironment` 任务,可以调用该任务来报告构建脚本依赖的解决方案.

== 进一步阅读

本章仅探讨了可能的内容.以下是一些可能有趣的主题:

- <<authoring_maintainable_build_scripts#authoring_maintainable_build_scripts,编写可维护的构建脚本>>
- <<organizing_gradle_projects#organizing_gradle_projects,组织您的 Gradle 项目>>
- <<custom_tasks#custom_tasks,编写自定义 tasks>>
