// Copyright 2017 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

[[writing_build_scripts]]
= 编写构建脚本

This chapter looks at some of the details of writing a build script.

[[sec:the_gradle_build_language]]
== Gradle 构建脚本语言

Gradle 提供了一种领域特定语言 DSL，用于描述构建。 Groovy 和 Kotlin 中提供了这种构建语言。

Groovy构建脚本可以包含任何Groovy语言元素。footnote:[Any language element except for statement labels.] Kotlin 构建脚本可以包含任何 Kotlin 语言元素。 Gradle 每个构建脚本都使用 UTF-8 编码。

[[sec:project_api]]
== Project API

在第七章 Java构建入门那部分我们使用了 apply() 方法，这个方法是从哪里来的呢? 我们之前
说过Gradle在构建脚本中定义了一个项目. 对于构建脚本中每个项目，Gradle 都创建了一个
Project 类型的对象用来关联此项目. 当构建脚本执行时，它会去配置所关联的工程对象.

构建脚本通过配置项目来描述您的构建。 项目是一个抽象的概念，但是您通常将 Gradle 项目映射到需要构建的软件组件，例如库或应用程序。 您拥有的每个构建脚本都与一个 link:{groovyDslPath}/org.gradle.api.Project.html[Project] 类型的对象相关联，并且在执行构建脚本时，当构建脚本执行时，它会去配置所关联的项目对象.

实际上，构建脚本中的几乎所有顶级属性和块都是 Project API 的一部分。 为了演示，请看下面的示例构建脚本，该脚本显示其项目名称，可通过 link:{groovyDslPath}/org.gradle.api.Project.html#org.gradle.api.Project:name[Project.name] 属性访问该名称：

.访问Project对象的属性
====
include::{snippets-dir}/tutorial/projectApi/groovy/build.gradle[tags=project-name]
include::{snippets-dir}/tutorial/projectApi/kotlin/build.gradle.kts[tags=project-name]

.**`gradle -q check`** 的输出
----
> gradle -q check
include::{snippetsPath}/tutorial/projectApi/tests/projectApi.out[]
----
====

这两个 `println` 语句都打印出相同的属性。 第一个使用对 `Project` 对象的 `name` 属性的顶级引用。 另一条语句使用可用于任何构建脚本的 `project` 属性，该脚本返回关联的 `Project` 对象。 只有定义了与 `Project` 对象的成员名称相同的属性或方法，才需要使用 `project` 属性。

[[sec:standard_project_properties]]
=== 标准的 project 属性

`Project` 对象提供了一些标准的属性，您可以在构建脚本中很方便的使用他们. 下面列出了常用的属性:

.Project 属性
[%header%autowidth,compact]
|===
| Name | Type | Default Value

| `project`
| link:{groovyDslPath}/org.gradle.api.Project.html[Project]
| `Project` 实例

| `name`
| `String`
| 项目目录的名称

| `path`
| `String`
| 项目的绝对路径

| `description`
| `String`
| 项目描述

| `projectDir`
| `File`
| 包含构建脚本的目录

| `buildDir`
| `File`
| `__projectDir__/build`

| `group`
| `Object`
| `unspecified`

| `version`
| `Object`
| `unspecified`

| `ant`
| link:{javadocPath}/org/gradle/api/AntBuilder.html[AntBuilder]
| `AntBuilder` 实例
|===

[IMPORTANT]
.Script with other targets
====
此处描述的构建脚本以 `Project` 对象为目标。还有分别针对 link:{groovyDslPath}/org.gradle.api.initialization.Settings.html[Settings] 和 link:{groovyDslPath}/org.gradle.api.invocation.Gradle.html[Gradle] 对象的 <<build_lifecycle.adoc#sec:settings_file,settings scripts>>和 <<init_scripts.adoc#init_scripts,init scripts>>。
====

[[sec:the_script_api]]
== script API

当 Gradle 执行一个脚本时，它会将这个脚本编译为实现了 Script 的类. 也就是说所有的属性
和方法都是在 Script 接口中声明的，由于你的脚本实现了 Script 接口，所以你可以在自己的
脚本中使用它们.

当 Gradle 执行 Groovy 构建脚本 (`.gradle`) 时，它会将脚本编译为实现 link:{groovyDslPath}/org.gradle.api.Script.html[Script] 的类。 这意味着脚本接口中声明的所有属性和方法在脚本中都可用。

当 Gradle 执行 Kotlin 构建脚本 (`.gradle.kts`) 时，它会将脚本编译为 link:https://gradle.github.io/kotlin-dsl-docs/api/org.gradle.kotlin.dsl/-kotlin-build-script/index.html[KotlinBuildScript] 的子类。 这意味着在脚本中可以使用KotlinBuildScript类型声明的所有可见属性和函数。 另请分别参见 link:https://gradle.github.io/kotlin-dsl-docs/api/org.gradle.kotlin.dsl/-kotlin-settings-script/index.html[KotlinSettingsScript] 和 link:https://gradle.github.io/kotlin-dsl-docs/api/org.gradle.kotlin.dsl/-kotlin-init-script/index.html[KotlinInitScript] 类型以获取设置脚本和初始化脚本。

[[sec:declaring_variables]]
== 声明变量

可以在构建脚本中声明两种变量：局部变量和额外属性。

[[sec:local_variables]]
=== 局部变量

[.multi-language-text.lang-groovy]
局部变量用 `def` 关键字声明。它们仅在声明它们的范围内可见。局部变量是基础 Groovy 语言的功能。

[.multi-language-text.lang-kotlin]
局部变量用 `val` 关键字声明。它们仅在声明它们的范围内可见。局部变量是基础 Kotlin 语言的功能。

.使用局部变量
====
include::{snippets-dir}/tutorial/localVariables/groovy/build.gradle[]
include::{snippets-dir}/tutorial/localVariables/kotlin/build.gradle.kts[]
====

[[sec:extra_properties]]
=== 额外属性

Gradle 的域模型中的所有增强型对象都可以包含其他用户定义的属性。 这包括但不限于 projects, tasks 和 source sets。

[.multi-language-text.lang-groovy]
可以通过拥有对象的 Extra 属性添加，读取和设置 `ext` 属性。或者，可以使用 `ext` 块一次添加多个属性。

[.multi-language-text.lang-kotlin]
可以通过拥有对象的 Extra 属性添加，读取和设置 `extra` 属性。 另外，它们可以通过 `by extra` 的 Kotlin 委托属性来解决。

.使用额外属性
====
include::{snippets-dir}/tutorial/extraProperties/groovy/build.gradle[tags=extraProperties]
include::{snippets-dir}/tutorial/extraProperties/kotlin/build.gradle.kts[tags=extraProperties]

.**`gradle -q printProperties`** 的输出
----
> gradle -q printProperties
include::{snippetsPath}/tutorial/extraProperties/tests/extraProperties.out[]
----
====

[.multi-language-text.lang-groovy]
在此示例中，`ext` 块向项目对象添加了两个额外的属性。 此外，通过将 `ext.purpose` 设置为 `null`（`null`是允许的值），将名为 `Purpose` 的属性添加到每个 source set。 添加属性后，就可以像预定义属性一样读取和设置它们。

[.multi-language-text.lang-kotlin]
在此示例中，两个额外的属性通过 `by extra` 添加到项目对象中。 另外，通过将 `extra["purpose"]` 设置为 `null`（`null`是允许的值），将名为 `purpose` 的属性添加到每个源集。 一旦添加了属性，就可以读取它们并对其进行额外设置。

通过要求添加属性的特殊语法，当尝试设置（预定义或额外的）属性但该属性拼写错误或不存在时，Gradle 可能会快速失败。 可以从可以访问其所属对象的任何位置访问其他属性，从而使它们的范围比局部变量更大。 从子项目中可以看到项目的其他属性。

有关其他属性及其API的更多详细信息，请参阅API文档中的 link:{groovyDslPath}/org.gradle.api.plugins.ExtraPropertiesExtension.html[ExtraPropertiesExtension] 类。

[[sec:configuring_arbitrary_objects]]
== 配置任意对象

您可以按照以下易读的方式配置任意对象。

.配置任意对象
====
include::{snippets-dir}/tutorial/configureObject/groovy/build.gradle[]
include::{snippets-dir}/tutorial/configureObject/kotlin/build.gradle.kts[]

.**`gradle -q configure`** 的输出
----
> gradle -q configure
include::{snippetsPath}/tutorial/configureObject/tests/configureObject.out[]
----
====

[[sec:configuring_arbitrary_objects_using_an_external_script]]
== 使用外部脚本配置任意对象

您也可以使用外部脚本配置任意对象。

[CAUTION]
.仅支持 Groovy 脚本
====
Kotlin DSL 尚不支持使用外部脚本配置任意对象。有关更多信息，请参见 link:https://github.com/gradle/kotlin-dsl/issues/659[gradle/kotlin-dsl#659] 
====

.使用脚本配置任意对象
====
include::{snippets-dir}/tutorial/configureObjectUsingScript/groovy/build.gradle[];other.gradle[]

.`gradle -q configure` 的输出
----
> gradle -q configure
include::{snippetsPath}/tutorial/configureObjectUsingScript/tests/configureObjectUsingScript.out[]
----
====

[[groovy-dsl-basics]]
== 一些 Groovy 基础知识

[TIP]
在寻找Kotlin的一些基础知识时，link:https://kotlinlang.org/docs/reference/[Kotlin参考文档] 和 link:https://kotlinlang.org/docs/tutorials/koans.html[Kotlin Koans] 应该对您有用。


https://docs.groovy-lang.org/latest/html/documentation/index.html[Groovy language] 为创建 DSL 提供了许多功能，而 Gradle 构建语言则利用了这些功能。 了解构建语言的工作原理将在您编写构建脚本时，特别是在开始编写自定义插件和任务时，对您有所帮助。

[[sec:groovy_jdk]]
=== Groovy JDK

Groovy 向标准 Java 类添加了许多有用的方法。例如，`Iterable`  获取一个 `each`  方法，该方法遍历 `Iterable` 的元素：

.Groovy JDK 方法
====
include::{snippets-dir}/tutorial/groovy/groovy/build.gradle[tags=groovyJdk]
====

有关更多详细信息，请访问  https://groovy-lang.org/gdk.html[]

[[sec:property_accessors]]
=== Property 访问器

Groovy 自动将属性引用转换为对适当的 getter 或 setter 方法的调用。

.Property accessors
====
include::{snippets-dir}/tutorial/groovy/groovy/build.gradle[tags=propertyAccessors]
====

[[sec:optional_parentheses_on_method_calls]]
=== 方法调用上的可选括号

括号对于方法调用是可选的。

.不带括号的方法调用
====
include::{snippets-dir}/tutorial/groovy/groovy/build.gradle[tags=methodCallWithoutParentheses]
====

[[sec:list_and_map_literals]]
=== List and map literals

Groovy 提供了一些用于定义 `List` 和  `Map` 实例的快捷方式。两种文字都很简单，但是 map literal 有一些有趣的变化。

例如，“`apply`” 方法（通常在其中应用插件）实际上带有一个 `map` 参数。 但是，当您有一行诸如 “`apply plugin:'java'`” 之类的行时，实际上并没有使用 map literal，而是使用了  “named parameters”，其语法与 map literal 几乎完全相同（没有 包装支架）。 调用该方法时，已命名的参数列表将转换为 map，但并非以 map 开头。

.List and map literals
====
include::{snippets-dir}/tutorial/groovy/groovy/build.gradle[tags=listAndMapLiterals]
====

[[sec:closures_as_the_last_parameter_in_a_method]]
=== 闭包作为方法中的最后一个参数

Gradle DSL在许多地方使用闭包。您可以在  https://docs.groovy-lang.org/latest/html/documentation/index.html#_closures[此处] 找到有关闭包的更多信息。当方法的最后一个参数是闭包时，可以将闭包放在方法调用之后：

.闭包作为方法参数
====
include::{snippets-dir}/tutorial/groovy/groovy/build.gradle[tags=closureAsLastParam]
====

[[sec:closure_delegate]]
=== Closure delegate

每个闭包都有一个 `delegate` 对象，Groovy 使用该对象来查找不是闭包的局部变量或参数的变量和方法引用。 Gradle 将其用于配置闭包，其中将委托对象设置为要配置的对象。

.Closure delegates
====
include::{snippets-dir}/tutorial/groovy/groovy/build.gradle[tags=closureDelegates]
====

[[script-default-imports]]
== 默认导入

为了使构建脚本更加简洁，Gradle 自动向 Gradle 脚本添加了一组导入语句。 这意味着，除了使用 `throw new org.gradle.api.tasks.StopExecutionException()` 之外，您还可以输入 `throw new StopExecutionException()`。

下面列出了添加到每个脚本的默认导入:

.Gradle default imports
[source,groovy]
----
include::default-imports.txt[]
----
