// Copyright 2018 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

= 依赖管理术语

依赖关系管理有着丰富的术语。 在这里，您可以找到最常用的术语，包括对用户指南的引用，以了解其实际应用。

[[sub:terminology_artifact]]
== Artifact（构件）

通过构建生成的文件或目录，例如 JAR、ZIP 包或本地可执行文件。

构件通常设计为供用户或其他项目使用，或部署到托管系统。 在这种情况下，构件是单个文件。 目录在项目间依赖的情况下很常见，以避免生成可发布构件的成本。

[[sub:terminology_capability]]
== Capability（能力）

能力标识一个或多个组件提供的功能。 能力由类似于用于 <<sub:terminology_module_version,module versions>> 的坐标的坐标来标识。
默认情况下，每个模块版本都提供与其坐标匹配的功能，例如 `com.google:guava:18.0`。
能力可以用来表示一个组件提供了多个 <<sub:terminology_feature_variant,功能变体>> 或者两个不同的组件实现了相同的特性（因此不能一起使用）。
有关更多详细信息，请参阅 <<component_capabilities.adoc#,capabilities>> 部分。

[[sub:terminology_component]]
== Component（组件）

<<dependency_management_terminology.adoc#sub:terminology_module,module>> 的任何一个版本.

对于外部库，术语 component 是指库的一个已发布版本。

在构建中，组件由插件（例如 Java Library 插件）定义，并提供一种简单的方法来定义要发布的 publication。 它们包括  <<#sub:terminology_artifact,artifacts>>  以及详细描述 <<#sub:terminology_variant,组件变体>> 的相应 <<#sub:terminology_artifact,metadata>> 。
例如，设置中的组件由 JAR（由任务生成）以及 JavaAPI和运行时变体的依赖信息组成。 它还可以定义其他变体，例如源代码和Javadoc，以及相应的工件。javajar

例如，默认设置中的 `java` 组件包含一个 JAR（由 `jar` 任务生成）以及 Java _api_ 和 _runtime_ 变体的依赖信息。
它还可以定义其他变体，例如 _sources_ 和 _Javadoc_，以及相应的构件。

[[sub:terminology_configuration]]
== Configuration（配置）

配置是为特定目标组合在一起的一组命名 <<#sub:terminology_dependency,依赖>>
配置提供对底层的、已解析的 <<#sub:terminology_module,modules>> 及其构件的访问。
有关详细信息，请参阅有关 <<declaring_dependencies.adoc#sec:what-are-dependency-configurations,dependency 配置>> 以及 <<declaring_dependencies.adoc#sec:resolvable-consumable-configs,resolvable 和 consumable 配置>> 的部分。

[NOTE]
====
"configuration" 一词是一个重载术语，在依赖管理的上下文之外具有不同的含义。
====

[[sub:terminology_dependency]]
== Dependency（依赖）

依赖项是指向构建、测试或运行  <<#sub:terminology_module,module>> 所需的另一个软件。 有关详细信息，请参阅有关  <<declaring_dependencies.adoc#,声明依赖>> 的部分。

[[sub:terminology_dependency_constraint]]
== Dependency constraint（依赖约束）

依赖约束定义了模块需要满足的要求，以使其成为依赖的有效解析结果。
例如，依赖约束可以缩小支持的模块版本集。 依赖约束可用于表达对传递依赖。
有关详细信息，请参阅有关 <<dependency_constraints.adoc#,upgrading>> 和 <<dependency_downgrade_and_exclude.adoc#,downgrading>> 传递依赖的部分。

[[sub:terminology_feature_variant]]
== Feature Variant（功能变体）

功能变体是表示组件特征的变体，可以单独选择或不单独选择。 功能变体由一个或多个 <<#sub:terminology_capability,capabilities>> 标识。 有关详细信息，
请参阅有关 <<feature_variants.adoc#,建模功能变体和可选依赖>> 的部分。

[[sub:terminology_module]]
== Module（模块）

一个随时间而演变的软件，例如  link:https://github.com/google/guava[Google Guava]。 每个模块都有一个名称。模块的每个版本都 由 <<#sub:terminology_module_version,module version>> 表示。
为了方便使用，模块可以托管在 <<#sub:terminology_repository,repository>> 中。

[[sub:terminology_module_metadata]]
== Module metadata（模块元数据）

<<#sub:terminology_module,module>> 的 Releases 提供元数据。
元数据是更详细地描述模块的数据，例如 关于构件的位置的信息或所需的<<#sub:terminology_transitive_dependency,transitive dependencies>>。
Gradle 提供了自己的元数据格式，称为 link:https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/design/gradle-module-metadata-latest-specification.md[Gradle Module Metadata] (`.module` file)  但也支持 Maven (`.pom`) 和 Ivy (`ivy.xml`) 元数据。
有关支持的元数据格式的更多信息，请参阅 <<publishing_gradle_module_metadata.adoc#,理解 Gradle 模块元数据>> 部分。

== Component metadata rule（组件元数据规则）

组件元数据规则是在从存储库获取组件元数据后修改组件元数据的规则，例如 添加缺失的信息或纠正错误的信息。
与 <<#sub:terminology_resolution_rule,resolution rules>> 相比，组件元数据规则在解析开始 *之前* 应用。
组件元数据规则被定义为构建逻辑的一部分，并且可以通过插件共享。
有关详细信息，请参阅  <<component_metadata_rules.adoc#,使用组件元数据规则修复元数据>> 部分。

[[sub:terminology_module_version]]
== Module version（模块版本）

模块版本表示已发布的 <<#sub:terminology_module,module>> 的一组不同的更改。 例如 `18.0` 表示模块的版本，坐标为 `com.google:guava:18.0`。
在实践中，模块版本的方案没有限制。 时间戳、数字、特殊后缀（如 `-GA`）都是允许的标识符。
最广泛使用的版本控制策略是 link:https://semver.org/[semantic versioning].

[[sub::terminology_platform]]
== Platform（平台）

平台是一组旨在一起使用的模块。 有不同类别的平台，对应不同的用例：

- 模块集：通常是一组模块作为一个整体发布在一起。 使用集合中的一个模块通常意味着我们希望对集合的所有模块使用相同的版本。 例如，如果使用 `groovy` 1.2，也使用 `groovy-json` 1.2。
- 运行时环境：一组已知可以很好地协同工作的库。 例如，Spring 平台，推荐 Spring 和与 Spring 配合良好的组件的版本。
- 部署环境：Java 运行时、应用服务器、...

此外，Gradle 定义了 <<dependency_version_alignment.adoc#sec:virtual_platform,virtual platform>>。

[NOTE]
====
Maven 的 BOM（物料清单）是一种流行的平台，<<platforms.adoc#sub:bom_import, Gradle 支持>>。
====

[[sub:terminology_publication]]
== Publication（发布）

应作为单个实体发布到存储库以供消费者使用的文件和元数据的描述。

publication 有一个名称，包含一个或多个构件以及有关这些构件的信息（<<#sub:terminology_module_metadata,metadata>>）。

[[sub:terminology_repository]]
== Repository（存储库）

存储库保管一组 <<#sub:terminology_module,modules>>，每个都可以提供由 <<#sub:terminology_module_version,module version>> 指示的一个或多个版本（组件）。
存储库可以基于二进制存储库产品（例如 Artifactory 或 Nexus）或文件系统中的目录结构。
有关详细信息，请参阅 <<declaring_repositories.adoc#,Declaring Repositories>>。

[[sub:terminology_resolution_rule]]
== Resolution rule（解析规则）

解析规则影响如何直接解析 <<#sub:terminology_dependency,dependency>> 的行为。
解析规则被定义为构建逻辑的一部分。
有关详细信息，请参阅 <<resolution_rules.adoc#,直接自定义依赖项的解析>> 部分。

[[sub:terminology_transitive_dependency]]
== Transitive dependency（依赖传递）

<<#sub:terminology_component,component>> 的变体可以依赖于其他模块才能正常工作，即所谓的传递依赖。
<<#sub:terminology_repository,repository>> 上托管的模块的版本可以提供 <<#sub:terminology_module_metadata,metadata>> 来声明这些传递依赖项。
默认情况下，Gradle 会自动解析传递依赖。 传递依赖的版本选择可以通过声明 <<dependency_constraints.adoc#,dependency constraints>> 来影响。

[[sub:terminology_variant]]
== Variant (of a component)（变体）

每个 <<#sub:terminology_component,component>> 包含一个或多个变体。 变体由一组构件组成并定义了一组依赖项。
它由一组 <<sub:terminology_attribute,attributes>> 和 <<sub:terminology_capability,capabilities>> 标识。

Gradle 的依赖解析是变体感知的，并在选择了一个组件（即一个模块的一个版本）之后选择每个组件的一个或多个变体。
如果变体选择结果不明确，也可能会失败，这意味着 Gradle 没有足够的信息来选择多个互斥变体之一。
在这种情况下，可以通过 <<#sub:terminology_attribute,variant attributes>> 提供更多信息。
每个 Java 组件通常提供的变体示例是 _api_ 和 _runtime_ 变体。 其他示例是 JDK8 和 JDK11 变体。 有关详细信息，请参阅<<variant_model.adoc#,variant selection>> 部分。

[[sub:terminology_attribute]]
== Variant Attribute（变体属性）

属性用于识别和选择<<#sub:terminology_variant,variants>>。
一个变体定义了一个或多个属性，例如 `org.gradle.usage=java-api`、`org.gradle.jvm.version=11`。
解决依赖关系后，会请求一组属性，Gradle 会为依赖关系图中的每个组件找到最合适的变体。
可以为属性实现兼容性和消歧规则以表示值之间的兼容性（例如，Java 8 与 Java 11 兼容，但如果请求的版本为 11 或更高版本，则应首选 Java 11）。
此类规则通常由插件提供。
有关详细信息，请参阅有关 <<variant_model.adoc#,variant selection>> 和 <<variant_attributes.adoc#,declaring attributes>> 的部分。