[[customizing-sdr.adding-sdr-to-spring-mvc-app]]
= 将 Spring Data REST 添加到现有的 Spring MVC 应用程序

NOTE: 如果您使用 Spring Boot， 则无需执行以下步骤.  对于 Boot 应用程序， 添加 `spring-boot-starter-data-rest` 会自动将 Spring Data REST 添加到您的应用程序.

您可以将 Spring Data REST 与现有的 Spring MVC 应用程序集成.  在您的 Spring MVC 配置中 (最有可能在其中配置 MVC 资源的地方) ， 向负责配置 `RepositoryRestController` 的 Java 配置类添加 Bean 引用.  类名称是 `org.springframework.data.rest.webmvc.RepositoryRestMvcConfiguration`.  下面的示例演示如何使用 `@Import` 注解添加正确的引用:

在 Java 中， 这看起来像:

====
[source,java]
----
import org.springframework.context.annotation.Import;
import org.springframework.data.rest.webmvc.RepositoryRestMvcConfiguration;

@Configuration
@Import(RepositoryRestMvcConfiguration.class)
public class MyApplicationConfiguration {

  …
}
----
====

以下示例显示了相应的 XML 配置: :

====
[source,xml]
----
<bean class="org.springframework.data.rest.webmvc.config.RepositoryRestMvcConfiguration"/>
----
====

当您的 `ApplicationContext` 遇到此 bean 定义时， 它将引导必需的 Spring MVC 资源， 以完全配置控制器以导出在该 `ApplicationContext` 和任何父上下文中找到的存储库.

[[customizing-sdr.adding-sdr-to-spring-mvc-app.required-config]]
== 有关所需配置的更多信息

Spring Data REST 依赖于几个 Spring MVC 资源， 这些资源必须正确配置才能在现有的 Spring MVC 应用程序中运行.  我们试图将那些资源与应用程序中已经存在的任何类似资源隔离开来， 但是可能您想通过修改这些 MVC 组件来自定义 Spring Data REST 的某些行为.

您应该特别注意配置下一节中介绍的 `RepositoryRestHandlerMapping`.

[[customizing-sdr.adding-sdr-to-spring-mvc-app.required-config.mapping]]
=== `RepositoryRestHandlerMapping`


我们注册了一个自定义 `HandlerMapping` 实例， 该实例仅对 `RepositoryRestController` 做出响应， 并且仅在要由 Spring Data REST 处理路径的情况下才响应.  为了使应由您的应用程序处理的路径与由 Spring Data REST 处理的路径分开， 此自定义 `HandlerMapping` 类检查 URL 路径并检查是否已以该名称暴露了存储库.  如果有， 则自定义 `HandlerMapping` 类使该请求由 Spring Data REST 处理.  如果没有使用该名称暴露的存储库， 则返回 `null`， 这意味着 "`让其他 `HandlerMapping` 实例尝试为该请求提供服务`".

Spring Data REST HandlerMapping 配置为 `order=(Ordered.LOWEST_PRECEDENCE - 100)`， 这意味着通常在映射 URL 路径时排在第一位.  您现有的应用程序永远不会有机会为存储库提供服务.  例如， 如果您有一个以 `person` name 宝咯的存储库， 那么所有以  `/person`  开头的对应用程序的请求都将由 Spring Data REST 处理， 而您的应用程序将永远不会看到该请求.  但是， 如果您的存储库以其他名称 (例如 `people`) 暴露， 则对 `/people` 的请求将转到 Spring Data REST， 而对 `/person` 的请求将由您的应用程序处理.