[[customizing-sdr.configuring-the-rest-url-path]]
= 配置 REST URL 路径

您可以配置 URL 路径的分段，JPA 存储库的资源将在该路径下暴露。为此，在类级别或查询方法级别添加注解。

默认情况下，暴露程序通过使用 domain 类的名称暴露 `CrudRepository`。Spring Data REST 还应用 https://github.com/atteo/evo-inflector[Evo Inflector] 将这个词复数化。考虑以下存储库定义:

====
[source,java]
----
interface PersonRepository extends CrudRepository<Person, Long> {}
----
====

上述示例定义的存储库在 `http://localhost:8080/persons/` 中暴露。

要更改存储库的暴露方式，请在类级别添加  `@RestResource` 注解，如下面的示例所示:

====
[source,java]
----
@RepositoryRestResource(path = "people")
interface PersonRepository extends CrudRepository<Person, Long> {}
----
====

可以在 `http://localhost:8080/people/` 上访问上述示例定义的存储库。

如果你定义了查询方法，它们也会默认按名称暴露，如下面的例子所示:

====
[source,java]
----
interface PersonRepository extends CrudRepository<Person, Long> {

  List<Person> findByName(String name);
}
----
====

上例中的方法在 `http://localhost:8080/persons/search/findByName` 中暴露。

NOTE: 所有查询方法资源都显示在 `search` 资源下.

要更改公开该查询方法的 URL 段，您可以再次使用 `@RestResource` 注解，如下面的示例所示:

====
[source,java]
----
@RepositoryRestResource(path = "people")
interface PersonRepository extends CrudRepository<Person, Long> {

  @RestResource(path = "names")
  List<Person> findByName(String name);
}
----
====

现在，前面示例中的查询方法在 `http://localhost:8080/people/search/names` 中暴露。

== 处理 `rel` 属性

由于这些资源都是可发现的，因此您还可以修改 `rel` 属性来更改链接中的显示方式。

例如，在默认配置中，如果您向 `http://localhost:8080/persons/search` 发出请求以了解暴露了哪些查询方法，则会获得类似于以下内容的链接列表:

====
[source,javascript]
----
{
  "_links" : {
    "findByName" : {
      "href" : "http://localhost:8080/persons/search/findByName"
    }
  }
}
----
====

要更改 `rel` 值，请使用 `@RestResource` 注解上的 `rel` 属性，如下所示:

====
[source,java]
----
@RepositoryRestResource(path = "people")
interface PersonRepository extends CrudRepository<Person, Long> {

  @RestResource(path = "names", rel = "names")
  List<Person> findByName(String name);
}
----
====

上述示例得到的链接值如下:

====
[source,javascript]
----
{
  "_links" : {
    "names" : {
      "href" : "http://localhost:8080/persons/search/names"
    }
  }
}
----
====

NOTE: 这些 JSON 片段认为您使用 Spring Data REST 的默认格式 http://stateless.co/hal_specification.html[HAL]。 您可以关闭 HAL，这将导致输出看起来有所不同。 但是，覆盖 `rel` 名称的能力完全独立于渲染格式.

您可以更改一个存储库的 `rel`，如下所示:

====
[source,java]
----
@RepositoryRestResource(path = "people", rel = "people")
interface PersonRepository extends CrudRepository<Person, Long> {

  @RestResource(path = "names", rel = "names")
  List<Person> findByName(String name);
}
----
====

改变存储库的 `rel` 会改变顶级名称，如下面的示例输出所示:

====
[source,javascript]
----
{
  "_links" : {
    "people" : {
      "href" : "http://localhost:8080/people"
    },
    …
  }
}
----
====

在前面的输出中显示的顶级片段中:

* `path = "people"` 将 `href` 中的值从 `/persons` to `/people`.
* `rel = "people"` 将 link 的名称从 `persons` to `people`.

当您使用 `search`  资源时，finder 方法的 `@RestResource` 注解已更改了路径，如下所示：

====
[source,javascript]
----
{
  "_links" : {
    "names" : {
      "href" : "http://localhost:8080/people/search/names"
    }
  }
}
----
====

您在存储库中定义的注解集合引起了以下更改:

* 存储库级注解的 `path = "people"` 在基本URI中以 `/people` 反应.
* finder method 为您提供了 `/people/search`.
* `path = "names"` 创建一个 `/people/search/names` 的 URI.
* `rel = "names"` 将该链接的名称从 `findByNames` 改为 `names`.

[[customizing-sdr.hiding-repositories]]
== 隐藏某些存储库、查询方法或字段

您可能根本不想暴露某个存储库，该存储库上的查询方法或您实体的某个字段。 例如在 `User` 对象上隐藏诸如 `password` 之类的字段以及类似的敏感数据。 要告诉使用这不要暴露这些属性，请使用 `@RestResource` 对注解并设置 `exported = false`.

例如，要跳过暴露存储库，可以创建与以下示例类似的存储库定义：

====
[source,java]
----
@RepositoryRestResource(exported = false)
interface PersonRepository extends CrudRepository<Person, Long> {}
----
====

要跳过暴露查询方法，可以使用 `@RestResource(exported = false)` 注解该查询方法，如下所示:

====
[source,java]
----
@RepositoryRestResource(path = "people", rel = "people")
interface PersonRepository extends CrudRepository<Person, Long> {

  @RestResource(exported = false)
  List<Person> findByName(String name);
}
----
====

类似地，要跳过暴露字段，可以使用 `@RestResource(exported = false)` 注解该字段，如下所示:

====
[source,java]
----
@Entity
public class Person {

  @Id @GeneratedValue private Long id;

  @OneToMany
  @RestResource(exported = false)
  private Map<String, Profile> profiles;
}
----
====

WARNING: Projections 提供了更改输出内容并有效避开 <<projections-excerpts.hidden-data,这些设置>> 的方法。 如果您是针对同一 domain 对象创建任何 projections，请确保不要导出字段。

[[customizing-sdr.hiding-repository-crud-methods]]
== 隐藏 Repository CRUD 方法

如果您不想在 `CrudRepository` 上暴露保存或删除方法，则可以使用 `@RestResource(exported = false)` 设置，方法是覆盖要关闭的方法并将注解放在覆盖的版本上。 例如，为防止 HTTP 用户调用 `CrudRepository` 的 `delete` 方法，请覆盖所有方法并将注解添加到覆盖的方法中，如下所示:

====
[source,java]
----
@RepositoryRestResource(path = "people", rel = "people")
interface PersonRepository extends CrudRepository<Person, Long> {

  @Override
  @RestResource(exported = false)
  void delete(Long id);

  @Override
  @RestResource(exported = false)
  void delete(Person entity);
}
----
====

WARNING: 覆盖这两个 `delete` 方法很重要。 为了获得更快的运行时性能，暴露器当前使用一种比较幼稚的算法来确定要使用哪种 CRUD 方法。 当前，您无法关闭带有 ID 的 `delete` 版本，但不能暴露带有实体实例的版本。 目前，您可以暴露 `delete` 方法，也可以不暴露。 如果要关闭它们，请记住，必须使用 `exported = false` 注解这两个版本。