[[customizing-sdr.configuring-cors]]
= 配置 CORS

出于安全原因，浏览器禁止 AJAX 调用当前来源之外的资源(同源策略)。 在处理浏览器发出的客户端 HTTP 请求时，您希望启用特定的 HTTP 资源。

从 2.6 版开始，Spring Data REST 通过 https://docs.spring.io/spring/docs/{spring-framework-version}/spring-framework-reference/web.html#mvc-cors[Spring's CORS]  来支持 https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[跨域资源共享] (CORS).

== 存储库接口 CORS 配置

您可以在存储库界面中添加 `@CrossOrigin` 注解，以对整个存储库启用 CORS。 默认情况下，`@CrossOrigin` 允许所有来源和 HTTP 方法。 以下示例显示了跨域存储库接口定义:

====
[source, java]
----
@CrossOrigin
interface PersonRepository extends CrudRepository<Person, Long> {}
----
====

在前面的示例中，为整个 `PersonRepository` 启用了 `CORS` 支持。 `@CrossOrigin` 提供了用于配置 CORS 支持的属性，如以下示例所示:

====
[source, java]
----
@CrossOrigin(origins = "http://domain2.example",
  methods = { RequestMethod.GET, RequestMethod.POST, RequestMethod.DELETE },
  maxAge = 3600)
interface PersonRepository extends CrudRepository<Person, Long> {}
----
====

前面的示例通过提供一个 origin（仅限 `GET`，`POST` 和 `DELETE` 方法）并且最长使用时间为 `3600` 秒，从而启用了对整个 `PersonRepository` 的 CORS 支持.

== 存储库 REST 控制器方法 CORS 配置

Spring Data REST 在共享存储库基本路径的自定义 REST 控制器上完全支持 https://docs.spring.io/spring/docs/{spring-framework-version}/spring-framework-reference/web.html#controller-method-cors-configuration[Spring Web MVC's controller method configuration]，如以下示例所示:

====
[source, java]
----
@RepositoryRestController
public class PersonController {

  @CrossOrigin(maxAge = 3600)
  @RequestMapping(path = "/people/xml/{id}", method = RequestMethod.GET, produces = MediaType.APPLICATION_XML_VALUE)
  public Person retrieve(@PathVariable Long id) {
    // …
  }
}
----
====

NOTE: 带有 `@RepositoryRestController` 注解的控制器从其关联的存储库继承 `@CrossOrigin` 配置.

== 全局 CORS 配置

除了基于注解的细粒度配置之外，您可能还希望定义一些全局 CORS 配置。 这类似于 Spring Web MVC 的 CORS 配置，但可以在 Spring Data REST 中声明，并与细粒度的 `@CrossOrigin` 配置结合使用。 默认情况下，允许所有 origins 以及 `GET`，`HEAD` 和 `POST` 方法.

NOTE: 现有的 Spring Web MVC CORS 配置不适用于 Spring Data REST。

以下示例设置了允许的 origin，添加了 `PUT` 和 `DELETE` HTTP 方法，添加并公开了一些头，并设置了最长一小时的时间:

====
[source, java]
----
@Component
public class SpringDataRestCustomization extends RepositoryRestConfigurerAdapter {

  @Override
  public void configureRepositoryRestConfiguration(RepositoryRestConfiguration config) {

    config.getCorsRegistry().addMapping("/person/**")
      .allowedOrigins("http://domain2.example")
      .allowedMethods("PUT", "DELETE")
      .allowedHeaders("header1", "header2", "header3")
      .exposedHeaders("header1", "header2")
      .allowCredentials(false).maxAge(3600);
  }
}
----
====
