[[customizing-sdr.customizing-json-output]]
= 自定义 JSON 输出

有时,  在您的应用程序中,  您需要提供指向特定实体中其他资源的链接.  例如,  `Customer` 响应中可能包含指向当前购物车的链接或管理与该实体相关的资源的链接.  Spring Data REST 提供了与 https://github.com/SpringSource/spring-hateoas[Spring HATEOAS] 的集成,  并提供了一个扩展钩子,  使您可以更改输出到客户端的资源的表示形式.

[[customizing-sdr.customizing-json-output.representation-model-processor]]
== `RepresentationModelProcessor` 接口

Spring HATEOAS 为处理实体定义了 `RepresentationModelProcessor<>` 接口.  Spring Data REST 导出器会自动检索所有 `RepresentationModelProcessor&lt;Resource&lt;T&gt;&gt;` 类型的 bean,  并在序列化 `T` 类型的实体时触发.

例如,  要为 `Person` 实体定义处理器,  请将类似于以下内容的 `@Bean` (从 Spring Data REST 测试中获取) 添加到您的 `ApplicationContext` 中:

====
[source,java]
----
@Bean
public RepresentationModelProcessor<EntityModel<Person>> personProcessor() {

   return new RepresentationModelProcessor<EntityModel<Person>>() {

     @Override
     public EntityModel<Person> process(EntityModel<Person> model) {

      model.add(new Link("http://localhost:8080/people", "added-link"));
      return model;
     }
   };
}
----
====

IMPORTANT: 上面的示例对到 `http://localhost:8080/people` 的链接进行硬编码.  如果您的应用程序内部有一个要链接的 Spring MVC 端点,  请考虑使用 Spring HATEOAS 的  https://github.com/spring-projects/spring-hateoas#building-links-pointing-to-methods[`linkTo(...)`] 方法来避免管理 URL.

[[customizing-sdr.customizing-json-output.adding-links]]
== 添加 Links

您可以通过调用 `model.add(Link)` 将链接添加到实体的默认表示形式,  如前面的示例所示.  您添加到  `Resource` 的所有链接都将添加到最终输出中.

[[customizing-sdr.customizing-json-output.customizing-representation]]
== 自定义表示

Spring Data REST 导出器在创建输出表示之前执行所有发现的 `RepresentationModelProcessor` 实例.  通过向内部 `ConversionService` 注册 `Converter<Entity, EntityModel>`  实例来实现此目的.  这是负责创建到所引用实体 (例如,  对象的 JSON 表示形式 `_links` 属性下的那些对象) 的链接的组件.  它需要一个 `@Entity` 并对其属性进行迭代,  为由存储库管理的那些属性创建链接,  并在任何嵌入式或简单属性之间进行复制.

但是,  如果您的项目需要使用其他格式的输出,  则可以使用您自己的格式完全替换默认的传出 JSON 表示形式.  如果在 `ApplicationContext` 中注册自己的 `ConversionService` 并注册自己的 `Converter<Entity, EntityModel>`,  则可以返回您选择的 `EntityModel` 实现.
