[[customizing-sdr]]
= 自定义 Spring Data REST

有许多选项可以定制 Spring Data REST.

== 自定义单个资源 URIs

默认情况下,单个资源的 URI 由资源集合的路径加数据库实体的标识符组成.这允许我们使用存储库的  `findOne(…)` 方法来查找实体实例.从 Spring Data REST 2.5 开始,可以使用  `RepositoryRestConfiguration` 配置API(Java 8中的首选)
或通过在应用程序中将 `EntityLookup` 的实现注册为 Spring bean 来自定义.Spring Data REST 将根据它们的实现来挑选并调整 URI 生成.

假设 `User` 具有唯一标识的 `username` 属性.另外,假设我们在相应的存储库中有一个方法  `Optional<User> findByUsername(String username)`.

在 Java 8 中,我们可以简单地将映射方法注册为引用 URI 的方法引用,如下所示:

====
[source, java]
----
@Component
public class SpringDataRestCustomization implements RepositoryRestConfigurer {

  @Override
  public void configureRepositoryRestConfiguration(RepositoryRestConfiguration config) {
    config.withEntityLookup()
      .forRepository(UserRepository.class)
      .withIdMapping(User::getUsername)
      .withLookup(UserRepository::findByUsername); 
  }
}
----
====

`forRepository(…)` 将存储库类型作为第一个参数,将存储库域类型映射到某个目标类型的方法引用作为第二个参数,以及另一个方法引用,  使用提到的存储库作为第一个参数来映射该值.

如果您没有使用 Java 8 或更高版本,  则可以使用以下方法,  但是它将需要一些相当冗长的匿名内部类.  在较老的 Java 版本上,  您可能应该更喜欢实现类似于以下内容的 `UserEntityLookup`:

====
[source, java]
----
@Component
public class UserEntityLookup extends EntityLookupSupport<User> {

    private final UserRepository repository;

    public UserEntityLookup(UserRepository repository) {
        this.repository = repository;
    }

    @Override
    public Serializable getResourceIdentifier(User entity) {
        return entity.getUsername();
    }

    @Override
    public Object lookupEntity(Serializable id) {
        return repository.findByUsername(id.toString());
    }
}
----
====

注意 `getResourceIdentifier(…)`  如何返回 URI 创建要使用的用户名.  要通过从该方法返回的值加载实体实例,  我们现在使用 `UserRepository上` 可用的查询方法来实现 `lookupEntity(…)`.

[[customizing-sdr.repository-exposure]]
== 暴露自定义存储库

默认情况下,  所有公共 Spring Data 存储库都用于公开 HTTP 资源,  如 <<repository-resources>> 中所述.  Package protected 存储库接口从此列表中排除,  因为您表示其功能仅对包内部可见.  可以通过在 `RepositoryRestConfiguration` 上显式设置 `RepositoryDetectionStrategy` (通常通过枚举 `RepositoryDetectionStrategies`) 来自定义.  可以配置以下值:

- `ALL` -- 暴露所有 Spring Data 存储库,  无论其 Java 可见性或注解配置如何.
- `DEFAULT` -- 暴露公共 Spring 数据存储库或使用 `@RepositoryRestResource` 显式注解的存储库,  并且其 `exported` 属性未设置为 `false`.
- `VISIBILITY` -- 仅公开公共Spring Data存储库,  而与注解配置无关.
- `ANNOTATED` -- 仅公开使用  `@RepositoryRestResource` 显式注解的 Spring Data 存储库,  其 `exported` 属性未设置为 `false`.

如果需要自定义规则,  只需实现 `RepositoryDetectionStrategy`.

[[customizing-sdr.http-methods]]
== 自定义支持的 HTTP 方法

[[customizing-sdr.http-methods.default-exposure]]
=== 自定义默认暴露

默认情况下,  Spring Data REST 暴露 HTTP 资源和方法,  如 <<repository-resources>> 中所述基于存储库 CRUD 方法暴露.  该存储库无需扩展 `CrudRepository`,  但也可以有选择地声明上述部分中描述的方法,  随后将b暴露资源.  例如.  如果存储库未暴露 `delete(…)` 方法,  则项目资源将不支持 HTTP DELETE.

如果需要声明一个用于内部使用的方法,  但不希望它暴露 HTTP 方法,  则可以使用 `@RestResource(exported = false)` 注解存储库方法.  <<repository-resources>> 中描述了哪些注解方法类似,  以删除对哪种 HTTP 方法的支持. .

有时,  在方法级别上暴露还不够细粒度.  例如.  `save(…)` 方法用于收集资源上的 `POST`,  以及项目资源上的 `PUT` 和 `PATCH`. 要有选择地定义应该公开的 HTTP 方法,  可以使用 `RepositoryRestConfiguration.getExposureConfiguration()`.

这个类公开了一个基于 Lambda 的 API 来定义全局规则和基于类型的规则::

[source, java]
----
ExposureConfiguration config = repositoryRestConfiguration.getExposureConfiguration();

config.forDomainType(User.class).disablePutForCreation(); <1>
config.withItemExposure((metadata, httpMethods) -> httpMethods.disable(HttpMethod.PATCH)); <2>
----
<1> 禁用对 HTTP `PUT` 的支持,  直接创建项目.
<2> 在所有项目资源上禁用对 HTTP `PATCH` 支持.


include::configuring-the-rest-url-path.adoc[leveloffset=+1]
include::adding-sdr-to-spring-mvc-app.adoc[leveloffset=+1]
include::overriding-sdr-response-handlers.adoc[leveloffset=+1]
include::customizing-json-output.adoc[leveloffset=+1]
include::custom-jackson-deserialization.adoc[leveloffset=+1]
include::configuring-cors.adoc[leveloffset=+1]
