[[install-chapter]]
= 入门
include::attributes.adoc[]

Spring Data REST 本身就是一个 Spring MVC 应用程序,它的设计方式应该是尽可能少的集成到现有的 Spring MVC 应用程序中. 现有的 (或将来的) 服务层可以与 Spring Data REST 一起运行,只有较小的考虑.

[[getting-started.boot]]
== 将 Spring Data REST 添加到 Spring Boot 项目

最简单的入门方法是构建一个 Spring Boot 应用程序,因为 Spring Boot 有一个适用于 Spring Data REST 的 starter,并且使用自动配置.  以下示例显示了如何使用 Gradle 在 Spring Boot 项目中包括 Spring Data Rest:

.Spring Boot configuration with Gradle
====
[source,groovy]
----
dependencies {
  ...
  compile("org.springframework.boot:spring-boot-starter-data-rest")
  ...
}
----
====

以下示例显示了如何使用 Maven 在 Spring Boot 项目中包括 Spring Data Rest:

.Spring Boot configuration with Maven
====
[source,xml]
----
<dependencies>
  ...
  <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-rest</artifactId>
  </dependency>
  ...
</dependencies>
----
====

NOTE: 如果您使用 https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-gradle-plugin[Spring Boot Gradle plugin]  插件或  https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-maven-plugin[Spring Boot Maven plugin] 插件,则无需提供版本号.

当您使用 Spring Boot 时,Spring Data REST会自动配置.

[[getting-started.gradle]]
== 将 Spring Data REST 添加到 Gradle 项目

要将 Spring Data REST 添加到基于 Gradle 的项目中,请将 spring-data-rest-webmvc artifact 添加到您的编译时依赖中,如下所示:

====
[source,groovy,subs="verbatim,attributes"]
----
dependencies {
  … other project dependencies
  compile("org.springframework.data:spring-data-rest-webmvc:{version}")
}
----
====

[[getting-started.maven]]
== 将 Spring Data REST 添加到 Maven 项目

要将 Spring Data REST 添加到基于 Maven 的项目中,请将 `spring-data-rest-webmvc` artifact 添加到编译时依赖中:

====
[source,xml,subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.springframework.data</groupId>
  <artifactId>spring-data-rest-webmvc</artifactId>
  <version>{version}</version>
</dependency>
----
====

[[getting-started.configuration]]
== 配置 Data REST

要在现有的 Spring MVC 应用程序安装 Spring Data REST,您需要包含适当的MVC配置. Spring Data REST 配置在名为 `RepositoryRestMvcConfiguration` 的类中定义,您可以将该类导入到应用程序的配置中.

IMPORTANT: 如果您使用 Spring Boot 的自动配置,则无需执行此步骤. 当你的应用程序包含  *spring-boot-starter-data-rest* ,并且使用  `@SpringBootApplication` 或 `@EnableAutoConfiguration`. SpringBoot 会自动启用 Spring Data Rest

要自定义配置,请注册 `RepositoryRestConfigurer`  的实现或覆盖与您的用例相关的  `configure…` -方法.

请确保您还使用了 Spring Data repositories.  有关详细信息,请参见 https://projects.spring.io/spring-data/[相应的 Spring Data 模块] 的参考文档.

[[getting-started.basic-settings]]
== Spring Data REST 的基本设置

本部分介绍配置 Spring Data REST 应用程序时可以操作的基本设置,包括:

* <<getting-started.setting-repository-detection-strategy>>
* <<getting-started.changing-base-uri>>
* <<getting-started.changing-other-properties>>

[[getting-started.setting-repository-detection-strategy]]
=== 设置存储库检测策略

Spring Data REST 使用 `RepositoryDetectionStrategy` 来确定是否将存储库暴露为REST资源.  `RepositoryDiscoveryStrategies` 枚举包括以下值:

.Repository 检测策略
[cols="1,5". options="header"]
|===
| 枚举值         | 描述
| `DEFAULT`    | 暴露所有公共存储库接口, 除了 `@(Repository)RestResource` 的 `exported` 标志.
| `ALL`        | 暴露所有独立可见的类型和注解的 repositories
| `ANNOTATED` | 只有使用 `@(Repository)RestResource`  注解的存储库才暴露,除非其 `exported` 标志设置为 `false`.
| `VISIBILITY` | 值暴露被注解的  public repositories
|===

[[getting-started.changing-base-uri]]
=== 更改基本 URI

默认情况下,Spring Data REST 在根 URI '/' 处提供 REST 资源.  有多种途径更改基本路径.

在 Spring Boot 1.2 和更高版本中,您可以通过在 `application.properties` 中设置单个属性来更改基本 URI,如下所示:

====
[source,properties]
----
spring.data.rest.basePath=/api
----
====

使用 Spring Boot 1.1 或更早版本,或者如果您不使用 Spring Boot,则可以执行以下操作:

====
[source,java]
----
@Configuration
class CustomRestMvcConfiguration {

  @Bean
  public RepositoryRestConfigurer repositoryRestConfigurer() {

    return new RepositoryRestConfigurer() {

      @Override
      public void configureRepositoryRestConfiguration(RepositoryRestConfiguration config, CorsRegistry cors) {
        config.setBasePath("/api");
      }
    };
  }
}
----
====

另外,您可以注册一个自定义实现 `RepositoryRestConfigurer` 作为 Spring bean,并确保它被组件扫描拾取,如下所示:

====
[source,java]
----
@Component
public class CustomizedRestMvcConfiguration extends RepositoryRestConfigurer {

  @Override
  public void configureRepositoryRestConfiguration(RepositoryRestConfiguration config, CorsRegistry cors) {
    config.setBasePath("/api");
  }
}
----
====

前面两种方法都将基本路径更改为 `/api`.

[[getting-started.changing-other-properties]]
=== 更改其他 Spring Data REST 属性

您可以更改以下属性:

您可以更改以下属性:
[cols="1,5". options="header"]
|===
| 属性             | 描述
| `basePath`           | Spring Data REST 根 URI
| `defaultPageSize`    | 更改默认的 PageSize 大小
| `maxPageSize`        | 更改每页最大的 PageSize
| `pageParamName`      | 重命名查询参数 page 的名称.
| `limitParamName`     | 重命名查询参数 size 的名称
| `sortParamName`      | 重命名查询参数 sort 的名称
| `defaultMediaType`   | 更改默认的媒体类型 (在没有指定时使用)
| `returnBodyOnCreate` | 更改在创建一个新实体的时候返回一个实体
| `returnBodyOnUpdate` | 更改在更新一个新实体的时候返回一个实体
|===

[[getting-started.bootstrap]]
== 启动应用程序

此时,您还必须配置一种数据存储.

Spring Data REST 官方支持:

* https://projects.spring.io/spring-data-jpa/[Spring Data JPA]
* https://projects.spring.io/spring-data-mongodb/[Spring Data MongoDB]
* https://projects.spring.io/spring-data-neo4j/[Spring Data Neo4j]
* https://projects.spring.io/spring-data-gemfire/[Spring Data GemFire]
* https://projects.spring.io/spring-data-cassandra/[Spring Data Cassandra]

以下入门指南可以帮助您快速入门和运行:

* https://spring.io/guides/gs/accessing-data-rest/[Spring Data JPA]
* https://spring.io/guides/gs/accessing-mongodb-data-rest/[Spring Data MongoDB]
* https://spring.io/guides/gs/accessing-neo4j-data-rest/[Spring Data Neo4j]
* https://spring.io/guides/gs/accessing-gemfire-data-rest/[Spring Data GemFire]

这些指南介绍了如何为相关数据存储添加依赖配置 实体 对象以及定义存储库.

您可以将应用程序作为 Spring Boot 应用程序运行 (具有前面显示的链接) ,也可以将其配置为经典的 Spring MVC 应用程序.

NOTE: 通常,Spring Data REST 不会向给定的数据存储添加功能.  根据定义,这意味着它应该与支持存储库编程模型的任何 Spring Data 项目一起使用.  上面列出的数据存储是我们已经为其编写集成测试的存储,以验证 Spring Data REST 可以与它们一起使用.

从这一点出发,您可以使用各种 <<customizing-sdr,自定义 Spring Data REST>> .