[[integration]]
= 集成

本节详细介绍了各种与 Spring Data REST 组件集成的方法,无论是使用 Spring Data REST 的 Spring 应用程序还是其他方式.

== 程序化链接

有时您需要在您自己定制的 Spring MVC 控制器中添加导出资源的链接. 有三个基本级别的链接可用:

* 手动组装链接
* 使用 Spring HATEOAS 的  https://docs.spring.io/spring-hateoas/docs/current/reference/html/#fundamentals.obtaining-links.builder[`LinkBuilder`] 与  `linkTo()`, `slash()` 等一起使用.
* 使用 Spring Data REST 的 https://docs.spring.io/spring-data/rest/docs/current/api/org/springframework/data/rest/webmvc/support/RepositoryEntityLinks.html[`RepositoryEntityLinks`] 实现.

第一个建议是可怕的,应该不惜一切代价避免.  它使您的代码变得脆弱和高风险.  第二个在创建与其他手写的 Spring MVC 控制器的链接时很方便.  最后一个,您稍后会看到,有助于查找由 Spring Data REST 导出的资源链接.

考虑以下类,该类使用 Spring 的自动装配:

====
[source,java]
----
public class MyWebApp {

	private RepositoryEntityLinks entityLinks;

	@Autowired
	public MyWebApp(RepositoryEntityLinks entityLinks) {
		this.entityLinks = entityLinks;
	}
}
----
====

对于前面示例中的类,可以使用以下操作:

.链接到导出资源的方式
|===
|方法 | 描述

|`entityLinks.linkToCollectionResource(Person.class)`
| 提供指向该类型的资源集合的链接 (在本例中,是 `Person`).

|`entityLinks.linkToItemResource(Person.class, 1)`
|提供一个链接到一个资源.

|`entityLinks.linkToPagedResource(Person.class, new PageRequest(...))`
|提供到分页资源的链接.

|`entityLinks.linksToSearchResources(Person.class)`
|提供由相应的存储库暴露的所有finder方法的链接列表.

|`entityLinks.linkToSearchResource(Person.class, "findByLastName")`
|通过 `rel` 提供查找程序链接 (即查找程序的名称) .

|===

NOTE: 所有基于搜索的链接都支持用于分页和排序的其他参数.  有关详细信息,请参见 https://docs.spring.io/spring-data/rest/docs/current/api/org/springframework/data/rest/webmvc/support/RepositoryEntityLinks.html[`RepositoryEntityLinks`].  还有 `linkFor(Class<?> type)`,但是返回一个 Spring HATEOAS `LinkBuilder`,这使您返回到较低级的API.  尝试先使用其他的.