[[metadata]]
= 元数据

本节详细介绍了基于 Spring Data REST 的应用程序提供的各种形式的元数据.

[[metadata.alps]]
== 应用级配置文件语义 (ALPS)

[quote, M. Admundsen / L. Richardson / M. Foster, https://tools.ietf.org/html/draft-amundsen-richardson-foster-alps-00]
http://alps.io/[ALPS] 用于定义应用程序级语义的简单描述,其复杂性类似于HTML微格式. 可以使用ALPS文档作为配置文件来解释具有应用无关媒体类型 (如HTML,HAL,Collection + JSON,Siren等) 的文档的应用程序语义. 这提高了配置文件在各种媒体类型中的可重用性.

Spring Data REST 为每个暴露的存储库提供一个 ALPS 文档.  它包含有关 RESTful 转换和每个存储库属性的信息.

Spring Data REST 应用程序的根目录是配置文件链接.  假设您有一个同时包含  `persons` 和关联  `addresses` 的应用程序,则根文档如下:

====
[source,javascript]
----
{
  "_links" : {
    "persons" : {
      "href" : "http://localhost:8080/persons"
    },
    "addresses" : {
      "href" : "http://localhost:8080/addresses"
    },
    "profile" : {
      "href" : "http://localhost:8080/profile"
    }
  }
}
----
====

https://tools.ietf.org/html/rfc6906[RFC 6906] 中定义的 profile 链接是包含应用程序级详细信息的地方.  https://tools.ietf.org/html/draft-amundsen-richardson-foster-alps-00[ALPS 规范草案] 旨在定义一种特定的配置文件格式,我们将在本节的后面进行探讨.

如果访问 `localhost:8080/profile` 链接,则会看到类似于以下内容的内容:

====
[source,javascript]
----
{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/profile"
    },
    "persons" : {
      "href" : "http://localhost:8080/profile/persons"
    },
    "addresses" : {
      "href" : "http://localhost:8080/profile/addresses"
    }
  }
}
----
====

IMPORTANT: 在根级别上,`profile` 是单个链接,不能提供多个应用程序 profile. 因此,您必须导航到 `/profile` 才能找到每个资源的元数据的链接.

如果访问  `/profile/persons` 并查看 `Person` 资源的 profile 数据,则会看到类似于以下示例的内容:

====
[source,javascript]
----
{
  "version" : "1.0",
  "descriptors" : [ {
    "id" : "person-representation", <1>
    "descriptors" : [ {
      "name" : "firstName",
      "type" : "SEMANTIC"
    }, {
      "name" : "lastName",
      "type" : "SEMANTIC"
    }, {
      "name" : "id",
      "type" : "SEMANTIC"
    }, {
      "name" : "address",
      "type" : "SAFE",
      "rt" : "http://localhost:8080/profile/addresses#address"
    } ]
  }, {
    "id" : "create-persons", <2>
    "name" : "persons", <3>
    "type" : "UNSAFE", <4>
    "rt" : "#person-representation" <5>
  }, {
    "id" : "get-persons",
    "name" : "persons",
    "type" : "SAFE",
    "rt" : "#person-representation"
  }, {
    "id" : "delete-person",
    "name" : "person",
    "type" : "IDEMPOTENT",
    "rt" : "#person-representation"
  }, {
    "id" : "patch-person",
    "name" : "person",
    "type" : "UNSAFE",
    "rt" : "#person-representation"
  }, {
    "id" : "update-person",
    "name" : "person",
    "type" : "IDEMPOTENT",
    "rt" : "#person-representation"
  }, {
    "id" : "get-person",
    "name" : "person",
    "type" : "SAFE",
    "rt" : "#person-representation"
  } ]
}
----

<1> 顶部是 `Person` 资源的属性的详细列表,标识为  `#person-representation`. 它列出了属性的名称.
<2> 支持的操作.  这表明如何创建一个新的 `Person`.
<3> `name` 是 `persons`,表示 (因为是复数的) POST应该应用于整个集合,而不是一个  `person`.
<4> `type` 是 `UNSAFE`, 因为此操作可以更改系统状态.
====

NOTE: 此JSON文档的媒体类型为 `application/alps+json`. 这与之前的JSON文档不同,后者的媒体类型为 `application/hal+json`. 这些格式不同,受不同规格的约束

当您检查资源集合时,还可以在 `_links` 集合中找到 `profile` 链接,如以下示例所示:

====
[source,javascript]
----
{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/persons" <1>
    },
    ... other links ...
    "profile" : {
      "href" : "http://localhost:8080/profile/persons" <2>
    }
  },
  ...
}
----

<1> 该HAL文档代表 `Person` 集合.
<2> 它具有指向相同元数据URI的 *profile* 链接.
====

同样,默认情况下, `profile` 链接提供 ALPS 服务.  但是,如果使用 https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1[`Accept` header],则它可以提供  `application/alps+json`.

[[metadata.alps.control-types]]
=== 超媒体控件类型

ALPS显示每个超媒体控件的类型.  他们包括:

.ALPS 类型
[cols="1,5". options="header"]
|===
| 类型 | 描述

| SEMANTIC | 状态元素 (例如  `HTML.SPAN`, `HTML.INPUT` 等) .
| SAFE | 触发安全,幂等状态转换的超媒体控件 (例如 `GET` 或 `HEAD`) .
| IDEMPOTENT | 触发不安全,幂等状态转换 (例如 `PUT` 或 `DELETE`) 的超媒体控件.
| UNSAFE | 触发不安全,非幂等状态转换 (例如 `POST`) 的超媒体控件.
|===

在上面的表示部分中,来自应用程序的数据位被标记为 `SEMANTIC`.   `address` 字段是一个涉及安全 `GET` 检索的链接.  因此,它被标记为 `SAFE`.  超媒体操作本身映射到上表中所示的类型.

[[metadata.alps.projections]]
=== ALPS 和 投影

如果定义任何投影,它们也会在 ALPS 元数据中列出.  假设我们还定义了 `inlineAddress` 和 `noAddresses`,它们将出现在相关的操作中.   (有关这两个投影的定义和讨论,请参见 "`<<projections-excerpts.projections>>`". ) 即  *GET* 将出现在整个集合的操作中,而  *GET* 将出现在单个资源的操作中.  下面的示例显示了 `get-persons` 子代码的替代版本:

====
[source,javascript]
----
...
  {
    "id" : "get-persons",
    "name" : "persons",
    "type" : "SAFE",
    "rt" : "#person-representation",
    "descriptors" : [ { <1>
      "name" : "projection",
      "doc" : {
        "value" : "The projection that shall be applied when rendering the response. Acceptable values available in nested descriptors.",
        "format" : "TEXT"
      },
      "type" : "SEMANTIC",
      "descriptors" : [ {
        "name" : "inlineAddress", <2>
        "type" : "SEMANTIC",
        "descriptors" : [ {
          "name" : "address",
          "type" : "SEMANTIC"
        }, {
          "name" : "firstName",
          "type" : "SEMANTIC"
        }, {
          "name" : "lastName",
          "type" : "SEMANTIC"
        } ]
      }, {
        "name" : "noAddresses", <3>
        "type" : "SEMANTIC",
        "descriptors" : [ {
          "name" : "firstName",
          "type" : "SEMANTIC"
        }, {
          "name" : "lastName",
          "type" : "SEMANTIC"
        } ]
      } ]
    } ]
  }
...
----

<1> 出现一个新的属性 `descriptors`, 其中包含单个资源的数组( `projection`).
<2> 在 `projection.descriptors` 内部, 我们可以看到 `inLineAddress`. 它呈现 `address`, `firstName`, 和 `lastName`.
<3> `noAddresses` 提供了一个包含 `firstName` 和 `lastName` 的子集.
====

利用所有这些信息,客户端不仅可以推断出可用的 RESTful 转换,而且可以在某种程度上推断与后端交互所需的数据元素.

[[metadata.alps.descriptions]]
=== 将自定义详细信息添加到您的ALPS描述中

您可以在ALPS元数据中的自定义消息.  如下创建 `rest-messages.properties`:

====
[source,properties]
----
rest.description.person=A collection of people
rest.description.person.id=primary key used internally to store a person (not for RESTful usage)
rest.description.person.firstName=Person's first name
rest.description.person.lastName=Person's last name
rest.description.person.address=Person's address
----
====

这些 `rest.description.*`  属性定义要显示的 `Person` 资源的详细信息.  它们更改了 `person-representation` 的ALPS格式,如下所示:

====
[source,javascript]
----
...
  {
    "id" : "person-representation",
    "doc" : {
      "value" : "A collection of people", <1>
      "format" : "TEXT"
    },
    "descriptors" : [ {
      "name" : "firstName",
      "doc" : {
        "value" : "Person's first name", <2>
        "format" : "TEXT"
      },
      "type" : "SEMANTIC"
    }, {
      "name" : "lastName",
      "doc" : {
        "value" : "Person's last name", <3>
        "format" : "TEXT"
      },
      "type" : "SEMANTIC"
    }, {
      "name" : "id",
      "doc" : {
        "value" : "primary key used internally to store a person (not for RESTful usage)", <4>
        "format" : "TEXT"
      },
      "type" : "SEMANTIC"
    }, {
      "name" : "address",
      "doc" : {
        "value" : "Person's address", <5>
        "format" : "TEXT"
      },
      "type" : "SAFE",
      "rt" : "http://localhost:8080/profile/addresses#address"
    } ]
  }
...
----

<1> `rest.description.person` 的值映射到整个表示.
<2> `rest.description.person.firstName` 的值映射到 `firstName` 属性.
<3> `rest.description.person.lastName` 的值映射到 `lastName` 属性.
<4> `rest.description.person.id` 的值映射到 `id` 属性,该字段通常不显示.
<5> `rest.description.person.address` 的值映射到 `address` 属性.
====

提供这些属性设置会使每个字段具有额外的 `doc` 属性.

NOTE: Spring MVC (这是Spring Data REST应用程序的本质) 支持语言环境,这意味着您可以将多个属性文件与不同的消息捆绑在一起.

[[metadata.json-schema]]
== JSON Schema

https://json-schema.org/[JSON Schema] 是 Spring Data REST 支持的另一种形式的元数据. 在他们的网站上,JSON Schema 具有以下优点:

* 描述您现有的数据格式
* 清晰的,人机可读的文档
* 完整的结构验证,对于自动测试和验证客户端提交的数据很有用

如<<metadata.alps,上一部分所示>>,您可以通过从根URI导航到  `profile` 链接来获取此数据.

====
[source,javascript]
----
{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/profile"
    },
    "persons" : {
      "href" : "http://localhost:8080/profile/persons"
    },
    "addresses" : {
      "href" : "http://localhost:8080/profile/addresses"
    }
  }
}
----
====

这些链接与前面所示的相同. 要检索 JSON Schema,您可以使用 `Accept` header: `application/schema+json` 调用它们.

在这种情况下,如果您执行 `curl -H 'Accept:application/schema+json' http://localhost:8080/profile/persons`,您会看到如下:

====
[source,javascript]
----
{
  "title" : "org.springframework.data.rest.webmvc.jpa.Person", <1>
  "properties" : { <2>
    "firstName" : {
      "readOnly" : false,
      "type" : "string"
    },
    "lastName" : {
      "readOnly" : false,
      "type" : "string"
    },
    "siblings" : {
      "readOnly" : false,
      "type" : "string",
      "format" : "uri"
    },
    "created" : {
      "readOnly" : false,
      "type" : "string",
      "format" : "date-time"
    },
    "father" : {
      "readOnly" : false,
      "type" : "string",
      "format" : "uri"
    },
    "weight" : {
      "readOnly" : false,
      "type" : "integer"
    },
    "height" : {
      "readOnly" : false,
      "type" : "integer"
    }
  },
  "descriptors" : { },
  "type" : "object",
  "$schema" : "https://json-schema.org/draft-04/schema#"
}
----

<1> 导出的类型
<2> 属性列表
====

如果您的资源具有其他资源的链接,则会有更多详细信息.

当您查看资源集合时,您还会找到 `_links` 集合中显示的  `profile`  链接.

====
[source,javascript]
----
{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/persons" <1>
    },
    ... other links ...
    "profile" : {
      "href" : "http://localhost:8080/profile/persons" <2>
    }
  },
  ...
}
----

<1> 该HAL文档代表 `Person` 集合.
<2> 它具有指向相同元数据URI的 *profile*  链接.
====

同样,默认情况下, `profile`  链接提供 <<metadata.alps,ALPS>> 服务.  如果为它提供了  `application/schema+json` 的 https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1[`Accept` header],则它将呈现 JSON Schema 表示形式.

//= JSON Patch

//TBD
