[[customizing-sdr.overriding-sdr-response-handlers]]
= 覆盖 Spring Data REST 响应处理程序

有时，您可能想为特定资源编写自定义处理程序。 要利用 Spring Data REST 的设置，消息转换器，异常处理等功能，请使用 `@RepositoryRestController` 注解，而不是标准的 Spring MVC `@Controller` 或 `@RestController`。 由 `@RepositoryRestController` 注解的控制器从 `RepositoryRestConfiguration.setBasePath` 中定义的API 基本路径提供服务，所有其他 RESTful 端点（例如，`/api`）都使用该 API 基本路径。 以下示例显示了如何使用 `@RepositoryRestController` 注解:

====
[source,java]
----
@RepositoryRestController
public class ScannerController {

    private final ScannerRepository repository;

    @Autowired
    public ScannerController(ScannerRepository repo) { // <1>
        repository = repo;
    }

    @RequestMapping(method = GET, value = "/scanners/search/listProducers") // <2>
    public @ResponseBody ResponseEntity<?> getProducers() {
        List<String> producers = repository.listProducers(); // <3>

        //
        // do some intermediate processing, logging, etc. with the producers
        //

        CollectionModel<String> resources = CollectionModel.of(producers); // <4>

        resources.add(linkTo(methodOn(ScannerController.class).getProducers()).withSelfRel()); // <5>

        // add other links as needed

        return ResponseEntity.ok(resources); // <6>
    }

}
----

<1> 此示例使用构造器注入.
<2> 该处理程序为 Spring Data finder 方法插入自定义处理程序.
<3> 该处理程序使用基础存储库来获取数据，但是在将最终数据集返回给客户端之前，先进行某种形式的后处理.
<4> 结果需要包装在 Spring HATEOAS `CollectionModel<T>` 对象中以返回集合，`EntityModel<T>` 或 `RepresentationModel<T>` 是单个项目包装器.
<5> 添加 `self` link.
<6> 通过使用 Spring MVC 的 `ResponseEntity` 包装器返回集合，可以确保将集合正确包装并以正确的接受类型呈现.
====

`CollectionModel` 用于集合，对于单个项目使用 `EntityModel`  -- 或更普通的 `RepresentationModel` 类。 这些类型可以组合。 如果您知道集合中每个项目的链接，请使用 `CollectionModel<EntityModel<String>>`（或任何核心 domain 类型而不是 `String`）。 这样，您就可以为每个项目以及整个集合组合链接.

IMPORTANT: 在这个例子中，组合路径是 `RepositoryRestConfiguration.getBasePath()` + `/scanners/search/listProducers`.

[[customizing-sdr.overriding-sdr-response-handlers.annotations]]
== @RepositoryRestResource VS. @BasePathAwareController

如果您对特定于实体的操作不感兴趣，但仍想在 `basePath` 下构建自定义操作，例如 Spring MVC 视图，资源和其他，请使用 `@BasePathAwareController`。
如果您在自定义控制器上使用 `@RepositoryRestController`，则仅当您的请求映射混合到存储库使用的 URI 空间中时，
它才会处理请求。 还将以下额外功能应用于控制器方法：

. 根据为存储库定义的 CORS 配置，该存储库已映射到处理程序方法的请求映射中使用的基本路径段。

. 如果使用 JPA 来确保您可以访问标记为延迟解析的属性，则应用 `OpenEntityManagerInViewInterceptor`。

WARNING: 如果对任何东西都使用 `@Controller` 或 `@RestController`，那么该代码完全不在 Spring Data REST 的范围内。 这扩展到请求处理，消息转换器，异常处理和其他用途。