[[representations]]
= 实体对象表示 (对象映射)

Spring Data REST 返回与 HTTP 请求中指定的请求的 `Accept` 类型对应的实体对象的表示.

目前,只支持 JSON 表示. 今后可以通过添加适当的转换器并使用适当的 content-type 更新控制器方法来支持其他表示类型.

有时,Spring Data REST `ObjectMapper` 的行为 (已专门配置为使用智能的序列化程序,这些序列化程序可以将实体对象转换为链接并再次返回) ,可能无法正确处理您的实体类型.
有很多方法可以构建您的数据,您可能会发现自己的实体类型没有被正确地转换为 JSON. 在这些情况下,有时不习惯以通用方式尝试和支持复杂的实体类型. 有时,根据复杂性,甚至不可能提供通用的解决方案.

[[representations.serializers-and-deserializers]]
== 将自定义的序列化程序添加到 Jackson 的 `ObjectMapper` 中

为了适应用例的最大百分比,Spring Data REST 非常难以正确地呈现对象图. 它将尝试将非托管 bean 作为普通 POJO 进行序列化,并且将尝试创建与需要的托管 bean 的链接. 但是,如果您的实体类型不容易读取或编写纯粹的 JSON,则可能需要为 Jackson 的 `ObjectMapper` 配置自己的自定义映射,序列化器和反序列化器.
则可能需要使用自己的自定义类型映射和序列化来配置 Jackson 的 ObjectMapper.

[[representations.serializers-and-deserializers.abstract-classes]]
=== 抽象类注册

当您在实体类型中使用抽象类 (或接口) 时,您可能需要钩住的一个关键配置点. Jackson 默认不知道为接口创建什么实现. 举个例子:

====
[source,java]
----
@Entity
public class MyEntity {
  @OneToMany
  private List<MyInterface> interfaces;
}
----
====

在默认配置中,Jackson 不知道将新数据发布到导出器时要实例化什么类. 这是您需要通过注解来告诉 Jackson,或者更干净地通过使用 `Module` 注册类型映射.

要将您自己的 Jackson 配置添加到 Spring Data REST 使用的 `ObjectMapper` 中,请覆盖 `configureJacksonObjectMapper` 方法. 该方法将传递一个具有特殊模块的 `ObjectMapper` 实例来处理  `PersistentEntity`  的序列化和反序列化. 您也可以注册自己的模块,如下例所示.

====
[source,java]
----
@Override
protected void configureJacksonObjectMapper(ObjectMapper objectMapper) {

  objectMapper.registerModule(new SimpleModule("MyCustomModule") {

    @Override
    public void setupModule(SetupContext context) {
      context.addAbstractTypeResolver(
        new SimpleAbstractTypeResolver()
          .addMapping(MyInterface.class, MyInterfaceImpl.class));
    }
  });
}
----
====

一旦您访问了您的 `Module` 中的 `SetupContext` 对象,您可以做各种各样的酷事来配置 Jackson 的 JSON 映射. 您可以在 https://wiki.fasterxml.com/JacksonFeatureModules[Jackson 的 Wiki ]上阅读有关 `Module` 实例如何工作的更多信息.

[[representations.serializers-and-deserializers.serializers]]
=== 为实体类型添加自定义序列化器

如果您想以特殊的方式序列化或反序列化实体类型,则可以向 Jackson 的 `ObjectMapper` 注册自己的实现,然后 Spring Data REST 导出器可以透明的正确处理这些实体对象.  要从 `setupModule` 方法实现中添加序列化器,可以执行以下操作:

====
[source,java]
----
@Override
public void setupModule(SetupContext context) {

  SimpleSerializers serializers = new SimpleSerializers();
  SimpleDeserializers deserializers = new SimpleDeserializers();

  serializers.addSerializer(MyEntity.class, new MyEntitySerializer());
  deserializers.addDeserializer(MyEntity.class, new MyEntityDeserializer());

  context.addSerializers(serializers);
  context.addDeserializers(deserializers);
}
----
====
