[[servlet-oauth2Client-additional-features]]
= 其他功能

本节介绍 Spring Security 为 OAuth2 客户端提供的其他功能。

[[servlet-oauth2Client-registered-authorized-client]]
== 解析授权客户端

`@RegisteredOAuth2AuthorizedClient` 注解提供了将方法参数解析为 `OAuth2AuthorizedClient` 类型的参数值的功能.  与使用 `OAuth2AuthorizedClientManager` 或 `OAuth2AuthorizedClientService` 访问 `OAuth2AuthorizedClient` 相比,
这是一种方便的替代方法。以下示例显示如何使用 `@RegisteredOAuth2AuthorizedClient`：

====
.Java
[source,java,role="primary"]
----
@Controller
public class OAuth2ClientController {

	@GetMapping("/")
	public String index(@RegisteredOAuth2AuthorizedClient("okta") OAuth2AuthorizedClient authorizedClient) {
		OAuth2AccessToken accessToken = authorizedClient.getAccessToken();

		...

		return "index";
	}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Controller
class OAuth2ClientController {
    @GetMapping("/")
    fun index(@RegisteredOAuth2AuthorizedClient("okta") authorizedClient: OAuth2AuthorizedClient): String {
        val accessToken = authorizedClient.accessToken

        ...

        return "index"
    }
}
----
====

`@RegisteredOAuth2AuthorizedClient` 注解由 `OAuth2AuthorizedClientArgumentResolver` 处理,该注解直接使用<<servlet-oauth2Client-authorized-manager-provider, OAuth2AuthorizedClientManager>> 并继承其功能.



[[servlet-oauth2Client-webclient-servlet]]
== 在 Servlet 环境中集成 WebClient

OAuth 2.0客户端支持使用 `ExchangeFilterFunction` 与 `WebClient` 集成.

`ServletOAuth2AuthorizedClientExchangeFilterFunction` 提供了一种简单的机制,可以通过使用 `OAuth2AuthorizedClient` 并包括关联的 `OAuth2AccessToken` 作为承载令牌来请求受保护的资源.  它直接使用 <<servlet-oauth2Client-authorized-manager-provider, OAuth2AuthorizedClientManager>>,因此继承了以下功能:

* 如果尚未授权客户端,则将请求 `OAuth2AccessToken`.
** `authorization_code` - 触发授权请求重定向以启动流程
** `client_credentials` - 访问令牌直接从令牌端点获取
** `password` - 访问令牌直接从令牌端点获取
* 如果 `OAuth2AccessToken` 过期,则如果 `OAuth2AuthorizedClientProvider` 可用于执行授权,它将被刷新 (或更新) .

以下代码显示了如何使用 OAuth 2.0 客户端支持配置 `WebClient` 的示例:

====
.Java
[source,java,role="primary"]
----
@Bean
WebClient webClient(OAuth2AuthorizedClientManager authorizedClientManager) {
	ServletOAuth2AuthorizedClientExchangeFilterFunction oauth2Client =
			new ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
	return WebClient.builder()
			.apply(oauth2Client.oauth2Configuration())
			.build();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun webClient(authorizedClientManager: OAuth2AuthorizedClientManager?): WebClient {
    val oauth2Client = ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
    return WebClient.builder()
            .apply(oauth2Client.oauth2Configuration())
            .build()
}
----
====


=== 提供授权客户端

`ServletOAuth2AuthorizedClientExchangeFilterFunction` 通过从 `ClientRequest.attributes()`  (请求属性) 解析 `OAuth2AuthorizedClient` 来确定要使用的客户端 (用于请求) .

以下代码显示了如何将 `OAuth2AuthorizedClient` 设置为请求属性:

====
.Java
[source,java,role="primary"]
----
@GetMapping("/")
public String index(@RegisteredOAuth2AuthorizedClient("okta") OAuth2AuthorizedClient authorizedClient) {
	String resourceUri = ...

	String body = webClient
			.get()
			.uri(resourceUri)
			.attributes(oauth2AuthorizedClient(authorizedClient))   <1>
			.retrieve()
			.bodyToMono(String.class)
			.block();

	...

	return "index";
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun index(@RegisteredOAuth2AuthorizedClient("okta") authorizedClient: OAuth2AuthorizedClient): String {
    val resourceUri: String = ...
    val body: String = webClient
            .get()
            .uri(resourceUri)
            .attributes(oauth2AuthorizedClient(authorizedClient)) <1>
            .retrieve()
            .bodyToMono()
            .block()

    ...

    return "index"
}
----
<1> `oauth2AuthorizedClient()` 是 `ServletOAuth2AuthorizedClientExchangeFilterFunction` 中的 `static` 方法.
====

以下代码显示了如何将 `ClientRegistration.getRegistrationId()` 设置为请求属性:

====
.Java
[source,java,role="primary"]
----
@GetMapping("/")
public String index() {
	String resourceUri = ...

	String body = webClient
			.get()
			.uri(resourceUri)
			.attributes(clientRegistrationId("okta"))   <1>
			.retrieve()
			.bodyToMono(String.class)
			.block();

	...

	return "index";
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@GetMapping("/")
fun index(): String {
    val resourceUri: String = ...

    val body: String = webClient
            .get()
            .uri(resourceUri)
            .attributes(clientRegistrationId("okta"))  <1>
            .retrieve()
            .bodyToMono()
            .block()

    ...

    return "index"
}
----
<1> `clientRegistrationId()` 是 `ServletOAuth2AuthorizedClientExchangeFilterFunction` 中的 `static` 方法.
====

=== 默认授权客户端

如果未提供 `OAuth2AuthorizedClient` 或 `ClientRegistration.getRegistrationId()` 作为请求属性,则 `ServletOAuth2AuthorizedClientExchangeFilterFunction` 可以根据其配置确定要使用的默认客户端.

如果配置了 `setDefaultOAuth2AuthorizedClient(true)` 且用户已使用 `HttpSecurity.oauth2Login()` 进行了身份验证,则使用与当前 `OAuth2AuthenticationToken` 关联的 `OAuth2AccessToken`.

以下代码显示了特定的配置:

====
.Java
[source,java,role="primary"]
----
@Bean
WebClient webClient(OAuth2AuthorizedClientManager authorizedClientManager) {
	ServletOAuth2AuthorizedClientExchangeFilterFunction oauth2Client =
			new ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
	oauth2Client.setDefaultOAuth2AuthorizedClient(true);
	return WebClient.builder()
			.apply(oauth2Client.oauth2Configuration())
			.build();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun webClient(authorizedClientManager: OAuth2AuthorizedClientManager?): WebClient {
    val oauth2Client = ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
    oauth2Client.setDefaultOAuth2AuthorizedClient(true)
    return WebClient.builder()
            .apply(oauth2Client.oauth2Configuration())
            .build()
}
----
====

[WARNING]
====
建议谨慎使用此功能,因为所有 HTTP 请求都会收到访问令牌.
====

或者,如果 `setDefaultClientRegistrationId("okta")` 配置了有效的 `ClientRegistration`,则使用与 `OAuth2AuthorizedClient` 关联的 `OAuth2AccessToken`.

以下代码显示了特定的配置:

====
.Java
[source,java,role="primary"]
----
@Bean
WebClient webClient(OAuth2AuthorizedClientManager authorizedClientManager) {
	ServletOAuth2AuthorizedClientExchangeFilterFunction oauth2Client =
			new ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager);
	oauth2Client.setDefaultClientRegistrationId("okta");
	return WebClient.builder()
			.apply(oauth2Client.oauth2Configuration())
			.build();
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun webClient(authorizedClientManager: OAuth2AuthorizedClientManager?): WebClient {
    val oauth2Client = ServletOAuth2AuthorizedClientExchangeFilterFunction(authorizedClientManager)
    oauth2Client.setDefaultClientRegistrationId("okta")
    return WebClient.builder()
            .apply(oauth2Client.oauth2Configuration())
            .build()
}
----
====

[WARNING]
====
建议谨慎使用此功能,因为所有 HTTP 请求都会收到访问令牌.
====