[[servlet-oauth2Client-core-interface-class]]
= 核心类和接口

本节介绍 Spring Security 提供的 OAuth2 核心接口和类。

[[reactive-oauth2Client-client-registration]]
== ClientRegistration

`ClientRegistration` 是向 OAuth 2.0 或 OpenID Connect 1.0 提供程序注册的客户端的表示.
`ClientRegistration` 对象保存信息，例如客户端 ID、客户端密码、授权授予类型、重定向 URI、范围、授权 URI、令牌 URI 和其他详细信息。

客户端注册包含信息,例如客户端 ID,客户端密钥,授权类型,重定向URI,作用域,授权 URI,令牌 URI 和其他详细信息.

`ClientRegistration` 及其属性定义如下:

====
[source,java]
----
public final class ClientRegistration {
	private String registrationId;	<1>
	private String clientId;	<2>
	private String clientSecret;	<3>
	private ClientAuthenticationMethod clientAuthenticationMethod;	<4>
	private AuthorizationGrantType authorizationGrantType;	<5>
	private String redirectUri;	<6>
	private Set<String> scopes;	<7>
	private ProviderDetails providerDetails;
	private String clientName;	<8>

	public class ProviderDetails {
		private String authorizationUri;	<9>
		private String tokenUri;	<10>
		private UserInfoEndpoint userInfoEndpoint;
		private String jwkSetUri;	<11>
		private String issuerUri;	<12>
        private Map<String, Object> configurationMetadata;  <13>

		public class UserInfoEndpoint {
			private String uri;	<14>
            private AuthenticationMethod authenticationMethod;  <15>
			private String userNameAttributeName;	<16>

		}
	}
}
----
<1> `registrationId`: 唯一标识 `ClientRegistration` 的ID. .
<2> `clientId`: 客户端标识符.
<3> `clientSecret`: 客户端密钥.
<4> `clientAuthenticationMethod`: 提供者对客户端进行身份验证的方法.  支持的值为*client_secret_basic*, *client_secret_post*, *private_key_jwt*, *client_secret_jwt* 和 *none* https://tools.ietf.org/html/rfc6749#section-2.1[(public clients)].
<5> `authorizationGrantType`: OAuth 2.0 授权框架定义了四种 https://tools.ietf.org/html/rfc6749#section-1.3[授权类型] .  支持的值是 `authorization_code`,`client_credentials`,`password`,以及扩展授权类型 `urn:ietf:params:oauth:grant-type:jwt-bearer`。
<6> `redirectUri`: 终端用户对客户端进行身份验证和授权访问后,授权服务器会将终端用户重定向到该客户的注册重定向URI.
<7> `scopes`: 客户在授权请求流程中请求的范围,例如 openid,电子邮件或配置文件.
<8> `clientName`: 用于客户端的描述性名称.  该名称可能在某些情况下使用,例如在自动生成的登录页面中显示客户端名称时.
<9> `authorizationUri`: 授权服务器的授权端点 URI.
<10> `tokenUri`: 授权服务器的令牌端点 URI.
<11> `jwkSetUri`: 用于从授权服务器检索 JSON Web 密钥( https://tools.ietf.org/html/rfc7517[JSON Web Key (JWK)])集的URI,其中包含用于验证 ID 令牌的 JSON Web 签名( https://tools.ietf.org/html/rfc7515[JSON Web Signature (JWS)]) 以及用户信息响应 (可选) 的加密密钥.
<12> `issuerUri`: 返回 OpenID Connect 1.0 provider 或 OAuth 2.0 授权服务器的 issuer 标识 uri.
<13> `configurationMetadata`:  https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[OpenID Provider 配置信息]. 仅当配置了 Spring Boot 2.x 属性 `spring.security.oauth2.client.provider.[providerId].issuerUri`  时,此信息才可用.
<14> `(userInfoEndpoint)uri`: UserInfo 端点 URI,用于访问经过身份验证的最终用户的声明/属性.
<15> `(userInfoEndpoint)authenticationMethod`: 将访问令牌发送到 UserInfo 端点时使用的身份验证方法. 支持  *header*, *form* 和 *query* 值
<16> `userNameAttributeName`: 在 UserInfo 响应中返回的属性名称,该属性引用了最终用户的名称或标识符.
====

可以使用发现 OpenID Connect 提供者的 https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig[Configuration endpoint] 或授权服务器的 https://tools.ietf.org/html/rfc8414#section-3[元数据端点] 来初始配置 `ClientRegistration`.

`ClientRegistrations` 提供了以这种方式配置 `ClientRegistration` 的便捷方法,如以下示例所示:

====
.Java
[source,java,role="primary"]
----
ClientRegistration clientRegistration =
    ClientRegistrations.fromIssuerLocation("https://idp.example.com/issuer").build();
----

.Kotlin
[source,kotlin,role="secondary"]
----
val clientRegistration = ClientRegistrations.fromIssuerLocation("https://idp.example.com/issuer").build()
----
====

上面的代码将依次查询 `https://idp.example.com/issuer/.well-known/openid-configuration` ,然后依次查询 `https://idp.example.com/.well-known/openid-configuration/issuer`,
最后是  `https://idp.example.com/.well-known/oauth-authorization-server/issuer` ,从第一个停止返回200响应.

或者,您可以使用 `ClientRegistrations.fromOidcIssuerLocation()`  仅查询 OpenID Connect 提供程序的配置端点.

[[servlet-oauth2Client-client-registration-repo]]
== ClientRegistrationRepository

`ClientRegistrationRepository` 充当 OAuth 2.0/OpenID Connect 1.0  `ClientRegistration` 的存储库.

[NOTE]
====
客户端注册信息最终由关联的授权服务器存储和拥有.  此存储库提供了检索与授权服务器一起存储的主要客户端注册信息的子集的功能.
====

Spring Boot 2.x 自动配置将 `spring.security.oauth2.client.registration._[registrationId]_`  下的每个属性绑定到 `ClientRegistration` 的实例,然后在 `ClientRegistrationRepository` 中组成每个 `ClientRegistration` 实例.

[NOTE]
====
`ClientRegistrationRepository` 的默认实现是 `InMemoryClientRegistrationRepository`.
====

自动配置还会在 `ApplicationContext` 中将 `ClientRegistrationRepository` 注册为 `@Bean`,以便在应用程序需要时可用于依赖注入.

以下清单显示了一个示例:

====
.Java
[source,java,role="primary"]
----
@Controller
public class OAuth2ClientController {

	@Autowired
	private ClientRegistrationRepository clientRegistrationRepository;

	@GetMapping("/")
	public String index() {
		ClientRegistration oktaRegistration =
			this.clientRegistrationRepository.findByRegistrationId("okta");

		...

		return "index";
	}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Controller
class OAuth2ClientController {

    @Autowired
    private lateinit var clientRegistrationRepository: ClientRegistrationRepository

    @GetMapping("/")
    fun index(): String {
        val oktaRegistration =
                this.clientRegistrationRepository.findByRegistrationId("okta")

        //...

        return "index";
    }
}
----
====

[[servlet-oauth2Client-authorized-client]]
== OAuth2AuthorizedClient

`OAuth2AuthorizedClient` 是授权客户端的表示.  当终端用户 (资源所有者) 已向客户端授权访问其受保护资源的权限时,则认为该客户端已被授权.

`OAuth2AuthorizedClient` 的目的是将 `OAuth2AccessToken` (和可选的 `OAuth2RefreshToken`) 与 `ClientRegistration` (客户端) 和资源所有者相关联,`ClientRegistration` 和资源所有者是授权的主要最终用户.


[[servlet-oauth2Client-authorized-repo-service]]
== OAuth2AuthorizedClientRepository 和 OAuth2AuthorizedClientService

`OAuth2AuthorizedClientRepository` 负责在 Web 请求之间持久保存 `OAuth2AuthorizedClient`.  而 `OAuth2AuthorizedClientService` 的主要作用是在应用程序级别管理 `OAuth2AuthorizedClient`.

从开发人员的角度来看,`OAuth2AuthorizedClientRepository` 或 `OAuth2AuthorizedClientService` 提供了查找与客户端关联的 `OAuth2AccessToken` 的功能,以便可以将其用于发起受保护的资源请求.

以下清单显示了一个示例:

====
.Java
[source,java,role="primary"]
----
@Controller
public class OAuth2ClientController {

    @Autowired
    private OAuth2AuthorizedClientService authorizedClientService;

    @GetMapping("/")
    public String index(Authentication authentication) {
        OAuth2AuthorizedClient authorizedClient =
            this.authorizedClientService.loadAuthorizedClient("okta", authentication.getName());

        OAuth2AccessToken accessToken = authorizedClient.getAccessToken();

        ...

        return "index";
    }
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Controller
class OAuth2ClientController {

    @Autowired
    private lateinit var authorizedClientService: OAuth2AuthorizedClientService

    @GetMapping("/")
    fun index(authentication: Authentication): String {
        val authorizedClient: OAuth2AuthorizedClient =
            this.authorizedClientService.loadAuthorizedClient("okta", authentication.getName());
        val accessToken = authorizedClient.accessToken

        ...

        return "index";
    }
}
----
====

[NOTE]
====
Spring Boot 2.x 自动配置在 `ApplicationContext` 中注册了 `OAuth2AuthorizedClientRepository` 和/或 `OAuth2AuthorizedClientService` `@Bean`.  但是,应用程序可以选择覆盖并注册自定义 `OAuth2AuthorizedClientRepository` 或 `OAuth2AuthorizedClientService` `@Bean`.
====

`OAuth2AuthorizedClientService` 的默认实现是 `InMemoryOAuth2AuthorizedClientService`,它在内存中存储 `OAuth2AuthorizedClient`.

或者,可以将 JDBC 实现 `JdbcOAuth2AuthorizedClientService` 配置为将 `OAuth2AuthorizedClient` 持久存储在数据库中.

[NOTE]
====
`JdbcOAuth2AuthorizedClientService` 取决于<<dbschema-oauth2-client, OAuth 2.0 客户端架构>>中描述的表定义.
====

[[servlet-oauth2Client-authorized-manager-provider]]
== OAuth2AuthorizedClientManager 和 OAuth2AuthorizedClientProvider

`OAuth2AuthorizedClientManager` 负责 `OAuth2AuthorizedClient` 的整体管理.

主要职责包括:

* 使用 `OAuth2AuthorizedClientProvider` 授权 (或重新授权) OAuth 2.0 客户端.
* 通常使用 `OAuth2AuthorizedClientService` 或 `OAuth2AuthorizedClientRepository` 委托 `OAuth2AuthorizedClient` 的持久性.
* 成功授权(或重新授权) OAuth 2.0 客户端后,委派给 `OAuth2AuthorizationSuccessHandler`
* 当 OAuth 2.0 客户端无法授权(或重新授权)时,委派给 `OAuth2AuthorizationFailureHandler`

`OAuth2AuthorizedClientProvider` 实施用于授权 (或重新授权) OAuth 2.0 客户端的策略.  实施通常将实施授权类型,例如.  `authorization_code`, `client_credentials` 等.

`OAuth2AuthorizedClientManager` 的默认实现是 `DefaultOAuth2AuthorizedClientManager`,它与 `OAuth2AuthorizedClientProvider` 关联,
该 `OAuth2AuthorizedClientProvider` 可以使用基于委托的组合来支持多种授权授权类型.  `OAuth2AuthorizedClientProviderBuilder` 可以用于配置和构建基于委托的组合.

以下代码显示了如何配置和构建 `OAuth2AuthorizedClientProvider` 组合的示例,该组合提供对  `authorization_code`,`refresh_token`,`client_credentials` 和 `password` 授权类型的支持:

====
.Java
[source,java,role="primary"]
----
@Bean
public OAuth2AuthorizedClientManager authorizedClientManager(
		ClientRegistrationRepository clientRegistrationRepository,
		OAuth2AuthorizedClientRepository authorizedClientRepository) {

	OAuth2AuthorizedClientProvider authorizedClientProvider =
			OAuth2AuthorizedClientProviderBuilder.builder()
					.authorizationCode()
					.refreshToken()
					.clientCredentials()
					.password()
					.build();

	DefaultOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ClientRegistrationRepository,
        authorizedClientRepository: OAuth2AuthorizedClientRepository): OAuth2AuthorizedClientManager {
    val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
            .authorizationCode()
            .refreshToken()
            .clientCredentials()
            .password()
            .build()
    val authorizedClientManager = DefaultOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
====

当尝试授权成功时,`DefaultOAuth2AuthorizedClientManager` 将委派给 `OAuth2AuthorizationSuccessHandler`,后者(默认情况下)将通过 `OAuth2AuthorizedClientRepository` 保存 `OAuth2AuthorizedClient`.
在重新授权失败的情况下,例如 刷新令牌不再有效,先前保存的 `OAuth2AuthorizedClient` 将通过 `RemoveAuthorizedClientOAuth2AuthorizationFailureHandler` 从 `OAuth2AuthorizedClientRepository` 中删除.
可以通过 `setAuthorizationSuccessHandler(OAuth2AuthorizationSuccessHandler)`  和  `setAuthorizationFailureHandler(OAuth2AuthorizationFailureHandler)` 自定义默认行为.

`DefaultOAuth2AuthorizedClientManager` 也与类型为 `Function<OAuth2AuthorizeRequest, Map<String, Object>>` 的 `contextAttributesMapper` 关联,后者负责将属性从 `OAuth2AuthorizeRequest` 映射到要与 `OAuth2AuthorizationContext` 关联的属性的映射.
当您需要为 `OAuth2AuthorizedClientProvider` 提供必需的 (受支持的) 属性时,这很有用.  `PasswordOAuth2AuthorizedClientProvider` 要求资源所有者的用户名和密码在 `OAuth2AuthorizationContext.getAttributes()` 中可用.

以下代码显示了 `contextAttributesMapper` 的示例:

====
.Java
[source,java,role="primary"]
----
@Bean
public OAuth2AuthorizedClientManager authorizedClientManager(
		ClientRegistrationRepository clientRegistrationRepository,
		OAuth2AuthorizedClientRepository authorizedClientRepository) {

	OAuth2AuthorizedClientProvider authorizedClientProvider =
			OAuth2AuthorizedClientProviderBuilder.builder()
					.password()
					.refreshToken()
					.build();

	DefaultOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	// Assuming the `username` and `password` are supplied as `HttpServletRequest` parameters,
	// map the `HttpServletRequest` parameters to `OAuth2AuthorizationContext.getAttributes()`
	authorizedClientManager.setContextAttributesMapper(contextAttributesMapper());

	return authorizedClientManager;
}

private Function<OAuth2AuthorizeRequest, Map<String, Object>> contextAttributesMapper() {
	return authorizeRequest -> {
		Map<String, Object> contextAttributes = Collections.emptyMap();
		HttpServletRequest servletRequest = authorizeRequest.getAttribute(HttpServletRequest.class.getName());
		String username = servletRequest.getParameter(OAuth2ParameterNames.USERNAME);
		String password = servletRequest.getParameter(OAuth2ParameterNames.PASSWORD);
		if (StringUtils.hasText(username) && StringUtils.hasText(password)) {
			contextAttributes = new HashMap<>();

			// `PasswordOAuth2AuthorizedClientProvider` requires both attributes
			contextAttributes.put(OAuth2AuthorizationContext.USERNAME_ATTRIBUTE_NAME, username);
			contextAttributes.put(OAuth2AuthorizationContext.PASSWORD_ATTRIBUTE_NAME, password);
		}
		return contextAttributes;
	};
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ClientRegistrationRepository,
        authorizedClientRepository: OAuth2AuthorizedClientRepository): OAuth2AuthorizedClientManager {
    val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
            .password()
            .refreshToken()
            .build()
    val authorizedClientManager = DefaultOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)

    // Assuming the `username` and `password` are supplied as `HttpServletRequest` parameters,
    // map the `HttpServletRequest` parameters to `OAuth2AuthorizationContext.getAttributes()`
    authorizedClientManager.setContextAttributesMapper(contextAttributesMapper())
    return authorizedClientManager
}

private fun contextAttributesMapper(): Function<OAuth2AuthorizeRequest, MutableMap<String, Any>> {
    return Function { authorizeRequest ->
        var contextAttributes: MutableMap<String, Any> = mutableMapOf()
        val servletRequest: HttpServletRequest = authorizeRequest.getAttribute(HttpServletRequest::class.java.name)
        val username: String = servletRequest.getParameter(OAuth2ParameterNames.USERNAME)
        val password: String = servletRequest.getParameter(OAuth2ParameterNames.PASSWORD)
        if (StringUtils.hasText(username) && StringUtils.hasText(password)) {
            contextAttributes = hashMapOf()

            // `PasswordOAuth2AuthorizedClientProvider` requires both attributes
            contextAttributes[OAuth2AuthorizationContext.USERNAME_ATTRIBUTE_NAME] = username
            contextAttributes[OAuth2AuthorizationContext.PASSWORD_ATTRIBUTE_NAME] = password
        }
        contextAttributes
    }
}
----
====

`DefaultOAuth2AuthorizedClientManager` 设计为在 `HttpServletRequest` 上下文中使用. 在 `HttpServletRequest` 上下文之外进行操作时,请改用 `AuthorizedClientServiceOAuth2AuthorizedClientManager`.

服务应用程序是何时使用 `AuthorizedClientServiceOAuth2AuthorizedClientManager` 的常见用例. 服务应用程序通常在后台运行,没有任何用户交互,并且通常在系统级帐户而不是用户帐户下运行. 配置为 `client_credentials` 授予类型的 OAuth 2.0 客户端可以视为服务应用程序的类型.

下面的代码显示了一个示例如何配置 `AuthorizedClientServiceOAuth2AuthorizedClientManager` 的示例,该 `ManagerManager` 提供对 `client_credentials` 授予类型的支持:

====
.Java
[source,java,role="primary"]
----
@Bean
public OAuth2AuthorizedClientManager authorizedClientManager(
		ClientRegistrationRepository clientRegistrationRepository,
		OAuth2AuthorizedClientService authorizedClientService) {

	OAuth2AuthorizedClientProvider authorizedClientProvider =
			OAuth2AuthorizedClientProviderBuilder.builder()
					.clientCredentials()
					.build();

	AuthorizedClientServiceOAuth2AuthorizedClientManager authorizedClientManager =
			new AuthorizedClientServiceOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientService);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ClientRegistrationRepository,
        authorizedClientService: OAuth2AuthorizedClientService): OAuth2AuthorizedClientManager {
    val authorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
            .clientCredentials()
            .build()
    val authorizedClientManager = AuthorizedClientServiceOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientService)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
====