[[oauth2client]]
= OAuth 2.0 客户端

OAuth 2.0 客户端功能提供了对 https://tools.ietf.org/html/rfc6749#section-1.1[OAuth 2.0 授权框架]中定义的客户端角色的支持.

在较高级别,可用的核心功能包括:

.授权支持
* https://tools.ietf.org/html/rfc6749#section-1.3.1[授权码]
* https://tools.ietf.org/html/rfc6749#section-6[刷新令牌]
* https://tools.ietf.org/html/rfc6749#section-1.3.4[客户端凭证]
* https://tools.ietf.org/html/rfc6749#section-1.3.3[资源所有者密码凭证]
* https://datatracker.ietf.org/doc/html/rfc7523#section-2.1[JWT Bearer]

.Client Authentication support
* https://datatracker.ietf.org/doc/html/rfc7523#section-2.2[JWT Bearer]

.HTTP 客户端支持
* <<servlet-oauth2Client-webclient-servlet, 在 Servlet 环境中集成 `WebClient`>> (用于请求受保护的资源)

`HttpSecurity.oauth2Client()` DSL 提供了许多配置选项,用于自定义 OAuth 2.0 客户端使用的核心组件.  另外, `HttpSecurity.oauth2Client().authorizationCodeGrant()` 启用自定义授权码授权.

以下代码显示了 `HttpSecurity.oauth2Client()` DSL 提供的完整配置选项:

.OAuth2 Client Configuration Options
====
.Java
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class OAuth2ClientSecurityConfig {

	@Bean
	public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
		http
			.oauth2Client(oauth2 -> oauth2
				.clientRegistrationRepository(this.clientRegistrationRepository())
				.authorizedClientRepository(this.authorizedClientRepository())
				.authorizedClientService(this.authorizedClientService())
				.authorizationCodeGrant(codeGrant -> codeGrant
					.authorizationRequestRepository(this.authorizationRequestRepository())
					.authorizationRequestResolver(this.authorizationRequestResolver())
					.accessTokenResponseClient(this.accessTokenResponseClient())
				)
			);
		return http.build();
	}
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Configuration
@EnableWebSecurity
class OAuth2ClientSecurityConfig {

    @Bean
    open fun filterChain(http: HttpSecurity): SecurityFilterChain {
        http {
            oauth2Client {
                clientRegistrationRepository = clientRegistrationRepository()
                authorizedClientRepository = authorizedClientRepository()
                authorizedClientService = authorizedClientService()
                authorizationCodeGrant {
                    authorizationRequestRepository = authorizationRequestRepository()
                    authorizationRequestResolver = authorizationRequestResolver()
                    accessTokenResponseClient = accessTokenResponseClient()
                }
            }
        }
        return http.build()
    }
}
----
====

除了 `HttpSecurity.oauth2Client()` DSL 外,还支持 XML 配置.

以下代码显示了 <<nsa-oauth2-client, security namespace>> 中可用的完整配置选项:

.OAuth2 Client XML Configuration Options
====
[source,xml]
----
<http>
	<oauth2-client client-registration-repository-ref="clientRegistrationRepository"
				   authorized-client-repository-ref="authorizedClientRepository"
				   authorized-client-service-ref="authorizedClientService">
		<authorization-code-grant
				authorization-request-repository-ref="authorizationRequestRepository"
				authorization-request-resolver-ref="authorizationRequestResolver"
				access-token-response-client-ref="accessTokenResponseClient"/>
	</oauth2-client>
</http>
----
====

`OAuth2AuthorizedClientManager` 负责与一个或多个 `OAuth2AuthorizedClientProvider` 协作管理 OAuth 2.0 客户端的授权 (或重新授权) .

以下代码显示了一个示例,该示例说明如何注册 `OAuth2AuthorizedClientManager` `@Bean` 并将其与 `OAuth2AuthorizedClientProvider` 组合关联,该组合提供对 `authorization_code`,`refresh_token`,`client_credentials` 和  `password`  授权类型的支持:

====
.Java
[source,java,role="primary"]
----
@Bean
public OAuth2AuthorizedClientManager authorizedClientManager(
		ClientRegistrationRepository clientRegistrationRepository,
		OAuth2AuthorizedClientRepository authorizedClientRepository) {

	OAuth2AuthorizedClientProvider authorizedClientProvider =
			OAuth2AuthorizedClientProviderBuilder.builder()
					.authorizationCode()
					.refreshToken()
					.clientCredentials()
					.password()
					.build();

	DefaultOAuth2AuthorizedClientManager authorizedClientManager =
			new DefaultOAuth2AuthorizedClientManager(
					clientRegistrationRepository, authorizedClientRepository);
	authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider);

	return authorizedClientManager;
}
----

.Kotlin
[source,kotlin,role="secondary"]
----
@Bean
fun authorizedClientManager(
        clientRegistrationRepository: ClientRegistrationRepository,
        authorizedClientRepository: OAuth2AuthorizedClientRepository): OAuth2AuthorizedClientManager {
    val authorizedClientProvider: OAuth2AuthorizedClientProvider = OAuth2AuthorizedClientProviderBuilder.builder()
            .authorizationCode()
            .refreshToken()
            .clientCredentials()
            .password()
            .build()
    val authorizedClientManager = DefaultOAuth2AuthorizedClientManager(
            clientRegistrationRepository, authorizedClientRepository)
    authorizedClientManager.setAuthorizedClientProvider(authorizedClientProvider)
    return authorizedClientManager
}
----
====

include::core.adoc[leveloffset=+1]

include::authorization-grants.adoc[leveloffset=+1]

include::client-authentication.adoc[leveloffset=+1]

include::authorized-clients.adoc[leveloffset=+1]