[[build-image]]
== 打包 OCI 镜像
该插件可以使用 https://buildpacks.io[Cloud Native Buildpacks] (CNB) 从可执行 jar 文件创建 https://github.com/opencontainers/image-spec[OCI image].可以使用 `bootBuildImage` 任务来构建镜像.

NOTE: 出于安全原因,镜像以非 root 用户身份构建和运行.有关更多详细信息,请参见 {buildpacks-reference}/reference/spec/platform-api/#users[CNB specification].

应用 `Java` 插件时,该任务会自动创建,并且是 {boot-build-image-javadoc}[`BootBuildImage`] 的实例.

NOTE: `bootBuildImage` 任务不支持 <<packaging-executable-wars, 打包成 war>>.

NOTE: `bootBuildImage` 任务不能与包含启动脚本的 <<packaging-executable-configuring-launch-script, fully executable Spring Boot archive>> 一起使用.在构建旨在与 bootBuildImage 一起使用的 jar 文件时,请在 `bootJar` 任务中禁用启动脚本配置.

[[build-image-docker-daemon]]
=== Docker Daemon

`bootBuildImage` 任务需要访问 Docker 守护程序. 默认情况下,它将通过本地连接与 Docker 守护程序通信. 无需配置即可在所有支持的平台上使用 https://docs.docker.com/install/[Docker Engine].

可以设置环境变量以将 `bootBuildImage` 任务配置为使用 https://minikube.sigs.k8s.io/docs/tasks/docker_daemon/[minikube 提供的 Docker 守护程序] . 下表显示了环境变量及其值:

|===
| Environment variable | Description

| DOCKER_HOST
| URL containing the host and port for the Docker daemon - e.g. `tcp://192.168.99.100:2376`

| DOCKER_TLS_VERIFY
| Enable secure HTTPS protocol when set to `1` (optional)

| DOCKER_CERT_PATH
| Path to certificate and key files for HTTPS (required if `DOCKER_TLS_VERIFY=1`, ignored otherwise)
|===

在 Linux 和 macOS 上,启动 minikube 之后,可以使用命令 `eval $(minikube docker-env)` 设置这些环境变量.

[[build-image-customization]]
=== 自定义镜像

该插件调用一个 {buildpacks-reference}/concepts/components/builder/[builder] 来协助镜像的生成. 该构建器包括多个  {buildpacks-reference}/concepts/components/buildpack[buildpacks],可以检查应用程序以影响生成的镜像. 默认情况下,插件选择一个生成镜像. 生成的镜像名称是从项目属性推导出的.

任务属性可用于配置构建器应如何在项目上运行.下表总结了可用的属性及其默认值:

|===
| Property | Command-line option | Description | Default value

| `builder`
| `--builder`
| Name of the Builder image to use.
| `gcr.io/paketo-buildpacks/builder:base-platform-api-0.3`

| `runImage`
| `--runImage`
| Name of the run image to use.
| No default value, indicating the run image specified in Builder metadata should be used.

| `imageName`
| `--imageName`
| {spring-boot-api}/buildpack/platform/docker/type/ImageReference.html#of-java.lang.String-[Image name] for the generated image.
| `docker.io/library/${project.name}:${project.version}`

| `environment`
|
| Environment variables that should be passed to the builder.
|

| `cleanCache`
|
| Whether to clean the cache before building.
| `false`

| `verboseLogging`
|
| Enables verbose logging of builder operations.
| `false`
|===

NOTE: 该插件使用 JavaPlugin 的 `targetCompatibility` 属性检测目标项目的 Java 兼容性. 当使用默认的 Paketo 构建器和 buildpacks 时,插件会指示 buildpacks 安装相同的 Java 版本. 您可以覆盖此行为,如 <<build-image-example-builder-configuration,builder configuration>> 示例中所示.

[[build-image-examples]]
=== 示例

[[build-image-example-custom-image-builder]]
==== Custom Image Builder and Run Image
如果需要自定义用于创建镜像的构建器或用于启动生成的镜像的运行镜像,请配置任务,如以下示例所示:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-build-image-builder.gradle[tags=builder]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-build-image-builder.gradle.kts[tags=builder]
----

此配置将使用名称为 `mine/java-cnb-builder` 的构建器镜像和最新的标签,以及名为 `mine/java-cnb-run` 的运行镜像和最新的标签.

生成器和运行镜像也可以在命令行上指定,如本示例所示:

[indent=0]
----
$ gradle bootBuildImage --builder=mine/java-cnb-builder --runImage=mine/java-cnb-run
----

[[build-image-example-builder-configuration]]
==== Builder Configuration
如果构建器公开了配置选项,则可以使用环境属性进行设置.

以下是配置在构建时由 Paketo Java  {paketo-java-reference}/#configuring-the-jvm-version[configuring the JVM version] 的示例:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-build-image-env.gradle[tags=env]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-build-image-env.gradle.kts[tags=env]
----

如果构建器在其运行的 Docker 守护程序与构建打包下载 artifacts 的网络位置之间存在网络代理,则需要将构建器配置为使用代理. 使用 Paketo 构建器时,可以通过设置 `HTTPS_PROXY` 和/或 `HTTP_PROXY` 环境变量来实现,如以下示例所示:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-build-image-env-proxy.gradle[tags=env]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-build-image-env-proxy.gradle.kts[tags=env]
----

[[build-image-example-runtime-jvm-configuration]]
==== Runtime JVM Configuration

Paketo Java buildpacks 通过设置环境变量 `JAVA_TOOL_OPTIONS` 来 {paketo-java-reference}/#runtime-jvm-configuration[配置 JVM 运行时环境]。

当在容器中启动应用程序镜像时，可以修改 buildpack 提供的 `JAVA_TOOL_OPTIONS` 值以自定义JVM运行时行为。

可以如 {paketo-reference}/buildpacks/configuration/#environment-variables[Paketo documentation] 中所述在镜像中配置并应用于每个部署的环境变量修改，并在以下示例中显示:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-build-image-env-runtime.gradle[tags=env-runtime]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-build-image-env-runtime.gradle.kts[tags=env-runtime]
----


[[build-image-example-custom-image-name]]
==== 自定义镜像名称
默认情况下,镜像名称是根据项目的  `name` 和  `version` 来推断的,例如 `docker.io/library/${project.name}:${project.version}`. 您可以通过设置任务属性来控制名称,如以下示例所示:

[source,groovy,indent=0,subs="verbatim,attributes",role="primary"]
.Groovy
----
include::../gradle/packaging/boot-build-image-name.gradle[tags=image-name]
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Kotlin
----
include::../gradle/packaging/boot-build-image-name.gradle.kts[tags=image-name]
----

请注意,此配置未提供明确的标记,因此使用了最新的标记. 也可以使用 `${project.version}`,构建中可用的任何属性或硬编码版本来指定标签.

镜像名称也可以在命令行上指定,如以下示例所示:

[indent=0]
----
$ gradle bootBuildImage --imageName=example.com/library/my-app:v1
----
