[[getting-started.installing]]
== 安装 Spring Boot
Spring Boot 可以与经典的 Java 开发工具一起使用或者作为命令行工具安装. 无论如何,您都需要 https://www.java.com[Java SDK v17] 或者更高版本. 在开始之前您应该检查 Java 的安装情况:

[source,shell,indent=0,subs="verbatim"]
----
	$ java -version
----

如果您是 Java 开发新手,或者您只想尝试使用 Spring Boot,您可能需要首先尝试使用 <<getting-started#getting-started.installing.cli, Spring Boot CLI>>,否则请阅读安装说明.

[[getting-started.installing.java]]
=== 针对 Java 开发人员的安装说明
您可以跟使用任何标准 Java 库的方式一样使用 Spring Boot. 只需要在 classpath 下包含相应的 `+spring-boot-*.jar+` 文件即可. Spring Boot 不需要任何专用的工具来集成,因此您可以使用任何 IDE 或者文本编辑器,并且 Spring Boot 应用也没什么特殊之处,因此可以像任何其它 Java 程序一样运行和调试.

虽然您可以复制 Spring Boot 的 jar 文件,但我们通常建议您使用支持依赖管理的构建工具 (比如 Maven 或者 Gradle) .

[[getting-started.installing.java.maven]]
==== 使用 Maven 安装
Spring Boot 兼容 Apache Maven 3.3 或更高版本. 如果您还没有安装 Maven,可以到 https://maven.apache.org 上按照说明进行操作.

TIP: 在许多操作系统上,可以通过软件包管理器来安装 Maven. 如果您是 OSX Homebrew 用户,请尝试使用 `brew install maven`. Ubuntu 用户可以运行 `sudo apt-get install maven`. 具有 https://chocolatey.org/[Chocolatey] 的 Windows 用户在管理员权限 (管理员) 下运行 `choco install maven`.

Spring Boot 依赖使用的 `groupId` 为 `org.springframework.boot` . 通常,您的 Maven POM 文件将从 `spring-boot-starter-parent` 项目继承,并声明一个或多个 <<using#using.build-systems.starters,"`Starters`">> 依赖. Spring Boot 还提供了一个可选的 <<build-tool-plugins#build-tool-plugins.maven, Maven 插件>>来创建可执行 jar.

有关使用 Spring Boot 和 Maven 入门的更多详细信息,请参见 Maven 插件参考指南的  {spring-boot-maven-plugin-docs}#getting-started[入门部分].

[[getting-started.installing.java.gradle]]
==== 使用 Gradle 安装
Spring Boot 与 Gradle 7.x (7.5 or later) 兼容. 如果您还没有安装 Gradle,您可以按照 https://gradle.org 上的说明进行操作.

Spring Boot 依赖使用的 `groupId` 为 `org.springframework.boot`. 通常,您的项目将声明一个或者多个 <<using#using.build-systems.starters, "`Starters`">> 的依赖. Spring Boot 提供了一个有用的  <<build-tool-plugins#build-tool-plugins.gradle, Gradle 插件>>,可用于简化依赖声明和创建可执行 jar 文件.

.Gradle Wrapper
****
当您许需要构建项目时,Gradle Wrapper 提供了一个用于获取 Gradle 的好方法. 它是由小脚本和库组成,您在提交的同时,您的代码将引导构建流程. 更多详细信息,请参阅 {gradle-docs}/gradle_wrapper.html.
****

有关 Spring Boot 和 Gradle 入门的更多详细信息,请参见 Gradle 插件参考指南的 {spring-boot-gradle-plugin-docs}#getting-started[入门部分].

[[getting-started.installing.cli]]
=== 通过 Spring Boot CLI 安装
Spring Boot CLI (Command Line Interface) 是一个命令行工具,如果您想使用 Spring 快速搭建项目原型,您可以选择它. 它允许您运行 https://groovy-lang.org/[Groovy] 脚本,这意味着您有可以具有类似 Java 语法且没有太多样板的代码.

您不需要使用 CLI 来配合 Spring Boot 使用,但它确实是一个入门 Spring 应用程序的快捷方式.

[[getting-started.installing.cli.manual-installation]]
==== 手动安装
您可以从 Spring 软件仓库中下载 Spring CLI 发行版:

* https://repo.spring.io/{spring-boot-artifactory-repo}/org/springframework/boot/spring-boot-cli/{spring-boot-version}/spring-boot-cli-{spring-boot-version}-bin.zip[spring-boot-cli-{spring-boot-version}-bin.zip]
* https://repo.spring.io/{spring-boot-artifactory-repo}/org/springframework/boot/spring-boot-cli/{spring-boot-version}/spring-boot-cli-{spring-boot-version}-bin.tar.gz[spring-boot-cli-{spring-boot-version}-bin.tar.gz]

https://repo.spring.io/snapshot/org/springframework/boot/spring-boot-cli/[最新的快照发行版] 也是可用的.

下载之后,请按照解压后文件中的 {github-raw}/spring-boot-project/spring-boot-tools/spring-boot-cli/src/main/content/INSTALL.txt[INSTALL.txt]  说明进行操作. 总之: 在 `.zip` 文件的 bin/ 目录中有一个 `spring` 脚本 (在 Windows 下为 `spring.bat`) ,或者也可以使用 `java -jar` 配合 `.jar` 文件 (该脚本可以帮助您确保 classpath 设置正确).

[[getting-started.installing.cli.sdkman]]
==== 使用 SDKMAN! 安装
SDKMAN!  (软件开发包管理器) 用于管理二进制 SDK 的多个版本,包括 Groovy 和 Spring Boot CLI. 从 https://sdkman.io 获取 SDKMAN! 并安装 Spring Boot:

[source,shell,indent=0,subs="verbatim,attributes"]
----
	$ sdk install springboot
	$ spring --version
	Spring CLI v{spring-boot-version}
----

如果您正在为 CLI 开发功能,并希望够能轻松地访问刚创建的版本,请参照以下指令.

[source,shell,indent=0,subs="verbatim,attributes"]
----
	$ sdk install springboot dev /path/to/spring-boot/spring-boot-cli/target/spring-boot-cli-{spring-boot-version}-bin/spring-{spring-boot-version}/
	$ sdk default springboot dev
	$ spring --version
	Spring CLI v{spring-boot-version}
----
以上操作将会安装一个名为 `dev` 实例的 `spring` 的本地实例. 它指向您的目标构建位置,因此每次重新构建 Spring Boot 时,`spring` 实例都是最新的.

您可以通过以下命令进行查看::

[source,shell,indent=0,subs="verbatim,attributes"]
----
	$ sdk ls springboot

	================================================================================
	Available Springboot Versions
	================================================================================
	> + dev
	* {spring-boot-version}

	================================================================================
	+ - local version
	* - installed
	> - currently in use
	================================================================================
----



[[getting-started.installing.cli.homebrew]]
==== 使用 OSX Homebrew 安装
如果您是在 Mac 上工作并且使用了 https://brew.sh/[Homebrew],您可以通过以下命令安装 Spring Boot CLI:

[source,shell,indent=0,subs="verbatim"]
----
	$ brew tap spring-io/tap
	$ brew install spring-boot
----

Homebrew 将 `spring` 安装在 `/usr/local/bin`.

NOTE: 如果您没有看到执行流程, 您安装的 brew 可能已经过期了. 执行 `brew update` 并重新尝试.

[[getting-started.installing.cli.macports]]
==== 使用 MacPorts 安装
如果您是在 Mac 上工作并且使用了 https://www.macports.org/[MacPorts],您可以通过以下命令安装 Spring Boot CLI 所需要做的:

[source,shell,indent=0,subs="verbatim"]
----
	$ sudo port install spring-boot-cli
----

[[getting-started.installing.cli.completion]]
==== 命令行完成
Spring Boot CLI 为 https://en.wikipedia.org/wiki/Bash_%28Unix_shell%29[BASH] 和  https://en.wikipedia.org/wiki/Z_shell[zsh] 提供了命令行完成脚本. 您可以在任何 shell 中执行此脚本 (也称为 `spring`) ,或将其放在您个人或系统作用域的 bash 中完成初始化. 在 Debian 系统上,系统作用域的脚本位于 `/shell-completion/bash` 中,当新的 shell 启动时,该目录中的所有脚本将被执行. 例如: 如果您使用了 SDKMAN!， 要手动运行脚本，则使用以下命令：

[source,shell,indent=0,subs="verbatim"]
----
	$ . ~/.sdkman/candidates/springboot/current/shell-completion/bash/spring
	$ spring <HIT TAB HERE>
	  grab  help  jar  run  test  version
----

NOTE: 如果您使用 Homebrew 或者 MacPorts 安装了 Spring Boot CLI,则命令行完成脚本将自动注册到您的 shell 中.

[[getting-started.installing.cli.scoop]]
==== Windows Scoop 安装
如果您在 Windows 上并使用 https://scoop.sh/[Scoop],则可以使用以下命令安装 Spring Boot CLI:

[indent=0]
----
	> scoop bucket add extras
	> scoop install springboot
----

Scoop 将 `spring` 安装在 `~/scoop/apps/springboot/current/bin`.

NOTE: 如果您没有看到应用清单,则可能是因为 scoop 的安装已过期. 在这种情况下,请运行  `scoop update`  更新,然后重试.

[[getting-started.installing.cli.quick-start]]
==== 快速入门 Spring CLI 示例
这是一个非常简单的 web 应用程序,可以用于测试您的安装情况. 创建一个名为 `app.groovy` 的文件:

[source,groovy,indent=0,pending-extract=true,subs="verbatim"]
----
	@RestController
	class ThisWillActuallyRun {

		@RequestMapping("/")
		String home() {
			"Hello World!"
		}

	}
----

之后在 shell 中运行它:

[source,shell,indent=0,subs="verbatim"]
----
	$ spring run app.groovy
----

NOTE: 第一次运行应用的时候需要一些时间,因为需要下载依赖. 后续运行将会更快.

在您喜欢的浏览器中打开 `http://localhost:8080`， 您应该会看到以下输出:

[indent=0]
----
	Hello World!
----

