# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Jcohy-Docs CI with Gradle

on:
  workflow_dispatch:
    inputs:
      uploadOss:
        description: '是否上传到 OSS'
        required: true
        default: 'false'

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 设置 JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: 为 gradlew 赋予执行权限
        run: chmod +x gradlew
      - name: 执行构建
        if: ${{ github.event.inputs.uploadOss == 'false'}}
        run: ./gradlew clean aggregatedAsciidoctor -Dfile.encoding=UTF-8
      - name: 上传到 OSS
        if: ${{ github.event.inputs.uploadOss == 'true'}}
        run: ./gradlew uploadOssFiles
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
