[[web-integration]]
= 其他 Web 框架

本章详细介绍了 Spring 与第三方 Web 框架的集成.

Spring Framework 的核心价值主张之一就是支持选择.  从一般意义上讲,Spring 并没有强迫您使用或购买任何特定的架构,技术或方法(尽管它肯定会推荐一些其他架构,技术或方法) .
这个自由选择的好处在开发人员及其开发团队最相关的技术或方法在 Web 区域中最为明显,其中 Spring 提供了自己的 Web 框架((<<mvc, Spring MVC>> 和 <<web-reactive.adoc#webflux, Spring WebFlux>>) ) ,同时又提供了与许多流行的第三方 Web 框架的集成.

[[web-integration-common]]
== 通用的配置

在深入到每个受支持的 Web 框架的集成细节之前,让我们先来看看不特定于任何一个 Web 框架的 Spring 配置(本节同样适用于 Spring 自己的 Web 框架 Spring MVC. )

Spring 的轻量级应用程序模型支持的一个概念(缺少更好的词) 是分层架构的概念. 请记住,在 "经典" 分层架构中,Web 层只是众多层中的一个.  它充当服务器端应用程序的入口点之一,并且它委托给服务层中定义的服务对象(外观) , 以满足特定于业务(和表示技术不可知) 的用例.
在 Spring 中,这些服务对象,任何其他特定于业务的对象,数据访问对象和其他对象存在于不同的 "business context" 中,该业务上下文不包含 Web 或表示层对象(表示对象,例如 Spring MVC 控制器,通常是 在不同的 "presentation context" 中配置.  本节详细介绍了如何配置包含应用程序中所有 "business bean" 的 Spring 容器(`WebApplicationContext`) .

在细节上,所需要做的就是在一个 Web 应用程序的标准 Jakarta EE Servlet `web.xml` 文件中声明一个 {api-spring-framework}/web/context/ContextLoaderListener.html[`ContextLoaderListener`], 并添加一个 `contextConfigLocation` `<context-param/>` (在同一个文件中),它定义了要加载的 Spring xml 配置文件集.

请考虑以下 `<listener/>` 配置:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<listener>
		<listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
	</listener>
----

进一步考虑以下 `<context-param/>` 配置:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<context-param>
		<param-name>contextConfigLocation</param-name>
		<param-value>/WEB-INF/applicationContext*.xml</param-value>
	</context-param>
----

如果未指定 `contextConfigLocation` 上下文参数,`ContextLoaderListener` 将会查找一个名为 `/WEB-INF/applicationContext.xml` 的文件并加载. 加载上下文文件后, Spring 将基于 bean 定义创建一个 `WebApplicationContext` 对象,并将其存储在 Web 应用程序的 `ServletContext` 中.

所有 Java Web 框架都是在 Servlet API 的基础上构建的,因此可以使用下面的代码段来访问由 `ApplicationContext` 创建的 "business context" 的 `ContextLoaderListener` .

以下示例显示如何获取 `WebApplicationContext`:

[source,java,indent=0,subs="verbatim,quotes"]
----
	WebApplicationContext ctx = WebApplicationContextUtils.getWebApplicationContext(servletContext);
----

{api-spring-framework}/web/context/support/WebApplicationContextUtils.html[`WebApplicationContextUtils`] 是方便的工具类,使用它你就不需要记住 ServletContext 属性的名字. 如果对象不存在于 `WebApplicationContext.ROOT_WEB_APPLICATION_CONTEXT_ATTRIBUTE` 的情况下,则其 `getWebApplicationContext()` 方法将返回 `null`.
与其冒着在应用程序中获取 `NullPointerExceptions` 的风险,不如使用 `getRequiredWebApplicationContext()`. 当 `ApplicationContext` 丢失时,此方法抛出异常.

一旦引用了 `WebApplicationContext`,就可以按名称或类型检索 bean.  大多数开发人员按名称检索 bean,然后将其转换为其实现的接口之一.

幸运的是,本节中的大多数框架都有更简单的查找 bean 的方法.  它们不仅可以轻松地从 Spring 容器中获取 bean,而且还允许您在其控制器上使用依赖注入.  每个 Web 框架部分都有关于其特定集成策略的更多详细信息.

[[jsf]]
== JSF

JavaServer Faces (JSF) 是 JCP 的标准的、基于组件的、事件驱动的 Web 用户界面框架, 它成为 Jakarta EE 的正式子项目. 也可单独使用,例如 通过将 Mojarra 或 MyFaces 嵌入 Tomcat 中.

请注意,JSF 的最新版本与应用程序服务器中与 CDI 基础结构紧密相关,所以,JSF 某些新的功能只能在这样的环境使用.  Spring 对 JSF 支持不再积极,主要是在现代化较旧的基于 JSF 的应用程序时,存在用于迁移的目的.

Spring 的 JSF 集成中的关键元素是 JSF `ELResolver` 机制.

[[jsf-springbeanfaceselresolver]]
=== Spring Bean Resolver

`SpringBeanFacesELResolver` 是符合 JSF 的 `ELResolver` 实现,与 JSF 和 JSP 使用的标准 Unified EL 集成.  它首先委托 Spring 的 "business context" `WebApplicationContext`,然后委托给底层 JSF 实现的默认解析器.

在配置方面,您可以在JSF `faces-context.xml` 文件中定义 `SpringBeanFacesELResolver`,如以下示例所示:

[source,xml,indent=0,subs="verbatim,quotes"]
----
	<faces-config>
		<application>
			<el-resolver>org.springframework.web.jsf.el.SpringBeanFacesELResolver</el-resolver>
			...
		</application>
	</faces-config>
----

[[jsf-facescontextutils]]
=== 使用 `FacesContextUtils`

在 `faces-config.xml` 中将属性映射到 bean 时,自定义 `ELResolver` 很有效,但有时您可能需要显式获取 bean. {api-spring-framework}/web/jsf/FacesContextUtils.html[`FacesContextUtils`] 类使这很容易.  它类似于 `WebApplicationContextUtils`,除了它采用 `FacesContext` 参数而不是 `ServletContext` 参数.

以下示例显示如何使用 `FacesContextUtils`:

[source,java,indent=0,subs="verbatim,quotes"]
----
	ApplicationContext ctx = FacesContextUtils.getWebApplicationContext(FacesContext.getCurrentInstance());
----

[[struts]]
== Apache Struts

由 Craig McClanahan 发明的 https://struts.apache.org[Struts]  是 Apache Software Foundation 基金主办的一个开源项目. 当时,Struts 1.x 它大大简化了 JSP/Servlet 编程范例,并赢得了许多使用专有框架的开发者.
它简化了编程模型,它是开放源码的(因此是免费的),而且它有一个很大的社区,这使得项目能够在 Java Web 开发者中成长和流行.

作为原始 Struts 1.x 的继承者，请查看 Struts 2.x 或更新的版本以及 Struts 提供的 https://struts.apache.org/plugins/spring/[Spring Plugin]，了解 Struts 附带的内置 Spring 集成.

[[tapestry]]
== Apache Tapestry

https://tapestry.apache.org/[Tapestry] "面向组件" 的框架,用于在 Java 中创建动态,健壮,高度可伸缩的 Web 应用程序.

虽然 Spring 拥有自己<<mvc, 强大的 Web 层>>,但是通过将 Tapestry 用于 Web 用户界面和 Spring 容器用于较低层,构建企业 Java 应用程序有许多独特的优势.

有关更多信息,请参阅 Tapestry 针对 https://tapestry.apache.org/integrating-with-spring-framework.html[Spring 的集成模块]


[[web-integration-resources]]
== 更多资源

以下链接涉及有关本章中描述的各种 Web 框架的更多资源.

*  https://www.oracle.com/java/technologies/javaserverfaces.html[JSF] 主页
*  https://struts.apache.org/[Struts] 主页
*  https://tapestry.apache.org/[Tapestry] 主页
