[[webflux-fn]]
= 功能端点
[.small]#<<web.adoc#webmvc-fn, Web MVC>>#

Spring WebFlux 包含 WebMvc.fn,这是一个轻量级的函数编程模型,其中的函数用于路由和处理请求,而约定则是为不变性而设计的. 它是基于注解的编程模型的替代方案,但可以在同一 <<web-reactive.adoc#webflux-reactive-spring-web>> 上运行.

[[webflux-fn-overview]]
== 概述
[.small]#<<web.adoc#webmvc-fn-overview, Web MVC>>#

在 WebMvc.fn 中,使用 `HandlerFunction` 处理 HTTP 请求: 该函数接受 `ServerRequest` 并返回 `ServerResponse` (例如. `Mono<ServerResponse>`). 作为请求对象的请求都具有不可变的协定,这些协定为 JDK 8 提供了对 HTTP 请求和响应的友好访问.
`HandlerFunction` 等效于基于注解的编程模型中 `@RequestMapping` 方法的主体.

传入的请求通过 `RouterFunction` 路由到处理程序函数: 该函数接受 `ServerRequest` 并返回可选的 `HandlerFunction` (例如 `Mono<HandlerFunction>`) . 当路由器功能匹配时,返回处理程序功能. 否则为空的 Mono. `RouterFunction` 等效于 `@RequestMapping` 注解,但主要区别在于路由器功能不仅提供数据,还提供行为.

`RouterFunctions.route()` 提供了一个有助于构建路由器的路由器构建器,如以下示例所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	import static org.springframework.http.MediaType.APPLICATION_JSON;
	import static org.springframework.web.reactive.function.server.RequestPredicates.*;
	import static org.springframework.web.reactive.function.server.RouterFunctions.route;

	PersonRepository repository = ...
	PersonHandler handler = new PersonHandler(repository);

	RouterFunction<ServerResponse> route = route() // <1>
		.GET("/person/{id}", accept(APPLICATION_JSON), handler::getPerson)
		.GET("/person", accept(APPLICATION_JSON), handler::listPeople)
		.POST("/person", handler::createPerson)
		.build();


	public class PersonHandler {

		// ...

		public Mono<ServerResponse> listPeople(ServerRequest request) {
			// ...
		}

		public Mono<ServerResponse> createPerson(ServerRequest request) {
			// ...
		}

		public Mono<ServerResponse> getPerson(ServerRequest request) {
			// ...
		}
	}
----
<1> 使用 `route()` 创建一个路由.

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val repository: PersonRepository = ...
	val handler = PersonHandler(repository)

	val route = coRouter { // <1>
		accept(APPLICATION_JSON).nest {
			GET("/person/{id}", handler::getPerson)
			GET("/person", handler::listPeople)
		}
		POST("/person", handler::createPerson)
	}


	class PersonHandler(private val repository: PersonRepository) {

		// ...

		suspend fun listPeople(request: ServerRequest): ServerResponse {
			// ...
		}

		suspend fun createPerson(request: ServerRequest): ServerResponse {
			// ...
		}

		suspend fun getPerson(request: ServerRequest): ServerResponse {
			// ...
		}
	}
----
<1> 使用路由器 DSL 创建路由器. 也可以通过 `router { }` 创建响应式

运行 `RouterFunction` 的一种方法是将其转换为 `HttpHandler` 并通过内置 <<web-reactive.adoc#webflux-httphandler, server adapters>> 之一进行安装:

* `RouterFunctions.toHttpHandler(RouterFunction)`
* `RouterFunctions.toHttpHandler(RouterFunction, HandlerStrategies)`

大多数应用程序都可以通过 WebFlux Java 配置运行,请参阅 <<webflux-fn-running>>.

[[webflux-fn-handler-functions]]
== HandlerFunction
[.small]#<<web.adoc#webmvc-fn-handler-functions, Web MVC>>#

`ServerRequest` 和 `ServerResponse` 是不可变的接口,它们提供 JDK 8 友好的 HTTP 请求和响应访问.
请求和响应都提供了 https://www.reactive-streams.org[Reactive Streams] 背压. 请求主体用 Reactor `Flux` 或 `Mono` 表示. 响应主体由任何 Reactive Streams `Publisher` 组成,包括 `Flux` 和 `Mono`. 有关更多信息,请参见 <<web-reactive.adoc#webflux-reactive-libraries, Reactive Libraries>>.
`ServerRequest` 和 `ServerResponse` 提供对 JDK 8 友好的不可变接口

[[webflux-fn-request]]
=== ServerRequest

`ServerRequest` 提供对 HTTP 方法,URI,请求头和查询参数的访问,而通过 `body` 方法提供对主体的访问.

下面的示例将请求正文提取到 `Mono<String>`:

[source,java,role="primary"]
.Java
----
Mono<String> string = request.bodyToMono(String.class);
----
[source,kotlin,role="secondary"]
.Kotlin
----
val string = request.awaitBody<String>()
----

以下示例将主体提取到 `Flux<Person>` (or a `Flow<Person>` in Kotlin),其中 `Person` 对象从某种序列化形式(例如 JSON 或 XML)解码:

[source,java,role="primary"]
.Java
----
Flux<Person> people = request.bodyToFlux(Person.class);
----
[source,kotlin,role="secondary"]
.Kotlin
----
val people = request.bodyToFlow<Person>()
----

前面的示例是使用更通用的 `ServerRequest.body(BodyExtractor)` 的快捷方式,该请求接受 `BodyExtractor` 功能策略接口. 实用程序类 `BodyExtractors` 提供对许多实例的访问. 例如,前面的示例也可以编写如下:

[source,java,role="primary"]
.Java
----
Mono<String> string = request.body(BodyExtractors.toMono(String.class));
Flux<Person> people = request.body(BodyExtractors.toFlux(Person.class));
----
[source,kotlin,role="secondary"]
.Kotlin
----
	val string = request.body(BodyExtractors.toMono(String::class.java)).awaitSingle()
	val people = request.body(BodyExtractors.toFlux(Person::class.java)).asFlow()
----

下面的示例显示如何访问表单数据:

[source,java,role="primary"]
.Java
----
Mono<MultiValueMap<String, String>> map = request.formData();
----
[source,kotlin,role="secondary"]
.Kotlin
----
val map = request.awaitFormData()
----

下面的例子展示了如何访问多部分数据作为一个 map:

[source,java,role="primary"]
.Java
----
Mono<MultiValueMap<String, Part>> map = request.multipartData();
----
[source,kotlin,role="secondary"]
.Kotlin
----
val map = request.awaitMultipartData()
----

以下示例显示了如何以流方式一次访问多个部分:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
Flux<PartEvent> allPartEvents = request.bodyToFlux(PartEvent.class);
allPartsEvents.windowUntil(PartEvent::isLast)
      .concatMap(p -> p.switchOnFirst((signal, partEvents) -> {
          if (signal.hasValue()) {
              PartEvent event = signal.get();
              if (event instanceof FormPartEvent formEvent) {
                  String value = formEvent.value();
                  // handle form field
              }
              else if (event instanceof FilePartEvent fileEvent) {
                  String filename = fileEvent.filename();
                  Flux<DataBuffer> contents = partEvents.map(PartEvent::content);
                  // handle file upload
              }
              else {
                  return Mono.error(new RuntimeException("Unexpected event: " + event));
              }
          }
          else {
              return partEvents; // either complete or error signal
          }
      }));
----

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
val parts = request.bodyToFlux<PartEvent>()
allPartsEvents.windowUntil(PartEvent::isLast)
    .concatMap {
        it.switchOnFirst { signal, partEvents ->
            if (signal.hasValue()) {
                val event = signal.get()
                if (event is FormPartEvent) {
                    val value: String = event.value();
                    // handle form field
                } else if (event is FilePartEvent) {
                    val filename: String = event.filename();
                    val contents: Flux<DataBuffer> = partEvents.map(PartEvent::content);
                    // handle file upload
                } else {
                    return Mono.error(RuntimeException("Unexpected event: " + event));
                }
            } else {
                return partEvents; // either complete or error signal
            }
        }
    }
}
----

请注意，`PartEvent` 对象的主体内容必须完全 consumed, relayed, 或 released ，以避免内存泄漏。


[[webflux-fn-response]]
=== ServerResponse

`ServerResponse` 提供对 HTTP 响应的访问,并且由于它是不可变的,因此您可以使用 `build` 方法来创建它.  您可以使用构建器来设置响应状态,添加响应头或提供正文.  以下示例使用 JSON 内容创建 200 (OK) 响应:


[source,java,role="primary"]
.Java
----
Mono<Person> person = ...
ServerResponse.ok().contentType(MediaType.APPLICATION_JSON).body(person, Person.class);
----
[source,kotlin,role="secondary"]
.Kotlin
----
val person: Person = ...
ServerResponse.ok().contentType(MediaType.APPLICATION_JSON).bodyValue(person)
----

以下示例显示了如何使用 `Location` 头且不包含主体来构建 201 (CREATED) 响应:

[source,java,role="primary"]
.Java
----
URI location = ...
ServerResponse.created(location).build();
----
[source,kotlin,role="secondary"]
.Kotlin
----
val location: URI = ...
ServerResponse.created(location).build()
----

根据所使用的编解码器,可以传递提示参数以自定义主体的序列化或反序列化方式. 例如,要指定 https://www.baeldung.com/jackson-json-view-annotation[Jackson JSON view]:

[source,java,role="primary"]
.Java
----
ServerResponse.ok().hint(Jackson2CodecSupport.JSON_VIEW_HINT, MyJacksonView.class).body(...);
----
[source,kotlin,role="secondary"]
.Kotlin
----
ServerResponse.ok().hint(Jackson2CodecSupport.JSON_VIEW_HINT, MyJacksonView::class.java).body(...)
----


[[webflux-fn-handler-classes]]
=== 处理 Classes

我们可以将处理程序函数编写为 lambda,如以下示例所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
HandlerFunction<ServerResponse> helloWorld =
  request -> ServerResponse.ok().bodyValue("Hello World");
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
val helloWorld = HandlerFunction<ServerResponse> { ServerResponse.ok().bodyValue("Hello World") }
----

这很方便,但是在应用程序中我们需要多个功能,并且多个内联 lambda 可能会变得凌乱.  因此,将相关的处理程序功能分组到一个处理程序类中很有用,该类的作用与基于注解的应用程序中的 `@Controller` 相似.  例如,以下类暴露了 reactive `Person`  存储库:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
import static org.springframework.http.MediaType.APPLICATION_JSON;
import static org.springframework.web.reactive.function.server.ServerResponse.ok;

public class PersonHandler {

	private final PersonRepository repository;

	public PersonHandler(PersonRepository repository) {
		this.repository = repository;
	}

	public Mono<ServerResponse> listPeople(ServerRequest request) { // <1>
		Flux<Person> people = repository.allPeople();
		return ok().contentType(APPLICATION_JSON).body(people, Person.class);
	}

	public Mono<ServerResponse> createPerson(ServerRequest request) { // <2>
		Mono<Person> person = request.bodyToMono(Person.class);
		return ok().build(repository.savePerson(person));
	}

	public Mono<ServerResponse> getPerson(ServerRequest request) { // <3>
		int personId = Integer.valueOf(request.pathVariable("id"));
		return repository.getPerson(personId)
			.flatMap(person -> ok().contentType(APPLICATION_JSON).bodyValue(person))
			.switchIfEmpty(ServerResponse.notFound().build());
	}
}
----
<1> `listPeople` 是一个处理函数,它以JSON格式返回存储库中找到的所有 `Person` 对象.
<2> `createPerson` 是一个处理函数,用于存储请求正文中包含的新 `Person` 请注意 `PersonRepository.savePerson(Person)` 返回 `Mono<Void>`: 一个空的 `Mono` ,当从请求中读取并存储此人时,它将发出完成信号.
因此,当接收到完成信号时(即,保存 `Person` 时),我们使用 `build(Publisher<Void>)` 方法发送响应.
<3> `getPerson` 是一个处理程序函数,它返回由 `id` 路径变量标识的单个人.  我们从存储库中检索该 `Person` 并创建一个 JSON 响应(如果找到) . 如果未找到,我们使用  `switchIfEmpty(Mono<T>)`  返回404 Not Found响应.

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	class PersonHandler(private val repository: PersonRepository) {

		suspend fun listPeople(request: ServerRequest): ServerResponse { // <1>
			val people: Flow<Person> = repository.allPeople()
			return ok().contentType(APPLICATION_JSON).bodyAndAwait(people);
		}

		suspend fun createPerson(request: ServerRequest): ServerResponse { // <2>
			val person = request.awaitBody<Person>()
			repository.savePerson(person)
			return ok().buildAndAwait()
		}

		suspend fun getPerson(request: ServerRequest): ServerResponse { // <3>
			val personId = request.pathVariable("id").toInt()
			return repository.getPerson(personId)?.let { ok().contentType(APPLICATION_JSON).bodyValueAndAwait(it) }
					?: ServerResponse.notFound().buildAndAwait()

		}
	}
----
<1> `listPeople` 是一个处理函数,它以 JSON 格式返回存储库中找到的所有 `Person` 对象.
<2> `createPerson` 是一个处理函数,用于存储请求正文中包含的新 `Person`. 请注意, `PersonRepository.savePerson(Person)` 是一个没有返回类型的函数.
<3> `getPerson` 是一个处理程序函数,它返回由 `id` 路径变量标识的单个人.  我们从存储库中检索该 `Person` 并创建一个 JSON 响应(如果找到) .  如果未找到,我们将返回 404 Not Found 响应.


[[webflux-fn-handler-validation]]
=== Validation

功能端点可以使用 Spring 的<<core.adoc#validation, 验证工具>>将验证应用于请求正文.  例如,给定 `Person` 的自定义 Spring <<core.adoc#validation, Validator>> 实现:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	public class PersonHandler {

		private final Validator validator = new PersonValidator(); // <1>

		// ...

		public Mono<ServerResponse> createPerson(ServerRequest request) {
			Mono<Person> person = request.bodyToMono(Person.class).doOnNext(this::validate); // <2>
			return ok().build(repository.savePerson(person));
		}

		private void validate(Person person) {
			Errors errors = new BeanPropertyBindingResult(person, "person");
			validator.validate(person, errors);
			if (errors.hasErrors()) {
				throw new ServerWebInputException(errors.toString()); // <3>
			}
		}
	}
----
<1> 创建 `Validator` 实例.
<2> 应用 validation.
<3> 引发 400 响应的异常.

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	class PersonHandler(private val repository: PersonRepository) {

		private val validator = PersonValidator() // <1>

		// ...

		suspend fun createPerson(request: ServerRequest): ServerResponse {
			val person = request.awaitBody<Person>()
			validate(person) // <2>
			repository.savePerson(person)
			return ok().buildAndAwait()
		}

		private fun validate(person: Person) {
			val errors: Errors = BeanPropertyBindingResult(person, "person");
			validator.validate(person, errors);
			if (errors.hasErrors()) {
				throw ServerWebInputException(errors.toString()) // <3>
			}
		}
	}
----
<1> 创建 `Validator` 实例.
<2> 应用 validation.
<3> 引发 400 响应的异常.

处理程序还可以通过基于 `LocalValidatorFactoryBean` 创建和注入全局 `Validator` 实例来使用标准 Bean 验证 API(JSR-303) .  请参阅<<core.adoc#validation-beanvalidation, Spring Validation>>.

[[webflux-fn-router-functions]]
== `RouterFunction`
[.small]#<<web.adoc#webmvc-fn-router-functions, Web MVC>>#

路由器功能用于将请求路由到相应的 `HandlerFunction`.  通常,您不是自己编写路由器功能,而是使用 `RouterFunctions` 实用工具类上的方法来创建一个.
`RouterFunctions.route()`(无参数) 为您提供了流式的生成器,用于创建路由器功能,而 `RouterFunctions.route(RequestPredicate,HandlerFunction)` 提供了直接创建路由器的方法.

通常,建议使用 `route()` 构建器,因为它为典型的映射方案提供了便捷的快捷方式,而无需发现静态导入.  例如,路由器功能构建器提供了 `GET(String, HandlerFunction)` 方法来为GET请求创建映射.  和 `POST(String, HandlerFunction)` 进行POST.

除了基于 HTTP 方法的映射外,路由构建器还提供了一种在映射到请求时引入其他断言的方法.  对于每个 HTTP 方法,都有一个重载的变体,它以 `RequestPredicate` 作为参数,尽管可以表达其他约束.

[[webflux-fn-predicates]]
=== 断言

您可以编写自己的 `RequestPredicate`,但是 `RequestPredicates` 实用程序类根据请求路径,HTTP 方法,内容类型等提供常用的实现.  以下示例使用请求断言基于 `Accept` 头创建约束:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	RouterFunction<ServerResponse> route = RouterFunctions.route()
		.GET("/hello-world", accept(MediaType.TEXT_PLAIN),
			request -> ServerResponse.ok().bodyValue("Hello World")).build();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val route = coRouter {
		GET("/hello-world", accept(TEXT_PLAIN)) {
            ServerResponse.ok().bodyValueAndAwait("Hello World")
        }
	}
----

您可以使用以下命令组合多个请求断言

* `RequestPredicate.and(RequestPredicate)` -- 两个都必须匹配
* `RequestPredicate.or(RequestPredicate)` -- 只需要匹配一个

`RequestPredicates` 中的许多断言都是组成的.
例如,`RequestPredicates.GET(String)` 由  `RequestPredicates.method(HttpMethod)` 和 `RequestPredicates.path(String)` 组成.  上面显示的示例还使用了两个请求断言,因为构建器在内部使用 `RequestPredicates.GET` 并将其与 `accept` 断言组合在一起.

[[webflux-fn-routes]]
=== 路由

路由器功能按顺序评估: 如果第一个路由不匹配,则评估第二个路由,依此类推.  因此,在通用路由之前声明更具体的路由是有意义的.当将路由器功能注册为 Spring Bean 时， 这一点也很重要， 这将在后面进行描述.   请注意,此行为不同于基于注解的编程模型,在该模型中,将自动选择 "最特定" 的控制器方法.

使用路由器功能生成器时,所有定义的路由都组成一个 `RouterFunction`,从 `build()` 返回.  还有其他方法可以将多个路由器功能组合在一起:

*  `RouterFunctions.route()` 构建器上添加 `add(RouterFunction)`
* `RouterFunction.and(RouterFunction)`
* `RouterFunction.andRoute(RequestPredicate, HandlerFunction)` -- — Router带有嵌套 `RouterFunctions.route()` 的 `RouterFunction.and()` 的快捷方式.

以下示例显示了四种路由的组成:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
import static org.springframework.http.MediaType.APPLICATION_JSON;
import static org.springframework.web.reactive.function.server.RequestPredicates.*;

PersonRepository repository = ...
PersonHandler handler = new PersonHandler(repository);

RouterFunction<ServerResponse> otherRoute = ...

RouterFunction<ServerResponse> route = route()
	.GET("/person/{id}", accept(APPLICATION_JSON), handler::getPerson) // <1>
	.GET("/person", accept(APPLICATION_JSON), handler::listPeople) // <2>
	.POST("/person", handler::createPerson) // <3>
	.add(otherRoute) // <4>
	.build();
----
<1>  带有与JSON匹配的 `Accept` 头的 `GET /person/{id}` 被路由到 `PersonHandler.getPerson`
<2>  带有与JSON匹配的 `Accept` 头的 `GET /person` 被路由到 `PersonHandler.listPeople`
<3>  没有其他断言的 POST `POST /person` 被路由到 `PersonHandler.createPerson`
<4> `otherRoute` 是在其他地方创建的路由器功能,并将其添加到构建的路由中.

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	import org.springframework.http.MediaType.APPLICATION_JSON

	val repository: PersonRepository = ...
	val handler = PersonHandler(repository);

	val otherRoute: RouterFunction<ServerResponse> = coRouter {  }

	val route = coRouter {
		GET("/person/{id}", accept(APPLICATION_JSON), handler::getPerson) // <1>
		GET("/person", accept(APPLICATION_JSON), handler::listPeople) // <2>
		POST("/person", handler::createPerson) // <3>
	}.and(otherRoute) // <4>
----
<1>  带有与JSON匹配的 `Accept` 头的 `GET /person/{id}` 被路由到 `PersonHandler.getPerson`
<2>  带有与JSON匹配的 `Accept` 头的 `GET /person` 被路由到 `PersonHandler.listPeople`
<3>  没有其他断言的 POST `POST /person` 被路由到 `PersonHandler.createPerson`
<4> `otherRoute` 是在其他地方创建的路由器功能,并将其添加到构建的路由中.

=== 嵌入路由

一组路由功能通常具有一个共享断言,例如一个共享路径. 在上面的示例中,共享断言将是与 `/person` 匹配的路径断言,由三个路由使用.  使用注解时,您可以通过使用映射到 `/person` 的类型级别 `@RequestMapping` 注解来删除此重复项.
在 WebMvc.fn 中,可以通过路由器功能构建器上的 `path` 方法共享路径断言.  例如,以上示例的最后几行可以通过使用嵌套路由以以下方式进行改进:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
RouterFunction<ServerResponse> route = route()
	.path("/person", builder -> builder // <1>
		.GET("/{id}", accept(APPLICATION_JSON), handler::getPerson)
		.GET(accept(APPLICATION_JSON), handler::listPeople)
		.POST(handler::createPerson))
	.build();
----
<1> 请注意,`path` 的第二个参数是使用路由器构建器的使用者.

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val route = coRouter { // <1>
		"/person".nest {
			GET("/{id}", accept(APPLICATION_JSON), handler::getPerson)
			GET(accept(APPLICATION_JSON), handler::listPeople)
			POST(handler::createPerson)
		}
	}
----
<1> 使用 Coroutines 路由器 DSL 创建路由器； 响应式替代方案也可通过 `router { }` 获得。


尽管基于路径的嵌套是最常见的,但是您可以通过使用构建器上的 `nest` 方法来嵌套在任何种类的断言上.  上面的内容仍然包含一些以共享的 `Accept-header` 断言形式出现的重复.  通过将 `nest` 方法与 `accept` 一起使用,我们可以进一步改进:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	RouterFunction<ServerResponse> route = route()
		.path("/person", b1 -> b1
			.nest(accept(APPLICATION_JSON), b2 -> b2
				.GET("/{id}", handler::getPerson)
				.GET(handler::listPeople))
			.POST(handler::createPerson))
		.build();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val route = coRouter {
		"/person".nest {
			accept(APPLICATION_JSON).nest {
				GET("/{id}", handler::getPerson)
				GET(handler::listPeople)
				POST(handler::createPerson)
			}
		}
	}
----


[[webflux-fn-running]]
== 运行服务器
[.small]#<<web.adoc#webmvc-fn-running, Web MVC>>#

如何在HTTP服务器中运行路由器功能? 一个简单的选择是转换路由器,使用以下其中一种功能将其作用于 `HttpHandler`:

* `RouterFunctions.toHttpHandler(RouterFunction)`
* `RouterFunctions.toHttpHandler(RouterFunction, HandlerStrategies)`

然后,可以通过遵循 `HttpHandler` 来获取特定于服务器的指令,将返回的 <<web-reactive.adoc#webflux-httphandler, HttpHandler>> 与许多服务器适配器一起使用.

Spring Boot 也使用了一个更典型的选项,即通过 <<web-reactive.adoc#webflux-config>> 使用基于 <<web-reactive.adoc#webflux-dispatcher-handler, `DispatcherHandler`>> 的设置来运行,该配置使用 Spring 配置声明处理请求所需的组件. WebFlux Java 配置声明以下基础结构组件以支持功能端点:

* `RouterFunctionMapping`: 在 Spring 配置中检测一个或多个 `RouterFunction<?>` bean,通过 `RouterFunction.andOther` 组合它们  <<core.adoc#beans-factory-ordered, orders them>> ,并将请求路由到生成的组成 `RouterFunction`.
* `HandlerFunctionAdapter`: 简单的适配器,使 `DispatcherHandler` 调用映射到请求的 `HandlerFunction`.
* `ServerResponseResultHandler`: 通过调用 `ServerResponse` 的 `writeTo` 方法来处理 `HandlerFunction` 调用的结果.

前面的组件使功能端点适合于 `DispatcherHandler` 请求处理生命周期,并且(可能) 与带注解的控制器(如果已声明) 并排运行.  这也是 Spring Boot WebFlux 启动程序如何启用功能端点的方式.

以下示例显示了 WebFlux Java 配置(有关如何运行它,请参见 <<web-reactive.adoc#webflux-dispatcher-handler, DispatcherHandler>>):

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@Configuration
	@EnableWebFlux
	public class WebConfig implements WebFluxConfigurer {

		@Bean
		public RouterFunction<?> routerFunctionA() {
			// ...
		}

		@Bean
		public RouterFunction<?> routerFunctionB() {
			// ...
		}

		// ...

		@Override
		public void configureHttpMessageCodecs(ServerCodecConfigurer configurer) {
			// configure message conversion...
		}

		@Override
		public void addCorsMappings(CorsRegistry registry) {
			// configure CORS...
		}

		@Override
		public void configureViewResolvers(ViewResolverRegistry registry) {
			// configure view resolution for HTML rendering...
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@Configuration
	@EnableWebFlux
	class WebConfig : WebFluxConfigurer {

		@Bean
		fun routerFunctionA(): RouterFunction<*> {
			// ...
		}

		@Bean
		fun routerFunctionB(): RouterFunction<*> {
			// ...
		}

		// ...

		override fun configureHttpMessageCodecs(configurer: ServerCodecConfigurer) {
			// configure message conversion...
		}

		override fun addCorsMappings(registry: CorsRegistry) {
			// configure CORS...
		}

		override fun configureViewResolvers(registry: ViewResolverRegistry) {
			// configure view resolution for HTML rendering...
		}
	}
----


[[webflux-fn-handler-filter-function]]
== 过滤器处理程序功能
[.small]#<<web.adoc#webmvc-fn-handler-filter-function, Web MVC>>#

您可以使用路由功能构建器上的 `before`,`after` 或 `filter` 方法来过滤处理程序函数.  使用注解,可以通过使用 `@ControllerAdvice`,`ServletFilter` 或同时使用两者来实现类似的功能.
该过滤器将应用于构建器构建的所有路由.  这意味着在嵌套路由中定义的过滤器不适用于 "top-level"  路由.  例如,考虑以下示例:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	RouterFunction<ServerResponse> route = route()
		.path("/person", b1 -> b1
			.nest(accept(APPLICATION_JSON), b2 -> b2
				.GET("/{id}", handler::getPerson)
				.GET(handler::listPeople)
				.before(request -> ServerRequest.from(request) // <1>
					.header("X-RequestHeader", "Value")
					.build()))
			.POST(handler::createPerson))
		.after((request, response) -> logResponse(response)) // <2>
		.build();
----
<1> 添加自定义请求头的 `before` 过滤器仅应用于两个 GET 路由.
<2> 记录响应的 `after` 过滤器将应用于所有路由,包括嵌套路由.

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val route = router {
		"/person".nest {
			GET("/{id}", handler::getPerson)
			GET("", handler::listPeople)
			before { // <1>
				ServerRequest.from(it)
						.header("X-RequestHeader", "Value").build()
			}
			POST(handler::createPerson)
			after { _, response -> // <2>
				logResponse(response)
			}
		}
	}
----
<1> 添加自定义请求头的 `before` 过滤器仅应用于两个GET路由.
<2> 记录响应的 `after` 过滤器将应用于所有路由,包括嵌套路由.

路由器构建器上的 `filter` 方法采用 `HandlerFilterFunction`: 该函数采用 `ServerRequest` 和 `HandlerFunction` 并返回 `ServerResponse`.  `handler` 函数参数代表链中的下一个元素.  这通常是路由到的处理程序,但是如果应用了多个,它也可以是另一个过滤器.

现在,我们可以在路由中添加一个简单的安全过滤器,假设我们拥有一个可以确定是否允许特定路径的 `SecurityManager`.  以下示例显示了如何执行此操作:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	SecurityManager securityManager = ...

	RouterFunction<ServerResponse> route = route()
		.path("/person", b1 -> b1
			.nest(accept(APPLICATION_JSON), b2 -> b2
				.GET("/{id}", handler::getPerson)
				.GET(handler::listPeople))
			.POST(handler::createPerson))
		.filter((request, next) -> {
			if (securityManager.allowAccessTo(request.path())) {
				return next.handle(request);
			}
			else {
				return ServerResponse.status(UNAUTHORIZED).build();
			}
		})
		.build();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val securityManager: SecurityManager = ...

	val route = router {
			("/person" and accept(APPLICATION_JSON)).nest {
				GET("/{id}", handler::getPerson)
				GET("", handler::listPeople)
				POST(handler::createPerson)
				filter { request, next ->
					if (securityManager.allowAccessTo(request.path())) {
						next(request)
					}
					else {
						status(UNAUTHORIZED).build();
					}
				}
			}
		}
----

前面的示例演示了调用 `next.handle(ServerRequest)` 是可选的.  当允许访问时,我们仅允许执行处理函数.

除了在路由器功能构建器上使用 `filter` 方法之外,还可以通过 `RouterFunction.filter(HandlerFilterFunction)` 将过滤器应用于现有路由器功能.

NOTE: 通过专用的 <<webflux-cors.adoc#webflux-cors-webfilter, `CorsWebFilter`>>. 提供对功能端点的 CORS 支持.