[[webflux-websocket]]
= WebSockets
[.small]#<<web.adoc#websocket, Same as in the Servlet stack>>#

这一部分介绍 Spring 框架在 reactive-stack 应用程序中对 WebSocket 消息传递的支持,

include::websocket-intro.adoc[leveloffset=+1]

[[webflux-websocket-server]]
== WebSocket API
[.small]#<<web.adoc#websocket-server, Same as in the Servlet stack>>#

Spring Framework 提供了一个 WebSocket API,您可以使用它来编写处理 WebSocket 消息的客户端和服务器端应用程序.

[[webflux-websocket-server-handler]]
=== Server
[.small]#<<web.adoc#websocket-server-handler, Same as in the Servlet stack>>#

创建 `WebSocket` 服务器,首先创建一个 `WebSocketHandler` 如下

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	import org.springframework.web.reactive.socket.WebSocketHandler;
	import org.springframework.web.reactive.socket.WebSocketSession;

	public class MyWebSocketHandler implements WebSocketHandler {

		@Override
		public Mono<Void> handle(WebSocketSession session) {
			// ...
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	import org.springframework.web.reactive.socket.WebSocketHandler
	import org.springframework.web.reactive.socket.WebSocketSession

	class MyWebSocketHandler : WebSocketHandler {

		override fun handle(session: WebSocketSession): Mono<Void> {
			// ...
		}
	}
----

然后,您可以将其映射到 URL ,如以下示例所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@Configuration
	class WebConfig {

		@Bean
		public HandlerMapping handlerMapping() {
			Map<String, WebSocketHandler> map = new HashMap<>();
			map.put("/path", new MyWebSocketHandler());
			int order = -1; // before annotated controllers

			return new SimpleUrlHandlerMapping(map, order);
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@Configuration
	class WebConfig {

		@Bean
		fun handlerMapping(): HandlerMapping {
			val map = mapOf("/path" to MyWebSocketHandler())
			val order = -1 // before annotated controllers

			return SimpleUrlHandlerMapping(map, order)
		}
	}
----

如果使用 <<web-reactive.adoc#webflux-config, WebFlux Config>> 则不需要进行下一步操作, 否则， 如果不使用 WebFlux config 则需要声明一个 `WebSocketHandlerAdapter` 如下:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@Configuration
	class WebConfig {

		// ...

		@Bean
		public WebSocketHandlerAdapter handlerAdapter() {
			return new WebSocketHandlerAdapter();
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@Configuration
	class WebConfig {

		// ...

		@Bean
		fun handlerAdapter() =  WebSocketHandlerAdapter()
	}
----



[[webflux-websockethandler]]
=== `WebSocketHandler`

`WebSocketHandler` 的 `handle` 方法采用 `WebSocketSession` 并返回  `Mono<Void>` 来指示会话的应用程序处理何时完成. 通过两个流处理会话,一个流用于入站消息,一个流用于出站消息. 下表描述了两种处理流的方法:

[options="header"]
|===
| `WebSocketSession` 方法 | 描述

| `Flux<WebSocketMessage> receive()`
| 提供对入站消息流的访问,并在关闭连接时完成.

| `Mono<Void> send(Publisher<WebSocketMessage>)`
| 获取传出消息的源,编写消息,然后返回 `Mono<Void>`,该源在完成源并完成写入后即完成.

|===

`WebSocketHandler` 必须将入站和出站流组成一个统一的流,并返回反映该流完成情况的  `Mono<Void>` . 根据应用程序要求,统一流程在以下情况下完成:

* 入站或出站消息流都已完成.
* 入站流完成(即,连接已关闭),而出站流是无限的.
* 在选定的时间点,通过 `WebSocketSession` 的 `close` 方法.

将入站和出站消息流组合在一起时,无需检查连接是否打开,因为 "响应流” 信号会终止活动. 入站流接收完成或错误信号,而出站流接收取消信号.

处理程序最基本的实现是处理入站流的实现. 以下示例显示了这样的实现:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	class ExampleHandler implements WebSocketHandler {

		@Override
		public Mono<Void> handle(WebSocketSession session) {
			return session.receive()			// <1>
					.doOnNext(message -> {
						// ...					// <2>
					})
					.concatMap(message -> {
						// ...					// <3>
					})
					.then();					// <4>
		}
	}
----
<1> 访问入站消息流.
<2> 对每条消息进行处理.
<3> 执行使用消息内容的嵌套异步操作.
<4> 返回接收完成后完成的 `Mono<Void>` .

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	class ExampleHandler : WebSocketHandler {

		override fun handle(session: WebSocketSession): Mono<Void> {
			return session.receive()            // <1>
					.doOnNext {
						// ...					// <2>
					}
					.concatMap {
						// ...					// <3>
					}
					.then()                     // <4>
		}
	}
----
<1> 访问入站消息流.
<2> 对每条消息进行处理.
<3> 执行使用消息内容的嵌套异步操作.
<4> 返回接收完成后完成的 `Mono<Void>` .


TIP: 对于嵌套的异步操作,您可能需要在使用池化数据缓冲区(例如 Netty)的基础服务器上调用  `message.retain()` . 否则,在您有机会读取数据之前,可能会释放数据缓冲区. 有关更多背景信息,请参见 <<core.adoc#databuffers, 数据缓冲区和编解码器>>.

以下实现将入站和出站流组合在一起:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	class ExampleHandler implements WebSocketHandler {

		@Override
		public Mono<Void> handle(WebSocketSession session) {

			Flux<WebSocketMessage> output = session.receive()				// <1>
					.doOnNext(message -> {
						// ...
					})
					.concatMap(message -> {
						// ...
					})
					.map(value -> session.textMessage("Echo " + value));	// <2>

			return session.send(output);									// <3>
		}
	}
----
<1> 处理入站消息流.
<2> 创建出站消息,产生合并流.
<3> 返回在我们继续接收时未完成的 `Mono<Void>` .

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	class ExampleHandler : WebSocketHandler {

		override fun handle(session: WebSocketSession): Mono<Void> {

			val output = session.receive()                      // <1>
					.doOnNext {
						// ...
					}
					.concatMap {
						// ...
					}
					.map { session.textMessage("Echo $it") }    // <2>

			return session.send(output)                         // <3>
		}
	}
----
<1> 处理入站消息流.
<2> 创建出站消息,产生合并流.
<3> 返回在我们继续接收时未完成的 `Mono<Void>` .


入站和出站流可以是独立的,并且只能为了完成而加入,如以下示例所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	class ExampleHandler implements WebSocketHandler {

		@Override
		public Mono<Void> handle(WebSocketSession session) {

			Mono<Void> input = session.receive()								<1>
					.doOnNext(message -> {
						// ...
					})
					.concatMap(message -> {
						// ...
					})
					.then();

			Flux<String> source = ... ;
			Mono<Void> output = session.send(source.map(session::textMessage));	<2>

			return Mono.zip(input, output).then();								<3>
		}
	}
----
<1> 处理入站消息流.
<2> 发送外发消息.
<3> 加入流,并返回一个  `Mono<Void>` ,该流在任一流结束时完成.

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	class ExampleHandler : WebSocketHandler {

		override fun handle(session: WebSocketSession): Mono<Void> {

			val input = session.receive()									// <1>
					.doOnNext {
						// ...
					}
					.concatMap {
						// ...
					}
					.then()

			val source: Flux<String> = ...
			val output = session.send(source.map(session::textMessage))		// <2>

			return Mono.zip(input, output).then()							// <3>
		}
	}
----
<1> 处理入站消息流.
<2> 发送外发消息.
<3> 加入流,并返回一个  `Mono<Void>` ,该流在任一流结束时完成.

[[webflux-websocket-databuffer]]
=== `DataBuffer`

`DataBuffer` 是 WebFlux 中字节缓冲区的表示形式. 该参考书的 Spring Core 部分在有关<<core#databuffers, 数据缓冲区和编解码器>>的部分中有更多内容. 要理解的关键点是,在诸如 Netty 之类的某些服务器上,字节缓冲区是池化的,并且对引用计数进行计数,并且在消耗字节缓冲时必须将其释放以避免内存泄漏.

在Netty上运行时,如果应用程序希望保留输入数据缓冲区以确保不释放它们,则必须使用 `DataBufferUtils.retain(dataBuffer)`,并在使用完缓冲区后随后使用  `DataBufferUtils.release(dataBuffer)`.

[[webflux-websocket-server-handshake]]
=== 握手
[.small]#<<web.adoc#websocket-server-handshake, Same as in the Servlet stack>>#

`WebSocketHandlerAdapter` 委托给 `WebSocketService`. 默认情况下,它是 `HandshakeWebSocketService` 的实例,该实例对 `WebSocket` 请求执行基本检查,然后对所使用的服务器使用 `RequestUpgradeStrategy`. 当前,内置了对 Reactor Netty,Tomcat,Jetty 和 Undertow 的支持.

`HandshakeWebSocketService` 暴露了一个 `sessionAttributePredicate` 属性,该属性允许设置 `Predicate<String>` 从 `WebSession` 中提取属性并将其插入到 `WebSocketSession` 的属性中.

[[webflux-websocket-server-config]]
=== Server 配置
[.small]#<<web.adoc#websocket-server-runtime-configuration, Same as in the Servlet stack>>#

每个服务器的 `RequestUpgradeStrategy` 暴露了可用于基础 WebSocket 引擎的 WebSocket 相关配置选项.
使用 WebFlux Java 配置时， 您可以自定义这样的属性， 如 <<web-reactive.adoc#webflux-config-websocket-service, WebFlux Config>> 的相应部分所示， 否则， 如果不使用 WebFlux 配置， 请使用下面的配置:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@Configuration
	class WebConfig {

		@Bean
		public WebSocketHandlerAdapter handlerAdapter() {
			return new WebSocketHandlerAdapter(webSocketService());
		}

		@Bean
		public WebSocketService webSocketService() {
			TomcatRequestUpgradeStrategy strategy = new TomcatRequestUpgradeStrategy();
			strategy.setMaxSessionIdleTimeout(0L);
			return new HandshakeWebSocketService(strategy);
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@Configuration
	class WebConfig {

		@Bean
		fun handlerAdapter() =
				WebSocketHandlerAdapter(webSocketService())

		@Bean
		fun webSocketService(): WebSocketService {
			val strategy = TomcatRequestUpgradeStrategy().apply {
				setMaxSessionIdleTimeout(0L)
			}
			return HandshakeWebSocketService(strategy)
		}
	}
----

检查服务器的升级策略,以查看可用的选项. 当前,只有 Tomcat 和 Jetty 暴露了此类选项.

[[webflux-websocket-server-cors]]
=== CORS
[.small]#<<web.adoc#websocket-server-allowed-origins, Same as in the Servlet stack>>#

配置 CORS 并限制对 `WebSocket` 端点的访问的最简单方法是让 `WebSocketHandler` 实现 `CorsConfigurationSource` 并返回带有允许的源, header 和其他详细信息的 `CorsConfiguration`.
如果无法执行此操作,则还可以在 `SimpleUrlHandler` 上设置 `corsConfigurations` 属性,以通过 URL 模式指定 CORS 设置. 如果同时指定了两者,则使用 `CorsConfiguration` 上的 `combine` 方法将它们合并.

[[webflux-websocket-client]]
=== Client

Spring WebFlux 为 `WebSocketClient` 抽象提供了 Reactor Netty,Tomcat,Jetty,Undertow 和标准 Java(即 JSR-356)的实现.

NOTE: Tomcat 客户端实际上是标准 Java 客户端的扩展,在 `WebSocketSession` 处理中具有一些额外功能,以利用特定于 Tomcat 的 API 暂停接收消息以产生反压.

要启动 WebSocket 会话,您可以创建客户端的实例并使用其 `execute` 方法:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	WebSocketClient client = new ReactorNettyWebSocketClient();

	URI url = new URI("ws://localhost:8080/path");
	client.execute(url, session ->
			session.receive()
					.doOnNext(System.out::println)
					.then());
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	val client = ReactorNettyWebSocketClient()

			val url = URI("ws://localhost:8080/path")
			client.execute(url) { session ->
				session.receive()
						.doOnNext(::println)
				.then()
			}
----

一些客户端(如 Jetty)实现了 `Lifecycle`,需要先停止和启动,然后才能使用它们. 所有客户端都具有与基础 WebSocket 客户端的配置相关的构造器选项.