[[webflux-view]]
= 视图技术
[.small]#<<web.adoc#mvc-view, Web MVC>>#

Spring WebFlux 中视图技术的使用是可配置的. 是否决定使用 Thymeleaf,FreeMarker 或其他某种视图技术,主要取决于配置更改. 本章介绍了与 Spring WebFlux 集成的视图技术. 我们假设您已经熟悉 <<webflux-viewresolution>>.

[[webflux-view-thymeleaf]]
== Thymeleaf
[.small]#<<web.adoc#mvc-view-thymeleaf, Web MVC>>#


Thymeleaf 是一个现代服务器端 Java 模板引擎,它强调可以通过双击在浏览器中预览的自然 HTML 模板,这对于 UI 模板的独立工作(例如,由设计人员) 非常有用,而无需运行服务器.  如果您想要替换JSP, https://www.thymeleaf.org/[Thymeleaf] 提供了一组最广泛的功能,使这种转换更容易.  Thymeleaf 积极开发和维护.  有关更完整的介绍,请参阅Thymeleaf项目主页.

Thymeleaf 与 Spring WebFlux 的集成由 Thymeleaf 项目管理.  配置涉及一些 bean 声明, 例如 `SpringResourceTemplateResolver`, `SpringWebFluxTemplateEngine`, 和 `ThymeleafReactiveViewResolver`.
有关详细信息,请参阅 https://www.thymeleaf.org/documentation.html[Thymeleaf+Spring] 和 https://web.archive.org/web/20210623051330/http%3A//forum.thymeleaf.org/Thymeleaf-3-0-8-JUST-PUBLISHED-td4030687.html[announcement]集成公告.

[[webflux-view-freemarker]]
== FreeMarker
[.small]#<<web.adoc#mvc-view-freemarker, Web MVC>>#

https://freemarker.apache.org/[Apache FreeMarker]  是一个模板引擎,用于生成从 HTML 到电子邮件和其他的任何类型的文本输出.  Spring Framework 有一个内置的集成,可以将 Spring WebFlux 与 FreeMarker 模板结合使用.

[[webflux-view-freemarker-contextconfig]]
=== View 配置
[.small]#<<web.adoc#mvc-view-freemarker-contextconfig, Web MVC>>#

以下示例显示如何将 FreeMarker 配置为视图技术:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@Configuration
	@EnableWebFlux
	public class WebConfig implements WebFluxConfigurer {

		@Override
		public void configureViewResolvers(ViewResolverRegistry registry) {
			registry.freeMarker();
		}

		// Configure FreeMarker...

		@Bean
		public FreeMarkerConfigurer freeMarkerConfigurer() {
			FreeMarkerConfigurer configurer = new FreeMarkerConfigurer();
			configurer.setTemplateLoaderPath("classpath:/templates/freemarker");
			return configurer;
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@Configuration
	@EnableWebFlux
	class WebConfig : WebFluxConfigurer {

		override fun configureViewResolvers(registry: ViewResolverRegistry) {
			registry.freeMarker()
		}

		// Configure FreeMarker...

		@Bean
		fun freeMarkerConfigurer() = FreeMarkerConfigurer().apply {
			setTemplateLoaderPath("classpath:/templates/freemarker")
		}
	}
----

模板需要存储在上面所示的 `FreeMarkerConfigurer` 指定的目录中,根据前面的配置,如果您的控制器返回 `welcome` 视图名称,解析器将查找 `classpath:/templates/freemarker/welcome.ftl` 模板.

[[webflux-views-freemarker]]
=== FreeMarker 配置
[.small]#<<web.adoc#mvc-views-freemarker, Web MVC>>#

通过设置 `FreeMarkerConfigurer` bean可以将 `FreeMarker` 的'Settings' 和 'SharedVariables' 值直接传递 Spring 管理的 `FreeMarker` 对象.  `freemarkerSettings` 属性需要 `java.util.Properties` 对象.  而 `freemarkerVariables` 属性需要 `java.util.Map` . 以下示例显示了如何执行此操作:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@Configuration
	@EnableWebFlux
	public class WebConfig implements WebFluxConfigurer {

		// ...

		@Bean
		public FreeMarkerConfigurer freeMarkerConfigurer() {
			Map<String, Object> variables = new HashMap<>();
			variables.put("xml_escape", new XmlEscape());

			FreeMarkerConfigurer configurer = new FreeMarkerConfigurer();
			configurer.setTemplateLoaderPath("classpath:/templates");
			configurer.setFreemarkerVariables(variables);
			return configurer;
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@Configuration
	@EnableWebFlux
	class WebConfig : WebFluxConfigurer {

		// ...

		@Bean
		fun freeMarkerConfigurer() = FreeMarkerConfigurer().apply {
			setTemplateLoaderPath("classpath:/templates")
			setFreemarkerVariables(mapOf("xml_escape" to XmlEscape()))
		}
	}
----

有关更多的 `Configuration` 内容的设置和变量可以查看 FreeMarker 文档

[[webflux-view-freemarker-forms]]
=== 表单处理
[.small]#<<web.adoc#mvc-view-freemarker-forms, Web MVC>>#

Spring 本身提供了用于 JSP 的标签库,其中包含(当然还有很多)  `<spring:bind/>` 标签,这个标签用来展示从 Web 上的 `Validator` 或业务层抛出的失败验证表单.  Spring 还支持 FreeMarker 中的相同功能,并提供了方便的宏来生成表单输入元素.

[[webflux-view-bind-macros]]
==== 绑定宏命令
[.small]#<<web.adoc#mvc-view-bind-macros, Web MVC>>#

`spring-webflux.jar` 包文件包含 FreeMarker 的一组标准宏,因此它们始终可用于经过适当配置的应用程序.

Spring 库中定义的某些宏被认为是内部的(私有的) ,但在宏定义中不存在这样的范围,其实所有宏都可以在调用代码和用户模板时看到. 以下各节仅集中于需要从模板中直接调用的宏, 如果希望直接查看宏代码, 那么可以看文件 `spring.ftl`,定义在 `org.springframework.web.reactive.result.view.freemarker`  包中.

有关绑定支持的更多详细信息,请参见<<web.adoc#mvc-view-simple-binding, 简单绑定>>.

[[webflux-views-form-macros]]
==== 表单 Macros

有关Spring对FreeMarker模板的表单宏支持的详细信息,请参阅以下内容
Spring MVC文档的各个部分.

* <<web.adoc#mvc-views-form-macros, Input Macros>>
* <<web.adoc#mvc-views-form-macros-input, Input Fields>>
* <<web.adoc#mvc-views-form-macros-select, Selection Fields>>
* <<web.adoc#mvc-views-form-macros-html-escaping, HTML Escaping>>



[[webflux-view-script]]
== 脚本视图
[.small]#<<web.adoc#mvc-view-script, Web MVC>>#

Spring Framework 有一个内置的集成,可以将 Spring WebFlux 与任何可以在 https://www.jcp.org/en/jsr/detail?id=223[JSR-223] Java 脚本引擎之上运行的模板库一起使用.  我们在不同的脚本引擎上测试了以下模板库:


[%header]
|===
|Scripting Library |Scripting Engine
|https://handlebarsjs.com/[Handlebars] |https://openjdk.java.net/projects/nashorn/[Nashorn]
|https://mustache.github.io/[Mustache] |https://openjdk.java.net/projects/nashorn/[Nashorn]
|https://facebook.github.io/react/[React] |https://openjdk.java.net/projects/nashorn/[Nashorn]
|https://www.embeddedjs.com/[EJS] |https://openjdk.java.net/projects/nashorn/[Nashorn]
|https://www.stuartellis.name/articles/erb/[ERB] |https://www.jruby.org[JRuby]
|https://docs.python.org/2/library/string.html#template-strings[String templates] |https://www.jython.org/[Jython]
|https://github.com/sdeleuze/kotlin-script-templating[Kotlin Script templating] |https://kotlinlang.org/[Kotlin]
|===

TIP: 集成任何其他脚本引擎的基本规则是它必须实现 `ScriptEngine` 和 `Invocable` 接口.

[[webflux-view-script-dependencies]]
=== 要求
[.small]#<<web.adoc#mvc-view-script-dependencies, Web MVC>>#

您需要在类路径上安装脚本引擎,其详细信息因脚本引擎而异:

* https://openjdk.java.net/projects/nashorn/[Nashorn] Javascript 引擎提供了内置的 Java 8+. 强烈建议使用最新的可用更新版本.
* 为了获得 https://www.jruby.org[JRuby] 支持,应添加 JRuby 依赖性
* 为了获得 https://www.jython.org[Jython] 支持,应添加 Jython 依赖性.
* `org.jetbrains.kotlin:kotlin-script-util` 依赖和包含在 `META-INF/services/javax.script.ScriptEngineFactory` 文件里的 `org.jetbrains.kotlin.script.jsr223.KotlinJsr223JvmLocalScriptEngineFactory` 行应添加到 Kotlin 脚本支持中.  有关详细信息,请参阅此 https://github.com/sdeleuze/kotlin-script-templating[示例] .

还需要为基于脚本的模板引擎添加依赖. 例如,对于 JavaScript,可以使用 https://www.webjars.org/[WebJars].

[[webflux-view-script-integrate]]
=== 脚本模板
[.small]#<<web.adoc#mvc-view-script-integrate, Web MVC>>#

您可以声明 `ScriptTemplateConfigurer` bean 以指定要使用的脚本引擎,要加载的脚本文件,要调用以呈现模板的函数,等等.  以下示例使用 Mustache 模板和 Nashorn JavaScript 引擎:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@Configuration
	@EnableWebFlux
	public class WebConfig implements WebFluxConfigurer {

		@Override
		public void configureViewResolvers(ViewResolverRegistry registry) {
			registry.scriptTemplate();
		}

		@Bean
		public ScriptTemplateConfigurer configurer() {
			ScriptTemplateConfigurer configurer = new ScriptTemplateConfigurer();
			configurer.setEngineName("nashorn");
			configurer.setScripts("mustache.js");
			configurer.setRenderObject("Mustache");
			configurer.setRenderFunction("render");
			return configurer;
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@Configuration
	@EnableWebFlux
	class WebConfig : WebFluxConfigurer {

		override fun configureViewResolvers(registry: ViewResolverRegistry) {
			registry.scriptTemplate()
		}

		@Bean
		fun configurer() = ScriptTemplateConfigurer().apply {
			engineName = "nashorn"
			setScripts("mustache.js")
			renderObject = "Mustache"
			renderFunction = "render"
		}
	}
----

使用以下参数调用 render 函数:

* `String template`: 模板内容
* `Map model`: 视图模型
* `RenderingContext renderingContext`:
{api-spring-framework}/web/servlet/view/script/RenderingContext.html[`RenderingContext`] 提供对应用程序上下文,区域设置,模板加载器和 URL 的访问(自5.0起) .

`Mustache.render()` 方法会与本地兼容,因此可以直接调用.

如果模板化技术需要自定义,则可以提供实现自定义渲染函数的脚本. 例如, https://handlebarsjs.com[Handlerbars] 需要在使用模板之前进行编译,并且需要使用 https://en.wikipedia.org/wiki/Polyfill[polyfill] 以模拟服务器端脚本引擎中不可用的某些浏览器功能.

以下示例显示了如何执行此操作:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@Configuration
	@EnableWebFlux
	public class WebConfig implements WebFluxConfigurer {

		@Override
		public void configureViewResolvers(ViewResolverRegistry registry) {
			registry.scriptTemplate();
		}

		@Bean
		public ScriptTemplateConfigurer configurer() {
			ScriptTemplateConfigurer configurer = new ScriptTemplateConfigurer();
			configurer.setEngineName("nashorn");
			configurer.setScripts("polyfill.js", "handlebars.js", "render.js");
			configurer.setRenderFunction("render");
			configurer.setSharedEngine(false);
			return configurer;
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@Configuration
	@EnableWebFlux
	class WebConfig : WebFluxConfigurer {

		override fun configureViewResolvers(registry: ViewResolverRegistry) {
			registry.scriptTemplate()
		}

		@Bean
		fun configurer() = ScriptTemplateConfigurer().apply {
			engineName = "nashorn"
			setScripts("polyfill.js", "handlebars.js", "render.js")
			renderFunction = "render"
			isSharedEngine = false
		}
	}
----

NOTE: NOTE: 当要求非线程安全地使用脚本引擎时,需要将 `sharedEngine` 的属性设置为 `false` ,因为模板库不是为了并发而设计的,具体可以看运行在 Nashorn 上的 Handlerbars 或 react. 据此,需要 Java 8u60+ 的版本来修复这个 https://bugs.openjdk.java.net/browse/JDK-8076099[this bug].

[source,javascript,indent=0,subs="verbatim,quotes"]
----
	var window = {};
----

脚本 `render.js` 会在使用该模板之前被编译,一个好的产品应当保存和重用模板(使用缓存的方法) ,这样高效些. 这可以在脚本中完成,并且可以自定义它(例如管理模板引擎配置. 以下示例显示了如何执行此操作:

[source,javascript,indent=0,subs="verbatim,quotes"]
----
	function render(template, model) {
		var compiledTemplate = Handlebars.compile(template);
		return compiledTemplate(model);
	}
----

有关更多配置示例,请查看 Spring Framework 单元测试, {spring-framework-main-code}/spring-webflux/src/test/java/org/springframework/web/reactive/result/view/script[Java], 和
{spring-framework-main-code}/spring-webflux/src/test/resources/org/springframework/web/reactive/result/view/script[resources].

[[webflux-view-httpmessagewriter]]
== JSON 和 XML
[.small]#<<web.adoc#mvc-view-jackson, Web MVC>>#

出于 <<webflux-multiple-representations>>,根据客户端请求的内容类型,能够在使用HTML模板呈现模型或以其他格式(例如 JSON 或 XML)呈现模型之间进行切换非常有用. 为了支持此操作,Spring WebFlux 提供了 `HttpMessageWriterView`,您可以使用它插入 `spring-web` 中的任何可用<<webflux-codecs>>(例如 `Jackson2JsonEncoder`,`Jackson2SmileEncoder` 或 `Jaxb2XmlEncoder`).

与其他视图技术不同,`HttpMessageWriterView` 不需要 `ViewResolver`,而是<<webflux-config-view-resolvers, 配置>>为默认视图. 您可以配置一个或多个此类默认视图,并包装不同的 `HttpMessageWriter` 实例或 `Encoder` 实例. 在运行时使用与请求的内容类型匹配的内容.

在大多数情况下,模型包含多个属性. 要确定要序列化的对象,可以使用模型属性的名称配置 `HttpMessageWriterView` 进行渲染. 如果模型仅包含一个属性,则使用该属性.