[[mvc-cors]]
= CORS
[.small]#<<web-reactive.adoc#webflux-cors, WebFlux>>#

Spring MVC 允许您处理 CORS (跨源资源共享) . 本节介绍如何执行此操作.

[[mvc-cors-intro]]
== 简介
[.small]#<<web-reactive.adoc#webflux-cors-intro, WebFlux>>#

出于安全原因,浏览器禁止对当前源外的资源进行 AJAX 调用.  例如,您可以将您的银行帐户放在一个标签页中,将 evil.com 放在另一个标签页中.  来自 evil.com 的脚本不应该使用您的凭据向您的银行 API 发出 AJAX 请求 - 例如从您的帐户中提取资金！

Cross-Origin Resource Sharing (CORS) 是 https://caniuse.com/#feat=cors[大多数浏览器] 实现的 https://www.w3.org/TR/cors/[W3C规范],它允许以灵活的方式指定哪些类型的跨域请求被授权, 而不是使用一些安全程度较低、功能较差的实现(如 IFRAME 或 JSONP).

[[mvc-cors-processing]]
== 处理
[.small]#<<web-reactive.adoc#webflux-cors-processing, WebFlux>>#

CORS 规范区分了预检查,简单和实际请求.  要了解 CORS 的工作原理,您可以 https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS[阅读本文] 以及其他许多内容,或者查看规范以获取更多详细信息.

Spring MVC `HandlerMapping` 为实现 CORS 提供内置支持. 成功将请求映射到处理程序后,`HandlerMapping` 实现检查给定请求和处理程序的 CORS 配置并采取进一步操作.  直接处理预检查请求,同时拦截,验证简单和实际的 CORS 请求,并设置所需的 CORS 响应头.

为了启用跨源请求(即,存在 `Origin` 头并且与请求的主机不同) ,您需要具有一些显式声明的 CORS 配置.  如果未找到匹配的 CORS 配置,则拒绝预检请求.  没有 CORS 头添加到简单和实际 CORS 请求的响应中,因此浏览器拒绝它们.

可以使用基于 URL 模式的 `CorsConfiguration` 映射单独 {api-spring-framework}/web/servlet/handler/AbstractHandlerMapping.html#setCorsConfigurations-java.util.Map-[configured] 每个 `HandlerMapping`.  在大多数情况下,应用程序使用 MVC Java 配置或 XML 命名空间来声明此类映射,这会导致将单个全局映射传递给所有 `HandlerMapping` 实例.

您可以将 `HandlerMapping` 级别的全局 CORS 配置与更细粒度的处理程序级 CORS 配置相结合.  例如,带注解的控制器可以使用类或方法级别的 `@CrossOrigin` 注解(其他处理程序可以实现 `CorsConfigurationSource`) .

组合全局和本地配置的规则通常是附加的 - 例如,所有全局和所有本地源.  对于只能接受单个值的属性(例如 `allowCredentials` 和 `maxAge`) , 本地会覆盖全局值.  有关详细信息,请参阅 {api-spring-framework}/web/cors/CorsConfiguration.html#combine-org.springframework.web.cors.CorsConfiguration-[`CorsConfiguration#combine(CorsConfiguration)`].

[TIP]
====
要从 source 中了解更多信息或进行高级自定义,请查看后面的代码:

* `CorsConfiguration`
* `CorsProcessor`, `DefaultCorsProcessor`
* `AbstractHandlerMapping`
====

[[mvc-cors-controller]]
== `@CrossOrigin`
[.small]#<<web-reactive.adoc#webflux-cors-controller, WebFlux>>#

在带注解的控制器方法上使用 {api-spring-framework}/web/bind/annotation/CrossOrigin.html[`@CrossOrigin`] 注解启用跨源请求,如以下示例所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@RestController
	@RequestMapping("/account")
	public class AccountController {

		@CrossOrigin
		@GetMapping("/{id}")
		public Account retrieve(@PathVariable Long id) {
			// ...
		}

		@DeleteMapping("/{id}")
		public void remove(@PathVariable Long id) {
			// ...
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@RestController
	@RequestMapping("/account")
	class AccountController {

		@CrossOrigin
		@GetMapping("/{id}")
		fun retrieve(@PathVariable id: Long): Account {
			// ...
		}

		@DeleteMapping("/{id}")
		fun remove(@PathVariable id: Long) {
			// ...
		}
	}
----

默认情况下,`@CrossOrigin` 允许:

* All origins.
* All headers.
* All HTTP methods to which the controller method is mapped.

默认情况下不启用 `allowCredentials`,因为它建立了一个信任级别,该信任级别暴露敏感的用户特定信息(例如 cookie 和 CSRF 令牌) ,并且只应在适当的地方使用.启用后， 必须将 `allowOrigins` 设置为一个或多个特定 domain (而不是特殊值 `"*"`) ， 或者可以使用 `allowOriginPatterns` 属性来动态匹配一组 origins.

`maxAge` 设置为30 分钟.

`@CrossOrigin` 在类级别也受支持,并且由所有方法继承,如以下示例所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
@CrossOrigin(origins = "https://domain2.com", maxAge = 3600)
@RestController
@RequestMapping("/account")
public class AccountController {

	@GetMapping("/{id}")
	public Account retrieve(@PathVariable Long id) {
		// ...
	}

	@DeleteMapping("/{id}")
	public void remove(@PathVariable Long id) {
		// ...
	}
}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@CrossOrigin(origins = ["https://domain2.com"], maxAge = 3600)
	@RestController
	@RequestMapping("/account")
	class AccountController {

		@GetMapping("/{id}")
		fun retrieve(@PathVariable id: Long): Account {
			// ...
		}

		@DeleteMapping("/{id}")
		fun remove(@PathVariable id: Long) {
			// ...
		}
----

您可以在类级别和方法级别使用 `@CrossOrigin` ,如以下示例所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@CrossOrigin(maxAge = 3600)
	@RestController
	@RequestMapping("/account")
	public class AccountController {

		@CrossOrigin("https://domain2.com")
		@GetMapping("/{id}")
		public Account retrieve(@PathVariable Long id) {
			// ...
		}

		@DeleteMapping("/{id}")
		public void remove(@PathVariable Long id) {
			// ...
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@CrossOrigin(maxAge = 3600)
	@RestController
	@RequestMapping("/account")
	class AccountController {

		@CrossOrigin("https://domain2.com")
		@GetMapping("/{id}")
		fun retrieve(@PathVariable id: Long): Account {
			// ...
		}

		@DeleteMapping("/{id}")
		fun remove(@PathVariable id: Long) {
			// ...
		}
	}
----


[[mvc-cors-global]]
== 全局配置
[.small]#<<web-reactive.adoc#webflux-cors-global, WebFlux>>#

除了细粒度,基于注解的配置以外,您可能还希望定义一些全局 CORS 配置. 您可以在任何 `HandlerMapping` 上单独设置基于 URL 的 `CorsConfiguration` 映射.  但是,大多数应用程序使用 MVC Java 配置或 MVC XNM 命名空间来执行此操作.

默认情况下,全局配置启用以下内容:

* All origins.
* All headers.
* `GET`, `HEAD`, and `POST` methods.

默认情况下不启用 `allowCredentials`,因为它建立了一个信任级别,该信任级别暴露敏感的用户特定信息(例如 cookie 和 CSRF 令牌) ,并且只应在适当的地方使用.启用后， 必须将 `allowOrigins` 设置为一个或多个特定 domain (而不是特殊值 `"*"`) ， 或者可以使用 `allowOriginPatterns` 属性来动态匹配一组 origins.

`maxAge` 设置为 30 分钟.

[[mvc-cors-global-java]]
=== Java 配置
[.small]#<<web-reactive.adoc#webflux-cors-global, WebFlux>>#

要在 MVC Java 配置中启用 CORS,可以使用 `CorsRegistry` 回调,如以下示例所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@Configuration
	@EnableWebMvc 
	public class WebConfig implements WebMvcConfigurer {

		@Override
		public void addCorsMappings(CorsRegistry registry) {

			registry.addMapping("/api/**")
				.allowedOrigins("https://domain2.com")
				.allowedMethods("PUT", "DELETE")
				.allowedHeaders("header1", "header2", "header3")
				.exposedHeaders("header1", "header2")
				.allowCredentials(true).maxAge(3600);

			// Add more mappings...
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@Configuration
	@EnableWebMvc
	class WebConfig : WebMvcConfigurer {

		override fun addCorsMappings(registry: CorsRegistry) {

			registry.addMapping("/api/**")
					.allowedOrigins("https://domain2.com")
					.allowedMethods("PUT", "DELETE")
					.allowedHeaders("header1", "header2", "header3")
					.exposedHeaders("header1", "header2")
					.allowCredentials(true).maxAge(3600)

			// Add more mappings...
		}
	}
----



[[mvc-cors-global-xml]]
=== XML 配置

要在 XML 命名空间中启用 CORS,可以使用 `<mvc:cors>` 元素,如以下示例所示:

[source,xml,indent=0,subs="verbatim"]
----
<mvc:cors>

	<mvc:mapping path="/api/**"
		allowed-origins="https://domain1.com, https://domain2.com"
		allowed-methods="GET, PUT"
		allowed-headers="header1, header2, header3"
		exposed-headers="header1, header2" allow-credentials="true"
		max-age="123" />

	<mvc:mapping path="/resources/**"
		allowed-origins="https://domain1.com" />

</mvc:cors>
----




[[mvc-cors-filter]]
== CORS 过滤器
[.small]#<<webflux-cors.adoc#webflux-cors-webfilter, WebFlux>>#

您可以通过内置的 {api-spring-framework}/web/filter/CorsFilter.html[`CorsFilter`] 应用 CORS 支持.

NOTE: 如果您尝试将 `CorsFilter` 与 Spring Security 一起使用,请记住 Spring Security {docs-spring-security}/servlet/integrations/cors.html[内置] 了对 CORS 的支持.

要配置过滤器,请将 `CorsConfigurationSource` 传递给其构造函数,如以下示例所示:

[source,java,indent=0,subs="verbatim",role="primary"]
.Java
----
	CorsConfiguration config = new CorsConfiguration();

	// Possibly...
	// config.applyPermitDefaultValues()

	config.setAllowCredentials(true);
	config.addAllowedOrigin("https://domain1.com");
	config.addAllowedHeader("*");
	config.addAllowedMethod("*");

	UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
	source.registerCorsConfiguration("/**", config);

	CorsFilter filter = new CorsFilter(source);
----
[source,kotlin,indent=0,subs="verbatim",role="secondary"]
.Kotlin
----
	val config = CorsConfiguration()

	// Possibly...
	// config.applyPermitDefaultValues()

	config.allowCredentials = true
	config.addAllowedOrigin("https://domain1.com")
	config.addAllowedHeader("*")
	config.addAllowedMethod("*")

	val source = UrlBasedCorsConfigurationSource()
	source.registerCorsConfiguration("/**", config)

	val filter = CorsFilter(source)
----
