[[webmvc-fn]]
= 功能端点
[.small]#<<web-reactive.adoc#webflux-fn, WebFlux>>#

Spring Web MVC 包含 WebMvc.fn,这是一个轻量级的函数编程模型,其中的函数用于路由和处理请求,而约定则是为不变性而设计的.  它是基于注解的编程模型的替代方案,但可以在同一  <<web#mvc-servlet>> 上运行.

[[webmvc-fn-overview]]
== 概述
[.small]#<<web-reactive.adoc#webflux-fn-overview, WebFlux>>#

在 WebMvc.fn 中,使用 `HandlerFunction` 处理 HTTP 请求: 该函数接受 `ServerRequest` 并返回 `ServerResponse`.  作为请求对象的请求都具有不可变的约定,这些约定为 JDK 8 提供了对 HTTP 请求和响应的友好访问.  `HandlerFunction` 等效于基于注解的编程模型中 `@RequestMapping` 方法的主体.

传入的请求通过 `RouterFunction` 路由到处理程序函数: 该函数接受 `ServerRequest` 并返回可选的 `HandlerFunction`(即 `Optional<HandlerFunction>`) .  当路由器功能匹配时,返回处理程序功能.  否则为空的 `Optional`.  `RouterFunction` 等效于 `@RequestMapping` 注解,但主要区别在于路由器功能不仅提供数据,还提供行为.

`RouterFunctions.route()` 提供了一个有助于构建路由器的路由器构建器,如以下示例所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	import static org.springframework.http.MediaType.APPLICATION_JSON;
	import static org.springframework.web.servlet.function.RequestPredicates.*;
	import static org.springframework.web.servlet.function.RouterFunctions.route;

	PersonRepository repository = ...
	PersonHandler handler = new PersonHandler(repository);

	RouterFunction<ServerResponse> route = route()
		.GET("/person/{id}", accept(APPLICATION_JSON), handler::getPerson)
		.GET("/person", accept(APPLICATION_JSON), handler::listPeople)
		.POST("/person", handler::createPerson)
		.build();


	public class PersonHandler {

		// ...

		public ServerResponse listPeople(ServerRequest request) {
			// ...
		}

		public ServerResponse createPerson(ServerRequest request) {
			// ...
		}

		public ServerResponse getPerson(ServerRequest request) {
			// ...
		}
	}
----

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	import org.springframework.web.servlet.function.router

	val repository: PersonRepository = ...
	val handler = PersonHandler(repository)

	val route = router { // <1>
		accept(APPLICATION_JSON).nest {
			GET("/person/{id}", handler::getPerson)
			GET("/person", handler::listPeople)
		}
		POST("/person", handler::createPerson)
	}


	class PersonHandler(private val repository: PersonRepository) {

		// ...

		fun listPeople(request: ServerRequest): ServerResponse {
			// ...
		}

		fun createPerson(request: ServerRequest): ServerResponse {
			// ...
		}

		fun getPerson(request: ServerRequest): ServerResponse {
			// ...
		}
	}
----
<1> 使用路由器 DSL 创建路由器.

如果将 `RouterFunction` 注册为 Bean (例如,通过将其暴露在 `@Configuration` 类中) ,则 Servlet 将自动检测到它,如<<webmvc-fn-running>>所述.

[[webmvc-fn-handler-functions]]
== HandlerFunction
[.small]#<<web-reactive.adoc#webflux-fn-handler-functions, WebFlux>>#

`ServerRequest` 和 `ServerResponse` 是不可变的接口,它们提供 JDK 8 友好的 HTTP 请求和响应访问,包括请求头,正文,方法和状态码.

[[webmvc-fn-request]]
=== ServerRequest

`ServerRequest` 提供对 HTTP 方法,URI,请求头和查询参数的访问,而通过 `body` 方法提供对主体的访问.

下面的示例将请求正文提取为 `String`:

[source,java,role="primary"]
.Java
----
String string = request.body(String.class);
----
[source,kotlin,role="secondary"]
.Kotlin
----
val string = request.body<String>()
----

以下示例将主体提取到 `List<Person>`,其中 Person 对象从序列化形式(例如 JSON 或 XML) 解码:

[source,java,role="primary"]
.Java
----
List<Person> people = request.body(new ParameterizedTypeReference<List<Person>>() {});
----
[source,kotlin,role="secondary"]
.Kotlin
----
val people = request.body<Person>()
----

以下示例显示如何访问参数:

[source,java,role="primary"]
.Java
----
MultiValueMap<String, String> params = request.params();
----
[source,kotlin,role="secondary"]
.Kotlin
----
val map = request.params()
----


[[webmvc-fn-response]]
=== ServerResponse

`ServerResponse` 提供对 HTTP 响应的访问,由于它是不可变的,因此您可以使用 `build` 方法来创建它.  您可以使用构建器来设置响应状态,添加响应头或提供正文.  以下示例使用 JSON 内容创建 200 (OK) 响应:

[source,java,role="primary"]
.Java
----
Person person = ...
ServerResponse.ok().contentType(MediaType.APPLICATION_JSON).body(person);
----
[source,kotlin,role="secondary"]
.Kotlin
----
val person: Person = ...
ServerResponse.ok().contentType(MediaType.APPLICATION_JSON).body(person)
----

以下示例显示了如何使用 `Location` 头且不包含主体来构建 201 (CREATED) 响应:

[source,java,role="primary"]
.Java
----
URI location = ...
ServerResponse.created(location).build();
----
[source,kotlin,role="secondary"]
.Kotlin
----
val location: URI = ...
ServerResponse.created(location).build()
----

您还可以使用异步结果作为主体， `CompletableFuture`， `Publisher` 或 `ReactiveAdapterRegistry` 支持的任何其他类型.  例如:

[source,java,role="primary"]
.Java
----
Mono<Person> person = webClient.get().retrieve().bodyToMono(Person.class);
ServerResponse.ok().contentType(MediaType.APPLICATION_JSON).body(person);
----
[source,kotlin,role="secondary"]
.Kotlin
----
val person = webClient.get().retrieve().awaitBody<Person>()
ServerResponse.ok().contentType(MediaType.APPLICATION_JSON).body(person)
----

如果不仅仅包含主体,还包含基于异步类型的状态和头部信息,您可以在  `ServerResponse` 使用静态的  `async` 方法,他接受 `CompletableFuture<ServerResponse>`, `Publisher<ServerResponse>` 或 `ReactiveAdapterRegistry` 支持的其他异步类型,例如:

[source,java,role="primary"]
.Java
----
Mono<ServerResponse> asyncResponse = webClient.get().retrieve().bodyToMono(Person.class)
  .map(p -> ServerResponse.ok().header("Name", p.name()).body(p));
ServerResponse.async(asyncResponse);
----

可以通过 `ServerResponse` 的静态 `sse` 方法提供 https://www.w3.org/TR/eventsource/[Server-Sent Events] . 该方法提供的 builder 允许您发送字符串或将其他对象作为 JSON 发送,例如:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	public RouterFunction<ServerResponse> sse() {
        return route(GET("/sse"), request -> ServerResponse.sse(sseBuilder -> {
                	// Save the sseBuilder object somewhere..
                }));
	}

	// In some other thread, sending a String
	sseBuilder.send("Hello world");

	// Or an object, which will be transformed into JSON
    Person person = ...
	sseBuilder.send(person);

    // Customize the event by using the other methods
    sseBuilder.id("42")
            .event("sse event")
            .data(person);

	// and done at some point
	sseBuilder.complete();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
    fun sse(): RouterFunction<ServerResponse> = router {
        GET("/sse") { request -> ServerResponse.sse { sseBuilder ->
            // Save the sseBuilder object somewhere..
        }
    }

	// In some other thread, sending a String
	sseBuilder.send("Hello world")

	// Or an object, which will be transformed into JSON
    val person = ...
	sseBuilder.send(person)

    // Customize the event by using the other methods
    sseBuilder.id("42")
            .event("sse event")
            .data(person)

	// and done at some point
	sseBuilder.complete()
----


[[webmvc-fn-handler-classes]]
=== 处理 Classes

我们可以将处理程序函数编写为 lambda,如以下示例所示:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
HandlerFunction<ServerResponse> helloWorld =
  request -> ServerResponse.ok().body("Hello World");
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
val helloWorld: (ServerRequest) -> ServerResponse =
  { ServerResponse.ok().body("Hello World") }
----

这很方便,但是在应用程序中我们需要多个功能,并且多个内联 lambda 可能会变得凌乱.  因此,将相关的处理程序功能分组到一个处理程序类中很有用,该类的作用与基于注解的应用程序中的 `@Controller` 相似.  例如,以下类暴露了 reactive `Person`  存储库:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
import static org.springframework.http.MediaType.APPLICATION_JSON;
import static org.springframework.web.reactive.function.server.ServerResponse.ok;

public class PersonHandler {

	private final PersonRepository repository;

	public PersonHandler(PersonRepository repository) {
		this.repository = repository;
	}

	public ServerResponse listPeople(ServerRequest request) { // <1>
		List<Person> people = repository.allPeople();
		return ok().contentType(APPLICATION_JSON).body(people);
	}

	public ServerResponse createPerson(ServerRequest request) throws Exception { // <2>
		Person person = request.body(Person.class);
		repository.savePerson(person);
		return ok().build();
	}

	public ServerResponse getPerson(ServerRequest request) { // <3>
		int personId = Integer.parseInt(request.pathVariable("id"));
		Person person = repository.getPerson(personId);
		if (person != null) {
			return ok().contentType(APPLICATION_JSON).body(person));
		}
		else {
			return ServerResponse.notFound().build();
		}
	}

}
----
<1> `listPeople` 是一个处理函数,它以  JSON 格式返回存储库中找到的所有 `Person` 对象.
<2> `createPerson` 是一个处理函数,用于存储请求正文中包含的新 `Person`.
<3> `getPerson` 是一个处理程序函数,它返回由 `id` 路径变量标识的单个人.  我们从存储库中检索该 `Person` 并创建一个 JSON 响应(如果找到) .  如果未找到,我们将返回 404 Not Found 响应.

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	class PersonHandler(private val repository: PersonRepository) {

		fun listPeople(request: ServerRequest): ServerResponse { // <1>
			val people: List<Person> = repository.allPeople()
			return ok().contentType(APPLICATION_JSON).body(people);
		}

		fun createPerson(request: ServerRequest): ServerResponse { // <2>
			val person = request.body<Person>()
			repository.savePerson(person)
			return ok().build()
		}

		fun getPerson(request: ServerRequest): ServerResponse { // <3>
			val personId = request.pathVariable("id").toInt()
			return repository.getPerson(personId)?.let { ok().contentType(APPLICATION_JSON).body(it) }
					?: ServerResponse.notFound().build()

		}
	}
----
<1> `listPeople` 是一个处理函数,它以 JSON 格式返回存储库中找到的所有 `Person` 对象.
<2> `createPerson` 是一个处理函数,用于存储请求正文中包含的新 `Person`.
<3> `getPerson` 是一个处理程序函数,它返回由 `id` 路径变量标识的单个人.  我们从存储库中检索该 `Person` 并创建一个 JSON 响应(如果找到) .  如果未找到,我们将返回 404 Not Found 响应.


[[webmvc-fn-handler-validation]]
=== 验证

功能端点可以使用 Spring 的<<core.adoc#validation, 验证工具>>将验证应用于请求正文.  例如,给定 `Person` 的自定义 Spring <<core.adoc#validation, Validator>> 实现:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	public class PersonHandler {

		private final Validator validator = new PersonValidator(); // <1>

		// ...

		public ServerResponse createPerson(ServerRequest request) {
			Person person = request.body(Person.class);
			validate(person); // <2>
			repository.savePerson(person);
			return ok().build();
		}

		private void validate(Person person) {
			Errors errors = new BeanPropertyBindingResult(person, "person");
			validator.validate(person, errors);
			if (errors.hasErrors()) {
				throw new ServerWebInputException(errors.toString()); // <3>
			}
		}
	}
----
<1> 创建 `Validator` 实例.
<2> 应用 validation.
<3> 引发 400 响应的异常.

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	class PersonHandler(private val repository: PersonRepository) {

		private val validator = PersonValidator() // <1>

		// ...

		fun createPerson(request: ServerRequest): ServerResponse {
			val person = request.body<Person>()
			validate(person) // <2>
			repository.savePerson(person)
			return ok().build()
		}

		private fun validate(person: Person) {
			val errors: Errors = BeanPropertyBindingResult(person, "person")
			validator.validate(person, errors)
			if (errors.hasErrors()) {
				throw ServerWebInputException(errors.toString()) // <3>
			}
		}
	}
----
<1> 创建 `Validator` 实例.
<2> 应用 validation.
<3> 引发 400 响应的异常.

处理程序还可以通过基于 `LocalValidatorFactoryBean` 创建和注入全局 `Validator` 实例来使用标准 Bean 验证 API(JSR-303) .  请参阅<<core.adoc#validation-beanvalidation, Spring Validation>>.

[[webmvc-fn-router-functions]]
== `RouterFunction`
[.small]#<<web-reactive.adoc#webflux-fn-router-functions, WebFlux>>#

路由器功能用于将请求路由到相应的 `HandlerFunction`.  通常,您不是自己编写路由器功能,而是使用 `RouterFunctions` 实用工具类上的方法来创建一个.
`RouterFunctions.route()`(无参数) 为您提供了流式的生成器,用于创建路由器功能,而 `RouterFunctions.route(RequestPredicate,HandlerFunction)` 提供了直接创建路由器的方法.

通常,建议使用 `route()` 构建器,因为它为典型的映射方案提供了便捷的快捷方式,而无需发现静态导入.  例如,路由器功能构建器提供了 `GET(String, HandlerFunction)` 方法来为 GET 请求创建映射.  和 `POST(String, HandlerFunction)` 进行 POST 映射.

除了基于 HTTP 方法的映射外,路由构建器还提供了一种在映射到请求时引入其他断言的方法.  对于每个 HTTP 方法,都有一个重载的方法,它以 `RequestPredicate` 作为参数,尽管可以表达其他约束.

[[webmvc-fn-predicates]]
=== 断言

您可以编写自己的 `RequestPredicate`,但是 `RequestPredicates` 实用程序类根据请求路径,HTTP 方法,内容类型等提供常用的实现.  以下示例使用请求断言基于 `Accept` 头创建约束:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	RouterFunction<ServerResponse> route = RouterFunctions.route()
		.GET("/hello-world", accept(MediaType.TEXT_PLAIN),
			request -> ServerResponse.ok().body("Hello World")).build();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	import org.springframework.web.servlet.function.router

	val route = router {
		GET("/hello-world", accept(TEXT_PLAIN)) {
			ServerResponse.ok().body("Hello World")
		}
	}
----

您可以使用以下命令组合多个请求断言:

* `RequestPredicate.and(RequestPredicate)` -- 两个都必须匹配.
* `RequestPredicate.or(RequestPredicate)` -- 只需要匹配一个.


`RequestPredicates` 中的许多断言都是组成的.
例如,`RequestPredicates.GET(String)` 由  `RequestPredicates.method(HttpMethod)` 和 `RequestPredicates.path(String)` 组成.  上面显示的示例还使用了两个请求断言,因为构建器在内部使用 `RequestPredicates.GET` 并将其与 `accept` 断言组合在一起.

[[webmvc-fn-routes]]
=== 路由

路由器功能按顺序评估: 如果第一个路由不匹配,则评估第二个路由,依此类推.  因此,在通用路由之前声明更具体的路由是有意义的.  当将路由器功能注册为 Spring Bean 时， 这一点也很重要， 这将在后面进行描述.  请注意,此行为不同于基于注解的编程模型,在该模型中,将自动选择 "最特定" 的控制器方法.

使用路由器功能生成器时,所有定义的路由都组成一个 `RouterFunction`,从 `build()` 返回.  还有其他方法可以将多个路由器功能组合在一起:

*  `RouterFunctions.route()` 构建器上添加 `add(RouterFunction)`
* `RouterFunction.and(RouterFunction)`
* `RouterFunction.andRoute(RequestPredicate, HandlerFunction)` --  Router 带有嵌套 `RouterFunctions.route()` 的 `RouterFunction.and()` 的快捷方式.

以下示例显示了四种路由的组成:


[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	import static org.springframework.http.MediaType.APPLICATION_JSON;
	import static org.springframework.web.servlet.function.RequestPredicates.*;

	PersonRepository repository = ...
	PersonHandler handler = new PersonHandler(repository);

	RouterFunction<ServerResponse> otherRoute = ...

	RouterFunction<ServerResponse> route = route()
		.GET("/person/{id}", accept(APPLICATION_JSON), handler::getPerson) // <1>
		.GET("/person", accept(APPLICATION_JSON), handler::listPeople) // <2>
		.POST("/person", handler::createPerson) // <3>
		.add(otherRoute) // <4>
		.build();
----
<1>  带有与 JSON 匹配的 `Accept` 头的 pass:q[`GET /person/{id}`] 被路由到 `PersonHandler.getPerson`
<2>  带有与 JSON 匹配的 `Accept` 头的 `GET /person` 被路由到 `PersonHandler.listPeople`
<3>  没有其他断言的 POST `POST /person` 被路由到 `PersonHandler.createPerson`
<4> `otherRoute` 是在其他地方创建的路由器功能,并将其添加到构建的路由中.

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	import org.springframework.http.MediaType.APPLICATION_JSON
	import org.springframework.web.servlet.function.router

	val repository: PersonRepository = ...
	val handler = PersonHandler(repository);

	val otherRoute = router {  }

	val route = router {
		GET("/person/{id}", accept(APPLICATION_JSON), handler::getPerson) // <1>
		GET("/person", accept(APPLICATION_JSON), handler::listPeople) // <2>
		POST("/person", handler::createPerson) // <3>
	}.and(otherRoute) // <4>
----
<1>  带有与JSON匹配的 `Accept` 头的 pass:q[`GET /person/{id}`] 被路由到 `PersonHandler.getPerson`
<2>  带有与JSON匹配的 `Accept` 头的 `GET /person` 被路由到 `PersonHandler.listPeople`
<3>  没有其他断言的 POST `POST /person` 被路由到 `PersonHandler.createPerson`
<4> `otherRoute` 是在其他地方创建的路由器功能,并将其添加到构建的路由中.


=== 嵌入路由

一组路由功能通常具有一个共享断言,例如一个共享路径. 在上面的示例中,共享断言将是与 `/person` 匹配的路径断言,由三个路由使用.  使用注解时,您可以通过使用映射到 `/person` 的类型级别 `@RequestMapping` 注解来删除此重复项.
在 WebMvc.fn 中,可以通过路由器功能构建器上的 `path` 方法共享路径断言.  例如,以上示例的最后几行可以通过使用嵌套路由以以下方式进行改进:


[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
RouterFunction<ServerResponse> route = route()
	.path("/person", builder -> builder // <1>
		.GET("/{id}", accept(APPLICATION_JSON), handler::getPerson)
		.GET(accept(APPLICATION_JSON), handler::listPeople)
		.POST(handler::createPerson))
	.build();
----
<1> 请注意,`path` 的第二个参数是使用路由器构建器的使用者.

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	import org.springframework.web.servlet.function.router

	val route = router {
		"/person".nest {
			GET("/{id}", accept(APPLICATION_JSON), handler::getPerson)
			GET(accept(APPLICATION_JSON), handler::listPeople)
			POST(handler::createPerson)
		}
	}
----

尽管基于路径的嵌套是最常见的,但是您可以通过使用构建器上的 `nest` 方法来嵌套在任何种类的断言上.  上面的内容仍然包含一些以共享的 `Accept-header` 断言形式出现的重复.  通过将 `nest` 方法与 `accept` 一起使用,我们可以进一步改进:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	RouterFunction<ServerResponse> route = route()
		.path("/person", b1 -> b1
			.nest(accept(APPLICATION_JSON), b2 -> b2
				.GET("/{id}", handler::getPerson)
				.GET(handler::listPeople))
			.POST(handler::createPerson))
		.build();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	import org.springframework.web.servlet.function.router

	val route = router {
		"/person".nest {
			accept(APPLICATION_JSON).nest {
				GET("/{id}", handler::getPerson)
				GET("", handler::listPeople)
				POST(handler::createPerson)
			}
		}
	}
----


[[webmvc-fn-running]]
== 运行服务器
[.small]#<<web-reactive.adoc#webflux-fn-running, WebFlux>>#

通常,您可以通过 MVC Config 在基于 <<web.adoc#mvc-servlet, `DispatcherHandler`>> 的设置中运行路由器功能,该<<web.adoc#mvc-config>> 使用 Spring 配置来声明处理请求所需的组件.  MVC Java 配置声明以下基础结构组件以支持功能端点:

* `RouterFunctionMapping`: 在 Spring 配置中检测一个或多个 `RouterFunction<?>` bean,通过 `RouterFunction.andOther` 组合它们,<<core.adoc#beans-factory-ordered, orders them>>,并将请求路由到生成的组成 `RouterFunction`.
* `HandlerFunctionAdapter`:简单的适配器,使 `DispatcherHandler` 调用映射到请求的 `HandlerFunction`.

前面的组件使功能端点适合于 `DispatcherServlet` 请求处理生命周期,并且(可能) 与带注解的控制器(如果已声明) 并排运行.  这也是 Spring Boot Web 启动程序如何启用功能端点的方式.

以下示例显示了 WebFlux Java 配置:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	@Configuration
	@EnableMvc
	public class WebConfig implements WebMvcConfigurer {

		@Bean
		public RouterFunction<?> routerFunctionA() {
			// ...
		}

		@Bean
		public RouterFunction<?> routerFunctionB() {
			// ...
		}

		// ...

		@Override
		public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
			// configure message conversion...
		}

		@Override
		public void addCorsMappings(CorsRegistry registry) {
			// configure CORS...
		}

		@Override
		public void configureViewResolvers(ViewResolverRegistry registry) {
			// configure view resolution for HTML rendering...
		}
	}
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	@Configuration
	@EnableMvc
	class WebConfig : WebMvcConfigurer {

		@Bean
		fun routerFunctionA(): RouterFunction<*> {
			// ...
		}

		@Bean
		fun routerFunctionB(): RouterFunction<*> {
			// ...
		}

		// ...

		override fun configureMessageConverters(converters: List<HttpMessageConverter<*>>) {
			// configure message conversion...
		}

		override fun addCorsMappings(registry: CorsRegistry) {
			// configure CORS...
		}

		override fun configureViewResolvers(registry: ViewResolverRegistry) {
			// configure view resolution for HTML rendering...
		}
	}
----




[[webmvc-fn-handler-filter-function]]
== 过滤器处理程序功能
[.small]#<<web-reactive.adoc#webflux-fn-handler-filter-function, WebFlux>>#

您可以使用路由功能构建器上的 `before`,`after` 或 `filter` 方法来过滤处理程序函数.  使用注解,可以通过使用 `@ControllerAdvice`,`ServletFilter` 或同时使用两者来实现类似的功能.
该过滤器将应用于构建器构建的所有路由.  这意味着在嵌套路由中定义的过滤器不适用于 "top-level"  路由.  例如,考虑以下示例:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	RouterFunction<ServerResponse> route = route()
		.path("/person", b1 -> b1
			.nest(accept(APPLICATION_JSON), b2 -> b2
				.GET("/{id}", handler::getPerson)
				.GET(handler::listPeople)
				.before(request -> ServerRequest.from(request) // <1>
					.header("X-RequestHeader", "Value")
					.build()))
			.POST(handler::createPerson))
		.after((request, response) -> logResponse(response)) // <2>
		.build();
----
<1> 添加自定义请求头的 `before` 过滤器仅应用于两个 GET 路由.
<2> 记录响应的 `after` 过滤器将应用于所有路由,包括嵌套路由.

[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	import org.springframework.web.servlet.function.router

	val route = router {
		"/person".nest {
			GET("/{id}", handler::getPerson)
			GET(handler::listPeople)
			before { // <1>
				ServerRequest.from(it)
						.header("X-RequestHeader", "Value").build()
			}
		}
		POST(handler::createPerson)
		after { _, response -> // <2>
			logResponse(response)
		}
	}
----
<1> 添加自定义请求头的 `before` 过滤器仅应用于两个 GET 路由.
<2> 记录响应的 `after` 过滤器将应用于所有路由,包括嵌套路由.


路由器构建器上的 `filter` 方法采用 `HandlerFilterFunction`: 该函数采用 `ServerRequest` 和 `HandlerFunction` 并返回 `ServerResponse`.  `handler` 函数参数代表链中的下一个元素.  这通常是路由到的处理程序,但是如果应用了多个,它也可以是另一个过滤器.

现在,我们可以在路由中添加一个简单的安全过滤器,假设我们拥有一个可以确定是否允许特定路径的 `SecurityManager`.  以下示例显示了如何执行此操作:

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
	SecurityManager securityManager = ...

	RouterFunction<ServerResponse> route = route()
		.path("/person", b1 -> b1
			.nest(accept(APPLICATION_JSON), b2 -> b2
				.GET("/{id}", handler::getPerson)
				.GET(handler::listPeople))
			.POST(handler::createPerson))
		.filter((request, next) -> {
			if (securityManager.allowAccessTo(request.path())) {
				return next.handle(request);
			}
			else {
				return ServerResponse.status(UNAUTHORIZED).build();
			}
		})
		.build();
----
[source,kotlin,indent=0,subs="verbatim,quotes",role="secondary"]
.Kotlin
----
	import org.springframework.web.servlet.function.router

	val securityManager: SecurityManager = ...

	val route = router {
		("/person" and accept(APPLICATION_JSON)).nest {
			GET("/{id}", handler::getPerson)
			GET("", handler::listPeople)
			POST(handler::createPerson)
			filter { request, next ->
				if (securityManager.allowAccessTo(request.path())) {
					next(request)
				}
				else {
					status(UNAUTHORIZED).build();
				}
			}
		}
	}
----

前面的示例演示了调用 `next.handle(ServerRequest)` 是可选的.  当允许访问时,我们仅允许执行处理函数.

除了在路由器功能构建器上使用 `filter` 方法之外,还可以通过 `RouterFunction.filter(HandlerFilterFunction)` 将过滤器应用于现有路由器功能.

NOTE: 通过专用的 <<webflux-cors.adoc#webflux-cors-webfilter, `CorsWebFilter`>>. 提供对功能端点的 CORS 支持.