[[{chapter}.websocket-intro]]
= WebSocket简介

WebSocket 协议 https://tools.ietf.org/html/rfc6455[RFC 6455],提供了一种标准化方法,可通过单个 TCP 连接在客户端和服务器之间建立全双工双向通信通道.
它是来自 HTTP 的不同 TCP 协议,但设计为通过 HTTP 工作并使用 80 和 443 端口,并允许重用现有防火墙规则.

WebSocket 交互以 HTTP 请求开始,该 HTTP 请求使用HTTP `Upgrade` 头进行升级,或者在这种情况下,切换到 WebSocket 协议.
以下示例显示了这样的交互:

[source,yaml,indent=0,subs="verbatim,quotes"]
----
	GET /spring-websocket-portfolio/portfolio HTTP/1.1
	Host: localhost:8080
	Upgrade: websocket <1>
	Connection: Upgrade <2>
	Sec-WebSocket-Key: Uc9l9TMkWGbHFD2qnFHltg==
	Sec-WebSocket-Protocol: v10.stomp, v11.stomp
	Sec-WebSocket-Version: 13
	Origin: http://localhost:8080
----

<1> `Upgrade` 头.
<2> 使用 `Upgrade` 连接.

具有 WebSocket 支持的服务器返回类似于以下内容的输出,而不是通常的 200 状态代码:

[source,yaml,indent=0,subs="verbatim,quotes"]
----
	HTTP/1.1 101 Switching Protocols <1>
	Upgrade: websocket
	Connection: Upgrade
	Sec-WebSocket-Accept: 1qVdfYHU9hPOl4JYYNXF623Gzn0=
	Sec-WebSocket-Protocol: v10.stomp
----

<1> 协议切换

成功握手后,则 HTTP 升级请求背后的 TCP 套接字将保持打开状态,并且客户端和服务器都可以使用它来彼此发送消息.

有关 WebSockets 如何工作的完整介绍超出了本文档的范围.
请参阅 RFC 6455,HTML5 的 WebSocket 章节,或 Web 上的许多介绍和教程.

请注意,如果 WebSocket 服务器在 Web 服务器(例如 nginx) 后面运行,则可能需要将其配置为将 WebSocket 升级请求传递到 WebSocket 服务器.
同样,如果应用程序在云环境中运行,请检查与 WebSocket 支持相关的云提供程序的说明.

[[{chapter}.websocket-intro-architecture]]
== HTTP 与 WebSocket

尽管 WebSocket 被设计为与 HTTP 兼容并且以 HTTP 请求开始,但重要的是要理解这两种协议会导致非常不同的体系结构和应用程序编程模型.

在 HTTP 和 REST 中,应用程序被设计为多个 URL.
要与应用程序进行交互,客户端将访问这些 URL 请求、响应样式.
服务器根据 HTTP URL,方法和请求头将请求路由到适当的处理程序.

相比之下,在 WebSockets 中,初始连接通常只有一个 URL.
随后,所有应用程序消息都在同一 TCP 连接上流动.
这指向完全不同的异步,事件驱动的消息传递体系结构.

WebSocket 也是一种低级传输协议,与 HTTP 不同,它不对消息内容规定任何语义.
这意味着除非客户端和服务器就消息语义达成一致,否则无法路由或处理消息.

WebSocket 客户端和服务器可以通过 HTTP 握手请求上的 `Sec-WebSocket-Protocol` 头协商使用更高级别的消息传递协议(例如,STOMP) . 如果没有,他们需要提出自己的惯例.

[[{chapter}.websocket-intro-when-to-use]]
== 何时使用 WebSockets

WebSockets 可以使网页变得动态和交互.
但是,在许多情况下,Ajax 和 HTTP 流式传输或长轮询的组合可以提供简单有效的解决方案.

例如,新闻,邮件和社交订阅资源需要动态更新,但是正常更新的间隔时间为几分钟.
另一方面,协作,游戏和财务应用程序需要更接近实时.

仅延迟并不是使用 WebSocket 的决定因素.
如果消息量相对较低(例如,监视网络故障) ,HTTP 流式传输或轮询可以提供有效的解决方案.
而当需要它是低延迟,高频率和高容量的组合,那使用 WebSocket 是最佳选择.

还要记住,通过 Internet,受控制之外的限制性代理可能会阻止 WebSocket 交互,因为它们未配置为传递 `Upgrade` 头, 或者因为它们关闭看似空闲的长期连接.
这意味着将 WebSocket 用于防火墙内的内部应用程序是一个比面向公众的应用程序更直接的决策.