
[[ns-config]]
= Security 命名空间配置


== 介绍
从Spring Framework 2.0版开始，可以使用命名空间配置。 它允许您使用其他XML模式中的元素来补充传统的Spring bean应用程序上下文语法。 您可以在 https://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/[Spring参考文档]中找到更多信息。 命名空间元素可以简单地用于允许以更简洁的方式配置单个bean，或者更强大地定义一种替代配置语法，该语法与问题域更紧密地匹配并向用户隐藏底层的复杂性。
一个简单的元素可能掩盖了将多个bean和处理步骤添加到应用程序上下文的事实。 例如，将以下元素从安全命名空间添加到应用程序上下文中将启动嵌入式LDAP服务器，以测试应用程序中的使用情况：

[source,xml]
----
<security:ldap-server />
----

这比连接等效的Apache Directory Server Bean要简单得多。 `ldap-server` 元素上的属性支持最常见的替代配置要求，并且使用户不必担心他们需要创建哪些bean以及bean属性名称是什么。footnote:[您可以在 pass:specialcharacters,macros [<<ldap>>]一章中找到有关 `ldap-server` 元素使用的更多信息。
在编辑应用程序上下文文件时使用良好的XML编辑器应提供有关可用属性和元素的信息。 我们建议您尝试一下 https://spring.io/tools/sts[Spring Tool Suite]，因为它具有使用标准Spring命名空间的特殊功能。

要开始在应用程序上下文中使用安全性命名空间，您需要在类路径上具有 `spring-security-config jar`。 然后，您要做的就是将架构声明添加到您的应用程序上下文文件中：

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
xmlns:security="http://www.springframework.org/schema/security"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.springframework.org/schema/beans
		https://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/security
		https://www.springframework.org/schema/security/spring-security.xsd">
	...
</beans>
----

在您将看到的许多示例中（以及在示例应用程序中），我们通常将 "security" 用作默认命名空间，而不是 "beans"，这意味着我们可以在所有 security 命名空间元素上省略前缀，从而使内容 更容易阅读。
如果将应用程序上下文划分为单独的文件，并且大多数安全配置都放在其中一个文件中，则可能还需要这样做。 然后，您的安全应用程序上下文文件将像这样开始

[source,xml]
----
<beans:beans xmlns="http://www.springframework.org/schema/security"
xmlns:beans="http://www.springframework.org/schema/beans"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.springframework.org/schema/beans
		https://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/security
		https://www.springframework.org/schema/security/spring-security.xsd">
	...
</beans:beans>
----

从现在开始，我们将假定使用此语法。


=== 命名空间的设计
命名空间旨在捕获框架的最常见用法，并提供简化和简洁的语法以在应用程序中启用它们。 该设计基于框架内的大规模依赖关系，并且可以分为以下几个方面：

* __Web/HTTP Security__ - 最复杂的部分。 设置用于应用框架身份验证机制的过滤器和相关服务Bean，以保护URL，呈现登录页面和错误页面等。

* __Business Object (Method) Security__ - 用于保护服务层的选项。

* __AuthenticationManager__ - 处理来自框架其他部分的身份验证请求。

* __AccessDecisionManager__ - 提供有关Web和方法安全性的访问决策。 默认的将被注册，但是您也可以选择使用自定义的，使用常规的Spring bean语法声明。

* __AuthenticationProvider__s - 身份验证管理器用来验证用户身份的机制。 命名空间提供了对几个标准选项的支持，还提供了添加使用传统语法声明的自定义bean的方法。

* __UserDetailsService__ - 与身份验证提供者密切相关，但其他bean通常也需要。

我们将在以下各节中介绍如何配置它们。

[[ns-getting-started]]
== security 命名空间配置入门
在本节中，我们将研究如何构建命名空间配置以使用框架的一些主要功能。 假设您最初希望尽快启动并运行，并通过一些测试登录来向现有Web应用程序添加身份验证支持和访问控制。 然后，我们将研究如何转换为针对数据库或其他安全存储库的身份验证。 在后面的部分中，我们将介绍更多高级的命名空间配置选项。

[[ns-web-xml]]
=== web.xml 配置
您需要做的第一件事是将以下过滤器声明添加到您的 `web.xml` 文件中：

[source,xml]
----
<filter>
<filter-name>springSecurityFilterChain</filter-name>
<filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
</filter>

<filter-mapping>
<filter-name>springSecurityFilterChain</filter-name>
<url-pattern>/*</url-pattern>
</filter-mapping>
----

这为Spring Security Web基础架构提供了一个挂钩。 `DelegatingFilterProxy` 是一个Spring Framework类，它委托一个过滤器实现，该实现在您的应用程序上下文中定义为Spring Bean。 在这种情况下，该Bean名为 "springSecurityFilterChain"，
它是由命名空间创建的内部基础结构Bean，用于处理Web安全。 请注意，您不应自己使用此bean名称。 将其添加到 `web.xml` 后，就可以开始编辑应用程序上下文文件了。 Web安全服务是使用 `<http>` 元素配置的。

[[ns-minimal]]
=== 最小化 <http> 配置
启用Web安全所需要做的就是

[source,xml]
----
<http>
<intercept-url pattern="/**" access="hasRole('USER')" />
<form-login />
<logout />
</http>
----

这表示我们希望保护应用程序中的所有URL，需要角色 `ROLE_USER` 对其进行访问，我们希望使用带有用户名和密码的表单登录到该应用程序，并且希望注册一个注销URL，以允许我们 注销该应用程序。 `<http>` 元素是所有与Web相关的命名空间功能的父级。`<intercept-url>` 元素定义了一种模式，该模式使用Ant路径样式语法footnote:[请参阅有关通行证的部分：特殊字符，宏[<< request-matching >>]]
与传入请求的URL匹配。 您还可以使用正则表达式匹配作为替代（有关更多详细信息，请参见命名空间附录）。 访问属性定义了与给定模式匹配的请求的访问要求。 在默认配置下，这通常是一个用逗号分隔的角色列表，必须允许用户发出一个角色来进行请求。
前缀 "`ROLE_`" 是一个标记，表示应与用户权限进行简单比较。 换句话说，应该使用基于角色的常规检查。 Spring Security中的访问控制不限于使用简单角色（因此使用前缀来区分不同类型的安全属性）。
稍后我们将解释解释如何变化 footnote:[access属性中逗号分隔值的解释取决于所使用的 `<<ns-access-manager,AccessDecisionManager>>` 的实现。]。 在Spring Security 3.0中，该属性也可以填充为 pass:specialcharacters,macros[<<el-access,EL expression>>]。

[NOTE]
您可以使用多个 `<intercept-url>` 元素为不同的URL集定义不同的访问要求，但是将按照列出的顺序对其进行评估，并且将使用第一个匹配项。 因此，您必须将最具体的匹配项放在顶部。 您还可以添加方法属性，以将匹配限制为特定的HTTP方法（`GET`，`POST`，`PUT` 等）。

要添加一些用户，可以直接在命名空间中定义一组测试数据：

[source,xml]
----
<authentication-manager>
<authentication-provider>
	<user-service>
	<!-- Password is prefixed with {noop} to indicate to DelegatingPasswordEncoder that
	NoOpPasswordEncoder should be used. This is not safe for production, but makes reading
	in samples easier. Normally passwords should be hashed using BCrypt -->
	<user name="jimi" password="{noop}jimispassword" authorities="ROLE_USER, ROLE_ADMIN" />
	<user name="bob" password="{noop}bobspassword" authorities="ROLE_USER" />
	</user-service>
</authentication-provider>
</authentication-manager>
----

这是存储相同密码的安全方法的示例。密码以{bcrypt}为前缀来指示 `DelegatingPasswordEncoder`（该密码支持任何已配置的 `PasswordEncoder` 进行匹配）使用 BCrypt 对密码进行哈希处理：

[source,xml]
----
<authentication-manager>
<authentication-provider>
	<user-service>
	<user name="jimi" password="{bcrypt}$2a$10$ddEWZUl8aU0GdZPPpy7wbu82dvEw/pBpbRvDQRqA41y6mK1CoH00m"
			authorities="ROLE_USER, ROLE_ADMIN" />
	<user name="bob" password="{bcrypt}$2a$10$/elFpMBnAYYig6KRR5bvOOYeZr1ie1hSogJryg9qDlhza4oCw1Qka"
			authorities="ROLE_USER" />
	<user name="jimi" password="{noop}jimispassword" authorities="ROLE_USER, ROLE_ADMIN" />
	<user name="bob" password="{noop}bobspassword" authorities="ROLE_USER" />
	</user-service>
</authentication-provider>
</authentication-manager>
----



[subs="quotes"]
****
如果您熟悉框架的命名空间前版本，则可能已经大概猜到了这里发生了什么。 `<http>` 元素负责创建 `FilterChainProxy` 及其使用的过滤器。 由于预定义了过滤器位置，不再像过滤器排序不正确这样的常见问题。

`<authentication-provider>` 元素创建一个 `DaoAuthenticationProvider` bean，而 `<user-service>` 元素创建一个 `InMemoryDaoImpl`。 所有身份验证提供者元素都必须是 `<authentication-manager>` 元素的子元素，该元素创建 `ProviderManager` 并向其注册身份验证提供者。
您可以找到有关在<<appendix-namespace,命名空间附录>>中创建的bean的更多详细信息。 如果您想开始了解框架中的重要类是什么以及如何使用它们，特别是如果您以后要自定义，则值得进行交叉检查。
****

上面的配置定义了两个用户，他们的密码和他们在应用程序中的角色（将用于访问控制）。 也可以使用 `user-service` 上的 `properties` 属性从标准属性文件中加载用户信息。 有关文件格式的更多详细信息，请参见<<core-services-in-memory-service,内存中身份验证>>部分。 使用 `<authentication-provider>` 元素意味着身份验证管理器将使用用户信息来处理身份验证请求。 您可以具有多个 `<authentication-provider>` 元素来定义不同的身份验证源，并且将依次查询每个身份验证源。

此时，您应该可以启动应用程序，并且需要登录才能继续。 试试看，或尝试使用该项目随附的“教程”示例应用程序。

[[ns-form-target]]
==== 设置默认的登录后目标
如果尝试访问受保护的资源未提示登录表单，则将使用 `default-target-url` 选项。 这是用户成功登录后将转到的URL，默认为 "/"。 您还可以通过将 `always-use-default-target` 属性设置为 "true"，进行配置，以使用户始终在该页面上结束（无论登录是“按需”还是明确选择登录）。  如果您的应用程序始终要求用户从 "主页" 页面开始，这将很有用，例如：

[source,xml]
----
<http pattern="/login.htm*" security="none"/>
<http use-expressions="false">
<intercept-url pattern='/**' access='ROLE_USER' />
<form-login login-page='/login.htm' default-target-url='/home.htm'
		always-use-default-target='true' />
</http>
----

为了更好地控制目标，可以使用 `authentication-success-handler-ref` 属性作为 `default-target-url` 的替代方法。 引用的bean应该是 `AuthenticationSuccessHandler` 的实例。 您可以在<<form-login-flow-handling,核心过滤器>>一章以及命名空间附录中找到有关此内容的更多信息，以及有关在身份验证失败时如何自定义流程的信息。

[[ns-web-advanced]]
== 高级 Web 功能

[[ns-custom-filters]]
=== 添加自己的过滤器

如果您以前使用过Spring Security，那么您会知道该框架会维护一系列过滤器，以便应用其服务。 您可能想在特定位置将自己的过滤器添加到堆栈中，或者使用Spring Security过滤器，该过滤器目前没有命名空间配置选项（例如CAS）。
或者，您可能想使用标准命名空间过滤器的定制版本，例如由 `<form-login>` 元素创建的 `UsernamePasswordAuthenticationFilter`，它利用了一些显式使用Bean可用的额外配置选项。 由于过滤器链未直接公开，您如何使用命名空间配置来做到这一点？

使用命名空间时，始终严格执行过滤器的顺序。 创建应用程序上下文时，过滤器bean按照命名空间处理代码进行排序，标准的Spring Security过滤器每个在命名空间中都有一个别名和一个众所周知的位置。

[NOTE]
在以前的版本中，排序是在应用程序上下文的后处理期间，在创建过滤器实例之后进行的。 在版本3.0+中，现在在实例化类之前在bean元数据级别完成排序。 这对如何将自己的过滤器添加到堆栈有影响，因为在解析 `<http>` 元素期间必须知道整个过滤器列表，因此在3.0中语法略有变化。

<<filter-stack,表17.1 "标准过滤器别名和排序">>中显示了创建过滤器的过滤器，别名和命名空间元素/属性。过滤器按它们在过滤器链中出现的顺序列出。

[[filter-stack]]
.标准过滤器别名和排序
|===
| 别名 | Filter 类 | 命名空间元素或属性

|  CHANNEL_FILTER
| `ChannelProcessingFilter`
| `http/intercept-url@requires-channel`

|  SECURITY_CONTEXT_FILTER
| `SecurityContextPersistenceFilter`
| `http`

|  CONCURRENT_SESSION_FILTER
| `ConcurrentSessionFilter`
| `session-management/concurrency-control`

| HEADERS_FILTER
| `HeaderWriterFilter`
| `http/headers`

| CSRF_FILTER
| `CsrfFilter`
| `http/csrf`

|  LOGOUT_FILTER
| `LogoutFilter`
| `http/logout`

|  X509_FILTER
| `X509AuthenticationFilter`
| `http/x509`

|  PRE_AUTH_FILTER
| `AbstractPreAuthenticatedProcessingFilter` Subclasses
| N/A

|  CAS_FILTER
| `CasAuthenticationFilter`
| N/A

|  FORM_LOGIN_FILTER
| `UsernamePasswordAuthenticationFilter`
| `http/form-login`

|  BASIC_AUTH_FILTER
| `BasicAuthenticationFilter`
| `http/http-basic`

|  SERVLET_API_SUPPORT_FILTER
| `SecurityContextHolderAwareRequestFilter`
| `http/@servlet-api-provision`

| JAAS_API_SUPPORT_FILTER
| `JaasApiIntegrationFilter`
| `http/@jaas-api-provision`

|  REMEMBER_ME_FILTER
| `RememberMeAuthenticationFilter`
| `http/remember-me`

|  ANONYMOUS_FILTER
| `AnonymousAuthenticationFilter`
| `http/anonymous`

|  SESSION_MANAGEMENT_FILTER
| `SessionManagementFilter`
| `session-management`

| EXCEPTION_TRANSLATION_FILTER
| `ExceptionTranslationFilter`
| `http`

|  FILTER_SECURITY_INTERCEPTOR
| `FilterSecurityInterceptor`
| `http`

|  SWITCH_USER_FILTER
| `SwitchUserFilter`
| N/A
|===

您可以使用 `custom-filter` 元素和以下名称之一指定自己的过滤器到堆栈中，以指定过滤器应出现的位置：

[source,xml]
----
<http>
<custom-filter position="FORM_LOGIN_FILTER" ref="myFilter" />
</http>

<beans:bean id="myFilter" class="com.mycompany.MySpecialAuthenticationFilter"/>
----

如果要在堆栈中的另一个过滤器之前或之后插入过滤器，也可以使用 `after` 或 `before` 属性。 名称 "FIRST" 和 "LAST" 可以与 `position` 属性一起使用，以指示您希望过滤器分别出现在整个堆栈之前或之后。

.避免过滤器位置冲突
[TIP]
如果您要插入一个自定义过滤器，该过滤器的位置可能与命名空间创建的标准过滤器中的位置相同，那么一定不要误添加命名空间版本，这一点很重要。 删除所有创建要替换其功能的过滤器的元素。

请注意，您不能替换使用<http>元素本身创建的过滤器- `SecurityContextPersistenceFilter`，`ExceptionTranslationFilter` 或 `FilterSecurityInterceptor`。 默认情况下会添加其他一些过滤器，但是您可以禁用它们。 默认情况下会添加 `AnonymousAuthenticationFilter`，除非您禁用了<<ns-session-fixation,会话固定保护>>，否则 `SessionManagementFilter` 也将添加到过滤器链中。

如果您要替换需要身份验证入口点的命名空间过滤器（即，未经身份验证的用户试图访问受保护的资源而触发身份验证过程），则也需要添加自定义入口点Bean。


[[ns-method-security]]
== 安全方法
从2.0版开始，Spring Security大大改进了对为服务层方法增加安全性的支持。 它提供对JSR-250注解安全性以及框架原始 `@Secured` 注解的支持。 从3.0开始，您还可以使用新的<<el-access,基于表达式的注解>>。
您可以使用 `intercept-methods` 元素来修饰bean声明，从而将安全性应用于单个bean，或者可以使用AspectJ样式切入点在整个服务层中保护多个bean。

[[ns-access-manager]]
== 默认 AccessDecisionManager
本部分假定您具有Spring Security中用于访问控制的基础架构的一些知识。 如果您不这样做，则可以跳过它，稍后再返回，因为此部分仅与需要进行一些自定义才能使用更多功能（而不是基于角色的简单安全性）的人员有关。

当您使用命名空间配置时，`AccessDecisionManager` 的默认实例将自动为您注册，并将根据您在拦截URL和保护切入点声明中指定的访问属性，为方法调用和Web URL访问制定访问决策。 （如果使用的是注解安全方法，则在注解中）。

默认策略是将 `AffirmativeBased` `AccessDecisionManager` 与 `RoleVoter` 和 `AuthenticatedVoter` 一起使用。 您可以在<<authz-arch,授权>>一章中找到更多有关这些的信息。

[[ns-custom-access-mgr]]
=== 自定义 AccessDecisionManager
如果您需要使用更复杂的访问控制策略，则可以轻松设置方法和Web安全性的替代方案。

为了实现方法安全，可以通过在应用程序上下文中将 `global-method-security` 上的 `access-decision-manager-ref` 属性设置为适当的 `AccessDecisionManager` bean的ID来实现此目的：

[source,xml]
----
<global-method-security access-decision-manager-ref="myAccessDecisionManagerBean">
...
</global-method-security>
----

Web安全性的语法相同，但是在 `http` 元素上：

[source,xml]
----
<http access-decision-manager-ref="myAccessDecisionManagerBean">
...
</http>
----
