[[client]]
= Client-side Support
include::attributes.adoc[]

本节介绍 Spring HATEOAS 对客户端的支持.

[[client.traverson]]
== Traverson
include::attributes.adoc[]

Spring HATEOAS 提供了用于客户端服务遍历的API.它受 https://blog.codecentric.de/en/2013/11/traverson/[Traverson JavaScript library] 的启发.以下示例显示了如何使用它:

====
[source, java, tabsize=2]
----
Map<String, Object> parameters = new HashMap<>();
parameters.put("user", 27);

Traverson traverson = new Traverson(URI.create("http://localhost:8080/api/"), MediaTypes.HAL_JSON);
String name = traverson
		.follow("movies", "movie", "actor").withTemplateParameters(parameters)
		.toObject("$.name");
----
====

您可以通过将 `Traverson` 实例指向 REST 服务器并配置要设置为 `Accept` 请求头的媒体类型来设置它. 然后,您可以定义要发现和遵循的关系名称. 关系名称可以是简单名称,也可以是 JSONPath 表达式(以 `$` 开头).

然后,示例将参数映射传递给 `Traverson` 实例. 这些参数用于扩展遍历过程中找到的 URI(已模板化). 通过访问最终遍历的表示来结束遍历. 在前面的示例中,我们评估一个 JSONPath 表达式来访问演员的名字.

前面的示例是遍历的最简单版本,其中 `rel` 值是字符串,并且在每个 hop 处都应用相同的模板参数.

在每个级别上,还有更多的选项可以自定义模板参数. 以下示例显示了这些选项.

[source,java,indent=0, tabsize=2]
----
include::{test-dir}/client/TraversonTest.java[tag=hop-with-param]
----

静态 `rel(...)`  函数是定义 single  `Hop` 的便捷方法.使用  `.withParameter(key, value)` 可以简化指定URI模板变量的过程.

NOTE: `.withParameter()` 返回可链接的新 `Hop` 对象. 您可以根据需要将任意多个 `.withParameter` 串在一起. 结果是单个 hop 定义. 以下示例显示了一种方法:

====
[source,java,indent=0, tabsize=2]
----
include::{test-dir}/client/TraversonTest.java[tag=hop-put]
----
====

您还可以使用 `.withParameters(Map)` 加载整个参数  `Map` .

NOTE: `follow()` 是可链接的,这意味着您可以将多个 hop 串在一起,如前面的示例所示. 您可以放置多个基于字符串的 `rel` 值(`follow("items", "item")`),也可以放置具有特定参数的单个 hop .

=== `EntityModel<T>` vs. `CollectionModel<T>`

到目前为止显示的示例演示了如何避免Java的类型擦除,以及如何将单个JSON格式的资源转换为 `EntityModel<Item>`  对象. 但是,如果您得到像 `\_embedded` HAL集合这样的集合,该怎么办? 只需稍作调整即可完成此操作,如以下示例所示:

====
[source,java, tabsize=2]
----
CollectionModelType<Item> collectionModelType =
		TypeReferences.CollectionModelType<Item>() {};

CollectionModel<Item> itemResource = traverson.//
		follow(rel("items")).//
		toObject(collectionModelType);
----
====

该资源没有获取单个资源,而是将一个集合反序列化为 `CollectionModel`.

[[client.link-discoverer]]
== 使用 `LinkDiscoverer` 实例

使用启用了超媒体的表示形式时,常见的任务是在其中找到具有特定关系类型的链接. Spring HATEOAS 为默认表示渲染或 HAL 提供了 `LinkDiscoverer` 接口的基于 https://code.google.com/p/json-path[JSONPath] 的实现. 使用 `@EnableHypermediaSupport` 时,我们会自动将支持配置的超媒体类型的实例作为 Spring Bean 暴露.

另外,您可以按以下步骤设置和使用实例:

====
[source, java]
----
String content = "{'_links' :  { 'foo' : { 'href' : '/foo/bar' }}}";
LinkDiscoverer discoverer = new HalLinkDiscoverer();
Link link = discoverer.findLinkWithRel("foo", content);

assertThat(link.getRel(), is("foo"));
assertThat(link.getHref(), is("/foo/bar"));
----
====

[[client.web-client]]
== 配置 WebClient 实例

如果您需要配置 `WebClient` 来说明超媒体, 这很容易. 需要 `HypermediaWebClientConfigurer`, 如下所示:

.Configuring a `WebClient` yourself
====
[source, java, tabsize=0, indent=0]
----
include::{code-dir}/client/HypermediaConfiguration.java[tag=web-client]
----
<1> 在你的 `@Configuration` 类中, 获取一个 `HypermediaWebClientConfigurer` bean 副本 Spring HATEOAS registers.
<2> 创建 `WebClient.Builder` 后, 使用 configurer 注册 hypermedia types.
====

NOTE: `HypermediaWebClientConfigurer` 的功能是向 `WebClient.Builder` 注册所有正确的编码器和解码器.  要使用它, 您需要将构建器注入到应用程序中的某个位置, 然后运行 `build()` 方法生成 `WebClient`.

如果您使用的是 Spring Boot, 则还有另一种方法:  `WebClientCustomizer`.

.Letting Spring Boot configure things
====
[source,java]
----
@Bean // <4>
WebClientCustomizer hypermediaWebClientCustomizer(HypermediaWebClientConfigurer configurer) { // <1>
    return webClientBuilder -> { // <2>
        configurer.registerHypermediaTypes(webClientBuilder); // <3>
    };
}
----
<1> 当创建一个 Spring bean 时, 请获取一个 Spring HATEOAS `HypermediaWebClientConfigurer` bean 的副本.
<2> 使用 Java 8 lambda 表达式定义 `WebClientCustomizer`.
<3> 在函数调用内部, 应用 `registerHypermediaTypes` 方法.
<4> 将整个内容作为 Spring bean 返回,  Spring Boot 可以自动获取并将其应用于其自动配置的 `WebClient.Builder` bean.
====

在这个阶段, 每当需要具体的 `WebClient` 时, 只需将 `WebClient.Builder` 注入代码中, 然后使用 `build()`.  `WebClient` 实例将能够使用超媒体进行交互.

[[client.web-test-client]]
== 配置 `WebTestClient` 实例

使用启用了超媒体的表示形式时, 常见的任务是使用 `WebTestClient` 执行各种测试.

要在测试案例中配置 `WebTestClient` 的实例, 请查看以下示例:

.Configuring `WebTestClient` when using Spring HATEOAS
====
[source, java, indent=0, tabsize=2]
----
include::{test-dir}/config/HypermediaWebTestClientConfigurerTest.java[tag=web-test-client]
----
<1> 注册使用了 `@EnableHypermediaSupport` 注解的配置类来开启 HAL 支持.
<2> 使用 `HypermediaWebTestClientConfigurer` 可以应用超媒体支持.
<3> 使用 Spring HATEOAS 的 `TypeReferences.CollectionModelType` helper 请求 `CollectionModel<EntityModel<Employee>>` 响应.
<4> 在获得 Spring HATEOAS 格式的 "body" 之后, 对其进行断言！
====

IMPORTANT: `WebTestClient` 是不可变的值类型, 因此您不能更改它. . `HypermediaWebClientConfigurer` 的返回值必须捕获才能使用.

如果您使用的是Spring Boot, 则还有其他选项, 例如:

.Configuring `WebTestClient` when using Spring Boot
====
[source,java,tabsize=2]
----
@SpringBootTest
@AutoConfigureWebTestClient // <1>
class WebClientBasedTests {

    @Test
    void exampleTest(@Autowired WebTestClient.Builder builder, @Autowired HypermediaWebTestClientConfigurer configurer) { // <2>
        client = builder.apply(configurer).build(); // <3>

        client.get().uri("/") //
                .exchange() //
                .expectBody(new TypeReferences.EntityModelType<Employee>() {}) // <4>
                .consumeWith(result -> {
                    // assert against this EntityModel<Employee>!
                });
    }
}
----
<1> 这是 Spring Boot 的测试注解, 它将为该测试类配置 `WebTestClient.Builder`.
<2> 自动将 Spring Boot 的 `WebTestClient.Builder` 插入到 `builder` 并将 Spring HATEOAS 的 configurer 作为方法参数. .
<3> 使用 `HypermediaWebTestClientConfigurer` 注册对超媒体的支持.
<4> 表示您希望使用 `TypeReferences` 返回 `EntityModel<Employee>` .

同样, 您可以使用与前面的示例类似的断言.
====

还有许多其他方式来测试案例.  `WebTestClient` 可以绑定到控制器, 函数和 URL.  本部分并不表示所有内容.  相反, 这为您提供了一些入门示例.  重要的是, `通过应用HypermediaWebTestClientConfigurer`, 可以更改 `WebTestClient` 的任何实例以处理超媒体.

[[client.rest-template]]
== 配置 RestTemplate 实例

如果要创建自己的 `RestTemplate` 副本 (配置为使用超媒体) , 则可以使用 `HypermediaRestTemplateConfigurer`:

.Configuring `RestTemplate` yourself
====
[source, java, tabsize=0, indent=0]
----
include::{code-dir}/client/HypermediaConfiguration.java[tag=rest-template]
----
<1> 在 `@Configuration` 类中, 获取 `HypermediaRestTemplateConfigurer` bean Spring HATEOAS registers 的副本.
<2> 创建 `RestTemplate` 之后, 使用配置器应用超媒体类型.
====

您可以自由地将此模式应用于所需的任何 `RestTemplate` 实例, 无论是创建注册的 bean 还是在定义的服务内部.

如果您使用的是 Spring Boot, 则还有另一种方法.

通常, Spring Boot 摆脱了在应用程序上下文中注册 `RestTemplate` bean的概念.


* 当与不同的服务通信时, 您通常需要不同的凭据.
* 当 `RestTemplate` 使用底层连接池时, 您会遇到其他问题.
* 用户通常需要不同的实例, 而不是单一的 bean.

为了弥补这一点, Spring Boot 提供了 `RestTemplateBuilder`. 这个自动配置的 bean 让您可以定义各种用于构造 `RestTemplate` 实例的 bean. `您请求RestTemplateBuilder` bean, 执行其 `build()` 方法, 然后应用 final 设置(如凭据等).

注册基于超媒体的消息转换器, 添加以下代码:

.Letting Spring Boot configure things
====
[source,java]
----
@Bean // <4>
RestTemplateCustomizer hypermediaRestTemplateCustomizer(HypermediaRestTemplateConfigurer configurer) { // <1>
    return restTemplate -> { // <2>
        configurer.registerHypermediaTypes(restTemplate); // <3>
    };
}
----
<1> 创建 Spring Bean 时, 请获取 Spring HATEOAS 的 `HypermediaRestTemplateConfigurer` Bean的副本.
<2> 使用 Java 8 lambda 表达式定义 `RestTemplateCustomizer`.
<3> 在函数调用内部, 应用 `registerHypermediaTypes` 方法.
<4> 将整个内容作为 Spring bean 返回, Spring Boot 可以自动获取并将其应用于其自动配置的  `RestTemplateBuilder`.
====

在这个阶段, 只要您需要一个具体的 `RestTemplate`, 只需将 `RestTemplateBuilder` 注入到代码中, 并使用 `build()`. `RestTemplate` 实例将能够使用超媒体进行交互.