[[configuration]]
= 配置

本节描述了如何配置 Spring HATEOAS.

[[configuration.at-enable]]
== 使用 `@EnableHypermediaSupport`

要使 `RepresentationModel` 子类型根据各种超媒体表示类型的规范来呈现,可以通过 `@EnableHypermediaSupport` 激活对特定超媒体表示格式的支持. 注解将 `HypermediaType` 枚举作为其参数.
当前,我们支持 HAL 以及默认渲染. 使用注解会触发以下内容:

* 它注册了必要的 Jackson 模块,以超媒体特定格式呈现 `EntityModel` 和 `CollectionModel`.
* 如果 JSONPath 在类路径上,它将自动注册一个 `LinkDiscoverer` 实例,并在 JSON 查找 `rel` 链接(请参阅使用 <<client.link-discoverer>>).
* 默认情况下,它启用  <<fundamentals.obtaining-links.entity-links,entity links>>  并自动选择 `EntityLinks` 实现并将它们捆绑到可以自动装配的 `DelegatingEntityLinks` 实例中.
* 它会自动拾取 `ApplicationContext` 中的所有 `RelProvider` 实现,并将它们捆绑到可以自动装配的 `DelegatingRelProvider` 中. 它注册提供程序以考虑 domain 以及 Spring MVC 控制器上的 `@Relation`. 如果 https://github.com/atteo/evo-inflector[EVO inflector] 位于类路径上,则使用库中实现的复数算法继承集合 `rel` 值(请参见 <<server.rel-provider>>).

[[configuration.at-enable.stacks]]
=== 明确启用对专用 Web 堆栈的支持

默认情况下,`@EnableHypermediaSupport` 将反射性地检测到您正在使用的 Web 应用程序堆栈,并挂接到为这些组件注册的 Spring 组件中,以启用对超媒体表示的支持.
但是,在某些情况下,您只希望明确激活对特定堆栈的支持. 例如. 如果基于 Spring WebMVC 的应用程序使用 WebFlux 的 WebClient 进行传出请求,并且该请求不应该与超媒体元素一起使用,
则可以通过在配置中显式声明 WebMVC 来限制要启用的功能:

.Explicitly activating hypermedia support for a particular web stack
====
[source, java]
----
@EnableHypermediaSupport(…, stacks = WebStack.WEBMVC)
class MyHypermediaConfiguration { … }
----
====
