[[server]]
= Server-side support
include::attributes.adoc[]

[[server.link-builder.webmvc]]
== [[fundamentals.obtaining-links]] [[fundamentals.obtaining-links.builder]] 在 Spring MVC 中创建 links

现在我们已经有了域词汇表,但是主要的挑战仍然存在:如何以更不脆弱的方式创建实际的 URI,以将其包装到 `Link` 实例中. 现在,我们将不得不在各处复制 URI 字符串. 这样做是脆弱且不可维持的.

假设您已按照以下方式实现了 Spring MVC 控制器:

====
[source, java]
----
@Controller
class PersonController {

  @GetMapping("/people")
  HttpEntity<PersonModel> showAll() { … }

  @GetMapping(value = "/{person}", method = RequestMethod.GET)
  HttpEntity<PersonModel> show(@PathVariable Long person) { … }
}
----
====

我们在这里看到两个约定. 第一个是通过控制器方法的  `@GetMapping` 注解暴露的集合资源,该集合的各个元素作为直接子资源暴露. 收集资源可能以简单的URI(如刚刚所示)或更复杂的URI(例如 `/people/{id}/addresses`)暴露. 假设您想链接到所有人的收藏资源. 遵循上面的方法将导致两个问题:

* 要创建绝对URI,您需要查找协议,主机名,端口,Servlet基址和其他值. 这很麻烦,并且需要难看的手动字符串连接代码.
* 您可能不希望将  `/people` 连接到基本URI之上,因为这样一来,您将不得不在多个位置维护信息. 如果更改映射,则必须更改所有指向该映射的客户端.

Spring HATEOAS 现在提供了一个 `WebMvcLinkBuilder`,使您可以通过指向控制器类来创建链接. 以下示例显示了如何执行此操作:

====
[source, java]
----
import static org.sfw.hateoas.server.mvc.WebMvcLinkBuilder.*;

Link link = linkTo(PersonController.class).withRel("people");

assertThat(link.getRel()).isEqualTo(LinkRelation.of("people"));
assertThat(link.getHref()).endsWith("/people");
----
====

`WebMvcLinkBuilder` 在后台使用 Spring 的 `ServletUriComponentsBuilder` 来从当前请求中获取基本URI信息. 假设您的应用程序在 `http://localhost:8080/your-app` 上运行,那么这正是您要在其上构建其他部分的URI.
现在,构建器将检查给定控制器类的根映射,从而以 `http://localhost:8080/your-app/people` 结尾. 您还可以构建更多的嵌套链接. 以下示例显示了如何执行此操作:

====
[source, java]
----
Person person = new Person(1L, "Dave", "Matthews");
//                 /person                 /     1
Link link = linkTo(PersonController.class).slash(person.getId()).withSelfRel();
assertThat(link.getRel(), is(IanaLinkRelation.SELF.value()));
assertThat(link.getHref(), endsWith("/people/1"));
----
====

该构建器还允许创建URI实例以进行构建(例如,响应头值):

====
[source, java]
----
HttpHeaders headers = new HttpHeaders();
headers.setLocation(linkTo(PersonController.class).slash(person).toUri());

return new ResponseEntity<PersonModel>(headers, HttpStatus.CREATED);
----
====

[[fundamentals.obtaining-links.builder.methods]]
=== 建立指向方法的链接

您甚至可以建立指向方法的链接,或创建虚拟控制器方法调用. 第一种方法是将 `Method` 实例传递给 `WebMvcLinkBuilder`. 以下示例显示了如何执行此操作:

====
[source, java]
----
Method method = PersonController.class.getMethod("show", Long.class);
Link link = linkTo(method, 2L).withSelfRel();

assertThat(link.getHref()).endsWith("/people/2"));
----
====

这仍然有点令人不满意,因为我们必须首先获取一个 `Method` 实例,该实例会引发异常,并且通常很麻烦. 至少我们不重复映射. 更好的方法是在控制器代理上对目标方法进行伪方法调用,我们可以使用  `methodOn(…)` 帮助器创建该方法. 以下示例显示了如何执行此操作:

====
[source, java]
----
Link link = linkTo(methodOn(PersonController.class).show(2L)).withSelfRel();

assertThat(link.getHref()).endsWith("/people/2");
----
====

`methodOn(…)` 创建记录方法调用的控制器类的代理,并在为方法的返回类型创建的代理中暴露它.这样就可以流式地表达我们希望获得映射的方法.但是,在使用这种技术可以获得的方法上有一些限制

* 返回类型必须能够代理,因为我们需要暴露对其的方法调用.
* 通常忽略传递给方法的参数(通过 `@PathVariable` 引用的参数除外,因为它们构成了URI).

[[server.link-builder.webflux]]
== 在 Spring WebFlux 中建立链接

TODO

[[server.affordances]]
== Affordances

[quote, James J. Gibson, The Ecological Approach to Visual Perception (page 126)]
____
The affordances of the environment are what it offers …​ what it provides or furnishes, either for good or ill. The verb 'to afford' is found in the dictionary, but the noun 'affordance' is not. I have made it up.
____

基于REST的资源不仅提供数据,还提供控件. 形成灵活服务的最后一个要素是有关如何使用各种控件的详细内容. 由于能力是与链接相关联的,因此 Spring HATEOAS 提供了一个API,可以将所需的尽可能多的相关方法附加到链接上.
就像您可以通过指向 Spring MVC 控制器方法来创建链接一样(请参见在  <<server.link-builder.webmvc>>  中构建链接以了解详细信息),您...

下面的代码显示了如何  *self*  链接

.Connecting affordances to `GET /employees/{id}`
====
[source, java, indent=0, tabsize=2]
----
include::{code-dir}/EmployeeController.java[tag=get]
----
<1> 创建 *self* 链接.
<2> 将 `updateEmployee` 方法与 `self` 链接相关联.
<3> 将 `partiallyUpdateEmployee` 方法与 `self` 链接相关联.
====

使用  `.andAffordance(afford(...))`,您可以使用控制器的方法将 `PUT` 和 `PATCH` 操作连接到 `GET` 操作. 想象一下,上面提供的相关方法如下所示:

.`updateEmpoyee` method that responds to `PUT /employees/{id}`
====
[source, java, indent=0, tabsize=2]
----
include::{code-dir}/EmployeeController.java[tag=put]
----
====

.`partiallyUpdateEmployee` method that responds to `PATCH /employees/{id}`
====
[source, java, indent=0, tabsize=2]
----
include::{code-dir}/EmployeeController.java[tag=patch]
----
====

使用 `afford(…)` 方法指向这些方法将导致 Spring HATEOAS 分析请求正文和响应类型并捕获元数据,以允许不同的媒体类型实现使用该信息将该信息转换为输入和输出的描述.

[[server.affordances.api]]
=== 手动创建 affordances

尽管是注册链接功能的主要方式,但可能有必要手动构建其中的一些功能. 这可以通过使用 `Affordances` API来实现:

.Using the `Affordances` API to manually register affordances
====
[source, java, indent=0, tabsize=2]
----
include::{code-dir}/AffordancesSample.java[tag=affordances]
----
<1> 首先,从一个 `Link` 实例创建 `Affordances` 实例,然后创建一个用于描述能力的上下文.
<2> 每种功能都应以其应支持的HTTP方法开始. 然后,我们将类型注册为有效负载描述,并显式命名提供. 后者可以省略,并且默认名称将从HTTP方法和输入类型名称继承. 这有效地创建了与创建的  `EmployeeController.newEmployee(…)`  指针相同的能力
<3> 建立下一个 affordance 是为了反映指向 `EmployeeController.search(…)` 的指针发生了什么. 在这里,我们将 `Employee` 定义为创建的响应的模型,并显式注册 `QueryParameters`.
====

Affordances 由媒体类型特定的 Affordances 模型支持,该模型将一般 Affordances 元数据转换为特定的表示形式. 请确保检查  <<mediatypes>> 部分中有关 affordances 的部分,以查找有关如何控制该元数据的显示量的更多详细信息.

[[server.link-builder.forwarded-headers]]
== 转发报头处理


当您的应用程序位于代理之后,负载均衡器之后或在云中时,最常使用 https://tools.ietf.org/html/rfc7239[RFC-7239 forwarding headers]. 实际接收Web请求的节点是基础结构的一部分,并将请求转发到您的应用程序.

您的应用程序可能正在  `localhost:8080` 上运行,但对于外界,您应该位于 `reallycoolsite.com`(和网络的标准端口80)上. 通过使代理包括额外的标头(许多人已经这样做了),Spring HATEOAS可以正确地生成链接,因为它使用 Spring Framework 功能来获取原始请求的基本URI

IMPORTANT: 任何可以根据外部输入更改根URI的内容都必须得到适当的保护. 这就是默认情况下  *disabled* 转发标头处理的原因. 您必须使它能够运行. 如果您要部署到云中或控制代理和负载均衡器的配置中,那么您肯定会希望使用此功能.

要启用转发标头处理,您需要在应用程序中注册 Spring 的 Spring MVC 的 `ForwardedHeaderFilter`( https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#filters-forwarded-headers[详细信息])或 Spring WebFlux 的 `ForwardedHeaderTransformer`(https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-web-applications.html#boot-features-embedded-container-servlets-filters-listeners-beans[详细信息]). 在 Spring Boot 应用程序中,这些组件可以简单地声明为 Spring Bean,如此处所述.

.Registering a `ForwardedHeaderFilter`
====
[source, java, tabsize=2, indent=0]
----
include::{code-dir}/ForwardedEnabledConfig.java[tags=code-1]
----
====

这将创建一个处理所有  `X-Forwarded-…`  标头的 servlet 过滤器. 并且它将在 servlet 处理程序中正确注册.

对于Spring WebFlux应用程序,reactive 对应的是 `ForwardedHeaderTransformer`:

.Registering a `ForwardedHeaderTransformer`
====
[source, java, tabsize=2, indent=0]
----
include::{code-dir}/ForwardedEnabledConfig.java[tags=code-2]
----
====

这将创建一个转换响应式Web请求,处理 `X-Forwarded-…` 标头的函数. 并且它将在WebFlux中正确注册.

有了上面显示的配置,传递 `X-Forwarded-…` 标头的请求将看到那些反映在生成的链接中:

.A request using `X-Forwarded-…` headers
====
[source, bash]
----
curl -v localhost:8080/employees \
    -H 'X-Forwarded-Proto: https' \
    -H 'X-Forwarded-Host: example.com' \
    -H 'X-Forwarded-Port: 9001'
----
====

.带有生成考虑这些标题的链接的相应响应
====
[source, json]
----
{
  "_embedded": {
    "employees": [
      {
        "id": 1,
        "name": "Bilbo Baggins",
        "role": "burglar",
        "_links": {
          "self": {
            "href": "https://example.com:9001/employees/1"
          },
          "employees": {
            "href": "https://example.com:9001/employees"
          }
        }
      }
    ]
  },
  "_links": {
    "self": {
      "href": "https://example.com:9001/employees"
    },
    "root": {
      "href": "https://example.com:9001"
    }
  }
}
----
====

[[server.entity-links]]
== [[fundamentals.obtaining-links.entity-links]] 使用 EntityLinks interface

IMPORTANT: 当前未为 Spring WebFlux 应用程序提供 `EntityLinks` 及其各种实现. `EntityLinks` SPI中定义的合同最初是针对 Spring Web MVC 的,不考虑 Reactor 类型. 开发支持反应式编程的可比合同仍在进行中.

到目前为止,我们已经通过指向Web框架实现(即Spring MVC控制器)创建了链接,并检查了映射. 在许多情况下,这些类实质上是读取和写入由模型类支持的表示形式.

`EntityLinks` 接口现在暴露一个API,以根据模型类型查找 `Link` 或 `LinkBuilder`. 这些方法实质上返回的链接要么指向集合资源(例如 `/people`),要么指向 item 资源(例如 `/people/1`). 以下示例显示如何使用 `EntityLinks`:

====
[source, java]
----
EntityLinks links = …;
LinkBuilder builder = links.linkFor(Customer.class);
Link link = links.linkToItemResource(Customer.class, 1L);
----
====

通过在 Spring MVC 配置中激活 `@EnableHypermediaSupport`,可以通过依赖注入来使用 `EntityLinks`. 这将导致注册 `EntityLink` 的各种默认实现. 最基础的是检​​查 SpringMVC 控制器类的 `ControllerEntityLinks`. 如果要注册自己的 `EntityLinks` 实现,请查看 <<server.entity-links.spi, 本节>>.

[[server.entity-links.controller]]
=== 基于 Spring MVC controllers 的 EntityLinks

激活实体链接功能将导致检查当前 `ApplicationContext` 中可用的所有 Spring MVC 控制器的  `@ExposesResourceFor(…)`  注解. 注解暴露了控制器管理的模型类型. 除此之外,我们假设您遵守以下URI映射设置和约定:

Activating entity links functionality causes all the Spring MVC controllers available in the current `ApplicationContext` to be inspected for the `@ExposesResourceFor(…)` annotation.
The annotation exposes which model type the controller manages.
Beyond that, we assume that you adhere to the following URI mapping setup and conventions:

* 类型级别 `@ExposesResourceFor(…)` 声明控制器暴露其集合和 items 资源的实体类型.
* 表示集合资源的类级别的基本映射.
* 附加的方法级别映射,该映射扩展了映射以将标识符附加为附加的路径段.

以下示例显示了支持 `EntityLinks` 的控制器的实现:

====
[source, java]
----
@Controller
@ExposesResourceFor(Order.class) <1>
@RequestMapping("/orders") <2>
class OrderController {

  @GetMapping <3>
  ResponseEntity orders(…) { … }

  @GetMapping("{id}") <4>
  ResponseEntity order(@PathVariable("id") … ) { … }
}
----
<1> 控制器表示它正在暴露实体 `Order` 的集合和 items 资源.
<2> 其收集资源显示在 `/orders` 下
<3> 该收集资源可以处理 `GET` 请求. 在方便时,为其他 HTTP 方法添加更多方法.
<4> 一种附加的控制器方法,用于处理带有路径变量的从属资源,以暴露 items 资源,即单个 `Order`.
====

有了此功能,当您在 Spring MVC 配置中启用 `EntityLinks` `@EnableHypermediaSupport` 时,可以按以下方式创建到控制器的链接:

====
[source, java]
----
@Controller
class PaymentController {

  private final EntityLinks entityLinks;

  PaymentController(EntityLinks entityLinks) { <1>
    this.entityLinks = entityLinks;
  }

  @PutMapping(…)
  ResponseEntity payment(@PathVariable Long orderId) {

    Link link = entityLinks.linkToItemResource(Order.class, orderId); <2>
    …
  }
}
----
<1> 注入由 `EntityLinks` 在您的配置中提供的 `EntityLink`.
<2> 使用API​​通过使用实体类型而不是控制器类来构建链接.
====

如您所见,您可以引用管理 `Order` 实例的资源,而无需显式引用 `OrderController`.

[[server.entity-links.api]]
=== EntityLinks API 细节

从根本上讲,`EntityLinks` 允许构建 `LinkBuilder` 和 `Link` 实例以收集实体类型的集合资源和 items 资源. 以  `linkFor…`  开头的方法将为您生成 `LinkBuilder` 实例,以供您扩展和扩充其他路径段,参数等.以  `linkTo`  开头的方法将生成完全准备好的 `Link` 实例.

虽然对于收集资源而言,提供一个实体类型就足够了,但指向 items 资源的链接将需要提供一个标识符. 通常如下所示:

.Obtaining a link to an item resource
====
[source, java]
----
entityLinks.linkToItemResource(order, order.getId());
----
====

如果您发现自己重复了这些方法调用,则可以将标识符提取步骤提取到可重用的  `Function`  中,以在不同的调用中重用:

====
[source, java]
----
Function<Order, Object> idExtractor = Order::getId; <1>

entityLinks.linkToItemResource(order, idExtractor); <2>
----
<1> 标识符提取已外部化,因此可以保存在一个字段中或保持不变.
<2> 使用提取器的链接查找.
====

[[server.entity-links.api.typed]]
==== TypedEntityLinks

由于控制器的实现通常围绕实体类型进行分组,因此您经常会在整个控制器类中使用相同的提取器功能(详细信息请参见 <<server.entity-links.api>> ). 通过获取一次提供提取器的 `TypedEntityLinks` 实例,我们可以进一步集中标识符提取逻辑,以便实际查找根本不再需要处理提取.

.Using TypedEntityLinks
====
[source, java]
----
class OrderController {

  private final TypedEntityLinks<Order> links;

  OrderController(EntityLinks entityLinks) { <1>
    this.links = entityLinks.forType(Order::getId); <2>
  }

  @GetMapping
  ResponseEntity<Order> someMethod(…) {

    Order order = … // lookup order

    Link link = links.linkToItemResource(order); <3>
  }
}
----
<1> 注入 `EntityLinks` 实例.
<2> 表示您要使用特定的标识符提取器功能查找 `Order` 实例.
<3> 根据唯一的 `Order` 实例查找商品资源链接.
====

[[server.entity-links.spi]]
=== EntityLinks 作为 SPI

`@EnableHypermediaSupport` 创建的 `EntityLinks` 实例的类型为 `DelegatingEntityLinks`,它将依次拾取 `ApplicationContext` 中可作为 bean 使用的所有其他 `EntityLinks` 实现. 它已注册为 primary bean,
因此通常在您注入 `EntityLink` 时始终是唯一的注入候选对象. `ControllerEntityLinks` 是设置中将包含的默认实现,但是用户可以自由实现和注册自己的实现. 使那些对 `EntityLinks` 实例可用的对象可用于注入是将实现注册为 Spring bean 的问题.

.Declaring a custom EntityLinks implementation
====
[source, java]
----
@Configuration
class CustomEntityLinksConfiguration {

  @Bean
  MyEntityLinks myEntityLinks(…) {
    return new MyEntityLinks(…);
  }
}
----
====

这种数据可扩展性的一个例子是 Spring Data REST 的 https://github.com/spring-projects/spring-data-rest/blob/3a0cba94a2cc8739375ecf24086da2f7c3bbf038/spring-data-rest-webmvc/src/main/java/org/springframework/data/rest/webmvc/support/RepositoryEntityLinks.java[`RepositoryEntityLinks`],它使用存储库映射信息来创建指向由 Spring Data 存储库支持的资源的链接. 同时,它甚至暴露了其他类型资源的其他查找方法. 如果要使用这些,只需显式注入 `RepositoryEntityLinks`.

[[server.representation-model-assembler]]
== [[fundamentals.resource-assembler]] 表示模型汇编器

由于必须在多个地方使用从实体到表示模型的映射,因此创建一个负责这样做的专用类是有意义的. 转换包含非常自定义的步骤,但也包含一些样板步骤:

. 模型类的实例化
. 添加一个具有 `rel` of `self` 关系的链接,指向要渲染的资源

Spring HATEOAS 现在提供了 `RepresentationModelAssemblerSupport` 基类,该基类有助于减少您需要编写的代码量. 以下示例显示了如何使用它:

====
[source, java]
----
class PersonModelAssembler extends RepresentationModelAssemblerSupport<Person, PersonModel> {

  public PersonModelAssembler() {
    super(PersonController.class, PersonModel.class);
  }

  @Override
  public PersonModel toModel(Person person) {

    PersonModel resource = createResource(person);
    // … do further mapping
    return resource;
  }
}
----
NOTE: `createResource(...)` 是您编写的代码,用于在给定 `Person` 对象的情况下实例化 `PersonModel` 对象. 它应该只专注于设置属性,而不是填充链接.
====

像前面的示例中一样设置类,可以为您带来以下好处:

* 有几个 `createModelWithId(…)` 方法可让您创建资源的实例,并为它添加一个带有  `self`  属性的 `Link`, 该链接的href由配置的控制器的请求映射加上实体的ID(for example, `/people/1`).
* 资源类型通过反射实例化,并且需要一个无参数的构造函数. 如果要使用专用的构造函数或避免反射性能开销,则可以重写 `instantiateModel(…)`.

然后,您可以使用汇编器来组装 `RepresentationModel` 或 `CollectionModel`.
以下示例创建 `PersonModel` 实例的 `CollectionModel`

====
[source, java]
----
Person person = new Person(…);
Iterable<Person> people = Collections.singletonList(person);

PersonModelAssembler assembler = new PersonModelAssembler();
PersonModel model = assembler.toModel(person);
CollectionModel<PersonModel> model = assembler.toCollectionModel(people);
----
====

[[server.processors]]
== 表示模型处理器

有时,您需要在 <<server.representation-model-assembler,assembled>> 超媒体表示后对其进行调整和调整.

一个完美的例子是,当您有一个负责处理订单履行的控制器,但您需要添加与付款相关的链接.

想象一下,让您的 Order 系统生产这种类型的超媒体:

====
[source, json, tabsize=2]
----
include::{resource-dir}/docs/order-plain.json[]
----
====

您希望添加一个链接,以便客户可以付款,但不想将有关 `PaymentController` 的详细信息混入 `OrderController` 中.

您可以像下面这样编写 `RepresentationModelProcessor`,而不用污染 Order 系统的详细信息:

====
[source, java, tabsize=2]
----
include::{code-dir}/PaymentProcessor.java[tag=code]
----
<1> 该处理器将仅应用于 `EntityModel<Order>` 对象.
<2> 通过添加无条件链接来处理现有的 `EntityModel` 对象.
<3> 返回 `EntityModel` 以便可以将其序列化为请求的媒体类型.
====

在您的应用程序中注册处理器:

====
[source, java, tabsize=2]
----
include::{code-dir}/PaymentProcessingApp.java[tag=code]
----
====

现在,当您发布 `Order` 的超媒体表示时,客户端会收到以下信息:

====
[source, java, tabsize=2]
----
include::{resource-dir}/docs/order-with-payment-link.json[]
----
<1> 您会看到此链接的关系已插入 `LinkRelation.of("payments")`
<2> URI由处理器提供.
====

这个例子很简单,但是您可以轻松地:

* 使用 `WebMvcLinkBuilder` 或 `WebFluxLinkBuilder` 构造到您的 `PaymentController` 的动态链接.
* 注入必要的服务,以有条件地添加由状态驱动的其他链接 (e.g. `cancel`, `amend`) .
* 利用诸如 Spring Security 之类的跨领域服务根据当前用户的上下文添加,删除或修改链接.

同样,在此示例中,`PaymentProcessor` 更改提供的  `EntityModel<Order>`. 您也可以将其替换为另一个对象. 请注意,API 要求返回类型等于输入类型.

[[server.rel-provider]]
== [[spis.rel-provider]] 使用 `LinkRelationProvider` API

构建链接时,通常需要确定要用于链接的关系类型. 在大多数情况下,关系类型与(域)类型直接关联. 我们封装了详细的算法,以在LinkRelationProvider API之后查找关系类型,该API使您可以确定单个资源和集合资源的关系类型. 查找关系类型的算法如下:

. 如果使用 `@Relation`, 则使用注解中配置的值.
. 如果不是,我们默认为不使用大写字母的简单类名,再加上集合 `rel` 的附加列表. `List` for the collection `rel`.
. 如果 https://github.com/atteo/evo-inflector[EVO inflector] 位于类路径中,则使用复数算法提供的多个单资源 `rel`.
. 用 `@ExposesResourceFor` 注解的 `@Controller` (有关详细信息,请参见 <<server.entity-links>> ) 透明地查找注解中配置的类型的关系类型,以便您可以使用 `LinkRelationProvider.getItemResourceRelFor(MyController.class)` 并获取 域类型暴露.

使用 `@EnableHypermediaSupport` 时,`LinkRelationProvider` 自动显示为 Spring Bean. 您可以通过实现接口并依次将其暴露为 Spring bean 来插入自定义提供程序.