[[preface]]
= 前言

Spring Data Redis 项目通过使用 key-value 风格的数据存储将 Spring 的核心概念应用于开发解决方案. 我们提供了一个 发送和接收消息的 "模板” 作为高级抽象. 您可能会注意到与 Spring Framework 中的 JDBC 支持相似.

本文档是 Spring Data Redis(SDR) 模块支持的参考指南.

[[get-started:first-steps:spring]]
== 学习 Spring

Spring Data 使用 Spring 框架的 https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html[核心] 功能, 包括:

* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#beans[IoC] 容器
* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#validation[类型转换系统]
* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/core.html#expressions[语言表达式]
* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/integration.html#jmx[JMX 集成]
* https://docs.spring.io/spring/docs/{springVersion}/spring-framework-reference/data-access.html#dao-exceptions[DAO 异常层次].

虽然了解 Spring API 并不重要,但了解它们背后的概念很重要. 至少,应该了解 IoC 背后的想法.并且您应该熟悉选择使用的任何IoC容器.

Redis 支持的核心功能可以直接使用, 而无需调用 Spring 容器的 IoC 服务.  这非常类似于 `JdbcTemplate`, 它可以在没有 Spring 容器的任何其他服务的情况下 "独立" 使用.  为了利用 Spring Data Redis 的所有功能, 例如存储库支持, 您需要配置库的某些部分以使用 Spring.

话虽如此,您对 Spring 的了解越多,您就能更快地获取 Spring Data Redis. 可以参考 Spring 框架的参考文档,关于该主题有很多文章, 博客和书籍.
有关更多信息, 请参见 Spring 框架 https://spring.io/docs[home page].

通常,这应该是想要尝试使用 Spring Data Redis 的开发人员的起点.

[[get-started:first-steps:nosql]]
== 学习 NoSQL 和 Key Value 存储

NoSQL 存储席卷了存储世界. 它是一个广阔的领域,具有许多解决方案,术语和模式(更糟糕的是,甚至术语本身也具有 https://www.google.com/search?q=nosoql+acronym[多种含义]).
尽管某些原则很普遍,但一定程度上要熟悉 SDR 支持的 处处,这一点至关重要. 熟悉这些解决方案的最佳方法是阅读其文档并遵循其示例. 通常需要花费五到十分钟的时间来完成这些步骤,而且,如果您具有 RDMBS 的背景,那么这些练习通常会使人大开眼界.

[[get-started:first-steps:samples]]
=== 尝试示例

您可以在 Spring Data 示例存储库中找到各种用于键值存储的示例,网址为 https://github.com/spring-projects/spring-data-keyvalue-examples[https://github.com/spring-projects/spring-data-keyvalue-examples].
对于 Spring Data Redis,您应该特别注意 `retwisj` 示例,该示例是在 Redis 之上构建的 Twitter-clone,可以在本地运行或部署到云中. 有关更多信息,请参阅其 https://docs.spring.io/spring-data/data-keyvalue/examples/retwisj/current/[文档],以下 https://spring.io/blog/2011/04/27/getting-started-redis-spring-cloud-foundry/[博客].

[[requirements]]
== 要求

Spring Data Redis 2.x 需要 JDK 8.0 或更高版本以及 https://projects.spring.io/spring-framework/[Spring Framework] {springVersion} 或更高版本.

就 key-value 存储而言, 需要 https://redis.io[Redis] 2.6.x 或更高版本.  Spring Data Redis 当前已针对最新的 4.0 版本进行了测试.

[[get-started:help]]
== 其他帮助资源
学习新框架并不总是那么简单.  在本节中, 我们提供开始学习 Spring Data Redis 的简要指南.  但是, 如果遇到问题或需要建议, 请随时使用以下链接之一:

[get-started:help:community]]
社区论坛 :: https://stackoverflow.com/questions/tagged/spring-data[Stack Overflow] 上的 Spring Data 标签是一个留言板,供所有 Spring Data(不仅仅是文档)用户共享信息并互相帮助. 请注意,只有注册了才能发布.

[[get-started:help:professional]]
Professional Support :: 可从 Spring Data 和 Spring 背后的公司  https://www.pivotal.io/[Pivotal Software, Inc.] 获得专业的支持.

[[get-started:up-to-date]]
== 后续发展

有关 Spring Data 源代码存储库,每夜构建和 snapshot artifacts 的信息,请参见 Spring Data https://spring.io/spring-data[主页].

通过在 https://stackoverflow.com/questions/tagged/spring-data[spring-data] 或 https://stackoverflow.com/questions/tagged/spring-data-redis[spring-data-redis] 上的 Stack Overflow 上与开发人员进行交互,可以帮助使 Spring Data 最好地满足 Spring 社区的需求.

如果您遇到错误或要提出改进建议(包括本文档中的内容),请在 Spring Data 问题跟踪器上创建 https://github.com/spring-projects/spring-data-redis/issues/new[Github].

要了解 Spring 生态系统中的最新新闻和公告,请订阅 Spring Community https://spring.io/[Portal].

最后,您可以在 Twitter 上关注 Spring  https://spring.io/blog/[blog] 或项目团队(https://twitter.com/SpringData[@SpringData]).