[[reactor-extra]]
= Reactor-Extra

`reactor-extra` 为满足 `reactor-core` 用户的更高级需求，提供了一些额外的操作符和工具。

由于这是一个单独的包，使用时需要明确它的依赖:

====
[source,groovy]
----
dependencies {
     compile 'io.projectreactor:reactor-core'
     compile 'io.projectreactor.addons:reactor-extra' <1>
}
----
<1> 添加 reactor-extra 的依赖。参考 <<getting>>  Reactor 了解为什么使用BOM的情况下不需要指定 version。
====

[[extra-tuples]]
== `TupleUtils` 以及函数式接口

在 Java 8 提供的函数式接口基础上，`reactor.function` 包又提供了一些支持 3 到 8 个值的 `Function`、`Predicate` 和 `Consumer`。

`TupleUtils` 提供的静态方法可以方便地用于将相应的 `Tuple` 函数式接口的 lambda 转换为更简单的接口。

这使得我们在使用 `Tuple` 中各成员的时候更加容易，比如:

====
[source,java]
----
.map(tuple -> {
  String firstName = tuple.getT1();
  String lastName = tuple.getT2();
  String address = tuple.getT3();

  return new Customer(firstName, lastName, address);
});
----
====

可以用下面的方式代替:

====
[source,java]
----
.map(TupleUtils.function(Customer::new)); // <1>
----
<1> (因为 `Customer` 的构造方法符合 `Consumer3` 的函数式接口标签)
====

[[extra-math]]
== `MathFlux` 的数学操作符

`reactor.math`  包的 `MathFlux` 提供了一些用于数学计算的操作符，如 `max`、`min`、`sumInt`、`averageDouble`...

[[extra-repeat-retry]]
== 重复与重试工具

`reactor.retry` 包中有一些能够帮助实现 `Flux#repeatWhen` 和 `Flux#retryWhen` 的工具。入口点(entry points)就是 `Repeat` 和 `Retry` 接口的工厂方法。

两个接口都可用作可变的构建器(mutative builder)，并且相应的实现(implementing) 都可作为 `Function` 用于对应的操作符。

从 `3.2.0` 版本开始，这些工具类的最先进的重试策略之一也直接成为 `reactor-core` 主要 artifact 的一部分。 Exponential backoff 可用作 `Flux#retryBackoff` 操作符。

从 `3.3.4` 开始，`Retry` 构建器直接在 core 中提供，并且基于 `RetrySignal` 封装了更多的状态而不是错误，它具有更多可能的自定义项。

[[extra-schedulers]]
== 调度器

Reactor-extra 提供了若干专用的调度器:

* `ForkJoinPoolScheduler` (位于 `reactor.scheduler.forkjoin` 包): 使用 Java `ForkJoinPool` 执行任务.
* `SwingScheduler` (位于 `reactor.swing` 包): 在Swing UI事件循环线程 "EDT" 中运行任务。
* `SwtScheduler` (位于 `reactor.swing` 包): 在SWT UI事件循环线程中运行任务。
