=== `subscribe` 方法示例

这一小节包含了对 `subscribe` 的 5 个不同签名的方法的示例，如下是一个无参的基本方法的使用:

====
[source,java]
----
Flux<Integer> ints = Flux.range(1, 3); <1>
ints.subscribe(); <2>
----
<1> 配置一个在订阅时会产生3个值的 `Flux`。
<2> 最简单的订阅方式
====

第二行代码没有任何输出，但是它确实执行了。`Flux` 产生了 3 个值。如果我们传入一个 lambda， 我们就可以看到这几个值，如下一个列子:

====
[source,java]
----
Flux<Integer> ints = Flux.range(1, 3); <1>
ints.subscribe(i -> System.out.println(i)); <2>
----
<1> 配置一个在订阅时会产生3个值的 `Flux`。
<2> 订阅它并输出值
====

第二行代码会输入如下内容:

====
[source]
----
1
2
3
----
====

为了演示下一个方法签名，我们故意引入一个错误，如下所示:

====
[source, java]
----
Flux<Integer> ints = Flux.range(1, 4) <1>
      .map(i -> { <2>
        if (i <= 3) return i; <3>
        throw new RuntimeException("Got to 4"); <4>
      });
ints.subscribe(i -> System.out.println(i), <5>
      error -> System.err.println("Error: " + error));
----
<1> 配置一个在订阅时会产生4个值的 Flux。
<2> 为了对元素进行处理，我们需要一个 map 操作
<3> 对于多数元素，返回值本身。
<4> 对其中一个元素抛出错误。
<5> 订阅的时候定义如何进行错误处理
====

现在我们有两个 lambda 表达式: 一个是用来处理正常数据，一个用来处理错误。 刚才的代码输出如下:

====
[source]
----
1
2
3
Error: java.lang.RuntimeException: Got to 4
----
====

下一个 `subscribe` 方法的签名既有错误处理，还有一个完成后的处理，如下:

====
[source,java]
----
Flux<Integer> ints = Flux.range(1, 4); <1>
ints.subscribe(i -> System.out.println(i),
    error -> System.err.println("Error " + error),
    () -> System.out.println("Done")); <2>
----
<1> 配置一个在订阅时会产生 4 个值的 Flux
<2> 订阅时定义错误和完成信号的处理。
====

错误和完成信号都是终止信号，并且二者只会出现其中之一。为了能够最终全部正常完成，你必须处理错误信号。

用于处理完成信号的 lambda 是一对空的括号，因为它实际上匹配的是 `Runnalbe` 接口中的 `run` 方法， 不接受参数。刚才的代码输出如下:

====
[source]
----
1
2
3
4
Done
----
====

`subscribe` 方法的最后一个签名包括 `Consumer<Subscription>`。

NOTE: 该变体需要您对 `Subscription` 进行操作(对它执行一个 `request(long)`  或 `cancel()` )。否则，`Flux` 会挂起。

以下示例显示了 `subscription` 方法的最后一个签名:

====
[source,java]
----
Flux<Integer> ints = Flux.range(1, 4);
ints.subscribe(i -> System.out.println(i),
    error -> System.err.println("Error " + error),
    () -> System.out.println("Done"),
    sub -> sub.request(10)); <1>
----
<1> 当我们订阅时，我们会收到一个  `Subscription`。表示我们要从源中获取最多 `10` 个元素(实际上将发出 `4` 个元素并完成)。
====

=== Cancelling a `subscribe()` with Its `Disposable`

All these lambda-based variants of `subscribe()` have a `Disposable` return type.
In this case, the `Disposable` interface represents the fact that the subscription
can be _cancelled_, by calling its `dispose()` method.

For a `Flux` or `Mono`, cancellation is a signal that the source should stop
producing elements. However, it is NOT guaranteed to be immediate: Some sources
might produce elements so fast that they could complete even before receiving the
cancel instruction.

Some utilities around `Disposable` are available in the `Disposables` class.
Among these, `Disposables.swap()` creates a `Disposable` wrapper that lets
you atomically cancel and replace a concrete `Disposable`. This can be useful,
for instance, in a UI scenario where you want to cancel a request and replace it
with a new one whenever the user clicks on a button. Disposing the wrapper itself
closes it. Doing so disposes the current concrete value and all future attempted replacements.

Another interesting utility is `Disposables.composite(...)`. This composite
lets you collect several `Disposable` -- for instance, multiple in-flight requests
associated with a service call -- and dispose all of them at once later on.
Once the composite's `dispose()` method has been called, any attempt to add
another `Disposable` immediately disposes it.

=== Lambda 的替代方案: `BaseSubscriber`

还有另一种更通用的  `subscribe` 方法，它采用了成熟的 `Subscriber` ，而不是由一个 lambda 组成一个。为了帮助编写这样的  `Subscriber`，我们提供了一个称为 `BaseSubscriber` 的可扩展类。

WARNING: BaseSubscriber(或其子类)的实例都只能使用一次，这意味着如果 `BaseSubscriber` 订阅了第二个 `Publisher`，则取消其对第一个 `Publisher` 的订阅。
那是因为两次使用一个实例将违反响应式流规则，即不能并行调用 `Subscriber` 的 `onNext` 方法。 因此，只有在对 `Publisher#subscribe(Subscriber)` 的调用中直接声明匿名实现时，匿名实现才可以。

现在我们可以实现其中之一。我们称它为 `SampleSubscriber`。以下示例显示了如何将其连接到 `Flux`:

====
[source,java]
----
SampleSubscriber<Integer> ss = new SampleSubscriber<Integer>();
Flux<Integer> ints = Flux.range(1, 4);
ints.subscribe(i -> System.out.println(i),
    error -> System.err.println("Error " + error),
    () -> {System.out.println("Done");},
    s -> s.request(10));
ints.subscribe(ss);
----
====

下面的示例显示了 `SampleSubscriber` ，它是 `BaseSubscriber` 的简约实现:

====
[source,java]
----
package io.projectreactor.samples;

import org.reactivestreams.Subscription;

import reactor.core.publisher.BaseSubscriber;

public class SampleSubscriber<T> extends BaseSubscriber<T> {

	public void hookOnSubscribe(Subscription subscription) {
		System.out.println("Subscribed");
		request(1);
	}

	public void hookOnNext(T value) {
		System.out.println(value);
		request(1);
	}
}
----
====

`SampleSubscriber` 类继承自 `BaseSubscriber`，在 Reactor 中, 推荐用户扩展它来实现自定义的 `Subscriber`。这个类提供了一些 hook 方法，我们可以通过重写它们来调整 subscriber 的行为。
默认情况下，它会触发一个无限个数的请求，但是当你想自定义请求元素的个数的时候，扩展 `BaseSubscriber` 就很方便了。

扩展的时候通常至少要覆盖 `hookOnSubscribe(Subscription subscription)` 和 `hookOnNext(T value)` 这两个方法。这个例子中， `hookOnSubscribe` 方法打印一段话到标准输出，然后进行第一次请求。
然后 `hookOnNext` 同样进行了打印，同时逐个处理剩余请求。

`SampleSubscriber` 输出如下:

====
[source]
----
Subscribed
1
2
3
4
----
====

`BaseSubscriber` 还提供了 `requestUnbounded()` 方法以切换到“无限”模式(等效于 `request(Long.MAX_VALUE)`)，还提供了  `cancel()`  方法。

它还具有其他钩子: `hookOnComplete`, `hookOnError`, `hookOnCancel`, 和 `hookFinally`(在序列终止时始终调用，并将终止类型作为 `SignalType` 参数传入)

NOTE: 建议你同时重写 `hookOnError`、`hookOnCancel`，以及 `hookOnComplete` 方法。 你最好也重写 `hookFinally` 方法。`SampleSubscribe` 确实是一个最简单的实现了 请求有限个数元素的 Subscriber。